### ISSUE TITLE
Code refactor: reorganize frontend file structure

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1017]
Our frontend directory and file structure starts to be a little cumbersome to maintain. How about we:
- merge `resourcelist` and `resourcedetail` folders into `resource/list` and `resource/detail` + maybe `resource/common`. 
- in folders `resource/list` strip all `resourcelist_` prefixes from files. E.g., rename `configmapcardlist_component` to `cardlist_component`. 

@floreks @digitalfishpond @maciaszczykm @olekzabl What do you think?

**Comment by digitalfishpond** [comment]
I'm a fan of precise categorizing in directories. Adding new layers of folders will keep things neater and therefore easier to navigate, for sure, particularly with unknown future scaling.

**Comment by maciaszczykm** [comment]
I agree. Out structure is getting out of control at the moment. It would be nice to merge bigger pull requests before this kind of refactoring.
