### ISSUE TITLE
Node status in Node List

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#1026]
One of my node was down, and from the UI, I could not figure it out which one (unless I go the detail page of each node). But if we use:

`kubect get nodes`

There is a "Status" column which instantly tells you which one is not ready. I think we could add the same column in the node list:

![image](https://cloud.githubusercontent.com/assets/7731641/16832739/06e53c02-49ef-11e6-9a39-71edfa788411.png)

If you guys are OK to add a new column with the value of the "Ready" Status, I'm more than happy to work on this and send a PR.

**Comment by bryk** [comment]
> If you guys are OK to add a new column with the value of the "Ready" Status, I'm more than happy to work on this and send a PR.

Yes, definitely, that would be great :) The Nodes view is beta-ish now, so that's why it is not widely announced yet.

**Comment by floreks** [comment]
cc @maciaszczykm :)

**Comment by maciaszczykm** [comment]
@edouardKaiser Yes, I forgot to add it here. However, it should be easy to add. 

You're welcome to work on this. If you need any help just let us know.

**Comment by edouardKaiser** [comment]
No worries, I'll do it, good way to get comfortable with Golang and the project.

**Comment by edouardKaiser** [comment]
I pushed a PR (https://github.com/kubernetes/dashboard/pull/1042)

**Comment by bryk** [comment]
@edouardKaiser How was your developer experience with this PR? How is it to work on Dashboard UI for the first time? Anything we can improve?

**Comment by edouardKaiser** [comment]
Once the tools were installed (npm, go, gulp...), it was very easy to get something running. For me, the main issue was setting up the IDE (IntelliJ in my case). There is no documentation to help you do that, and if that's the first Golang project in your life, it's even more tricky.

I still have to figure it out how to debug (through breakpoints) from the IDE directly, but at least I can now code from it and benefit from auto-completion.  So I would say, the main point to improve is helping people setting up there environment.
