### ISSUE TITLE
CRUD Nodes in the UI

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1027]
Should we allow for editing/deleting nodes through the UI? I think yes.

@edouardKaiser @maciaszczykm What is your opinion?

**Comment by maciaszczykm** [comment]
I think it can be very valuable feature. Actually, @cheld had an idea of similar feature, so maybe he can provide more details what could be most useful functionalities, that we are missing right now.

**Comment by bryk** [comment]
Perfect. Note that I'm talking now about YAML editor + delete button. Which is very easy to implement.

**Comment by maciaszczykm** [comment]
@bryk I know. Added @cheld to the loop,  because he had an idea of features similar to ones mentioned by you (but maybe not so easy to implement at the moment).

**Comment by edouardKaiser** [comment]
Sounds like a good idea, especially the edition (labels, etc.)

**Comment by cheld** [comment]
Yes like it. I will comment more at enf of week

**Comment by cheld** [comment]
I assume that deleting nodes would just remove them from the cluster, but the VM still exist, right? This might not be expected by the user. Maybe we drain/cordon the node instead of delete?

So, my proposal would be edit & cordon (e.g use pause icon)

**Comment by bryk** [comment]
I think we can start with edition. Deletion is tricky, as you've noticed.

**Comment by cheld** [comment]
Cordon is a kubectl command. Should be easy, too.

**Comment by bryk** [comment]
Oh, I see. Yes, should be easy.
