### ISSUE TITLE
Add resource quotas and limits to namespace details

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1028]
Add missing details to match `kubectl describe ns <namespace>` behavior.

**Comment by batikanu** [comment]
The pull request #1258 is for resource quotas. I am implementing also for limit ranges.

**Comment by maciaszczykm** [comment]
@batikanu Let me know, when we'll be able to close it.

**Comment by batikanu** [comment]
The pull requests #1292 and #1290 are for limit ranges. Waiting for review.

**Comment by bryk** [comment]
Can we do a short design of this features? I'm mostly concerned about the part of whether this should be a new menu item in the nav or a child property of a namespace. @batikanu @maciaszczykm Can you provide rationales for both approaches and state which one do you think is correct? 

CC @romlein

**Comment by maciaszczykm** [comment]
At the moment I can see following rationales:

Menu item:

- quick and easy to find
- list of resource quotas in all namespaces, not only in specific ones (when `All namespaces` is selected)
- similar to what we have right now (list and detail page for every resource)

Property of a namespace:

- menu contains only most important resources
- logic connection (all resource quotas are connected to the namespaces)

I'll update it later.

**Comment by floreks** [comment]
Resource quota is tied to a single namespace, however we have wanted to show only non-namespaced objects in Admin category AFAIK. Still it's possible to list all resource quotas using `kubectl get`, so I think that we should have a list of objects here together with details page. We could introduce some category and add it somewhere below namespace selector. I think we've established that all namespaced resources will be located under this selector.

**Comment by bryk** [comment]
Read resource quotas docs: http://kubernetes.io/docs/admin/resourcequota/

`Resource Quota is enforced in a particular namespace when there is a ResourceQuota object in that namespace. There should be at most one ResourceQuota object in a namespace.`

This means that essentially, resource quotas is just a property of a namespace. I think it is a separate object to make it pluggable so that some clusters use it and some not.

**Comment by maciaszczykm** [comment]
@bryk That makes sense and presents resource quotas in similar role as endpoints of service. Endpoints and other minor resources don't have their list pages at the moment, so I'd say we should make resource quota property of a namespace. No need to have list page or menu entry in that case.

**Comment by bryk** [comment]
@batikanu @floreks What is your opinion on this?

**Comment by maciaszczykm** [comment]
However it would be nice to have a page where developer or operator can take a look on resource quotas of all namespaces he can access. It could be valuable during debugging/monitoring. Nice to have in the future. Maybe in form of some short info in namespace list page?

**Comment by bryk** [comment]
> Maybe in form of some short info in namespace list page?

Yes. I hope that we'll be able to add columns to the view soon. Or have different namespace-oriented tables.

**Comment by floreks** [comment]
For sure we need some way to list all resource quotas in single namespace, but I can understand how displaying new nav item for this resource would be unnecessary. For now I vote to remove that and we'll think about how to display it properly in the future.

**Comment by bryk** [comment]
> For sure we need some way to list all resource quotas in single namespace

A namespace can have at most one resource quota. So it is either "I have a resource quota or dont have it". So I think that the proper way of displaying it is like "details" section in a pod. 

Then we can pull resource quota info to namespace tables. We have plenty of space there.

**Comment by batikanu** [comment]
It sounds good for me. I will update the implementation accordingly.

**Comment by floreks** [comment]
> For sure we need some way to list all resource quotas in single namespace

> A namespace can have at most one resource quota. So it is either "I have a resource quota or dont have it". So I think that the proper way of displaying it is like "details" section in a pod.

I've meant list resource qutoas in all namespaces of course :)

**Comment by maciaszczykm** [comment]
Closing as done:

![zrzut ekranu 2017-10-17 o 13 33 45](https://user-images.githubusercontent.com/2823399/31662727-e3d1b400-b33f-11e7-9605-33e418e8785c.png)
