### ISSUE TITLE
Viewing all namespaces - should prefix the workloads with the namespace.

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/dashboard#1030]
#### Issue details
When viewing all namespaces, it should prefix the workloads with the namespace.

I.e. <namespace>/<pod>

##### Environment
gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0

**Comment by bryk** [comment]
Do you mean we should add a column named "namespace" to resource lists?

**Comment by ajohnstone** [comment]
Yes a column would be good

**Comment by digitalfishpond** [comment]
Starting work on this now

**Comment by ajohnstone** [comment]
Awesome @digitalfishpond

**Comment by digitalfishpond** [comment]
I assume we'd _only_ want this when more than one namespace was displayed?

**Comment by bryk** [comment]
Yes

**Comment by ibrasho** [comment]
I would prefer to have it shown whenever "All user namespaces" is selected even if only one namespace exists. Consistency is worth it sometimes.

**Comment by digitalfishpond** [comment]
Yes, of course. I was thinking more along the lines of a future hypothetical possibility of showing more than one but not all namespaces, but I agree that whenever "All namespaces" is selected should be the current effect.

**Comment by digitalfishpond** [comment]
Done. This can probably be closed now.
