### ISSUE TITLE
Add pod spec to Pod and Controller objects

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1033]
Currently we display only very limited info about pod specification. We should display all info about pod spec in Pod and Controller detail pages.

**Comment by floreks** [comment]
I agree that we should show more information based on pod spec, however it is quite large. We have to think what is important for the user and show that.

[PodSpec struct](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1430)

- [ ] Volumes
- [ ] InitContainers
- [ ] Containers
- [ ] RestartPolicy
- [ ] TerminationGracePeriodSeconds
- [ ] ActiveDeadlineSeconds
- [ ] DNSPolicy
- [ ] NodeSelector
- [ ] ServiceAccountName
- [ ] NodeName
- [ ] SecurityContext
- [ ] ImagePullSecrets
- [ ] Hostname
- [ ] Subdomain

**Comment by bryk** [comment]
Yes, good point. I think Containers part is most important and this is what I'm doing now. As for the rest, we should mimic kubectl. What is your opinion?

**Comment by floreks** [comment]
Yes, so containers could be actually shown as related list and we could prepare similar container detail page for that. Some of information could be shown directly on pod details page under `Spec` section and some resources like `Volumes` will have its own list+details page soon.

What do you think?

**Comment by bryk** [comment]
We can show containers in-line or in a separate details page. That's an interesting problem. I currently think that it is best to show containers inline. This is because vast majority pods/controllers have only one container and the information there is relevant to what you're looking at. Next, containers aren't _kubernetes resources_, so you cannot get them from API, thus this makes stuff harder to implement.

So I propose we go inline. What's your opinion?

**Comment by floreks** [comment]
If we manage to squeeze them nicely on pods page then I'm up for that, however I see that they have quite many details.

![zrzut ekranu z 2016-07-18 08-24-46](https://cloud.githubusercontent.com/assets/2285385/16907162/572c5298-4cc1-11e6-8739-81519fdf3d85.png)

**Comment by bryk** [comment]
I guess that we can do some nice densification of information in the UI. And btw, bonus of having this inline is that we'll be consistent with the UX of command line.

**Comment by maciaszczykm** [comment]
Most of the info is already there.
