### ISSUE TITLE
Support ANSI color codes in dashboard log output

### ISSUE THREAD

**Issue by ekuefler** [kubernetes/dashboard#1035]
The dashboard log viewer is great, but it doesn't handle my beautiful colored log output very nicely (it looks ok on the console with `kubectl logs`). Currently it looks like this:

```
2016-07-14T19:55:01.042410815Z [34mI 2016-07-14 19:55:01,024:[0;39m Logging initialized @526ms
2016-07-14T19:55:01.117667521Z [34mI 2016-07-14 19:55:01,114:[0;39m jetty-9.3.z-SNAPSHOT
2016-07-14T19:55:01.144351171Z [34mI 2016-07-14 19:55:01,143:[0;39m Started o.e.j.s.ServletContextHandler@5e4c8041{/,null,AVAILABLE}
2016-07-14T19:55:01.358607587Z [34mI 2016-07-14 19:55:01,358:[0;39m Started ServerConnector@40005471{SSL,[ssl, http/1.1]}{0.0.0.0:443}
2016-07-14T19:55:01.358967764Z [34mI 2016-07-14 19:55:01,358:[0;39m Started @865ms
2016-07-14T19:55:01.360299460Z [34mI 2016-07-14 19:55:01,359:[0;39m jetty-9.3.z-SNAPSHOT
2016-07-14T19:55:01.362919564Z [34mI 2016-07-14 19:55:01,362:[0;39m Started o.e.j.s.ServletContextHandler@2aceadd4{/,null,AVAILABLE}
2016-07-14T19:55:01.364062603Z [34mI 2016-07-14 19:55:01,363:[0;39m Started ServerConnector@24aed80c{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2016-07-14T19:55:01.364378549Z [34mI 2016-07-14 19:55:01,364:[0;39m Started @870ms
2016-07-14T19:55:29.902895969Z [31mW 2016-07-14 19:55:29,902:[0;39m Requested image via deprecated API
2016-07-14T19:55:29.915895809Z [34mI 2016-07-14 19:55:29,914:[0;39m Requested ImageBlobMetadataId[C5LKlz8-QpshXr6z-OKJ2k] in formats []
2016-07-14T19:55:29.921048965Z [34mI 2016-07-14 19:55:29,920:[0;39m Loading ImageBlobMetadataId[C5LKlz8-QpshXr6z-OKJ2k] from datastore
2016-07-14T19:55:30.391477288Z [34mI 2016-07-14 19:55:30,390:[0;39m Streaming C5LKlz8-QpshXr6z-OKJ2k for ImageBlobMetadataId[C5LKlz8-QpshXr6z-OKJ2k] as default
2016-07-14T19:55:30.920560314Z [34mI 2016-07-14 19:55:30,919:[0;39m Total response time: 1019ms
```

**Comment by bryk** [comment]
This is a nice feature. Can you contribute to have this fixed? Or specify what is needed?

**Comment by ekuefler** [comment]
ANSI escape sequences are described in brief [here](http://ascii-table.com/ansi-escape-sequences.php) ("Set Graphics Mode" is the one that's relevant here) or in detail on [Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code). We would need to parse each log line looking for escape sequences and convert them to HTML spans.

Do you think that should happen on the client or the server? Looking at the code it doesn't look like Dashboard does any formatting of log lines right now after they come back form the API server, so it would be a new chunk of code on either side. It looks like there are some [javascript libraries](https://github.com/drudru/ansi_up) that do it; I didn't find any Go libraries. Doing it manually probably wouldn't be that hard.

I'd be willing to give this a shot, but don't have a ton of time to devote to it, so it might take a while.

**Comment by bryk** [comment]
I think we should do this in the frontend JavaScript. Either manually or using some library for this. 

> I'd be willing to give this a shot, but don't have a ton of time to devote to it, so it might take a while.

Thanks! Let us know whether you need any help :)

**Comment by greggbjensen** [comment]
.NET Core outputs ANSI color codes for it's standard logging, and these are not currently translated.  This leads to output that contains unprintable characters.

![image](https://user-images.githubusercontent.com/1800213/75565125-a903e900-5a0a-11ea-9f96-a35706962c89.png)


Adding support for ANSI color codes will allow for more readable logs, and consistent support for .NET Core as well as other applications.

![image](https://user-images.githubusercontent.com/1800213/75565290-ee281b00-5a0a-11ea-8fe7-beab4c4f57b1.png)

**Comment by TobiasWenzel** [comment]
I experience the same issues as @greggbjensen. We have tons of ASP.NET Core services running in our Kubernetes cluster and it's really a pain to read the logs which would otherwise (when shown with proper colors instead of ANSI character garbage) look beautiful.

So @bryk or @ekuefler is there any chance to reopen this issue and have another look what's wrong here?

**Comment by TobiasWenzel** [comment]
I just saw that this seems to have been fixed already in #4632, so probably my last comment can be ignored.

**Comment by zzvara** [comment]
Somewhere along the way, during automatic updates, this became an issue on our deployment as well.

![image](https://user-images.githubusercontent.com/8371789/134813336-65800e35-3bf9-4af9-b373-18d9f2af95bc.png)

The dashboard is deployed with:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  chart:
    repository: https://kubernetes.github.io/dashboard/
    name: kubernetes-dashboard
    version: 5.0.1
  releaseName: kubernetes-dashboard
  values:
    settings:
      clusterName: "Sigma"
      itemsPerPage: 50
    protocolHttp: true
    metricsScraper:
      enabled: true
    metrics-server:
      enabled: true
      hostNetwork:
        enabled: true
      rbac:
        pspEnabled: true
      args:
        - '--kubelet-insecure-tls=true'
        - '--kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP'
    service:
      externalPort: 9090
    resources:
      requests:
        cpu: 50m
        memory: 300Mi
      limits:
        cpu: 1000m
        memory: 400Mi
    extraArgs:
      - '--enable-insecure-login'
      - '--namespace=kube-system'
      - '--token-ttl=0'
      - '--insecure-bind-address=0.0.0.0'
      - '--insecure-port=9090'
      - '--system-banner="Welcome to Sigma Kubernetes"'
```

Kubernetes is deployed using Kubespray on Flatcar.

```
sigma01   Ready    control-plane,master   587d   v1.20.7
sigma02   Ready    control-plane,master   587d   v1.20.7
sigma03   Ready    <none>                 587d   v1.20.7
sigma04   Ready    <none>                 587d   v1.20.7
```

Using `kubectl log ...` displays ANSI color codes properly.

**Comment by goncafab** [comment]
> It seems this functionality has regressed at some point.
> 
> Any chance of having ansi colors back ?

Echoing this, any news regarding a fix?

**Comment by floreks** [comment]
The ANSI codes are now properly removed from the logs. Unfortunately, we do not plan to add support for colored output as it introduced some security issues. We'd rather keep it simple instead.
