### ISSUE TITLE
Implement events view

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#104]
This issue was created to implement events view:

![Design](https://github.com/kubernetes/dashboard/blob/master/docs/design/mockups/11-11-2015/19_events.png?raw=true)

First step is to implement backend, then frontend. I'm working on backend right now.

**Comment by maciaszczykm** [comment]
@bryk To use `md-tab` in this view I think we need to switch from Material Design version `0.11.4` to at least `0.12.0-rc1` due to issue described at https://github.com/angular/material/issues/5240, it's the next version so impact shouldn't be too big. Otherwise, workaround will be required. Do you agree on upgrade to `0.12.0-rc1`?

**Comment by bryk** [comment]
Yes, feel free to update ngMaterial. I hope that version 1.0 will be available before EOQ1 2016.

**Comment by floreks** [comment]
I'm supporting marcin on this. I'll take left side of the view.

**Comment by maciaszczykm** [comment]
@bryk Events view appear on replica set details page along with pods view. This page has two parameters at the moment - `namespace` and `replicaSet`. I wonder how we should filter events using `replicaSet` parameter, because `namespace` parameter is already considered when loading list of events from backend. 

I have just checked and Kubernetes API, available at http://127.0.0.1:8080/api/v1/events, returns JSON with structure like below:
```
{
  "kind": "EventList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/events",
    "resourceVersion": "124873"
  },
  "items": [
    {
      "metadata": {
        "name": "asd-2skdj.141bbf69fadf45fd",
        "namespace": "asdasdsad",
        "selfLink": "/api/v1/namespaces/asdasdsad/events/asd-2skdj.141bbf69fadf45fd",
        "uid": "041815b5-980e-11e5-8194-901b0e5324e4",
        "resourceVersion": "124599",
        "creationTimestamp": "2015-12-01T09:29:27Z",
        "deletionTimestamp": "2015-12-01T14:25:49Z"
      },
      "involvedObject": {
        "kind": "Pod",
        "namespace": "asdasdsad",
        "name": "asd-2skdj",
        "uid": "f6586a19-980d-11e5-8194-901b0e5324e4",
        "apiVersion": "v1",
        "resourceVersion": "92530",
        "fieldPath": "spec.containers{asd}"
      },
      "reason": "Pulling",
      "message": "pulling image \"123\"",
      "source": {
        "component": "kubelet",
        "host": "127.0.0.1"
      },
      "firstTimestamp": "2015-12-01T09:29:27Z",
      "lastTimestamp": "2015-12-01T13:25:49Z",
      "count": 50
    },
    ...
  ]
}
```

Should we just filter it based on `involvedObject`? I'm not sure if it a pod will always be `involvedObject`, what if not? Any suggestions would be helpful.

**Comment by bryk** [comment]
It's often good to see how kubernetes core does things. E.g., check how kubectl gets events for an object when you describe it: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go line 424. 

See also at events client API: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/events.go

Does this help?

**Comment by maciaszczykm** [comment]
Yes, it's nice starting point.

**Comment by floreks** [comment]
@bryk: I've been looking on getting information about service for this view. Only way replication controller and service are connected is through labels. We have to assume that for RC label selector there will be matching service with same label selector(if created) and if there is no service just hide this information. There is no other way around this, right?

**Comment by bryk** [comment]
@floreks See how replicasetlist.go matches services with replication controllers. Definitely reuse code from there. For now services that have label selector that is subset of replication controller label selector are matched. Though this may change in the future.

**Comment by floreks** [comment]
@bryk: That's all i needed, thx.

**Comment by bryk** [comment]
Are you touching replica set details page here? I want to work on it

**Comment by floreks** [comment]
Yes me and Marcin are working on it. UI is mostly done and part of backend. We can create PR in 15 min if you want to work on it also.

**Comment by bryk** [comment]
Yes, create a PR so that I can work on one part on the view and you on the other :)

**Comment by maciaszczykm** [comment]
@bryk I've created a pull request https://github.com/kubernetes/dashboard/pull/127.

**Comment by maciaszczykm** [comment]
@bryk I was thinking if implementing next part of this view is good idea at the moment. If yes, I could work on events filtering, but there are few details, that need to be clarified:

- How we can tell, that event is a warning or not? Is there any property for it (but I couldn't find it with `kubectl get ev --namespace=asdasdsad -o wide`) or we should implement some kind of check (for example based on message)?
- Similar question is connected to source. How we can tell if it is from user, system or anything else?

That's all, that comes to my mind at the moment, but I think a few more questions may appear later.

**Comment by bryk** [comment]
> I was thinking if implementing next part of this view is good idea at the moment.

Yes

**Comment by bryk** [comment]
> How we can tell, that event is a warning or not?

See:
https://github.com/kubernetes/kubernetes/pull/15999
https://github.com/kubernetes/kubernetes/issues/15624

Does this help?

**Comment by bryk** [comment]
> Similar question is connected to source. How we can tell if it is from user, system or anything else?

Honestly, I dont know. Isn't there an API for this? Did you check kubernetes/pkg/api/{unversioned}/types.go?

**Comment by bryk** [comment]
> I've checked and events view displays at the moment events only for pods that, still exists in replica set, but kubectl get ev displays events for deleted pods too. What is our target? Should we follow kubectl behaviour?

Do you think we can do this?

**Comment by maciaszczykm** [comment]
>>  How we can tell, that event is a warning or not?

> See:
kubernetes/kubernetes#15999
kubernetes/kubernetes#15624

> Does this help?

Yes, it does, but I think there is still something wrong in my cluster or somewhere else, because everytime I check this field is empty. I will implement empty-string check and if it will be true, then I will return type `api.EventTypeNormal`. If someone could check if his events have `type` set, then maybe we can make more progress with it.

**Comment by bryk** [comment]
> Yes, it does, but I think there is still something wrong in my cluster or somewhere else,

Maybe you have old version of Kubernetes?

**Comment by maciaszczykm** [comment]
You were right, I was using my fork, which was not up-to-date with base repository... Now events have proper types. Please check pull request #146 for more details.

Now I will investigate second option picker and check if its possible to load events for deleted pods.

**Comment by maciaszczykm** [comment]
>>Similar question is connected to source. How we can tell if it is from user, system or anything else?

>Honestly, I dont know. Isn't there an API for this? Did you check kubernetes/pkg/api/{unversioned}/types.go?

I've checked and I didn't find anything useful. Only thing connected to event source in its structure is component and host data, for example `{kubelet 127.0.0.1}`. I don't know if it's possible to implement this functionality at the moment. Should we provide any kind of mock or maybe open an issue on Kubernetes repository to get help?

**Comment by maciaszczykm** [comment]
>>I've checked and events view displays at the moment events only for pods that, still exists in replica set, but `kubectl get ev` displays events for deleted pods too. What is our target? Should we follow kubectl behaviour?

>Do you think we can do this?

I wasn't able to find any way yet. It displays history data in `kubectl get ev` because only namespace is parameter there. Since we specify also replica set, then I think the only way would be adding history for replica set (its previous pods). I think it's a bit too complex to implement at the moment.

**Comment by bryk** [comment]
So you say: display events only for currently living pods? I agree.

**Comment by floreks** [comment]
Just progress update. I'm currently working on delete and edit replicas count buttons. PR related to delete button is already created: #151. Second part should be done soon.

**Comment by maciaszczykm** [comment]
@bryk Yes, currently we display events only for replica set and its living pods.

**Comment by bryk** [comment]
Awesome. 

Btw, rolling update is going to be hard. It needs a separate issue, design and discussion.

**Comment by maciaszczykm** [comment]
Closing as initial version of events view is implemented. However, still some things to do like filtering by source.

**Comment by bryk** [comment]
Awesome, thanks! :)
