### ISSUE TITLE
Time format inconsistency across dashboard

### ISSUE THREAD

**Issue by PiotrDabkowski** [kubernetes/dashboard#1040]
Tooltip shows local time for example for replica sets while for pods it shows UTC time. I think we should agree on one time format.

`getCreatedAtTooltip` method is present in all XYZcard_component.js files therefore it would be nice to create one common component.

**Comment by cheld** [comment]
Bug is still there for Replica Set. In general we show all dates in UTC. We also have a filter component

https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/common/filters/date.js

Seems to be missing at some places

**Comment by cheld** [comment]
By now date is handled correctly. Just fund small labeling issues (missing word 'UTC')
