### ISSUE TITLE
Filter replica sets with zero pods

### ISSUE THREAD

**Issue by neelance** [kubernetes/dashboard#1041]
#### Issue details

Deployments create a large number of replica sets for older versions of the deployment. Those have no pods and are not really useful on the dashboard view. I propose filtering those by default and adding a toggle to show them.

```
Dashboard version: 1.1.0
```

**Comment by bryk** [comment]
@therc, can you comment?

Yeah, we're aware of this issue. @therc was going to fix this in the core Kubernetes, but the PR got stuck for a while.

**Comment by therc** [comment]
It would be great if you could comment on https://github.com/kubernetes/kubernetes/pull/27510 with your user experience feedback. 
The client-side PR is kinda stuck in review limbo. I'll try to see if I can come up with some server-side change, but that's an area of the code I have never touched or seen before.

**Comment by bryk** [comment]
I'll ping that issue. If this is not going to move forward anywhere, I guess we'll do this on the UI side.

**Comment by neelance** [comment]
This is still any issue. Any plans to maybe fix this on the UI side?

**Comment by cheld** [comment]
Currently, the UI shows the same number of replica sets as the CLI. I assume this is the expected behavior

**Comment by neelance** [comment]
@cheld This is true, but it is still quite inconvenient when using a lot of deployments.

**Comment by cheld** [comment]
Ok I see. In my cluster (v1.7) 2 revisions are kept by default. Let me clarify:
- Do you have an older cluster with unlimited default
- did you change .spec.revisionHistoryLimit 
- Is 2 revisions still too much

**Comment by neelance** [comment]
We're on a GKE cluster (version 1.7.6) and it looks as if the default for `revisionHistoryLimit` is 10. A default of 10 can also be seen here:
https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/apis/extensions/v1beta1/defaults.go#L60-L63

**Comment by neelance** [comment]
Okay, the code snipped I liked if for daemon sets, but I also see it for deployments on our cluster.

**Comment by cheld** [comment]
https://github.com/kubernetes/kubernetes/issues/23597

**Comment by cheld** [comment]
https://github.com/kubernetes/dashboard/issues/882

**Comment by cheld** [comment]
In Kubernetes 1.6 there is no limit:
https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/apis/extensions/v1beta1/defaults.go#L75

In Kubernetes 1.7 the limit is 3:
https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/apis/apps/v1beta1/defaults.go#L110

In Kubernetes 1.8 the limit is 10:
https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/apis/apps/v1beta2/defaults.go#L113

**Comment by cheld** [comment]
kubectl also shows all empty rs:

```
cheld@workstation:~/devel/test$ kubectl get rs 
NAME                          DESIRED   CURRENT   READY     AGE
nginx-deployment-56cb865897   0         0         0         20m
nginx-deployment-5c96cd678    0         0         0         18m
nginx-deployment-5f487f48c5   0         0         0         15m
nginx-deployment-66c8996cb4   0         0         0         16m
nginx-deployment-67c8777f6f   0         0         0         16m
nginx-deployment-68668d5d59   0         0         0         16m
nginx-deployment-74857495dd   0         0         0         13m
nginx-deployment-7b4554c48b   0         0         0         16m
nginx-deployment-855977575    0         0         0         16m
nginx-deployment-bc55988d8    3         3         3         10m
nginx-deployment-dd96b5fc8    0         0         0         15m
```

I don't think there is an option to hide empt rs

**Comment by cheld** [comment]
@maciaszczykm WDYT?

**Comment by maciaszczykm** [comment]
I would follow `kubectl` here. We could filter it on our own, but not by default. This would have to be an enhancement (for example checkbox below list `hide empty rs` or something like that).

**Comment by maciaszczykm** [comment]
The backend issue was closed as the decision was to avoid the filtering. I think we should do the same.

It is too custom to implement only for one resource. It should work for all workloads, not only the replica sets.

**Comment by maciaszczykm** [comment]
Please reopen/comment if you disagree.
