### ISSUE TITLE
Links from namespaced list views don't include namespace

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1056]
Links from namespaced views are broken. They don't include the current namespace. To try this out, open UI at HEAD, navigate to kube-system workloads and click on a link to details. Notice that namespace has changed to "all user namespaces". 

This was introduced in https://github.com/kubernetes/dashboard/pull/1032 by modifying globalresourcedetail.js. 

@floreks Can you fix this?

**Comment by floreks** [comment]
Did you encounter that issue on other list views also?

**Comment by bryk** [comment]
Yes. All list views are affected.
