### ISSUE TITLE
Empty pod list on node details page

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1064]
##### Environment

```
Dashboard version: latest
Kubernetes version: latest
Operating system: Ubuntu
Node.js version: v5.10.1
Go version: go version go1.6.2 linux/amd64
```

##### Steps to reproduce

1. Start empty cluster.
2. Go to `/nodes` view.
3. Open node details view (note: node shouldn't have any pods scheduled).

##### Observed result

Only table headers are displayed in pods table.

##### Expected result

In pods section there is information, that there is nothing to display.

**Comment by bryk** [comment]
What do you mean? Can you post a screenshot?

**Comment by digitalfishpond** [comment]
Looking at this now.

**Comment by digitalfishpond** [comment]
![selection_005](https://cloud.githubusercontent.com/assets/13361549/17357755/a73c7ae8-595e-11e6-8fa9-44c4f650b25c.jpg)

**Comment by maciaszczykm** [comment]
@digitalfishpond Yes, that's the problem.

**Comment by digitalfishpond** [comment]
Would something like this be acceptable? Or would we want the generic zerostate message ('There is nothing to display here')

![selection_007](https://cloud.githubusercontent.com/assets/13361549/17363784/d71add2c-597c-11e6-8d51-b5f99633ef1a.jpg)

**Comment by maciaszczykm** [comment]
So it seems, that we need only one `ng-if` there :)

**Comment by digitalfishpond** [comment]
Fixed with #1094

**Comment by digitalfishpond** [comment]
Moved the general issue of showing message rather than hiding component to new issue #1095

**Comment by maciaszczykm** [comment]
@digitalfishpond Sure. Closing.
