### ISSUE TITLE
pasting into edit field also pastes in spurious leading newlines

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/dashboard#1065]
##### Environment

I'm running Google Container Engine with 1.3.2. Using Chrome 52.0.2743.82 on OS X 10.11.6
##### Steps to reproduce

Click edit on a deployment, delete a tag from container's image field, copy the new tag from your Terminal instance, and then paste a new tag there at the end after the colon. 
##### Observed result

There'll be a newline before the tag you posted, and after the colon. When you Alt+Left arrow over, 12 `\n` characters will be displayed. Pasting the same text into another OS X app will have no newlines.

Before:
<img width="448" alt="screen shot 2016-07-23 at 11 20 29 pm" src="https://cloud.githubusercontent.com/assets/598/17082277/4ce19950-512c-11e6-97f7-17c8c9e49ce0.png">

The copied text from terminal:
<img width="163" alt="screen shot 2016-07-23 at 11 20 37 pm" src="https://cloud.githubusercontent.com/assets/598/17082281/71f4f5e8-512c-11e6-9ba8-8f9300042184.png">

The pasted in text:
<img width="395" alt="screen shot 2016-07-23 at 11 20 45 pm" src="https://cloud.githubusercontent.com/assets/598/17082283/825c0822-512c-11e6-97a7-696833baee56.png">

After Alt-Left'ing away:

<img width="400" alt="screen shot 2016-07-23 at 11 21 24 pm" src="https://cloud.githubusercontent.com/assets/598/17082285/8ece031c-512c-11e6-93c6-1a1e6a69a98d.png">

Pasting the same text into this GitHub issue field with words around it:

<img width="289" alt="screen shot 2016-07-23 at 11 26 18 pm" src="https://cloud.githubusercontent.com/assets/598/17082296/e0798010-512c-11e6-9419-638e6205f9f4.png">
##### Expected result

I'd expect there to be no newlines insert the field.

**Comment by jmhodges** [comment]
(Fixed up the issue's screenshots to be more clear and added that I'm running Kubernetes 1.3.2 in GKE)

**Comment by bryk** [comment]
Would having a plaintext-only mode help?

**Comment by jmhodges** [comment]
Maybe? Feels like the bug is elsewhere, though.

**Comment by bryk** [comment]
All right. Thanks for reporting the bug. We'll investigate this soon.

**Comment by maciaszczykm** [comment]
We have switched YAML editor dependency and set `code` instead of `tree` mode. It should fix most of the problems, as standard text editor operations work right now.
