### ISSUE TITLE
Dashboard password 

### ISSUE THREAD

**Issue by chowyu08** [kubernetes/dashboard#1067]
Dashboard version: 1.1.0
Kubernetes version: 1.3.0
Operating system: ubuntu14.04
Go version: 1.6.2

kubernetes install
1. git clone https://github.com/kubernetes/kubernetes.git
   cd kubernetes
    make release
2. deploy it as 
   http://kubernetes.io/docs/getting-started-guides/ubuntu/
   KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
3. deploy dashboard as 
   KUBERNETES_PROVIDER=ubuntu ./deployAddons.sh

##### Observed result:
Everyone can access the dashboard by the http://159.99.93.113:8080/ui    , everyone can delete an modify it .
### kube-apiserver set:
KUBE_APISERVER_OPTS=" --insecure-bind-address=0.0.0.0 --insecure-port=8080 --etcd-servers=http://127.0.0.1:4001 --logtostderr=true --service-cluster-ip-range=10.0.0.0/16 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,SecurityContextDeny,ResourceQuota --service-node-port-range=30000-32767 --advertise-address=159.99.93.113 --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key

##### Expected result
Everyone should input the username and password

how can I do to set  it ?

**Comment by cheld** [comment]
Remove  --insecure-bind-address=0.0.0.0 and use https to access Dashboard

**Comment by chowyu08** [comment]
@cheld I change ,and restart the kube-spiserver service ,but does not work
KUBE_APISERVER_OPTS=" --bind-address=0.0.0.0 --secure-port=6443 --etcd-servers=http://127.0.0.1:4001 --logtostderr=true --service-cluster-ip-range=10.0.0.0/16 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,SecurityContextDeny,ResourceQuota --service-node-port-range=30000-32767 --advertise-address=159.99.93.113 --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key

**Comment by chowyu08** [comment]
@cheld I change the petermeters in /etc/default/kube-apiserver as 
KUBE_APISERVER_OPTS=" --bind-address=0.0.0.0 --secure-port=6443 --etcd-servers=http://127.0.0.1:4001 --logtostderr=true --service-cluster-ip-range=10.0.0.0/16 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,SecurityContextDeny,ResourceQuota --service-node-port-range=30000-32767 --advertise-address=159.99.93.113 --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key

but it does not work?

**Comment by cheld** [comment]
Do you use the correct url ?

https://159.99.93.113/ui

**Comment by chowyu08** [comment]
@cheld yes

**Comment by cheld** [comment]
Does https://159.99.93.113/ work in browser?

**Comment by chowyu08** [comment]
@cheld no, return error “refused to connect."

**Comment by cheld** [comment]
well...then your installation is completely broken

I assume the KUBERNETES_PROVIDER=ubuntu provider is not making the required steps for secure setup.   
You should better file issue in kubernetes core

**Comment by bryk** [comment]
Yep, @chowyu08 I guess that it's best to file an issue in the documentation guide.
