### ISSUE TITLE
Overview pages - UX and content

### ISSUE THREAD

**Issue by Lukenickerson** [kubernetes/dashboard#1068]
Given the current navigation, we're looking at having an overview page for each of the main sections -- Workloads, Services, Storage, Config -- as well as a main overview for the entire workspace. This issue is to discuss what content should be on each of these overviews, and how it should be displayed.

Initially I'm thinking the _section overviews_ should have these **goals**:
- Alerts - What needs alerting + what action can be done to resolve the alert -- Inform the user of anything that is cause for concern and provide them with both a suggested course of action and the navigation to perform this action.
- History - What has changed -- Let the user know how the items have changed since the last time they checked or within the last day or two (precise timeframe TBD)
- Health Metrics -- Give the user some indication of the status of the items in the section (could be combined with the two above in some way)
- Navigation -- User should be able to get to the details of each of the items.
- Education -- We should help explain what each item is. [It's important to consider the new user experience](https://groups.google.com/forum/#!topic/kubernetes-dev/MoyWB66vAKY/discussion), and these overview pages are a good place to further explain some of the basic concepts.

The _main overview_ could either have the same goals and content as the section overviews, or could have something different. (As an aside: Is there better wording for "main overview" and "section overview"?)

Regarding the UI and style, I think some obvious things to consider are:
- Card format - at least one card per section item
- Graphs / Visualization where it makes sense
- Real-time updates (have the data pushed to the front end)
- "As simple as possible, but no simpler." When providing lots of information in a single view there is fine line between providing a helpful summary and information overload.

There are many good examples of "dashboards": Datadog has some good examples ([here](http://ispokemongodownornot.com/), [here](https://www.datadoghq.com/dashboarding/)), as does google cloud platform, google analytics, and [many](https://camo.githubusercontent.com/a294bbeb78340c703f12a7eb1f8cebe1da1fe3dc/687474703a2f2f636c2e6c792f696d6167652f3154336130583430327230572f53637265656e25323053686f74253230323031342d31302d32392532306174253230332e33352e3034253230414d2e706e67) [others](http://www.jenunderwood.com/wp-content/uploads/2015/05/520.gif).

**Comment by bryk** [comment]
> Alerts - What needs alerting + what action can be done to resolve the alert -- Inform the user of anything that is cause for concern and provide them with both a suggested course of action and the navigation to perform this action.

I think this is not strictly alerts, but things that require your attention. Alert would be something that wakes you up at night. This may be "pod x is in a crash loop, fix this" or "node x cannot schedule any more pods". 

> History - What has changed -- Let the user know how the items have changed since the last time they checked or within the last day or two (precise timeframe TBD)

Yeah, like recent changes to all your workloads. This is super nice, but I'm worried that there's technical challenges with this. I.e., no one provides us a history of changes, so we'd have to architect it by ourselves. But this is to be researched. 

> Health Metrics -- Give the user some indication of the status of the items in the section (could be combined with the two above in some way)

Do you mean something like CPU usage or similar? @PiotrDabkowski works on this at the moment. The idea is to combine metrics like CPU/memory usage with events stream and display this on a single graph.

**Comment by bryk** [comment]
> Navigation -- User should be able to get to the details of each of the items.
Education -- We should help explain what each item is. It's important to consider the new user experience, and these overview pages are a good place to further explain some of the basic concepts.

I agree with you here. 

Do you have any proposal how section overview page would look like when incorporated all those five goals? You know how it looks now and you've probably seen the balsamiq wireframes. Can we work with @romlein here?

**Comment by bryk** [comment]
> Card format - at least one card per section item

I think whether we use cards or not depends on the style we settle on in the nav discussions. Things can be here in cards and in "blocks" as on any other website.

**Comment by bryk** [comment]
@digitalfishpond @batikanu Any comments here?

**Comment by digitalfishpond** [comment]
> As an aside: Is there better wording for "main overview" and "section overview"

Overview / Section Summary ?

**Comment by digitalfishpond** [comment]
> I think this is not strictly alerts, but things that require your attention

Maintenance tips ?

**Comment by digitalfishpond** [comment]
> Card format - at least one card per section item

Is it not feasible that a section item may be in a state where it has no cards yet? In that case maybe a place-holder card could mark the space, something saying "There are no ... in ... yet, create one" with a link to the relevant area of creation.

**Comment by batikanu** [comment]
> Education -- We should help explain what each item is. It's important to consider the new user experience, and these overview pages are a good place to further explain some of the basic concepts.

Maybe short hover help text for each item which links to corresponding kubernetes documentation sections for more details.

**Comment by Lukenickerson** [comment]
Now that I think about it more I like the word "Notifications". Like Piotr says, they would be "things that require your attention" but don't necessarily keep you up at night. They could be analogous to Notifications in GitHub, Facebook, etc. I think there is considerable overlap between notifications, history, and health metrics so I'll have to give this more thought and see if Dan and I can get some mockups.

Regarding the history: 

> no one provides us a history of changes, so we'd have to architect it by ourselves. But this is to be researched 

My initial thought is that this could be something that is better to have built into the core of Kubernetes, so that others (kubectl) can make use of the same APIs. @bryk What's the best way to figure this out?

For the health metrics, I was thinking more about individual numbers or statuses that would indicate whether a particular thing (e.g., pod, node) is "healthy" or "unhealthy". But we might be able to utilize some minimal graphs from https://github.com/kubernetes/dashboard/issues/1010.

To some of the other points...

>a place-holder card could mark the space, something saying "There are no ... in ... yet, create one" with a link to the relevant area of creation

:+1: Yes, that sounds good for a zero state. 

> short hover help text for each item which links to corresponding kubernetes documentation sections for more details

:+1: I like that!

**Comment by romlein** [comment]
I'm realizing we seem to have an 'overview overload' situation here:
- There's an _Overview_ for the entire cluster
- Each main item like _Workloads_ we've been referring to as an _Overview_, and...
- Based on the [wireframes](https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/23-03-2016-scale-and-navigation/pod-details-page-overview.png) from [UX and navigation that scales](https://github.com/kubernetes/dashboard/blob/master/docs/design/navigation-and-scale.md#navigation), each object (e.g. _Pods_) will have an _Overview_.

This many "Overviews" will confuse users, so I think we should reconsider information architecture, or at the least rename each to be unique.

**Comment by romlein** [comment]
[Paper sketch in InVision](https://invis.io/3586G3YJ2) of what a section (_Workloads_, in this case) could look like. Thoughts? Toggle on "Comments" to view a few notes I've left.

**Comment by maciaszczykm** [comment]
@romlein Hmm, I couldn't see any comments after turning them on... don't know why.

Regarding this view and card design - I think it may be a problem. Especially with this grid layout and two cards in a row. It can cause additional problems during implementation and I'm not sure if we will be able to put all data in shrunk cards. Otherwise it looks good. I like these two graphs in the top, but still I'm not sure what to put here.

**Comment by bryk** [comment]
@Lukenickerson 
> Now that I think about it more I like the word "Notifications". Like Piotr says, they would be "things that require your attention" but don't necessarily keep you up at night. They could be analogous to Notifications in GitHub, Facebook, etc. I think there is considerable overlap between notifications, history, and health metrics so I'll have to give this more thought and see if Dan and I can get some mockups.

Fully agree.

> My initial thought is that this could be something that is better to have built into the core of Kubernetes, so that others (kubectl) can make use of the same APIs. @bryk What's the best way to figure this out?

Yes, we can (and should) build this into K8s core. But this is a quarter-long task, so we should do this only when we have all the basics.

**Comment by bryk** [comment]
@romlein 

> I'm realizing we seem to have an 'overview overload' situation here:
There's an Overview for the entire cluster
Each main item like Workloads we've been referring to as an Overview, and...
Based on the wireframes from UX and navigation that scales, each object (e.g. Pods) will have an Overview.
This many "Overviews" will confuse users, so I think we should reconsider information architecture, or at the least rename each to be unique.

I agree. I think that we can (and should) remove the _Overview_ from resource detail page.

Regarding the pages pages like "Workloads", how about we call them "category pages"? What they really show is all your workloads/services/foos, which could be called "overview", but I think that there is no need.

Regarding cluster overview - this should be the overview.

**Comment by maciaszczykm** [comment]
We already have an overview of each category and global overview. There is A LOT to improve, but I believe this discussion has ended. We will track from other issues like #2145.
