### ISSUE TITLE
Delete namespace missing in design mock-ups

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#107]
It seems it is possible to create namespaces, but it is not possible to delete them again.

Is this intentional?

**Comment by cheld** [comment]
@maciaszczykm

**Comment by bryk** [comment]
@kenmoore

**Comment by maciaszczykm** [comment]
@cheld Yes, namespaces creation is possible and already implemented (at least initial version). However, I do not know anything about functionality of deleting existing namespaces. I think it's a question rather for someone who was creating designs.

From my point of view it's possible to implement it, but I'm not sure if it's necessary. Moreover, to delete namespace I suppose it's required to delete all associated objects or block operation if there are any associations.

**Comment by cheld** [comment]
I asked this as a design question, not a technical question. I am wondering if this is a design bug. With the current design a bit tricky to fix.

**Comment by kenmoore** [comment]
Namespaces were a late(r) addition to the design and while creating a new namespace was noted as important to support, deleting namespaces hasn't previously been raised as a common use case.  Unless there's a strong case to be made for it, I'd prefer to leave it out initially and we can add support in later if the need becomes clear.
