### ISSUE TITLE
kubectl config view - no users

### ISSUE THREAD

**Issue by bweston92** [kubernetes/dashboard#1076]
#### Issue details

I've created a small cluster using the documentation for [Fedora multi node](http://kubernetes.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/)

##### Environment

```
Dashboard version: Latest (https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml)
Kubernetes version: 1.2
Operating system: Fedora 24
Node.js version: not installed.
Go version: not installed.
```

##### Steps to reproduce

- Use documentation to setup Fedora multi node cluster.
- follow README for dashboard to install.

##### Observed result

No users (shown below) and no `/ui` on my master node.

```
# kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

##### Expected result

A dashboard user and the HTTPS route to work.

##### Comments

More documentation required for bare bones setup maybe?

**Comment by bryk** [comment]
Thanks for reporting this issue. I think this is certainly a problem with the Fedora setup. Can you repost this issue on https://github.com/kubernetes/kubernetes.github.io ?
