### ISSUE TITLE
Release v1.1.1

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#1078]
Lots of changes since v1.1.0, it's probably time to release a v1.1.1 ?

**Comment by floreks** [comment]
Thanks for creating this issue :) I've totally forgot about that.

**Comment by edouardKaiser** [comment]
Are we waiting for some particular issues to release 1.1.1 ?

**Comment by floreks** [comment]
We have to wait for @bryk as he is the only one that can do the release :) He should be back next week.

**Comment by edouardKaiser** [comment]
Thanks for the information !

**Comment by bryk** [comment]
Ooops, just returned from vacation. Will do release tomorrow.

**Comment by edouardKaiser** [comment]
Awesome, thanks

**Comment by maciaszczykm** [comment]
Done by @bryk.

https://github.com/kubernetes/dashboard/releases/tag/v1.1.1
