### ISSUE TITLE
problem of pod list

### ISSUE THREAD

**Issue by GavinSong123** [kubernetes/dashboard#1080]
We run Dashboard in container with Kubernetes.
Dashboard version:v1.1.0
Kubernetes version:v1.3.0-beta.1

In our cluster, there will be some failed pods because of some problems. Sometimes there will be thousands of pods whose status is failed. 

Observed result
We can see these failed pods on the dashboard.

Expected result
These failed pods can filter or can be deleted together

**Comment by bryk** [comment]
Do the failed pods expire at some point? Would sorting by status help here?

**Comment by GavinSong123** [comment]
On dashboard, resources can't be sorted by status. And the failed pods have left for a period of time. Maybe it won't expire I think.

**Comment by bryk** [comment]
> On dashboard, resources can't be sorted by status.

Yes, that's right. But we plan to add such feature.

**Comment by GavinSong123** [comment]
About faild pod, are there some method to solve? Listing all faild pod on dashboard is not convenient for users.

**Comment by bryk** [comment]
We aim to solve this problem by filtering. But, as you see, there is no filtering yet. What you can do is delete all the failed pods. Either through the UI, CLI or API.

**Comment by GavinSong123** [comment]
OK, looking forward to more features of dashboard.
