### ISSUE TITLE
Dashboard Mission Statement

### ISSUE THREAD

**Issue by Lukenickerson** [kubernetes/dashboard#1081]
I think it might be helpful to distill the Dashboard's mission into a small handful of easy-to-consume [mission statement](https://en.wikipedia.org/wiki/Mission_statement) bullet points. This would help explain the purpose of the dashboard to outsiders, help encourage more people to join the SIG UI group and contribute, and help guide certain decisions.

This mission statement would be helpful on both of these pages:
- https://github.com/kubernetes/dashboard/blob/master/README.md 
- https://github.com/kubernetes/community/blob/master/sig-ui/README.md (currently empty!)

A good starting point is the intro sentences on the README: 

> Kubernetes Dashboard is a general purpose, web-based UI for Kubernetes clusters. It allows users to manage applications running in the cluster and troubleshoot them, as well as manage the cluster itself.

and in the Kube docs:

> Dashboard (the web-based user interface of Kubernetes) allows you to deploy containerized applications to a Kubernetes cluster, troubleshoot them, and manage the cluster and its resources itself. 

...as well as the original ["Console thoughts" issue](https://github.com/kubernetes/dashboard/issues/21), and probably other discussions that I just haven't found yet.

Some discussion-starter questions: _What do we do?_ (main purpose), _How do we do it?_ (plan to achieve the mission), _Whom do we do it for?_ ([users](https://github.com/kubernetes/dashboard/issues/975)), _What value are we bringing?_ (benefits)... Should the dashboard be focused more towards new users to kubernetes vs. power users? Which is most important: visualization, actions, guidance, etc.?

**Comment by bryk** [comment]
@Lukenickerson Thanks for starting this discussion. How about answer I start the discussion-starter questions as I've been longest in the project and then we distill the mission statement?

**Comment by Lukenickerson** [comment]
@bryk -- Yeah, you will have the best insight in the project, so you should take the first pass at answering the discussion starter questions.

**Comment by maciaszczykm** [comment]
Closing as stale. https://github.com/kubernetes/community/blob/master/sig-ui/README.md is no longer empty.
