### ISSUE TITLE
Create unit tests for create namespace

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#109]
I start writing unit tests for the create namespace dialog. 

There are some small issues on this page e.g. validation. I would consider to do these next

**Comment by bryk** [comment]
Thanks for taking this. I think that the project codebase has stabilized enough that we should start writing tests for all features.

**Comment by cheld** [comment]
One async validation and some unit-tests missing. I continue on this issue

**Comment by bryk** [comment]
Closing as stale.
