### ISSUE TITLE
Show empty resource message in relevant details page section rather than hide section.

### ISSUE THREAD

**Issue by digitalfishpond** [kubernetes/dashboard#1095]
#### Issue details

From discussion in #1064 , @maciaszczykm wrote :
> In longer term I think it would be nice to inform users, that there are no pods scheduled on given node. Otherwise, they might think, that this feature is no implemented yet or something is not working correctly.

##### Steps to reproduce
Currently when a resource is empty, their card is hidden in related details pages. (eg. create an empty cluster, open /node url, click on node - there is no Pods section at the bottom of the page because there are no pods scheduled on that node.)

##### Expected result
There should be a section entitled 'Pods' (or other relevant resource) with a message saying that there are currently no pods scheduled on that node (or other relevant message) so that the user knows that this functionality exists, just there is currently nothing to show.

**Comment by digitalfishpond** [comment]
Working on this now

**Comment by digitalfishpond** [comment]
@maciaszczykm, @floreks, @batikanu, What do you guys think of this message? Or should we recycle the message from the zerostate title - "There is nothing to display here" ?
![selection_008](https://cloud.githubusercontent.com/assets/13361549/17435047/6501de28-5b0e-11e6-80da-d43dbc4eb581.jpg)

**Comment by maciaszczykm** [comment]
Hmm... this message seems to be okay. Try to use same font as in `There is nothing to display here` message.

**Comment by digitalfishpond** [comment]
I think it is, even in this screen-shot, I used the kd-zerostate-title class just for the purpose of the screenshot.

**Comment by digitalfishpond** [comment]
![selection_009](https://cloud.githubusercontent.com/assets/13361549/17435699/c708a6d4-5b12-11e6-8f51-d049e83e961d.jpg)

**Comment by bryk** [comment]
Hmm.. How about changing "there is nothing to disaply here" to "No pods are running on this node"? I.e., make the message less generic :)

**Comment by digitalfishpond** [comment]
@bryk, so that's where I started, (#1064) , however @maciaszczykm suggested that it would look better if we had the same message as for zerostate with the specific message about no pods scheduled on this node underneath. which is why I suggested this generic title and specific body solution. There is another example a few messages further up on this issue.

**Comment by bryk** [comment]
Oh, I see. There is the second line which explains details. LGTM

**Comment by bryk** [comment]
Should this be closed? Don't we want to solve the problem holistically for all pages?

**Comment by maciaszczykm** [comment]
@bryk Sure, let's fix this everywhere.

**Comment by digitalfishpond** [comment]
fixed with #1132
