### ISSUE TITLE
Service detail view does not update after switching namespace

### ISSUE THREAD

**Issue by aneeshd16** [kubernetes/dashboard#1097]
#### Issue details
Service detail view does not update after switching namespace from the top-right dropdown
##### Environment

```
Dashboard version: 1.1.0
Kubernetes version: 1.3.3
```

##### Steps to reproduce

1. Go to services view `https://<k8surl>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/service?namespace=test` (I have a namespace called test)
2. Click on any service `https://<k8surl>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/service/test/<service-name>?namespace=test` (Note the values of pod name, elb etc)
3. Change the namespace from the top-right dropdown. The view seems to refresh, but it does not fetch the values of the selected namespace

##### Observed result

The service details remain exactly the same
##### Expected result

The service details should update when the namespace is switched

**Comment by floreks** [comment]
Yes, we're aware of this 'issue'. Switch on details page will be changed/removed. Probably it will redirect user back to list page after namespace change because we can't assume that same resource exists in different namespace.

This issue is similar to #816.

**Comment by aneeshd16** [comment]
Awesome. Caused a lot of confusion in my deployment though. Closing this, will wait for #816.
