### ISSUE TITLE
Update go veriosn in getting-started guide

### ISSUE THREAD

**Issue by fwalker** [kubernetes/dashboard#1107]
The [getting started guide](https://github.com/kubernetes/dashboard/blob/master/docs/devel/getting-started.md#preparation) states 

> go (1.5+)

as minimum required go version. The [actual required version](https://github.com/kubernetes/dashboard/blob/master/build/gocommand.js#L38) is 

> const minGoVersion = '1.6.1';

**Comment by maciaszczykm** [comment]
Done.
