### ISSUE TITLE
Failure of /workloads API request causes looping requests

### ISSUE THREAD

**Issue by julia-allyce** [kubernetes/dashboard#1110]
#### Issue details
When the dashboard initially loads if the /workloads api returns an error it will keep making the workloads request until it succeeds. 
##### Environment
```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

##### Steps to reproduce
1. Force api to return 500s on /workloads
2. Load dashboard

##### Observed result
app keeps reloading workloads and remaking workloads request, this will cause the browser to crash

##### Expected result
Display an error message

##### Comments
I'm not entirely sure, because I am unfamiliar with the app, but I think this is caused by this line:
https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/index_route.js#L25

**Comment by julia-allyce** [comment]
I see the nil pointer issue was fixed, but was the an error handler added to the UI?

**Comment by bryk** [comment]
Currently we handle errors by showing "Internal error" view + optional stacktrace. So that's the error handling.

**Comment by julia-allyce** [comment]
Is that newly added?  When the workloads request fails you pretty much DoS your own service, because the error is never handled and the ui defaults to the to the workloads view and keeps making the request over and over again.

**Comment by bryk** [comment]
@julia-allyce The DoS does not happen anymore. Now, when we see an error, we just show "internal error" page and stop autorefreshing.

**Comment by julia-allyce** [comment]
Ok cool. Thank you for clarifying 😁
