### ISSUE TITLE
Add resource quotas

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1112]
- [x] backend
- [ ] frontend list
- [ ] frontend details
- [ ] frontend namespace details link

**Comment by bryk** [comment]
Awesome, thanks!

**Comment by maciaszczykm** [comment]
Unfortunately, I cannot finish it at the moment...

**Comment by maciaszczykm** [comment]
@batikanu Can you take over?

**Comment by batikanu** [comment]
Sure, I'm looking at it

**Comment by maciaszczykm** [comment]
Waiting for #1258.

**Comment by batikanu** [comment]
I think this issue can be closed.
