### ISSUE TITLE
Add CPU/RAM details to node list

### ISSUE THREAD

**Issue by therc** [kubernetes/dashboard#1115]
It would be great to see how much CPU and RAM are reserved/used/free on each node, at a glance. I know there's limited horizontal space, so we can't show everything. There's disk, too, but that might be going too far. :-)

**Comment by bryk** [comment]
@PiotrDabkowski is working on this. The feature should land by the end of this quarter.

**Comment by maciaszczykm** [comment]
It seems, that we already have it covered. Allocated resources are displayed in the same way as in the `kubectl` and the only thing missing seems to be usage of certain pods (allocated resources is summary of all pods usage).
