### ISSUE TITLE
Implementation of left-hand navigation menu

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1117]
This is to track implementation of the left hand nav menu from #908. 

cc @Lukenickerson

**Comment by romlein** [comment]
Attached is a [Sketch file](https://github.com/kubernetes/dashboard/files/424956/dashboard-side-nav.sketch.zip) of finalized designs for the Dashboard side nav. This [InVision prototype](https://invis.io/3C8BDK9ZD) shows each Sketch artboard saved out as a separate PNGs.

Header and secondary / action bar we're still exploring a few different configuration options for, but those won't affect side nav. 

### Rationale:
 - General design principles:
  - _Simple_ – We want to make Dashboard easy to use, especially for new users.
  - _Flexible_ – To allow for future changes.
 - This follows as closely as possible the [Material design spec for navigation](https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-behavior), and has been designed in collaboration with Google designers from Cloud Platform – leveraging their expertise around following Material principles in the context of enterprise applications.
 - As far as specific Google products, this most closely resembles the styling of [Inbox](https://www.google.com/inbox/) and [Keep](https://www.google.com/keep/). The navigation and main content background occupy the same plane, thereby drawing users' attention to the content itself – displayed in cards.
 - Ordering of the side nav items is based on hierarchy established through research and discussion in #908. These views show what an admin would see, so they have the additional global namespace-independent objects of _Namespaces, Nodes, Persistent Volumes, and Pod Security Policies_. Devs would have that top section removed, so first in their view of the side nav would be _Namespace_. 

### Spec:
 - Side nav scrollbar appears only when a user hovers over the area. 
 - *Fonts*
  - Main: 14 px Roboto Medium, Regular #000000, 87% opacity
  - Label: 12px Roboto Regular #000000, 54% opacity
  - Namespace dropdown: 14px Roboto Mono Medium, #000000, 87% opacity
 - Background: #F2F2F2
 - Dividers: #DDDDDD
 - Selected nav item background / nav item hover: #000000, 5% opacity.
 - 1280 artboard contains a group called "Spacing" and shows the various sizing specs for elements.
  - Primary list items have a line height of 44px.
  - Sub-lists have a line height of 32px

Someday we would like to have the side nav collapse to icons, but for this initial design we've decided to hold off incorporating icons, for the reasons outlined in [#789](https://github.com/kubernetes/kubernetes.github.io/issues/789#issuecomment-240114775)

Please don't hesitate to reach out if you have any questions or see anything that should be changed!

**Comment by bryk** [comment]
So this is my most recent implementation. Still WIP. Based on this [Invision mockups](https://projects.invisionapp.com/share/3C8BDK9ZD#/screens).

![selection_108](https://cloud.githubusercontent.com/assets/1159999/17775237/a1d6ee4e-6557-11e6-967c-21cd51b94a17.png)

![selection_109](https://cloud.githubusercontent.com/assets/1159999/17775332/121e3a4a-6558-11e6-80be-33dc50a51425.png)

![selection_110](https://cloud.githubusercontent.com/assets/1159999/17775484/b52b991c-6558-11e6-9d2c-236d433ef4e8.png)



By playing with it I see a couple of insights:
* it is weird to have the hamburger button and nav separated by actionbar
* page title (e.g., "Pods") seems too far to the left and detached from the page content  

Questions (@romlein)
* what should an menu item be? Full width material button? A link? What is the click area?
* should table titles in workload page link to specific pages (E.g., "Replica Sets" title links to replica sets page). This is a duplication from the menu, not necessarily wrong. Should we maybe make the link less prominent and just render it as normal text?
* what about tabs in resource detail pages (aka tetrary nav level)? 
* what happens to the menu when I'm on, e.g., Workloads page? Should workloads menu item highlight?

**Comment by romlein** [comment]
@bryk
>it is weird to have the hamburger button and nav separated by actionbar.

Agreed, I think we should move the hamburger down a level.
![hamburger](https://cloud.githubusercontent.com/assets/5114858/17775669/426a71a4-6527-11e6-88c5-338d5791cd88.png)

>page title (e.g., "Pods") seems too far to the left and detached from the page content

Will think more on potential solutions for this.

>what should an menu item be? Full width material button? A link? What is the click area?

Click area is the full width of the background hover. Hmm, not sure on the best element / class to use there. cc @Lukenickerson 
![screen shot 2016-08-18 at 9 42 16 am](https://cloud.githubusercontent.com/assets/5114858/17775832/159b8e28-6528-11e6-877a-b5a6c06226a3.png)

>should table titles in workload page link to specific pages (E.g., "Replica Sets" title links to replica sets page). This is a duplication from the menu, not necessarily wrong. Should we maybe make the link less prominent and just render it as normal text?

Yes they should link, and no I don't see a problem with leaving them styled as-is for now.

>what about tabs in resource detail pages (aka tetrary nav level)?

Still working on that exact configuration, but they will push taller the second bar ("Workloads" in this case), and appear below "Workloads."

>what happens to the menu when I'm on, e.g., Workloads page? Should workloads menu item highlight?

Yes, it should be blue with the light gray background, as shown in the mockups as "Overview."

Also: side nav should slide away to the left _at the same time_ as cards expanding. This is what Inbox and Keep do.

**Comment by maciaszczykm** [comment]
The idea of moving hamburger menu lower seems to be good solution. Moreover, I like colors of these bars from @romlein's proposal:

> ![hamburger](https://cloud.githubusercontent.com/assets/5114858/17775669/426a71a4-6527-11e6-88c5-338d5791cd88.png)

**Comment by Lukenickerson** [comment]
I think that making the 2nd bar full width and moving the hamburger icon down is causing more problems than it's solving. 

Comparison of the previous design with the proposed design above:
![image](https://cloud.githubusercontent.com/assets/3942453/17779380/78739aa6-6535-11e6-86da-2b0df2d41660.png)

(blue = global-level navigation and actions, orange = content based on your page/selection/resource)

The issues with the design proposed above:
* Breadcrumb/title alignment breaks up the visual division between left-hand nav and content on the right
* Due to proximity, the breadcrumb/title may appear more closely tied to left-hand nav than to the actions on the right (echo of what Piotr said: "detached from the page content")
* Confusing to determine what elements on the page are related to global navigation/actions, and what is related to the selected page. 
* Most implementations of Material Design have the hamburger in the upper left. If we're going to break convention it should be for a good reason.

**Comment by Lukenickerson** [comment]
> what about tabs in resource detail pages (aka tetrary nav level)?

I think it would be great if we can somehow display the data so that a third level of navigation is unnecessary. Can the table of events just be shown below the overview information?

**Comment by bryk** [comment]
> Can the table of events just be shown below the overview information?

I think for this task we can just move events tables down to the page content. So that we have one design problem less. We have only events tabs anyways.

But for the future, we should consider alternatives in https://github.com/kubernetes/dashboard/issues/1137.
