### ISSUE TITLE
Pod state not correct

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#1121]
#### Issue details
Pod state is not correct in UI

##### Environment

```
Dashboard version: master (12. Aug)
Kubernetes version: v1.4.0-alpha.2
```

##### Steps to reproduce
```
$ kubectl run test --image=debian -- echo hello
$ kubectl get pods
NAME                    READY     STATUS             RESTARTS   AGE
test-2172490464-elqbi   0/1       CrashLoopBackOff   18         1h
```
##### Observed result
UI claims pod is in "Running" state

##### Expected result
"Crashed"

**Comment by bryk** [comment]
Interesting. Is CrashLoopBackOff status something new in 1.4 ?

**Comment by cheld** [comment]
Hmmm...I would say I have seen at least the "CrashLoopBack" part before. Not sure if I have seen the suffix "Off", though

**Comment by bryk** [comment]
Closing as stale.

**Comment by cheld** [comment]
Reproducible in v1.4.0-alpha.3

**Comment by maciaszczykm** [comment]
I guess we have to follow `kubectl` logic on backend side to fix it.

**Comment by cheld** [comment]
An alternative (not so nice) would be to show something unspecific e.g. 'unkown', 'incorrect'  as state in the UI. Than we do not have to copy the logic which seems a bit fragile

**Comment by bryk** [comment]
Ok, thanks for reopening!

**Comment by batikanu** [comment]
I made some research about it. I think we can reflect the logic of the [resource printer](https://github.com/kubernetes/kubernetes/blob/64f5d9c3f4b3997b59638448c76e58a56328b984/pkg/kubectl/resource_printer.go#L677) in kubectl. I can take it if you approve the solution.

**Comment by cheld** [comment]
I did not dig into the code. Maybe it is possible to extract a closed function (without side effects) that could be used by kubectl and Dashboard?

**Comment by floreks** [comment]
I think main assumption of this issue is wrong. It assumes that dashboard relies on simplified data description and we are actually trying to reflect `kubectl describe` not `kubectl get`.

Let's compare:
`kubectl describe pod test-496409221-psuql` returns
```
NAME                   READY     STATUS             RESTARTS   AGE
test-496409221-psuql   0/1       CrashLoopBackOff   6          9m
```

`kubectl describe pod test-496409221-psuql` returns
```
Name:		test-496409221-psuql
Namespace:	default
Node:		floreks-celsius-w530-power/192.168.30.230
Start Time:	Wed, 21 Sep 2016 09:15:52 +0200
Labels:		pod-template-hash=496409221
		    run=test
Status:		Running
IP:		    10.1.20.27
Controllers:	ReplicaSet/test-496409221
Containers:
  test:
    Container ID:	docker://6635f88851028a388f6cbb74e0a7270271ed1829f92019100dcb174c07d53b3a
    Image:		debian
    Image ID:		docker://sha256:a24c3183e91047d3a74482f37d5ec454e1741d4fed8611e2c4d84a65a3b404ff
    Port:		
    Args:
      echo
      hello
    State:		    Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Wed, 21 Sep 2016 09:17:32 +0200
      Finished:		Wed, 21 Sep 2016 09:17:32 +0200
    Ready:		False
    Restart Count:	4
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-p9hre (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-p9hre:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-p9hre
QoS Class:	BestEffort
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath		Type		Reason		Message
  ---------	--------	-----	----					-------------		--------	------		-------
  2m		2m		1	{default-scheduler }						Normal		Scheduled	Successfully assigned test-496409221-psuql to floreks-celsius-w530-power
...
```

Additionally when we check the code, `PodPhase` that is directly displayed in pod details page under pod `Status` offers only simple statuses.
![zrzut ekranu z 2016-09-21 09-28-59](https://cloud.githubusercontent.com/assets/2285385/18701613/dc6fd386-7fdd-11e6-8e49-c36910957376.png)

As the UI is aiming to reflect detailed info of resources, then currently displayed status is correct. `kubectl get` displays status of the container (if it's failing), not only status of the pod.

Solution for everything will be #1248. There will be available detailed information about containers, their statuses and events of the pod. Thanks to events we'll be able to also display errors on pod list page.

**Comment by cheld** [comment]
@floreks  
if a user clicks on workloads, the pods would be listed as running with a green check. This might be technically correct, but from user perspective it is not running. It would be counter intuitive. Fundamentally, we want problems to surface and not hide them.

If a user clicks on a pod it might be ok to display the pod as running and the container as crashed. 

Also, a pod listing is comparable to kubectl get pods and pod details is comparable to kubectl describe

**Comment by cheld** [comment]
@floreks  Just imagine Bob, our administrator has a cluster with 100 pods (non very much). How would he find out if there is a problem? Click on every pod?

**Comment by maciaszczykm** [comment]
> Also, a pod listing is comparable to kubectl get pods and pod details is comparable to kubectl describe

@cheld Yes, this was our assumption AFAIR. This issue is connected to list view, because detail view seems to be okay.

> I can add events support for pods so we can check them for errors as we do in other resources because implementation of #1248 can take some time.

It seems to be good solution IMO. 

Overall, I'd follow `kubectl` here.

**Comment by maciaszczykm** [comment]
CC @bryk

**Comment by batikanu** [comment]
so is it something like {kubectl get pods} **≈** {pod list view} and {kubectl describe pod} **≈** {pods detail view} ?

**Comment by floreks** [comment]
> @floreks Just imagine Bob, our administrator has a cluster with 100 pods (non very much). How would he find out if there is a problem? Click on every pod?

That's why I've proposed that:

>Solution for everything will be #1248. There will be available detailed information about containers, their statuses and events of the pod. Thanks to events we'll be able to also display errors on pod list page. I can add events support for pods so we can check them for errors as we do in other resources because implementation of #1248 can take some time.

It will be similar to example below with the exception that in this case status of the pod would be still running as stated in documented code
```
// PodRunning means the pod has been bound to a node and all of the containers have been started.
// At least one container is still running or is in the process of being restarted.
```
![zrzut ekranu z 2016-09-21 10-09-23](https://cloud.githubusercontent.com/assets/2285385/18702774/88898590-7fe3-11e6-8586-42650dbd7972.png)

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes/issues/12143#issuecomment-160728358

**Comment by bryk** [comment]
@batikanu 
>I made some research about it. I think we can reflect the logic of the resource printer in kubectl. I can take it if you approve the solution.

We already include kubectl code, so can you maybe work on this and use the function? 

> so is it something like {kubectl get pods} ≈ {pod list view} and {kubectl describe pod} ≈ {pods detail view} ?

Yes, exactly.

**Comment by IanLewis** [comment]
@bryk 

I'm familiar with how kubectl shows the statuses. I could take this as a way to get started on dashboard dev.

**Comment by batikanu** [comment]
@bryk sure I can implement it as I suggested by reusing kubectl. @lanLewis I have other open pull requests at the moment to complete. In this case, I can pass it to you if you want to use this time gap to implement a quick solution until I start to it.

**Comment by IanLewis** [comment]
@batikanu Yah. I don't think it should be too much of a problem. Why don't you pass it off to me. I would appreciate a review once I cut a PR though.

**Comment by batikanu** [comment]
@lanlewis great feel free to get it.

**Comment by IanLewis** [comment]
The code to display the status the way that kubectl does is buried in a non-public function [printPodBase](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L669) so we can't use it as is. I think that for now I will just copy the logic for how it determines the "Reason" that gets printed by kubectl.

**Comment by IanLewis** [comment]
Just to be clear, I plan to display the same reason string as kubectl does, and not "crashed" as the OP expected.

**Comment by cheld** [comment]
Original string is ok. It will not be localized, but I think we can live with that.

I am not so happy with coping code. Long term goal seems to move logic to server (https://github.com/kubernetes/kubernetes/issues/29472). Any other idea for short term?

**Comment by IanLewis** [comment]
I don't think that copying code is necessarily bad but, long term, yes, we will want to make use of the printers API if it gets included on the server.

We may also want to look at localized names for the error messages.
