### ISSUE TITLE
List of images not shown on the details page

### ISSUE THREAD

**Issue by Trane9991** [kubernetes/dashboard#1126]
##### Environment
```
Dashboard version: Default for GKE 1.3.4
Kubernetes version: GKE 1.3.4
Operating system: Debian for GKE 1.3.4
Node.js version: Default for GKE 1.3.4
Go version: Default for GKE 1.3.4
```

##### Steps to reproduce
Create pod with 5 containers in it

##### Observed result
List of images shown on the Dashboard page, but list of images is empty on the Details page for RC or Pod

##### Expected result
Details page for RC or Pod should show list of 5 images

##### Comments
![elk-1](https://cloud.githubusercontent.com/assets/9948629/17662134/3438328e-62ec-11e6-9b41-1ab930cd992f.png)
![elk-2](https://cloud.githubusercontent.com/assets/9948629/17662133/34375c2e-62ec-11e6-9121-73ac6179c0a9.png)
![elk-3](https://cloud.githubusercontent.com/assets/9948629/17662135/34394ebc-62ec-11e6-8e3d-639f673a288a.png)

**Comment by bryk** [comment]
@digitalfishpond Can you investigate why is that?

**Comment by digitalfishpond** [comment]
Working on this now

**Comment by digitalfishpond** [comment]
@Trane9991 , are you still able to reproduce with latest code? I got the following results when creating a pod with 5 containers:

![selection_013](https://cloud.githubusercontent.com/assets/13361549/17766156/07dcfd92-652a-11e6-85db-206ad56810d3.jpg)
![selection_011](https://cloud.githubusercontent.com/assets/13361549/17766157/0a4fa4ee-652a-11e6-9f2a-2155b1ec449f.jpg)
![selection_012](https://cloud.githubusercontent.com/assets/13361549/17766160/0caad290-652a-11e6-81b9-2cbcba8dc837.jpg)

**Comment by maciaszczykm** [comment]
@digitalfishpond I think, that @Trane9991 is using version `Default for GKE 1.3.4`. It's not the latest version of the code. I assume it should be fixed when we'll release.

**Comment by digitalfishpond** [comment]
Just tested again using elasicsearch, logstash and kibana images as in @Trane9991 's example, and I have the same successful result, so I will close for now as this is already fixed in the next release. In the meantime, thank you @Trane9991 for reporting this!
