### ISSUE TITLE
new component for selecting pods status

### ISSUE THREAD

**Issue by Tokkiu** [kubernetes/dashboard#1127]
##### Environment

```
Dashboard version:     1.1.0
Kubernetes version:     
Operating system:     linux/amd64
Node.js version:     5.12.0
Go version:      1.6.2 
```

##### Steps to reproduce

1.i has newed a component called podstatusselect,besides namesapceselect on html,just like namespaceselect.
2.when selecting a status,i want the podcardlist to just show the status i selected.
3.i set a func in podstatusselect.service to expose the selected status
4.i set a $scope.$watch in podcardlist component to get the selected status
5.i think when i select a status,the $scope.$watch will get the status,so i can just show the pod i need

##### Observed result

but when i select the status,$watch is not executed,so i can't do sth on the list.

##### Expected result

i need when i select the status,the podcardlist component can be informed so i can do sth on the html

**Comment by cheld** [comment]
If I understand you correctly you would like to contribute, but have some troubles to get started?

Please have a look at the design mockups to make sure you enhancement fits to the overall picture:

https://github.com/kubernetes/dashboard/tree/master/docs/design/mockups/23-03-2016-scale-and-navigation

**Comment by maciaszczykm** [comment]
AFAIK @Tokkiu uses Dashboard to manage his Kubernetes cluster in his company. He'd like to perform some code changes but only within his fork. He had contacted with me in previous week and I've told him to describe his issue here. Generally the most specific part was:

> The question goes : we can't find where u define your own directive ?
just like how 
"<kd-namespace-select></kd-namespace-select>"   -  -  -/frontend/chrome/chrome.html
binded with module 
common.namespace?    -    -  - /frontend/common/namespace/namespace_module.js

**Comment by Tokkiu** [comment]
yes,i want to do some change on the code,now my problem is how to communicate between two components?I tried the $boardcast and factory even service,maybe initial communication works,
but i want a component to inform another component,so how should i do?

**Comment by bryk** [comment]
Closing as stale.
