### ISSUE TITLE
Namespace column in resource lists is broken

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1131]
Something is wrong when I look at details of a RC:

![selection_107](https://cloud.githubusercontent.com/assets/1159999/17729622/5aa7946c-6465-11e6-892a-f76f1ebc9558.png)

@digitalfishpond Can you fix this?

**Comment by digitalfishpond** [comment]
yes, I'll check.

**Comment by bryk** [comment]
I think this is only for pod lists.

**Comment by digitalfishpond** [comment]
it seems to be for any resource in RC details: 
![selection_010](https://cloud.githubusercontent.com/assets/13361549/17733065/1d3a3570-6475-11e6-99f5-1e8cac886cd8.jpg)

**Comment by digitalfishpond** [comment]
Just looking into it now - also interesting that my view leaves space in the column whereas yours doesn't. Are you using Safari?

**Comment by bryk** [comment]
I'm using chrome.

**Comment by digitalfishpond** [comment]
Ok, solved the Services one (typo), now checking pods (not seeing any typos yet)

**Comment by digitalfishpond** [comment]
fixed with #1133

**Comment by bryk** [comment]
Awesome, thanks!
