### ISSUE TITLE
Navigation Design and Content for Individual Resource

### ISSUE THREAD

**Issue by Lukenickerson** [kubernetes/dashboard#1137]
Issues https://github.com/kubernetes/dashboard/issues/908 and https://github.com/kubernetes/dashboard/issues/908 handle the left-hand navigation, and https://github.com/kubernetes/dashboard/issues/1015 handles the 2nd-level action bar / title / breadcrumb. This issue is focused on the navigation when a user has worked their way down to a specific resource (e.g., a single pod).

The [navigation and scale design doc](https://github.com/kubernetes/dashboard/blob/6c70845df71c9514097b5936fff743648b692b3f/docs/design/navigation-and-scale.md) shows there being 2-4 **tabs**: Overview, Events, and in some mockups Logs, and Exec. 

Open questions for discussion/research:
- When viewing a resource, what does a user most care about? Possibly tied to issue https://github.com/kubernetes/dashboard/issues/975. Can we get valuable information from survey results (see [blog post](http://blog.kubernetes.io/2016/08/sig-apps-running-apps-in-kubernetes.html) and [survey data](https://docs.google.com/spreadsheets/d/1lIRRYbnDHWcGw3aRnd2THicHAoA8SS_vdUD-F4oB-R8/edit#gid=325530331))?
- Once we determine what the user wants to see: Are tabs the best navigation or is there something else?
- Is the "Exec" functionality still planned or will we just provide tips for using the CLI - https://github.com/kubernetes/dashboard/issues/959 ? 
- Which resources need to see which content (overview, events, logs)?
- Is there a better way to summarize or display log and event data?
- If we do end up using tabs, is there a better word for "Overview"? (It's already used for two other things -- see https://github.com/kubernetes/dashboard/issues/1068 -- so [is overloaded](https://github.com/kubernetes/dashboard/issues/1068#issuecomment-237551944); _"[I think that we can (and should) remove the Overview from resource detail page.](https://github.com/kubernetes/dashboard/issues/1068#issuecomment-238532112)"_).

**Comment by romlein** [comment]
[This design](https://invis.io/XZ7RITOQD#/182527560_Two_Bars_-_768_-_Breadcrumb_Tabs) is a solution Keith and I have been discussing for a tertiary navigation level.

**Comment by floreks** [comment]
I like this design a lot! Few things to consider:

* Should third level navigation bar be visible for all pages or only detail pages? For UX consistency it should be visible at all times but I don't see any tab that we could display on list pages and displaying only 1 tab would be an imo an overkill.

* "Overview" tab on details page. I agree that it should be changed once we introduce "Overview Page". Maybe something like "Properties", "Report", "General". Just throwing some ideas.

* Moving hamburger menu to second level toolbar. IMHO it feels that this toolbar is tied to page content and may change with it. Nav menu on the other side is global. Should it be moved to top toolbar?

As for the coloring I generally like it. Different shades of blue look nice. I'm not sure if "Workloads" link color should differ from other links color in dashboard. It's a bit inconsistent and confusing for me.

**Comment by maciaszczykm** [comment]
> Should third level navigation bar be visible for all pages or only detail pages? For UX consistency it should be visible at all times but I don't see any tab that we could display on list pages and displaying only 1 tab would be an imo an overkill.

It's only displayed when there is more than one tab, so on details pages at the moment.

> "Overview" tab on details page. I agree that it should be changed once we introduce "Overview Page". Maybe something like "Properties", "Report", "General". Just throwing some ideas.

+ `Details`

> Moving hamburger menu to second level toolbar. IMHO it feels that this toolbar is tied to page content and may change with it. Nav menu on the other side is global. Should it be moved to top toolbar?

I'd keep it near breadcrumbs, as both components are connected to the navigation. It's hard to fit it near Kubernetes' logo.

**Comment by romlein** [comment]
Thanks for the feedback @maciaszczykm & @floreks!

>Should third level navigation bar be visible for all pages or only detail pages? For UX consistency it should be visible at all times but I don't see any tab that we could display on list pages and displaying only 1 tab would be an imo an overkill.

As @maciaszczykm mentioned, it would only be shown when there's more than one tertiary-level page to be displayed. It's not a UX issue to show tabs on some pages and not on others (e.g. Google+)

>Moving hamburger menu to second level toolbar.

On recommendation of Google Cloud Platform UX designer Keith Guerin we've been thinking of the second bar as the main app bar, and the top bar as an addition that takes advantage of the extra screen real estate of desktop. For this reason – and if we're having the second bar be full-width – as is the Material spec, it makes more sense to include the menu icon in the second bar, so it's related to the side nav below it. I do agree that it's a bit odd the menu icon isn't in the top left, but I think showing the breadcrumb helps clarify. Thoughts?

**Comment by maciaszczykm** [comment]
Closing as stale.
