### ISSUE TITLE
is it possible to use keystone authentication to log in dashboard like basic auth?

### ISSUE THREAD

**Issue by Johnzinvalid** [kubernetes/dashboard#1138]
I have set kubernetes to authenticate with keystone to talk with an existing LDAP server and kubectl works fine, I have tried several group of username/password in LDAP but when I access https://masterIP:6443/ui the browser returns Unauthorized like authenticate with Token, so is it possible to authenticate dashboard with keystone?

**Comment by bryk** [comment]
@mlbiam recently did OICD setup in https://github.com/kubernetes/dashboard/issues/964#issuecomment-240496867. Does this help?

**Comment by Johnzinvalid** [comment]
@bryk yes, mlbiam's architecture is worth to take a try. I will close the issue.
