### ISSUE TITLE
Nodes view is not accessible easily

### ISSUE THREAD

**Issue by vishh** [kubernetes/dashboard#1139]
It is possible to access node information via pods. How can one access the list of nodes directly?
Cluster admins often care about nodes and it is imperative that nodes are a first class entity in the dashboard. Is the dashboard attempting to hide nodes into the background similar to k8s APIs?

cc @davidopp

**Comment by davidopp** [comment]
+1. We should have a direct link to some kind of "node view" from the main dashboard page, that shows you info about each node on a single page (clickable to drill down to the per-node view).

**Comment by bryk** [comment]
Yes, this is actually our P0 item that we work on now. The design is in https://github.com/kubernetes/dashboard/issues/908, so I'll close this as a duplicate. 

1. Our recent designs to see how this will look like: https://projects.invisionapp.com/share/3C8BDK9ZD#/screens
2. You can access a view that shows all nodes manually via: http(s)://master_ip/ui#/node

**Comment by bryk** [comment]
And yeah, this will be available for 1.4.

**Comment by davidopp** [comment]
Great!

**Comment by vishh** [comment]
The new UI looks awesome. Waiting for the changes to land! Thanks!
