### ISSUE TITLE
Services section in RC detail is broken

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1140]
See

![selection_111](https://cloud.githubusercontent.com/assets/1159999/17808917/309a5dd0-6613-11e6-8481-8fbe9801e31d.png)

**Comment by floreks** [comment]
Any steps how to reproduce?

**Comment by bryk** [comment]
Oh, yeah. I already fixed this in https://github.com/kubernetes/dashboard/pull/1154
