### ISSUE TITLE
Service objects are not shown in dashboard

### ISSUE THREAD

**Issue by aaskey** [kubernetes/dashboard#1148]
#### Issue details
The dashboard shows objects such as Deployments, RS, RC, and Pods, but there is no Service objects. It would be nice to be able to show Service objects. 

##### Environment
GCE

```
Dashboard version: 1.1.1
Kubernetes version: 1.3.5
```

**Comment by floreks** [comment]
Option to list services is already added with the prototype of the nav bar (#1141) on master. It will be available in next release.
