### ISSUE TITLE
how to config dashboard with https

### ISSUE THREAD

**Issue by chowyu08** [kubernetes/dashboard#1162]
Dashboard version:  1.1
Kubernetes version: 1.3.6
Operating system: ubuntu14.04
Go version:1.6.2
 Ideploy kubernetes and dashboard  as http://kubernetes.io/docs/getting-started-guides/ubuntu/
I can access the dashboard  http://master-ip:8080/  
![image](https://cloud.githubusercontent.com/assets/16483518/18073221/d001a0be-6e96-11e6-9d12-fdf56d685075.png)

bur when I access https://master-ip:6443/  ,return "Unauthorized"
![image](https://cloud.githubusercontent.com/assets/16483518/18073229/df9c3782-6e96-11e6-9ce6-132c39f8195e.png)

why?

**Comment by bryk** [comment]
Dashboard has nothing to do here. It is your master server that is not configured properly. Make sure you follow the ubuntu guide correctly or file bugs to the documentation. 

Best,
Piotr

**Comment by maciaszczykm** [comment]
Closing as stale.
