### ISSUE TITLE
Missing pod list title in job details page.

### ISSUE THREAD

**Issue by PiotrDabkowski** [kubernetes/dashboard#1166]
Title is missing:

![jobpodlabelbug](https://cloud.githubusercontent.com/assets/4052440/18086837/2f7b5d6c-6eb2-11e6-8aa0-fa291de78509.png)

**Comment by bryk** [comment]
Can you fix this issue?

**Comment by PiotrDabkowski** [comment]
Sure

**Comment by floreks** [comment]
Controller reference in `src/app/frontend/jobdetail/jobdetail.html:20` is wrong. Just change `$ctrl` to `ctrl`. :)
