### ISSUE TITLE
Pod logs are available from list view, but not detail view

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1174]
#### Issue details
```
Dashboard version: 1.4.0-beta1
Kubernetes version: 1.4.0-alpha.3
Operating system: ubuntu
Node.js version: n/a
Go version: n/a
```

##### Steps to reproduce
Go to a view that shows a list of pods. Note there is a log button to see the logs from the pod.

Go to a pod detail page. There is no button to get to logs.

**Comment by bryk** [comment]
Thanks for reporting. This is an omission. We'll add the link soon.

**Comment by batikanu** [comment]
@bryk would you prefer to have logs icon like this?
![podetaillogs](https://cloud.githubusercontent.com/assets/11628279/18248614/abd1152a-7379-11e6-8651-114aa1a50583.png)

**Comment by bryk** [comment]
In the details view we should have an icon + text or only text. Maybe place it below "Status"? 

cc @romlein

**Comment by maciaszczykm** [comment]
@batikanu It's hard to understand what this icon represents. IMO we definitely need to add label nearby or use pure text without icon. I'd also move it to another location.

**Comment by batikanu** [comment]
do you mean just putting a Label as a link under Status?

**Comment by maciaszczykm** [comment]
@batikanu It's a bit more descriptive now, but if we are putting it here, then I'd go for something like`Logs: ...`, like it's done for node. 

However, since we have logs for every container, not for all of them, shouldn't we move this link to `Containers` section and add a link to every container? For example `Click here to see logs`. It would be much more intuitive I think.

**Comment by floreks** [comment]
I'd go witch @maciaszczykm proposal and make per container logs link. Another option is to add logs link near container name i.e. `commandpod [See logs]`

**Comment by bryk** [comment]
Brainstorming: how about adding the link both to containers and the pod? We have a link in the list page and I'd like to have a corresponding one here. 

And the idea of links in container sections is really nice.

**Comment by maciaszczykm** [comment]
@bryk SGTM.

**Comment by batikanu** [comment]
@bryk do you mean using the same duplicated link in both pod and container section on the same page?

**Comment by maciaszczykm** [comment]
@batikanu For container sections you need to use links to logs of specific container, without any sub-menu etc.
