### ISSUE TITLE
Pod Detail Page omits the containers' commands

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1180]
```
Dashboard version: 1.4.0-beta1
Kubernetes version: 1.4.0-alpha.3
Operating system: ubuntu
Node.js version: n/a
Go version: n/a
```

##### Steps to reproduce
Pod Detail > Containers

See:
* Image
* Env Vars

Don't see:
* Command

It'd be nice to have the Pod Detail view show the command as well.

**Comment by bryk** [comment]
@batikanu Can you take this once done with PVCs?

**Comment by batikanu** [comment]
Sure I'll check it

**Comment by batikanu** [comment]
Shall we display command as a whole command including args or both separated?

**Comment by bryk** [comment]
Do this the same way kubectl does. We aim for consistency here.
