### ISSUE TITLE
Services could link to the api service proxy

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1181]
```
Dashboard version: 1.4.0-beta1
Kubernetes version: 1.4.0-alpha.3
Operating system: ubuntu
Node.js version: n/a
Go version: n/a
```

Just a nice to have feature req:

<img width="1131" alt="screen shot 2016-08-31 at 4 15 35 pm" src="https://cloud.githubusercontent.com/assets/327028/18149659/5deaa6a0-6f96-11e6-81cd-bfd3792094cd.png">

It would be nice if `dashboard` could detect that I'm accessing it through the service proxy and then offer to make these internal endpoints hyperlinks as well.

**Comment by bryk** [comment]
That's good suggestion. We though about it in the past, but then realized that it is hard to detect whether you're running behind the proxy. Will take a closer look at this after our next release.

**Comment by maciaszczykm** [comment]
Another potential issue here is, that proxy might not allow enter all of the services. Number of them can be filtered or inaccessible through proxy. We'll have to investigate it deeper to find out if it's possible to implement.

**Comment by colemickens** [comment]
"filtered" or "inaccessible" ?

The only thing I can think of is cases where the user running `kubectl proxy` has limited RBAC roles.

(This brings up the point  that the dashboard is basically bypassing RBAC in many cases).

**Comment by maciaszczykm** [comment]
@colemickens In case of `kubectl proxy --api-prefix=/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` usage, only `http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` should be served.

**Comment by colemickens** [comment]
Oh thanks for explaining, I didn't know that!

**Comment by maciaszczykm** [comment]
No problem. It's not so clearly described in `kubectl proxy --help`...

**Comment by cheld** [comment]
Relates to
https://github.com/kubernetes/dashboard/pull/2249

**Comment by maciaszczykm** [comment]
As it was already said it is hard to detect if the proxy is used and if given service is available. I will close it until we will find a good solution.
