### ISSUE TITLE
[v1.4.0-beta1] Maxing CPU and bringing down cluster. 

### ISSUE THREAD

**Issue by Salakar** [kubernetes/dashboard#1183]
#### Issue details

Dashboard deployment is maxing out CPU on all cluster nodes and grinding the cluster to a halt as they're all maxed out on CPU.

##### Environment

```
Dashboard version: v1.4.0-beta1
Kubernetes version:  1.3.2
Operating system: -
Node.js version: 6.4
Go version:
```

##### Steps to reproduce

- Deploy dashboard via kubectl command on readme.

##### Observed result

Think this screen best describes it:
![image](https://cloud.githubusercontent.com/assets/5347038/18198455/07d02baa-70f4-11e6-8759-231c3ff6691f.png)

Deployed it at 11am, as you can see the CPU started maxing out on each node - by yesterday the page for the dashboard wouldn't load, gets stuck on the spinner and then spamming reload by itself.

Deleted the deployment this morning around 9:45am:
![image](https://cloud.githubusercontent.com/assets/5347038/18198510/4b4dfe34-70f4-11e6-99b5-c9fddf9bdfb4.png)

CPU on all nodes returned to normal.

Worth noting that it seems to have got worse overnight (when no-one was around to have the dashboard page open) so not sure it's self DDOS related - logs in my other comment below indicate heavy reboot loops and sometimes log an error about DNS and localhost:8080?

##### Comments

Not sure how to provide any debug info for this - so please advise, kinda a big issue considering it took down our entire cluster.

**Comment by bryk** [comment]
Yes, we had this bug where page would get stuck in a reload-loop, causing to DDoS your master. But this has been fixed already. 

How about we do beta2 release today and send it you to verify that this does not happen again?

**Comment by bryk** [comment]
To debug this, can you post logs of the dashboard pod? Let me know if you cannot find them

**Comment by Salakar** [comment]
@bryk all i can see log wise is reboot loops:

![image](https://cloud.githubusercontent.com/assets/5347038/18205342/66cd1f8a-7119-11e6-806f-5f5f716ccba0.png)

**Comment by Salakar** [comment]
And occasionally logs:

```
I0901 13:24:53.593250 1 dns.go:660] DNS Record:&{kubernetes-dashboard.kube-system.svc.cluster.local. 0 10 10 false 30 0 }, hash:529066a8
```

**Comment by bryk** [comment]
Oh, so that's something new. Are you on https://kubernetes.slack.com/messages/sig-ui?

**Comment by Salakar** [comment]
![image](https://cloud.githubusercontent.com/assets/5347038/18205680/2c3d7b24-711b-11e6-93ec-e6b918b2eb10.png)

Also this pops up sometimes too.

**Comment by bryk** [comment]
Interesting. I've got a 1.3.5 cluster on GKE and was able to deploy the UI. Is there anything specific about your cluster? What's your heapster version?

**Comment by Salakar** [comment]
Discussed this with @bryk on slack - turns out this deployment was conflicting with the default dashboard that GCE deploys - I deleted this default dashboard, service and deployment but it just gets re-created on it's own - so it conflicts with the beta version I deployed - it tries to run the two side by side and blows up.

The only way to get beta on a GCE managed cluster is to deploy the `canary.yml` version as this doesn't conflict with the pre-setup GCE one. Guess it just needs noting somewhere that manual deployments of the dashboard on a GCE cluster is bad, unless it's canary.

**Comment by floreks** [comment]
Do you have any addons management options in GCE or can you access kubernetes master node?

Dashboard is brought back because it's installed as an addon in `/etc/kubernetes/addons` (default location).

**Comment by cheld** [comment]
Actually, the it is the value "cluster-service" in the yaml definition in combination with addon manager

**Comment by bryk** [comment]
So I created a brand new 1.3.*6* cluster in GKE. Then deployed Dashboard UI:
```
 kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.4.0-beta1/src/deploy/kubernetes-dashboard.yaml
deployment "kubernetes-dashboard" created
Error from server: error when creating "https://raw.githubusercontent.com/kubernetes/dashboard/v1.4.0-beta1/src/deploy/kubernetes-dashboard.yaml": services "kubernetes-dashboard" already exists
```

No errors or bad signs. I can see easily the dashboard via `http://localhost:8001/api/v1/proxy/namespaces/kube-system/pods/kubernetes-dashboard-997876578-03mzo/#/deployment?namespace=kube-system` 

My best guess now is that this is a problem with Deployment resource. We use it for config in `src/deploy/kubernetes-dashboard.yaml` and it is in beta now. I see many bug reports and fixes on it passing by. 

In production we use RCs to manage Dashboard UI, so this should not be a problem.

**Comment by Salakar** [comment]
When i saw the dashboard already exists error - I deleted the existing deployment and service then immediately after re-ran the create. Was not aware that even if you delete the deployment and service that the GKE one automatically gets re-deployed.

**Comment by floreks** [comment]
Should be fixed now. Can we close?
