### ISSUE TITLE
Disable "Deploy" / "Upload" button until its criteria are met

### ISSUE THREAD

**Issue by romlein** [kubernetes/dashboard#1209]
The "Deploy" / "Upload" button should be disabled until a user has correctly input the required fields before appearing clickable.
<img width="597" alt="screen shot 2016-09-09 at 11 44 49 am" src="https://cloud.githubusercontent.com/assets/5114858/18393409/39c24e42-7683-11e6-9be9-6bae98e961de.png">

**Comment by cheld** [comment]
We intentionally do not disable the buttons, but show validation messages. 

In my understanding a common pattern see e.g. 

https://accounts.google.com/SignUp?service=mail&continue=http%3A%2F%2Fmail.google.com%2Fmail%2Fe-11-147333d73d2544cc5eb6b7b4950b6ead-ab93933ef015ad41ae75c07c5c3b74ba2070a088

**Comment by digitalfishpond** [comment]
Yes, This way we can give hints as to how to get the form into a state that can be deployed.

**Comment by bryk** [comment]
@romlein What should be error handling if we disable button on non-met criteria? Currently the algorithm is that you have no errors until you click deploy. And then all errors are continuously updated. That's library default behavior.

**Comment by romlein** [comment]
@cheld ah, OK: I wasn't aware of that pattern instance in other Google products. Thank you! In light of that I think we should leave as is. Closing this issue.
