### ISSUE TITLE
Next iteration of i18n framework

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1217]
I have some thoughts on our i18n framework. It is generally super cool, but has some issues around developer productivity. I.e., it significantly slows me down when coding. 

How about enhancing the framework so that we keep 90% of our texts in the html files, never touching controllers.

Rough idea:
1. In templates we write text to be translated in `[[]]` brackets. Syntax is: `[[Hello world | Text that appears on initial page load]]`
2. This is all put in .html templates. E.g, my file named hello.html would be:

``` html
<div>
  [[Hello world | Text that appears on initial page load]]
</div>
```
1. Then, during build, this file is processed into hello.html.js, with the following content:

``` js

/** @desc Text that appears on initial page load */
const MSG_HELLO_WORLD = 'Hello World';

angular.module(['app']).config(($templateCache) => {
$templateCache.put('path/to/file/hello.html', <div>${MSG_HELLO_WORLD}</div>`); 
});
```
1. Then this file is passed to normal build pipeline and compiled

Pros: I write text in templates and don't have to bloat my controllers. Harder to make mistakes.

**Comment by bryk** [comment]
@batikanu @cheld What do you think?

**Comment by cheld** [comment]
@taimir

**Comment by taimir** [comment]
I like the idea, here are a couple of possible issues that come to mind:
* generated `MSG_` variable names - are we going to use the original `html` file name as some sort of prefix for the `MSG_` vars in the generated `js` file?  
* this approach would lead to leaving out the specific variable suffixes (e.g. LABEL, TITLE, ACTION, etc.) that we've used so far, as those cannot be easily extracted from the context. Personally, I bet those are not 100% required, given that the `@desc` fields are filled in properly, but that's just my opinion.
* at a first glance, `placeholder` definitions (`{$ ... }` syntax) might be a bit tricky to implement that way. Should those specific messages stay at their current place, i.e. in the controllers?

**Comment by bryk** [comment]
> generated MSG_ variable names - are we going to use the original html file name as some sort of prefix for the MSG_ vars in the generated js file? This mostly concerns variable name clashes ...

Yep, we can do this. Or include generates JSes in the module system. E.g., import all generated JSes from one, generated, file. This would prevent from clashes as JS modules are file-scoped. 

> this approach would lead to leaving out the specific variable suffixes (e.g. LABEL, TITLE, ACTION, etc.) that we've used so far, as those cannot be easily extracted from the context. Personally, I bet those are not 100% required, given that the @desc fields are filled in properly, but that's just my opinion.

Thats correct. I've been using similar system to proposed here for years. Nobody complains as everything is in the `@desc` part. 

> at a first glance, placeholder definitions ({$ ... } syntax) might be a bit tricky to implement that way. Should those specific messages stay at their current place, i.e. in the controllers?

Yes. If a message is complicated, it can stay in the controller. But we can have bindings in the messages this way, which is super cool. E.g., `<div>[[Hey {{$ctrl.user.name}}, how are you | Welcome message to the user</div>`. Since this is all translated during compile time, angular bindings and any arbitrary HTML just works. As opposed to current state where we have to write dozens of lines of code to pass variables around.

**Comment by taimir** [comment]
> Yes. If a message is complicated, it can stay in the controller. But we can have bindings in the messages this way, which is super cool. E.g., <div>[[Hey {{$ctrl.user.name}}, how are you?| Welcome message to the user]]</div>. Since this is all translated during compile time, angular bindings and any arbitrary HTML just works. As opposed to current state where we have to write dozens of lines of code to pass variables around.

Agreed, that would be quire more natural than what's currently supported.

**Comment by digitalfishpond** [comment]
Can this be closed now?

**Comment by bryk** [comment]
Yes, I think so.
