### ISSUE TITLE
YAML browser great; YAML editor not so helpful

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1221]
##### Environment

```
Dashboard version:3230343cf811574bd369bd058f6d9c331843e69a
Kubernetes version: 1.4.0-beta something
Operating system: n/a
Node.js version: n/a
Go version: n/a
```
##### Steps to reproduce
1. Use the YAML browser on the "Edit" window.
##### Observed result
1. The YAML browser is convenient for navigating the YAML.
2. It very much hinders making non-trivial changes to the YAML - it requires so much clicking when I really just want to copy/paste an existing section and swap in the new values.

It would be nice if I could choose to switch between a plain text box and the structured browser.

**Comment by bryk** [comment]
Totally agree here. YAML editor needs more work, especially for the copy/paste use case which now is purely frustrating. 

cc @romlein

**Comment by bryk** [comment]
See https://github.com/kubernetes/dashboard/issues/922 for description of problems when editing a configmap/secret.

**Comment by naisanza** [comment]
@bryk also, it would be very handy if we could copy the yaml and paste it when creating a new container instead of having to upload it. I'll probably create a new request for this

**Comment by bryk** [comment]
Yep, go ahead :)

**Comment by maciaszczykm** [comment]
@colemickens @edouardKaiser @naisanza and all other people waiting for improvements, it is improved in 1.6.1 and after images will be available we are open for any feedback. Does new way of copy/paste work for you or we need to make further improvements at the moment?

**Comment by edouardKaiser** [comment]
Can't wait to try 1.6.1 and give feedback !

**Comment by maciaszczykm** [comment]
@edouardKaiser https://github.com/kubernetes/dashboard/releases/tag/v1.6.1 is out.

**Comment by edouardKaiser** [comment]
@maciaszczykm copy is nice, but how do I paste back in the editor?

Also, it's still very hard to edit a ConfigMap through the YAML editor, because of the CR control character, even if I use copy:

![image](https://cloud.githubusercontent.com/assets/7731641/26179188/76be1a96-3ba5-11e7-93f3-3696dcca1e62.png)

**Comment by floreks** [comment]
Right now we only have option to copy from editor. We'll be working on adding paste option also.

**Comment by sylr** [comment]
A view with a simple textarea of the yaml data for copy/pasting would be nice.

**Comment by maciaszczykm** [comment]
@sylr We already have copy button, but we are missing paste. We are a bit short of developers right now and our main focus is on security and login page. Perhaps you could help to implement paste feature?

**Comment by skyscooby** [comment]
Would it be possible to have a Copy as YAML button? The default (copy as JSON) is more difficult to edit manually than the yaml is.. and since the editor brings up YAML it would be more consistent if the COPY button copied to the clipboard as yaml.. but both options could be usable..

**Comment by floreks** [comment]
Should be possible. We'll take a look at that.

**Comment by maciaszczykm** [comment]
We have switched YAML editor dependency and set `code` instead of `tree` mode. It should fix most of the problems, as standard text editor operations work right now.
