### ISSUE TITLE
Messages consistency

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1223]
There still is some inconsistency across Dashboard's messages. Take a look on following screenshot:

![](https://cloud.githubusercontent.com/assets/1159999/18435351/d9e01d98-78f2-11e6-9d69-f149abdf7f9c.png)

Message title shouldn't end with dot, but following message should. Like in Inbox. Now it's inconsistent.

Thing to consider is naming of Kubernetes' resources. Are we using capital letters everywhere? Do we consider resources like event, endpoint etc. as Kubernetes'? We should decide it here and then fix all messages.

**Comment by bryk** [comment]
@maciaszczykm Can you document guidelines on how we should write messages? 

I can give some input, based on my experience with other UI projects. E.g., when to use sentences, when to end with dot, etc. 

cc @Lukenickerson @romlein

**Comment by maciaszczykm** [comment]
@bryk Sure, let's continue discussion and I'll create summary of it.

**Comment by maciaszczykm** [comment]
I'll create short document with guidelines for the repository and after that maybe also I will be able to refactor existing messages.

**Comment by maciaszczykm** [comment]
The next step is to review all messages across the app and fix all issues. We can also apply new localization framework everywhere.

**Comment by bryk** [comment]
@digitalfishpond Can you go over this? To apply i18n framework and go over messages?

**Comment by digitalfishpond** [comment]
Yep, it's what I'm currently doing :)
