### ISSUE TITLE
Remove unused middleellipsis code

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#1224]
I'm creating issue so we won't forget about that. :)

**Comment by bryk** [comment]
Where is the code? I think I removed it :)

**Comment by floreks** [comment]
I must have been on some older branch then. It's cleaned up on master. :) Closing.

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/tree/master/src/app/frontend/common/components/middleellipsis

**Comment by floreks** [comment]
It's actually more a refactor because code is still there but only acts as a wrapper. Tooltip is not displayed.

**Comment by bryk** [comment]
How about we make it click-to-expand solution? E.g., you can click on it to see it fully. Of course, this does not apply to all cases, but in tables we can (and should) do this.

**Comment by floreks** [comment]
Sounds good. If we can easily do it then I say we should go for it.

**Comment by floreks** [comment]
We are now using css based middleellipsis that is wrapped in a component. Let's track any updates from #2048.
