### ISSUE TITLE
Current namespace is rendered in Roboto Mono

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1234]
##### Environment
```
Dashboard version: 95efdf3d699a102c4c7ce844af2e1cfc9f255abd
```

Not sure if this is intentional:

The text for the currently selected namespace is rendered in "Roboto Mono Medium" rather than some variant of "Roboto Sans" as I might've expected.

![2016-09-14-143641_1443x953_scrot](https://cloud.githubusercontent.com/assets/327028/18530987/d0c11bee-7a88-11e6-9c40-392bcffd9f6b.png)

**Comment by maciaszczykm** [comment]
It's intentional, so I'm closing it. Check discussion in https://github.com/kubernetes/dashboard/issues/908#issuecomment-245025906.

CC @bryk @romlein

**Comment by bryk** [comment]
Thanks @colemickens  for reporting the issue! If you think that this should be changed, please comment this in #908 and cc @romlein
