### ISSUE TITLE
Logs are rendered in Roboto rather than Roboto Mono

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1235]
##### Environment
```
Dashboard version: 95efdf3d699a102c4c7ce844af2e1cfc9f255abd
```

Similar to #1234, not sure if this is intentional or not. I'd *strongly* prefer that logs be shown in `Roboto Mono`.

![2016-09-14-144211_5760x1200_scrot](https://cloud.githubusercontent.com/assets/327028/18531192/da921c30-7a89-11e6-906d-a22dc68c0029.png)

**Comment by maciaszczykm** [comment]
Will be done soon in #1229.
