### ISSUE TITLE
HTML is not rendered for logs with colour attribute

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#1236]
#### Issue details

The logs with color attributes don't render anymore:

![image](https://cloud.githubusercontent.com/assets/7731641/18534280/bea13c7e-7b2c-11e6-8050-d419ad7eceaa.png)

```
Dashboard version: 1.4.0
```

**Comment by bryk** [comment]
@maciaszczykm Will you take care of this in your logs view overhaul PR?

**Comment by maciaszczykm** [comment]
@edouardKaiser Is there any public container returning colorful logs?

**Comment by floreks** [comment]
I guess it was intentional not to allow HTML rendering in logs. Check [this](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/logs/logs_controller.js#L187) out. Logs line is escaped not to contain any HTML markup. Allowing that could be a potential security issue.

**Comment by bryk** [comment]
@floreks I think that our pipeline is broken at some point, because: we first sanity the logs, then add <spans with colors> and finally render this as HTML. I think that "render as HTML" part does not work.

**Comment by edouardKaiser** [comment]
@maciaszczykm there is (keycloak docker image for example), but it's not really a matter of the public container. I can take a public container and change the logging configuration.

The dashboard used to display the colour, but we lost that feature (https://github.com/kubernetes/dashboard/commit/1602b5f61603045d35ce7171498dada1a4e9ceb9).

**Comment by floreks** [comment]
It seems that [this](https://github.com/kubernetes/dashboard/commit/1602b5f61603045d35ce7171498dada1a4e9ceb9#diff-5c9fe37bf019cf432650ac319231ac7dR20) was changed with [that](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/logs/logs.html#L49) and that caused logs line not to be rendered as html.

**Comment by maciaszczykm** [comment]
@edouardKaiser Yes, I'm aware of it. I'll restore it. Thanks for pointing out sample container.

**Comment by maciaszczykm** [comment]
> @edouardKaiser Yes, I'm aware of it. I'll restore it. Thanks for pointing out sample container.

It's done now in #1229. However, it won't accept HTML, but only ANSI tags (for example `\033[1;31m`)to change logs colors.
