### ISSUE TITLE
Tabulation and spacing is not respected when displaying log

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#1237]
#### Issue details

Logs should get displayed like this, respecting TAB and spaces:

![image](https://cloud.githubusercontent.com/assets/7731641/18534571/fa3b27ec-7b2f-11e6-8d55-80665389a402.png)

But it gets displayed like this now:

![image](https://cloud.githubusercontent.com/assets/7731641/18534578/09d97ae6-7b30-11e6-81f4-9ce841d8a64d.png)

```
Dashboard version: v1.4.0
```

**Comment by gillesdemey** [comment]
A simple `whitespace: pre-wrap` on `.kd-logs-element` should do the trick.
