### ISSUE TITLE
Use new GitHub features?

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1238]
We might be interested in using some of GitHub new features, especially new review system seems to look nicely:

https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

**Comment by bryk** [comment]
Yeah, I just noticed this and all looks super exciting. We could use GH review system instead of reviewable and track progress on the project boards.

**Comment by floreks** [comment]
Is it possible to add GH check instead of Reviewable for PRs?

**Comment by maciaszczykm** [comment]
@floreks Yes, it is:

> ![image](https://cloud.githubusercontent.com/assets/2823399/18547385/7810bad4-7b43-11e6-8e7e-9d607ed8f027.png)

**Comment by floreks** [comment]
Then I think we can try and use it instead of reviewable.

**Comment by cheld** [comment]
Have you seen the projects tab? Seems to be something like a trello/kanban-board

https://github.com/kubernetes/kubernetes/projects

**Comment by bryk** [comment]
Yes, the projects looks super cool. We could use it for tracking.

**Comment by bryk** [comment]
Let's try GitHub's review system for a while. I made a setting to require GH code review approval before merging. Please post here if this causes any problems. If not, let's review our feelings after a week.

**Comment by maciaszczykm** [comment]
I like this new system a lot mainly, because I can do everything on GitHub, without need to going to other places like Reviewable. Functionalities are very similar. One thing, that is missing seems to be marking files as reviewed. 

What about making few checks required? I know, that not everything is working as expected (issue with greenkeeper check, that didn't allowed to merge pull requests), but I think, that if there is possibility we should require at least 1 review to not forget about it. Moreover, setting up check on CI seems to be reasonable.

**Comment by bryk** [comment]
I'm for this :) Let's use github's review system and make it required for merges.

**Comment by maciaszczykm** [comment]
I see it's already done :) Closing issue.

**Comment by bryk** [comment]
Regarding projects tab: let's test it out for our planning in following weeks.
