### ISSUE TITLE
Empty graph card should be hidden

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#1240]
![zrzut ekranu z 2016-09-15 13-57-04](https://cloud.githubusercontent.com/assets/2285385/18549064/7af5196c-7b4c-11e6-816e-83f6431580c8.png)

Empty graph card should not be rendered in HTML if it's empty.

**Comment by bryk** [comment]
How is this possible? Can you fix the issue?

**Comment by floreks** [comment]
It can happen when we first start dashboard/heapster and there are no data yet to display graphs. For me it took few minutes to get the data and only `Memory usage` was displayed.

I'll take a look at that.

**Comment by bryk** [comment]
Awesome, thanks! Are you able to fix this today? If yes, I'll include this into 1.4 release fixup.

**Comment by floreks** [comment]
I'll try. This shouldn't take long to fix.
