### ISSUE TITLE
Option to skip validation on deployment

### ISSUE THREAD

**Issue by digitalfishpond** [kubernetes/dashboard#1245]
#### Issue details

When deploying a new app, the following message sometimes (correctly) appears:
`Deploying file has failed`
`error validating "daemonset.yaml.txt": error validating data: found invalid field request for v1.ResourceRequirements; if you choose to ignore these errors, turn validation off with --validate=false`
This is impossible to do via the UI. 
Would it be useful to have a checkbox 'Ignore Validation' which optionally adds `--validate=false` to the create request so that the deployment can still be made via the UI?

##### Steps to reproduce
For example, attempt to upload the YAML described [here](https://github.com/eBay/Kubernetes/blob/master/docs/design/daemon.md)

**Comment by bryk** [comment]
Why is this invalid, yet should be deployable?

**Comment by digitalfishpond** [comment]
The majority of the example yaml files from Kubernetes' docs result in the same validation error message. Kubectl offers the feature to turn off validation, so I was thinking that maybe we'd want Dashboard to do so too. @floreks made a suggestion to not add a checkbox, but rather a 'deploy anyway' button on the error dialog, which I like.

**Comment by bryk** [comment]
Can something wrong happen if we always disable validation?

**Comment by digitalfishpond** [comment]
For sure, I mean validation is there for a reason, but if kubectl enables the option, shouldn't Dashboard too, particularly since the message currently points the user to this very option for which he/she currently has to revert to kubectl? You definitely wouldn't want to permanently disable validation, which is why @floreks ' solution seems like a nice idea to me...?

**Comment by bryk** [comment]
Yep, I like @floreks' idea :)
