### ISSUE TITLE
Heapster metrics can go below 0

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1249]
Sometimes Heapster metrics go below 0. We should protect from this. 

See https://raw.githubusercontent.com/jskswamy/dashboard/b9b34f9a1a1bdc0178e00f8e035cbe129ed66db4/docs/dashboard-ui.png

**Comment by maciaszczykm** [comment]
+ plot sizes should be equal.

**Comment by floreks** [comment]
Fixed. Closing.
