### ISSUE TITLE
Menu open animation is absent

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1253]
#### Issue details

```
Dashboard version: 25ac3ea44152db7cd2d8b77f3aec2a9f605ed896
```

##### Steps to reproduce
1. Press hamburger button to collapse left nav.
2. Press hamburger button to uncollapse left nav.

##### Observed result
1. Collapse is animated.
2. Uncollapse is not animated.

##### Expected result
Both collapse and uncollapse should be animated.

##### Comments
Tested in dev versions of Chrome and Firefox and Edge.

**Comment by floreks** [comment]
I have also noticed that. It's possible that this is angular material bug.

On angular material page same issue occurs when you resize the page. Collapse is fine but uncollapse is not animated.

**Comment by bryk** [comment]
Known issue, but minor one. Thanks @colemickens for reporting! Will be fixed in the second iteration of the nav menu work :)

**Comment by romlein** [comment]
@bryk actually, side nav should animate off to the left of the page so the cards expand _toward_ it, not over it. See [Google Keep](https://keep.google.com) for example of desired functionality.

**Comment by bryk** [comment]
Ok, that I didn't know. The issue here was that there was no animation at all when closing and this resulted in 0.5s lag.

**Comment by colemickens** [comment]
This seems to be fixed...

**Comment by maciaszczykm** [comment]
@colemickens Thanks, you're right. Closing it.
