### ISSUE TITLE
A single page/view to see overview of nodes allocation

### ISSUE THREAD

**Issue by nvartolomei** [kubernetes/dashboard#1259]
I think it would be useful to have a page with overview of all nodes and % of ram, cpu allocated and available per node.

Is there any plans for this?

**Comment by cheld** [comment]
![nodes](https://cloud.githubusercontent.com/assets/7448799/18659632/1eea7a86-7f0c-11e6-8643-749d3f61e30d.png)

Like this? Have you tested latest version? It existed already for a while, but there was no menu entry.

**Comment by nvartolomei** [comment]
@cheld can we expose allocated resources there too? Maybe as gauge charts, one for cpu and another one for memory with 2 indicators, one for requests and another one for limits (gauge bars?).

So you can get overview for nodes without visiting each one.

ps. can we also expose CPU and Memory Available/Total on charts above?

**Comment by nvartolomei** [comment]
just to make it more clear what I'm looking for to see, do you have other ideas how to organize this information in another way?

![take1](https://cloud.githubusercontent.com/assets/543193/19417822/0c59a28a-93bf-11e6-8246-745e1809571b.jpg)

may look better
![2c362a3fb74c8798ab0300789ab5be1e](https://cloud.githubusercontent.com/assets/543193/19417843/800583b6-93bf-11e6-882e-8c6fbd9947ff.jpg)

**Comment by bryk** [comment]
> just to make it more clear what I'm looking for to see, do you have other ideas how to organize this information in another way?


Dod you try to put this information in the table? The rows may get higher, but this allows for support of 100s of nodes.

Do you have any code or demo for this?

@rf232 @romlein Any comments?

**Comment by nvartolomei** [comment]
@bryk actually the table may work better. No code demos :)

**Comment by bryk** [comment]
All right, thanks for this feature request! We'll put it in the backlog.
