### ISSUE TITLE
canary image is perpetually stale

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1262]
Similar to #1261, the `canary` tagged image is basically always stale.

Is there any CI that runs for this repo? It could easily build/tag/push up to GCR or some other registry.

In the meantime, I run [this script](https://gist.github.com/anonymous/4de04c7f3abac324472bfeeb3998db42) to update to `master` and replace the current running dashboard in my cluster. (The Deployment in my cluster is already set to use this image and I have the admission controller active that causes images to get pulled every time.)

**Comment by bryk** [comment]
So we really want to make this happen. We even had somebody working on it, but since then they went away.

We'll do this once we are done with the release, bug fixes, docs and stuff. It is needed for entire dev team since it eases development a lot.

Is this anything you can contribute to? Basically, we could push canaryies and per-PR images to docker hub. Should be easy to do on travis.

**Comment by bryk** [comment]
Previous report: https://github.com/kubernetes/dashboard/issues/1114

**Comment by colemickens** [comment]
I'm not sure how I'd go about it. I don't have credentials for the google_containers registry, or for the Travis instance used for this project. From my understanding of the build script, it should be basically a matter of a line or two added to the `.travis.yml`, assuming that docker/gcloud credentials can be put into place by someone with the right access.

**Comment by floreks** [comment]
I have some prototype prepared to release daily canary images using travis. We will try to configure it when @bryk will be back.

**Comment by bryk** [comment]
@floreks Do you have any PR for this? Or is is only the matter of creds?

**Comment by bryk** [comment]
All code is done here. The auto-push procedure has been working for a week now without problems. We now need to decide where to push the images. 

Should it be `gcr.io/google_containers`? Or maybe `docker.io/kubernetes/foo`? Or `docker.io/kubernetes-dashboard/foo`? 

I'm leaning towards `docker.io/kubernetes-dashboard/$foo-test` to make sure people don't treat this as an official release to use, but a test ground. 

What do you think?

**Comment by colemickens** [comment]
Doesn't matter to me as long as it's documented somewhere. Hosting it on docker and clearly labeling the image name as non-release-quality makes sense to me.

**Comment by rf232** [comment]
we currently push head images, see instructions here: https://github.com/kubernetes/dashboard/blob/master/docs/devel/head-releases.md
