### ISSUE TITLE
Roboto Mono Medium is an eyefull on the log page

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1263]
Left is "Roboto Mono Medium". Right is "Roboto Mono" (regular).

I find the "Medium" hard to read, as if it's bolded (AIUI, "medium" *is* a light bold when it comes to font faces).

Any chance others agree and it can be made to be `Roboto Mono` instead of `Roboto Mono Medium`?

![sketch 1](https://cloud.githubusercontent.com/assets/327028/18661213/6bf89bde-7ec9-11e6-99df-97d7c0c966e2.png)

**Comment by bryk** [comment]
@romlein what do you think?

**Comment by bryk** [comment]
I personally think this is a good suggestion. I'll proactively pick it into our last batch of style fixes and put into 1.4 release. If you think that's bad, we'll revert it for the next minor one. cc @maciaszczykm

**Comment by digitalfishpond** [comment]
I agree that the Romoto Mono seems less aggressive on the eye, less contrasting area.

**Comment by maciaszczykm** [comment]
@colemickens I agree, right one looks better & is easier to read.

**Comment by romlein** [comment]
Agreed. Good catch @colemickens and thanks for the speedy implementation @bryk 🔥

**Comment by maciaszczykm** [comment]
Done in #1264.
