### ISSUE TITLE
Left hand side navigation glitch on Safari. 

### ISSUE THREAD

**Issue by PiotrDabkowski** [kubernetes/dashboard#1265]
Expanding left hand side menu on Safari causes whole webpage to flicker.

**Comment by bryk** [comment]
I confirm that this issue is still there. Working on it...

**Comment by bryk** [comment]
It is there but I don't know how to fix it. I'll spend time on something else now. The issue is pretty minor, anyway.

**Comment by maciaszczykm** [comment]
Couldn't reproduce it now.

**Comment by bryk** [comment]
Close?

**Comment by bryk** [comment]
AFAIR I fixed this.
