### ISSUE TITLE
Horizontal slider on Firefox.

### ISSUE THREAD

**Issue by PiotrDabkowski** [kubernetes/dashboard#1266]
Lists of resources have horizontal sliders on Firefox. On other browsers list of resources are shrank as far as possible to fit the size of the window before applying horizontal slider. Horizontal slider is rather inconvenient.

**Comment by romlein** [comment]
+1
Table responsiveness in Firefox doesn't collapse column width as it should.
![scrollbars](https://cloud.githubusercontent.com/assets/5114858/18720028/e73428e8-7ff7-11e6-9669-2a7b480e0b3c.jpg)

**Comment by digitalfishpond** [comment]
Looking at this now

**Comment by maciaszczykm** [comment]
Cannot reproduce:

![image](https://cloud.githubusercontent.com/assets/2823399/24600053/3e155918-1853-11e7-8c80-2a5e05d33ba5.png)
