### ISSUE TITLE
Various Design Fixes and Improvements

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/dashboard#1268]
#### Issue details
- [x] Kubernetes logo not properly aligned with breadcrumb. Breadcrumb needs to be moved down 1px, and I _think_ logo has to go up 1px.
  - ![alignment](https://cloud.githubusercontent.com/assets/5114858/18734004/f9a13c82-803d-11e6-8973-748ccb9e1582.png)
- [x] When a second level of breadcrumb is added, the parent jumps up a pixel
  - ![jump](https://cloud.githubusercontent.com/assets/5114858/18733453/2082b63c-8039-11e6-8603-f7e148f55a18.png)
- [x] Breadcrumb should start with overview page (e.g. Workloads > Pods)
- [x] "Kubernetes" logo is too close to menu icon – should be 24px
  - <img width="241" alt="screen shot 2016-09-21 at 8 19 10 pm" src="https://cloud.githubusercontent.com/assets/5114858/18733399/b40c4cca-8038-11e6-8469-3f7f0107f6c0.png">
- [x] Divider between local & global actions should be 1px instead of 2px; 32px tall instead of 40px
  - Desired: 
    <img width="196" alt="screen shot 2016-09-21 at 8 33 45 pm" src="https://cloud.githubusercontent.com/assets/5114858/18733659/efbb80b8-803a-11e6-8c6f-702d3794f358.png">
- [ ] Some action buttons have insufficient right padding ("Create" is too tight; "Edit" is correct)
  ![padding](https://cloud.githubusercontent.com/assets/5114858/18733698/4806cd18-803b-11e6-9538-f0200cbcf042.png)
- [x] Increase space between action button icon and text by 2px
  - ![too-close-buttons](https://cloud.githubusercontent.com/assets/5114858/18733768/d433c836-803b-11e6-9362-3236463a8426.png)
- [ ] Selected Namespace shouldn’t be blue _and_ have gray background.  
  - ![screen shot 2016-09-16 at 2 51 37 pm](https://cloud.githubusercontent.com/assets/5114858/18733252/3d4dc0d8-8037-11e6-8a13-550da6669a29.png)
  - Selected should be blue; hover state should have gray background, as per the [Material spec](https://material.google.com/components/buttons.html#buttons-dropdown-buttons).
- [x] Namespace dropdown font should be `Roboto Medium`, not `Roboto Mono Medium`
- [x] Namespace dropdown should have 10px spacing between Namespace and bottom border (currently 7px)
  <img width="156" alt="screen shot 2016-09-21 at 8 52 46 pm" src="https://cloud.githubusercontent.com/assets/5114858/18733950/83c0bf4c-803d-11e6-9dbb-67e615e2955c.png">
- [x] Cards should have 2px border radius
  - 
    ![corners](https://cloud.githubusercontent.com/assets/5114858/18733987/ce31132e-803d-11e6-83ab-cac83c05f86c.png)
- [x] Cards should have 1px border of 0,0,0, .12
- [x] “Ingress” is currently the only singular nav item. Change to "Ingresses"
- [x] Titles of graphs: "history" is redundant in “CPU usage history”. I think we should change to "CPU / Memory Usage [or Utilization?]" or even just "CPU".
##### Environment

```
Dashboard version: 1.4.0
Operating system: OSX
Chrome and Firefox
```

**Comment by maciaszczykm** [comment]
@romlein I hope you don't have anything against me putting checkboxes near items to be completed :)

**Comment by floreks** [comment]
> Cards should have 1px border of 0,0,0, .12
Is it border between title and content?

>  Cards should have 2px border radius
Is it blur radius or spread radius? Current value for [box shadow](https://developer.mozilla.org/pl/docs/Web/CSS/box-shadow) is quite complex. 
`0 1px 3px 0 rgba(0, 0, 0, .2), 0 1px 1px 0 rgba(0, 0, 0, .14), 0 2px 1px -1px rgba(0, 0, 0, .12)`

**Comment by floreks** [comment]
> Breadcrumb should start with overview page (e.g. Workloads > Pods)

We've abandoned this idea at some point but I'm not sure why. We can add this again I think. @bryk @maciaszczykm what do you think?

>  Some action buttons have insufficient right padding ("Create" is too tight; "Edit" is correct) 

Unfortunately this is default angular material behavior. When text is too long and takes too much space then padding is smaller. To fix that globally we'd need some kind of wrapper for md-button. Anyone has a better idea for that?

> Selected Namespace shouldn’t be blue and have gray background.

Same as above. Not easy to fix and requires default angular material behavior override.

> Titles of graphs: "history" is redundant in “CPU usage history”. I think we should change to "CPU / Memory Usage [or Utilization?]" or even just "CPU".

I don't have any strong opinions here. Simple `CPU/Memory Usage` sounds good to me. I'll change that once we agree on something.

**Comment by romlein** [comment]
@maciaszczykm checkboxes are great! Sorry, I didn't know you could include those. 

@floreks 
>Breadcrumb should start with overview page (e.g. Workloads > Pods)

As with all of these I'm totally open to being to persuaded otherwise if there's a good reason.

>Some action buttons have insufficient right padding ("Create" is too tight; "Edit" is correct)

Ah ok, that's unfortunate. No I don't have any ideas.

>Simple CPU/Memory Usage sounds good to me

Cool, let's wait for @bryk to weigh in. 

>Is it border between title and content?

No, I was referring to the border all the way around the card. Since the divider between title and content is `#ddd`, that would work for the border all the way around as well I think.

>Cards should have 2px border radius

That's referring to the rounding of the corners of the card itself – not the shadow.

**Comment by floreks** [comment]
Current state:

Card
![zrzut ekranu z 2016-09-22 15-40-19](https://cloud.githubusercontent.com/assets/2285385/18750319/f984bd26-80da-11e6-8006-e81139b4cd9b.png)

Logo & breadcrumbs
![zrzut ekranu z 2016-09-22 15-40-23](https://cloud.githubusercontent.com/assets/2285385/18750323/facf5970-80da-11e6-95ef-d250e41146d8.png)

Logo & breadcrumbs (2 levels)
![zrzut ekranu z 2016-09-22 15-40-34](https://cloud.githubusercontent.com/assets/2285385/18750324/fc2a1f08-80da-11e6-847c-618cb7be4b6c.png)

Overall
![zrzut ekranu z 2016-09-22 15-41-26](https://cloud.githubusercontent.com/assets/2285385/18750344/0ccd4e3e-80db-11e6-8d36-894aad89ace8.png)

**Comment by bryk** [comment]
>> Breadcrumb should start with overview page (e.g. Workloads > Pods)

> We've abandoned this idea at some point but I'm not sure why. We can add this again I think. @bryk @maciaszczykm what do you think?

This was at the time of menu with workloads only. This can be reintroduced.

**Comment by bryk** [comment]
>>  Simple CPU/Memory Usage sounds good to me

> Cool, let's wait for @bryk to weigh in.

I'd go with CPU/Memory or CPU usage/Memory usage. I've been commenting about this before.

**Comment by bryk** [comment]
> Some action buttons have insufficient right padding ("Create" is too tight; "Edit" is correct) 

Hmm.. This looks like a bug. I'll take a look.

**Comment by danielromlein** [comment]
@bryk where do we stand with these remaining changes? It'd be nice to wrap these up. 
Still to be done: 
- [ ] Rename CPU & Memory graphs
- [ ] Start breadcrumb with overview page (e.g. Workloads > Pods)
- [ ] Fix padding issue where some action buttons have insufficient right padding ("Create" is too tight; "Edit" is correct)
- [ ] Selected Namespace shouldn’t be blue _and_ have gray background.

**Comment by bryk** [comment]
>  Rename CPU & Memory graphs

This is done already. 

>  Start breadcrumb with overview page (e.g. Workloads > Pods)

I'll take care of this.

**Comment by bryk** [comment]
> Fix padding issue where some action buttons have insufficient right padding ("Create" is too tight; "Edit" is correct)

This is harder than expected, as the behavior is built into the library we use... 


But all other comments are done :)

**Comment by maciaszczykm** [comment]
> But all other comments are done :)

Can we close it then?

**Comment by danielromlein** [comment]
If the button padding is too hard to correct for this release we can punt that, but I would like to see the following fixed:
> Selected Namespace shouldn’t be blue _and_ have gray background.

Thoughts on how difficult that would be @maciaszczykm?

**Comment by maciaszczykm** [comment]
@danielromlein As @floreks already noticed it's hard to implement. We use Angular Material select component (https://material.angularjs.org/latest/demo/select) and unfortunately it's not working as described in Material Design docs (https://material.io/guidelines/components/buttons.html#buttons-dropdown-buttons). We would need to override standard behavior, which is not good for us.

**Comment by maciaszczykm** [comment]
Opened issue in Angular Material repo, will track it from #1730. Closing this issue.

**Comment by danielromlein** [comment]
@maciaszczykm sounds good! Thank you for taking care of that
