### ISSUE TITLE
node5 is deprecated

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1272]
If you use the build-in-docker support, you now see a nasty message (and an extra 10 second wait) telling you to move to node4 or node6.

I can try to test an update to node6, but it may not be for a while.

**Comment by maciaszczykm** [comment]
@colemickens It would be great! Let us know when you will have anymore details.

**Comment by bryk** [comment]
@colemickens What's the fix for this? changing the node version we install in build/Dockerfile?

**Comment by maciaszczykm** [comment]
I'll fix that issue soon.
