### ISSUE TITLE
find endpoint err: The server asked for the client provide credentials

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/dashboard#1283]
##### Environment

```
Dashboard version:
Kubernetes version: 1.2
Operating system: centos 7.2
Node.js version: 
Go version: 1.7
```
##### Steps to reproduce

**in my env, the /var/run/secrets/kubernetes.io/serviceaccount   folder contain the token file , ca.crt**

when i create kube-dashboard service, it's reported the err：

```
err find endpoint ：the server has asked for the client to provide credentials(get endponits elasticsearch-logging)
```
##### Observed result

err find endpoint ：the server has asked for the client to provide credentials(get endponits elasticsearch-logging)

- when i watch the source code of (kubernetes/clusteraddons/fluentd-elasticsearc/es-image/elasticsearch_logging_discovery.go) ,it's : 
  
  ```
  c, err := client.NewInCluster() ,  it's will be call restclient.InClusterConfig() , in this func : InClusterConfig(), it's already authenticated,  
  ```
- when the code get the service by name of  elasticsearch-logging:  
  
  ```
   elasticsearch, err = c.Services(api.NamespaceSystem).Get("elasticsearch-logging") 
  ```
  
  it's not report the err : Failed to find the elasticsearch-logging service: the server has asked for the client to provide credentials(get service elasticsearch-logging)
- when the code get the endpoint by name of  elasticsearch-logging: 
  
  ```
  endpoints, err = c.Endpoints(api.NamespaceSystem).Get("elasticsearch-logging")
  ```
  
  it's  report the err : Failed to find the elasticsearch-logging service: the server has asked for the client to provide credentials(get service elasticsearch-logging)
##### Expected result

i thought the client already authenticated when cretate client  (client.NewInCluster()) ,if authenticate fail, should be repoert error,  but, why the err was reported when  the code get the endpoint by name of  elasticsearch-logging.  l can't understand it.

**Comment by luohoufu** [comment]
i also get the error.
[kube-error.txt](https://github.com/kubernetes/dashboard/files/583519/kube-error.txt)

**Comment by cheld** [comment]
@huangjiasingle Dashboard has nothing to do with elasticsearch. Maybe your service account is invalid. Please remove it, it should be recreated automatically

**Comment by luohoufu** [comment]
@cheld i check service account ok with https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

[root@k8s-master ~]# ﻿TOKEN_VALUE=$(kubectl exec test-701078429-wx47q -- cat /var/run/secrets/kubernetes.io/serviceaccount/token)  
[root@k8s-master ~]# kubectl exec test-701078429-wx47q -- curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H  "Authorization: Bearer $TOKEN_VALUE" https://172.16.0.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1alpha1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1alpha1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1alpha1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/logs",
    "/metrics",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]

**Comment by cheld** [comment]
@luohoufu 

In the log, dashboard tries to connect to https://10.37.116.31:6443, while in the upper test you connect to https://172.16.0.1

What is the output of: 
```
$ kubectl get services
```

**Comment by maciaszczykm** [comment]
Most likely this issue is connected to cluster configuration. You should check our troubleshooting guide:
https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

Closing as stale. If issue still occurs please reopen it or create new one.
