### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by junsaw** [kubernetes/dashboard#1286]
I installed the kubernetes dashboard using the instructions provided online. I updated the apiserver on the configuration file to point to the master server.  The deployment of the pods were successfully however when I go to the kubernetes dashboard I am getting the following error:

**Internal Server Error (500)**

**the server could not find the requested resource (get replicationControllers)**

I then issued the following command to get more logs:

kubectl logs kubernetes-dashboard-2354787505-iuj2g --namespace=kube-system

**I get the following:**

Getting lists of all workloads
the server could not find the requested resource (get pods)
[2016-09-26T20:20:39Z] Outcoming response to 192.168.58.0:59132 with 500 status code
[2016-09-26T20:20:39Z] Incoming HTTP/1.1 GET /api/v1/petset/default?itemsPerPage=10&page=1 request from 192.168.58.0:59132
Getting list of all pet sets in the cluster
[2016-09-26T20:20:39Z] Outcoming response to 192.168.58.0:59132 with 201 status code
[2016-09-26T20:20:41Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 192.168.58.0:59132
Getting namespace list
the server could not find the requested resource (get namespaces)
[2016-09-26T20:20:41Z] Outcoming response to 192.168.58.0:59132 with 500 status code
[2016-09-26T20:26:26Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 192.168.58.0:59132
Getting namespace list
the server could not find the requested resource (get namespaces)
[2016-09-26T20:26:26Z] Outcoming response to 192.168.58.0:59132 with 500 status code
Getting application global configuration
Application configuration {"serverTime":1474921588965}
[2016-09-26T20:26:30Z] Incoming HTTP/1.1 GET /api/v1/petset/default?itemsPerPage=10&page=1 request from 192.168.58.0:59128
Getting list of all pet sets in the cluster
[2016-09-26T20:26:30Z] Outcoming response to 192.168.58.0:59128 with 201 status code
Getting application global configuration
Application configuration {"serverTime":1474921598777}
[2016-09-26T20:26:40Z] Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from 192.168.58.0:59128
Getting lists of all workloads
the server could not find the requested resource (get pods)
[2016-09-26T20:26:40Z] Outcoming response to 192.168.58.0:59128 with 500 status code
[2016-09-26T20:26:40Z] Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from 192.168.58.0:59128
Getting lists of all workloads
the server could not find the requested resource (get replicationControllers)
[2016-09-26T20:26:40Z] Outcoming response to 192.168.58.0:59128 with 500 status code
[2016-09-26T20:26:40Z] Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from 192.168.58.0:59128
Getting lists of all workloads
the server could not find the requested resource (get replicationControllers)
[2016-09-26T20:26:41Z] Outcoming response to 192.168.58.0:59128 with 500 status code

**My Kubernetes version is:**

kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ec7364b6e3b155e78086018aa644057edbe196e5", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ec7364b6e3b155e78086018aa644057edbe196e5", GitTreeState:"clean"}

Any help will be appreciated.

Thanks A lot 
Junior

**Comment by bryk** [comment]
Can add this argument to the UI container: `--v 999` and restart the pod? Then show logs again here.

**Comment by junsaw** [comment]
I attempted that and unfortunately the container is unable to start:

CONTAINER ID                                                       IMAGE                                                        COMMAND                                                                          CREATED              STATUS                          PORTS               NAMES
9204c11da508ed095f5c726fb5ae0f5ee06c12afbf2d8b78b39e43ee49bcec4b   gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0   "/dashboard --port=9090 '--apiserver-host=http://10.199.240.73:2379  --v 999'"   33 seconds ago       Exited (1) 32 seconds ago                           k8s_kubernetes-dashboard.5dbedc88_kubernetes-dashboard-650327692-3k9kh_kube-system_12be9400-919c-11e6-85d4-00155df07e03_8beb617a
d01c0e010d0bc61efa7472559b01a03a83aae23bfcfba86d6c65460822ecdc01   gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0   "/dashboard --port=9090 '--apiserver-host=http://10.199.240.73:2379  --v 999'"   55 seconds ago       Exited (1) 54 seconds ago                           k8s_kubernetes-dashboard.5dbedc88_kubernetes-dashboard-650327692-3k9kh_kube-system_12be9400-919c-11e6-85d4-00155df07e03_e432245e
05ef919df007e92caee99d904520096d36e46dc21a96740d81a390513398551a   gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0   "/dashboard --port=9090 '--apiserver-host=http://10.199.240.73:2379  --v 999'"   About a minute ago   Exited (1) About a minute ago                       k8s_kubernetes-dashboard.5dbedc88_kubernetes-dashboard-650327692-3k9kh_kube-system_12be9400-919c-11e6-85d4-00155df07e03_7a3cb55f
3a3c7049bbfbdf199bdf122da5b1bc7ca8ba63a21ae77a742de8068a5cac0e56   gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0   "/dashboard --port=9090 '--apiserver-host=http://10.199.240.73:2379  --v 999'"   About a minute ago   Exited (1) About a minute ago                       k8s_kubernetes-dashboard.5dbedc88_kubernetes-dashboard-650327692-3k9kh_kube-system_12be9400-919c-11e6-85d4-00155df07e03_eb39a1e0
5587a3d17b96c55ce9ec19dcdb897316a176f78db2e50009b6acf7154ff00c0b   registry.access.redhat.com/rhel7/pod-infrastructure:latest   "/pod"                                                                           About a minute ago   Up About a minute                                   k8s_POD.42430ae1_kubernetes-dashboard-650327692-3k9kh_kube-system_12be9400-919c-11e6-85d4-00155df07e03_577f7c6c

**Comment by bryk** [comment]
Can you show us logs of the Dashboard UI container?

**Comment by maciaszczykm** [comment]
Closing as stale.
