### ISSUE TITLE
Dashboard v1.4.0 incorrectly renders opaque secrets

### ISSUE THREAD

**Issue by ashmere** [kubernetes/dashboard#1291]
#### Issue details

the new dashboard shows any secret including opaque ones I would have expected this to have the same behaviour as kubectl which will only list the file names of an opaque secret not the contents
##### Environment

```
Dashboard version: v1.4.0
Kubernetes version: v1.4.0
Operating system: coreos
Node.js version: n/a
Go version: n/a
```
##### Steps to reproduce

deploy the currently manifest for v1.4.0 dashboard and add an opaque secret to your kubernetes cluster then try to view it in the ui
##### Observed result

I can see the full details of any secret via the web ui dashboard even opaque ones
##### Expected result

I would expect to see a listing on the secrets but no contents similar to what kubectl shows.

**Comment by jkemp101** [comment]
+1 for fixing.  This gives a bad impression on the overall security of k8s and its protection of secrets.

**Comment by bryk** [comment]
Yep, the linked PR should get it soon.

**Comment by maciaszczykm** [comment]
You can use HEAD release soon to test it: https://github.com/kubernetes/dashboard/blob/master/docs/devel/head-releases.md

Otherwise, just wait for next release.
