### ISSUE TITLE
cpu & memory metrics view

### ISSUE THREAD

**Issue by tsn77130** [kubernetes/dashboard#1298]
#### Issue details
Hi, I can't see how to get CPU & memory metrics for individual pods, I just have dashes instead.
Is there any prerequisites to have, or something else ?
I haven't found anything in documentation about it.

Thanks

##### Environment
Dashboard version: 1.4.0 // gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0
Kubernetes version: 1.2.4 / 1.3.6
Operating system: CoreOs

**Comment by bryk** [comment]
You need to install Heapster on your cluster to make metrics view work.

**Comment by tsn77130** [comment]
HI bryk,
I already have a heapster pod, deployed with influxdb as asked in "Running Heapster on Kubernetes" of heapster guide, isn't it good ?

**Comment by ntquyen** [comment]
I got the same issue here, using dashboard 1.4.1, heapster 1.2.0, already expose `heapster` service, port 8082, but still get dashes instead.

**Comment by maciaszczykm** [comment]
@tsn77130 @ntquyen Where are your Heapsters deployed? In the cluster? In which namespace?

**Comment by tsn77130** [comment]
@ntquyen  : I 've two things in order to make it work 
- upgraded heapster to v1.2.0 
- upgrading kubernetes cluster from 1.2 to 1.3(.6)

As @maciaszczykm  said, heapster is deployed in namespace kube-system

**Comment by ntquyen** [comment]
Heapster is deployed in same namespace: kube-system, may be the issue lies in heapster, because  its api doesnt work, i'll try upgrade k8s, thanks!

**Comment by ntquyen** [comment]
Heapster is deployed in same namespace: kube-system, may be the issue lies in heapster, because  its api doesnt work, i'll try upgrade k8s, thanks!

**Comment by maciaszczykm** [comment]
@ntquyen I'm closing the issue since we know, that issue is on Heapster side at the moment. If you'll find any issues more, then please reopen and let us know about them.
