### ISSUE TITLE
"dial tcp:  no suitable address found" error while connecting to heapster

### ISSUE THREAD

**Issue by ravilr** [kubernetes/dashboard#1305]
#### Issue details
"
Skipping Heapster metrics because of error: Get http://heapster.kube-system.svc.cluster.local:8082/api/v1/model/namespaces/tachyon/pod-list/boson.adapter-controller-82fc521c54a4d16c0002785d631c0d67-g3ptc,qa.default.nimbus-1252092381-tnnju,qa.default.supervisor-content-webpage-3936070723-mhjc2,qa.default.supervisor-horoscope-2832703161-9oq2u,qa.default.zk1-2153710118-xhowg,qa.default.zk2-2957443626-25le2,qa.default.zk3-3761177134-x82cm/metrics/cpu-usage: dial tcp: no suitable address found "

we override the docker run command with "/dashboard --port=9090 --heapster-host=http://heapster.kube-system.svc.cluster.local:8082"  as we want to avoid going through service proxy. 

##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0
Kubernetes version: v1.4.0
Operating system: RHEL 7.1
Node.js version:
Go version:
```

there is an issue with golang-1.7 skipping *.local dns resolution. which is fixed in golang-1.7.1: https://github.com/golang/go/issues/16739

Can you please confirm if v1.4.0 image is built using golang-1.7 . if so release a new image built using golang-1.7.1 ? Thanks.

**Comment by ravilr** [comment]
@bryk

**Comment by bryk** [comment]
So you say if we rebuild the image with go1.7.1, the problem will vanish?

**Comment by ravilr** [comment]
@bryk yes. the debian `golang:latest` image here https://github.com/kubernetes/dashboard/blob/v1.4.0/build/Dockerfile#L21 is already updated to golang-1.7.1 in docker hub.
So, looks like we just have to rebuild and publish the new image.

**Comment by bryk** [comment]
Fixed in: https://github.com/kubernetes/dashboard/releases/tag/v1.4.1
