### ISSUE TITLE
Display info about which controller created a pod

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1306]
In pod details we should display a row info about which controller created it. E.g., a replication controller that created it.

**Comment by maciaszczykm** [comment]
Already done by @rf232:

![image](https://cloud.githubusercontent.com/assets/2823399/20137468/e40ea7d4-a67a-11e6-8fe9-181a3ffbb40e.png)

Do we need anything else at this stage? If yes, please comment/reopen.

**Comment by maciaszczykm** [comment]
#1344

**Comment by rf232** [comment]
oops, forgot to close this issue, thanks @maciaszczykm
