### ISSUE TITLE
FAQ about dashboard setup

### ISSUE THREAD

**Issue by IanLewis** [kubernetes/dashboard#1309]
We get a lot of issues related to the dashboard not working in new clusters which almost invariably turn out to be improperly set up Kubernetes clusters rather than issues with the dashboard. We should have a FAQ or suggestions when installing the dashboard that users can reference for guidance about where to create issues.

**Comment by bryk** [comment]
My idea was to start our installation guide with references to tools/providers that we know that work. And only in the advanced section explain how to run the UI on a hand-crafted cluster. 

E.g., 
```To access the UI open http://master/ui on your cluster provider (e.g., GKE, stackpoint, Foo) or use minikube to create a new cluster.

(advanced)
To install the UI on your claster do $Foo and $Bar. 
```

**Comment by IanLewis** [comment]
Ok. I think we should at least do what you suggested. I think it might also be good to call out network related issues as most likely being cluster related rather than dashboard related. Maybe a "Troubleshooting" section?

**Comment by cheld** [comment]
I will start with a trouble shooting section regarding service account and kubeconfig file. We can add other topics later.

**Comment by maciaszczykm** [comment]
It is already available in project's wikis.
