### ISSUE TITLE
create pod error 

### ISSUE THREAD

**Issue by gl328518397** [kubernetes/dashboard#1328]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

**Comment by gl328518397** [comment]
docker pull gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0
Trying to pull repository gcr.io/google_containers/kubernetes-dashboard-amd64 ... 
unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp 173.194.72.82:443: getsockopt: connection refused
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp 173.194.72.82:443: getsockopt: connection refused

**Comment by colemickens** [comment]
1. Why are you manually `docker pull`ing it?

2. It seems you can't hit `gcr.io` from wherever you're running that command. Works fine from all of my machines.

**Comment by gl328518397** [comment]
1.because when I run ‘kubectl create -f kubernetes-dashboard.yaml’ ,and 'kubectl get pods' it show 'ContainerCreating'  ,

2.if should I must hit gcr.io ,,other addr is avaliable ?

**Comment by floreks** [comment]
> 2.if should I must hit gcr.io ,,other addr is avaliable ?

I don't think it is. By default `gcr.io` images are hosted in US and for now we don't host images anywhere else. Soon there should be available canary image on Docker Hub, but AFAIK official releases will always be available only on `gcr.io`.

**Comment by maciaszczykm** [comment]
Yes, most probably it's an issue connected to firewall if you cannot `docker pull` it.

**Comment by maciaszczykm** [comment]
@gl328518397 do you have any updates? Were you able to pull docker image? Can we close the issue?

**Comment by gl328518397** [comment]
OK
