### ISSUE TITLE
create a "deployment" rather "replication controller" when click the "+CREATE" button

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/dashboard#1330]
#### Issue details

"Deployment" is  the next-generation Replication Controller with many enhanced features.
And deployment has been supported for a while. I think it's time to make dashboard users
able to create a "deployment".
When users click the button "+CREATE", by default users will create a new replication controller,
I think we need to create a deployment by default in the feature.
##### Environment

```
Dashboard version: v1.4.0
Kubernetes version: v1.4.0
Operating system: ubuntu 16.04
Node.js version:
Go version: go1.6.3
```
##### Steps to reproduce
1. click "+CREATE"
2. specify the details
3. click "DEPLOY" button
##### Observed result

A new Replication controller is created.
##### Expected result

According to the doc the behavior that a new rc is created is right.
http://kubernetes.io/docs/user-guide/ui/
However, I thinks it's time to create a new deployment by default now.

**Comment by CaoShuFeng** [comment]
I am working on this now.
Can someone assign me to this issue?

**Comment by maciaszczykm** [comment]
Yes, it's good idea.

Regarding title - there is a way to create all kinds of resources from the UI, but you need to use YAML files and upload them. Having deploy forms for resources other than replication controller is on the roadmap.

Thanks for reporting this issue.

**Comment by bryk** [comment]
@CaoShuFeng Thanks for working on it? Me and @rf232 can happily help you with anything that's needed?

Can you outline your plan for tackling this? Just code and docs change? Or something else? 

I'm wondering whether we should do this conditionally for 1.4+ clusters or for all.

**Comment by Sn0rt** [comment]
@bryk hi: the [PR](https://github.com/kubernetes/dashboard/pull/1350) was sent and test is fixing...
