### ISSUE TITLE
Roundup of other K8s UIs

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/dashboard#1333]
1. What other UIs for K8s exist? In the interest of building the best possible product for our users, I think it'd be helpful to consider how other teams are tackling similar issues. 
2. More generally, what other container orchestration UIs exist? @bgrant0607 proposed [this list](https://github.com/kubernetes/community/wiki/Roadmap:-Cluster-Deployment#production-grade-easy-to-use-cluster-management-toolsservices) of cluster management tools. 

cc @floreks @maciaszczykm

**Comment by bgrant0607** [comment]
Cockpit:
http://stef.thewalter.net/cockpit-kubernetes-dashboard.html
https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/single/getting-started-with-cockpit/
Techtonic console:
https://tectonic.com/
Cabin (mobile):
http://www.skippbox.com/announcing-cabin-the-first-mobile-app-for-kubernetes/

Related UIs:

Openshift console:
https://docs.openshift.org/latest/getting_started/developers_console.html
Weavescope:
https://medium.com/google-cloud/using-kube-ui-and-weave-scope-with-google-container-engine-63fadf9656f#.2drcpetm5
Rancher:
http://rancher.com/kubernetes/
Navops:
http://www.navops.io/launch.html

Other systems:

Mesos:
https://github.com/mesosphere/marathon-ui
https://github.com/Capgemini/mesos-ui

**Comment by colemickens** [comment]
[ElastiKube](https://elasticbox.com/kubernetes/) seems visually pleasing and functional.

**Comment by romlein** [comment]
Thanks @bgrant0607! That's exactly what I was looking for. 
Yeah @colemickens ElastiKube seems to do a pretty good job of incorporating Material. I hadn't seen that before.

**Comment by IanLewis** [comment]
@romlein @bgrant0607 In order to turn this into an action item, is this something something that is missing that we could add to the Kubernetes docs? I feel it might be out of place here since Dashboard is just one UI.

**Comment by bgrant0607** [comment]
http://fabric8.io/guide/console.html

**Comment by romlein** [comment]
Sorry @IanLewis I'm not sure I follow? I was intending this to be a way to research how other people are problems similar to the ones we're tackling in Dashboard. I think as a Dashboard product team we should at least be aware of how other groups are doing things.

**Comment by edouardKaiser** [comment]
Disclaimer: I'm not bashing the dashboard (that we love very much and we use it every day). I just want to use this opportunity to lay out a couple of stuff that we also particularly appreciate in the Tectonic Console:

- Global stream of events (that's just the best, love this one)

![image](https://cloud.githubusercontent.com/assets/7731641/19370341/18a77b9e-91f7-11e6-91b9-c51a8a51fc91.png)

- Friendly label modification on every ressource (specially useful on the Nodes, something we cannot do in the Dashboard right now):

![image](https://cloud.githubusercontent.com/assets/7731641/19370307/d99b96a6-91f6-11e6-940f-5a59a51cf688.png)


- Search feature

![image](https://cloud.githubusercontent.com/assets/7731641/19370323/f7d64a62-91f6-11e6-9ac8-1956f34a82b7.png)


- More Details on the container running (health check configuration, mounted volumes, resource limits...)

![image](https://cloud.githubusercontent.com/assets/7731641/19370442/99356230-91f7-11e6-8839-7d0e6a306d67.png)


- Download YAML

![image](https://cloud.githubusercontent.com/assets/7731641/19370466/bd2c7caa-91f7-11e6-9cce-bb46fef669e6.png)

- Globally, the resource modification is very friendly, example of "Deployment" edition:

![image](https://cloud.githubusercontent.com/assets/7731641/19370546/1e1c22e0-91f8-11e6-9f81-7ac28b8e378f.png)

![image](https://cloud.githubusercontent.com/assets/7731641/19370552/267d50a8-91f8-11e6-88e7-abc97d45dbe0.png)

![image](https://cloud.githubusercontent.com/assets/7731641/19370557/3278872e-91f8-11e6-92dc-dbda89bde556.png)

![image](https://cloud.githubusercontent.com/assets/7731641/19370588/61073126-91f8-11e6-81f4-9264394a806c.png)

It's not perfect, there is no PetSet, Jobs, Daemon Sets, Secrets, Config Maps management....

**Comment by IanLewis** [comment]
@romlein Ok. You just filed an issue so I assumed there was some kind of bug or issue that needed to be addressed.

I thought if we want to have a general discussion then something like sharing a Google doc or discussion on the sig-ui Slack or sig-ui mailing list would be better.

**Comment by bryk** [comment]
@edouardKaiser Thanks for listing all those features that we don't have. I'm super happy that you did this! :) We turn such requests into actual work.

**Comment by romlein** [comment]
@IanLewis sorry for the delay in response. Ah, I see your point. That is an interesting idea about including this info somewhere in our docs. @bryk WDYT? At the least, I'm putting together a Google Doc with the summary roundup of other UIs.

**Comment by bryk** [comment]
@romlein Sounds like an awesome idea.

**Comment by cristim** [comment]
I think [spinnaker](https://github.com/spinnaker/spinnaker) can also be used to some degree as a GUI for kubernetes

**Comment by maciaszczykm** [comment]
Closing as the discussion will follow in #2508.
