### ISSUE TITLE
UI docs have wrong link

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/dashboard#1339]
http://kubernetes.io/docs/user-guide/ui/

PetSet links to LoadBalancer

**Comment by colemickens** [comment]
Reported here already: https://github.com/kubernetes/kubernetes.github.io/issues/750

**Comment by digitalfishpond** [comment]
Assuming this should link to here: [http://kubernetes.io/docs/user-guide/petset/](http://kubernetes.io/docs/user-guide/petset/) ? If someone can confirm, I will fix.

**Comment by digitalfishpond** [comment]
(continued in [kubernetes/kubernetes.github.io#750](kubernetes/kubernetes.github.io#750) ) I will close this instance of the issue.
