### ISSUE TITLE
Allow to see pods distribution across nodes

### ISSUE THREAD

**Issue by djsly** [kubernetes/dashboard#1372]
#### Enhancement details

It would be useful to be to able to see on which nodes all replicas of the same type are scheduled. 
The pod table currently shows the clusterIP only, if we could add to that column the pod Name (which is available on the pod description page that would help have a quick idea on which node all of our replicas are. 

Eventually having a better distribution dashboard could be nicer where the user could quickly identify if replicas are stacked too much on the same nodes or if replicas are spawning across different DC or Rack Hosts.

**Comment by floreks** [comment]
I guess this is already covered. On node details page there is a list of all pods running on a node and also on pod details page there is information about the node on which pod is running.

**Comment by djsly** [comment]
While we do have the information available, it isn't handy enough when you have 10/20/50 replicas of the same pod.

From this table, it would make sense to display the node each pod are running on, similar to the output we get when running `kubectl get pods -o wide`

<img width="1168" alt="screen shot 2017-06-28 at 10 47 26" src="https://user-images.githubusercontent.com/4981802/27643574-7253dd14-5bef-11e7-8c72-9c307809ef6f.png">

`kubectl get pods --selector=k8s-app=kubernetes-dashboard -o wide`
````
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
kubernetes-dashboard-3727042919-df8pc   1/1       Running   0          1d        172.17.30.2   k8sii-ksinst-143-p30552--kubenode-edge-0
kubernetes-dashboard-3727042919-llrng   1/1       Running   0          1d        172.17.93.2   k8sii-ksinst-143-p30552--kubenode-edge-1
kubernetes-dashboard-3727042919-pbsl2   1/1       Running   0          1d        172.17.55.3   k8sii-ksinst-143-p30552--kubenode-edge-2
````

**Comment by djsly** [comment]
please reopen or let me know if you prefer that I open a new feature request.

**Comment by floreks** [comment]
We can add node information to pod list.

_Sent from my LGE Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cheld** [comment]
This would be a simple fix, but I guess it requires manual counting and is not really a visualization.
