### ISSUE TITLE
YAML upload should respect the selected namespace

### ISSUE THREAD

**Issue by YvanDaSilva** [kubernetes/dashboard#1374]
#### Issue details

The upload of a YAML file does not respect the selected namespace in the dashboard.
##### Environment

```
Dashboard version: n/a
Kubernetes version: 1.4 (GKE hosted)
Operating system: debian
Node.js version: n/a
Go version: n/a
```
##### Steps to reproduce
- Select a namespace other than default.
- Build a simple YAML of any resource (example a secret), upload it through the YAML upload dialog.
##### Observed result

If no namespace is provided in the YAML the resource is created on the 'default namespace' even when "All namespaces" or "default" are not selected.
##### Expected result

It should react like the CLI commands. If in the dashboard: 
- a namespace is selected and no namespace is present in the YAML file, use the selected one.
- a namespace is selected but different than the one in the YAML file, show an error that the selected namespace differs from the one enforced in the file.
- no namespace is selected and the YAML enforces a namespace, create the resource in the proper namespace.
- no namespace or 'default' is selected and the YAML doesn't enforce a namespace, create the resource in the 'default' namespace.
##### Comments

At the moment the selected namespace is only shown when the menu is open, which I guess is there for smaller screens. Because of this, I think,  we should also have a reminder of the current namespace next to each screen name on the top as a secondary information.

**Comment by bryk** [comment]
@digitalfishpond Can you investigate this?

**Comment by IanLewis** [comment]
This is tricky because I could see this either way. The current information architecture of the UI does not really make it clear that you would be creating in the currently selected namespace.

**Comment by bryk** [comment]
How about we re-add namespace selector to the YAML upload form? And default it to currently viewed namespace.

**Comment by YvanDaSilva** [comment]
I also thought about the namespace selector in the upload screen.
But isn't it a bit weird just like now ? You might have already filtered by your namespace in the menu, meaning you are now creating a resource that you won't be able to see until you change that filter.

If the menu is closed, this can lead to confusion.

This is why I suggested the CLI approach.

**Comment by IanLewis** [comment]
Yah, A bit cumbersome but I suppose that would be ok. The namespace selector in the upload form would default to the currently selected namespace in the sidebar.

**Comment by digitalfishpond** [comment]
How about: 

1) linking the namespace selector in the upload form to the one in the sidebar so that changes in one are reflected in the other so that if you upload to a different namespace, when the upload completes you'd find yourself in the namespace you uploaded to, addressing @YvanDaSilva 's point? 

Or alternatively...

2) _instead_ of a second namespace selector, have a message on the upload form saying: "please ensure the namespace you wish to upload to is selected in the menu sidebar, you can also select 'All namespaces' if a namespace is specified in your YAML file."

Any thoughts? @YvanDaSilva @bryk @IanLewis

**Comment by digitalfishpond** [comment]
Another option is to change the help message next to the form which currently says: "Select a YAML or JSON file, specifying the resources to deploy." 

to a message that will change depending on the namespace selected: 

if a specific namespace is selected, it would say: "Select a YAML or JSON file, specifying the resources to deploy to the current namespace or the namespace specified in your file." 
if 'All namespaces' or 'default' are selected, it would say: "Select a YAML or JSON file, specifying the resources to deploy to the default namespace or the namespace specified in your file."

**Comment by digitalfishpond** [comment]
... as well as the changes recommended by @YvanDaSilva in the description, of course.

**Comment by YvanDaSilva** [comment]
Linking the namespace selectors or messages is fine IMHO.
However how do you handle the case where the file enforces an environment that is not the one selected? Kubernetes API returns an error message if you try to create a resource on a specific namespace and the yaml content provides a different one.

**Comment by digitalfishpond** [comment]
So the message _'Select a YAML or JSON file, specifying the resources to deploy to the current namespace or the namespace specified in your file.'_ implies that if the file mentions a namespace, that would take precedence over the current namespace selected in the UI. 

But I think we would want to be as consistent with the Kubernetes API as possible? 

Does everyone agree that a file that specifies a namespace should only be deployable if the selected namespace in the UI is the same or shows 'All namespaces', which would be consistent with the Kubernetes API? An error message could say: 
_'Your file specifies a namespace that is inconsistent with the namespace currently selected in Dashboard. Either edit the namespace entry in your file or select a different namespace in Dashboard to deploy to (eg. 'All namespaces').'_

@YvanDaSilva @bryk @IanLewis

**Comment by YvanDaSilva** [comment]
@digitalfishpond "All namespaces" or the correct namespace provided through the yaml.
Yes that would make sense and is what the k8s API actually does.

kubectl client error message : 
> the namespace from the provided object "staging" does not match the namespace "production". You must pass '--namespace=staging' to perform this operation.

**Comment by bryk** [comment]
@digitalfishpond I like your proposals here. I'd go with adjusting the text message based on the namespace selected and then aligning with `kubectl`, meaning that you have to select namespace `foo` to upload to it, if specified in the YAML file.

**Comment by digitalfishpond** [comment]
Ok, so I need confirmation at this point: I've gone from handling checks in the front end to now letting kubectl use its own logic. Obviously, kubectl does not consider "_all" and "default" to be special in any way, and returns false when comparing them to any namespace in a YAML. @bryk, I realised that your latest comment could be interpreted in several ways, so I wanted to check that you still did want to be able to deploy if the selected namespace in the UI was 'All namespaces' and a namespace was specified in the YAML?

**Comment by bryk** [comment]
> I wanted to check that you still did want to be able to deploy if the selected namespace in the UI was 'All namespaces' and a namespace was specified in the YAML?

Yes, exactly.

**Comment by digitalfishpond** [comment]
I'm moving away from this backend issue for which I don't have the pre-required background understanding (backend, Go) to make any further progress. Anyone with back-end/Go familiarity will probably find it to be a simple, quick fix; I'm afraid I'll be sticking to front-end issues where I can be of more use :)

So far, the solution (for which the back-end part should be mainly attributed to @florex) includes the changes described in the document linked [here](https://docs.google.com/document/d/16nAOsX3km6Zi99wEwZ7U_OCSAf8lGv88FaBftXl7gKY/edit?usp=sharing)

**Comment by eric-tucker** [comment]
The documentation for Kubernetes does not describe how to add a namespace to to a YAML file.  Can someone please comment on how this is done?

I just ran into this same problem - the selected namespace is ignored and there's no option to specify a namespace when uploading a YAML file.

**Comment by digitalfishpond** [comment]
Currently, as long as the namespace exists, you can add a parameter inside your YAML file (for example under the file's "name" parameter) called "namespace" like this: 
```
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: existingnamespace
  labels:
    app: redis
    tier: backend
    role: master
```

**Comment by zhouhaibing089** [comment]
Is this the summary: Adding `namespace` entry in the form, and promote an error when the namespace does not match?

**Comment by floreks** [comment]
I'm working on it. There are some use cases to consider, but it should not take long for me to finish.
