### ISSUE TITLE
Kubernetes dashboard unauthorized & endpoints failed problem

### ISSUE THREAD

**Issue by ensalty** [kubernetes/dashboard#1382]
#### Issue details

![image](https://cloud.githubusercontent.com/assets/5126301/19834035/ba7f77ec-9e8a-11e6-9644-e87ad6dba7e8.png)

![image](https://cloud.githubusercontent.com/assets/5126301/19834044/00b330be-9e8b-11e6-8409-1f5db672e198.png)

localhost:8001

![image](https://cloud.githubusercontent.com/assets/5126301/19834313/92fc6c2a-9e94-11e6-9afc-62918a8675ca.png)

localhost:8001/ui
![image](https://cloud.githubusercontent.com/assets/5126301/19834317/aa39f308-9e94-11e6-9150-25a4934228fd.png)

```
kubeadm-1.5.0-0.alpha.0.1534.gcf7301f.x86_64
kubelet-1.4.0-0.x86_64
kubernetes-cni-0.3.0.1-0.07a8a2.x86_64
kubectl-1.4.0-0.x86_64
CentOS 7
```
##### Observed result

```
[root@cloud ~]# kubectl get svc --all-namespaces
NAMESPACE     NAME                   CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             100.64.0.1      <none>        443/TCP         17h
kube-system   kube-dns               100.64.0.10     <none>        53/UDP,53/TCP   17h
kube-system   kubernetes-dashboard   100.73.172.90   <nodes>       80/TCP          17h
```

```
[root@cloud kubernetes]# kubectl cluster-info
Kubernetes master is running at http://localhost:8080
kube-dns is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns

```

```
[root@cloud kubernetes]# kubectl describe nodes
Name:                   cloud
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubeadm.alpha.kubernetes.io/role=master
                        kubernetes.io/hostname=cloud
Taints:                 dedicated=master:NoSchedule
CreationTimestamp:      Sat, 29 Oct 2016 20:35:47 +0800
Phase:
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason          Message
  ----                  ------  -----------------                       ------------------                      ------          -------
  OutOfDisk             False   Sun, 30 Oct 2016 13:23:04 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletHasSufficientDisk         kubelet has sufficient disk space available
  MemoryPressure        False   Sun, 30 Oct 2016 13:23:04 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletHasSufficientMemory       kubelet has sufficient memory available
  DiskPressure          False   Sun, 30 Oct 2016 13:23:04 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletHasNoDiskPressure         kubelet has no disk pressure
  Ready                 True    Sun, 30 Oct 2016 13:23:04 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletReady    kubelet is posting ready status
Addresses:              131.160.56.47,131.160.56.47
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   16
 memory:                                49283376Ki
 pods:                                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   16
 memory:                                49283376Ki
 pods:                                  110
System Info:
 Machine ID:                    6361e3b01be64734877ddc707f6564a4
 System UUID:                   44454C4C-4700-1059-8059-B9C04F38344A
 Boot ID:                       ee853c9a-3c53-4800-b1e3-c9b1d474f3f4
 Kernel Version:                3.10.0-327.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.10.3
 Kubelet Version:               v1.4.0
 Kube-Proxy Version:            v1.4.0
ExternalID:                     cloud
Non-terminated Pods:            (7 in total)
  Namespace                     Name                                    CPU Requests    CPU Limits      Memory Requests Memory Limits
  ---------                     ----                                    ------------    ----------      --------------- -------------
  kube-system                   etcd-cloud                              200m (1%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-apiserver-cloud                    250m (1%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-controller-manager-cloud           200m (1%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-discovery-982812725-z4b0v          0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-dns-2247936740-j6pq1               210m (1%)       210m (1%)       390Mi (0%)      390Mi (0%)
  kube-system                   kube-proxy-amd64-d2nr2                  0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-scheduler-cloud                    100m (0%)       0 (0%)          0 (0%)          0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  960m (6%)     210m (1%)       390Mi (0%)      390Mi (0%)
No events.[root@cloud kubernetes]# kubectl describe nodes
Name:                   cloud
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubeadm.alpha.kubernetes.io/role=master
                        kubernetes.io/hostname=cloud
Taints:                 dedicated=master:NoSchedule
CreationTimestamp:      Sat, 29 Oct 2016 20:35:47 +0800
Phase:
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason          Message
  ----                  ------  -----------------                       ------------------                      ------          -------
  OutOfDisk             False   Sun, 30 Oct 2016 13:23:55 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletHasSufficientDisk         kubelet has sufficient disk space available
  MemoryPressure        False   Sun, 30 Oct 2016 13:23:55 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletHasSufficientMemory       kubelet has sufficient memory available
  DiskPressure          False   Sun, 30 Oct 2016 13:23:55 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletHasNoDiskPressure         kubelet has no disk pressure
  Ready                 True    Sun, 30 Oct 2016 13:23:55 +0800         Sat, 29 Oct 2016 20:35:47 +0800         KubeletReady    kubelet is posting ready status
Addresses:              131.160.56.47,131.160.56.47
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   16
 memory:                                49283376Ki
 pods:                                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   16
 memory:                                49283376Ki
 pods:                                  110
System Info:
 Machine ID:                    6361e3b01be64734877ddc707f6564a4
 System UUID:                   44454C4C-4700-1059-8059-B9C04F38344A
 Boot ID:                       ee853c9a-3c53-4800-b1e3-c9b1d474f3f4
 Kernel Version:                3.10.0-327.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.10.3
 Kubelet Version:               v1.4.0
 Kube-Proxy Version:            v1.4.0
ExternalID:                     cloud
Non-terminated Pods:            (7 in total)
  Namespace                     Name                                    CPU Requests    CPU Limits      Memory Requests Memory Limits
  ---------                     ----                                    ------------    ----------      --------------- -------------
  kube-system                   etcd-cloud                              200m (1%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-apiserver-cloud                    250m (1%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-controller-manager-cloud           200m (1%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-discovery-982812725-z4b0v          0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-dns-2247936740-j6pq1               210m (1%)       210m (1%)       390Mi (0%)      390Mi (0%)
  kube-system                   kube-proxy-amd64-d2nr2                  0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-scheduler-cloud                    100m (0%)       0 (0%)          0 (0%)          0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  960m (6%)     210m (1%)       390Mi (0%)      390Mi (0%)
No events.[root@cloud kubernetes]# kubectl get svc --all-namespaces
NAMESPACE     NAME                   CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             100.64.0.1      <none>        443/TCP         16h
kube-system   kube-dns               100.64.0.10     <none>        53/UDP,53/TCP   16h
kube-system   kubernetes-dashboard   100.73.172.90   <nodes>       80/TCP          16h

```

```
[root@cloud kubernetes]# kubectl get svc --all-namespaces^C
[root@cloud kubernetes]# kubectl get events --namespace=kube-system
LASTSEEN   FIRSTSEEN   COUNT     NAME                        KIND      SUBOBJECT   TYPE      REASON       SOURCE            MESSAGE
1s         16h         26052     kube-dns-2247936740-j6pq1   Pod                   Warning   FailedSync   {kubelet cloud}   Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-2247936740-j6pq1_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-2247936740-j6pq1_kube-system(472b334c-9dd4-11e6-bb85-002219c0946b)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

2s        16h       3302      kubernetes-dashboard-1655269645-km0gq   Pod                 Warning   FailedScheduling   {default-scheduler }   pod (kubernetes-dashboard-1655269645-km0gq) failed to fit in any node
fit failure on node (cloud): PodToleratesNodeTaints


```
##### Expected result

want to login the kube dashboard from external broswer.
##### Comments

May need the help to have a look. Thank you

**Comment by colemickens** [comment]
It would have been useful to have described the kubernetes-dashboard pod, but it looks like it's not getting scheduled because of taints you have on your nodes.

The Unauthorized error is not a bug (and is again a different Issue, see this one for some details: https://github.com/kubernetes/dashboard/issues/964). You are trying to access the API server and you're not presenting any authentication. You could stick your client certificate into your browser and it would work, but using the proxy is easier. The other option is the same I've described twice already: put a reverse proxy up that has a load balancer and authentication on it and reverse proxies to the dashboard Service in the cluster.

**Comment by colemickens** [comment]
It looks like you only have a single node, the master, and you've tainted it as Unschedulable... That would be precisely why it's not getting scheduled. There's no where to put it...

**Comment by ensalty** [comment]
@colemickens  Thanks for your commets. I follow the http://kubernetes.io/docs/getting-started-guides/kubeadm/ to install the kubernetes on one physical server(CentOS 7). Then, I just want to see the dashboard web page.  Does that mean I need to create another nodes on other servers.

**Comment by ensalty** [comment]
I tried to run an sample ngnix the server and it looks like working. But the kube-dashboard has the error event output.


```
[root@cloud ~]# kubectl get events --namespace=kube-system
LASTSEEN   FIRSTSEEN   COUNT     NAME                        KIND      SUBOBJECT   TYPE      REASON       SOURCE            MESSAGE
3s         17h         27233     kube-dns-2247936740-j6pq1   Pod                   Warning   FailedSync   {kubelet cloud}   Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-2247936740-j6pq1_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-2247936740-j6pq1_kube-system(472b334c-9dd4-11e6-bb85-002219c0946b)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

34s       16h       3473      kubernetes-dashboard-1655269645-km0gq   Pod                 Warning   FailedScheduling   {default-scheduler }   pod (kubernetes-dashboard-1655269645-km0gq) failed to fit in any node
fit failure on node (cloud): PodToleratesNodeTaints

[root@cloud ~]# kubectl get events
LASTSEEN   FIRSTSEEN   COUNT     NAME                       KIND      SUBOBJECT   TYPE      REASON             SOURCE                 MESSAGE
3s         34s         7         my-nginx-379829228-0d3tr   Pod                   Warning   FailedScheduling   {default-scheduler }   pod (my-nginx-379829228-0d3tr) failed to fit in any node
fit failure on node (cloud): PodToleratesNodeTaints

3s        34s       7         my-nginx-379829228-6tc7i   Pod                 Warning   FailedScheduling   {default-scheduler }   pod (my-nginx-379829228-6tc7i) failed to fit in any node
fit failure on node (cloud): PodToleratesNodeTaints

34s       34s       1         my-nginx-379829228   ReplicaSet             Normal    SuccessfulCreate    {replicaset-controller }   Created pod: my-nginx-379829228-6tc7i
34s       34s       1         my-nginx-379829228   ReplicaSet             Normal    SuccessfulCreate    {replicaset-controller }   Created pod: my-nginx-379829228-0d3tr
34s       34s       1         my-nginx             Deployment             Normal    ScalingReplicaSet   {deployment-controller }   Scaled up replica set my-nginx-379829228 to 2
```

**Comment by ensalty** [comment]
localhost:8001

![image](https://cloud.githubusercontent.com/assets/5126301/19834313/92fc6c2a-9e94-11e6-9afc-62918a8675ca.png)


localhost:8001/ui
![image](https://cloud.githubusercontent.com/assets/5126301/19834317/aa39f308-9e94-11e6-9150-25a4934228fd.png)

**Comment by colemickens** [comment]
No, it says it scaled the deployment up to two pods, but it doesn't look like they're running. It says *right there* in the output: "my-nginx-379829228-6tc7i   Pod                 Warning   **FailedScheduling**".

Yes, you either need to add more nodes or you need to remove the taint and mark the node as schedule-able if you want Pods to start.

**Comment by ensalty** [comment]
@colemickens  Sorry, I felt a little puzzled. Do you know how to add more nodes or it need extra pythical server? I used the kube 1.4 version.  I follow the documents to set up it step by step. Is there any documents or link that I can follow to start with?

**Comment by ensalty** [comment]
![image](https://cloud.githubusercontent.com/assets/5126301/19835291/3aa8b560-9ebc-11e6-8959-3dcc9ef7c5dc.png)

As the documents shows that the dashboard should be set up after following the yaml.

**Comment by cheld** [comment]
CC @bryk 

I see two parts in this issue:
1. Improve kubeadm documentation
2. Add a 'toleration annotation' to kubernetes-dashboard.yaml to ignore taint and allow deployments on master. I assume that most users expect that dashboard is a similar thing as e.g. kube-dns which is also deployed on master. In other words I would suggest that all pods of kube-systems can be deployed on master. WDYT?

**Comment by bryk** [comment]
> 2. Add a 'toleration annotation' to kubernetes-dashboard.yaml to ignore taint and allow deployments on master

How can we do this? Can you provide links to some docs?

> I assume that most users expect that dashboard is a similar thing as e.g. kube-dns which is also deployed on master. In other words I would suggest that all pods of kube-systems can be deployed on master. WDYT?

I'd allow running Dashboard UI on master, but don't force it. Is such thing even possible? Dashboard can run basically anywhere, so I wouldn't restrict it to only masters.

**Comment by cheld** [comment]
With a toleration. I have already tested it and it works exactly as you suggest. I will create a PR. 

After the change Dashboard will be deployed on any node. (Most likely not master because many pods run on it after installation)

**Comment by cheld** [comment]
I will provide links with pr

**Comment by colemickens** [comment]
Why is this desirable? I definitely do not want this behavior for my dashboard deployments.

**Comment by cheld** [comment]
Could you explain?

**Comment by bryk** [comment]
If this turns out to be controversial, we could make it a commented-out configuration option in our YAML files.

**Comment by colemickens** [comment]
My master is marked unschedulable. I don't want things scheduled on it. I don't want any anything other than the master components running on it.

To be honest, my concern is that this is being done for single node clusters... but if the user has the master marked unscheduable then basically every single thing they try to deploy is going to fail to schedule anyway.

Either way, I can either remove the toleration from the yaml or leave it commented out, it's not really that big of a deal to me. I vendor my own copy of the dashboard files anyway for posterity.

**Comment by cheld** [comment]
Most users want Dashboard to be deployed. Setting up master first and validating that everything works before adding worker nodes is a possible workflow with kubeadm. So, considering the many problems I would rather make it simple, for the moment. Minimizing master for production would apply for dns too,  I assume. 
Anyway, overall the problem is rather related to kubeadm documentation. I will create a PR for it too.

**Comment by bweston92** [comment]
@cheld you know where the PR as I have this issue?

**Comment by colemickens** [comment]
Is there at least a way to taint the master after the fact to mark it as unscheduable in the same way that `--register-scheduable=false` works? I understand the desire for quick validation, but not at the expense of a reliable setup for real clusters built out with `kubeadm` -- I don't want dashboard or anything else potentially acting up and interfering with the master.

**Comment by bryk** [comment]
> I understand the desire for quick validation, but not at the expense of a reliable setup for real clusters built out with kubeadm -- I don't want dashboard or anything else potentially acting up and interfering with the master.

Yes, I totally agree. The YAML install files we have here are mostly for devs and people trying out Kubernetes. The "real" config files are in kubernetes/kubernetes/addons repository and are custom made for specific providers. The configs there do not schedule on masters. 
Does this make sense?

**Comment by evgkarasev** [comment]
Most of those who trying to implement something on GKE have this issue. Please provide some workaround. Thank you!

**Comment by maciaszczykm** [comment]
Dashboard's part is already done:
https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml#L36

**Comment by naisanza** [comment]
@colemickens so just to double check what you're saying is, that the dashboard should have been created on the node, not the master?

**Comment by naisanza** [comment]
@cheld did you have your pull request linked to this issue, so that others could follow along with how it's progressed?

**Comment by colemickens** [comment]
@naisanza it's an old issue, but if I recall correctly, `kubeadm` taints the master by default so that workloads won't normally run there. Since April though, it's possible that `kubeadm` now tolerates the taint on master to avoid this issue. I'm not sure, as I've not been paying a lot of attention in this area.

If you're having issues and you're not sure it's the same issue as this one, it might be best to open a new issue and describe your problem fresh.
