### ISSUE TITLE
UI enhancement: Rows per page

### ISSUE THREAD

**Issue by TerraTech** [kubernetes/dashboard#1387]
#### Issue details
Would like for "Rows per page" to be sticky between page reloads and navigation.

##### Environment
```
Dashboard version:  1.4.0  (gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0)
Kubernetes version: hyperkube-v1.4.5_coreos.0
Operating system: CoreOS (stable)
```

##### Steps to reproduce
Change the initial setting from 10 => 25, then reload the page or navigate to another menu selection.

##### Observed result

After reload, it will be reset to 10.

##### Expected result

Would like for it to remain at what I selected, in this case: 25

**Comment by nonotest** [comment]
this would be really good!

**Comment by floreks** [comment]
Closing in favour of #1703.
