### ISSUE TITLE
Show Horizontal Pod Autoscaler resource

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1389]
We should show HPA resources in the UI as described here: http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/

My opinion now is that we should show this as a property of a RS/Deployment, rather than a separate menu item.

**Comment by rf232** [comment]
hmm, technically a RS/RC/Deployment can have more than 1 HPA linked to it, so I think we do need to do something more like a normal resource instead of just as a property
