### ISSUE TITLE
Application theming

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#139]
We should think about good way to handle global css theming (fonts, elements coloring) as angular material supports theming only for very few ng elements. Currently global fonts colors are kept inside `assets/styles/_color_variables.scss` file.

From what I've found there are 2 options:

1. Write custom service to extend `$mdThemingProvider` and allow using attributes like `md-primary` on other elements and additional `md-hue-x` to color fonts based on defined color palette.
2. Define custom scss files with colors variables, import them in specific module and apply to custom css rules on elements.

First approach would be more clean to use, but requires much effort to implement and test. Second approach is easy to use but requires more custom css rules and styling.

What do you think?

@bryk, @maciaszczykm, @cheld, @batikanu, @zreigz  add more if needed

**Comment by cheld** [comment]
@seb36

**Comment by cheld** [comment]
I cannot answer your question directly. However, Sebastien, will look at dashboard this or next week. I will discuss requirements with him.

**Comment by floreks** [comment]
For now this is resolved using `_variables.scss` with some global style configuration.
