### ISSUE TITLE
How to view logs of crashed pods?

### ISSUE THREAD

**Issue by aliakhtar** [kubernetes/dashboard#1393]
If a pod crashes and restarts, and I view its logs in the dashboard, they only show the logs after the restart.

Is it possible to view the logs from before the restart, i.e from the crash?

`kubectl logs -p` is how to view these logs from the command line

Clicking the previous / next buttons in the dashboard doesn't refresh the logs

**Comment by bryk** [comment]
Sounds like a nice feature request. @aliakhtar should this be enabled by default or a toggle-able option? What's your workflow on this? 

API reference: http://kubernetes.io/kubernetes/third_party/swagger-ui/#!/api%2Fv1/readNamespacedPodLog

**Comment by aliakhtar** [comment]
@bryk The use case is to share logs with my colleagues who aren't familiar with k8s. I'm on a team where everyone pushes their services in a docker image. If someone's service is failing, I share the link to view the logs of their pod with the person responsible, so they can debug.

Yesterday we had a problem where someone's pod was crashing as soon as it started, but because it wasn't possible to view the crashed pod's logs on the dashboard, I had to copy and paste them into slack (and it was a loooong stacktrace)

I think it should be toggleable. Ideally if there could be a list of previous crashes and a link to view the logs from any crash, that would be awesome. If not, then just clicking the previous button when viewing logs, would work.

**Comment by amibenson** [comment]
Any feature in place for this? Would be great if could specify -p 2 as in show log of a crashed pod 2 restarts ago.

**Comment by frankgreco** [comment]
any update on this?

**Comment by cheld** [comment]
Fixed in https://github.com/kubernetes/dashboard/pull/2392
