### ISSUE TITLE
Rename PetSet to StatefulSet 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/dashboard#1395]
@bryk In k8s 1.5 we're renaming PetSet to StatefulSet. We should do the rename in dashboard too (both frontend and backend). 

@kow3ns @foxish @erictune

**Comment by bryk** [comment]
Yes, we were aware of this.

**Comment by kow3ns** [comment]
@bryk would you guys like some help on the refactor?

**Comment by floreks** [comment]
Of course, any help is appreciated. We want to be in sync with k8s releases so it would be great to release dashboard 1.5 at the same time with StatefulSets already.

Thanks for your help!

**Comment by rf232** [comment]
I don't know to well exactly how go dependencies work, but I tried to do the refactor and I found out that our vendored libraries don't have the StatefulSet changes in kubernetes/kubernetes yet.

Also govendor doesn't tell me I can update those libs (we reference the kubernetes core source by looking at k8s.io/kubernetes) 

Does that mean that we need to wait till this refactor is moved to k8s.io repo somehow. And is that linked to actual releases?

**Comment by maciaszczykm** [comment]
@rf232 Basically our version of core code is inside our repository, so we have to update it to get newest changes. New ~1.5 core alpha has them, so we can make our alpha by updating dependencies and performing changes in code (switching from `PetSets` to `StatefulSets`) in one pull request. If we would make it, then our next release should be tagged with 1.5 alpha too, because it will be incompatible with <1.5 versions of Kubernetes.

**Comment by rf232** [comment]
hmm, updating dependencies to the versions from github master is /far/ from trivial, so if someone can help me/do that I would be very grateful :)

**Comment by erictune** [comment]
@caesarxuchao or @mbohlool could one of you take a look at how Dashboard is vendoring its libraries and suggest any best practices?

It looks like the only client they import directly from their source is k8s.io/kubernetes/pkg/client/unversioned

**Comment by floreks** [comment]
Maybe we should switch to [client-go](https://github.com/kubernetes/client-go) and clean up our kubernetes deps? We're mostly using old client Interface that is no longer available in newer version of k8s and a bit of kubectl code I think.

I can take care of that. It will take some time to refactor everything though.

**Comment by caesarxuchao** [comment]
client/unversioned is already removed from the main repo. I'll also recommend using client-go. However, there will be some frictions migrating to client-go. If `dashboard` is looking for a quick solution, the easiest thing to do is vendor the [internalclient](https://github.com/kubernetes/kubernetes/tree/master/pkg/client/clientset_generated/internalclientset).

One potential blocker for adopting `client-go` is that `client-go` defines its own API types, (e.g., client-go/api.Pod), though their definitions are exactly the same as the types defined in kubernetes main repo. It means dashboard needs to convert the types before using utility functions defined in the kubernetes main repo, e.g., [deploymentutil](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/deployment/deploymentdetail.go#L147). We plan to let client-go share the same types with the main repo, but that's going to take O(weeks) to happen.

**Comment by floreks** [comment]
@caesarxuchao It helps a lot, thanks! I'll try with `client-go` first and if it's too much work then use `internalclient` for now and keep working on adapting our code to use `client-go`.

**Comment by floreks** [comment]
I do have one concern though. If we want to rename `PetSet` -> `StatefulSet` then we have to use `client-go@v2.0.0-alpha.0`. It is stable enough to use? How compatibility matrix looks like for this version?

@caesarxuchao @rf232

**Comment by caesarxuchao** [comment]
Don't use v2.0.0-alpha.0. It still has apps/v1alpha1, which had graduated to v1beta1 in master.

Client code for apps/v1beta1 will be published  to client-go today, I can cut v2.0.0-alpha.1 after that. This version will be quite stable.

**Comment by floreks** [comment]
I've used `internalclient` for now because we are also using some utility functions from `cmdutil` and `deploymentutil`. Fetching these dependencies downloads most of k8s core repo anyway so we can stick with that for now and wait for better compatibility with `client-go`.

**Comment by caesarxuchao** [comment]
Sounds good. FYI, the signature of those utility functions will be changed soon (https://github.com/kubernetes/kubernetes/issues/35159#issuecomment-257371845), so you might have to go through the refactor once more.
