### ISSUE TITLE
Panic on startup CreateApiserverClient

### ISSUE THREAD

**Issue by peterdeka** [kubernetes/dashboard#1412]
#### Issue details
When the dashboard pod starts it immediately dies with a runtime panic.

##### Environment
```
Dashboard version: 1.4.2
Kubernetes version: 1.4.4
Operating system: CentOS 7
Node.js version:
Go version:
```

##### Steps to reproduce

1.  Launch the dashboard with `kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml`
2. Open the container logs

##### Observed result

- `kubectl describe pods` returns an infinite loop of _Created container_, _Started container_, _Error syncing pod, skipping: Failed to start container_

- the dashboard container logs contain the following:
```
Using HTTP port: 9090
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x4ecf12]
goroutine 1 [running]:
panic(0x15316a0, 0xc420014020)
	/usr/lib/google-golang/src/runtime/panic.go:507 +0x1b3
github.com/kubernetes/dashboard/src/app/backend/client.CreateApiserverClient(0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0xc420068090, 0x2044340, 0xc420437490)
	/usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/apiserverclient.go:48 +0x1d2
main.main()
	/usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:58 +0x2f1
```

##### Expected result
The dashboard to start.

##### Comments
It started and worked the first time, then after the first reboot of the node, this behaviour is persistent.
Fresh `kubeadm` installation.
Weavenet

**Comment by nick** [comment]
I had the same issue and with 1.4.1 too. 1.4.0 seems to work, though:

    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.4.0/src/deploy/kubernetes-dashboard.yaml

**Comment by luohoufu** [comment]
when i use kubeconfig , i get the issue like.

**Comment by cheld** [comment]
@floreks can you have a look

**Comment by floreks** [comment]
Yes, I'll investigate this issue.
