### ISSUE TITLE
Persistent Volumes list is limited to max 10 items

### ISSUE THREAD

**Issue by TerraTech** [kubernetes/dashboard#1422]
#### Issue details
We have 29 PVs, however the dashboard will only list the first 10 (regardless of pagination).

##### Environment
```
Dashboard version:  1.4.2  (gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.2)
Kubernetes version: hyperkube-v1.4.5_coreos.0
Operating system: CoreOS (stable)
```
This issue also occurred with: v1.4.0

##### Steps to reproduce
Have more than 10 PVs and load the list.

##### Expected result

List all defined PVs while respecting the pagination settings.

As an aside, the dashboard is correctly showing all 11 Persistent Volume Claims.

**Comment by bryk** [comment]
That's a serious problem. Thanks for reporting it. I'll investigate.

**Comment by bryk** [comment]
Fix will be available in next release.

**Comment by TerraTech** [comment]
@bryk Thank you!
