### ISSUE TITLE
Usage metrics

### ISSUE THREAD

**Issue by ianlewis** [kubernetes/dashboard#1423]
The purpose of this issue is to discuss the feasabity of collecting some kind of usage metrics for the dashboard UI.

Brought up originally here: https://github.com/kubernetes/dashboard/issues/1354#issuecomment-255637633

**Comment by bryk** [comment]
I'd really love to have this!

I remember having these discussion in the team and the consensus was that this is a hard technical problem in the environment we have. I.e., it is hard to collect metrics directly from the browser if users are running this in a non-Internet env. The same for collecting from the backend: if users run this in an isolated cluster, metrics would not get transmitted.

If anybody has ideas here, let us know. CC @rf232

**Comment by danielromlein** [comment]
Has anyone have any ideas around telemetry for Dashboard? I'd love to be able to pull in a UX researcher to both validate the decisions we've been making and shape what we choose to do in the future.
/ @rf232 @bryk @maciaszczykm @floreks

**Comment by IanLewis** [comment]
To answer @bryk's question I think this can be opt-in via a command line flag or something to the app in the Deployment and in that case we can assume they have access to the internet.

**Comment by cheld** [comment]
This might help: https://github.com/kubernetes-incubator/spartakus.

**Comment by floreks** [comment]
We don't really plan to automatically store and analyze information about how people use Dashboard. I don't think this will change unless we get many more contributors to be able to properly support such feature.

/close
