### ISSUE TITLE
Failed to start Dashboard container 

### ISSUE THREAD

**Issue by moshe0076** [kubernetes/dashboard#1426]
#### Issue details
Container failed to start with error:
Using HTTP port: 9090
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x4ecf12]

goroutine 1 [running]:
panic(0x15316a0, 0xc420014020)
	/usr/lib/google-golang/src/runtime/panic.go:507 +0x1b3
github.com/kubernetes/dashboard/src/app/backend/client.CreateApiserverClient(0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0xc420072090, 0x2044340, 0xc4204132e0)
	/usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/apiserverclient.go:48 +0x1d2
main.main()
	/usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:58 +0x2f1

##### Environment

```
Dashboard version:
1.4.2 and master
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Operating system:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Node.js version:
Go version:
```

##### Steps to reproduce

kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard-head.yaml

##### Observed result

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x4ecf12]

goroutine 1 [running]:
panic(0x15316a0, 0xc420014020)
	/usr/lib/google-golang/src/runtime/panic.go:507 +0x1b3
github.com/kubernetes/dashboard/src/app/backend/client.CreateApiserverClient(0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0xc420072090, 0x2044340, 0xc4204132e0)
	/usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/apiserverclient.go:48 +0x1d2
main.main()
	/usr/local/google/home/rfranken/k8s/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:58 +0x2f1
##### Comments

Thanks!

**Comment by floreks** [comment]
Should be fixed already in #1412. Try to delete downloaded image and pull latest one from DH [kubernetesdashboarddev](https://hub.docker.com/r/kubernetesdashboarddev/kubernetes-dashboard-amd64/tags/).

**Comment by moshe0076** [comment]
Hi,

Now I have a different problem:
 docker logs d11fd77c8a6b
Using HTTP port: 9090
Using apiserver-host location: http://127.0.0.1:8080
Creating API server client for http://127.0.0.1:8080
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get http://127.0.0.1:8080/version: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

but:
root@ip-172-31-41-165:~/kubernetes-test# curl http://127.0.0.1:8080/version
{
  "major": "1",
  "minor": "4",
  "gitVersion": "v1.4.5",
  "gitCommit": "5a0a696437ad35c133c0c8493f7e9d22b0f9b81b",
  "gitTreeState": "clean",
  "buildDate": "2016-10-29T01:32:42Z",
  "goVersion": "go1.6.3",
  "compiler": "gc",
  "platform": "linux/amd64"

Work.
Any idea?
Thanks

**Comment by IanLewis** [comment]
I'm pretty sure the dashboard doesn't run using host networking by default so 127.0..0.1 on the host and 127.0.0.1 from the container are different. You'll want to make sure you point to an accessable IP address that can be accessed from inside the container.

**Comment by Masber** [comment]
Hi @moshe0076,

is this issue fixed? could you please give some details about how to fix it?

thank you very much
