### ISSUE TITLE
Dashboard fails to delete a job

### ISSUE THREAD

**Issue by roadmapper** [kubernetes/dashboard#1429]
#### Issue details
When deleting a job in the dashboard, the delete does not complete and returns with an error from the API server: `api.DeleteOptions is not suitable for converting to "batch/v1"`
![k8s_job_delete_failed](https://cloud.githubusercontent.com/assets/1834410/20358725/e26d4e00-abfa-11e6-9594-9cf4261fdf4a.png)

##### Environment
```
Dashboard version: 1.4.2
Kubernetes version: 1.4.5
Operating system: CentOS 7
```

##### Steps to reproduce
1. Create a job
2. Attempt to delete the job object

##### Observed result
The delete operation fails and does not delete the job.

##### Expected result
The delete operation succeeds and deletes the job.

##### Comments
I tried looking through the source to find where the api.DeleteOptions is passed by the UI to the unversioned k8s Go client, but I didn't find anything that might be suspect. The job can be deleted from the API server directly by making a correct HTTP DELETE call or via kubectl.

**Comment by rf232** [comment]
Thanks for your attention to detail. 

We are aware of this issue, and are talking with core how to fix this.

kubernetes/kubernetes#36806

**Comment by floreks** [comment]
We could apply same fix for our deps as this is critical issue. It always takes much time to merge something into the core.

**Comment by bryk** [comment]
@rf232 Can you take care of this for 1.5?

**Comment by floreks** [comment]
My PR to core was merged so it's just the matter of updating our deps.

**Comment by rf232** [comment]
will do
