### ISSUE TITLE
Doubled headers in admin and config views

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1433]
![image](https://cloud.githubusercontent.com/assets/2823399/20390533/aa67fbe2-accf-11e6-89fb-dd74b197ddce.png)

![image](https://cloud.githubusercontent.com/assets/2823399/20390540/b10b7186-accf-11e6-9eec-8005549fc654.png)

Bug occurs in latest HEAD image.

**Comment by bryk** [comment]
Are you working on this? I can help if needed.

**Comment by maciaszczykm** [comment]
I'm fixing it right now.
