### ISSUE TITLE
Headers for empty resource lists are missing

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1436]
As in the screenshot. That's my fault, I'll fix this soon:

![selection_144](https://cloud.githubusercontent.com/assets/1159999/20391915/d5698f94-acd5-11e6-9f4f-40cf8e12ab93.png)

**Comment by maciaszczykm** [comment]
@bryk #1435 fixes issue on list pages, I suppose details pages have to be updated too.
