### ISSUE TITLE
Unstable CI

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1438]
I think we should do something about CI flakes. They occur mainly due to integration tests.

**Comment by rf232** [comment]
Agreed, this is really hampering our speed of development/merging

**Comment by bryk** [comment]
My thinking is that this is super important, but not release blocker, so we can remove it from 1.5 release kanban.

**Comment by maciaszczykm** [comment]
Previous issue is fixed, but still we do have too few Sauce Labs channels to run them on master and pull request branches.

**Comment by maciaszczykm** [comment]
We are encountering fewer problems with missing channels at the moment. I am closing it.
