### ISSUE TITLE
UI for managing RBAC-related resources

### ISSUE THREAD

**Issue by mlamina** [kubernetes/dashboard#1441]
Following #964, I would like to draft a feature that would allow users to manage [Roles, RolesBindings, ClusterRoles, and ClusterRoleBindings](http://kubernetes.io/docs/admin/authorization/) in the dashboard.

**Issue Goal**
Develop use cases, UI workflows and wireframes for managing RBAC resources.

**Mockups**
There are clickable mockups in [InVision](https://invis.io/AF9E3F55W#/206606225_RBAC__List_Of_Roles).

**Initial Thoughts on Workflows**
- Roles and ClusterRoles are almost identical in how they are used/created, so the UI could display them as one single concept that has a flag (cluster yes/no)
- The UI could be centered around Roles, meaning that users would be presented with a list of existing roles which contains buttons for CRUD operations
- Existing roles could then have a _bind_ action, allowing the user to grant a particular permission to a user or set of users
- In general, the UI could be a simplified, more user-friendly way to manage a cluster's access control by abstracting the raw concepts of Roles, RolesBindings, ClusterRoles, and ClusterRoleBindings 

CC @rf232 @bryk

**Comment by rf232** [comment]
cc @romlein

**Comment by rf232** [comment]
Great! Also I love that this explicitly is about managing the RBAC resources and *not* about the dashboard using and handling RBAC related like issue #964 describes. Please keep it that way!

**Comment by mlamina** [comment]
I agree. Deep integration of AuthN and AuthZ into the dashboard should be a separate topic.

**Comment by mlamina** [comment]
Two quick ideas for a simple UI...

"Landing page" showing a list of existing roles. If namespace is set to "*", the role is a ClusterRole:

![list of roles](https://cloud.githubusercontent.com/assets/474314/20413893/4490f2b4-ace4-11e6-888f-169c6eeb736c.png)

------------------
Clicking on one of the list items would lead to a detail view for a role:

![role details](https://cloud.githubusercontent.com/assets/474314/20413912/645fbdc8-ace4-11e6-9b90-bafbbd464e3b.png)

------------------

There were a couple of things that popped into my mind while creating the wireframes:

- Where in the main menu should we put this section of the dashboard? Since it's namespace-independent, I would put it right next to Nodes and Persistent Volumes under the Admin section?
- The only difference between Roles and ClusterRoles is that ClusterRoles apply to any namespace. In the UI, this could be represented by either choosing a namespace for a role or selecting "*".
- RoleBindings don't make sense without an existing (Cluster)Role, so for every exiting role there should be an action button for binding this role to users or groups.

**Comment by bryk** [comment]
> Where in the main menu should we put this section of the dashboard? Since it's namespace-independent, I would put it right next to Nodes and Persistent Volumes under the Admin section?


Yes, this should be somewhere under admin section. This is the place for global objects. 

> The only difference between Roles and ClusterRoles is that ClusterRoles apply to any namespace. In the UI, this could be represented by either choosing a namespace for a role or selecting "*".

Can you explain the difference of what belongs to a namespace and what not? This is especially important in the context of where to put the UI for it, as, historically, we have separation for namespaced and non-namespaced objects in the menu. We can, of course, break the tradition here if needed. 


Thanks a lot for this proposal. Looks really solid and I hope we can deliver it quickly! :) Feel free to ping this thread to speed up feedback flow :)

**Comment by mlamina** [comment]
So as far as I understand, there are **Roles** and **ClusterRoles**, both of which do the same thing: They define a set of permissions, so _what_ can be done to _which resource(s)_. The only difference is that a **Role** is restricted to a particular namespace, whereas a **ClusterRole** will apply to all namespaces when bound. [The docs](http://kubernetes.io/docs/admin/authorization/) contain some nice examples.

So in the context of the UI, both Roles and ClusterRoles are global objects; one is just more restrictive than the other.

**Comment by bryk** [comment]
> So in the context of the UI, I believe both Roles and ClusterRoles should be treated as global objects, even though a Role lives in a particular namespace and a ClusterRole does not.

Yes, I like this reasoning. Admin section would then be only for admin things. 

Once you get all input needed, can you write a design doc with proposal to this feature? The PR can be similar in layout to this one: https://github.com/kubernetes/dashboard/pull/589

**Comment by danielromlein** [comment]
@mlamina that InVision link isn't working for me for some reason. If you just copied the URL, try instead clicking the _Share_ link.

**Comment by mlamina** [comment]
Here you go: https://invis.io/AF9E3F55W#/206606225_RBAC__List_Of_Roles
Let me know if that works, then I'll update the link in the issue description

**Comment by danielromlein** [comment]
Sweet! Thanks @mlamina 👍

**Comment by mlamina** [comment]
@bryk Please check out the PR and let me know if this is what you had in mind!

**Comment by danielromlein** [comment]
@mlamina I think those wireframes are a great start. A product requirement doc like @bryk mentioned would help me as a designer figure out the best approaches for things (e.g. how many roles might there be in a cluster?). 
Since one of the goals of this issue was creating use cases, what more input do you need to go into detail with those?

**Comment by mlamina** [comment]
@danielromlein check out #1463 . It's only a template by now, but I'm working on it. The good thing is that there aren't too many use cases, so the whole thing will hopefully not become too big :)

**Comment by tanner-bruce** [comment]
The Tectonic UI for this is pretty nice

**Comment by v1k0d3n** [comment]
anything further on this, or is there a need for assistance with this? so far, i like the proposal but it's been sitting for a bit without any updates.

**Comment by virtuman** [comment]
wanted to follow up to check if this is something that anyone is already pursuing or if there was a decision to not work on it any further?

/remove-lifecycle rotten

**Comment by maciaszczykm** [comment]
It is already being done during Angular migration that we are working on with @floreks. We should be able to push it even further after migration will be done.

**Comment by tirumaraiselvan** [comment]
Hey, will this UI also show Users -> Roles . I.e can I see list of users and then for each user, all the roles that are granted to it?

**Comment by andrehp** [comment]
Is there any estimate when a preliminary version of this feature will be released?

**Comment by maciaszczykm** [comment]
@andrehp We are adding it during Angular migration. It is very early version. Look for anything at the beginning of 2019.

**Comment by therealsamlin** [comment]
do we have an update on this feature? _waiting anxiously_

**Comment by akhilputhiry** [comment]
Any update?

**Comment by maciaszczykm** [comment]
Not yet. We are working on getting the migration to the new Angular done. We have fairly limited resources, so I wouldn't expect it to be done soon. First, we want to release a new version with migration and changes done during it, then we will focus on other things like metrics API or this.

**Comment by danielwhatmuff** [comment]
+1

**Comment by elminsterjimmy** [comment]
+1

**Comment by rahulb3521** [comment]
@maciaszczykm Let me know if you require any help in the migration in terms of testing/developing any features

**Comment by maciaszczykm** [comment]
@rahulb3521 We would love to see some PRs from you if you are interested. First I'd recommend to help us writing some unit tests because we have a lot to do in that area after migration to the new Angular. Then we can discuss some features, once you will get to know the codebase better. What do you think?

**Comment by timblaktu** [comment]
@maciaszczykm I see no reference to this issue, a UI for RBAC, over on #5232. Can you comment on why this (#1441) was closed, and what is the status of this Proposal for a UI for managing RBAC resources?
