### ISSUE TITLE
Japanese translations for 1.5

### ISSUE THREAD

**Issue by rf232** [kubernetes/dashboard#1445]
We should have all our messages translated to Japanese for 1.5

**Comment by IanLewis** [comment]
@Yamagami-Takuma

**Comment by Yamagami-Takuma** [comment]
OK. I'll do this.

**Comment by IanLewis** [comment]
@Yamagami-Takuma Cool thanks. I'll review it when it's done.

**Comment by IanLewis** [comment]
@Yamagami-Takuma BTW. This is for 1.5 which is supposed to go out in 2 weeks (Dec 8 I think?) so just letting you know there is a bit of urgency.

**Comment by Yamagami-Takuma** [comment]
@IanLewis 
Yes. I will translate ASAP :)

**Comment by bryk** [comment]
@Yamagami-Takuma Thanks a lot! :)

**Comment by bryk** [comment]
Done via: https://github.com/kubernetes/dashboard/pull/1487

**Comment by Yamagami-Takuma** [comment]
@bryk  
Ah, sorry for my lack of explanation.  
There is another translation PR.
After #1494 is merged, this issue is closed :)

**Comment by rf232** [comment]
Thanks for the update, reopened issue to keep track :)

**Comment by cheld** [comment]
Thanks :+1:
