### ISSUE TITLE
Update docu for 1.5

### ISSUE THREAD

**Issue by rf232** [kubernetes/dashboard#1446]

**Comment by cheld** [comment]
CC @gertipoppel 

When is the planned release date of Kubernetes?

**Comment by bryk** [comment]
Docs are due by end of the week or Monday

https://github.com/kubernetes/features/blob/master/release-1.5/release-1.5.md

**Comment by cheld** [comment]
Ok, then Gerti cannot help as she is very busy this week.

**Comment by bryk** [comment]
Update log: PR sent https://github.com/kubernetes/kubernetes.github.io/pull/1793
