### ISSUE TITLE
Verify that the UI works on safari, firefox and IE

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1447]
A process to verify this for 1.5. @rf232 can you add this to the project?

**Comment by rf232** [comment]
Related to #794, close that one if the UI works on IE.

**Comment by IanLewis** [comment]
What can users expect for browser support again? What versions are supported?

**Comment by bryk** [comment]
Latest versions of evergreen browsers + latest IE

**Comment by bryk** [comment]
Re what is support: UI works there in sane way

**Comment by bryk** [comment]
Once #1481 is merged, we can close this. I did a roundtrip of all browsers and everything seems to work.
