### ISSUE TITLE
Online help / tutorials

### ISSUE THREAD

**Issue by GertiPoppel** [kubernetes/dashboard#145]
I would like to start a discussion about how online help / tutorials will/can be included in the dashboard. 

1. The links "Learn more" as indicated on the mockups are not yet implemented. 
2. Where should the texts be stored (close to the source code or in a separate "docs" folder (like in the K8S documentation)? 
3. Should the documentation be in markdown format and be generated as HTML during the software build (similar to the K8S doc)?
4. Are there any Google-specific writing guidelines for OSS online tutorials / docs describing a GUI?

**Comment by cheld** [comment]
I checked GCE. This UI has some similar links. The links open a new browser tab and the user ends up in the normal html user documentation. This documentation is not localized (at least not german). However, the german locale is passed in the URL. Overall, I think we can start simple.

If we want to do it fancy we could think about a central place with keys and urls. This might simplify url testing and url management.

**Comment by bryk** [comment]
CC @kenmoore 

> 2. Where should the texts be stored (close to the source code or in a separate "docs" folder (like in the K8S documentation)?

I agree with @cheld. We should start simple. So having docs in GitHub repository (e.g., 'docs' folder) is a good start. 

> 3. Should the documentation be in markdown format and be generated as HTML during the software build (similar to the K8S doc)?

This sounds good to me. 

> 4. Are there any Google-specific writing guidelines for OSS online tutorials / docs describing a GUI?

I have no answer for this question now. I think that we should default to what k8s core does, to be consistent with the ecosystem.

**Comment by cheld** [comment]
CC @taimir 

Ok, as first step lets add some 'hello world' markdown pages, enhance the build scripts and add links to the UI.

**Comment by taimir** [comment]
I'm working on what @cheld said just now :)

**Comment by GertiPoppel** [comment]
@maciaszczykm Guess this issue can also be closed. Is related to https://github.com/kubernetes/dashboard/issues/276

**Comment by maciaszczykm** [comment]
@GertiPoppel Thank you, closing.
