### ISSUE TITLE
Unify card headers across the UI

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1451]
Some cards have such headers:

![image](https://cloud.githubusercontent.com/assets/1159999/20436397/6e318f80-adb0-11e6-96b9-bacdd002dde1.png)

Some such:

![image](https://cloud.githubusercontent.com/assets/1159999/20436418/82fb1f76-adb0-11e6-8af8-f32599897d03.png)

Should we unify this? Is this for 1.5? @maciaszczykm @rf232

**Comment by maciaszczykm** [comment]
Yeah, I think that's not good. I like second version more. Should be quite easy to do, so 1.5 is realistic target.
