### ISSUE TITLE
Add "send feedback/report bug" button to the UI

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1456]
While reading https://github.com/kubernetes/dashboard/issues/1431 I realized that our users do not have easy way of reporting bugs and sending feedback when seeing an error.

We could add a button to error pages that'd report a bug on github with the stacktrace user saw. Or we could just add a generic "send feedback" button somewhere.

**Comment by IanLewis** [comment]
This is a great idea.

**Comment by maciaszczykm** [comment]
It's nice feature to work on. New issues can be created at:
https://github.com/kubernetes/dashboard/issues/new. 

Considering, that issues have following API:
https://developer.github.com/v3/issues/#create-an-issue

We can link to page with initially filled bug report:
https://github.com/kubernetes/dashboard/issues/new?title=bug_report&body=error_message

I'll try to add it to error pages.
