### ISSUE TITLE
Migrate to client-go

### ISSUE THREAD

**Issue by IanLewis** [kubernetes/dashboard#1457]
It may take a while but since the dashboard is essentially just a client application using the Kubernetes API, it would be good to migrate to the official Go client at some point.

Is this even feasible?

**Comment by bryk** [comment]
Yes, this should be doable. When we started the UI project there was no client-go project yet. That wa sthe reason.

**Comment by floreks** [comment]
We've discussed that already in #1395. Unfortunately at this point `client-go` can not be used by dashboard. We are using some utility functions available only in the core for now. Additionally there is a problem with object types that requires very much work to resolve. I have started to work on that and even have a branch but we have to wait until these issues are resolved.

**Comment by bryk** [comment]
> We are using some utility functions available only in the core for now.

Do you remember what functions are those?

**Comment by floreks** [comment]
`k8s.io/kubernetes/pkg/controller/deployment/util`, `k8s.io/kubernetes/pkg/kubectl/cmd/util` and probably `k8s.io/kubernetes/pkg/kubectl/resource`.

There might be something else though.

**Comment by IanLewis** [comment]
A cursory look also leads me to believe that it currently doesn't support exec/attach API which is required for #1345
