### ISSUE TITLE
Use richer material design icons library

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1460]
Currently we use the official material design icon library: https://material.io/icons/. It is, however, very limited in the number of icons there. We should evaluate other libraries, such as https://materialdesignicons.com, which have much more icons. 

cc @batikanu

**Comment by rf232** [comment]
Icons look nice, we might need to do quick check about how https://opensource.org/licenses/OFL-1.1 works for us, especially combined with the fancy GKE autoinstall of the dashboard

**Comment by maciaszczykm** [comment]
@bryk @rf232 Have you checked if we can use this icon library?

**Comment by maciaszczykm** [comment]
We were not able to verify if we can use it, so pull request is already closed. I think we will keep current icon set and think about it once more in the future (for example during Angular migration). Closing.

**Comment by floreks** [comment]
No plans for icon set change for the foreseeable future.

/close
