### ISSUE TITLE
Translation guide for translators

### ISSUE THREAD

**Issue by IanLewis** [kubernetes/dashboard#1464]
We only have English :us: and Japanese :jp: translations. We should have a guide explaining how to provide new translations for the UI geared towards translators.

**Comment by IanLewis** [comment]
We use a kind of XML format for translations. I wonder if there is a way we could use standard gettext files so we could make use of translation platforms like [Transifex](https://www.transifex.com/).

**Comment by bryk** [comment]
The XML we use is also supposed to be standard-ish. So either we can use it or transform to gettext. Should be doable.

Re translating it to other languages: we'd need budget for it, so that's going to complicate things. But overall, I love the idea.

**Comment by IanLewis** [comment]
I was thinking more about trying to enable more open-source translation contributions by creating a guide rather than hiring vendors to do more translations.
