### ISSUE TITLE
Dashboard should present standardised dates (or make it an option)

### ISSUE THREAD

**Issue by mrwacky42** [kubernetes/dashboard#1470]
#### Issue details

I really would like to see ISO8601 dates in the dashboard.

##### Environment

```
Dashboard version: 1.4.0
Kubernetes version: NA
Operating system: NA
Node.js version: NA
Go version: NA
```

##### Steps to reproduce
Install v1.4.0, navigate anywhere in the UI, observe date formats

##### Observed result
23/11/16 HH:MM

##### Expected result
2016-11-23 HH:MM

##### Comments
If someone points me in the right direction and agrees that ISO8601 is the one true way <TM> I'm happy to try to make a pull request out of it.

**Comment by IanLewis** [comment]
This is really a localization issue IMHO. i.e. Date formats come from from the user's language.

I do think we should stick to 4 digit years in any case.

**Comment by bryk** [comment]
I can be convinced either way. Displaying dates in ISO8601 sound good.

**Comment by IanLewis** [comment]
Yah. I agree that it's not super important that the dates be localized and ISO8601 is much better than what we have currently.
