### ISSUE TITLE
Scrollbar is always visible

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1473]
It shouldn't look like this.

![image](https://cloud.githubusercontent.com/assets/2823399/20560826/956b50e4-b17b-11e6-90f9-dd65ea963d75.png)

**Comment by maciaszczykm** [comment]
Doesn't occur in all views.

**Comment by bryk** [comment]
How can I reproduce this? Just open namespace view?

**Comment by maciaszczykm** [comment]
Yes.
