### ISSUE TITLE
Gobal error dialog

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#148]
I would create a global error dialog that pops up in case of error. I assume that proper validation is in place and this error dialog is only shown in severe errors. 

I suggest to create a service implementation that adds a little bit of logic to $mdDialog. The error message dialog should have a localized title and a content area with the message from the server. This message is not localized and in many cases ugly. So, I would suggest to hide and only show after click on details button.

Usage like:
resource.save(
 ....
 (err) => {
      this.errorHandler_.open('a localized message', err);

}

**Comment by bryk** [comment]
@kenmoore Do you have any ideas on how to show global app errors? A dialog? Butter bar? Toast? I think that toasts is the thing for material design, isn't it?

http://designmodo.com/wp-content/uploads/2014/10/7.jpg

**Comment by bryk** [comment]
@cheld 
Global service is nice.
Dumping server error is a good start.

For full solution I'd consider having error codes and translations for them in the UI. This is the same how you handle errors in forms in Angular. For example, when deleting already deleted namespace, the server could return `alreadyDeleted` error code, and the UI will display appropriate (localized) message based on the code.

**Comment by cheld** [comment]
Thanks for the comments. I thought about toasts, as well. However, I have started with a pop-up, because GCE uses pop-ups (at least in case of an Internal Server Error)

I have already finished the implementation based on pop-up. I am just struggling with a typedef for Google Closure. I start with a simple PR and improve on that.

**Comment by maciaszczykm** [comment]
Closing as stale. We already have page for errors coming from server plus we have recently added warnings card. Still a lot to do in that area, but we should create new tasks for it.
