### ISSUE TITLE
Chrome and navigation - ver. 2 of the UX

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1485]
We should start thinking about our next iteration to the chrome and navigation UX. Theres a lot of issues we have with current UX, so we have space for improvements :) Ideally we should have this for 1.6 release. 

Non exhaustive list of issues:
* clutter and too many menu items: we have like 20 menu entries (and growing)
* no support for mobile (no responsiveness at all actually)
* global components like search or user settings are not defined 
* no icons 

cc @danielromlein @normalnorman

**Comment by bryk** [comment]
FYI, I've found a nice example of how material nav can be done. If you have Google account you can check it our at: https://myaccount.google.com/preferences

Sample screenshot of how they mix cards and nav there: 

![image](https://cloud.githubusercontent.com/assets/1159999/20603490/fd1d52d2-b261-11e6-9cfa-9162ba2f98fc.png)

**Comment by floreks** [comment]
Most points here are already covered in v2.

/close
