### ISSUE TITLE
Dashboard crashes when Service Account is used for authentication

### ISSUE THREAD

**Issue by kishorenc** [kubernetes/dashboard#1496]
#### Issue details

I get the following error when I configure the Dashboard to use the API server's secure port via the `apiserver-host` parameter (**insecure port works fine, though**):

```
Error while initializing connection to Kubernetes apiserver. 
This most likely means that the cluster is misconfigured (e.g., it has invalid 
apiserver certificates or service accounts configuration) or the --apiserver-host 
param points to a server that does not exist. Reason: 
Get https://foo.bar.com:6443/version: x509: failed to load system roots and 
no roots provided
```

On the API server logs, I see:

```
http: TLS handshake error from 10.0.2.245:56264: EOF
```

I followed the troubleshooting steps on this [page](https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md#service-account) and I was able to `curl` the API server on the secure port using a token from inside a test K8 container. However, the dashboard alone, when started, crashes with the error above.

What else could be going wrong? Do I need to pass any other arguments to the dashboard?

##### Environment

```
Dashboard version: kubernetes-dashboard-amd64:v1.4.2
Kubernetes version: v1.4.0
Operating system: Ubuntu 14.04
Go version: go1.6.3
```

**Comment by floreks** [comment]
It is cluster configuration issue.

Make sure that `ServiceAccount` plugin is enabled (apiserver argument) and that you have specified `--service-account-private-key-file` for `kube-controller-manager`.

Then delete default service account and secret in `kube-system` namespace (they will be recreated automatically). Delete dashboard pod and it should pick up.

Also you should specify custom SAN with IP of the main kubernetes service (usually 10.0.0.1) for you apiserver certificate.

Secure cluster configuration is quite complex. Not everything is described in kubernetes documentation. [Here](https://github.com/kubernetes/dashboard/issues/1287#issuecomment-250681546) you can find better description how to configure your cluster.

**Comment by kishorenc** [comment]
@floreks Yes, the `ServiceAccount` plugin is enabled and `--service-account-private-key-file` is also specified. I don't follow what you mean by `custom SAN` though. Are you saying that I should include the Kubernetes service IP (listed in `kubectl get services`) as one of the hosts when generating the API server certificate?

**Comment by floreks** [comment]
Yes, check `Certificates Configuration` section of my post (link above).

**Comment by kishorenc** [comment]
@floreks - That worked, thanks! I had to add the kubernetes service IP to the cert, and as we all as delete the older secret tokens (they were regenerated automatically).
