### ISSUE TITLE
Nav Icons (top-level objects only)

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/dashboard#1505]
Jennifer Kim, visual designer on the Google Cloud Platform team, has put together these [icon options](https://invis.io/XM9JJ2Z8B) for the top-level navigation items in Dashboard. 

This builds on the groundwork laid in [#789](https://github.com/kubernetes/kubernetes.github.io/issues/789), and will allow us to introduce a pattern where the side nav is collapsible.

**Comment by IanLewis** [comment]
I don't see the comments in the mockup 😞

**Comment by danielromlein** [comment]
@IanLewis I'll remove that part for now – she's going to be commenting soon.

**Comment by IanLewis** [comment]
Oh ok cool. I was too quick ;)

**Comment by bryk** [comment]
@danielromlein @IanLewis @rf232 @olekzabl @mijajasinski  Can you look at the icons and comment which you like?

**Comment by IanLewis** [comment]
> @danielromlein @IanLewis @rf232 @olekzabl @mijajasinski  Can you look at the icons and comment which you like?

Done.

**Comment by danielromlein** [comment]
> @danielromlein @IanLewis @rf232 @olekzabl @mijajasinski Can you look at the icons and comment which you like?

Done.

**Comment by danielromlein** [comment]
@bryk what's the latest on this? I'd like to get Jennifer feedback so she can continue to make progress.

**Comment by bryk** [comment]
I think Invision has all the feedback we have.

**Comment by maciaszczykm** [comment]
Closing as stale. InVision link doesn't work anymore.
