### ISSUE TITLE
Add debug information to the frontend

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1507]
Dashboard UI should have the option to show debug info layer in the browser. It'd say its version, which SHA commit it was built at and such. This info can then be passed when sending out feedback reports from within the UI. This should help a lot with debugging.

**Comment by IanLewis** [comment]
If we have a "report issue" button this kind of info could be automatically added to the bug report.

**Comment by dlsniper** [comment]
Would it be possible to start with something small like adding this extra information under the menu on the left side? I've tried upgrading the dashboard in GKE but I was clueless if it worked or not quite a while.
Thank you!

**Comment by cheld** [comment]
I think we need both: a menu entry and automatic collection from bug report dialot

**Comment by dlsniper** [comment]
Awesome! Thank you for fixing this!

**Comment by cheld** [comment]
I will do some more changes

**Comment by maciaszczykm** [comment]
@cheld Can we close it already?

**Comment by cheld** [comment]
Could be improved, but let's keep the current state. Can be improved later on
