### ISSUE TITLE
NodePort should not be the standard deployment

### ISSUE THREAD

**Issue by bronger** [kubernetes/dashboard#1513]
In the [YAML file for deploying Dashboard on k8s](https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml), the Dashboard is exposed by `type: NodePort`. While it is nice that it is *possible* to bypass any authentication (point (3) in the [troubleshooting guide](https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md#authentication-to-the-kubernetes-api-server)), I think that this is a dangerous *default behaviour*, especially for an admin tool.

**Comment by bryk** [comment]
We're already working on auth, so the problem would be solved here. But downgrading NodePort to ClusterIP may be a step in between.

@rf232 Can you comment?

**Comment by maciaszczykm** [comment]
Already changed.
