### ISSUE TITLE
k8s-dashboard1.4.1 can open at node but can't open at master 

### ISSUE THREAD

**Issue by zhaojigang** [kubernetes/dashboard#1517]
hi,
I install k8s-dashboard1.4.1 on centos7,then I find it can open at node but can't open at master 
k8s-version:1.4.6
k8s-dashboard:1.4.1
centos7

master's firewalld is closed

**Comment by bryk** [comment]
It is most likely that there is a problem with your K8s installation, not the dashboard itself. Try following the troubleshooting guide: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

**Comment by cheld** [comment]
closing as stale
