### ISSUE TITLE
support visualising Third Party Resources

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/dashboard#1519]
I tried creating a ThirdPartyResource using this example:  http://kubernetes.io/docs/user-guide/thirdpartyresources/ and nothing appears in the Dashboard.

I might be nice to detect them and show them as named resources in the nav bar on the left and at least show the names, labels & allow editing of the YAML?

One day it'd be awesome to allow UI plugins to render/edit them

**Comment by bryk** [comment]
Yes, that's super important feature request. We've already had initial discussions on this with @IanLewis and I guess basic support for this will be added soon.

**Comment by IanLewis** [comment]
@jstrachan Thanks for the feature request! I had created an issue earlier so I would say this is essentially a duplicate of #1504

**Comment by bryk** [comment]
Yeah, I'll close this as dupe.
