### ISSUE TITLE
Show the namespace of a PV

### ISSUE THREAD

**Issue by ankon** [kubernetes/dashboard#1522]
#### Issue details

On the console using `kubectl get pv` the PVs show their claim as "namespace/claimname", in the dashboard only the claimname is shown. This is confusing when you have multiple namespaces with the same claim name.

For example:
~~~~
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                           REASON    AGE
pvc-11111111-1111-1111-1111-11111111111  4Gi        RWO           Delete          Bound     master/data             12m
pvc-22222222-2222-2222-2222-22222222222   4Gi        RWO           Delete          Bound     branch/data                     2h
~~~~

##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.1
Kubernetes version: server v1.4.3+coreos.0/go 1.6.3; client v1.4.6/go 1.6.3
Operating system: server coreos in AWS, client Fedora Linux 
```

##### Steps to reproduce

1. Create a PVC with the same name in multiple namespaces
2. Create enough PVs to fulfill the PVCs

##### Observed result

Dashboard shows all PVs, but it is not possible to determine the namespace from the claim.

##### Expected result

Dashboard 'CLAIM' column matches kubectl CLAIM column.

**Comment by bryk** [comment]
This is a valid observation. @digitalfishpond Are you able to work on this for a while?

**Comment by digitalfishpond** [comment]
gratefully :)

**Comment by digitalfishpond** [comment]
I have moved to a new project within the Fujitsu organisation and will unfortunately no longer be able to devote any time to Dashboard. 

This issue is now unassigned.

**Comment by bryk** [comment]
Have fun @digitalfishpond!

**Comment by digitalfishpond** [comment]
Thanks @bryk ! it's been a pleasure and a privilege to work with you!
