### ISSUE TITLE
Documentation and dashboard is not clear how service types map

### ISSUE THREAD

**Issue by et304383** [kubernetes/dashboard#1523]
Didn't bother to fill in the template as this is really a matter of documentation or label updates.

It's not apparent that the service types map to ClusterIP, NodePort, or LoadBalancer.  The labels are internal/external, with a link to documentation on Kubernetes that does not contain either of these words.

It came up in the thread on #984 that it was confusing how these dropdown options map to actual types.

**Comment by maciaszczykm** [comment]
Closing as stale.
