### ISSUE TITLE
Add support for creating Stateful Set via the dashboard

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/dashboard#1527]
#### Issue details
I cannot create the Stateful Set via the kubernetes dashboard for now, it seems to be a feature enhancement?

##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

**Comment by IanLewis** [comment]
You should be able to create any kind of object via the create button in the upper right and uploading YAML. Is the issue that you can't do that?

**Comment by gyliu513** [comment]
Yes, but I want to use form, it is a bit complex for some end users input the full JSON/YAML string when want to deploy a stateful set, does there are any plan to support this?

**Comment by IanLewis** [comment]
There has been some discussion but tbh given the number of different types of objects there are and that object creation is pretty low on the list of things most users want to do, the priority for something like that is pretty low.

**Comment by gyliu513** [comment]
thanks @IanLewis for the notification, we can take this as low priority for now, but really hope that the dashboard can have forms for all of the kubernetes objects, not everyone is JSON/YAML expert ;-)

**Comment by maciaszczykm** [comment]
Closing as we'll track it from #1600.
