### ISSUE TITLE
Add support for creating namespace in dashboard

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/dashboard#1528]
#### Issue details
As an admin, I want to create namespaces via the kubernetes dashboard.
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

**Comment by maciaszczykm** [comment]
It's already possible, go to create page, open advanced options and in the namespaces combobox you'll find option to create new namespace. 

It's hidden, but better support for creating resources from Dashboard is on the roadmap.

**Comment by gyliu513** [comment]
Thanks @maciaszczykm , it is not easy to find this ;-( , but anyway, it works for now.

**Comment by maciaszczykm** [comment]
Yeah, we are aware of it.
