### ISSUE TITLE
State name import - closure compiler dependency errors

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#153]
Currently there is a problem with importing `stateName`. I will give an example:

In `replicasetdetail_controller.js` we import `stateName` from `replicasetlist_state.js`.
In `replicasetlist_controller.js` we import `stateName` from `replicasetdetail_state.js`.

This results in frontend build error.

Unfortunately compiler does not provide good information about real cause of error. It's similar to this:
```
ERROR - required "module$replicasetlist$replicasetlist_state" namespace not provided yet import {stateName} from 'replicasetlist/replicasetlist_state';
```

Real cause is due to circual dependency between modules as I've described here: https://github.com/floreks/dashboard/commit/ad6c93803d09efd0fcc0020d931ee1cf507386e5#commitcomment-14899972

I've tested this in different case for `zerostate` and `replicasetlist` modules and the result is the same.

For now only solution I've in mind requires creation of new module or new file independent of current modules where we can keep state names. 

Any other ideas?

**Comment by bryk** [comment]
Generally, the compiler is right. It does not allow for circular dependencies. However, the message is very misleading. Thanks @floreks for investigating. 

I guess that our design with having state name and logic in foo_state.js files is wrong and this causes circular deps. I think we should redesign this.

**Comment by bryk** [comment]
@floreks Can you take this issue? As our code gets more and more complex, I see TODOs for this issues a lot. 

We basically need some kind of proposal of how to rearrange files so that we dont have circular deps (this is a benefit anywany).

At minimum, we need to place state names and state params in a file that does not import anything else (well, except for maybe some model classes).

**Comment by bryk** [comment]
@cheld @floreks FYI

**Comment by floreks** [comment]
I can take care of this but at the beginning of next week, so if anyone wants to take this sooner then be my guest ;)

**Comment by floreks** [comment]
This is fixed. Closing.
