### ISSUE TITLE
Dashboard reported Service Unavailable (503)

### ISSUE THREAD

**Issue by raghavendrapj** [kubernetes/dashboard#1535]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'dial tcp 172.42.83.3:9090: getsockopt: no route to host'
Trying to reach: 'http://172.42.83.3:9090/api/v1/appdeployment/protocols'
```

**Comment by rf232** [comment]
Hello @raghavendrapj, this looks like an installation/setup issue, can you follow the troubleshooting guide and see if that fixes your problem:

[docs/user-guide/troubleshooting.md](https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md)

I close the issue now, please reopen if it doesn't fix the problem
