### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by 327101303** [kubernetes/dashboard#1536]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
Get https://192.168.3.1:443/api/v1/namespaces/default/pods: x509: certificate signed by unknown authority

```

**Comment by 327101303** [comment]
Dashboard reported Internal Server Error (500)

**Comment by bryk** [comment]
Thanks for reporting the issue. The problem is with your cluster, not the UI itself. The cluster cert is signed by unknown authority. Refer to installation guide of Kubernetes clusters to fix this.
