### ISSUE TITLE
dashboard 1.5 unknown logs prefix appears 

### ISSUE THREAD

**Issue by Slahser** [kubernetes/dashboard#1546]
##### Environment

```
Dashboard version: 1.5
Kubernetes version: 1.5.1 
Operating system: Centos 7.2

```

##### Steps to reproduce

compare dashboard log panel with `kubectl logs xxx`

##### Observed result

i.e. 2017-03-15T10:02:38.48196648Z appears in dashboard log panel.

##### Expected result

maybe there is some ways to disable the prefix display?

##### Comments

**Comment by IanLewis** [comment]
@Slahser The screenshot of the dashboard doesn't seem to be viewable. Could you either re-upload your screenshot or expand on what the issue is?

**Comment by maciaszczykm** [comment]
@Slahser What is unknown prefix? By default Dashboard displays log message time, i.e. `2017-03-15T10:02:38.48196648Z`. We cannot see the screenshots. Please reopen issue if it still occurs.

**Comment by Slahser** [comment]
oh sorry i ignored this issue... 

just like @maciaszczykm say ,it maybe `2017-03-15T10:02:38.48196648Z` , can we have a feature toggle here?

**Comment by maciaszczykm** [comment]
Okay, we'll check.
