### ISSUE TITLE
Create fails with the default config (no named 

### ISSUE THREAD

**Issue by sandcastle** [kubernetes/dashboard#1547]
#### Issue details
When trying to setup dashboard on a fresh kops install, using the recommended script on this repo in the readme I get an error.

##### Environment

```
Dashboard version: github master
Kubernetes server version: 1.4.7
Kubernetes client version: 0.20.1
Operating system: macOS
Go version: 1.7.4 darwin/amd64
```

##### Steps to reproduce
When running the recommended install step from the readme.md in this repo:

```
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```

##### Observed result
The following error occurs:

```
unable to recognize "https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml": no kind named "Deployment" is registered in versions ["" "extensions/v1beta1"]
```

##### Expected result
The service should be created.

**Comment by IanLewis** [comment]
Do you not have beta extensions enabled? See https://github.com/kubernetes/kubernetes/blob/master/docs/api.md#enabling-resources-in-the-extensions-group

**Comment by cheld** [comment]
closing as stale
