### ISSUE TITLE
Buttons in logs view disappear after decreasing window width

### ISSUE THREAD

**Issue by olekzabl** [kubernetes/dashboard#1548]
#### Issue details

On the logs page for a pod, there are two buttons governing font style:
![kplwkm8vkm9](https://cloud.githubusercontent.com/assets/17475944/21562091/aa44f904-ce75-11e6-951b-1bb3f944c5d9.png)

However, after decreasing window width, they disappear:
![k0oqq3gfcrm](https://cloud.githubusercontent.com/assets/17475944/21562097/c02351c6-ce75-11e6-8ecf-669a0a846926.png)
In that case, their functionality seems unreachable.

##### Environment
Dashboard version: 1.4.0
Kubernetes version: 1.4.7
Operating system: Linux
Node.js version: 5.11.1
Go version: 1.7.3

**Comment by maciaszczykm** [comment]
We will track from #1828.
