### ISSUE TITLE
Dashboard reported Service Unavailable (503)

### ISSUE THREAD

**Issue by HeTaixiang** [kubernetes/dashboard#1555]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'EOF'
Trying to reach: 'http://10.2.58.2:9090/api/v1/pod/kube-system/kube-apiserver-192.168.1.236/log'
```

**Comment by IanLewis** [comment]
Your Kubernetes cluster is likely not currently configured correctly. Please see the troubleshooting doc: https://github.com/IanLewis/dashboard/blob/master/docs/user-guide/troubleshooting.md

**Comment by maciaszczykm** [comment]
Closing as stale. Reopen if needed and please provide us more details.
