### ISSUE TITLE
Kube dashboard installation sync issue

### ISSUE THREAD

**Issue by githubvick** [kubernetes/dashboard#1557]
#### Issue details
I have setup a Kube cluster up and running. The pods and everything work fine. I'm trying to setup the Kube dashboard. But facing issues while doing so.

##### Environment

```
Versions: Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"86dc49aa137175378ac7fba7751c3d3e7f18e5fc", GitTreeState:"clean", BuildDate:"2016-12-15T16:57:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"86dc49aa137175378ac7fba7751c3d3e7f18e5fc", GitTreeState:"clean", BuildDate:"2016-12-15T16:57:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
OS Version:Linux kubemaster 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

##### Steps to reproduce

I run the command as described in the document **sudo kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml**

##### Observed result

I get the error in journal -xe

 _Error syncing deployment kube-system/kubernetes-dashboard: Operation cannot be fulfilled on deployments.extensions "kubernetes-dashboard": the object has been modified; please apply your changes to the latest version and try again_

##### Expected result

To install dashboard without errors.

##### Comments

I have tried cleaning up the system by deleting all pods, services, deployments in the namespaces kubesystem. But still doesn't work.

**Comment by IanLewis** [comment]
What do you mean by doesn't work? AFAIK this error happens only when updating an existing object but the resource versions are incorrect as to have created a race condition.

Do you have something that runs dashboard in your kubelet manifests directory? usually /etc/kubernetes/manifests. That would need to be updated or removed.

**Comment by githubvick** [comment]
I was able to get this working. The above error message still occurs but seems like it doesn't affect and it was a port issue because of which it didn't work earlier. Thanks
