### ISSUE TITLE
Support cronjobs

### ISSUE THREAD

**Issue by luispabon** [kubernetes/dashboard#1562]
Would be great if Dashboard would support cronjobs in the same way it supports jobs (cronjobs being a level above jobs).

**Comment by IanLewis** [comment]
We probably want cronjobs to go at least beta before implementing this.

**Comment by libnux** [comment]
It seems that Cronjobs will go beta in 1.6 release according to the following issue in 1.6 milestone:

https://github.com/kubernetes/kubernetes/issues/41039

**Comment by floreks** [comment]
@luispabon Good idea. We'll look into that after the release.

**Comment by libnux** [comment]
Unfortunately , cronjobs' going beta postponed to v1.7.

**Comment by silverkorn** [comment]
Greetings!
Any updates?

**Comment by oscarbatori** [comment]
Is there an open PR for this, or is there design work required to figure out where this sits in the `Dashboard` UI? `CronJob` doesn't seem to fit neatly into any of the existing tabs.

**Comment by maciaszczykm** [comment]
@oscarbatori We can always introduce new tab, but you are right. We need to discuss it a bit before implementing it.

**Comment by oscarbatori** [comment]
@maciaszczykm is this the appropriate forum for discussing features, or is `JIRA`/mailing-list used for that?

I think `cronjobs` just below `pods` would probably do the trick. I think probably critical information to replicate `kubectl get` functionality:
1. schedule
2. name
3. suspend
4. active

Also, we might want to look at separating `cronjob` `pods` from longer running `pods`. As an example, it's pretty easy to see how a litany of `cronjobs` could end up polluting the `pod` list with the status of transient pods:
<img width="1089" alt="screen shot 2017-07-25 at 9 53 07 am" src="https://user-images.githubusercontent.com/1596348/28575529-2ce4e45e-711f-11e7-859b-0132253df192.png">

**Comment by maciaszczykm** [comment]
> @maciaszczykm is this the appropriate forum for discussing features, or is JIRA/mailing-list used for that?

@oscarbatori It is a good place. 

I will take a look on your proposal later.

**Comment by oscarbatori** [comment]
@maciaszczykm thanks! Feel free to reach out if you want some help!

**Comment by maciaszczykm** [comment]
@oscarbatori We have updated our Kubernetes deps to 1.7.2 so it is a good time to start working on it. Are you willing to do so? We can guide you if you want. Just start with the backend and take Replica Sets as an example. Cron Jobs have to be in Workloads menu which we keep sorted alphabetically.

**Comment by oscarbatori** [comment]
@maciaszczykm yes, I can take a look this weekend!

Do you use Gitter? Just in case questions come up.

**Comment by floreks** [comment]
You can find us on: https://kubernetes.slack.com

**Comment by oscarbatori** [comment]
Swell, thanks guys!
