### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by von-Sanders** [kubernetes/dashboard#1564]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
Get https://10.0.0.1:443/apis/extensions/v1beta1/namespaces/default/replicasets: write tcp 172.17.0.2:48952->10.0.0.1:443: write: broken pipe

```

**Comment by IanLewis** [comment]
Your Kubernetes API server is not currently configured correctly. Please see the troubleshooting doc: https://github.com/IanLewis/dashboard/blob/master/docs/user-guide/troubleshooting.md

**Comment by maciaszczykm** [comment]
Closing as stale. Reopen if needed and please provide us more details.
