### ISSUE TITLE
From busybox instead of scratch ?

### ISSUE THREAD

**Issue by abourget** [kubernetes/dashboard#1567]
Would it be possible to base the image off of `busybox` instead of `scratch` ? It makes it difficult to debug the image when it fails otherwise.

**Comment by bryk** [comment]
We use scratch image for security reasons and we know that it is not good for debugging.

Would better logs from dashboard help you? What was your use case for debugging?

@rf232 Can you comment/suggest something here?

**Comment by abourget** [comment]
I figured out through the host, that the serviceaccount secrets mount was
empty.. would have like to be able to exec in and check from `kubectl exec`.

My issue is fixed now.. I think the logs did say _No such file or
directory_, so I guess we can close this if it doesn't come up elsewhere.

**Comment by IanLewis** [comment]
@abourget What did you do to solve the issue? Is there a way to reproduce the issue you saw?

**Comment by abourget** [comment]
The issue was with a self-hosted kubelet, started with bootkube. It's an
experimental mode, and an issue I bumped into was that it did not properly
mount the service account volume, and so I had an error with the dashboard.
Since it is unrelated to the dashboard itself, I'd close this :)

Thanks for following up!

**Comment by IanLewis** [comment]
Ok. Cool. I'll look a little into the error messages that come up when a service account isn't set up properly in dashboard and see if the errors can't be improved.

**Comment by cheld** [comment]
@abourget I think self-hosted kubelet uses --containerized flag (https://github.com/kubernetes-incubator/bootkube/issues/96) which had (maybe still has) issues (https://github.com/kubernetes/kubernetes/issues/26943) Is this the problem?

@bryk out of curiosity, could you elaborate a bit on the security ? Is it a general issue or specific for Dashboard?

**Comment by abourget** [comment]
Yes I think it was related to self-hosted kubelet.

**Comment by cheld** [comment]
If you enable shared mount propagation for docker than it should work (it is described in upper issue)

**Comment by bryk** [comment]
> @bryk out of curiosity, could you elaborate a bit on the security ? Is it a general issue or specific for Dashboard?

The scratch image usually does not have security holes in itself. On the contrary, when you base on ubuntu, it has, like, a few security holes every other week. This forces to constantly do updates of prod images, to apply fixes. When we base on scratch, we do not need to update it.

**Comment by cheld** [comment]
Closing as we are not going to change
