### ISSUE TITLE
Dashboard should load fast, even when heapster is unresponsive

### ISSUE THREAD

**Issue by marians** [kubernetes/dashboard#1572]
#### Issue details

We had the problem that the Dashboard would not load certain pages, like the list of all deployments in a namespace, within reasonable time (= seconds). Instead it took in the order of minutes to load these pages, making them effectively unusable. When they appeared, heapster graphs were missing.

Lacking any more information on the cause of the problem, we removed our heapster deployment entirely. Without heapster running, the according Dashboard views were loaded within the usual sub-second response time. Then, with heapster being re-deployed, everything remained functional, suggesting that heapster was the cause of the problem.

##### Environment

```
Dashboard version: 1.5.1
Kubernetes version: 1.5.1
Image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1
```

##### Steps to reproduce

Actually I have no idea how to reproduce this. Simulating this should be easy using an unresponsive mock service.

##### Observed result

- Views taking very long to load
- Missing heapster graphs
- No information about heapster problems

##### Expected result

- Reasonably load time of the page itself (< 5 seconds)
- Missing heapster graphs with information on heapster being unresponsive ("Cannot display metrics, as heapster could not respond within reasonable time").
- Asynchronous loading: Ideally the graph data would be loaded independent from the embedding page, so that the user can already use the page while the client still waits for heapster data.

**Comment by floreks** [comment]
Fixed by #2017. Metrics will be disabled now if initial request to heapster fails. No more unnecessary requests if heapster is not available in the cluster.
