### ISSUE TITLE
Pods which are "Terminated: Completed" wrongly show a "Pending" icon

### ISSUE THREAD

**Issue by tinselspoon** [kubernetes/dashboard#1574]
#### Issue details
In version 1.5.1 of kubernetes-dashboard, pods which are of state "Terminated: Completed" show a "Pending" icon. Version 1.5.0 of kubernetes-dashboard shows the correct icon.

##### Environment

```
Dashboard version: 1.5.1
Kubernetes version: 1.5.1
Operating system: CoreOS 1185.5.0
Node.js version: n/a
Go version: n/a
```

##### Steps to reproduce

1. Create a Job which will run once and complete successfully.
2. Once the Pod created by the Job completes, look at the list of Pods and observe the icon.

##### Observed result

The icon is "pending" despite the pod being completed successfully.
![1 5 1](https://cloud.githubusercontent.com/assets/9112859/22022403/c84c2ccc-dcb9-11e6-8dd7-d204f8142d07.PNG)

##### Expected result

The icon is a green tick as the pod completed successfully. This is the case on kubernetes-dashboard 1.5.0. The screenshot below is taken after rolling back the dashboard version to 1.5.0 and refreshing.
![1 5 0](https://cloud.githubusercontent.com/assets/9112859/22022397/c2a4cc16-dcb9-11e6-88ab-0a9ae26b3ff0.PNG)

##### Comments

Note that pods which are Terminated and Failed show the correct icon. It only appears to be the completed successfully state which has problems.

**Comment by IanLewis** [comment]
Fixed by #1595
