### ISSUE TITLE
Proposal: experimentally embed Weave Scope

### ISSUE THREAD

**Issue by lukemarsden** [kubernetes/dashboard#1577]
[Weave Scope](http://github.com/weaveworks/scope) provides orchestrator independent troubleshooting & debugging through visualisation. It has table and graph views. It includes Kubernetes integration to show pods, replica sets, deployments, services etc, including showing the live network connections between components in a graph, and also includes a terminal-in-the-browser to let you exec into a pod. Scope is 100% open source and this proposal is made in the spirit of a community effort.

Embedding Weave Scope into Dashboard addresses this topic from your [blog post](http://blog.kubernetes.io/2017/01/kubernetes-ux-survey-infographic.html).

> Troubleshooting & Debugging [...] is now our top area of investment. Currently in-progress is the ability to be able to exec into a Pod [...] One of a UI’s strengths over a CLI is its ability to show things, and the troubleshooting and debugging feature area is a prime application of this capability.
– http://blog.kubernetes.io/2017/01/kubernetes-ux-survey-infographic.html

In the SIG call today we discussed bringing these features to Dashboard via a Scope integration, and @bryk, @danielromlein and I provisionally agreed that an experiment to add Scope to Dashboard via a lightweight iframe integration would be a great way to gather user feedback. If this is successful (i.e. if we get good user feedback) we could later look at a deeper app-level integration.

Specifically, therefore I'm proposing that we, for this Phase I experiment:
1. Identify a location in the existing Dashboard UI for a "Scope (experimental)" or similar nav item.
2. When a user clicks that nav item, Dashboard determines whether the Scope probes and UI service are installed on the Kubernetes cluster. If they are not, it provides the user with a button to deploy these API objects into the kube-system namespace.
3. If they are, it simply includes the Scope UI within the "frame" of the Dashboard UI.

cc @bryk @danielromlein please correct me if I got any of this wrong :)

**Comment by danielromlein** [comment]
@lukemarsden FYI it's @bryk you want to mention 😉 
And technically "Kubedash" is a deprecated UI; the official UI for K8s is "Dashboard" – I should have clarified that on our call.
Otherwise this looks great! Thanks for tackling this so promptly and I'm excited to see this in the product!
/ cc @rf232

**Comment by bryk** [comment]
> Identify a location in the existing Dashboard UI for a "Scope (experimental)" or similar nav item.

@danielromlein I'm calling out you here. Do you have any idea of how/where we may place this?

**Comment by IanLewis** [comment]
I'm guessing that this wouldn't depend on weave and would be a feature similar to weave scope?

**Comment by danielromlein** [comment]
Regarding the best location, I have a few questions around use cases:

- Who is Scope most relevant for? Devs? Operators? It seems like to some extent both, but is it more valuable to one or the other?
- Would Scope respect the selected Namespace? If so, I think adding a top-level nav item below the selected Namespace would make sense.

![screen shot 2017-01-20 at 10 58 14 am](https://cloud.githubusercontent.com/assets/5114858/22155998/72d2a062-deff-11e6-8b59-1d68c39dabd0.png)
Scope is relevant to whatever Namespace you have, but is also more overview / top-level than all the rest of the non-admin nav items.
We could add an icon suggesting its visualization aspect once we incorporate the icons Google's working on.

**Comment by bryk** [comment]
@lukemarsden Can Scope and Dashboard UI interact? Can we set scope's url params or similar? From technical point of view this IFrame communication should work fine. I've done such things in the past.

**Comment by lukemarsden** [comment]
@IanLewis Correct, it wouldn't depend on Weave Net (assuming that's what you meant).

@danielromlein Scope is relevant to Dev and Ops in equal measure, I think. Scope has its own namespace selector, so we should put it "above" the Dashboard namespace selector in the IA, at least for this initial phase, IMHO.

@bryk You could set the Scope URL params from Dashboard, sure. Let's get it in there and then have a chat about how we might want to customize it? I'm also happy to pull in the Scope devs to answer deeper technical questions :)

**Comment by IanLewis** [comment]
@lukemarsden Yah. I just wanted to make sure we weren't adding something that only folks using Weave as their network solution could use.

**Comment by danielromlein** [comment]
>Scope has its own namespace selector, so we should put it "above" the Dashboard namespace selector in the IA

@lukemarsden cool, makes sense. So we'll include it as a child nav object of _Admin_ 👍

**Comment by lukemarsden** [comment]
I'll take a look at producing a PR later this week. But if anyone else wants to take a look, please don't wait for me :)

**Comment by danielromlein** [comment]
@lukemarsden any updates on this from your end?

**Comment by cheld** [comment]
cc @cheld

**Comment by vlal** [comment]
@danielromlein It seems the layout of the dashboard menu has changed. Where exactly should Scope appear in this new dashboard?

**Comment by danielromlein** [comment]
@vlal great question! The Dashboard side nav is in a bit of flux at the moment. We'll keep Scope in mind in any adjustments that get made, but it seems to me for now including it directly above the Namespace dropdown at the primary level makes sense?
![scope](https://cloud.githubusercontent.com/assets/5114858/24521369/eda6f442-1559-11e7-9d56-b783985aa84c.png)

WDYT @maciaszczykm @floreks?

**Comment by maciaszczykm** [comment]
@danielromlein @vlal I agree with Dan here. Let's keep it there and if we'll be doing any changes, then it's not hard to change.

**Comment by lukemarsden** [comment]
See https://www.youtube.com/watch?v=6f-JNoHrBN4&feature=youtu.be as a demo of #1949 working 😄

**Comment by maciaszczykm** [comment]
@lukemarsden Looks good! We will review it soon, but we also need @bryk opinion there.

**Comment by floreks** [comment]
It looks nice however I am not so sure if dashboard should be responsible for deploying integrations in the cluster this way. IMHO we should make integrations act like heapster or third party resources. If they are available in the cluster then show them in dashboard, otherwise we will have x additional entries for integrations in menu but only few will be actually used.

Other option is to introduce some additional page with list of supported integrations and option to deploy/delete or just enable/disable them. That would however require some settings page.

@danielromlein @bryk how in your opinion integrations should look like in dashboard?

**Comment by maciaszczykm** [comment]
> Other option is to introduce some additional page with list of supported integrations and option to deploy/delete or just enable/disable them. That would however require some settings page.

I like this option the most. We may add integrations page, where users could decide which integrations they would like to install and use. Putting all integrations like Scope or Helm in the menu can be confusing.

If integration page would be present then in my opinion there is nothing wrong with installing Scope or Helm in the cluster if user wants it.

Also, I think having integrations will be benefitial for both projects.

**Comment by cheld** [comment]
I wonder about the menu entry "Scope". I assume that most users have not heard of WeaveScope. Maybe we should put it and helm in a menu group called e.g. "Add-ons" or "Plugins". WDYT?

**Comment by danielromlein** [comment]
Very cool @lukemarsden! Thanks for sharing that. I'll need to research a bit more into what else might go on an _Integrations_ page, but my gut reaction is that that approach makes sense. Otherwise having such a different look-and-feel to one of Dashboard's menu items could be potentially confusing.

**Comment by maciaszczykm** [comment]
Will be covered in #1832 as we would like to be more generic, not destined only for one plugin but rather common interface for many of them.
