### ISSUE TITLE
Implement "Minimum CPU..." and "Minimum memory..." checkboxes on deploy contenerized app form.

### ISSUE THREAD

**Issue by vulpecula** [kubernetes/dashboard#158]
I am implementing "Minimum CPU..." and "Minimum memory..." checkboxes from: https://raw.githubusercontent.com/kubernetes/dashboard/master/designs/11-11-2015/14_deploy%20more.png

**Comment by floreks** [comment]
@bryk I guess this is already covered by #237. I think we can close.

**Comment by bryk** [comment]
Yes
