### ISSUE TITLE
Unable to select the whole manifest in edit mode

### ISSUE THREAD

**Issue by kargakis** [kubernetes/dashboard#1583]
I was unable to Ctrl+A a manifest in the dashboard and I couldn't find a way to export things.

**Comment by IanLewis** [comment]
@kargakis Am I right in assuming that you want to download the yaml for an object?

**Comment by kargakis** [comment]
@IanLewis yes, that's right

**Comment by IanLewis** [comment]
@kargakis We have an issue for a better YAML editor (#1221). Would your use case be solved by that or do you think a download feature is necessary?

**Comment by kargakis** [comment]
@IanLewis as long as I am able to easily copy/paste manifest, download is not necessary.

**Comment by maciaszczykm** [comment]
It is already done. We will include it in next official release (>1.6) and you can always check HEAD releases.

![image](https://cloud.githubusercontent.com/assets/2823399/25851874/d2ae6c3c-34c7-11e7-84a0-d0de136ca5b0.png)
