### ISSUE TITLE
Use of OIDC with dashboard?

### ISSUE THREAD

**Issue by AlainRoy** [kubernetes/dashboard#1589]
I don't understand if the dashboard is expected to work when Kubernetes is configured to use OIDC. I looked through the source code and issues, and it's not clear to me. 

Specific questions:

- Can the dashboard be configured with an OIDC client ID?
- Can the dashboard use OIDC login/logout URLs? 
- How does a user authenticate when using OIDC? 

I saw some references (lost them, sorry), that the dashboard may not work with OIDC, but may expect the user to run `kubectl proxy ...`, thus pushing the job of authentication to kubectl, and the browser isn't then responsible for authentication. Is that correct, or am I just completely confused?

Thanks!

**Comment by IanLewis** [comment]
Yes. Currently the dashboard doesn't do authentication itself. Users either use `kubectl proxy` or https://<kubernetes-master-ip>/ui + HTTP auth through the Kubernetes API server.

**Comment by bryk** [comment]
When https://github.com/kubernetes/dashboard/pull/1539 gets it you'll be able to have a proxy in front of Dashboard for auth.

**Comment by AlainRoy** [comment]
Thanks!

**Comment by spnzig** [comment]
is #1539 complete? Can i use OIDC with the dashboard now?

**Comment by floreks** [comment]
You can't use OIDC directly. You can however configure proxy server that will require logging in and will pass bearer token to dashboard. Dashboard checks for `Authorization: Bearer <token>` in a request header and uses it to authorize user.

**Comment by spnzig** [comment]
@floreks thanks for that. Is the procedure documented somewhere for reference?

**Comment by floreks** [comment]
Unfortunately not right now. We will document everything once login feature will be added to dashboard.

**Comment by spnzig** [comment]
@floreks I'm confused So basically for now what is the role of openid authentication with K8S? Who are being authorized then?

**Comment by floreks** [comment]
OIDC provides you JWT token that you can use to authorize yourself. As an example you can use `kubectl --token xxx...`. Token will be passed to apiserver and used to authorize action. Dashboard also accepts this token in a request header. You just have to use proxy in front of dashboard that will pass this token on every request.

**Comment by dalu** [comment]
But if you bootstrapped your cluster with kubeadm, how do you tell who is able to access your cluster and how would k8s know the client_id and client_secret from an id_token to verify you have access or not?
And how would you use kubeadm in the first place to bootstrap your cluster with the info of scopes and claims and oidc endpoints etc?
