### ISSUE TITLE
Referencing default export types from other js files doesn't work

### ISSUE THREAD

**Issue by batikanu** [kubernetes/dashboard#159]
In [filereader_directive.js] (https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/deploy/filereader_directive.js#L28)
The type annotation `/** @type {./upload_controller} */` for `UploadController`, which is default export of the file, fails with the error below:

```
src/app/frontend/deploy/filereader_directive.js:28: ERROR - Bad type annotation. Unknown type module$deploy$upload_controller
      /** @type {!./upload_controller} */
```

**Comment by bryk** [comment]
CC @floreks @maciaszczykm @cheld 

It seems that closure compiler has problems with referencing ES6 default exports in JSDocs. What do you think about banning default exports and using only named ones?

**Comment by floreks** [comment]
If this resolves the problem then it's good for me.

**Comment by batikanu** [comment]
it seems there has to be at least one default in file 
```
src/app/frontend/deploy/upload_directive.js:29: ERROR - Property default never defined on module$deploy$upload_controller
    controller: UploadController,
```

**Comment by batikanu** [comment]
Sorry I forgot to modify import section after removing default. It works without default as well

**Comment by cheld** [comment]
I could reproduce the described behavior as well. I had to use a work-around.

Please fix also TODO in:

https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/deploy/createnamespace_controller.js

**Comment by floreks** [comment]
We've already working solution for that issue. Removing `default` and referencing type with path works fine. Closing.
