### ISSUE TITLE
Creating Persistent Volumes and Claims

### ISSUE THREAD

**Issue by naisanza** [kubernetes/dashboard#1598]
#### Issue details
The UI doesn't have an obvious way of creating Persistent Volumes and adding a PVC to a new Deployment. From the documentations it seems the only way of creating a PV is manually creating it from the shell

##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1
Kubernetes Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Kubernetes Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Operating system: Linux k8s-master01 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Node.js version:
Go version: 1.7.4
```

##### Steps to reproduce

1. Create new Deployment

or

1. Clicking Persistent Volume Claims tab in Dashboard

##### Observed result

No option for provisioning a new Volume or attaching an existing PV

##### Expected result

1. Option to create new PV when creating new Deployment
2. Option in create new PV in Persistent Volume Claims tab

**Comment by maciaszczykm** [comment]
Closing as we'll track it from #1600.
