### ISSUE TITLE
Supporting "Apps"

### ISSUE THREAD

**Issue by ianlewis** [kubernetes/dashboard#1599]
There has been some discussion about how to best support "Applications". Many users will want to view deployed objects as an "application" and may not care or even be aware of each of the individual objects (Deployments, Services, ConfigMaps, ThirdPartyResources, etc.) deployed in the cluster.

We will need to figure out what an "app" is. It implies some kind of ownership relationship between an "app" and the individual objects deployed in the cluster. Helm does something similar with objects deployed as part of a helm chart. This may be a good place to start.

Some other UIs like OpenShift do some grouping of objects into projects and applications.

Related issues/PRs: #1504 #1570 #1332 

cc @erictune @davidopp

**Comment by IanLewis** [comment]
Also cc @foxish

**Comment by IanLewis** [comment]
Tentatively assigning myself to this

**Comment by IanLewis** [comment]
Need to work with [sig-apps](https://github.com/kubernetes/community/tree/master/sig-apps) to figure out best definition of an "app". I'll try to engage and join one of the sig-apps meetings.

**Comment by foxish** [comment]
Currently we're building [Spark](https://github.com/kubernetes/kubernetes/issues/34377) support and what we consider an instance of a SparkJob consists of one `driver pod`, several `executor pods`, 2 `services`, several `secrets` and a ThirdPartyResource named `SparkJob`. 

In order to achieve garbage collection in this model, we have OwnerReferences in the resources pointing up to the driver pod and the SparkJob resource. The OwnerReferences serve as a way to establish relationships between resources and signify that they belong to a single application, the way I see it.

**Comment by IanLewis** [comment]
At the risk of having a discussion here when it may be better had in a sig-apps venue, I guess from a UI perspective there needs to be a way of saying "what apps are deployed in my cluster?", "what objects are owned by app x?".

The first question isn't answered there AFAICT. ThirdPartyResources may or may not represent an "app"

The owner references help with the second question but it's indexed the other way around from what I would want. I would need to be able to find the owned objects without having to scan every object type.

**Comment by bryk** [comment]
That's interesting discussion. Is this common for users to create ThirdPartyResources for "apps"? Or something that happens rarely?

**Comment by davidopp** [comment]
Specifically from #1504 I highly recommend
https://github.com/kubernetes/dashboard/issues/1504#issuecomment-273826941
and
https://github.com/kubernetes/dashboard/issues/1504#issuecomment-273995110

**Comment by IanLewis** [comment]
Copied for the lazy readers

@erictune
> My take on this:
>
> * Users think about their cluster as holding a number of "apps".
> * Useful: an "app summary" view in dashboard that lists all their apps, regardless of what Kinds make up that app.
> * Not as useful: Having one view which is just Deployments, another which is just StatefulSet, and another which is just TPR, etc.
> * With Helm Charts, and similar packaging systems, users often won't even be aware what Kind implements their app.
> * An "app" is a collection of resources, but you don't want to see most of them most of the time. There is a clear "parent" object which should be shown
in the "app summary" view, and child objects should be hidden in a summary view, but show when you drill down on a pariticular app.
> * Examples of "apps":
>   * nginx app, parent object is Deployment, children are ReplicaSet and Pods.
>   * mysql app, parent object is a StatefulSet, children are Pods and PVCs.
>   * a spark job called, parent object is a TPR of type SparkJob, children are a ReplicaSets and Pods
>   * there are too many possibilities to hard code.

@davidopp
> I like @erictune 's idea. One refinement I would propose, though perhaps it's too radical, is to say that every app should have a TPR as the top-level parent. Obviously we can't force people to do this, but we could declare the pattern to be a best practice. The benefits would include

> * uniformity
> * Service objects can have a parent; if the parent is Deployment or StatefulSet (as in Eric's example for nginx and mysql) there isn't anywhere natural in the hierarchy to stick Service if the user wants one
> * related to the previous bullet, this would address the issue @IanLewis pointed to (#1570) in a uniform way, since you could clean up the Service (and any other objects that don't fit into the single-line hierarchy)
> * we could finally address kubernetes/kubernetes#14956

Yah. I think we all have similar ideas and the idea of an app isn't controversial, just the specifics of exactly what objects can be parents, how to identify them as apps, and how the objects link together haven't really be decided.

I feel it's probably best to work with sig-apps to hammer out some kind of spec and just have dashboard use that. That way we get more input and end up with something that other tools like helm, or other UIs can use.

**Comment by erictune** [comment]
[This doc](https://docs.google.com/document/d/1fWy-acaUCF6Wi581eKp2lJMTM9YeS6Shfma0OZ2D9qg/edit#heading=h.isxvg94vcadi) has some ideas about conventions to group things into apps.

**Comment by bryk** [comment]
I commented in the doc.

**Comment by fabiand** [comment]
Is there a way to get comment permissions on that document @bryk ?

Considering our use-case, we will be shipping some TPRs, DaemonSets, Services, Deployments, and maybe StatefulSets and today there is no grouping mechanism which allows me to group arbitrary objects into an "app". And that concept is also missing from that document.

So picking up what has been said above, that a TPR could be the logical root of an app, but I'd still like to have a type - similar to a deployment - where I can specify all the resources we need for the app.

**Comment by bryk** [comment]
> Is there a way to get comment permissions on that document @bryk ?

@fabiand Yes. Ping me on slack (handle: bryk) with email address or request comment access through Docs interface.

**Comment by bryk** [comment]
> Considering our use-case, we will be shipping some TPRs, DaemonSets, Services, Deployments, and maybe StatefulSets and today there is no grouping mechanism which allows me to group arbitrary objects into an "app"

Are DaemonSets, Services and Deployments one app? Or multiple apps?

**Comment by bryk** [comment]
> So picking up what has been said above, that a TPR could be the logical root of an app, but I'd still like to have a type - similar to a deployment - where I can specify all the resources we need for the app.

IMO, TPR is best candidate for the root of an app.
But how about all those who do not use TPRs, but just stock K8s objects? That's why the proposal to infer apps based on ObjectRef metadata emerged. Take a look into the doc.

**Comment by IanLewis** [comment]
> But how about all those who do not use TPRs, but just stock K8s objects? That's why the proposal to infer apps based on ObjectRef metadata emerged. Take a look into the doc.

I think he means like a Pod template in a Deployment, he would like to define all dependencies in one TPR object.

**Comment by erictune** [comment]
https://github.com/Mirantis/k8s-AppController is sort of like that

**Comment by IanLewis** [comment]
I talked with @michelleN at Container Camp AU about this. She seemed to think that having an extension mechanism for the dashboard and implement things like showing Helm charts/releases, or App-Controller apps would allow us to have the community decide the best idea rather than having an official standard or an "application" construct built into Kubernetes itself.

**Comment by IanLewis** [comment]
There was the idea of adding "Extension points" to the dashboard in the roadmap we had last year.

https://github.com/kubernetes/dashboard/blob/master/docs/devel/roadmap.md

**Comment by erictune** [comment]
Extension is great if you have the ability to support it fully.   But, it can be hard to find people to build and support the common parts of the extension code.   Prospective extension authors are not always the right people to build the common code and extension API.

I see this pattern in other parts of the project:
-  Lots of people want to write new cloud providers, but not enough people to write the cloud provider extendability code (@thockin knows about this).
- Lots of people want to write API extensions, but building the Aggregated APIserver extension mechanism is taking a long time (@dbsmith knows about this).

**Comment by IanLewis** [comment]
Sure. I agree we have few developers as is and lots of higher priority issues to work on. My comment wasn't really about how viable the idea was. Just wanted to capture her comment.

**Comment by krmayankk** [comment]
@mattfarina  where is the application crd work going on, i cant find it ?

**Comment by mattfarina** [comment]
@krmayankk http://github.com/kubernetes-sigs/application

**Comment by ant31** [comment]
Related to: https://github.com/kubernetes/dashboard/issues/2891

How could I help to have this issue moving forward ?

**Comment by fabiand** [comment]
To some degree operators and charts are addressing this issue imho.
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
seems to be the minimum bar that kubernete is recommending. In my
understanding kube as a community could look what further standardization
would be needed to identify "applications" regardless of their higher level
orchestration like helm or operators. aka the next steps to the recommended
labels.

**Comment by ant31** [comment]
@fabiand yes the community, sig-apps, already identified what an application could mean in kubernetes upstream , and interactions with owned resources. 
Helm or operator are package and lifecycle manager tools not resources. 
The Application resources provide necessary metadata to group resources under one entity and provide the standardization you mentioned: https://github.com/kubernetes-sigs/application. 
It started as a CRD but could become a core resource with an increased adoption. 
Adoption should start via other sig and upstream project, including kubernetes-dashoard. 

cc @mattfarina

**Comment by maciaszczykm** [comment]
I think https://github.com/kubernetes/dashboard/issues/3160 would cover it in a very basic way that should be enough for now. At least until it will be more common.

**Comment by ant31** [comment]
@maciaszczykm  
How could it become more common there isn't any integration with other projects ?

**Comment by maciaszczykm** [comment]
I said that's a very basic way. We have a lot of more important issues at the moment and not a lot of developers working on them. If we can do something then I would start with being able to search using labels that could help with application support too. We will not work on anything specific for https://github.com/kubernetes-sigs/application for now, if there will be anybody that would like to work on this we will be glad to help him.

**Comment by maciaszczykm** [comment]
I would be also hesitant to put it in the master, I'd rather see it implemented as a plugin for now.

**Comment by ant31** [comment]
@maciaszczykm Then keep the issue open and say that you approve the feature and would look at PR.

>I would be also hesitant to put it in the master, I'd rather see it implemented as a plugin for now.
Why ? I mean cross-sig project collaboration is key. 
I'll be happy to come in a sig meeting and demo it's integration within the GKE to discuss the value

**Comment by floreks** [comment]
We could support such a thing only if this would be a part of the core. As this is a CRD only, we don't want to officially support that. This is a custom resource after all. Such things should be handled by plugins mechanism, not as part of our core code. Searching by label would be generic enough and would not depend on any custom resources that may or may not be installed inside the user cluster.

**Comment by ant31** [comment]
To be part of core it should be integrated in the ecosystem and first in other sig projects. Once adoption is raised it could be discussed to get into core. 

I'll get a look at the plugin mechanism, as it could still be a good in-between solution

**Comment by maciaszczykm** [comment]
I think a plugin would be the best for now as not all clusters that are running dashboard are running the application controller and have the application CRD. If someone doesn't want it then he should not be forced to use it.

**Comment by floreks** [comment]
I think plugin mechanism right now is in very basic state and would need to be improved first in order to actually support such feature (https://github.com/kubernetes/dashboard/issues/4583). @ajatprabha was working on it. 

As for the integration. We do not integrate third-party solutions (metrics are an exception here) that require custom controllers and have their own custom API. The main reason is that we do not have enough people to support that and second thing is that we do not support things that are not commonly installed in the user clusters by default. We rely on the core API, if something gets there, then we are trying to introduce it in the Dashboard also.
