### ISSUE TITLE
Deployment in version "v1beta1" cannot be handled as a Deployment: [pos 620]: json: expect char '"' but got char '1'

### ISSUE THREAD

**Issue by naisanza** [kubernetes/dashboard#1603]
#### Issue details
Edited Deployment config in kubernetes/dashboard UI to include [NEO4J_HEAP_MEMORY ](https://neo4j.com/developer/docker-23/)environment variable for [neo4j](https://hub.docker.com/_/neo4j/) but received an error when updated the deployment

##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1
Kubernetes Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Kubernetes Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Operating system: Linux k8s-master01 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Node.js version:
Go version: 1.7.4
```

##### Steps to reproduce

1. Create new Deployment with out environment variable
2. Edit the deployment and add the new environment variable
3. Update deployment

##### Observed result

Error:
![Error](http://i.imgur.com/Un1a5zE.png)

I got the structure and where to add the `NEO4J_HEAP_MEMORY` from here:
![Config structure](http://i.imgur.com/agXld23.png)

And updated it to the existing Deployment:
![Updating existing deployment](http://i.imgur.com/VDm3Da0.png)

##### Expected result

ReplicaSet and Pods updated with new config

**Comment by guiocavalcanti** [comment]
Hey @naisanza can you paste the manifest you are using?

**Comment by naisanza** [comment]
@guiocavalcanti I don't have a manifest as I am using purely the UI for kubernetes/dashboard with all default settings

I'm using the docker image at https://hub.docker.com/_/neo4j/

**Comment by guiocavalcanti** [comment]
@naisanza I think this is a wrong error message. The actual problem is occuring because somewhere you have a key with a numeric value. Try to search the manifest for the char `1` and surround it with double quotes.

**Comment by naisanza** [comment]
@guiocavalcanti I noticed that I took the settings from the (working) Replica Set config and applied it to the (old) Deployment config

I'll recreate the test and will create the new key-values in the (old) Replica Set config

**Comment by naisanza** [comment]
@guiocavalcanti so I recreated the test, and this time, created the NEO4J_HEAP_MEMORY key by editing the ReplicaSet config instead of editing the Deployment config, and it still gives me the same issue

![kubernetes dashboard](https://cloud.githubusercontent.com/assets/1614425/22860497/af8f01a0-f0cd-11e6-81e6-cd784b0ebce5.png)

However, if I put the integer in quotes `"1500"` it works, but it's shown in Environmental variables incorrectly

![not-the-same](https://cloud.githubusercontent.com/assets/1614425/22860525/7eaadea0-f0ce-11e6-8ac0-e115fb3d2dae.png)

It looks like this if the Environmental variables is added from using the `+CREATE` button

![what-i-want](https://cloud.githubusercontent.com/assets/1614425/22860527/8768388a-f0ce-11e6-90d6-3032967d85db.png)

**Comment by floreks** [comment]
@naisanza 

It actually looks like kubernetes issue not dashboard. I've tried that on dashboard 1.5.1 with kubernetes 1.5.2(you are using 1.5.1) and it worked fine. I've updated deployment with env variable `test/test` and it was correctly propagated to pod.

![zrzut ekranu z 2017-02-22 10-26-09](https://cloud.githubusercontent.com/assets/2285385/23205233/61b89512-f8e9-11e6-89f1-417fea9cf4aa.png)

![zrzut ekranu z 2017-02-22 10-26-22](https://cloud.githubusercontent.com/assets/2285385/23205237/63c83ed4-f8e9-11e6-879f-37777e442fba.png)

**Comment by naisanza** [comment]
@floreks try it with an integer value

Using an integer without quotation marks will get an error when adding environment variables after creating the deployment from the UI, but using quotation marks will be reflected in the deployment configuration.

I'm trying to find out if that has any impact when the docker image reads that value that includes quotations versus no quotations

**Comment by zouyee** [comment]
Any progress?

**Comment by floreks** [comment]
After investigating this a bit more I have to say that it works as expected. Kubernetes accepts env variables only as strings.

```golang
type EnvVar struct {
	// Required: This must be a C_IDENTIFIER.
	Name string
	// Optional: no more than one of the following may be specified.
	// Optional: Defaults to ""; variable references $(VAR_NAME) are expanded
	// using the previous defined environment variables in the container and
	// any service environment variables.  If a variable cannot be resolved,
	// the reference in the input string will be unchanged.  The $(VAR_NAME)
	// syntax can be escaped with a double $$, ie: $$(VAR_NAME).  Escaped
	// references will never be expanded, regardless of whether the variable
	// exists or not.
	// +optional
	Value string
	// Optional: Specifies a source the value of this var should come from.
	// +optional
	ValueFrom *EnvVarSource
}
```

As editor has to allow integer values also and we can not do any validity check if added object, field, etc. is compliant with kubernetes api then such errors may happen.

**Comment by maciaszczykm** [comment]
You can always try to put integer into quotation marks, so it will be recognized as a string.

**Comment by kobelb** [comment]
When specifying env variables using the UI after the initial deployment, I was experiencing this same issue when trying to specify settings that were Integers or Booleans. I was able to get past this by changing the "type" of the value to a string using the following:

![k8s-boolean-setting](https://user-images.githubusercontent.com/627123/33320978-f32de516-d411-11e7-831e-729358f83fdc.gif)

**Comment by floreks** [comment]
Edit mode was changed to text mode in `1.7`. This should not be a problem anymore.

**Comment by ykfq** [comment]
In my case , justin because I configured a wrong yaml file with a missing `-`:
![image](https://ws1.sinaimg.cn/large/6ee6fa3egy1fpi74c8b18j20hm02a74k.jpg)  

Below is the difference of a `-` exist or not, the `JSON` format at left is more intuitive: 
![image](https://ws1.sinaimg.cn/large/6ee6fa3egy1fpi7bssbr4j211b04q0tb.jpg)

![image](https://ws1.sinaimg.cn/large/6ee6fa3egy1fpi7apy9o0j211m06adgj.jpg)

**Comment by kamalguptadevops** [comment]
Please try to pass the environment variable's value within the double quotes, especially when you are passing some numeric value, In my case, I was passing the environment variables in the deployment file without the double quotes. I was getting the same error, but when I changed it worked for me. It might help you as well.

Thanks,
