### ISSUE TITLE
File upload input allows for entering arbitrary text

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#162]
![selection_002](https://cloud.githubusercontent.com/assets/1159999/11745387/1674e630-a018-11e5-8c10-d3a909c8f520.png)

I can type into the file input text. Modifying text there should be disabled. The input should be focusable, clickable, but not editable by user. 

@batikanu

**Comment by batikanu** [comment]
Yes I am aware of that. I will search for a solution as the next.
