### ISSUE TITLE
Task 'default' is not in your gulpfile

### ISSUE THREAD

**Issue by wefine** [kubernetes/dashboard#1625]
#### Issue details

I follow the develop guide with [requirements-installation](https://github.com/kubernetes/dashboard/blob/master/docs/devel/requirements-installation.md)

``` shell
$ build/run-gulp-in-docker.sh
```

I got the below errors after the image was build.
![image](https://cloud.githubusercontent.com/assets/22292664/22731217/d2a2d7bc-ee24-11e6-8d1f-a91147ce4bec.png)

Who can help me to resolve it?

**Comment by bryk** [comment]
@floreks @maciaszczykm  Are you using this script?

**Comment by floreks** [comment]
I have never actually used it.

**Comment by maciaszczykm** [comment]
Neither did I.

**Comment by wefine** [comment]
Dear All, I am trying to join and want to do something for dashboard, but first I need to make a development environment and make the dashboard running, so I follow the development guide. I find out some simple miss in the requirement-installation and fix it myself, but I can not fix the gulp problem currently. So any suggestions are appreciated, thanks!

**Comment by wefine** [comment]
When running "build/run-gulp-in-docker.sh", "serve" parameter is necessary, otherwise, the error will break out like above.
