### ISSUE TITLE
UX improvement: Deployments show 2/2 under pods even if pods are in crashed state

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/dashboard#1629]
#### Issue details
I had pods that were in `Waiting: CrashLoopBackOff` state, but I didn't realize it because the deployments summary showed all pods as running.  e.g. It showed 2/2 under pods column.  

##### Environment
k8s dashboard launched from Rancher UI.  

```
Dashboard version: 1.5.0
Kubernetes version: 1.5.2
Operating system: Ubuntu 14.04
```

##### Steps to reproduce
Try to deploy a container that exits immediately as a deployment.

##### Observed result
Pod is in `Waiting: CrashLoopBackOff` state but deployment is green and shows 2/2.

##### Expected result
Would expect deployment to show 0/2 if pod is in `Waiting: CrashLoopBackOff` state

**Comment by olekzabl** [comment]
Right, 0/2 would be better to show. Thanks for reporting!

**Comment by IanLewis** [comment]
I suppose that 2/2 is supposed to show the <ready pods>/<total pods> as is shown by kubectl?

**Comment by ryanwalls** [comment]
@IanLewis Not following your question.  Are you asking whether it should show the slash?  I would assume the answer is yes.  What would the alternative be?

**Comment by IanLewis** [comment]
@ryanwalls That may have been a typo. I just presumed that it should show the same values as kubectl when running `kubectl get deployments`

**Comment by maciaszczykm** [comment]
Closing as stale.
