### ISSUE TITLE
Dashboard reported Unknown Server Error (500)

### ISSUE THREAD

**Issue by zacbayhan** [kubernetes/dashboard#1643]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Unknown Server Error (500):
```
pods "kube-dns-v20-3531996453-qj5pn" not found

```

**Comment by cheld** [comment]
Please provide information for environment and steps to reproduce

**Comment by zacbayhan** [comment]
Feel free to close this issue I believe the problem resides with kops, and the fact that somehow my nodes are getting lost. So it attempts to install that on that master node.

**Comment by floreks** [comment]
> Feel free to close this issue I believe the problem resides with kops, and the fact that somehow my nodes are getting lost. So it attempts to install that on that master node.

Ok. Feel free to reopen if there there are any issues with dashboard itself.
