### ISSUE TITLE
Move backend tests to /src?

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1644]
Benefits from having Go tests in same package as source code:

- possibility to test non-exported functions (names starting with small letters)
- no need to prefix calls to package methods
- tests are easier to find, when placing them in the nearby with `_test.go` suffix
- it **should** be possible to get code coverage also from backend (https://github.com/codecov/example-go)
- allows IDE to autocomplete

Drawbacks:

- need to refactor
- more files in `/src` directory
- perhaps we shouldn't focus on testing non-exported functions?

@kubernetes/dashboard-maintainers What do you think? I'd say it's at lease worth considering.

**Comment by IanLewis** [comment]
I think it's usually more common  to have the tests in the same directory as the source files so this gets a 👍 from me.
