### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by edbergavera** [kubernetes/dashboard#1647]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
Get https://10.43.0.1:443/apis/extensions/v1beta1/namespaces/default/daemonsets: dial tcp 10.43.0.1:443: getsockopt: connection refused

```

**Comment by maciaszczykm** [comment]
Could you provide more details to help us solve the issue?

**Comment by edbergavera** [comment]
hello @maciaszczykm I'm rancherOS, where do I find these info?

**Comment by maciaszczykm** [comment]
First of all we need to know how to reproduce the issue, so can you fill in steps to reproduce?
