### ISSUE TITLE
Dashboard reported Unknown Server Error (503)

### ISSUE THREAD

**Issue by m-mikula** [kubernetes/dashboard#1648]
##### Environment

```
Dashboard version: i do not know
Kubernetes version: i do not know
Operating system: AWS
Node.js version: i do not know
Go version: i do not know (on my host 1.7)
```
##### Steps to reproduce
export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash
I'm at AZ eu-central-1a maybe that's the problem?

##### Observed result
Dashboard reported Unknown Server Error (503):
```
No error data available
```

**Comment by m-mikula** [comment]
After my 4th try I just gave it Time (about 20 Minutes) and tadaaa, it works somehow seems like patience is the answer.

**Comment by maciaszczykm** [comment]
So it's working, but it starts slowly?

**Comment by m-mikula** [comment]
yup it starts super slow, giving the feeling that it is broken

**Comment by maciaszczykm** [comment]
Yeah, cluster creation can take a while... You are using command which downloads everything on its own and it's not making it quicker. Anyways, I'm glad it works at the moment.

I'm closing the issue, please reopen if you'll have any questions.
