### ISSUE TITLE
Pointing to api-server

### ISSUE THREAD

**Issue by tdeheurles** [kubernetes/dashboard#165]
Hi,

I'm looking for the `how-to` point to the api-server.

It seems for now that it only works with a local kubernetes ?

**Comment by bryk** [comment]
When you run the Dashboard inside a cluster, it should work. Other than that you can do `kubectl proxy --port=8080`, which I use for development.

**Comment by floreks** [comment]
Other option would be to build backend manually and pass `apiserver-host` argument to it. Something like that, but you have to build it yourself using `go build`

![zrzut ekranu z 2015-12-11 17-02-13](https://cloud.githubusercontent.com/assets/2285385/11748622/6de173aa-a029-11e5-87b5-2fe0a62c2d2c.png)

**Comment by tdeheurles** [comment]
For nowm I'm on the creation of the container. So then I just run it in the kubernetes cluster and it should find it's needed informations ? no need for any credentials or things like that ?

**Comment by tdeheurles** [comment]
`Other option would be to build backend manually using go build and pass apiserver-host argument to it.` ==> looking to that

**Comment by floreks** [comment]
You can just run local cluster using `local-up-cluster.sh` kubernetes script and dashboard should find it on `localhost:8080`.

**Comment by tdeheurles** [comment]
Ok. No I'm running it on a cloud cluster or inside a VM. localhost can't work for me I think.

**Comment by floreks** [comment]
Then as @bryk mentioned you can use `kubectl --proxy` command. I don't have running vm to test, but try to configure `kubectl config set-cluster` and `kubectl config set-context` to point to your cluster then `kubectl config use-context` so you can just write `kubectl get rc` without pointing to server. Then configure `kubectl --proxy` to redirect traffic through local port 8080. Should work.

**Comment by tdeheurles** [comment]
=> kubectl for local test on windows can't be done as kubectl can't be installed (no delivery for windows). Only way to run it is in the VM, so same problem here.

So I need to add the `kubectl` to my container that will run into the cluster and start it as a proxy to the api-server ...

I'll try that solution ... seems a bit complicated `oO`

Thanks

**Comment by bryk** [comment]
@tdeheurles 
> So I need to add the kubectl to my container that will run into the cluster and start it as a proxy to the api-server ...

No. Just run Kubernetes Dashboard in your cluster and it should work. We don't have installation instructions for running in a cluster, though (yet, it should be done soon).

**Comment by tdeheurles** [comment]
I'm not working on that for now. So I propose to close ^^
Thanks for support.
