### ISSUE TITLE
Refactor go backend

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1653]
I think it would be nice to decouple backend code a bit. 

Especially `resource/pod/detail.go`, which shouldn't import daemon set, job etc. To do it I'd suggest making interface for it or using not resource list but specific structure. At the moment `Controller` struct seems to be a bit too big and forces us to use `detail` and `list` packages inside our resource packages.

**Comment by bryk** [comment]
Yep, I think this is a good idea.
