### ISSUE TITLE
Minikube Dashboard renders incorrectly in Firefox

### ISSUE THREAD

**Issue by jwhitehouse-raise** [kubernetes/dashboard#1655]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
minikube version: v0.16.0

**Environment**:
- **OS** OS X El Capitan 10.11.6
- **VM Driver** "DriverName": "xhyve"
- **ISO version** "Boot2DockerURL": "file:///Users/jennawhitehouse/.minikube/cache/iso/minikube-v1.0.6.iso"
- **Install tools** Minikube via curl instructions, Kubectl via Brew
- **Others**: Firefox 51.0.1 (64-bit)

**What happened**:
Firefox renders `minikube dashboard` without any images/icons.

**What you expected to happen**:
Firefox renders the page correctly.

**How to reproduce it** (as minimally and precisely as possible):
Using Firefox as default browser, install minikube v0.16, minikube start, minikube dashboard.
![minikube_render_error](https://cloud.githubusercontent.com/assets/23040526/23077161/f9b5ee30-f508-11e6-8b4d-ab72e85f435e.png)

**Anything else do we need to know**:
Google Chrome & Safari render the dashboard correctly for me. Also note, did turn off plug-ins such as ad-block when testing. Final addition: the Label & Images blurring is intentional, not part of my rendering error.

**Comment by floreks** [comment]
I'll try to reproduce on ubuntu and if I can then try to fix it.

**Comment by floreks** [comment]
Unfortunately on my env I could not reproduce it. It might be related to different OS and vm driver.

My env:
```
OS: Ubuntu 16.10
Firefox: 51.0.1 (x64)
Minikube: v0.16.0
VM Driver: VirtualBox-5.1
```

![zrzut ekranu z 2017-02-22 10-02-00](https://cloud.githubusercontent.com/assets/2285385/23204297/4a6f14b0-f8e6-11e6-89bb-d14827e9d498.png)

**Comment by maciaszczykm** [comment]
Neither do I:

![image](https://cloud.githubusercontent.com/assets/2823399/24602467/23aa94e4-185d-11e7-853d-122abbf73ba8.png)

Probably it occurs only on macOS.

**Comment by jwhitehouse-raise** [comment]
Closing as it seems too difficult to replicate to be a proper issue.
