### ISSUE TITLE
[Feature Request] - User selected dashboard color

### ISSUE THREAD

**Issue by CelsoSantos** [kubernetes/dashboard#1657]
This is a feature request.

#### Issue details
I'd love to have the option to chose the primary color for the Kubernetes Dashboard. This would be useful to distinguish between development/staging/production environments by color coding them.
This could either be a namespace specific option or a general dashboard option.

##### Observed result
Right now, this is impossible.

##### Expected result
The dashboard saves the chosen color, which is set by default upon following accesses

##### Comments
As far as I'm concerned, the only item that would change color would be the toolbar at the top of the page.

The color picker could be placed alongside with the namespace selection.
Something along these lines:
![kubernetes_dashboard](https://cloud.githubusercontent.com/assets/1015506/23095853/34ae254c-f609-11e6-838b-dbcd60f12940.jpg)

**Comment by kgignatyev-inspur** [comment]
I might try. Will cookie work for that?

**Comment by floreks** [comment]
For user selected themes cookies for sure would be needed, however we do not yet have any support for cookies in dashboard. It is fully stateless application. We are considering introducing support for them, but no ETA yet.

**Comment by CelsoSantos** [comment]
Personally, as I haven't yet had the required time to look into this, I'm using a simple Chrome extension.
I can drop a couple screenshots if you guys want to take a look at it.

Cookies or LocalStorage (maybe LocalStorage would be better) are two missing pieces in the grand scheme of things which would allow, for instance, selection of the number of pods, deployments, etc to be shown on the UI tables.

If I had to choose, I'd personally go with LocalStorage but that's just my preference

**Comment by floreks** [comment]
This is an interesting idea. We are definitely planning to support LocalStorage or cookies. Thanks to #1539 we could tie user to session config and introduce something like user page with settings that would allow  to personalize dashboard better. Probably this will be our next step after search and filtering will be finished.

**Comment by kgignatyev-inspur** [comment]
Submitted simple implementation based on cookies 
https://github.com/kubernetes/dashboard/pull/1938

**Comment by toidiu** [comment]
Ideally this could be passed in as a parameter to the docker command. This would make deployment reproducible and versioning possible.

**Comment by maciaszczykm** [comment]
Will be tracked from #2417.
