### ISSUE TITLE
Dashboard crashes with too many pods

### ISSUE THREAD

**Issue by sethpollack** [kubernetes/dashboard#1658]
#### Issue details

I had a cronjob that created ~ 2.k jobs/pods. When I try to visit the dashboard on a page that displays pods, the dashboard app crashes.

```
Dashboard version: 1.5
Kubernetes version: 1.5.2
```

**Comment by IanLewis** [comment]
See issue #1431. Try increasing the limits imposed on the container and see if that helps.

**Comment by sethpollack** [comment]
Ok thanks
