### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by rainleon** [kubernetes/dashboard#1666]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
pods "tiller-deploy-3991468440-sgjsx" not found

```

**Comment by maciaszczykm** [comment]
It looks like you tried to access page of non-existing pod, refresh the page and everything should be up-to-date. We're working on live update, which will eliminate these situations.

**Comment by rainleon** [comment]
Yes,it take a long time to pull image,and sometimes it failed.
