### ISSUE TITLE
Dashboard image for s390x platform

### ISSUE THREAD

**Issue by XiLongZheng** [kubernetes/dashboard#1668]
#### Issue details
From 1.6.0 alpha1 s390x platform binaries are included in kuberentes release. While, I didn't find dashboard image for s390x platform so far. Is the image planned to be released with kubernetes 1.6.0?
##### Environment

```
Dashboard version: 1.6.0
Kubernetes version: 1.6.0
Operating system: s390x
Node.js version:
Go version:
```

**Comment by IanLewis** [comment]
Yep. We should have builds for all the platforms that Kubernetes releases.

**Comment by XiLongZheng** [comment]
Is it planned to ship with 3/27 kubernetes 1.6 release?

**Comment by cheld** [comment]
What is "3/27"?

**Comment by maciaszczykm** [comment]
@cheld It's a date.

**Comment by maciaszczykm** [comment]
@XiLongZheng Unfortunately it's not done for 1.6 release.

**Comment by XiLongZheng** [comment]
@maciaszczykm Thanks for clarifying the date! It there any target date in the near future?

**Comment by floreks** [comment]
We'll merge PR with support for s390x platform and after successful master build our dev images on dockerhub will be updated. Unfortunately for the official release with support for s390x you'll have to wait for our next dashboard release. We might do a minor release 1.6.1 in a few weeks but I can't say when exactly.

**Comment by floreks** [comment]
It's merged. Master build should finish in 20-30m and images should be pushed. Could you please test it?

**Comment by XiLongZheng** [comment]
Just got time to try, dashboard dev build worked perfect with Kubernetes 1.6.1 on s390x. Thanks for your great help! Dashboard makes our life a lot of easier!

**Comment by floreks** [comment]
That's great to hear! Thanks for testing it. Starting from next release s390x arch will be now officially supported.
