### ISSUE TITLE
Unable to access dashboard from desktop/laptop 

### ISSUE THREAD

**Issue by harighub** [kubernetes/dashboard#1674]
I setup k8s cluster on multiple VM's by following https://kubernetes.io/docs/getting-started-guides/kubeadm/ on Oracle Linux 7.0. I'm unable to access dashboard UI from laptop windows/browser. It appears that dashboard is installed and running properly.

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"58b7c16a52c03e4a849874602be42ee71afdcab1", GitTreeState:"clean", BuildDate:"2016-12-12T23:31:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

On master VM where dashboard is installed:

curl http://127.0.0.1:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/
 <!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title>Kubernetes Dashboard</title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.a0fa0655.css"> <link rel="stylesheet" href="static/app.968d5cf5.css"> </head> <body>  <kd-chrome layout="column" layout-fill=""> </kd-chrome> <script src="static/vendor.89dbb771.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.50ef120b.js"></script> </body> </html> 

kubectl logs kubernetes-dashboard-3203831700-3w9qn --namespace=kube-system
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Successful initial request to the apiserver, version: v1.5.0
Creating in-cluster Heapster client
Using service account token for csrf signing

I appreciate if you could help to access dashboard from outside of master node.

**Comment by harighub** [comment]
I read authentication page of the documentation. And I decided I want to add authentication via a Static Password File. To do so I have to append the option --basic-auth-file=SOMEFILE to the Api server and restated api server by rebooting the system. When I initiated a request from browser it asks for username/password at secured port (6443). Then: I got below error:

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

**Comment by cheld** [comment]
You can use `kubectl proxy` (see https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md for details) or change authentication like you are proposing. 

I guess dashboard is not running any more after you have changed authentication

**Comment by harighub** [comment]
You are right, I see that dashboard status showing as error:

 kubectl get pods --all-namespaces
NAMESPACE     NAME                                             READY     STATUS              RESTARTS   AGE
default       test-701078429-84h2x                             0/1       ContainerCreating   0          16h
default       test1-2794429439-7xfp5                           0/1       ContainerCreating   0          16h
kube-system   calico-policy-controller-kt9sh                   0/1       Error               240        2d
kube-system   canal-etcd-37dqr                                 0/1       MatchNodeSelector   0          2d
kube-system   canal-node-f9zxc                                 2/3       CrashLoopBackOff    252        2d
kube-system   canal-node-zmmqj                                 2/3       CrashLoopBackOff    108        1d
kube-system   dummy-2088944543-4mgf3                           1/1       Running             5          2d
kube-system   etcd-slc07ylr.us.oracle.com                      1/1       Running             6          2d
kube-system   kube-apiserver-slc07ylr.us.oracle.com            1/1       Running             0          17h
kube-system   kube-controller-manager-slc07ylr.us.oracle.com   1/1       Running             10         2d
kube-system   kube-discovery-1769846148-0gf34                  0/1       MatchNodeSelector   0          2d
kube-system   kube-discovery-1769846148-hx525                  1/1       Running             4          18h
kube-system   kube-dns-2924299975-4k9d8                        0/4       Error               0          2d
kube-system   kube-proxy-l0kxp                                 1/1       Running             1          1d
kube-system   kube-proxy-swv9z                                 1/1       Running             5          2d
kube-system   kube-scheduler-slc07ylr.us.oracle.com            1/1       Running             10         2d
kube-system   kubernetes-dashboard-3203831700-3w9qn            0/1       Error               0          2d

I see issue when I attempt to start dashboard container:

[root@slc07ylr ~]# docker ps -a | grep 'dashboard'
42377bceaa6c        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 3 seconds ago       Exited (0) 1 second ago                                 k8s_POD.d8dbe16c_kubernetes-dashboard-3203831700-3w9qn_kube-system_51a045ec-fb30-11e6-9397-0021f6b61679_4f60ac1b
32e235b604d8        gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1      "/dashboard --port..."   2 days ago          Exited (255) 18 hours ago                               k8s_kubernetes-dashboard.6d4dd84f_kubernetes-dashboard-3203831700-3w9qn_kube-system_51a045ec-fb30-11e6-9397-0021f6b61679_3f9cb75a
[root@slc07ylr ~]# docker start 32e235b604d8
Error response from daemon: No such container: b3623e5f99506c33a37202bfee9a991d124e046ada95c759acd7b165c11a8249
Error: failed to start containers: 32e235b604d8

what is possible way to bring back dashboard up?

**Comment by harighub** [comment]
Looks like dashboard is connected successfully api server. 
kubectl logs kubernetes-dashboard-3203831700-3w9qn --namespace=kube-system
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Successful initial request to the apiserver, version: v1.5.0
Creating in-cluster Heapster client
Using service account token for csrf signing

**Comment by cheld** [comment]
So, is it working? Can we close?

**Comment by harighub** [comment]
Nope, showing dash-board status as:

kube-system   kubernetes-dashboard-3203831700-h85pv            0/1       ContainerCreating   0          7m
[

**Comment by harighub** [comment]
Finally I'm able to access dashboard after re-installing cluster/pod network and deploy dashboard.

**Comment by vglisin** [comment]
I think that only bunch of very strange people can put documentation of creating kubernetes cluster with kubeadm and then hide in a middle of whole documentation: "Please note, this works only if the apiserver is set up to allow authentication with username and password. This is not currently the case with some setup tools (e.g., kubeadm")."
So, if you manage to setup kubernetes dashboard looking into documentation of these strange people, you are more than a Genuis.

**Comment by floreks** [comment]
You are referring to document (it is not Dashboard's documentation) that hasn't been updated for quite some time and is based on dashboard 1.5. Up-to-date documentation is always available on our wiki pages.

We will update it...

PS. It is not that hard to setup everything after reading latest **documentation**: https://github.com/kubernetes/dashboard/wiki
