### ISSUE TITLE
Feature request: Jobs should be sorted by date instead of name

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/dashboard#1677]
#### Issue details
It appears that jobs are sorted by name.  I think sorting by date would make more sense for batch type work.  i.e.  Newest jobs show up at the top of the list.  

Ideally this issue gets addressed across all resources in a flexible way, see https://github.com/kubernetes/dashboard/issues/966

**Comment by Southclaws** [comment]
Yes, one hundred times yes.
It's especially annoying when your pods are named by UUID so you end up with a meaningless sort order.
If we can't have the option to sort in the UI (#966) then at least make the default sort order a more meaningful one.

**Comment by mhenc** [comment]
@maciaszczykm @floreks What do you think about that?

**Comment by floreks** [comment]
That's for sure an important feature. We'll try to invest some time and implement that.

**Comment by maciaszczykm** [comment]
Waiting to be finally merged :)

**Comment by maciaszczykm** [comment]
Done, sorting will be available in HEAD release in 1-2 hours and in next official release.

**Comment by tsublette** [comment]
+1 !!!!!!!
