### ISSUE TITLE
Feature request: parse URLs in annotations

### ISSUE THREAD

**Issue by Starefossen** [kubernetes/dashboard#1680]
Not sure how common this is but we are storing URLs to various external resources (jenkins build, git repo, documentation++),  as annotations for deployments, services and all other objects in Kubernetes and it would be nice if they where parsed and clickable from the UI without having to copy/paste them.

**Comment by cheld** [comment]
Can you share a screenshot?

**Comment by Starefossen** [comment]
Currently annotations looks like this:

<img width="1142" alt="screen shot 2017-03-01 at 10 17 01" src="https://cloud.githubusercontent.com/assets/968267/23453493/e08de570-fe68-11e6-9eee-9a7ea9c1c51a.png">

With automatic URL parsing it would look like this:

<img width="1139" alt="screen shot 2017-03-01 at 10 21 30" src="https://cloud.githubusercontent.com/assets/968267/23453500/e73bd512-fe68-11e6-94c0-75a935da8558.png">
