### ISSUE TITLE
We should do next major release

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1688]
We should do next major release and upstream it to latest Kubernetes. This is because we've added a lot of new features recently.

Before we do this, however, we need to validate that there are no half-baked WIP features.

@floreks @maciaszczykm @cheld @IanLewis What WIP is currently blocking the release?

**Comment by floreks** [comment]
I guess only thing that is a potential blocker is missing frontend for TPR instances. It should not take long to implement frontend so maybe we could take next week to finish everything and then do a code freeze for features. 

@maciaszczykm what do you think?

I should be able to finish implemeting basic support for sorting and maybe filtering next week.

**Comment by bryk** [comment]
Sounds cool. Can you be this release's tzar and make sure we're withing Kubernetes core timelines and schedules? :)

**Comment by maciaszczykm** [comment]
> missing frontend for TPR instances

I'm only aware of this. Working on finishing backend today and should start it soon. If we want pagination here (in longer run we do) it could take one or two days more.

Next week is realistic estimate for whole work to be finished, then we can work on next iteration :)

**Comment by bryk** [comment]
> Next week is realistic estimate for whole work to be finished, then we can work on next iteration :)

Yep. We should do QA before releasing. How about having explicit sign-off from 3-4 folks?

**Comment by maciaszczykm** [comment]
@bryk We might be able to do it and for sure we will test on our own. There were few bigger changes like client-go migration or further refactoring and it needs to be checked before release.

**Comment by cheld** [comment]
There seems to be an issue with latest Hyperkube and kubeadm. 1.6 I had no time to investigate yet.

See also: https://github.com/kubernetes/dashboard/issues/1578

**Comment by maciaszczykm** [comment]
@bryk TPRs are in #1695 waiting for review :) Today I'm going to start tests.

**Comment by maciaszczykm** [comment]
@bryk Do you know when there will be next stable Kubernetes release? I cannot find anything...

**Comment by bryk** [comment]
Awesome. What's totally essential to cut the release? We have only a few days left.

**Comment by maciaszczykm** [comment]
TPR and maybe @floreks' sorting. AFAIK he's already finishing it, but we need to review and test it.

**Comment by maciaszczykm** [comment]
@bryk Do you know exact date when we need to finish dev and prepare for a release?

**Comment by bryk** [comment]
That's the timeline: https://github.com/kubernetes/features/blob/master/release-1.6/release-1.6.md

We should be fast, but if we miss the deadline, that's not a problem since 1.6.1 will be released soon after.

**Comment by bryk** [comment]
@maciaszczykm Will you craft release notes for our 1.6? When we have this we can push to gcr.io repo (I can do this) and send PRs to customer's repos.

**Comment by maciaszczykm** [comment]
@bryk Sure, we'll do it tommorow.

**Comment by bryk** [comment]
I found an issue that v1.6.0 tag does not start on a GKE cluster. Error I get is: 

```
 kubectl logs dash-demo-2-pyqhs
Using HTTP port: 9090
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: invalid configuration: default cluster has no server defined
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
```

Can you investigate?

**Comment by bryk** [comment]
I updated https://github.com/kubernetes/dashboard/releases/tag/v1.6.0 to DRAFT and pre-release for now.

**Comment by bryk** [comment]
When this is fixed, we must do v1.6.1 when this is fixed

**Comment by maciaszczykm** [comment]
Okay, we'll do it as soon as we'll fix `client-go`-related issue.

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/releases/tag/v1.6.0 is fixed now.
