### ISSUE TITLE
please describe how to run the application

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#17]
please add some more documentation, about how to build & run the application

**Comment by bryk** [comment]
Will definitely do! I'll take some time, however, till the application is production ready.

Do you want this to hack around and contribute or to use the app in production?

**Comment by cheld** [comment]
I want to contribute in the UI area. Currently, I would like to understand the difference between kube-ui, kubedash and console...

**Comment by preillyme** [comment]
@cheld I'd like to understand the difference as well. If console can do everything that kube-ui can do I'd like to retire kube-ui. I don't think we should have three different but similar efforts.

**Comment by SebastianM** [comment]
@bryk I'm interested too. I started to work on a new kube-ui version that is capable of managing multiple kubernetes clusters and adds some Cluster management features. So question is: why is there a second project?

https://github.com/kubernetes/kube-ui/tree/new-ui

**Comment by stevesloka** [comment]
+1 for contributing and +1 for understanding the differences.

**Comment by bryk** [comment]
Re "please describe how to run the application": As you can see, we're now busy building awesome development environment for the project. Once this is done, the instruction about how to run and develop the application will land here. This should take a few days more.

**Comment by bryk** [comment]
Re what is this project: This is a general purpose GUI for Kubernetes clusters. In brief, it will allow for managing and troubleshooting applications running on a cluster. In this project we've taken a use-case product approach. This means that we're not doing a raw dump of all possible resources in the cluster. Instead, we create views that best satisfy use cases, e.g., "deploy my first app" or "troubleshoot a production issue in the app".

**Comment by bryk** [comment]
Re why new project: Simply, all planned views are going to be different from the ones that exist in current UIs. So instead of rewriting everything we did a clean start. We plan, however, to reuse individual components from kubedash, kube-ui or kubernetes-ui.

**Comment by bryk** [comment]
Re roadmaps and mocks: We will publish them soon. We did not anticipate such interest in the early stages of the development, so that's why we didn't do this already. Thanks for the interest! We will keep you posted on everything. If you have any more questions, just ask me :)

**Comment by luxas** [comment]
+1 I'm also very interested in this area.
When this project is ready to contribute to, I'll see if there is something I am able to do
Keep us notified :smile:

**Comment by bryk** [comment]
@luxas That's awesome! There's a community meeting soon, you can join it. See more details at: https://groups.google.com/forum/#!forum/kubernetes-sig-ui

**Comment by jordic** [comment]
I'm also interested in contributing.

**Comment by bryk** [comment]
@cheld Are you working on this?

**Comment by cheld** [comment]
yes, I started

**Comment by cheld** [comment]
basic documentation how to build & run has been added to the read-me
