### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by sgrichardson** [kubernetes/dashboard#1702]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
Get https://10.0.0.1:443/api/v1/nodes: read tcp 172.17.0.2:41916->10.0.0.1:443: read: connection reset by peer

```

**Comment by maciaszczykm** [comment]
Hey, we need more details to reproduce the bug and help you solve it. Please fill the template and reopen bug if it still occurs.
