### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by dipadipa** [kubernetes/dashboard#1705]
##### Environment

```
Dashboard version:1.5.1
Kubernetes version:1.5
Operating system:ubuntu16.04
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
daemonsets.extensions "calico-node" not found

```

**Comment by maciaszczykm** [comment]
Hi, you probably entered a page of orphaned pod which was connected to daemon set. Issue is fixed in latest head release and will be in next official release. I'm closing the issue, please reopen if you have any details more.
