### ISSUE TITLE
Kube dashboard fails to start with Crashloopoff

### ISSUE THREAD

**Issue by githubvick** [kubernetes/dashboard#1706]
#### Issue details

Trying to run Kubernetes dashboard on already existing and working cluster. Downloaded from https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

When I start kube dashboard it fails with below error

##### Environment

```
Dashboard version: v1beta1
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-03-07T00:03:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-03-07T00:03:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
Operating system: Red Hat Enterprise Linux Server release 7.3 (Maipo)
Node.js version:
Go version:
```

##### Steps to reproduce

1) Setup basic cluster
2) Setup authentication using certificates and kubeconfig using this link
http://www.dasblinkenlichten.com/kubernetes-authentication-plugins-and-kubeconfig/
3) Downloaded dashboard yaml from link provided above. 
4) KUBE_CONTROLLER_MANAGER_ARGS="--root-ca-file=/etc/kubernetes/ssl/ca.crt" and provided permissions of 755.
5) Start kube dashboard

##### Observed result

```
Using HTTP port: 9090
Using apiserver-host location: http://11.168.24.xxx:8080
Creating API server client for http://11.168.24.xxx:8080
Successful initial request to the apiserver, version: v1.5.2
Creating in-cluster Heapster client
E0309 17:16:25.511333       1 config.go:275] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
E0309 17:16:25.511333       1 config.go:275] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-1076339410-4jl8v.unknownuser.log.ERROR.20170309-171625.1: no such file or directory

```

##### Expected result

Dashboard to start without errors
##### Comments

1) Kubedns is up and running.

When I give this command kubectl get pod kube-dns-v20-m26v4 -o  yaml --namespace=kube-system volume mounts are fine.
volumeMounts:
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    name: default-token-tkce6
    readOnly: true
but logging into kubedns container, I don't see any files or dirs after /var/run/secrets

2)
See these errors in the logs.

Failed to start certificate controller: open /etc/kubernetes/ca/ca.pem: no such file or directory - But nowhere I have given the path above.

kube-scheduler: E0309 12:03:01.911684     743 reflector.go:199] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:463: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused

k8s.io/kubernetes/plugin/pkg/admission/resourcequota/resource_access.go:83: Failed to list *api.ResourceQuota: Get http://0.0.0.0:8080/api/v1/resourcequotas?resourceVersion=0: dial tcp 0.0.0.0:8080: getsockopt: connection refused

**Comment by cheld** [comment]
There is something wrong with your kuberentes setup. Most likely, service accounts not working. Please check the trouble shooting guide: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md#service-account

**Comment by githubvick** [comment]
Hi Cheld, thx for your reply. 

My understanding is that the ca.crt should be automounted in the pod container by default. I use this KUBE_API_ARGS="--client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key" and all other components including kube dns works fine.

I had followed the troubleshooting document earlier and got this 

kubectl exec test-701078429-td4vf ls /var/run/secrets/kubernetes.io/serviceaccount/
namespace
token

and deleted the secret as suggested since the ca.crt was missing. I'm using a non standard installation I guess in that I installed kubernetes through yum and manually configured all components. I already have a working kube cluster with Dashboard configured without https. The only difference between the earlier cluster and this one is that I tried to configure https for the api server. I'm able to view the ca.crt files in my working kube cluster. 

Someone suggested in slack that this might be an issue in Docker/Kubernetes latest version, so raised this issue.

**Comment by cheld** [comment]
Yes ca.crt should automatically mounted. Unfortunately, I have never setup service account. 

An alternative is to use kubeconfig file. Again, see the trouble shooting guide https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md#kubeconfig

**Comment by githubvick** [comment]
I actually deleted the service account itself and the secret and it worked fine. Maybe in the trouble shooting guide, you can add this one as well. to delete and create the default service account. 

Closing this, thanks once again for looking into this.

**Comment by cheld** [comment]
Could you please paste the commands? So, I can understand better the solution...

**Comment by githubvick** [comment]
Sure, just deleted the default service account

kubectl get serviceAccounts

NAME      SECRETS   AGE
default   1         2d

kubectl delete serviceAccount default

Think I deleted the default secret after running this command, Both the service account and secret should be created immediately after deletion.

**Comment by floreks** [comment]
Deleting SA should also delete related secret and recreate it immediately. As for the configuration it's just the matter of adding `--admission-control=ServiceAccount` param to api server and `--service-account=cert` to controller manager.
