### ISSUE TITLE
TPR location in the menu

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1709]
Quoting from @danielromlein's https://github.com/kubernetes/dashboard/pull/1695#issuecomment-285441166:

> Since TPR's are not Namespaced, might there be a better location in the information architecture than where they are currently? The navigation scheme was to have only namespace-dependent objects below the Namespace dropdown...
/ @maciaszczykm @floreks @bryk

**Comment by maciaszczykm** [comment]
If there are >3 TPRs perhaps we should display only 3 of them in the menu and in the next line put a link to list of all of them (something like `... and X more`)?

**Comment by danielromlein** [comment]
I still need to learn more about ThirdPartyResources, but I met with @normalnorman today and he suggested two possible approaches that seem to me worth considering:
1. Have a system-generated Namespace that corresponds exclusively to TPRs and is auto-assigned to any TPR created.
2. Reevaluate how we think about Namespaces and change their representation in the information architecture of Dashboard.

Thoughts?

**Comment by cheld** [comment]
TPR are namespaced. (Only the meta objects that describe the TPR are not). In general the menu seems ok. 

Maybe the label 'Third Party Resource' should be replaced with something less technical (e.g. 'Other'). But on the other hand it is the official name. Names should be shortened, as discussed. 

@danielromlein I don't think we should change the namespace handling in general or in respect of TPR. 

However, there is a fundamental problem with the TPR in the menu. From user perspective, it would make sense to add TPR to the existing menus, e.g. a TPR 'cron-tab' is a workload, a TPR 'lets-encrypt-certificate' is a config. Unfortunately, we don't know the meaning, so we have to group them in separate menu.

**Comment by danielromlein** [comment]
@cheld ah OK. I was confused by the [docs](https://kubernetes.io/docs/user-guide/thirdpartyresources/) saying,
>`ThirdPartyResources` themselves are non-namespaced and are available to all namespaces.

So that's referring to the meta objects _describing_ the TPR?

**Comment by danielromlein** [comment]
I'm wondering if we might want to consider having just the "Third-Party Resources" navigation item and not list any of its children? Certainly `cron-tab.stable.example.com` is a disorienting navigation item for a user to have to parse through.
How many Third-Party Resource objects will a user typically have? If the >3 use-case is typical then I think that more strongly supports not showing any children.

**Comment by maciaszczykm** [comment]
> How many Third-Party Resource objects will a user typically have? If the >3 use-case is typical then I think that more strongly supports not showing any children.

@danielromlein I'm not sure if it's typical, but there is a possibility of having dozens of them. Most of the uses won't have any TPRs in their system, but there will be a few people using them.

> Certainly `cron-tab.stable.example.com` is a disorienting navigation item for a user to have to parse through.

`cron-tab.stable.example.com` name will be changed soon to more user-friendly. There is issue #1708 for this.

**Comment by maciaszczykm** [comment]
I like the idea of getting rid of that issue and leaving only TPR link in the menu. We don't have much space in the menu anyways and new resources will come soon.

**Comment by danielromlein** [comment]
>I like the idea of getting rid of that issue and leaving only TPR link in the menu. We don't have much space in the menu anyways and new resources will come soon.

Ok, cool. Let's move forward with that solution then.

If we're changing "ThirdPartyResources" to be more a user-friendly "Third Party Resources", WDYT addition of a hyphen: "Third-Party Resources"?

Will that nav item, "Third-Party Resources" be shown on all Dashboard instances, regardless of whether or not a user has TPRs set up?

**Comment by floreks** [comment]
> Will that nav item, "Third-Party Resources" be shown on all Dashboard instances, regardless of whether or not a user has TPRs set up?

It is dynamically added only if there are any TPRs registered.

As for the addhing hyphen, both solutions work for me. In documentation they are actually using `Third Party Resources` name.
