### ISSUE TITLE
Switch hyperkube to something else as it is deprecated

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#1710]
#### Issue details
I tried to update build/hyperkube.sh to the latest version (1.6-beta), but it fails to a few small issues. I guess it is not maintained any more. 

I think the two official alternatives are minikube and kubeadm. For travis only kubeadm can be used, I guess.

@bryk, @luxas any suggestions?

**Comment by cheld** [comment]
@maciaszczykm, @floreks do you have any idea?

**Comment by maciaszczykm** [comment]
@cheld We should wait till 1.6.0 is out and test it on stable release. Recently we've switched to 1.5.4 and it works just fine: 

https://github.com/kubernetes/dashboard/blob/master/build/hyperkube.sh#L20

**Comment by luxas** [comment]
@cheld It's not maintained anymore, correct.

Please use kubeadm, that's maintained and much more secure than docker-multinode

**Comment by cheld** [comment]
hmm...we use single node hyperkube for build. So security is not really a concern. I assume that kubeadm will slow down travis, but I can give it a try

**Comment by cheld** [comment]
kubeadm also needs sudo - not very nice for build script....

**Comment by cheld** [comment]
We might use:

https://github.com/Mirantis/kubeadm-dind-cluster

A new version is planned to be moved to kubernetes, rewritten in go.

**Comment by luxas** [comment]
cc @ivan4th 

I think you might even be able to use it as-is now, and maybe help Ivan with the Go version if that's of interest

**Comment by ivan4th** [comment]
@luxas thanks for the mention.

I think I'll be able to get back to DIND work in coming weeks and get some progress with Go version.
Yet I confirm that [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) works just fine on Travis, starting 3-node k8s 1.6 cluster  (1 master + 2 workers) takes about 7 min there.

**Comment by luxas** [comment]
@cheld I guess that's what you want then, when it works well on Travis. And you got multiple nodes for free ;)

**Comment by maciaszczykm** [comment]
We should consider doing it faster as new problems may occur. Few people already occured errors connected to hyperkube and it makes no sense for us to stick with it.

**Comment by cheld** [comment]
I am using DIND cluster for a while now. So for it works very well.
