### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1719]
Should it be done like in #1446 for 1.5?

**Comment by bryk** [comment]
Yes, it should :)

**Comment by maciaszczykm** [comment]
Quite a high priority right now. A lot of changes were made and people need to know how to use security layer, that was introduced to the app.

**Comment by maciaszczykm** [comment]
Should be done ASAP.

**Comment by jimangel** [comment]
I can tackle it. From this issue, the focus is on screen shots and general "what's new" docs? I still plan to delete a lot of documentation that reference older version setups / issues / etc and focus on improving the k8s 1.8-1.11 information and support.

**Comment by maciaszczykm** [comment]
Yes, exactly. It would be nice to let people know that project is alive and give them some input about current state, setup manual etc.

**Comment by maciaszczykm** [comment]
Hi @jimangel, do you have any progress here?
