### ISSUE TITLE
Switch to Codecov and Greenkeeper integrations

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1720]
![image](https://cloud.githubusercontent.com/assets/2823399/23852443/13356d8a-07e8-11e7-8849-e9e2c129407c.png)

![image](https://cloud.githubusercontent.com/assets/2823399/25797042/feaa97f8-33db-11e7-804b-0e00738b3d72.png)

**Comment by maciaszczykm** [comment]
https://github.com/integrations/codecov

Code coverage check would also be a good improvement.

**Comment by bryk** [comment]
Done, I think. Can you verify?

**Comment by maciaszczykm** [comment]
@bryk I guess we have to wait till integrations will be used.

**Comment by maciaszczykm** [comment]
Codecov works, let's keep it open to verify also Greenkeeper.

**Comment by maciaszczykm** [comment]
I have seen Greenkeeper check so it seems to works too. Closing it :-)
