### ISSUE TITLE
Some tooltips don't disappear

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1734]
![image](https://cloud.githubusercontent.com/assets/2823399/23943291/4b9a66de-096f-11e7-90a5-8ecdabe1f4eb.png)

Screenshot from secret detail view, mouse wasn't on item.

**Comment by floreks** [comment]
It's default angular material behavior. I have opened an issue there: https://github.com/angular/material/issues/10538. Closing here. We will update angular material version when it's fixed there.

**Comment by maciaszczykm** [comment]
I suggest to keep it to track issue.

**Comment by maciaszczykm** [comment]
One more issue with it from #877:

> Ok, this looks like angular material bug when used with target="_blank", we should create an issue there. I've created example codepen to show the issue.
>
> http://codepen.io/anon/pen/WxwpwE

**Comment by floreks** [comment]
Closing as this is not dashboard issue. It does not seem to be fixed any time soon on angular side. We are keeping our dependencies up to date so if it will be fixed upstream then it will be fixed in dashboard also.
