### ISSUE TITLE
Can I deploy pod with more than one containers?

### ISSUE THREAD

**Issue by lucklove** [kubernetes/dashboard#1735]
It seems dashboard allow only one image url in every deploy.

**Comment by floreks** [comment]
Currently you can only deploy resources with more than one container using deploy from file option. We are planning to rebuild from scratch resources creation flow but don't have any exact dates yet.

**Comment by floreks** [comment]
Can be tracked from #1600. Closing for now. If you have more questions feel free to create new issue.
