### ISSUE TITLE
1.6 image not available from GCR

### ISSUE THREAD

**Issue by zsustar** [kubernetes/dashboard#1740]
#### Issue details
The latest dashboard yaml deplyment files refers to image  v1.6.0
 containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0

However this version of image is not available on GCR any more, the latest available update is v1.5.1

Workaround: download the yaml to local and change the image from 
 `       image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
to        
`     image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.1
and create the dashboard deployment
` kubectl create -f kubernetes-dashboard.yaml`

**Comment by floreks** [comment]
Unfortunately we've had some issues and found a critical bug during the release. Image should be available later today. Sorry for the confusion and the delay.

**Comment by maciaszczykm** [comment]
@zsustar 1.6.0 release is available to download at https://github.com/kubernetes/dashboard/releases/tag/v1.6.0.
