### ISSUE TITLE
Why is NodePort exposed?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#1744]
Why does the `kubernetes-dashboard` service exposing via NodePort by default? https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml

**Comment by floreks** [comment]
I'm not sure why it was added there. One reason might be that it makes dashboard easily accessible on local clusters such as minikube(they are even exposing it using NodePort 30000). Usually kubelet is bound to local ip anyway so there should not be any security issues there. 

However if there are any security issues related to NodePort beeing default way of exposing dashboard then we might consider changing that.

@maciaszczykm @rf232 @bryk WDYT?

**Comment by bryk** [comment]
We could be ClusterIP by default and do NodePort in minikube and other environments that need this. I like @colemickens proposal.

**Comment by cheld** [comment]
I did a bit of research:

* it was introduced a while ago: https://github.com/kubernetes/dashboard/commit/8d249ecaf9cdc3487aa7b008c26027003ae47d8d

* minikube is using nodeport, but it uses own deployment descriptors

* the descriptor is most likely used by kubeadm users

So, I don't see any reason to keep nodeport
