### ISSUE TITLE
Remove app name from deploy from file directive in UI

### ISSUE THREAD

**Issue by batikanu** [kubernetes/dashboard#175]
Since the files have already name attribute inside, we can remove `app name` from [GUI](https://github.com/kubernetes/dashboard/blob/master/designs/11-11-2015/04_deploy%20form%20upload.png), when upload file is selected.  

@kenmoore

**Comment by floreks** [comment]
In my opinion this can stay and when file is selected then name can be shown. This is basic information and it would be good to display it after parsing the file.

**Comment by bryk** [comment]
Yeah, that's very good idea @floreks. But then there lots of corner cases, i.e., YAML does not contain a replication controller, or has two. This is getting more and more complicated.

**Comment by floreks** [comment]
Other option is to show short report of what actually was read from file. Something like `2 rc, 1 service, 1 namespace will be created` and then on click show detailed report from extracted data, possibly with some validation.

**Comment by floreks** [comment]
Alread done.
