### ISSUE TITLE
Dashboard pod fails with CrashLoopBackOff CA key on new CentOS cluster nodes

### ISSUE THREAD

**Issue by BrandonPotter** [kubernetes/dashboard#1752]
#### Issue details

Dashboard deployment creates pod, but fails with `CrashLoopBackOff` status.

```
[root@kube1 ~]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
default       nginx                                   1/1       Running            0          15h
kube-system   kubernetes-dashboard-3203962772-zt7j1   0/1       CrashLoopBackOff   190        15h

```

Failing node docker log indicates the following:

> Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory

Not sure if problem with dashboard specifically (since other containers do run) or if another step needs to be added to configure service accounts/keys on CentOS during setup.

##### Environment

Operating system: CentOS Linux release 7.3.1611 (Core)

```
[root@kube1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-03-07T00:03:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-03-07T00:03:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps to reproduce

1. Provision CentOS (minimal) VM's
2. New CentOS install per instructions @ https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/
3. Run `kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml`

##### Observed result

`CrashLoopBackOff` status in `get pods --all-namespaces`

# describe pod

```
[root@kube1 ~]# kubectl describe pod kubernetes-dashboard-3203962772-zt7j1 -n kube-system
Name:           kubernetes-dashboard-3203962772-zt7j1
Namespace:      kube-system
Node:           kube3/10.0.137.12
Start Time:     Thu, 16 Mar 2017 22:26:11 -0400
Labels:         app=kubernetes-dashboard
                pod-template-hash=3203962772
Status:         Running
IP:             172.30.24.2
Controllers:    ReplicaSet/kubernetes-dashboard-3203962772
Containers:
  kubernetes-dashboard:
    Container ID:       docker://8412ad8886556a65d6b4d1a86ecc86779a581f46b8cf7059f53d084488dc7e20
    Image:              gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
    Image ID:           docker-pullable://gcr.io/google_containers/kubernetes-dashboard-amd64@sha256:4ad64dfa7159ff4a99a65a4f96432f2fdb6542857cf230858b3159017833a882
    Port:               9090/TCP
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Error
      Exit Code:        2
      Started:          Fri, 17 Mar 2017 14:25:36 -0400
      Finished:         Fri, 17 Mar 2017 14:25:37 -0400
    Ready:              False
    Restart Count:      191
    Liveness:           http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-s2xgk (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  default-token-s2xgk:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-s2xgk
QoS Class:      BestEffort
Tolerations:    dedicated=master:Equal:NoSchedule
Events:
  FirstSeen     LastSeen        Count   From            SubObjectPath                           Type            Reason                  Message
  ---------     --------        -----   ----            -------------                           --------        ------                  -------
  16h           3m              194     {kubelet kube3} spec.containers{kubernetes-dashboard}   Normal          Pulling                 pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
  16h           3m              193     {kubelet kube3}                                         Warning         MissingClusterDNS       kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  16h           3m              192     {kubelet kube3} spec.containers{kubernetes-dashboard}   Normal          Pulled                  Successfully pulled image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
  15h           3m              183     {kubelet kube3} spec.containers{kubernetes-dashboard}   Normal          Created                 (events with common reason combined)
  15h           3m              183     {kubelet kube3} spec.containers{kubernetes-dashboard}   Normal          Started                 (events with common reason combined)
  16h           6s              4448    {kubelet kube3} spec.containers{kubernetes-dashboard}   Warning         BackOff                 Back-off restarting failed docker container
  15h           6s              4419    {kubelet kube3}                                         Warning         FailedSync              Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-zt7j1_kube-system(15f4af4b-0ab9-11e7-a89d-005056ac11c9)"

```

# output of docker ps -a on node

```
[root@kube3 ~]# docker ps -a
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED              STATUS                          PORTS               NAMES
cc41b58a371a        gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0   "/dashboard --port=90"   About a minute ago   Exited (2) About a minute ago                       k8s_kubernetes-dashboard.a34dd860_kubernetes-dashboard-3203962772-zt7j1_kube-system_15f4af4b-0ab9-11e7-a89d-005056ac11c9_5ccb61b4
3cde46989ecd        registry.access.redhat.com/rhel7/pod-infrastructure:latest   "/pod"                   16 hours ago         Up 16 hours                                         k8s_POD.28c50bab_kubernetes-dashboard-3203962772-zt7j1_kube-system_15f4af4b-0ab9-11e7-a89d-005056ac11c9_5ced24cf

```

# docker logs on node

```
[root@kube3 ~]# docker logs cc41
E0317 18:30:49.265701       1 config.go:287] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
Using HTTP port: 9090
E0317 18:30:49.265701       1 config.go:287] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-3203962772-zt7j1.unknownuser.log.ERROR.20170317-183049.1: no such file or directory

```

##### Expected result

Running Dashboard pod

**Comment by floreks** [comment]
According to [link](https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/) you've provided this cluster setup does not have Service Accounts configured.

If you don't have experience with configuring kubernetes then you might want to try out [minikube](https://github.com/kubernetes/minikube). It does have SA configured and is easy to start.

If you would like to try setup the cluster on your own, check out my [basic guide](https://github.com/kubernetes/dashboard/issues/1287#issuecomment-250681546) explaining how to configure secure local cluster with certificates and SA enabled (certificate setup should not be needed, only SA).

Starting from version 1.6 dashboard requires SA to be enabled in the cluster. We have added comment in our release notes.

**Comment by BrandonPotter** [comment]
Right now, setting up an experimental CentOS cluster after being on GCP where everything just works... opened this issue to help search results on it since it's fairly easy to run into, but would also like to better understand the internals myself. Thank you for the other thread/guide, for some reason I had not found that one.

This might be a super dumb question, but if I satisfy the error condition by running the following on the node:

```
mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
cd /var/run/secrets/kubernetes.io/serviceaccount
openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -days 365 -out ca.crt -subj "/CN=kube-ca"
```

... why would it still log the same error (file not found)? I was kind of assuming the dashboard container was mounting the node's path to `ca.key`, but that doesn't appear to be the case?

**Comment by floreks** [comment]
It's kubernetes that mounts service accounts into the pod. Dashboard is just an app and it does not configure anything by itself. API server requires `--admission-controller` with `ServiceAccount`  and controller manager needs `--service-account-private-key-file`(might be different, check docs to confirm) argument to enable service account. API Server needs it to identify pod and controller manager mounts it into the pod.

Also if I remember correctly certs are automatically generated by kubernetes and stored in `var/run/kubernetes` or some other system path, and they are mounted from there if all components are configured properly. 

Good luck :)

**Comment by BrandonPotter** [comment]
Interesting thing is I had already configured these on master:

```
[root@kube1 kubernetes]# kubectl get serviceaccount
NAME      SECRETS   AGE
default   1         18h

[root@kube1 kubernetes]# kubectl describe serviceaccount default
Name:           default
Namespace:      default
Labels:         <none>

Image pull secrets:     <none>

Mountable secrets:      default-token-sx2fn

Tokens:                 default-token-sx2fn

```

## apiserver

`KUBE_API_ARGS="--service_account_key_file=/tmp/serviceaccount.key"`

## controller-manager

`KUBE_CONTROLLER_MANAGER_ARGS="--service_account_private_key_file=/tmp/serviceaccount.key"`

With `get pods <dashboard-pod> -n kube-system -o yaml` I see this:

```
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-s2xgk
      readOnly: true
```

Also, following [this guide](https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md), if I spin up a test container and run:

`kubectl exec <test_pod_name> ls /var/run/secrets/kubernetes.io/serviceaccount/`

... I have `namespace` and `token`. Missing `ca.crt`.

Two things stick out here, the token name in the pod YAML doesn't match the describe serviceaccount token name, and missing ca.crt in `/var/run/secrets/kubernetes.io/serviceaccount/` from the container's perspective. Are both of these a problem?

**Comment by floreks** [comment]
https://kubernetes.io/docs/admin/kube-apiserver/

Check `--admission-controller` param. Service accounts is a plugin. Without that it will not work.

**Comment by BrandonPotter** [comment]
`ServiceAccount` is in the list in `apiserver` config. :(

`KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"`

**Comment by floreks** [comment]
To recreate token you can just delete default service account from `kube-system` namespace. It will recreate secret and sa. As for the `ca.crt` in order for the controller to mount it into the pod you need to add `--root-ca-file` param to controller manager.

**Comment by zouyee** [comment]
when your start kubelet that must be configure ca-file

**Comment by karunakar1122v** [comment]
Hi,
I am installing kubernetes 1.3.0 on Ubuntu 16.10. kubernetes master and node up and running.
Kubernetes cluster also running.
But when I am trying to create kubernetes-dashboard facing below issue?
Anyone let meknow what was the issue exactly?

E0317 18:30:49.265701       1 config.go:287] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
Using HTTP port: 9090
E0317 18:30:49.265701       1 config.go:287] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-3203962772-zt7j1.unknownuser.log.ERROR.20170317-183049.1: no such file or directory

**Comment by floreks** [comment]
Closing as stale and related to cluster configuration not dashboard itself.
