### ISSUE TITLE
Dashboard use wrong url to get heapster metrics?

### ISSUE THREAD

**Issue by radishgz** [kubernetes/dashboard#1754]
#### Issue details
My dashboard can't get heapster metrics , no CPU and Memory usage content.

##### Environment
 
Dashboard version: kubernetes-dashboard-amd64:v1.6.0
Kubernetes version: 1.4.7
Operating system: centos 7.2
Heapster : heapster-amd64:v1.3.0-beta.1 
I have look dashboard log and found: 
Skipping Heapster metrics because of error: an error on the server ("Error: 'dial tcp 172.30.79.5:8082: getsockopt: no route to host'\nTrying to reach: 'http://172.30.79.5:8082/api/v1/model/namespaces/kube-system/pod-list/heapster-3925791291-toe2e,kube-dns-v20-y9o1o,kubernetes-dashboard-1961665494-hrlfm,monitoring-grafana-3344903701-l5mfu,monitoring-influxdb-1433623390-xf24d,traefik-ingress-controller-2307324806-bvgea/metrics/cpu/usage_rate'") has prevented the request from succeeding (get services heapster)
Skipping Heapster metrics because of error: an error on the server ("Error: 'dial tcp 172.30.79.5:8082: getsockopt: no route to host'\nTrying to reach: 'http://172.30.79.5:8082/api/v1/model/namespaces/kube-system/pod-list/heapster-3925791291-toe2e,kube-dns-v20-y9o1o,kubernetes-dashboard-1961665494-hrlfm,monitoring-grafana-3344903701-l5mfu,monitoring-influxdb-1433623390-xf24d,traefik-ingress-controller-2307324806-bvgea/metrics/cpu/usage_rate'") has prevented the request from succeeding (get services heapster)

dashboard use url kube-system/pod-list but I read heapster documents it seem should be  kube-system/pods .

I also use docker exec to exec wget in heapster contain, get follow result

 # wget http://127.0.0.1:8082/api/v1/model/namespaces/kube-system/pods
Connecting to 127.0.0.1:8082 (127.0.0.1:8082)
pods                 100% |**********************************************************************************************************************************************************************|   233   0:00:00 ETA
/ # cat pods
[
  "heapster-3925791291-toe2e",
  "traefik-ingress-controller-2307324806-bvgea",
  "monitoring-influxdb-1433623390-xf24d",
  "kube-dns-v20-y9o1o",
  "monitoring-grafana-3344903701-l5mfu",
  "kubernetes-dashboard-1961665494-hrlfm"

**Comment by floreks** [comment]
Pod list is also correct. `api/v1/model/namespaces/{namespace}/pods/{pod}` is for getting pod-level metrics. We are gathering metrics for list of pods in order to provide summary cpu/memory usage.

Here is a handler registered for `pod-list`: https://github.com/kubernetes/heapster/blob/a235099f87417711022d99d6537a506aa9da81d3/metrics/api/v1/model_handlers.go#L243

It checks if heapster is running in kubernetes to register it, so maybe that's the issue. Are you running heapster inside the cluster? Do you have networking and dns correctly configured?

**Comment by radishgz** [comment]
Hi Floreks,  heapster is a service in kubernetes and grafana is working fine.
[root@harbor heapster1.3]# kubectl exec -it monitoring-grafana-3344903701-l5mfu /bin/sh --namespace kube-system
/ # wget http://172.30.79.5:8082/api/v1/model/namespaces/kube-system/pod-list
Connecting to 172.30.79.5:8082 (172.30.79.5:8082)
/ # wget http://heapster:80/api/v1/model/namespaces/kube-system/pods/
Connecting to heapster:80 (10.254.224.60:80)
index.html           100% |**********************************************************************************************************************************************************************|   233   0:00:00 ETA
/ # wget http://heapster:80/api/v1/model/namespaces/kube-system/pod-list/
Connecting to heapster:80 (10.254.224.60:80)
wget: server returned error: HTTP/1.1 404 Not Found
/ # wget http://heapster:80/api/v1/model/namespaces/kube-system/pod-list
Connecting to heapster:80 (10.254.224.60:80)
wget: server returned error: HTTP/1.1 404 Not Found
/ # exit
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1
You have new mail in /var/spool/mail/root
[root@harbor heapster1.3]#  kubectl describe service heapster --namespace kube-system
Name:                   heapster
Namespace:              kube-system
Labels:                 kubernetes.io/cluster-service=true
                        kubernetes.io/name=Heapster
Selector:               k8s-app=heapster
Type:                   NodePort
IP:                     10.254.224.60
Port:                   <unset> 80/TCP
NodePort:               <unset> 30082/TCP
Endpoints:              172.30.79.3:8082
Session Affinity:       None
---
heapster deployment yaml in here ： 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
        imagePullPolicy: IfNotPresent
        command: 
        - /heapster
        - --v=10
#        - --logtostderr
        - --sink=influxdb:http://10.254.117.4:8086
        - --source=kubernetes:http://10.211.55.44:8080?inClusterConfig=true
#        ?inClusterConfig=false
#        - --source=kubernetes:https://kubernetes.default
