### ISSUE TITLE
Get https://172.20.0.211:6443/version: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by braveliuchina** [kubernetes/dashboard#1755]
#### Issue details
I run the gulp serve task in dashboard development, and i want to connect the api server from a remote cluster https://172.20.0.211:6443 . 
i set the 'conf.js' file in the 'build' directory:  'apiServerHost: to 'https://172.20.0.211:6443',.
the gulp task run an error 'Get https://172.20.0.211:6443/version: x509: certificate signed by unknown authority'
I know it is because the https CA problem, but how can I use a https CA in dashboard development mode ?
The remote kubernetes api server runs on hyperkube .
If i start a proxy local, dahboard 'conf.js' api server host set to the proxy address, I run 'gulp serve', the error can not display, and I access the url through chrome, it is normal.

ps : how can I debug the golang part in the dashboard? and how can i use a keystone to authenticate users 
##### Environment
```
Dashboard version: 1.5.1
Kubernetes version: recently
Operating system: ubuntu 14
Node.js version: v6.9.5
Go version:v1.6.3
```

**Comment by floreks** [comment]
`apiserver-host` argument does not offer secure connection. In order to use secure connection you have to either use `kubeconfig` param or in-cluster config (install dashboard as an app in the cluster).
In your case try using kubeconfig. If kubectl works then so should dashboard.

>ps : how can I debug the golang part in the dashboard? and how can i use a keystone to authenticate users

Check k8s [authentication](https://kubernetes.io/docs/admin/authentication/) docs. For more detailed information I'd recommend checking official kubernetes repo or creating an issue there. I have tried to do that once but it's rather complicated and I don't remember all steps. People from k8s community have more experience in this area.

**Comment by braveliuchina** [comment]
@floreks  i try to use the kubeconfig param in the 'dashboard.go',set it to my local kubeconfig file , and it works. But how can i make the basic http auth dialog pop up when i access the 'http://127.0.0.1:9090' through the chrome in local development environment rather than product environment

**Comment by braveliuchina** [comment]
@floreks  here is my kubeconfig file content: 
`apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/liuxiaoyong/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
- cluster:
    server: https://172.20.0.211:6443
    insecure-skip-tls-verify: true
  name: vpnkube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
- context:
    cluster: vpnkube
    user: vpnkube
  name: vpnkube
current-context: vpnkube
kind: Config
preferences:
  colors: true
users:
- name: minikube
  user:
    client-certificate: /home/liuxiaoyong/.minikube/apiserver.crt
    client-key: /home/liuxiaoyong/.minikube/apiserver.key
- name: vpnkube
  user:
    password:
    username:
`

**Comment by floreks** [comment]
Dashboard itself does not provide auth yet. It relies fully on kubernetes so you have to run dashborad inside the kubernetes cluster and set up basic auth. Probably even when we implement it, it will be only supported for in-cluster configuration.

If you want to run dashboard outside of the cluster and expose it in a secure way then you have to configure some kind of reverse-proxy with auth mechanism. Easy solution would be to configure ngix/apache with some auth plugin.

**Comment by cheld** [comment]
@braveliuchina 
I did not fully understand what you are trying to achieve. It seems you trying to devleop (you mention gulp serve)? 

you can create a local Kubernetes cluster with `gulp local-up-cluster`. If you want to reuse an existing cluster you can run `kubectl proxy` (assuming kubectl is setup properly)

In both configuration you will not have to configure anything!

**Comment by floreks** [comment]
Closing as stale. Please reopen if error still occurs.
