### ISSUE TITLE
Node memory usage can be more accurate?

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/dashboard#1781]
Here is the `free -m` outputs from my 2 nodes:

![image](https://cloud.githubusercontent.com/assets/159209/24259958/9ae2f4d6-0faf-11e7-8b1e-920e373562d5.png)

Here's what I see in my Kubernetes dashboard “Nodes” section:

![image](https://cloud.githubusercontent.com/assets/159209/24259979/aa913bf4-0faf-11e7-8c48-23fcf3348241.png)

I'm no Linux expert (I get my information at  http://www.linuxatemyram.com/) which claims that the intersection of `+/- buffers cache` & `used`  reflects a more realistic memory usage. However it looks like dashboard does not report that and the tooltip makes it clear.

Is this a deliberate choice of the Dashboard or is it what we get out of the API?

**Comment by rf232** [comment]
This is what we are getting from the api

kubernetes/heapster#1356 and google/cadvisor#1529 are related.
