### ISSUE TITLE
Should we put release notes in kubernetes/kubernetes-1.6?

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1782]
Here: https://github.com/kubernetes/features/blob/release-notes-draft-1.6/release-1.6/release-notes-draft.md#ui

Every SIG has place there. Should we take advantage of this?

**Comment by zouyee** [comment]
may be here: https://github.com/kubernetes/features/blob/master/release-1.6/release-notes-draft.md

**Comment by maciaszczykm** [comment]
Done it in https://github.com/kubernetes/features/pull/243.

**Comment by maciaszczykm** [comment]
> Created pull request at https://github.com/kubernetes/features/pull/243, but it might be too late...

Unfortunately, it was.
