### ISSUE TITLE
Menu should be updated?

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1786]
I've discovered few things related to RBAC resource management in Dashboard, that I'd like to discuss:

- [ ] **Menu entry** - IMO we shoiuldn't make `Access Control` as a part of `Admin` group. It's not the Kubernetes resource like other menu entries. It's more like group. However, I'm not sure how to proceed. Maybe we should display `Roles`, `Role Bindings` etc. under `Admin` group?
- [x] ~~**Tabs** - It isn't new approach, I remember, that previously we decided to not use them as it allowed to show more info within display.~~

Related to #1441 and #1576.

***

We should decide if we add access control group or we follow documentation's team categorization of resources.

**Comment by maciaszczykm** [comment]
cc @danielromlein @mlamina

**Comment by mlamina** [comment]
Maybe "Access Control" could be a category on the same level as "Admin" and "Workloads" and then have two subitems "Roles" and "Role Bindings"? I think @danielromlein has more insights into the design decisions here :)

**Comment by maciaszczykm** [comment]
@mlamina I we'd like to align with https://kubernetes.io/docs/resources-reference/v1.5/ then we should make `Roles` and `Role Bindings` part of `Admin` group, just like we do with other resources. It'd be consistent. Creating `Access control` can be more intuitive for users.

**Comment by maciaszczykm** [comment]
> I'm not sure I follow your concern about the tabs @maciaszczykm...? Could you elaborate please?

@danielromlein I might not remember it correctly, but I thought, that we decided to use cards instead of tabs to display more info on single page. I can see now, that our target design has both (multiple cards on multiple tabs). It will be done, when we'll add new features like exec into pod for example I think. At the moment there are no tabs anywhere I believe.

Related to #1137, #1117 and #908.

**Comment by maciaszczykm** [comment]
@bryk What do you think about Access Control category? Should we consider adding it? Documentation has all access-related resources in Cluster category, but we might want to do it to improve usability.

**Comment by maciaszczykm** [comment]
Linking to discussion from #1787.

**Comment by floreks** [comment]
Moving the discussion from #1787 here:

> Looking at docs and our menu I am a bit confused now. We should decide whether we want to group nav menu on our own or be more consistent with the docs.<br /> 
Docs do not group items based on namespace relation but rather on their role, so i.e. under Config and Storage section there is Storage Class resource that is non-namespaced.<br /> 
If we want to keep our current grouping then we have to think how to display Roles because there is ClusterRole resource under Cluster section that is non-namespaced and there is also Role resource under Cluster section that is namespaced and showing them currently under Cluster does not make sense to me.<br /> 
I am leaning towards grouping that is introduced in docs and rethinking how and where to show namespace selector. IMHO it would be more consistent and we do not have to think about custom grouping of resources.

@danielromlein @maciaszczykm @bryk WDYT?

**Comment by danielromlein** [comment]
Taking a step back: what exactly _is_ the https://kubernetes.io/docs/resources-reference/v1.5/ referenced in #1787, and where did it come from? Is that the new docs site? A sub-section of the current docs site? Unless we know the rationale that went into their ordering scheme, it seems maybe unwise to align to that without further investigation...?
Regardless, the problem of a Namespace applying to Roles and not ClusterRoles seems significant. It probably makes sense to revisit Namespacing as a whole and how best to place it in the information architecture. 

> It will be done, when we'll add new features like exec into pod for example I think. At the moment there are no tabs anywhere I believe.

@maciaszczykm so are you saying it's technically not feasible to introduce tabs at this point?

**Comment by maciaszczykm** [comment]
> @maciaszczykm so are you saying it's technically not feasible to introduce tabs at this point?

No, it's possible and we can do it. I'm just saying, that at the moment we do not use tabs (like I mentioned before). However, there will be a moment, when we'll have to introduce them (maybe it's time :)).

**Comment by bryk** [comment]
> @bryk What do you think about Access Control category? Should we consider adding it? Documentation has all access-related resources in Cluster category, but we might want to do it to improve usability.

I think this makes sense. There'll be like ~4 resources grouped there, right?

**Comment by maciaszczykm** [comment]
@bryk Right.

**Comment by maciaszczykm** [comment]
Examples to follow:

![image](https://user-images.githubusercontent.com/2823399/32442939-7d11a126-c2fd-11e7-8619-8eaf653cd47e.png) ![image](https://user-images.githubusercontent.com/2823399/32442945-87d3497a-c2fd-11e7-860b-34c584378ee3.png)

**Comment by maciaszczykm** [comment]
Closing it as stale. "Access control" is no longer in the menu, we have the "Cluster roles" instead. I think we will continue to follow schema from https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/.
