### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by onlywhite** [kubernetes/dashboard#1789]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
pods "cwwallet-wechat2-4215789198-t4c5g" not found

```

**Comment by maciaszczykm** [comment]
@onlywhite If you'll update to 1.6.0 you will see 404 error, because pod `cwwallet-wechat2-4215789198-t4c5g` was not found. We have pending pull request with live update and might be done soon to avoid these kind of issues.
