### ISSUE TITLE
Support owner references

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1827]
We should use owner references instead of label selectors. There is a list of action items:

- [ ] Highlight problematic/orphaned pods (#878)
- [x] Display owned resources (#1727 and #1848)
- [x] Display owned events and other minor resources (events for deployments)

**Comment by floreks** [comment]
As highlighting orpahned pods should not be hard to add then we can think how to show that in dashboard. We have to remember that it's possible to just create pod without any controller so it should not be done to scare users but rather as information that some pods do not have any controllers managing them.

As a simple solution we could probably just add new column on pod list and display `Orphaned` `true/false`. Also it should not be hard to add support for sorting by this column. This way user could easily sort and check which pods are orphaned.

@therc would this solution work for you?
