### ISSUE TITLE
Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by johanhaleby** [kubernetes/dashboard#183]
When running `gulp docker-image` I end up with the following error message:

```
[09:12:24] Requiring external module babel-core/register
[09:12:27] Using gulpfile ~/test22/k8s-dashboard/gulpfile.babel.js
[09:12:27] Starting 'package-backend-source'...
[09:12:27] Starting 'assets'...
[09:12:27] Starting 'angular-templates'...
[09:12:27] Starting 'styles:prod'...
[09:12:27] Starting 'docker-file'...
[09:12:27] Finished 'docker-file' after 126 ms
[09:12:27] Finished 'assets' after 175 ms
[09:12:27] Finished 'styles:prod' after 219 ms
[09:12:27] Finished 'package-backend-source' after 271 ms
[09:12:27] Starting 'backend:prod'...
[09:12:27] Finished 'angular-templates' after 289 ms
[09:12:27] Starting 'scripts:prod'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
```

**Comment by bryk** [comment]
I guess that you dont have Java (or one of other deps) installed. Can you verify?

**Comment by johanhaleby** [comment]
I think I do. Here are my versions:

Docker: `version 1.9.1, build a34a1d5`
Go: `1.5.1 darwin/amd64`
nodejs: `v5.3.0`
npm: `3.3.12`
etcd: `2.2.1`
java: `1.8.0_60`
gulp: `CLI version 3.9.0, Local version 3.9.0`

**Comment by bryk** [comment]
@cheld @taimir Can you help?

**Comment by johanhaleby** [comment]
Perhaps off-topic but all I want to do is to try the docker image on our K8S cluster. You don't happen to provide a pre-built version?

**Comment by taimir** [comment]
Let me see if I can reproduce it.

**Comment by taimir** [comment]
On a side note: we're currently planning on releasing a runnable docker container image with every new version (as a next step).

**Comment by johanhaleby** [comment]
@taimir :+1:

**Comment by taimir** [comment]
@johanhaleby I cannot reproduce the issue on my machine, the only differences are the java version `OpenJDK: 1.7.0_91` and `node: v4.2.3`. From the looks of it the `gulp scripts:prod` task is failing in your setting. Could you confirm this? Then we could troubleshoot further.

**Comment by johanhaleby** [comment]
Thanks for trying to help. I'll try to look into it in a few days.

**Comment by taimir** [comment]
@johanhaleby You're quite welcome :)

**Comment by Alasio** [comment]
I had the same issue, Java 8 didn't allow for multiple compiling so downgraded to Java 7 and that seemed to resolve the issues.

**Comment by cheld** [comment]
Many thanks for sharing this information. We will try to reproduce it.

**Comment by bryk** [comment]
FYI, I have OpenJDK Java 8 and it works.

**Comment by cheld** [comment]
I have JDK 7 on one machine and JDK 8 on another. But, it seems the problem is related to some kind of java setup.

If java is not installed at all, we get the (more or less) obvious error:


stream.js:74
      throw er; // Unhandled stream error in pipe

Error: spawn java ENOENT
at <...stack-trace...>

Maybe the full stack trace was not pasted or the log level of node is set differently somehow?
Maybe the gulp docker-image was run with sudo, but the path variable was not passed root?

**Comment by cheld** [comment]
We should enhance our gulp scripts to check java

**Comment by floreks** [comment]
Closing as stale. Please reopen if problem still occurs.
