### ISSUE TITLE
Switch from Heapster to metrics API

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1831]

**Comment by patrickf55places** [comment]
@maciaszczykm is this in the works?

**Comment by floreks** [comment]
Currently all new features are on hold due to angular migration (https://github.com/kubernetes/dashboard/pull/2727). Anyway I think that metrics API is still in alpha/beta and needs some more work to be incorporated into Dashboard.

**Comment by beatlejuse** [comment]
/reopen
i need Switch from Heapster to metrics API too

**Comment by discostur** [comment]
We need also a Dashboard which uses the metrics API instead of Heapster

**Comment by maciaszczykm** [comment]
Tracked from #2986.

/close
