### ISSUE TITLE
Introduce plugin mechanism?

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1832]
Starting a discussion here. Plugin mechanism should allow all people using their third party resources to customize Dashboard to their needs.

Things to consider:
 - Architecture
 - How would it enhance Dashboard functionalities (dynamically added components?)
 - How would it connect to external APIs
 - Limitations and possibilities (how much can we enhance Dashboard UI with plugins?)

**Comment by cheld** [comment]
The use case is to replace the generic UI of third-party-resources with a customized, user friendly version. This is just one use case for a plug mechanism. There are others like helm or weave.

Some technical issues to consider:
- Bread crumbs
- Namespace selector
- Error handling
- Automatic refresh (not merged yet)
- cross origin stuff

**Comment by aledbf** [comment]
@maciaszczykm do you have some estimation when this feature could be available? Or better yet how I can add a feature to the dashboard?
This is what I want to add https://github.com/kubernetes/ingress/issues/109 as feature

**Comment by bryk** [comment]
@aledbf I guess this feature is still to be defined and scoped. Can you help here by stating what would be needed from Dashboard to support kubernetes/ingress#109 case?

**Comment by floreks** [comment]
I'm not sure if ingress features would be a good example of a plugin. We could just extend our detail page and provide better control over ingress resources. AFAIR our plugin mechanism was supposed to mainly support custom views for third party resources.

**Comment by maciaszczykm** [comment]
The first working version is already done thanks to @ajatprabha.
