### ISSUE TITLE
Zerostate page layout is broken 

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#184]
```
body {
  height: 100% 
}
```
Causes this problems. @zreigz Can you fix this? 

![selection_003](https://cloud.githubusercontent.com/assets/1159999/11895281/bb060ff2-a57d-11e5-8ab1-5cd280c343cc.png)

**Comment by floreks** [comment]
We are on it :)

**Comment by zreigz** [comment]
Fixed. PR created: 
https://github.com/kubernetes/dashboard/pull/185
