### ISSUE TITLE
daemonset view in 1.6 always shows 0/N pods ready

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/dashboard#1848]
##### Environment

```
Dashboard version: 1.6.0
Kubernetes version: 1.6.0
Operating system: whatever is in the image
Node.js version: whatever is in the image
Go version: whatever is in the image
```

##### Steps to reproduce

Create a daemonset

##### Observed result

![image](https://cloud.githubusercontent.com/assets/3876739/25026206/734d2a16-2073-11e7-8a29-ff7fb5047e94.png)

##### Expected result

It should show `12/12`. 

```
NAME               DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR   AGE
systemd-exporter   12        12        12        12           12          <none>          4m
```

##### Comments

I don't see any network errors in the browser and nothing weird in the dashboards logs. 

json object returned from server:
```
   {
    "objectMeta": {
     "name": "systemd-exporter",
     "namespace": "kube-system",
     "labels": {
      "app": "systemd-exporter"
     },
     "annotations": {
     },
     "creationTimestamp": "2017-04-13T21:58:21Z"
    },
    "typeMeta": {
     "kind": "daemonset"
    },
    "pods": {
     "current": 12,
     "desired": 12,
     "running": 0,
     "pending": 0,
     "failed": 0,
     "succeeded": 0,
     "warnings": []
    },
    "containerImages": [
     "prom/node-exporter:v0.14.0"
    ]
   }
  ],
```

I thought this was because my DS's use the new rolling update, but it does this regardless of that.

**Comment by zouyee** [comment]
could you describe your kube cluster version? Because in my cluster using the 1.6 dashboard,there is no such problem.

**Comment by jhorwit2** [comment]
The cluster is running version 1.6.0

**Comment by nmohoric** [comment]
Same issue here, Kubernetes 1.6.1, Dashboard 1.6.0, kubectl shows all available.

**Comment by maciaszczykm** [comment]
Still have to verify it, but probably connected to the fact we have not switched to owner references yet. Check #1827.

**Comment by maciaszczykm** [comment]
It's covered by #1827. #1857 fixes it.

**Comment by jhorwit2** [comment]
Why was this closed when that PR hasn't landed?

**Comment by maciaszczykm** [comment]
I'll reopen if you want to track it from there. Closed it, because it's covered by #1827 which was created earlier, so in general this is a duplicate.

**Comment by jhorwit2** [comment]
IMO this is a bug based on the current implementation and that ticket is an enhancement that just happens to replace the current implementation & fix the bug. Using label selectors should still technically work, which is why the other views (e.g. deployments) still work fine for me. 

Do you plan to release that new feature in a point release? If so tracking it there is fine. The dashboard is basically not usable for daemonsets. I have to paginate through 10+ pages of pods to find a given pod.

**Comment by maciaszczykm** [comment]
@jhorwit2 Perhaps, but there is no sense in fixing it to work with label selectors if they are not going to be supported anymore. We are doing our best to fix current problems and when it will be merged you will be notified.

Regarding release I cannot provide you any date yet, because we have no plans yet. However, minor release will be done shortly, because we are working on multiple bug fixes and sorting is going to be introduced soon.

> The dashboard is basically not usable for daemonsets. I have to paginate through 10+ pages of pods to find a given pod.

Do you experience other daemon-set-related issues besides label selectors/owner references?

**Comment by maciaszczykm** [comment]
You may also use HEAD release after fix will be merged if you do not want to wait for official release.

**Comment by jhorwit2** [comment]
![image](https://cloud.githubusercontent.com/assets/3876739/25134767/6f0ef052-241e-11e7-8a41-d8b6206dfbf7.png)

I'm not sure the implementation logic behind the scenes to populate everything, but this what happens in every DS view.

**Comment by jhorwit2** [comment]
@maciaszczykm I agree it doesnt make sense to fix this while working on the other PR. Id just like it fixed / released :)

If push comes to shove, I'll just cherry-pick and build a custom image. I'll close this out and subscribe to the other issue. 

Thanks.

**Comment by maciaszczykm** [comment]
@jhorwit2 Looks like a serious bug, we have to check it. A lot of issues may be connected to new Kubernetes releases and lack of Dashboard compatibility.

**Comment by zouyee** [comment]
[recreate deployment can not bring the replicaset and pods(kubernetes/kubernetes 44198)](https://github.com/kubernetes/kubernetes/issues/44198)
[recreate deployment w/ same name does not work(kubernetes/kubernetes 41760)](https://github.com/kubernetes/kubernetes/issues/41760)
<img width="876" alt="2017-04-18 5 56 41" src="https://cloud.githubusercontent.com/assets/5785605/25125172/767ba140-2460-11e7-9699-dd6f355e7b18.png">
this issue cased by recreate deployment or other things,when you choose etcd:v3.0.7 to storage data.

**Comment by Slahser** [comment]
@zouyee i met the same situation,and i used the embbed etcd-amd64:3.0.17
