### ISSUE TITLE
Can I contribute to this branch?

### ISSUE THREAD

**Issue by sonic008** [kubernetes/dashboard#1851]
#### Issue details
I noticed that dashboard does not deploy properly to kubeadm that I'm using.
It shows ContainerCreating... Lookbackoff.
But I think I found a solution with RBAC, so I want to contribute.
Could anybody show me how I can contribute code?

##### Environment

```
Dashboard version: latest 
Kubernetes version: 1.6.1
Operating system: CentOS 7.2
Node.js version:
Go version:
```

**Comment by floreks** [comment]
Our contribution process is similar to kubernetes one.

![image](https://cloud.githubusercontent.com/assets/2285385/25070174/9365dcc8-2297-11e7-8e21-1b19f933b5f2.png)

1. Fork dashboard.
1. Clone your fork.
1. Create new feature branch and work there.
1. Once you finish, fetch upstream repo and rebase your changes with our master. 
1. Push your branch and create a Pull Request.

**Comment by sonic008** [comment]
Thanks man!

**Comment by cheld** [comment]
PRs are very welcome. Some thoughts:
- If you like you can suggest the changes in an issue to discuss, before creating the PR
- In case it is rather a documentation issue, then you can update the readme or the troubleshooting guide

BTW: I tried kubeadm-1,6-alpha and had no problems. Can you describe for me the exact steps to reproduce?

**Comment by Kaijun** [comment]
@cheld And how about bugs? Is it still necessary to open an issue before creating a new PR?

**Comment by cheld** [comment]
No, of course not. 'Issue before PR' was just an offer to get started. Another good way to get started is to create a quick-and-dirty PR and mark it as WIP (work in progress) to get some early feedback.

Only in case of larger UI changes we create upfront PRs with UI mocks

**Comment by maciaszczykm** [comment]
There is also a guide you might be interested in: https://github.com/kubernetes/dashboard/blob/master/docs/devel/getting-started.md

Closing it. If you will have any questions just let us know!
