### ISSUE TITLE
Can't load dashboard with kubernetes >=1.6 and LAN required proxy

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/dashboard#1858]
##### Environment
Ubuntu 16.04 with current `apt install kubeadm kubernetes-cli`

```
Dashboard version: how to find out the version? (dashboard doesn't open)
Kubernetes version: Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Operating system: Ubuntu 16.04
Node.js version: not installed
Go version: not installed
```

##### Steps to reproduce
Have a VM with HTTP_PROXY/HTTP_PROXY set to a proxy server and NO_PROXY set to `localhost,127.0.0.1,<current_ip>`

follow the dashboard tutorial:

 - install with create -f <link>
 - `kubectl proxy`
 - open `localhost:8001/ui` in browser

##### Observed result

Despite `no_proxy` and `NO_PROXY` being set to both `localhost` and `<apiserver_ip>` a response  `503` from the proxy is shown (verified by looking at the HTML content of the response), after redirecting internally to `/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/`.

Calling the `curl` request from the proxy logs results in a different error that seems to be related to RBAC.

Logs:

```
I0418 15:17:45.992083   42324 loader.go:354] Config loaded from file /etc/kubernetes/admin.conf
I0418 15:17:45.997241   42324 cached_discovery.go:118] returning cached discovery info from /home/kube/.kube/cache/discovery/<eth0_ip>_6443/servergroups.json
Starting to serve on 127.0.0.1:8001I0418 15:17:55.209878   42324 proxy_server.go:91] /ui/ matched ^.*
I0418 15:17:55.210148   42324 proxy_server.go:91] 127.0.0.1 matched ^127\.0\.0\.1$
I0418 15:17:55.210218   42324 proxy_server.go:130] Filter accepting GET /ui/ 127.0.0.1
I0418 15:17:55.211285   42324 round_trippers.go:398] curl -k -v -XGET  -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate" -H "X-Forwarded-For: 127.0.0.1" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" https://<eth0_ip>:6443/ui/
I0418 15:17:55.246977   42324 round_trippers.go:417] GET https://<eth0_ip>:6443/ui/ 307 Temporary Redirect in 35 milliseconds
I0418 15:17:55.246997   42324 round_trippers.go:423] Response Headers:
I0418 15:17:55.247001   42324 round_trippers.go:426]     Location: /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
I0418 15:17:55.247004   42324 round_trippers.go:426]     Content-Type: text/html; charset=utf-8
I0418 15:17:55.247008   42324 round_trippers.go:426]     Content-Length: 102
I0418 15:17:55.247012   42324 round_trippers.go:426]     Date: Tue, 18 Apr 2017 13:17:55 GMT
I0418 15:17:55.277869   42324 proxy_server.go:91] /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ matched ^.*
I0418 15:17:55.278097   42324 proxy_server.go:91] 127.0.0.1 matched ^127\.0\.0\.1$
I0418 15:17:55.278161   42324 proxy_server.go:130] Filter accepting GET /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ 127.0.0.1
I0418 15:17:55.278289   42324 round_trippers.go:398] curl -k -v -XGET  -H "User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate" -H "X-Forwarded-For: 127.0.0.1" -H "Upgrade-Insecure-Requests: 1" https://<eth0_ip>:6443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/
I0418 15:19:32.974175   42324 round_trippers.go:417] GET https://<eth0_ip>:6443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ 503 Service Unavailable in 97695 milliseconds
# note: the following response is verfied to be from my environment proxy not from the kube proxy
I0418 15:19:32.974199   42324 round_trippers.go:423] Response Headers:
I0418 15:19:32.974206   42324 round_trippers.go:426]     Cache-Control: no-cache
I0418 15:19:32.974211   42324 round_trippers.go:426]     Content-Type: text/html; charset=utf-8
I0418 15:19:32.974216   42324 round_trippers.go:426]     Pragma: no-cache
I0418 15:19:32.974219   42324 round_trippers.go:426]     Date: Tue, 18 Apr 2017 13:19:32 GMT
```

##### Expected result
opens the dashboard

**Comment by maciaszczykm** [comment]
To provide versions use `kubectl version` command.

**Comment by erikbgithub** [comment]
Version string entered to original post.

$ sudo kubectl logs -n kube-system kubernetes-dashboard-2396447444-qld6k
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Successful initial request to the apiserver, version: v1.6.0
Creating in-cluster Heapster client
Using service account token for csrf signing

**Comment by maciaszczykm** [comment]
> Calling the curl request from the proxy logs results in a different error that seems to be related to RBAC.

Can you provide error?

**Comment by maciaszczykm** [comment]
It seems, that Dashboard started and it is running. Where & how exactly are you using `kubectl proxy`?

**Comment by erikbgithub** [comment]
Yes, the dashboard is running. I'm following the [dashboard README](https://github.com/kubernetes/dashboard#usage).

Currently I can't provide the curl error, but I'm sure about it being RBAC related. The curl request doesn't contain any details that would authenticate it. So RBAC considers it "ubuntu:unauthorized" or "ubuntu:anonymous" or something like that.

**Comment by maciaszczykm** [comment]
> Where & how exactly are you using `kubectl proxy`?

**Comment by erikbgithub** [comment]
I literally don't do anything else than the guide says. I start a proxy. I open the browser at `localhost:8001`. Should I quote the README?


    ## Usage
    The easiest way to access Dashboard is to use kubectl. Run the following command in your desktop environment:
    ```shell
    $ kubectl proxy
    ```
    kubectl will handle authentication with apiserver and make Dashboard available at [http://localhost:8001/ui](http://localhost:8001/ui)

    The UI can _only_ be accessed from the machine where the command is executed. See `kubectl proxy ---help` for more options.

**Comment by floreks** [comment]
If you are following our current guide then with current kubernetes 1.6 for sure there will be RBAC issue preventing dashboard from accessing cluster resources. 

There is an ongoing PR #1856 with new yaml files that should be used for Kubernetes 1.6+ when RBACs are enabled. Main page will be also updated to reflect these changes. Try using one of the new files from this pull request to deploy dashboard.

**Comment by maciaszczykm** [comment]
@erikbgithub `kubectl proxy` will work **only locally** unless you specify its params. You have to change bind adress.

**Comment by lenartj** [comment]
@erikbgithub, I think RBAC might not be the only problem you are dealing with. The guide instructs "Run the following command in your **desktop environment**", that is not on the node, but from the host where your browser is running. To be able to do that you need a properly setup kubeconfig.

Alternatively (for testing..), you may edit the kubernetes-dashboard Service and set the `externalIPs: [1.2.3.4]` to the externally (well, from your desktop at least) accessible IP of the Node. Then you can just visit http://1.2.3.4 from your browser running on your desktop. (Again, this is not a secure setup.)

If you have a problem with your LAN proxy it's possible that your browser needs to be configured to ignore the proxy server for 127.0.0.1 (and whatever address you have for the Node if you are going with the externalIPs option)

**Comment by erikbgithub** [comment]
There is only one node and it is equal to the host. So I'm certain everything is on the right machine. That's also why I'm certain that my LAN's proxy should never be involved. No package should leave the machine.

**Comment by erikbgithub** [comment]
I also tried the `externalIPs` suggestion. I really like it, thanks! But it yields the same result. For some reason the request is delivered outside of my computer.

To me it looks like the `kubectl proxy` call honoring the `HTTP_PROXY` environment variable, but not honoring the `NO_PROXY` variable (both small/big with same values in env).

**Comment by lenartj** [comment]
Can you unset the environment variables and restart `kubectl proxy` ? Then from a browser that is not using proxy go to http://127.0.0.1:8001/ui

You can also try to get rid of RBAC as a test:
https://kubernetes.io/docs/admin/authorization/rbac/#permissive-rbac-permissions

I am pretty sure this problem has nothing to do with the dashboard.

**Comment by erikbgithub** [comment]
> Can you unset the environment variables and restart kubectl proxy ? Then from a browser that is not using proxy go to http://127.0.0.1:8001/ui

Same result, getting the page from the LAN's proxy.


> You can also try to get rid of RBAC as a test: https://kubernetes.io/docs/admin/authorization/rbac/#permissive-rbac-permissions

This makes curl work if I add another line before commiting the code snippet from the bottom of your link.

```
  --user=anonymous \
```

Now `curl` gets the same LAN proxy response, with the interesting side effect that curl doesn't know about that proxy call at all. Usually `curl -vvv` will tell you about using a proxy to reach its target.
Also we now know that the "kube proxy" doesn't use the proxy, because it doesn't know about it without the environment variable. Maybe it calls the api server and the api server ignores `the `no_proxy` setting?

**Comment by erikbgithub** [comment]
I just found out that with all proxy ENV settings opening localhost:<dashboard_nodeport> works just fine.

My final guess with all the info is this, correct me if you see it differently: dashboard does as it should, at least with nearly deactivated RBAC.

Now the question remains, whether the README should be adapted (I'm happy to provide a PR, if you have a suggestion. Or I just write a one liner that generates the correct link), and if an issue should be created for "kube proxy" (at kubernetes/kubernetes?).

**Comment by maciaszczykm** [comment]
> README should be adapted (I'm happy to provide a PR, if you have a suggestion. Or I just write a one liner that generates the correct link)

What adaptation do you mean here?

**Comment by cheld** [comment]
> Have a VM with HTTP_PROXY/HTTP_PROXY set to a proxy server and NO_PROXY set to localhost,127.0.0.1,<current_ip>

Not sure if this is your problem. First you must configure Docker to use proxy explicitely (because systemd does not pass environment variables to docker ). Afterwards, you might be able to pull containers, but still you will not be able to reach from inside of the container to the internet. E.g. you will have troubles to build containers using commands like apt-get or curl.

You can hack around each problem one by one, but it will never work smoothly. Because of this, I would recommend to use transparent proxy in your lan network

**Comment by erikbgithub** [comment]
Well, [this](https://github.com/kubernetes/dashboard#usage) doesn't work, because of the described "kube proxy" problem. Instead one needs to figure out the port of the dashboard pod and use that in the browser.

**Comment by maciaszczykm** [comment]
@erikbgithub Well, it does not cover all the cases. If you have anything, that would be improvement in your opinion and will help new Kubernetes users, just open pull request :-)

**Comment by maciaszczykm** [comment]
@erikbgithub We don't want to describe insecure setup with nodeport in our main `README.md`, but we may leave short note here if you have any good idea. I suggest creating issue at core repo to describe them your problem. 

RBAC issue is also solved as our deployment files cover it.

**Comment by cheld** [comment]
@erikbgithub If you think that kube proxy has an issue with LAN proxy then maybe you create an issue for it

**Comment by erikbgithub** [comment]
@cheld Thanks, that problem still exists. I forgot that!

**Comment by maciaszczykm** [comment]
Why do we keep it open? When I am looking at it now, it seems to be a bit too precise to describe every possible use case. This time `kubectl proxy` didn't work because of environment variables. Should we cover it in our `README.md` before we will close this issue?

**Comment by lenartj** [comment]
I think this should be closed. Nothing to do with dashboard.

**Comment by erikbgithub** [comment]
I'll close it due to request of devs.

However, I think there should be another issue which figures out what alternative besides kube-proxy could be provided. Because for the user they don't care. They just feel dashboard is hard to use. I personally also don't have much stake in it, therefore do as you like. But believe me that people will move away from kubernetes-dashboard to alternatives. Our >300 developer team is currently also looking at alternatives.

**Comment by floreks** [comment]
We could provide more options how to configure and use dashboard, but it would be very generic description. Many use cases  depend on the cluster configuration and additionally some users might want to use custom dns, networking, proxy. This gives us dozens of possible configurations that we can't cover. In README we try to cover most generic and usually used options. 

If you have some unusual configuration then of course we can try to help you, we could also dedicate some place in documentation to describe such cases if they are resolved. Everyone is welcome to contribute.

IMHO most related issues involve users that do not understand how kubernetes works and that's fine, because configuration of cluster should be cluster operator responsibility.

Also I am afraid that if we would provide more advanced options that involve i.e. auth-proxy in front of dashboard or using keystone to authenticate then there would be even more issues created because proxy that we would choose as an example would not work in some environments or there would be some networking issues and we would end up with more issues related to external tools and incorrect configurations rather than actual dashboard issues.
