### ISSUE TITLE
It didn't create any pod after I run "kubectl create -f kubernetes-dashboard.yaml"

### ISSUE THREAD

**Issue by RayWoodson** [kubernetes/dashboard#1861]
##### Environment

```
Dashboard version:1.6.0
Kubernetes version:1.5.2
Operating system:centos 7.2.1511
Node.js version:
Go version:
```

##### Comments

It didn't create any pod after I run "kubectl create -f kubernetes-dashboard.yaml"

[root@master opt]# kubectl  create -f kubernetes-dashboard.yaml 
deployment "kubernetes-dashboard" created
service "kubernetes-dashboard" created

[root@master opt]# kubectl get svc --namespace=kube-system
NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes-dashboard   10.254.246.150   <nodes>       80:31040/TCP   3m
[root@master opt]# kubectl get pod --namespace=kube-system
No resources found.
[root@master opt]# kubectl get rc --namespace=kube-system
No resources found.
[root@master opt]# kubectl get deployment --namespace=kube-system
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kubernetes-dashboard   1         0         0            0           3m

**Comment by maciaszczykm** [comment]
Can you give us result of kubectl `kubectl get all --all-namespaces`? Most probably it is cluster issue... Do other pods schedule? Do you have any nodes available?

**Comment by zouyee** [comment]
could you exec the following command to get the detail?
`kuberctl get deployment kubernetes-dashboard --namespace=kube-system -o yaml`

**Comment by cheld** [comment]
Maybe containers crashed. Can you check with docker ps -a?

**Comment by RayWoodson** [comment]
I have two  available nodes
and I had run kubectl get deployment --namespace=kube-system
it is appeared "kubernetes-dashboard " but available is 0
and svc is also there only pods none.
docker ps -a cannot find any containeer wich use image kubernetes-dashboard 
I had rebuild my cluster and I will try it later

**Comment by maciaszczykm** [comment]
@RayWoodson Hi, any update here?

**Comment by RayWoodson** [comment]
@maciaszczykm 
no 
i didnt update anything
the first thing I  had do is deploy the dashboard after the cluster is running

**Comment by floreks** [comment]
It is a cluster issue, probably related to scheduler error or some taints that do not allow creation of pods on a node. You have to investigate your cluster logs. Try to create any other app (in kube-system ns) and check if it will work. I believe it will also not schedule any pods. 

If it is indeed dashboard issue an other apps are scheduled ok then feel free to reopen it and provide us logs from `kube-scheduler` and dashboard deployment. There might be events related to scheduler error.
