### ISSUE TITLE
Use Container Builder for building prod images?

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#1862]
What do you think of using Container Builder for building and pushing prod images? And still staying with travis for dev builds? 

Docs: https://cloud.google.com/container-builder/docs/

This would reduce bus factor for the release and automate the most error prone step of building and pushing.

@maciaszczykm @floreks @rf232  WDYT?

**Comment by floreks** [comment]
I like this idea. We could also move our head releases to gcr and keep them all at one place.

**Comment by maciaszczykm** [comment]
I agree with you. Keeping all the images in the same place and getting rid of flakes sounds nice!

**Comment by maciaszczykm** [comment]
I think we can close right now, true @floreks?

/close
