### ISSUE TITLE
feature request: allow user to copy spec in resource edit dialog

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/dashboard#1870]
while we are using ng-jsoneditor to display spec, it is not convenient(or trivial) to copy the spec out, I believe it is useful to support that, considering the following use cases:

1.  I lost the original spec, and now I want to deploy the same spec to another cluster.
2.  I want to start with a new spec, and I do not want to do it from scratch, so I need a template as a basis.
3.  share the spec with others, for example, someone helps to debug an issue, and want to see its status(or something like that)..

I have done some work to add this feature, and want to get some feedback w.r.t this.

**Comment by floreks** [comment]
I like this idea. Can you make it work without modifying `ng-jsoneditor` module itself?

**Comment by floreks** [comment]
We have also been thinking about changing `ng-jsoneditor` or writing custom editor from scratch because this one has some bugs and is not that user friendly.

There is actually similar issue open already #1221. Isn't it a duplicate?

**Comment by zhouhaibing089** [comment]
@floreks The way that I made it working is via adding another button(so `cancel, copy, update` three buttons in total) in the dialog, and leverages `angular-clipboard` tool to handle it.

**Comment by zhouhaibing089** [comment]
> There is actually similar issue open already #1221. Isn't it a duplicate?

#1221 is about editing functionality itself(copy part of the fields, easy editing, etc).. while my intention, to be honest, is just get the spec in clipboard via a single click.

Well, either way, this one is much simpler(smaller change) than #1221.

**Comment by floreks** [comment]
> @floreks The way that I made it working is via adding another button(so cancel, copy, update three buttons in total) in the dialog, and leverages angular-clipboard tool to handle it.

Sounds nice. I think you can create PR with such a change if you want.

**Comment by zhouhaibing089** [comment]
@floreks please take a look at #1878

**Comment by floreks** [comment]
I will take a look but probably after the weekend. I don't have much time over the weekend.
