### ISSUE TITLE
Update Dashboard preview image

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1871]
![screenshot at kwi 21 11-26-21](https://cloud.githubusercontent.com/assets/2823399/25271811/bd7c93e8-2685-11e7-86f3-3e30413ca811.png)

vs.

![image](https://cloud.githubusercontent.com/assets/2823399/25271893/f6a6c40e-2685-11e7-8efc-d0da030eda05.png)

I think we should do it to show new features on it.

@bryk Your screenshot has better quality, can you maybe do it once again or tell us which tool did you use?

**Comment by floreks** [comment]
IMO both images have good quality. We can use this one to replace current image.

**Comment by maciaszczykm** [comment]
Okay, I figured it out. It's done by `shift + cmd + 4`. I will send pull request.
