### ISSUE TITLE
Prepare new release

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1873]
Once owner references will be handled, we can make new release. @floreks added sorting and we have fixed few other issues. Is there anything missing for 1.6.1 at the moment?

**Comment by edouardKaiser** [comment]
Any news on a release?

**Comment by maciaszczykm** [comment]
We would like to polish filtering and search a bit before publishing it. Should be done this/next week.

**Comment by maciaszczykm** [comment]
Global search, filtering and basic authorization is in. We need to test everything once more and then we can do a release. This probably will happen next week.
