### ISSUE TITLE
web vision error

### ISSUE THREAD

**Issue by caikun** [kubernetes/dashboard#1887]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:default:default" cannot list deployments.extensions in the namespace "default". (get deployments.extensions)
```

**Comment by maciaszczykm** [comment]
Check https://github.com/kubernetes/dashboard#deployment. You need to use following command to install Dashboard if you have Kubernetes version >= 1.6 (as your error is connected to missing/misconfigured service account):

```
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```
