### ISSUE TITLE
Create deployment from file should respect the namespace param

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/dashboard#1891]
Click the `CREATE` button at the top right, then select `Upload a YAML or JSON file`, and upload a deployment spec with no `namespace` information.

While I expect the deployment will be created in the same namespace which shows in the query parameter(`?namespace=xxx`), but it is created to `default` anyway, check: https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/deployment/deploy.go#L309.

**Comment by floreks** [comment]
We have similar issue #1374 open for a long time now. I actually know how to fix that but didn't have time to look at it. :smiley:

**Comment by maciaszczykm** [comment]
@zhouhaibing089 Are you willing to contribute also in this area?

Let's keep track of it from original issue #1374.
