### ISSUE TITLE
Dashboard won't restart after cluster reboot

### ISSUE THREAD

**Issue by martin31821** [kubernetes/dashboard#1898]
After a complete reboot of my cluster the Dashboard won't startup again.

##### Environment

- 3 Nodes
- CoreOS Stable
- Followed the CoreOS+Kubernetes setup guide

```
Dashboard version: 1.6.0
Kubernetes version: 1.6.1
Operating system: CoreOS 1298.7.0
```

##### Steps to reproduce
Setup a cluster as described above, create the dashboard from kubernetes-dashboard.yaml, reboot the cluster.

##### Observed result
The dashboard enters state CrashLoopBackOff, giving the following error message:
```
Using HTTP port: 9090
Creating API server client for https://10.3.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: the server has asked for the client to provide credentials (get .meta.k8s.io)
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
```

When I delete the dashboard services and recreate them, everything is working again.

##### Expected result
The dashboard should startup normally. 

##### Comments
This may be related to: https://github.com/kubernetes/kubernetes/issues/7958

**Comment by floreks** [comment]
IMO it's not dashboard issue but rather cluster configuration or a kubernetes bug. I have tested K8S 1.6.1 deployed using kubeadm on my RPI cluster and dashboard survives reboots just fine.

If that is a secret issue then you can just delete dashboard pod and during recreation it will have new secret mounted. Unfortunately in this case there is nothing we can do as kubernetes is responsible for mounting secrets.

**Comment by martin31821** [comment]
just fyi, this is indeed a problem in my cluster setup.
I have an APIServer running on all nodes but the don't share each others certificates which results in incorrect signed ServiceAccounts and Tokens. 
I will close this.
