### ISSUE TITLE
Kubernetes-Dashboard pod not running

### ISSUE THREAD

**Issue by karunakar1122v** [kubernetes/dashboard#1901]
I am facing below issue while creating kubernetes-Dashboard pod on kube-system.

E0317 18:30:49.265701 1 config.go:287] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
 Using HTTP port: 9090
 E0317 18:30:49.265701 1 config.go:287] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
 log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-3203962772-zt7j1.unknownuser.log.ERROR.20170317-183049.1: no such file or directory

```
Dashboard version: 1.5.1
Kubernetes version: 1.3.0
Operating system: Ubuntu 16.10
Node.js version:
Docker  version: 1.9
```

##### Steps to reproduce
Kubernetes cluster running. Node also running on master VM.

##### Observed result
Kubernetes -Dashboard pod Crashbackloop

##### Expected result
Kubernetes -Dashboard pod running

**Comment by floreks** [comment]
Your cluster is not configured properly. Dashboard needs Service Accounts to be enabled in the cluster.

**Comment by karunakar1122v** [comment]
When I execuete 
kubectl cluster-info  command I am able to see kubernets master is running,..
In Admssion-control also added ServiceAccount. When I get kubecrl get serviceAccounts receving one account. But still dashboard not running.

**Comment by karunakar1122v** [comment]
When I execuete
kubectl cluster-info command I am able to see kubernets master is running,..
In Admssion-control also added ServiceAccount. When I get kubectl get serviceAccounts receiving one account. But still dashboard not running.

Thanks & Regards
Karunakar

**Comment by floreks** [comment]
Check out my comment about [cluster configuration](https://github.com/kubernetes/dashboard/issues/1287#issuecomment-250681546).
