### ISSUE TITLE
Show initContainers amongst other containers

### ISSUE THREAD

**Issue by schlomo** [kubernetes/dashboard#1909]
version 1.6

I would like to see the initContainers same like the regular containers, with environment variables, logs etc.

**Comment by cheld** [comment]
What is a initContainer? Maybe I missed somethi g....Could you please elaborate a bit?

**Comment by schlomo** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

Containers that are run to completion **before** the regular containers. Very useful to configure stuff or restore data before your app starts. `kubectl logs` can show the logs, `kubectl describe` shows it, but the dashboard doesn't show the details, it only shows the annotations for it.

**Comment by floreks** [comment]
Sounds good to me. I actually did not know about such feature. Thanks for pointing this out. This is kind of related to #1833 so we can add this to our milestone.
