### ISSUE TITLE
Dashboard no graphs - Followed install instructions

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/dashboard#1910]
Looking for the exact install instructions to get Heapster, InfluxDB, Grafana working and Dashboard to include graphs. I am using kubeadm to install a basic 3 node cluster. Typically I use the ansible scripts to do the full install of kubernetes on Centos 7.3. However, decided to try kubeadm. To get Heapster/InfluxDB/Grafana in stalled I followed the guidance of : kubectl create -f deploy/kube-config/influxdb/

Services were successfully created. However, Grafana throws an error on the UI that no server found and Dashboard still missing the graphs, etc.

I have looked online and found very little if any step-by-step instructions of getting this working when using kubeadm as the base installer for the cluster.

Kubeadm installs latest from repo which is v1.6.2 of kubernetes. Using Calico for the networking. Dashboard functional (minus graphs) along with all services are running with no issues

Heapster: v1.3.0
InfluxDB: v1.1.1
Grafana: v4.0.2

Please advise

Thanks
DB
- Posted on the heapster repo but they recommended I post this here. Looks like a few of these issues around this topic are being opened across this repo and heapster

**Comment by floreks** [comment]
Pretty much only requirement is that heapster is running and is accessible through the service proxy at `/api/v1/proxy/namespaces/kube-system/services/heapster`. Both heapster app and service have to be deployed in `kube-system` namespace and service should be named `heapster`. If heapster is running and has access to influxdb then it should work. You might want to delete dashboard pod after that if it's not picked up.

**Comment by cheld** [comment]
The dashboard logs might also give a hint?

**Comment by floreks** [comment]
@DarkBlaez any progress here?

**Comment by DarkBlaez** [comment]
No progress. I have installed on clean VMs many times. When installed via kubernetes ansible scripts things work. When using kubeadm and trying to install manually result is no graphs. It's reproducible. I think anyone following the guides do have the same issue. I think it's on the roadmap for kubeadm to support add-on install for the combined monitoring solution

**Comment by floreks** [comment]
It depends. I've encountered some issue with networking and dns when using kubeadm on ubuntu 16.10 but on 17.04 everything works fine. Also kubeadm seems to work with HypriotOS on my RPi. I can see graphs without any trouble.

They still some issues with `kube-proxy` and dns on some OSes. I think that we will be diverging from heapster anyway and trying to switch to docker-engine api exposed by kubernetes.

**Comment by kalgecin** [comment]
i have rpi cluster setup with hypriotos as well, i am unable to see the graphs, i have heapster and dashboard running. i do however see error in the logs

```
Getting pod metrics
Skipping Heapster metrics because of error: an error on the server ("Error: 'dial tcp 10.38.0.2:8082: getsockopt: no route to host'\nTrying to reach: 'http://10.38.0.2:8082/api/v1/model/namespaces/kube-system/pod-list/etcd-node01,heapster-1052634017-mp3kg,kube-apiserver-node01,kube-controller-manager-node01,kube-dns-279829092-8lqrc,kube-proxy-dpc84,kube-proxy-pqbbz,kube-proxy-zwzj4,kube-scheduler-node01,kubernetes-dashboard-3512663533-f2197,weave-net-bjptv,weave-net-dh25j,weave-net-tn0lt/metrics/cpu/usage_rate'") has prevented the request from succeeding (get services heapster)
[2017-05-14T16:18:28Z] Outcoming response to 10.38.0.0:48572 with 200 status code
```

**Comment by floreks** [comment]
`No route to host` means that overlay network does not work correctly. I have always used flannel. Run some busybox pod attach to it and check if dns and networking works as it should.

**Comment by DarkBlaez** [comment]
While I am all for hypriotos on the rpi, the issue I am seeing is on Centos 7.3 with kubeadm. Kubeadm does not by default install dashboard, etc. When one installs the dashboard via kubeadm it does not default to installing heapster, influxdb, grafana, these are additional items. This issue still exist. I have seen it on Ubuntu 16.04 as well. This is not the only post on this issue as there are a number of others. I can say kubernetes ansible in the contrib does work and installs the dashboad with heapster, etc. and works fine. Only with kubeadm do I see issues (among other users sharing the same issue). I will try and post logs

**Comment by floreks** [comment]
I'm aware that it might be hard to configure everything properly as there are no good guides for that. On the other hand we can not make dashboard install any integrations like heapster by default as this is standalone app that uses other apps to extend user experience if they are available. 

Some kubernetes provisioners choose to install dashboard/heapster etc. by default but we have to remember that heapster is not the only monitoring tool.

I'm currently trying to introduce settings/integrations page and common framework for handling integrations that will allow users to dynamically install/uninstall and enable/disable integrations supported by dashboard. In the beginning we will support heapster as main monitoring tool. Later we'll try to add support for prometheus and others. Beside that we will be able to support other integrations like helm, weave scope, etc.

**Comment by floreks** [comment]
Closing as stale.

**Comment by matjam** [comment]
This was one of many threads I came across searching for instructions on how to configure Kubernetes with the dashboard, if your instance didn't get built with it. In my case, I used Kops, so I needed to do the following:

```
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.6.3.yaml
```

I hope this is useful for other people googling who are lost.

**Comment by arno01** [comment]
And for the RBAC-enabled K8s deployments don't forget to apply the heapster-rbac:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml
```

**Comment by edbergavera** [comment]
Deleting `kubernetes-dashboard` pod picks up the graph :)

**Comment by floreks** [comment]
Actually since 1.7 it is not needed anymore. There was periodic check added.
