### ISSUE TITLE
add quick 'change color scheme' dropdown

### ISSUE THREAD

**Issue by kgignatyev** [kubernetes/dashboard#1921]
When using dash against 2 or 3 clusters, for example minikube and 'qa' it would be nice to tell at a glance which cluster it is connected to. Better yet if it was possible to upload custom 'skin' with logo etc.

**Comment by maciaszczykm** [comment]
Closing as duplicate of #1657. We will take it under consideration, but it is low-priority at the moment for us. If you would like to contribute then go ahead, we will review any pull request.
