### ISSUE TITLE
Dashboard reported Unknown Server Error (503) on logs page

### ISSUE THREAD

**Issue by rcarlson8974** [kubernetes/dashboard#1925]
##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.0
Kubernetes version: 1.5.6
Operating system: Google, Container-Optimized OS
Node.js version: ?
Go version: ?
```
##### Steps to reproduce

It happens a lot when clicking on 'Pods' -> 'Logs' to view the logs of a pod

##### Observed result
Dashboard reported Unknown Server Error (503):
```
Error: 'EOF'
Trying to reach: 'http://10.0.1.4:9090/api/v1/pod/webapps/projector-deployment-3030463844-wt9z8/log'
```

##### Expected result

The log viewer/console appears

##### Comments

It appears to happen most (maybe all the time) when the cluster is under heavy load

**Comment by maciaszczykm** [comment]
Can you fill in details to help us solve the issue?

**Comment by maciaszczykm** [comment]
You should also consider using >1.6 version, because we are fixing issues constantly.

**Comment by rcarlson8974** [comment]
Also, we have seen this with every k8s version to date and tried upgrading to 1.6.x a couple weeks ago but too many issues between gcloud, kubectl, helm, etc... and decided to let the dust settle for a bit before giving it another try.

**Comment by maciaszczykm** [comment]
Can you paste `kubectl logs` here?

**Comment by floreks** [comment]
Did you try increasing resource quota for dashboard (cpu, memory)? Some logs might be very long and due to lack of memory to load them backend/frontend might crash. Default settings are quite low for applications such as dashboard.

**Comment by floreks** [comment]
This is related to #1828 so we will track it from there. Please inform us if this is not an memory issue, we will add new point there to track.
