### ISSUE TITLE
Dashboard crashing 

### ISSUE THREAD

**Issue by srinivas1008** [kubernetes/dashboard#1936]
##### Steps to reproduce

1) able to launch kubernetes dashboard
2) when I try to create deployment from WebUI , Its crashing

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Unknown Server Error:
```
No error data available```


##### Comments
<!-- If you have any comments or more details, put them here. -->

**Comment by maciaszczykm** [comment]
Can you paste logs from Dashboard?

**Comment by floreks** [comment]
We need more details to reproduce it.

**Comment by maciaszczykm** [comment]
Please reopen after providing more details.
