### ISSUE TITLE
Dashboard reports wrong pods on Deployment/ReplicaSet when using matchExpressions

### ISSUE THREAD

**Issue by p-bakker** [kubernetes/dashboard#1944]
#### Issue details
Created a Deployment with the following selector spec:

> ...
> spec:
>    replicas: 3
>    selector:
>      matchLabels:
>          run: myapp
>      matchExpressions:
>       - {key: exclude, operator: NotIn, values: [true]}
> ...

The 3 replica pods start up nicely.
Then added a label 'exclude=true' to one of the pods.
A new pod automatically got created since the pod with the label doesn't match the selector used for the Deployment/ReplicaSet.

The Dashboard/WebUI now shows 4/3 under Pods running for both the Deployment and ReplicaSets (and lists 4 pods under the ReplicaSet POD details)

Checking the # of pods for the Deployment/ReplicaSet using kubectl shows the proper number, so it's 'just' a display issue in the Dashboard

##### Environment
Running MiniKube v0.18.0 on Windows 10

##### Steps to reproduce
See Issue details

##### Observed result
The Dashboard/WebUI shows the wrong number of Pods on both the Deployment and ReplicaSets (and lists the wrong number of Pods under the ReplicaSet POD details

##### Expected result
The dashboard showing the proper number of Pods

##### Comments
I had first filed this issue directly under Kubernetes: https://github.com/kubernetes/kubernetes/issues/45725, but it was determined it was Dashboard related

**Comment by p-bakker** [comment]
Rolling out a new update fixes the glitch on the ReplicaSet, but not on the Deployment

**Comment by floreks** [comment]
Could you check if this issue is fixed on our development release? @maciaszczykm did we switch to OwnerRef on deployments and rs also?

**Comment by maciaszczykm** [comment]
@floreks I fixed it for workload resources in #1857, but is still missing for few minor resources. Anyways, #1857 is not part of 1.6.0 Dashboard release.

@p-bakker You will need to wait until new release will be out. It should happen next week.

Changelog for new release:
https://github.com/kubernetes/dashboard/compare/v1.6.0...master

**Comment by maciaszczykm** [comment]
@p-bakker You should wait for https://github.com/kubernetes/dashboard/releases/tag/v1.6.1 image links to show, should happen today or tommorrow. This issue seems to be fixed there.
