### ISSUE TITLE
json error when deploying dashboard

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#1946]
#### Issue details
I could not install dashboard after kubeadm. 

##### Environment

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

uname -a
Linux vbox 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

##### Steps to reproduce
1. Install kubernetes with kubeadm
2. kubectl create -f https://github.com/cheld/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml

##### Observed result
error: error converting YAML to JSON: yaml: line 286: mapping values are not allowed in this context

##### Comments
Any quick ideas?

**Comment by floreks** [comment]
Please follow our README and use this to deploy dashboard

`kubectl create -f https://git.io/kube-dashboard`

Your are trying to use some version from your own fork.

**Comment by cheld** [comment]
It seems I used my own fork and it is broken
