### ISSUE TITLE
Scaling feature does not work on master branch. 

### ISSUE THREAD

**Issue by kenan435** [kubernetes/dashboard#1947]
#### Issue details
Seems the "common" dialog.js file for scaling dialog is missing a line of code. Therefor non of the scaling works. 

##### Steps to reproduce
Open dialog for scaling in any of the resources (Jobs, Deployment, ReplicaSets, Replication Controller. )

##### Observed result
Scaling dialog is missing some ui elements. Dialog OK, Cancel buttons do not respond to user input.

##### Expected result
UI element need to show and OK Cancel need to respond to user clicks.

**Comment by maciaszczykm** [comment]
Tested and it works after your change :-)
