### ISSUE TITLE
HeapSter not read the metrics

### ISSUE THREAD

**Issue by karunakar1122v** [kubernetes/dashboard#1956]
##### Environment

```
Dashboard version: 1.5.1
Kubernetes version: 1.3
Operating system: Ubuntu 16.10
```

##### Steps to reproduce
Kubectl describe hpa
showing error feailed get metrics.CPu consumption

When I enter curl http://heapsterIp:port/api/v1/model/debug/metrics
I am ablet get all list with pods namespaces and nodes
![Uploading issue.PNG…]()
![Uploading issue.PNG…]()

##### Observed result
showing error feailed get metrics.CPu consumption

##### Expected result
Read the metrics

##### Comments
PFA attached images.

**Comment by maciaszczykm** [comment]
We are not able to see the images.

**Comment by karunakar1122v** [comment]
Pf the below logs of HeapSter

I0516 10:51:04.489826       1 manager.go:79] Scraping metrics start: 2017-05-16 10:50:00 +0000 UTC, end: 2017-05-16 10:51:00 +0000 UTC
I0516 10:51:04.554364       1 manager.go:152] ScrapeMetrics: time: 64.460685ms size: 85
I0516 10:51:23.211425       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:51:52.955202       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:52:04.488679       1 manager.go:79] Scraping metrics start: 2017-05-16 10:51:00 +0000 UTC, end: 2017-05-16 10:52:00 +0000 UTC
I0516 10:52:04.540076       1 manager.go:152] ScrapeMetrics: time: 51.317089ms size: 84
I0516 10:52:22.699476       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:52:52.443880       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:53:04.488125       1 manager.go:79] Scraping metrics start: 2017-05-16 10:52:00 +0000 UTC, end: 2017-05-16 10:53:00 +0000 UTC
I0516 10:53:04.541195       1 manager.go:152] ScrapeMetrics: time: 52.988773ms size: 84
I0516 10:53:22.188846       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:53:51.932514       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:54:04.487996       1 manager.go:79] Scraping metrics start: 2017-05-16 10:53:00 +0000 UTC, end: 2017-05-16 10:54:00 +0000 UTC
I0516 10:54:04.538689       1 manager.go:152] ScrapeMetrics: time: 50.537974ms size: 85
I0516 10:54:21.675333       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:54:51.418428       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:55:04.485896       1 manager.go:79] Scraping metrics start: 2017-05-16 10:54:00 +0000 UTC, end: 2017-05-16 10:55:00 +0000 UTC
I0516 10:55:04.536734       1 manager.go:152] ScrapeMetrics: time: 50.762734ms size: 84
I0516 10:55:21.161961       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:55:50.906350       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:56:04.485718       1 manager.go:79] Scraping metrics start: 2017-05-16 10:55:00 +0000 UTC, end: 2017-05-16 10:56:00 +0000 UTC
I0516 10:56:04.536854       1 manager.go:152] ScrapeMetrics: time: 51.057986ms size: 85
I0516 10:56:20.646578       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd
I0516 10:56:50.397245       1 handlers.go:178] No metrics for pod default/tomcat-4194739372-5y8pd

**Comment by karunakar1122v** [comment]
PF below logs of HPA of tomcat. HeapSter unable to read the metrics of Pods.Please let me know what was the issue?
root@KubernetesMaster:/var/lib/docker# kubectl describe hpa
Name:                           tomcat
Namespace:                      default
Labels:                         <none>
Annotations:                    <none>
CreationTimestamp:              Tue, 16 May 2017 10:40:13 +0000
Reference:                      Deployment/tomcat
Target CPU utilization:         50%
Current CPU utilization:        0%
Min replicas:                   1
Max replicas:                   10
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  1h            55m             18      {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 0/1 of pods
  1h            55m             18      {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods


root@KubernetesMaster:/var/lib/docker#

**Comment by floreks** [comment]
Closing as this is a cluster issue not dashboard. Try to open issue on kubernetes repo. This is not related to dashboard.
