### ISSUE TITLE
gcr.io doesn't know dashbaord v1.6.1

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/dashboard#1961]
The apply script listed in the README tries to `docker pull` an image tag (1.6.1) which doesn't exist yet. `wget file`, then changing it to 1.6.0 works.

**Comment by maciaszczykm** [comment]
@erikbgithub We are currently releasing it. I will let you know when it will be ready ir you can check it there:

https://github.com/kubernetes/dashboard/releases/tag/v1.6.1

**Comment by erikbgithub** [comment]
Is it on purpose that the dashboard service doesn't have a nodeport anymore? Maybe I'm understanding it incorrectly but without Nodeport you can't reach it directly.

**Comment by erikbgithub** [comment]
I checked it's `type: NodePort` that's missing for some reason, in Service->spec.

**Comment by maciaszczykm** [comment]
Yes, it was removed.

Linking: #1513, #1744 and #1952.

**Comment by therc** [comment]
Do new releases require Google employees to be involved?

**Comment by floreks** [comment]
Yes, unfortunately we can not push new images to gcr. They should be available at latest tomorrow.

**Comment by erikbgithub** [comment]
@floreks @maciaszczykm If one follows the solution proposed in the README, shouldn't the provided script not contain `v1.6.0` until the image is there? I mean, I'm a developer, you can expect me to download the script and change that config value myself. But I also don't really need the dashboard for the same reason. Most dashboard users probably aren't experienced enough to easily work around such an issue. What do you think?

**Comment by floreks** [comment]
Unfortunately this is the release process and we can't work around that. First we have to update master branch. All yaml files and version numbers need to be updated. After that we can create tag from master and wait for gcr images to be pushed. We could minimize images 'downtime' by introducing some automation tools, but for now we do not have such option. Sorry for the inconvenience.

**Comment by erikbgithub** [comment]
@floreks I think all of that is possible and still provide a user experience. I.e. just point people to tagged 1.6.0 in the README instead of to master.

Instead of: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

Direct to: https://raw.githubusercontent.com/kubernetes/dashboard/v1.6.0/src/deploy/kubernetes-dashboard.yaml

You can decide with a simple [`curl`](https://github.com/blog/985-git-io-github-url-shortener) request what `https://git.io/kube-dashboard` provides, right?

**Comment by floreks** [comment]
@erikbgithub As far as I see there is no option to override already existing location for shortened link. It just creates a new one. I guess it's done this way for security reason.

**Comment by vagharsh** [comment]
when can we expect it to be ready ?

**Comment by erikbgithub** [comment]
@floreks Look, you can't tell me that this is unsolvable. The options are unlimited.

For instance:
 - use the raw.githubcontent links in the README
 - use another url shortener
 - find a way to update the git.io link
 - make a new link for each version and update the README accordingly (once the image is there)
 - make a new git.io link ala "kubernetes-dashboard-stable" that uses another branch beside master (e.g. "stable"); then merge from master into stable when the image is online
 - update the yaml file to use ":latest" (which of course may result in other errors)
 - find another suggested solution to deploy it, e.g. a helm chart, and maintain that independently

I'm sure you'll find a way.

**Comment by maciaszczykm** [comment]
@vagharsh Today.

**Comment by floreks** [comment]
> Look, you can't tell me that this is unsolvable. The options are unlimited.

Actually I have never stated that this is not solvable. I know we could do it better. I have described our current release process. I agree that it is not good and results in image downtime but most of the proposed options would not solve the problem. Currently we need master to be updated with latest version of images before we create a tag even so they are not pushed yet. 

Next time we will try to improve our release process and maybe introduce some automation tools that will build and push images for us. 

Also please keep in mind that we do not have full privileges to this repository and we can not push images to gcr. We are only contributors here and we're trying to do our best to maintain everything and introduce new features.

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/releases/tag/v1.6.1 is already out.

**Comment by bryk** [comment]
Thanks @floreks and @maciaszczykm for doing the work! It is super valuable :) 

Re me pushing images: It is possible to build auto-push-to-gcr infrastructure, but this costs a lot developer effort. So for now we stick with me pushing images which is very cheap :) If someone can pick this automation task, I'd be more than happy.
