### ISSUE TITLE
Pod events appear in list twice

### ISSUE THREAD

**Issue by tinselspoon** [kubernetes/dashboard#1970]
##### Environment

```
Dashboard version: 1.6.1
Kubernetes version: 1.6.2
Operating system: CoreOS 1353.7.0
```

##### Steps to reproduce

1. Create a pod that will start successfully
2. Navigate the Pods list in the UI, and click on the created Pod to go to its details page
3. Observe the list of events

##### Observed result

The list of events appears to be duplicated, see the screenshot below. The list is repeated twice with the same content.
![image](https://cloud.githubusercontent.com/assets/9112859/26204042/71babb8c-3bd5-11e7-905e-9e9c60a1d7f4.png)

##### Expected result

Each event is only listed once. `kubectl get ev` shows the list without duplicates.
```
$ kubectl get ev --namespace cluster-services | grep spec.containers{mongo}
6m         6m          1         mongo-3427211192-36cdn                Pod          spec.containers{mongo}                Normal    Pulling             {kubelet 192.168.9.54}     pulling image "mongo:3"
1m         1m          1         mongo-3427211192-36cdn                Pod          spec.containers{mongo}                Normal    Pulled              {kubelet 192.168.9.54}     Successfully pulled image "mongo:3"
1m         1m          1         mongo-3427211192-36cdn                Pod          spec.containers{mongo}                Normal    Created             {kubelet 192.168.9.54}     Created container with id a11da1c6b6f39676a2412017e85de84910a1efad2b9475244b91c71c30e9a62a
1m         1m          1         mongo-3427211192-36cdn                Pod          spec.containers{mongo}                Normal    Started             {kubelet 192.168.9.54}     Started container with id a11da1c6b6f39676a2412017e85de84910a1efad2b9475244b91c71c30e9a62a
```
##### Comments

This only seems to affect pods. It doesn't appear to affect ReplicaSet, DaemonSet or Node events.

**Comment by floreks** [comment]
Good catch! Thanks for creating an issue for that.

**Comment by tinselspoon** [comment]
No problem, thanks for the prompt fix :)
