### ISSUE TITLE
Kubernetes metrics not geneerated.But i am able to autoscaling Based on cpu utilization automatically increase the load and create the replica pods.But not able to generate metrics.

### ISSUE THREAD

**Issue by karunakar1122v** [kubernetes/dashboard#1975]
Kubernetes-Dashboard logs:
Getting pod metrics
[2017-05-17T09:53:50Z] Outcoming response to 172.17.0.1:58156 with 201 status code
Getting application global configuration
Application configuration {"serverTime":1495014832149}
[2017-05-17T09:53:53Z] Incoming HTTP/1.1 GET /api/v1/pod/kube-system?itemsPerPage=10&page=1 request from 172.17.0.1:58156
Getting list of all pods in the cluster
Getting pod metrics
[2017-05-17T09:53:53Z] Outcoming response to 172.17.0.1:58156 with 201 status code
Getting application global configuration
Application configuration {"serverTime":1495014836402}
[2017-05-17T09:53:58Z] Incoming HTTP/1.1 GET /api/v1/pod/kube-system/heapster-4287223874-84sqz/container request from 172.17.0.1:58156
[2017-05-17T09:53:58Z] Outcoming response to 172.17.0.1:58156 with 201 status code
[2017-05-17T09:53:59Z] Incoming HTTP/1.1 GET /api/v1/pod/kube-system/heapster-4287223874-84sqz/log request from 172.17.0.1:58156
[2017-05-17T09:53:59Z] Outcoming response to 172.17.0.1:58156 with 201 status code
Getting application global configuration
Application configuration {"serverTime":1495174738485}
[2017-05-19T06:18:59Z] Incoming HTTP/1.1 GET /api/v1/pod/kube-system?itemsPerPage=10&page=1 request from 172.17.0.1:45982
Getting list of all pods in the cluster
Getting pod metrics
[2017-05-19T06:18:59Z] Outcoming response to 172.17.0.1:45982 with 201 status code
[2017-05-19T06:19:04Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 172.17.0.1:45982
Getting namespace list
[2017-05-19T06:19:04Z] Outcoming response to 172.17.0.1:45982 with 201 status code
[2017-05-19T06:19:06Z] Incoming HTTP/1.1 GET /api/v1/pod/default?itemsPerPage=10&page=1 request from 172.17.0.1:45982
Getting list of all pods in the cluster
Getting pod metrics
[2017-05-19T06:19:06Z] Outcoming response to 172.17.0.1:45982 with 201 status code
Getting application global configuration
Application configuration {"serverTime":1495174749229}
[2017-05-19T06:19:10Z] Incoming HTTP/1.1 GET /api/v1/pod/default?itemsPerPage=10&page=1 request from 172.17.0.1:45982
Getting list of all pods in the cluster
Getting pod metrics
[2017-05-19T06:19:10Z] Outcoming response to 172.17.0.1:45982 with 201 status code
Getting application global configuration
Application configuration {"serverTime":1495174754736}
[2017-05-19T06:19:16Z] Incoming HTTP/1.1 GET /api/v1/pod/default/tomcat-4194739372-5y8pd/container request from 172.17.0.1:45982
[2017-05-19T06:19:16Z] Incoming HTTP/1.1 GET /api/v1/pod/default/tomcat-4194739372-5y8pd/log request from 172.17.0.1:58156
[2017-05-19T06:19:16Z] Outcoming response to 172.17.0.1:45982 with 201 status code
[2017-05-19T06:19:16Z] Outcoming response to 172.17.0.1:58156 with 201 status code

HeapSter Logs:
I0519 06:43:03.817415       1 manager.go:79] Scraping metrics start: 2017-05-19 06:42:00 +0000 UTC, end: 2017-05-19 06:43:00 +0000 UTC
I0519 06:43:03.879737       1 manager.go:152] ScrapeMetrics: time: 62.210037ms size: 103
I0519 06:43:25.737711       1 handlers.go:178] No metrics for pod default/tomcat-2666999182-xzzhv
I0519 06:43:25.737787       1 handlers.go:178] No metrics for pod default/tomcat-2666999182-21p8b
I0519 06:43:55.250253       1 handlers.go:178] No metrics for pod default/tomcat-2666999182-xzzhv
I0519 06:43:55.250287       1 handlers.go:178] No metrics for pod default/tomcat-2666999182-21p8b
I0519 06:44:03.915625       1 manager.go:79] Scraping metrics start: 2017-05-19 06:43:00 +0000 UTC, end: 2017-05-19 06:44:00 +0000 UTC
I0519 06:44:03.977825       1 manager.go:152] ScrapeMetrics: time: 62.123884ms size: 103
I0519 06:45:03.818150       1 manager.go:79] Scraping metrics start: 2017-05-19 06:44:00 +0000 UTC, end: 2017-05-19 06:45:00 +0000 UTC
I0519 06:45:03.880674       1 manager.go:152] ScrapeMetrics: time: 62.449942ms size: 103
I0519 06:46:03.816301       1 manager.go:79] Scraping metrics start: 2017-05-19 06:45:00 +0000 UTC, end: 2017-05-19 06:46:00 +0000 UTC
I0519 06:46:03.882322       1 manager.go:152] ScrapeMetrics: time: 65.94842ms size: 103
I0519 06:47:03.815581       1 manager.go:79] Scraping metrics start: 2017-05-19 06:46:00 +0000 UTC, end: 2017-05-19 06:47:00 +0000 UTC
I0519 06:47:03.867574       1 manager.go:152] ScrapeMetrics: time: 51.912291ms size: 85
I0519 06:48:03.813904       1 manager.go:79] Scraping metrics start: 2017-05-19 06:47:00 +0000 UTC, end: 2017-05-19 06:48:00 +0000 UTC
I0519 06:48:03.859275       1 manager.go:152] ScrapeMetrics: time: 45.301319ms size: 85
I0519 06:49:03.812592       1 manager.go:79] Scraping metrics start: 2017-05-19 06:48:00 +0000 UTC, end: 2017-05-19 06:49:00 +0000 UTC
I0519 06:49:03.865371       1 manager.go:152] ScrapeMetrics: time: 52.70762ms size: 85
I0519 06:50:03.812197       1 manager.go:79] Scraping metrics start: 2017-05-19 06:49:00 +0000 UTC, end: 2017-05-19 06:50:00 +0000 UTC
I0519 06:50:03.855638       1 manager.go:152] ScrapeMetrics: time: 43.379368ms size: 85
I0519 06:51:03.811524       1 manager.go:79] Scraping metrics start: 2017-05-19 06:50:00 +0000 UTC, end: 2017-05-19 06:51:00 +0000 UTC
I0519 06:51:03.864453       1 manager.go:152] ScrapeMetrics: time: 52.84268ms size: 85
I0519 06:52:03.809174       1 manager.go:79] Scraping metrics start: 2017-05-19 06:51:00 +0000 UTC, end: 2017-05-19 06:52:00 +0000 UTC
I0519 06:52:03.856038       1 manager.go:152] ScrapeMetrics: time: 46.795045ms size: 85
I0519 06:53:03.807958       1 manager.go:79] Scraping metrics start: 2017-05-19 06:52:00 +0000 UTC, end: 2017-05-19 06:53:00 +0000 UTC
I0519 06:53:03.860804       1 manager.go:152] ScrapeMetrics: time: 52.7522ms size: 85
I0519 06:54:03.808310       1 manager.go:79] Scraping metrics start: 2017-05-19 06:53:00 +0000 UTC, end: 2017-05-19 06:54:00 +0000 UTC
I0519 06:54:03.852481       1 manager.go:152] ScrapeMetrics: time: 44.089859ms size: 85
I0519 06:55:03.806782       1 manager.go:79] Scraping metrics start: 2017-05-19 06:54:00 +0000 UTC, end: 2017-05-19 06:55:00 +0000 UTC
I0519 06:55:03.859026       1 manager.go:152] ScrapeMetrics: time: 52.166897ms size: 85
I0519 06:56:03.804262       1 manager.go:79] Scraping metrics start: 2017-05-19 06:55:00 +0000 UTC, end: 2017-05-19 06:56:00 +0000 UTC
I0519 06:56:03.852827       1 manager.go:152] ScrapeMetrics: time: 48.48322ms size: 85
I0519 06:57:03.802789       1 manager.go:79] Scraping metrics start: 2017-05-19 06:56:00 +0000 UTC, end: 2017-05-19 06:57:00 +0

InfluxDb logs:
[httpd] 172.17.0.2 - root [19/May/2017:06:57:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 5d572bc1-3c60-11e7-9054-000000000000 12977
[retention] 2017/05/19 06:57:24 retention policy shard deletion check commencing
[httpd] 172.17.0.2 - root [19/May/2017:06:58:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 81197c23-3c60-11e7-9055-000000000000 14143
[httpd] 172.17.0.2 - root [19/May/2017:06:59:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" a4dea2b6-3c60-11e7-9056-000000000000 13829
[httpd] 172.17.0.2 - root [19/May/2017:07:00:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" c8a186ae-3c60-11e7-9057-000000000000 14400
[httpd] 172.17.0.2 - root [19/May/2017:07:01:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" ec6561a9-3c60-11e7-9058-000000000000 12612
[httpd] 172.17.0.2 - root [19/May/2017:07:02:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 1027841b-3c61-11e7-9059-000000000000 14163
[httpd] 172.17.0.2 - root [19/May/2017:07:03:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 33e9b7fa-3c61-11e7-905a-000000000000 13727
[httpd] 172.17.0.2 - root [19/May/2017:07:04:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 57ad9dc6-3c61-11e7-905b-000000000000 13254
[httpd] 172.17.0.2 - root [19/May/2017:07:05:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 7b708519-3c61-11e7-905c-000000000000 13056
[httpd] 172.17.0.2 - root [19/May/2017:07:06:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 9f33ad7a-3c61-11e7-905d-000000000000 14731
[httpd] 172.17.0.2 - root [19/May/2017:07:07:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" c2f6684c-3c61-11e7-905e-000000000000 14701
[httpd] 172.17.0.2 - root [19/May/2017:07:08:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" e6b9a750-3c61-11e7-905f-000000000000 13970
[httpd] 172.17.0.2 - root [19/May/2017:07:09:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 204 0 "-" "heapster/1.1.0" 0a7bb899-3c62-11e7-9060-000000000000 15514
[httpd] 172.17.0.2 - root [19/May/2017:07:10:03 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.

Kubectl decribe hpa logs:

Name:                           tomcat
Namespace:                      default
Labels:                         <none>
Annotations:                    <none>
CreationTimestamp:              Tue, 16 May 2017 10:40:13 +0000
Reference:                      Deployment/tomcat
Target CPU utilization:         50%
Current CPU utilization:        2%
Min replicas:                   1
Max replicas:                   10
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  46m           39m             14      {horizontal-pod-autoscaler }                    Warning         FailedGetScale          deployments/scale.extensions "tomcat" not found
  2d            38m             31      {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 0/1 of pods
  2d            38m             31      {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods
  29m           29m             1       {horizontal-pod-autoscaler }                    Normal          SuccessfulRescale       New size: 10; reason: CPU utilization above target
  28m           28m             1       {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 1/8 of pods
  28m           28m             1       {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 1/8 of pods
  28m           27m             2       {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 1/10 of pods
  28m           27m             2       {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 1/10 of pods
  27m           27m             2       {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 8/10 of pods
  27m           27m             2       {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 8/10 of pods
  1d            24m             3       {horizontal-pod-autoscaler }                    Normal          SuccessfulRescale       New size: 1; reason: All metrics below target

Please let me know why i am not generating metrics for pods and also i am stroing in InfluxDb..Please respond ASAP.

**Comment by maciaszczykm** [comment]
How this issue is connected to the Dashboard?
