### ISSUE TITLE
Dashboard search 1.6.1 not working when not all resources are allowed

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/dashboard#1976]
##### Environment
Kubernetes v1.6.3
Dashboard v1.6.1

##### Steps to reproduce
Enable all but (for example) GET secrets to dashboard user

##### Observed result
User "dashboard" cannot list secrets in the namespace "default".: "No policy matched." (get secrets)

##### Expected result
Search in everything and possibly get a warning about not allowed search in component X?

##### Comments
As we show Dashboard to developers we want them to lock out of secure information (and our dashboard runs with RO permissions), secrets are locked out. Doing this prevents search from properly working.

Ashley

**Comment by bryk** [comment]
@CallMeFoxie Can you tell me more about the configuration you have? How do you lock access to secrets? I'd need preferably YAML files.

**Comment by CallMeFoxie** [comment]
We use ABAC for now (would take some time to convert it to RBAC that we do not have right now). The dashboard user has got these permissions:

```
{"user":"dashboard","readonly":true, "resource": "nodes"}
{"user":"dashboard","readonly":true, "resource": "componentstatuses"}
{"user":"dashboard","readonly":true, "resource": "endpoints"}
{"user":"dashboard","readonly":true, "resource": "events"}
{"user":"dashboard","readonly":true, "resource": "namespaces"}
{"user":"dashboard","readonly":true, "resource": "pods"}
{"user":"dashboard","readonly":true, "resource": "replicationcontrollers"}
{"user":"dashboard","readonly":true, "resource": "services"}
{"user":"dashboard","readonly":true, "resource": "daemonsets"}
{"user":"dashboard","readonly":true, "resource": "deployments"}
{"user":"dashboard","readonly":true, "resource": "ingresses"}
{"user":"dashboard","readonly":true, "resource": "jobs"}
{"user":"dashboard","readonly":true, "resource": "replicasets"}
{"user":"dashboard","readonly":true, "resource": "statefulsets"}
{"user":"dashboard","readonly":true, "resource": "configmaps"}
{"user":"dashboard","readonly":true, "resource": "horizontalpodautoscalers"}
{"user":"dashboard","readonly":true, "resource": "resourcequotas"}
{"user":"dashboard","readonly":true, "resource": "persistentvolumeclaims"}
{"user":"dashboard","readonly":true, "resource": "limitranges"}
{"user":"dashboard","readonly":true, "resource": "persistentvolumes"}
{"user":"dashboard","readonly":true, "resource": "storageclasses"}
{"user":"dashboard","readonly":true, "resource": "roles"}
{"user":"dashboard","readonly":true, "resource": "clusterroles"}
```

the only YAML we use is kubeconfig.yaml which has got kubernetes.default.svc endpoint and authorization token.

**Comment by CallMeFoxie** [comment]
It is indeed done on purpose that the dashboard user cannot list secrets. Which blocks search with forementioned error.

**Comment by floreks** [comment]
That totally makes sense. We now return error in case any error occurs during search. We should be handling that and instead display resources that are available and fail only if all fail.

**Comment by bryk** [comment]
@floreks We should custom handle auth errors in all pages. We should not attribute this as system error, but user error (e.g., "you cannot access this page"). And auth errors should be ignored in some places (e.g., search).

**Comment by CallMeFoxie** [comment]
thanks! :) will be happy to test this

**Comment by maciaszczykm** [comment]
Search has to be updated as this is initial implementation, multiple features are missing, but this is even more important. As @bryk and @floreks pointed out auth error should be ignored there and this resource should be skipped in search results.

Thanks once more for letting us know about it! We will get back to you once it is fixed.

**Comment by cheld** [comment]
@maciaszczykm please make sure to leave a good comment (or test) in the code because the issue is not very obvious when coding

**Comment by maciaszczykm** [comment]
I am working on it, like @bryk said in search case we should ignore error and display maybe notification. I need to check error type and then proceed (sending error or ignoring it, because it is access control related).
