### ISSUE TITLE
Greenkeeper may not work correctly

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1978]
Greenkeeper has created branch https://github.com/kubernetes/dashboard/tree/greenkeeper/initial, where it added badge saying, that it is disabled. It should create initial pull request, but did not.

Linking issue with intruction how to solve it:
https://github.com/greenkeeperio/greenkeeper/issues/402#issuecomment-297676799

And official instruction:
https://github.com/integration/greenkeeper

**Comment by maciaszczykm** [comment]
@bryk Could you take a look?

**Comment by bryk** [comment]
Greenkeeper enabled.
