### ISSUE TITLE
Dashboard Access deined! Error and typo message:-)

### ISSUE THREAD

**Issue by Viali** [kubernetes/dashboard#1980]
I install my k8s cluster through [kubeadm](https://kubernetes.io/docs/getting-started-guides/kubeadm/), and then install dashboard via
**kubectl create -f https://git.io/kube-dashboard** (I changed the file, "_type: NodePort_" added).

Then I can access the dashboard via NodePort:
![image](https://cloud.githubusercontent.com/assets/5557331/26272585/021448b4-3cea-11e7-8e03-9963b6572d42.png)

Then I tried:
`kubectl proxy --address='0.0.0.0'  --accept-hosts='^*$'`
But I got 'Access deined!' in the browser.
![image](https://cloud.githubusercontent.com/assets/5557331/26272595/54ac8f82-3cea-11e7-91ae-d62525cc5227.png)
----------------------------------------
**Interestingly**, even the message has a typo!  it should be '**denied**', not 'deined'!...

**Comment by floreks** [comment]
This page does not come from dashboard but rather from proxy. This has to be some config issue. Try to create an issue on kubernetes repo. I have never seen anything like that.

**Comment by lenartj** [comment]
Try `kubectl proxy --address='0.0.0.0' --accept-hosts='.*'`

**Comment by maciaszczykm** [comment]
Closing it as it is not Dashboard bug. You should try @lenartj suggestion, if it doesn't work you should create bug on Kubernetes core repo.
