### ISSUE TITLE
1.6.1 broke being able to view pods without access to secrets

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/dashboard#1993]
##### Environment

```
Dashboard version: 1.6.1
Kubernetes version: 1.6.4
Operating system:
Node.js version:
Go version:
```

##### Steps to reproduce

Give access to the dashboard service account that does not include get/list secrets.

Try to view a pod

##### Observed result

`User "system:serviceaccount:kube-system:kube-dashboard" cannot list secrets in the namespace "default". (get secrets)`
##### Expected result

I can view the pod just as I did in 1.6.0

##### Comments

Giving access to list secrets also means anyone can view all the secret values if they simply open up the network tab. This is a huge issue for us and basically renders the dashboard unusable.

**Comment by floreks** [comment]
Linking to #1976 as solution for both issues is the same. We have to gracefully handle and hide resources in such cases.
