### ISSUE TITLE
md-icons not loading

### ISSUE THREAD

**Issue by timothyjosefik** [kubernetes/dashboard#1994]
##### Environment

```
Dashboard version: master branch
Kubernetes version:
Operating system: Mac OSX 10.11.6
Node.js version:v7.4.0
Go version: go 1.8
```

##### Steps to reproduce
1. run minikube start
2.remove deployment for dashboard
3.run $kubectl apply -f src/deploy/kubernetes-dashboard-head-no-rbac.yaml
4.run $kubectl proxy --port=9090
4.Open chrome and go to 
http://localhost:9090/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard-head/#!/workload?namespace=default

##### Observed result
It seems like no md-icons are loaded. Instead of seeing actual green checkmarks I see "check_circle"

<img width="1221" alt="md-icons" src="https://cloud.githubusercontent.com/assets/15002167/26510874/e07b5f04-4224-11e7-80cb-b4561210104f.png">

##### Expected result
The md-icons are loaded

##### Comments
I have also tried doing this locally by using gulp docker-image:head and deploying that image with the same results.

**Comment by timothyjosefik** [comment]
You can close this issue. It was just a proxy issue not allowing it to grab the materials on my computer.

**Comment by gtaylor** [comment]
How did you end up resolving this, @timothyjosefik ? Seeing the same thing.

**Comment by timothyjosefik** [comment]
@gtaylor I believe it was an issue with my VPN and company's proxy blocking the icons from being downloaded for me. After jumping on to an open wifi it worked.
