### ISSUE TITLE
Feature Request: Show crashed containers and/or pods for logs and events in dashboard

### ISSUE THREAD

**Issue by betterman9394** [kubernetes/dashboard#1995]
Hi, when I was investigating a production issue due to OOMing, i realize that there is no easy way for me to view/show the killed/crashed containers/pods in dashboard. It will be super helpful for user to monitor/debug the system

**Comment by floreks** [comment]
As a quick solution we could provide logs from last crashed container. This way user could check the cuase of crash in container logs. WDYT?
