### ISSUE TITLE
UI container usage seems too high

### ISSUE THREAD

**Issue by dlsniper** [kubernetes/dashboard#1996]
Hi,

I'm using a k8s 1.6.2 cluster in GKE so I'm not sure how to provide the dashboard information about version and so on.
I've noticed however that the memory usage of the UI is rather high compared with my process, see the screenshot: 
![screencapture-app-google-stackdriver-1495918368300](https://cloud.githubusercontent.com/assets/607868/26524325/6443b900-4327-11e7-9cb5-4f6185a7bffe.png)

My process is listening to a websocket processing realtime messages from a Slack team. My process uses about 16MB while the k8s dashboard uses 45MB. Given that the UI is supposed to serve requests on demand, and I wasn't using the UI at the time of the screenshot, I feel that this should be investigated as I think it's a lot of memory used for a server that should otherwise do nothing while not used and just handle incoming requests as needed.
Thank you.

**Comment by floreks** [comment]
Interesting. Did you check resource usage of newly created dashboard container or it was running for some time? Pods often claim memory and do not free it easily i.e. if you open large logs page and dashboard needs to use 50MB of memory to process it then it may not free all of it.

Could you compare how it behaves when it is newly created container and after using dashboard for a few minutes? Unfortunately I don't have GKE cluster to test it.

**Comment by cheld** [comment]
I would assume that the webserver caches the static content e.g. app.js.

**Comment by dlsniper** [comment]
Hmmm, good point. Here's a screenshot taken a couple of moments ago 
![screencapture-app-google-stackdriver-1496042417856](https://cloud.githubusercontent.com/assets/607868/26540130/c24ffc68-4447-11e7-8df7-caf78ca9e78f.png)

The cluster has been running for 2 days now. I've noticed that looking at a page like a ` Pods ` results in about 10MB usage (that you can see at the end of the screenshot as a spike. Other containers seem to be rather stable in their usage.

I'm not sure if there's anything to be worried about, it's more of a heads-up for something that looks a bit suspicious.

Thank you all for your hard work and let me know if you need any help to investigate this further.

**Comment by floreks** [comment]
I think these peaks are normal since we need to load not only pods but also all related data like events, etc.  Dashboard is stateless so peaks should happen on requests and then memory should be freed. At least most of it should be freed but some of it will be cached.

Looking at metrics from heapster I can tell that after 11 days of running my dashboard pod uses ~50MB of memory. 

Thanks for raising that topic. We will keep an eye on that. You can also do that and if there will be anything suspicious let us know. For now I think that this is rather normal behavior for dashboard.

**Comment by bryk** [comment]
@dlsniper Are you using Dashboard UI? I'm asking this to figure our whether the memory spikes are happening on idle or actual usage.

**Comment by dlsniper** [comment]
The spikes happen if I'm leaving the app at idle for say 2-3 hours at least, then just refresh a page like this one: http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/pod?namespace=gopher-slack-bot 

Does it make sense?

**Comment by bryk** [comment]
This looks fine. Memory should go up when you use the UI. Then go down eventually.

**Comment by maciaszczykm** [comment]
It seems to work as expected. We are always trying to keep performance high. Please reopen if you have any suggestions/requests etc.
