### ISSUE TITLE
Show allocated resources graphs on node details page

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1997]
Show graphs instead of:

![zrzut ekranu 2017-05-19 o 12 36 12](https://cloud.githubusercontent.com/assets/2823399/26244406/c44c57f6-3c8f-11e7-85c0-58fc52bacd4f.png)

**Comment by maciaszczykm** [comment]
I am thinking about library to display graphs and I can see two options right now:

- http://jsfiddle.net/Qh9X5/10483/ - D3 is what we already use, but it generates static graphs and a lot of coding might be needed to display them correctly (scaling, animations and tooltips are not implemented by default it seems).
- https://jsfiddle.net/zuupzpLL/ - ChartJS is more advanced and easier to use in our case.

**Comment by cheld** [comment]
The old kube-ui project had a similar visualization. Guess it was implemented with d3.

**Comment by floreks** [comment]
IMO i'd go with ChartJS only if we would rewrite current charts to use it. Using and maintaining 2 different libraries for graphs is not that nice.

**Comment by floreks** [comment]
@bryk WDYT?

**Comment by maciaszczykm** [comment]
I am already working on D3 implementation.
