### ISSUE TITLE
Run as container on Kubernetes problem

### ISSUE THREAD

**Issue by sheriffmohamed** [kubernetes/dashboard#200]
Hi,

I have built and pushed the docker image for the dashboard, but when I go to run it as a pod I get the following error:

```
Cannot start container ...: [8] System error: exec format error
```

Is there anything that I can do to fix this issue?

Thanks!

**Comment by bryk** [comment]
It's the first time I see this issue. We'll fix it, but in a few weeks, when preparing for our first release. Does this timeline work for you?

**Comment by sheriffmohamed** [comment]
Gotcha. Is this going to be your first stable release?

**Comment by bryk** [comment]
Yes

**Comment by sheriffmohamed** [comment]
Perfect. Can we expect it in the second or third week of Jan?

**Comment by bryk** [comment]
Stable release? Rather no. Single command to deploy beta on your cluster: yes.

**Comment by sheriffmohamed** [comment]
Ok sounds good thank you. I know I'm putting you on the spot here :), but is there a rough timeline as to when the first stable release will be?

**Comment by floreks** [comment]
First feature complete (beta) is planned to be delivered by the end of January. Then for the next few weeks we'll try to polish everything and release stable build (mid/end of February).

It might be a good idea to create milestone and share work progress on github.

**Comment by sheriffmohamed** [comment]
Great! Thanks guys.

**Comment by luxas** [comment]
What host architecture are running on when you are getting `exec format error`?
And on which host have you built `dashboard` on?

`exec format error` arises e.g. when one tries to run an ARM binary on a `amd64` host and vice versa
I think this has with binary compability to do

**Comment by bryk** [comment]
Btw, the production binary is build for Linux architecture and the Docker image is `scratch`. This may be the reason of crashing on ARM.

**Comment by luxas** [comment]
Yes, of course the released binaries are built for `amd64`. But we don't know if @sheriffmohamed tried to run it on ARM...

@bryk When you're doing the beta release, could we include ARMv6, ARM64 and ppc64le support OOTB? That shouldn't be hard at all and I may help with it. Cross-ref: kubernetes/kubernetes#17981
I'm running dashoard on my Pi now, but it required quite many hacks. I will create an issue soon

**Comment by bryk** [comment]
Running Dashboard on ARM should not be a problem. We're just a standard HTTP server, so I guess changing compilation arch target should we all we need. Or, am I missing something?

**Comment by sheriffmohamed** [comment]
@bryk When I got the error, I was actually running dashboard on an AWS Kubernetes v1.1.3 cluster that I created running vivid. I built the binaries locally on my Mac running Kitematic. 

I didn't do anything crazy with ARM vs amd64 all standard stuff. Let me know if you need more information.

**Comment by bryk** [comment]
Okay, I'll test deployment on a K8s cluster soon :)

**Comment by luxas** [comment]
@bryk No, since this is a statically linked binary, the only thing one have to do it to set `GOARCH=(arm|arm64|ppc64le)` and `GOARM=6`.
So that should be fine

**Comment by luxas** [comment]
@sheriffmohamed Then it's because you built it on Mac (aka `darwin`), which isn't binary compatible with `amd64` linux on AWS

**Comment by bryk** [comment]
Btw, if you want to contribute to make production build run on Mac/Win/anything, then go ahead :) This is a nice feature, but none from the core team is looking into this.

**Comment by Millyna** [comment]
Just to add to this, I have got the dashboard working on my RPi2 cluster.
I've documented it here incase anyone wants to try it...
https://raspberrypicloud.wordpress.com/2016/01/12/kubernetes-dashboard-on-raspberry-pi-2/

**Comment by bryk** [comment]
That looks really nice @Millyna! If you have any thoughts on what can be improved on our side, let us know, or just contribute to this repository :)

**Comment by luxas** [comment]
I'm working on the same thing (to run dashboard on ARM clusters), but with one big difference: building is done in a docker container for reproducability. This is something I think upstream also should have.
Right now, there are much dependencies, and not every computer has them installed. Running in a development docker container would be much easier.

When I've fixed up the Dockerfile a bit, I'll post the gist here.
I can also try to propose some cross-compilation code in the future,
One question though @bryk, is `gulp build` making a statically linked binary in `dist/` for you? 
It doesn't for me...

@Millyna `dashboard` is going to be included in `kubernetes-on-arm` when `dashboard` reaches beta :)

**Comment by bryk** [comment]
> One question though @bryk, is gulp build making a statically linked binary in dist/ for you? 
It doesn't for me...

It does. `gulp clean` `gulp build` and I see `dist/dashboard.

Re upstreaming multi target compilation: We're definitely for it. It's just nobody needed this before.

**Comment by luxas** [comment]
Oh, sorry for the mis-typing. I meant that it doesn't produce a statically linked binary

**Comment by bryk** [comment]
AFAIK it is statically linked. I haven't checked that in a while, though. Will double check this in a few days when doing alpha releases.

Go compiler code:
```js
            goCommand(
                [
                  'build',
                  '-a',
                  '-installsuffix',
                  'cgo',
                  '-o',
                  outputBinaryPath,
                  conf.backend.packageName,
                ],
                doneFn, {
                  // Disable cgo package. Required to run on scratch docker image.
                  CGO_ENABLED: '0',
                  // Scratch docker image is linux.
                  GOOS: 'linux',
                });
          },
```

**Comment by bryk** [comment]
Btw, are you folks working on the same team? Or is it two unrelated k8s-on-arm projects? :)

**Comment by luxas** [comment]
Yes I saw that and it's very strange.
```
$ ldd dist/dashboard
linux-vdso.so.1 (0xbefd9000)
libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6eff000)
libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6dc1000)
/lib/ld-linux-armhf.so.3 (0x7f5a3000)
```

**Comment by luxas** [comment]
@bryk Well, I don't really know :) 

I'm doing this on my spare time just for fun :)
But it would be great to collaborate with some other people, of course

@Millyna Are you using `kubernetes-on-arm` for this?
(We've had some contact, but not too much for a while)

**Comment by luxas** [comment]
@bryk I think I've found why. 
```
goCommand(
    [
      'build',
      '-a',
      '-installsuffix',
      'cgo',
      '-o',
      outputBinaryPath,
      conf.backend.packageName,
    ],
    doneFn, {
       // Disable cgo package. Required to run on scratch docker image.
       CGO_ENABLED: '0',
       // Scratch docker image is linux.
       GOOS: 'linux',
     });
```
is in pseudo-code something like this:
```
goCommand([ goArgs ], doneFn, { envVars })
```
but in `gocommand.js` it's
```
export default function spawnGoProcess(args, doneFn) {
  checkPrerequisites().then(() => spawnProcess(args)).then(doneFn).fail((error) => doneFn(error));
}
```

I guess you thought of implementing it, but forgot it in `gocommand.js`, such things happens
Anyway `export CGO_ENABLED=0` before running `gulp build` produces a static binary.

**Comment by luxas** [comment]
Whohoo! Finally I'm up and running in a docker container
```
docker run -d -p 9090:9090 kubernetesonarm/dashboard --apiserver-host=http://192.168.1.54:8080
```
Will share the source soon

**Comment by bryk** [comment]
Thank you @luxas for finding the bug! :) I'll fix it soon.

**Comment by Millyna** [comment]
@bryk @luxas 
late reply, so many emails.. 
I'm just working alone, I'm a final year SE student and using kubernetes as part as my dissertation.
I was using your project @luxas towards the beginning but kept running into issues (not your fault, or the projects) I decided to build kubernetes myself to gain knowledge and understanding so no longer using! Great project though!

**Comment by luxas** [comment]
OK, I'm working on kubernetes/kubernetes#17981 right now. 
There you'll probably find some useful information.

Instructions how to build Kubernetes on arm hosts can be found in the `kubernetesonarm/build` image if you like

I totally agree that the best way of learning Kubernetes is by porting it by yourself, that's how I learned it :smile:

**Comment by floreks** [comment]
Our build pipeline is now pretty good and we're targeting many architectures. I think this is resolved. 
Newest release: https://github.com/kubernetes/dashboard/releases/tag/v1.0.0
