### ISSUE TITLE
Allow overriding the bearer token via an authorization header

### ISSUE THREAD

**Issue by Steniaz** [kubernetes/dashboard#2002]
##### Environment
My kubernetes environment has been created using kops. The dashboard is running in a pod and proxied via the following docker image: evry/oidc-proxy

I am trying to use the authorization header as authentication that is set by this proxy. However I allways get the error:

User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)

I gave the kubernetes dashboard account the cluster role system:discovery. This is a default role provided by kubernetes that gives the dashboard access to the version as needed.

So It seems the forwarding of the authorization header does not work.

```
Dashboard version: 1.6.1
Kubernetes version: 1.6.4
Operating system: ubuntu 16.04
```

##### Steps to reproduce
Deploy kubernetes dashboard in one pod with a proxy container from this image: https://hub.docker.com/r/evry/oidc-proxy/

##### Observed result
This error always pops up.

User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)

##### Expected result
The kubernetes dashboard should use the authorization header set instead of the service account

**Comment by Steniaz** [comment]
It seems that evry/oidc-proxy did not forward the authorization header

**Comment by Starefossen** [comment]
@stijndehaes it does now in v1.1.0 😄
