### ISSUE TITLE
Update screenshots on k8s.io docs page

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#2009]
K8s.io docs page seems to be pretty stale at the moment: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

Screenshots do not capture great progress we've made over time :) 

I guess this needs a small update, doesn't it?

**Comment by cnwalker** [comment]
Is the current screenshot updated (doesn't appear to have search and some other features)? If not I'd be interested in doing this! I can provide an image or merge one you provide.

**Comment by zouyee** [comment]
update screenshots with kubernetes-dashboard:v1.6.1? @bryk

**Comment by floreks** [comment]
I think we should wait until before or right after the 1.6.2 release because UI has changed a bit and there is no point in updating doc with old screenshots.

**Comment by sachet-mittal** [comment]
I have a pull request for this. Seeking approval

/assign @steveperry-53

**Comment by sachet-mittal** [comment]
Can we close this issue now that commit is merged. @steveperry-53 ?

**Comment by maciaszczykm** [comment]
@sachet-mittal We can close. Whole UI docs need update but we will track from https://github.com/kubernetes/dashboard/issues/1719.
