### ISSUE TITLE
"Roles" section is broken

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#2010]
##### Environment

```
Dashboard Version: v1.6.1
Git Commit: dd28d1a01225d441e8d012235e5cf91d23381197
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", 
GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", 
GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps to reproduce
Clic "Roles" menu item.

##### Observed result
The page responds 404. Logs are:

```
[2017-06-02T21:42:14Z] Incoming HTTP/1.1 GET /api/v1/rbacrole?filterBy=&itemsPerPage=10&namespace=&page=1&sortBy=d,creationTimestamp request from 10.242.0.28:59740: {}
Getting list of RBAC roles
the server could not find the requested resource
[2017-06-02T21:42:14Z] Outcoming response to 10.242.0.28:59740 with 404 status code
Getting application global configuration
```

![image](https://cloud.githubusercontent.com/assets/1159999/26745950/f161137c-47a1-11e7-9fb0-3defeb5a2844.png)

##### Comments
Is this because I'm running on an old cluster? Or have disabled Rbac? How can we prevent this from happening?

**Comment by floreks** [comment]
What k8s version are u using? Some of resources have different versions i.e. they advance from `v1beta1` to `v1` and we'd need to use different client to get them on older cluster version. We are trying to be compliant with kubernetes versioning and support all features. Dashboard 1.6.X will work on K8S 1.6.X but we can't guarantee that it will work the same with K8S 1.5.X. API and versioning changes too much between versions.

**Comment by bryk** [comment]
I have a 1.6.2 cluster.

**Comment by bryk** [comment]
Are roles in alpha?

**Comment by floreks** [comment]
AFAIR they have been promoted from alpha to beta in 1.6 release.

**Comment by bryk** [comment]
RBAC is disabled for me. That's the thing. Can we make our code resilient to such configurations? We could just show a page that says RBAC is disabled.

**Comment by floreks** [comment]
Yes. We should do that.

**Comment by floreks** [comment]
@bryk Any ideas what should we do in case RBACs are not enabled? Remove them from menu? Change error message to indicate that they might be disabled?

**Comment by cheld** [comment]
I would remove from the menu, but write a log message.
