### ISSUE TITLE
Dashboard making too many unnecessary api calls

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/dashboard#2014]
IIUC, currently the dashboard seems to make GET/LIST requests once every minute for all the different kinds of resources (jobs, RCs, daemonsets, configmaps, secrets, pretty much everything). These account for about 1/5th of the steady state qps in a 3-node cluster started using kube-up.sh.

How to reproduce:
- Start a cluster with [cluster/kube-up.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-up.sh)
- SSH to master and grep for the no. of api calls made in one minute. It was ~430 per minute when I checked.
- Now delete the `kubernetes-dashboard` deployment and recheck the qps. It should be ~340 per minute.

We shouldn't be needing to make 90 calls every minute. We should instead watch for the resources or at least make these calls on a per-user-request basis. But listing them each minute is too much load, even more if the cluster is huge with a large no. of resources.

cc @kubernetes/kube-ui-maintainers  @kubernetes/sig-scalability-misc

**Comment by bryk** [comment]
@floreks @maciaszczykm Have you observed that? Is this something introduced recently?

**Comment by cheld** [comment]
Interesting, not aware that anything happens without user request

**Comment by floreks** [comment]
Dashboard shouldn't do any request by itself. We do not have any kind of polling mechanism. Even if you keep dashboard open in a browser then looking at network usage and logs I can tell that there are no requests made without user action. 

Could you provide us logs from dashboard and which version are you using? Maybe it's some health check of the container not dashboard backend.

**Comment by maciaszczykm** [comment]
I am also not aware of any requests done without user actions, but we may be missing something.

> SSH to master and grep for the no. of api calls made in one minute. It was ~430 per minute when I checked.

@shyamjvs Could you tell us  which command did you use?

**Comment by shyamjvs** [comment]
> I am also not aware of any requests done without user actions, but we may be missing something.

@floreks @maciaszczykm I could finally get to this today. It turns out you are right and there are no requests made by the dashboard itself without having user requests. And yes, those seem to be calls around maintenance of the dashboard controller and service. Like these:

```
I0607 01:49:03.315751       5 wrap.go:42] GET /api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: (3.483186ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/f33a5f8/system:serviceaccount:kube-system:endpoint-controller] [::1]:45562]
I0607 01:49:33.310616       5 wrap.go:42] GET /api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: (9.545886ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/f33a5f8/system:serviceaccount:kube-system:endpoint-controller] [::1]:45562]
I0607 01:49:41.612891       5 wrap.go:42] GET /apis/extensions/v1beta1/namespaces/kube-system/deployments/kubernetes-dashboard: (2.21122ms) 200 [[kubectl/v1.6.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:43772]
I0607 01:49:41.617431       5 wrap.go:42] PATCH /apis/extensions/v1beta1/namespaces/kube-system/deployments/kubernetes-dashboard: (2.051893ms) 200 [[kubectl/v1.6.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:43772]
I0607 01:49:41.668681       5 wrap.go:42] GET /api/v1/namespaces/kube-system/services/kubernetes-dashboard: (1.901546ms) 200 [[kubectl/v1.6.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:43772]
I0607 01:49:41.673817       5 wrap.go:42] PATCH /api/v1/namespaces/kube-system/services/kubernetes-dashboard: (3.155823ms) 200 [[kubectl/v1.6.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:43772]
I0607 01:49:41.680501       5 wrap.go:42] GET /api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: (3.514621ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/f33a5f8/system:serviceaccount:kube-system:endpoint-controller] [::1]:45562]
```

And there are not many of them, 10-15 per minute. I'm trying to figure out why I had seen a difference of 80 back then. Could be a coincidence that api calls reduced at around the same time as I killed the dashboard. Because from what I'm seeing now, 
```
shyamjvs@kubernetes-master ~ $ grep "wrap.go:42" /var/log/kube-apiserver.log | grep " 02:34" | wc -l
480
shyamjvs@kubernetes-master ~ $ grep "wrap.go:42" /var/log/kube-apiserver.log | grep " 02:35" | wc -l
522
shyamjvs@kubernetes-master ~ $ grep "wrap.go:42" /var/log/kube-apiserver.log | grep " 02:36" | wc -l
469
shyamjvs@kubernetes-master ~ $ grep "wrap.go:42" /var/log/kube-apiserver.log | grep " 02:37" | wc -l
476
```
it seems to go up by ~40 occasionally and then come back to normal again.
And fyi, I might've been using dashboard v1.6.0 as my cluster was a bit old and I see you've changed the version to 1.6.1 ~20 days ago (though it doesn't seem like that affected much). Sorry for the blooper, closing this issue. Though I'll recheck this once again later to be sure if there's something I might've failed to reproduce.
