### ISSUE TITLE
Basic authentication file 

### ISSUE THREAD

**Issue by Ludea** [kubernetes/dashboard#2021]
##### Environment
I install Kubernetes with kubeadm. 
I install dashboard with this command : kubectl create -f https://git.io/kube-dashboard
The network pod is weave. 
I add into /etc/kubernetes/manifests/kube-apiserver.yaml  --basic-auth-file=/home/login.csv
I create login.csv and populate it like https://kubernetes.io/docs/admin/authentication/#static-password-file. 
I reboot my vps, go at https://master-ip/ and I have not the page with login page 
All pods are running with commands kubetcl get pods - - all-namespaces

Dashboard version: 1.6.1
Kubernetes version: 1.6.4
Operating system: Ubuntu server 16.04

##### Steps to reproduce
 install kubernetes with kudeadm et weave for the network pod. 
Install dashboard 
 Add --basic-auth-file=/home/login . csv in kube-apiserver.yaml 
Restart the vps 
Open a web browser and go at https://master-ip/

##### Observed result
The web page return : ERR_CONNECTION_RESET

##### Expected result
I would like to access dashboard over Internet with basic auth file 

##### Comments
I cannot go to http://localhost:8001 because it is a distant vps.

**Comment by floreks** [comment]
This is cluster config issue. You can't easily access apiserver over https without having valid certificates installed in your browser. Dashboard works fine but you are having troubles with configuration. Try to create an issue on kubernetes repository.

**Comment by Ludea** [comment]
Is there an example to access dashboard through external nginx oauth with ingress controller and kube-lego?

**Comment by floreks** [comment]
I don't think there is. At least we do not provide any tutorials for custom configurations. Our docs cover only very basic deploy and access to dashboard. Rest is up to the user how he wants to secure and access dashboard.

As mentioned on our slack @benley had some success configuring dashboard with oauth proxy.  
https://kubernetes.slack.com/archives/C09R1JVU6/p1496625562082058
