### ISSUE TITLE
Can't access dashboard after upgrading GKE cluster from 1.5.7 -> 1.6.4

### ISSUE THREAD

**Issue by troy0820** [kubernetes/dashboard#2022]
##### Environment

```
Dashboard version: 1.6.0
Kubernetes version: 1.6.4
Operating system: macOS sierra
Node.js version: 8.0.0
Go version: 1.8
```

##### Steps to reproduce

Upgraded cluster from master 1.5.7 to 1.6.4 on GKE
##### Observed result

`User "system:anonymous" cannot proxy services in the namespace "kube-system".: "No policy matched.\nUnknown user \"system:anonymous\""`
##### Expected result

I expected to see the kubernetes-dashboard that was present before upgrading my cluster 

##### Comments

I can still `kubectl proxy` and access the dashboard at `localhost:8001/ui` but not directly from the information found in `kubectl cluster-info`

**Comment by floreks** [comment]
Starting from 1.6.x kubernetes has more restrictive RBACs and you can't access any resources over proxy as anonymous user anymore. You have to use either correctly configured kubectl proxy or configure some auth-proxy in front of dashboard.

**Comment by floreks** [comment]
Also our new yaml files contain separate SA for dashboard wth all required privileges set. You might want to upgrade dashboard to 1.6.1.
