### ISSUE TITLE
Dashboard main page not showing up. Instead showing warning for outdated browser.

### ISSUE THREAD

**Issue by ajayapte** [kubernetes/dashboard#2023]
##### Environment

```
Dashboard version: One from https://git.io/kube-dashboard
Kubernetes version: Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Operating system: Ubuntu 16.04
Node.js version:
Go version: GoVersion:"go1.7.5",
```

##### Steps to reproduce

Install dashboard by doing kubectl create -f https://git.io/kube-dashboard

##### Observed result

I get something like this from browser or from curl - 
```
<!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title ng-controller="kdTitle as $ctrl" ng-bind="$ctrl.title()"></title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.803608cb.css"> <link rel="stylesheet" href="static/app.336a76b4.css"> </head> <body> <!--[if lt IE 10]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser.
      Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
      experience.</p>
    <![endif]--> <kd-chrome layout="column" layout-fill> </kd-chrome> <script src="static/vendor.31531c85.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.f69f96ab.js"></script> </body> </html>
```
##### Expected result

Daashboard main page.

##### Comments

I have tried various browsers - safari, FF, chrome and all my browsers are quite up to date.   RBAC is on.  I don't see any errors in dashboard pod logs.  Last few lines show like this - 
```
Getting application global configuration
Application configuration {"serverTime":1497240305016}
Getting application global configuration
Application configuration {"serverTime":1497240607086}
Getting application global configuration
Application configuration {"serverTime":1497240788633}
Getting application global configuration
Application configuration {"serverTime":1497240923280}
Getting application global configuration
Application configuration {"serverTime":1497240953145}
Getting application global configuration
Application configuration {"serverTime":1497240991450}
Getting application global configuration
Application configuration {"serverTime":1497241110426}
```

**Comment by floreks** [comment]
We have a check in `index.html` to make sure that user does not use IE < 10. All other browsers should work fine. We've never seen such a problem actually and personally I also have never seen this page and I usually check dashboard on FF, Chrome and sometimes IE 11+.

As for the curl it is normal that it returns such page since we have only single page with many states and angular is responsible for dynamically loading parts of a page.

I don't really know what might be the cause of this. Maybe some plugins that makes requests anonymous or maybe you are using some proxy that hides browser identity. It looks like some system issue.

**Comment by ajayapte** [comment]
I am using a floating IP in front of a VM dispensed by openstack.   I am on Mac so IE is not even in the picture.  Does the code check for IE in the header before making a check  for version?

**Comment by floreks** [comment]
We are using very simple conditional comment:
```html
<!--[if lt IE 10]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser.
      Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
      experience.</p>
<![endif]-->
```
Main part is not commented out anyway so this should be displayed only in addition to the page content.

**Comment by floreks** [comment]
Any progress?

**Comment by floreks** [comment]
Closing as stale.

**Comment by lrills** [comment]
Also encounter the same problem, it seems that static files inaccessible by browser.
![screen shot 2017-07-21 at 4 39 29 pm](https://user-images.githubusercontent.com/7855890/28459744-660c88da-6e41-11e7-90a5-3caea3e84723.png)
Dashboard created with the latest deploy manifest.

**Comment by floreks** [comment]
This looks like a cluster config issue. It seems that you don't have access to some resources in the cluster. Try to expose and access dashboard using `NodePort` and check if error still occurs.

**Comment by lrills** [comment]
It still happens while exposing dashboard with `NodePort`, which `index.html` successsfully fetched and the static files are pending.
![screen shot 2017-07-24 at 11 53 05 am](https://user-images.githubusercontent.com/7855890/28507675-4f68a348-7067-11e7-900a-55b846e67f34.png)

**Comment by floreks** [comment]
It looks like cluster/system issue. Something along the way is blocking you from downloading assets from the server. It might be firewall, some browser plugin, etc. There are many possibilities but I don't think this is related directly to dashboard.
