### ISSUE TITLE
Bug: about page template not filled in (@@THINGS)

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/dashboard#2025]
I'm on kops 1.6.1, running kubernetes 1.6.4.

Dashboard Docker image used: `gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1`

Screenshot demonstrating the issue:

![2017-06-12-192033_1920x1080_scrot](https://user-images.githubusercontent.com/4689687/27046416-9ef3d0ec-4fa4-11e7-8f84-c477dc7bc86d.png)

If there's anything more that needs clarifying I'm around.

**Comment by floreks** [comment]
It's already fixed on master. Will be available in 1.6.2 release.

**Comment by bryk** [comment]
@floreks Should we do 1.6.2 release? I can push

**Comment by floreks** [comment]
We could. We have fixed some important bugs. Minor release might be a good idea.
