### ISSUE TITLE
browserify version can’t meet requirements

### ISSUE THREAD

**Issue by chunnallu** [kubernetes/dashboard#2028]
when i run 
```
npm install
```
i got an error : 
```
npm ERR! peer dep missing: browserify@>= 2.3.0 < 4, required by browserify-shim@2.0.10
```
so，i install the browserify@2.3.0 ：

```
npm install browserify@2.3.0
```
and now , the other error appeared:
```
npm ERR! peer dep missing: browserify@>=10 <15, required by karma-browserify@5.1.1
``` 

this is  contradictory ! is there a suitable version can solve this?

**Comment by floreks** [comment]
Whas OS are you using? Just yesterday I have tried full npm install on clean repo and it worked fine on my ubuntu.

_Sent from my LGE Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chunnallu** [comment]
My OS is Ubuntu, when i running 
```
npm install 
``` 
that information is shown as a warnning，and then i run
```
npm list
```
that information is shown as a error like above!

Today i had deleted the `node_modules` directory ,and ran `npm install ` again . Due to the network is slow ,  the process have not yet  complete !  I would place more informations the next monday !

**Comment by cheld** [comment]
Things like this happen to me also from time to time (sometimes network has issues, also enterprise firewalls have issues) Can you retry? Maybe different network?

**Comment by chunnallu** [comment]
# my environment

The OS is:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
The node version  is:
```
v6.11.0
```
the npm version is ：
```
3.10.10
```

# retry  operation and error

#### (1) network is free

 I setup an Ipsec VPN , so the network is considered to be free ! 

#### (2) redo npm install and get error
 update the `package.json` , clean the  `node_modules` directory and run npm install : 
```
npm cache clean
rm -rf node_modules
sudonpm install --unsafe-perm
```
and then i got a list of warnning: 
```text
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none was installed.
npm WARN browserify-shim@2.0.10 requires a peer of browserify@>= 2.3.0 < 4 but none was installed.
npm WARN kubernetes-dashboard@1.6.1 No description

```
i run `npm list`,and get two ERR:
```text
npm ERR! peer dep missing: webpack@2, required by babel-loader@7.0.0
npm ERR! peer dep missing: browserify@>= 2.3.0 < 4, required by browserify-shim@2.0.10
```
the first ERR can be solve by:
```text
npm install  webpack@2.6.1 --save-dev
```

but i have not idea to solve the second one ! because if i install ` browserify@2.3.0`:
```text
 npm install browserify@2.3.0 --save-dev
```
i would get an another ERR:
```text
npm ERR! peer dep missing: browserify@>=10 <15, required by karma-browserify@5.1.1
```


#### (3)may be the result cause by that Error

With that ERR unsolve,i run`sudo gulp frontend-test`,and get under error:
```text
19 06 2017 14:22:21.111:ERROR [launcher]: Cannot start Chrome

19 06 2017 14:22:21.114:ERROR [launcher]: Chrome stdout:
19 06 2017 14:22:21.115:ERROR [launcher]: Chrome stderr:
19 06 2017 14:22:21.387:ERROR [launcher]: Cannot start Chrome

19 06 2017 14:22:21.387:ERROR [launcher]: Chrome stdout:
19 06 2017 14:22:21.387:ERROR [launcher]: Chrome stderr:
19 06 2017 14:22:21.677:ERROR [launcher]: Cannot start Chrome

19 06 2017 14:22:21.677:ERROR [launcher]: Chrome stdout:
19 06 2017 14:22:21.678:ERROR [launcher]: Chrome stderr:
19 06 2017 14:22:21.678:ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
[14:22:21] 'frontend-test' errored after 1.35 min
[14:22:21] Error: Failed 1 tests.
    at /root/.jenkins/workspace/dashboard-dev/build/test.js:64:24
    at removeAllListeners (/root/.jenkins/workspace/dashboard-dev/node_modules/karma/lib/server.js:380:7)
    at Server.<anonymous> (/root/.jenkins/workspace/dashboard-dev/node_modules/karma/lib/server.js:391:9)
    at Server.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1552:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9
```

**Comment by chunnallu** [comment]
@cheld @floreks

**Comment by floreks** [comment]
Is there a reason why you are running `npm` as a sudo? Do you keep dashboard in root only directory?

I can also see bunch of warnings when doing `npm i` and same errors on `npm list`. Warnings are mostly because of using deprecated modules. We'll update them eventually. I'm not sure what can be the cause. Maybe running as sudo causes some kind of issues with dependencies.

Try using nvm to install node and just run `npm i` to install deps when in dashboard directory. No more steps should be required.

PS. Did you try to run other tasks? i.e. `gulp backend-test` or `gulp serve`

**Comment by cheld** [comment]
Do you have Chrome installed? I guess Karma defaults to Chrome

**Comment by chunnallu** [comment]
@floreks thanks very much! no special cause , just because my development server can't not run `npm install` directly by default , and the server is in a  secure LAN network . The auto test and build tasks created in jenkins also run as root defalut too. Thus both of us can see those errors and you can run `gulp test` correctly , it most likely to be my mistake ! 
Another, `gulp serve` can be run seccessfully !   `gulp backend-test`  fail !

@cheld thanks very much ! It seems that my chrome was not installed correctly ! I have installed the chrome by running:
```
sudo apt-get  install google-chrome-stable
```
i can see it in my development server which is a ubuntu desktop . but I can't start it by command line:
```
sudo google-chrome-stable
```
thanks again ! I would write below if i find out the reason!
