### ISSUE TITLE
Table titles unreadable on smaller screens

### ISSUE THREAD

**Issue by OmgImAlexis** [kubernetes/dashboard#2032]
##### Environment

Not sure because of https://github.com/kubernetes/dashboard/issues/2030

##### Steps to reproduce

Open nodes page

##### Observed result
Loads of different pages have this issue with the table titles not fitting. If I close the sidebar it's readable.
![screen shot 2017-06-16 at 5 56 08 pm](https://user-images.githubusercontent.com/6525926/27218473-68b2e394-52bd-11e7-93a2-c7b2faa958ee.png)

**Comment by floreks** [comment]
This is also already fixed on master but thanks for creating issue. It's always appreciated because we can't notice everything :)
