### ISSUE TITLE
how to build dockerfile and run as a container

### ISSUE THREAD

**Issue by HaiboShi** [kubernetes/dashboard#2039]
i just built the Dockerfile using : docker build
 and  got a image : dashnew

when i apply the dashnew on the k8s environment, it doesn't work.

how to fix it ?

**Comment by cheld** [comment]
You must run the gulp build script to create the binaries. Have you done this?

Please provide more details, logs etc

**Comment by HaiboShi** [comment]
@cheld 
I run into the docker image and run "gulp serve"
is that right? 
and 'Proxy created: /api  ->  http://localhost:9091'  

____________________
applied yaml:

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-dashboard
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
    spec:
      containers:
      - name: kubernetes-dashboard
        #image: 10.37.19.2:5000/gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
        image: 10.37.19.2:5000/dashnew:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP
        args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          - --apiserver-host=http://10.37.19.31:8080
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
      serviceAccountName: kubernetes-dashboard
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kubernetes-dashboard

root@3611babc8915:/dashboard# gulp serve
[06:15:44] Requiring external module babel-register
[06:15:48] Using gulpfile /dashboard/gulpfile.babel.js
[06:15:48] Starting 'clean-packaged-backend-source'...
[06:15:48] Starting 'kill-backend'...
[06:15:48] Finished 'kill-backend' after 106 μs
[06:15:48] Starting 'locales-for-backend:dev'...
[06:15:48] Starting 'scripts'...
[06:15:48] Starting 'styles'...
[06:15:48] Starting 'buildExistingI18nCache'...
[06:15:48] Finished 'clean-packaged-backend-source' after 244 ms
[06:15:48] Starting 'package-backend-source'...
[06:15:48] Finished 'buildExistingI18nCache' after 346 ms
[06:15:48] Starting 'angular-templates'...
[06:15:48] Finished 'locales-for-backend:dev' after 697 ms
[06:16:01] Finished 'scripts' after 13 s
[06:16:01] Finished 'styles' after 14 s
[06:16:01] Starting 'index'...
[06:16:01] Finished 'index' after 196 ms
[06:16:02] Finished 'angular-templates' after 14 s
[06:16:02] Starting 'watch'...
[06:16:02] Finished 'watch' after 563 ms
[06:16:02] Finished 'package-backend-source' after 14 s
[06:16:02] Starting 'link-vendor'...
[06:16:02] Finished 'link-vendor' after 302 μs
[06:16:02] Starting 'package-backend'...
[06:16:02] Finished 'package-backend' after 2.59 μs
[06:16:02] Starting 'backend'...
[06:17:35] Finished 'backend' after 1.55 min
[06:17:35] Starting 'spawn-backend'...
[06:17:35] Finished 'spawn-backend' after 21 ms
[06:17:35] Starting 'serve'...
[HPM] Proxy created: /api  ->  http://localhost:9091
[06:17:35] Finished 'serve' after 27 ms
Using HTTP port: 8443
Using apiserver-host location: http://10.37.19.31:8080
Skipping in-cluster config
Using random key for csrf signing
No request provided. Skipping authorization header
Successful initial request to the apiserver, version: v1.6.0
Creating in-cluster Heapster client

**Comment by cheld** [comment]
Sorry, I am a bit confused. Have you read the documentation?

https://github.com/kubernetes/dashboard/blob/master/docs/devel/getting-started.md

**Comment by floreks** [comment]
`gulp serve` starts dashboard locally based on source code not docker container. You should build docker image only if you want to deploy it in the cluster, i.e. using `kubectl create`. Please read documentation for more information.

**Comment by floreks** [comment]
I think that what you were looking for is to build and start dashboard in a docker container. It is described in our documentation: https://github.com/kubernetes/dashboard/blob/b0d21984065681ed3d5ea878eb60bd54a8d6a0ce/docs/devel/requirements-installation.md#run-the-kubernetes-cluster
