### ISSUE TITLE
Building Dashboard Inside a Container -Task 'default' is not in your gulpfile

### ISSUE THREAD

**Issue by HaiboShi** [kubernetes/dashboard#2040]
# sh build/run-gulp-in-docker.sh
Sending build context to Docker daemon 90.79 MB
Step 1 : FROM golang
 ---> 41e7847de71b
Step 2 : RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -   && apt-get install -y --no-install-recommends 	openjdk-7-jre 	nodejs 	&& rm -rf /var/lib/apt/lists/* 	&& apt-get clean
 ---> Using cache
 ---> 9f062ae6aa76
Step 3 : RUN curl -sSL https://get.docker.com/builds/Linux/x86_64/docker-1.9.1 > /usr/bin/docker &&     chmod +x /usr/bin/docker
 ---> Using cache
 ---> aa69d8091320
Step 4 : WORKDIR /dashboard
 ---> Using cache
 ---> 155c4eeec2d2
Step 5 : COPY package.json bower.json ./
 ---> Using cache
 ---> 03c9da79df44
Step 6 : COPY build/postinstall.sh build/
 ---> Using cache
 ---> c60b570dca0b
Step 7 : RUN npm install --unsafe-perm
 ---> Using cache
 ---> 74bf21ee92de
Step 8 : COPY ./ ./
 ---> Using cache
 ---> 165f97dcd49e
Successfully built 165f97dcd49e
[06:37:21] Requiring external module babel-register
[06:37:25] Using gulpfile /dashboard/gulpfile.babel.js
[06:37:25] Task 'default' is not in your gulpfile
[06:37:25] Please check the documentation for proper gulpfile formatting

**Comment by HaiboShi** [comment]
fix adding 'serve' as arg

**Comment by floreks** [comment]
This is correct. Just like our documentation says. https://github.com/kubernetes/dashboard/blob/b0d21984065681ed3d5ea878eb60bd54a8d6a0ce/docs/devel/requirements-installation.md#run-the-kubernetes-cluster

You need to pass some arg to this script.
