### ISSUE TITLE
Deploy from file should use token from rest request

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/dashboard#2041]
DeployAppFromFile still use in cluster config. It should also use the token extracted from request to build the config. 

I would like to submit a pr to fix it.

**Comment by floreks** [comment]
That's true. You are welcome to create PR for that. Thanks for creating an issue!

**Comment by qiujian16** [comment]
https://github.com/kubernetes/dashboard/pull/2046

**Comment by floreks** [comment]
Fixed by #2046.
