### ISSUE TITLE
problem with create deploy on the webui

### ISSUE THREAD

**Issue by HaiboShi** [kubernetes/dashboard#2047]
creating job in the backend with shell command is good, but fails with the webui.

the error message:
error validating "o.yml": error validating data: found invalid field schedulerName for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false 
Would you like to deploy anyway?

push ok, then come up with:
Internal error occurred: error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused.

the backend log:
error validating "o.yml": error validating data: found invalid field schedulerName for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
[2017-06-21T09:57:58Z] Outcoming response to 127.0.0.1:47513 with 500 status code
[2017-06-21T09:58:11Z] Incoming HTTP/1.1 POST /api/v1/appdeploymentfromfile request from 127.0.0.1:47812: {
  "content": "# deployment\n\napiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  name: openquake-centos7-test\n  namespace: train\n  labels:\n    app: openquake-centos7-test\nspec:\n  replicas: 1\n  strategy:\n    rollingUpdate:\n      maxSurge: 1\n      maxUnavailable: 1\n    type: RollingUpdate\n  template:\n    metadata:\n      labels:\n        app: openquake-centos7-test\n      name: openquake-centos7-test\n    spec:\n      containers:\n      - command:\n        - /bin/bash \n        - '-c'\n        args:\n        - \"/bin/bash /opt/openquake/oqrun.sh \u0026\u0026 sleep infinity\"\n        image: 10.37.19.2:5000/openquake-centos7\n        imagePullPolicy: Always\n        name: openquake-centos7-test\n        ports:\n        - containerPort: 8800\n          protocol: TCP\n        resources: {}\n      dnsPolicy: ClusterFirst\n      restartPolicy: Always\n      schedulerName: default-scheduler\n      securityContext: {}\n      terminationGracePeriodSeconds: 30\n\n---\n# service\n\napiVersion: v1\nkind: Service\nmetadata:\n  name: openquake-test\n  namespace: train\nspec:\n  ports:\n    - protocol: TCP\n      port: 80\n      targetPort: 8800\n  selector:\n    app: openquake-centos7-test\n  sessionAffinity: None\n  type: LoadBalancer\nstatus:\n  loadBalancer: {}\n\n---\n# ingress\n\napiVersion: extensions/v1beta1\nkind: Ingress\nmetadata:\n  name: train-test\n  namespace: train\nspec:\n  rules:\n  - host: openquake-test.com\n    http:\n      paths:\n      - backend:\n          serviceName: openquake-test\n          servicePort: 80\n",
  "name": "o.yml",
  "namespace": "train",
  "validate": false
}
Namespace for deploy from file: train
Internal error occurred: error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused

yaml:
# deployment

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openquake-centos71
  namespace: train
  labels:
    app: openquake-centos71
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openquake-centos71
      name: openquake-centos71
    spec:
      containers:
      - command:
        - /bin/bash 
        - '-c'
        args:
        - "/bin/bash /opt/openquake/oqrun.sh && sleep infinity"
        image: 10.37.19.2:5000/openquake-centos7
        imagePullPolicy: Always
        name: openquake-centos71
        ports:
        - containerPort: 8800
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
# service

apiVersion: v1
kind: Service
metadata:
  name: openquake1
  namespace: train
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8800
  selector:
    app: openquake-centos7
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

---
# ingress

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: train
  namespace: train
spec:
  rules:
  - host: openquake1.com
    http:
      paths:
      - backend:
          serviceName: openquake1
          servicePort: 80

**Comment by floreks** [comment]
How do you start dashboard?

**Comment by floreks** [comment]
Should be fixed by #2046.
