### ISSUE TITLE
Redesign display of chips

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#2048]
Related to #2033. We have to think how to improve display of labels/annotations/taints so the data is either not truncated or view mode can be easily switched.

**Comment by maciaszczykm** [comment]
We have reduced the number of chips displayed by default in ng migration and we have added a feature which displays whole chip content in dialog if chip would be too long:

<img width="333" alt="zrzut ekranu 2018-11-8 o 10 07 34" src="https://user-images.githubusercontent.com/2823399/48188488-269b7580-e33e-11e8-8db0-da3f38b73066.png">

<img width="647" alt="zrzut ekranu 2018-11-8 o 10 07 41" src="https://user-images.githubusercontent.com/2823399/48188487-269b7580-e33e-11e8-8ad5-fb41783fd1c4.png">

/close
