### ISSUE TITLE
Deploy a Containerized App ： can not set port for service！

### ISSUE THREAD

**Issue by helhades** [kubernetes/dashboard#2052]
##### Environment

```
Dashboard version:1.6.2
Kubernetes version:1.6.2
Operating system:centos7
Node.js version: i dont know
Go version:1.7.5
docker version:17.04
```

I want to "Deploy a Containerized App" .  
I chioce "Service" as internal or external . It should show port and targetPort to config. but it not show to me. 
I find some errors of js where i choice the service: 
TypeError: Cannot read property 'length' of undefined
    at N.ea (app.8a6b8127.js:84)
    at fn (eval at compile (vendor.6952e31e.js:10), <anonymous>:4:179)
    at f.$eval (vendor.6952e31e.js:8)
    at vendor.6952e31e.js:10
    at Object.<anonymous> (vendor.6952e31e.js:10)
    at o (vendor.6952e31e.js:6)
    at Object.$$writeModelToScope (vendor.6952e31e.js:10)
    at t (vendor.6952e31e.js:10)
    at vendor.6952e31e.js:10
    at l (vendor.6952e31e.js:10)

this.portMappings is undefined! i don't know why, thanks!

![image](https://user-images.githubusercontent.com/3489910/27473354-7ada3544-5831-11e7-9c6c-40e48f3243ab.png)

![image](https://user-images.githubusercontent.com/3489910/27473366-8ed385d2-5831-11e7-9468-1de09bca423d.png)

**Comment by floreks** [comment]
I can't reproduce that. What browser are you using? Could you check other browser?

**Comment by helhades** [comment]
thank for the  Reply of @floreks ，this problem is show in chrome firefox safari.
i debug js in safiri . it is show
![image](https://user-images.githubusercontent.com/3489910/27522304-9a008e64-5a57-11e7-8405-99674772737d.png)

![image](https://user-images.githubusercontent.com/3489910/27522315-b0a7b962-5a57-11e7-934c-38e5ee9d1c47.png)

so the this.portMappings is undefined.

**Comment by floreks** [comment]
I have looked at the code and checked multiple browser and unfortunately I don't see a way how portMappings could be undefined, both firefox and chrome are wroking fine for me. They are always initialized in controller constructor.

https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/deploy/deployfromsettings_controller.js#L87

**Comment by floreks** [comment]
Closing as stale. 

We have changed a bit `deployfromsettings_controller` and now it's handled as a `component`. Maybe this will fix it for you. We'll do a release in a few days so you can check it then. If it will happen again after release please inform us.
