### ISSUE TITLE
Old Replica Set is empty

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#2054]
```
Dashboard version: latest
Kubernetes version: 1.6.1 (dind-cluster)
```

##### Steps to reproduce
Create Deployment.
Update Deployment a couple of times

e.g. like in docs. https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

##### Observed result
UI shows only the active rs.
The historic rs are not shown.

But kubectl describe deployment also does not show the old replica sets. Did I miss anything?

```
$ kubectl describe deployment
Name:			nginx-deployment
Namespace:		default
CreationTimestamp:	Mon, 26 Jun 2017 08:35:36 +0200
Labels:			app=nginx
Annotations:		deployment.kubernetes.io/revision=8
			kubernetes.io/change-cause=kubectl set image deployment/nginx-deployment nginx=nginx:1.9.3
Selector:		app=nginx
Replicas:		3 desired | 3 updated | 3 total | 3 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	25% max unavailable, 25% max surge
Pod Template:
  Labels:	app=nginx
  Containers:
   nginx:
    Image:		nginx:1.9.3
    Port:		80/TCP
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
  Progressing 	True	NewReplicaSetAvailable
OldReplicaSets:	<none>
NewReplicaSet:	nginx-deployment-3842378742 (3/3 replicas created)
Events:		<none>
```

```
kubectl get rs
NAME                          DESIRED   CURRENT   READY     AGE
nginx-deployment-3646295028   0         0         0         2h
nginx-deployment-3744336885   0         0         0         1h
nginx-deployment-3842378742   3         3         3         1h
```

Why is old replicaset list empty?

**Comment by floreks** [comment]
Documentation of deployments describes pretty well what old replica sets are for. I have followed it and I was able to see them in dashboard.

![zrzut ekranu z 2017-06-26 16-40-45](https://user-images.githubusercontent.com/2285385/27544794-835d15b0-5a8e-11e7-91c3-b253396c84a6.png)

They can be used for rollbacks and they are also "created" during rolling updates.

**Comment by cheld** [comment]
Ok, got it. but it is confusing...

I would suggest the following: 

```
If old replica set is empty:

    Only show new replica set with name "Replica Set"

Else:

   show as it is (new & old replica set)

```

WDYT?

**Comment by maciaszczykm** [comment]
@cheld In my opinion it could confuse users, because they would not know what happened with "old replica sets" card. I would say, that we should follow `kubectl` here, but it is not a strong opinion.

**Comment by cheld** [comment]
"kubectl get rs" and "kubectl rollout status" not really similar. I will check with our production team. If they guess the meaning correctly we can close

**Comment by floreks** [comment]
Opinion of few is not a reliable sample. Kubernetes has quite high point of entry and there are many terms that user has to get familiar with in the beginning. That is why in the early stage of the project we have agreed to follow `kubectl` user experience whenever we can. It is already used and known by many people that use kubernetes. If they know `kubectl` then they will have no problem using dashboard.

I think that we should not change the convention here. `Old Replica Sets` is a term used in documentation of kubernetes and like any other term introduced in kubernetes it is something that user has to get familiar with. We could extract information from documentation and just explain shortly in some info tooltip what it is.

**Comment by cheld** [comment]
In general it is a good idea to follow kubectl. However, in this case the CLI described in the docs is `kubectl rollout status` rather than `kubectl describe deployment`.

Overall we want to use the possiblities a graphical user interface allows. Supervising a rollout is a very important use case that deserves a much better user interface. But this is bigger issue and a point for the roadmap

BTW: non of the production teams guessed it correctly...

**Comment by floreks** [comment]
Idea to somehow show `rollout status` is nice. I'd keep that in mind and when @danielromlein is back think about a way to show it. Currently IMHO detail pages should reflect `describe` verb and extend it if possible. Rollout status seems like useful information to show in addition to what we have now.

**Comment by huapox** [comment]
> also "created" during rolling updates.
only showing when rolling
