### ISSUE TITLE
Remove TPR resource in favor of CRD

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2070]
Quoting from https://github.com/kubernetes/features/issues/95#issuecomment-311483403:

> As mentioned in the 1.7 release notes and docs, TPR is now deprecated and we plan to remove it in 1.8. Users should switch to CRD during the 1.7 timeframe.
>
> Please comment on the tracking issue for removal if you have any questions or concerns.

Should we remove all our customization related to them?

---

Tracker on core repository: https://github.com/kubernetes/kubernetes/issues/48152

---

During migration to CRD we should also add detail page which is missing for TPR instances at the moment (more details in https://github.com/kubernetes/dashboard/issues/1504).

**Comment by enisoc** [comment]
I imagine it would make sense to port any TPR customizations to CRD, which is essentially the next version of TPR.

**Comment by maciaszczykm** [comment]
@enisoc It is good news for us. I did not yet read full discussion, so thank you for you input.

**Comment by kenan435** [comment]
I had a short look at this. I would suggest keeping TPR and introducing CRD side by side for the **k8s** 1.7 release, since that is the approach the community is taking. Will will then phase out TPR's for 1.8.

**Comment by maciaszczykm** [comment]
We will track from #2493.
