### ISSUE TITLE
Update Chinese translations

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2077]
A lot of redundant translations were removed after my last changes. They were not used anyways. We need to provide new translations, because a lot of refactoring were done in the last months.

@Yamagami-Takuma @f-higashi @tangfeixiong @zouyee Could you help us there?

**Comment by Yamagami-Takuma** [comment]
Sure :)
@maciaszczykm 
About when is the deadline of this?

**Comment by maciaszczykm** [comment]
@Yamagami-Takuma Currently we have no precise date, but within a week or two we may be pushing new release.

**Comment by idealhack** [comment]
Hi, I've put up Chinese translations in #2116, please review.
