### ISSUE TITLE
Implement current CPU and memory usage 

### ISSUE THREAD

**Issue by zreigz** [kubernetes/dashboard#208]
![17_job details](https://cloud.githubusercontent.com/assets/13030040/12034129/7fcaf6e6-ae24-11e5-8ddf-21eafd16b595.png)

It requires mostly work on backend side.
TODO
- investigate ho to retrieve CPU and memory usage from API
- implement solution on backend side
- display data on detail view page

**Comment by maciaszczykm** [comment]
Already fixed.
