### ISSUE TITLE
Dashboard reported Internal Server Error (500)

### ISSUE THREAD

**Issue by jacieyoung** [kubernetes/dashboard#2080]
##### Environment

```
Dashboard version:1.5.1
Kubernetes version:1.6.2
Operating system:centos7.3
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
the server does not allow access to the requested resource (get replicationcontrollers)

```

**Comment by jacieyoung** [comment]
kubectl create clusterrolebinding add-on-cluster-admin \
    --clusterrole=cluster-admin \
    --serviceaccount=kube-system:default
resolved by accident

**Comment by jacieyoung** [comment]
https://github.com/luxas/kubeadm-workshop/blob/master/demos/monitoring/heapster.yaml

**Comment by maciaszczykm** [comment]
@jacieyoung Does it still occur?

**Comment by maciaszczykm** [comment]
Your Dashboard version is not aligned with Kubernetes 1.6+. Please use current release, as this is RBAC related issue.
