### ISSUE TITLE
execution commands on pod's containers - feature request

### ISSUE THREAD

**Issue by DawidCh** [kubernetes/dashboard#2082]
Hi.
It would be cool if I would have possibility to execute shell script (or have access to shell) on docker container which is started up for particular pod. 
![obraz](https://user-images.githubusercontent.com/14540695/27827513-e97f3f7e-60b7-11e7-9a3f-50073cdf7d09.png)
Or even have it in every workload entry, to invoke the same script to every docker container under it.
Also it would be nice to have console access (like in google cloud) to be able to perform operations on k8s nodes.
Now to be able to take a look into docker container (to debug sth) I have to ssh into machine where k8s is installed, then bash into docker image of the node (I have k8s into docker) then bash into particular pod's docker container. It would be a lot of easier to have it accessible from dashboard.
It is of course just an idea. With or without it I will use the dashboard anyway;)
Regards, Dawid.

**Comment by maciaszczykm** [comment]
@DawidCh It was implemented in #1939, but release it not done yet. You can check it out using our [HEAD release](https://github.com/kubernetes/dashboard/blob/master/docs/devel/head-releases.md).

**Comment by DawidCh** [comment]
Cool, thanks. So closing.
