### ISSUE TITLE
Namespace filtering: not(kube-system) or custom multi-select

### ISSUE THREAD

**Issue by donaldguy** [kubernetes/dashboard#2088]
I looked for another request like this and made a cursory search to see if it might be covered in the multi-tenant stuff, but didn't see anything; super sorry if I overlooked!

Currently I run a k8s 1.5 cluster where workloads are allocated:
- default: public-facing production services
- tools: internal-facing services
- kube-system: cluster wide services + k8s internals

As it stands, the Dashboard's left sidebar namespace selector is very useful to look at "just public", "just private", "just cluster-wide" or "all".

The public services serve different independent customers, and ideally we'd treat them as multi-tenant workloads (albeit in a scenario where all cluster admins with dashboard access will have at least ro, and probably rw, on all namespaces; isolation is just for the token-carriers/pods w.r.t. RBAC & potentially NetworkPolicy etc)

This would be a step up in data security, but it would be a loss for admin UX. In the cli we can at least suffix our `kubectl get`s w/ `--all-namsepaces | grep -v kube-system` but in the dashboard, splitting up will mean losing our ability to have a "global public" and "global private" view as we currently do.

Our "tools" workloads are probably gonna find their way to a separate cluster, but we are still gonna end up having to chose to look at either all production workloads mixed together w/ kube-system services or just a single namespace.

It would be ideal to be able to have a custom select for multiple namespaces, but that wouldn't really jive with the API namespacing as I understand it; (though label selectors are supported across namespaces and might be an option?)

But I think it would still be worthwhile to a to have a boolean option w.r.t `kube-system` in the context of "All Namespaces". Probably the filtering can/should just happen client side. It seems to me rather akin to the concept of "Show System Files" in Windows Explorer or macOS Finder

**Comment by maciaszczykm** [comment]
> It would be ideal to be able to have a custom select for multiple namespaces, but that wouldn't really jive with the API namespacing as I understand it; (though label selectors are supported across namespaces and might be an option?)

It is interesting proposal. We have to investigate how much time it will take to switch to it. Moreover, after we decide on something you can always help  us to implement it :) 

> But I think it would still be worthwhile to a to have a boolean option w.r.t kube-system in the context of "All Namespaces".

It is quickest way to start, but I am wondering if this is not too custom solution and if community will like it. The other way of filtering would be selecting `All namespaces` option and using filtering action (which currently filters using only namespaces, but we have plans to improve it).

> It seems to me rather akin to the concept of "Show System Files" in Windows Explorer or macOS Finder

I get your point, but I would like to add, that in my opinion if user/admin has access to system namespace then it is okay to show him its contents. We are targeting constant improvements in authorization area.
