### ISSUE TITLE
kubernetes dashboard support user login 

### ISSUE THREAD

**Issue by hongtao12310** [kubernetes/dashboard#2091]
do we have a plan to support user login on the dashboard?

so far , everyone could view / edit all the objects in all the namespaces which is not safe.

if i add some users into kubernetes and define the authorization for those users then i will expect to login the dashboard with different user account.

**Comment by floreks** [comment]
We are supporting user authorization through request header right now. In short if you add `Authorization: Bearer <token>` to request header that goes to dashboard then it will use it to authorize user.

We are planning to extend that but we have to rely on kubernetes authorization and there are many ways to authorize user right now. All of them depend on how you configure the cluster (webhook, external identity provider, keystone, simple auth, etc.).

**Comment by floreks** [comment]
We will track that from #2093.
