### ISSUE TITLE
Dashboard log in mechanism

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#2093]
We have had some initial discussion about that with @bryk. I have continued my investigation and came up with an idea how we could provide some log in mechanism in dashboard. 

Here is a sketch of how the data flow would look like (not very detailed though). First let's explain the general flow.

1. For user to log in we would need to handle few options. We would use structure similar to [this](https://github.com/kubernetes/client-go/blob/master/tools/auth/clientauth.go#L76) and at log in screen show this log in options: kubeconfig file, certificates, username & password, token.
2. Based on given data we can fill in this structure, encrypt it and save in a cookie.
3. Backend would get this cookie, decrypt structure and use it to create client.
4. Rest works similar to what we do now with authorization header. API server checks if user that "created client" is authorized to execute operation and returns data/not authorized error.

Note: We need to investigate if there is a way to check if user "exists" first.

![zrzut ekranu z 2017-07-06 16-01-15](https://user-images.githubusercontent.com/2285385/27914752-66fdd570-6264-11e7-9908-d904e8ed0d87.png)

Few things to consider:
1. We need some symmetric encryption alghorithm such as AES (128/256 bit key) as we need to send whole structure to the backend. Hashing will not work for us.
2. Key needs to be stored outside of our backend (secret/config map) in a secure way. Is it possible to give dashboard access only to single resource? Not whole resource type. If not then we could create separate namespace with configmap/secret just to store the key somewhere. 
3. Only dashboard/cluster admin should be able to see the key. Encrypted data is only stored in user browser as a cookie.
4. Do we need to think of a way to secure cookie from being copied to another computer and used there? We could add some expired flag and roll out new encryption key every 30/60/x min? Is it secure enough if we use HTTPS protocol to encrypt traffic between client and server? We can't force users to expose dashboard through HTTPS only but they have to be aware that they are open for MITM attacks if they use plain HTTP. 

Our backend would remain stateless and encrypted "session" would be stored in users' browser as a cookie. Are there any other problems to consider?

@bryk @rf232 @maciaszczykm @cheld @liggitt WDYT?

**Comment by floreks** [comment]
There also also JWT tokens that we could consider to secure user data.

_Sent from my LGE Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cheld** [comment]
Kubernetes supports sticky sessions. Would that help?

**Comment by floreks** [comment]
Session affinity requires stateful backend and our backend should remain stateless. Additionally kubernetes support for this is quite limited and might require additional controllers to be installed in the cluster.

JWT tokens seem to be perfect for us. They allow backend to remain stateless and keep encrypted user data in local storage/cookies.

_Sent from my LGE Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by floreks** [comment]
With JWT token data flow would be similar but secret used to sign user data would not be exposed. Only dashboard would have access to it and there would be no endpoint to check it. In our case secret would be kept in `kube-system` or some other namespace.

![image](https://user-images.githubusercontent.com/2285385/27947992-60d99668-62f8-11e7-8d70-7627216305aa.png)

We'd also need to enfroce dashboard to enable HTTPS by default as initial user data would have to be sent directly to the server so traffic encryption is highly recommended here to avoid MITM attacks.

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-proposals 

> We can't force users to expose dashboard through HTTPS only but they have to be aware that they are open for MITM attacks if they use plain HTTP.

I wouldn't expect user authentication to be made available over HTTP.

> We need some symmetric encryption alghorithm such as AES (128/256 bit key) as we need to send whole structure to the backend

I have a hard time telling from the diagram in the description, but if the encryption happens in the browser, the algorithm can't be symmetric, since that would give the browser the decrypting key.

> With JWT token data flow would be similar but secret used to sign user data would not be exposed. 

Are you proposing the dashboard act as a JWT issuer? For scenarios where the API server was configured with OIDC, I actually expected the dashboard to kick into an OIDC flow, outsource the whole login process, and consume an id_token and refresh_token.

**Comment by floreks** [comment]
> I wouldn't expect user authentication to be made available over HTTP.

We could probably do that or at least show some warning dialog if user wants to log in using HTTP.

> I have a hard time telling from the diagram in the description, but if the encryption happens in the browser, the algorithm can't be symmetric, since that would give the browser the decrypting key.

That was my initial thought but after doing some more investigation I know that we can't expose key. Data has to be sent and encrypted on our backend and only backend should have access to encryption key.

> Are you proposing the dashboard act as a JWT issuer? For scenarios where the API server was configured with OIDC, I actually expected the dashboard to kick into an OIDC flow, outsource the whole login process, and consume an id_token and refresh_token.

Yes, later on we could integrate log in mechanism with external identity providers and get JWT token from them. Initially I was just thinking that we could use JWT mechanism (actually JWE standard) to encrypt user data and save that in a cookie. In example in the beginning we can offer 4 options to log in: username & password, certificates (cert data), bearer token (which is using JWT standard) and using existing kubeconfig file. We can send this data to the backend and encrypt payload that contains sensitive user information there using HS256 symmetric alghorithm.

Usually these information are not stored in a token returned by the server but we need them to create api client. That is why my proposal is to encrypt them using JWE standard and keep encrypted data in a cookie.

Anyone knows if there is some api to check/get configured auth providers for apiserver? We would need to check how apiserver is configured in order to integrate with it better.

**Comment by ericchiang** [comment]
> Anyone knows if there is some api to check/get configured auth providers for apiserver? We would need to check how apiserver is configured in order to integrate with it better.

There's been some discussion around a public cluster-info document, and some of the initial "kubectl login" proposal discussed this (I think it was shot down).

Login as a general concept is also super complex. The kubectl auth providers aren't nice and extremely provider specific https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth. For example, even if you know the API server is using OpenID Connect, that doesn't mean you know how to trigger an OAuth2 login.

> Yes, later on we could integrate log in mechanism with external identity providers and get JWT token from them.

I'm skeptical of this proposal. I would have expected the dashboard to auth with an external provider like https://github.com/coreos/dex first. I believe the openshift dashboard does something similar (though the provider is the API server that case).
