### ISSUE TITLE
how i18n work?

### ISSUE THREAD

**Issue by chunnallu** [kubernetes/dashboard#2104]
i want to see the dashboard showing in Chinese when i run : 
```text
gulp serve
// or gulp serve:prod
```
I have looked through the `build\i18n.js`，but can,t find the answer.
what should i do ? 

thanks!

**Comment by maciaszczykm** [comment]
Just change yor browser main language to Chinese:

![image](https://user-images.githubusercontent.com/2823399/28066280-a31a3798-663c-11e7-92bb-0f2defc13181.png)

You will be able to see translations:

![image](https://user-images.githubusercontent.com/2823399/28066297-b77e5c0a-663c-11e7-86db-7e281160e7d4.png)

**Comment by maciaszczykm** [comment]
Will you be able to help us with providing more Chinese translations? We track it from https://github.com/kubernetes/dashboard/issues/2077. I am working on translation guide in https://github.com/kubernetes/dashboard/pull/2103. Your help would be appreciated very much!

**Comment by kaasia** [comment]
it not work anyway
i use this 
`export LANG="zh_CN.UTF-8"`
change my system language
then i run
"gulp serve"
i access url http://ip:9090
it still display English

**Comment by maciaszczykm** [comment]
Which browser do you use?

**Comment by kaasia** [comment]
i use IE , not local access , use external style

**Comment by maciaszczykm** [comment]
Please follow this tutorial: https://www.youtube.com/watch?v=XpoFlwJ_y9s

**Comment by chunnallu** [comment]
thanks very much! @maciaszczykm 

>  Will you be able to help us with providing more Chinese translations? We track it from #2077. I am working on translation guide in #2103. Your help would be appreciated very much!

my pleasure !  I'd like have a  try ! you do a great job !

**Comment by kaasia** [comment]
@maciaszczykm,
my outsite ie is using Chinese, but still not work 
 @chunnallu  do you know how to display Chinese

**Comment by chunnallu** [comment]
i am still trying，because myself project problem. 
i think you can try:  run with `:prod`
```
gulp serve:prod
```
As i see ,  only `gulp serve` may not do i18n.

Write in Chinese :
 由于我自己的项目的其它问题，我现在也还没有调出中文界面。不过我认为你可以试一下加上`prod`标签来运行：
```
gulp serve:prod
```
因为`gulp serve` 这个任务好像不做国际化的工作。 具体我也还没试过，调通再说吧！

**Comment by chunnallu** [comment]
@kaasia

**Comment by chunnallu** [comment]
I have solve  the problem in my project ! 
1. if you are using an older version of dashboard ,  open the `build/i18n.js`， search 
```
  if (fileExists.sync(translationBundle)) {
    command = `${command} --translations_file ${translationBundle}`;
  }
```
  the code `fileExists.sync(translationBundle)` can't not work in my ubuntu although the `translationBundle`   
 path exist ! It would cause your `i18n` folder be overrideed everytime you run `gulp serve:prod` , by the default english version.

  the quickly way to fix may be update ! If you can't , you can learn from the last version of `i18n.js`

2. if you are run with  `gulp serve` , you should run with `gulp serve:prod` instead！

@kaasia

**Comment by chunnallu** [comment]
solved!
