### ISSUE TITLE
Different results in dashboard and `kubectl top pod`

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/dashboard#2105]
I'm running on GCE (kubernetes 1.6.4)

Currently, I see this picture in dashboard, it shows usage of 500MB:

![image](https://user-images.githubusercontent.com/736697/28069425-d963672c-6662-11e7-8c04-d996d81b0991.png)

and `kubectl top pod ..` shows 324MB

![image](https://user-images.githubusercontent.com/736697/28069393-c1da4508-6662-11e7-9b99-19fe6eec0971.png)

Why I see such difference?

**Comment by floreks** [comment]
![zrzut ekranu z 2017-07-11 15-14-54](https://user-images.githubusercontent.com/2285385/28069985-b8432332-664b-11e7-8400-c1afd4f62753.png)

I don't know how kubectl checks usage but this is probably why.

**Comment by whitecolor** [comment]
Sorry if stupid question. What are memory caches in pods? Are they in RAM or something else?

**Comment by floreks** [comment]
It's related to how heapster exposes metrics. It exposes 2 metric names to get memory usage:

`memory/usage - Total memory usage.`
`memory/cache - Cache memory usage.`

I haven't checked the code so I don't know what exactly gets cached but total memory usage contains also the cache. I guess kubectl might get current usage where we display overall usage. OSes tend not to free memory when it is no longer used. This value might be the maximum value that was used by the pod at some point and system just did not freed unused memory. This is only my assumption.

> Are they in RAM or something else?

Usually yes, but it also depends on the system. It might keep some "RAM cache" on a disk file.

**Comment by whitecolor** [comment]
Some people on kube team may help to find this out? Maybe you ping them to draw attention to this issue?

**Comment by floreks** [comment]
I don't think this is an issue. Probably kubectl by default displays `all memory usage - cache` and we are displaying all memory usage including cache.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by floreks** [comment]
I have looked into this a bit and the difference is that we are using `memory/usage` metric and kubectl gets `memory/working_set`. From the heapster doc:

```
memory/usage - Total memory usage.
```
```
memory/working_set - Total working set usage. Working set is the memory being used and not easily dropped by the kernel.
```

I have checked the output of heapster, `kubectl top` and dashboard.

### Working set
![zrzut ekranu z 2017-07-12 11-19-59](https://user-images.githubusercontent.com/2285385/28111138-c3ecb5b4-66f4-11e7-9820-4115ad5101bd.png)
![zrzut ekranu z 2017-07-12 11-20-16](https://user-images.githubusercontent.com/2285385/28111142-c5a0c4ae-66f4-11e7-822e-4db069978705.png)

**8175616 bytes ~= 7.79 Mi**

### Total memory usage
![zrzut ekranu z 2017-07-12 11-20-26](https://user-images.githubusercontent.com/2285385/28111178-e936c1f2-66f4-11e7-96dd-1f74c15e7a4f.png)
![zrzut ekranu z 2017-07-12 11-20-36](https://user-images.githubusercontent.com/2285385/28111180-eb6104e2-66f4-11e7-8f0a-0c0ded8d2857.png)

**12881920 bytes ~= 12.28 Mi**

The question is if we should switch our memory usage metrics to working set to be consistent with kubectl?

@kubernetes/dashboard-maintainers

**Comment by whitecolor** [comment]
What is the best value to plan overall memory capacity of the cluster/nodes to accommodate pods? I believe max value?

**Comment by floreks** [comment]
> What is the best value to plan overall memory capacity of the cluster/nodes to accommodate pods? I believe max value?

I think max value will be a good choice for most scenarios unless you strictly need to minimize overall cost.

**Comment by genexp** [comment]
I just wanted to add - I think this is very unexpected and confusing.  I have several pods that report 400MB or so when I list them via `kubectl top` and 800MB with the Dashboard.

Users use these to configure Horizontal Pod Autoscaling, and out of memory kill limits.  Whatever is shown by the Dashboard and Kubectl should be consistent with whatever is used by the HPAs.

**Comment by floreks** [comment]
I was planning to update it before next release. It's just the matter of changing endpoint we are using to get cpu metrics.

**Comment by rakeshvanga** [comment]
When the memory limits are set on the container, which metric would be used by K8s to check the memory usage? `memory/usage` or `memory/working_set`

**Comment by juliantaylor** [comment]
Kubernetes (on linux) uses cgroups to limit the memory and let pods get killed if the use to much.
The cgroup limits do also consider the caches, see 2.2.1 Accounting details:
https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

So so `memory/usage` should be the correct metric and `kubectl top pods` is currently not a good source to determine the limits.

**Comment by malusm** [comment]
Is there a way to access memory/usage from kubectl?

**Comment by claudioweiler** [comment]
This is an old thread, but I got here and like to share my 50 cents.

Seems that memory limits do not apply to memory/usage (k8s 1.24). We have memory limits defined and they are below reported memory/usage with no pod killed, we just need to put memory limits below memory reported on kubectl to get pod killed.
