### ISSUE TITLE
dashboard backend should not log http request's body, otherwise, we could not get body by request.Request.Body 

### ISSUE THREAD

**Issue by riclava** [kubernetes/dashboard#2107]
##### Environment

```
Dashboard version: v1.6.1
Kubernetes version: v1.6.6
Operating system: centos 7.3
Node.js version: v6.10.1
Go version: go version go1.8 linux/amd64
```

##### Steps to reproduce

normally, besides, we can still use go-restful to get body data, but can not use request.Request.Body
##### Observed result

can not get body from request.Request.Body
##### Comments

it is caused by this method, I update it, from src/app/backend/handler/apihandler.go
```
// formatRequestLog formats request log string.
func formatRequestLog(request *restful.Request) string {
	uri := ""
	if request.Request.URL != nil {
		uri = request.Request.URL.RequestURI()
	}

	return fmt.Sprintf(RequestLogString, time.Now().Format(time.RFC3339), request.Request.Proto,
		request.Request.Method, uri, request.Request.RemoteAddr)
}
```

**Comment by floreks** [comment]
I'm not sure what do you mean, but currently we are displaying request body in logs also. You have copied outdated version of this function. This is the current version:

```golang
func formatRequestLog(request *restful.Request) string {
	uri := ""
	if request.Request.URL != nil {
		uri = request.Request.URL.RequestURI()
	}

	content := "{}"
	entity := make(map[string]interface{})
	request.ReadEntity(&entity)
	if len(entity) > 0 {
		bytes, err := json.MarshalIndent(entity, "", "  ")
		if err == nil {
			content = string(bytes)
		}
	}

	return fmt.Sprintf(RequestLogString, time.Now().Format(time.RFC3339), request.Request.Proto,
		request.Request.Method, uri, request.Request.RemoteAddr, content)
}
```

**Comment by maciaszczykm** [comment]
@riclava We do need to display it as it is pretty valuable for debugging.

I guess, that you are working on some custom code on your fork, if it is true, please modify this method inside your codebase. I do not know your use case, but with my current understanding this update would be a step backwards, so we cannot do it. Please correct me if I am wrong.

**Comment by floreks** [comment]
I don't see any valid use case that would require removing request body from logs also. It's a valuable information and we do not need to use it anywhere beside logs. Do you have any custom use case for it? If so then unless it's generic enough and useful for all we can't push it upstream.

**Comment by riclava** [comment]
@maciaszczykm @floreks 
my case is below:
```
func (prx *NginxProx) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	// Here I could not get req's Body by using ioutil
	// req is from request.Request
	redirectPrefix := "/api/v1/nginx"
	fw, freq, err := proxy.RequestFilter(w, req, redirectPrefix, prx.exchangeKey, prx.host)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	log.Println("<", req.Host, ">")
	prx.proxy.ServeHTTP(fw, freq)
}
```
yes, I have some custom code (reverse proxy) that will use request.Request.Body; it is true that I can use go-restful's API to read request body, and dashboard's own code works well without any problem ;-)
maybe this is just a case that warn someone who want to use request.Request directly.

**Comment by maciaszczykm** [comment]
> maybe this is just a case that warn someone who want to use request.Request directly.

I agree here, but still we cannot push it to upstream. You have to modify our log method on your fork. I think you already know how to do it, but if you have any questions let us know.

**Comment by riclava** [comment]
@maciaszczykm thanks a lot ~
