### ISSUE TITLE
Question: Where is the kubectl proxy  "/ui" URL path configured?

### ISSUE THREAD

**Issue by aalba6675** [kubernetes/dashboard#2111]
Newbie question: kubectl proxy  will proxy localhost:8001/ui to dashboard, I'm curious where is the mount path  /ui configured to map to selfLink: /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/?

**Comment by floreks** [comment]
In kubernetes core: https://github.com/kubernetes/kubernetes/blob/1bfef70836eff21d0e2945b5b786eb806b43ad92/pkg/routes/ui.go
