### ISSUE TITLE
Show same version of zero state on all pages?

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2121]
We have different versions of zero state on list views for example. All list views should look the same.

**Comment by cnwalker** [comment]
I'd be interested in taking a look at this. What are some examples of list views with different zero states?

**Comment by maciaszczykm** [comment]
It's a bit of refactoring, because we have duplicate zero state definitions in our code. Besides that, we are inconsistent so on node list view I can see following zero state:

![image](https://user-images.githubusercontent.com/2823399/28456237-f55bdcf6-6e01-11e7-9084-4e528dd63778.png)

And for almost all workload resources:

![image](https://user-images.githubusercontent.com/2823399/28456289-2417ceb0-6e02-11e7-8a77-01d911d70e6e.png)

It should be more consistent. If you need our help reach out to us on Slack or here :)

**Comment by floreks** [comment]
Second option should be displayed on pages like: Cluster, Workloads, Config and Storage. First option should be displayed on all resource list (for single resource) and detail pages.
