### ISSUE TITLE
Got Forbidden (403) when `kubectl proxy` a newly created GCP cluster

### ISSUE THREAD

**Issue by duzy** [kubernetes/dashboard#2122]
##### Steps to reproduce

1. Create a GCP cluster (selected the latest 1.7 kubernates)
2. Do `gcloud container clusters get-credentials`, it runs well.
3. Do `kubectl proxy`
4. Open http://localhost:8001/ui

##### Environment
```
Installation method: gcloud install kubectl
Kubernetes version: 1.7
Dashboard version: 1.7
Commit: 
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list nodes at the cluster scope.: "Unknown user \"system:serviceaccount:kube-system:default\"" (get nodes)

```

##### Comments
Just created a new cluster on Google Cloud Platform, then do the guided "connect" steps. Note that I didn't change any IAM permissions.

**Comment by floreks** [comment]
`Dashboard version: 1.7` is not possible since latest version is `1.6.1`. I don't know how GCP provisions the cluster but probably they deploy some older version of dashboard. Follow our [README.md](https://github.com/kubernetes/dashboard#deployment) to deploy dashboard.

**Comment by duzy** [comment]
Thanks @floreks for the information. I'm now using the command line interfaces, got lucky because command line is working for me. I also posted this bug to Google, I'll get back here after they replied.

**Comment by duzy** [comment]
@floreks Well, Google returned to me, it turns out it was about it's "legacy authorization" being off on the cluster creation. I'm getting used to the cli now. Thanks for all the information from @floreks  and Google support.
