### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2123]
https://github.com/kubernetes/dashboard/blob/master/docs/devel/release.md

**Comment by bryk** [comment]
I guess it is on me or Rob to push, right?

**Comment by maciaszczykm** [comment]
@bryk Yes, we can't do it.

**Comment by maciaszczykm** [comment]
@bryk @rf232 Could you merge pull request with version 1.6.2 and create image?

**Comment by maciaszczykm** [comment]
@bryk @rf232 https://github.com/kubernetes/dashboard/tags Can you remove `1.6.2` tag and leave `v.1.6.2`?

**Comment by maciaszczykm** [comment]
We will wait with announcing it and creating PRs for related repos because of issue with metrics.

**Comment by floreks** [comment]
We have to remember to remove heapster workaround from yaml file before the release.
