### ISSUE TITLE
Migrate kubernetes/kubernetes SIG-UI tests to a separate folder

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#2128]
E2e tests in kubernetes/kubernetes repository need to have explicit owners. We should move our [dashboard.go](https://github.com/kubernetes/kubernetes/blob/a14abaabab2b385994c20129ba95cf89a97d01f1/test/e2e/dashboard.go) test to a separate folder.

This is instruction from Garrett:
1. That test moves to test/e2e/storage
2. The test names start with sig-ui (using a package level function called SigDescribe).  See this example: https://github.com/kubernetes/kubernetes/pull/48781/files
3.  You setup a sig-ui dashboard in testgrid.  See this example: https://github.com/kubernetes/test-infra/pull/3469

**Comment by cheld** [comment]
Thanks for pointing out. Is there a deadline?

**Comment by maciaszczykm** [comment]
It will be tracked from #2395.

**Comment by maciaszczykm** [comment]
Looks like this is already removed: https://github.com/kubernetes/test-infra/commit/7942ba3c89511bfb1a63418a4dc2d11a858821ae

**Comment by floreks** [comment]
It was recently updated from what I see: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/ui

/close
