### ISSUE TITLE
Show endpoints

### ISSUE THREAD

**Issue by ffahri** [kubernetes/dashboard#2131]
dashboard wont show endpoints
it can be seen by kubectl
$ kubectl get endpoints

**Comment by floreks** [comment]
@kenan435 is already working on service detail view to show available information in a more user friendly way.

**Comment by maciaszczykm** [comment]
Done in #2150. Endpoints are listed on service details page:

![image](https://user-images.githubusercontent.com/2823399/28783619-2cff368c-7611-11e7-9cd2-a7efcd7bf54a.png)

To check it out use development image or wait for official release.
