### ISSUE TITLE
Unable to access K8s dashboard

### ISSUE THREAD

**Issue by mfb2** [kubernetes/dashboard#2133]
##### Steps to reproduce

1.  Created a new Kubernetes cluster via Google Container Engine page in Google Cloud Console
2.  Copied and executed the statements provided from the "Connect" button next to the newly created cluster on the Container Engine page
3.  Attempted to access dashboard and received this error message

Executing `helm list` also produces this result.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default".: "Unknown user \"system:serviceaccount:kube-system:default\"" (get replicationcontrollers)

```

**Comment by floreks** [comment]
> Executing helm list also produces this result.

This is obviously a cluster issue not dashboard. Neither dashboard nor helm have access to the cluster resources. Read how to configure RBACs and grant privileges for resources in your cluster or follow our README to deploy dashboard with admin privileges.
