### ISSUE TITLE
Move exec button to actionbar?

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2143]
We can use dropdown menu to list available containers on hover.

Similar to #2138.

**Comment by cheld** [comment]
I would tend to move exec into the action bar, in order to make it more prominent. But, I am not sure about UX. Should it be touch friendly? Should it be consistent with logs? Extra dialog?

**Comment by floreks** [comment]
I think that we can simply make it act same as logs page button. Choose the first container on the pod and open console for it. There is a combobox on exec page to choose other container if user wants to.
