### ISSUE TITLE
Dashboard reported Unknown Server Error (500)

### ISSUE THREAD

**Issue by abhijit201** [kubernetes/dashboard#2147]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Unknown Server Error (500):
```
pods "flcore-3044258048-mb1z3" not found

```

**Comment by cheld** [comment]
Pod `flcore-3044258048-mb1z3` was concurrently deleted.

Can we remove the `send feedback` button in such a case? Also we should make it look less like an error. Might be a bit tricky because we have no error codes.

**Comment by floreks** [comment]
We can check `404` code for object not found error and implement new behavior for that. I have created issue for that #2149.

**Comment by cheld** [comment]
BTW: in this case it was `Dashboard reported Unknown Server Error (500)`

**Comment by floreks** [comment]
No. We qualify all errors not handled by us as internal server errors (code 500). Normally kubernetes returns 404 and our backend transforms it.
