### ISSUE TITLE
is it  necessary to replace directly connection with informer(cache) ?

### ISSUE THREAD

**Issue by zouyee** [kubernetes/dashboard#2148]
when my namespace deployed many apps,the workload API  will processing slowly.

**Comment by floreks** [comment]
We will consider adding cache after we deal with top priority issues. For now we have to take care of log in mechanism and improve overall security. Then we will focus on performance. Also having some pagination option directly in apiserver would improve our performance. Right now we have to do that on our side.

**Comment by zouyee** [comment]
would you like to assign  to me the task？

**Comment by floreks** [comment]
You are welcome to do that. We can not assign you on github as only kubernetes team members are visible in assignee list.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
