### ISSUE TITLE
Disable translation

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/dashboard#2154]
##### Environment

```
Dashboard version: v1.6.1
Kubernetes version: v1.7
Operating system: CentOS 7
Dashborad image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1
```

##### Steps to reproduce

```
kubectl create -f https://git.io/kube-dashboard
```

##### Observed result

Some pages are shown in translated characters, while others in English.

##### Expected result

Should be able to switch to English versioned dashboard.

##### Comments

Translations seems not completed now, is there a way to disable translations on dashboard?

**Comment by floreks** [comment]
Translations are based on your browser locale. Change it to english and all pages will be visible in english.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by feiskyer** [comment]
@floreks Thanks.
