### ISSUE TITLE
Cannot display Pod page if `get secrets` is forbidden

### ISSUE THREAD

**Issue by stephanlindauer** [kubernetes/dashboard#2161]
##### Environment

I run the Dashboard as a Deployment behind an Ingress Controller to expose it to people who need to have **read**-access to it. The way I do that, is, that i use a `kubeconfig` file that references the "readonly" user, that I have setup in my API-server policy file.

That user gets to read all the things in a specific namespace **except** the Secrets.
When that User uses the Dashboard he's can't navigate to a Pod Page because that Page `get`s the Secret endpoint which is forbidden.
```
User "readonly" cannot list secrets in the namespace "foobar".: "No policy matched." (get secrets)
```

```
Dashboard version: 1.6.1
Kubernetes version: 1.6.5
Operating system: CoreOS
```

##### Steps to reproduce
Setup `readonly`-User that is forbidden from reading Secrets.

##### Observed result
Navigate to Pod page and see that you get send back to the page you came from.

##### Expected result
See the Pod page.

**Comment by floreks** [comment]
This is already fixed on master and will be available in our next release. Hopefully it will happen next week on Monday, Tuesday.

Authz errors are now displayed as warnings and access to pages is possible without all permissions.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stephanlindauer** [comment]
nice, thanks! :heart:
