### ISSUE TITLE
Links to pods from nodes page redirect when outside of the current namespace

### ISSUE THREAD

**Issue by Firehed** [kubernetes/dashboard#2163]
```
Dashboard version: 1.6.1
Kubernetes version: 1.7.1
```

##### Steps to reproduce
Click `Nodes` in the `Cluster` section of the sidebar
Click on any node in the list
Note the current `namespace` selection in the sidebar
Click any pod within that node's details that is not in the current namespace

##### Observed result
I am redirected back to the list of nodes

##### Expected result
I am taken to that pod's details page

##### Comments
This only happens if pod clicked from the list of pods on the node is outside of the currently-selected namespace. When the clicked pod is in the currently-selected namespace (or all namespaces) is selected, the link works as expected.

**Comment by floreks** [comment]
This is not so obvious how we should handle that. I see 2 options right now.

1. Show only pods on the node matching currently selected namespace
2. Redirect to pod's details page and change selected namespace to the namespace of chosen pod

@bryk @maciaszczykm WDYT?

**Comment by maciaszczykm** [comment]
> Redirect to pod's details page and change selected namespace to the namespace of chosen pod

I would go with this solution. IMO we should list all pods for given node.

**Comment by floreks** [comment]
Closing in favour of #2300.
