### ISSUE TITLE
Replace "gofmt" with "goimports" as a Go formating tool

### ISSUE THREAD

**Issue by kenan435** [kubernetes/dashboard#2171]
goimports does everything that gofmt do. Additionally it groups and corrects imported packages.  Packages from standard library are not mixed with third party packages as is the case with gofmt.

**Comment by maciaszczykm** [comment]
We cannot replace it, because `goimports` manages imports only and it doesn't format code. We have to use `goimports` after `gofmt` finish.

**Comment by kenan435** [comment]
Have a look,

https://godoc.org/golang.org/x/tools/cmd/goimports

_In addition to fixing imports, goimports also formats your code in the same style as gofmt so it can be used as a replacement for your editor's gofmt-on-save hook._

**Comment by maciaszczykm** [comment]
@kenan435 Well, you are right :-)
