### ISSUE TITLE
Show object filter input by default

### ISSUE THREAD

**Issue by cnwalker** [kubernetes/dashboard#2175]
Currently when you encounter a resource list in the dashboard the "filter by objects by name" input is hidden by default until the user clicks on an icon. I wasn't aware this was possible until I accidentally clicked on the icon and now use this feature frequently. Perhaps we should show the input field by default?

<img width="232" alt="screen shot 2017-07-24 at 3 48 06 pm" src="https://user-images.githubusercontent.com/8570077/28548190-7504698c-7087-11e7-950d-45c04edbcee4.png">

**Comment by floreks** [comment]
@danielromlein WDYT? 

I think current behavior is suggested by material design guidelines that we are trying to follow.

**Comment by cnwalker** [comment]
Another idea, maybe it would be better to have a magnifying glass on the right hand side of each resource list like in the upper right hand corner of the material design homepage (https://material.io/guidelines/).

**Comment by floreks** [comment]
Magnifying glass icon is good for search functionality. On the list level we are only filtering out items not actually searching.

https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards

**Comment by cnwalker** [comment]
Right, I think the existing icon is depicting starting with a lot of elements and then whittling them down. However my concern is that without having seen that icon before it is difficult to know you can filter.

I showed this to some people who had lightly used the dashboard before and asked them to "filter and/or search the pods without the big bar at the top" and they looked at the screen for a few minutes before giving up. With search input visible by default or a magnifying glass, it might be easier to know that filtering resources is possible.

**Comment by maciaszczykm** [comment]
I get @cnwalker point here. We decided to follow Material Design, because we are not UX experts and it gives us pretty good set of guidelines. However, we may break our rules here...

@danielromlein Can you tell us what do you think?

**Comment by maciaszczykm** [comment]
We will follow Material Design here.
