### ISSUE TITLE
Should use ordered termination when deleting StatefulSets

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/dashboard#2176]
Dashboard deletes a StatefulSet from the API, make its pods GC'ed by the server at the same time.  This is not desirable behavior for an application that relies on ordered termination.

`kubectl delete statefulset` scales the statefulset down to 0 first, which is an ordered termination. 

@bryk @kow3ns @foxish @erictune

**Comment by floreks** [comment]
Thanks for information. We''ll fix that.

**Comment by bryk** [comment]
@janetkuo Should it be implemented in the UI codebase? I'm not sure. If that's behavior users expect, this should be part of spec and be in the API server. Otherwise, this is implementation detail of kubectl and none of other clients will follow it. Think of, e.g., openshift console, GKE UI or any other client.

**Comment by bryk** [comment]
@mhenc

**Comment by floreks** [comment]
I guess behavior here is somehow similar for Jobs as they are not picked up by GC at all and we have to find and delete the Job pods manually. In both scenarios there is some additional logic required to handle correct deletion.

**Comment by bryk** [comment]
But for stateful set the pods are picked. 

And anyway, implementing such logic is kubectl should not be the way to go. Look at kubectl rolling-update for replication controllers. Its been moved to the server as virtually everyone agreed that it should not be done in kubectl.

**Comment by floreks** [comment]
I agree that it should be handled on the server side and not by clients. Even documentation does not say how custom client should handle specific actions. Do you think that we should not merge #2081 then and wait for kubernetes to fix such cases on their side?

**Comment by floreks** [comment]
@bryk WDYT about #2081? Should we push it forward or wait for core to handle it?
