### ISSUE TITLE
Dashboard reported Unknown Server Error (500)

### ISSUE THREAD

**Issue by nallagonda** [kubernetes/dashboard#2188]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Unknown Server Error (500):
```
replicasets "data-upload-service-223565254" not found

```

**Comment by floreks** [comment]
This is not a bug. Object was conccurently deleted.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
