### ISSUE TITLE
On Kubernetes 1.5.2 the Cluster view is not working

### ISSUE THREAD

**Issue by cfontes** [kubernetes/dashboard#2196]
##### Steps to reproduce

When I click on the link for cluster I get this 404

##### Environment
```
Installation method: official deployment 
Kubernetes version: v1.5.2
Dashboard version: v1.6.2
Commit: b7669ed2081e7b444f8db000704bd7d7f61395b3
```

##### Observed result
Dashboard reported Not Found (404):
```
the server could not find the requested resource

```

**Comment by maciaszczykm** [comment]
@cfontes Can you pase logs from Dashboard container?

**Comment by floreks** [comment]
For `1.5.X` cluster you should user `1.5.X` dashboard version. Kubernetes changes from version to version and we also have to adapt to it. We always make sure that dashboard is compatible with equal or higher kubernetes version.

**Comment by maciaszczykm** [comment]
Most probably it is caused by Storage Classes... Anyways, we will not fix it.

**Comment by cfontes** [comment]
Yeah I thought so....

Don't worry about it.
