### ISSUE TITLE
Dashboard reported Internal Server Error (500) listing nodes

### ISSUE THREAD

**Issue by shinji** [kubernetes/dashboard#2199]
##### Environment
```
Kubernetes version: 1.5.2
Operating system: RHEL 7.3
Docker version: 1.12.6
Heapster version: 1.4.0
Dashboard version: v1.6.2
Commit: 6d8abef02d7efc9c57a157135237a8c69a3da2ac
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
���	n��ԗQ��0�ߑ��/���EU/RU����"�����+��.��o~��ߌ�q~Fަ�� �a�$����ZD�I�
~-�%�֡@�@ka�����|��B@���Ek�C�#E|�6�E]�Eo}�(�3�
"i��6��~+gVU�U�>�ݭ8�húZ6���uFm�lo`�6H#�MPd�`7�F�z�4����)tp��p�����[�����	to���e)_�W�<����=�b4?ֹ�LI�0�D�(V{�|�	f��ɞ��t�빞dS>˓��q�WS����߻Ny�#��iy���=�Sv���W>�j��أ7�.c�ջ-���4�@��z���ԡ}������hjJ�S�o�������P�g��J����[��T�&ڗcr������y?a���L���:�"��[e-s�q��\ȩ�'��&70�{�"��r�M�[)�+'�j>�������qjk��
```

```
STDERR:
[2017-07-27T16:21:47Z] Outcoming response to 10.10.15.0:55782 with 200 status code
[2017-07-27T16:21:49Z] Incoming HTTP/1.1 GET /api/v1/node?filterBy=&itemsPerPage=15&namespace=&page=1&sortBy=d,creationTimestamp request from 10.10.15.0:55782: {}
[restful] 2017/07/27 16:21:49 log.go:26: [restful] recover from panic situation: - runtime error: index out of range
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/asm_amd64.s:479
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/panic.go:458
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/panic.go:27
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster/client.go:112
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster/client.go:75
    <autogenerated>:8
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:158
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:186
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:281
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/node/list.go:84
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/node/list.go:72
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:799
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/apihandler.go:441
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:267
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:21
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/filter.go:106
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/filter.go:79
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/handler/filter.go:43
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/filter.go:19
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:269
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:120
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:1726
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:2022
    /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:287
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:2022
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:2202
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/net/http/server.go:1579
    /home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/asm_amd64.s:2086
```

**Comment by shinji** [comment]
In "Cluster" option:

panic: runtime error: index out of range

goroutine 119 [running]:
panic(0x1c6c980, 0xc420014060)
	/home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster.heapsterClient.downloadMetric(0x2cc7e60, 0xc4201dd540, 0xc420165080, 0x15, 0x15, 0xc4205bc040, 0x1, 0x1, 0xc4207ce6f0, 0x1ea1861, ...)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster/client.go:112 +0x60b
github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster.heapsterClient.DownloadMetric(0x2cc7e60, 0xc4201dd540, 0xc42088a600, 0x15, 0x15, 0x1ea1861, 0xe, 0x2d3ef20, 0x1d77be0, 0xc42000fef0, ...)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster/client.go:75 +0x11c
github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster.(*heapsterClient).DownloadMetric(0xc4201dd550, 0xc42088a600, 0x15, 0x15, 0x1ea1861, 0xe, 0x2d3ef20, 0xffffffffffffffff, 0xc42094cca0, 0x0)
	<autogenerated>:8 +0xa7
github.com/kubernetes/dashboard/src/app/backend/resource/dataselect.(*DataSelector).getMetrics(0xc4208553d0, 0x2cdae40, 0xc4201dd550, 0x0, 0xf, 0xd, 0xe, 0xc420855320)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:158 +0x2df
github.com/kubernetes/dashboard/src/app/backend/resource/dataselect.(*DataSelector).GetCumulativeMetrics(0xc4208553d0, 0x2cdae40, 0xc4201dd550, 0xc42024cb06)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:186 +0x5d
github.com/kubernetes/dashboard/src/app/backend/resource/dataselect.GenericDataSelectWithFilterAndMetrics(0xc42009c9a0, 0x15, 0x15, 0xc420397d60, 0x2d3ef20, 0x2cdae40, 0xc4201dd550, 0x0, 0x0, 0x0, ...)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/dataselect/dataselect.go:281 +0xe5
github.com/kubernetes/dashboard/src/app/backend/resource/node.toNodeList(0x2ce42c0, 0xc42068d9a0, 0xc42092e000, 0x15, 0x20, 0x2d61780, 0x0, 0x0, 0xc420397d60, 0x2cdae40, ...)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/node/list.go:84 +0x1e1
github.com/kubernetes/dashboard/src/app/backend/resource/node.GetNodeListFromChannels(0x2ce42c0, 0xc42068d9a0, 0xc420641ba0, 0xc420397d60, 0x2cdae40, 0xc4201dd550, 0x0, 0x6e98fb, 0x45aa41)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/node/list.go:60 +0x15e
github.com/kubernetes/dashboard/src/app/backend/resource/cluster.GetClusterFromChannels.func2(0xc42068d9a0, 0xc420641ba0, 0xc420397740, 0x2cdae40, 0xc4201dd550, 0xc42051c8a0, 0xc42051c960)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/cluster/cluster.go:82 +0x129
created by github.com/kubernetes/dashboard/src/app/backend/resource/cluster.GetClusterFromChannels
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/cluster/cluster.go:85 +0x1b7

**Comment by floreks** [comment]
We do not guarantee that latest dashboard will work with kubernetes 1.5 and lower. We always aim to make it compatible with same major k8s version as dashboard version. `v1.6.2` should work with k8s `1.6` and `1.7`.

Try upgrading k8s version. If error still occurs you can reopen it.
