### ISSUE TITLE
Google container engine v1.7.1 Dashboard error

### ISSUE THREAD

**Issue by EugeneAditazz** [kubernetes/dashboard#2201]
##### Steps to reproduce

Deployed the cluster using the gcloud, Installed the kubernetes credentials using 'gcloud container clusters get-credentials ...' started the kubectl proxy, connected to the port and got the following error.
All of the kubectl commands work fine. 

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: kubernetes-dashboard-1265873680
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default".: "Unknown user \"system:serviceaccount:kube-system:default\"" (get replicationcontrollers)

```

**Comment by floreks** [comment]
GCP deploys older version of dashboard with minimal privileges. Deploy new version using command from our readme. 

Note that it might be insecure to deploy dashboard with full admin privileges if cluster is used by many users with different set for of privileges. You should pass `Authorization: Bearer <token>` header to dashboard to maintain security and authorize users.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
