### ISSUE TITLE
Update Dashboard version on core & minikube

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2208]

**Comment by zouyee** [comment]
[minikube](https://github.com/kubernetes/minikube/pull/1773)
[kubernetes](https://github.com/kubernetes/kubernetes/pull/49855)

**Comment by maciaszczykm** [comment]
@zouyee Let us know when it will be done.

**Comment by zouyee** [comment]
👌

**Comment by zouyee** [comment]
it is time to close this issue, which has beed updated
