### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by furbaez** [kubernetes/dashboard#2210]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.2
Commit: b7669ed2081e7b444f8db000704bd7d7f61395b3
```

##### Observed result
Dashboard reported Not Found (404):
```
the server could not find the requested resource

```

**Comment by floreks** [comment]
Concurrent deletion. Not an issue.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
