### ISSUE TITLE
Dashboard 1.6.2/3 listening to port 8443

### ISSUE THREAD

**Issue by gondor** [kubernetes/dashboard#2212]
I've tried everything to get a successful dashboard implementation working on Kubernetes.  I'm new to K8s so may be doing something completely wrong.  I've tested setting up a new cluster on `1.7.2` with `kubeadm init` , joining nodes and then adding the dashboard in a Rackspace cloud environment.

I'm installing using `kubectl create -f https://git.io/kube-dashboard`.  

I've also tried installing a cluster with `kubespray` on rackspace.   Everything is successful but the dashboard won't work on there either.   

My current thoughts are it's trying to listen to port `8443` but the `yml` files are trying to map `9090`.

##### Output from the running dashboard container
```
Using HTTP port: 8443
Creating API server client for https://10.233.0.1:443
Successful initial request to the apiserver, version: v1.6.7+coreos.0
Creating in-cluster Heapster client
Using service account token for csrf signing
```

##### Environment

```
Dashboard version: 1.6.3
Kubernetes version: 1.6.7
Operating system: Ubuntu 16.04
Node.js version:
Go version:
```

**Comment by gondor** [comment]
Issue resolved, thanks

**Comment by floreks** [comment]
Glad to hear. What was the issue here?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gondor** [comment]
I downloaded the remote yaml from the `git.io/kube-dashboard` and added `--insecure-bind-address=0.0.0.0` as an argument.  It then worked instantly.

**Comment by floreks** [comment]
You mean as an argument to our dashboard container? If so then this is very weird as we already do have this in our Dockerfile used for building images.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
