### ISSUE TITLE
Add link to switch namespace in the list view

### ISSUE THREAD

**Issue by cnwalker** [kubernetes/dashboard#2214]
Since the overview page is supposed to describe a namespace, I think it would make sense to have some of the information on the namespace itself like that found in the namespace detail page there. Particularly events and annotations.

**Comment by floreks** [comment]
IMO overview page is not only for a single namespace but also for all namespace (cluster-wide). We should keep it as an overview of high level resources. Events are usually related to details and this is more of a cluster level get than describe (comparing to kubectl).

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cnwalker** [comment]
That's a good point about "All namespaces". Part of the reason this would be useful is that you currently have to actively look for some namespace info that changes relatively frequently like "last applied configuration". 

What do you think of showing only the details on the overview page (no events) and hiding the details when "All namespaces" is selected.

**Comment by floreks** [comment]
What do you mean by?

> showing only the details on the overview page

**Comment by cnwalker** [comment]
The information in the "details" card when you click on a namespace in the cluster resources.

**Comment by cnwalker** [comment]
Part of the reason I think this might be useful is because it is currently a little cumbersome to switch between namespaces with the dropdown on the left hand side. But there is already a good way to find namespaces in the `namespaces` tab of the cluster resources.

If users could get to the namespace overview page by clicking on a namespace in the list under the cluster resources, it might alleviate that problem.

**Comment by floreks** [comment]
You'd like to add some link to the overview page on namespace detail page?

**Comment by cnwalker** [comment]
Exactly, or even giving the user a way to get to the overview page from the list view.

**Comment by cnwalker** [comment]
Actually a better solution might be to replace the current dropdown with something like https://material.angularjs.org/latest/demo/autocomplete

**Comment by floreks** [comment]
Link from namespace to an Overview page is fine for me but I'd not change current namespace selector behavior. We have quite custom design for it and IMO autocomplete with `All namespaces` and `default`, `kube-system` options on the same level could be misleading. Right now it's clear that you have all namespace option or you have to choose single namespace under `Namespaces` label. You can also type name of namepsace to quickly find it if the list is long.

@maciaszczykm WDYT?

**Comment by maciaszczykm** [comment]
@floreks I agree in general, I think current one matches our needs.

**Comment by maciaszczykm** [comment]
>You'd like to add some link to the overview page on namespace detail page?

@cnwalker Could you take care of it?




@cnwalker

**Comment by cnwalker** [comment]
Missed this somehow, will update it ASAP @maciaszczykm

**Comment by maciaszczykm** [comment]
@cnwalker Hi, any progress here?

**Comment by cnwalker** [comment]
Hey! Sorry I intended to submit something recently but was out of town last week and forgot. I will push the PR soon!
