### ISSUE TITLE
kubernetes_v1.6.1 dashboard error

### ISSUE THREAD

**Issue by limited1010** [kubernetes/dashboard#2216]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list ingresses.extensions at the cluster scope. (get ingresses.extensions)

```

**Comment by floreks** [comment]
`User "system:serviceaccount:kube-system:default" cannot list ingresses.extensions at the cluster scope. (get ingresses.extensions)`

Default SA is unauthorized to access the ingress resource.
