### ISSUE TITLE
Include high level architecture and overview of components in docs

### ISSUE THREAD

**Issue by cnwalker** [kubernetes/dashboard#2218]
When I was working on my first PR for the dashboard it took me a good amount of time to get a high level understanding of how the dashboard is structured. 

Even when I thought I understood a system built into the dashboard, I couldn't be 100% certain because there were many files and functions I had never closely evaluated.

In my limited open source experience it is common to not have documentation on the general architecture/code structure of a project, but it would have been helpful for me and might be helpful for others interested in contributing. 

Do we have some docs like these somewhere that I missed? If not, I am willing to write them, provided that people are willing to correct me where I go wrong.

**Comment by maciaszczykm** [comment]
@cnwalker We have some docs at:
https://github.com/kubernetes/dashboard/tree/master/docs

However, we are missing such a document. You can propose something, just read what we have before.

**Comment by cnwalker** [comment]
Awesome! I'll submit a PR with what I have and we can iterate there.
