### ISSUE TITLE
will the dashboard add image management?

### ISSUE THREAD

**Issue by davidstack** [kubernetes/dashboard#2225]
kubernetes need container image, does the dashboard have the roadmap to add image management?

**Comment by floreks** [comment]
I'm not sure I understand your request. Could you tell us a bit more about that?

**Comment by maciaszczykm** [comment]
Is this about adding/improving Container resource management?

**Comment by davidstack** [comment]
@floreks  @maciaszczykm  i am sorry for  my unclear expression. i mean,will the dashboard add the docker registry management (just as the docker hub)

**Comment by floreks** [comment]
What feature exactly do you have in mind? IMO only integration with docker registry we could provide would be autocomplete option when typing image name in create form. Is there something that kubectl provides and dashboard doesn't regarding docker registry management?

**Comment by davidstack** [comment]
most companies will use their private docker registry, should the dashboard add a menu to display the images in the registry?

**Comment by maciaszczykm** [comment]
We can add only autocomplete for image input, but displaying these images is out of scope for the Dashboard.

**Comment by zouyee** [comment]
image management is out scope

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/issues/2225#issuecomment-319894781 is covered in https://github.com/kubernetes/dashboard/issues/511. Closing.
