### ISSUE TITLE
Paste to pod exec terminal doesn't work on Firefox

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/dashboard#2228]
dashboard version 1.6.3. exec'ing into a pod works. copying text works.

On chrome, paste works too via middle click or ctrl-shift-v.

On firefox 52.1.0 (64-bit) on centos 7.3, both paste methods fail. The data is copied into the X clipboard though, as pasting into other apps works.

**Comment by floreks** [comment]
We are using external `hterm` library to manage exec frontend. It is up to it to guarantee such behavior. @lenartj should know more about it.

**Comment by floreks** [comment]
Closing as we'll track it from #2029.
