### ISSUE TITLE
Unable to access the dashboard

### ISSUE THREAD

**Issue by johnnyb2good** [kubernetes/dashboard#2232]
A Kubernetes cluster was setup in AWS with kubespray using flannel host-gw backend and dashboard was installed by copying the latest yaml file from https://git.io/kube-dashboard.

kubectl get all -n kube-system yields:

--------

NAME                                        READY     STATUS    RESTARTS   AGE
po/flannel-ip-172-16-0-11                   1/1       Running   6          20h
po/flannel-ip-172-16-0-23                   1/1       Running   12         20h
po/flannel-ip-172-16-0-35                   1/1       Running   6          20h
po/flannel-ip-172-16-0-47                   1/1       Running   6          20h
po/flannel-ip-172-16-0-59                   1/1       Running   7          20h
po/flannel-ip-172-16-0-71                   1/1       Running   6          20h
po/flannel-ip-172-16-0-83                   1/1       Running   7          20h
po/flannel-ip-172-16-0-95                   1/1       Running   6          20h
po/kube-apiserver-ip-172-16-0-11            1/1       Running   4          20h
po/kube-controller-manager-ip-172-16-0-11   1/1       Running   4          20h
po/kube-dns-3841192733-3q0gh                3/3       Running   20         20h
po/kube-dns-3841192733-7mgpc                3/3       Running   9          20h
po/kube-proxy-ip-172-16-0-11                1/1       Running   6          20h
po/kube-proxy-ip-172-16-0-23                1/1       Running   12         20h
po/kube-proxy-ip-172-16-0-35                1/1       Running   6          20h
po/kube-proxy-ip-172-16-0-47                1/1       Running   6          20h
po/kube-proxy-ip-172-16-0-59                1/1       Running   7          20h
po/kube-proxy-ip-172-16-0-71                1/1       Running   6          20h
po/kube-proxy-ip-172-16-0-83                1/1       Running   7          20h
po/kube-proxy-ip-172-16-0-95                1/1       Running   6          20h
po/kube-scheduler-ip-172-16-0-11            1/1       Running   4          20h
po/kubedns-autoscaler-1833630871-nqd7f      1/1       Running   4          20h
po/kubernetes-dashboard-2615018832-rqfv8    1/1       Running   0          11m
po/nginx-proxy-ip-172-16-0-23               1/1       Running   12         20h
po/nginx-proxy-ip-172-16-0-35               1/1       Running   6          20h
po/nginx-proxy-ip-172-16-0-47               1/1       Running   6          20h
po/nginx-proxy-ip-172-16-0-59               1/1       Running   7          20h
po/nginx-proxy-ip-172-16-0-71               1/1       Running   6          20h
po/nginx-proxy-ip-172-16-0-83               1/1       Running   7          20h
po/nginx-proxy-ip-172-16-0-95               1/1       Running   6          20h

NAME                       CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
svc/kube-dns               172.17.0.3     <none>        53/UDP,53/TCP   20h
svc/kubernetes-dashboard   172.17.57.52   <none>        80/TCP          11m

NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns               2         2         2            2           20h
deploy/kubedns-autoscaler     1         1         1            1           20h
deploy/kubernetes-dashboard   1         1         1            1           11m

NAME                                 DESIRED   CURRENT   READY     AGE
rs/kube-dns-3841192733               2         2         2         20h
rs/kubedns-autoscaler-1833630871     1         1         1         20h
rs/kubernetes-dashboard-2615018832   1         1         1         11`

--------

Kubectl Proxy is used to allow access to the dashboard from outside the localhost by using:

kubectl proxy --address 172.16.0.11 --port=8001 --accept-hosts='^*$'

But, rather than showing the dashboard, the results are text output of:

paths |  
-- | --
0 | "/api"
1 | "/api/v1"
2 | "/apis"
3 | "/apis/apps"
4 | "/apis/apps/v1beta1"
5 | "/apis/authentication.k8s.io"
6 | "/apis/authentication.k8s.io/v1"
7 | "/apis/authentication.k8s.io/v1beta1"
8 | "/apis/authorization.k8s.io"
9 | "/apis/authorization.k8s.io/v1"
10 | "/apis/authorization.k8s.io/v1beta1"
11 | "/apis/autoscaling"
12 | "/apis/autoscaling/v1"
13 | "/apis/autoscaling/v2alpha1"
14 | "/apis/batch"
15 | "/apis/batch/v1"
16 | "/apis/batch/v2alpha1"
17 | "/apis/certificates.k8s.io"
18 | "/apis/certificates.k8s.io/v1beta1"
19 | "/apis/extensions"
20 | "/apis/extensions/v1beta1"
21 | "/apis/policy"
22 | "/apis/policy/v1beta1"
23 | "/apis/rbac.authorization.k8s.io"
24 | "/apis/rbac.authorization.k8s.io/v1alpha1"
25 | "/apis/rbac.authorization.k8s.io/v1beta1"
26 | "/apis/settings.k8s.io"
27 | "/apis/settings.k8s.io/v1alpha1"
28 | "/apis/storage.k8s.io"
29 | "/apis/storage.k8s.io/v1"
30 | "/apis/storage.k8s.io/v1beta1"
31 | "/healthz"
32 | "/healthz/ping"
33 | "/healthz/poststarthook/bootstrap-controller"
34 | "/healthz/poststarthook/ca-registration"
35 | "/healthz/poststarthook/extensions/third-party-resources"
36 | "/logs"
37 | "/metrics"
38 | "/swaggerapi/"
39 | "/ui/"
40 | "/version"

Doing a "docker logs <docker_ID_for_dashboard_pod>" yields:

--------

Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
Successful initial request to the apiserver, version: v1.6.7+coreos.0
No request provided. Skipping authorization header
Creating in-cluster Heapster client
Could not enable metric client: Health check failed: the server could not find the requested resource (get services heapster). Continuing.

--------

I tried modifying the dashboard.yaml file so that the pod is attached to the master which some people reported in other threads solved this problem, but didn't here.

Any feedback is appreciated.

Thanks,

John

**Comment by floreks** [comment]
Number | Paths
------------ | -------------
... | ...
39 | "/ui/" - this is and endpoint to dashboard

`kubectl proxy` is a proxy to apiserver not directly to dashboard.

**Comment by johnnyb2good** [comment]
Hi @floreks.  I had tried the /ui URL before and it just timed out.  I just tried again and now it works -- no idea what changed.  Looks like  I can close this, thanks!  John

**Comment by floreks** [comment]
Maybe container was creating or just did not started yet. Good that it works now.
