### ISSUE TITLE
received unexpected HTTP status: 502

### ISSUE THREAD

**Issue by markqiu** [kubernetes/dashboard#2235]
##### Environment

install kubernetes by kubeadm on a centos7 system
```
Dashboard version: 
   try to install dashboard by: kubectl create -f https://git.io/kube-dashboard
Kubernetes version:  1.7.0
Operating system: centos 7
Node.js version: none
Go version: none
```

##### Comments

in china, gcr.io is blocked. So I tried to add a proxy to get access. But it reports pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3": rpc error: code = 2 desc = received unexpected HTTP status: 502

kubectl describe results as follow:
Name:           kubernetes-dashboard-3313488171-mtn1c
Namespace:      kube-system
Node:           knode2/10.23.179.70
Start Time:     Fri, 04 Aug 2017 09:40:01 +0800
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=3313488171
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-3313488171","uid":"d4a56f00-78b5-11e7-9...
Status:         Pending
IP:
Created By:     ReplicaSet/kubernetes-dashboard-3313488171
Controlled By:  ReplicaSet/kubernetes-dashboard-3313488171
Containers:
  kubernetes-dashboard:
    Container ID:
    Image:              gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
    Image ID:
    Port:               9090/TCP
    State:              Waiting
      Reason:           ErrImagePull
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-2ztxd (ro)
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  kubernetes-dashboard-token-2ztxd:
    Type:       Secret (a volume populated by a Secret)
    SecretName: kubernetes-dashboard-token-2ztxd
    Optional:   false
QoS Class:      BestEffort
Node-Selectors: <none>
Tolerations:    node-role.kubernetes.io/master:NoSchedule
                node.alpha.kubernetes.io/notReady:NoExecute for 300s
                node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen     LastSeen        Count   From            SubObjectPath                           Type            Reason          Message
  ---------     --------        -----   ----            -------------                           --------        ------          -------
  58m           53m             2       kubelet, knode2 spec.containers{kubernetes-dashboard}   Warning         Failed          Failed to pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3": rpc error: code = 2 desc = Get https://gcr.io/v1/_ping: dial tcp 74.125.203.82:443: i/o timeout
  57m           21m             5       kubelet, knode2 spec.containers{kubernetes-dashboard}   Warning         Failed          Failed to pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3": rpc error: code = 2 desc = Get https://gcr.io/v1/_ping: dial tcp 74.125.204.82:443: i/o timeout
  10m           10m             1       kubelet, knode2 spec.containers{kubernetes-dashboard}   Warning         Failed          Failed to pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3": rpc error: code = 2 desc = Get https://gcr.io/v1/_ping: dial tcp 108.177.97.82:443: i/o timeout
  10m           10m             1       kubelet, knode2 spec.containers{kubernetes-dashboard}   Warning         InspectFailed   Failed to inspect image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3": rpc error: code = 2 desc = Cannot connect to the Docker daemon. Is the docker daemon running on this host?
  1h            8m              30      kubelet, knode2 spec.containers{kubernetes-dashboard}   Normal          BackOff         Back-off pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3"
  1h            1m              19      kubelet, knode2 spec.containers{kubernetes-dashboard}   Normal          Pulling         pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3"
  8m            25s             3       kubelet, knode2 spec.containers{kubernetes-dashboard}   Warning         Failed          Failed to pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3": rpc error: code = 2 desc = received unexpected HTTP status: 502
  1h            2s              1808    kubelet, knode2                                         Normal          SandboxChanged  Pod sandbox changed, it will be killed and re-created.
  1h            1s              1917    kubelet, knode2                                         Warning         FailedSync      Error syncing pod

**Comment by markqiu** [comment]
btw I tried execute: docker pull gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3 on knode2, it just works fine.

**Comment by floreks** [comment]
So what exactly is the problem here? Our official releases go to gcr. If this does not work you can try docker hub and kubernetesdashboarddev. There are also all tagged images signed with commit hash. You'd have to search for correct one.

**Comment by markqiu** [comment]
The problem is solved! thank you very much!
