### ISSUE TITLE
Show cluster name in the dashboard, ideally in header

### ISSUE THREAD

**Issue by rturk** [kubernetes/dashboard#2239]
This is a feature request.

We run multiple clusters and we use the dashboard to maintain our clusters. We have `production` and `staging` clusters so it is quite tricky,  also dangerous, to be certain of the cluster we are connected to when using the dashboard.

Ideally the dashboard will display, in a clear manner, the cluster name so no one will use the dashboard expecting it to be a staging cluster when in fact is a production cluster.

**Comment by zouyee** [comment]
sounds good

**Comment by floreks** [comment]
We'll check if it's possible to check the cluster name. To be honest I'm not sure.

**Comment by cheld** [comment]
Most likely cluster name is a cloup provider feature like GKE.

**Comment by zouyee** [comment]
In my opinion，cluster name was used by dns,which configured with kubelet and kubedns.
<img width="504" alt="2017-08-08 9 31 19" src="https://user-images.githubusercontent.com/5785605/29052408-7aa2d310-7c1c-11e7-9177-27d7c5009a0b.png">

**Comment by floreks** [comment]
This is only a local name supported by kubeconfig to distinguish multiple clusters. This is not something global or supported by API.

**Comment by floreks** [comment]
K8S api does not have any information about "cluster name". `kubectl` config file has concept of naming only to differentiate between multiple local configurations. 

What we could do is to add argument to dashboard, i.e. `name` that would be displayed as a part of page title and maybe near logo. Later we could move it to some settings page.

**Comment by zouyee** [comment]
I think he want to use dashboard as a multi-cluster controller plane.

**Comment by floreks** [comment]
And option I have proposed would work with that. @rturk only wants to distinguish cluster when using dashboard. User only needs to pass additional argument `--name <name>` to dashboard and it would be displayed in frontend.

**Comment by rturk** [comment]
@floreks in addition to this discussion we can also think of a pane with any cluster setup information

**Comment by floreks** [comment]
> pane with any cluster setup information

Could you elaborate on that?

**Comment by maciaszczykm** [comment]
Will be tracked from #2417.
