### ISSUE TITLE
Default Language can not been changed in dashbaord

### ISSUE THREAD

**Issue by PeiKevin** [kubernetes/dashboard#2240]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Default Language has been set up in Chinese, I think this is related to browser or OS environment. 

##### Comments
But how  can I change to English,  is there any setting option ?

**Comment by cheld** [comment]
Dashboard takes the browser locale. Currently, Dashboard is completely statless and has no user authentication, therefore it is not possible to configure anything per user. We could provide a command line flag to force all users to english

**Comment by PeiKevin** [comment]
Great. It will be nice if there is the force flage setting, So many thanks for your support.

**Comment by floreks** [comment]
If you want to enforce language for dashboard just download some browser extensions like `Simple locale switcher` or `Quick language switcher` and when on dashboard page set it to either english/japanese/chinese. 

We will eventually provide some settings page but this is rather low priority for now.

**Comment by maciaszczykm** [comment]
Will be tracked from #2417.

**Comment by XinhaiWang** [comment]
Go to chrome://settings/, and at the Languages section, move your favorite language to the top.
