### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by AliYmn** [kubernetes/dashboard#2245]
Hi,

	>> kubectl get pods --all-namespaces | grep dashboard
	Result ;
	The connection to the server localhost:8080 was refused - did you specify the right host or port?

----

	>> kubectl create -f https://git.io/kube-dashboard

	Result ; 

	The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by floreks** [comment]
Not a dashboard issue. Go to kubernetes core repo.

**Comment by AliYmn** [comment]
OK thanks.
