### ISSUE TITLE
Legacy Auth disabaled and clusterrole-cluster-admin

### ISSUE THREAD

**Issue by bradrhod** [kubernetes/dashboard#2257]
##### Steps to reproduce

1.) in gcloud ui create new cluster
2.) select 1.7.2 (latest version)
3.) set legacy authorization to disabled.
4.) Follow this article to enable RBAC.
5>) install coreOS prometheus operator https://github.com/coreos/prometheus-operator  by running 'kubectl apply -f bundle.yaml' from prometheus-operator.

##### Environment
```
Installation method: Google Cloud UI
Kubernetes version:1.7.2
Dashboard version:
Commit: 
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list jobs.batch in the namespace "default".: "Unknown user \"system:serviceaccount:kube-system:default\"" (get jobs.batch)

```

**Comment by floreks** [comment]
Closing as stale. No dashboard version provided.
