### ISSUE TITLE
Dashboard should not use CreatedByAnnotation

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/dashboard#2261]
Based on this [announcement](https://groups.google.com/forum/#!msg/kubernetes-dev/juMOsdaCml0/FwVNJA9uBAAJ), `CreatedByAnnotation` will be deprecated in 1.8 in favor of `ControllerRef`. However, the annotation is still used in this repo: [here](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/pod/detail.go#L131) and [here](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/pod/detail.go#L204)

There is a necessary change to use `ControllerRef`. Does anyone have bandwidth to work on this?

**Comment by zouyee** [comment]
@maciaszczykm

**Comment by maciaszczykm** [comment]
@crimsonfaith91 Thanks for the information. We migrated most of our backend to use controller references, but this is not finished as you correctly pointed out. We will take care of it before 1.8.

**Comment by maciaszczykm** [comment]
> Does anyone have bandwidth to work on this?

We are currently focused on auth stuff. Are you willing to send pull request for it? Otherwise, we will do it just after that.

**Comment by crimsonfaith91** [comment]
@maciaszczykm Will you work on this? I am happy to review the PR.

**Comment by crimsonfaith91** [comment]
@maciaszczykm I can work on this if needed.

**Comment by maciaszczykm** [comment]
>@maciaszczykm I can work on this if needed.

@crimsonfaith91 Would be great :)

**Comment by crimsonfaith91** [comment]
@maciaszczykm After examining the workload, i think i will let you or someone else who is familiar with the codebase to make the change. It will take some time to learn the codebase before making the change to use `ControllerRef`, but i do not have the bandwidth (it looks like the required changes will be quite different from main `kubernetes/kubernetes` repo).

Will you be fine with this?

**Comment by crimsonfaith91** [comment]
@maciaszczykm I suggest using `ControllerRef` rather than `OwnerReference`. To clarify, `OwnerReference` is the more general feature that `ControllerRef` is built on. A `ControllerRef` is just an `OwnerReference` with the `Controller` field set to true. There can be only one `OwnerReference` that is a `ControllerRef` on a given object.

Some good references:
https://github.com/kubernetes/kubernetes/pull/47469
https://github.com/kubernetes/kubernetes/pull/47471

**Comment by maciaszczykm** [comment]
@crimsonfaith91 Thanks, we will take care of that :+1: Also good to know about `ControllerRef` field I had to miss it somehow.
