### ISSUE TITLE
Websocket auth with multiple replicas

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/dashboard#2272]
##### Environment

```
Dashboard version: 1.6.3
Kubernetes version: 1.7.3
Operating system: (using official docker image)
Node.js version: (using official docker image)
Go version: (using official docker image)
Docker image:  gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
```

##### Steps to reproduce
Run multiple replicas of the dashboard behind a standard service (not behind apiservers).

##### Observed result
If you attempt to use the shell feature, the websockets may fail to connect. The backend will show errors like:
```
handleTerminalSession: can't find session '58b0f210745ff704af190f0d181a5111'
```
I'm guessing this is because one instance of the backend is not aware of sessions created on another instance of the backend.

##### Expected result
I'd expect to be able to run multiple replicas of the dashboard for redundancy. 

##### Comments
I'm curious if there is any workaround that I'm currently missing. It seems like the dashboard makes a standard XHR request to get a terminal session, and then another to open the websocket. Would it be possible to make it skip the XHR request and do everything over the websocket so only one backend is involved?

**Comment by rf232** [comment]
I guess we should update the dashboard service to include some form of session affinity. IIRC it should be as simple as adding `sessionAffinity: "ClientIP"` to the spec of our service. Could you perhaps confirm that for us @PaulFurtado ?

**Comment by floreks** [comment]
Beside that shell feature is still in early stage. We will be working on improving it.

**Comment by cheld** [comment]
@PaulFurtado I curious about your environment. Do you have so many concurrent users that you need multiple replicas?

**Comment by floreks** [comment]
Closing as we'll track it from #2029.

**Comment by abursavich** [comment]
Can we reopen this issue? #2029 seems pretty dead.
