### ISSUE TITLE
Kubernetes dashboard 'crashLoopBackoff' error with code 503 on master ip

### ISSUE THREAD

**Issue by manojRy** [kubernetes/dashboard#2274]
I have created kubernetes cluster with Kops version 1.6.1. My cluster is up and running fine in AWS with one master and 2 worker nodes. I have also configured dashboard with the following four commands

> kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.6.3.yaml

and `kubectl cluster-info` gave me this output

> Kubernetes master is running at https://api.junlin-master.aws.mms-at-work.de
Heapster is running at https://api.junlin-master.aws.mms-at-work.de/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://api.junlin-master.aws.mms-at-work.de/api/v1/namespaces/kube-system/services/kube-dns/proxy
kubernetes-dashboard is running at https://api.junlin-master.aws.mms-at-work.de/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
monitoring-grafana is running at https://api.junlin-master.aws.mms-at-work.de/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
monitoring-influxdb is running at https://api.junlin-master.aws.mms-at-work.de/api/v1/namespaces/kube-system/services/monitoring-influxdb/proxy

also `kubectl get pods -n kube-system -o wide` results as below

> NAME                                                                    READY     STATUS             RESTARTS   AGE       IP             NODE
dns-controller-3641780472-wvfxm                                         1/1       Running            0          41m       172.23.3.124   ip-172-23-3-124.eu-central-1.compute.internal
etcd-server-events-ip-172-23-3-124.eu-central-1.compute.internal        1/1       Running            0          40m       172.23.3.124   ip-172-23-3-124.eu-central-1.compute.internal
etcd-server-ip-172-23-3-124.eu-central-1.compute.internal               1/1       Running            0          41m       172.23.3.124   ip-172-23-3-124.eu-central-1.compute.internal
heapster-1528902802-rc4jq                                               1/1       Running            0          24m       100.96.2.4     ip-172-23-3-115.eu-central-1.compute.internal
kube-apiserver-ip-172-23-3-124.eu-central-1.compute.internal            1/1       Running            0          40m       172.23.3.124   ip-172-23-3-124.eu-central-1.compute.internal
kube-controller-manager-ip-172-23-3-124.eu-central-1.compute.internal   1/1       Running            0          40m       172.23.3.124   ip-172-23-3-124.eu-central-1.compute.internal
kube-dns-1321724180-2fjrr                                               3/3       Running            0          41m       100.96.1.2     ip-172-23-3-114.eu-central-1.compute.internal
kube-dns-1321724180-zrx8m                                               3/3       Running            0          38m       100.96.2.3     ip-172-23-3-115.eu-central-1.compute.internal
kube-dns-autoscaler-265231812-gn3g4                                     1/1       Running            0          41m       100.96.2.2     ip-172-23-3-115.eu-central-1.compute.internal
kube-proxy-ip-172-23-3-114.eu-central-1.compute.internal                1/1       Running            0          39m       172.23.3.114   ip-172-23-3-114.eu-central-1.compute.internal
kube-proxy-ip-172-23-3-115.eu-central-1.compute.internal                1/1       Running            0          39m       172.23.3.115   ip-172-23-3-115.eu-central-1.compute.internal
kube-proxy-ip-172-23-3-124.eu-central-1.compute.internal                1/1       Running            0          40m       172.23.3.124   ip-172-23-3-124.eu-central-1.compute.internal
kube-scheduler-ip-172-23-3-124.eu-central-1.compute.internal            1/1       Running            0          40m       172.23.3.124   ip-172-23-3-124.eu-central-1.compute.internal
kubernetes-dashboard-1322534851-2tjzw                                   0/1       CrashLoopBackOff   11         24m       100.96.2.5     ip-172-23-3-115.eu-central-1.compute.internal
monitoring-grafana-2527507788-v6r8d                                     1/1       Running            0          24m       100.96.1.4     ip-172-23-3-114.eu-central-1.compute.internal
monitoring-influxdb-3480804314-fdv8d                                    1/1       Running            0          24m       100.96.1.3     ip-172-23-3-114.eu-central-1.compute.internal

There is a crashloopbackoff error for the dashboard. i didn't understand why is it running in a different Ip like "100.96.2.5" as it has nothing to do with me because my private address is "172.23.3..124" for master node. Accessing the master node with `https://172.23.3.124/ui` ended up with 
`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}`

and grafana and influxdb gave this output on the webpage
`Error: 'dial tcp 100.96.1.4:3000: getsockopt: connection timed out'
Trying to reach: 'http://100.96.1.4:3000/'`
`Error: 'dial tcp 100.96.1.3:8086: getsockopt: connection timed out'
Trying to reach: 'http://100.96.1.3:8086/'`
I dont think it is a cluster issue as in some git issue they have specified it is the reason. Anyone with a solid explanation what went wrong in this case. Thanks

**Comment by floreks** [comment]
Gives us logs from dashboard `kubectl logs -n kube-system <dashboard_pod>`.

**Comment by manojRy** [comment]
@floreks here are the logs

> Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
Successful initial request to the apiserver, version: v1.6.2
No request provided. Skipping authorization header
Creating in-cluster Heapster client

**Comment by floreks** [comment]
There should be more. I do not see any error here. You can also try `kubectl logs -n kube-system <dashboard_pod> --previous`

**Comment by manojRy** [comment]
<img width="750" alt="error" src="https://user-images.githubusercontent.com/16360625/29356876-f90fc212-8275-11e7-9916-b38e5e9ecbc6.PNG">

**Comment by floreks** [comment]
Probably dashboard, grafana and influx are deployed on a different node. From dashboard logs I do not see any problems. You won't be able to access pod IP directly as this is internal ip accessible only from inside the cluster.

I see that kops yaml for dashboard is customized. Try to remove dashboard and deploy it using `kubectl create -f https://git.io/kube-dashboard`. Probably you also need overlay network to allow pod to pod communication between nodes.

**Comment by manojRy** [comment]
@floreks Thanks it is working now. I have created an overlay network.
I am just referring it here if someone else has this issue 

> kops create cluster \
--cloud=aws 
--zones=eu-central-1a 
--node-size=t2.small 
--master-size=t2.small 
--node-count=2 
--name=gave a name here 
--dns-zone=my DNS name 
--dns private 
--vpc=vpc-xxxxxx
--network-cidr=172.xx.xx.xx/xx 
--networking flannel \
--state=s3://waterinthebucket 
--image ami-xxxxx 
--ssh-public-key=~/keys/id_rsa.pub

> kubectl create -f https://git.io/kube-dashboard
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml

`kubectl proxy`
to access the dashboard https://<masterip>/ui
I am closing the issue.
