### ISSUE TITLE
Request logging on the backend

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#228]
I'll add logging for requests coming to the backend.

**Comment by maciaszczykm** [comment]
@bryk @cheld @floreks @zreigz I am thinking about architecture of this implementation and it would be great if you would have any suggestions. Currently I can see two ways how it could be implemented:

- We're using [emicklei/go-restful](https://github.com/emicklei/go-restful) to provide restful webservices, and we can try to use logging provided by it. It needs to be configured in the way, that we want (still not sure about it, what do we need in logs?).
- We can log every request from `apihandler.go` file. It would be easier to configure and messages could be more specific, but it won't be as generic as first solution.

Do you have any tips? Maybe you can see another solution?

**Comment by floreks** [comment]
I think it would be good to use what `go-restful` provides. We can define for every web service different log function or common for every ws. This example shows it pretty good.

https://github.com/emicklei/go-restful/blob/master/examples/restful-NCSA-logging.go

Only thing to establish is whether we need to log differently every WS or use commong log formatting for all.

**Comment by bryk** [comment]
We should have two layers of logging. One generic, which basically logs all HTTP requests, without knowing what they do. This is actually very useful for debugging. It can show method, URI, cookies or headers. The other specific to api methods, which would help in debugging, like `log.info('creating replica set %#v', foo)`.

**Comment by cheld** [comment]
I cannot help much as I have briefly looked in the backend code yet.

In Java I would recommend not to mix logs during concurrent rest calls and add some kind of session information to each log. So logs are clean and can easily be filtered for a specific session or specific action. 
But, in our case everything different so just ignore my comment :)
