### ISSUE TITLE
Redirect to overview after successful deployment instead of going to previous state

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2281]
When going back from deploy from file view users will always end up on deploy app view. This is not expected. It would be better to redirect them to overview page to show them if the resource was actually deployed.

@floreks @cheld thoughts?

**Comment by cnwalker** [comment]
I'd be interested in doing this!

**Comment by cheld** [comment]
I tried to reproduce. Actually, I ended up on overview page most of the times. Only one time I stayed on deploy page. I think it depends on usage of namespace selector.

Current behavior is certainly a bug. The following page should either be the previous page (e.g. pod list) or overview page. Both is reasonable.

**Comment by cheld** [comment]
@cnwalker go for it, thanks
