### ISSUE TITLE
See full Image name in Overview

### ISSUE THREAD

**Issue by Globegitter** [kubernetes/dashboard#2286]
##### Environment

```
Dashboard version: 1.6.3
Kubernetes version: 1.7.3
Operating system:
Node.js version:
Go version:
```
I am running this yaml file: https://github.com/kubernetes/kops/blob/fd6eb881b4a1901b5171ce07966c67f2b1fbda16/addons/kubernetes-dashboard/v1.6.3.yaml

##### Steps to reproduce

Launch a deployment with an image that has a very long name

##### Observed result

Name on overview dashboard gets cut off and not possible to see the full name.

##### Expected result

Some ability to see the full name, e.g. by hovering over it, to easily see what version is deployed

##### Comments

This is how it looks for basically all of our deplyoments:

![image](https://user-images.githubusercontent.com/2580254/29449545-7366e0c8-83fb-11e7-81e7-97eae8ec8aa3.png)

**Comment by cheld** [comment]
Fundamentally, we have two options:
1. find a better presentation. Make it expandable somehow. (Maybe hover or Inbox style or something else.)
2. Remove information that is not absolutely required. It would be interessting to have some guidance from users which infromation they use and which information is obsolete.

**Comment by Globegitter** [comment]
Both are valid arguments - I like having this information in the overview to quickly check what image version this is using - maybe there is another option to have this customizable to users? But maybe that also just adds unnecessary bloat.

Not sure what the best solution here is but if the information does stay it would definitely be great to have  something along the lines of 1. what you mentioned.

**Comment by cheld** [comment]
Customization is a good point. We can do so after we implemented a settings page. Currently, Dashboard is completely stateless.

So, you are actually interessted in the versions. This makes sense. (Of course, the versions require the image name)

**Comment by imkmf** [comment]
Hi all! I'd like to get started contributing to the k8s dashboard and this ticket stood out to me today–would y'all be amenable if I fixed this via CSS? Modifying the text class `white-space` property on `hover` looks like this, locally:

![out](https://user-images.githubusercontent.com/922353/30399993-5f3fc60c-988a-11e7-8c5c-cf00afdc5d0f.gif)

**Comment by maciaszczykm** [comment]
@imkmf I think there could be overlays if there is less space vertically. Also, this could cause a lot of flickering.

**Comment by floreks** [comment]
There is already PR open for this #2330.

**Comment by cheld** [comment]
@imkmf the video is certainly nice. A few comments:
1. we have many resources that are potentially cut. Not only image names. e.g. labels, annotations.... if we apply this everywhere, I could imagine that any mouse movement would cause the layout to jump arround. I assume one would want a longer delay than in the video.
2. In the video the space below the image name is empty. However, a pod may have multiple containers. What happens with the text that is potentially below the image name?
3. Some resources can theoretically get very, very long. Not sure if this approach would work in a scenario where the expanded text is much longer than in the video. Of course, resources with maximum length are rather unlikely, but we should consider
4. It is not mobile compatible

Of course, small improvements are better than no improvements. I tend to believe the best solution would be similar to "Google Inbox": In table view the elements are listed with limited amount of information. A single click on a element does not leave the list view, but vertically expand the selected element. Of course, this is much more work - help is very welcome :)

**Comment by imkmf** [comment]
Really good points @cheld! I'll check out the Google Inbox solution and see if it's feasible to put something together like that.

**Comment by cheld** [comment]
https://github.com/kubernetes/dashboard/issues/2048

**Comment by cheld** [comment]
Solution of codefresh:

https://www.youtube.com/watch?v=mRwSoDSj7BY

**Comment by rahulb3521** [comment]
Hi @maciaszczykm is anybody working on this issue currently, if not can I take this up and try it out

**Comment by maciaszczykm** [comment]
@rahulb3521 Sure, take it.

**Comment by floreks** [comment]
This does not happen anymore as we break image name into multiple lines if there is not enough space.

/close
