### ISSUE TITLE
[Feature Request] Traditional Chinese translation support

### ISSUE THREAD

**Issue by kairen** [kubernetes/dashboard#2297]
Hi all, Have any plans for Chinese traditional translation?

**Comment by maciaszczykm** [comment]
@kairen Are you willing to provide it? I am asking because within our team nobody knows it, so we can rely only on external contributions. If you are willing to help, take a look at https://github.com/kubernetes/dashboard/blob/master/docs/devel/translations.md.

**Comment by kairen** [comment]
@maciaszczykm Yes, I willing to provide this support. The work is in progress, if work is done, I will provide a preview.

**Comment by maciaszczykm** [comment]
@kairen Amazing :+1:
