### ISSUE TITLE
how to get dashboard backend API?

### ISSUE THREAD

**Issue by chunnallu** [kubernetes/dashboard#2299]
I need to make a query like below:
```
http://xxx.xxx.xxx.xxx:9091/api/v1/deployment?name=[kubedns,kubernetes-dashboard]
```
it means that i want the deployments who's name match `kubedns` or `kubernetes-dashboard` , but i don't kown how to make this query and waht params should post to ? can anybody help me ? thanks!

and i think ,may be it is necessary to have a backend API.

**Comment by floreks** [comment]
This is what API server is for. We are building api accessible by frontend and will not provide custom endpoints that frontend will not use.

**Comment by maciaszczykm** [comment]
Like @floreks said. Use `client-go` to connect to Kubernetes API.
