### ISSUE TITLE
Broken links on Nodes view

### ISSUE THREAD

**Issue by aandryashin** [kubernetes/dashboard#2300]
##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
Kubernetes version: Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0"
Operating system: Linux 4.4.0-62-generic
Node.js version: -
Go version: -
```
##### Steps to reproduce
1) Open dashboard in browser
2) Switch namespace selector to 'default'
3) Go to Nodes view
4) Click to any node
5) Scroll down to see pods
6) Click on any system pod (that run in kube-system namespace) 

##### Observed result
Popup with "Unknown Server Error: No error data available"

##### Expected result
Display selected pod info

##### Comments
There is addition parameter in pod url 'namespace=default' causes error, if I change parameter from 'default' to '_all' pod is successfully displayed.

**Comment by floreks** [comment]
I think this was already reported. We have to think how to handle that. Changing selected namespace just by clicking pod in different namespace is not really an option. We might display some dialog informing user that he is about to switch to different namespace. He would need to confirm to change state.

**Comment by aandryashin** [comment]
Another way is to display pods only from selected namespace, in that case all urls will be correct.

**Comment by floreks** [comment]
In this case user also would have to be informed about that somehow. Normally user expects to see all pods that belong to a node . If we'd filter them by namespace selector then we'd need to show some notification. Right now I'm leaning towards first option. @maciaszczykm WDYT?

**Comment by cheld** [comment]
Filtering seems to be problematic. I assume it is hard to understand. An alternative would be to remove the links. But I don't like this. I think notification is best.
