### ISSUE TITLE
Dashboard reported Service Unavailable (503)

### ISSUE THREAD

**Issue by jmveramaiquez** [kubernetes/dashboard#2312]
#### Issue details
This is happening every time I try to see POD logs, and logs are already consumed by the filebeat deamon set.

##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```
##### Observed result
Dashboard reported Service Unavailable (503):
```
No error data available
```

**Comment by floreks** [comment]
Probably container crash. Use kubectl to check what was the reason. If it is `OOMKilled` then increase memory limit for dashboard. Also you did not provide any information about your setup.

**Comment by floreks** [comment]
Closing because of missing details. Reopen after providing more details about environment and issue itself.
