### ISSUE TITLE
Deployments Scaling on dashboard not working when language set to Chinese

### ISSUE THREAD

**Issue by JakimLi** [kubernetes/dashboard#2314]
##### Environment

```
Dashboard version:v1.6.3
Kubernetes version:v1.7.4
Operating system:centos
```

##### Steps to reproduce

Set your browser language to Chinese

##### Observed result

When the dashboard is in Chinese, if you scale for a deployment, nothing happens. Check the log for the dashboard pod gives:
```
[2017-08-28T15:08:25Z] Incoming HTTP/1.1 PUT /api/v1/scale/%!E(MISSING)9%A8%!E(MISSING)7%!B(MISSING)D%!B(MISSING)2/default/my-deployment?scaleBy=1 request from 172.17.40.1:52432: {
  "Content-Type": "application/json"
}
the server could not find the requested resource
```

##### Expected result

scale as expected

**Comment by floreks** [comment]
This is already fixed on master (#2276). Will be available in next release.
