### ISSUE TITLE
How can the dashboard run in the kubernetes master node?

### ISSUE THREAD

**Issue by yisun1900** [kubernetes/dashboard#2319]
I want to figure it out,please give me some references,thank you so much.

**Comment by cheld** [comment]
The k8s feature that's controlls the scheduling is called taints & tollerations 

We added a tolleration to allow scheduling in master in the deployment description

https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml

**Comment by kairen** [comment]
You can use `nodeSelector`, It is the simplest form of constraint.

**Comment by floreks** [comment]
I think it's resolved. Closing.
