### ISSUE TITLE
how to use source map to debug google closure compiler compiled code?

### ISSUE THREAD

**Issue by chunnallu** [kubernetes/dashboard#2321]
run `gulp serve:prod` and report error like below:
```
vendor.b6d65a97.js:33 Error: [$injector:unpr] Unknown provider: aProvider <- a
http://errors.angularjs.org/1.6.6/$injector/unpr?p0=aProvider%20%3C-%20a
    at vendor.b6d65a97.js:31
    at vendor.b6d65a97.js:31
    at Object.i [as get] (vendor.b6d65a97.js:31)
    at vendor.b6d65a97.js:31
    at i (vendor.b6d65a97.js:31)
    at r (vendor.b6d65a97.js:31)
    at Object.a [as invoke] (vendor.b6d65a97.js:31)
    at t (vendor.b6d65a97.js:32)
    at f (vendor.b6d65a97.js:32)
    at vendor.b6d65a97.js:32
```
 i want to debug the closure compiler compiled code to find out the reason , i have try add below option in `script.js`,but not source map at all:
```
let closureCompilerConfig = {
    // ---- BASIC OPTIONS ----
    compilation_level: 'ADVANCED_OPTIMIZATIONS',
    js_output_file: 'app.js',
    language_in: 'ECMASCRIPT6_STRICT',
    language_out: 'ECMASCRIPT5',
    externs: externs,
    
  // i add this line 
   create_source_map:'app.js.map',
```
could anyone tell me how to setup the source map in dashboard `serve:prod` task ? or best tell me what' wrong i make ,hh? thank!

**Comment by floreks** [comment]
I haven't actually ever needed it so I don't know. If you really need it then you have to search for a solution. We have quite complex build pipeline and code is already partially transformed (webpack-stream) before it goes through closure compiler.

**Comment by chunnallu** [comment]
thanks! the error report also give a link `https://docs.angularjs.org/error/$injector/unpr?p0=aProvider%20%3C-%20a` that point out the similar reasons. but now i have add a bit too much code , i can't locate the error ,sadly .

**Comment by chunnallu** [comment]
in the end , i use  add below in `build/script.js`  `closureCompilerConfig`:
```
debug:true,
formatting:'PRETTY_PRINT',
```
it can locate the error too!  see:[Debugging Compiled Code](https://github.com/google/closure-compiler/wiki/Debugging-Compiled-Code)

----

the error report is cause by loose `@ngInject` anotation:
```
         /**
	 * @ngInject
	 */
    constructor($element) {
    }
```
i use jQuery replace angular build in jqlite . don't add `@param {!angular.jqlite} $element` , the type jQuery is unknow , so let is blank would work!
