### ISSUE TITLE
kube-dashboard results in a container that fails to deploy when attempted to use in a stack

### ISSUE THREAD

**Issue by hemanthaSN** [kubernetes/dashboard#2327]
For the Kubernetes 1.7 version, am trying to update the Kubernetes container version(Kube-dashboard:1.6.1)
am able to build successfully but the while testing in MSP the pod status CrashLoopBackOff and it restart every time.

Kubernetes 1.7 supports Kube-dashboard:1.6.1 version or is it a known issue?
please let me know

**Comment by floreks** [comment]
It does work on k8s 1.7. I'm running it without any problems on 1.7.2 cluster. Honestly I'm not sure what exactly you are doing and how you are trying to deploy it. I also don't know what MSP stands for here. You need to provide more details.

**Comment by hemanthaSN** [comment]
Dashboard 1.6.1 crashes frequently on Kube 1.7.3  and the dashboard is not coming up.

**Comment by floreks** [comment]
Latest version is v1.6.3. Update it first.

**Comment by hemanthaSN** [comment]
is there any known issue with dashboard 1.6.1 for the Kube 1.7.3?

**Comment by floreks** [comment]
No there is not, however we do not guarantee that older versions will work correctly with newer core versions. I'm sure that 1.6.3 works fine with k8s 1.7. Only exec into pod is not stable and might cause crashes.

https://github.com/kubernetes/dashboard#compatibility-matrix
