### ISSUE TITLE
Sidebar background bug

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#233]
As you can see on image below, there is a bug with white background (it shouldn't be visible) under labels in sidebar on replica set details view.

![image](https://cloud.githubusercontent.com/assets/2823399/12229504/c56f2d4c-b848-11e5-96cd-dcd1f229a00c.png)

**Comment by bryk** [comment]
@floreks Works on this already.

**Comment by floreks** [comment]
I've created PR #234 with fix.

**Comment by maciaszczykm** [comment]
Okay, then I'm closing it.
