### ISSUE TITLE
Can't create role

### ISSUE THREAD

**Issue by codrut51** [kubernetes/dashboard#2331]
kubectl create role things1 --verb=get --verb=list --verb=watch --resource=pods --resource-name=readablepod
Error from server (Forbidden): roles.rbac.authorization.k8s.io "things1" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], ResourceNames:["readablepod"], APIGroups:[""], Ver
bs:["get"]} PolicyRule{Resources:["pods"], ResourceNames:["readablepod"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], ResourceNames:["readablepod"], APIGroups:[""], Verbs:["watch"]}] us
er=&{codrutsoft13@gmail.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:[
"/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]

**Comment by floreks** [comment]
Not related to dashboard. Kubernetes core repistory is for that.
