### ISSUE TITLE
Customizable Links for Events

### ISSUE THREAD

**Issue by marusak** [kubernetes/dashboard#2332]
#### This is a new feature proposal.
I think that one video explains my idea much clearly than words.

https://www.youtube.com/watch?v=AdcH-3-4Vn0

Some discussion was held on https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kubernetes-sig-ui/gEEE2Ws6Elc

**Comment by floreks** [comment]
Looks promising. I'm not sure however if implementation should be started before we finish [integrations framework](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/integration/api/types.go). Currently it does not offer option to enable/disable integrations so all of them would have to be enabled by default.

**Comment by cheld** [comment]
Very good proposal. There is another feature request to add customizable links to Dashboard:

https://github.com/kubernetes/dashboard/issues/1989

So we should aim for a more generic approach. Not just events. We should try to find a solution that is simple, but also flexible to support linking to many different kinds of applications, e.g. CI, monitoring, etc

**Comment by kenan435** [comment]
@marusak I watched your YouTube video... I am not too familiar with node-problem-detector, but from reading your suggested implementations it requires node-problem-detector and would make the events entries clickable. Is this limited to node level problems only?

**Comment by marusak** [comment]
@kenan435 

The ideal case is that NPD sends exact identifier, so events can refer to exact logs.
However, that is quite some work (mainly in NPD). But when we do not know exact identifier of log message, we still can point into small group of relevant messages and let user to find the correct one, and that is easily doable with setting up url. And as I watched your PR, is seems that this use case would be possible (correct?).

> it requires node-problem-detector

Not really but also yes. It NPD is not available, then no messages comes from it. And if is available, then messages are present. So some condition for event source would be necessary.

> Is this limited to node level problems only?

It can report all problems that are visible from nodes. So if some problem occurs in pod, but is visible from node (such as crashes of c binaries, since kernel is shared), then it gets reported.

**Comment by cheld** [comment]
Is this proposal bound to Cockpit or was ist just an example?

**Comment by marusak** [comment]
It is just an example. Any service which can show logs or even problems would work just as well.
However Cockpit can show problem information in log https://abrt.github.io/abrt/cockpit/2017/06/29/ABRT-in-cockpit/ and NPD can also report problems from ABRT https://abrt.github.io/abrt/kubernetes/node-problem-detector/2017/03/31/kubernetes-npd-adaptation/

**Comment by cheld** [comment]
@marusak I have not Cockpit installed and do not know much about ABRT. Could you please provide a sample URL and if needed explain the params

**Comment by marusak** [comment]
@cheld 
An example URL is http://localhost:9090/system/logs#/?prio=2 . Of course `localhost` would be replaced, but rest would be the same.

`/system/logs#` is page with journal logs

`prio=2` means filter only problems (caught by ABRT)

**Comment by cheld** [comment]
@marusak it seems that something like an event-id or ABRT-id is missing. So in other words, after clicking the link the user must search for the corresponding ABRT issue again, right?

Anyway, could you describe in more technical detail how such an integration could look like. When is Dashboard creating links, how is it extracting the information

**Comment by marusak** [comment]
@cheld Yes, the URL I've provided only points to all problems and user must find the corresponding one. This was only example, how it could work. (And how it could get prepared, while similar work is being done in  #2249)

If we want to have a full integration (which I would love to have), we need `__CURSOR` field from journal. NPD watches journal and when it finds match, then reports this into Kubernetes. So NPD should be able to read `__CURSOR` from log and send it with other data as well. If NPD does not sent this identifier, we can only guess which log message it really comes from.

Then the URL would be something like:
`http://localhost:9090/system/logs#/s=a23191d531794ecb894a017a80eba816%3Bi%3D7791%3Bb%3Ddee980f60bda4838a43d6287e164f6aa%3Bm%3D20472b59f6%3Bt%3D5596f5f515b54%3Bx%3D7f81f2c47fac314d`

The message `__CURSOR` is 
`s=a23191d531794ecb894a017a80eba816;i=7791;b=dee980f60bda4838a43d6287e164f6aa;m=20472b59f6;t=5596f5f515b54;x=7f81f2c47fac314d`

**Comment by floreks** [comment]
As this requires third-party integration and support with the external application we will not integrate it into the core. It would be something that should be handled by plugins once they are in mature enough state to handle it correctly.

/close
