### ISSUE TITLE
Update licenses to 2017

### ISSUE THREAD

**Issue by cnwalker** [kubernetes/dashboard#2337]
There are a number of places that are "copyright 2015" like `src/app/backend/resource/pod/fieldpath.go`. Should these be updated to 2017?

There are also instances where there are multiple licenses in one file like in `src/app/frontend/chrome/nav/module.js`. Are both licenses really correct, or should there only be one?

**Comment by floreks** [comment]
First is excluded as wrotten in comment. This code is copied from core so their license note is applied.

Every file should only have 1 license note. License script had to double them. They have to be manually removed.

**Comment by cnwalker** [comment]
Which license should be removed? I'll try to find as many as I can and submit a PR.

**Comment by floreks** [comment]
Older one.

**Comment by maciaszczykm** [comment]
Copyrights should include files' publication/commit date.

**Comment by floreks** [comment]
So actually all our files should probably include year range `2015-2017`. This would allow us to keep single template for all of them. Normally copyright notice should contain year of creation.

**Comment by cheld** [comment]
In my understanding year of creation is enough
