### ISSUE TITLE
Dashboard reported Unknown Server Error (503)

### ISSUE THREAD

**Issue by carlosmkb** [kubernetes/dashboard#2341]
##### Steps to reproduce
enter in a pod shell, exec some commands and then navigate to _Workloads_ menu

##### Environment
```
Installation method: kops
Kubernetes version: 17.2
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Unknown Server Error (503):
```
No error data available
```

**Comment by floreks** [comment]
This is a known issue and was already reported. Closing.
