### ISSUE TITLE
Binding normal user to read pods only

### ISSUE THREAD

**Issue by codrut51** [kubernetes/dashboard#2345]
I tried binding a normal user to read pods only but it still has access to read deployments and everything. The .yml document that I used is this:
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
name: pod-admin
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: pod-reader
subjects:
   - kind: User
    name: "dcnexttest@gmail.com"
    namespace: kube-system

**Comment by floreks** [comment]
Not related to dashboard. With such issues please go to core repository.
