### ISSUE TITLE
Backspace in shell moves cursor to the right

### ISSUE THREAD

**Issue by vdmkenny** [kubernetes/dashboard#2346]
##### Environment
```
Dashboard version: 1.6.3
Kubernetes version: 1.5.2
Operating system: Centos 7.3
Container: Custom buildroot container, Busybox 1.27.1, Bash 4.4.12
```

##### Steps to reproduce
Go to pods -> choose a pod -> open Shell -> Type a letter, and press backspace in terminal

##### Observed result
The cursor moves to the right instead of the left. The removed letter is still visible, however pressing enter reveals that the letter was in fact removed. This is a graphical glitch.
So: typing lss, pressing backspace will move the cursor to the right, so the line now reads lss[space]. Press enter, and the command "ls" will in fact execute.

##### Expected result
Letters are removed when typing backspace, and the cursor moved left appropriately.

##### Comments
I noticed that it works as expected in programs like `vi`.

**Comment by vdmkenny** [comment]
So turns out the issue lies with the TERM environment variable. When setting TERM=xterm, it works as expected. This may be a sane default to set when a new shell is started through the dashboard.

**Comment by floreks** [comment]
Interesting we'll take a look at it.

**Comment by vdmkenny** [comment]
@floreks All the containers I'm running on this cluster are based on the same container I build from scratch, which have this issue. 
It probably depends on the distro (if any) the container is based on, and what they have set as a value, I haven't encountered it with pre-built containers from dockerhub so far, but I don't use many pre-built ones to begint with. It's probably safe to say that there are others which don't have this env var set by default, and for a shell session in browser, it looks like a safe default to me.

**Comment by maciaszczykm** [comment]
I cannot repoduce it using `busybox` on the current master. During Angular migration we have rewritten almost everything so it might have fixed the issue. Second possibility is that your container is broken and it will work with other containers.

Anyways I am closing it as a non-reproducible.

/close
