### ISSUE TITLE
can not visit dashboard with the master code

### ISSUE THREAD

**Issue by davidstack** [kubernetes/dashboard#2349]
i clone the latest code of dashboard. after i run the command:gulp serve,then visit the dashbor,i find this error.
![image](https://user-images.githubusercontent.com/5036200/30194759-bad0c900-9487-11e7-8136-d01329f5cf7d.png)

**Comment by maciaszczykm** [comment]
I am checking this.

**Comment by maciaszczykm** [comment]
Cannot reproduce. Works just fine on `gulp serve` with newest master and newly installed node deps. Maybe following commands will do the trick for you:

``` sh
rm -rf node_modules
rm -rf bower_components
npm i
```

**Comment by maciaszczykm** [comment]
Also, you did not tell which view crashed.

**Comment by davidstack** [comment]
thanks,i will try
`rm -rf node_modules
rm -rf bower_components
npm i`

**Comment by maciaszczykm** [comment]
@davidstack Did it help?

**Comment by maciaszczykm** [comment]
Closing as stale. Reopen if help is still needed.
