### ISSUE TITLE
error with viewing jobs

### ISSUE THREAD

**Issue by vmarcel** [kubernetes/dashboard#2350]
##### Steps to reproduce

Refresh page while jobs are being spun up

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.0
Commit: bfab10151f012d1acc5dfb1979f3172e2400aa3c
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'ssh: rejected: connect failed (Connection refused)'
Trying to reach: 'http://10.28.0.6:9090/api/v1/job/default?itemsPerPage=10&page=1'```


##### Comments
<!-- If you have any comments or more details, put them here. -->

**Comment by floreks** [comment]
Looks like container crash or proxy rejected the request. 

Closing due to missing details. For sure this is not related to jobs view.
