### ISSUE TITLE
Migrate docs to wiki pages

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2352]

**Comment by cheld** [comment]
Why? You cannot checkout wikipages or create PRs on documentation changes

**Comment by maciaszczykm** [comment]
Wiki pages are stored within a repository, so anybody can check them out:

![zrzut ekranu 2017-09-11 o 20 17 34](https://user-images.githubusercontent.com/2823399/30290010-45e5986a-972e-11e7-8875-cbce8d31e953.png)

However, it may be not possible to make pull requests for them.

I would like to move them because I think they are easier to discover for users. Today, with Sebastian, we have quickly initialized it so you can already check why I think that way. Sidebar menu with all topics is a lot easier to find than going through repository contents:

![zrzut ekranu 2017-09-11 o 20 19 09](https://user-images.githubusercontent.com/2823399/30290164-b70f39c4-972e-11e7-9b56-27a4dd9cbe5f.png)

A lot of projects uses them. Kubernetes core does not need it (still wikis are available) because it has its own page with docs that are easy to find (kubernetes.io). Just check these wikis:

- https://github.com/google/closure-compiler/wiki
- https://github.com/angular/angular.js/wiki

All of these projects have their own generated docs (like kubernetes.io). I think our current `docs` folder looks like "sources" at the moment and is not user-friendly.

**Comment by cheld** [comment]
Ok, can external persons still make doc contributions? How is the workflow?

**Comment by maciaszczykm** [comment]
@cheld Currently it is disabled for our repository because if it would be enabled it would allow any logged in user to edit it. It is a con for us. Perhaps we can keep important files here as origins and use wikis as a user-friendly mirror then?

cc @floreks

**Comment by maciaszczykm** [comment]
A bit of info about wikis: https://help.github.com/articles/about-github-wikis/

**Comment by floreks** [comment]
I also think that wiki pages would be much more convenient for our documentation. We could keep README short and redirect users to our wiki where more detailed description of features could be provided. Currently it is not that easy (even for me) to navigate through our docs and find exactly what I need. Sidebar on wiki pages is really great and user can quickly discover what topics are covered.

As for external contributors I think it's good that only collaborators can edit it currently. Collaborators have best knowledge about the project and in case something is obscure then it can be pointed out in issues as @maciaszczykm mentioned.

**Comment by cheld** [comment]
Hmm..maybe free editing would motivate more contributions. We have all revisions and can compare and revert changes. I guess the idea is like Wikipedia - the more people are involved the better the quality will be

**Comment by maciaszczykm** [comment]
Yes, it is a good idea to encourage people.

**Comment by floreks** [comment]
> I guess the idea is like Wikipedia - the more people are involved the better the quality will be

Yes but on wikipedia text can be first reviewed before it gets published. Here anyone could write whatever he wants and there is no clear way of avoiding that. Also wiki changes do not have any notifications for us so unless someone explicitly sees the changes, they can stay there for quite some time without review. 

IMO documentation should be only changed by collaborators. They have knowledge about the project that allows them to add something meaningful. Strict documentation is not something that should motivate contributions. New contributors should first get familiar with the project, help us with bugs, features, etc. and once they gain collaborator status they can help with documentation.

**Comment by maciaszczykm** [comment]
It is done.
