### ISSUE TITLE
Unable to access Kubernetes 1.7 Dashboard Kubectl Proxy

### ISSUE THREAD

**Issue by pradeepantil** [kubernetes/dashboard#2356]
##### Environment

```
Dashboard version: 1.7
Kubernetes version: 1.7
Operating system: CentOS 7.3
Node.js version:
Go version:
```

##### Steps to reproduce

Hi Folks, 

I am new to Kubernetes, i have installed multi node kubernetes 1.7 with kubeadm on CentOS 7.3. i am successfully able to launch Pods and services. I want to use Kubernetes dashboard, for this i have run the below command on master node

[root@kube-master ~]# kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
[root@kube-master ~]# kubectl proxy
Starting to serve on 127.0.0.1:8001

But when i try to access Dashboard (http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy) i got below error message 

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

##### Observed result

While Accessing Dashboard via http://localhost:8001/ui , getting error message 

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

##### Expected result

Kubernetes Dashboard should be accessible 

##### Comments

[root@kube-master code]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE       IP                NODE
default       webserver-rc-2r6vz                      1/1       Running            0          4h        10.32.0.4         kube-minion2
default       webserver-rc-3f5x5                      1/1       Running            0          3h        10.40.0.2         kube-minion1
default       webserver-rc-4kvzf                      1/1       Running            0          4h        10.40.0.1         kube-minion1
default       webserver-rc-hkb7h                      1/1       Running            0          4h        10.32.0.3         kube-minion2
default       webserver-rc-wzxxb                      1/1       Running            0          4h        10.32.0.2         kube-minion2
kube-system   etcd-kube-master                        1/1       Running            1          5d        169.144.106.187   kube-master
kube-system   kube-apiserver-kube-master              1/1       Running            0          5d        169.144.106.187   kube-master
kube-system   kube-controller-manager-kube-master     1/1       Running            1          5d        169.144.106.187   kube-master
kube-system   kube-dns-2425271678-sb8q6               3/3       Running            0          5d        10.32.0.2         kube-master
kube-system   kube-proxy-bfnh5                        1/1       Running            0          5d        169.144.106.189   kube-minion2
kube-system   kube-proxy-d8hrs                        1/1       Running            0          5d        169.144.106.188   kube-minion1
kube-system   kube-proxy-gm4ps                        1/1       Running            0          5d        169.144.106.187   kube-master
kube-system   kube-scheduler-kube-master              1/1       Running            1          5d        169.144.106.187   kube-master
kube-system   kubernetes-dashboard-3313488171-stssl   0/1       CrashLoopBackOff   45         3h        10.32.0.5         kube-minion2
kube-system   weave-net-j1dmk                         2/2       Running            1          5d        169.144.106.188   kube-minion1
kube-system   weave-net-s7bm1                         2/2       Running            0          5d        169.144.106.187   kube-master
kube-system   weave-net-wg8qv                         2/2       Running            0          5d        169.144.106.189   kube-minion2
[root@kube-master code]#

[root@kube-master code]# kubectl logs kubernetes-dashboard-3313488171-stssl -n kube-system
Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: getsockopt: no route to host
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
[root@kube-master code]#

**Comment by floreks** [comment]
This is a cluster configuration issue. Check already closed issues first. This is not related to dashboard.
