### ISSUE TITLE
Display logs also for init containers

### ISSUE THREAD

**Issue by jagregory** [kubernetes/dashboard#2358]
I'm running 1.6.3 and it's great to see Init Containers appearing in Pods now, excellent progress!

Just raising that it'd really useful to be able to view the Logs of Init Containers. I was surprised to see them not appear in the drop-down of containers within the Logs view.

**Comment by maciaszczykm** [comment]
Thanks for this feature request. Makes sense. We will implement that in upcoming versions.

**Comment by jagregory** [comment]
Thanks @maciaszczykm. I had a look through the code and it seemed reasonably straight forward for a first PR, so I gave it a go: #2359

**Comment by maciaszczykm** [comment]
Done by @kenan435 in #2425.

**Comment by georgecrawford** [comment]
Thanks @kenan435!
