### ISSUE TITLE
I‘d like to add some other functions, how can i do that?

### ISSUE THREAD

**Issue by Edge00** [kubernetes/dashboard#2364]
I want to add authority system to my project, but i am not good at angular, is it possible to do that?
could you give me some advice, Thank you.

**Comment by floreks** [comment]
What do you mean? Do you want to configure Dashboard access control or change code and build your own version of Dashboard?

**Comment by Edge00** [comment]
@floreks yes, i need to rebuild the UI and add some other functions

**Comment by floreks** [comment]
Check out our wiki. We are still adding and improving it, but there are already many useful information to get started. https://github.com/kubernetes/dashboard/wiki

**Comment by Edge00** [comment]
OK, Thank you a lot.
