### ISSUE TITLE
User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list resources in the namespace "default"

### ISSUE THREAD

**Issue by pnpavlov** [kubernetes/dashboard#2369]
##### Environment
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```
Dashboard version: HEAD v1.6.3 (Git Commit 6ffb22e2485f85c418087ac4311b11ed07e66824)
Kubernetes version: v1.7.5
Operating system: Ubuntu 16.04.3 LTS
Node.js version: ?
Go version: go1.8.3
```

##### Steps to reproduce
1. Install Kubernetes via [Installing kubeadm](https://kubernetes.io/docs/setup/independent/install-kubeadm/) guide
    apt-get update
    apt-get install -y kubelet kubeadm docker.io
    kubeadm init --pod-network-cidr=192.168.0.0/16
    kubectl apply -f http://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
    kubectl taint nodes --all node-role.kubernetes.io/master-
2. Install dashboard HEAD, as recommended in [development guide](https://github.com/kubernetes/dashboard/blob/master/docs/devel/head-releases.md)
    kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard-head.yaml

##### Observed result
1. Get dashboard ip 
kubectl get svc --all-namespaces -o wide | grep dashboard
kube-system   kubernetes-dashboard-head   10.110.221.230   <none>        80/TCP,443/TCP   40m       k8s-app=kubernetes-dashboard-head
2. Open http://10.110.221.230/#!/overview?namespace=default

>  User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list configmaps in the namespace "default". (get configmaps)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list persistentvolumeclaims in the namespace "default". (get persistentvolumeclaims)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list secrets in the namespace "default". (get secrets)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list services in the namespace "default". (get services)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list ingresses.extensions in the namespace "default". (get ingresses.extensions)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list daemonsets.extensions in the namespace "default". (get daemonsets.extensions)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list pods in the namespace "default". (get pods)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list events in the namespace "default". (get events)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list deployments.extensions in the namespace "default". (get deployments.extensions)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list replicasets.extensions in the namespace "default". (get replicasets.extensions)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list jobs.batch in the namespace "default". (get jobs.batch)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)
> close
> warning
> User "system:serviceaccount:kube-system:kubernetes-dashboard-head" cannot list statefulsets.apps in the namespace "default". (get statefulsets.apps) 

##### Expected result
As user following the Kubernetes installation and dashboard guides, I expect to have sufficient permissions to use the dashboard. As of now - no view is properly populated due to security problems.

##### Comments
not available

**Comment by floreks** [comment]
As stated in docs. HEAD images might be unstable and are not supposed to be used unless you're up-to-date with latest changes and know how to use them.

**Comment by floreks** [comment]
To get familiar with latest security changes read our [Access Control](https://github.com/kubernetes/dashboard/wiki/Access-control) guide.

**Comment by pnpavlov** [comment]
@floreks  thanks for the wiki! I opened the issue just to share that the "happy path" seems to require further configuration steps. I checked the older issues, where you discussed similar situation for Kubernetes 1.6 release. I understand the point you made also before - the user should configure the security of his cluster. 100% agree, but for dev purposes, it's good to have some starting config. Looking forward to 1.7 ! :)

**Comment by floreks** [comment]
Yaml for the devs (with full access) will be only available on our wiki in form of listing. On repo we will only keep secure setups that will require additional steps to make dashboard fully functional. Everything will be described in README and in our docs.
