### ISSUE TITLE
Latest stable of `kube-dashboard-no-rbac` link broken

### ISSUE THREAD

**Issue by irfanhabib** [kubernetes/dashboard#2370]
The link `https://git.io/kube-dashboard-no-rbac` appears to be broken and results in a 404.

```
15:58 $ kubectl create -f https://git.io/kube-dashboard-no-rbac
error: unable to read URL "https://git.io/kube-dashboard-no-rbac", server reported 404 Not Found, status code=404
```

**Comment by irfanhabib** [comment]
Issue is, the file was removed in this PR https://github.com/kubernetes/dashboard/pull/2363/files.

Going forward will the kubernetes dashboard not support installation into a 1.5.x cluster?

**Comment by floreks** [comment]
We have started preparation for 1.7 release. That is why these files were removed. README will be updated in PR #2366. Pretty much whole documentation will be updated and moved to github wiki pages.
