### ISSUE TITLE
When deleting pod dashboard pod will be gone.

### ISSUE THREAD

**Issue by pgnaleen** [kubernetes/dashboard#2373]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'dial tcp 172.17.0.3:9090: getsockopt: connection refused'
Trying to reach: 'http://172.17.0.3:9090/api/v1/pod/micro-services?filterBy=&itemsPerPage=15&page=1&sortBy=d,creationTimestamp'
```

**Comment by floreks** [comment]
Fill in our issue template correctly and provide more details together with dashboard logs. Without that there is nothing we can do.

**Comment by pgnaleen** [comment]
thank you very much for fast response i am using 1.6 dashboard with kubenetes 1.7.5

**Comment by pgnaleen** [comment]
please provide me your details to contact you directly.

**Comment by floreks** [comment]
Devs can be reached on https://kubernetes.slack.com/ on a `sig-ui` channel.

**Comment by pgnaleen** [comment]
can't be accessed this site. it is blocked by our proxy server.

**Comment by pgnaleen** [comment]
heloo i were trying dashboard head but i got following error.

2017/09/15 08:28:40 Metric client health check failed: an error on the server ("unknown") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.


dashboard pod is running but still cant access dashboard.

**Comment by pgnaleen** [comment]
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "endpoints"
  },
  "code": 404
}


above response for following link

http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/

**Comment by floreks** [comment]
Why are you using our HEAD image?

> 2017/09/15 08:28:40 Metric client health check failed: an error on the server ("unknown") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.

This was introduced few days ago and is not available in official release.

**Comment by pgnaleen** [comment]
but compatibility matrix says it is the only version which has full support to the kubenetes 1.7

**Comment by floreks** [comment]
It also says that HEAD builds are unstable. They should not be used unless you know how to use them and are up-to-date with latest features. `1.6.3` release also works fine with k8s 1.7.

**Comment by floreks** [comment]
Dashboard 1.7 will introduce many breaking changes and whole new approach to security. We are updating docs and preparing for the release. You can track PR #2366.

**Comment by pgnaleen** [comment]
thank you veyr much my dear friend.

**Comment by pgnaleen** [comment]
what is this heapster service is this needed in order to funtioning properly of dashboaed 1.6.3 and kubernetes 1.7.5

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/wiki/Integrations

**Comment by pgnaleen** [comment]
[restful] 2017/09/15 08:56:17 log.go:26: No metric client provided. Skipping metrics.
[2017-09-15T08:56:17Z] Outcoming response to 172.17.0.1:58206 with 200 status code
[2017-09-15T08:56:45Z] Incoming HTTP/1.1 GET /api/v1/namespace?filterBy=&itemsPerPage=15&namespace=&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:58206: {}
Getting list of namespaces
[2017-09-15T08:56:45Z] Outcoming response to 172.17.0.1:58206 with 200 status code
[2017-09-15T08:56:49Z] Incoming HTTP/1.1 GET /api/v1/namespace/kube-system request from 172.17.0.1:58206: {}
Getting details of kube-system namespace
[2017-09-15T08:56:49Z] Outcoming response to 172.17.0.1:58206 with 200 status code
[2017-09-15T08:57:16Z] Incoming HTTP/1.1 GET /api/v1/node?filterBy=&itemsPerPage=15&namespace=&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:58206: {}
[restful] 2017/09/15 08:57:16 log.go:26: No metric client provided. Skipping metrics.
[2017-09-15T08:57:16Z] Outcoming response to 172.17.0.1:58206 with 200 status code
[2017-09-15T08:57:19Z] Incoming HTTP/1.1 GET /api/v1/node/master?filterBy=&itemsPerPage=15&name=master&namespace=&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:58206: {}
Getting details of master node
[restful] 2017/09/15 08:57:19 log.go:26: No metric client provided. Skipping metrics.
[restful] 2017/09/15 08:57:19 log.go:26: No metric client provided. Skipping metrics.
[restful] 2017/09/15 08:57:19 log.go:26: No metric client provided. Skipping metrics.
Getting pod metrics
[2017-09-15T08:57:19Z] Outcoming response to 172.17.0.1:58206 with 200 status code
[2017-09-15T08:59:56Z] Incoming HTTP/1.1 GET /api/v1/node?filterBy=&itemsPerPage=15&namespace=&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:58206: {}
[restful] 2017/09/15 08:59:56 log.go:26: No metric client provided. Skipping metrics.
[2017-09-15T08:59:56Z] Outcoming response to 172.17.0.1:58206 with 200 status code
[2017-09-15T09:00:00Z] Incoming HTTP/1.1 GET /api/v1/pod/kube-system?filterBy=&itemsPerPage=15&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:58206: {}
Getting list of all pods in the cluster
[restful] 2017/09/15 09:00:00 log.go:26: No metric client provided. Skipping metrics.
[restful] 2017/09/15 09:00:00 log.go:26: No metric client provided. Skipping metrics.


this is the error with the dashboard 1.6.3
but i have started ster service

**Comment by pgnaleen** [comment]
Kubernetes master is running at https://172.26.76.121:6443
Heapster is running at https://172.26.76.121:6443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://172.26.76.121:6443/api/v1/namespaces/kube-system/services/kube-dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
You have new mail in /var/spool/mail/root

**Comment by floreks** [comment]
Version 1.6.3 does not have periodic check for heapster. Heapster has to be started first. Then you need to wait a few minutes and delete dashboard pod. After restart it will try to connect to heapster and if it succeeds metrics will be enabled.

**Comment by pgnaleen** [comment]
[root@master ~]# kubectl get all --all-namespaces
NAMESPACE        NAME                                       READY     STATUS    RESTARTS   AGE
kube-system      po/etcd-master                             1/1       Running   2          5h
kube-system      po/kube-apiserver-master                   1/1       Running   2          1d
kube-system      po/kube-controller-manager-master          1/1       Running   38         7d
kube-system      po/kube-dns-2425271678-f46fk               3/3       Running   3          7d
kube-system      po/kube-flannel-ds-jg1bt                   2/2       Running   0          2d
kube-system      po/kube-flannel-ds-t51dj                   2/2       Running   0          4h
kube-system      po/kube-flannel-ds-vg270                   2/2       Running   0          2d
kube-system      po/kube-flannel-ds-vgjjs                   2/2       Running   3          12h
kube-system      po/kube-proxy-k61z0                        1/1       Running   0          4h
kube-system      po/kube-proxy-kb2mq                        1/1       Running   0          2d
kube-system      po/kube-proxy-q0flb                        1/1       Running   1          20h
kube-system      po/kube-proxy-rcwmq                        1/1       Running   0          2d
kube-system      po/kube-scheduler-master                   1/1       Running   38         7d
kube-system      po/kubernetes-dashboard-1784437746-7hfhz   1/1       Running   0          11m
micro-services   po/nginx-app-89289518-2j5jd                1/1       Running   0          4h
micro-services   po/nginx-app-89289518-b2ft5                1/1       Running   0          5h
micro-services   po/nginx-app-89289518-gdrfh                1/1       Running   0          4h

NAMESPACE        NAME                       CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
default          svc/kubernetes             10.96.0.1        <none>        443/TCP         7d
kube-system      svc/heapster               10.104.173.232   <none>        80/TCP          2d
kube-system      svc/kube-dns               10.96.0.10       <none>        53/UDP,53/TCP   7d
kube-system      svc/kubernetes-dashboard   10.104.32.109    <none>        80/TCP          11m
micro-services   svc/nginx-app              10.104.249.211   <none>        80/TCP          5h

NAMESPACE        NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system      deploy/kube-dns               1         1         1            1           7d
kube-system      deploy/kubernetes-dashboard   1         1         1            1           11m
micro-services   deploy/nginx-app              3         3         3            3           5h

NAMESPACE        NAME                                 DESIRED   CURRENT   READY     AGE
kube-system      rs/kube-dns-2425271678               1         1         1         7d
kube-system      rs/kubernetes-dashboard-1784437746   1         1         1         11m
micro-services   rs/nginx-app-89289518                3         3         3         5h


my heapster service few days old. i just started kashboard. but it still said 

Creating in-cluster Heapster client
Could not enable metric client: Health check failed: an error on the server ("unknown") has prevented the request from succeeding (get services heapster). Continuing.

**Comment by floreks** [comment]
> NAMESPACE NAME READY STATUS RESTARTS AGE
kube-system po/etcd-master 1/1 Running 2 5h
kube-system po/kube-apiserver-master 1/1 Running 2 1d
kube-system po/kube-controller-manager-master 1/1 Running 38 7d
kube-system po/kube-dns-2425271678-f46fk 3/3 Running 3 7d
kube-system po/kube-flannel-ds-jg1bt 2/2 Running 0 2d
kube-system po/kube-flannel-ds-t51dj 2/2 Running 0 4h
kube-system po/kube-flannel-ds-vg270 2/2 Running 0 2d
kube-system po/kube-flannel-ds-vgjjs 2/2 Running 3 12h
kube-system po/kube-proxy-k61z0 1/1 Running 0 4h
kube-system po/kube-proxy-kb2mq 1/1 Running 0 2d
kube-system po/kube-proxy-q0flb 1/1 Running 1 20h
kube-system po/kube-proxy-rcwmq 1/1 Running 0 2d
kube-system po/kube-scheduler-master 1/1 Running 38 7d
kube-system po/kubernetes-dashboard-1784437746-7hfhz 1/1 Running 0 11m
micro-services po/nginx-app-89289518-2j5jd 1/1 Running 0 4h
micro-services po/nginx-app-89289518-b2ft5 1/1 Running 0 5h
micro-services po/nginx-app-89289518-gdrfh 1/1 Running 0 4h

Where is heapster pod?

**Comment by pgnaleen** [comment]
thank you very much my friend. you are a blessing for me.

please send me .yaml file to execute.

**Comment by floreks** [comment]
Just read and follow instructions described on [Heapster](https://github.com/kubernetes/heapster) repository.

**Comment by pgnaleen** [comment]
i used kubeadm in order to deploy cluster. i don't see instructions to deploy headster.

**Comment by floreks** [comment]
From Heapster's repo README.md
![zrzut ekranu z 2017-09-15 12-06-24](https://user-images.githubusercontent.com/2285385/30477690-53d93cfa-9a0e-11e7-9cd7-e8ff53b3fec5.png)

Going further to link under **InfluxDB use [this guide](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md).**
![zrzut ekranu z 2017-09-15 12-07-17](https://user-images.githubusercontent.com/2285385/30477749-97fd4b4c-9a0e-11e7-9c18-a3605d16d2c4.png)

**In order to deploy Heapster and InfluxDB, you will need to create the Kubernetes resources described by the contents of [deploy/kube-config/influxdb](https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb).**

**Comment by pgnaleen** [comment]
what is this influxDB

**Comment by pgnaleen** [comment]
awesome. it is working. thank you very much my dear friend.

**Comment by pgnaleen** [comment]
i am facing problem when deploying LoadBalancer. Please help me.  how can i map master ip and a port with load balancer in order to access from out side and deploy service in worker nodes to connect.

**Comment by pgnaleen** [comment]
please send me service yaml
