### ISSUE TITLE
Can't access pods using clusterIP:port

### ISSUE THREAD

**Issue by pgnaleen** [kubernetes/dashboard#2377]
##### Environment
Installed kubenetes with kubeadm
kubernetes: 1.7.5
dashboard 1.6.3

operating system redhat 7.3

##### Steps to reproduce
just setup cluster using kubeadm and with cni network plugin disabled. after installed flanel network enable network args again. pods can't curl from different nodes in the cluster as well.
I ran nginx in the pods.

[root@master ~]# kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
default       po/my-nginx-4293833666-1x4cv               1/1       Running   0          52m
default       po/my-nginx-4293833666-l6jn3               1/1       Running   0          52m
kube-system   po/etcd-master                             1/1       Running   3          1d
kube-system   po/heapster-1783826406-fp4x3               1/1       Running   0          38m
kube-system   po/kube-apiserver-master                   1/1       Running   3          2d
kube-system   po/kube-controller-manager-master          1/1       Running   39         8d
kube-system   po/kube-dns-2425271678-f46fk               3/3       Running   6          8d
kube-system   po/kube-flannel-ds-jg1bt                   2/2       Running   0          2d
kube-system   po/kube-flannel-ds-t51dj                   2/2       Running   0          1d
kube-system   po/kube-flannel-ds-vg270                   2/2       Running   0          2d
kube-system   po/kube-flannel-ds-vgjjs                   2/2       Running   6          1d
kube-system   po/kube-proxy-k61z0                        1/1       Running   0          1d
kube-system   po/kube-proxy-kb2mq                        1/1       Running   0          2d
kube-system   po/kube-proxy-q0flb                        1/1       Running   2          1d
kube-system   po/kube-proxy-rcwmq                        1/1       Running   0          2d
kube-system   po/kube-scheduler-master                   1/1       Running   39         8d
kube-system   po/kubernetes-dashboard-1784437746-7n5w6   1/1       Running   0          38m

NAMESPACE     NAME                       CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       svc/kubernetes             10.96.0.1       <none>        443/TCP         8d
default       svc/my-nginx               10.102.96.200   <none>        80/TCP          50m
kube-system   svc/heapster               10.97.47.158    <none>        80/TCP          20h
kube-system   svc/kube-dns               10.96.0.10      <none>        53/UDP,53/TCP   8d
kube-system   svc/kubernetes-dashboard   10.98.167.55    <none>        80/TCP          20h

NAMESPACE     NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default       deploy/my-nginx               2         2         2            2           52m
kube-system   deploy/heapster               1         1         1            1           20h
kube-system   deploy/kube-dns               1         1         1            1           8d
kube-system   deploy/kubernetes-dashboard   1         1         1            1           20h

NAMESPACE     NAME                                 DESIRED   CURRENT   READY     AGE
default       rs/my-nginx-4293833666               2         2         2         52m
kube-system   rs/heapster-1783826406               1         1         1         20h
kube-system   rs/kube-dns-2425271678               1         1         1         8d
kube-system   rs/kubernetes-dashboard-1784437746   1         1         1         20h

[root@master ~]# kubectl describe svc/my-nginx
Name:			my-nginx
Namespace:		default
Labels:			run=my-nginx
Annotations:		<none>
Selector:		run=my-nginx
Type:			ClusterIP
IP:			10.102.96.200
Port:			<unset>	80/TCP
Endpoints:		10.244.2.3:80,10.244.3.6:80
Session Affinity:	None
Events:			<none>

this is the page i followed.
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

##### Observed result
nothing is going to display

##### Expected result
nginx home page

**Comment by floreks** [comment]
This repository is for Dashboard related issues **only**. Go to core repository: https://github.com/kubernetes/kubernetes
