### ISSUE TITLE
Waw. Just Waw.

### ISSUE THREAD

**Issue by warpdigital** [kubernetes/dashboard#2378]
##### Steps to reproduce
All detailed on the website

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Everything as expected

##### Comments
Brilliant piece of software. Got a bit daunting when i first started glanced at the instructions.
When i actually read it, it was just me being a nob head.
Absolutely brilliant

**Comment by cheld** [comment]
Thank you so much. We really appreciate. Kudos to all @kubernetes/dashboard-maintainers
