### ISSUE TITLE
http://xxxx/ui miss a `/`

### ISSUE THREAD

**Issue by opspy** [kubernetes/dashboard#2388]
##### Environment
```
Dashboard version: 1.6.3
Kubernetes version: 1.7.6
Operating system: centos 7.3
Node.js version:
Go version:
```
when i use  kubectl proxy proxy the dashboard , access the ` http://xxx/ui` , rewrite to the `http://xxx/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy`,but the right address is `http://xxx/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/` , the end missing a `/`

**Comment by floreks** [comment]
Not a Dashboard issue: https://github.com/kubernetes/kubernetes/issues/52729
