### ISSUE TITLE
403 after install

### ISSUE THREAD

**Issue by vasiliyb** [kubernetes/dashboard#2391]
##### Steps to reproduce

brand new Kubernetes GCE cluster v1.7.6

Browse to http://localhost:8001/ui

##### Environment
```
Installation method: GCE UI
Kubernetes version: 1.7.6
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Forbidden (403):
```
User "system:serviceaccount:kube-system:default" cannot list jobs.batch in the namespace "default".: "Unknown user \"system:serviceaccount:kube-system:default\"" (get jobs.batch)

```

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/wiki/FAQ#i-am-using-kubernetes-gce-cluster-but-getting-forbidden-access-errors
