### ISSUE TITLE
Minikube times out all the time in Windows

### ISSUE THREAD

**Issue by dimplerohara** [kubernetes/dashboard#2393]
##### Steps to reproduce

1.  minikube start
2. minikube status
3. minikube dashboard
4. kubectl cluster-info
5. kubectl cluster-info dump
Unable to connect to the server: dial tcp 192.168.99.100:8443: connectex: No connection could be made because the target machine actively refused it.

6.Open Minikube dashboard and get below error

##### Environment
```
Installation method: using minikube 0.22.2 executable
Kubernetes version: 1.7.5
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
Get https://10.0.0.1:443/apis/apps/v1beta1/namespaces/default/statefulsets: dial tcp 10.0.0.1:443: getsockopt: connection refused

```

**Comment by floreks** [comment]
This repository is for Kubernetes Dashboard related issues **only**. If minikube has some issues on windows then create an issue there.
