### ISSUE TITLE
Log-out button dont delete "jwt Token" cookie on safari 11

### ISSUE THREAD

**Issue by ekozan** [kubernetes/dashboard#2396]
##### Environment

```
Dashboard version: 1.7.0
Kubernetes version: 1.7.0
```

##### Steps to reproduce
On login page press skip
I have no ressources acces ( it's ok )
Login with an token
I have all ressources acces ( it's ok )
Logout
On login page press skip
I have all ressources acces ( Here is the issue )

##### Observed result
Acces to all logs, all pods info, etc ....

##### Expected result
No acces to the resources ( return to dashboard-minimal )

**Comment by maciaszczykm** [comment]
It is expected behavior. Dashboard no longer uses admin privileges by default.

**Comment by maciaszczykm** [comment]
Did you read https://github.com/kubernetes/dashboard/wiki/Access-control as it is recommended in https://github.com/kubernetes/dashboard/blob/master/README.md#getting-started?

**Comment by ekozan** [comment]
Yeah i have remove all resources

-  On login page press skip 
-  I have no ressources acces  ( it's ok )
- Login with an token 
- I have all ressources acces  ( it's ok )
- Logout
-  On login page press skip 
- I have all ressources acces  ( Here is the issue )

**Comment by floreks** [comment]
How are you accessing Dashboard?

**Comment by floreks** [comment]
I believe that you were not logged out and token is still saved in your cookies. Click on the user icon and see if it says `Logged in with token`.

**Comment by ekozan** [comment]
I figured out what's the issue the "jwt Token" cookie is not deleted in case of logout

**Comment by floreks** [comment]
It does delete it. It has to be specific to your environment. You need to provide much more information about it. 

Used browser and version of it, details of how you are accessing dashboard, screenshot from plugin similar to `EditThisCookie`.

![zrzut ekranu z 2017-09-22 14-45-01](https://user-images.githubusercontent.com/2285385/30744974-b008810c-9fa4-11e7-82e3-a953e5f440f2.png)

**Comment by ekozan** [comment]
baaahhh, Apple again ... 

Mac OS 10.12.6
Safari Version 11.0

It's works in the fox ..

**Comment by floreks** [comment]
Probably AngularJS `$cookies` service does not work correctly with Safari browser. We will investigate that and create an issue on AngularJS repo it that's the case.

**Comment by floreks** [comment]
Linking: https://discussions.apple.com/thread/7907561?start=0&tstart=0 as it might be related to the issue. @ekozan can you check if some of the posted solutions work for you? I know that browser version is different but it still might be Safari issue not Dashboard or AngularJS.

**Comment by maciaszczykm** [comment]
We will track from #2420.
