### ISSUE TITLE
Cannot list configmaps, persistentvolumeclaims, secrets, services ... etc

### ISSUE THREAD

**Issue by neegor** [kubernetes/dashboard#2399]
```
Dashboard version: 1.7.0
Kubernetes version: 1.75
Operating system: ubuntu 16.04
```

##### Steps to reproduce
Deploy dashboard
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```
Authorization with token. The token received here.
```
kubectl -n kube-system describe secret replicaset-controller-token
```

##### Observed result
![pic](https://user-images.githubusercontent.com/436337/30772004-8297fba4-a05c-11e7-8746-4d86426a4fe2.PNG)

##### Comments
Maybe I'm doing something wrong. Thanks!

**Comment by floreks** [comment]
Works as intended. 

From wiki:
>There are many Service Accounts created in Kubernetes by default. **All with different access permissions**. In order to find **any token**, that can be used to log in we'll use kubectl:
...
We can now use printed token to log in to Dashboard. **To find out more about how to configure and use Bearer Tokens, please read Introduction section**.

Wiki does not describe how you should configure authorization in your cluster. It lists all the links to official kubernetes documentation that are needed to understand and configure it. Provided example uses existing token to log in but it does not say this token will allow you to access all resources in the cluster.

Read `Access Control` section carefully with all the links to understand how it works.
