### ISSUE TITLE
dashboard not working with https 

### ISSUE THREAD

**Issue by dorsegal** [kubernetes/dashboard#2404]
Hi I upgraded the dashboard from 1.7 using the recommended steps and for some reason https is not working.

I created a secret with our certificates (issued from godaddy).
when i try https://api.example.com/ui im getting this:
```
Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://100.96.0.9:8443/'
```

here is the startup logs from the dashboard container:
```
2017/09/25 11:13:41 Starting overwatch
2017/09/25 11:13:41 Using in-cluster config to connect to apiserver
2017/09/25 11:13:41 Using service account token for csrf signing
2017/09/25 11:13:41 No request provided. Skipping authorization
2017/09/25 11:13:41 Successful initial request to the apiserver, version: v1.7.0
2017/09/25 11:13:41 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2017/09/25 11:13:41 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2017/09/25 11:13:41 Initializing secret synchronizer synchronously using secret kubernetes-dashboard-key-holder from namespace kube-system
2017/09/25 11:13:41 Initializing JWE encryption key from synchronized object
2017/09/25 11:13:41 Creating in-cluster Heapster client
2017/09/25 11:13:41 Trying to update secret with same object. Skipping
2017/09/25 11:13:41 Serving securely on HTTPS port: 8443
2017/09/25 11:13:41 Successful request to heapster
2017/09/25 11:13:49 Getting application global configuration
2017/09/25 11:13:49 Application configuration {"serverTime":1506338029475}
```

```
Dashboard version: 1.7
Kubernetes version: 1.7
```

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/wiki/Accessing-dashboard

**Comment by dorsegal** [comment]
I can connect via `https://<master-ip>:<apiserver-port>/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`
but browser still warns about unsecure connection
![image](https://user-images.githubusercontent.com/7013837/30807206-91386e9a-a201-11e7-9370-96d1405d6ed0.png)

**Comment by floreks** [comment]
In this case certificate presented in the browser will be certificate of the API server. The one specified by `--tls-cert-file` flag in `kube-apiserver`.

**Comment by cheld** [comment]
@dorsegal with `kubectl proxy` creates a secure channel to apiserver. It is the simplest way to connect to apiserver.

**Comment by cloorc** [comment]
@cheld Hi, I started my cluster through `kubeadm init` and create proxy with `--kubeconfig ${HOME}/.kube/config` option. The `${HOME}/.kube/config` file is actually copied from `/etc/kubernetes/admin.conf`. After my proxy started, access `/ui` threw this exception too. Would you please give me some advice about how to solve this problem? 

Pods already started are as following:

```
NAME                                    READY     STATUS    RESTARTS   AGE
etcd-z0228                              1/1       Running   0          48m
kube-apiserver-z0228                    1/1       Running   0          49m
kube-controller-manager-z0228           1/1       Running   0          48m
kube-dns-545bc4bfd4-2d5b2               3/3       Running   0          49m
kube-flannel-ds-8dtz2                   1/1       Running   0          45m
kube-proxy-fzpsv                        1/1       Running   0          49m
kube-scheduler-z0228                    1/1       Running   0          48m
kubernetes-dashboard-79d9896c7b-kjk7w   1/1       Running   0          29m
```
Proxy command is `sudo kubectl --kubeconfig ${HOME}/.kube/config proxy --port 80`. `http://127.0.0.1/` works, however, `http://127.0.0.1/ui` will be redirected to `http://127.0.0.1/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/` and the content is as following:

```text
Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://10.244.0.4:8443/'
```
---

Images already downloaded:

```text
REPOSITORY                                                 TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kubernetes-dashboard-init-amd64   v1.0.1              95bfc2b3e5a3        21 hours ago        250.5 MB
gcr.io/google_containers/kube-controller-manager-amd64     v1.8.1              08514038038e        5 days ago          129.2 MB
gcr.io/google_containers/kube-apiserver-amd64              v1.8.1              e24ccd46aab5        5 days ago          194 MB
gcr.io/google_containers/kube-scheduler-amd64              v1.8.1              e9999818cef2        5 days ago          54.88 MB
gcr.io/google_containers/kube-proxy-amd64                  v1.8.1              30643046b829        5 days ago          93.14 MB
gcr.io/google_containers/kubernetes-dashboard-amd64        v1.7.1              294879c6444e        2 weeks ago         128.4 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64             1.14.5              fed89e8b4248        2 weeks ago         41.82 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64            1.14.5              512cd7425a73        2 weeks ago         49.39 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64       1.14.5              459944ce8cc4        2 weeks ago         41.42 MB
quay.io/coreos/flannel                                     v0.9.0-amd64        4c600a64a18a        3 weeks ago         51.34 MB
gcr.io/google_containers/etcd-amd64                        3.0.17              243830dae7dd        7 months ago        168.9 MB
gcr.io/google_containers/pause-amd64                       3.0                 99e59f495ffa        17 months ago       746.9 kB
```

**Comment by floreks** [comment]
Do not use /ui redirect as it has not been updated yet. Our main README and Acessing Dashboard guide on wiki pages has correct link to Dashboard. Read them please.

**Comment by cheld** [comment]
Copy & paste the correct link. /ui is currently not working

**Comment by cloorc** [comment]
@floreks @cheld Ok, thanks a lot! However, it tolds me handshake timeout. Actually I'm reusing `/etc/kubernetes/pki/front-proxy-client.crt` and `/etc/kubernetes/pki/front-proxy-client.key` as its certs according to https://github.com/kubernetes/dashboard/wiki/Installation#recommended-setup .

My steps are(I just want to reuse these keys instead of generating new keys manually):

```bash
cp /etc/kubernetes/pki/front-proxy-client.crt $HOME/certs/dashboard.crt
cp /etc/kubernetes/pki/front-proxy-client.key $HOME/certs/dashboard.key
kubectl create secret generic kubernetes-dashboard-certs --from-file=$HOME/certs -n kube-system
kubectl apply -f https://github.com/kubernetes/dashboard/wiki/Installation#recommended-setup
kubectl --kubeconfig $HOME/.kube/config proxy --port 80
```

When I trying to access http://127.0.0.1/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/, it tells me like this:

```text
Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.244.0.6:8443/'
```

I guess it's a problem about certificate, I've no idea what's wrong with it. Could you guys please give me some suggestion? Thanks a head!

**Comment by floreks** [comment]
Can you show us the logs from dashboard pod?

**Comment by cloorc** [comment]
@floreks Sorry, logs from dashboad is as following:

```text
z0228@z0228:~$ kubectl -n kube-system logs kubernetes-dashboard-79d9896c7b-rnknc
2017/10/17 07:47:41 Starting overwatch
2017/10/17 07:47:41 Using in-cluster config to connect to apiserver
2017/10/17 07:47:41 Using service account token for csrf signing
2017/10/17 07:47:41 No request provided. Skipping authorization
2017/10/17 07:47:41 Successful initial request to the apiserver, version: v1.8.1
2017/10/17 07:47:41 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2017/10/17 07:47:41 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2017/10/17 07:47:41 Initializing secret synchronizer synchronously using secret kubernetes-dashboard-key-holder from namespace kube-system
2017/10/17 07:47:41 Initializing JWE encryption key from synchronized object
2017/10/17 07:47:41 Trying to update secret with same object. Skipping
2017/10/17 07:47:41 Creating in-cluster Heapster client
2017/10/17 07:47:41 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 07:47:41 Serving securely on HTTPS port: 8443
2017/10/17 07:48:11 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 07:48:41 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 07:49:11 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 07:49:41 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 07:50:11 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 07:50:41 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 07:51:02 http: TLS handshake error from 10.244.0.1:42704: tls: first record does not look like a TLS handshake
2017/10/17 07:51:03 http: TLS handshake error from 10.244.0.1:42706: tls: first record does not look like a TLS handshake
2017/10/17 07:51:03 http: TLS handshake error from 10.244.0.1:42708: tls: first record does not look like a TLS handshake
2017/10/17 07:51:08 http: TLS handshake error from 10.244.0.1:42718: tls: first record does not look like a TLS handshake
2017/10/17 07:51:11 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:20:11 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:20:34 http: TLS handshake error from 10.244.0.1:47162: tls: first record does not look like a TLS handshake
2017/10/17 08:20:41 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
```

**Comment by floreks** [comment]
Have you tried to use autogenerated certificates? If it will work then possibly there is a problem with these certificates and they can not be used.

**Comment by cloorc** [comment]
@floreks Actually, just let dashboard do everything is my first solution and my actually command is as following:

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml
```

> I've delete these pods before I recreate it. And the response is as following:

```bash
Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.244.0.7:9090/'
```

Logging information looks like this:

```
2017/10/17 08:53:54 Starting overwatch
2017/10/17 08:53:54 Using in-cluster config to connect to apiserver
2017/10/17 08:53:54 Using service account token for csrf signing
2017/10/17 08:53:54 No request provided. Skipping authorization
2017/10/17 08:53:54 Successful initial request to the apiserver, version: v1.8.1
2017/10/17 08:53:54 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2017/10/17 08:53:54 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2017/10/17 08:53:54 Initializing secret synchronizer synchronously using secret kubernetes-dashboard-key-holder from namespace kube-system
2017/10/17 08:53:54 Initializing JWE encryption key from synchronized object
2017/10/17 08:53:54 Trying to update secret with same object. Skipping
2017/10/17 08:53:54 Creating in-cluster Heapster client
2017/10/17 08:53:54 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:53:54 Serving insecurely on HTTP port: 9090
2017/10/17 08:54:24 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:54:54 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:55:24 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:55:54 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:56:24 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:56:54 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 08:57:24 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
```

This time, the ip address seems changed from `https://10.244.0.6:8443/` to `https://10.244.0.7:9090/`

**Comment by floreks** [comment]
These are not errors but warnings that current user does not have access to listed resource. 

> Serving insecurely on HTTP port: 9090

This means that `--tls-key-file` and `--tls-cert-file` flags were not passed to Dashboard and certs were not used to serve Dashboard securely. `/ui` point to old, insecure Dashboard (HTTP endpoint).

**Comment by cloorc** [comment]
Ok, I've copied my `apiserver.crt` and `apiserver.key` to `$HOME/certs` and rename them to `dashboard.crt` and `dashboard.key`, I recreated resources as following:

```bash
kubectl create secret generic kubernetes-dashboard-certs --from-file=$HOME/certs -n kube-system
wget https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
kubectl apply -f kubernetes-dashboard.yaml
```

Logs from dashboard are as following:

```text
2017/10/17 09:29:44 Starting overwatch
2017/10/17 09:29:44 Using in-cluster config to connect to apiserver
2017/10/17 09:29:44 Using service account token for csrf signing
2017/10/17 09:29:44 No request provided. Skipping authorization
2017/10/17 09:29:44 Successful initial request to the apiserver, version: v1.8.1
2017/10/17 09:29:44 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2017/10/17 09:29:44 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2017/10/17 09:29:44 Initializing secret synchronizer synchronously using secret kubernetes-dashboard-key-holder from namespace kube-system
2017/10/17 09:29:44 Initializing JWE encryption key from synchronized object
2017/10/17 09:29:44 Trying to update secret with same object. Skipping
2017/10/17 09:29:44 Creating in-cluster Heapster client
2017/10/17 09:29:44 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 09:29:44 Serving securely on HTTPS port: 8443
2017/10/17 09:30:14 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/10/17 09:30:33 http: TLS handshake error from 10.244.0.1:41198: tls: first record does not look like a TLS handshake
2
```

Then I retried `http://127.0.0.1/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/` and been told:

```
Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.244.0.9:8443/'
```

Browser `http://127.0.0.1/ui` and it was redirected to `http://127.0.0.1/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default` and it told me like this:

```text
Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://10.244.0.9:8443/'
```

BTW, `dashboard` will access `apiserver` by `apiserver` certificates, which are providded in `certs`, am I right? Why it won't work yet?

**Comment by floreks** [comment]
I asked you not to provide your own certs and let them be autogenerated. Delete created secret and use command from our README. I need to know if this will work.

**Comment by cloorc** [comment]
I've done that already. Please check my last post([#issuecomment-337165510](#issuecomment-337165510)). 

1. Remove old resources(`kubectl delete -f kubernetes-dashboard.yaml`) and make sure old `dashboard` pod has already been destroyed(`kubectl -n kube-system get pods` won't show it already);
1. Create everything as `kubernetes-dashboard.yaml`(`kubectl apply -f kubernetes-dashboard.yaml`);
1. Make sure `dashboard` pod has already been created and started(`kubernetes-dashboard-79d9896c7b-bfrwr   1/1       Running   0          7s`)
1. Open my browser and point it to `http://127.0.0.1/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`, shows `Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.244.0.11:8443/'`
1. Try to access `/ui` and the location was redirected to `http://127.0.0.1/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/` and told me `Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://10.244.0.10:8443/'`

My last post is trying to resolve the problem of forbidden access of resources, in which you told me there are no flags of `--tls-cert-file` and `--tls-key-file` provided. However, I thought copying `apiserver.{crt,key}` as `dashboard.{crt,key}` and creating `kubernetes-dashboard-certs` manully would solve this problem, but it is not. Is it not what you are mean? And what should be the right solution for supply these flags?

**Comment by floreks** [comment]
If you do not provide certificates manually (`kubectl create secret --from-file ...`), they are created automatically by our init container. I am certain that it generates correct certificates and I wanted to make sure that it is not certificates fault. That is why I asked you not to create secret manually.

If this scenario does not work then kubernetes version `1.8.1` might be the cause. They might have changed something. Dashboard `1.7.X` is known to be working only with same core version `1.7.X`. We can not guarantee that future versions of core will work with older versions of Dashboard.

Are you able to check if version is the cause?

**Comment by cloorc** [comment]
Yes, create `kubernetes-dashboard` based on `https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml` won't work in my circumstance. Now I'm sure `dashboard` created based on https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml would make `/ui` work (old style), but all resources can not be accessed.

I'll downgrade my kubernetes to `1.7.8` and test it later.

**Comment by cloorc** [comment]
Kubernetes : v1.7.8
Dashboard : v1.7.1

Version information:

```text
kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Steps:

```bash
https_proxy=http://127.0.0.1:2080 wget -O readme.yaml https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
kubectl apply -f readme.yaml
sudo kubectl --kubeconfig /home/z0228/.kube/config proxy --port 80
```

Results:

Both `https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml` and `https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml` are abnormal.

I'm not sure what's the real reason for this problem.

**Comment by cloorc** [comment]
I'm going to deploy dashboard through alternative method according to wiki and grant admin access  for local usage. `/ui` works in this manner. Thanks a lot!

**Comment by dotw** [comment]
I have the same issue with k8s 1.8. @cloorc , could you let us know how to make it work?

**Comment by KeithTt** [comment]
there are many TLS errors in my case:

```
# kubectl logs -f kubernetes-dashboard-3168217588-6vdz0 -n kube-system

...
2017/11/02 18:13:50 http: TLS handshake error from 172.17.0.1:27531: EOF
2017/11/02 18:13:50 http: TLS handshake error from 172.17.0.1:26333: EOF
2017/11/02 18:13:51 http: TLS handshake error from 172.17.0.1:28635: EOF
2017/11/02 18:13:51 http: TLS handshake error from 172.17.0.1:36110: EOF
2017/11/02 18:13:51 http: TLS handshake error from 172.17.0.1:33731: EOF
2017/11/02 18:13:51 http: TLS handshake error from 172.17.0.1:29863: EOF
2017/11/02 18:13:51 http: TLS handshake error from 172.17.0.1:18200: EOF
2017/11/02 18:13:51 http: TLS handshake error from 172.17.0.1:20909: EOF
2017/11/02 18:13:52 http: TLS handshake error from 172.17.0.1:7458: EOF
2017/11/02 18:13:52 http: TLS handshake error from 172.17.0.1:5308: EOF
2017/11/02 18:13:52 http: TLS handshake error from 172.17.0.1:20494: EOF
2017/11/02 18:13:52 http: TLS handshake error from 172.17.0.1:26512: EOF
2017/11/02 18:13:52 http: TLS handshake error from 172.17.0.1:37642: EOF
2017/11/02 18:13:52 http: TLS handshake error from 172.17.0.1:59152: EOF
...
```

**Comment by cloorc** [comment]
In my circumstance, I tried installing `k8s` in a fresh new initialized virtual machine, in which there will have no port conflicting problems. By the way, how have you installed `kube*`? I've installed them by command `apt install`. `TLS` problems mostly because of the `kubelet` is not running.

**Comment by KeithTt** [comment]
`kubelet` is running. And the kubernetes seems healthy, I guess there is something wrong with dashboard, I am reading the wiki page of dashboard project.

**Comment by rama-arun** [comment]
This helped me --- take it for what its worth.

https://github.com/kubernetes/dashboard/issues/2465

**Comment by thomasjungblut** [comment]
so indeed something changed. I tried to create a dashboard with the current latest 1.7.1 (https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml). I get the TLS handshake issue. 

I works however with the 1.6.3 version of this. Any idea? None of the instructions above seem to do it so far.

**Comment by nelson-cf** [comment]
To make a long story short for everyone - the dashboard moved and the redirect from /ui was not updated.  Go here instead and it will likely work if you are receiving the error that brought you here:

/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

Thanks to @rama-arun for the link.

**Comment by HolimaX** [comment]
Hmm. It still does not work for me. Tried to do kubectl proxy both from dashboard node, both from master node on windows 10, still nothing opens. Tried both ClusterIP, both NodePort setting for Service, nothing helps.

**Comment by jturi** [comment]
Try this:
Source: (Link1) https://stackoverflow.com/questions/46664104/how-to-sign-in-kubernetes-dashboard

Go to the login page and select Token :

(Link2) http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login

Generate token with kubectl:
```
kubectl -n kube-system get secret
look for something like this: 
deployment-controller-token-fwwd4                kubernetes.io/service-account-token   3      9d
kubectl -n kube-system describe secret deployment-controller-token--fwwd4
(your last 5 letters will be different, not fwwd4)
Copy the generated token and paste it in (Link2)
```
Go to dashboard :
(Link3) http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default

**Comment by floreks** [comment]
> Download a dashboard file: curl -O https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

**IMPORTANT:** Do not use `v1.10.1` as it is outdated. Use `v2.0.0-rcX`.
