### ISSUE TITLE
Exec is broken

### ISSUE THREAD

**Issue by EvolveZy** [kubernetes/dashboard#2407]
##### Environment

```
Dashboard version:1.7.0
Kubernetes version:1.7.0
Operating system:CentOS7.3
Node.js version:
Go version:
```
Today,I update dashboard from v1.6.3 to 1.7.0,  web page notice "unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr" when i exec container ,but 1.6.3 is working

**Comment by EvolveZy** [comment]
![qq 20170926111652](https://user-images.githubusercontent.com/16017151/30840970-bb2472a2-a2ac-11e7-9fa3-bb43d0268f18.png)

**Comment by floreks** [comment]
It is a known issue. API has changed on k8s side and we have to rewrite exec functionality.

**Comment by kachkaev** [comment]
Also noticed this. Posted details in https://github.com/kubernetes/dashboard/issues/2029#issuecomment-331450969

**Comment by jsenon** [comment]
But it's works with same k8s cluster and dashboard 1.6.3. Don't sure about API change on k8s.

**Comment by floreks** [comment]
1.6.3 uses k8s 1.6 dependencies. 1.7 uses k8s 1.7.

**Comment by Kaijun** [comment]
@floreks  has anyone already taken over this issue?  if i understood u correctly, is the new v1.7 dashboard still using v1.6.x client-go?

**Comment by floreks** [comment]
No. Version of Dashboard always reflects dependency on similar major version of kubernetes. 
Dashboard 1.6 - K8S 1.6
Dashboard 1.7 - K8S 1.7

We did not started work on this yet. We need to rewrite exec functionality anyway as it is not stable right now.

**Comment by Kaijun** [comment]
@floreks i think i could fix this issue for now and make the basic functionality of web-term work. After that we could re-consider how we rewrite exec functionality in a better way.  I could probably take a look into it

**Comment by maciaszczykm** [comment]
@Kaijun Go ahead :)

**Comment by Kaijun** [comment]
@floreks @maciaszczykm fixed, have a try

**Comment by Kaijun** [comment]
I just dive into the code and found the problem, after upgrading to client-go v4, we have to pass scheme.ParameterCodec instead of api.ParameterCodec while calling req.VersionedParams

check: https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=VersionedParams%28&type=

**Comment by maciaszczykm** [comment]
Done in #2422. Thanks, @Kaijun.

**Comment by sineycoder** [comment]
great！i meet the same problem, thanks a lot
