### ISSUE TITLE
Can't update dashboard on GKE cluster

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/dashboard#2409]
##### Environment
Google Cluster 1.7.6
```
✗ kubectl version                                                                   
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

✗ kubectl describe deploy kubernetes-dashboard --namespace=kube-system
...
    Image:	eu.gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1
```

##### Steps to reproduce
```
✗ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.6.3/src/deploy/kubernetes-dashboard.yaml
```

##### Observed result
Pods are recreated, but version doesn't move from 1.6.1 to 1.6.3.

##### Expected result
```
    Image:	eu.gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
```

**Comment by floreks** [comment]
GKE uses kube addon manager to make sure that installed addons can not be changed. You would have to find YAML file on disk that is used to sync addon state and update/remove it.

**Comment by rf232** [comment]
On gke you can't edit the on disk YAML file, however you can change the list of enabled addons with gcloud

https://cloud.google.com/container-engine/docs/clusters/operations#updating_a_container_cluster
```gcloud container clusters update $NAME --zone $ZONE --update-addons KubernetesDashboard=DISABLED```

and then deploy the latest version of the dashboard yourself
