### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by Ludea** [kubernetes/dashboard#2410]
```
Dashboard version: 1.7. 0
Kubernetes version:  1.7.5
Operating system: Ubuntu Server 

```

##### Steps to reproduce

Install kubernetes with kubeadm 
Install dashboard from 
##### Observed resultkubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml command 
Change clusterip by NodePort in service 
Go to https://master-ip:nodeport

The connection is not secure. 
The message is ; NET::ERR_CERT_AUTHORITY_INVALID

##### Expected result

I try to access on the login view page

**Comment by maciaszczykm** [comment]
Added ````` to fix template a bit. Still a lot info is missing.

**Comment by maciaszczykm** [comment]
Added ``` to fix template a bit.

**Comment by floreks** [comment]
Works as expected. Self-signed certificates will never be shown as trusted by the browser unless you manually import them.

Use your own trusted certificates if you want.
