### ISSUE TITLE
you must specify at least 1 of stdin, stdout, stderr

### ISSUE THREAD

**Issue by dc520** [kubernetes/dashboard#2411]
1:My environment
Dashboard version:1.7.0
Kubernetes version:1.7.6
Operating system:CentOS7.3
Node.js version:None
Go version:None

2:What did you do ?
 I enter the pods through the web interface, and then choose to run the command, into the container when the error.

3:What did you see instead
The error message on the web interface:
unable to upgrade : you must specify at least 1 of stdin, stdout, stderr

I run the command on the server : kubectl logs -f kubernetes-dashboard-xx -n kube-system

Error message:
2017/09/27 06:35:02 [2017-09-27T06:35:02Z] Outcoming response to 10.254.90.0:42160 with 200 status code
2017/09/27 06:35:02 http2: server: error reading preface from client 10.254.86.0:45166: bogus greeting "GET /api/sockjs/122/05lm"

4:What did you expect to see ?
I would like to be able to correctly enter the container to run the command

**Comment by floreks** [comment]
#2407
