### ISSUE TITLE
localhost:8001/ui is directing to wrong URL

### ISSUE THREAD

**Issue by vongohren** [kubernetes/dashboard#2419]
##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.0
Kubernetes version: 1.7.4 og pool and master cluster version 1.7.6
Running on GCE
```

##### Steps to reproduce
Have the defualt GCE cluster running with 1.7.5. Verify the dashboard works on http://localhost:8001/ui
Then try to deploy the recomended version:
https://github.com/kubernetes/dashboard/blob/master/src/deploy/recommended/kubernetes-dashboard.yaml
Then do
```kubectl proxy```
Go to http://localhost:8001/ui/

##### Observed result
Redircets to: http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy

Which gives a blank page because it cant load the js and different things.

##### Expected result
Redirect to: http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/
WITH THE / AT THE END
And show the dashboard

**Comment by floreks** [comment]
Not a dashboard issue. API server is reponsible for redirect. We are updating latest core version but old version will stay this way.

**Comment by maciaszczykm** [comment]
Problem is at core repository. I am already working on a fix, you can check progress here: https://github.com/kubernetes/kubernetes/pull/53046.

**Comment by gabrielfsousa** [comment]
when this problem will be fixed ?

**Comment by floreks** [comment]
Wrong redirect was already fixed in core (https://github.com/kubernetes/kubernetes/issues/52729). It's up to them if they cherry pick it to 1.7 releases (probably not). 1.8 should contain this fix so if you upgrade kubernetes then it should be solved.

**Comment by web-apply** [comment]
https://localhosts.mobi/8001 here a good solution.
