### ISSUE TITLE
Accessing "/kubernetes-dashboard/proxy" path with no trailing slash results in blank page

### ISSUE THREAD

**Issue by PanJ** [kubernetes/dashboard#2426]
##### Environment

```
Dashboard version: 1.6.1
Kubernetes version: 1.7.6
Operating system: cos
Node.js version: 7.9.0
Go version: -
```

##### Steps to reproduce

```
$> kubectl proxy
```
- And then browse to `http://localhost:8001/ui`
- The page will be redirect to `http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy` (See https://github.com/kubernetes/kubernetes/blob/1bfef70836eff21d0e2945b5b786eb806b43ad92/pkg/routes/ui.go#L25)

##### Observed result

Blank page is shown. Error log indicated 404 error in fetching asset files
##### Expected result

Show a dashboard. The result will be correct when adding trailing slash to URL

**Comment by floreks** [comment]
First check our wiki and closed issues.

**Comment by PanJ** [comment]
@floreks Thanks for pointing to [wiki page](https://github.com/kubernetes/dashboard/wiki/FAQ#i-am-seeing-404-errors-when-trying-to-access-dashbord-dashboard-resources-can-not-be-loaded). I did tried to find previous issues first but the result didn't come out.
