### ISSUE TITLE
Permalink 404: git.io/kube-dashboard

### ISSUE THREAD

**Issue by macropin** [kubernetes/dashboard#2437]
Installation instructions often reference the git.io permalink: `kubectl create -f https://git.io/kube-dashboard`. This no longer works and the link 404's.

**Comment by floreks** [comment]
Any example of documentation/wiki where this link still exists?

**Comment by maciaszczykm** [comment]
I could not find it anywhere: https://github.com/kubernetes/dashboard/search?q=git.io%2Fkube-dashboard&type=Code&utf8=%E2%9C%93

**Comment by maciaszczykm** [comment]
Closing. If it is about documentation at kubernetes.io, then it is a duplicate of https://github.com/kubernetes/dashboard/issues/1719. We have to fix this ASAP.
