### ISSUE TITLE
Downloaded log file behaves strangely

### ISSUE THREAD

**Issue by Globegitter** [kubernetes/dashboard#2439]
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version: 1.7.3
```

##### Steps to reproduce
Go to a pod's logs and download the log file

##### Observed result
log files start and end with `'`, FireFox on my OS (elementary OS, which is based on Ubuntu 16.04) recognises the file as Gzip archive and VS Code shows an error message when trying to open the file

##### Expected result
It would download the file that is recognized as a text file

##### Comments
This is not a super high priority issue imo as I could manage to open the text file.

**Comment by cheld** [comment]
I could reproduce: Firefox adds quotes to the beginning and end of filename. Does not happen when using Chrome

**Comment by maciaszczykm** [comment]
We will track it from #2420 just like other browser-specific bugs.
