### ISSUE TITLE
Not able to load overview when there are a lot of "Completed" pods

### ISSUE THREAD

**Issue by joshes** [kubernetes/dashboard#2442]
##### Environment

```
Dashboard version:
kubernetes-dashboard-0.2.1 installed via Helm

Kubernetes version:
Kubernetes 1.7.5 (using kops) with the following flag set to get cron job support:

  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"

Operating system: 
Mac OSX 10.12.6

Node.js version:
$ node --version
v8.6.0

Go version:
$ go version
go version go1.9 darwin/amd64
```

##### Steps to reproduce
Create a cron job and have it run on a frequent schedule. Go to the overview URL http://localhost:8080/#!/overview?namespace=default - then navigate to the namespace where the jobs were run (in my case develop) - http://localhost:8080/#!/overview?namespace=develop

##### Observed result
After some time, the ui appears to be overwhelmed by the "Completed" pods showing up in the dashboard, even though they are paged. Effectively, the UI would simply not update, finally ending in an error and going back to the default namespace.

##### Expected result
Perhaps hide "Completed" pods or at the least not block the UI

##### Comments
As cron jobs aren't fully supported until k8s 1.8, I'm not sure if this is a bug per se as it would seem possible to reproduce this simply by having a lot of pods, regardless of state would be my assumption.

**Comment by joshes** [comment]
I should note, that once I ran the following to remove the "Completed" cron jobs, the UI worked as expected.

`kubectl get po -a | grep Completed  | awk '{print $1}' | xargs kubectl delete po`

So the immediate workaround will be to run some kind of cleanup job to not hit this.

**Comment by floreks** [comment]
Interesting. Do you have any resource limits (CPU, memory, etc.) set for Dashboard or for namespace that Dashboard is running in?

**Comment by cheld** [comment]
Do you know how many completed pods did you have bevore clean up?

**Comment by joshes** [comment]
@floreks my limits set in the `values.yaml` are:
```
resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi
```

@cheld not sure, over 100 would be a guess, I currently have 127 and the issue is not showing itself. 

I'll keep an eye on it throughout the day and will update with any new info.

Thanks.

**Comment by floreks** [comment]
@joshes I believe that low resource limits are causing the troubles here. Dashboard might be running out of memory. Pagination is done in backend but we always have to load almost all resources running on the cluster (or in a namespace) when viewing overview page. API server does not support any kind of pagination so we have to do it on our end. 

We have set a bit higher limits in the core by default.
```
limits:
  cpu: 100m
  memory: 300Mi
requests:
  cpu: 100m
  memory: 100Mi
```

**Comment by joshes** [comment]
@floreks Thanks, I'll update to reflect your limits. I'll go ahead and close this as thats most likely the solve.
