### ISSUE TITLE
Update API versions and groups

### ISSUE THREAD

**Issue by zouyee** [kubernetes/dashboard#2454]
- [x] update client-go(v5.0) for kubernetes 1.8 which will be cut in this weekend

- [x] migrate rbac from vbeta1 to v1

- [x] migrate DaemonSet, Deployment, ReplicaSet, and StatefulSet from v1beta1 to v1beta2

- [x] migrate storage from v1beta1 to v1

**Comment by maciaszczykm** [comment]
`client-go` migration is partly done as we have switched to master branch. When release will be out it should be easier to migrate.

**Comment by floreks** [comment]
Please open single PR when doing such small changes.

**Comment by floreks** [comment]
Closing as client-go was updated to `v5.0.0` in our deps.

**Comment by maciaszczykm** [comment]
Taking care of it.
