### ISSUE TITLE
Update CI cluster

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2462]
Currently, we are using hyperkube with Kubernetes 1.5.4 and it is too old. Roles, cron jobs etc. do no longer exist in it and it produces `server could not find requested resource` errors. We have to use a version compatible with our current dependencies (now 1.8.0). 

Until migration will be done, all stories have to stay disabled.

**Comment by cheld** [comment]
Another option might be minikube without virtual box. Just checked and it seems they officially support running without hypervisor!

**Comment by maciaszczykm** [comment]
https://github.com/bitnami/kubernetes-travis
