### ISSUE TITLE
Add option/button for OAuth logout

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/dashboard#2464]
I have setup oauth2_proxy in front of kube-dashboard and have it working well.

One feature that is suboptomal though, is when the user wants to logout, they must change the url to be /oauth/sign_out manually in the location bar and hit enter.

Could we add an option to the cli to take in a partial url '/oauth/sign_out' to add to an optionally displayed logout link on the UI that would just link to the specified url? Clicking on the link should cause the proxy to do the proper logout.

**Comment by dbogatov** [comment]
I would be interested in this feature too.
For now, I have to manually type the URL.

**Comment by floreks** [comment]
Will be tracked from #2353 
/close
