### ISSUE TITLE
provide kubernetes-dashboard-init for ppc64le

### ISSUE THREAD

**Issue by victorlsy** [kubernetes/dashboard#2466]
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version: 1.7.6
Operating system: Centos7.3
Node.js version:
Go version:
```

##### Steps to reproduce

    Hi,I created a  k8s cluster on ppc64le platform, now I want to install dashboard , I have to download kubernetes-dashboard.yaml，and then change all of "amd64" to "ppc64le"，last exec "kubectl apply -f kubernetes-dashboard.yaml", but run failed finally. now I know there is not image kubernetes-dashboard-init-ppc64le:v1.0.0 indeed.
    Why not provide image kubernetes-dashboard-init-ppc64le:v1.0.0? or how can I skip to use init image?
##### Observed result

cannot install dashboard
##### Expected result

provide image kubernetes-dashboard-init-ppc64le:v1.0.0

**Comment by floreks** [comment]
```bash
13:25 $ docker pull gcr.io/google_containers/kubernetes-dashboard-ppc64le:v1.7.1
v1.7.1: Pulling from google_containers/kubernetes-dashboard-ppc64le
7df55624ed5d: Pull complete 
Digest: sha256:d74a63e3e7ae7b33773b36d4820c006975200e44092065bbe9a0f0a8cd55f976
Status: Downloaded newer image for gcr.io/google_containers/kubernetes-dashboard-ppc64le:v1.7.1
```

It does exist. Closing as invalid.

**Comment by victorlsy** [comment]
not kubernetes-dashboard-ppc64le:v1.7.1 , it's kubernetes-dashboard-init-ppc64le:v1.0.0

**Comment by floreks** [comment]
Everything is described in here: https://github.com/kubernetes/dashboard/wiki/Installation#official-release
