### ISSUE TITLE
Wrong number of running and pending pods

### ISSUE THREAD

**Issue by f-higashi** [kubernetes/dashboard#247]
Hi,

Number of running and pending pods in replicasets view shows number of 'current' and 'desired - current' of replicas currently.
So even when pods status is failed, it is counted as running.

I think it is better to change display (e.g. 'x pods created, y desired') 
or to get pods of replicaset and count them such as 'kubectl describe' command.

```
$ kubectl describe rc noimage
...
...
Replicas:       2 current / 2 desired
Pods Status:    0 Running / 2 Waiting / 0 Succeeded / 0 Failed
...
```

Actual view

![wrongnumber](https://cloud.githubusercontent.com/assets/8746742/12290559/db75d08a-ba25-11e5-993a-2a3c8d2bb0a8.PNG)

Proposal

```
0 pods running, 2 waiting
```

Other case

```
$ kubectl describe rc jenkins
...
Replicas:       2 current / 3 desired
Pods Status:    2 Running / 0 Waiting / 0 Succeeded / 0 Failed
...
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Reason          Message

  1d            17s             2879    {replication-controller }                       FailedCreate    Error creating: Pod "jenkins-" is forbidden: limited to 5 pods
```

Actual view

![limit](https://cloud.githubusercontent.com/assets/8746742/12290768/e53f284a-ba26-11e5-84d1-12c2f841a835.PNG)

Proposal:

```
2 pods created, 3 desired
2 pods running
```
If some pods is not created, show number of created and desired too.

What do you think?

**Comment by bryk** [comment]
Thanks for the bug report! :) We'll look into this shortly

**Comment by bryk** [comment]
I'm starting work on this.

**Comment by ukasamgithub** [comment]
3 current / 3 desired
Pods Status:  0 Running / 3 Waiting / 0 Succeeded / 0 Failed

Please what is problem here, need help
