### ISSUE TITLE
Monitor display exception

### ISSUE THREAD

**Issue by 361007018** [kubernetes/dashboard#2470]
##### Environment

```
Dashboard version: 1.6.3
Kubernetes version: 1.8.0
Operating system: CentOS 7.3(1611)
```

##### Observed result

![image](https://user-images.githubusercontent.com/13548195/31527502-4c05128a-b000-11e7-9aae-044334b3c072.png)

##### Comments
It appears that there is an abnormality on the high-resolution display.Such as surfacebook.

**Comment by floreks** [comment]
I don't think that resolution is an issue here. What browser are you using?

**Comment by 361007018** [comment]
I'm using the Chrome browser, and the version number is 61.0.3163.100.It looks like this happens only on my monitor
