### ISSUE TITLE
unable to access dashboard using azure acs engine

### ISSUE THREAD

**Issue by manojRy** [kubernetes/dashboard#2471]
Hello,
I have deployed kubernetes cluster on azure using acs-engine. The deployment was successfull I can also execute all the kubectl commands. To view the dash board I have ssh into master node and executed `kubectl poxy` on it and it has started to serve on local host but I am unable to see any dashboard when I give the `http://privateIp:8001/ui` (I am behind a corporate firewall and can use only private ip) in the browser. I can see the dashboard is already running with `kubectl get pods --all-namespaces`. I have also tried to set an ssh tunnel from my windows host machine and ssh into the master node and execute `kubectl proxy` this time I am recieving an connection refused error when I access `http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/workload?namespace=_all` in the browser.

Thanks.

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/wiki/Accessing-dashboard

**Comment by manojRy** [comment]
Thanks @floreks , I receive an unauthorized error when I point to dashboard `https://mmskubetest.westeurope.cloudapp.azure.com/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy`, it hasn't asked me to provide credentials.

**Comment by floreks** [comment]
Your apiserver is exposed but is not accessible from outside. You wouldn't need to install user certificate in the browser to pass apiserver authentication and authorization.

**Comment by manojRy** [comment]
@floreks, sorry but can you say how can I overcome this. Do I need to specify that it should use private ip instead or any other method?. Thanks for the quick reply

**Comment by floreks** [comment]
Did you read accessing guide that I have linked? Everything is described in there.

**Comment by brobichaud** [comment]
I'm trying to do the same thing. Following the instructions at the linked page results in a response of:
{
kind: "Status",
apiVersion: "v1",
metadata: { },
status: "Failure",
message: "no endpoints available for service "kubernetes-dashboard"",
reason: "ServiceUnavailable",
code: 503
}

kubectl cluster-info shows a valid url for the dashboard. Any clues what I'm doing wrong?
