### ISSUE TITLE
no values in cpu and memory columns 

### ISSUE THREAD

**Issue by lghinet** [kubernetes/dashboard#2472]
```
Dashboard version:  v1.7.1
Kubernetes version: 1.8.1
Operating system: ubuntu 16.04
Node.js version: -
Go version: -
```

hello 
i cannot see cpu and memory loads in pods list, 
and no errors 
and i do not use docker i use https://github.com/kubernetes-incubator/cri-containerd

![image](https://user-images.githubusercontent.com/12889810/31543327-3a56a4fe-b01e-11e7-91df-ac350ca27158.png)

but i have cluster graphs 
![image](https://user-images.githubusercontent.com/12889810/31543420-9c383cc8-b01e-11e7-8eaf-ddc43a7e18ee.png)

logs from dashboard 
```
2017/10/13 10:50:12 Getting list of third party resources
2017/10/13 10:50:12 the server could not find the requested resource
2017/10/13 10:50:12 [2017-10-13T10:50:12Z] Outcoming response to 10.200.57.0:37180 with 404 status code
2017/10/13 10:50:12 [2017-10-13T10:50:12Z] Outcoming response to 10.200.57.0:37180 with 200 status code
2017/10/13 10:50:12 [2017-10-13T10:50:12Z] Incoming HTTP/2.0 GET /api/v1/workload?filterBy=&amp;itemsPerPage=15&amp;name=&amp;page=1&amp;sortBy=d,creationTimestamp request from 10.200.57.0:37180: {}
2017/10/13 10:50:12 Getting lists of all workloads
2017/10/13 10:50:12 No metric client provided. Skipping metrics.
2017/10/13 10:50:12 No metric client provided. Skipping metrics.
2017/10/13 10:50:12 No metric client provided. Skipping metrics.
2017/10/13 10:50:12 No metric client provided. Skipping metrics.
2017/10/13 10:50:12 No metric client provided. Skipping metrics.
2017/10/13 10:50:12 No metric client provided. Skipping metrics.
2017/10/13 10:50:12 Getting pod metrics
2017/10/13 10:50:12 [2017-10-13T10:50:12Z] Outcoming response to 10.200.57.0:37180 with 200 status code
2017/10/13 10:50:14 Getting application global configuration
2017/10/13 10:50:14 Application configuration {"serverTime":1507891814127}
2017/10/13 10:50:14 [2017-10-13T10:50:14Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 10.200.57.0:37180: {}
```

logs from heapster 
```
I1013 10:45:39.915794       1 heapster.go:72] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
I1013 10:45:39.915861       1 heapster.go:73] Heapster version v1.4.3
I1013 10:45:39.916247       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version v1
I1013 10:45:39.916281       1 configs.go:62] Using kubelet port 10255
I1013 10:45:39.950333       1 influxdb.go:278] created influxdb sink with options: host:monitoring-influxdb.kube-system.svc:8086 user:root db:k8s
I1013 10:45:39.950380       1 heapster.go:196] Starting with InfluxDB Sink
I1013 10:45:39.950387       1 heapster.go:196] Starting with Metric Sink
I1013 10:45:39.968696       1 heapster.go:106] Starting heapster on port 8082
I1013 10:46:05.115964       1 influxdb.go:241] Created database "k8s" on influxDB server at "monitoring-influxdb.kube-system.svc:8086"
```

**Comment by floreks** [comment]
> and i do not use docker i use https://github.com/kubernetes-incubator/cri-containerd

That's probably the reason. We are getting metrics from heapster and it is getting metrics from cluster in 2 ways. Cluster view is accessing node-level metrics and pod list view is accessing pod-level metrics. I think that pod-level metrics depend somehow on CRI.

You can check these endpoints for data. Adjust them to your environment. If pod-level metrics will be empty then that is the reason. Heapster is not gathering data from your containers.

**Node-level metrics**
`http://192.168.30.148:32553/api/v1/model/nodes/floreks-celsius-w530-power/metrics/cpu/usage`

**Pod-level metrics**
`http://192.168.30.148:32553/api/v1/model/namespaces/kube-system/pods/kube-proxy-9ljm7/metrics/cpu/usage`

**Comment by maciaszczykm** [comment]
Any update?

**Comment by maciaszczykm** [comment]
We cannot go further without any additional information. It might be a problem with heapster, that is not collecting metrics from containerd. Please reopen after providing us missing details.

**Comment by VA-PLE** [comment]
Hi, I have the same problem. Tell me what data you need for the fix. And tell me how I can collect them

**Comment by maciaszczykm** [comment]
@VA-PLE Open a new issue.
