### ISSUE TITLE
 Get http://172.18.0.16:8080/version: dial tcp 172.18.0.16:8080: timeout but curl ok

### ISSUE THREAD

**Issue by lijingcsu** [kubernetes/dashboard#2475]
Dashboard version:1.7.0
Kubernetes version:1.7.2
Operating system:centos7.2
 
kubuctl create -f kubernetes-dashboard.yaml, I rewrote - --apiserver-host=http://172.18.0.16:8080, this ip is my kube-master node,  I found this problem:
![qq 20171015205603](https://user-images.githubusercontent.com/8297694/31584950-57e27dc6-b1eb-11e7-865d-55c44732db63.png)

what's the problem? 
help

**Comment by floreks** [comment]
This is a cluster issue. Error message clearly says that provided ip is not reachable from inside the container.

**Comment by floreks** [comment]
Closing as invalid. It's best not to provide `--apiserver-host` param at all when running kubernetes dashboard inside the cluster. It is only there in case user want to use it in standalone mode.
