### ISSUE TITLE
how to config a user to login

### ISSUE THREAD

**Issue by gensmusic** [kubernetes/dashboard#2476]
##### Environment

Still don't know how to login!!
I update dashboard to  1.7.1 then I got the login view.
I want to login with Bearer token. But I don't know how to config a user!
Can anyone give me an example?
Let's say I want to config a user with read permissions such as nodes, namespaces, configmap, pods ... Only read permissions!
How can I make it ?

```
Dashboard version: 1.7.1
Kubernetes version: 1.7.4
Operating system: centos7.2
Node.js version:
Go version:
```

**Comment by floreks** [comment]
Read documentation: https://github.com/kubernetes/dashboard/wiki/Access-control

**Comment by kfkawalec** [comment]
I have the same problem and I HAVE read documentation many times, but if someone is not expert in kubernetes it's hard to imaginate how to to this.
I see couple question about this topic, maybe this is good idea to add example how to add bearer token with correct perminision?

**Comment by stychu** [comment]
I do upvote this thread. I think there should be some examples showing some approach to do it. I did read docs also and I'm still confused as hell.
 Im experiencing
#2522 
```
Error: 'ssh: rejected: connect failed (Connection refused)'
Trying to reach: 'http://10.4.5.13:9090/'
```
 I guesss once I would be able to pass this problem then there will be another with the approach for loggin to the dashboard for example using bearer. So yeah it would be awesome !

**Comment by maciaszczykm** [comment]
It is in wiki and will be added soon to https://github.com/kubernetes/dashboard/pull/2473.

**Comment by cheld** [comment]
I will have a look at the docs

**Comment by maciaszczykm** [comment]
@cheld Good, update them if you need.
