### ISSUE TITLE
Default service-account is used to download logs

### ISSUE THREAD

**Issue by onesolpark** [kubernetes/dashboard#2479]
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version: 1.7.4
Operating system: CentOS 7
```

##### Steps to reproduce
1. Install dashboard with minimum role that only has roles that can watch secrets and get metrics from heapster.

2. Login through the login page of dashboard with cluster-admin account.
    - In my case, I used token /w appropriate roles but I assume using kubeconfig would not be a problem.

3. Download log file from any pod.

##### Observed result
Dashboard tries to use the minimum service-account rather than using the token provided during login.
ERROR:
system:serviceaccount:kube-dashboard doesn't have the authority to ~~~

##### Expected result
Should use the token provided during login to download log file (send API to apiserver).

##### Comments
I'm not really sure if this is intended(Using service-account rather than the provided token in login page) or not but I personally think tokens that are provided during login should be used. (If it is truly intended)

**Comment by floreks** [comment]
In [here](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/apihandler.go#L2173)  you can see that we are using client created based on request. If you are logged in then it will be authenticated user. 

Check your cookies to see if token used to authenticate user was actually saved.

**Comment by onesolpark** [comment]
Seems to have happened due to cookie cache.
Thanks anyway.
