### ISSUE TITLE
Failed to scale pod on dashboard

### ISSUE THREAD

**Issue by 361007018** [kubernetes/dashboard#2484]
##### Environment

```
Dashboard version: 1.6.3
Kubernetes version: 1.8.1
Operating system: CentOS 7.3
Node.js version:
Go version:
```

##### Steps to reproduce
Tried to scale pod on dashboard
![image](https://user-images.githubusercontent.com/13548195/31650051-3990a1aa-b348-11e7-96f1-6de49cb6083c.png)
![image](https://user-images.githubusercontent.com/13548195/31650067-489052ea-b348-11e7-9ea0-e55f9803b23d.png)

##### Observed result
Got a http status code 404
![image](https://user-images.githubusercontent.com/13548195/31650141-96c710c0-b348-11e7-920c-b0c85272351e.png)

**Comment by floreks** [comment]
Update dashboard to latest version. It os fixed there.
