### ISSUE TITLE
cannot list nodes at the cluster scope

### ISSUE THREAD

**Issue by fanux** [kubernetes/dashboard#2485]
##### Environment
using kubeadm to install k8s.

install dashboard: 
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

```
Dashboard version: 
gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
Kubernetes version:
1.8
Operating system:
centos7.2
```

##### Steps to reproduce
install k8s and then install dashboard, using nodeport

##### Observed result
dashboard can't show namespace, pod ... 

nodes is forbidden: User "system:bootstrap:372455" cannot list nodes at the cluster scope

##### Expected result
dashborad can show all the object

##### Comments
I can login to dashboard, but nothing show on it

**Comment by floreks** [comment]
Works as intended. Log in with user that has access to cluster resources. This is how authorization mechanism works in kubernetes.

https://github.com/kubernetes/dashboard/wiki/Access-control

**Comment by fanux** [comment]
I am using kubectl -n kube-system describe secret namespace-controller-token-9hdfr to print a token. and fill the output token in the dashboard, but came out the error:
```
namespaces is forbidden: User "system:serviceaccount:kube-system:replicaset-controller" cannot list namespaces at the cluster scope
```
and still can not show objects

**Comment by floreks** [comment]
Read kubernetes documentation first. Without understanding how authentication and authorization works you will not be able to securely use kubernetes and kubernetes dashboard.

**Comment by fanux** [comment]
I still read it, but have no idea about it. 😢  just tell me which secret will work?
```
[root@iZj6cj36enzsqq4f96ww9yZ ~]# kubectl -n kube-system get secret
NAME                                     TYPE                                  DATA      AGE
attachdetach-controller-token-tstgx      kubernetes.io/service-account-token   3         3h
bootstrap-signer-token-nhqq7             kubernetes.io/service-account-token   3         3h
bootstrap-token-372455                   bootstrap.kubernetes.io/token         7         3h
calico-cni-plugin-token-bccrh            kubernetes.io/service-account-token   3         3h
calico-kube-controllers-token-hpp2x      kubernetes.io/service-account-token   3         3h
certificate-controller-token-8rx9f       kubernetes.io/service-account-token   3         3h
cronjob-controller-token-5t9m6           kubernetes.io/service-account-token   3         3h
daemon-set-controller-token-fhfz9        kubernetes.io/service-account-token   3         3h
default-token-xwtwp                      kubernetes.io/service-account-token   3         3h
deployment-controller-token-bx9bq        kubernetes.io/service-account-token   3         3h
disruption-controller-token-dk7nt        kubernetes.io/service-account-token   3         3h
endpoint-controller-token-bdjm9          kubernetes.io/service-account-token   3         3h
generic-garbage-collector-token-qhh9h    kubernetes.io/service-account-token   3         3h
horizontal-pod-autoscaler-token-f6lvf    kubernetes.io/service-account-token   3         3h
job-controller-token-qqm4g               kubernetes.io/service-account-token   3         3h
kube-dns-token-slwfd                     kubernetes.io/service-account-token   3         3h
kube-proxy-token-j7bld                   kubernetes.io/service-account-token   3         3h
kubernetes-dashboard-certs               Opaque                                2         3h
kubernetes-dashboard-key-holder          Opaque                                2         3h
kubernetes-dashboard-token-gtqrx         kubernetes.io/service-account-token   3         3h
namespace-controller-token-9hdfr         kubernetes.io/service-account-token   3         3h
node-controller-token-2flvx              kubernetes.io/service-account-token   3         3h
persistent-volume-binder-token-pw89m     kubernetes.io/service-account-token   3         3h
pod-garbage-collector-token-str5g        kubernetes.io/service-account-token   3         3h
replicaset-controller-token-mc5qp        kubernetes.io/service-account-token   3         3h
replication-controller-token-vw4jg       kubernetes.io/service-account-token   3         3h
resourcequota-controller-token-klmnt     kubernetes.io/service-account-token   3         3h
service-account-controller-token-fb2ks   kubernetes.io/service-account-token   3         3h
service-controller-token-5575x           kubernetes.io/service-account-token   3         3h
statefulset-controller-token-sw6zl       kubernetes.io/service-account-token   3         3h
token-cleaner-token-55ssx                kubernetes.io/service-account-token   3         3h
ttl-controller-token-z8qv7               kubernetes.io/service-account-token   3         3h
```

**Comment by maciaszczykm** [comment]
@fanux These are cluster service accounts and you should not use them. Create your own and use it. You should decide which access rights will be assigned etc.

**Comment by floreks** [comment]
Possibly none of default will have the privileges you seek for. You need to create new Service Account and define your own Role with needed permissions.

Read about how to create `Service Account` and define your own `Role` with `RoleBinding`.

https://kubernetes.io/docs/admin/authorization/rbac/
https://kubernetes.io/docs/admin/authentication/

Sample SA, Role and RoleBinding can be found at the top of our deployment file.
https://github.com/kubernetes/dashboard/blob/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by fanux** [comment]
[root@dev-86-208 kubeadm]# kubectl get pods -o wide -n kube-system
NAME                                       READY     STATUS    RESTARTS   AGE       IP               NODE
calico-etcd-t4p9v                          1/1       Running   0          1h        10.1.86.208      dev-86-208
calico-kube-controllers-6ff88bf6d4-qmgm9   1/1       Running   0          1h        10.1.86.208      dev-86-208
calico-node-c7hss                          2/2       Running   1          1h        10.1.86.206      dev-86-206
calico-node-clsw6                          2/2       Running   1          1h        10.1.86.207      dev-86-207
calico-node-xq59n                          2/2       Running   0          1h        10.1.86.208      dev-86-208
etcd-dev-86-208                            1/1       Running   0          1h        10.1.86.208      dev-86-208
kube-apiserver-dev-86-208                  1/1       Running   0          1h        10.1.86.208      dev-86-208
kube-controller-manager-dev-86-208         1/1       Running   0          1h        10.1.86.208      dev-86-208
kube-dns-545bc4bfd4-qqszn                  3/3       Running   0          1h        192.168.71.193   dev-86-208
kube-proxy-5n8t7                           1/1       Running   0          1h        10.1.86.206      dev-86-206
kube-proxy-6xm2p                           1/1       Running   1          1h        10.1.86.207      dev-86-207
kube-proxy-rt9tl                           1/1       Running   0          1h        10.1.86.208      dev-86-208
kube-scheduler-dev-86-208                  1/1       Running   0          1h        10.1.86.208      dev-86-208
kubernetes-dashboard-69c5c78645-nzvmp      1/1       Running   0          9m        192.168.209.65   dev-86-206

I can't access to dashboard, master is 10.1.86.208 dashboard is 10.1.86.206. 
``` 
[root@dev-86-208 kubeadm]# kubectl -n kube-system get service kubernetes-dashboard
NAME                   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes-dashboard   NodePort   10.111.199.204   <none>        80:32148/TCP   7m
```
https://10.1.86.206:32148 is can't access, why?

**Comment by floreks** [comment]
Looks like networking issue. Try using `kubectl proxy` method instead.
