### ISSUE TITLE
Update minikube to version supporting Kubernetes 1.8

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2494]
Blocks #2438.

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/minikube/releases

**Comment by zouyee** [comment]
https://github.com/kubernetes/minikube/pull/2082

**Comment by floreks** [comment]
https://github.com/kubernetes/minikube/pull/2060 was already merged. Also `client-go v5` was not yet released. They are still working on it: https://github.com/kubernetes/client-go/pull/313

**Comment by maciaszczykm** [comment]
@zouyee We will do it on our own. There were a lot of breaking changes recently and your pull requests to core and [minikube](https://github.com/kubernetes/minikube/pull/2081) have just been wrong. None of them would work. Did you actually test them? 

Please stop sending more pull requests to other repositories with Dashboard's version update.

**Comment by zouyee** [comment]
ok, this PR has been closed.
