### ISSUE TITLE
Design updates

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2508]
As discussed during last SIG UI we should think about redesigning the whole app starting from detail pages. Currently, these views are unlike in other dashboards and not user-friendly.

These are few examples of what we have right now:

![image](https://user-images.githubusercontent.com/2823399/31820976-b7e89532-b5a3-11e7-8a30-f28625403605.png)

- a lot of empty space
- important data with the small regular font not visible at first look
- no headers (data in `label: value` format)
- a lot of blank space
- very basic styling (looks old)
- label component is changing whole views when there are many labels available

Review of other UIs is available in #1333.

**Comment by maciaszczykm** [comment]
cc @rahuldhide @cheld @floreks

**Comment by justjanne** [comment]
An interesting question, with regards to design updates, might be how to handle smaller screens. Currently the UI starts breaking down below 1280x720, which affects smaller laptops, but also tablets.
