### ISSUE TITLE
Cant access the dashboard

### ISSUE THREAD

**Issue by stychu** [kubernetes/dashboard#2522]
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version: Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"...", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"...", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Operating system: linux
Node.js version: v6.10.0
```

##### Steps to reproduce
Run kubectl proxy
http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy

##### Observed result
```
Error: 'ssh: rejected: connect failed (Connection refused)'
Trying to reach: 'http://10.4.5.13:9090/'
```

##### Expected result
Able to access to the dashboard

##### Comments
I thought that after runnin `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml` I would be able to access the dashboard with minimal priviledges but I got this error. Im stuck with this for 2 days already and can't figure it out how to solve this problem.

**Comment by maciaszczykm** [comment]
What is your container status (`kubectl describe pod...`)? If it crashed it might be out of memory problem or something else, we need more information. This can be an issue with proxy rejecting requests., doesn't look like Dashboard issue.

**Comment by stychu** [comment]
Nope. Accessing this `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/` resolves as the same error

this is the describe of the dashboard pod
```Name:		kubernetes-dashboard-2932672137-6r0hf
Namespace:	kube-system
Node:		gke-safemotos-staging-default-pool-6ae11e82-9k91/10.132.0.2
Start Time:	Tue, 24 Oct 2017 14:00:55 +0200
Labels:		k8s-app=kubernetes-dashboard
		pod-template-hash=2932672137
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-2932672137","uid":"fd2cf885-b8b2-11e7-8...
Status:		Running
IP:		10.4.5.13
Created By:	ReplicaSet/kubernetes-dashboard-2932672137
Controlled By:	ReplicaSet/kubernetes-dashboard-2932672137
Init Containers:
  kubernetes-dashboard-init:
    Container ID:	docker://bd42a3845656c3287de52b101655f761431879bd3d84c923ce3f63c6d05af873
    Image:		gcr.io/google_containers/kubernetes-dashboard-init-amd64:v1.0.1
    Image ID:		docker-pullable://gcr.io/google_containers/kubernetes-dashboard-init-amd64@sha256:7e0356253d780007a39820b24676676dd40902cc1ee02ba28d77697149b090a8
    Port:		<none>
    State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Tue, 24 Oct 2017 14:01:06 +0200
      Finished:		Tue, 24 Oct 2017 14:01:07 +0200
    Ready:		True
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-gbbbf (ro)
Containers:
  kubernetes-dashboard:
    Container ID:	docker://5aa6f0d32b839228c749ea40f6434120f7206511040c315b4504d3d905746519
    Image:		gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
    Image ID:		docker-pullable://gcr.io/google_containers/kubernetes-dashboard-amd64@sha256:327cfef378e88ffbc327f98dd24adacf6c9363c042db78e922d050f2bdcf6f78
    Port:		8443/TCP
    Args:
      --tls-key-file=/certs/dashboard.key
      --tls-cert-file=/certs/dashboard.crt
    State:		Running
      Started:		Tue, 24 Oct 2017 14:01:13 +0200
    Ready:		True
    Restart Count:	0
    Liveness:		http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:	<none>
    Mounts:
      /certs from kubernetes-dashboard-certs (ro)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-gbbbf (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  kubernetes-dashboard-certs:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	kubernetes-dashboard-certs
    Optional:	false
  tmp-volume:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  kubernetes-dashboard-token-gbbbf:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	kubernetes-dashboard-token-gbbbf
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node-role.kubernetes.io/master:NoSchedule
		node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:		<none>
```

Seems like its running normally.
```
NAME                                    READY     STATUS    RESTARTS   AGE
kubernetes-dashboard-2932672137-6r0hf   1/1       Running   0          1d
```

**Comment by maciaszczykm** [comment]
Are you able to access other apps? It looks like a networking problem. Can you paste logs too?

**Comment by stychu** [comment]
@maciaszczykm what do you mean by other apps ? And in what logs are you interested in ? Dashboard pod ?

**Comment by maciaszczykm** [comment]
By other apps I mean other applications like Dashboard, Heapster, nginx etc.

Can you paste output of `kubectl describe secret kubernetes-dashboard-key-holder -n kube-system`?

**Comment by stychu** [comment]
`Error from server (NotFound): secrets "kubernetes-dashboard-2932672137-6r0hf" not found`

**Comment by maciaszczykm** [comment]
Sorry, the name is `kubernetes-dashboard-certs`, so you should run `kubectl describe secret kubernetes-dashboard-certs - n kube-system`.

https://github.com/kubernetes/dashboard/blob/master/src/deploy/recommended/kubernetes-dashboard.yaml#L27

So your cluster does not have any other application running? You should read the documentation at kubernetes.io to check how to use Kubernetes and access deployed application. This is most probably cluster configuration issue.

**Comment by stychu** [comment]
kubectl describe secret kubernetes-dashboard-certs - n kube-system : 
`Error from server (NotFound): secrets "kubernetes-dashboard-certs" not found`

Ymm sorry if I do misunderstand what do you mean. Im running cluster on GCP with backend server application and Im able to access it via the exposed prot so it seems like here is no problem with accessing. If this is waht did you mean.

**Comment by stychu** [comment]
GCP has some functionalities derived from kubernetes dashboard into its own so i guess its working.
![zrzut ekranu z 2017-10-26 13-19-11](https://user-images.githubusercontent.com/9383657/32050157-23749b74-ba50-11e7-94bb-488d0564b834.png)

**Comment by maciaszczykm** [comment]
This secret should be created from YAML during deployment, but something happened to it. Did you try to redeploy all Dashboard resources?

**Comment by stychu** [comment]
Okay its working finally! I deleted dashboard deployment and secrets and now I am able to see the dashboard via proxy.

**Comment by stychu** [comment]
I think this problem was caused by running this command
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`
without proper access privileges. I did run it and there were some errors about access restriction and I think that this applied some wrong configs in background to the dashboard deployment or something.
Anyway its working now thank you for your help !!!

**Comment by shangyaqi** [comment]
kubectl logs kubernetes-dashboard-845747bdd4-dwk2c -n=kube-system
2018/03/07 09:37:58 Starting overwatch
2018/03/07 09:37:58 Using in-cluster config to connect to apiserver
2018/03/07 09:37:58 Using service account token for csrf signing
2018/03/07 09:37:58 No request provided. Skipping authorization
2018/03/07 09:37:58 Successful initial request to the apiserver, version: v1.9.2
2018/03/07 09:37:58 Generating JWE encryption key
2018/03/07 09:37:58 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/03/07 09:37:58 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/03/07 09:37:58 Initializing JWE encryption key from synchronized object
2018/03/07 09:37:58 Creating in-cluster Heapster client
2018/03/07 09:37:58 Successful request to heapster
2018/03/07 09:37:58 Auto-generating certificates
2018/03/07 09:37:58 Successfuly created and stored certificates
2018/03/07 09:37:58 Serving securely on HTTPS port: 8443
2018/03/07 09:38:48 http: TLS handshake error from 10.244.0.0:53411: tls: first record does not look like a TLS handshake
2018/03/07 09:38:48 http: TLS handshake error from 10.244.0.0:53412: tls: first record does not look like a TLS handshake
2018/03/07 09:38:53 http: TLS handshake error from 10.244.0.0:53429: tls: first record does not look like a TLS handshake
2018/03/07 09:39:23 http: TLS handshake error from 10.244.0.0:53506: tls: first record does not look like a TLS handshake
2018/03/07 09:40:23 http: TLS handshake error from 10.244.0.0:53655: tls: first record does not look like a TLS handshake
2018/03/09 02:05:43 http: TLS handshake error from 10.244.0.0:50549: tls: first record does not look like a TLS handshake
2018/03/09 02:05:43 http: TLS handshake error from 10.244.0.0:50550: tls: first record does not look like a TLS handshake
2018/03/09 02:05:45 http: TLS handshake error from 10.244.0.0:50559: tls: first record does not look like a TLS handshake
2018/03/09 02:05:45 http: TLS handshake error from 10.244.0.0:50560: tls: first record does not look like a TLS handshake
2018/03/09 02:05:45 http: TLS handshake error from 10.244.0.0:50561: tls: first record does not look like a TLS handshake
