### ISSUE TITLE
Recommended setup makes no sense

### ISSUE THREAD

**Issue by cohadar** [kubernetes/dashboard#2527]
What is the point of creating valid custom certs for dashboard?
>>> kubectl create secret generic kubernetes-dashboard-certs --from-file=$HOME/certs -n kube-system

Dashboard will be accessed through k8s api proxy anyways, and will use cert of k8s api.

**Comment by cheld** [comment]
Self-signed certificates are created during startup of Dashboard to secure (to some extend) the cluster internal traffic. If you expose access to Dashboard directly to the internet (e.g. with LoadBalancer) than you should use proper certificates. I will update the documentation

**Comment by floreks** [comment]
> What is the point of creating valid custom certs for dashboard?
>
> kubectl create secret generic kubernetes-dashboard-certs --from-file=$HOME/certs -n kube-system
> Dashboard will be accessed through k8s api proxy anyways, and will use cert of k8s api.

Dashboard **can** be accessed through k8s api proxy, but this is only one way of accessing it. As we do not know how exactly user will access Dashboard, we have to secure the traffic between user's machine and our backend, without that there would be a chance that Dashboard is exposed over plain HTTP without any secure proxy and during logging in credentials would be sent to the server with plain text (open to being hijacked by the attacker).

**Comment by cheld** [comment]
Still, the documentation does not explain your statement

**Comment by floreks** [comment]
You mean that we should basically explain why any webapp with log in functionality that can be made publicly accessible should use HTTPS, not HTTP?

**Comment by cheld** [comment]
The documentation does not describe Loadbalancer access. Only proxy access is described. However, proxy + valid certificates does not make much sense as apiserver-proxy does not validate the Dashboard certificate anyway. 

A potential improvement could be
e.g. 'Recommended setup' rename to 'Setup for direct access without proxy'

**Comment by floreks** [comment]
Are there any other steps that need to be taken before closing this issue? IMHO everything is clear on our end.

**Comment by cheld** [comment]
Updated documentation.
