### ISSUE TITLE
Dashboard upgrade stopped due to 'name' required in non existent port

### ISSUE THREAD

**Issue by renewooller** [kubernetes/dashboard#2529]
```
Dashboard version: 1.7 (IE https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml)
Kubernetes version: 1.6.4, 1.7.2, 1.8.2
Operating system: Linux, ubuntu
Node.js version:
8.5.0
Go version:
NA
```

##### Steps to reproduce
1. Already have a dashboard running, from v1.6.4.
2. Apply the new dashboard: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result
```
dev[~] : kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
secret "kubernetes-dashboard-certs" configured
serviceaccount "kubernetes-dashboard" configured
role "kubernetes-dashboard-minimal" configured
rolebinding "kubernetes-dashboard-minimal" configured
deployment "kubernetes-dashboard" configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The Service "kubernetes-dashboard" is invalid: 
* spec.ports[0].name: Required value
* spec.ports[1].name: Required value
```
##### Expected result
I expected the service to be able to be created

##### Comments
I tried to edit the service to add the name. When I did this, it removed the error for "* spec.ports[0].name: Required value", but the other still existed: "* spec.ports[1].name: Required value". To test, I added another port and then it threw an error for "* spec.ports[2].name: Required value", so it seems to be expecting a portname for the size of the port array plus 1.

**Comment by renewooller** [comment]
Having deleted and recreated all the components, eg:
```
kubectl delete secret kubernetes-dashboard-certs --namespace=kube-system
kubectl delete serviceaccounts kubernetes-dashboard --namespace=kube-system
kubectl delete roles.rbac.authorization.k8s.io kubernetes-dashboard-minimal --namespace=kube-system
kubectl delete rolebindings.rbac.authorization.k8s.io kubernetes-dashboard-minimal --namespace=kube-system
kubectl delete deployments.extensions kubernetes-dashboard --namespace=kube-system
kubectl delete svc kubernetes-dashboard --namespace=kube-system
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```

I end up with no errors, but it isn't working. EG if I visit the /ui page, I get:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

Looking into the errors on the kubernetes-dashboard pod, I see:

```
2017/10/30 06:19:36 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
```

**Comment by maciaszczykm** [comment]
Heapster error is not a problem. You will not be able to see metrics/graphs but everything else should work. You are using Dashboard 1.7 with 1.6 which is not fully supported:

https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix

**Comment by maciaszczykm** [comment]
> no endpoints available for service \"kubernetes-dashboard\"

This is strange. Do `kubectl get svc -n kube-system` and paste results here.

**Comment by renewooller** [comment]
I have this working now by hitting a different endpoint. It looks like the heapster errors are unrelated
