### ISSUE TITLE
remote error: tls: unknown certificate authority

### ISSUE THREAD

**Issue by idczuojun** [kubernetes/dashboard#2534]
##### Environment

```
Dashboard version: v1.7.1
Kubernetes version: v1.7.3
Operating system: CentOS 7.4.1708
Node.js version:
Go version:
```

##### Steps to reproduce

kubectl logs po/kubernetes-dashboard-1679879790-h1c5x -n kube-system
##### Observed result

2017/11/01 10:26:22 http2: server: error reading preface from client 10.254.93.0:60297: remote error: tls: unknown certificate authority

**Comment by maciaszczykm** [comment]
1. When it happens? Steps to reproduce are incomplete.
2. Paste full log.
3. Do you use official YAMLs or is your setup modified somehow?

**Comment by floreks** [comment]
Closing as stale.
