### ISSUE TITLE
Dashboard won't come up

### ISSUE THREAD

**Issue by vrmerlin** [kubernetes/dashboard#2535]
##### Environment

```
Dashboard version: 1.7.1 I think (just downloaded today)
Kubernetes version: 1.8.1
Operating system: RHEL
Node.js version: ? I'm just installing the container
Go version: ? I'm just installing the container
```

##### Steps to reproduce
I have Kubernetes up and running, with a master and three nodes.

I installed the dashboard via the apply command:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
secret "kubernetes-dashboard-certs" created
serviceaccount "kubernetes-dashboard" created
role "kubernetes-dashboard-minimal" created
rolebinding "kubernetes-dashboard-minimal" created
deployment "kubernetes-dashboard" created
service "kubernetes-dashboard" created
```

Using ```kubectl get all --all-namespaces``` it appears that all the dashboard objects came up successfully

I run ```kubectl proxy```, and get the results ```Starting to serve on 127.0.0.1:8001```

I start a Firefox browser on the same machine.

##### Observed result

When I connect to http://localhost:8001/, I can see the list of paths, as I would expect.

When I go to http://localhost:8001/ui, I get this results:

```
Error: 'dial tcp 172.17.0.2:8443: getsockopt: connection refused'
Trying to reach: 'http://172.17.0.2:8443/'
```

##### Expected result

I expected the user interface to come properly.

##### Comments

Why am I getting connection refused? What's failing?

**Comment by cheld** [comment]
The URL changed and is not yet updated in core. Use (as documented):

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Comment by vrmerlin** [comment]
I tried that URL as well, and got the same error:

```
Error: 'dial tcp 172.17.0.2:8443: getsockopt: connection refused'
Trying to reach: 'https://172.17.0.2:8443/'
```

Can we re-open this issue? It's still not working for me.

**Comment by lucbelliveau** [comment]
@vrmerlin Your error is likely related to networking and not dashboard.

**Comment by bxyb214** [comment]
@vrmerlin I got the same error, have you solved it?

**Comment by floreks** [comment]
This issues are most likely not Dashboard related. If you provide some logs showing that this is related to Dashboard then we will reopen. Right now it looks like configuration issue.

**Comment by vrmerlin** [comment]
I got it to work by downloading the YAML directly, and added "hostNetwork: true" to the spec. So, yes, perhaps it's a configuration issue in my environment. Any idea why that would be required though?

**Comment by lucbelliveau** [comment]
@vrmerlin without knowing more about your config it's hard to say - either way this isn't the right place.. maybe open up a stackoverflow question with more details.  My guess would be either your pod networking is broken, or something is wrong with kube-proxy

**Comment by manukasa** [comment]
@vrmerlin  can you please tell me the exact path of the Yaml file you changed "hostNetwork: true"

**Comment by dreamkiller67** [comment]
I am also having this issue ...
