### ISSUE TITLE
Error to exec into pod from Dashboard

### ISSUE THREAD

**Issue by alexlokshin** [kubernetes/dashboard#2538]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Unknown Server Error:
```
No error data available
```

**Comment by azweb76** [comment]
Im running 1.7.1 without issues. However if you run more than 1 dashboard pod, exec will fail.
