### ISSUE TITLE
Switching namespaces while in exec container results in undefined errors, and broken navigation.

### ISSUE THREAD

**Issue by danbopes** [kubernetes/dashboard#2539]
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version: 1.8.1
```

##### Steps to reproduce

Select a namespace: (ie. kube-system)
Goto pods and select a pod.
Click exec (Doesn't matter if the pod has a shell or not).
Change the namespace.

##### Observed result

![image](https://user-images.githubusercontent.com/4589840/32339687-ea0e86fe-bfce-11e7-9857-411823416b1d.png)
None of the links on the left hand side work either.

##### Expected result

I think the expected result should be it redirecting to the main pods index view for that namespace, (It's what happens when you try and goto a pod that doesn't exist in another namespace).

**Comment by floreks** [comment]
This is already fixed by https://github.com/kubernetes/dashboard/pull/2482.
