### ISSUE TITLE
dashboard pod can't run on current kubeadm

### ISSUE THREAD

**Issue by donutloop** [kubernetes/dashboard#2547]
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}

##### Issue details

I can't make the dashboard to run. I am using a fresh kubeadm installation and a weave network.

#####  Steps to reproduce

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

##### Observed result
`kubectl get pods --all-namespaces`

kube-system   etcd-master                            1/1       Running    1          1d
kube-system   kube-apiserver-master                  1/1       Running    2          1d
kube-system   kube-controller-manager-master         1/1       Running    1          1d
kube-system   kube-dns-66ffd5c588-hvcm5              3/3       Running    0          1d
kube-system   kube-proxy-k9bdp                       1/1       Running    0          1d
kube-system   kube-proxy-vvxx9                       1/1       Running    0          1d
kube-system   kube-proxy-w69sd                       1/1       Running    0          1d
kube-system   kube-proxy-zgv2j                       1/1       Running    1          1d
kube-system   kube-scheduler-master                  1/1       Running    1          1d
kube-system   kubernetes-dashboard-747c4f7cf-bsl6l   0/1       Init:0/1   0          1d
kube-system   weave-net-6c7nd                        2/2       Running    0          1d
kube-system   weave-net-ftnhz                        2/2       Running    0          1d
kube-system   weave-net-hbglr                        2/2       Running    0          1d
kube-system   weave-net-ts9sw 

`kubectl logs kubernetes-dashboard-747c4f7cf-bsl6l --namespace=kube-system`

Error from server (BadRequest): container "kubernetes-dashboard" in pod "kubernetes-dashboard-747c4f7cf-bsl6l" is waiting to start: PodInitializing

`kubectl describe nodes`

Name:               master
Roles:              master
Labels:             beta.kubernetes.io/arch=arm
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=master
                    node-role.kubernetes.io/master=
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             node-role.kubernetes.io/master:NoSchedule
CreationTimestamp:  Sun, 05 Nov 2017 17:46:51 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 17:46:47 +0000   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 17:46:47 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 17:46:47 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready            True    Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 18:32:17 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.178.73
  Hostname:    master
Capacity:
 cpu:     4
 memory:  882632Ki
 pods:    110
Allocatable:
 cpu:     4
 memory:  780232Ki
 pods:    110
System Info:
 Machine ID:                 d7866798b7e648d38289364f159bec68
 System UUID:                d7866798b7e648d38289364f159bec68
 Boot ID:                    7601031f-d63b-45fb-a546-bb6c91c900c7
 Kernel Version:             4.4.50-hypriotos-v7+
 OS Image:                   Raspbian GNU/Linux 8 (jessie)
 Operating System:           linux
 Architecture:               arm
 Container Runtime Version:  docker://Unknown
 Kubelet Version:            v1.8.2
 Kube-Proxy Version:         v1.8.2
PodCIDR:                     10.244.0.0/24
ExternalID:                  master
Non-terminated Pods:         (7 in total)
  Namespace                  Name                              CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                              ------------  ----------  ---------------  -------------
  kube-system                etcd-master                       0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-apiserver-master             250m (6%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-controller-manager-master    200m (5%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-dns-66ffd5c588-hvcm5         260m (6%)     0 (0%)      110Mi (14%)      170Mi (22%)
  kube-system                kube-proxy-zgv2j                  0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-scheduler-master             100m (2%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                weave-net-ftnhz                   20m (0%)      0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  830m (20%)    0 (0%)      110Mi (14%)      170Mi (22%)
Events:         <none>

Name:               node02
Roles:              <none>
Labels:             beta.kubernetes.io/arch=arm
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=node02
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
CreationTimestamp:  Sun, 05 Nov 2017 18:46:21 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Mon, 06 Nov 2017 19:42:10 +0000   Sun, 05 Nov 2017 18:46:22 +0000   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Mon, 06 Nov 2017 19:42:10 +0000   Sun, 05 Nov 2017 18:46:22 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 06 Nov 2017 19:42:10 +0000   Sun, 05 Nov 2017 18:46:22 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready            True    Mon, 06 Nov 2017 19:42:10 +0000   Sun, 05 Nov 2017 18:46:42 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.178.75
  Hostname:    node02
Capacity:
 cpu:     4
 memory:  882632Ki
 pods:    110
Allocatable:
 cpu:     4
 memory:  780232Ki
 pods:    110
System Info:
 Machine ID:                 d7866798b7e648d38289364f159bec68
 System UUID:                d7866798b7e648d38289364f159bec68
 Boot ID:                    01f6529a-51ee-4b98-84e5-3f21f39f07b8
 Kernel Version:             4.4.50-hypriotos-v7+
 OS Image:                   Raspbian GNU/Linux 8 (jessie)
 Operating System:           linux
 Architecture:               arm
 Container Runtime Version:  docker://Unknown
 Kubelet Version:            v1.8.2
 Kube-Proxy Version:         v1.8.2
PodCIDR:                     10.244.2.0/24
ExternalID:                  node02
Non-terminated Pods:         (2 in total)
  Namespace                  Name                CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                ------------  ----------  ---------------  -------------
  kube-system                kube-proxy-w69sd    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                weave-net-ts9sw     20m (0%)      0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  20m (0%)      0 (0%)      0 (0%)           0 (0%)
Events:         <none>

Name:               node03
Roles:              <none>
Labels:             beta.kubernetes.io/arch=arm
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=node03
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
CreationTimestamp:  Sun, 05 Nov 2017 18:46:05 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 18:46:05 +0000   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 18:46:05 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 18:46:05 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready            True    Mon, 06 Nov 2017 19:42:11 +0000   Sun, 05 Nov 2017 18:46:25 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.178.76
  Hostname:    node03
Capacity:
 cpu:     4
 memory:  882632Ki
 pods:    110
Allocatable:
 cpu:     4
 memory:  780232Ki
 pods:    110
System Info:
 Machine ID:                 d7866798b7e648d38289364f159bec68
 System UUID:                d7866798b7e648d38289364f159bec68
 Boot ID:                    46b7af0a-71a8-47fe-807e-2f85f22234dd
 Kernel Version:             4.4.50-hypriotos-v7+
 OS Image:                   Raspbian GNU/Linux 8 (jessie)
 Operating System:           linux
 Architecture:               arm
 Container Runtime Version:  docker://Unknown
 Kubelet Version:            v1.8.2
 Kube-Proxy Version:         v1.8.2
PodCIDR:                     10.244.1.0/24
ExternalID:                  node03
Non-terminated Pods:         (2 in total)
  Namespace                  Name                CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                ------------  ----------  ---------------  -------------
  kube-system                kube-proxy-k9bdp    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                weave-net-6c7nd     20m (0%)      0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  20m (0%)      0 (0%)      0 (0%)           0 (0%)
Events:         <none>

Name:               node04
Roles:              <none>
Labels:             beta.kubernetes.io/arch=arm
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=node04
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
CreationTimestamp:  Sun, 05 Nov 2017 18:46:28 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Mon, 06 Nov 2017 19:42:14 +0000   Sun, 05 Nov 2017 18:46:28 +0000   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Mon, 06 Nov 2017 19:42:14 +0000   Sun, 05 Nov 2017 18:46:28 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 06 Nov 2017 19:42:14 +0000   Sun, 05 Nov 2017 18:46:28 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready            True    Mon, 06 Nov 2017 19:42:14 +0000   Sun, 05 Nov 2017 18:46:48 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.178.79
  Hostname:    node04
Capacity:
 cpu:     4
 memory:  882632Ki
 pods:    110
Allocatable:
 cpu:     4
 memory:  780232Ki
 pods:    110
System Info:
 Machine ID:                 d7866798b7e648d38289364f159bec68
 System UUID:                d7866798b7e648d38289364f159bec68
 Boot ID:                    8bc4c321-2187-4dc9-ac3e-e0bd57fbe0fd
 Kernel Version:             4.4.50-hypriotos-v7+
 OS Image:                   Raspbian GNU/Linux 8 (jessie)
 Operating System:           linux
 Architecture:               arm
 Container Runtime Version:  docker://Unknown
 Kubelet Version:            v1.8.2
 Kube-Proxy Version:         v1.8.2
PodCIDR:                     10.244.3.0/24
ExternalID:                  node04
Non-terminated Pods:         (3 in total)
  Namespace                  Name                                    CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                    ------------  ----------  ---------------  -------------
  kube-system                kube-proxy-vvxx9                        0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kubernetes-dashboard-747c4f7cf-bsl6l    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                weave-net-hbglr                         20m (0%)      0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  20m (0%)      0 (0%)      0 (0%)           0 (0%)
Events:         <none>

**Comment by floreks** [comment]
> kubectl logs kubernetes-dashboard-747c4f7cf-bsl6l --namespace=kube-system
>
> Error from server (BadRequest): container "kubernetes-dashboard" in pod "kubernetes-dashboard-747c4f7cf-bsl6l" is waiting to start: PodInitializing

Does it stay in `PodInitializing` state forever?

**Comment by donutloop** [comment]
> Does it stay in PodInitializing state forever?

it's stays forever in that state

`kubectl logs kubernetes-dashboard-747c4f7cf-bsl6l --namespace=kube-system -c kubernetes-dashboard-init`

Error from server (BadRequest): container "kubernetes-dashboard-init" in pod "kubernetes-dashboard-747c4f7cf-bsl6l" is waiting to start: PodInitializing

**Comment by floreks** [comment]
Did you run `kubectl taint nodes --all node-role.kubernetes.io/master-` after `kubeadm init`?

**Comment by donutloop** [comment]
i have executed the following steps 

`kubectl taint nodes --all node-role.kubernetes.io/master-`
node "master" untainted
taint "node-role.kubernetes.io/master:" not found
taint "node-role.kubernetes.io/master:" not found
taint "node-role.kubernetes.io/master:" not found

`kubectl delete -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
`

`kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

Unfortunately, nothing has changed!

` kubectl logs kubernetes-dashboard-747c4f7cf-kvclb  --namespace=kube-system -c kubernetes-dashboard-init`

Error from server (BadRequest): container "kubernetes-dashboard-init" in pod "kubernetes-dashboard-747c4f7cf-kvclb" is waiting to start: PodInitializing

` kubectl logs kubernetes-dashboard-747c4f7cf-kvclb --namespace=kube-system`
Error from server (BadRequest): container "kubernetes-dashboard" in pod "kubernetes-dashboard-747c4f7cf-kvclb" is waiting to start: PodInitializing

**Comment by floreks** [comment]
Run `kubectl describe <dashboard-deployment-name>` and `kubectl describe <dashboard-pod-name>`. Maybe there are some events that can explain why it is not starting.

**Comment by floreks** [comment]
Any progress here?

**Comment by floreks** [comment]
Closing as stale.

**Comment by 0angelic0** [comment]
Hi,

I have the same problem here.

I have followed @floreks  instructions, but no luck.


Here is the output from `kubectl describe pod <dashboard-pod-name> -n kube-system`

<pre>
kubectl describe po/kubernetes-dashboard-747c4f7cf-5sknx -n kube-system
Name:           kubernetes-dashboard-747c4f7cf-5sknx
Namespace:      kube-system
Node:           typt-node-04/128.199.80.153
Start Time:     Fri, 17 Nov 2017 12:37:48 +0700
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=303709379
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-747c4f7cf","uid":"96dbce19-caf4-11e7-9a...
Status:         Pending
IP:
Created By:     ReplicaSet/kubernetes-dashboard-747c4f7cf
Controlled By:  ReplicaSet/kubernetes-dashboard-747c4f7cf
Init Containers:
  kubernetes-dashboard-init:
    Container ID:
    Image:          gcr.io/google_containers/kubernetes-dashboard-init-amd64:v1.0.1
    Image ID:
    Port:           <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-khvtq (ro)
Containers:
  kubernetes-dashboard:
    Container ID:
    Image:         gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
    Image ID:
    Port:          8443/TCP
    Args:
      --tls-key-file=/certs/dashboard.key
      --tls-cert-file=/certs/dashboard.crt
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (ro)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-khvtq (ro)
Conditions:
  Type           Status
  Initialized    False
  Ready          False
  PodScheduled   True
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  kubernetes-dashboard-token-khvtq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-khvtq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                From                   Message
  ----     ------                  ----               ----                   -------
  Normal   Scheduled               22s                default-scheduler      Successfully assigned kubernetes-dashboard-747c4f7cf-5sknx to typt-node-04
  Normal   SuccessfulMountVolume   22s                kubelet, typt-node-04  MountVolume.SetUp succeeded for volume "tmp-volume"
  Normal   SuccessfulMountVolume   22s                kubelet, typt-node-04  MountVolume.SetUp succeeded for volume "kubernetes-dashboard-token-khvtq"
  Normal   SuccessfulMountVolume   22s                kubelet, typt-node-04  MountVolume.SetUp succeeded for volume "kubernetes-dashboard-certs"
  Warning  FailedCreatePodSandBox  14s (x7 over 21s)  kubelet, typt-node-04  Failed create pod sandbox.
  Normal   SandboxChanged          14s (x7 over 20s)  kubelet, typt-node-04  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedSync              13s (x8 over 21s)  kubelet, typt-node-04  Error syncing pod
</pre>


There is Events.

<pre>
Events:
  Type     Reason                  Age                From                   Message
  ----     ------                  ----               ----                   -------
  Normal   Scheduled               22s                default-scheduler      Successfully assigned kubernetes-dashboard-747c4f7cf-5sknx to typt-node-04
  Normal   SuccessfulMountVolume   22s                kubelet, typt-node-04  MountVolume.SetUp succeeded for volume "tmp-volume"
  Normal   SuccessfulMountVolume   22s                kubelet, typt-node-04  MountVolume.SetUp succeeded for volume "kubernetes-dashboard-token-khvtq"
  Normal   SuccessfulMountVolume   22s                kubelet, typt-node-04  MountVolume.SetUp succeeded for volume "kubernetes-dashboard-certs"
  Warning  FailedCreatePodSandBox  14s (x7 over 21s)  kubelet, typt-node-04  Failed create pod sandbox.
  Normal   SandboxChanged          14s (x7 over 20s)  kubelet, typt-node-04  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedSync              13s (x8 over 21s)  kubelet, typt-node-04  Error syncing pod
</pre>

I tried

`kubectl delete po/<dashboard-pod-name>`

and

`kubectl delete -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

Unfortunately, the <dashboard-pod> is in status Init:0/1 forever.

`kubernetes-dashboard-747c4f7cf-5sknx     0/1       Init:0/1   0          7m`

Please help and re-open the issue. Thank you.

**Comment by floreks** [comment]
This is not a Dashboard issue. Look at event warnings:

`FailedCreatePodSandBox: Failed create pod sandbox.`

Similar issues were reported on core/kubeadm repos already: https://github.com/kubernetes/kubeadm/issues/507, https://github.com/kubernetes/kubernetes/issues/55094

**Comment by 0angelic0** [comment]
@floreks, from your references, Restarting docker on all nodes resolved the issue (`systemctl restart docker`).

Thank you very much.

**Comment by donutloop** [comment]
Unfortunately, I do have still have this issue

Here is the output from kubectl describe pod <dashboard-pod-name> -n kube-system

kubectl describe pod kubernetes-dashboard-747c4f7cf-cdmj5  -n kube-system
Name:           kubernetes-dashboard-747c4f7cf-cdmj5
Namespace:      kube-system
Node:           node03/192.168.2.109
Start Time:     Sun, 19 Nov 2017 14:12:06 +0000
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=303709379
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-747c4f7cf","uid":"9f88d58e-cd33-11e7-8a...
Status:         Pending
IP:             
Created By:     ReplicaSet/kubernetes-dashboard-747c4f7cf
Controlled By:  ReplicaSet/kubernetes-dashboard-747c4f7cf
Init Containers:
  kubernetes-dashboard-init:
    Container ID:   
    Image:          gcr.io/google_containers/kubernetes-dashboard-init-amd64:v1.0.1
    Image ID:       
    Port:           <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-kcd74 (ro)
Containers:
  kubernetes-dashboard:
    Container ID:  
    Image:         gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
    Image ID:      
    Port:          8443/TCP
    Args:
      --tls-key-file=/certs/dashboard.key
      --tls-cert-file=/certs/dashboard.crt
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (ro)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-kcd74 (ro)
Conditions:
  Type           Status
  Initialized    False 
  Ready          False 
  PodScheduled   True 
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  kubernetes-dashboard-token-kcd74:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-kcd74
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From               Message
  ----    ------                 ----  ----               -------
  Normal  Scheduled              1m    default-scheduler  Successfully assigned kubernetes-dashboard-747c4f7cf-cdmj5 to node03
  Normal  SuccessfulMountVolume  1m    kubelet, node03    MountVolume.SetUp succeeded for volume "tmp-volume"
  Normal  SuccessfulMountVolume  1m    kubelet, node03    MountVolume.SetUp succeeded for volume "kubernetes-dashboard-certs"
  Normal  SuccessfulMountVolume  1m    kubelet, node03    MountVolume.SetUp succeeded for volume "kubernetes-dashboard-token-kcd74"

**Comment by donutloop** [comment]
@floreks Could you reopen this issue, please!

**Comment by floreks** [comment]
Like I said already in https://github.com/kubernetes/dashboard/issues/2547#issuecomment-345174496, this issue is not related to Dashboard. There is an issue with the cluster.

**Comment by maheshreddy32825** [comment]
@floreks  can you help me with this issue. I am new to K8s

root@kmaster:~# kubectl describe pod kubernetes-dashboard-7c54d59f66-s7ckx -n kube-system
Name:           kubernetes-dashboard-7c54d59f66-s7ckx
Namespace:      kube-system
Priority:       0
Node:           <none>
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=7c54d59f66
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/kubernetes-dashboard-7c54d59f66
Containers:
  kubernetes-dashboard:
    Image:      k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      --auto-generate-certificates
    Liveness:     http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-q7fxb (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kubernetes-dashboard-token-q7fxb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-q7fxb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  2m29s (x203 over 22m)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
