### ISSUE TITLE
Packaging for openSUSE

### ISSUE THREAD

**Issue by rbwsam** [kubernetes/dashboard#2553]
I'm packaging dashboard for openSUSE and running into an issue.

As far as I can tell, the `dashboard` binary assumes that the `public` directory and `locale_conf.json` file that result from `gulp build` are located in the same directory as the `dashboard` binary during runtime. 

Is this correct? If so, it seems that I will need to submit a pull request that allows the location of `locale_conf.json` and `public` to be passed as flags when `dashboard` is run - that way I can place the files in appropriate directories and the `dashboard` binary in `/usr/bin`.

Any input is appreciated, thanks!

**Comment by cheld** [comment]
I would prefer to package everything into the binary e.g with 

https://github.com/jteeuwen/go-bindata

Not sure about effort though

**Comment by cheld** [comment]
https://github.com/elazarl/go-bindata-assetfs

**Comment by floreks** [comment]
We could add such options, however I think this is not needed. This is what we have symbolic links for. You can simply create symbolic link in your `/usr/bin` directory and keep `dashboard` with all its' dependencies somewhere else.

**Comment by rbwsam** [comment]
@floreks I like your idea but I think it requires a code change. It seems that the code looks in the current working directory for the localized frontend assets. I'm working on a PR that gets the directory of the executable using `os.Executable` then resolves symlinks and looks for the assets dir relative to that path. Does this seems like a sound strategy?

**Comment by rbwsam** [comment]
Closed by #2739
