### ISSUE TITLE
Couldn't connect to K8S Dashboard

### ISSUE THREAD

**Issue by lzvoyager** [kubernetes/dashboard#2554]
##### Steps to reproduce

$ gcloud container clusters get-credentials us-east --zone us-east1-b --project apiai-dev
In a browser: http://localhost:8001/ui

This GCP project "apiai-dev" is viewable by all googlers. Feel free to poke around.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'ssh: rejected: connect failed (Connection refused)'
Trying to reach: 'http://10.4.0.39:9090/api/v1/overview/default?filterBy=&itemsPerPage=15&page=1&sortBy=d,creationTimestamp'
```

**Comment by maciaszczykm** [comment]
We cannot view it as non-Googlers, so we need a bit more steps to reproduce the error.

**Comment by maciaszczykm** [comment]
Reopen after providing us more details.
