### ISSUE TITLE
UX improvements and design activities

### ISSUE THREAD

**Issue by rahuldhide** [kubernetes/dashboard#2556]
@danielromlein, @bryk, @floreks, @maciaszczykm, @cheld Creating this issue to share the UX design plan that we discussed last week. 

# Usability Review
- Review existing product to identify what can be used in the new product what needs to be improved, and what’s relevant
**Output:** Heuristic evaluation- list of usability issues and recommendations

# User Research
- Create user pool during the KubeCon
- Conduct Card sort to test the navigation
- Conduct a survey with participants to understand the key pain points, expectations and usage
- Interview existing customers about what’s good and bad about the product
- Interview existing users about how they balance work/life today, pain points, tools and projects they use etc.
**Output:** Navigation model, proto personas and user stories

# Strategy Workshops (TBD)
- Share findings and recommendations with the core team
- Identify key themes for the next version(s)
- Conduct design sprints
**Output:** UI concepts and user flows

# Design Concepts and Reviews
- Share the design concepts with the community and iterate designs based on the feedback
- Conduct 1:1 UX reviews and usability tests
**Output:** Detail designs

**Comment by maciaszczykm** [comment]
@rahuldhide Any update?

**Comment by rahuldhide** [comment]
@maciaszczykm This was more of a proposal. As we discussed I have been working on these items. Kubernetes Dashboard User Survey (tinyurl.com/y7rdn8af) is already published and we will continue to get the feedback until Jan end.

**Comment by itsyogesh** [comment]
Hey @maciaszczykm, I created something called [Projectwise](https://projectwise.in). Its a platform for open-source projects to find design help. Can I add the repo in the list of projects that require design help ?

**Comment by maciaszczykm** [comment]
@itsyogesh Sure, we can try.

cc @floreks

**Comment by itsyogesh** [comment]
Hi @maciaszczykm Just added the repo to the list, I've also included this issue url for further discussion. 

Thanks

**Comment by pmvogt** [comment]
I'm a designer, found this VIA projectwise. Can I help?

**Comment by rahuldhide** [comment]
@itsyogesh @pmvogt It's great to see that more folks are joining to contribute on design. 

Currently we are in the discovery phase where the goal is to identify the user pain points and areas that need better solutions. As mentioned in this issue, we have several activities planned for the same. We would definitely need more hands when we start on the different flows and associated screens. In the meantime, I would recommend you to create a cluster (if you don't have one) and get familiar with the current dashboard and existing design patterns.

**Comment by pmvogt** [comment]
@rahuldhide cool. happy to work on some screens and flows.

**Comment by floreks** [comment]
@pmvogt We appreciate any help. Like @rahuldhide mentioned try out Dashboard first and get familiar with our current UX. If you feel like something could be improved and have some ideas feel free to share them with us. We are open to feedback and any suggestions. 

Currently we mainly need feedback on login screen and new create forms.

**Comment by dprathipati** [comment]
hey! I'm a designer interested in helping! If there's anything I can help with in the research and initial design and prototyping stages, please let me know how I can get started.

**Comment by jayprat95** [comment]
hey! I'm a designer interested in helping! If there's anything I can help with in the research and initial design and prototyping stages, please let me know how I can get started.

**Comment by danielromlein** [comment]
Love the Projectwise idea @itsyogesh! It would be great to have you join one of our [SIG-UI weekly calls](https://github.com/kubernetes/community/tree/master/sig-ui) in the new year so you can get a better sense of what we're all about. 

@pmvogt & @jayprat95 same to you: beyond playing around with something like [Minikube](https://kubernetes.io/docs/getting-started-guides/minikube/), if you're able to join a SIG-UI weekly call that would probably be the most efficient way to bring you up to speed.

Excited to have folks interested in contributing!

**Comment by JackHasaKeyboard** [comment]
Here's a logo idea.
Isn't specific to the dashboard part of Kubernetes, still thought it would be worth sharing though:

![kubernetes](https://user-images.githubusercontent.com/12004300/34343436-26469df4-e983-11e7-81ab-2ad5866f1fc1.png)

>Hexagon, the ubiquitous symbol for an application
>Implies segmentation
>K created in negative space

**Comment by jayprat95** [comment]
@danielromlein I would definitely be interested in joining the weekly call depending on the time

**Comment by julienlim** [comment]
@rahuldhide, @danielromlein, @bryk, @floreks, @maciaszczykm, @cheld

It's terrific to see growing interest and efforts in Kubernetes UX.  I was curious if any of the findings and observations from the User Survey results has been published and shared with the community.  If so, where might one find this information?

I'd also be interested in helping contribute as well.  Is there information available on what kind of contributions you folks are seeking?

Thank you in advance.

**Comment by inyee786** [comment]
hey, 
I am UI developer, i also want to contribute to the k8s community, if any help  is required let me know

**Comment by rahuldhide** [comment]
@julienlim We didn't receive enough responses so we didn't share the results with the entire community. There were many interesting nuggets that we're using for some design proposals. @danielromlein I have some ideas to discuss. We can review those during the upcoming meeting.

**Comment by maciaszczykm** [comment]
Deprecated. If somebody still would like to contribute please reach out on Slack. There is a lot of design work to do especially considering ongoing Angular migration.

/close
