### ISSUE TITLE
Auth with google openid 

### ISSUE THREAD

**Issue by sergeohl** [kubernetes/dashboard#2562]
```
Dashboard version: 1.7.1
Kubernetes version: 1.8.2
Auth method: token
```

I have a strange behaviour with the dashboard and the google openid token. In our clusters, all users use token for cli and we are trying to use it for the dashboard. But I have an issue, multiple time per day the dashboard  says to me: **error_outline Unauthorized (401) Unauthorized**. I sign out,  and when I try to sign in with the same token I can't with a **Authentication failed. Please try again.**

I checked log and I have 
`Non-critical error occurred during resource retrieval: the server has asked for the client to provide credentials`

And I have to renew my token to google to do working. But without renew all the cli still working, is juste the dashboard auth.

Do you already meet this issue ?

**Comment by floreks** [comment]
@sergeohl Unfortunately we do not have environment to test this scenario. Does it happen while using Dashboard or after leaving it unused for some time? To check if provided credentials are valid we are doing a request to `/version` endpoint of apiserver. This is the only place where this error can be returned during logging in.

**Comment by sergeohl** [comment]
Sometime we have this issue when we are using the dashboard sometime when we let it (in an onglet) and come back. 

I tried this morning /version is ok but auth with token in dashbard doesn't work. 

I use kubectl proxy to reach the dashboard and the api

**Comment by rf232** [comment]
I don't have access to my dev environment at the moment, but if I remember
correctly, if you want se gke the generated kubeconfig file will not only
contain the oauth token, but also a command to refresh it. So the reason
kubectl keeps working is because it keeps refreshing the token.

**Comment by sergeohl** [comment]
It's not on gke it is on AWS.

The issue it's because the dashboard doesn't refresh the token to the oauth provider.

**Comment by floreks** [comment]
True, dashboard would need information about address of identity provider in order to be able to refresh the token. This is not yet supported.

**Comment by c-knowles** [comment]
Also using Google login on our AWS clusters so was just looking into how support could be added. The user section of our kube config files look a bit like this:

```yaml
- name: USER
  user:
    auth-provider:
      config:
        client-id: CLIENT_ID.apps.googleusercontent.com
        client-secret: SECRET
        id-token: TOKEN
        idp-issuer-url: https://accounts.google.com
        refresh-token: TOKEN
      name: oidc
```

My current understanding is we'd need the dashboard to support `id-token` [here](https://github.com/kubernetes/dashboard/blob/92a256425d23bd725923506b6cb37047f85e39d9/src/app/backend/auth/kubeconfig.go#L109) as well as support refresh of the token via `refresh-token`. Does that sound about right or am I missing something? New to the codebase so some pointers might help get started.

**Comment by floreks** [comment]
Probably we'd need all information required to refresh token. I think it requires initial token that allows access to the cluster, url of the identity provider that we can use to refresh token and refresh token that has to be provided together with initial token to refresh it.

**Comment by sergeohl** [comment]
Kubernetes do it.  Maybe we just have to take inspiration from kubernetes project.

**Comment by floreks** [comment]
It's a bit tricky because both apiserver and kubectl have some logic implemented to support that. Personally, I'd love to see some API exposed by core that would allow us to get information about configured identity provider and still act as a proxy, forcing apiserver to refresh the token when needed.

**Comment by floreks** [comment]
Closing as we have a tracking issue for it #2353. Adding support for external identity providers also requires support for token refresh functionality. Currently we are only accepting tokens, that are accepted by apiserver but Dashboard has no idea where it came from or how to refresh it if needed.
