### ISSUE TITLE
Make TLS secrets names configurable

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [kubernetes/dashboard#2572]
##### Environment
```
Dashboard version: 1.7.1
Kubernetes version: any
```

To bring the new tls self signed certificate feature in the kubernetes-dashboard Helm Chart and make it generic the secrets names should be configurable.

**Comment by maciaszczykm** [comment]
They are: https://github.com/kubernetes/dashboard/blob/master/src/deploy/recommended/kubernetes-dashboard.yaml#L115-L116

**Comment by SharpEdgeMarshall** [comment]
No i'm talking about the secrets names:
- `kubernetes-dashboard-key-holder`
- `kubernetes-dashboard-certs`

**Comment by floreks** [comment]
Why exactly should they be configurable?

**Comment by SharpEdgeMarshall** [comment]
I think that they should not be hardcoded for many reasons: 
- If someone needs to deploy multiple dashboards is going to have issues because it's impossible to use different secrets.
- Helm Charts needs to be generic and Helm promote the use of Release Name + Chart Name to name the resources and differentiate them.

Maybe I'm missing something?

**Comment by floreks** [comment]
> If someone needs to deploy multiple dashboards is going to have issues because it's impossible to use different secrets.

True. It is already on our list of improvements (#2353).

**Comment by SharpEdgeMarshall** [comment]
Ok I didn't see that.
