### ISSUE TITLE
kubernetes dashboard is not accessible 

### ISSUE THREAD

**Issue by darshoka** [kubernetes/dashboard#2576]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

##### Observed result
kubectl --kubeconfig ./admin.conf logs kubernetes-dashboard-747c4f7cf-kns2w --namespace=kube-system
2017/11/14 11:43:42 Starting overwatch
2017/11/14 11:43:42 Using in-cluster config to connect to apiserver
2017/11/14 11:43:42 Using service account token for csrf signing
2017/11/14 11:43:42 No request provided. Skipping authorization
2017/11/14 11:43:42 Successful initial request to the apiserver, version: v1.8.3
2017/11/14 11:43:42 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2017/11/14 11:43:42 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2017/11/14 11:43:42 Initializing secret synchronizer synchronously using secret kubernetes-dashboard-key-holder from namespace kube-system
2017/11/14 11:43:42 Initializing JWE encryption key from synchronized object
2017/11/14 11:43:42 Trying to update secret with same object. Skipping
2017/11/14 11:43:42 Creating in-cluster Heapster client
2017/11/14 11:43:42 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2017/11/14 11:43:42 Serving securely on HTTPS port: 8443
2017/11/14 11:44:12 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.

##### Comments

I am new to kubernetes ,please help .. How to enable heapster service .

**Comment by maciaszczykm** [comment]
You can still access Dashboard without Heapster running. How do you try to access? Do you use `kubectl proxy`?

**Comment by darshoka** [comment]
I got dashboard right now. I have not used  kubectl proxy . Instead i have exposed my dashboard deployment using NodePort . 

Thanks maciaszczykm .

I am closing issue now .

**Comment by IsDragon** [comment]
@maciaszczykm  i am facing same issue, while running the dashboard in local development
i have follow the wiki but it is giving me same error

**Comment by qasim9641** [comment]
I am also facing the same issue.I am able to access the Dashboard but without the cpu and memory metrics.I am little confused here.As with new dashboard we only need to deploy the metrics-server then why dashboard is complaining about the heapster ?
 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.

**Comment by maciaszczykm** [comment]
>As with new dashboard we only need to deploy the metrics-server then why dashboard is complaining about the heapster ?

Dashboard needs Heapster at the moment. Metrics API is not supported yet.
