### ISSUE TITLE
Error displaying pod info managed by an Operator with CRD

### ISSUE THREAD

**Issue by jhernandezb** [kubernetes/dashboard#2577]
##### Environment
```
Dashboard version: 1.7.0
Kubernetes version: 1.8.0
Operating system: minikube
```

##### Steps to reproduce
In the process of creating an Operator with a custom controller. 
- Create a Custom Resource Definition
- Create a new resource of this new CRD
-  The controller manages the creation of pods assigning OwnerReference  to  new Pods pointing to the crd resource. 

So each pod contains this kind of reference.
```
{
		APIVersion:        "custom.crd.com/v1",
		Kind:               "ADeployment",
		Name:               "resource-name",
		UID:                "resource-uid",
}
```

##### Observed result
When I go to the dashboard to see the details of the pod.

http://192.168.64.18:30000/#!/pod/my-namespace/managed-pod

I got a 500 error
`Unknown reference kind ADeployment`

This comes from `/api/v1/pod/demo/my-namespace/managed-pod`
##### Expected result
To see pod details.

##### Comments
It seems like this might be a problem with CRDs as owners 
https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/pod/detail.go#L148

**Comment by maciaszczykm** [comment]
@jhernandezb Yes. We have to fix it. Thanks for reporting.

**Comment by fabiand** [comment]
KubeVirt is also using references to the underlying pods, we'd also benefit from a fix for this issue.

**Comment by fabiand** [comment]
@maciaszczykm is there an issue to track CRD support?

**Comment by NielsDoucet** [comment]
With the recent introduction of the [operator-framework](https://coreos.com/operators/) to facilitate easy development of operators and crds, I expect more and more people will run into this issue (as I have).
Would really appreciate a fix here too>

**Comment by fabiand** [comment]
We should establish a pattern for this. So far I saw that at least Spark CRDs are referencing the hosting pod via a spec field.
