### ISSUE TITLE
will dashboar support prometheus?

### ISSUE THREAD

**Issue by davidstack** [kubernetes/dashboard#2578]
the dashboard now support heapster for resource metric, but we know, heapster does not have alert manager,will dashboar support prometheus? thanks

**Comment by floreks** [comment]
It was planned at some point, but we do not have enough devs and time to work on such integrations right now. It will be added at some point for sure. I'd love to only use kubernetes metrics API and get rid of heapster/prometheus hard dependencies. I'll have to investigate if this is possible.

**Comment by davidstack** [comment]
kubernetes may  not have the metrics API. maybe it need a long time

**Comment by floreks** [comment]
It does: https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/

**Comment by davidstack** [comment]
thanks.

**Comment by davidstack** [comment]
I deploy heapster and metric-server. i test the metric-server api. it works well. from the api , we can get one metric of the pod or one metric of all pods. but  metric server does't store history metrics
`http://10.110.17.88:8080/apis/metrics.k8s.io/v1beta1/nodes/node2
`
response is 
`{
    "kind": "NodeMetrics",
    "apiVersion": "metrics.k8s.io/v1beta1",
    "metadata": {
        "name": "node2",
        "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes/node2",
        "creationTimestamp": "2017-11-10T09:57:48Z"
    },
    "timestamp": "2017-11-10T09:57:00Z",
    "window": "1m0s",
    "usage": {
        "cpu": "185m",
        "memory": "2471876Ki"
    }
}`

i think metric-server  can not be integrated with dashboard at present

**Comment by floreks** [comment]
It is still being actively developed. Even though currently it returns only current metric, it might change in the future.
