### ISSUE TITLE
gulp-minify-css is deprecated. Use gulp-cssnano instead

### ISSUE THREAD

**Issue by luxas** [kubernetes/dashboard#258]
```
unmet dependency browserify@3.46.1

npm WARN EPEERINVALID browserify-shim@2.0.10 requires a peer of browserify@>= 2.3.0 < 4 but none was installed.

npm WARN DEPRECATED gulp-minify-css@1.2.3: Please use gulp-cssnano instead
```
Will be back with little more info soon

**Comment by bryk** [comment]
I cannot reproduce on master@HEAD. Can you fetch latest version of the repo and try to reproduce?

**Comment by luxas** [comment]
When running `npm install`:
```
+-- gulp-browserify@0.5.1 
| +-- UNMET PEER DEPENDENCY browserify@3.46.1
| | +-- assert@1.1.2 
| | +-- browser-pack@2.0.1 
| | | +-- combine-source-map@0.3.0 
| | | | +-- convert-source-map@0.3.5 
| | | | +-- inline-source-map@0.3.1 
| | | | | `-- source-map@0.3.0 
| | | | `-- source-map@0.1.43 
| | | `-- JSONStream@0.6.4 
| | |   `-- through@2.2.7 
```
It seems like it has to do with `gulp browserify`

However, the `gulp-minify-css` has been deprecated as `npm' says. See this page: https://www.npmjs.com/package/gulp-minify-css
Maybe you want to fix that before this reaches `beta`

**Comment by bryk** [comment]
Which npm/nodejs versions do you have?

Re gulp-minify-css: Yeah. Will do this at some point ;)

**Comment by luxas** [comment]
Using official docker image `node`.
```
root@3ba016f64ebc:/dashboard# node -v 
v5.4.1
root@3ba016f64ebc:/dashboard# npm -v 
3.3.12
```

**Comment by bryk** [comment]
I've tested this. It is not a problem. It is just a warning. The warning is about not critical *peer* dependency.

**Comment by luxas** [comment]
I'm ok with that. I just notified if it could be a problem.
But for this one, we'll keep it open for `cssnano` (not a huge problem either, but should be fixed)
