### ISSUE TITLE
the resource stauts chart of the overvie page should show all running pods 

### ISSUE THREAD

**Issue by likunbyl** [kubernetes/dashboard#2593]
##### Environment
```
Dashboard version:  google_containers/kubernetes-dashboard-amd64:v1.7.1
Kubernetes version:  1.7.8
Operating system: coreos 1298.5.0
```

##### Steps to reproduce
1. Have dashboard running in the non-SSL mode.
2. Config service point to dashboard pod.
3. Config ingress point to the dashboard service.
4. Access dashboard through nginx-ingress-controller external ip.

##### Observed result
The overview page displays the status of the default namespace, but it only shows 'Running  15' pods at the 'Resource status' chart, while we actually see 19 pods at the Pod part. 

##### Expected result
The overview page should show 'Running  19' pod at the "Resource Status" chart.

**Comment by maciaszczykm** [comment]
@likunbyl Can you send us a screenshot?
