### ISSUE TITLE
 want to exec more command other than the default one in the dashboard

### ISSUE THREAD

**Issue by likunbyl** [kubernetes/dashboard#2594]
##### Environment
```
Dashboard version: 1.7.1
Kubernetes version: 1.7.8
Operating system: coreos 1298.5.0
```

##### Steps to reproduce
1. loging into dashboard with user admin.
2. find the busybox pod, and click it to enter it.
3.  click the 'EXEC' to exec into pod.

##### Observed result
failed with 'rpc error, ... "bash": executable file not found in $PATH". 

##### Expected result
Should have some place to setup the command I want to run, like, /bin/sh, or after failed the default command, I have a chance to run the command I'd like to run .

**Comment by floreks** [comment]
Currently, supported shells are `bash` and `sh` only. #2029 is our tracking issue for exec improvements and it already has `Add support for more shell types`. If you want to execute an entirely custom command like in `kubectl exec <pod> -- nslookup ...` then there is no such feature yet. Exec functionality is supposed to provide terminal access. We might consider adding such feature in the future.

**Comment by likunbyl** [comment]
ok, I added the following lines to the dashboard deploy yaml file, sh is working now:

      volumeMount
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
        emptyDir: {}

So, why should dashboard rely on these configuration to exec sh? Can somebody give some hint ?

**Comment by likunbyl** [comment]
got it, it seems dashboard image doesn't have /tmp directory , so we need mount some space to /tmp to hold the temp log file when running bash or sh.
