### ISSUE TITLE
Provide a way for cloud providers to show a system banner

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#2603]
Feature proposal:
Allow cloud providers to configure Dashboard UI to show a system banner. The banner would be configurable via command line flags. Admins would be able to set its prominence and style. 

Use cases for this:
1. Showing cloud provider specific banner, e.g., "To edit this cluster go [there]". 
2. Showing system messages, e.g., "This cluster is going into maintenance mode next week [learn more]".

@maciaszczykm @floreks @danielromlein What do you think of contributing this?

**Comment by maciaszczykm** [comment]
I think it could be achieved quite easily and if it has some value then we should do it.

What about placement? Above toolbars?

**Comment by bryk** [comment]
I think so. Do you have any proposals/opinions here? I guess I can take @danielromlein and propose something here.

**Comment by maciaszczykm** [comment]
Also thinking how to make it configurable. Perhaps settings would be a better place to set it up?

**Comment by bryk** [comment]
Do you mean configuring this in settings rather than command line flag/environment variable? We could theoretically add this option there, but I fear we need CLI flag because I don't see how otherwise cloud providers can use it.

**Comment by floreks** [comment]
Any example of how you think this would be used? I get the general idea but can't exactly imagine how would you want to use it.

**Comment by bryk** [comment]
Using this would be just editing the command line flag. Since Dashboard UI is a deployment, it'll populate the flag in a rolling update. To take down the system message, we remove the flag. Does this answer your question?

**Comment by floreks** [comment]
Not exactly. What I meant is what should be configurable via CLI, i.e. should it accept something like HTML or should there be several flags that configure banner message, logo, size, prominency, color, etc.?

**Comment by bryk** [comment]
I think this should be "simple HTML". Meaning text links, p, pre, hrefs. Angular has a mechanism for parsing and using only "simple HTML". 

This could be:
```
--system-banner="<p>foo, bar <a href="xx">baz</a></p>"
--system-banner-severity=INFO|WARNING|ERROR
```

WDYT?

**Comment by maciaszczykm** [comment]
Sounds fine.

**Comment by floreks** [comment]
That should work and should not be hard to add.
