### ISSUE TITLE
Failed to launch: unknown flag: --tls-key-file

### ISSUE THREAD

**Issue by anykeyh** [kubernetes/dashboard#2609]
##### Environment

I use Kubernetes build-in inside Google Container Engine.

##### Kubernetes version:
My version of kubernetes is mixed, my apps run on 1.6.10 and my master on 1.6.11-gke.0

The dashboard pod is in crashloopback state:

```
kubernetes-dashboard-4160701715-4d237               0/1       CrashLoopBackOff   518        1d
```

Obviously, it seems like the dashboard changed, and some options are not available anymore.

```
#The log of the pod give me:
unknown flag: --tls-key-file
# Followed by printed help
```

My main problem is I'm confused how to fix this / where to get the good new pod declaration

Thank in advance,

**Comment by maciaszczykm** [comment]
@anykeyh What is your Dashboard version? You did not fill the issue template.

**Comment by floreks** [comment]
@anykeyh You are definitely using old version of Dashboard. GCE uses Addon Manager to handle addons such as Dashboard. It stores addon manifests that need to be kept in sync somewhere on disk. You can ask GCE support for help or check kubernetes core repo. Unfortunately we are not using GCE so we don't know how to configure and update Dashboard there.

**Comment by anykeyh** [comment]
Hi,

Thanks for your reply and sorry for not following the issue template. 

Indeed it seems like built-in dashboard on GCE is slighty different from the open-sourced project. I tried to fix it but I guess I put some mess in my cluster instead. I'll ask support from GCE.

**Comment by maciaszczykm** [comment]
Please reopen if our assumption is wrong. Otherwise, update the app to use certs etc.
