### ISSUE TITLE
Wrong URL for accessing dashboard in documentation

### ISSUE THREAD

**Issue by coommen** [kubernetes/dashboard#2611]
In the Readme.md, under *Getting Started*,  the documentation says use this URL to access the dashboard after you start the proxy:

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

That URL is incorrect. It should be:
http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/

**Comment by floreks** [comment]
No, provided url is correct. If you follow the readme from the beginning to the end then Dashboard will be accessible using first url.

**Comment by cheld** [comment]
The URL has changed since 1.7. (it is also documented in readme)

**Comment by coommen** [comment]
Ok. The documented URL returned this error, when I tried and the other one I posted worked:
>Error: 'tls: oversized record received with length 20527'
>Trying to reach: 'https://10.244.3.3:9090/'

**Comment by floreks** [comment]
I can only assume that you either did not deploy latest version of Dashboard or you are using some cloud provider that enables addon manager in kubernetes, which disables option to easily update addon version.
