### ISSUE TITLE
503 error!After I compile the dashboard and execute it by gul server，localhost:9090 return empty

### ISSUE THREAD

**Issue by BiggerBrain** [kubernetes/dashboard#2624]
I use F12，find the log in chrome. here is the log, how to solve the problem?

Uncaught ReferenceError: **angular is not defined**
    at ui-router-angularjs.js:14
    at ng_from_global (ui-router-angularjs.js:11)
    at ui-router-angularjs.js:12
deps.js Failed to load resource: the server responded with a status of 503 (Service Unavailable)
base.js Failed to load resource: the server responded with a status of 503 (Service Unavailable)
deps.js Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-dev.js:8623 Uncaught ReferenceError: goog is not defined
    at Object.defineProperty.value (app-dev.js:8623)
    at __webpack_require__ (app-dev.js:20)
    at Object.defineProperty.value (app-dev.js:8535)
    at __webpack_require__ (app-dev.js:20)
    at Object.defineProperty.value (app-dev.js:8335)
    at __webpack_require__ (app-dev.js:20)
    at Object.defineProperty.value (app-dev.js:63)
    at app-dev.js:66
angular.js:4957 Uncaught Error: [$injector:modulerr] Failed to instantiate module kubernetesDashboard due to:
Error: [$injector:nomod] Module 'kubernetesDashboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by floreks** [comment]
Provide more details about how to reproduce this. Exact steps from cloning repo to starting `gulp serve`.

**Comment by maciaszczykm** [comment]
Did you run `npm i`?

**Comment by BiggerBrain** [comment]
yes，I  rum npm i

**Comment by maciaszczykm** [comment]
@BiggerBrain Write full steps to reproduce section. Otherwise, we cannot help.

**Comment by maciaszczykm** [comment]
And read https://github.com/kubernetes/dashboard/wiki/Getting-started.

**Comment by BiggerBrain** [comment]
here is my step
1. git clone https://github.com/kubernetes/dashboard.git
2. npm i 
3 kubectl proxy --port=8080
4. gulp server（I get the erro( "Task 'server' is not in your gulpfile" )）
5. curl localhost:9090
6. empty?（the same with chrome） 
 k8s which version is 1.8.1 installed by kubeadmin,and I had a dashboard 1.7.1 is running in cluster , the dashboard 1.7.1 runing normal 。
Am I missing some steps?

**Comment by floreks** [comment]
It is `gulp serve` not `gulp server`.

You have to wait until it starts and should see something like that (without the kubeconfig part).
![zrzut ekranu z 2017-11-28 12-54-20](https://user-images.githubusercontent.com/2285385/33318572-578f45f8-d43b-11e7-826a-78c9c2da8157.png)

Also what version of Node/NPM are you using?

**Comment by floreks** [comment]
Any update here?

**Comment by maciaszczykm** [comment]
Please reopen after providing details.

> It is gulp serve not gulp server.

Should solve the problem.
