### ISSUE TITLE
Overview Redirects

### ISSUE THREAD

**Issue by azweb76** [kubernetes/dashboard#2625]
##### Environment

```
Dashboard version: 1.8.0
Kubernetes version: 1.7.6
Operating system: CentOS 7
Node.js version:
Go version:
```

##### Steps to reproduce
Install the dashboard using the provided install manifest file.
Navigate to the dashboard using kubectl proxy url (http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/)

##### Observed result
Repeated 404 Page is displayed. Redirected in 3 seconds.

##### Expected result
Overview page is displayed.

##### Comments
Note: I skipped the login page.

**Comment by floreks** [comment]
Look at kubernetes version. Dashboard 1.8 is targeting k8s 1.8+. There is a compatibility matrix on the wiki.
