### ISSUE TITLE
Observed resultDashboard reported Internal Server Error (500):```client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup etcd.kubernetes.rancher.internal on 169.254.169.250:53: no such host

### ISSUE THREAD

**Issue by bowenming** [kubernetes/dashboard#2626]
##### Steps to reproduce##### Environment```Installation method: Kubernetes version:Dashboard version: v1.7.1Commit: b44f7cc5fde4dbe2a884b1e32a2b363d8031e4ca```##### Observed resultDashboard reported Internal Server Error (500):```client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup etcd.kubernetes.rancher.internal on 169.254.169.250:53: no such host```##### Comments

**Comment by floreks** [comment]
I don't see any Dashboard issue here. If etcd is not working then Dashboard won't also.
