### ISSUE TITLE
502 Bad Gateway encountered on INT when trying to access logs

### ISSUE THREAD

**Issue by jay-walters** [kubernetes/dashboard#2637]
##### Steps to reproduce

When trying to access the logs from...
https://inta.kube.nmlv.nml.com/#!/replicaset/default/smash-webapp-java-9889977-3738086798?namespace=default

OR

https://inta.kube.nmlv.nml.com/#!/pod/default/smash-webapp-java-9889977-3738086798-j8hnv?namespace=default

a 502 is encountered...

https://inta.kube.nmlv.nml.com/#!/log/default/smash-webapp-java-9889977-3738086798/replicaset?namespace=default

AND

https://inta.kube.nmlv.nml.com/#!/log/default/smash-webapp-java-9889977-3738086798-j8hnv/pod?namespace=default

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 
```

##### Observed result
Dashboard reported Bad Gateway (502):
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty/1.11.2.3</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by floreks** [comment]
Try updating Dashboard to latest version first. Reopen if issue still occurs.
