### ISSUE TITLE
Can not download logs anymore

### ISSUE THREAD

**Issue by Globegitter** [kubernetes/dashboard#2640]
```
Dashboard version: 1.8.0
Kubernetes version: 1.8.3
Operating system: host OS is debian jessie
```

##### Steps to reproduce
Setup k8s dashboard 1.8 with recommended minimal rbac rights. Login with a service account token that has sufficient rights (e.g. I logged in with cluster admin)

##### Observed result
I can look at any pods logs but when trying to download them I get:
pods "name-5769679557-2ssp2" is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot get pods/log in the namespace "xxx"

##### Expected result
I should be able to download the logs as the account I logged in with has the rights to get the logs.

##### Comments
One quick fix I assume is to give the dashboard service accounts sufficient rights, but I suppose that should really be downloaded with the logged in account, right?

**Comment by maciaszczykm** [comment]
> I suppose that should really be downloaded with the logged in account, right?

Yes. We have to fix.
