### ISSUE TITLE
Login form compatibility with password managers

### ISSUE THREAD

**Issue by kachkaev** [kubernetes/dashboard#2641]
After upgrading to dashboard 1.8.0 and making it available at https://dashboard.example.com/, I've decided to save a few tokens into my password manager to then quickly authenticate in the UI with different privileges. However, I've noticed that the dashboard's login form is incomparable with the password managers I tried ([1password](https://1password.com/) and [LastPass](https://www.lastpass.com/)). Usually password managers work fine with any website without any effort from its developers, so it seems like there's something trivial missing in the angular-controlled login form. I'd like to open this issue to start a discussion.

##### Environment
```
Dashboard version: 1.8.0
Kubernetes version:
Operating system: macos Firefox / Chrome with 1password and LastPass extensions
```

##### Steps to reproduce
0. Make the dashboard available at https://dashboard.example.com/

_scenario 1_
1. Open the dashboard and see the login screen
1. Paste a token into the form and click "sign in"

_scenario 2_
1. Open your password manager browser extension and manually add a new password entry for https://dashboard.example.com/ (I tried [1password](https://1password.com/) and [LastPass](https://www.lastpass.com/)).
1. Open the k8s dashboard and see the login screen
1. Click on the password manager's icon, select the existing entry with the just-created token and click on it to paste the data into the form.

##### Observed result
_scenario 1:_ the password manager does not suggest to save the token as a new password entry

_scenario 2:_ the token (which is saved as password) does not get pasted into the _token_ form field

##### Expected result
_scenario 1:_ the password manager suggests to save the token as a new password entry

_scenario 2:_ the token gets pasted into the _token_ form field of the login form and "sign in" is automatically pressed

##### Comments

Password managers like 1password and LastPass are widely used both by individuals and teams. They are recommended in quite a few security articles, so it is likely that their prevalence will grow in the forthcoming months. Keeping k8s tokens in a password manager seems like a right thing to do, because this way cluster admins can share access with their colleagues quite easily while keeping things secure and transparent.

It'd be great to have the dashboard login form compatible with the password managers, which probably just means that its elements should get a few extra HTML attributes. If anyone has any experience with making password managers happy, please share your thoughts!

**Comment by maciaszczykm** [comment]
Thanks for reporting this issue. We will take a look on it.

**Comment by floreks** [comment]
Great feature request. Simple, yet very helpful. We already have an idea why it is not working and should be easy to fix.

**Comment by floreks** [comment]
I've had some time to test it and with our current design and custom login page having full support for password manager extensions might not be possible. #2642 will enable partial support for them as after successful sign in last pass have asked me to save "credentials". It will not autocomplete the filed for you nor show additional button on input field to just click and choose it. It is required to either right click and choose it from menu or use extension menu to trigger autocompletion.

I have found that unfortunately last pass plugin support for input field is triggered by certain key words used as placeholder for input field and login button. We would have to use `Password` description instead of `Enter token` for token field and rename our `Sign in` button to `Login`. This is not very nice. I guess it should work just by setting the field type and maybe id or name tag on field.

We will leave partial support for now. Maybe it will be improved by them at some point.

**Comment by kachkaev** [comment]
Thanks for investigating the issue @floreks! Perhaps this hint from LastPass can help too? https://lastpass.com/support.php?cmd=showfaq&id=3385

**Comment by floreks** [comment]
I have seen it during investigating. It doesn't help as it is their "perfect" example. All the fields with id, name, value, everything that is a keyword they are looking for. For custom login forms with different text it just does not work correctly.

**Comment by kachkaev** [comment]
After #2642 has been merged, I installed the [dev release](https://github.com/kubernetes/dashboard/wiki/Installation#development-release) and the experience became better! Now entering the token for the first time and pressing "Sign In" triggers a password manager's prompt to save a new item. So _scenario 1_ can be considered as resolved. Reusing a saved password is also possible with a minor hiccup: because "token" is not a default login option - you have to click on the radio button first.

What if we make "token" selected by default? In this case password managers will be able fill in the input in one less click, but the kubeconfig scenario UX will not get worse. At the moment the kubeconfig radiobutton is initially on, but you still need to make one extra click before you upload a file. If "token" option is default, clicking on kubeconfig can trigger the window right away - still the same one click.

One extra benefit of making "token" a default option is that the input field can be made focused right away. Users will be able to `command v` into a new tab without any extra clicks (e.g. when they are pasting a token from kubectl or an email).

WDYT?

**Comment by kachkaev** [comment]
One more minor bit: I don't think that an asterisk for marking mandatory fields is necessary in the form. There's only one thing to enter and it's an obvious thing.

Shame that I don't know angular and so can't submit a PR with all this.

**Comment by floreks** [comment]
We can change ordering. It is not a problem. Anyway this should be handled by adding autofocus to the input field so it will actually be focused when page first loads.

As for the `*` sign it is how angular material works. Adding `required` tag to input field triggers whole validation logic and adds this sign to every field. We don't want to change default behavior here.

**Comment by kachkaev** [comment]
Looks like you can remove the asterisk while keeping the behaviour by [adding `md-no-asterisk` to the input](https://material.angularjs.org/latest/api/directive/mdInput). This will be just a cosmetic change that makes the form a bit cleaner. IMO asterisks only make sense when a form contains a _mix_ of required and optional fields. In any case, this is a very minor thing.

**Comment by kachkaev** [comment]
Perhaps keeping the order of the radio buttons is fine, because this way the "token" radiobutton is closer to its input field, which is good from the perspective of the proximity principle. Just making the second option selected by default is OK.

If clicking on "kubeconfig" opens a file dialog box, nearly no one will have to click on "Choose kubeconfig file". This will be only necessary if you've cancelled a dialog and want to trigger it again.

**Comment by joelharkes** [comment]
Currently autofill is still/ no longer supported?

or is there a way we have to setup the k8s dashboard so auto-filling works?

it annoying you first have to manually click on the radio button every time to login (and than manualy copy paste password).

**Comment by floreks** [comment]
I am not sure which version are you referring to, but v2 has token option selected by default.

**Comment by joelharkes** [comment]
Not in my case? 
i use kubernetesui/dashboard:v2.0.0-rc2 but it always pre-selects kubeconfig optinos

**Comment by shu-mutou** [comment]
The former solution using `md-no-asterisk` in #2666 does not seem to work in 2.0. I could not find other solution for now.
