### ISSUE TITLE
Larger time range for metrics

### ISSUE THREAD

**Issue by onitake** [kubernetes/dashboard#2646]
##### Environment

```
Dashboard version: 1.8.0
Kubernetes version: 1.8.3
Heapster: 1.3.0-beta.1
Operating system: CentOS 7
```

##### Feature request

1. Log into dashboard
2. Select a resource with Heapster metrics, for example a pod
3. Zoom in or out of a metric graph or select a specific time range

##### Observed result

There does not seem to be a way to choose a time range.

##### Expected result

There should be controls for zooming in/out of resource graphs and/or for selecting a specific time range.
Alternatively, more than the last 15 minutes should be displayed.

##### Comments

I'm not sure if this feature needs to be implemented in Dashboard, Heapster or both.
Our Heapster installation is backed by an InfluxDB database, so the data should be available somehow.

**Comment by floreks** [comment]
We can add option to choose more time frames on our side, however if heapster is not configured to use database then it will only keep metrics from very short period of time.

**Comment by onitake** [comment]
This would be very nice, yes.

The heapster repo has an example deployment with a backing influxdb ( https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/heapster.yaml ), so I think think it's ok to do this. Perhaps mention it somewhere in the documentation.

**Comment by maciaszczykm** [comment]
Heapster is deprecated and we are going to use metrics API. Issue can be closed because it will be reimplemented.

/close
