### ISSUE TITLE
Since Time Selector (On Logs page)

### ISSUE THREAD

**Issue by digitalfishpond** [kubernetes/dashboard#265]
Currently working on this

**Comment by bryk** [comment]
Nice! What since time selector exactly? On the logs page?

**Comment by digitalfishpond** [comment]
@bryk Hi Piotr, Yes, on the logs page. Just want to check your vision for this task. Do we only need a time picker here? Or is a date picker necessary too?

**Comment by bryk** [comment]
I'd say we need date-time selector. The pod may be running for a few days, so this is the only possible option, I guess.

**Comment by digitalfishpond** [comment]
Ok, I'll work on an implementation that's consistent with the look of the other 2 selectors. Thx!

**Comment by floreks** [comment]
Do we still want this?

**Comment by bryk** [comment]
Yes. Now after @PiotrDabkowski change, it is very valuable.

**Comment by maciaszczykm** [comment]
Let's track it from #1828.
