### ISSUE TITLE
dashboard exec seems not support GBK 

### ISSUE THREAD

**Issue by skytalemcc** [kubernetes/dashboard#2650]
I use the dashboard 1.7.1   when i used the exec to go into the docker and check the application logs in docker ,i see it show chaos .finally i find the reason ,it is due to the dashboard exec seems only support utf-8 character  ,but my application log character is GBK.could you advise is there anyway  to temporary solve this issue .thanks

**Comment by floreks** [comment]
From what I understand GBK is a specialized encoding for Chinese that is not portable. We'd need to add support for it on our side to make it work.

**Comment by pigletfly** [comment]
I recommend https://xtermjs.org/ instead of hterm, xterm has CJK (Chinese, Japanese, Korean) character support.

**Comment by maciaszczykm** [comment]
Good to know that xterm will solve this problem as it was introduced to the new version that is currently under development. You can see the change here: https://github.com/kubernetes/dashboard/pull/3166/files.

We won't update current implementation on master branch so you will have to wait until we will release version after Angular migration.

/triage unresolved
/close

**Comment by maciaszczykm** [comment]
Good to know that xterm solves this problem as it was introduced to the new version that is currently under development. You can see the change in https://github.com/kubernetes/dashboard/pull/3166. We won't update current implementation before finishing Angular migration so you will have to wait a while.

/triage unresolved
/close
