### ISSUE TITLE
404 on attempt to view Deployments using service account token with Cluster Role View binding

### ISSUE THREAD

**Issue by mattreyuk** [kubernetes/dashboard#2654]
##### Environment

```
Dashboard version: 1.8.0 & head (loaded with yaml from src/deploy/recommended)
Kubernetes version: 1.7.9 RBAC auth mode
```

##### Steps to reproduce

1. Create a service account with view access from the provided system view ClusterRole for the default namespace
2. Get the generated token for this service account and use it to login to the dashboard
3. Click on the Deployments link for the default namespace

##### Observed result

A "Not Found 404 page  - the server could not find the requested resource" is displayed before returning to the prior page

##### Expected result

The Deployment page is shown with list of deployments in the default namespace.

##### Comments

The Secrets page (which the view ClusterRole does not have access to shows the empty secret with the banner `User "system:serviceaccount:default:view" cannot list secrets in the namespace "default". (get secrets)` as expected.

The Pods, Config Map, Services pages all correctly show the view data as expected.

Cron Jobs and Stateful sets both exhibit the 404 behavior.

Running ` kubectl auth can-i list deployments -n default --as system:serviceaccount:default:view` returns `yes`

Log snippet from dashboard pod on clicking pods:
```
2017/12/07 17:33:58 [2017-12-07T17:33:58Z] Incoming HTTP/2.0 GET /api/v1/pod/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 101.124.32.0:43568: {}
2017/12/07 17:33:58 Getting list of all pods in the cluster
2017/12/07 17:33:58 No metric client provided. Skipping metrics.
2017/12/07 17:33:58 Getting pod metrics
2017/12/07 17:33:58 No metric client provided. Skipping metrics.
2017/12/07 17:33:58 [2017-12-07T17:33:58Z] Outcoming response to 101.124.32.0:43568 with 200 status code
``` 
Log snippet from dashboard on clicking deployments:
```
2017/12/07 17:38:31 [2017-12-07T17:38:31Z] Incoming HTTP/2.0 GET /api/v1/deployment/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 101.124.32.0:43568: {}
2017/12/07 17:38:31 Getting list of all deployments in the cluster
2017/12/07 17:38:31 the server could not find the requested resource
2017/12/07 17:38:31 [2017-12-07T17:38:31Z] Outcoming response to 101.124.32.0:43568 with 404 status code
```

**Comment by floreks** [comment]
The problem is version of kubernetes you are using. See our [Compatibility Matrix](https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix) to find out which version of Dashboard support which version of K8S.
