### ISSUE TITLE
Dashboard 1.6.3 in default v1.8.4-gke.0 GKE cluster is broken by RBAC

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/dashboard#2659]
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
Kubernetes version: v1.8.4-gke.0
Operating system:
Node.js version:
Go version:
```

##### Steps to reproduce
Create a GKE cluster running on version 1.8: `gcloud container clusters create v1-8 --cluster-version=1.8.4-gke.0 --machine-type=g1-small`
Open up the dashboard by running `kubectl proxy` as instructed by the GKE docs, then open http://localhost:8001/ui

##### Observed result
The UI landing page is full of RBAC warnings:
<img width="1352" alt="screen shot 2017-12-10 at 5 08 51 pm" src="https://user-images.githubusercontent.com/7085343/33810015-3bc48c2a-ddcd-11e7-9bf6-4eb8255ff9d5.png">

I'm similarly unable to view any information if I load one of the other pages. For example, the `pods` page looks like:
<img width="1361" alt="screen shot 2017-12-10 at 5 14 19 pm" src="https://user-images.githubusercontent.com/7085343/33810034-9528b4e4-ddcd-11e7-80e0-03ae4f152d2d.png">

##### Expected result
I'd expect the dashboard to just work. I'd assume that the problem is that the dashboard's version is `v1.6.3`.

##### Comments
Sorry if this is a dupe or has been fixed since `v1.8.4-gke.0`. Paging @roberthbailey

**Comment by maciaszczykm** [comment]
It is an old version of Dashboard where we are displaying errors coming from API server (RBAC stuff). Please install Dashboard 1.8.0 and retry.

I am not sure how GKE installs Dashboard, but if with addon manager you need to update its manifest instead of `kubectl apply -f ...`.

**Comment by floreks** [comment]
Even though this is an old version, everything works as expected. GKE deploys Dashboard with minimal set of privileges. You need to grant Dashboard Service Account additional permissions. You might want to grant it admin privileges depending on the configuration.

https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges

If you need some more help, ping us on `sig-ui` or `kubernetes-users` k8s slack.

**Comment by roberthbailey** [comment]
@bryk
