### ISSUE TITLE
Unable to connect to kuberneter dashboard

### ISSUE THREAD

**Issue by Katiyman** [kubernetes/dashboard#2660]
##### Environment

```
Dashboard version: Latest
Kubernetes version: Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Operating system:centos 7
Node.js version:v6.12.0
Go version: 1.9.2
```

##### Steps to reproduce

1. i deployed the dashboard following the below link
https://github.com/kubernetes/dashboard

2.  i run kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

3. then i try to access it from another machine using the url
https://10.157.145.187:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
4. but i get error mentioned in the observer result 

##### Observed result

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"https:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get services/proxy in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "https:kubernetes-dashboard:",
    "kind": "services"
  },
  "code": 403
}

##### Expected result
Dashboard UI should come up

##### Comments
Unable to understand why this forbidden error and what steps to follow to overcome it.

**Comment by maciaszczykm** [comment]
Are you able to do `kubectl get services -n kube-system`? It seems like RBAC configuration issue.

**Comment by Katiyman** [comment]
Yes
 kubectl get services -n kube-system
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
kube-dns               ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP   4d
kubernetes-dashboard   ClusterIP   10.100.83.130   <none>        443/TCP         9s

**Comment by maciaszczykm** [comment]
Okay, I have just noticed that you are trying to enter Dashboard from a different machine. When you will take a look at https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#kubectl-proxy you will notice following information:

> By default it is only accessible locally (from the machine that started it).

> NOTE: Dashboard should not be exposed publicly using kubectl proxy command as it only allows HTTP connection. For domains other than localhost and 127.0.0.1 it will not be possible to sign in. Nothing will happen after clicking Sign in button on login page.

**Comment by Katiyman** [comment]
Thanks
I checked and followed this
API Server

In case Kubernetes API server is exposed and accessible from outside you can directly access dashboard at: https://<master-ip>:<apiserver-port>/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

but got the error i have mentioned

**Comment by floreks** [comment]
Your api server is exposed but not accessible from outside. You can not access any kubernetes endpoints if you do not authenticate and authorize yourself. This is not a Dashboard issue, but rather configuration.

**Comment by floreks** [comment]
Closing as this is not a Dashboard issue.

**Comment by abhishekunotech** [comment]
Would be useful to at least link to a configuration

**Comment by rifaurasheed** [comment]
> Would be useful to at least link to a configuration

The authentication and authorization setup needed to access the dashboard is described here 
https://github.com/kubernetes/dashboard/wiki/Access-control

**Comment by hillbun** [comment]
@Katiyman 

How to fix this issue?

**Comment by hillbun** [comment]
@Katiyman 

How to fix this issue?

**Comment by jakerobb** [comment]
The wiki link above is no longer current; it's now here:

https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md

Now, to see if I can figure this out -- because I have the same error message despite accessing it from localhost.
