### ISSUE TITLE
Error while installing dashboard on kops (Failed to download OpenAPI)

### ISSUE THREAD

**Issue by tmikulin** [kubernetes/dashboard#2661]
Hi,

I created a cluster on aws with kops version:

**Version 1.6.1 (git-22b22cc)**

**kubectl version:**
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.13", GitCommit:"14ea65f53cdae4a5657cf38cfc8d7349b75b5512", GitTreeState:"clean", BuildDate:"2017-11-22T20:19:06Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**When creating the kubernetes-dashboard with the following command:**

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**The errors that I get were:**

9620 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
secret "kubernetes-dashboard-certs" unchanged
serviceaccount "kubernetes-dashboard" unchanged

**I also tried downloading the file locally, and the creating it, and I got the following errors:**

secret "kubernetes-dashboard-certs" unchanged
serviceaccount "kubernetes-dashboard" unchanged
service "kubernetes-dashboard" created
Error from server (BadRequest): error when creating "kubernetes-dashboard.yaml": Role in version "v1" cannot be handled as a Role: no kind "Role" is registered for version "rbac.authorization.k8s.io/v1"
Error from server (BadRequest): error when creating "kubernetes-dashboard.yaml": RoleBinding in version "v1" cannot be handled as a RoleBinding: no kind "RoleBinding" is registered for version "rbac.authorization.k8s.io/v1"
Error from server (BadRequest): error when creating "kubernetes-dashboard.yaml": Deployment in version "v1beta2" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1beta2"

Tnx,
Tom

**Comment by maciaszczykm** [comment]
Check https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix. Dashboard 1.8 is not compatible with Kubernetes <1.8. It will not work because of `rbac.authorization.k8s.io/v1` API that we are using, it was registered in Kubernetes 1.8. Please update Kubernetes or use an older version of Dashboard (not recommended).

**Comment by tmikulin** [comment]
Cool tnx for you help.

Tom
