### ISSUE TITLE
How to add some logo or picture on dashboard UI?

### ISSUE THREAD

**Issue by sandylss** [kubernetes/dashboard#2662]
##### Environment

```
Dashboard version:1.8.0
Kubernetes version:1.8.4
Operating system:ubuntu 16.10

```

##### Observed result

I deploy dashboard as the offical guide,and the heapster is work well.I want to add some logo on the web UI,but I don't find some configuretion to edit the web.
##### Expected result

I want to know how to edit the dashboard UI.
##### Comments

thank u~

**Comment by maciaszczykm** [comment]
There is no possibility to change the logo from any of the settings/config. We are welcome for any contributions, but we will not work on it in the near future. You can build your own image with a customized logo if you need it.
