### ISSUE TITLE
how to change timezone ?

### ISSUE THREAD

**Issue by RonaldinhoL** [kubernetes/dashboard#2677]
##### Environment
```
Dashboard version:1.8.0
Kubernetes version:1.8.3
Operating system:ubuntu 16.04 lts
```

i have mount host /usr/share/zoneinfo/Asia/Shanghai to pod of dashboard, but it still used UTC on the web page, is there any way to change the timezone?

**Comment by floreks** [comment]
It is not possible to change timezone in Dashboard as we are only displaying CreationTimestamps which are guaranteed to be represented in RFC3339 form and are in UTC. 

From Kubernetes documentation:
>  CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

**Comment by kevinsingapore** [comment]
> It is not possible to change timezone in Dashboard as we are only displaying CreationTimestamps which are guaranteed to be represented in RFC3339 form and are in UTC.
> 
> From Kubernetes documentation:
> 
> > CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

yes，i agree；
and i change the kubernetes-dashboar.yaml file，to mounts the node timezone file；
reboot the dashboard again，it was not effective, the dashboard default timezone did not changed.
