### ISSUE TITLE
login dashboard have errors.

### ISSUE THREAD

**Issue by dytmh** [kubernetes/dashboard#2682]
![051e06bf-9c29-406f-85d0-f8406b13442c](https://user-images.githubusercontent.com/4333197/34030739-30bdc082-e1a9-11e7-9a3f-0e37e2257229.png)

**dashboard-admin.yaml**
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system

**dashboard service**

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard","namespace":"kube-system"},
"spec":{"ports":[{"port":80,"targetPort":9090}],"selector":{"k8s-app":"kubernetes-dashboard"}}}
  creationTimestamp: 2017-12-15T06:14:15Z
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
  resourceVersion: "3373"
  selfLink: /api/v1/namespaces/kube-system/services/kubernetes-dashboard
  uid: 2d3bafe9-e15f-11e7-a74a-525400412138
spec:
  clusterIP: 10.110.179.16
  externalTrafficPolicy: Cluster  ports:  - nodePort: 32092
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:    k8s-app: kubernetes-dashboard  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

[root@master etc]# kubectl get pods --all-namespaces;
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   calico-etcd-b67pk                          1/1       Running   0          1h
kube-system   calico-kube-controllers-685f8bc7fb-r2vlv   1/1       Running   0          1h
kube-system   calico-node-ktkq6                          2/2       Running   0          55m
kube-system   calico-node-txrr6                          2/2       Running   0          1h
kube-system   etcd-master                                1/1       Running   0          1h
kube-system   kube-apiserver-master                      1/1       Running   0          1h
kube-system   kube-controller-manager-master             1/1       Running   0          1h
kube-system   kube-dns-545bc4bfd4-qvhz9                  3/3       Running   0          1h
kube-system   kube-proxy-bw6jr                           1/1       Running   0          55m
kube-system   kube-proxy-pxr5c                           1/1       Running   0          1h
kube-system   kube-scheduler-master                      1/1       Running   0          1h
kube-system   kubernetes-dashboard-676975d47f-kjbmc      1/1       Running   7          52m

[root@master etc]# kubectl -n kube-system get service kubernetes-dashboard
NAME                   TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes-dashboard   NodePort   10.110.179.16   <none>        80:32092/TCP   52m

**Comment by floreks** [comment]
No steps to reproduce. No versions provided. No information about how cluster was provisioned.

Fill out the template correctly and we will reopen. Based on provided information it looks like cluster config issue.
