### ISSUE TITLE
login have errors

### ISSUE THREAD

**Issue by dytmh** [kubernetes/dashboard#2683]
##### Environment
Dashboard version: 1.8.0
Kubernetes version: 1.8.5
Operating system: centos7
```

##### Steps to reproduce
1.$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
2. follow Creating sample user guide.
3.kubectl proxy --address='0.0.0.0'

##### Observed result
1.http://119.28.112.161:32092/
show there errors
![051e06bf-9c29-406f-85d0-f8406b13442c](https://user-images.githubusercontent.com/4333197/34032843-cacc1f08-e1b2-11e7-8602-4c47cf3cfdc5.png)

2.http://119.28.112.161:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
show <h3>Unauthorized</h3>

##### Expected result
no errors

##### Comments
[root@master ~]# kubectl get pods --all-namespaces;
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   calico-etcd-b67pk                          1/1       Running   0          1h
kube-system   calico-kube-controllers-685f8bc7fb-r2vlv   1/1       Running   0          1h
kube-system   calico-node-ktkq6                          2/2       Running   0          1h
kube-system   calico-node-txrr6                          2/2       Running   0          1h
kube-system   etcd-master                                1/1       Running   0          1h
kube-system   kube-apiserver-master                      1/1       Running   0          1h
kube-system   kube-controller-manager-master             1/1       Running   0          1h
kube-system   kube-dns-545bc4bfd4-qvhz9                  3/3       Running   0          2h
kube-system   kube-proxy-bw6jr                           1/1       Running   0          1h
kube-system   kube-proxy-pxr5c                           1/1       Running   0          2h
kube-system   kube-scheduler-master                      1/1       Running   0          1h
kube-system   kubernetes-dashboard-676975d47f-kjbmc      1/1       Running   7          1h


[root@master ~]# kubectl -n kube-system get service kubernetes-dashboard
NAME                   TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes-dashboard   NodePort   10.110.179.16   <none>        80:32092/TCP   1h

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard","namespace":"kube-system"},"s
pec":{"ports":[{"port":80,"targetPort":9090}],"selector":{"k8s-app":"kubernetes-dashboard"}}}
  creationTimestamp: 2017-12-15T06:14:15Z
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
  resourceVersion: "3373"
  selfLink: /api/v1/namespaces/kube-system/services/kubernetes-dashboard
  uid: 2d3bafe9-e15f-11e7-a74a-525400412138
spec:
  clusterIP: 10.110.179.16
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32092
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: kubernetes-dashboard
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

[root@master ~]# kubectl describe pods kubernetes-dashboard-676975d47f-kjbmc --namespace=kube-system
Name:           kubernetes-dashboard-676975d47f-kjbmc
Namespace:      kube-system
Node:           node1/172.22.0.12
Start Time:     Fri, 15 Dec 2017 14:14:15 +0800
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=2325318039
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-676975d47f","uid":"2d38c340-e15f-11e7-a...
Status:         Running
IP:             192.168.166.130
Created By:     ReplicaSet/kubernetes-dashboard-676975d47f
Controlled By:  ReplicaSet/kubernetes-dashboard-676975d47f
Containers:
  kubernetes-dashboard:
    Container ID:   docker://e54cd4d940104648e352941385f4a41e32ac932cc7b18123425288a858017056
    Image:          gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.0
    Image ID:       docker-pullable://gcr.io/google_containers/kubernetes-dashboard-amd64@sha256:71a0de5c6a21cb0c2fbcad71a4fef47acd3e61cd78109822d35e1742f9d8140d
    Port:           9090/TCP
    State:          Running

Node:           node1/172.22.0.12    is other pc

**Comment by floreks** [comment]
Are you sure that the Dashboard version is 1.7?

**Comment by dytmh** [comment]
@floreks sorry. Dashboard version is 1.8

**Comment by dytmh** [comment]
@floreks 
https://119.28.112.161:32092/ 
Invalid response sent

http://119.28.112.161:32092/ 
https://user-images.githubusercontent.com/4333197/34032843-cacc1f08-e1b2-11e7-8602-4c47cf3cfdc5.png

**Comment by floreks** [comment]
This is literally impossible since Dashboard 1.8 by default starts on HTTPS and HTTP endpoint is not available. How/where did you start your cluster?

**Comment by dytmh** [comment]
i delete Dashboard, re install Dashboard.  now https is ok, but errors is same.

[root@master ~]# kubectl -n kube-system get service kubernetes-dashboardNAME                   TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
kubernetes-dashboard   NodePort   10.110.179.16   <none>        443:30117/TCP   3h

@floreks

**Comment by dytmh** [comment]
kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')

i can`t find admin-user-token

**dashboard-admin.yaml**
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system

**Comment by floreks** [comment]
What did `kubectl apply -f dashboard-admin.yaml` returned?

**Comment by dytmh** [comment]
@floreks 
[root@master etc]# kubectl apply -f dashboard-admin.yaml
clusterrolebinding "admin-user" configured

can`t find admin-user-token

**Comment by floreks** [comment]
Do `kubectl -n kube-system get serviceaccount` and `kubectl -n kube-system get clusterrole` and post the results.

**Comment by dytmh** [comment]
[root@master ~]# kubectl -n kube-system get serviceaccount
NAME                         SECRETS   AGE
admin                        1         2h
attachdetach-controller      1         4h
bootstrap-signer             1         4h
calico-cni-plugin            1         4h
calico-kube-controllers      1         4h
certificate-controller       1         4h
cronjob-controller           1         4h
daemon-set-controller        1         4h
default                      1         4h
deployment-controller        1         4h
disruption-controller        1         4h
endpoint-controller          1         4h
generic-garbage-collector    1         4h
horizontal-pod-autoscaler    1         4h
job-controller               1         4h
kube-dns                     1         4h
kube-proxy                   1         4h
kubernetes-dashboard         1         3h
namespace-controller         1         4h
node-controller              1         4h
persistent-volume-binder     1         4h
pod-garbage-collector        1         4h
replicaset-controller        1         4h
replication-controller       1         4h
resourcequota-controller     1         4h
service-account-controller   1         4h
service-controller           1         4h
statefulset-controller       1         4h
token-cleaner                1         4h
ttl-controller               1         4h

[root@master ~]# kubectl -n kube-system get clusterrole
NAME                                                                   AGE
admin                                                                  4h
calico-cni-plugin                                                      4h
calico-kube-controllers                                                4h
cluster-admin                                                          4h
edit                                                                   4h
system:auth-delegator                                                  4h
system:basic-user                                                      4h
system:certificates.k8s.io:certificatesigningrequests:nodeclient       4h
system:certificates.k8s.io:certificatesigningrequests:selfnodeclient   4h
system:controller:attachdetach-controller                              4h
system:controller:certificate-controller                               4h
system:controller:cronjob-controller                                   4h
system:controller:daemon-set-controller                                4h
system:controller:deployment-controller                                4h
system:controller:disruption-controller                                4h
system:controller:endpoint-controller                                  4h
system:controller:generic-garbage-collector                            4h
system:controller:horizontal-pod-autoscaler                            4h
system:controller:job-controller                                       4h
system:controller:namespace-controller                                 4h
system:controller:node-controller                                      4h
system:controller:persistent-volume-binder                             4h
system:controller:pod-garbage-collector                                4h
system:controller:replicaset-controller                                4h
system:controller:replication-controller                               4h
system:controller:resourcequota-controller                             4h
system:controller:route-controller                                     4h
system:controller:service-account-controller                           4h
system:controller:service-controller                                   4h
system:controller:statefulset-controller                               4h
system:controller:ttl-controller                                       4h
system:discovery                                                       4h
system:heapster                                                        4h
system:kube-aggregator                                                 4h
system:kube-controller-manager                                         4h
system:kube-dns                                                        4h
system:kube-scheduler                                                  4h
system:node                                                            4h
system:node-bootstrapper                                               4h
system:node-problem-detector                                           4h
system:node-proxier                                                    4h
system:persistent-volume-provisioner                                   4h
view                                                                   4h

@floreks

**Comment by floreks** [comment]
You did not create service account for `admin-user`...

**Comment by dytmh** [comment]
[root@master etc]# kubectl create -f dashboard-admin.yaml
Error from server (AlreadyExists): error when creating "dashboard-admin.yaml": clusterrolebindings.rbac.authorization.k8s.io "admin-user" already exists

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system

@floreks

**Comment by floreks** [comment]
You need to understand how it works first in order to be able to use kubernetes and dashboard.

**Comment by floreks** [comment]
Closing as this is configuration issue. Ping us on slack if you need further help. On github we are trying to deal with actual issues.

**Comment by WuLeeX** [comment]
I meet the same problem. I setup a kubernetes using kubeadm v1.8.5, and setup a dashboard using:
```
    wget https://raw.githubusercontent.com/kubernetes/dashboard/v1.8.0/src/deploy/recommended/kubernetes-dashboard.yaml
    
    kubectl create -f kubernetes-dashboard.yaml
    kubectl create -f kubernetes-dashboard-admin.rbac.yaml
```
Then,  setup kubectl proxy, using 
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/  as recommended.

**But I CANT access the dashboard via token, when I paste the token and click "Signin" botton, nothing happened. And I get nothing in my log[using tail -f /var/log/messages and journalctl -xeu kubelet]. I am a newbee on k8s, maybe someone could tell me where the log file located?**

Here are my k8s cluster-info:

```
    [root@k8s-1 pki]# kubectl get pods --all-namespaces
    NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
    kube-system   etcd-k8s-1                              1/1       Running   2          4d
    kube-system   kube-apiserver-k8s-1                    1/1       Running   2          4d
    kube-system   kube-controller-manager-k8s-1           1/1       Running   1          4d
    kube-system   kube-dns-545bc4bfd4-94vxx               3/3       Running   3          4d
    kube-system   kube-flannel-ds-97frd                   1/1       Running   2          4d
    kube-system   kube-flannel-ds-bl9tp                   1/1       Running   2          4d
    kube-system   kube-flannel-ds-bn9hp                   1/1       Running   1          4d
    kube-system   kube-proxy-9ncdm                        1/1       Running   0          4d
    kube-system   kube-proxy-qjm9k                        1/1       Running   1          4d
    kube-system   kube-proxy-rknz4                        1/1       Running   0          4d
    kube-system   kube-scheduler-k8s-1                    1/1       Running   2          4d
    kube-system   kubernetes-dashboard-7486b894c6-tszq9   1/1       Running   0          2h
    [root@k8s-1 pki]# 
    [root@k8s-1 pki]# kubectl get nodes
    NAME      STATUS    ROLES     AGE       VERSION
    k8s-1     Ready     master    4d        v1.8.5
    k8s-2     Ready     <none>    4d        v1.8.5
    k8s-3     Ready     <none>    4d        v1.8.5
    [root@k8s-1 pki]# kubectl cluster-info
    Kubernetes master is running at https://172.16.1.15:6443
    KubeDNS is running at https://172.16.1.15:6443/api/v1/namespaces/kube-system/services/kube-dns/proxy
    kubernetes-dashboard is running at https://172.16.1.15:6443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
    
    To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

here is my kubernetes-dashboard-admin-rbac.yaml:

```
    [root@k8s-1 dashboards]# cat kubernetes-dashboard-admin.rbac.yaml 
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
        kubernetes.io/cluster-service: "true"
        addonmanager.kubernetes.io/mode: Reconcile
      name: kubernetes-dashboard-admin
      namespace: kube-system
      
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: kubernetes-dashboard-admin
      annotations:
        rbac.authorization.kubernetes.io/autoupdate: "true"
      labels:
        k8s-app: kubernetes-dashboard
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - kind: ServiceAccount
      name: kubernetes-dashboard-admin
      namespace: kube-system
```

more infos:

```
[root@k8s-1 dashboards]# kubectl -n kube-system get serviceaccount
NAME                         SECRETS   AGE
attachdetach-controller      1         4d
bootstrap-signer             1         4d
certificate-controller       1         4d
cronjob-controller           1         4d
daemon-set-controller        1         4d
default                      1         4d
deployment-controller        1         4d
disruption-controller        1         4d
endpoint-controller          1         4d
flannel                      1         4d
generic-garbage-collector    1         4d
horizontal-pod-autoscaler    1         4d
job-controller               1         4d
kube-dns                     1         4d
kube-proxy                   1         4d
kubernetes-dashboard         1         2h
kubernetes-dashboard-admin   1         2h
namespace-controller         1         4d
node-controller              1         4d
persistent-volume-binder     1         4d
pod-garbage-collector        1         4d
replicaset-controller        1         4d
replication-controller       1         4d
resourcequota-controller     1         4d
service-account-controller   1         4d
service-controller           1         4d
statefulset-controller       1         4d
token-cleaner                1         4d
ttl-controller               1         4d

[root@k8s-1 dashboards]# kubectl -n kube-system get clusterrole
NAME                                                                   AGE
admin                                                                  4d
cluster-admin                                                          4d
edit                                                                   4d
flannel                                                                4d
system:auth-delegator                                                  4d
system:basic-user                                                      4d
system:certificates.k8s.io:certificatesigningrequests:nodeclient       4d
system:certificates.k8s.io:certificatesigningrequests:selfnodeclient   4d
system:controller:attachdetach-controller                              4d
system:controller:certificate-controller                               4d
system:controller:cronjob-controller                                   4d
system:controller:daemon-set-controller                                4d
system:controller:deployment-controller                                4d
system:controller:disruption-controller                                4d
system:controller:endpoint-controller                                  4d
system:controller:generic-garbage-collector                            4d
system:controller:horizontal-pod-autoscaler                            4d
system:controller:job-controller                                       4d
system:controller:namespace-controller                                 4d
system:controller:node-controller                                      4d
system:controller:persistent-volume-binder                             4d
system:controller:pod-garbage-collector                                4d
system:controller:replicaset-controller                                4d
system:controller:replication-controller                               4d
system:controller:resourcequota-controller                             4d
system:controller:route-controller                                     4d
system:controller:service-account-controller                           4d
system:controller:service-controller                                   4d
system:controller:statefulset-controller                               4d
system:controller:ttl-controller                                       4d
system:discovery                                                       4d
system:heapster                                                        4d
system:kube-aggregator                                                 4d
system:kube-controller-manager                                         4d
system:kube-dns                                                        4d
system:kube-scheduler                                                  4d
system:node                                                            4d
system:node-bootstrapper                                               4d
system:node-problem-detector                                           4d
system:node-proxier                                                    4d
system:persistent-volume-provisioner                                   4d
view                                                                   4d

```


Any suggestions? Thank you!!!

**Comment by sachet-synapsefi** [comment]
you will have to create a `kind: ServiceAccount` and then connect it to a `kind: ServiceAccount`. if you already have the user, delete it and run it again. that worked for me
