### ISSUE TITLE
The default dashboard link seems broken

### ISSUE THREAD

**Issue by konryd** [kubernetes/dashboard#2684]
The front github page says:
`http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/.
`

Whereas it should rather say:
`http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/.`

**Comment by floreks** [comment]
The link is correct if you use steps provided in README to deploy Dashboard. Provided link works with older versions of Dashboard and with alternative deployment where HTTPS is disabled.
