### ISSUE TITLE
[kubernetes-dashboard] rbac.create=true seems not to work

### ISSUE THREAD

**Issue by monotek** [kubernetes/dashboard#2685]
When installing kubernetes-dashboard via helm and using the rbac.create=true option i get a rbac related errors anyway when accessing the dashboard via: 

http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

I expected rbac is handled by the "rbac.create=true" option but it seem not to work.

##### Environment
Empty 3 Node cluster on Google Kubernetes Engine

```
Dashboard version: 1.8.0
Kubernetes version: 1.8.4
Operating system: Google Container OS
```

##### Steps to reproduce
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller
helm install stable/kubernetes-dashboard --set rbac.create=true,imageTag=v1.8.0 --name kubernetes-dashboard

##### Observed result
A lot of errors in Dashboard like:

configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "default": Unknown user "system:serviceaccount:kube-system:default"
close

##### Expected result
No Error messages in Dashboard

**Comment by floreks** [comment]
Sorry, but we can't help with helm related issues. On our side everything works fine. Either Dashboard helm chart or cluster is not configured properly and RBACs are not working correctly.

Try reporting that on helm repo.
