### ISSUE TITLE
[question] Is there a plan for people to orchestrate resources graphically, and drag & drop to define and generate YAML/JSON files?

### ISSUE THREAD

**Issue by warmchang** [kubernetes/dashboard#2692]
This is a question and kind/feature.

Is there a plan for people to orchestrate resources graphically, and drag & drop to define and generate YAML/JSON files?

Thanks!

**Comment by floreks** [comment]
Interesting idea. How do you think this would look like and work? We haven't considered anything like that as we don't have any active designers and only few developers. It's still an interesting idea so we can discuss it.

**Comment by rahuldhide** [comment]
This is a really good idea. Please share more thoughts on the same. @floreks I would add this in the UX improvements and then create some design options.

**Comment by floreks** [comment]
Sure, we can add this feature request to our UX improvements list.

**Comment by zhangxiaoyu-zidif** [comment]
great, I'd like it. Let do something to start it. writing a yaml, especially json manually is really tough.

**Comment by maciaszczykm** [comment]
Closing as stale.
