### ISSUE TITLE
pod edit filter

### ISSUE THREAD

**Issue by massimodeluisa** [kubernetes/dashboard#2696]
##### Steps to reproduce
1. Open k8s dashboard locally with `kubectl proxy`
2. Open the **Workloads** section and scroll to the **Pod** section

[http://localhost:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/workload?namespace=production](http://localhost:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/workload?namespace=production)

3. Press the vertical point on the right of a pod line record and then `View edit YAML` 
4. On the edit view, type something in the top right search bar
5. Clear the search

now you cannot edit anymore the pod YAML either if you try to reopen that view, probably because of the cache.

##### Environment
```
Installation method: "default Google Cloud Engine"
Kubernetes version: v1.7.8-gke.0
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
No error data available
```

##### Comments
Browser used: Google Chrome
Version: 63.0.3239.84 (64 bit)
Platform: Mac Os X 10.13.2

**Comment by floreks** [comment]
I think you are using old version of Dashboard (`v1.7.X`). Latest version is `v1.8.1`, however it only works with k8s 1.8+. We have fixed many issues in new versions so it is highly possible that this is also fixed. Try to upgrade and recheck.
