### ISSUE TITLE
Logs - Dashboard reported Not Found (404): pods "default" not found

### ISSUE THREAD

**Issue by funkswing** [kubernetes/dashboard#2698]
##### Steps to reproduce

After upgrading Master/Nodes to 1.8.4, the logs for a pods cannot be viewed.

##### Environment
```
Installation method: GKE
Kubernetes version: 1.8.4
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Not Found (404):
```
pods "default" not found

```

##### Comments

Deleting and recreating deployments does not solve the issue

**Comment by floreks** [comment]
Update Dashboard version. Compatibility matrix can be found on our wiki.
