### ISSUE TITLE
Add license comments

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#2702]
Some projects add license comments to all (production) dependencies.

https://github.com/openstack/monasca-api/blob/master/requirements.txt

Seems like a good practice to me. We could do the same for package.json. WDYT?

**Comment by floreks** [comment]
You mean all our files that accept comments (except vendored deps)? Mainly at the top level of repo.

**Comment by cheld** [comment]
Only package.json and Gopkg.tom, e.g.

"angular-animate": "~1.6.6",  # Apache 2.0

It simplifies for us the process of verifying 3rd party licenses.

**Comment by floreks** [comment]
Unfortunately, we can not do that for `package.json` as JSON standard does not allow comments. The only (hacky) way to simulate comments is to use `//` as the key but this forces us to add new line per every dependency we want to comment. For Go dependencies, we are pretty much using same dependencies as the kubernetes core so it is either MIT or Apache 2.0 license and we don't need to worry about licenses there.

**Comment by cheld** [comment]
ok makes sense
