### ISSUE TITLE
Any plans to move to Angular 2+ ?

### ISSUE THREAD

**Issue by pengx17** [kubernetes/dashboard#2712]
Currently the frontend project is written with AngularJS. As far as I can see this project follows AngularJS best practice towards migration to the new Angular version (2+), not sure if the k8s dashboard team has any plans to moving forward to migrate this project to Angular?

**Comment by maciaszczykm** [comment]
We had plans to move to the newest version of Angular. @floreks started to change build process, but after a week or two, we have decided to postpone it. It requires **a lot** of changes and we cannot spend 100% of our time on refactoring. It would be a **very** good change though. 

Are you willing to help? Why do you need it?

**Comment by floreks** [comment]
The main problem lies in our build system as we are not using i.e. only webpack to manage our dependencies + we are using google closure compiler with advanced optimizations to build our bundled js files. AFAIK latest angular 5 has some issues working with closure compiler. Additionally we are using `goog.getMsg` and closure library for translations. We'd have to get rid of that and use some other mechanism as it was also not compatible with latest angular.

We'd have to start with a complete rebuild of our build system and then think about getting rid of other things that are stopping us from migration.

**Comment by pengx17** [comment]
Thanks for the insights.

Despite the facts of dependency limitations and refactoring impacts, I suppose some developers like me may have an intuition that if this project is implemented with AngularJS there may be a risk in long time maintenance.

**Comment by maciaszczykm** [comment]
Closing in favour of #2726.
