### ISSUE TITLE
Why does the service I created have not shown success or failure, and can't be deleted?

### ISSUE THREAD

**Issue by amlyj** [kubernetes/dashboard#2713]
##### Environment

```
Dashboard version:1.6.0
Kubernetes version:1.5.2
Operating system:centos7
Node.js version:None
Go version:None
```

##### Steps to reproduce

* i'm get the tagv1.6.0 dashboard.yaml
* kubectl create -f dashborad.yaml, but it's fail
* look it 
![qq 20171226235659](https://user-images.githubusercontent.com/20984777/34360161-066ecdfa-ea99-11e7-9c32-37433af23256.png)

**Comment by floreks** [comment]
Wrong namespace. It is in `kube-system` namespace.
