### ISSUE TITLE
Dashboard reported Service Unavailable (503)

### ISSUE THREAD

**Issue by IsmailMarmoush** [kubernetes/dashboard#2724]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: @@BUILD_DASHBOARD_VERSION
Commit: @@BUILD_GIT_COMMIT
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'EOF'
Trying to reach: 'http://10.2.110.4:9090/api/v1/pod/default/matchmaking-live-2694862331-qn9s7/log'
```

**Comment by IsmailMarmoush** [comment]
@maciaszczykm  Sorry about the missing details, I will update with more info, let me know if there are more info needed

**Comment by maciaszczykm** [comment]
@IsmailMarmoush, first of all, you are using a very old version of Dashboard. Update it and check how it works out. Let us know if any errors will occur.

**Comment by IsmailMarmoush** [comment]
@maciaszczykm  Very sorry for the confusion, It was very confusing we're using it here in our company and I thought I was submitting this issue to our internal Github enterprise. Thanks a lot for your help
