### ISSUE TITLE
firefox login is show unauthorized in mac

### ISSUE THREAD

**Issue by dytmh** [kubernetes/dashboard#2742]
##### Environment
Dashboard version: v1.8.5
Kubernetes version: v1.8.5 
Operating system: CentOS  7
Node.js version: -
Go version: -

##### Steps to reproduce
login dashboard

Observed result
1. I use firefox login is no problem in win10
2. I use firefox login is show unauthorized in mac
3. My friend use firefox login is no problem in mac

firefox version :  57.0.4
mac version : 10.13.2

Expected result

Comments
  Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by floreks** [comment]
Not enough details and wrong Dashboard version provided. We need more info about cluster/dashboard deployment and how you are accessing Dashboard. Closing until all the details are provided.
