### ISSUE TITLE
Setup merge automation for this repo

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/dashboard#2747]
I'd like to setup merge automation for this repo.  This means:

Use an OWNERS file, /approve, /lgtm to allow people to merge PR's into this repo:
- If there isn't an OWNERS file, create one and populate it with people who already have write access to this repo (as approvers)
- Configure prow to turn on the "approval" plugin for this repo
- Configure prow/tide to include this repo in the tide query

/assign

**Comment by floreks** [comment]
Adding OWNERS file we can do but as for the configuration of plugins goes I think only repo admin can do that. @bryk would have to take a look.

**Comment by bryk** [comment]
@floreks Can you investigate why you're not an admin for this repo? What are guidelines for adding ppl as repo admins?

**Comment by bryk** [comment]
@spiffxp I can do this. What are exact steps I need to do?

**Comment by floreks** [comment]
@bryk For a user-owned repository collaborators cannot have more privileges.

https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account

**Comment by bryk** [comment]
@floreks This is kubernetes repo. All you need to do is to be added to the @kubernetes/dashboard-admins group.

**Comment by floreks** [comment]
Great. I thought that only you can manage those groups. We will request to join it.

**Comment by spiffxp** [comment]
The rest of the steps are things I will do myself via PR's to the kubernetes/test-infra repo, no additional steps are needed on your part
