### ISSUE TITLE
The convenient and quick function is gone！

### ISSUE THREAD

**Issue by Bruce-sz** [kubernetes/dashboard#2750]
##### Steps to reproduce

Dashboard version: v1.8.1 **# vs** v1.8.0

<img width="519" alt="qq20180110-083619 2x" src="https://user-images.githubusercontent.com/5813610/34750348-9d065aaa-f5e1-11e7-9d39-7ad0c7cdde88.png">
<img width="692" alt="qq20180110-083459 2x" src="https://user-images.githubusercontent.com/5813610/34750355-a280f5f8-f5e1-11e7-9e6a-4d0d75c88704.png">

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.1
Commit: 7b3553aecf28224ef7275e157b5bba7dd23f436a
```

**Comment by floreks** [comment]
We have decided to change editor mode to raw code editor in order to allow easy manual edit of resources. You can use it as any text editor with syntax highlighting and easily adjust resources. Old editor was a bit buggy and as it was 3rd party library we did not want to wait for bug fixes.
