### ISSUE TITLE
Load your own certificate chain for dashboard?

### ISSUE THREAD

**Issue by eroji** [kubernetes/dashboard#2751]
##### Environment

```
Dashboard version: 1.81
Kubernetes version: 1.91
Operating system: CentOS 7
Node.js version:
Go version:
```

##### Steps to reproduce
The default configuration for Kubernetes Dashboard does not provide any certificates. Is there a way to load your own certificate chain so that it can be properly controlled and presented by the ingress controller?

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments

There are cert related arguments that you can pass to load your own certificates. By default certs are auto-generated and stored inside the secret resource (`kubernetes-dashboard-certs`).
