### ISSUE TITLE
Deep-linking to logs of a specific container within a pod has become broken

### ISSUE THREAD

**Issue by jstangroome** [kubernetes/dashboard#2760]
##### Environment
```
Dashboard version: 1.8.0 (git commit 054916b8fbadebd32dc16d32108fdd3c9ccbf400)
Kubernetes version: 1.8.0 (via minikube 0.24.1)
Operating system: Windows 10 x64 host with VirtualBox 5.1.30 and Minikube guest OS on Buildroot 2017.02 with kernel Linux minikube 4.9.13
```

##### Steps to reproduce

1. Open the logs page for a Pod with two or more containers.
2. Note the URL in the browser address bar.
3. Select a different container.
4. Note the URL in the browser address bar doesn't change.
5. Open the URL in a new tab and note the new tab shows the logs for a different container in the pod.

##### Expected result
The container selected on the Log page should be represented in the URL so that bookmarking or sharing the URL will still refer to the correct container. In a Dashboard version prior to 1.8.0 (sorry not sure which) the container was part of the URL.

Previously the URL took the form:
`/#!/log/<namespace>/<pod>/<container>?namespace=<namespace>`

But now in Dashboard 1.8.0 the URL to the log page has replaced the container name with the constant literal "pod":
`/#!/log/<namespace>/<pod>/pod?namespace=<namespace>`

**Comment by floreks** [comment]
We'll keep that in mind while migrating to new angular version.
