### ISSUE TITLE
Error: 'dial tcp 10.244.1.7:8443: getsockopt: connection timed out'

### ISSUE THREAD

**Issue by JiaLei123** [kubernetes/dashboard#2764]
##### Environment

After run kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml and after dashboard is running, 
After run kubectl proxy and open link http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

Is always show Error "Error: 'dial tcp 10.244.1.7:8443: getsockopt: connection timed out'"

```
Dashboard version:
latest version 
Kubernetes version:
V1.9.1
Operating system:
linux
Node.js version:
Go version:
```

**Comment by floreks** [comment]
Looks like a cluster issue to me. Connection timed out means that there are some issues with apiserver not dashboard.
