### ISSUE TITLE
Error: 'tls: oversized record received with length 20527' Trying to reach: 'https://172.17.0.4:9090/'

### ISSUE THREAD

**Issue by jpavanaryan** [kubernetes/dashboard#2772]
I setup Kubernetes cluster with Minikube and setup the  [JHipster microservices](http://www.jhipster.tech/kubernetes/) on Kubernetes cluster with the following commands. 

```
WARNING! You will need to push your image to a registry. If you have not done so, use the following commands to tag and push the images:
  	docker image tag books duppoc/books
  	docker image push duppoc/books
  	docker image tag bookstore duppoc/bookstore
  	docker image push duppoc/bookstore

You can deploy all your apps by running: 
	kubectl apply -f namespace.yml  
	kubectl apply -f console
  	kubectl apply -f registry
  	kubectl apply -f books
  	kubectl apply -f bookstore

Use these commands to find your application's IP addresses:
  	kubectl get svc bookstore
```

After this, I tried to open Kubernetes dashboard to see all containers. I tried to follow the instructions mentioned [here](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui). However, I am getting following error 
```
Error: 'dial tcp 172.17.0.4:9090: getsockopt: connection refused'
Trying to reach: 'https://172.17.0.4:9090/'
```
```
$ kubectl get services
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                   AGE
books                    ClusterIP      10.101.116.144   <none>        8081/TCP                                                                  3d
books-mysql              ClusterIP      10.105.15.73     <none>        3306/TCP                                                                  3d
bookstore                LoadBalancer   10.101.207.112   <pending>     8080:30201/TCP                                                            3d
bookstore-mysql          ClusterIP      10.111.4.93      <none>        3306/TCP                                                                  3d
consul                   ClusterIP      None             <none>        8500/TCP,8400/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP   3d
jhipster-console         ClusterIP      10.104.235.209   <none>        5601/TCP                                                                  3d
jhipster-elasticsearch   ClusterIP      10.106.16.149    <none>        9200/TCP,9300/TCP                                                         3d
jhipster-logstash        ClusterIP      10.99.106.2      <none>        5000/UDP                                                                  3d
kubernetes               ClusterIP      10.96.0.1        <none>        443/TCP                                                                   3d

```

**Comment by jpavanaryan** [comment]
Based on #2691 I am able to access my dashboard using following link [http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy](http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy). I am not sure why wasn't [this](http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/) working. Refer #2691 for more information.


Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://172.17.0.4:9090/'

**Comment by floreks** [comment]
Minikube by default installs Dashboard in alternative version which means that HTTPS is disabled. They might be using addon manager to install it so it is not possible to install newer version easily.

Also `kubernetes.io` documentation is outdated and you should only use our official documentation available on https://github.com/kubernetes/dashboard or on our wiki pages https://github.com/kubernetes/dashboard/wiki. `xxx/ui` endpoint is also deprecated and will be removed in future kubernetes versions. You should use direct service proxy path to access Dashboard.

**Comment by belgacea** [comment]
@pavankjadda Take a look at [this](https://github.com/kubernetes/dashboard/issues/2691#issuecomment-368591700)
