### ISSUE TITLE
in dashboard code,how to set default chinese(zh)?

### ISSUE THREAD

**Issue by ap6108** [kubernetes/dashboard#2774]
##### Environment

```
Dashboard 1.8.2:
Kubernetes 1.9.1:
Operating system: ubuntu server 16.04
Node.js version: 9.4.0
Go version: 1.9.2
```

##### Steps to reproduce

in dashboard code,how to set default chinese(zh)?
and i modify handler/localhandler.go
defaultLocaleDir = "zh"

and the chrome browser display still engilsh.
note,the chrome setting chinese language.

how to set dashboard to chinese,and display chinese ?
thanks!
##### Observed result

how to set dashboard to chinese,and display chinese ?
thanks!
##### Expected result

how to set dashboard to chinese,and display chinese ?
thanks!

**Comment by wjzhangcsu** [comment]
哥们，你哪个地方看不懂吗？

**Comment by ap6108** [comment]
@wjzhangcsu dashboard1.8.2源代码npm i OK，然后使用gulp serve也运行OK，但是显示的是英文界面，如何设置显示中文界面?在哪里设置？

**Comment by wjzhangcsu** [comment]
我也是才接触这个不久，据我所知，这个项目还比较新，目前应该还没有支持中文。你如果没玩过k8s，就算是把界面给你翻译成中文效果还是和英文一样，如果你玩过k8s，那么你就会知道中文英文没什么区别。

**Comment by floreks** [comment]
Current Dashboard language is based on browser's locale. Supported languages are mentioned here: https://github.com/kubernetes/dashboard/wiki/Internationalization

You can also set `ACCEPT_LANGUAGE` environment variable inside Dashboard docker container to override language as introduced in https://github.com/kubernetes/dashboard/pull/2402.
