### ISSUE TITLE
Exec into pod can not work for alpine container

### ISSUE THREAD

**Issue by wjzhangcsu** [kubernetes/dashboard#2775]
##### Environment
```
Installation method: I don't remember it~
Kubernetes version:v1.8.0
Dashboard version: v1.8.0
Commit: 054916b8fbadebd32dc16d32108fdd3c9ccbf400
```

##### Observed result

I found "Exec into pod" has a problem.It can work normally when my docker image from ubuntu,but it doesn't work when my docker image from alpine. 

##### Comments

I try to exec "kubectl exec -it podname sh",and this command can work for ubuntu and alpine container.  Maybe we need to fix this little bug~

**Comment by floreks** [comment]
Support for more shell types already mentioned in https://github.com/kubernetes/dashboard/issues/2029.
