### ISSUE TITLE
Failed to use kubectl proxy to access dashboard when enable certificate authentication 

### ISSUE THREAD

**Issue by cheyang** [kubernetes/dashboard#2778]
##### Environment

```
Dashboard version: 1.8.2
Kubernetes version: v1.8.4
Operating system: Centos 7.4
Node.js version:
Go version:
```

##### Steps to reproduce
1. configure CA instead of --auto-generate-certificates
```
 - --tls-key-file=/certs/dashboard.key
    - --tls-cert-file=/certs/dashboard.crt
    - --tls-ca-file=/certs/dashboard-ca.crt
```
2. I can curl it successfully inside the cluster

```
curl -L -v --cacert ./cert/ca.crt --cert ./cert/client.crt --key ./cert/key.crt https://192.168.134.160:6443
```

3. but when I use 'kubectl proxy', it's failed

##### Observed result

```
Error: 'remote error: tls: bad certificate'
Trying to reach: 'https://172.16.0.3:8443/'
```
##### Expected result

```
It should provide the way to add key/cert for authencation
```

##### Comments

```
I imported pkc12 into the browser, it doesn't help.
openssl pkcs12 -export -inkey key.key -in cert.pem -out iphone_dev.p12
but I can access it without `kubectl proxy`
```

**Comment by floreks** [comment]
1. Dashboard does not have `--tls-ca-file` flag.
2. I think that pkcs12 cert might not be supported at some point. We have used x509 format and it worked fine.

Taken from our init container
`openssl req -x509 -nodes -newkey rsa:2048 -keyout dashboard.key -out dashboard.crt -days 365 -subj "/C=/ST=/L=/O=/OU=/CN=kubernetes-dashboard"\n\`
