### ISSUE TITLE
History of jobs in Cron Jobs view

### ISSUE THREAD

**Issue by dzoeteman** [kubernetes/dashboard#2786]
##### Environment

```
Dashboard version: master
Kubernetes version: 1.8.0
```
As was discussed in #2438, it would be great to have a history of jobs available in the Cron Job view, not just the active ones.

**Comment by Sai-Adarsh** [comment]
Is it still open? If so, could I work on this?

**Comment by floreks** [comment]
You are welcome to work on this.

**Comment by maciaszczykm** [comment]
It is already done on master.

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/resource/workloads/cronjob/detail/template.html#L81

/close
