### ISSUE TITLE
kubernetes-dashboard ServiceAcc is not getting full admin privileges

### ISSUE THREAD

**Issue by den-is** [kubernetes/dashboard#2787]
##### Environment
Fresh kubernetes 1.9.2 setup via kubeadm. single master, single worker dev setup.

```
Dashboard version: 1.8.2
Kubernetes version: 1.9.2
Operating system: centos 7.4
```

##### Steps to reproduce
- Grant dashboard-admin full admin privileges by as by https://github.com/kubernetes/dashboard/wiki/Access-control#official-release
- Press skip on login view
- Try to edit `Settings` and you will get:

##### Observed result
```
Forbidden (403)
You do not have required permissions to access this page.
```

##### Expected result
Normal settings view were you can set refresh interval and number of items per page.

##### Comments
Creating "admin" Service Account, as described in wiki, works just fine
https://github.com/kubernetes/dashboard/wiki/Creating-sample-user

**Comment by maciaszczykm** [comment]
> Normal settings view were you can set refresh interval and number of items per page.

Is not an expected result if you are not authorized to do it. We are not raising privileges and you are not allowed to edit settings config map in kube-system namespace.

**Comment by maciaszczykm** [comment]
> Creating "admin" Service Account, as described in wiki, works just fine
https://github.com/kubernetes/dashboard/wiki/Creating-sample-user

Use this account instead of pressing skip button.

**Comment by floreks** [comment]
As `Skip` button is available for everyone then it is not expected to allow everyone to be able to change global settings. Dashboard itself cannot edit them and this is intentional. If you want to be able to edit settings when using `Skip` button then you need to disable settings authorizer. There is an argument `disable-settings-authorizer` you can use to disable it.
https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments

**Comment by den-is** [comment]
No problem. I'm logging in with separate admin which I've created using your Wiki as guiide.
Were RoleBinding config looks absolutely similar to one described [here](https://github.com/kubernetes/dashboard/wiki/Access-control#official-release), except `label` in meta.

So I thought that something is not OKAY.

Thanks for pointing on dashboard arguments, will take a look.

**Comment by itkroplis** [comment]
I upgraded Cluster from 1.13 to 1.17  and kubernetes-dasboard access lost. I try giv permission but i get errors. 
The ClusterRoleBinding "kubernetes-dashboard" is invalid: subjects[0].namespace: Required value

How is new .yaml for cluster-admin access?
