### ISSUE TITLE
dashboard can not run on master 

### ISSUE THREAD

**Issue by lpxxn** [kubernetes/dashboard#2799]
i use kubeadm to install my cluster and i can not run dashboard on master

My Step
1.
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

`secret "kubernetes-dashboard-certs" created
serviceaccount "kubernetes-dashboard" created
role "kubernetes-dashboard-minimal" created
rolebinding "kubernetes-dashboard-minimal" created
deployment "kubernetes-dashboard" created
service "kubernetes-dashboard" created
`

2.
`kubectl get pods --all-namespaces -o wide`
`NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP              NODE
default       tomcat001-667844b98-8hk47               1/1       Running   1          2d        10.244.1.15     worker-node1
default       tomcat001-667844b98-mlqrj               1/1       Running   1          2d        10.244.1.14     worker-node1
kube-system   etcd-k8s-master                         1/1       Running   1          3d        192.168.0.118   k8s-master
kube-system   kube-apiserver-k8s-master               1/1       Running   1          3d        192.168.0.118   k8s-master
kube-system   kube-controller-manager-k8s-master      1/1       Running   1          3d        192.168.0.118   k8s-master
kube-system   kube-dns-6f4fd4bdf-qdzg6                3/3       Running   3          3d        10.244.0.10     k8s-master
kube-system   kube-flannel-ds-5zmlg                   1/1       Running   3          3d        192.168.0.105   worker-node1
kube-system   kube-flannel-ds-lvxpc                   1/1       Running   1          3d        192.168.0.118   k8s-master
kube-system   kube-proxy-c99qs                        1/1       Running   1          3d        192.168.0.118   k8s-master
kube-system   kube-proxy-g4nfm                        1/1       Running   3          3d        192.168.0.105   worker-node1
kube-system   kube-scheduler-k8s-master               1/1       Running   1          3d        192.168.0.118   k8s-master
kube-system   kubernetes-dashboard-845747bdd4-j92zb   0/1       Error     0          21s       10.244.1.20     worker-node1
`

3. 
`kubectl logs kubernetes-dashboard-845747bdd4-j92zb  -n kube-system`

`2018/01/29 02:08:20 Using in-cluster config to connect to apiserver
2018/01/29 02:08:20 Using service account token for csrf signing
2018/01/29 02:08:20 No request provided. Skipping authorization
2018/01/29 02:08:20 Starting overwatch
2018/01/29 02:08:20 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: getsockopt: no route to host
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ
`
4.
`kubectl describe pod kubernetes-dashboard-845747bdd4-j92zb  -n kube-system
`
`Name:           kubernetes-dashboard-845747bdd4-j92zb
Namespace:      kube-system
Node:           worker-node1/192.168.0.105
Start Time:     Mon, 29 Jan 2018 10:07:29 +0800
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=4013036880
Annotations:    <none>
Status:         Running
IP:             10.244.1.20
Controlled By:  ReplicaSet/kubernetes-dashboard-845747bdd4
Containers:
  kubernetes-dashboard:
    Container ID:  docker://f560800714739c023a168f4f43d18079f7f5fa275a04cd0f4a8e706e01dad853
    Image:         k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.2
    Image ID:      docker-pullable://k8s.gcr.io/kubernetes-dashboard-amd64@sha256:e7984d10351601080bbc146635d51f0cfbea31ca6f0df323cf7a58cf2f6a68df
    Port:          8443/TCP
    Args:
      --auto-generate-certificates
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 29 Jan 2018 10:11:25 +0800
      Finished:     Mon, 29 Jan 2018 10:11:27 +0800
    Ready:          False
    Restart Count:  5
    Liveness:       http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-s6zsf (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  kubernetes-dashboard-token-s6zsf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-s6zsf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                      From                   Message
  ----     ------                 ----                     ----                   -------
  Normal   Scheduled              5m                       default-scheduler      Successfully assigned kubernetes-dashboard-845747bdd4-j92zb to worker-node1
  Normal   SuccessfulMountVolume  5m                       kubelet, worker-node1  MountVolume.SetUp succeeded for volume "tmp-volume"
  Normal   SuccessfulMountVolume  5m                       kubelet, worker-node1  MountVolume.SetUp succeeded for volume "kubernetes-dashboard-certs"
  Normal   SuccessfulMountVolume  5m                       kubelet, worker-node1  MountVolume.SetUp succeeded for volume "kubernetes-dashboard-token-s6zsf"
  Normal   Pulled                 3m (x4 over 4m)          kubelet, worker-node1  Container image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.2" already present on machine
  Normal   Created                3m (x4 over 4m)          kubelet, worker-node1  Created container
  Normal   Started                3m (x4 over 4m)          kubelet, worker-node1  Started container
  Warning  BackOff                <invalid> (x31 over 4m)  kubelet, worker-node1  Back-off restarting failed container
`

and i have run the code 
`kubectl taint nodes --all node-role.kubernetes.io/master-`

network used flannel

**Comment by floreks** [comment]
> Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: getsockopt: no route to host 

This error clearly shows that there is an issue with networking in your cluster. Main kubernetes service can not be reached.

**Comment by lpxxn** [comment]
curl -k https://10.96.0.1:443/version

![image](https://user-images.githubusercontent.com/7147958/35551407-e584fb0e-05c9-11e8-988d-28e6cb9498f8.png)

**Comment by floreks** [comment]
It can not be reached from inside the container...

**Comment by lpxxn** [comment]
thanks @floreks 

but i don know how to slove the problem

i use kubeadm to setup my cluster
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

network use flannel

![image](https://user-images.githubusercontent.com/7147958/35554937-70cd965e-05d8-11e8-9942-dd4cf0f2bc5f.png)


it looks my cluster is ok.

**Comment by lpxxn** [comment]
i modify the apiserver to host ip

![image](https://user-images.githubusercontent.com/7147958/35555725-1396d74a-05db-11e8-93c0-a3b3f2eab8f7.png)

same error 

![image](https://user-images.githubusercontent.com/7147958/35555758-2fb1bdbe-05db-11e8-8903-103bcd4f43c7.png)

**Comment by floreks** [comment]
It's not a Dashboard issue. Container networking fails to resolve those addresses.

**Comment by floreks** [comment]
You can look for help on core/kubeadm repo. You can try to exec into some container that is on a node-1 and `curl` apiserver IP or kubernetes service IP. It has to work otherwise Dashboard won't be able to connect to apiserver.

**Comment by lpxxn** [comment]
@floreks  thanks
i change network flannel to Weave Net

now my dashboard runing success
