### ISSUE TITLE
dashboard inaccessible 

### ISSUE THREAD

**Issue by raghavtan** [kubernetes/dashboard#2800]
##### Environment
```
Installation method:  KOPS
Kubernetes version: 1.9.1
Dashboard version: v1.8.2
Commit: 72832429656c74c4c568ad5b7163fa9716c3e0ec
```

##### Observed result
Dashboard reported Unknown Server Error (503):
```
Error: 'dial tcp 100.96.4.3:8443: getsockopt: connection refused'
Trying to reach: 'https://100.96.4.3:8443/api/v1/overview/staging?filterBy=&itemsPerPage=30&name=&page=1&sortBy=d,creationTimestamp'
```

**Comment by PhoenixAD** [comment]
I am facing the same problem.

**Comment by raghavtan** [comment]
@PhoenixAD this happed due to over load on masters/etcd servers hence causing the pods on them to crash
can you please explain your problem more in detail and what steps you did

**Comment by floreks** [comment]
If you are seeing `connection refused` or similar error then this always means that there is an issue with apiserver. Dashboard is fully relying on apiserver and such errors can only come from it.
