### ISSUE TITLE
how to execute copy and paste operation in the commandline of dashoboad

### ISSUE THREAD

**Issue by zhaofengcumt** [kubernetes/dashboard#2805]
##### Environment

```
Dashboard version:1.8.0
Kubernetes version:1.8.4
Operating system:centos
Node.js version:
Go version:
```

**Comment by floreks** [comment]
On Linux use `ctrl+shift+v`.

**Comment by zhaofengcumt** [comment]
it does not work. I mean in the ui of the dashboard

**Comment by zhaofengcumt** [comment]
this is the image

https://user-images.githubusercontent.com/30680275/35614281-7e4df23e-06a9-11e8-8a77-346b2b4c553e.png

**Comment by floreks** [comment]
It depends on the system and possibly browser you are using. On Ubuntu and Chrome `ctrl+shift+v` works fine.
