### ISSUE TITLE
access kubernetes dashboard using username and password

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/dashboard#2808]
Hi,
I have been asked to use username/password to login in to dashboard. 
I have looked for documentation on it but it seems that only bearer token and kubeconfig is available. 
Can you let me know if this is possible or not.
I am having to use dashboard version 1.7.1

Many Thks

**Comment by floreks** [comment]
See `authentication-mode` argument on [Dashboard arguments](https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments) wiki page.
