### ISSUE TITLE
Describe and document installing dashboard on arm64 clusters

### ISSUE THREAD

**Issue by vielmetti** [kubernetes/dashboard#2811]
##### Environment

```
Dashboard version: 1.8.2
Kubernetes version: 1.9.2
Operating system: Ubuntu 16.04 LTS on arm64 Packet "Type 2A"
Node.js version:
Go version: 
```

##### Steps to reproduce

Install dashboard according to package directions found in [releases](https://github.com/kubernetes/dashboard/releases) on an `arm64` machine, with
the command

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.8.2/src/deploy/recommended/kubernetes-dashboard.yaml
```

##### Observed result

Dashboard fails to load, with status CrashLoopBackOff, since the provided recommended deploy file explicitly references amd64 images.

##### Expected result

Dashboard loads successfully on all provided architectures.

##### Comments

Two remedies for this, one better than the other.

The not-better remedy is to have an explicit `arm64` dashboard, along the lines of the `arm` dashboard, with a parallel file then again each for all architectures where there's a binary provided.

The better remedy is a multl-arch manifest for the dashboard, so that a single dashboard works across all architectures, and the manifest pulls the right image.

**Comment by floreks** [comment]
We do not want to create and support distinct yamls each for every architecture. We do have already do have quite many of them as there are 2 ways of deploying Dashboard (recommended + alternative) + there are head + official deployments for both amd64 and arm. This gives us already 8 yaml files.

Second option is also not possible as yaml file has to explicitly define single image that should be used for deployment. If you need to use other supported architecture then you simply need to take our official deployment yaml, download it and replace image with the one required by you. I think this is quite simple and does not need documenting.

**Comment by vielmetti** [comment]
@floreks 

I agree that the first option is untenable, though I disagree that the second is not possible. Perhaps dashboard is not the first to get a manifest list per https://github.com/kubernetes/kubernetes/issues/57869 but I think that's the roadmap.

**Comment by floreks** [comment]
How do you imagine manifest with multiple architectures to work? Kubernetes resource manifest has to define some resource(s) i.e. deployment and each deployment requires image. We can not simply define multiple deployments in single manifest file for different architectures.

**Comment by vielmetti** [comment]
@floreks I imagine as follows:

Kubernetes resource manifest that defines resources for deployment, pointing to a Docker image that's multi-arch for all of the architectures that you want to support. The multi-arch image would be built with `manifest-tool` or `docker manifest`. I'll try to find a good example (still wrestling a little with the new and poorly documented `docker manifest`).

**Comment by floreks** [comment]
We can surely use such feature if it will be compatible with kubernetes and cause no issues.

**Comment by vielmetti** [comment]
Looks like #3143 directly addresses this use case.

**Comment by maciaszczykm** [comment]
Already done.
