### ISSUE TITLE
Kubernetes project needs a new Dashboard build that includes the in-mem key/cert autogenerate fix

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/dashboard#2813]
I have opened the following issue against the Kubernetes project:
https://github.com/kubernetes/kubernetes/issues/59354
I have opened a PR to resolve the issue, but that PR depends upon a new Dashboard release (1.8.3?) that would include #2795 :
https://github.com/kubernetes/kubernetes/pull/59355
Please do a new release 1.8.3 and build.

##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.0

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.3.126+dae6a813036b40", GitCommit:"dae6a813036b4046346c01fcb3d8ce9681aafbb8", GitTreeState:"clean", BuildDate:"2018-02-05T17:24:03Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.3.126+dae6a813036b40", GitCommit:"dae6a813036b4046346c01fcb3d8ce9681aafbb8", GitTreeState:"clean", BuildDate:"2018-02-05T16:54:16Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Operating system: Linux
Node.js version: unknown
Go version: unknown
```

##### Steps to reproduce
1. Check out any kubernetes version that includes https://github.com/kubernetes/kubernetes/pull/58720
2. Bring up a cluster with `cluster/kube-up.sh`
3. Add a certificate and key to the secret `kubernetes-dashboard-certs` in the `kube-system` namespace.
4. Re-deploy Dashboard

##### Observed result
Dashboard continues to ignore the cert/key from the secret and use an autogenerated pair

##### Expected result
Dashboard should use the cert/key from the secret

##### Comments
This result is partially my fault. The better approach would have been for us to wait to merge https://github.com/kubernetes/kubernetes/pull/58720 until a new Dashboard version could be released that included the fix to #2795 had been merged and a build with it produced.

**Comment by floreks** [comment]
I agree. We need this change. We'll try to do a release this week.
