### ISSUE TITLE
[Dashboard version: v1.6.3] Clicking Deployments leads to feedback/error

### ISSUE THREAD

**Issue by evandropaula** [kubernetes/dashboard#2826]
##### Steps to reproduce

1. Open the kubernetes 1.7.7 dashboard through executing the command below o
az aks browse --name <Azure AKS name> --resource-group <Resource Group Name>
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Forwarding from 127.0.0.1:8001 -> 9090
Handling connection for 8001

2. Chrome (version 63.0.3239.132) opened loading the dashboard.

3. I clicked Deployments and I received the feedback page.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Unknown Server Error:
```
No error data available
```

**Comment by floreks** [comment]
Old Dashboard versions are not supported. Most errors are fixed in newer versions. Update it.
