### ISSUE TITLE
Lists of things (Pods, services, etc) do not respect page size setting on first load

### ISSUE THREAD

**Issue by rabbitfang** [kubernetes/dashboard#2834]
##### Environment

```
Dashboard version: 1.8.2
Kubernetes version: 1.9.2
Operating system: Dashboard in Docker for Mac 17.12.0-ce-mac49; API server on Ubuntu 16.04.3 LTS
Browser: Google Chrome 63.0.3239.132 64-bit
```

##### Steps to reproduce
1. Find a list page (e.g. pods) that has at least 16 items.
2. Set the dashboard's "Items per page" setting to 15.
2. Navigate to the list page.
3. Refresh the page in the browser (i.e. F5 or cmd+R)

##### Observed result
1. Only 10 items are displayed, but the page control still shows that items 1-15 are being displayed.
<img width="627" alt="screen shot 2018-02-08 at 12 16 29 pm" src="https://user-images.githubusercontent.com/2784296/35991300-68fac6cc-0ccc-11e8-9c37-df83b6ad6083.png">

2. Navigating to the second page does not list items 11-15, but rather 16+ (as expected for normal behavior)
<img width="750" alt="screen shot 2018-02-08 at 12 16 37 pm" src="https://user-images.githubusercontent.com/2784296/35991312-73a92370-0ccc-11e8-9a02-e0b6300a9668.png">

3. Navigating back to the first page lists items 1-15, as expected.
<img width="750" alt="screen shot 2018-02-08 at 12 16 45 pm" src="https://user-images.githubusercontent.com/2784296/35991319-78ddb0cc-0ccc-11e8-9da2-24fe3913a44d.png">

##### Expected result
1. When loading the page for the first time (e.g. with a refresh), items 1-15 should be displayed.

##### Comments
- When setting the items per page to 5, the setting is respected when the page loads (i.e. only 5 items are displayed, not 10).
- When the items per page setting is higher than the total number of items, (e.g. setting of 50 with only 15 items), only 10 items are shown on initial page load, but no page controls are shown (i.e. there is no next page).

**Comment by floreks** [comment]
Dashboard v1.8.2. Can not reproduce this issue. Probably you are using some older version.
![limpglossyasianelephant-max-14mb](https://user-images.githubusercontent.com/2285385/36021941-a39ddd26-0d87-11e8-90ea-b82708ec5301.gif)

**Comment by rabbitfang** [comment]
Did some more debugging (I am indeed on dashboard version 1.8.2). It is a race condition between loading the dashboard configuration and creating the data select query on the pod list page.

[SettingsService.load](https://github.com/kubernetes/dashboard/blob/40dc9f9e732530470b776aab00877e1da45cc534/src/app/frontend/common/settings/service.js#L42) is called in the [run step](https://github.com/kubernetes/dashboard/blob/40dc9f9e732530470b776aab00877e1da45cc534/src/app/frontend/common/settings/module.js#L28) of the settings module. When the [pod list state resolves](https://github.com/kubernetes/dashboard/blob/40dc9f9e732530470b776aab00877e1da45cc534/src/app/frontend/pod/list/stateconfig.js#L71), it does not wait for the settings to be ready before making the query to fetch the pod list. In the common case, the auth service needs to fetch its JWE and CSRF tokens before it can list the pods, which delays the pod list request. Usually, by this time the settings request has completed.

The reason I see this issue is because I am running my dashboard instance locally on my machine instead of on a k8s cluster, connecting to the dashboard's insecure port, and using my local kubeconfig when running the dashboard. The frontend therefore does not make requests to the `csrftoken/token` and `token/refresh` endpoints. If I artificially reduce my connection speed via Chrome's devtools (e.g. to "Fast 3G"), the issue goes away as the settings request completes before the pod list request starts.

**Comment by floreks** [comment]
Nice job. Thanks for trying to investigate that.

This is an interesting situation because run step of module is only executed once during initial page load. Every state change does not execute it. The only time `load()` method is called again is after clicking `Save` button on Settings page. Unless time between clicking `Save` and changing state is very short, there should not be any issues with that. This issue will be fixed anyway once we finish angular migration as current behavior was changed to reload settings as part of every state transition.

**Comment by rabbitfang** [comment]
I figured out a possible fix that could be implemented in the meantime with ~30 lines: Add a resolver in the chrome state that waits on settings to be loaded. I would be willing to create a PR with this fix, but I'm not sure how best to unit test the fix.

**Comment by floreks** [comment]
I think that the best option would be to just include load logic into a `state.onSuccess` transition hook. When used properly it would always wait for the promise to resolve before actually loading the state.

**Comment by floreks** [comment]
Anyway we are on soft code freeze during angular migration and this is not a critical issue. It will be fixed with new angular 5. We'll leave it open for reference and recheck after release.

**Comment by maciaszczykm** [comment]
It is fixed already. Please wait for https://github.com/kubernetes/dashboard/milestone/1.
