### ISSUE TITLE
Dashboard crashing every so often with cannot create log error

### ISSUE THREAD

**Issue by dzoeteman** [kubernetes/dashboard#2835]
##### Environment

```
Dashboard version: 1.8.2
Kubernetes version: 1.8.5
```

##### Steps to reproduce
This seems to happen randomly, but mostly when working with shell & logs features

##### Observed result
An error in the log: `log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-6899454d65-vs7st.unknownuser.log.ERROR.20180209-095321.1: no such file or directory`, and dashboard is restarted.

##### Expected result
No crash

**Comment by floreks** [comment]
Not possible as all our official yaml file have `/tmp` dir mounted into the pod.
https://github.com/kubernetes/dashboard/blob/master/src/deploy/recommended/kubernetes-dashboard.yaml#L131

Do not use custom yamls to deploy Dashboard.

**Comment by dzoeteman** [comment]
@floreks Ah thanks, I was running the YAML from the 1.7 release with 1.8, that's where I went wrong.
