### ISSUE TITLE
Need help in setting up Development environment 

### ISSUE THREAD

**Issue by shrutikamendhe** [kubernetes/dashboard#2839]
OS: Windows 10 (64bit)

Hello Team, Can you please provide the guidline to setup the development environment on 64 bit Windows 10 system.

**Comment by floreks** [comment]
We do not really support Windows as dev environment. There are some npm dependencies that will not work or will be hard to configure on windows. I have done it once long time ago but it required some advanced configuration and reconfiguring compiler options for one of the dependencies. Additionally it's very hard or even impossible to run kubernetes cluster on Windows at the moment.
