### ISSUE TITLE
square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by submarin76** [kubernetes/dashboard#2841]
##### Steps to reproduce

Open dashboard 
Login dashboard usşng token
( Let dashboard open)
Switch from  one context to another usng gcloud get credentials
Reload the dashboard

##### Environment
gcloud, ubuntu 16.04, firefox 58.0.2

Installation method: 
Kubernetes version:
Dashboard version: v1.8.0
Commit: 054916b8fbadebd32dc16d32108fdd3c9ccbf400
```


##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```


##### Comments
<!-- If you have any comments or more details, put them here. -->

**Comment by floreks** [comment]
Not enough details and outdated Dashboard version (v1.8.0). Current version in (v1.8.3). Please describe issue better, update Dashboard and then reopen if needed.
