### ISSUE TITLE
Kubernetes Dashboard not running. It's CrashLoopBackOff.

### ISSUE THREAD

**Issue by Ninetk** [kubernetes/dashboard#2844]
```
Dashboard version: 1.6.3
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"cfc-1.6.1.17+f04cb2d1cde1c7-dirty", GitCommit:"f04cb2d1cde1c7ae8edbb44289529b871e84d541", GitTreeState:"dirty", BuildDate:"2017-04-18T07:05:15Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+$Format:%h$", GitCommit:"99c252a4ef89291a62fb526fc3033cb98c04cd41", GitTreeState:"clean", BuildDate:"2017-09-13T09:02:02Z", GoVersion:"devel +e27a812 Sun Sep 10 23:21:02 2017 +0000", Compiler:"gc", Platform:"linux/ppc64le"}
Operating system: Ubuntu 16.04.3 LTS
```

##### Steps to reproduce
I install kubernetes dashboard by this command.
`kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.6.3/src/deploy/kubernetes-dashboard.yaml`
Then I change deployment to gcr.io/google_containers/kubernetes-dashboard-ppc64le:v1.6.3 since I use powerai to deploy kubernetes.

##### Observed result
After installed, The dashboard container don't running. It's CrashLoopBackOff   
```
$ kubectl -n kube-system get pod
NAME                                    READY     STATUS             RESTARTS   AGE
default-http-backend-1896357908-70000   1/1       Running            0          3h
kubernetes-dashboard-1557463588-qmsw9   0/1       CrashLoopBackOff   11         2d
nginx-ingress-lb-ppc64le-9pn2t          1/1       Running            0          3h
```

Here is some log of my pods.
```
inet@inetminsky:~$ kubectl -n kube-system logs kubernetes-dashboard-1557463588-qmsw9
Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Could not init in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
Using random key for csrf signing
No request provided. Skipping authorization header
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Could not create client config. Check logs for more information
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
```

How can I fix this error ?

##### Expected result
Access kubernetes dashboard webportal.

##### Comments
I'm new on kubernetes and programming. You can tell me, If you want more information.

**Comment by floreks** [comment]
ServiceAccounts are disabled in your cluster. They have to be enabled in order to be able to run Dashboard using in-cluster config.

**Comment by Ninetk** [comment]
Cloud you please guide me how to enable ServiceAccounts ?
I try to follow this step but it still not work.
https://v1-6.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

I don't see ServiceAccountToken in my pod so I follow Manually create a service account API token and Add ImagePullSecrets to a service account
https://v1-6.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

Some results I had deifference from URL 
After secret is created, My DATA is 0
```
$ kubectl -n kube-system get secrets
NAME                          TYPE                                  DATA      AGE
kubernetes-dashboard-secret   kubernetes.io/service-account-token   0         8m
```

And serviceaccount secret still 0.
```
$ kubectl -n kube-system get serviceaccount
NAME                   SECRETS   AGE
default                0         21d
kubernetes-dashboard   0         31m
```

**Comment by floreks** [comment]
To configure SA you'd need to pass additional arguments to core components like apiserver. If you don't know how to do this then use `kubeadm` or some other tool to provision the cluster. Most of them enable SA by default.

**Comment by Ninetk** [comment]
Thank for your advices.
