### ISSUE TITLE
Merge automation appears to be misconfigured for this repository.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/dashboard#2846]
Merge automation provided by Tide appears to be misconfigured for this repo based on the following error message: `Merge commits are not allowed on this repository.` The [Tide dashboard](https://prow.k8s.io/tide) also shows that Tide is stuck merging PR #2832
Either Tide needs to be configured to use the `squash` or `rebase` merge method (instead of `merge`) for this repo, or the repository needs to be configured to allow merge commits.

To configure Tide to use a different merge method you will need to add 1 line to the Prow configuration here: https://github.com/kubernetes/test-infra/blob/5b25c840d4019fc034097116ed019b49fb07467e/prow/config.yaml#L91-L93

**Comment by cjwagner** [comment]
I'll switch Tide to do squash merges for this repo for the time being.

**Comment by floreks** [comment]
Closing as https://github.com/kubernetes/test-infra/pull/6924 was merged already and it should be fixed.
