### ISSUE TITLE
Strange error with dashboard - can't access

### ISSUE THREAD

**Issue by TimBobkov** [kubernetes/dashboard#2848]
##### Steps to reproduce
I don't know what happen and how to reproduce this... Kubectl work as usual.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.2
Commit: 72832429656c74c4c568ad5b7163fa9716c3e0ec
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by maciaszczykm** [comment]
We need more details to help you.

**Comment by floreks** [comment]
Also duplicate of #2847.
