### ISSUE TITLE
TLS certificates are auto generated with dnsName "."

### ISSUE THREAD

**Issue by strigazi** [kubernetes/dashboard#2851]
##### Environment

```
Dashboard version: v1.8.3
Kubernetes version: v1.9.3
Operating system: Fedora 27
RBAC enabled cluster with NodeAuthorizer
```

##### Steps to reproduce

kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.8.3/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result

In the dashboard log I get:
2018/02/21 19:33:58 http: TLS handshake error from 10.100.23.1:55746: remote error: tls: bad certificate

When I do describe pod I get:
Liveness probe failed: Get https://10.100.23.3:8443/: tls: failed to parse certificate from server: x509: cannot parse dnsName "."

If I change the liveness probe and access the dashboard over https with kubectl proxy I get
Error: 'tls: failed to parse certificate from server: x509: cannot parse dnsName "."'
Trying to reach: 'https://10.100.23.3:8443/'

```
$ kubectl -n kube-system get po -o wide
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
coredns-5864cfd79d-dggcv                1/1       Running   1          1h        10.100.23.4   kube-minion-0
heapster-68b976dd7-sbmbp                1/1       Running   1          1h        10.100.23.2   kube-minion-0
kubernetes-dashboard-6cc785786d-s9mld   1/1       Running   5          4m        10.100.23.3   kube-minion-0
```
dashboard log:
```
2018/02/21 19:33:10 Starting overwatch
2018/02/21 19:33:10 Using in-cluster config to connect to apiserver
2018/02/21 19:33:10 Using service account token for csrf signing
2018/02/21 19:33:10 No request provided. Skipping authorization
2018/02/21 19:33:10 Successful initial request to the apiserver, version: v1.9.3
2018/02/21 19:33:10 Generating JWE encryption key
2018/02/21 19:33:10 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/02/21 19:33:10 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/02/21 19:33:10 Initializing JWE encryption key from synchronized object
2018/02/21 19:33:10 Creating remote Heapster client for heapster:80
2018/02/21 19:33:10 Auto-generating certificates
2018/02/21 19:33:10 Successfully created certificates
2018/02/21 19:33:10 Serving securely on HTTPS port: 8443
2018/02/21 19:33:10 Successful request to heapster
2018/02/21 19:33:48 http: TLS handshake error from 10.100.23.1:55740: remote error: tls: bad certificate
2018/02/21 19:33:58 http: TLS handshake error from 10.100.23.1:55746: remote error: tls: bad certificate
```

##### Expected result
Access to the dashboard with kubectl proxy.

##### Comments

I can run the dashboard over http without problems.

Something might be happening around here?
https://github.com/kubernetes/dashboard/blob/master/src/app/backend/cert/ecdsa/creator.go#L57

**Comment by floreks** [comment]
If you are getting `.` only as a dns name then it means that kubernetes downward API is not working as expected. This API is supposed to populate environment variables to every pod with basic information about pod/cluster (name, namespace, ip, etc.).

**Comment by strigazi** [comment]
After adding this in my spec it works. Is it supposed to get these variables by default?

Does this still mean that the downward api is not working in my cluster? Any hints on what I miss? Some configuration?

```
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace=
```

**Comment by strigazi** [comment]
Apart from the three below, does the dashboard expect any other parameter?
```
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

**Comment by floreks** [comment]
It should work by default without the need to modify our yaml file. It's possible that something has changed in k8s `1.9.3` and these values are not populated by default or some apiserver argument enabled/disabled this API when provided. Dashboard only uses pod name and namespace variables mounted into the pod. IP is not required. I'll take a look at core changed to see if something has changed between versions, however I am using k8s `1.9.3` provisioned using kubeadm and I am not seeing such errors.

**Comment by strigazi** [comment]
Thanks! I created the cluster manually, maybe I missed something. I'll close this and I'll have a look as well if there is such a parameter. I'll comment here if I find something.

Thanks for the prompt reply, I really appreciate it!
