### ISSUE TITLE
kubernetes-dashboard pod getting the CrashLoopBackOff

### ISSUE THREAD

**Issue by bamb00** [kubernetes/dashboard#2857]
```
Dashboard version: kubernetes-dashboard-amd64:v1.6.1
Kubernetes version: v1.7.4
Operating system: CentOS 7.3.1611
Node.js version:
Go version:
```

##### Observed result
     # kubectl logs kubernetes-dashboard-3902617266-2vjk8 -n kube-system
     Using HTTP port: 8443
     Creating API server client for https://10.96.0.1:443
     Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is 
     misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --
     apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: 
     dial tcp 10.96.0.1:443: getsockopt: no route to host
     Refer to the troubleshooting guide for more information: 
     https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

     # kubectl get po -n kube-system
      NAME                                               READY     STATUS             RESTARTS   AGE
      etcd-devtest-stage5-master-01                      1/1       Running            0          112d
      kube-apiserver-devtest-stage5-master-01            1/1       Running            0          20h
      kube-controller-manager-devtest-stage5-master-01   1/1       Running            0          112d
      kube-dns-2425271678-5bzs5                          3/3       Running            0          112d
      kube-proxy-n9962                                   1/1       Running            0          112d
      kube-scheduler-devtest-stage5-master-01            1/1       Running            0          112d
      kubernetes-dashboard-3902617266-wf9r6              0/1       CrashLoopBackOff   8          19h
      snap-zq06d                                         1/1       Running            0          1d
      weave-net-lcx0z                                    2/2       Running            0          112d

     # iptables -L 
     Chain KUBE-SERVICES (2 references)
     target     prot opt source               destination
     REJECT     tcp  --  anywhere             10.102.190.40        /* kube-system/heapster: has no endpoints */ tcp dpt:http reject-with icmp-port-unreachable
     REJECT     tcp  --  anywhere             anywhere             /* kube-system/kubernetes-dashboard: has no endpoints */ ADDRTYPE match dst-type LOCAL tcp dpt:32260 reject-with icmp-port-unreachable
     REJECT     tcp  --  anywhere             10.99.79.112         /* kube-system/kubernetes-dashboard: has no endpoints */ tcp dpt:http reject-with icmp-port-unreachable

##### Expected result
Dashboard should be accessible.

##### Comments
Dashboard was running over 100 days then the CrashLoopBackOff occurs.  Need to understand why the kubernetes-dashboard has no endpoints all of a sudden.

**Comment by floreks** [comment]
This is not a Dashboard issue but configuration. kube-proxy is responsible for iptables.

**Comment by bamb00** [comment]
@floreks, Thanks for the info.
