### ISSUE TITLE
node chinese translation

### ISSUE THREAD

**Issue by zhangjianweibj** [kubernetes/dashboard#2862]
Dashboard version:1.8.2
Kubernetes version:1.8
node allocated resources chart,CPU & Memory & Pods supply chinese translation.

![image](https://user-images.githubusercontent.com/18585129/36704949-af32edb0-1b9d-11e8-8d92-079d5c3b683f.png)

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/blob/c0274d8725bedacf0b030d2ee927bdb438df126d/src/app/frontend/node/detail/allocatedresources.html#L58

You are right. We are currently migrating to new Angular and next major release is going to use it. Old translation mechanism will no longer be used so at the moment we will not fix it.
