### ISSUE TITLE
Issues while building kubernetes dashboard  source code

### ISSUE THREAD

**Issue by jyoti-26** [kubernetes/dashboard#2864]
##### Environment
I used  Developer guide to build kubernetes dashboard source code v1.8.3  and followed the following steps
Operating system: windows10
Dashboard version: kubernetes dashboard v1.8.3
Docker version 17.06.0-ce, build 02c1d87
Node.js version: v8.9.4
Go version: go version go1.10 windows/amd64
Gulp version: Local version 3.9.1 and CLI version 3.9.1
Then i run the command
 ==> npm i
It downloads all the packages mentioned in package.json file but giving me configuration error as well.
Below is the screenshots of error kindly help me.
[kubernetes_dashboard_error.txt](https://github.com/kubernetes/dashboard/files/1761352/kubernetes_dashboard_error.txt)

**Comment by floreks** [comment]
Windows is not officially supported as a dev platform. Some of our npm dependencies will not work on Windows.

**Comment by jyoti-26** [comment]
@floreks Thanks for quick reply
