### ISSUE TITLE
Kubeadm / Dashboard is not working after installation

### ISSUE THREAD

**Issue by Deimos620** [kubernetes/dashboard#2865]
Sorry, regarding to the #2863, I was missing one step. Of course, the master node is added a taint while "kubeadm init".
And, I installed pod network with this:

> sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

> sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml

I did all the steps from here , to install / init kubeadm: 

> https://www.techrepublic.com/article/how-to-quickly-install-kubernetes-on-ubuntu/

But dashboard is still in "ContainerCreating" status.

**Comment by maciaszczykm** [comment]
Can you create other containers or is it only Dashboard that is not working? Looks like a cluster issue to me.

**Comment by maciaszczykm** [comment]
I would also recommend to use official doc: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by maciaszczykm** [comment]
+ https://github.com/kubernetes/dashboard/issues/2863#issuecomment-368791354
