### ISSUE TITLE
'View/Edit YAML' action shows JSON instead

### ISSUE THREAD

**Issue by brokenmass** [kubernetes/dashboard#2868]
##### Environment
Standard dashboard installation in kubernetes cluster

```
Dashboard version: 1.8.3
Kubernetes version: 1.9.3
Operating system: rhel7
```

##### Steps to reproduce
Go to any section that allow editing (pods, deployment etc)

##### Observed result
When selecting 'View/edit YAML' the dashboard show the configuration in JSON format

##### Expected result
The configuration should be in YAML format or at least the action should be  'View/edit JSON'

##### Comment
`kubectl edit pod XXXX` displays the configuration in yaml format

**Comment by floreks** [comment]
Actually, it should just be `View/edit resource`. We are displaying whatever comes from API server. If it is JSON format then that is what dialog will display.

**Comment by brokenmass** [comment]
[this](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/common/resource/editresource_controller.js#L60) seems to indicate that it's always going to be json. 
any way to have the response displayed as yaml ?

**Comment by floreks** [comment]
Input is already a json and `angular.toJson` only formats the string. We'd rather display whatever comes from API server and not change formatting. It is additional logic that does not really give us any advantage and we'd have to make a json once again before sending updated version back to our backend and api server. I don't see any benefit here.

**Comment by floreks** [comment]
Button text will be updated as part of the ongoing angular migration.

**Comment by tsturzl** [comment]
JSON is for machines, YAML is for humans. I think additional formatting is not only helpful, but **the correct way of presenting data**. If I wanted to deal with JSON without formatting why don't I just curl the API? YAML serves the same purpose as a UI, it makes it tangible. I think formatting to yaml makes more sense than barfing JSON onto the screen. It destroys this feature. I currently just use kubectl to edit because making any significant change is likely to blow up for something like a missing comma, and then changes are lost and it tells me that the json isn't formatted correctly. YAML to JSON and back to YAML is not difficult, especially because they have the same types, plus all YAML parsers can parse JSON, so you effectively achieve support for both by just parsing the edit input unconditionally.

**Comment by tsturzl** [comment]
Not to mention k8s docs provide only YAML examples. It feels broken this way, and changing the button text is dressing a bug as a feature.

**Comment by maciaszczykm** [comment]
It makes sense to check if we can change that.

**Comment by floreks** [comment]
I have done some quick research on how `kubectl` is doing the transformation. It is done manually by json to yaml formatters in Go, after object is received from apiserver. Apiserver will always return json. There is no way around that. Additionally I don't see any support for `application/yaml` format in `go-restful` library that we are using to provide REST api.

We would have to modify our backend and add transformation logic there, then return raw string and always format it as yaml. Other option would be to do the json to yaml transformation directly in frontend. I actually don't see much benefit here as both JSON and YAML when formatted are easy to understand and modify. It's just different syntax. In JSON you have to remember to put commas and quotes, but in YAML you have to keep correct indents.

**Comment by brokenmass** [comment]
as of now I'm using kubernetes/dashboard for deployments status/management and [kubernator](https://github.com/smpio/kubernator) to view and modify the configurations.
I found yaml much more easy to follow and less error prone (multiline environment variable or configmap values in json are a pain)

I think this feature should definitely be added to the roadmap

**Comment by floreks** [comment]
Added feature to choose between yaml/json mode during resource edit.

![zrzut ekranu z 2018-03-27 13-04-52](https://user-images.githubusercontent.com/2285385/37963724-79209f14-31bf-11e8-81c4-aae5d6bc359e.png)

![zrzut ekranu z 2018-03-27 13-04-58](https://user-images.githubusercontent.com/2285385/37963725-7a981016-31bf-11e8-9177-397d10beeb54.png)

I think we can close now.

**Comment by jamstar** [comment]
Is it known what dashboard release this feature will be targeted for? i greatly prefer using yaml.

**Comment by maziyarpanahi** [comment]
I also appreciate this feature.

I'd prefer to keep everything in the same format! If I write configs in YAML, I would like to edit them in YAML.
(I would do them all in JSON, but it's just not enough resources out there in JSON)

**Comment by flowchartsman** [comment]
Was looking for this commit to cherry-pick it for testing and couldn't find it. Can someone point me in the right direction?

**Comment by iamkarlson** [comment]
Has not it been released yet?

**Comment by floreks** [comment]
No, it will be a part of new Dashboard based on Angular 6.

**Comment by jamstar** [comment]
do we know what release this will be targeted for?

**Comment by RainerW** [comment]
Nice feature. Where can i find that angular 6 branch? https://github.com/kubernetes/dashboard/branches/all?query=angular looks like all angular branches are merged, so this will be in the next release?

**Comment by maciaszczykm** [comment]
`ng-migration` --> PR #3152

**Comment by RainerW** [comment]
Thanks
