### ISSUE TITLE
Why does not the dashboard support to integrate with the OIDC for the authentication?

### ISSUE THREAD

**Issue by kilsoo75** [kubernetes/dashboard#2873]
The current dashboard supports only the token and basic mode for authentication.

I checked the roadmap of this project but I could not find the feature regarding the integration with OIDC for authentication.

Why does not the dashboard support to integrate with the OIDC for the authentication?

**Comment by floreks** [comment]
It is already on the roadmap https://github.com/kubernetes/dashboard/issues/2353. First we need some API on core side to check if apiserver is configured to use OIDC. Dashboard has to be sure that token it is getting will be accepted by API server.
