### ISSUE TITLE
the pod doesn't work

### ISSUE THREAD

**Issue by cbdog94** [kubernetes/dashboard#2876]
##### Environment

```
Dashboard version: 1.8.3
Kubernetes version: 1.9.1 && 1.8.2
Operating system: ubuntu 16.04
Node.js version: v9.7.1
Go version: 1.10
```

##### Steps to reproduce

I want to add some features to the dashboard and deploy it to the real kubernetes cluster. So

1. I clone the repo to my PC (with kubernetes 1.9.1 via minikube) and make some modification. The command 'gulp serve' works well. So I want to build the modified dashboard to a new docker image. 
2. Through the command 'gulp build' && 'gulp docker-image:head', the image has been built in my PC's docker and I upload the image to my personal registry.
3. In the kubernetes cluster (with kubernetes 1.8.2 via kubeadm), I want to use the new dashboard image so I download 'https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml' , replace 'k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3' to my personal registry and apply it. Unfortunately, the pod can not work.
##### Observed result

The logs of the error dashboard pod is below:
> 2018/03/05 14:14:49 Starting overwatch
> 2018/03/05 14:14:49 Using in-cluster config to connect to apiserver
> 2018/03/05 14:14:49 Using service account token for csrf signing
> 2018/03/05 14:14:49 No request provided. Skipping authorization
> 2018/03/05 14:14:49 Successful initial request to the apiserver, version: v1.8.2
> 2018/03/05 14:14:49 Generating JWE encryption key
> 2018/03/05 14:14:49 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
> 2018/03/05 14:14:49 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
> 2018/03/05 14:14:49 Initializing JWE encryption key from synchronized object
> 2018/03/05 14:14:49 Creating in-cluster Heapster client
> 2018/03/05 14:14:49 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
> 2018/03/05 14:14:49 Auto-generating certificates
> 2018/03/05 14:14:49 Successfully created certificates
> 2018/03/05 14:14:49 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service account's configuration) or the --apiserver-host param points to a server that does not exist. Reason: x509: cannot parse dnsName "."
> Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

##### Expected result

The pod created by the new dashboard image can work well.
##### Comments

The official dashboard (v1.8.3) can work well in the cluster (v1.8.2) without config apiserver-host. And the part of modification is correct. I don't to know which step is wrong. Also I don't want to add the apiserver-host param to solve this issue.

**Comment by floreks** [comment]
Duplicate of https://github.com/kubernetes/dashboard/issues/2851

There is a solution provided there if downward API is not working in your cluster.

**Comment by cbdog94** [comment]
Sorry, I can't find suitable solution in [#2851](https://github.com/kubernetes/dashboard/issues/2851) to solve the problem. I don't know why the official dashboard can get POD_NAME and POD_NAMESPACE but the new dashboard I build can't get the two ENVs.
