### ISSUE TITLE
Admin access to dashboard after clicking on skip

### ISSUE THREAD

**Issue by cdelpinogeo** [kubernetes/dashboard#2884]
##### Environment

```
Dashboard version: v1.8.3
Kubernetes version: v1.8.4
Operating system: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
```

##### Steps to reproduce

1. Deleted old dashboard deployment from cluster, including secrets, ServiceAccount, role, RoleBinding, and service.
2. Deployed latest version of dashboard per instructions:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```

##### Observed result

When accessing the dashboard after entering the command:
```
kubectl proxy
```
and going to the following page:
```
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
```
I am presented with the login page for the dashboard. I click on skip, and I am able to freely browse through the dashboard and also view secrets.

##### Expected result

I thought that access would be very limited since I clicked on skip.

##### Comments

I checked to make sure that the dashboard service account did not have admin privileges. There was no ClusterRoleBinding. Not sure if I am missing something. Thanks.

**Comment by floreks** [comment]
You can easily test privileges by taking Service Account token and using it with kubectl. I believe with `kubectl --token xxx` you will also have access to the cluster. It will mean that it is not a Dashboard issue. It can not escalate any privileges on its' own.

**Comment by floreks** [comment]
Closing as stale.
