### ISSUE TITLE
Common Application Description

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/dashboard#2891]
The [app def working group](https://github.com/kubernetes/community/tree/master/wg-app-def) two things have come out to describe applications.

1. A recommended set of labels and annotations ([currently in a PR](https://github.com/kubernetes/website/pull/7695)). Note that a) this was worked through both the App Def WG and SIG Apps (which owns the output) and b) everything is prefixed as labels and annotations not prefixed are considered private.
1. An [application CRD](https://github.com/kubernetes-sigs/apps_application) to provide a top level application object. The work for this just started under SIG Apps as owners of the code.

Given this, on the [charts](https://github.com/kubernetes/charts) repo we got PRs to add metadata descriptions due to [this](https://github.com/kubernetes/dashboard/blob/a3c8d93a89823f1d1db62cc88cade46911fd1992/src/app/backend/resource/deployment/deploy.go#L42).

Instead of a top level description can we move this to either a prefixed description or wait on the Application CRD?

**Comment by ant31** [comment]
Is there any way I can help on this issue?

**Comment by sftim** [comment]
Is the “Application” CRD something that this Dashboard repo / project should own?
