### ISSUE TITLE
503 Service Unavailable from Dashboard UI

### ISSUE THREAD

**Issue by antoinne85** [kubernetes/dashboard#2896]
##### Steps to reproduce
I have no idea.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.2
Commit: 72832429656c74c4c568ad5b7163fa9716c3e0ec
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'dial tcp 10.244.1.113:9090: getsockopt: connection refused'
Trying to reach: 'http://10.244.1.113:9090/api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp'
```

##### Comments
Everything was going along just fine, then I started receiving this error out of nowhere.

I'm guessing its probably not even related to the dashboard _specifically_, but I'm at a loss for how to troubleshoot it. `10.244.1.113` is the cluster-IP of the pod running the dashboard, so it's not clear to me _what_ is trying to connect to _what_.

Any advice on how to begin troubleshooting this issue would be greatly appreciated.

Other info--
1. My cluster is running in Azure AKS.
1. Everything else in the cluster seems to be operating normally.
1. I've attempted to resolve the issue by deleting both the heapster and dashboard pods (and letting the deployment produce new one), but without benefit.
1. I've examined the logs and descriptions to the best of my ability, but wasn't able to identify any strings to pull on.

**Comment by floreks** [comment]
All the information related to deploying and accessing Dashboard can be found on our wiki: https://github.com/kubernetes/dashboard/wiki

If mentioned methods do not work then it is most likely cluster configuration issue. Regarding configuration part you can ask for help on kubernetes slack. We are trying to deal with actual issues here only.
