### ISSUE TITLE
Sign in failed with Kubeconfig and Token options

### ISSUE THREAD

**Issue by piyushkv1** [kubernetes/dashboard#2899]
##### Environment

```
Dashboard version: latest
Kubernetes version: 1.9
Operating system: Ubuntu 16.04.3 LTS
Node.js version: v4.2.6
Go version: go1.9.2
```

##### Steps to reproduce
1. kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
2. kubectl proxy --address='0.0.0.0' --port=80 --accept-hosts='^*$'
3. Download kubeconfig file to workstation
4. Upload kubeconfig file to first login UI and click sign in

##### Observed result
null
![image](https://user-images.githubusercontent.com/9156164/37555304-6dedfcb0-2a0b-11e8-8ea4-edf0c957f456.png)

##### Expected result
Login should work. I didn't do any modification.

##### Comments
Same has happened with Token option. I copied token and applied as per guide https://github.com/kubernetes/dashboard/wiki/Access-control#kubeconfig.
What is the production procedure to configure dashboard for admin and basic user?

**Comment by floreks** [comment]
Read the `NOTE` section under `kubectl proxy`: https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#kubectl-proxy

We will only update the error message, which is already part of the angular migration. Being unable to log in when using `kubectl proxy` with `0.0.0.0` address binding is expected.
