### ISSUE TITLE
can not inspect etcd pod after a kubernetes restart

### ISSUE THREAD

**Issue by chifamba** [kubernetes/dashboard#2901]
##### Steps to reproduce

while using kubernetes dashboard on docker for mac with kubernetes enabled, 
create a etc cluster as per https://github.com/coreos/etcd-operator 
restart docker
etc pods cannot be inspected using dashboard

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
Unknown reference kind EtcdCluster

```

**Comment by maciaszczykm** [comment]
> etc pods cannot be inspected using dashboard

What does that mean? Which view crashes? Details of the pod?

**Comment by floreks** [comment]
`Unknown reference kind EtcdCluster` this error definitely does not come from Dashboard. It has to be from API server and Dashboard is just showing the response. If it can not be viewed then there is a cluster issue.

**Comment by kcao3** [comment]
We are currently encountering the same problem when clicking on one of the etcd-cluster-xyz pod, managed by the etcd-operator, from the k8s dashboard.
Kubernetes version: v1.10.0
Dashboard version: v1.8.3

From the k8s dashboard, we see this:
   Internal Server Error (500)
  Unknown reference kind EtcdCluster

From one of our k8s dashboard pods, we see this log:
  Getting details of etcd-cluster-xyz pod in default namespace
  Unknown reference kind EtcdCluster
  Outcoming response to <POD_IP>:<PORT> with 500 status code

However, we are still able to get logs and information of this pod when using kubectl command:
kubectl describe pod etcd-cluster-xyz 
kubectl logs -f etcd-cluster-xyz..

So, this means k8s API server is fine...

Please reopen this issue.
