### ISSUE TITLE
Enhancement request: do not open logs in a new tab

### ISSUE THREAD

**Issue by jakerobb** [kubernetes/dashboard#2906]
It's bad form for a web page to open some internal links in new tabs and others in the same tab. Experienced browser users know to right click or hold a modifier key if they want something in a new tab. As I work with the Kubernetes dashboard I end up cluttering my browser windows with a bunch of old tabs, which I periodically notice and close.

As such, I request that all internal links in the dashboard open in the same tab. 

Thanks! The dashboard is great! :)

**Comment by maciaszczykm** [comment]
It is added in #3296, that will be released after Angular migration (#3152).

/close
