### ISSUE TITLE
let's encrypt dashboard through nodeport on a raspberry pi cluster

### ISSUE THREAD

**Issue by bilalAchahbar** [kubernetes/dashboard#2910]
##### Environment

Right now i can access my dashboard on my host node though the ip address of the node my dashboard is running(probably not the most secure option). 

To access the dashboard i need to check the certificate manually inside my browser. I want to add Let's encrypt to do this automatically but i have no clue how that i do this. As i am still a beginner in kubernetes i don't know how to add the let's encrypt method to the dashboard service

**Comment by floreks** [comment]
It is configuration issue, not Dashboard. We do not provide support for custom/advanced configurations that are not part of our documentation. If you need help with configuration ask for help on kubernetes slack. There are many experts familiar with such setups.
