### ISSUE TITLE
How to debug authentication failures

### ISSUE THREAD

**Issue by XANi** [kubernetes/dashboard#2917]
I'm using 1.8 dashboard with kube 1.9.6.

I've tried both methods via manual and in case of tokens (tried both with newly created admin-user(-token) and all I get is:

    2018/03/26 10:35:59 [2018-03-26T10:35:59Z] Incoming HTTP/2.0 POST /api/v1/login request from 172.16.124.197:40590: {
      "kubeConfig": "",
      "password": "",
      "token": "xxxxxxxxxxxxxxxxxxxxxxx",
      "username": ""
    }
    2018/03/26 10:35:59 Non-critical error occurred during resource retrieval: the server has asked for the client to provide credentials
    2018/03/26 10:35:59 [2018-03-26T10:35:59Z] Outcoming response to 172.16.124.197:40590 with 200 status code

Trying to use kubeconfig just returns ```Not enough data to create auth info structure.``` without anything sensible in logs

**Comment by floreks** [comment]
There are couple of options:
1. Token might be invalid.
2. User tied to the token does not have privileges to get server version (this is our basic check to see if provided "credentials" are valid).
3. Issue with cluster auth configuration.
4. Custom Dashboard deployment with different than default flags used that might cause some issues.

**Comment by XANi** [comment]
About kubeconf it was my mistake, I didn't read that part that said it doesn't work if kubeconf uses client certs.

But there is something weird about token auth. When I type anything that starts with space at the beginning  (i've found it by mistake when I copied a token with space in the beginning) it logs with "system:anonymous" user. Is that intended ?

**Comment by XANi** [comment]
For example:

    -> ᛯ kubectl --kubeconfig ~/.kube/dashboard get nodes                                                                                            
    NAME            STATUS    ROLES     AGE       VERSION
    d1-efi4-kube1   Ready     master    3d        v1.9.6
    d1-efi4-kube2   Ready     master    3d        v1.9.6
    d1-efi4-kube3   Ready     master    3d        v1.9.6
    
    
    kubectl -n kube-system --kubeconfig ~/.kube/dashboard get pods 
    NAME                                    READY     STATUS    RESTARTS   AGE
    kube-apiserver-d1-efi4-kube1            1/1       Running   4          3d
    kube-apiserver-d1-efi4-kube2            1/1       Running   3          3d
    kube-apiserver-d1-efi4-kube3            1/1       Running   3          3d
    kube-controller-manager-d1-efi4-kube1   1/1       Running   4          3d
    kube-controller-manager-d1-efi4-kube2   1/1       Running   3          3d
    kube-controller-manager-d1-efi4-kube3   1/1       Running   3          3d
    kube-dns-6f4fd4bdf-lghmk                3/3       Running   3          3d
    kube-router-hbhhw                       1/1       Running   13         3d
    kube-router-jjf7k                       1/1       Running   6          3d
    kube-router-qgxwd                       1/1       Running   13         3d
    kube-scheduler-d1-efi4-kube1            1/1       Running   4          3d
    kube-scheduler-d1-efi4-kube2            1/1       Running   3          3d
    kube-scheduler-d1-efi4-kube3            1/1       Running   3          3d
    kubernetes-dashboard-5bd6f767c7-ccj8m   1/1       Running   11         3d

and kubeconfig:

    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: xxxx
        server: https://172.16.124.197:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: admin-user
      name: admin-user@kubernetes
    current-context: admin-user@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: admin-user
      user:
        token: xxxx

    -> ᛯ kubectl -n kube-system --kubeconfig ~/.kube/dashboard version
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by floreks** [comment]
You have probably enabled basic auth in the cluster in a wrong way. This is why apiserver accepts incorrect token and logs you in as an anonymous user.

**Comment by XANi** [comment]
I did everything according to manual with no changes... incl creating the user for it and giving it permissions.

here's the configmap:

    kubectl -n kube-system get cm kubernetes-dashboard-settings -o yaml
    apiVersion: v1
    data:
      _global: '{"clusterName":"","itemsPerPage":10,"autoRefreshTimeInterval":5}'
    kind: ConfigMap

and actual app
    :~☠ ps aux |grep dashboard
    root      3596  0.1  0.0  83484 46468 ?        Ssl  Mar23   4:36 /dashboard --insecure-bind-address=0.0.0.0 --bind-address=0.0.0.0 --auto-generate-certificates



> This is why apiserver accepts incorrect token and logs you in as an anonymous user.

That's something different. If I put any garbage that doesn't start with space, I get access denied. To sum it up:

* invalid token - access denied
* valid token - access denied
* space + valid token - anonymous
* space + random garbage - anonymous

**Comment by floreks** [comment]
Regarding first 2 scenarios. As there is no actual way of checking if user exists and has access, we are just creating client based on provided auth info and checking if it is possible to get server version.

https://github.com/kubernetes/dashboard/blob/be02f3c6981edeaa393e3c1f021d1f4ab4117fed/src/app/backend/client/manager.go#L180

In case there is no error we are assuming that provided "credentials" are valid. Basically, every Dashboard "user" requires this root privilege to check server version.

As for the scenarios where `anonymous` user is used, we can simply trim the data and then pass it to the server. I think that there is an issue on apiserver side because we are passing the data "as is". This is apiserver that accepts the token with space in it and falls back to anonymous user.

**Comment by XANi** [comment]
So basically only way to debug it would be adding more debug on apiserver side ?

Removing and re-creating dashboard for nth fixed it... somehow. Only difference from my previous tries was ripping out kube-router's routing (which worked, but didn't allow to specify which NIC/network to use for inter-node traffic) and replacing it with just Bird instance running on nodes but that seems unrelated as I didn't get any timeout errors...

**Comment by floreks** [comment]
Our backend is checking almost all possible errors so if there is no error in logs then request to apiserver was successful. There is no way to debug it further without modifying backend or manually creating requests to apiserver and checking reponses.
