### ISSUE TITLE
question of the command

### ISSUE THREAD

**Issue by 15211002483** [kubernetes/dashboard#2918]
##### Steps to reproduce

1332/5000  
I added a login module, and when I used command gulp serve, I was able to access the dashboard normally, and no problem.
However, when I use gulp docker-image, when I package it as a mirror, I will go to the page, and there will be an Error (vendor. Bd425c26. Js :6 Uncaught Error: [$injector:unpr] Unknown provider: loginServiceProvider < -loginservice.
http://errors.angularjs.org/1.6.6/$injector/unpr? P0 = 20 loginservice loginServiceProvider % 3 c - 20% %
The at vendor. Bd425c26. Js: 6
The at vendor. Bd425c26. Js: 6
At Object. R [as get] (vendor. Bd425c26. Js :6)
The at vendor. Bd425c26. Js: 6
At r (vendor. Bd425c26. Js: 6)
At I (vendor. Bd425c26. Js: 6)
At Object. S [as invoke] (vendor. Bd425c26. Js :6)
The at vendor. Bd425c26. Js: 6
The at o (vendor. Bd425c26. Js: 6)
At he (vendor. Bd425c26. Js: 6))
. Here is part of my code, thank you!
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --module
export default angular
    .module(
        'kubernetesDashboard.login',
        [
          'ngMaterial',
          'ui.router',
        ])
	.service('loginService', LoginService)
	.component('kdLogin', loginComponent)
    .config(stateConfig);
--service
export class LoginService {
  /**
   * @param {!angular.$cookies} $cookies
	 @param {!angular.$q} $q
	 @param {!angular.$resource} $resource
   * @ngInject
   */
  constructor($cookies, $q,$resource) {
   ......
   }
}
---index-module
import loginModule from './system/login/module';
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Since it is the first time to contact this, please help me, thanks a lot.

**Comment by maciaszczykm** [comment]
> I added a login module

Is it your own module?

**Comment by 15211002483** [comment]
I have solved this problem, I am so stupid, I added the login module and conflicts with the original, I changed the identification name,Thanks anyway！☺

**Comment by maciaszczykm** [comment]
@15211002483 No problem :)
