### ISSUE TITLE
InitContainer is in Pending State

### ISSUE THREAD

**Issue by neliel123** [kubernetes/dashboard#2920]
I have an init container which runs a java process...it runs in a loop and exits gracefully when all my required preprocessing events are met.
I just noticed that even if my java process completes and the thread is exited... my containers are not booting up and it is still in the PENDING state.

It seems that it is waiting for something from my initcontainer.
Are init containers not capable of running a java process?

**Comment by floreks** [comment]
How is that related to Dashboard?

**Comment by neliel123** [comment]
Oopps..my bad... Can you please transfer this to the correct board?

**Comment by floreks** [comment]
Create issue on the core repo.
