### ISSUE TITLE
--auto-generate-certificates disables insecure port

### ISSUE THREAD

**Issue by jpiper** [kubernetes/dashboard#2924]
```
Dashboard version: 1.8.3
Kubernetes version: 1.10.0
```

##### Steps to reproduce
Start 1.8.3 with the flags:
```yaml
- --auto-generate-certificates
- --enable-insecure-login=true
- --insecure-bind-address=0.0.0.0
- --insecure-port=9090
```
##### Observed result
```
2018/03/28 12:29:24 Starting overwatch
2018/03/28 12:29:24 Using in-cluster config to connect to apiserver
2018/03/28 12:29:24 Using service account token for csrf signing
2018/03/28 12:29:24 No request provided. Skipping authorization
2018/03/28 12:29:24 Successful initial request to the apiserver, version: v1.10.0
2018/03/28 12:29:24 Generating JWE encryption key
2018/03/28 12:29:24 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/03/28 12:29:24 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/03/28 12:29:25 Initializing JWE encryption key from synchronized object
2018/03/28 12:29:25 Creating in-cluster Heapster client
2018/03/28 12:29:25 Successful request to heapster
2018/03/28 12:29:25 Auto-generating certificates
2018/03/28 12:29:25 Successfully created certificates
2018/03/28 12:29:25 Serving securely on HTTPS port: 8443
```

##### Expected result
I expect an insecure port to also become available. If you remove the "--auto-generate-certificates" flag everything works.

**Comment by floreks** [comment]
As described in our docs:
> When enabled, Dashboard login view will also be shown when Dashboard is not served over HTTPS. Still, it requires frontend to be accessed over HTTPS (i.e. secure nginx proxy).

This means that those 2 arguments are mutually exclusive and `auto-generate-certificates` arg is more important. By providing `auto-generate-certificates` flag you are basically enabling HTTPS on the backend side.

`enable-insecure-login` flag is there only in case you do not want to use HTTPS directly on backend side but it is still required that frontend will be accessed over HTTPS, like mentioned above. Thanks to this flag you are able to easily configure secure ingress resource with i.e. nginx proxy that will handle the traffic.

All this is done for security reasons and we will not allow to make raw requests with user credentials.
