### ISSUE TITLE
In Japanese environment, the text of the dashboard left menu is truncated.

### ISSUE THREAD

**Issue by thinkingcoding** [kubernetes/dashboard#2929]
##### Environment

```
Dashboard version:v1.8.3
Kubernetes version:v1.9.2
Operating system:3.10.0-327.el7.x86_64  x86_64 GNU/Linux
Node.js version:v9.4.0
Go version:go version go1.9 linux/amd64
```

##### Steps to reproduce

Google Chrome 
1.Set the language of the browser into Japanese.
2.Open dashboard
3.On the left menu, some long Japanese are truncated

##### Observed result

On the left menu, some long Japanese are truncated

##### Expected result

Some long text of the left menu is truncated

##### Comments

If the other language is very long, the text behind will be truncated.

**Comment by maciaszczykm** [comment]
Outdated after Angular migration. We will be implementing localization once more.

/close
