### ISSUE TITLE
k8s docker image

### ISSUE THREAD

**Issue by zhixingPan** [kubernetes/dashboard#2932]
##### Environment

```
Dashboard version:v1.8.2
Kubernetes version:v1.8.4
Operating system:redhat
Node.js version:v8.9.4
Go version:17.09.0-ce
```

##### Steps to reproduce

1. revised some codes in the dashboard project,
2. maked a docker image by the Dockerfile in this project
3.deployed the dashboard using the image I maded in kubernetes,but the pod occured an error,here is the detail
Error: failed to start container "kubernetes-dashboard": Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"--auto-generate-certificates\": executable file not found in $PATH"

##### Observed result

the pod cann't be run normally,I have no idea how to fix the bug ,wish someone can give me some advise.

**Comment by tedmiston** [comment]
Do you experience the same error with the latest release (v1.8.3)?  The image can be pulled from Google's registry at `k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3`.

**Comment by zhixingPan** [comment]
no ,I didn't .I just hava some question with the docker image I made after I changed some code in the kubernetes dashborad project.

**Comment by floreks** [comment]
As latest release starts fine, I am assuming that your changes in the code/yaml are causing the crash. We don't have any information that could be used to determine why it crashes.
