### ISSUE TITLE
How to delete dashboard from google cloud cluster created by default

### ISSUE THREAD

**Issue by kolpav** [kubernetes/dashboard#2939]
##### Environment

```
Dashboard version:
1.8.0
Kubernetes version:
1.8.8-gke.0
Operating system:
Container-Optimized OS (cos)
```

##### Steps to reproduce

1. Create cluster on google cloud with kubernetes dashboard option enabled
2. Try to delete dashboard

```
kubectl delete rs kubernetes-dashboard-768854d6dc --namespace=kube-system
kubectl delete deployment kubernetes-dashboard --namespace=kube-system
kubectl delete service kubernetes-dashboard  --namespace=kube-system
kubectl delete role kubernetes-dashboard-minimal --namespace=kube-system
kubectl delete rolebinding kubernetes-dashboard-minimal --namespace=kube-system
kubectl delete sa kubernetes-dashboard --namespace=kube-system
kubectl delete secret kubernetes-dashboard-certs --namespace=kube-system
kubectl delete secret kubernetes-dashboard-key-holder --namespace=kube-system
```
##### Observed result

Dashboard is never deleted
##### Expected result

Dashboard is deleted
##### Comments

If I could I would create my cluster again from scratch but I can't because I would run out of letsencrypt certificates issued for my domain I think I am just below limit now.

**Comment by rf232** [comment]
you need to disable the dashboard addon otherwise the cluster will recreate all dashboard related resources

**Comment by kolpav** [comment]
Thanks, `gcloud container clusters update <cluster_name> --update-addons=KubernetesDashboard=DISABLED` did it.
