### ISSUE TITLE
Unable to reinstall dashboard

### ISSUE THREAD

**Issue by andrei-dascalu** [kubernetes/dashboard#2940]
##### Environment

```
Dashboard version: v1.8.3 
Kubernetes version: v1.10.0
Operating system: Linux docker5 4.9.80-hypriotos-v7+ #1 SMP Tue Mar 27 07:46:13 UTC 2018 armv7l GNU/Linux  (RaspberryPi3, HypriotOS) 
Node.js version:
Go version:
```

##### Steps to reproduce

1. Deploy dashboard: `kubectl apply -f https://github.com/kubernetes/dashboard/blob/v1.8.3/src/deploy/recommended/kubernetes-dashboard-arm.yaml`
2. Remove dashboard: 

- kubectl delete deployment kubernetes-dashboard --namespace=kube-system
- kubectl delete service kubernetes-dashboard  --namespace=kube-system
- kubectl delete role kubernetes-dashboard-minimal --namespace=kube-system
- kubectl delete rolebinding kubernetes-dashboard-minimal --namespace=kube-system
- kubectl delete sa kubernetes-dashboard --namespace=kube-system
- kubectl delete secret kubernetes-dashboard-certs --namespace=kube-system
- kubectl delete secret kubernetes-dashboard-key-holder --namespace=kube-system

3. Try to deploy again:
`kubectl apply -f https://github.com/kubernetes/dashboard/blob/v1.8.3/src/deploy/recommended/kubernetes-dashboard-arm.yaml`

##### Observed result
`error: error converting YAML to JSON: yaml: line 325: mapping values are not allowed in this context`

##### Expected result
deploy successful

##### Comments
Seems strange that it reports an error on the non-existent line 325 as if the yaml were concatenated against another file. Also, it's the exact same command that previously worked.

**Comment by Arslanbekov** [comment]
I think it's better to use raw.

```https://raw.githubusercontent.com/kubernetes/dashboard/v1.8.3/src/deploy/recommended/kubernetes-dashboard.yaml```

**Comment by andrei-dascalu** [comment]
No difference, regardless of which I use I can't reinstall the dashboard after an initial installation.
