### ISSUE TITLE
Unable to view details of etcd-cluster pods, launched and manged by the etcd-operator

### ISSUE THREAD

**Issue by kcao3** [kubernetes/dashboard#2946]
##### Environment
```
Dashboard version: v1.8.3
Kubernetes version: v1.10.0
Operating system: CentOS 7.4
Node.js version:
Go version:
```
##### Steps to reproduce
We're  currently running an etcd cluster in k8s, managed by the etcd-operator:  https://github.com/coreos/etcd-operator.
From k8s dashboard, we are not able to view details of any etcd-cluster pods. When we click on  one of the etcd-cluster-xyz pods from the k8s dashboard, we see the following:
Internal Server Error (500)
Unknown reference kind EtcdCluster

From one of our k8s dashboard pods, we see these logging errors:
Getting details of etcd-cluster-xyz pod in default namespace
Unknown reference kind EtcdCluster
Outcoming response to <POD_IP>: with 500 status code

However, we are still able to get logs and information of this pod when using kubectl command:
kubectl describe pod etcd-cluster-xyz
kubectl logs -f etcd-cluster-xyz..

So, this means k8s API server is fine.

##### Observed result
k8s dashboard user is not able to view details of etcd-cluster pod, launched by the etcd-operator.

##### Expected result
k8s dashboard user should be able to view details of etcd-cluster pod, launched by the etcd-operator, just like other k8s pods.

##### Comments
I believe this issue is related to #2901.

**Comment by kcao3** [comment]
Does anyone have any update on this one?

**Comment by MichaelMitchellM** [comment]
I am also having this problem

**Comment by maciaszczykm** [comment]
Closing in favor of #3251.

/close
