### ISSUE TITLE
Unable to access dashboard in chome or firefox

### ISSUE THREAD

**Issue by Dileep2016** [kubernetes/dashboard#2953]
##### Environment
<!  I have created the kubernetes cluster on my AWS environment by following document Kubernetes Hard way-kelseyhightower my kuberneets cluster is up and running.
but i am unable to access the outside it is throwing the 401 error.

Unauthorized error

please help me  on this

 
     $node 1.9
     $ go version 1.9
 -->

```
Dashboard version: 1.9
Kubernetes version:1.9
Operating system: ubuntu 
Node.js version:
Go version:
```

##### Steps to reproduce
https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#nodeport
using this i am able to access dashboard but it is not safe for production 

##### Expected result
i would like to expose my dash board and conatiner to expose out side secure way ..

**Comment by floreks** [comment]
This is a configuration issue, not a Dashboard issue. Ask for help on kubernetes slack if you want to know how to expose an application in a secure way.
