### ISSUE TITLE
i can access dashboard in Linux with https://masternodeIP:port with googlechrome, but can't do that in Windows.

### ISSUE THREAD

**Issue by GoodJoey** [kubernetes/dashboard#2954]
##### Environment

i can access dashboard in Linux browser with https://masternodeIP:port , but can't access in Windows.
the computers are all in the same local network, and can reach each other.
the error code shown in the windows' browser is NET::ERR_CERT_INVALID.

```
Dashboard version: 1.8.3
Kubernetes version: 1.9
Operating system: linux/ windows
Node.js version:
Go version:
```

**Comment by weapon008** [comment]
我之前也有这个问题。

**Comment by xuchenhao001** [comment]
@GoodJoey I met the same problem. 
When I create a dashboard deployment, this solve the `NET::ERR_CERT_INVALID` problem of chrome:
```bash
$ mkdir certs
$ openssl req -nodes -newkey rsa:2048 -keyout certs/dashboard.key -out certs/dashboard.csr -subj "/C=/ST=/L=/O=/OU=/CN=kubernetes-dashboard"
$ openssl x509 -req -sha256 -days 365 -in certs/dashboard.csr -signkey certs/dashboard.key -out certs/dashboard.crt
$ kubectl create secret generic kubernetes-dashboard-certs --from-file=certs -n kube-system
$ kubectl create -f kubernetes-dashboard.yaml
```

**Comment by cheld** [comment]
https://masternodeIP:port - not sure which port you mean. Most likely your setup only allows local bindings to this port. Use `kubectl proxy` to connect from outside to apiserver. Or expose Dashboard with nodeport or loadbalancer. Make sure to have proper SSL & authentication in place

**Comment by GoodJoey** [comment]
@xuchenhao001 
thanks, i will take a try
@cheld 
by https://masternodeIP:port , i meant i can access the dashboard from another linux machine.
but can't access the dashboard from another windows machine. seems like some certification error.

**Comment by bamboox** [comment]
kubeadm init:

Dashboard version: 1.8.3
Kubernetes version: 1.10.2


Google Chrome 66.0.3359.139 

"NET::ERR_CERT_INVALID"

**Comment by henshitou** [comment]
> "/C=/ST=/L=/O=/OU=/CN=kubernetes-dashboard"

this info should specify for the case when you create it, for example, this info should get from this command "openssl x509 -req -sha256 -days 365 -in dashboard.csr -signkey dashboard.key -out dashboard.crt"

**Comment by pravinba** [comment]
https://github.com/kubernetes/dashboard/issues/3472

This solution works !!!

**Comment by zimmertr** [comment]
I don't understand how creating a certificate and registering it as a secret is solving this issue. Considering that the Dashboard won't be instructed at any point to use the newly generated certificate instead of the old one?

**Comment by zimmertr** [comment]
FYI for those using v2 of the dashboard you will need to change the namespace in which you create the `kubernetes-dashboard-certs` secret as it has been moved to `kubernetes-dashboard` from `kube-system`.

**Comment by graywen24** [comment]
> FYI for those using v2 of the dashboard you will need to change the namespace in which you create the `kubernetes-dashboard-certs` secret as it has been moved to `kubernetes-dashboard` from `kube-system`.

thansk..i also notice it so create the namespace first then apply the yaml file..
which works for me..
cool.
