### ISSUE TITLE
Dashboard can not jump to the main page after sign in within token 

### ISSUE THREAD

**Issue by Itfly** [kubernetes/dashboard#2956]
##### Environment

```
Dashboard version:
k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Operating system:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
Node.js version:
?
Go version:
?
```

##### Steps to reproduce

I installed the dashboard by using the [recommended setup](https://github.com/kubernetes/dashboard/wiki/Installation) 
And start it by using the below command
```
 kubectl proxy --address='0.0.0.0' --accept-hosts='.*'
```
with the url: http://10.190.148.74:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login, i can see the `Kubernetes Dashboard` enter token window. after entering the right token(response status is 200), it can not jump to the main page.

**Comment by floreks** [comment]
Read *NOTE*:
https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#kubectl-proxy
