### ISSUE TITLE
`square/go-jose: error in cryptographic primitive` when trying to access dashboard

### ISSUE THREAD

**Issue by keigezellig** [kubernetes/dashboard#2962]
##### Steps to reproduce
1. Created a new cluster in the google cloud console with default settings
2. Used `gcloud container clusters get-credentials <cluster name>` to switch to the cluster
3. Started the proxy `kubectl proxy`
4. Try to access to dashboard with `http://localhost:8001` which fails with said error message even after retrying several times

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.0
Commit: 054916b8fbadebd32dc16d32108fdd3c9ccbf400
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by floreks** [comment]
Outdated Dashboard version.
