### ISSUE TITLE
/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/ returns net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by DongyouSeo** [kubernetes/dashboard#2965]
##### Environment

```
Dashboard version: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3
Kubernetes version:
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Operating system:
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# uname -a
Linux ucf2c-iot-jamesdocker1-mgmt1 4.1.12-103.3.8.el7uek.x86_64 #2 SMP Mon Aug 21 17:27:54 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
Node.js version:
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# node --version
v6.10.1
Go version:
```

##### Steps to reproduce

I have 2 VMs running on some cloud computing (not local), master(ucf2c-iot-jamesdocker1-mgmt1) and worker(ucf2c-iot-jamesdocker4-mgmt1).
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# kubectl get nodes
NAME                           STATUS    ROLES     AGE       VERSION
ucf2c-iot-jamesdocker1-mgmt1   Ready     master    4h        v1.8.4
ucf2c-iot-jamesdocker4-mgmt1   Ready     <none>    4h        v1.8.4

1. Install dashboard on master node
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

2. Run proxy on master node
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# kubectl proxy --address="10.248.37.174" -p 8001 --accept-hosts '.*'
Starting to serve on 10.248.37.174:8001

3. Access to 'http://10.248.37.174:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/' through web browser such as Chrome, Firefox and so on
[Error found here]
![image](https://user-images.githubusercontent.com/38396641/38777230-6d027264-40df-11e8-8e2e-17ece8daa7b2.png)

'https://10.244.1.8:8443/' presented in the above attachment is Dashboard service's Endpoint.
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# kubectl describe service -n kube-system kubernetes-dashboard
Name:              kubernetes-dashboard
Namespace:         kube-system
Labels:            k8s-app=kubernetes-dashboard
Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard","namespace":...
Selector:          k8s-app=kubernetes-dashboard
Type:              ClusterIP
IP:                10.97.64.43
Port:              <unset>  443/TCP
TargetPort:        8443/TCP
Endpoints:         10.244.1.8:8443
Session Affinity:  None
Events:            <none>

##### Observed result

I have suspected points.

1. Proxy returns the 'context canceled' as time passes on master node.
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# kubectl proxy --address="ucf2c-iot-jamesdocker1-mgmt1.opciot.oracleinternalucf2c.oraclecorp.com" -p 8001 --accept-hosts '.*'
Starting to serve on 10.248.37.174:8001
I0415 09:54:41.655184    6194 logs.go:41] http: proxy error: context canceled
I0415 09:54:52.789000    6194 logs.go:41] http: proxy error: context canceled

2. Localkube doesn't find the apiserver.crt in /var/lib/localkube/certs on worker node
[root@ucf2c-iot-jamesdocker4-mgmt1 ~]# vim /var/log/messages
Apr 15 10:05:34 ucf2c-iot-jamesdocker4-mgmt1 localkube: E0415 10:05:34.898477   23697 localkube.go:137] open /var/lib/localkube/certs/apiserver.crt: no such file or directory
Apr 15 10:05:35 ucf2c-iot-jamesdocker4-mgmt1 localkube: I0415 10:05:35.898354   23697 ready.go:30] Performing healthcheck on https://localhost:8443/healthz
Apr 15 10:05:35 ucf2c-iot-jamesdocker4-mgmt1 localkube: E0415 10:05:35.898465   23697 localkube.go:137] open /var/lib/localkube/certs/apiserver.crt: no such file or directory
Apr 15 10:05:36 ucf2c-iot-jamesdocker4-mgmt1 localkube: I0415 10:05:36.898353   23697 ready.go:30] Performing healthcheck on https://localhost:8443/healthz
Apr 15 10:05:36 ucf2c-iot-jamesdocker4-mgmt1 localkube: E0415 10:05:36.898429   23697 localkube.go:137] open /var/lib/localkube/certs/apiserver.crt: no such file or directory
Apr 15 10:05:37 ucf2c-iot-jamesdocker4-mgmt1 kubelet: W0415 10:05:37.477143   13145 helpers.go:847] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Apr 15 10:05:37 ucf2c-iot-jamesdocker4-mgmt1 localkube: I0415 10:05:37.898354   23697 ready.go:30] Performing healthcheck on https://localhost:8443/healthz
Apr 15 10:05:37 ucf2c-iot-jamesdocker4-mgmt1 localkube: E0415 10:05:37.898472   23697 localkube.go:137] open /var/lib/localkube/certs/apiserver.crt: no such file or directory

3. kubernetes-dashboard returns some heapster error in log while heapster is working fine.
[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# kubectl logs -n kube-system -f heapster-746cc766d7-zjpgr
I0415 06:05:14.673823       1 heapster.go:72] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
I0415 06:05:14.673885       1 heapster.go:73] Heapster version v1.4.2
I0415 06:05:14.674294       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version v1
I0415 06:05:14.674322       1 configs.go:62] Using kubelet port 10255
I0415 06:05:14.774810       1 influxdb.go:278] created influxdb sink with options: host:monitoring-influxdb.kube-system.svc:8086 user:root db:k8s
I0415 06:05:14.774871       1 heapster.go:196] Starting with InfluxDB Sink
I0415 06:05:14.774886       1 heapster.go:196] Starting with Metric Sink
I0415 06:05:14.809557       1 heapster.go:106] Starting heapster on port 8082
I0415 06:06:05.072190       1 influxdb.go:241] Created database "k8s" on influxDB server at "monitoring-influxdb.kube-system.svc:8086"

[root@ucf2c-iot-jamesdocker1-mgmt1 ~]# kubectl logs -n kube-system -f kubernetes-dashboard-5569448c6d-j88vd
...
2018/04/15 10:07:10 Metric client health check failed: an error on the server ("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html>\n\n\n<head>\n  <meta content=\"text/html; charset=UTF-8\" http-equiv=\"Content-Type\">\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\"/>\n  <title>McAfee Web Gateway - Notification</title>\n  <script src=\"/api/v1/namespaces/kube-system/services/heapster/proxy/mwg-internal/de5fs23hu73ds/files/javascript/sw.js\" type=\"text/javascript\"></script>\n  <link rel=\"stylesheet\" href=\"/api/v1/namespaces/kube-system/services/heapster/proxy/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css\"/>\n</head>\n\n\n<body onload=\"swOnLoad();\">\n  <table class=\"bodyTable\">\n    <tr>\n      <td class=\"bodyData\" background=\"/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif\">\n\n<table class=\"logoTable\">\n  <tr>\n    <td class=\"logoData\">\n      <a href=\"http://www.mcafee.com\">\n        <img src=\"/api/v1/namespaces/kube-system/services/heapster/proxy/mwg-internal/de5fs23hu73ds/files/default/img/oralogo-small.gif\"></a>\n    </td>\n  </tr>\n</table>\n\n\n\n\n<table class=\"titleTable\" background=\"/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg\">\n  <tr>\n    <td class=\"titleData\">\n      Cannot Connect\n    </td>\n  </tr>\n</table>\n\n\n\n<table class=\"contentTable\">\n  <tr>\n    <td class=\"contentData\">\n      The proxy could not connect to the destination in time. Please verify the site you are attempting to access and retry.\n    </td>\n  </tr>\n</table>\n\n\n\n<table class=\"infoTable\">\n  <tr>\n    <td class=\"infoData\">\n      <b>URL: </b><script type=\"text/javascript\">break_line(\"http://10.96.0.1:443/healthz\");</script><br/>\n    </td>\n  </tr>\n</table>\n\n\n\n\n<table class=\"policyTable\">\n  <tr>\n    <td class=\"policyHeading\">\n      <hr>\n\n    </td>\n  </tr>\n  <tr>") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.

##### Expected result

Successfully open the dashboard in web browser

##### Comments

Please guide me to correct this TLS issue in web browser to access dashboard login page.

**Comment by tubzby** [comment]
same error.
can't access with 'kubectl proxy', but if I login to one of the host I can reach https://ip:8443

**Comment by floreks** [comment]
This is a configuration issue. It is api server and kubectl proxy that block your requests. The application you are trying to access has nothing to do with it. Try to access any other application this way and you will see same error.
