### ISSUE TITLE
Dashboard does not load fully

### ISSUE THREAD

**Issue by mabushey** [kubernetes/dashboard#2969]
##### Environment

```
Dashboard version:
https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

Kubernetes version:
Client Version: v1.10.1
Server Version: v1.10.1

Operating system:
Kubernetes cluster: CoreOS
client machine: Ubuntu 16.04

Node.js version:
not installed

Go version:
go version go1.8.3 linux/amd64

```

##### Steps to reproduce

kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

kubectl proxy

chrome: http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/pod?namespace=default

##### Observed result
menu bar on left eventually loads, blue loading circle in middle never goes away

##### Expected result
Working web UI

**Comment by floreks** [comment]
Closing this as K8S v1.10+ is not officially tested and supported by latest Dashboard v1.8. We will be updating it soon to support newer versions of K8S.

Please always refer to [Compatibility matrix](https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix) to find out supported version ranges.
