### ISSUE TITLE
square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by yellowred** [kubernetes/dashboard#2970]
##### Steps to reproduce
```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

secret "kubernetes-dashboard-certs" created
serviceaccount "kubernetes-dashboard" created
role "kubernetes-dashboard-minimal" created
rolebinding "kubernetes-dashboard-minimal" created
deployment "kubernetes-dashboard" created
service "kubernetes-dashboard" created

$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

##### Environment
```
Installation method: see above
Kubernetes version: v1.9.6
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by yellowred** [comment]
After I had deleted all the pods it started to work. So it was either resource caused or just needed more time to initialise. Gonna keep this issue for informational reasons, but closed as it is solved for me.

**Comment by tanmaykm** [comment]
Faced it too. It was because of a stale browser cookie in my case.

**Comment by rajatrai** [comment]
Faced it too, a bit annoying. In my case, I was using chrome and started a new window in incognito mode and it worked fine.

**Comment by xiaoanyunfei** [comment]
It maybe because your secret token was not encrypted and decrypted by the same pair private key and public key. kube-controller-manager generates the token, and kube-apiserver detects the token. the private key is specified by  **--service-account-key-file** If unspecified, **--tls-private-key-file** is used.

**Comment by rajatrai** [comment]
> It maybe because your secret token was not encrypted and decrypted by the same pair private key and public key. kube-controller-manager generates the token, and kube-apiserver detects the token. the private key is specified by **--service-account-key-file** If unspecified, **--tls-private-key-file** is used.

It didn't get that far where it takes the token ;-)

**Comment by njfix6** [comment]
Yes also get this issue. It happened to me when I switched between kubernetes clusters and I think it doesn't handle the token properly. If I log out and log back in it works.

**Comment by LevonBecker** [comment]
Had the same issue in Chrome. Clear Browser data fixes it.

**Comment by aaronhadoop** [comment]
I solve the same question by login again and input the TOKEN again.

**Comment by farhanJR** [comment]
Faced it too. It was because of a stale browser cookie in my case.

**Comment by alramdein** [comment]
the question is why did the cookie become stale?

**Comment by alramdein** [comment]
The question is, how can the browser cookie be stale, and what is its possible cause? Because it happened multiple times on my end.
