### ISSUE TITLE
Logs show someone attempting to brute force access.

### ISSUE THREAD

**Issue by DiginessForever** [kubernetes/dashboard#2973]
##### Steps to reproduce

Rather than letting someone send signal all day, can you auto block them for an hour or so after they've sent a few thousand random application IDs?

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.0
Commit: 054916b8fbadebd32dc16d32108fdd3c9ccbf400
```

**Comment by maciaszczykm** [comment]
I guess that is not Dashboard responsibility, but please correct me if I am wrong.
