### ISSUE TITLE
Default Dashboard URL is overview for all namespaces, slow to load with many services

### ISSUE THREAD

**Issue by davidtseng** [kubernetes/dashboard#2974]
##### Environment

```
Dashboard version: 1.8.3
Kubernetes version: 1.9.2
Operating system: coreos
Node.js version:
Go version:
```

##### Steps to reproduce

Load the default Dashboard URL:
/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview
##### Observed result

With a few services this loads fast but with on a larger cluster with 1000+ services, this can take over 1 minute to load. Using the login screen, after logging in the page is not functional until the default page loads.
##### Expected result

Dashboard loads and is functional quickly.
##### Comments

Specifying a namespace dramatically improves load time, for example using the 'default' namespace (Dashboard version 1.6.0 appears to use this):
/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default

**Comment by davidtseng** [comment]
Currently with the head version of Kube Dashboard with fix from @pengx17 hitting 'skip' on the login screen hangs, appears to redirect to the login screen.

**Comment by pengx17** [comment]
@davidtseng I will have a look, sorry about that

**Comment by floreks** [comment]
First try to increase memory and cpu limits of Dashboard. As API server does not offer pagination, then all this data has to first be loaded into the memory of our backend. It's possible that due to memory limits your instance of Dashboard becomes unresponsive as it eventually goes out of memory.
