### ISSUE TITLE
Support metrics API

### ISSUE THREAD

**Issue by ijl** [kubernetes/dashboard#2986]
dashboard should read from the metrics APIs in order to be compatible with future kubernetes versions.

heapster is being deprecated (https://github.com/kubernetes/heapster/pull/2022) in favor of metrics-server (https://github.com/kubernetes-incubator/metrics-server).

The current heapster or metrics-server releases can provide the metrics APIs (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/resource-metrics-api.md). So a single client implementation can support both on I think kubernetes 1.7 or above.

cc #2976, #1310

**Comment by ibrasho** [comment]
I can start working on this.

**Comment by bryk** [comment]
Awesome, this is yours then. Enjoy :) Talk to me or @konryd on slack if you need any help.

**Comment by gjmzj** [comment]
@ibrasho looking forward to your good news.

**Comment by ibrasho** [comment]
I hadn't had much time to work on this in the past couple of weeks. I'm expecting to be able to put more time into it soon.

I'd appreciate someone with good understanding of the current implementation to run ideas by on Slack or email.

**Comment by xdexter** [comment]
+1

**Comment by dudo** [comment]
+1 - I'm being told not to install heapster and its dependencies.

**Comment by ansilh** [comment]
+1

**Comment by chrisbeach** [comment]
+1

**Comment by cheynewallace** [comment]
+1 from me

**Comment by nickychow** [comment]
+1

**Comment by mylesjao** [comment]
+1

**Comment by GarethOates** [comment]
+1

**Comment by nikox94** [comment]
+1

**Comment by midN** [comment]
👍

**Comment by llamahunter** [comment]
People, you don't need to each individually comment "+1" to follow this issue.  Just subscribe to it using the button to the right.

**Comment by marceliwac** [comment]
@llamahunter
Or just use the thumbs up reaction to the original issue post to bump it up...

**Comment by chrisob** [comment]
Since this didn't make it into the latest release, is it still planned to replace the dependency on Heapster with the metrics API?  (@ibrasho ?)

We're having to run Heapster along-side metrics-server in our 1.11 cluster just for the dashboard  :grimacing:

**Comment by leezout** [comment]
Any news on that ? As right now using k8 1.11.3 and the latest version of the dashboard/heapster/influxdb
I am unable to get the metric system to work.

`Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.`

**Comment by XciD** [comment]
@ibrasho Do you need some help about that ?

**Comment by maciaszczykm** [comment]
@XciD He has not beed active since then. Perhaps you can take it with our assistance?

/cc @floreks

**Comment by Ascendance** [comment]
the default heapster install on top of a Kubeadm cluster is broken with certificate errors

**Comment by Stocco** [comment]
this one is a must. waiting for it

**Comment by ajatkj** [comment]
Is it possible to run heapster for dashboard in parallel with metric-server? Will they give the same stats?

**Comment by guruprasadbhavsar** [comment]
Any good news about this issue? Can we now able to do the same?

**Comment by XciD** [comment]
@johnSchnake I will not be able to start soon, so go ahead.

**Comment by AishSundar** [comment]
@johnSchnake @XciD in the light of Heapster retiring in 1.13 timeframe is there any latest progress on getting dashboard to metricsAPI? Is there an ETA of when this can land. 1.13 is targeted for release next week 12/3

**Comment by johnSchnake** [comment]
I’ve just started peeking at this so I don’t have a great timeline; I do plan on actively working on it though.

**Comment by PierluigiLenociAkelius** [comment]
+1

**Comment by ironfugu** [comment]
Hey @johnSchnake  - hope you have a good holiday.  Do you have any update on this work?

**Comment by johnSchnake** [comment]
Sorry, after doing a bit of investigation on this I hadn't gotten back to be active on it. I had just done more investigation since I wasn't familiar with the codebase. I am still happy to help but will step aside. Happy to help with reviews though if it would help.

**Comment by Angha** [comment]
Kubernetes-dashboard 1.10.1 (https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml)  not  working with  kubernetes on-prem cluster  version 1.13.1.
'kubectl logs -n kube-system  kubernetes-dashboard-57df4db6b-4h5wr' errors out  " Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds"

What's the work around  or  it's  an open issue which needs a  fix?

**Comment by jeefy** [comment]
@Angha Kubernetes v1.13 removed Heapster. Short term, you can still install Heapster to get things working. 

Long term, there is already a fix in flight (https://github.com/kubernetes/dashboard/pull/3504) that will be in the next Dashboard release.

**Comment by anupambasak** [comment]
+1

**Comment by aleks-mariusz** [comment]
any guidance on how this is going or how to test what's been done so far (in case you want more folks testing it)

**Comment by MrD2** [comment]
@aleks-mariusz  check https://github.com/kubernetes/dashboard/pull/3504

I'm actually trying to test the container but i'm having some issues with the kubeconfig file import

**Comment by midN** [comment]
@aleks-mariusz @MrD2 - https://brookbach.com/2018/10/29/Heapster-on-Kubernetes-1.11.3.html

**Comment by MrD2** [comment]
This requires to move back to heapster (which i don't want to)

The only thing not working in the dashboard are the usage visualization.... And for that you have monitoring. I'm just testing the proposed container to maintain compatibility

**Comment by weiqiang333** [comment]
有新的进展吗？我打算在接下来选型中抛弃 heapster，使用 metrics server。

**Comment by scorsair** [comment]
Guys, do you have any updates on this?

**Comment by maciaszczykm** [comment]
@jeefy Any updates?

**Comment by mouhsinelonly** [comment]
i think maybe next year, it has already been a year already

**Comment by maciaszczykm** [comment]
@mouhsinelonly You are free to work on that, nobody is stopping you from it I think.

**Comment by jeefy** [comment]
https://github.com/kubernetes/dashboard/pull/3504 Is ready to be reviewed. Please bring any criticisms (constructive or otherwise) and we'll hash this out. :)

**Comment by onitake** [comment]
@weiqiang333 对不起，标准语言是英语。如果您不会说英语，请使用翻译服务。 (And sorry for my terrible Chinese... I simply used Google Translate...)

**Comment by chiefy** [comment]
As someone who has deployed dashboard w/ heapster, coming back here and trying to figure out if I still need to use heapster, or if I can use metrics-server is _very_ confusing. The wiki still states you have to use heapster?

**Comment by labria** [comment]
@chiefy this has been merged, but not yet released.

**Comment by leezout** [comment]
@labria Do we know the approximate release date for 2.0?

**Comment by Vrtak-CZ** [comment]
@leezout see https://github.com/kubernetes/dashboard/milestone/1

**Comment by ld-singh** [comment]
any idea on new release date for 2.0?

**Comment by xspeng** [comment]
How's this going?

**Comment by floreks** [comment]
Check the relases :)

**Comment by MarcusNoble** [comment]
Looks like there's a mistake in https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml, the deployment refers to `kubernetes-dashboard-head` while all other resources use `kubernetes-dashboard`.

I'm also having trouble running this on 1.13. Looks like the dashboard isn't finding the metrics scraper service so isn't starting.

**Comment by cw-pratik** [comment]
Ya same issue here..I tried deploying [this](https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/alternative.yaml)  and it worked. It is not on https though

**Comment by ld-singh** [comment]
Anyone faced issue mentioned in https://github.com/kubernetes/dashboard/issues/4088 and fixed?

**Comment by lz006** [comment]
same issue here on 1.14

**Comment by starplanet** [comment]
Does this problem have been fixed on 1.14?

**Comment by maciaszczykm** [comment]
Metrics support is part of v2 beta. Beta is not part of K8s release, we have to make it final then we can update.

**Comment by nicklhy** [comment]
Same issue on kubernetes V1.15.2

**Comment by BealChen** [comment]
Same issue on kubernetes V1.15.2 

Is there any other way to temporarily use it?

**Comment by BskyRui** [comment]
Dashboard doesn't support merics on Kubernetes V1.15.3 🙁

**Comment by floreks** [comment]
Any details about that? Version used? Configuration details? Without additional information, I am just assuming this is a configuration issue on your end.

**Comment by BskyRui** [comment]
> Any details about that? Version used? Configuration details? Without additional information, I am just assuming this is a configuration issue on your end.

Kubernets V1.15.3 & Dashboard v1.10.1, I installed metrics successful,  After refresh the dashboard page, I can't see the CPU graph. I need to configure something?

**Comment by BouweCeunen** [comment]
I have this issue when there are 'completed' pods in my namespace. When I execute `kubectl delete pods --field-selector=status.phase=Succeeded --all-namespaces`, everything is ok.

**Comment by floreks** [comment]
@BskyRui what part of the sentence "Metrics support is part of v2 beta" is not clear? It will not work with v1. Also, there are still some issues related to the graphs itself: https://github.com/kubernetes/dashboard/milestone/1

**Comment by patsadow2** [comment]
kubeadm v1.16.2 is there any idea how to run dashboard there ?

**Comment by oscarlofwenhamn** [comment]
@patsadow2 We've gotten the v2 beta dashboard running easily in our 1.16.2 cluster, using the manifest provided [here](https://github.com/kubernetes/dashboard/blob/master/docs/user/installation.md).
