### ISSUE TITLE
Dashboard v2 reloads in the loop 

### ISSUE THREAD

**Issue by svennela** [kubernetes/dashboard#2987]
##### Environment

```
Dashboard version:
Kubernetes version: 1.9
Operating system: mac
Node.js version: v6.9.1
Go version:go1.10
```

##### Steps to reproduce

started kubeproxy and then gulp serve

2018/04/26 11:20:13 Starting overwatch
2018/04/26 11:20:13 Using apiserver-host location: http://localhost:8080
2018/04/26 11:20:13 Skipping in-cluster config
2018/04/26 11:20:13 Using random key for csrf signing
2018/04/26 11:20:13 No request provided. Skipping authorization
[BS] [BrowserSync SPA] Running...
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:9090/
    External: http://<externalip>:9090/
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://<ExternalIP>:3001
 --------------------------------------
[Browsersync] Serving files from: /Users/svennela/workspace/go-apps/dashboard/.tmp/serve
[Browsersync] Serving files from: /Users/svennela/workspace/go-apps/dashboard/src/app
2018/04/26 11:20:13 Successful initial request to the apiserver, version: v1.9.0
2018/04/26 11:20:13 Generating JWE encryption key
2018/04/26 11:20:13 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/04/26 11:20:13 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/04/26 11:20:14 Initializing JWE encryption key from synchronized object
2018/04/26 11:20:14 Creating in-cluster Heapster client
2018/04/26 11:20:14 Serving insecurely on HTTP port: 9091
2018/04/26 11:20:16 Successful request to heapster
##### Observed result

when i open browser, it is loop where overview link flickers and in command line of server

2018/04/26 11:19:55 [2018-04-26T11:19:55-07:00] Incoming HTTP/1.1 GET /api/v1/login/status request from 127.0.0.1:57973: {}
2018/04/26 11:19:55 [2018-04-26T11:19:55-07:00] Outcoming response to 127.0.0.1:57973 with 200 status code
2018/04/26 11:19:55 [2018-04-26T11:19:55-07:00] Incoming HTTP/1.1 GET /api/v1/login/status request from 127.0.0.1:57975: {}
2018/04/26 11:19:55 [2018-04-26T11:19:55-07:00] Outcoming response to 127.0.0.1:57975 with 200 status code
2018/04/26 11:19:55 [2018-04-26T11:19:55-07:00] Incoming HTTP/1.1 GET /api/v1/login/status request from 127.0.0.1:57977: {}
2018/04/26 11:19:55 [2018-04-26T11:19:55-07:00] Outcoming response to 127.0.0.1:57977 with 200 status code

**Comment by maciaszczykm** [comment]
You need to provide more specific steps to reproduce. I am running `gulp serve` on macOS too and it works fine at the moment.

/triage needs-information
/assign
/close
