### ISSUE TITLE
Nodeport management function

### ISSUE THREAD

**Issue by shigy123456** [kubernetes/dashboard#2992]
##### Environment
```
Dashboard version:1.8.2
Kubernetes version:1.9.5
Operating system:centos7.4
Node.js version:8.10.0
Go version:1.9
```

##### Steps to reproduce
When the service allocates the nodeport, you can use nodeip:nodeport to access the service, but after the service restarts, a new nodeport is allocated, and the user cannot find the corresponding service through the original nodeport.
This is problematic because nodeport is a K8s resource, and the user may be buying a nodeport. the nodeport cannot be modified at will, even if the service is rebooted.

##### Observed result
We don't have the ability to manage nodeport, and we need to have this capability to manage nodeport. we can identify whether a particular nodeport is being used, which service is used, the nodeport that is used cannot be allocated, when the service is restarted. The allocated node should continue to be used to ensure that users use their own nodeport resources.

##### Expected result
We need to have a nodeport management interface that manages the nodeport resources of the K8s cluster,Nodeport state to be allocated/assigned,To indicate which service to which nodeport is assigned; when creating the service, use the allocated nodeport

##### Comments

Need to develop a new interface management nodeport

**Comment by cheld** [comment]
Typically, nodeport is intended to be used by load balancer and not directly by user. Nodeports are either randomly taken or you can spefiy in the yaml. In the later case you are risking a port conflict. 
In development bare-metal setups it is probably ok to use node ports. In production environments you might want to use a more sophisticated setup (e.g. use HA-proxy or something else) that balances requests to the nodeports.
Hope this helps

**Comment by shigy123456** [comment]
Well, there are two problems. 
The first is that using yml is a node designated by the user himself when building pod, and he doesn't know if anyone else is using it, so there's a risk of interface conflicts, and I mean add an nodeport management capability. Automatically allocates nodeport by the system, which is used by default and cannot be redistributed. To release, there must be administrator action
The second: in a production environment, even if haproxy is used, you need to remember the corresponding nodeport.once the nodeport is changed, We need to modify the configuration of haproxy
Of course, there are a number of options for external access: load balancery， nodeoport ， externalip. I would like to say that nodeport is a resource for k8s. Since it is a resource, there should be a management function that allows administrators to manage nodeport resources through the interface, which is the original intention of me to ask this question.

**Comment by cheld** [comment]
The haproxy should be configured automatically with the nodeport information retrieving from apiserver. There are a couple of solutions. There is no nodport management needed. In production, users should not have to worry about nodeports. 
For on-premise demo/development environments you can use nodeports as you know what you are doing.

**Comment by shigy123456** [comment]
OK, is there an example of using haproxy? For example: how to use service in the production environment?

**Comment by cheld** [comment]
Not out of my head. BTW: for development purpose you can use also apiserver-proxy (apiserver-ip:port/url-to-service). Depending on apiserver configuration you might need to use kubectl proxy for authentication

Nice overview with some links:
https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0

**Comment by shigy123456** [comment]
ok,thanks

**Comment by cheld** [comment]
Works as intended. Enhancement requests for Kubernetes should go into main repo
