### ISSUE TITLE
not able to access kubernetes dashboard for cluster in an existing vpc  in aws-ec2 instance.

### ISSUE THREAD

**Issue by ishanupadhyay** [kubernetes/dashboard#2994]
I created a cluster in an existing vpc with one master and three nodes . I deployed the kubernetes dashboard using the following command :
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

On running it on browser following error is shown.
Error: 'dial tcp 100.96.1.2:8443: getsockopt: connection timed out'
Trying to reach: 'https://100.96.1.2:8443/'

I changed the service type of dashboard to NodePort then also I'm not able to access it
kubectl logs shows that dashboard pod is running and is secured by port 8443. 

I dont know what is the problem here .......please try to reply at your earliest guys.
My dashboard version is 1.8
Here is the logs in my ec2 instance  
 Starting overwatch
2018/04/30 07:00:54 Using in-cluster config to connect to apiserver
2018/04/30 07:00:54 Using service account token for csrf signing
2018/04/30 07:00:54 No request provided. Skipping authorization
2018/04/30 07:00:54 Successful initial request to the apiserver, version: v1.8.7
2018/04/30 07:00:54 Generating JWE encryption key
2018/04/30 07:00:54 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/04/30 07:00:54 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/04/30 07:00:54 Storing encryption key in a secret
2018/04/30 07:00:54 Creating in-cluster Heapster client
2018/04/30 07:00:54 Auto-generating certificates
2018/04/30 07:00:54 Successfully created certificates
2018/04/30 07:00:54 Serving securely on HTTPS port: 8443
2018/04/30 07:00:54 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.

When I do not specify the vpc in the kops create cluster command  then the dashboard works fine i.e
**kops  create cluster --name=name --zones=awszone --state=s3://s3bucket --yes**
when cluster is created using the above command then the dashboard works fine but in the below case 
as soon as I specify vpc and subnet -
**kops create cluster  --node-count 3 --name wpp.k8s.local --zones us-west-2a,us-west-2b,us-west-2c --master-zones  us-west-2a  --state=s3://kubernetess3bucket --node-size t2.micro --master-size t2.micro --topology public --vpc=vpc-04a96d63**
cluster is created successfully but dashboard does not show up

 Can anyone tell me how to solve this issue?

**Comment by stijndehaes** [comment]
Are you sure this is not a routing problem in your existing vpc? Do you have a route in your route table to forward traffic to the outside world.
For example:
![screen shot 2018-04-30 at 14 54 26](https://user-images.githubusercontent.com/5019818/39428091-7390058a-4c86-11e8-8d55-5c9be10defc2.png)

**Comment by james-knott** [comment]
Just did a fresh k8's cluster with kops. Deployed Jenkins everything went fine. Deployed Dashboard and unable to connect.

**Comment by ishanupadhyay** [comment]
@cheld  Below is kubernetes-dashboard yaml file and I have changed the type: ClusterIP to NodePort  . 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-05-02T09:59:25Z
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
  resourceVersion: "883"
  selfLink: /api/v1/namespaces/kube-system/services/kubernetes-dashboard
  uid: 7e8bacb3-4def-11e8-9a8e-061096369a42
spec:
  clusterIP: 100.71.109.104
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31065
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
 after this I am doing curl localhost:NodePort  
 then also it is not working ...

**Comment by ishanupadhyay** [comment]
@cheld  I did apiserverIP:NodePort still ui is **not accessible** . One thing I noticed is that whenever while creating the cluster I specify the subnets to be used , then ui shows the above error. But when I allow the same subnets that kubernetes creates on its own while creating the cluster then the ui is **accessable**. Does this give you any hint or idea of what is happening? Is there a problem in updating the subnets in the clusters yaml file?

**Comment by cheld** [comment]
Have you tried a hello-world web application (like tutum/hello-world)? Just to make sure your general setup is ok

**Comment by ishanupadhyay** [comment]
@cheld  yes  at first I built a simple docker image of a apache hello world web application and deployed that in kubernetes cluster . It was working totally fine , but in that cluster I did not specify the vpc in the yaml file of the cluster , it created a new vpc on its own .  But for production level use, we dont want this to happen right ? , we have to specify the vpc and subnets to be used as well as the security groups .
The thing that I observed is that , when I am not updating the subnetIDs in the cluster yaml file and allowing kops to use the **default subnetIDs** that it uses from the start then ui is **accessible**  .

**Comment by ishanupadhyay** [comment]
This the logs of kubectl cluster-info dump I think this might help us -

5b6a-4ec3-11e8-9265-06233ba07312", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node ip-10-101-43-104.us-west-2.compute.internal event: Registered Node ip-10-101-43-104.us-west-2.compute.internal in Controller
W0503 11:17:53.676198       5 node_controller.go:916] Missing timestamp for Node ip-10-101-43-104.us-west-2.compute.internal. Assuming now as a timestamp.
I0503 11:17:53.738435       5 node_controller.go:832] Controller detected that zone us-west-2:^@:us-west-2b is now in state FullDisruption.
E0503 11:17:58.326920       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
I0503 11:18:08.255537       5 service_controller.go:651] Detected change in list of current cluster nodes. New node set: [ip-10-101-40-184.us-west-2.compute.internal]
I0503 11:18:08.255558       5 service_controller.go:659] Successfully updated 2 out of 2 load balancers to direct traffic to the updated set of nodes
E0503 11:18:08.297275       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
I0503 11:18:14.116027       5 node_controller.go:832] Controller detected that zone us-west-2:^@:us-west-2b is now in state Normal.
E0503 11:18:18.310345       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
E0503 11:18:28.406475       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
E0503 11:18:38.316046       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
I0503 11:18:44.516154       5 replica_set.go:454] Too few "kube-system"/"kube-dns-7f56f9f8c7" replicas, need 2, creating 1
I0503 11:18:44.519304       5 event.go:218] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"kube-dns", UID:"721ec620-4ec3-11e8-9265-06233ba07312", APIVersion:"extensions", ResourceVersion:"385", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set kube-dns-7f56f9f8c7 to 2
I0503 11:18:44.542576       5 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kube-dns-7f56f9f8c7", UID:"722079db-4ec3-11e8-9265-06233ba07312", APIVersion:"extensions", ResourceVersion:"386", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: kube-dns-7f56f9f8c7-5n7lr
E0503 11:18:48.319117       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
E0503 11:18:58.313164       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
E0503 11:19:08.363153       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
E0503 11:19:18.311385       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
E0503 11:19:28.317747       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
E0503 11:19:38.498542       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
I0503 11:19:48.255760       5 service_controller.go:651] Detected change in list of current cluster nodes. New node set: [ip-10-101-43-104.us-west-2.compute.internal ip-10-101-40-184.us-west-2.compute.internal]
I0503 11:19:48.255784       5 service_controller.go:659] Successfully updated 2 out of 2 load balancers to direct traffic to the updated set of nodes
E0503 11:19:48.312565       5 route_controller.go:115] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: wpp1.k8s.local
I think its like what were saying @stijndehaes

**Comment by ishanupadhyay** [comment]
This issue is been solved now . It was really a small problem . I was using kops version 1.8.7 ., once I upgraded my cluster to 1.9.3 it worked .  Also the other services of type loadbalancer started working by making a small change in the service yaml file .  adding the annotations:service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
 also change the 
  externalTrafficPolicy: from Cluster to Local


service yaml file
**apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
type: LoadBalancer**
