### ISSUE TITLE
Login screen unavailable

### ISSUE THREAD

**Issue by MadWombat** [kubernetes/dashboard#3000]
##### Environment
```
Dashboard version: 1.8.3
Kubernetes version: 1.10.0
Operating system: ubuntu xenial
```

##### Steps to reproduce
Configure a cluster with Node,RBAC authorization
Install Dashboard
Access dashboard via kubectl proxy as described in the README
##### Observed result
Dashboard defaults to the minimal dashboard service account and displays all sorts of warnings about not having access to things. Such as 
```
configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list configmaps in the namespace "default" 
```
##### Expected result
Show the login view or provide reasonable access level for the default dashboard account.
##### Comments
According to docs to show the login view by default, you have to specify --tls-key-file and --tls-cert-file. The deployment process mentioned in all the docs uses --autogenerate-certs flag. And according to PR #2795 auto generated certs are now stored in memory rather than written to the kubernetes-dashboard-certs secret. The means that in the provided configuration dashboard will default to the minimal account and show all the access warnings.

**Comment by proskehy** [comment]
@maciaszczykm then go with the other option in that OR statement: login view...

**Comment by MadWombat** [comment]
The first time you see the dashboard, you should not be bombarded with a zillion errors with no clear recourse on how to fix them. That is what I mean by reasonable. And since it is a dashboard, you should probably have at least enough access by default to view everything dashboard is intended to show.

**Comment by floreks** [comment]
Steps to reproduce are not really reproducible as there are 2 different ways (described by us and tons of unofficial ones) of installing dashboard and only one of them offers login functionality to be enabled by default. 

> According to docs to show the login view by default, you have to specify --tls-key-file and --tls-cert-file.
I have added information to the docs that if you are using latest dashborad installed using recommended setup then login functionality will be working without any additional steps.

How do you think should we extend default dashboard privileges in a way that does not compromise security?

**Comment by floreks** [comment]
Closing as stale.
/close
