### ISSUE TITLE
After closing a window showing a pod's exec view

### ISSUE THREAD

**Issue by joaocc** [kubernetes/dashboard#3003]
##### Steps to reproduce
Whenever I open a pod's exec view, and then close the window, the dashboard pod will always crash

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'dial tcp 10.244.0.155:9090: getsockopt: connection refused'
Trying to reach: 'http://10.244.0.155:9090/api/v1/pod?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp'
```

**Comment by maciaszczykm** [comment]
Cannot reproduce with latest HEAD image. Please reopen if problem still exists.

/triage not-reproducible
/close
