### ISSUE TITLE
Minikube Dashboard reported Gateway Timeout (504)

### ISSUE THREAD

**Issue by clawbc** [kubernetes/dashboard#3007]
##### Steps to reproduce
1. Start minikube
2. Delete failed deployments
3. Try to reload dashboard
3.a Run ```kubectl get deployments``` and get the following response:
```Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get deployments.extensions)```

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.1
Commit: 7b3553aecf28224ef7275e157b5bba7dd23f436a
```

##### Observed result
Dashboard reported Gateway Timeout (504):
```
the server was unable to return a response in the time allotted, but may still be processing the request (get pods)

```

**Comment by maciaszczykm** [comment]
Same as https://github.com/kubernetes/dashboard/issues/3239.

/assign
/close
