### ISSUE TITLE
Replica set card status

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#302]
I've been working on showing statuses of cards. First draft looks like that:

![screenshot from 2016-01-27 14-37-50](https://cloud.githubusercontent.com/assets/2285385/12615047/aeaa2fc2-c503-11e5-94a4-7bebaaaa491f.png)

The problem is that in order to get status we need to query every pod in every controller and check events. This is time consuming. My proposal is to make it async for every card. Currently I've made draft that waits for all info to get retrieved and for even small set of objects I need to wait way too long.

While updating status of card it would be a good idea to show some linear bar on the bottom of card. This should look good. What do you think? Any suggestions about architecture? I was thinking about some validator. 

@bryk @maciaszczykm

**Comment by maciaszczykm** [comment]
Draft image looks good, finally getting closer to state, which is present on mocks. I'm curious if we can format error messages somehow.

Regarding performance I think async calls can be solution, but how it would interact with card placing if we don't know if there will be a message (this means we don't know its size)? Definitely some kind of information about progress should be displayed in that case.

**Comment by floreks** [comment]
Card placing algorithm actually watches for changes, so it should reposition cards if needed. Hopefully without causing much distraction. Beside that we definitely need some kind of pagination on this page.

**Comment by bryk** [comment]
Don't we already query all pods for getting their state? Instead of looking for events, you can check state reasons. Can you try this out?

**Comment by floreks** [comment]
That was the first thing I've tried. They were empty. That's because this error messages actually comes from scheduler object and only events connected to a pod have that information.

**Comment by bryk** [comment]
How about using Reason and Status fields from there: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1391

We already list all pods in the replica set list page.

**Comment by floreks** [comment]
That was also my first idea. When there is a scheduler error, f.e. PodExceedsFreeCpu, then pod is in status pending and both message and reason in this structure are empty. Only event shows failure message. Even when there is image pull error this message is empty.

https://github.com/kubernetes/dashboard/blob/master/src/app/backend/replicasetcommon.go#L84

I've checked in here if it contains some more information but unfortunately no. I think we are stuck with events.

**Comment by bryk** [comment]
I see. That's bad. So how about checking for events for replica set pods only when there is at least only one pod there that is not in running state. This would cut, like, 90% positive cases. 

Re async: The idea behind moving business logic to the backend is to have as much as possible synchronous and fallback to pagination when things get slow. Backend <-> apiserver communication is cheap, whereas frontend <-> backend is costly, so we really want to have one request for replica set list (and possibly paginate or infini-scroll it later). What do you think?

**Comment by floreks** [comment]
> So how about checking for events for replica set pods only when there is at least only one pod there that is not in running state. This would cut, like, 90% positive cases.

That's actually a good idea. I think we can go even further with that. We are getting pod info anyway so how about extending this method and if there is a pod that is in state != running then querying for this pod related events only. Fallback message about warnings could come directly with replica set list structure when loading cards.

**Comment by floreks** [comment]
This was added in #319. Closing.
