### ISSUE TITLE
Not able to access dashboard if kubernetes is behind a proxy server

### ISSUE THREAD

**Issue by whgao** [kubernetes/dashboard#3027]
##### Environment

```
Dashboard version:1.8.3
Kubernetes version:1.10.2
Operating system:   ubuntu x86-64
Node.js version:N/A
Go version:N/A
```

##### Steps to reproduce

Install Kubernetes using kubeadm on a network witha proxy server.

NO_PROXY=localhost,127.0.0.1, 172.16.2.74,172.16.2.75,*.indxhq.com
http_proxy=http://172.16.0.25:3128
https_proxy=http://172.16.0.25:3128
HTTP_PROXY=http://172.16.0.25:3128
HTTPS_PROXY=http://172.16.0.25:3128

kubectl proxy

Access hashboard in the browser with URL: "http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/"

##### Observed result

Browser window shoes error:
      Error: 'Forbidden'
      Trying to reach: 'https://10.244.1.14:8443/'

In another network without proxy server. Dashboard is displayed normally without any problems.

##### Expected result

Expecting to see the dashboard page.

##### Comments

N/A

**Comment by whgao** [comment]
![browserproxysettings](https://user-images.githubusercontent.com/5151552/40039298-bbf063ac-57ca-11e8-9fc1-7beca6e138ff.PNG)

Above is my browser's proxy settings.

**Comment by maciaszczykm** [comment]
> In another network without proxy server. Dashboard is displayed normally without any problems.

Then it is not a Dashboard issue but proxy/setup.

**Comment by yechnlin** [comment]
@whgao do you have resolved this issue? same issue encountered as you, and kubernetes running behind proxy likes your environment.

**Comment by yechnlin** [comment]
need update kube-apiserver pod with "no_proxy=10.244.1.14"
```
root@k8s:/home/k8s# kubectl edit po -n kube-system kube-apiserver-k8s
...
...
    env:
    - name: no_proxy
      value: 10.244.1.14
    image: k8s.gcr.io/kube-apiserver:v1.14.1
    imagePullPolicy: IfNotPresent
...
...
```
