### ISSUE TITLE
Toolbar hides when there's a popup opened in the app

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#303]
@maciaszczykm Try opening image pull secret creation popup to reproduce. Maybe adding `z-index` can help?

**Comment by maciaszczykm** [comment]
Okay, I'll check it.

**Comment by maciaszczykm** [comment]
Okay, I got it. It was caused by Angular behavior, which sets `position: fixed` to `<body>` after clicking option picker. Setting `top: 0` on `kd-toolbar` fixes the issue. Created pull request #304, after it will be merged this issue can be closed.

**Comment by maciaszczykm** [comment]
@bryk It's fixed now.
