### ISSUE TITLE
Viewing a pod with OwnerReferences "kind": "Pod" causes a 500

### ISSUE THREAD

**Issue by bgeesaman** [kubernetes/dashboard#3030]
##### Steps to reproduce
Install the dashboard
```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```
Have a pod with the following metadata (this happens to be from spark-k8s pods):
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-05-15T23:04:55Z
  labels:
    spark-app-selector: spark-991748b029324be69cf0df12fffe7d92
    spark-exec-id: "1"
    spark-role: executor
  name: mypod-1526425486015-exec-1
  namespace: default
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Pod
    name: mypod
    uid: 5cf340d2-5894-11e8-a7d8-024cf569f16a
  resourceVersion: "5321867"
```

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
Unknown reference kind Pod

```

##### Comments
If I use kubectl edit to remove the entire `ownerReferences` block, the dashboard can then resume accessing the pod as normal. It seems that it is simply a matter of the logic being unable to parse metadata.ownerReferences.kind = "Pod"

**Comment by EliZucker** [comment]
Commit f585597581f82c984b6caaf8fde15b701ca54004 seems to have solved this.

**Comment by bgeesaman** [comment]
I'll give that a try.  Thanks!

**Comment by jeefy** [comment]
/close

fix merged to master
