### ISSUE TITLE
question of function formatRequestLog: can we log Request.Body and keep process Request.Body in the same time?

### ISSUE THREAD

**Issue by tubzby** [kubernetes/dashboard#3034]
This is not an issue but a question of function formatRequestLog.

https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/filter.go
```
// formatRequestLog formats request log string.
func formatRequestLog(request *restful.Request) string {
	uri := ""
	if request.Request.URL != nil {
		uri = request.Request.URL.RequestURI()
	}

	content := "{}"
	entity := make(map[string]interface{})
	request.ReadEntity(&entity)
	if len(entity) > 0 {
		bytes, err := json.MarshalIndent(entity, "", "  ")
		if err == nil {
			content = string(bytes)
		}
	}

	return fmt.Sprintf(RequestLogString, time.Now().Format(time.RFC3339), request.Request.Proto,
		request.Request.Method, uri, request.Request.RemoteAddr, content)
}
```

request.ReadEntity will read all http.Request.Body which is an io.Reader, it will be empty after that.
so next time in function handleLogin it will fail with EOF.

```
func (self AuthHandler) handleLogin(request *restful.Request, response *restful.Response) {
	loginSpec := new(authApi.LoginSpec)
	if err := request.ReadEntity(loginSpec); err != nil {
		response.AddHeader("Content-Type", "text/plain")
		response.WriteErrorString(http.StatusInternalServerError, err.Error()+"\n")
		return
	}

	loginResponse, err := self.manager.Login(loginSpec)
	if err != nil {
		response.AddHeader("Content-Type", "text/plain")
		response.WriteErrorString(http.StatusInternalServerError, err.Error()+"\n")
		return
	}

	response.WriteHeaderAndEntity(http.StatusOK, loginResponse)
}
```
I know dashboard is working very well, I also deploy it my self in a kubernetes cluster.
But I don't know how it works.

**Comment by floreks** [comment]
> request.ReadEntity will read all http.Request.Body which is an io.Reader, it will be empty after that.
so next time in function handleLogin it will fail with EOF.

This is handled by `restful-go`. Probably it only passes a copy of request to both functions so in case request has changed it will not affect any functions executed later on.
