### ISSUE TITLE
Kubernetes 1.10.2 - Dashboard not accessible

### ISSUE THREAD

**Issue by eliasbalasis** [kubernetes/dashboard#3038]
##### Environment
Azure
acs-engine
Kubernetes 1.10.2
```
Dashboard version:
latest
Kubernetes version:
1.10.2
Operating system:
linux/amd64
Node.js version:
Unknown
Go version:
go1.9.3
```

##### Steps to reproduce
Successfully installed Kubernetes 1.10.2 using acs-engine on Azure

```
kubectl cluster-info
Kubernetes master is running at https://10.246.7.100:443
Heapster is running at https://10.246.7.100:443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://10.246.7.100:443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://10.246.7.100:443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
Metrics-server is running at https://10.246.7.100:443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
tiller-deploy is running at https://10.246.7.100:443/api/v1/namespaces/kube-system/services/tiller-deploy:tiller/proxy
```

Followed steps under https://github.com/kubernetes/dashboard/blob/master/README.md

##### Observed result
```
Error: 'dial tcp 10.244.1.41:9090: getsockopt: connection timed out'
Trying to reach: 'https://10.244.1.41:9090/'

```
##### Expected result
Dashboard main page

**Comment by vilelm** [comment]
Same problem here, my environment:

Platform: Azure
Deployment: acs-engine

Versions:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Steps to reproduce**
Successfully installed Kubernetes 1.10.2 using acs-engine on Azure:
```
$ kubectl cluster-info
Kubernetes master is running at https://<REDACTED>.cloudapp.azure.com
KubeDNS is running at https://<REDACTED>.cloudapp.azure.com/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://<REDACTED>.cloudapp.azure.com/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
Metrics-server is running at https://<REDACTED>.cloudapp.azure.com/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
tiller-deploy is running at https://<REDACTED>.cloudapp.azure.com/api/v1/namespaces/kube-system/services/tiller-deploy:tiller/proxy
```

Followed steps under [https://github.com/kubernetes/dashboard/blob/master/README.md](https://github.com/kubernetes/dashboard/blob/master/README.md):
Run

```
$ kubectl proxy
```
Then opened this url on my browser http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Observed result**
```
Error: 'dial tcp 10.244.0.9:8443: getsockopt: connection timed out'
Trying to reach: 'https://10.244.0.9:8443/'
```

**Comment by tubzby** [comment]
same problem here with kubernetes v1.10.3, dashboard v1.8.3.

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
outputs:
```
Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.244.1.144:8443/'
```

but if changed it to 
http://localhost:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/, it shows:
```
Error: 'net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://10.244.1.144:8443/'
```
So the service must be normal.

**Comment by tubzby** [comment]
any update on this issue?

**Comment by dennis-xie** [comment]
master install flannel

**Comment by smm190** [comment]
I am experiencing the same issue with Kubernetes 1.10.4

**Comment by tubzby** [comment]
Finally reinstall recommended docker version 17.03 fixed my problem.

**Comment by aar6ncai** [comment]
same problem here too

**Comment by leeadh** [comment]
same problem, how do we resolve?

**Comment by maciaszczykm** [comment]
Unfortunately you have to wait for the next release when we will introduce changes allowing to use it with Kubernetes 1.10.

**Comment by alien2003** [comment]
kubectl --namespace=kube-system port-forward kubernetes-dashboard-5bd6f767c7-8bhkf 8443

https://127.0.0.1:8443/

works for me

**Comment by jorgebirck** [comment]
Same problem with Kubernetes v1.11.0. Port forward temporary solve the issue. Thanks @alien2003

**Comment by Kaijun** [comment]
same problem

**Comment by maciaszczykm** [comment]
Release https://github.com/kubernetes/dashboard/releases/tag/v1.10.0 fixes that problem:

https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix

/close
