### ISSUE TITLE
why the shortcut http://localhost:8001/ui is deprecated ?

### ISSUE THREAD

**Issue by dfang** [kubernetes/dashboard#3042]
From the doc, 

```
The shortcut http://localhost:8001/ui is deprecated. Use the full proxy URL http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
```

why ?

**Comment by floreks** [comment]
API server should only act as an API and it should not provide endpoints that are dependant on external applications being installed inside the cluster. Dashboard is not a built-in application. It is an external UI for kubernetes that might or might not be installed.
