### ISSUE TITLE
error: Unknown controller kind "EtcdCluster": etcd-cluster-000x

### ISSUE THREAD

**Issue by processease** [kubernetes/dashboard#3043]
##### Steps to reproduce
1. Install Service Catalog for Brokered Services
2. Try to drain node via kubectl with --ignore-daemonsets --delete-local-data and --force flags 

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
Unknown reference kind EtcdCluster

```

**Comment by MichaelMitchellM** [comment]
I am also having this problem

**Comment by maciaszczykm** [comment]
What is your Kubernetes version?

**Comment by maciaszczykm** [comment]
@processease @MichaelMitchellM What is your Kubernetes version?

**Comment by MichaelMitchellM** [comment]
@maciaszczykm v1.10.3 from minikube

**Comment by maciaszczykm** [comment]
Okay, so it it most probably version mismatch between Kubernetes and Dashboard. We have to update `client-go` and fix issues on our side to make it work.

**Comment by maciaszczykm** [comment]
Closing in favor of #3251.

/close
