### ISSUE TITLE
User "system:serviceaccount:default:default" cannot ... for 14 items

### ISSUE THREAD

**Issue by zedtux** [kubernetes/dashboard#3064]
##### Environment

```
Dashboard version: 1.8.3
Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:`
Operating system: Debian 9
```

##### Steps to reproduce

1. Install a fresh Kubernetes cluster
2. execute the `kubectl apply -f` to install the dashboard
3. Run `kubectl proxy`
4. Open the dashboard and login

##### Observed result

![screen shot 2018-05-30 at 08 51 42](https://user-images.githubusercontent.com/478564/40703817-b7874aba-63e6-11e8-8792-ac3a34b742bc.png)

##### Expected result

No permission issue.

##### Comments

A workaround is to run the following command :

```
kubectl create clusterrolebinding --user system:serviceaccount:default:default default-sa-admin --clusterrole cluster-admin
```

But it sounds incorrect, plus the dashboard YAML file is already creating a special role and rolebinding which should be fixed.

**Comment by floreks** [comment]
It creates a role with minimal privileges required to start the application. Everything works as expected. Log in with user that is allowed to list resources and this warnings will be gone. There are more information about default setup in the documentation.

**Comment by Enelar** [comment]
@floreks i've been fighting against it for 3 hours straight, even suggested workaround won't help. if you care pre-installing dashboard, you have to create user with access to it. otherwise it doesn't make sense. for what purposes it were pre-instailed?

feels like you're teamed up with 'learn kubernetes for 99.99$ courses'. there no warning sign, and its hard to predict what actually is 'expected' by dev team. :(

**Comment by floreks** [comment]
> i've been fighting against it for 3 hours straight, even suggested workaround won't help. if you care pre-installing dashboard, you have to create user with access to it. otherwise it doesn't make sense. for what purposes it were pre-instailed?

Are WE pre-installing Dashboard anywhere? I honestly don't think that we are. We are providing a FREE tool for the users and it is up to them how they want to use it. Most K8S providers enable Dashboard by default but it is their decision to do so, not ours.

Please, ask yourself that: Was your comment in any way helpful to others and us (maintainers team)? Did it contain any constructive criticism? Did you point out what was not understandable in our documentation so we could improve it? Did you describe your issue in any way other than saying "I tried to do something (I honestly have no idea what) for some time and something didn't work"?

> feels like you're teamed up with 'learn kubernetes for 99.99$ courses'. there no warning sign, and its hard to predict what actually is 'expected' by dev team. :(

Besides accusing us of "teaming up" with some paid kubernetes tutorials/courses you didn't actually try to help us improve what you think could be improved.  Next time please consider those few things and dedicate some time to provide us a detailed description of the steps you have taken, your issue, what you think should be the result and maybe how you think we could improve the current state. Just like we are dedicating much of our free time to create, support and maintain something that could be useful for others.
