### ISSUE TITLE
dashborad  connection closed

### ISSUE THREAD

**Issue by xuejipeng** [kubernetes/dashboard#3068]
##### Environment

```
Dashboard version: v1.8.3
Kubernetes version: v1.8.6
Operating system: 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

##### Steps to reproduce
Open  CLI from the browser , feel free to enter commands, CLI crashes after ten or twenty or thirty commands

##### Comments
![image](https://user-images.githubusercontent.com/18901031/40767809-2eb494f8-64e6-11e8-8840-45c5485891bb.png)

**Comment by xuejipeng** [comment]
sorry ,it's a problem with ingress, can be close this issue

**Comment by qianyong-2005** [comment]
I have the same problem,how to solve this ?

**Comment by xuejipeng** [comment]
@qianyong-2005  There may be a problem with the configuration of the timeout on the ingress。

**Comment by qianyong-2005** [comment]
@xuejipeng I add follow three parameter on dashboard ing, problem continue; how do you configure?
nginx.ingress.kubernetes.io/proxy-connect-timeout：“600”
nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
nginx.ingress.kubernetes.io/proxy-read-timeout: "600"

**Comment by qianyong-2005** [comment]
@xuejipeng  configure timeout time < 30s is valid,  and > 35s is not invalid 
  proxy-read-timeout: "20"
  proxy-send-timeout: "20"
  worker-shutdown-timeout: "20"

**Comment by xuejipeng** [comment]
@qianyong-2005 
"vaild" mean to solve your problem? This problem doesn't seem to be common. i don't understand why the time is short, but it's good, and it feels like the problem isn't here
I think you can test these three parameters alone to see which one is affecting it.
