### ISSUE TITLE
Unknown reference kind TFJob

### ISSUE THREAD

**Issue by sbisl** [kubernetes/dashboard#3070]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Unknown Server Error (500):
```
Unknown reference kind TFJob

```

##### Comments

I've deployed a Kubernetes cluster on AWS and deployed Kubeflow. I'm running a tensorflow job and trying to access the pods from the dashboard which is throwing this error. 

I'm also trying to deploy a tensorflow job from the dashboard and it doesn't execute.

**Comment by floreks** [comment]
Probably you are using unsupported k8s version.

**Comment by Lothiraldan** [comment]
It's likely related to https://github.com/kubeflow/kubeflow, I got the same error after installed it.

**Comment by sbisl** [comment]
I've deployed Kubernetes (k8s 1.9) cluster in AWS (GPU based) and deployed kubeflow to run Tensorflow jobs. Using CLI tool `ksonnet` to deploy Tensorflow jobs. The worker pod and ps pods comes up on Kubernetes UI. I should be able to login to the pod shell. But it throws the above error.

@Lothiraldan Do you mean the GitHub Token? Does it resolve the issue?
