### ISSUE TITLE
Unable to reach internal DNS

### ISSUE THREAD

**Issue by kbaegis** [kubernetes/dashboard#3078]
##### Environment
Using kubernetes-dashboard-amd64:v1.8.3

```
Dashboard version: v1.8.3
Kubernetes version: v1.10.2
Operating system: Gentoo
Node.js version:
Go version: kubectl running on go1.10.2 darwin/amd64
```

##### Steps to reproduce
1) kubectl create secret generic kubernetes-dashboard-certs --from-file <directory> -n kube-system
2) kubectl create -f kubernetes-dashboard.yaml

##### Observed result
Pod DNS failure specific to kubernetes-dashboard (other pods are working fine with DNS).

```
2018/06/04 18:06:23 Starting overwatch
2018/06/04 18:06:23 Using apiserver-host location: https://services.lab:6443
2018/06/04 18:06:23 Skipping in-cluster config
2018/06/04 18:06:23 Using random key for csrf signing
2018/06/04 18:06:23 No request provided. Skipping authorization
2018/06/04 18:06:33 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://services.lab:6443/version: dial tcp: lookup services.lab on 172.21.255.254:53: read udp 10.0.0.6:33662->172.21.255.254:53: i/o timeout
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ
```

##### Expected result
A functional container

##### Comments
Don't know why it's timing out on port 53. Again, other pods are up and functional working with internal DNS.

**Comment by kbaegis** [comment]
Fixed. It was indeed a cluster routing issue.

**Comment by floreks** [comment]
How did you check that other pods are working fine with DNS? Most pods are not like Dashboard. They are not trying to directly connect to API server, instead they are just doing their job without even knowing that they are running inside the cluster.

**Comment by maciaszczykm** [comment]
Closing as stale.

/close
