### ISSUE TITLE
cronjob page to allow the creation of jobs from cronjobs

### ISSUE THREAD

**Issue by CharlesCara** [kubernetes/dashboard#3080]
The dashboard support for cronjobs is a welcome addition, but please can you enhance the cronjob page to allow the creation of jobs from cronjobs.  

This would be  implemention/replication of the kubectl command: 
`kubectl create job jobname --from=cronjob\cjname`

Also could allow cronjobs be disabled/enabled in the dashboard

**Comment by maciaszczykm** [comment]
It is already done. Tested in on HEAD. It will be also part of ng migration.

/close
