### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by michaelgeorgeattard** [kubernetes/dashboard#3094]
Hi,

Seeing that `Basic Access Authentication` is enabled for the dashboard, with a strong enough password:

Is it necessary/recommended to provide minimal role rights to the dashboard, and "log in" with a more privileged serviceaccount's token?

**Comment by floreks** [comment]
Dashboard already has minimal privileges required to only make it work. They will be restricted even more soon. I'd recommend to always use login functionality or configure reverse proxy that will handle auth to Dashboard. Using privileged service account is one option and it is a good one also.
