### ISSUE TITLE
exec pod show connection closed

### ISSUE THREAD

**Issue by dennis-xie** [kubernetes/dashboard#3100]
##### Environment

```
Dashboard version: 1.8.3
Kubernetes version: 1.10.2
Operating system:  centos7.4
Node.js version:
Go version:
```

##### Steps to reproduce
1、exec into a pod 
2、dashboard show connections closed

##### Observed result
dashboard log

2018/06/19 10:40:40 Getting application global configuration
2018/06/19 10:40:40 Application configuration {"serverTime":1529404840760}
2018/06/19 10:40:41 [2018-06-19T10:40:41Z] Incoming HTTP/2.0 GET /api/v1/rbac/status request from 172.30.50.0:33744: {}
2018/06/19 10:40:41 [2018-06-19T10:40:41Z] Outcoming response to 172.30.50.0:33744 with 200 status code
2018/06/19 10:40:41 http2: server: error reading preface from client 172.30.50.0:33988: bogus greeting "GET /api/sockjs/809/1xyu"
2018/06/19 10:40:41 handleTerminalSession: can't Recv: sockjs: session not in open state

**Comment by cheld** [comment]
Does pod contain shell? Does it work with kubectl exec?

**Comment by miramar-labs** [comment]
i'm seeing the same thing and it does work via kubectl exec for me

**Comment by floreks** [comment]
Compatibility with Kubernetes 1.9+ is not guaranteed. Dashboard and client-go have to be updated first. Most probably there were some changes in k8s api and that is why it does not work.

**Comment by zhaoyibeijing** [comment]
@floreks  

hi，I got the same problem，Is there any progress in this issue?。when I run bash shell command in dashboard terminal:
`while true
do
  echo 1;
done
`
Dashboard version:v1.7.1
Kubernetes version:v1.7.16

**Comment by shfpflyawei** [comment]
hello, I met this issue too, I'm using dashboard :v1.8.3  and kubernetes  1.10.1

**Comment by xinghan666** [comment]
any progress for this problem?
