### ISSUE TITLE
Not able to access the dashboard when the dashboard pod is created in another node in the cluster other than master node

### ISSUE THREAD

**Issue by sunnymeska** [kubernetes/dashboard#3104]
##### Environment
i am using kubernets cluster (non-production purpose) by setting up 3 ubuntu 16.04 os using oracle vm.

```
Dashboard version:v1.8.3
Kubernetes version:v1.10.4
Operating system:ubuntu
```

##### Steps to reproduce
Setup kubernetes claster (1 master 2 worker)in oracle VM deploy dashboard in master such that the pod(dashbaord) is created in a node other than the master 

##### Observed result

Error: 'dial tcp 10.100.22.2:9090: i/o timeout'
Trying to reach: 'http://10.100.22.2:9090/'

##### Expected result
Dashboard UI should come
##### Comments
If i Deploy the dashbaord before joining other nodes then the UI comes without any problem i think it has to do something with the network

**Comment by jeefy** [comment]
1) What CNI driver are you using?
2) Are there other applications you're running successfully?
3) If you are able, could you give the output of `kubectl -n kube-system get pods` ? That might help me debug a little more. :)

Thanks!

**Comment by floreks** [comment]
Definitely looks like networking issue. Dashboard needs connection to the apiserver and it is usually part of the masted node.

**Comment by sunnymeska** [comment]
Hi , Found the problem it was a Network issue thanks!

On Tue, Jul 24, 2018 at 12:30 AM, Sebastian Florek <notifications@github.com

**Comment by sunnymeska** [comment]
please close it asap!
