### ISSUE TITLE
Specify to install Java JDK in docs

### ISSUE THREAD

**Issue by ericandrewlewis** [kubernetes/dashboard#311]
I never use Java and found figuring out what to install confusing. Maybe we can specify to install the Java JDK rather than [whatever this is](https://www.java.com/en/download/).

**Comment by luxas** [comment]
A docker dev env will soon be merged: #279 
That's the easiest way of running and building `dashboard`

**Comment by bryk** [comment]
I've clarified this in the documentation. But as @luxas mentioned, you can now `build/run-gulp-in-docker.sh serve` to serve the dev version of UI.

**Comment by bryk** [comment]
Fixed?
