### ISSUE TITLE
Rbac kube-proxy dashboard

### ISSUE THREAD

**Issue by bhack** [kubernetes/dashboard#3115]
Can we document what kind rolebinding we need to create to give an user the access to the dashboard trought the proxy?
As in the `Readme.md` is still the default access to the dashboard and Rbac now is enabled by default in K8s.

I've found [this reply](https://stackoverflow.com/a/47796023) and probably we could put something like this in the docs.

**Comment by jeefy** [comment]
/assign @jimangel 

I do think we should put a small blurb in the base README when it comes to installing and RBAC.

@jimangel You mind taking this on? I think being able to link to https://github.com/kubernetes/dashboard/blob/master/src/deploy/recommended/kubernetes-dashboard.yaml#L43 and saying "default install has minimal permissions" is a good start, especially as we address more security concerns. :)

Thanks!

**Comment by jimangel** [comment]
The README already had a blurb in there about minimal RBAC, but I will submit a PR to beef it up a bit.
