### ISSUE TITLE
Does it is possible to check version and install or not

### ISSUE THREAD

**Issue by jhaoheng** [kubernetes/dashboard#3116]
Hi 
Does it is possible to check version?
and get install status, just like `minikube addons list`

**Comment by cheld** [comment]
Version should printed in the about dialog. Also the commit-sha. 

I don't know minikube addons list. Could you paste the output?

**Comment by jhaoheng** [comment]
Hi @cheld 
Thanks for your reply.
Maybe i should change my word.
I mean , Does possible to check "Dashboard" installed or not by kubectl command?

**Comment by maciaszczykm** [comment]
@jhaoheng There is no way to be 100% sure as it can be installed using add-on manager or deployed as a resource to namespace of your choice. You can search for `kubernetes-dahsboard` deployment inside `kube-system` namespace or look at installed add-ons, but there is no single step.

**Comment by jhaoheng** [comment]
ok, got it.
