### ISSUE TITLE
External link not displayed without load balance

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#313]
Prerequisites:
1. Run local cluster
2. Open Dashboard

Steps:

1. Open deploy dialog
2. Enter data
3. click expose service externally
4. Click deploy

=> no external link is shown

The current implementation expects a load-balancer. However, load-balancer is optional and it should work without. A link with nodeport should be displayed in case load balancer is not available.

I would suggest the following implementation:

--- Expose service externally not checked: ClusterIP should be used. No nodeport created. (current implementation creates nodeport)

--- Expose service externally checked: Either nodeport or loadbalancer. Do we know what the platform supports? If not, I would suggest to create loadbalancer and show nodeport until the loadbalancer ip is returned.

Needs to be fixed before release

**Comment by bryk** [comment]
> --- Expose service externally not checked: ClusterIP should be used. No nodeport created. (current implementation creates nodeport)

LGTM

**Comment by bryk** [comment]
> --- Expose service externally checked: Either nodeport or loadbalancer. Do we know what the platform supports? If not, I would suggest to create loadbalancer and show nodeport until the loadbalancer ip is returned.

If we can check it during creation time, then LGTM. But this needs investigation?

**Comment by bryk** [comment]
Can anyone take this?

**Comment by cheld** [comment]
@floreks @maciaszczykm @batikanu Can anyone have a look?

**Comment by maciaszczykm** [comment]
I'll check it.

**Comment by maciaszczykm** [comment]
This issue is fixed now, #369 is continuation of it.

**Comment by maciaszczykm** [comment]
@cheld I believe it's already fixed. Can we close it?

**Comment by cheld** [comment]
Yes we can close
