### ISSUE TITLE
Dashboard not working on CentOS 7 AWS EC2 instance

### ISSUE THREAD

**Issue by hrishikeshgjoshi** [kubernetes/dashboard#3130]
##### Environment

```
Dashboard version:
Kubernetes version: 1.11
Operating system: CentOS 7 
Node.js version:
Go version:
Network Plugin: weave net 
```

##### Steps to reproduce
Followed instruction from https://github.com/kubernetes/dashboard/wiki/Installation page and
https://github.com/kubernetes/dashboard/wiki/Accessing-dashboard

kubects get events --namespace=kube-system 
Showing following message
Dashboard POD is not running container.
LAST SEEN   FIRST SEEN   COUNT     NAME                                                    KIND      SUBOBJECT   TYPE      REASON                   SOURCE                                 MESSAGE
3m          1d           559       kubernetes-dashboard-6948bdb78-9pjq4.153dee880baaccdb   Pod                   Warning   FailedCreatePodSandBox   kubelet, ip-10-76-67-41.ec2.internal   Failed create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded

##### Observed result
Dashboard is not accessible

##### Expected result
Dashboard POD should be running with all required containers.

**Comment by jimangel** [comment]
This looks like you might have some issues with kubelet. Did you by chance use kubeadm to install? It's possibly related to this issue: https://github.com/kubernetes/kubeadm/issues/578

**Comment by floreks** [comment]
Definitely not a Dashboard issue. Looks like docker/k8s issue.
