### ISSUE TITLE
Add nodeSelector architecture to prevent amd64 versions getting deployed to arm nodes

### ISSUE THREAD

**Issue by drake7707** [kubernetes/dashboard#3137]
I have a mixed architecture cluster consisting of both amd64 and arm nodes. Currently when deploying the dashboard it does not check the architecture label and often deploys the pod to a node with the wrong architecture.

Please add

```
      nodeSelector:
        beta.kubernetes.io/arch: amd64
```
and
```
      nodeSelector:
        beta.kubernetes.io/arch: arm
```
to the deployment yaml so the pod can never be deployed to a node with a different architecture than the image.

(or alternatively, provide a multi-arch image manifest to use in the deployment)

##### Environment
Mixed architecture cluster consisting of both arm and amd64 nodes

```
Kubernetes version: v1.11.0
Operating system: Linux (debian) for the amd64 nodes and Raspbian for the arm nodes
```

##### Steps to reproduce
Set up a mixed architecture cluster, deploy the amd64 version of the dashboard. if it lands on an arm node it will fail to start

##### Observed result
Dashboard amd64 fails when deployed to arm.

##### Expected result
Deployment should have selected an amd64 node for the dashboard to deploy on

**Comment by jeefy** [comment]
I think it would be better to have a multi-arch Dashboard container?

Thoughts? /cc @bryk 

(FYI I'd be willing to take that on)

**Comment by drake7707** [comment]
@jeefy Yeah that would be the best future proof option.

**Comment by floreks** [comment]
We've already had a proposal to use multi-arch image and deployment in https://github.com/kubernetes/dashboard/issues/2811. If someone is willing to work on this then it would be great.

**Comment by jeefy** [comment]
@floreks Dibs! :) I was already looking to take that on.

**Comment by floreks** [comment]
We support multi-arch docker image now.

/close
