### ISSUE TITLE
Feature Request: UI customizability

### ISSUE THREAD

**Issue by siddharthlatest** [kubernetes/dashboard#3140]
##### Environment

```
Dashboard version: 1.8.3
Kubernetes version: 1.9.6
Operating system: Not relevant
Node.js version: Not relevant
Go version: Not relevant
```

##### Steps to reproduce

This is a question about the UI, not a bug in a behavior. What is the best way to customize the dashboard UI (e.g. hide the top toolbars) elements?

![](https://i.imgur.com/QmINH6m.png)
**Image:** A quick hack to show what I am looking to do

My use-case is embedding the dashboard inside an existing UI project (to provide insights into what's going under the hood).

##### Observed result

A current alternative I can see is to fork the project.

##### Expected result

I would like to hear if this is possible by any less intrusive means, e.g. some query string param like `?toolbar=false` would be ideal for an embed use-case.

##### Comments

I am open to possibly taking a stab at doing this if it can be a useful feature in general. Would like some pointers on where to start.

**Comment by floreks** [comment]
Dashboard was never planned to be written in a way to expose some components to the outside or to be used as an iframe. Unfortunately, there is no option to customize it this way. The only way would be to fork it and implement such logic on your own.
