### ISSUE TITLE
Missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by aojea** [kubernetes/dashboard#3145]
All K8s subrepositories should have a CONTRIBUTING.md file, which at the minimum should point to https://github.com/kubernetes/community/blob/master/contributors/guide/README.md. Care should be taken that all information is in sync with the contributor guide.

Subrepositories may also have contributing guidelines specific to that repository. They should be explicitly documented and explained in the CONTRIBUTING.md

Ref:  https://github.com/kubernetes/community/issues/1832

**Comment by jeefy** [comment]
Heya @aojea! 

I noticed this too and added an agenda item to [this week's call](https://docs.google.com/document/d/1PwHFvqiShLIq8ZpoXvE3dSUnOv1ts5BTtZ7aATuKd-E/edit)

A lot of our docs are in the [wiki](https://github.com/kubernetes/dashboard/wiki) portion of our repo but we do need to get more in line with the rest of the community.

Thanks for raising an issue on this!

**Comment by maciaszczykm** [comment]
Hi @aojea, you might not notice but we already have one:
https://github.com/kubernetes/dashboard/blob/master/.github/CONTRIBUTING.md

Perhaps it needs an update though.

**Comment by aojea** [comment]
@maciaszczykm ups sorry, I was looking for the file in the parent folder only. 
@guineveresaenger @chris-sort can you chime in?  this repo was referenced in your list  too :)
