### ISSUE TITLE
Proposal: OAuth2 support

### ISSUE THREAD

**Issue by SerialVelocity** [kubernetes/dashboard#3148]
Hi Kubernetes dashboard team,

We are running Kubernetes backed by an OAuth2 provider and require audit logging for all requests going through the dashboard.

Would you be willing to accept a PR to add first-class OAuth2 support to the dashboard?

This would be running the OAuth2 workflow with the `authorization_code` grant type. The bearer token that gets returned would be used for connecting to the kubernetes apiserver.

To do this, I would add flags for:
 - Client ID
 - Client Secret (I would expect to be able to pass this in by filename/environment variable)
 - OAuth URL
 - Redirect URL (Since you can have a different external URL to internal URL)

I wouldn't be adding explicit support for Google OAuth, Github OAuth, etc but they may be implicitly supported if Kubernetes is set up to do the authorization.

Best,
Ben

### Related tickets

#964
#2353
#2621
#2630

**Comment by SerialVelocity** [comment]
@jeefy Sorry for the delay in responding here. Unfortunately we have deprioritised this internally so I will not be implementing this soon.

**Comment by jeefy** [comment]
That's fine. The issue will remain open as it is something we need to address in the future. :) Thanks!

**Comment by floreks** [comment]
Will be tracked from #2353 
/close
