### ISSUE TITLE
Unknown reference kind TFJob

### ISSUE THREAD

**Issue by veliborfrobas** [kubernetes/dashboard#3158]
##### Steps to reproduce
On my local kubernetes with kubeflow installed (using deploy.sh) I started Run the TfCnn example:
https://www.kubeflow.org/docs/about/user_guide/
Everything works ok but after approx. 10minutes I got 
mycnnjob-worker-0                           0/1       Error     0          12m
and in dashboard Subject message.

##### Environment
```
Installation method: minikube and kubectl (minikube version: v0.28.1)
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Dashboard Version: v1.8.1
```
##### Observed result
Dashboard reported Internal Server Error (500):
```
Unknown reference kind TFJob
```
##### Comments
I am a Sysadmin try to figure out working environment for our developers. If I continue like this... It won't be working.

**Comment by floreks** [comment]
Closing in favor of #2493.
