### ISSUE TITLE
Service metrics not showing in Kubernetes Dashboard

### ISSUE THREAD

**Issue by zhughes3** [kubernetes/dashboard#3165]
Hey Guys,

In Kubernetes, I have a cluster w/ a Stateful Set, a NodePort and a GCE Ingress.

After some initial configuration debugging, I was able to get the service running and it is available on the Internet. My only problem now is with the Kubernetes dashboard for the service. You can see a picture below:

![Here is our image](https://i.imgur.com/MYKi9R2.png)

As you can see above, none of the metrics from Stackdriver are showing up.

##### Steps to reproduce
1. Deploy cluster and services.
2. Log into GCP.
3. Go to Kubernetes Engine.
4. Click on services.
5. Click on service you are looking to monitor.
6. View dashboard of metrics that are monitored by StackDriver.

##### Observed result
Service metrics are not showing up.

##### Expected result
I expect to see metrics for CPU, Memory and Disk Usage.

##### Comments
Also, please check out the output of `gcloud container clusters describe <CLUSTER_NAME> --zone us-east1-b` if it would be helpful. EDIT: took this down, but let me know if it would be helpful and I can send it to you.

**Comment by floreks** [comment]
This is not kubernetes dashboard.
