### ISSUE TITLE
Dashboard not realizing context switch

### ISSUE THREAD

**Issue by Mechtecs** [kubernetes/dashboard#3169]
##### Steps to reproduce:
* kubectl proxy
* open the dashboard & login
* click some buttons
* stop the proxy, use another cluster context, start the proxy
* click a button ==> *BOOM!*

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by floreks** [comment]
This is the "improve error handling" part of #2353.
