### ISSUE TITLE
Delete daemon set doesn't work

### ISSUE THREAD

**Issue by AndersonChoi** [kubernetes/dashboard#3171]
##### Steps to reproduce
1. daemon set list
2. filebeat daemonset information
3. delete button clicked

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Unknown Server Error (504):
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.13.12</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

##### Comments

Delete daemon set doesn't work
also kubectl command doesn't work too.
---
> $ kubectl delete daemonset filebeat --namespace=kube-system
> error: timed out waiting for the condition

**Comment by floreks** [comment]
If even kubectl doesn't work then this is probably a cluster issue, not directly related to Dashboard.

**Comment by AndersonChoi** [comment]
@jeefy Thank you for the comment.
I found a cluster issue. After the kubernetes restarts, the dashboard was operate normally.
