### ISSUE TITLE
Design dark theme color palette

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/dashboard#3176]
## Background
As part of the Angular migration (#3152), a dark theme is being introduced for Dashboard. This is all custom CSS in one file, and will make it easy to customize Dashboard's color scheme – a feature requested in #1657. 
![image](https://user-images.githubusercontent.com/5114858/43277015-93cf82f2-90bb-11e8-9c12-769a9b59c404.png)
A possible use case for this custom theming  would be to distinguish  dev / staging / prod environments by color-coding them.

Relevant issues:
*    #2618 
*    #2417 
*    #1938 

## Goal
The current dark theme has not had design attention, and as a result 1) Is not aligned with the Kubernetes brand, and 2) Has not been assessed in terms of color connotation (e.g. orange = warning) or accessibility (e.g. contrast). We would like to address these with a comprehensive color palette redesign that identifies key color(s) that can be swapped out to distinguish between Dashboard instances.

**Comment by danielromlein** [comment]
@maciaszczykm @konryd PTAL and see if this makes sense to you.

**Comment by danielromlein** [comment]
@Stritty want to post here anything you think is ready for feedback?

**Comment by maciaszczykm** [comment]
@danielromlein @stritty Do you have any updates? Migration is finally going forward so it would be nice to change this before release.

**Comment by stritt** [comment]
Finally got the angular dev build working thanks @maciaszczykm  I will have updates for this shortly

**Comment by maciaszczykm** [comment]
Any update?

**Comment by stritt** [comment]
![image](https://user-images.githubusercontent.com/3777243/49956481-44c33b00-fed3-11e8-93bf-0cb57c73b5e3.png)

Updated styling to be on brand and WCAG accessible, you can see hover color of a card on the 'hello' cron job. Let me know what you guys think and I will go in and make any necessary changes

**Comment by danielromlein** [comment]
I think this is looking awesome @stritt. Taking a cue from Mojave, I think if the top bar were lighter it would help the blue bar across look less jarring:
![image](https://user-images.githubusercontent.com/5114858/50659098-5dfa5d00-0f50-11e9-8064-1d53fdf1d439.png)

Right now I feel like the two dark sections are sort of isolated and my eye is distracted by the top bar. 
![image](https://user-images.githubusercontent.com/5114858/50659075-415e2500-0f50-11e9-8820-2ca1dfb94ec4.png)
