### ISSUE TITLE
kubernetes 1.11.x no graphs 

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/dashboard#3177]
##### Environment
```
Dashboard version: 1.8.3
Kubernetes version:1.11.1
Operating system:centos 7.5
Node.js version: 
Go version:
```

##### Steps to reproduce
on version 1.11.x  dont have graphics ( worked on 1.10.x )
10255 port is closed

##### Comments
<what are the solutions ?

**Comment by floreks** [comment]
K8S 1.10+ is not officially supported yet so we can not guarantee that everything will work. You need to wait for the next release.
