### ISSUE TITLE
Remove "Overview" button when viewing individual namespace

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/dashboard#3178]
When viewing an individual namespace in Dashboard, there appears an _Overview_ button, which takes a user back up a level to the namespaces list page. 
![overview-button](https://user-images.githubusercontent.com/5114858/43277812-11086bf6-90be-11e8-8a32-fd87671a78c3.png)
This is the only place such a button exists in Dashboard (as far as I could tell), and is a confusing one-off UI affordance. If a user wants to go back to the namespaces list, the intended interaction is that they navigate using browser _back_ or using the breadcrumb.
![image](https://user-images.githubusercontent.com/5114858/43278088-d9bcb764-90be-11e8-8b04-d85f83496ea7.png)
The space where the _Overview_ button is should be reserved for actions relating to the object being viewed.

**Comment by maciaszczykm** [comment]
It should redirect to overview and switch namespace. In your case it should be overview of default-system namespace.

**Comment by danielromlein** [comment]
@maciaszczykm 
>It should redirect to overview and switch namespace. In your case it should be overview of default-system namespace.

Sorry I don't follow: could you clarify what the expected behavior is?

**Comment by maciaszczykm** [comment]
> Sorry I don't follow: could you clarify what the expected behavior is? Do you agree the Overview button should be removed?

 No, I think it shouldn't be removed, but it should work different than you have described. It should redirect to overview of currently viewed namespace.

**Comment by danielromlein** [comment]
> It should redirect to overview of currently viewed namespace. 

But isn't the screen in the first screenshot above the currently viewed namespace? Where else would the user be directed?

**Comment by maciaszczykm** [comment]
No, it's not. You have selected `kube-system` namespace in the picker on the left and you are viewing details of `default-system` namespace.

After clicking on the button you should be redirected to an overview page with `default-system` namespace selected.

**Comment by floreks** [comment]
Closing as stale.
/close
