### ISSUE TITLE
Backend test does not clean up after execution

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#318]
During writing go tests I've encountered that this test:

https://github.com/kubernetes/dashboard/blob/master/src/test/backend/deploy_test.go#L163

is creating namespace `development` during execution. Second execution of test results in failure as namespace already exists and is not deleted afterwards.

**Comment by bryk** [comment]
Ouch, that's true. The test talks to real local cluster. 

@batikanu Can you fix this?

**Comment by batikanu** [comment]
Ok I will check it

**Comment by batikanu** [comment]
It is solved with #321
