### ISSUE TITLE
K8s dashboard failing to open

### ISSUE THREAD

**Issue by as428y** [kubernetes/dashboard#3184]
##### Steps to reproduce

1. Navigate to https://zltv3748.vci.att.com 
2. Press on Dashboard
expected Dashboard opened for default name space,
actually getting bellow error message

##### Environment
```
Installation method: Do not know 
Kubernetes version: Do not know
Dashboard version: v1.7.1
Commit: b44f7cc5fde4dbe2a884b1e32a2b363d8031e4ca
```

##### Observed result
Dashboard reported Unknown Server Error (500):
```
Get https://10.233.0.1:443/api/v1/namespaces/default/configmaps: dial tcp 10.233.0.1:443: getsockopt: connection refused

```

##### Comments
Access was working fine until recently started to fail

**Comment by floreks** [comment]
1. Old Dashboard version (update it first).
2. No information on how Dashboard was installed in the cluster and how it is configured.
3. Steps to reproduce need to be described in a way that allows us to actually REPRODUCE the issue. Provided steps are wrong and environment specific. They need to be more general.
4. Missing K8S version.
5. Connection refused issue are generally not a Dashboard issue but a cluster issue. Probably cluster networking is not working properly.
