### ISSUE TITLE
 kubernetes-dashboard Error while initializing connection to Kubernetes apiserver for V1.11

### ISSUE THREAD

**Issue by Scofields** [kubernetes/dashboard#3186]
##### Environment

```
Dashboard version: kubernetes-dashboard-amd64:v1.8.3
Kubernetes version: 1.11
Operating system: centos7.3
Node.js version:
Go version:
```

##### Steps to reproduce
` 

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
`

`

        args:
          - --auto-generate-certificates
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
          - --apiserver-host=https://10.26.31.134:6443
`

##### Observed result

`

2018/07/31 10:27:59 Using apiserver-host location: https://10.26.31.134:6443
2018/07/31 10:27:59 Skipping in-cluster config
2018/07/31 10:27:59 Using random key for csrf signing
2018/07/31 10:27:59 No request provided. Skipping authorization
2018/07/31 10:27:59 Starting overwatch
2018/07/31 10:28:29 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.26.31.134:6443/version: dial tcp 10.26.31.134:6443: i/o timeout
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ
`

##### Comments
 but I can access apiserver:  https://10.26.31.134:6443

**Comment by floreks** [comment]
1. Accessing the API server from the outside does not mean that container will be able to access it. Networking has to be configured properly to allow containers to access the internet or local machines.
2. K8S 1.11 is not yet officially supported and it is also possible that Dashboard won't work with it, however it is most likely cluster configuration issue in this case.

**Comment by lwx294821** [comment]
The same issue happened in my environment. Is there one solution .(K8s v1.12.5)
