### ISSUE TITLE
Expired token should be HTTP 401, not HTTP 500

### ISSUE THREAD

**Issue by mxey** [kubernetes/dashboard#3189]
##### Environment

```
Dashboard version: v1.8.3
Kubernetes version: v1.11.1
Operating system: CentOS Linux release 7.5.1804 (Core)
```

##### Steps to reproduce
1. Log in to dashboard and keep the page open
2. Wait/let token expire
3. Refresh page

##### Observed result

in log:

```
2018/08/01 13:18:32 MSG_TOKEN_EXPIRED_ERROR
2018/08/01 13:18:32 [2018-08-01T13:18:32Z] Outcoming response to 10.244.18.212:38208 with 500 status code
```

##### Expected result

in log:

```
2018/08/01 13:18:32 MSG_TOKEN_EXPIRED_ERROR
2018/08/01 13:18:32 [2018-08-01T13:18:32Z] Outcoming response to 10.244.18.212:38208 with 401 status code
```

**Comment by jeefy** [comment]
/kind bug
/assign

I'll pick this one up! I see where the problem is and it should be fairly straight forward (famous last words) :)
