### ISSUE TITLE
Add missing flag to the `gulp serve` command and update Wikis

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3193]
https://github.com/kubernetes/dashboard/pull/3180#issuecomment-410077009

**Comment by floreks** [comment]
@jeefy I have opened the wiki pages for contributors. You should be able to edit it now. We will monitor the changes and see how it works out.

**Comment by jeefy** [comment]
Awesome, thank you! I've since updated the wiki. 

If I missed anything, feel free to re-open this. :)

/close
