### ISSUE TITLE
503 error when trying to access dashboard

### ISSUE THREAD

**Issue by shoaibechidna** [kubernetes/dashboard#3199]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Error: 'ssh: rejected: connect failed (Connection refused)'
Trying to reach: 'https://10.140.63.6:8443/api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp'
```

**Comment by jeefy** [comment]
/triage needs-information
/assign

Please re-open this issue once you have more information (Way to reproduce, Kubernetes version and installation method.)

I don't think this is a dashboard-specific issue either. 

/close
