### ISSUE TITLE
node don't have enough space

### ISSUE THREAD

**Issue by xiaxingtao** [kubernetes/dashboard#3200]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.7.1
Commit: b44f7cc5fde4dbe2a884b1e32a2b363d8031e4ca
```

##### Observed result
Dashboard reported 未知服务器错误 (504):
```
the server cannot complete the requested operation at this time, try again later (get pods)

```

**Comment by jeefy** [comment]
This is likely a cluster issue and not a dashboard-specific issue.

Please re-open this issue when you have more information (steps to recreate, Kubernetes version) and can confirm it is dashboard-specific.

/triage needs-information
/assign
