### ISSUE TITLE
Way to access Dashboard running in AWS master node from my local Browser

### ISSUE THREAD

**Issue by rajeevghosh2000** [kubernetes/dashboard#3205]
##### Environment

```
Its a related to "Help/Best practice" 
Kubernetes Cluster is running in AWS. and its is installed using kubeadm. 
Dashboard version: v1.8.3
Kubernetes version: v1.11
Operating system: CentOS
Node.js version: NA
Go version: NA
```

##### Steps to reproduce

1. Installed Kubernetes on 1 Master and 3 Slave EC2 instance using kubeadm. Used Canal add-on.
2. Installed certificates using openssl (https://github.com/kubernetes/dashboard/wiki/Certificate-management)
3. Created dashboard POD:
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
4. Created a Service account and Cluster Role Binding (https://github.com/kubernetes/dashboard/wiki/Creating-sample-user)
5. Ran in Master Node: kubectl proxy --address 0.0.0.0 --accept-hosts '.*'
6. in the Local Browser entered : 
http://<Master node Public IP>:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login

##### Observed result

 In the DashBoard GUI If I enter either Bearer token or Kubeconfig , nothing happens (And understood this is as expected)
And if In the GUI, when I click on "skip", its with default Service Account which has all the full admin privileges. So anyone can use my Cluster if they know my Public IP
##### Comments

Please help me whats the best practice to access the DashBoard GUI from my local Browser considering only authorised users can access the GUI.
I went over (https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above) and understood:
1. Can't use kubectl since its only accessible locally (from the machine that started it)
2.NodePort: its only Development environments.
3. API Server: Kubernetes API server is exposed and accessible from outside. This is not possible. I think its again a security issue. Also, my API server is exposed in Private IP. Is it possible we can expose it outside world ? won't it be security problem?
4.  Ingress : Not sure how to do this ?

Please help to clarify whats the best way to access the Dashboard GUI

**Comment by vijaycjadhav** [comment]
root@ip-172-31-23-165:~# netstat -plan |grep 8001
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      24277/kubectl
tcp        0      0 127.0.0.1:52960         127.0.0.1:8001          TIME_WAIT   -
root@ip-172-31-23-165:~#

It is showing the port 8001 is bind with localhost - hence in EC2 we need to write iptables to do so.

**Comment by vijaycjadhav** [comment]
You may use CURL or elink in terminal like -
root@ip-172-31-23-165:~# curl 127.0.0.1:8001
