### ISSUE TITLE
Is the lastest version of dashboard compatibility with Kubernetes 1.11.2?

### ISSUE THREAD

**Issue by TreHack** [kubernetes/dashboard#3206]
##### Environment

```
Dashboard version: 1.8.3
Kubernetes version: 1.11.2
Operating system: ubantu16.04
Node.js version:
Go version:
```

**Comment by maciaszczykm** [comment]
Not yet, at least not officially supported. We are in the process of making new release, it improves compatibility with newer versions. Check #3203 for more information.

/assign
/close
