### ISSUE TITLE
Prepending whitespace in token while login doesn't result in "Authentication failed" but also not in a valid login.

### ISSUE THREAD

**Issue by cduch** [kubernetes/dashboard#3209]
##### Environment
SUSE CaaS Platform 3 running Kubernetes Dashboard deployed via helm (kubernetes-dashboard-0.6.8)

```
Dashboard version: helm chart: kubernetes-dashboard-0.6.8, image: kubernetes-dashboard-amd64:v1.8.3
Kubernetes version: v1.9.8
Operating system: SUSE Micro OS
Node.js version: -
Go version: -
```

##### Steps to reproduce
Try to login into kubernetes dashboard and copy and paste a valid token with an additional whitespace prepended.

##### Observed result
Login will succeed but the kubernetes dashboard will give a lot of errors because it did a fallback to the user "system:anonymous" which is of course not able to list anything in the cluster.

##### Expected result
I would expect a " Authentication failed. Please try again. " message instead because the string of the token with a whitespace in front of it is invalid. 

##### Comments
Other possible result could be a successful login for the correct user, but therefore the input field should do a trim automatically to prevent prepending and apending whitespaces.

**Comment by floreks** [comment]
It is not a Dashboard issue. Kubernetes API server does not offer any kind of credentials validation. It is API server that falls back to the anonymous user in this case. We are only proxying its response. If API server allows the user to get server version then we are assuming that credentials are valid. 

We will be able to adjust this behavior if API server will expose some kind of API to actually validate credentials until then it has to stay as it is.
