### ISSUE TITLE
Can you add new management functions in the next edition? Including pod creation, service creation, ingress creation and so on.

### ISSUE THREAD

**Issue by kissingtiger** [kubernetes/dashboard#3218]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

**Comment by maciaszczykm** [comment]
We keep track of it in https://github.com/kubernetes/dashboard/issues/1600, however it has fairly low priority. You can always use YAML/JSON input to create any kind of resources.

/assign
/close
