### ISSUE TITLE
dashboard cannot be opened

### ISSUE THREAD

**Issue by XinhaiWang** [kubernetes/dashboard#3220]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by jeefy** [comment]
Please re-open when you can provide the required info above (Steps to reproduce, dashboard installation method, etc)

/triage missing-details
/assign
/close
