### ISSUE TITLE
dashboard timeouts... 

### ISSUE THREAD

**Issue by X-E-n-G** [kubernetes/dashboard#3226]
##### Environment
```
Installation method:  MacBook Pro --- installed with brew
Kubernetes version: 0.10.0
Dashboard version: v1.8.1
Commit: 7b3553aecf28224ef7275e157b5bba7dd23f436a
```

##### Observed result
Dashboard reported Gateway Timeout (504):
```
the server was unable to return a response in the time allotted, but may still be processing the request (get namespaces)

```
I was deleteing a pv 1 gb in size at the time from the shell

**Comment by floreks** [comment]
1. Use most recent version of Dashboard. 2. It does not look like an issue to me. API server timed out and Dashboard just informed you about that
