### ISSUE TITLE
Spark Executors when using Kubernetes as Scheduler

### ISSUE THREAD

**Issue by leoconco** [kubernetes/dashboard#3229]
##### Steps to reproduce

Start a spark application using kubernetes as scheduler. In the dashboard, try to open the Pod for one of the Spark executors and get this error. It does not happen when I see the Driver pod.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.2
Commit: 72832429656c74c4c568ad5b7163fa9716c3e0ec
```

##### Observed result
Dashboard reported Unknown Server Error (500):
```
Unknown reference kind Pod

```

**Comment by floreks** [comment]
Closing in favor of #1599. Spark jobs/applications have been discussed there already and due to its custom configuration they are not currently supported by Dashboard.
