### ISSUE TITLE
Clean up service when deleting a rc

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#323]
Steps:

1. Go to deploy page
2. Select upload yaml
3. Select guestbook-all-in-one.yaml
4. Deploy
5. Delete all RCs
6. Repeat steps 2-4.

=> Error: master service already exists

This is not nice. Especially, in case a yaml is selected, because the names cannot be changed easily.

I think we discussed some kind of clean-up. 

Please someone has a look at this bug. Please fix before release.

**Comment by bryk** [comment]
Yeah. A checkbox and prompt on what will be deleted in the delete form would be nice. 

I cannot take it ATM. This is high priority. Anyone can take this?

**Comment by floreks** [comment]
I can work on this one. I'll prepare some concept.

**Comment by floreks** [comment]
It's done so we can close.
