### ISSUE TITLE
unable to pull k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0

### ISSUE THREAD

**Issue by sneak** [kubernetes/dashboard#3230]
```
Events:                                                                                                                                                                               │·············
  Type     Reason     Age                 From                   Message                                                                                                              │·············
  ----     ------     ----                ----                   -------                                                                                                              │·············
  Normal   Scheduled  28m                 default-scheduler      Successfully assigned kube-system/kubernetes-dashboard-767dc7d4d-2jdmp to lej1.eeqj.de                               │·············
  Warning  Failed     26m (x6 over 28m)   kubelet, lej1.eeqj.de  Error: ImagePullBackOff                                                                                              │·············
  Normal   Pulling    26m (x4 over 28m)   kubelet, lej1.eeqj.de  pulling image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0"                                                        │·············
  Warning  Failed     26m (x4 over 28m)   kubelet, lej1.eeqj.de  Failed to pull image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0": rpc error: code = Unknown desc = Error response│·············
 from daemon: manifest for k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0 not found                                                                                                    │·············
  Warning  Failed     26m (x4 over 28m)   kubelet, lej1.eeqj.de  Error: ErrImagePull                                                                                                  │·············  Normal   BackOff    3m (x108 over 28m)  kubelet, lej1.eeqj.de  Back-off pulling image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0"                                               │·············
```

```
root@lej1 ~ # docker pull k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0
Error response from daemon: manifest for k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0 not found
root@lej1 ~ # 
```

**Comment by floreks** [comment]
We are in the process of releasing it. It is not automated and only 2 people can push the images so we have to wait. Use v1.8.3 till then.

**Comment by AndrewSav** [comment]
@floreks 

Both [here](https://github.com/kubernetes/dashboard) and [here](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) we are instructed to run:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```
in order to perform installation. This link currently points to 1.10 image that is not available. I hope you appreciate how this could be a problem.

Would it be possible in the future not to update any part of installation instructions (including the yaml it refers to) before the image is actually available?

Would it be possible to revert the update, until the image becomes available?

Many thanks!

**Comment by klaymen47** [comment]
This is impacting many production deployments, I presume. Please revert the change until the new images are available.

**Comment by zerkms** [comment]
@klaymen47 it's a good idea to install known version in production so that you weren't surprised when you install a new version and it has a bunch of breaking changes

The old url works and must be used for any sensitive deployments, instead of `master`

https://raw.githubusercontent.com/kubernetes/dashboard/v1.8.3/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by sneak** [comment]
If a change someone else makes on their repo affects your production deployments, your production deployments are not configured correctly.

**Comment by floreks** [comment]
Master will be reverted soon to the previous state by #3232 and master deploy link should be working again. We do see how this is an issue and will try to configure automated build pipeline soon, and also modify the release procedure so it does not affect users at any time.

@AndrewSav 
The second link you have provided is actually not maintained by us.

@jimmypw 
> Indeed this is a bit short sighted to update the generic installation URL before it is even available. Are we talking hours or days before the new container will become available?

Only few people can actually do the release and it is done manually. From the information I got, it is possible that the images will not be pushed until monday.

@klaymen47
> This is impacting many production deployments, I presume. Please revert the change until the new images are available.

As @zerkms and @sneak mentioned it is not a good idea to use master link to deploy anything to a production as there is always a chance that it will be changed somehow and this change might affect your environment. Only stable/fixed links should be used that are available on the [Releases](https://github.com/kubernetes/dashboard/releases) page.

I will update our README and wiki pages to point users to the releases page, so there will be no more confusion like that even after master breaks.
