### ISSUE TITLE
kubernetes-dashboard build differs from parallelism

### ISSUE THREAD

**Issue by bmwiedemann** [kubernetes/dashboard#3234]
##### Environment
```
Dashboard version: 27408f1922c26d758cf1ac4639ccc4d1efdd45a5
Kubernetes version: N/A
Operating system: openSUSE-Tumbleweed 20180825
Node.js version: v8.11.3
Go version: go1.10.3
```

##### Steps to reproduce

On openSUSE or Debian do
```bash
osc checkout openSUSE:Factory/kubernetes-dashboard && cd $_
osc build -j2 --vm-type=kvm --keep-pkg=RPMS --noservice \
 "--build-opt=--vm-custom-opt=-rtc base=$(date -d@$((1535200000+31536000*($RANDOM%100))) -u +%FT%T)" \
 --define='%_buildhost reproducible' \
 --define='%clamp_mtime_to_source_date_epoch Y' \
 --define='%use_source_date_epoch_as_buildtime Y'
cd RPMS
md5sum *x86_64.rpm
unrpm *x86_64.rpm
md5sum var/lib/kubernetes-dashboard/public/*/static/app.*.js
```

##### Observed result
produces different RPMs for most runs

##### Expected result
should produce identical RPMs in each run

##### Comments
This is in addition to #3233
If you do not apply this patch, you have to omit the line with `-rtc`
Building with `-j1` instead of `-j2` already gives reproducible results.

**Comment by bmwiedemann** [comment]
The part that differs is /var/lib/kubernetes-dashboard/public/en/static/app.*.js
where even the name varies

**Comment by bmwiedemann** [comment]
/remove-lifecycle stale.

a workaround for this issue is to do
```bash
taskset 1 node node_modules/gulp/bin/gulp.js build
```

**Comment by floreks** [comment]
This should be resolved when we switch to the migration build, which should happen quite soon.

**Comment by maciaszczykm** [comment]
We have changed build system with the new version. Please reopen if the issue persists.
