### ISSUE TITLE
Error on minikube

### ISSUE THREAD

**Issue by Joby81** [kubernetes/dashboard#3239]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.1
Commit: 7b3553aecf28224ef7275e157b5bba7dd23f436a
```

##### Observed result
Dashboard reported Gateway Timeout (504):
```
the server was unable to return a response in the time allotted, but may still be processing the request (get pods)

```

**Comment by maciaszczykm** [comment]
This is not a Dashboard issue. It is coming from Kubernetes cluster.

Moreover, I'd recommend to update to the newer version. 

/assign
/close

**Comment by maciaszczykm** [comment]
Looks like Kubernetes issue rather than Dashboard one. Are you able to do `kubectl get pods --all-namespaces` without any troubles?

Moreover, I'd recommend to update to the newer version.

/assign

**Comment by maciaszczykm** [comment]
Please reopen when you can provide the required info.

/close
