### ISSUE TITLE
Error Accessing the Kubernetes dashboard

### ISSUE THREAD

**Issue by codepossible** [kubernetes/dashboard#3242]
##### Steps to reproduce

Provision AKS cluster using az-cli.

First Attempt:
Follow the steps provided in the instructions to launch the Kubernetes Dashboard on Azure Portal.

Second Attempt:
Create a RBAC role based on instruction provided here - https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard

Follow the steps provided in the instructions to launch the Kubernetes Dashboard on Azure Portal.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
Get https://10.0.0.1:443/api/v1/namespaces/default/persistentvolumeclaims: dial tcp 10.0.0.1:443: getsockopt: no route to host

```

##### Comments
Cannot access any part of the dashboard.

**Comment by maciaszczykm** [comment]
+1 to @floreks comment.

One more question - does `kubectl` work with your cluster?

**Comment by codepossible** [comment]
Yes, kubectl does. My apologizes, did not realize that it was wrong forum. Thanks for pointing it out.
