### ISSUE TITLE
Unable to access Dashboard in browser and getting : localhost refused to connect.

### ISSUE THREAD

**Issue by samkrish123** [kubernetes/dashboard#3247]
I am installing Kubernetes on CentOS 7, and created the dashboard successfully.
kubectl get pods --all-namespaces  -o wide
kube-system   kubernetes-dashboard-767dc7d4d-7jvd2      1/1       Running   0          39m       192.168.151.68   mas.kuber.com   <none>
*******************************************
No error description:
[root@mas ~]# kubectl describe deployment kubernetes-dashboard-767dc7d4d-7jvd2  -n kube-system
Error from server (NotFound): deployments.extensions "kubernetes-dashboard-767dc7d4d-7jvd2" not found
[root@mas ~]# kubectl describe pod  kubernetes-dashboard-767dc7d4d-7jvd2 -n kube-system
Name:               kubernetes-dashboard-767dc7d4d-7jvd2
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               mas.kuber.com/192.168.0.11
Start Time:         Sun, 02 Sep 2018 13:10:46 +0530
Labels:             k8s-app=kubernetes-dashboard
                    pod-template-hash=323873808
Annotations:        <none>
Status:             Running
IP:                 192.168.151.68
Controlled By:      ReplicaSet/kubernetes-dashboard-767dc7d4d
Containers:
  kubernetes-dashboard:
    Container ID:  docker://f76db66633256d0fa426ff238463890d1a853c9453a8502c1e96ae352fdaf37b
    Image:         k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0
    Image ID:      docker-pullable://k8s.gcr.io/kubernetes-dashboard-amd64@sha256:1d2e1229a918f4bc38b5a3f9f5f11302b3e71f8397b492afac7f273a0008776a
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
    State:          Running
      Started:      Sun, 02 Sep 2018 13:10:48 +0530
    Ready:          True
    Restart Count:  0
    Liveness:       http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-bcpn2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  kubernetes-dashboard-token-bcpn2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-bcpn2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                    Message
  ----    ------     ----  ----                    -------
  Normal  Scheduled  41m   default-scheduler       Successfully assigned kube-system/kubernetes-dashboard-767dc7d4d-7jvd2 to mas.kuber.com
  Normal  Pulled     41m   kubelet, mas.kuber.com  Container image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0" already present on machine
  Normal  Created    41m   kubelet, mas.kuber.com  Created container
  Normal  Started    41m   kubelet, mas.kuber.com  Started container
***********************************
But I could see some error message in log file.

[root@mas ~]# kubectl -n kube-system logs -p  kubernetes-dashboard-767dc7d4d-sggrb
Error from server (BadRequest): previous terminated container "kubernetes-dashboard" in pod "kubernetes-dashboard-767dc7d4d-sggrb" not found

root@mas ~]# kubectl get nodes
NAME            STATUS    ROLES     AGE       VERSION
mas.kuber.com   Ready     master    1h        v1.11.2
***********************************
Pls help me to resolve this issue, Thanks in advance.

**Comment by floreks** [comment]
I don't see any error message here so I can't really help. Unless you provide logs from dashboard there is nothing we can do.

**Comment by samkrish123** [comment]
I have fixed the problem. Earlier I was not able to view the dashboard in the browser and getting connection refused message.  The actual problem was instead of localhost ip (127.0.0.1)  I changed to static IP address of the master server in proxy. Then it started working.
