### ISSUE TITLE
Uncaught ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by leoyer** [kubernetes/dashboard#3248]
- OS : Ubuntu 17.10
- CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
- architecture x64
<pre><font color="#3465A4"><b>kubernetes/dashboard</b></font>$ gulp -v
[<font color="#555753">09:40:21</font>] Requiring external module <font color="#75507B">@babel/register</font>
[<font color="#555753">09:40:21</font>] CLI version 3.9.1
[<font color="#555753">09:40:21</font>] Local version 3.9.1

<font color="#4E9A06"><b>leoyer@leoyer</b></font>:<font color="#3465A4"><b>~</b></font>$ go version
go version go1.10.3 linux/amd64

<font color="#4E9A06"><b>leoyer@leoyer</b></font>:<font color="#3465A4"><b>~</b></font>$ java -version
java version &quot;1.8.0_161&quot;
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

<font color="#4E9A06"><b>leoyer@leoyer</b></font>:<font color="#3465A4"><b>~</b></font>$ npm -v
5.6.0

<font color="#4E9A06"><b>leoyer@leoyer</b></font>:<font color="#3465A4"><b>~</b></font>$ node -v
v8.9.4
</pre>

- first

<pre>root@leoyer:/home/leoyer/soft/goproxy# kubectl proxy --port=8080
Starting to serve on 127.0.0.1:8080
</pre>

export KUBE_DASHBOARD_KUBECONFIG="/etc/kubernetes/admin.conf"

npm  i

gulp serve

<pre><font color="#3465A4"><b>kubernetes/dashboard</b></font>$ gulp serve
[<font color="#555753">09:46:51</font>] Requiring external module <font color="#75507B">@babel/register</font>
[<font color="#555753">09:46:53</font>] Using gulpfile <font color="#75507B">~/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/gulpfile.babel.js</font>
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">clean-packaged-backend-source</font>&apos;...
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">kill-backend</font>&apos;...
[<font color="#555753">09:46:53</font>] Finished &apos;<font color="#06989A">kill-backend</font>&apos; after <font color="#75507B">108 μs</font>
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">locales-for-backend:dev</font>&apos;...
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">scripts</font>&apos;...
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">styles</font>&apos;...
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">buildExistingI18nCache</font>&apos;...
[<font color="#555753">09:46:53</font>] Finished &apos;<font color="#06989A">buildExistingI18nCache</font>&apos; after <font color="#75507B">314 ms</font>
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">angular-templates</font>&apos;...
[<font color="#555753">09:46:53</font>] Finished &apos;<font color="#06989A">locales-for-backend:dev</font>&apos; after <font color="#75507B">626 ms</font>
[<font color="#555753">09:46:53</font>] Finished &apos;<font color="#06989A">clean-packaged-backend-source</font>&apos; after <font color="#75507B">679 ms</font>
[<font color="#555753">09:46:53</font>] Starting &apos;<font color="#06989A">package-backend-source</font>&apos;...
[<font color="#555753">09:46:58</font>] Finished &apos;<font color="#06989A">scripts</font>&apos; after <font color="#75507B">5.68 s</font>
[<font color="#555753">09:46:59</font>] Finished &apos;<font color="#06989A">styles</font>&apos; after <font color="#75507B">5.92 s</font>
[<font color="#555753">09:46:59</font>] Starting &apos;<font color="#06989A">index</font>&apos;...
[<font color="#555753">09:46:59</font>] Finished &apos;<font color="#06989A">index</font>&apos; after <font color="#75507B">126 ms</font>
[<font color="#555753">09:46:59</font>] Finished &apos;<font color="#06989A">angular-templates</font>&apos; after <font color="#75507B">5.82 s</font>
[<font color="#555753">09:46:59</font>] Starting &apos;<font color="#06989A">watch</font>&apos;...
[<font color="#555753">09:46:59</font>] Finished &apos;<font color="#06989A">watch</font>&apos; after <font color="#75507B">363 ms</font>
[<font color="#555753">09:47:00</font>] Finished &apos;<font color="#06989A">package-backend-source</font>&apos; after <font color="#75507B">6.12 s</font>
[<font color="#555753">09:47:00</font>] Starting &apos;<font color="#06989A">link-vendor</font>&apos;...
[<font color="#555753">09:47:00</font>] Finished &apos;<font color="#06989A">link-vendor</font>&apos; after <font color="#75507B">223 μs</font>
[<font color="#555753">09:47:00</font>] Starting &apos;<font color="#06989A">package-backend</font>&apos;...
[<font color="#555753">09:47:00</font>] Finished &apos;<font color="#06989A">package-backend</font>&apos; after <font color="#75507B">16 μs</font>
[<font color="#555753">09:47:00</font>] Starting &apos;<font color="#06989A">backend</font>&apos;...
[<font color="#555753">09:47:00</font>] Finished &apos;<font color="#06989A">backend</font>&apos; after <font color="#75507B">434 ms</font>
[<font color="#555753">09:47:00</font>] Starting &apos;<font color="#06989A">spawn-backend</font>&apos;...
[<font color="#555753">09:47:00</font>] Finished &apos;<font color="#06989A">spawn-backend</font>&apos; after <font color="#75507B">9.94 ms</font>
[<font color="#555753">09:47:00</font>] Starting &apos;<font color="#06989A">serve</font>&apos;...
[HPM] Proxy created: /api  -&gt;  http://localhost:9091
2018/09/04 09:47:00 Starting overwatch
2018/09/04 09:47:00 Using kubeconfig file: /etc/kubernetes/admin-b.conf
2018/09/04 09:47:00 Skipping in-cluster config
2018/09/04 09:47:00 Using random key for csrf signing
2018/09/04 09:47:00 No request provided. Skipping authorization
[<font color="#555753">09:47:00</font>] Finished &apos;<font color="#06989A">serve</font>&apos; after <font color="#75507B">18 ms</font>
2018/09/04 09:47:00 Successful initial request to the apiserver, version: v1.11.1
2018/09/04 09:47:00 Generating JWE encryption key
2018/09/04 09:47:00 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/09/04 09:47:00 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
[<font color="#3465A4">BS</font>] [<font color="#3465A4">BrowserSync SPA</font>] Running...
[<font color="#3465A4">Browsersync</font>] <b>Access URLs:</b>
<font color="#555753"> ---------------------------------------</font>
       Local: <font color="#75507B">http://localhost:9090/</font>
    External: <font color="#75507B">http://192.168.1.104:9090/</font>
<font color="#555753"> ---------------------------------------</font>
          UI: <font color="#75507B">http://localhost:3001</font>
 UI External: <font color="#75507B">http://192.168.1.104:3001</font>
<font color="#555753"> ---------------------------------------</font>
[<font color="#3465A4">Browsersync</font>] Serving files from: <font color="#75507B">/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/.tmp/serve</font>
[<font color="#3465A4">Browsersync</font>] Serving files from: <font color="#75507B">/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/src/app</font>
2018/09/04 09:47:00 Initializing JWE encryption key from synchronized object
2018/09/04 09:47:00 Creating in-cluster Heapster client
2018/09/04 09:47:00 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2018/09/04 09:47:00 Serving insecurely on HTTP port: 9091
</pre>

- and then i open browe  localhost:9090  

> f12 console output   angular is not defined 

<pre><font color="#3465A4"><b>kubernetes/dashboard</b></font>$ /usr/local/bin/node /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/gulp/bin/gulp.js --color --gulpfile /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/gulpfile.babel.js frontend-test
[<font color="#555753">09:48:12</font>] Requiring external module <font color="#75507B">@babel/register</font>
[<font color="#555753">09:48:14</font>] Using gulpfile <font color="#75507B">~/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/gulpfile.babel.js</font>
[<font color="#555753">09:48:14</font>] Starting &apos;<font color="#06989A">set-test-node-env</font>&apos;...
[<font color="#555753">09:48:14</font>] Finished &apos;<font color="#06989A">set-test-node-env</font>&apos; after <font color="#75507B">94 μs</font>
[<font color="#555753">09:48:14</font>] Starting &apos;<font color="#06989A">frontend-test</font>&apos;...
<font color="#4E9A06">04 09 2018 09:48:31.252:INFO [framework.browserify]: </font>bundle built
<font color="#4E9A06">04 09 2018 09:48:31.288:INFO [karma]: </font>Karma v2.0.5 server started at http://0.0.0.0:9876/
<font color="#4E9A06">04 09 2018 09:48:31.288:INFO [launcher]: </font>Launching browser Chrome with unlimited concurrency
<font color="#4E9A06">04 09 2018 09:48:31.291:INFO [launcher]: </font>Starting browser Chrome
<font color="#4E9A06">04 09 2018 09:48:33.004:INFO [Chrome 67.0.3396 (Linux 0.0.0)]: </font>Connected on socket 119gsZljmzVWaSSSAAAA with id 42584841
<font color="#CC0000">Chrome 67.0.3396 (Linux 0.0.0) ERROR</font>
  {
    &quot;message&quot;: &quot;Uncaught ReferenceError: angular is not defined\nat /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:15:41\n\nReferenceError: angular is not defined\n    at /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:15:41\n    at ng_from_global (/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:11:6)\n    at /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:12:2&quot;,
    &quot;str&quot;: &quot;Uncaught ReferenceError: angular is not defined\nat /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:15:41\n\nReferenceError: angular is not defined\n    at /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:15:41\n    at ng_from_global (/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:11:6)\n    at /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:12:2&quot;
  }
Chrome 67.0.3396 (Linux 0.0.0): Executed 0 of 0<font color="#CC0000"> ERROR</font> (0.251 secs / 0 secs)
[<font color="#555753">09:48:34</font>] &apos;<font color="#06989A">frontend-test</font>&apos; <font color="#CC0000">errored after</font> <font color="#75507B">20 s</font>
[<font color="#555753">09:48:34</font>] Error: Failed 1 tests.
    at /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/build/test.js:68:24
    at removeAllListeners (/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/_karma@2.0.5@karma/lib/server.js:334:9)
    at webServer.close (/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/_karma@2.0.5@karma/lib/server.js:344:11)
    at Server.close (net.js:1604:9)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1655:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
</pre>

[截图](https://test.lvhukuaixi.com/dashboard.png)
![Alt text](https://test.lvhukuaixi.com/dashboard.png)

**Comment by dongsuo** [comment]
看起来像是 ui-router 安装失败的问题？试试重新 npm install ?

**Comment by leoyer** [comment]
<pre><font color="#3465A4"><b>kubernetes/dashboard</b></font>$ npm install --save @uirouter/angularjs
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> browserify-shim@2.0.10 requires a peer of browserify@&gt;= 2.3.0 &lt; 4 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> karma-browserify@5.1.2 requires a peer of browserify@&gt;=10 &lt;15 but none is installed. You must install peer dependencies yourself.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">path</font> /home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/npm/node_modules/dezalgo
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ENOENT
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> -2
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">syscall</font> rename
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">enoent</font> ENOENT: no such file or directory, rename &apos;/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/npm/node_modules/dezalgo&apos; -&gt; &apos;/home/leoyer/gowork/src/websocketServer/src/github.com/kubernetes/dashboard/node_modules/npm/node_modules/.dezalgo.DELETE&apos;
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">enoent</font> This is related to npm not being able to find a file.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">enoent</font> 

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/leoyer/.npm/_logs/2018-09-04T03_13_57_315Z-debug.log
</pre>

**Comment by leoyer** [comment]
git clone  it again, and then it's ready.

**Comment by lcmatt** [comment]
I hit exactly the same issue and solved it by following @leoyer 's https://github.com/kubernetes/dashboard/issues/3248#issuecomment-418233715 that
1) Remove cloned dashboard project and clone it again
2) in dashboard folder, do 'npm i' (noted that I changed 'bower' download protocol from git to https in package-lock.json due to my network limitation, not sure if the breakage last time cause ui.router installation side-effect)
3) kubectl proxy --port=8080, then in other terminal, issue 'gulp serve'
4) The UI finally showed up in the browser with URL 'http://localhost:9090/'

Again, thanks @leoyer for saving my day!
