### ISSUE TITLE
[Bug] Safari on Mac os dont show kd-replica-set-card

### ISSUE THREAD

**Issue by ekozan** [kubernetes/dashboard#325]
they have a css bug on safari nothing show but kd-replica-set-card is present 

![kubernetes_dashboard](https://cloud.githubusercontent.com/assets/688184/12728921/71376cac-c924-11e5-8152-bb67fd238ff7.png)

**Comment by ekozan** [comment]
just think abut one thing i try the pre-build docker img it's may be not the last version

**Comment by bryk** [comment]
Fixed already on HEAD. I've pushed new canary image. You can test it out.

In the future, btw, we'll be pushing canary images automatically.
