### ISSUE TITLE
Dashboard always CrashLoopBackOff cannot connect.

### ISSUE THREAD

**Issue by Rukeith** [kubernetes/dashboard#3258]
##### Environment
```
Dashboard version: v.10.0
Kubernetes version: v.1.11.2
Operating system: CentOS 7.5.1804
```

##### Steps to reproduce
Run `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`
Run `kube-proxy`

##### Observed result
I cannot connect dashboard, then I run `kubectl get pods --namespace=kube-system`

Output：

```
NAME                                                        READY     STATUS             RESTARTS   AGE
coredns-78fcdf6894-qh6zb                                    1/1       Running            2          2d
coredns-78fcdf6894-xbzgn                                    1/1       Running            1          2d
etcd-twsr-whtestserver01.garenanet.com                      1/1       Running            2          2d
kube-apiserver-twsr-whtestserver01.garenanet.com            1/1       Running            2          2d
kube-controller-manager-twsr-whtestserver01.garenanet.com   1/1       Running            2          2d
kube-flannel-ds-amd64-2bnmx                                 1/1       Running            3          2d
kube-flannel-ds-amd64-r58j6                                 1/1       Running            0          2d
kube-flannel-ds-amd64-wq6ls                                 1/1       Running            0          2d
kube-proxy-ds7lg                                            1/1       Running            0          2d
kube-proxy-fx46d                                            1/1       Running            0          2d
kube-proxy-ph7qq                                            1/1       Running            2          2d
kube-scheduler-twsr-whtestserver01.garenanet.com            1/1       Running            1          2d
kubernetes-dashboard-767dc7d4d-mc2sm                        0/1       CrashLoopBackOff   784        2d
```

I found the dashboard always `CrashLoopBackOff`.
I run `kubectl logs kubernetes-dashboard-767dc7d4d-mc2sm --namespace=kube-system` to see the log.

Log：

```
Error from server: Get https://10.4.211.53:10250/containerLogs/kube-system/kubernetes-dashboard-767dc7d4d-mc2sm/kubernetes-dashboard: dial tcp 10.4.211.53:10250: connect: no route to host
```

##### Expected result
I could connect dashboard.

##### Comments
I am not sure it's my server block the connection or I install dashboard with wrong steps. I need some help. Hope someone could help me fix this issue.

**Comment by jeefy** [comment]
I think there is a problem with a node in your cluster. 

`kubectl` can talk to your API Server, but it seems like there is a problem with the host the dashboard is trying to run on. When you attempt to run `kubectl logs` it tries and fails to grab logs from the host the pod is scheduled on.

See https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level 

Closing since this appears to not be a Dashboard issue. Please re-open if needed!
/assign
/close
