### ISSUE TITLE
PUBLIC DASHBOARD WITH IP PUBLICA

### ISSUE THREAD

**Issue by juanpablohp33** [kubernetes/dashboard#3260]
##### Environment

```
Dashboard version:
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Operating system:
Ubuntu 16.04 LT
Node.js version:
Go version:
```

##### Steps to reproduce

Hi, 

I have a VM on cloud, and I have 1 node master and 3 nodes slaves, I installed the dashboard and I think is correct, but I have problem when I tried expose to internet, I don know how expose my dashboard witH my IP PUBLICA

ubuntu@ip-10-0-3-54:/home/kubernetes/master/dashboard$ kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE       IP               NODE            NOMINATED NODE
kube-system   calico-etcd-q9lzr                         1/1       Running   1          6h        10.0.3.54        ip-10-0-3-54    <none>
kube-system   calico-kube-controllers-cd589c58b-zqf6j   1/1       Running   8          2d        10.0.3.54        ip-10-0-3-54    <none>
kube-system   calico-node-dbxcc                         2/2       Running   22         2d        10.0.3.200       ip-10-0-3-200   <none>
kube-system   calico-node-rpsdn                         2/2       Running   25         2d        10.0.3.71        ip-10-0-3-71    <none>
kube-system   calico-node-wghrr                         2/2       Running   13         2d        10.0.3.54        ip-10-0-3-54    <none>
kube-system   calico-node-zqxrw                         2/2       Running   14         2d        10.0.3.143       ip-10-0-3-143   <none>
kube-system   coredns-78fcdf6894-7cpsx                  1/1       Running   5          2d        192.168.89.149   ip-10-0-3-54    <none>
kube-system   coredns-78fcdf6894-htxfw                  1/1       Running   5          2d        192.168.89.150   ip-10-0-3-54    <none>
kube-system   etcd-ip-10-0-3-54                         1/1       Running   5          2d        10.0.3.54        ip-10-0-3-54    <none>
kube-system   kube-apiserver-ip-10-0-3-54               1/1       Running   5          2d        10.0.3.54        ip-10-0-3-54    <none>
kube-system   kube-controller-manager-ip-10-0-3-54      1/1       Running   5          2d        10.0.3.54        ip-10-0-3-54    <none>
kube-system   kube-proxy-f65lh                          1/1       Running   5          2d        10.0.3.200       ip-10-0-3-200   <none>
kube-system   kube-proxy-n8gcf                          1/1       Running   4          2d        10.0.3.143       ip-10-0-3-143   <none>
kube-system   kube-proxy-tqh49                          1/1       Running   5          2d        10.0.3.54        ip-10-0-3-54    <none>
kube-system   kube-proxy-zljvj                          1/1       Running   6          2d        10.0.3.71        ip-10-0-3-71    <none>
kube-system   kube-scheduler-ip-10-0-3-54               1/1       Running   5          2d        10.0.3.54        ip-10-0-3-54    <none>
kube-system   kubernetes-dashboard-767dc7d4d-89lbs      1/1       Running   4          2d        192.168.11.197   ip-10-0-3-71    <none>

**Comment by maciaszczykm** [comment]
You need to be aware that this can cause major security issues if your setup will be incorrect. Please ensure that access control in your Dashboard is configured properly, then read these docs:

- https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/
- https://kubernetes.io/docs/concepts/services-networking/ingress/
- https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above

Do not use `kubectl proxy` as it will not allow to sign in. `kubectl proxy` does not allow HTTPS connection.

It looks like support request for Kubernetes itself (exposing apps). I suggest to move it to core repo.

/close
