### ISSUE TITLE
Restore search box in YAML manifest editor

### ISSUE THREAD

**Issue by asarkar** [kubernetes/dashboard#3263]
After upgrading from 1.7 to 1.10, the search box that used to exist when editing the YAML manifest is no longer there. This is an issue since there's no way to efficiently search for keywords in the manifest without having to scroll through all of it.

##### Environment
API server is installed as RPM. Dashboard runs as Docker container.

```
Dashboard version: v1.8.3
Kubernetes version: v1.10.2
Operating system: Centos 7.4
Node.js version: Not applicable
Go version: go1.9.3
```

##### Steps to reproduce
1. Open Dashboard in a browser.
2. Click on 'Replication Controllers' on the left (yes, we are still using RC). Pick any on the right, and click on the dropdown (three dots).
3. Click on 'View/edit YAML'
4. Attempt to find an environment variable. Realize that you really can't without scroll through the manifest from top to bottom.

##### Observed result
No search box available.

##### Expected result
Search box is available, and when a keyword is entered, if there's one or more search hits, those parts of the manifest are highlighted and the page automatically scrolls to the first one. Basically, do the same as before.

##### Comments
I didn't see any mention of removing this feature in the changelog, so it must be a bug.

**Comment by floreks** [comment]
Change from the `tree` to `code` mode in the editor was dictated by user complaints about several usability issues related to `tree` mode. As those issues are part of ace editor and most probably won't be fixed, we will not be reverting back to the `tree` mode. In the future, we might think about using more advanced editor, but for now, this is not a priority.

> I didn't see any mention of removing this feature in the changelog, so it must be a bug.

From the `v1.7.1` **changelog**:
* Change jsoneditor mode from `tree` to `code`

**Comment by asarkar** [comment]
So, your solution for fixing problems reported by the users is to remove the feature without offering any replacement? That makes no sense; of course, any bug can be fixed by removing the affected code, but that’s hardly what’s expected.

**Comment by floreks** [comment]
Our solution was to offer less features that are more stable than more features that are buggy and can't be fixed without fixing 3rd party library or replacing editor completely.
