### ISSUE TITLE
Replace Ace with monaco-editor?

### ISSUE THREAD

**Issue by pengx17** [kubernetes/dashboard#3268]
The YAML/JSON editor currently using in the Dashboard is baked with ACE editor. It is light weight and easy to be integrated, but I think we could do more magic stuff with [monaco-editor](https://github.com/Microsoft/monaco-editor) like Kubernetes schema validation.

Here is an example of using JSON schema to do validation over a deployment yaml.
https://pengx17.github.io/json-schema/

It is powered by monaco-editor and monaco-yaml (which is managed by me here: https://github.com/pengx17/monaco-yaml since there is no official one).

Some of the features it highlights:
- load json-schema files dynamically
- show field info upon hovering
- syntax and schema validation
- showing path of the focused field
- good performance (virtual scrolling)

**Comment by maciaszczykm** [comment]
Looks good, UX is much better. However, I have some concerns about maintenance. I would like to keep up to date with new releases of all libs and avoid any wrappers. Could you tell how much of work is done on your side in https://github.com/pengx17/monaco-yaml? Is there a chance that we could keep this customization within Dashboard repo or is it too big/you do not want it?

**Comment by pengx17** [comment]
@maciaszczykm I am also concerned about the maintenance efforts.
For using monaco-editor alone, I believe there should not be too much concersn. We could directly replace ace with it without using monaco-yaml. A simple wrapper should do the work (by implementing ControlValueAccessor).

For monaco-yaml , since it is not managed officially and perhaps it will never be managed by the vscode team.  As you see my repo (monaco-yaml) was originally forked from another guy's work, but he stoped maintaining it a few months ago after he releasing the first version.
Here is how I maintain the monaco-yaml's deps: whenever the deps updates, I have to manually copy the related codes from repos (mainly redhat-developer/yaml-language-server) to the source folder of monaco-yaml. There will be some manual changes including refactoring import paths and types. After dep updating is done, I will load the demo and see if the functionalities are broken or not.

Overall the maintenance effort is ok. It is pretty similar to what we do updating the Golang deps for the dashboard project. Indeed keeping the maintenance will be a sustainable endeavour over the long term, but I guess at least I could do the dep updates every a couple of months.

**Comment by maciaszczykm** [comment]
@pengx17 It is not a problem until it is only dep update. If there is bigger API change and we are not able to modify code on our side then it becomes an issue. For me we should use Microsoft's one.

@floreks What do you think about it?

**Comment by pengx17** [comment]
@maciaszczykm the only lead I can find on goole is the issue here: https://github.com/Microsoft/monaco-editor/issues/131 Looks like the guys in vscode team are not interested in supporting yaml at the moment.

**Comment by floreks** [comment]
I have some concerns regarding this. As @maciaszczykm mentioned the biggest one is maintenance.

Additionally, such "big" featured editor seems a bit like an overkill just for Dashboard purposes. We do not really need a full-fledged solution, but rather a simple editor with syntax highlight and simple YAML/JSON schema validation.

Dynamic schema loading, virtual scrolling, etc. are great for standalone solution, but I don't see such features as part of simple "Edit resource" feature.

**Comment by maciaszczykm** [comment]
I think we can continue with Ace and focus on the more important stuff.

/close
