### ISSUE TITLE
Execute the command to read the file on the dashboard shell command line terminal, which crashed and displays connection closed

### ISSUE THREAD

**Issue by zhaoyibeijing** [kubernetes/dashboard#3275]
##### Environment

```
Dashboard version:v1.7.1
Kubernetes version:v1.7.16
Operating system: Linux Server release 7.2
Node.js version:
Go version:
```

When I execute the bash command at the dashboard terminal to read larger files, such as Hadoop fs -cat, the error message "connection closed" appears and the terminal hangs up.

I looked at the server's log and it showed like this：
`2018/09/28 15:28:00 handleTerminalSession: can't Recv: sockjs: session not in open state
E0928 15:28:00.827007 1 v2.go:105] sockjs: session not in open state`

##### Steps to reproduce

 execute the bash command at the dashboard terminal 

##### Observed result

The content will be output to the screen line by line, but after about a minute, the dashboard shell terminal hangs up with a larger identifier (gray font background) prompt: connection closed

##### Expected result

Read the content correctly and output it to the screen.

**Comment by zhaoyibeijing** [comment]
when I run command like this： `while true; do echo 1;done`

This problem will reappear.

**Comment by maciaszczykm** [comment]
Duplicate of https://github.com/kubernetes/dashboard/issues/2029#issuecomment-309792341.

/close
