### ISSUE TITLE
setting not work

### ISSUE THREAD

**Issue by ALexanderMarginal** [kubernetes/dashboard#3281]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Unknown Server Error:
```
No error data available
```

**Comment by ALexanderMarginal** [comment]
settings not opening!!!

**Comment by maciaszczykm** [comment]
@maciaszczykm Have you filled the issue template? How we can possibly know what is happening?
