### ISSUE TITLE
Kubernetes hang in docker for mac

### ISSUE THREAD

**Issue by itommey** [kubernetes/dashboard#3282]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Unknown Server Error (504):
```
the server was unable to return a response in the time allotted, but may still be processing the request (get deployments.apps)

```

##### Comments

I've my kubernetes running in docker for mac hang. It looks like kubernetes in docker for mac consuming my CPU

**Comment by jeefy** [comment]
This looks to be a server config issue and not a Dashboard issue. File an issue with Docker if it appears to be a problem with Docker's Kubernetes install.

Please re-open this issue with more information if closed in error.

/assign
/close
