### ISSUE TITLE
[Feature Request] Add ability to run cronjob based job manually

### ISSUE THREAD

**Issue by Dm3Ch** [kubernetes/dashboard#3284]
I think it would be useful to have a button on cronjob view to create job based on this cronjob right now.

Same idea was discussed here https://github.com/kubernetes/kubernetes/issues/47538
Accepted PR with same functionality to kubelet https://github.com/kubernetes/kubernetes/pull/60084

**Comment by maciaszczykm** [comment]
It's a bit hidden, but it seems to be in the resource list. Check the menu on the right in the row. It should be named `Trigger`.

**Comment by Dm3Ch** [comment]
Ok, thank you.
