### ISSUE TITLE
Suddenly Error while stress test 

### ISSUE THREAD

**Issue by hungz** [kubernetes/dashboard#3292]
##### Steps to reproduce

I'm stress test about 20k CCU then error occur
I also see some socket pod is timeout also 
"
Readiness probe failed: Get http://10.233.118.1:3000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
"

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Unknown Server Error (503):
```
Error: 'dial tcp 10.233.67.1:8443: getsockopt: connection refused'
Trying to reach: 'https://10.233.67.1:8443/api/v1/deployment/testing/staging-redis-ha-server'
```

**Comment by maciaszczykm** [comment]
Please provide better description. I can't understand current one.

/triage needs-information

**Comment by hungz** [comment]
Could you tell me what exactly information you need to analyze? 
I will collect for you
Thanks you

**Comment by maciaszczykm** [comment]
@hungz Detailed description of steps to reproduce. What is your expected result and what was observed? What is your `kubectl version`?

**Comment by maciaszczykm** [comment]
Information is still missing. Please reopen after providing it.

/close
