### ISSUE TITLE
Kubernetes management UI do not response

### ISSUE THREAD

**Issue by benzhi2011** [kubernetes/dashboard#3295]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
```

##### Observed result
Dashboard reported Gateway Timeout (504):
```
the server was unable to return a response in the time allotted, but may still be processing the request (get configmaps)

```

##### Comments
25112 portforward.go:271] error creating error stream for port 8001 -> 9090: Timeout occured from console. Apps running in the cluster works fine.

**Comment by maciaszczykm** [comment]
The error is coming from Kubernetes itself, can you check if you can `kubectl get configmap`?

/triage needs-information

**Comment by benzhi2011** [comment]
Hi @maciaszczykm I am new to Kubernates, I am a .net dev and want to try running my .net core app in the Kubernates. I used AKS and deployed two apps in to the Cluster and it works fine yesterday. I came this morning the management UI do not response. I have tried few time.
 `kubectl get configmap` gives No resources found 
Is there any command to restart the worker node for Management UI? Other services running fine

**Comment by benzhi2011** [comment]
`kubectl --namespace=kube-system get pods`
`kubectl --namespace=kube-system delete pod kubernetes-dashboard-5fd84f4858-xlpl4`
pod "kubernetes-dashboard-5fd84f4858-xlpl4" deleted
How do I recreate the dashboard?

**Comment by maciaszczykm** [comment]
It should be done automtically by deployment. Check again for their presence with `kubectl --namespace=kube-system get pods`.

**Comment by benzhi2011** [comment]
Thanks, I have already done that, a new pod is up and running but the dashboard is not responding.
E1018 10:45:03.240630    4012 portforward.go:331] an error occurred forwarding 8001 -> 9090: error forwarding port 9090 to pod 46d561363bc92372aba13e845aded76fae35298db37a401f63c757b52de5ed01, uid : exit status 1: 2018/10/18 08:45:03 socat[432] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused

**Comment by benzhi2011** [comment]
`E1018 10:53:07.379024   30728 portforward.go:331] an error occurred forwarding 8001 -> 9090: error forwarding port 9090 to pod 46d561363bc92372aba13e845aded76fae35298db37a401f63c757b52de5ed01, uid : exit status 1: 2018/10/18 08:53:07 socat[24433] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-acs\azure\cli\command_modules\acs\custom.py", line 93, in wait_then_open
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 526, in open
  File "urllib\request.py", line 544, in _open
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 1346, in http_open
  File "urllib\request.py", line 1321, in do_open
  File "http\client.py", line 1331, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 266, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response`

I don‘t know this is an AKS problem or Kubernetes problem, but if this happens in production we cannot access to management UI, then it would block some work I think.

**Comment by maciaszczykm** [comment]
Seems like nothing connected directly to the Dashboard. At least not looking into these errors.

Are you able to access any other app?

**Comment by benzhi2011** [comment]
@maciaszczykm Yes, I have two other apps were running fine. Its difficult to say this is a AKS problem or its pure Kubernetes dashboard problem. Since it is test cluster, I just wiped everything and created a new one.

**Comment by maciaszczykm** [comment]
@benzhi2011 And the problem is gone?

**Comment by benzhi2011** [comment]
Yes for now, it is completely new cluster. But if this happens for a production cluster, I cannot just delete it and create a new one

**Comment by maciaszczykm** [comment]
@benzhi2011 Okay, so perhaps it was some misconfiguration. Please reopen if the problem will appear again.

/close
