### ISSUE TITLE
Establish release process procedure

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#330]
We should establish reliable release process to be included as a default addon for K8s clusters. Here's my proposal. 

For each release:

1. Send a pull request that increases version number in `build/conf.js`. Follow semver versioning: http://semver.org/. 
1. The pull request should contain release notes written in `CHANGELOG.md`. 
1. Get it reviewed and merged.
1. Create a git tag for the merged PR. With the name the same as the version.
1. Build and push images to GCR with `gulp push-to-gcr`.
1. Update addons configuration in k8s core.

**Comment by bryk** [comment]
@floreks @maciaszczykm @cheld Please review.

**Comment by cheld** [comment]
Sounds very good to me. 

Step 4-5: I assume this is done manually.

BTW:
* Do we plan to run tests in a real cluster with a real setup? 

* At some point in time we were thinking about executing tests against multiple versions of Kubernetes. 

I don't think this should be part of the release process, but where would that fit in?

**Comment by floreks** [comment]
LGTM :)

Are we going to push images for different architectures or only main one?

**Comment by maciaszczykm** [comment]
It's good to have this. LGTM

**Comment by luxas** [comment]
LGTM. 

How about release branches like `release-1.0` or something when this is stable? Is it necessary/an option?
For how long will you support e.g. different k8s releases and for how long is `dashboard` backwards-compatible.

**Comment by bryk** [comment]
> How about release branches like release-1.0 or something when this is stable?

But discussions about this haven't happened yet. We can either go with having only one version (i.e., the latest) or support a few major releases.

> For how long will you support e.g. different k8s releases and for how long is dashboard backwards-compatible.

We're aiming for the same support horizon as k8s core. This means that the UI should work on any cluster that is not extremely out of date.

**Comment by bryk** [comment]
Followup proposal:

Start using conventional commit messages to facilitate writing release notes and have better git history. Info: https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.uyo6cb12dt6w

@maciaszczykm @cheld @floreks @taimir @batikanu Review please.

**Comment by bryk** [comment]
Ping?

**Comment by maciaszczykm** [comment]
How should we use it for us? I agree, that one naming convention is good idea, but should we use exactly the same pattern as AngularJS?

```
feat($browser): onUrlChange event (popstate/hashchange/polling)

Added new event to $browser:
- forward popstate event if available
- forward hashchange event if popstate not available
- do polling when neither popstate nor hashchange available

Breaks $browser.onHashChange, which was removed (use onUrlChange instead)
```
```
fix($compile): couple of unit tests for IE9

Older IEs serialize html uppercased, but IE9 does not...
Would be better to expect case insensitive, unfortunately jasmine does
not allow to user regexps for throw expectations.

Closes #392
Breaks foo.bar api, foo.baz should be used instead
```
```
feat(directive): ng:disabled, ng:checked, ng:multiple, ng:readonly, ng:selected

New directives for proper binding these attributes in older browsers (IE).
Added coresponding description, live examples and e2e tests.

Closes #351
```
```
style($location): add couple of missing semi colons

docs(guide): updated fixed docs from Google Docs

Couple of typos fixed:
- indentation
- batchLogbatchLog -> batchLog
- start periodic checking
- missing brace
```
```
feat($compile): simplify isolate scope bindings

Changed the isolate scope binding options to:
  - @attr - attribute binding (including interpolation)
  - =model - by-directional model binding
  - &expr - expression execution binding

This change simplifies the terminology as well as
number of choices available to the developer. It
also supports local name aliasing from the parent.

BREAKING CHANGE: isolate scope bindings definition has changed and
the inject option for the directive controller injection was removed.

To migrate the code follow the example below:

Before:

scope: {
  myAttr: 'attribute',
  myBind: 'bind',
  myExpression: 'expression',
  myEval: 'evaluate',
  myAccessor: 'accessor'
}

After:

scope: {
  myAttr: '@',
  myBind: '@',
  myExpression: '&',
  // myEval - usually not useful, but in cases where the expression is assignable, you can use '='
  myAccessor: '=' // in directive's template change myAccessor() to myAccessor
}

The removed `inject` wasn't generaly useful for directives so there should be no code using it
```

Or should we create own pattern? I'm not convinced about modules put in brackets, we should define them so everyone will use the same.

**Comment by bryk** [comment]
@maciaszczykm After a second thought I think that conventional commits from AngularJS do not make sense for our project. We're a consumer product rather than a library.

**Comment by bryk** [comment]
Agree to drop the conventional commits proposal?

**Comment by maciaszczykm** [comment]
We should borrow some good ideas from them, for example using one form of verb is good. `Fix` instead of `Fixed`, `Fixing` etc. looks good. Also we can decide if we are using capital letters and dots :)

**Comment by cheld** [comment]
I think in some projects (like a database development) commit history is very helpful and used intensively. In UI projects commit history is typically not used much. So, I would suggest to focus on the needs of creating release notes.
