### ISSUE TITLE
Show zero state page even when there are things in kube-system namespace

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#331]
kube-system namespace is not intended for end-users, so we should show zero state even if there's something there. We can also show a link to bypass zerostate and show RCs anyway.

**Comment by digitalfishpond** [comment]
I can look into this

**Comment by digitalfishpond** [comment]
I have a solution for showing zero state if there are only things in kube-system namespace, but I have a question: if there are things in the kube-system namespace but also in other namespaces, do you want to show the pods that are in the kube-space namespace with the others? or do you want them always hidden?

**Comment by floreks** [comment]
I think this is not related to this issue and actual display of replication controllers in namespaces will be handled with #348. Only thing that should be done here is to check if there are any RC available to display in namespaces other than `kube-system`, if no then redirect to zerostate.

**Comment by maciaszczykm** [comment]
I agree with @floreks. I think at the moment we should only redirect and solve filtering issue later.

**Comment by digitalfishpond** [comment]
sounds good to me

**Comment by digitalfishpond** [comment]
...and add a link on zero-state page if there are RCs available in the kube-system namespace.

**Comment by bryk** [comment]
Correct :)

**Comment by digitalfishpond** [comment]
Sorry @bryk , I'm still working on a test for this. Slowly working out how to :/ Already discussed with @cheld and @floreks  has said he will give me a hand later today to get this finished.

**Comment by bryk** [comment]
Oh, forgot about this. Thanks.
