### ISSUE TITLE
Remember user's selected namespace

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/dashboard#3312]
##### Environment

```
Dashboard version: 1.10.0
Kubernetes version: 1.11.2
Operating system: Debian Stretch
```

In my case, we're using the Authorization header for authenticating users.

##### Steps to reproduce

1. Navigate and log in to the dashboard
2. Get taken to the overview page, current namespace will be `default`
3. Select a different namespace
4. Close browser tab
5. Navigate back to the dashboard
6. Get taken to the overview page again, current namespace will still be `default`

##### Observed result

See above

##### Expected result

I'd like it if the namespace selected would persist for the given user.

##### Comments

I'm not opinionated on how to accomplish this. Cookies or values in a ConfigMap (keyed by username), either would work.

**Comment by floreks** [comment]
We'll track that from #2618
