### ISSUE TITLE
输入访问令牌后，点击登陆按钮没有响应

### ISSUE THREAD

**Issue by rainqinchina** [kubernetes/dashboard#3331]
##### Environment

```
Dashboard version: 
Kubernetes version:
![image](https://user-images.githubusercontent.com/8306053/48194807-f6c58f80-e388-11e8-9690-9d1fa49fd428.png)
![image](https://user-images.githubusercontent.com/8306053/48194920-4d32ce00-e389-11e8-804d-55c6201dd0cd.png)
![image](https://user-images.githubusercontent.com/8306053/48194963-6b98c980-e389-11e8-867d-bff91e569db1.png)
![image](https://user-images.githubusercontent.com/8306053/48195019-8f5c0f80-e389-11e8-9b3b-fd618f02afbb.png)
![image](https://user-images.githubusercontent.com/8306053/48195131-bd415400-e389-11e8-9605-5190d5d89b5b.png)
![image](https://user-images.githubusercontent.com/8306053/48195232-042f4980-e38a-11e8-8936-ac75a161f2ce.png)


Operating system: CentOS 7.3
Node.js version:
Go version:
```

**Comment by rainqinchina** [comment]
![image](https://user-images.githubusercontent.com/8306053/48195268-20cb8180-e38a-11e8-80d2-99a331e144d6.png)

**Comment by rainqinchina** [comment]
![image](https://user-images.githubusercontent.com/8306053/48195350-6425f000-e38a-11e8-9f3c-2085c72fa59d.png)
![image](https://user-images.githubusercontent.com/8306053/48195384-7a33b080-e38a-11e8-97ea-3aafbb8f267b.png)

**Comment by maciaszczykm** [comment]
You have to write in english. Please create new issue and fill the template. Otherwise we are not able to help.

/close

**Comment by rainqinchina** [comment]
@maciaszczykm  After entering the access token, clicking the login button does not respond

**Comment by maciaszczykm** [comment]
From https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above:

> NOTE: Dashboard should not be exposed publicly over HTTP. For domains accessed over HTTP it will not be possible to sign in. Nothing will happen after clicking Sign in button on login page.
