### ISSUE TITLE
Dashboard `kubectl apply` fails on latest minikube

### ISSUE THREAD

**Issue by elliotmrodriguez** [kubernetes/dashboard#3333]
##### Environment

```
Dashboard version: current
Kubernetes version: server 1.10, client 1.12
Operating system: OSX Mojave
Node.js version:
Go version:
```

##### Steps to reproduce
run minikube
deploy Dashboard

##### Observed result

```
secret/kubernetes-dashboard-certs created
serviceaccount/kubernetes-dashboard created
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
service/kubernetes-dashboard configured

The Deployment "kubernetes-dashboard" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"k8s-app":"kubernetes-dashboard"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

##### Expected result

```secret/kubernetes-dashboard-certs created
serviceaccount/kubernetes-dashboard created
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
deployment.apps/kubernetes-dashboard created
service/kubernetes-dashboard created
```

##### Comments
Response from the proxy endpoint:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Comment by maciaszczykm** [comment]
I think minikube deploys Dashboard by default, so during `kubectl apply` it tries to update (apply) immutable field (label selector). Can you list deployments that are already in your cluster? Is there Dashboard? Can you run `kubectl describe` on it and check if is has the same label selector?

This is config issue, because on an empty cluster it works.

/triage support

**Comment by elliotmrodriguez** [comment]
I could not get this working on an empty cluster, using minikube 0.30. There are no deployments. This morning I upgraded minikube from 0.28 to 0.30.

I realized I could do `minikube dashboard` but I get Temporary Error unexpected response code : 503 errors.

One thing I notice when looking at the logs for the container, Liveness probes fail. I also noticed it looks like it's trying to pull an older image instead of 1.10.

```
Normal   SuccessfulMountVolume  4m8s                  kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-797gp"
  Warning  Unhealthy              3m35s                 kubelet, minikube  Liveness probe failed: Get http://172.17.0.4:9090/: dial tcp 172.17.0.4:9090: getsockopt: connection refused
  Normal   Pulled                 68s (x4 over 4m7s)    kubelet, minikube  Container image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.1" already present on machine
  Normal   Created                67s (x4 over 4m7s)    kubelet, minikube  Created container
  Normal   Started                67s (x4 over 4m6s)    kubelet, minikube  Started container
  Warning  BackOff                35s (x10 over 3m35s)  kubelet, minikube  Back-off restarting failed container
```

**Comment by maciaszczykm** [comment]
Please provide results of:
- `kubectl get deployments --all-namespaces`
- `kubectl get pods --all-namespaces`
- `kubectl describe kubernetes-dashboard -n kube-system`

**Comment by elliotmrodriguez** [comment]
```
10:34 $ kubectl get deployment --all-namespaces
NAMESPACE      NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
istio-system   grafana                1         1         1            1           136d
istio-system   istio-ca               1         1         1            1           136d
istio-system   istio-ingress          1         1         1            0           136d
istio-system   istio-mixer            1         1         1            1           136d
istio-system   istio-pilot            1         1         1            0           136d
istio-system   prometheus             1         1         1            1           136d
istio-system   servicegraph           1         1         1            1           136d
istio-system   zipkin                 1         1         1            1           136d
kube-system    coredns                1         1         1            0           2h
kube-system    kube-dns               1         1         1            0           137d
kube-system    kubernetes-dashboard   1         1         1            0           137d
✔ ~ 
10:35 $ kubectl get pods --all-namespaces
NAMESPACE      NAME                                    READY   STATUS             RESTARTS   AGE
istio-system   grafana-bd4db4cc6-flnvl                 1/1     Running            4          136d
istio-system   istio-ca-5fd466bc8-kwspm                1/1     Running            4          136d
istio-system   istio-ingress-844b4cd647-gpvlr          0/1     CrashLoopBackOff   38         136d
istio-system   istio-mixer-69c67f7f7-9wx52             3/3     Running            12         136d
istio-system   istio-pilot-665d57b889-pxwnv            1/2     CrashLoopBackOff   43         136d
istio-system   prometheus-7556c5b7b6-lr2hc             1/1     Running            4          136d
istio-system   servicegraph-7b96b8d556-nn4hz           1/1     Running            4          136d
istio-system   zipkin-648b887bf6-dfr7f                 1/1     Running            4          136d
kube-system    coredns-c4cffd6dc-qh7lb                 0/1     CrashLoopBackOff   38         2h
kube-system    etcd-minikube                           1/1     Running            0          11m
kube-system    kube-addon-manager-minikube             1/1     Running            3          2h
kube-system    kube-apiserver-minikube                 1/1     Running            0          11m
kube-system    kube-controller-manager-minikube        1/1     Running            1          11m
kube-system    kube-dns-86f4d74b45-gwp7j               1/3     CrashLoopBackOff   109        137d
kube-system    kube-proxy-rz46k                        1/1     Running            0          10m
kube-system    kube-scheduler-minikube                 1/1     Running            6          136d
kube-system    kubernetes-dashboard-5498ccf677-7q495   0/1     CrashLoopBackOff   12         25m
kube-system    storage-provisioner                     0/1     CrashLoopBackOff   43         137d
✔ ~ 
10:35 $ kubectl describe kubernetes-dashboard -n kube-system
error: the server doesn't have a resource type "kubernetes-dashboard"
```

**Comment by maciaszczykm** [comment]
Sorry, last one should be `kubectl describe deployment kubernetes-dashboard -n kube-system`.

**Comment by elliotmrodriguez** [comment]
Hah, read my mind - 

```
Name:                   kubernetes-dashboard
Namespace:              kube-system
CreationTimestamp:      Fri, 09 Nov 2018 09:05:29 -0500
Labels:                 k8s-app=kubernetes-dashboard
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"kubernetes-dashboard"},"name":"kubernet...
Selector:               k8s-app=kubernetes-dashboard
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           k8s-app=kubernetes-dashboard
  Service Account:  kubernetes-dashboard
  Containers:
   kubernetes-dashboard:
    Image:      k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      --auto-generate-certificates
    Liveness:     http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
  Volumes:
   kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
   tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kubernetes-dashboard-7b9c7bc8c9 (1/1 replicas created)
Events:          <none>
```

**Comment by maciaszczykm** [comment]
I can clearly see that your cluster is not empty and the dashboard is already running inside it.

Try to use manual from https://github.com/kubernetes/minikube:

> Dashboard
>
> To access the Kubernetes Dashboard, run this command in a shell after starting Minikube to get the address:
>
>```
>minikube dashboard
>```

**Comment by maciaszczykm** [comment]
> kube-system    kubernetes-dashboard-5498ccf677-7q495   0/1     CrashLoopBackOff   12         25m

Check also `kubectl logs kubernetes-dashboard-5498ccf677-7q495 -n kube-system`.

**Comment by maciaszczykm** [comment]
You can try to fix it with `kubectl delete pod kubernetes-dashboard-5498ccf677-7q495 -n kube-system`. Pod should be recreated.

**Comment by elliotmrodriguez** [comment]
I've deleted the pod a number of times now.  I will just use docker-for-desktop, as it seems to be pointing to the correct image and working.

**Comment by bestbelief** [comment]
@maciaszczykm @maciaszczykm Hello, I also met this problem,Can you help me see it?
`dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo  kubectl get deployments --all-namespaces
NAMESPACE     NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   coredns                1         1         1            1           23m
kube-system   kube-dns               1         1         1            1           23m
kube-system   kubernetes-dashboard   1         1         1            1           23m
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo  kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
kube-system   coredns-5bfd87b64b-l9ftj               1/1     Running   0          24m
kube-system   etcd-minikube                          1/1     Running   0          23m
kube-system   kube-addon-manager-minikube            1/1     Running   0          23m
kube-system   kube-apiserver-minikube                1/1     Running   0          23m
kube-system   kube-controller-manager-minikube       1/1     Running   0          23m
kube-system   kube-dns-b4bd9576-7xfqh                3/3     Running   0          24m
kube-system   kube-proxy-p87nb                       1/1     Running   0          24m
kube-system   kube-scheduler-minikube                1/1     Running   0          24m
kube-system   kubernetes-dashboard-866c7586d-m7lxp   1/1     Running   0          24m
kube-system   storage-provisioner                    1/1     Running   0          24m
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ kubectl describe deployment kubernetes-dashboard -n kube-system
error: Error loading config file "/home/dev/.kube/config": open /home/dev/.kube/config: permission denied
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo kubectl describe deployment kubernetes-dashboard -n kube-system
Name:                   kubernetes-dashboard
Namespace:              kube-system
CreationTimestamp:      Wed, 20 Feb 2019 10:40:57 +0800
Labels:                 addonmanager.kubernetes.io/mode=Reconcile
                        kubernetes.io/minikube-addons=dashboard
                        version=v1.10.0
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernet...
Selector:               addonmanager.kubernetes.io/mode=Reconcile,app=kubernetes-dashboard,version=v1.10.0
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  addonmanager.kubernetes.io/mode=Reconcile
           app=kubernetes-dashboard
           version=v1.10.0
  Containers:
   kubernetes-dashboard:
    Image:        registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:v1.10.0
    Port:         9090/TCP
    Host Port:    0/TCP
    Liveness:     http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kubernetes-dashboard-866c7586d (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  25m   deployment-controller  Scaled up replica set kubernetes-dashboard-866c7586d to 1
dev@ubuntu:/work/dev/project/angular-pen/dashboard$`

**Comment by bestbelief** [comment]
hello,I also met this problem. Can you help me see it?

> dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo  kubectl get deployments --all-namespaces
NAMESPACE     NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   coredns                1         1         1            1           23m
kube-system   kube-dns               1         1         1            1           23m
kube-system   kubernetes-dashboard   1         1         1            1           23m
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo  kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
kube-system   coredns-5bfd87b64b-l9ftj               1/1     Running   0          24m
kube-system   etcd-minikube                          1/1     Running   0          23m
kube-system   kube-addon-manager-minikube            1/1     Running   0          23m
kube-system   kube-apiserver-minikube                1/1     Running   0          23m
kube-system   kube-controller-manager-minikube       1/1     Running   0          23m
kube-system   kube-dns-b4bd9576-7xfqh                3/3     Running   0          24m
kube-system   kube-proxy-p87nb                       1/1     Running   0          24m
kube-system   kube-scheduler-minikube                1/1     Running   0          24m
kube-system   kubernetes-dashboard-866c7586d-m7lxp   1/1     Running   0          24m
kube-system   storage-provisioner                    1/1     Running   0          24m
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ kubectl describe deployment kubernetes-dashboard -n kube-system
error: Error loading config file "/home/dev/.kube/config": open /home/dev/.kube/config: permission denied
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo kubectl describe deployment kubernetes-dashboard -n kube-system
Name:                   kubernetes-dashboard
Namespace:              kube-system
CreationTimestamp:      Wed, 20 Feb 2019 10:40:57 +0800
Labels:                 addonmanager.kubernetes.io/mode=Reconcile
                        kubernetes.io/minikube-addons=dashboard
                        version=v1.10.0
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernet...
Selector:               addonmanager.kubernetes.io/mode=Reconcile,app=kubernetes-dashboard,version=v1.10.0
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  addonmanager.kubernetes.io/mode=Reconcile
           app=kubernetes-dashboard
           version=v1.10.0
  Containers:
   kubernetes-dashboard:
    Image:        registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:v1.10.0
    Port:         9090/TCP
    Host Port:    0/TCP
    Liveness:     http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kubernetes-dashboard-866c7586d (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  25m   deployment-controller  Scaled up replica set kubernetes-dashboard-866c7586d to 1
dev@ubuntu:/work/dev/project/angular-pen/dashboard$

**Comment by bestbelief** [comment]
hello,I also met this problem. How did you solve this proble
`dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo  kubectl get deployments --all-namespaces
NAMESPACE     NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   coredns                1         1         1            1           23m
kube-system   kube-dns               1         1         1            1           23m
kube-system   kubernetes-dashboard   1         1         1            1           23m
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo  kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
kube-system   coredns-5bfd87b64b-l9ftj               1/1     Running   0          24m
kube-system   etcd-minikube                          1/1     Running   0          23m
kube-system   kube-addon-manager-minikube            1/1     Running   0          23m
kube-system   kube-apiserver-minikube                1/1     Running   0          23m
kube-system   kube-controller-manager-minikube       1/1     Running   0          23m
kube-system   kube-dns-b4bd9576-7xfqh                3/3     Running   0          24m
kube-system   kube-proxy-p87nb                       1/1     Running   0          24m
kube-system   kube-scheduler-minikube                1/1     Running   0          24m
kube-system   kubernetes-dashboard-866c7586d-m7lxp   1/1     Running   0          24m
kube-system   storage-provisioner                    1/1     Running   0          24m
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ kubectl describe deployment kubernetes-dashboard -n kube-system
error: Error loading config file "/home/dev/.kube/config": open /home/dev/.kube/config: permission denied
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ sudo kubectl describe deployment kubernetes-dashboard -n kube-system
Name:                   kubernetes-dashboard
Namespace:              kube-system
CreationTimestamp:      Wed, 20 Feb 2019 10:40:57 +0800
Labels:                 addonmanager.kubernetes.io/mode=Reconcile
                        kubernetes.io/minikube-addons=dashboard
                        version=v1.10.0
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernet...
Selector:               addonmanager.kubernetes.io/mode=Reconcile,app=kubernetes-dashboard,version=v1.10.0
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  addonmanager.kubernetes.io/mode=Reconcile
           app=kubernetes-dashboard
           version=v1.10.0
  Containers:
   kubernetes-dashboard:
    Image:        registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:v1.10.0
    Port:         9090/TCP
    Host Port:    0/TCP
    Liveness:     http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kubernetes-dashboard-866c7586d (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  25m   deployment-controller  Scaled up replica set kubernetes-dashboard-866c7586d to 1`
