### ISSUE TITLE
Details page is really wide. Make it work on smaller screens.

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#334]
When you open the details page on, e.g., 13 inch laptop, it does not feel good. Even worse on mobile or tablet. Can we make something to fit all details on one screen? Maybe hide left nav into a tab?

**Comment by bryk** [comment]
@floreks @maciaszczykm Opinions?

**Comment by floreks** [comment]
I agree. We could just show small tab with arrow back and button that would expand the sidebar over the current view. Clicking outside of it would hide it again. What do you think?

**Comment by maciaszczykm** [comment]
I think, that adding possibility to hide sidebar would be very nice feature. We can hide details into another tab and like @floreks mentioned, we can add `hide/show` switch. Second option however won't solve all problems on mobiles, because with expanded sidebar there will be no difference to current state.

**Comment by bryk** [comment]
Re show/hide on the details on the left: the problem with this is that on the left hand side we'll likely have a navigation menu. So having two hide/show left menus would not look great. Opinions?

**Comment by maciaszczykm** [comment]
@bryk Menu and the sidebar on the same side would be too much. I'm for changing sidebar into tab of existing `md-tabs` then.

**Comment by maciaszczykm** [comment]
@bryk Should we change sidebar into new `md-tab`? I can create PR for this.

**Comment by bryk** [comment]
Hmm.... I dont know. Do you want to just move details to a tab, or hide/show it based on screen width?

**Comment by maciaszczykm** [comment]
Yes, moving it to tab in all cases seems to be not the best idea... Maybe it should be done only in specific cases. But it means **a lot** of refactoring. I'll play with it and check if I'll have any good idea.

**Comment by floreks** [comment]
I was thinking about effect similar to this: When width is too small then sidebar can be shown like that with some button to show/hide.

http://gfycat.com/PracticalZanyEasternglasslizard

**Comment by bryk** [comment]
@floreks Yeah, this is cool, but I'm pretty sure we should reserve this kind of behavior for application wide menu. Do you agree?

**Comment by floreks** [comment]
That's a good point. I agree.

**Comment by maciaszczykm** [comment]
I'm working on this. It'll take some time though.

**Comment by bryk** [comment]
@maciaszczykm Can you describe the behavior you're working on? Or are you just experimenting?

**Comment by maciaszczykm** [comment]
I'm experimenting, but I've got some concept. It's not yet fully ready, but you can check my `details-styling` branch. General idea is to move sidebar to `md-tab` if page is too narrow.

**Comment by batikanu** [comment]
I think md-tab solution from @maciaszczykm looks practical right now. If we use show/hide menu, we need to replace kubernetes logo with menu icon in small sizes or let it open from right side and locate the icon on the right corner.

**Comment by batikanu** [comment]
At smartphone size still the events and pods table should be scrolled horizontally a lot to see one line. There is also an option for table rows like in this example https://css-tricks.com/examples/ResponsiveTables/responsive.php by making each row its own table.

**Comment by batikanu** [comment]
Or freeze the first column and scroll the rest

**Comment by maciaszczykm** [comment]
@batikanu It's nice idea. It can be done in next pull request.

**Comment by bryk** [comment]
@batikanu The responsive table you've linked looks really nice! :) Thanks for finding it. We can iterate on this in a next PR.

**Comment by maciaszczykm** [comment]
I'm starting to work on responsive table to close this issue.

**Comment by bryk** [comment]
Ok, go for something easy and simple :)

**Comment by floreks** [comment]
@bryk what do you think about using this directive 
https://github.com/awerlang/angular-responsive-tables

It's simple and easy to style.

**Comment by maciaszczykm** [comment]
I agree with @floreks, I'll try to use it.

**Comment by maciaszczykm** [comment]
There is one issue with this directive. After transforming table into smaller ones, tooltips near headers aren't available. In my opinion we should proceed with it anyways and then think about workaround for it.
