### ISSUE TITLE
DashBoard get pods is  CrashLoopBackOff

### ISSUE THREAD

**Issue by Lemon-le** [kubernetes/dashboard#3342]
##### Environment
```
Dashboard version:  v1.10
Kubernetes version: v1.10.10
```

##### Steps to reproduce
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result

kubectl get pods --all-namespaces   

[root@ip-172-29-1-113 bin]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
default       frontend-52tff                          1/1       Running            0          17h
default       frontend-bzt74                          1/1       Running            0          17h
default       frontend-gfdrl                          1/1       Running            0          17h
default       redis-master-55v95                      1/1       Running            0          17h
default       redis-slave-5gm7f                       1/1       Running            0          17h
default       redis-slave-z8znk                       1/1       Running            0          17h
kube-system   kubernetes-dashboard-7b9c7bc8c9-hcw5v   0/1       CrashLoopBackOff   7          15m

docker logs 

2018/11/15 02:41:35 Starting overwatch
panic: Could not create client config. Check logs for more information

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initInsecureClient(0xc4201f5f20)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:335 +0x9a
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc4201f5f20)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:297 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:365 +0x84
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:94 +0x13b
2018/11/15 02:41:35 Using in-cluster config to connect to apiserver
2018/11/15 02:41:35 Could not init in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2018/11/15 02:41:35 Using random key for csrf signing
2018/11/15 02:41:35 No request provided. Skipping authorization

##### Expected result
How resolve this problem? this problem is version question？

**Comment by jeefy** [comment]
You should be seeing a lot more pods than just those six if you're using `--all-namespaces`. Also with this error: `2018/11/15 02:41:35 Could not init in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory` I think one of two things is wrong:

1. The credentials you're connecting with with via `kubectl` _may_ be wrong
2. There is something wrong with your cluster.

Can you look into either of these first before we dive deeper?

Thanks!

/triage needs-information

**Comment by floreks** [comment]
It is an issue with your cluster. `/var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory` means that service accounts are not configured in your cluster. They are required to start dashboard.

**Comment by sriramperumalla** [comment]
Hi @floreks 
I do see the same issue for my dashboard service. It goes into CrashLoopBackOff status. I am writing after trying various things for two days. Please find the steps I followed to deploy kubernetes-dashboard in attached text file. You help is much appreciated as I am doing pilot project in my office.
Cheers,
Sriram
[Git-Issues-Created.txt](https://github.com/kubernetes/dashboard/files/4005021/Git-Issues-Created.txt)
