### ISSUE TITLE
Tracker for fixing Tide config

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3343]
https://github.com/kubernetes/test-infra/pull/10149

**Comment by maciaszczykm** [comment]
Done :)

/close

**Comment by maciaszczykm** [comment]
Got the wrong context name (see: https://github.com/kubernetes/dashboard/pull/3529):

![zrzut ekranu 2019-01-21 o 11 22 19](https://user-images.githubusercontent.com/2823399/51468296-e198b400-1d6e-11e9-8e00-834bfa58f4f1.png)

**Comment by BenTheElder** [comment]
I think this is fixed now ref https://github.com/kubernetes/test-infra/issues/10921 https://github.com/kubernetes/test-infra/pull/10922 -- just saw a dashboard PR go through tide.

**Comment by maciaszczykm** [comment]
It is. Thanks once more.

/close
