### ISSUE TITLE
GKE docs statement "highly privileged Kubernetes Service Account"

### ISSUE THREAD

**Issue by jimangel** [kubernetes/dashboard#3351]
##### Environment
```
Dashboard version: 1.8.3 (default for GKE)
Kubernetes version: 1.9.7 (default for GKE)
Operating system: Container-Optimized OS from Google (default for GKE)
Node.js version: n/a
Go version: n/a
```

##### Steps to reproduce
```
gcloud container clusters create $CLUSTER --network "default" --num-nodes 1 --zone $ZONE \
--machine-type n1-standard-1 --zone $ZONE \
--disk-size 50 --scopes storage-full  \
--addons=KubernetesDashboard

kubectl -n kube-system edit pod kubernetes-dashboard-7c4ff76bd4-9tksn
# see: args
```

##### Observed result
Dashboard launches but the config spec contains a warning stating: "We recommend that you [disable the Kubernetes Web UI](https://cloud.google.com/blog/products/gcp/precious-cargo-securing-containers-with-kubernetes-engine-18). Use [Cloud Console](https://console.cloud.google.com) instead."

##### Expected result
No injected banner to the deployment spec.

##### Comments
I was working on https://github.com/kubernetes/dashboard/issues/1719 and playing with GKE. I noticed that the default cluster build includes the following yaml:

```
spec:
  containers:
  - args:
    - --system-banner=We <a href="https://goo.gl/yRsHKB">recommend that you disable</a>
      the Kubernetes Web UI. Use <a href="https://console.cloud.google.com">Cloud
      Console</a> instead.
    - --system-banner-severity=WARNING
```

I checked the dashboard service account and saw:
```
$ kubectl describe -n kube-system role kubernetes-dashboard-minimal
Name:         kubernetes-dashboard-minimal
Labels:       addonmanager.kubernetes.io/mode=Reconcile
              k8s-app=kubernetes-dashboard
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-ap...
PolicyRule:
  Resources       Non-Resource URLs  Resource Names                     Verbs
  ---------       -----------------  --------------                     -----
  configmaps      []                 [kubernetes-dashboard-settings]    [get update]
  secrets         []                 [kubernetes-dashboard-certs]       [get update delete]
  secrets         []                 [kubernetes-dashboard-key-holder]  [get update delete]
  services        []                 [heapster]                         [proxy]
  services/proxy  []                 [heapster]                         [get]
  services/proxy  []                 [http:heapster:]                   [get]
  services/proxy  []                 [https:heapster:]                  [get]
```

That doesn't seem too terrible considering their [documentation](https://cloud.google.com/blog/products/gcp/precious-cargo-securing-containers-with-kubernetes-engine-18) states: "We recommend you disable the Kubernetes Web UI when running on Kubernetes Engine. The Kubernetes Web UI (aka KubernetesDashboard) is backed by a highly privileged Kubernetes Service Account. The Cloud Console provides much of the same functionality, so you don't need these permissions if you're running on Kubernetes Engine."

Is that statement still correct?

**Comment by floreks** [comment]
Definitely not correct based on shown policy rules. It has only access to dashboard exclusive resources and nothing else.
