### ISSUE TITLE
Dashboard realated issue

### ISSUE THREAD

**Issue by waytoharish** [kubernetes/dashboard#3352]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

**Comment by waytoharish** [comment]
I am trying to acess the DashBoard with aces Token but getting below error-
"roles.rbac.authorization.k8s.io is forbidden: User "system:anonymous" cannot"

Created a admin user as mentioned -
![image](https://user-images.githubusercontent.com/5119613/48842875-7442c400-edbb-11e8-85ac-9c5373147eca.png)

but still same error.Please suggest

**Comment by floreks** [comment]
Not enough information about setup. Reopen once all the information are provided and steps to reproduce are clear.
