### ISSUE TITLE
square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by sfxworks** [kubernetes/dashboard#3356]
##### Steps to reproduce

1. Kubectl reset & kubectl init because you're trying to learn
2. Use kube-flannel
3. kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
4. Proxy / SSH Tunnel
5. Get the error.

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

##### Comments

A solution is to clear the browser's cache. Takes a good few minutes though.

**Comment by jeefy** [comment]
This is caused because cookies for a previous session remain and try to be re-used on a new cluster.

As you said, the solution is to clear the browser's cache. Another option that I often use is to use an Incognito window whenever accessing resources I know I'll respawn often.

/close
