### ISSUE TITLE
filter job which not belong to other workloads

### ISSUE THREAD

**Issue by zouyee** [kubernetes/dashboard#3357]
##### Environment

In the process of using, we found that cronjob will generate a large number of jobs, and in dashboard project, there is no filtering operation for this. For the jobs which has owner, we may filter them out better.
```
Dashboard version: master
Kubernetes version: 1.11
/kind feature
```

**Comment by maciaszczykm** [comment]
We should include this as advanced filtering options. Not by default.

/close
