### ISSUE TITLE
Port mapping input fails when 0 value is entered

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#336]
When you enter `0` value for port mapping value it gets ignored. 

Thanks @maciaszczykm for finding this problem.

**Comment by maciaszczykm** [comment]
I can take care of this. I sugesst to set minimum port number to `1`, because port `0` shouldn't be used. Otherwise I'll change validation method. 

@bryk What's your opinion about it?

**Comment by bryk** [comment]
Sounds good.
