### ISSUE TITLE
How to add the third module？

### ISSUE THREAD

**Issue by gary-fei** [kubernetes/dashboard#3363]
##### Environment
while i want to use js-yaml, i can't use "import yaml from 'js-yaml' " in "app/frontend/comon" after i do "npm install js-yaml"
```
Dashboard version:1.8.3
Kubernetes version:1.11
Operating system:linux
Node.js version:
Go version:1.10.3
```

##### Observed result

sudo ./build/run-gulp-in-docker.sh build
![image](https://user-images.githubusercontent.com/30195355/49132786-9aff7e00-f318-11e8-9469-09ea16592db3.png)

**Comment by floreks** [comment]
Due to our very specific build configuration it is hard to add modules that were not written in "angular way" and can't be injected into the angular pipeline. I'd recommend looking for angular friendly module.
