### ISSUE TITLE
The Service "kubernetes-dashboard" is invalid: 

### ISSUE THREAD

**Issue by kamal2222ahmed** [kubernetes/dashboard#3365]
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

##### Steps to reproduce

 kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
secret/kubernetes-dashboard-certs unchanged
serviceaccount/kubernetes-dashboard configured
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal configured
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal configured
deployment.apps/kubernetes-dashboard configured
The Service "kubernetes-dashboard" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'

**Comment by jeefy** [comment]
Hi Kamal,

I'm thinking this is an issue with your cluster and not with the dashboard. Could you please provide more information on your cluster? The Issue Template above asks for some specifics. Thanks!
