### ISSUE TITLE
apiserver-host incorrectly handles trailing slashes 

### ISSUE THREAD

**Issue by therc** [kubernetes/dashboard#338]
Setting --apisever-host to http://a.b.c.d:x results in broken requests like

http://a.b.c.d:x/v1/replicationcontrollers

I'm not sure exactly how that's happening. Perhaps APIPath should be set in the client config?

**Comment by bryk** [comment]
How do you run the Dashboard? I run it like this and it works.

```
[bryk@bryk dist (master)]$ ./dashboard --apiserver-host=http://localhost:8080
2016/02/08 11:27:30 Starting HTTP server on port 9090
2016/02/08 11:27:30 Creating API client for http://localhost:8080
2016/02/08 11:27:30 Creating Heapster REST client for http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster/api
```

**Comment by therc** [comment]
This is the setup:
```
        - --apiserver-host=http://a.b.c.d:8080/
        - --port=9090
```
Your log message doesn't guarantee anything, because I get that far, too:

```
2016/02/05 15:52:18 Starting HTTP server on port 9090
2016/02/05 15:52:18 Creating API client for http://a.b.c.d:8080/
2016/02/05 15:52:18 Creating Heapster REST client for http://a.b.c.d:8080/api/v1/proxy/namespaces/kube-system/services/heapster/api
```

It's when you actually try to open the dashboard that you find it's broken:

```
2016/02/05 16:12:30 Incoming HTTP/1.1 GET /api/replicationcontrollers request from x:y
2016/02/05 16:12:30 Getting list of all replication controllers in the cluster
2016/02/05 16:12:30 the server could not find the requested resource (get replicationControllers)
```

There's no way to log what it's doing, so with the help of tcpdump I found that it's trying to hit `/v1/replicationcontrollers` on the apiserver, without the leading `/api`.

**Comment by therc** [comment]
Now I'm wondering if this actually a bug in the client itself, not in the dashboard.

**Comment by bryk** [comment]
You have trailing slash at apiserver host `http://a.b.c.d:8080/`. Maybe removing it can fix this?

**Comment by therc** [comment]
Thanks... it's a bit crazy that the trailing slash makes a difference, but it does. I'm assuming I'll be the first of many.

**Comment by bryk** [comment]
Thanks for reporting this! :) We will fix the problem or document the behavior.

**Comment by bryk** [comment]
This is fixed. Apiserver host works with trailing slashes.
