### ISSUE TITLE
After deleting PODS , dashboard is refresh and setting are lost

### ISSUE THREAD

**Issue by pratikthorve90** [kubernetes/dashboard#3397]
##### Steps to reproduce
1 Open K8S dashboard , select namespace , click on PODS
2 Now sort the PODS according to the status
3 Delete one of the PODS
4 POD is deleted and screen is refreshed , but the PODS are not sorted as per the what i did in step 2

##### Observed result
PODS are not sorted as per the what i did in step 2

##### Expected result
User settings should not be disturbed

**Comment by jeefy** [comment]
@pratikthorve90 Thanks for letting us know.

Could you tell us which version of the dashboard you're using? 

Thanks!

**Comment by pratikthorve90** [comment]
@jeefy : below are the details.

Dashboard Version:
v1.10.0
Git Commit:
aa1b6c0c31c4b3b703e16e554a15ed2a019aad47

**Comment by floreks** [comment]
This is actually not a bug, but feature request. Dashboard does not store user specific settings right now in any way. I'd say that this falls under #2618. @maciaszczykm WDYT?

**Comment by maciaszczykm** [comment]
@floreks +1, it is a feature indeed.

At the moment we have only global settings. During the migration, we have added local ones (based on cookies) and we can work on that.

**Comment by floreks** [comment]
We'll track that from #2618
