### ISSUE TITLE
net/http: timeout awaiting response headers

### ISSUE THREAD

**Issue by zeed-w-beez** [kubernetes/dashboard#3398]
##### Steps to reproduce

refresh Deployments Detail page.

Url looks like: 
https://kubernetes-dashboard.xxx.com/#!/deployment/NAMESPACE/DEPLAYMENTNAME?namespace=NAMESPACE

##### Environment
```
Installation method: manual deploy on CoreOS
Kubernetes version: v1.11.3
Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
net/http: timeout awaiting response headers

```

##### Comments

![image](https://user-images.githubusercontent.com/20834022/49577068-97f03780-f981-11e8-9754-039581d89884.png)

**Comment by floreks** [comment]
Timeout means that there is a connection issue with the cluster. It is not a Dashboard issue.
