### ISSUE TITLE
Switch CI to dockerized builds

### ISSUE THREAD

**Issue by luxas** [kubernetes/dashboard#341]
I think we want to use the dockerized build for Travis CI at some point in the future.
Is it easy to do? Thoughts on that?
@bryk @cheld

**Comment by cheld** [comment]
My thoughts:

Advantages:
- run-gulp-in-docker.sh would be tested
- The build is not so dependant on travis

About easy:
``run-gulp-in-docker.sh check:local-cluster`` is the task that is executed on travis. If I run this command on my machine it seems not to complete... In general it creates a local-cluster and is doing some selenium click tests. You probably know better if this is easy or not.

**Comment by bryk** [comment]
Right now our travis config contains almost no project specific thing. Basically, it just runs `./node_modules/.bin/gulp check:local-cluster`.

So the benefit of running in docker on Travis would be testing our Docker config, right? Anything else?

**Comment by bryk** [comment]
This is not needed now, as the default Travis build system is good enough
