### ISSUE TITLE
shell in chrome does not show up - shows errors in console window

### ISSUE THREAD

**Issue by gparvind** [kubernetes/dashboard#3411]
```
Dashboard version: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.0
Kubernetes version: 1.11.5
```

##### Steps to reproduce
Navigate to "Exec" from a pod details page in dashboard.

##### Observed result
Blank Shell UI.
Errors in the console window:
![image](https://user-images.githubusercontent.com/1861655/49918725-2c9aee00-feca-11e8-8f0e-b536fd2a9977.png)

##### Expected result
Shell UI should come up

**Comment by floreks** [comment]
Not enough information about cluster and dashboard setup.
