### ISSUE TITLE
Improve error message after switching contexts without logging out

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#3417]
```
Dashboard reported Internal Server Error (500): square/go-jose: error in cryptographic primitive
```

There are a couple of scenarios in which this error will be thrown:
 1. Switching context without logging out.
    1. Start kubectl proxy
    1. Login to Dashboard
    1. Kill kubectl proxy, switch to another cluster and start it again
    1. Error is shown as a result of trying to decode token encrypted with key generated by other instance of Dashboard.
 1. Waiting until token expires and refreshing the page again

We should improve error handling here.

**Comment by greggbjensen** [comment]
Our company is running into this same issue.  We often switch clusters with the dashboard still open.  I have had to train around it for now.  Is there a way to just have it sign the user out when the message occurs?  I would be happy to work on it, if you have some direction for the fix.

**Comment by floreks** [comment]
The problem with your case is that killing proxy, basically kills access to the application. Then underneath a new connection is made and access to a completely different instance of Dashboard is granted. We can't really detect this and you can't guarantee that access to a new instance of Dashboard will always use the exact same version of the application. In this case manual refresh is required. In any other case, we already detect token expiration and encryption key change, and the user is automatically logged out.

It's basically like exposing some application A on localhost while working on it and then switching to application B. I can then kill the application A and start a dev server for application B. I can't expect that it will just work unless something triggers the external page refresh. 

https://github.com/kubernetes/dashboard/blob/53115e0984354340a7025a1b711aaec0b6b7b13b/src/app/frontend/error/handler.ts#L49-L57

**Comment by floreks** [comment]
To summarize in case of `kubectl proxy` current error is ok and manual refresh should be triggered by the user. Other cases are already handled by our error handler and use will be automatically logged out.

/close
