### ISSUE TITLE
Update external repos w/ v1.10.1 release

### ISSUE THREAD

**Issue by jeefy** [kubernetes/dashboard#3419]
Placeholder issue for me.

Once v1.10.1 is released, update external repos referencing Dashboard.

See: https://cs.k8s.io/?q=kubernetes%5C-dashboard%5C-&i=nope&files=&repos= for a (rough) list.

/assign

**Comment by jeefy** [comment]
/cc @maciaszczykm @floreks @bryk What's the status of cutting new images for the release? 

It doesn't look like the images have been created and the notes under the v1.10.1 release still say TBD. :(

I'm going to at least submit/hold all the PRs to do this so they're staged.

**Comment by jeefy** [comment]
https://github.com/kubernetes/kubernetes/pull/72141

https://github.com/kubernetes/minikube/pull/3466

https://github.com/kubernetes/kops/pull/6221

**Comment by floreks** [comment]
@jeefy They have just been pushed. I have updated release notes: https://github.com/kubernetes/dashboard/releases/tag/v1.10.1

**Comment by jeefy** [comment]
Awesome thanks! I removed the holds on the other PRs. 

I'll keep this open to remind myself to check on them periodically and nudge them along.

**Comment by jeefy** [comment]
There's a cherry-pick in k/k that requires an \approve before I can close this. :) 

https://github.com/kubernetes/kubernetes/pull/72496
