### ISSUE TITLE
Complete Angular migration

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3440]
Things left to do:

- [x] merge `ng-migration` to `master` branch
- [ ] ~~deployment list and details (85% done; missing: new replica set list, hpa list in details @daminisatya )~~
- [x] cron job list and details
- [x] align actionbar actions with context actions in list menu for every resource
- [ ] ~~graphs for cluster, nodes, overview, workloads, daemon sets, deployments, pods, rc, rs, and stateful sets (@eloyekunle)~~
- [ ] ~~error handling (@floreks)~~
- [x] remove skip button
- [x] update `README.md`
- [ ] ~~update wikis~~
- [x] workload statuses for workload and overview page (@ajatprabha)
- [ ] ~~tests~~
- [ ] ~~check `frontend_old` for any leftovers~~
- [ ] ~~solving all TODOs from the code~~
- [ ] ~~manual tests and final code review~~
- [ ] ~~release and annoucements~~

Related to #3152.

**Comment by junsionzhang** [comment]
is Angular migration done now and what is the plan ?

**Comment by floreks** [comment]
As you can see, there are still some pending tasks left to be implemented/fixed. Now, that the migration has been merged to master it will be easier to maintain and move forward with it.

**Comment by maciaszczykm** [comment]
@jeefy Do you have any updates about metrics container?

**Comment by jeefy** [comment]
@maciaszczykm It works! I'm still waiting on @DirectXMan12 to give it another look over (https://github.com/jeefy/metrics-sidecar) but after that I can PR in support for it (See https://github.com/kubernetes/dashboard/compare/master...jeefy:sidecar?expand=1) 

I still have to pull in the angular migration changes and apply them to that branch though.

**Comment by ajatprabha** [comment]
I'd like to work on `align actionbar actions with context actions in list menu for every resource` task.
cc: @maciaszczykm

**Comment by maciaszczykm** [comment]
@daminisatya You can take a look at one of following:

>- [ ] deployment list and details (85% done; missing: hpa list in details)
>  - [ ] cron job list and details (80% done; missing: inactive job list, trigger option in list, pause action)

We can discuss details here or at #sig-ui Slack.

**Comment by drazul** [comment]
Why you removed skip button on loging screen?
Are there a new way to avoid authentication?

All my team work on our local cluster before go to real cluster and we don't want to need to set up a new credential each time we need to use the dashboard.

**Comment by maciaszczykm** [comment]
@drazul Check `enable-skip-login` flag at https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments.

**Comment by daminisatya** [comment]
@maciaszczykm This is my current dashboard and the deployment metrics it's showing. Took some decent amount of time getting the metrics on the dashboard. 😟 

<img width="1660" alt="screen shot 1940-11-18 at 2 46 10 am" src="https://user-images.githubusercontent.com/6227784/52374217-b5757680-2a82-11e9-9cba-62f96a850400.png">

 Can you please further explain to me what exactly these hpa lists are, where to display the list details?

**Comment by maciaszczykm** [comment]
@daminisatya Of course. HPA is a shortcut from Horizontal Pod Autoscalers that we would like to display in the detail view of Deployments. So, when you enter the Deployments detail page you will be able to see all HPAs connected to it.

Implementation should be similar to what we have right now as we already display connected resources in the detail views of multiple resources. 

Here you can find the endpoints for HPAs:
https://github.com/kubernetes/dashboard/blob/1f2007d1f8e68646c10ae3b29e566b8a9b72f640/src/app/backend/handler/apihandler.go#L292

Here is backend implementation:
https://github.com/kubernetes/dashboard/tree/master/src/app/backend/resource/horizontalpodautoscaler

And there you can find old pre-migration code:
https://github.com/kubernetes/dashboard/tree/master/src/app/frontend_old/horizontalpodautoscaler

If you need any more information don't hesitate to ask questions.

**Comment by maciaszczykm** [comment]
Here is how we included it in the past on the Deployment detail view:

https://github.com/kubernetes/dashboard/blob/91a1efbf1eeec237c8f27e0093f0509a39ee6852/src/app/frontend/deployment/detail/detail.html#L56-L64

**Comment by eloyekunle** [comment]
@maciaszczykm re: 

> graphs for cluster, nodes, overview, workloads, daemon sets, deployments, pods, rc, rs, and stateful sets

I'll work on this.

Were there graphs for these resources in the old frontend?

**Comment by maciaszczykm** [comment]
@eloyekunle Great! Could you also take a look on switch to c3 possibly? 

> Were there graphs for these resources in the old frontend?

Yes.

**Comment by eloyekunle** [comment]
> Could you also take a look on switch to c3 possibly?
Yes, I'll look into into it.

**Comment by maciaszczykm** [comment]
@ajatprabha Can you add workload statuses to the workloads page too?

**Comment by ajatprabha** [comment]
Sure @maciaszczykm. I'm working on a PR.

**Comment by yinhaijiao** [comment]
Hi @maciaszczykm . Long time no contact. As I was busy with my work before, I didn't continue to help. Now I have some time. Is there anything I can do for you?

**Comment by maciaszczykm** [comment]
Split the issue to the smaller tasks in the https://github.com/kubernetes/dashboard/milestone/1.

/close
