### ISSUE TITLE
Missing kubernetes-dashboard.yaml

### ISSUE THREAD

**Issue by Behoston** [kubernetes/dashboard#3441]
https://github.com/kubernetes/dashboard#getting-started
There are instructions how to deploy dashboard on cluster, but it uses wrong url to deployment file. 

##### Steps to reproduce
`kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

##### Observed result
404 status code

##### Expected result
dashboard installed on k8s

**Comment by anton-yurchenko** [comment]
https://web.archive.org/web/20181006041622/https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by mkielar** [comment]
It's now this one is probably:
https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

For some reason this one breaks on Worker Node with docker logs saying:
```
[ec2-user@ip-10-0-2-251 ~]$ docker logs 60da480bd281
standard_init_linux.go:187: exec user process caused "exec format error"
```

**Comment by mkielar** [comment]
@Behoston wouldn't you rather point to a latest release (that is at least supposed to be stable) instead of linking to master in official docs? From what I just tried, the `master/aio` version fails currently with the message I posted above. And the `v1.10.1/src/deploy` version actually deploys.

**Comment by maciaszczykm** [comment]
Done in #3443.
