### ISSUE TITLE
Arm version seems to be reversed

### ISSUE THREAD

**Issue by seanhig** [kubernetes/dashboard#3447]
On master, the current `kubernetes-dashboard.yaml` references an ARM based image, and the `kubernetes-dashboard-arm.yaml` references an amd64 image.  Pretty sure this was a mix up in the commit that occurred a few hours ago now.
https://github.com/kubernetes/dashboard/commit/7c73bacd64d5fc1e80561d355a4e0dd3c33f984b#diff-a0ed1ebb3f4da2a985b54b6a2ddc770f

Taught me a valuable lesson about not trusting the link in the master README and referencing tagged releases instead ;)

**Comment by jmabry** [comment]
For anyone else affected, I was able to get started by running `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml`

**Comment by maciaszczykm** [comment]
Fixed.

/close
