### ISSUE TITLE
ELB long names continue past the card's right border

### ISSUE THREAD

**Issue by therc** [kubernetes/dashboard#345]
ELB names are, admittedly, very long. Make them wrap, truncate abruptly or truncate with an ellipsis.

This is what they look like right now:
![screenshot from 2016-02-09 10-29-13](https://cloud.githubusercontent.com/assets/13481082/12921189/0083dc2e-cf1a-11e5-8b8c-15b20c5d9bd6.png)

You'll also notice that there's space wasted on the sides because of the fixed card size. Are there any plans to make that dynamic?

**Comment by floreks** [comment]
We are aware of that, but thanks. :) I'm currently working on making dynamic middle ellipsis that fit available space when some strings are too long.

**Comment by therc** [comment]
Cool. Looking forward to the fixes!

**Comment by bryk** [comment]
@therc We are very happy that you're reporting the bugs. Thanks for this! Please report any issues you run into, especially on AWS. We're on bug-fix mode now.

**Comment by bryk** [comment]
@therc Take a look now.

**Comment by therc** [comment]
Is there a new build? Last time I tried to do it myself, it tried to push a 1.4GB monster...

**Comment by bryk** [comment]
I've built a canary release. Try `kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml`

**Comment by bryk** [comment]
Re size: can you elaborate? Did you use the dockerfile in the root of the repository? This dockerfile is for build environment only :)

**Comment by therc** [comment]
And you mention that only now? :-) The Dockerfile seemed to build a huge container with every programming language ever created, except maybe Intercal.

The ellipses are working, thanks a lot! Now, if I only could get back my pods that are behind replicasets instead of RC, as in #384...
