### ISSUE TITLE
Dashboard image

### ISSUE THREAD

**Issue by marcin-kasinski** [kubernetes/dashboard#3455]
##### Environment

```
Installation method:
Kubernetes version:
Dashboard version:
Operating system:
Node.js version ('node --version' output):
Go version ('go version' output):
```

**Comment by marcin-kasinski** [comment]
In kubernetes-dashboard.yaml there is

`image: k8s.gcr.io/kubernetes-dashboard-arm:v1.10.1
`
Shouldn't is be 
`
k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1`

**Comment by maciaszczykm** [comment]
Fixed.

/close
