### ISSUE TITLE
Integration testing user stories

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#346]
We're doing integration/e2e testing based on user stories. This issue names and enumerates the stories.

1. "Simple deploy" -> Deploy 1 replica nginx application using simple deploy form. See that a card for it is created.
2. "Advanced deploy" -> Deploy multi replica nginx application. Expose port 80 externally. Access the external endpoint. See that details page has N pods listed.

**Comment by bryk** [comment]
CC @floreks @maciaszczykm @cheld +others

Can you add other stories so that we have, like, 3-5 of them?

**Comment by floreks** [comment]
3. "Deploy not existing image" -> Deploy not existing app like `test`. Check that card has error status notification. Check error msg. Go to details page, events tab. Filter by warnings and check. Go to logs and also check for errors.

**Comment by maciaszczykm** [comment]
Few proposals:
- deploy to newly created namespace  - create new namespace, then deploy application into it using deploy form
- deploy from .yaml file - deploy application using .yaml file, check if details page matches application specification from .yaml file
- delete application - delete application (can be tested with and without service option)
- update pods count - update pods count and check if it was updated

**Comment by cheld** [comment]
1. "Simple Deploy" ...click link and check if application is running
2. "Advanced deploy"...deploy guest book, check if application is running. enter one value and see that it is displayed.

This is a minimum sanity check, I would like to see.

What about using a different container than nginx? Some special test container like tutum/hello-world?

**Comment by bryk** [comment]
Using other image than nginx sounds good to me.

**Comment by bryk** [comment]
Ok, let's move forward with this. I'll propose a plan, but interrupt me if you have other ideas.

**Comment by bryk** [comment]
Let's split the work here.

1. I'll take "Simple deploy" scenario. Implement it first, trying to fix any issues with our test setup.
Then
2. @floreks implements "Deploy not existing image" 
3. @maciaszczykm implements deploy from yaml test
4. @cheld Can you find somebody to implement "delete" and "update pods count" tests?

What do you think?

**Comment by cheld** [comment]
@digitalfishpond

**Comment by cheld** [comment]
@batikanu

**Comment by cheld** [comment]
Please pick

BTW: we have also details-page, events-tab and logs-page

We also wanted to start some manual testing. Maybe better if we do not all the same task the same time...

**Comment by bryk** [comment]
> BTW: we have also details-page, events-tab and logs-page

Yes, I know. I picked something to start with.

**Comment by bryk** [comment]
> We also wanted to start some manual testing. Maybe better if we do not all the same task the same time...

This should not cause problems. They're separate tasks.

**Comment by digitalfishpond** [comment]
I will pick update pods count if that's ok with you @batikanu

**Comment by maciaszczykm** [comment]
I'm starting to work on delete replication controller intrgration tests.

**Comment by bryk** [comment]
Closing as done.
