### ISSUE TITLE
HTTPS  connection error

### ISSUE THREAD

**Issue by mengxu2018** [kubernetes/dashboard#3460]
##### Environment
```
Dashboard version: 1.10.1
Kubernetes version:1.13
Operating system: centos 7.6
Docker version 17.12.1-ce
```

##### Steps to reproduce
I am new bie to k8s, I setup the cluster environment in two vms created by vmware. One is the master, another is the work node. I was referring the offical document 
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

After starting the kubeadm by 
```
kubeadm init --pod-network-cidr=10.244.0.0/16
```
I install the pod network flannel
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network.
by 
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
```
At last, I installed the dashboard using the easiest way.
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
I can see the running pod in my master machine.
```
[root@k8s-master ~]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
kube-system   coredns-86c58d9df4-4gm2v               1/1     Running   0          25m
kube-system   coredns-86c58d9df4-bmn7h               1/1     Running   0          25m
kube-system   etcd-k8s-master                        1/1     Running   0          25m
kube-system   kube-apiserver-k8s-master              1/1     Running   0          25m
kube-system   kube-controller-manager-k8s-master     1/1     Running   0          25m
kube-system   kube-flannel-ds-amd64-t5gv8            1/1     Running   0          25m
kube-system   kube-flannel-ds-amd64-tzb9f            1/1     Running   0          25m
kube-system   kube-proxy-jgbpm                       1/1     Running   0          25m
kube-system   kube-proxy-snt4j                       1/1     Running   0          25m
kube-system   kube-scheduler-k8s-master              1/1     Running   0          25m
kube-system   kubernetes-dashboard-57df4db6b-ntwgg   1/1     Running   0          24m
```
I need to visit the dashboard ui from my window 10, so I can not use 'kubectl proxy',
I found the **NodePort** section in https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above.
In this part, I run 
```
kubectl -n kube-system get service kubernetes-dashboard
``` 
to get 
```
kubernetes-dashboard   NodePort   10.108.66.97   <none>        443:31873/TCP   30m
```
So I should visit https://192.168.77.131:31873 or https://192.168.77.130:31873 since the doc said
**In case you are trying to expose Dashboard using NodePort on a multi-node cluster, then you have to find out IP of the node on which Dashboard is running to access it. Instead of accessing https://<master-ip>:<nodePort> you should access https://<node-ip>:<nodePort>.**

But both not work.
I also can see the error message.
[root@k8s-master ~]# kubectl logs -n kube-system  kubernetes-dashboard-57df4db6b-ntwgg
2018/12/21 11:53:56 http: TLS handshake error from 10.244.0.0:51613: tls: first record does not look like a TLS handshake
2018/12/21 11:53:58 http: TLS handshake error from 10.244.0.0:51614: tls: first record does not look like a TLS handshake
2018/12/21 11:54:12 http: TLS handshake error from 10.244.0.0:51615: EOF
2018/12/21 11:54:19 Metric client health check failed: the server could not find the requested resource (get services 

I have another question, If I can visit the UI , whether can I refer to the https://github.com/kubernetes/dashboard/wiki/Creating-sample-user to log in the dashboard?
But I stuck in the first step.

##### Observed result
I can not see the dashboard screen.
##### Expected result
I can see the dashboard screen.

##### Comments

**Comment by floreks** [comment]
```
2018/12/21 11:53:56 http: TLS handshake error from 10.244.0.0:51613: tls: first record does not look like a TLS handshake
```

This means that you are trying to access it over HTTP instead of HTTPS.

**Comment by mengxu2018** [comment]
> ```
> 2018/12/21 11:53:56 http: TLS handshake error from 10.244.0.0:51613: tls: first record does not look like a TLS handshake
> ```
> This means that you are trying to access it over HTTP instead of HTTPS.
But I visit it by  https://192.168.77.131:31873 or https://192.168.77.130:31873

**Comment by floreks** [comment]
Maybe your browser is blocking connection to the page with insecure certificates. Self-signed certs will always be recognized as dangerous by the browser.

**Comment by mengxu2018** [comment]
> Maybe your browser is blocking connection to the page with insecure certificates. Self-signed certs will always be recognized as dangerous by the browser.


Thanks. It seems I can visit https://192.168.77.131:31873  in firefox which can allow insecure certificates, but it need token, then I refer to the https://github.com/kubernetes/dashboard/wiki/Creating-sample-user.

But it report below error.
[root@k8s-master ~]# kubectl apply -f dashboard-adminuser.yaml
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "admin-user", Namespace: "kube-system"
Object: &{map["kind":"ServiceAccount" "metadata":map["namespace":"kube-system" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "name":"admin-user"] "apiVersion":"v1"]}
from server for: "dashboard-adminuser.yaml": serviceaccounts "admin-user" is forbidden: User "system:node:k8s-master" cannot get resource "serviceaccounts" in API group "" in the namespace "kube-system": can only create tokens for individual service accounts
[root@k8s-master ~]#

How to fix it? Thanks very much.  Actually I ever execute this command before succesfully, but I forget to save the token since I can not access the ui in browser.

**Comment by mengxu2018** [comment]
it's since I forget to export KUBECONFIG=/etc/kubernetes/admin.conf
