### ISSUE TITLE
Update K8s vagrant provider to use dashboard UI

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#347]
Per discussion at #340

@cheld

**Comment by bryk** [comment]
If you dont have time for this, assign to somebody else.

**Comment by cheld** [comment]
I start on this, now

**Comment by cheld** [comment]
@bryk I am very sorry, but the vagrant provisioning from master is failing on my machine due to some networking issues I have inside the company network. It also failed on a second developer machine. We cannot resolve the issue in the next few days.

**Comment by bryk** [comment]
Deferring to post 1.0 then

**Comment by taimir** [comment]
I think there has been a misunderstanding, the vagrant provider already uses dashboard.
This has been be resolved already in [this commit](https://github.com/kubernetes/kubernetes/commit/46f51d74bbaf695b2effae74d62d44ded3e7d2a9) by @bryk (`cluster/saltbase/salt/kube-addons/init.sls`, line 151). I just started a vagrant cluster and dashboard is up and running under `http://\<master\>/ui` :)

Please close.

**Comment by floreks** [comment]
That's great. Thanks for checking that. Closing.

**Comment by bryk** [comment]
I like it! Fixing bug even when you don't know this
