### ISSUE TITLE
what  kind problem is it?

### ISSUE THREAD

**Issue by weifangan** [kubernetes/dashboard#3470]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.7.1
Commit: 
```

##### Observed result
Dashboard reported Service Unavailable (503):
```
Service Unavailable
```

**Comment by jeefy** [comment]
/triage needs-information

/close

It's a rather old version of the dashboard and there's a lot of missing information. If you want to provide more information and re-open it that would be appreciated, otherwise I'd suggest upgrading first.
