### ISSUE TITLE
Deploy has disappeared 

### ISSUE THREAD

**Issue by georgetulakyan** [kubernetes/dashboard#3471]
Been getting 404 Not Found error when I try to setup Dashboard
i.e. kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
error: unable to read URL "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml", server reported 404 Not Found, status code=404

I tracked the issue down to a commit by florecks on Dec 20th
https://github.com/kubernetes/dashboard/tree/7c73bacd64d5fc1e80561d355a4e0dd3c33f984b/src

The deploy folder did exist in the previous commit by maciaszczykm
https://github.com/kubernetes/dashboard/tree/db92a809716a79fc36e22d5868b676410ce8d2c3/src

Has location been moved or is this an issue with fast forward when doing a commit?
In either case, please address. Because, there are a ton of docs out there using the deploy.

**Comment by floreks** [comment]
The fastest way to find correct link would be to check our official documentation. Main repo page and README + wiki pages. We have updated links there.
