### ISSUE TITLE
dashboard apiserver-host param points to a server that does not exist

### ISSUE THREAD

**Issue by minminmsn** [kubernetes/dashboard#3472]
##### Environment

```
Installation method:  
kubernetes binaries install：http://blog.51cto.com/jerrymin/2336502
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
Kubernetes version:1.13.1
Dashboard version: 1.10.1
Operating system: Centos7.4
```

[root@elasticsearch01 yaml]# kubectl logs kubernetes-dashboard-7649fbd576-r4wn2 --namespace=kube-system
2018/12/29 05:52:10 Starting overwatch
2018/12/29 05:52:10 Using apiserver-host location: https://10.2.8.44:6443
2018/12/29 05:52:10 Skipping in-cluster config
2018/12/29 05:52:10 Using random key for csrf signing
2018/12/29 05:52:10 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service account's configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.2.8.44:6443/version: x509: failed to load system roots and no roots provided
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

**Comment by minminmsn** [comment]
use default args  
        args:
          - --auto-generate-certificates
error also 👎 
NET::ERR_CERT_INVALID

![image](https://user-images.githubusercontent.com/17631009/50536669-b10b9300-0b91-11e9-9e95-258918b8f709.png)

**Comment by minminmsn** [comment]
resolved:
$ mkdir certs
$ openssl req -nodes -newkey rsa:2048 -keyout certs/dashboard.key -out certs/dashboard.csr -subj "/C=/ST=/L=/O=/OU=/CN=kubernetes-dashboard"
$ openssl x509 -req -sha256 -days 365 -in certs/dashboard.csr -signkey certs/dashboard.key -out certs/dashboard.crt
$ kubectl create secret generic kubernetes-dashboard-certs --from-file=certs -n kube-system
$ kubectl create -f kubernetes-dashboard.yaml

**Comment by richardsonlima** [comment]
@minminmsn this workaround works for me. Thank you !!
