### ISSUE TITLE
Failed to pull image     "k8s.gcr.io/kubernetes-dashboard-arm:v2.0.0-alpha0"

### ISSUE THREAD

**Issue by alexellis** [kubernetes/dashboard#3473]
##### Environment

 Installed via `kubeadm`

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/arm"}
```

##### Steps to reproduce

```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/alternative/kubernetes-dashboard-arm.yaml
```

##### Observed result

Failed to pull image     "k8s.gcr.io/kubernetes-dashboard-arm:v2.0.0-alpha0"

##### Expected result

Running dashboard

##### Comments

It appears that there may be an issue with the CI or the image name referenced for the 32-bit ARM entry. The image does not exist on the remote repository so the dashboard cannot be pulled.

I worked around this in my K8s-on-Raspbian guide by pointing at the "-head" version in the same folder: https://github.com/alexellis/k8s-on-raspbian

**Comment by alexellis** [comment]
cc @luxas

**Comment by alexellis** [comment]
Pointing to master used to work and it seems to be the same in the docs. Is it generally expected that master won't work for the dashboard? What should we point at instead? 

Alex

**Comment by floreks** [comment]
We have changed it to be more like other projects. Official links are always available on the releases page and README also points to the latest release instead of master. Master should never be used as reference for stable build. We are using it for development of new versions and it might be unstable. Right now we have bumped version on the master to v2 alpha but it is not yet released.
