### ISSUE TITLE
can't login dashbord

### ISSUE THREAD

**Issue by roamergu** [kubernetes/dashboard#3474]
##### Environment

```
Installation method:Linux
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

Dashboard version:v1.10.1
Operating system:Centos 7
Node.js version ('node --version' output):null
Go version ('go version' output):null
```

##### Steps to reproduce

1.install kubenet follow the page :https://kubernetes.io/docs/setup/independent/install-kubeadm/
2.install dashbord follow the page:https://github.com/kubernetes/dashboard/releases
3.create Admin privileges follow the page :https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges
4.get token follw same page
5.run kubectl proxy,i can view loging page and paste the token,but no any feedback.i just find taoken false message from chrome dev-tools.

6.i run a windows 10,and use vmware createed 4 centos7,one manage,one master,2 nods.i run ``` kubectl proxy --address='0.0.0.0' --port=8888 --accept-hosts='^*$' &```

and use chrome access to``` http://masterip:8888//api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/ ```

but when i paste token and click login, the system no any feedback.

**Comment by maciaszczykm** [comment]
From https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above:
> **NOTE**: Dashboard should not be exposed publicly over HTTP. For domains accessed over HTTP it will not be possible to sign in. Nothing will happen after clicking Sign in button on login page.

> **NOTE:** Dashboard should not be exposed publicly using `kubectl proxy` command as it only allows HTTP connection. For domains other than `localhost` and `127.0.0.1` it will not be possible to sign in. Nothing will happen after clicking `Sign in` button on login page.

/close
