### ISSUE TITLE
Add namespace selector for replication-controller-list page

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#348]
When deploying an app, it is possible to select/create a namespace for it. However, in the replication-controller-list page it is not possible to utilize this information. Also, by default all the add-on containers are shown. IMHO, this is not so nice. As a user I would say I do not want the add on containers mixed with my application containers.

I would suggest to add some kind of namespace selector (e.g. combo-box) in the header that shows the default-namespace by default.

```
-------------------------------
| default                v    |
-------------------------------
 my-namespace
 kube-system (?)
 all
```

There might be better ways. Piotr mentioned that the mockups contain a suggested namespace handling concept. However, I could not find it.

**Comment by bryk** [comment]
Now I remember. This was in some of Ken's early mocks. Take a look: 
![namespaces](https://cloud.githubusercontent.com/assets/1159999/12946666/5d6bf0f2-cff6-11e5-9f43-ef719d29ec8d.png)

**Comment by cheld** [comment]
Nice.

From user point of view, I think in most cases I only want to see one namespace at a time.

So, my suggestion:
- add a selector at the top
- show the cards like in the mockup if 'all' is selected

**Comment by bryk** [comment]
@floreks @maciaszczykm Inviting to discussion re: "All namespaces or namespace selector".

**Comment by maciaszczykm** [comment]
This early mock looks nice, but I agree, that we should be available to filter displayed namespaces. I would list them all and create checklist:

- [x] default
- [x] namespace-1
- [ ] namespace-2

In this case we should display replication controllers only from default and namespace-1 namespaces.

Moreover, some switch to hide groups (current state) would be nice.

**Comment by floreks** [comment]
I've have a little different idea of handling that. How about making expandable rows that will hold card containers. This represents the idea: http://jsfiddle.net/Pixic/6Texj/

On click all other expanded namespaces would be collapsed again. What do you think?

**Comment by bryk** [comment]
@floreks So you say to show all namespaces, but make the containers that contain them collapsable?

**Comment by floreks** [comment]
Yes, then on click we can async load data related to namespace and collapse others. One namespace would be shown at a time. Normally we would start with default namespace.

**Comment by cheld** [comment]
Hmm...the namespace concept is a bit fuzzy. So lets define some scenarios and use cases first.

If I remember correctly, the namespaces have been requested by RedHat for OpenShift. I have never checked myself, but I assume that OpenShift uses namespaces to separate applications
 
=> Use Case 1: one namespace for each application

In a development project, several roles are involved (QA, doc, PM). They want different versions (e.g. stable, head,...) of the product

=> Use Case2: one namespace for each product version

In a team every user gets his own namespace and can deploy whatever he wants to his namespace

=> Use Case3: namespaces as a lightweight tenant approach

In very big applications like Gmail, Spotify, the application is so big that it cannot be developed by a single team. 

=> Use Case4: namespaces to structure large applications

So, I consider it the following:
90% of use cases is to see only one
5% of use cases is to see all
5% of use cases is to see a selection out of all

Something like a combobox seems to me like a quick win. However, what Marcin suggested is more flexible and seems to me like the best solution.

**Comment by bryk** [comment]
@dodwyer Can you describe how you use namespaces in Kubernetes?
We're having a discussion here on whether to show applications from all namespaces at once or one-namespace-at-a-time.

**Comment by bryk** [comment]
I'm worried about discoverability and exposure to advanced K8s concepts for all users. The problem is that when user opens the apps view, we show apps from a namespace (default perhaps?). In most cases where there is more than one namespace, this does not make sense. Why is _default_ namespace better than other ones? So now comes the problem. User has now to understand what namespaces are, think, and select their namespace from a dropdown. This contradict with the priorities of this UI that are to make things easy and discoverable.

I understand the use case that somebody wants to see one namespace at a time. What do you think about showing all namespaces at first screen (/#replicationcontrollers) and allow users to click on namespace title to show only selected one (/#foo-namespace/replicationcontrollers)?

**Comment by cheld** [comment]
Ok, we shouldn't be academic, we should ask the users :)

So, I asked one operator in our neighbour team which started using Dashboard in production. It is a normal DevOps team very similar to most projects, I would say.

They do not like the current state. He would prefer Ken's proposal. In the future he would like to see some kind of filtering.

**Comment by cheld** [comment]
Namespaces in Tectonic
![tectonic_namespace](https://cloud.githubusercontent.com/assets/7448799/13006269/0822cba0-d188-11e5-939d-415d01b38539.png)

**Comment by codegoblins** [comment]
We use namespaces as tenants, so I like @cheld's suggestion - I would also like to be able to set a default namespace to start in, because it takes almost 20 seconds to load everyone's deployments.

**Comment by titilambert** [comment]
Hello !
As @codegoblins, we want to use namespaces as tenants.
As @bryk said, So I made a small patch #363 adding a new option to dashboard backend binary. This option restricts the backend to the specified namespace. So we will create a Kubernetes Dashboard instance by namespace. Each tenant will use Kubernetes Dashboard as admin panel for his namespace.

**Comment by bryk** [comment]
@bgrant0607 Can you give us feedback on namespaces UX?

**Comment by bgrant0607** [comment]
I'd rank the scenarios by frequency as:
1. Namespace = environment (dev, staging, prod)
2. (*)Namespace = tenant (X environment)
3. Namespace = application (X tenant X environment)
4. Namespace = part of an application (X application X tenant X environment)

kubectl interacts with one namespace at a time, which is remembered via the context in .kube/config. The initial context is set to `default`, which is a namespace that is created automatically upon cluster creation.

Interaction with a single namespace is likely relatively common, especially for beginning users. 

(*) In single-tenant clusters like GKE, that namespace is likely to be `default`. In multi-tenant scenarios, such as Openshift, it's likely to be the user's "project" namespace. Note that in such scenarios, users won't have access to all namespaces.

System namespaces such as kube-system, tectonic-system, openshift-infra, etc. are intended for cluster admins, and shouldn't be the first things the user sees.

Whether collapsed or not, I don't think we should show all namespaces, at least not unless the user specifically requests to see them all.

I like the checklist proposal. It would be even better if the user could choose the order of display.

In the case of multiple selected namespaces, I like the separation by namespace in the original mocks.

**Comment by dodwyer** [comment]
I agree with @bgrant0607 rankings for the namespace scenarios. 
For typical client installs we mostly see scenario 1 as it follows a 1:1 transition from a traditional single application VM set-up. 
I imagine we will see scenario 3 more in the future as the tradition dev, staging, prod model makes ways for more dynamic set-ups as people get more comfortable with the concept.

**Comment by dodwyer** [comment]
In regards to the design, would it be possible to have a Google Keep style filter for namespaces? So as you are typing the "Cards" representing each namespace is removed when it doesn't match the filter? You could also introduce a basic namespace label filter for quick group matching?

**Comment by cheld** [comment]
@dodwyer 

> For typical client installs we mostly see scenario 1 as it follows a 1:1 transition from a traditional single application VM set-up

But this is scenario 3 of bgrant0607, isn't it? VM = application = namespace

> I imagine we will see scenario 3 more in the future as the tradition dev, staging, prod model makes ways for more dynamic set-ups as people get more comfortable with the concept.

But this is scenario 1, isn't it? namespace = (dev, staging, prod)

**Comment by codegoblins** [comment]
@dodwyer I haven't used the google keep webapp much, but it seems the filter applies to the cards' content. It might make sense to let the user select namespace from a (multi)select as described above and use such a box for filtering by selectors e.g. something like app:myapp but that seems like a separate discussion. 

For those with a dev-staging-production namespace setup, how would you use this dashboard in a multi-tenant environment? Exposing everything in the production namespace in the flow that users deploy their applications from seems like it could lead to problems. Do you deploy a per-application instance of the dashboard like @titilambert suggested?

**Comment by bryk** [comment]
Done.
