### ISSUE TITLE
Move compatibility matrix to releases page

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3480]
I think it would be a good idea to move [compatibility matrix](https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix) from wikis to releases in the release page. Then in every single release, we can do something similar to:

### Compatibility matrix
| Kubernetes version | 1.8 | 1.9 | 1.10 | 1.11 |
|------------------------|-----|-----|-----|-----|
| Compatibility               | ✕    | ✓   | ?   | ✕   |

**Comment by floreks** [comment]
Something like a shortened version only showing compatibility of the latest release?

**Comment by maciaszczykm** [comment]
Yes, exactly. And info would be there for every release. No need to check the docs.

**Comment by floreks** [comment]
+1

**Comment by maciaszczykm** [comment]
Added it to last 3 releases.

/close
