### ISSUE TITLE
Unable to access Kubertenes Dashboard n my host machine

### ISSUE THREAD

**Issue by shaktiprasadrath** [kubernetes/dashboard#3481]
I have setup a 3 Virtualbox on my machine out of which one is master and other 2 are child.
So, when I am trying to open the Dashboard on my host machine it is showing error. Below are all the details about my Kubernetes infrastructure:

**Nodes info:**
[kmaster@kmaster ~]$ kubectl get nodes
NAME      STATUS   ROLES    AGE   VERSION
kchild    Ready    <none>   8d    v1.13.1
kmaster   Ready    master   8d    v1.13.1
kslave    Ready    <none>   8d    v1.13.1

**Pods details**
[kmaster@kmaster ~]$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY   STATUS             RESTARTS   AGE
kube-system   coredns-86c58d9df4-bk7z2               1/1     Running            1          8d
kube-system   coredns-86c58d9df4-zrjmn               1/1     Running            1          8d
kube-system   etcd-kmaster                           1/1     Running            1          8d
kube-system   kube-apiserver-kmaster                 1/1     Running            1          8d
kube-system   kube-controller-manager-kmaster        1/1     Running            1          8d
kube-system   kube-flannel-ds-amd64-2xkzp            1/1     Running            2          8d
kube-system   kube-flannel-ds-amd64-tnmqg            1/1     Running            1          8d
kube-system   kube-flannel-ds-amd64-tt8tf            1/1     Running            2          8d
kube-system   kube-proxy-6gk7f                       1/1     Running            1          8d
kube-system   kube-proxy-nkwnt                       1/1     Running            1          8d
kube-system   kube-proxy-tf9qk                       1/1     Running            1          8d
kube-system   kube-scheduler-kmaster                 1/1     Running            1          8d
kube-system   kubernetes-dashboard-57df4db6b-b6x65   0/1     CrashLoopBackOff   11         41m

**OS version**
CentOS Linux release 7.6.1810 (Core)

**Kubectl version**
[kmaster@kmaster ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Services**
[kmaster@kmaster ~]$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   8d

**Dashboard configuration Steps**
1. kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

2. [kmaster@kmaster ~]$ sudo kubectl proxy --address="10.0.0.162" -p 999 --accept-hosts='^*$'
[sudo] password for kmaster:
Starting to serve on 10.0.0.162:999
**I0103 13:14:00.903563   13139 log.go:172] http: proxy error: dial tcp [::1]:8080: connect: connection refused**

3. I am accessing the dashboard with the below url:
http://10.0.0.162:999/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

I am getting the above error.

Please, advise.

**Comment by floreks** [comment]
1. This is not a Dashboard issue if you are seeing connection refused error coming from `kubectl`.
2. Exposing Dashboard over HTTP is forbidden and will not work as stated in the documentation.

**Comment by floreks** [comment]
You can use ingress resource and expose it over HTTPS or use `kubectl proxy` locally to access it on `localhost` domain.
