### ISSUE TITLE
Dashboard login not showing SKIP option

### ISSUE THREAD

**Issue by kkcgmail** [kubernetes/dashboard#3483]
##### Environment

```
Installation method:
Kubernetes version:1.13.1
Dashboard version:
Operating system:
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Comments

kubectl proxy is running.
I can see dashboard in browser
ip:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login
But can not find and option to SKIP login
<img width="942" alt="screenshot 2019-01-05 at 13 54 09" src="https://user-images.githubusercontent.com/25150152/50725172-89687d80-10f1-11e9-846d-2a84e2ef190e.png">

**Comment by floreks** [comment]
Read the release notes for v1.10.1. It has been disabled by default for security reasons.

**Comment by kkcgmail** [comment]
Thanks floreks. I have created service accounts. Using Token..when I click SIGN IN its not moving but APIs all looks to be returning ok.
Does it mean that I cant access it outside localhost? Please help.

**Comment by floreks** [comment]
This behavior is also described in the documentation. Exposing Dashboard on HTTP is forbidden and will not work.

**Comment by kkcgmail** [comment]
Ok. Thanks for your help.
