### ISSUE TITLE
Manual testing

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#350]
We want to create a manual testing document. A process we have had best results in the past is what we call 'FBT' (Factor Based Testing).

In this approach test factors are defined. e.g.

* Browsers
* Input border cases
* Concurrency

Then we define variations of each factor (we call this level)
```
|-----------------|----1----------------|-----2------------------|
| browser         | IE                  | Firefox                |
| appname         | empty               | max length ...         | 
| concurrency     | create concurrently | delete concurrently ...|

....
```
Important to understand:
* the document does not state the expected outcome. This is intentional. It is up to the tester to decide if the behavior is a bug or not
* the tester is expected to do some multi-factor testing, e.g. IE + delete concurrently. The combination is up to his choice.

This is a sample document:
https://drive.google.com/open?id=1OJYM9gcR92msnSqxQ7ueCzpI5Hgdf4C0kEM2n0KoeMI

**Comment by bryk** [comment]
I dont quite understand how I use the document to execute the test. Can you explain a little bit?

**Comment by cheld** [comment]
I suggest we make a hangout call on friday. I am not in office tomorrow.

**Comment by bryk** [comment]
OK

**Comment by cheld** [comment]
Following the template in PR

https://github.com/kubernetes/dashboard/pull/376

As discussed with Piotr, we should create 1-2 additional sheets as a starting point

I would suggest:
- Deploy from settings
- ReplicationController list page

cc @digitalfishpond , @maciaszczykm , @floreks , @f-higashi 

Please pick if you have time

**Comment by maciaszczykm** [comment]
I'll prepare tests for replication controller list page.

**Comment by f-higashi** [comment]
I'll create 'Deploy from settings' sheet.

**Comment by cheld** [comment]
Manual testing day!

So, we have the following test areas:
- Deploy from file. Covered by FBT
- Deploy from settings. Covered by FBT
- RC list. Covered by FBT
- RC details. Not yet covered by FBT.
- Logs. Not yet covered by FBT. 
(- ZeroState. Not yet covered by FBT.)
(- Deployment into different environments - actually this should be a factor  )

We can divide the work the following way:
- Fujitsu style: every developer picks one test area and test all factors, including all browsers (browsersync will help?)
- Google style: every developer tests all areas, but only one browser

How should we divide the work, any suggestion?

@bryk, @maciaszczykm, @digitalfishpond, @floreks, @f-higashi, @batikanu, @taimir

**Comment by bryk** [comment]
> (Deployment into different environments - actually this should be a factor )

Please test the UI that runs as a container inside a cluster. This is how the UI will be run in most cases.

**Comment by bryk** [comment]
> Google style: every developer tests all areas, but only one browser

Can we do Google style for this time? I have huge problems with making this work on IE

**Comment by bryk** [comment]
I claim "Deploy from file. Covered by FBT" "RC list. Covered by FBT" on Firefox.

Make sure someone claims this also on IE :)

**Comment by floreks** [comment]
I can take that on IE :)

**Comment by digitalfishpond** [comment]
Ok, I'll take this on Chrome

**Comment by f-higashi** [comment]
I'll take "RC details. Not yet covered by FBT" on Firefox.

BTW, when I need to finish tests by?
In Japan, I have a little remaining time today.

Is it OK by tomorrow morning in your timezone?

**Comment by floreks** [comment]
Sure. We will prioritize all discovered issues tomorrow anyway so take your time.

**Comment by floreks** [comment]
@bryk 
> Please test the UI that runs as a container inside a cluster. This is how the UI will be run in most cases.

I've deployed dashboard from newest yaml and it doesn't contain IE display fix. Can't really test without that :) I'll have to do it on serve:prod

**Comment by cheld** [comment]
@f-higashi yes, of course. We will not finish today

**Comment by cheld** [comment]
I take deploy from settings, logs on firefox

**Comment by bryk** [comment]
Hey, I'm on vacation tomorrow. Can you folks go over the list of issues produced and prioritize them?

**Comment by olekzabl** [comment]
I'll deploy from settings on Chrome.

**Comment by f-higashi** [comment]
I'll take logs on IE.

**Comment by f-higashi** [comment]
|                                                               |chrome            |firefox     |ie             |
|--------------------------------------------------|--------------------|------------|------------|
|Deploy from file. Covered by FBT          |digitalfishpond  |bryk        |floreks     |
|Deploy from settings. Covered by FBT  |olekzabl            |cheld       |               |
|RC list. Covered by FBT                        |digitalfishpond  |bryk         |floreks     |
|RC details. Not yet covered by FBT.      |                         |f-higashi |                |
|Logs. Not yet covered by FBT.              |                         |cheld       |f-higashi  |
|(ZeroState. Not yet covered by FBT.)    |                         |               |                |

**Comment by cheld** [comment]
@f-higashi good idea

I could have tested much more....

About prioritization, I think we can group the following:
- IE issues
- Major functional bugs
- Fix validation: make it complete and consistent
- Minor functional bugs in unusual scenarios
- nice to have layouting issues and conceptual issues

**Comment by bryk** [comment]
Thank you all for participation! This was really valuable :) 

This round of manual tests is done. Closing. Will create a new issue for next round.
