### ISSUE TITLE
Do not remove query after namespace change and page reload

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3502]
##### Environment

```
Installation method: any
Kubernetes version: any
Dashboard version: master
Operating system: any
Node.js version ('node --version' output): any
Go version ('go version' output): any
```

##### Steps to reproduce

1. Search for a some query, i.e. "nginx". Confirm your search. See the results.
2. Change namespace. Notice URL change. Notice results change.
3. Query does not match results and URL. It is empty.

##### Observed result

Query is empty in the top bar.

##### Expected result

It should contain query. In this case "nginx".

##### Comments

n/a

**Comment by eloyekunle** [comment]
When I tried to reproduce this, even before changing namespace or reloading the page, the query disappears from the top bar immediately I press enter.

I'm working on this.
