### ISSUE TITLE
timeout awaiting response headers on certain namespaces

### ISSUE THREAD

**Issue by falcoriss** [kubernetes/dashboard#3507]
##### Steps to reproduce
Try to access to overview, workload or search for something

##### Environment
```
Installation method: kubespray
Kubernetes version: 1.12.3
Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
net/http: timeout awaiting response headers

```

##### Comments
I only seem to have the problem on specific location of the dashboard, overview, workload or when i search for something.
Moreover, the problem only affects one namespace : kube-system and another namespace don't throw me any error.

There is nothing helpfull in the logs, unless i missed something : 
```
2019/01/10 16:31:37 [2019-01-10T16:31:37Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 10.233.112.15:59338: {}
2019/01/10 16:31:37 Getting list of namespaces
2019/01/10 16:31:37 [2019-01-10T16:31:37Z] Outcoming response to 10.233.112.15:59338 with 200 status code
2019/01/10 16:31:39 [2019-01-10T16:31:39Z] Incoming HTTP/1.1 GET /api/v1/login/status request from 10.233.112.15:59360: {}
2019/01/10 16:31:39 [2019-01-10T16:31:39Z] Outcoming response to 10.233.112.15:59360 with 200 status code
2019/01/10 16:31:39 [2019-01-10T16:31:39Z] Incoming HTTP/1.1 GET /api/v1/overview/dev?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 10.233.112.15:59364: {}
2019/01/10 16:31:39 Getting config category
2019/01/10 16:31:39 Getting discovery and load balancing category
2019/01/10 16:31:39 Getting lists of all workloads
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:39 Getting pod metrics
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:39 No metric client provided. Skipping metrics.
2019/01/10 16:31:40 No metric client provided. Skipping metrics.
2019/01/10 16:31:41 [2019-01-10T16:31:41Z] Outcoming response to 10.233.112.15:59364 with 200 status code
```

It could very well be related to a non dashboard issue but so far I don't have any other problem on my cluster.

Any idea ?

**Comment by floreks** [comment]
> net/http: timeout awaiting response headers

I think that this message comes directly from the apiserver. Looks like it did not return any request or it took too long. All errors that come with error code `500` are returned from the apiserver and they are mostly not related to Dashboard.

**Comment by falcoriss** [comment]
looks like my problem was coming from my keycloak reverse proxy before the dashboard. 
I will close this

**Comment by mlachowski-stx** [comment]
@falcoriss I have a similar issue. Can you give more details, how you resolve problem with keycloak reverse proxy?

**Comment by 8160960572** [comment]
Hi All,

I also faced same issue.
Keycloak gatekeeper has a flag mentioned below.
--upstream-response-header-timeout value  the timeout placed on the response header for upstream (default: 1s)

I have increased its value to 10 sec. And its working fine.

It looks like Keycloak expect some headers from kubernetes dashboard but as it is unavailable to provide it in 1s, it returns that error.
