### ISSUE TITLE
Pagination for logs and events

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#351]
Currently all logs and events are loaded into the browser. This can easily become a performance (and memory) problem, especially for logs.

So, we should add some paging or lazy loading mechansim

**Comment by taimir** [comment]
I'll pick this up of noone else has :)

**Comment by bryk** [comment]
I think this is P2 => still a nice feature, but not critical :) Feel free to take this :)

**Comment by kwodzynski** [comment]
I checked how Dashboard cope with large number of lines in logs (Ubuntu 15.10, Mozilla Firefox 45.0.1, Google Chrome 49.0.2623.112). In the table below I have given time elapses from the start of generating logs to their completion. Left column - amount of log lines, top row - where logs were generated

<table border=1 style="text-align: center;">
<tr>
 <td style="padding: 0 5px 0 5px"></td> <td style="padding: 0 5px 0 5px"><b>Firefox</b></td> <td style="padding: 0 5px 0 5px"><b>Chrome</b></td><td style="padding: 0 5px 0 5px"><b>Kubectl</b></td>
</tr>
<tr>
 <td style="padding: 0 5px 0 5px"><b>10000</b></td> <td style="padding: 0 5px 0 5px">5s</td> <td style="padding: 0 5px 0 5px">5s</td> <td style="padding: 0 5px 0 5px">2s</td>
</tr>
<tr>
 <td style="padding: 0 5px 0 5px"><b>50000</b></td> <td style="padding: 0 5px 0 5px">30s, script crashed</td> <td style="padding: 0 5px 0 5px">20s</td> <td style="padding: 0 5px 0 5px">3s</td>
</tr>
<tr>
 <td style="padding: 0 5px 0 5px"><b>75000</b></td> <td style="padding: 0 5px 0 5px">script crashed</td> <td style="padding: 0 5px 0 5px">40s</td> <td style="padding: 0 5px 0 5px">5s</td>
</tr>
<tr>
 <td style="padding: 0 5px 0 5px"><b>100000</b></td> <td style="padding: 0 5px 0 5px">script crashed</td> <td style="padding: 0 5px 0 5px">50s, browser works very slowly</td> <td style="padding: 0 5px 0 5px">7s</td>
</tr>
<tr>
 <td style="padding: 0 5px 0 5px"><b>1000000</b></td> <td style="padding: 0 5px 0 5px">script crashed</td> <td style="padding: 0 5px 0 5px">script crashed</td> <td style="padding: 0 5px 0 5px">60s</td>
</tr>
</table>

I think the biggest number of logs, which will quickly generate is max 10000. Maybe we should give the users the ability to generete a CSV file with all of logs?

**Comment by cheld** [comment]
Nice test. 

I think from a user perspective, I would like to see the last 10000 logs (or even less) and have a download link for all logs. Not sure about the format of the file. I think txt is fine. I don't know if this can be implemented.

**Comment by bryk** [comment]
Hmm... How about pagination or progressive loading? This would solve the problem

**Comment by kwodzynski** [comment]
I think that pagination would be a better solution. What do you think?

**Comment by cheld** [comment]
I guess, from user perspective I would prefer progressive loading, because it would be better to search with CTRL-F. But I assume after 5 times loading 10000 items, the script would crash again?

**Comment by bryk** [comment]
The logs viewer should show N log lines at a time, with pagination. N may be high (like 1k or 10k). For real searching we need a backend-based search box, because CTRL+F is suboptimal when you have lots of logs.

**Comment by edouardKaiser** [comment]
Regarding the current situation of logs loading/displaying, is it "normal" that when the dashboard is loading a big amount of logs, the entire dashboard application is freezing ? (can't access the dashboard on another tab on the browser).

**Comment by bryk** [comment]
It is not normal. How can I reproduce this? Which version do you use?

**Comment by edouardKaiser** [comment]
Ok, if it's not normal, give me a little bit of time to come up with a protocol to reproduce easily. I noticed this behaviour with v1.0.1 and also the last beta.

**Comment by bryk** [comment]
Partially done. We have pagination for events now.

**Comment by floreks** [comment]
We have pagination for all resources. Events and Logs are still missing it. It should be easy to add to events, I'm not sure about logs. I'll take a look.

**Comment by bryk** [comment]
Fixed.
