### ISSUE TITLE
Wrong link to install dashboard UI in README

### ISSUE THREAD

**Issue by mazharul** [kubernetes/dashboard#3512]
README points to the wrong link to install dashboard UI.

`https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml`

This above link results in 404.

**Comment by jeefy** [comment]
I just clicked the link from my email (I'm on mobile) and it worked. I also
just checked from the website and it worked.

Could you make sure it copied right when you used it?

Thanks!

**Comment by mazharul** [comment]
It works on mine now as well. Sorry for the trouble. I will close the issue. 

Thanks!
