### ISSUE TITLE
Unable to connect to kubernetes dashboard

### ISSUE THREAD

**Issue by mridulsmile** [kubernetes/dashboard#3527]
##### Environment

```
Installation method:
Kubernetes version:
Dashboard version:
Operating system:
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

In a given kubernetes cluster:
Create a reader role (yaml file):

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: view-role
rules:
- apiGroups: ["", "extensions"]
  resources: ["nodes", "deployments", "replicasets", "pods", "pods/log", "services"]
  verbs: ["get", "list"]

Create a service account: kubectl --kubeconfig <clusteradminkubeconfig> create sa view-sa --namespace:default

Create cluster role binding: kubectl --kubeconfig <clusteradminkubeconfig> create clusterrolebinding view-sa-view-role --clusterrole=view-role --serviceaccount=default:view-sa

Run a proxy using the view service account: kubectl --kubeconfig <viewsakubeconfig> proxy -p9000

##### Observed result
http://127.0.0.1:9000/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default
fails with error:

User "system:serviceaccount:default:view-sa" cannot get services/proxy in the namespace "kube-system".

##### Expected result
Dashboard should be visible with get/list permission for nodes, deployments, replicasets, pods, logs and services

##### Comments
If I add "services/proxy" to the resources while creating the cluster role, the dashboard appears but it also displays the secrets which I don't want.

**Comment by floreks** [comment]
`services/proxy` is a different resource than `service` and it is required to resolve the URL.

**Comment by mridulsmile** [comment]
Allowing services/proxy also allows the user to view secrets. How that can be avoided

**Comment by floreks** [comment]
@mridulsmile how do you think privilege to use `services/proxy` allows access to `secrets` resource which is a completely different resource managed by a different set of rules?
