### ISSUE TITLE
Dashboard is throwing error

### ISSUE THREAD

**Issue by shaktiprasadrath** [kubernetes/dashboard#3530]
I have setup a 1 master 2 slave cluster and below are the details:

[kmaster@kmaster ~]$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                   READY   STATUS             RESTARTS   AGE   IP           NODE      NOMINATED NODE   READINESS GATES
kube-system   coredns-86c58d9df4-8hdzj               0/1     CrashLoopBackOff   23         11h   172.30.1.2   kslave    <none>           <none>
kube-system   coredns-86c58d9df4-sqwkg               0/1     CrashLoopBackOff   23         11h   172.30.1.3   kslave    <none>           <none>
kube-system   etcd-kmaster                           1/1     Running            2          12h   10.0.0.210   kmaster   <none>           <none>
kube-system   kube-apiserver-kmaster                 1/1     Running            2          12h   10.0.0.210   kmaster   <none>           <none>
kube-system   kube-controller-manager-kmaster        1/1     Running            2          12h   10.0.0.210   kmaster   <none>           <none>
kube-system   kube-flannel-ds-amd64-4b4p6            1/1     Running            0          11h   10.0.0.181   kchild    <none>           <none>
kube-system   kube-flannel-ds-amd64-jdgnr            1/1     Running            2          11h   10.0.0.210   kmaster   <none>           <none>
kube-system   kube-flannel-ds-amd64-stjx7            1/1     Running            0          11h   10.0.0.231   kslave    <none>           <none>
kube-system   kube-proxy-bx9rx                       1/1     Running            2          12h   10.0.0.210   kmaster   <none>           <none>
kube-system   kube-proxy-gldcc                       1/1     Running            0          11h   10.0.0.181   kchild    <none>           <none>
kube-system   kube-proxy-hsch6                       1/1     Running            0          11h   10.0.0.231   kslave    <none>           <none>
kube-system   kube-scheduler-kmaster                 1/1     Running            2          12h   10.0.0.210   kmaster   <none>           <none>
kube-system   kubernetes-dashboard-57df4db6b-544ml   0/1     CrashLoopBackOff   15         11h   172.30.1.4   kslave    <none>           <none>

Below is the cluster info:

[kmaster@kmaster ~]$ kubectl cluster-info
Kubernetes master is running at https://10.0.0.210:6443
KubeDNS is running at https://10.0.0.210:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

Below is the my node details:

[kmaster@kmaster ~]$ kubectl get nodes -o wide
NAME      STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
kchild    Ready    <none>   11h   v1.13.2   10.0.0.181    <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://1.13.1
kmaster   Ready    master   12h   v1.13.2   10.0.0.210    <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://1.13.1
kslave    Ready    <none>   12h   v1.13.2   10.0.0.231    <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://1.13.1

I followed the below Kubernetes/Dashbord git hub link to setup dashboard but when i am accessing the url, it is showing below error:
 URL: http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

Error is:
**Error: 'dial tcp 172.30.1.4:8443: i/o timeout'
Trying to reach 'https://172.30.1.4:8443/'**

I have already stopped and disabled firewall, SeLinux for all the 3 nodes.

I am accessing the dashboard url in the master node only and not from any remote workstation.
lease, advise.

**Comment by floreks** [comment]
Not enough information about how did you deploy dashboard, if you have used `kubectl proxy`, etc. Fill out the issue form correctly.

**Comment by shaktiprasadrath** [comment]
I referred this beow link to deploy the Kubernetes dashboard:

https://github.com/kubernetes/dashboard

Steps:
1. Execute the below command in master node:
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

Output:
secret/kubernetes-dashboard-certs created
serviceaccount/kubernetes-dashboard created
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
deployment.apps/kubernetes-dashboard created
service/kubernetes-dashboard created

2. hen execute the below command to access the dashboard:
$ kubectl proxy

Output:
Starting 127.0.0.1:8001

3. Then the open the chrome bowser in master node and execute the below url to see the dashboard
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

Output:
Error: 'dial tcp 172.30.1.4:8443: i/o timeout'
Trying to reach 'https://172.30.1.4:8443/'


All my nodes are of centos7
Let me know, if that helps or any more information is required.

**Comment by floreks** [comment]
After running `kubectl proxy` go to `http://localhost:8001/api/v1/namespaces` and tell me if this works.

**Comment by shaktiprasadrath** [comment]
This is the below output:

{
  "kind": "NamespaceList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces",
    "resourceVersion": "19935"
  },
  "items": [
    {
      "metadata": {
        "name": "default",
        "selfLink": "/api/v1/namespaces/default",
        "uid": "84a0f8d2-1e06-11e9-8e83-080027995e9c",
        "resourceVersion": "4",
        "creationTimestamp": "2019-01-22T05:28:15Z"
      },
      "spec": {
        "finalizers": [
          "kubernetes"
        ]
      },
      "status": {
        "phase": "Active"
      }
    },
    {
      "metadata": {
        "name": "kube-public",
        "selfLink": "/api/v1/namespaces/kube-public",
        "uid": "84b0126f-1e06-11e9-8e83-080027995e9c",
        "resourceVersion": "40",
        "creationTimestamp": "2019-01-22T05:28:15Z"
      },
      "spec": {
        "finalizers": [
          "kubernetes"
        ]
      },
      "status": {
        "phase": "Active"
      }
    },
    {
      "metadata": {
        "name": "kube-system",
        "selfLink": "/api/v1/namespaces/kube-system",
        "uid": "84ae0037-1e06-11e9-8e83-080027995e9c",
        "resourceVersion": "37",
        "creationTimestamp": "2019-01-22T05:28:15Z"
      },
      "spec": {
        "finalizers": [
          "kubernetes"
        ]
      },
      "status": {
        "phase": "Active"
      }
    }
  ]
}

**Comment by floreks** [comment]
Ok, this is most likely a networking issue in your cluster. API server does not correctly proxy to the service.

**Comment by shaktiprasadrath** [comment]
what network issue?? Do you know?? 

FYI, I have used below kubeadm configuration and flannel network

kubeadm init --pod-network-cidr=172.30.0.0/16

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

Plz advise

**Comment by floreks** [comment]
We can help with Dashboard related issue. Kubernetes related issues are handled by a kubernetes core team.

> Error: 'dial tcp 172.30.1.4:8443: i/o timeout'
Trying to reach 'https://172.30.1.4:8443/'

This error means that apiserver didn't even let you reach Dashboard. Most probably if you try to access any other application through apiserver service proxy, you will see this error.

**Comment by shaktiprasadrath** [comment]
Can you add K8 core team to this issue?? or let me know how to reach out core team??

**Comment by shaktiprasadrath** [comment]
And per the below output the apiserver is working fine then what let you tell this is an apiserver issue:

$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                   READY   STATUS             RESTARTS   AGE   IP            NODE      NOMINATED NODE   READINESS GATES
kube-system   coredns-86c58d9df4-8hdzj               0/1     CrashLoopBackOff   125        40h   172.30.1.10   kslave    <none>           <none>
kube-system   coredns-86c58d9df4-sqwkg               1/1     Running            126        40h   172.30.1.8    kslave    <none>           <none>
kube-system   etcd-kmaster                           1/1     Running            4          40h   10.0.0.210    kmaster   <none>           <none>
**kube-system   kube-apiserver-kmaster                 1/1     Running            4          40h   10.0.0.210    kmaster   <none>           <none>**
kube-system   kube-controller-manager-kmaster        1/1     Running            4          40h   10.0.0.210    kmaster   <none>           <none>
kube-system   kube-flannel-ds-amd64-4b4p6            1/1     Running            4          40h   10.0.0.181    kchild    <none>           <none>
kube-system   kube-flannel-ds-amd64-jdgnr            1/1     Running            4          40h   10.0.0.210    kmaster   <none>           <none>
kube-system   kube-flannel-ds-amd64-stjx7            1/1     Running            4          40h   10.0.0.231    kslave    <none>           <none>
kube-system   kube-proxy-bx9rx                       1/1     Running            4          40h   10.0.0.210    kmaster   <none>           <none>
kube-system   kube-proxy-gldcc                       1/1     Running            2          40h   10.0.0.181    kchild    <none>           <none>
kube-system   kube-proxy-hsch6                       1/1     Running            2          40h   10.0.0.231    kslave    <none>           <none>
kube-system   kube-scheduler-kmaster                 1/1     Running            4          40h   10.0.0.210    kmaster   <none>           <none>
kube-system   kubernetes-dashboard-57df4db6b-544ml   0/1     CrashLoopBackOff   100        39h   172.30.1.9    kslave    <none>           <none>

**Comment by shaktiprasadrath** [comment]
When I tried now for the below url I got diff output

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy


{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

In documentation, no other steps are mentioned to access the dashboard locally.

**Comment by floreks** [comment]
1. You need to know how to diagnose the issue first.
2. Dashboard has crashed `kube-system kubernetes-dashboard-57df4db6b-544ml 0/1 CrashLoopBackOff 100 39h 172.30.1.9 kslave`
3. `core-dns` (networking) has crashed `kube-system coredns-86c58d9df4-8hdzj 0/1 CrashLoopBackOff 125 40h 172.30.1.10 kslave`
4. Kubernetes core has its own repository.

**Comment by maciaszczykm** [comment]
> Can you add K8 core team to this issue?? or let me know how to reach out core team??

https://github.com/kubernetes/kubernetes/issues/new/choose

**Comment by jeefy** [comment]
Agree, this is a networking issue in-cluster and not a Dashboard related issue.

Please open an issue within the core Kubernetes repo, or hop into slack for help with your problem.

/close
