### ISSUE TITLE
Use KinD instead of Minikube for e2e tests

### ISSUE THREAD

**Issue by jeefy** [kubernetes/dashboard#3539]
##### What would you like to be added
We should move our e2e tests to use kind (https://github.com/kubernetes-sigs/kind) 

##### Why is this needed
Lighter weight testing, removes the need for minikube, and it's the general direction testing is going.

##### Comments
This is a placeholder issue, I'm gonna look to tackle this in the next couple weeks.

/assign

**Comment by maciaszczykm** [comment]
Big +1 from my side 👍
