### ISSUE TITLE
Document which versions of K8s masters are compatible

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#355]
Per #349, the UI does not work on 1.0.x masters.

**Comment by maciaszczykm** [comment]
We are trying to follow Kubernetes core versioning, so our 1.6 should be always compatible with Kubernetes 1.6. Moreover, we have annotation in `README.md` related to compatibility:

```
If you are using Kubernetes 1.5 or earlier, you can install the latest stable release by running the following command:
```

Should we still prepare any kind of matrix here?
