### ISSUE TITLE
kubernetes-dashboard deployment has wrong url for the image

### ISSUE THREAD

**Issue by shbhardwaj** [kubernetes/dashboard#3556]
Instructions used to deploy
https://github.com/kubernetes/dashboard#getting-started

##### Steps to reproduce
Using the master branch kubernetes-dashboard.yaml

kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/alternative/kubernetes-dashboard.yaml

##### Observed result
kubernetes-dashboard   0/1     ErrImagePull   0          10s
kubernetes-dashboard   0/1    ImagePullBackOff

##### Expected result
kubernetes-dashboard   0/1     Running 0          10s

##### Comments
The image url is wrong in https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/alternative/kubernetes-dashboard.yaml. 

It should be 
image: kubernetesdashboarddev/kubernetes-dashboard-amd64:v2.0.0-alpha0 
instead of 
image: k8s.gcr.io/kubernetes-dashboard-amd64:v2.0.0-alpha0

**Comment by maciaszczykm** [comment]
This is the actual link from getting started that you have linked:

```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
```
