### ISSUE TITLE
Prevent page exit on the create page when there are unsaved changes

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/dashboard#3567]
##### What would you like to be added

On the resource creation page, it will be good to have a prompt asking users to confirm page reloads or navigation if the user has entered some content that have not yet been uploaded.
The prompt should also be applied on the various resource editing sections in the dashboard.

##### Why is this needed

This will ensure users do not accidentally lose contents they have entered in the boxes.

##### Comments
A sample prompt:

![image](https://user-images.githubusercontent.com/11166933/52707100-394dc800-2f87-11e9-8729-65c5219ad808.png)

**Comment by maciaszczykm** [comment]
In case of reload it is fine, I am wondering if we need it for navigation.

cc @floreks

**Comment by eloyekunle** [comment]
If we'll save the changes locally even when the user navigates, then we can skip it for navigation and only show it for reload.
Otherwise, the changes will be lost on navigation.

**Comment by DanielUche** [comment]
i would like to work on this issue

**Comment by eloyekunle** [comment]
@DanielUche Great :)

**Comment by prnam** [comment]
Fixed on #6566

/close

**Comment by prnam** [comment]
Hey @floreks,

This is fixed on #6566, kindly close.
