### ISSUE TITLE
Setup codecov for backend code

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#357]
At in title. Setup codecov coverage for backend code. We already have this for frontend.

CC @floreks ?

**Comment by floreks** [comment]
I'll take a look at that.

**Comment by bryk** [comment]
Awesome, thanks!

**Comment by floreks** [comment]
I've checked that briefly and I'm afraid that all tests would have to be refactored to make codecov work with Go.

https://github.com/codecov/example-go

We are not using any testing framework or matcher in tests. Also we would need to use ginkgo reporter. This is quite big change. Should we go with that now?

**Comment by bryk** [comment]
Ok, not now. Thanks for investigating this. Let's just keep this in backlog.
