### ISSUE TITLE
Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by doudou0312** [kubernetes/dashboard#3570]
issue details:
Possibly unhandled rejection: {"data":"MSG_LOGIN_UNAUTHORIZED_ERROR\n","status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/v1/rbac/status","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Unauthorized","xhrStatus":"complete","resource":{}}
![image](https://user-images.githubusercontent.com/30106688/52770623-91132e80-306e-11e9-824d-598a0cb3a279.png)
my config:
[program:kube-apiserver]
command=/usr/bin/kube-apiserver --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --insecure-bind-address=0.0.0.0 --etcd-servers=http://localhost:2379 --service-cluster-ip-range=100.0.0.128/25 --anonymous-auth=false --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota,ServiceAccount --client-ca-file=/etc/kubernetes/ca.crt --tls-private-key-file=/etc/kubernetes/server.key --tls-cert-file=/etc/kubernetes/server.crt --service-account-key-file=/etc/kubernetes/server.key
numprocs=1
autostart=yes
autorestart=yes
user=root
redirect_stderr=true
stdout_logfile=/var/log/kube-apiserver.log
startsecs=5
stopasgroup=true

[program:kube-controller-manager]
command=/usr/bin/kube-controller-manager --master=http://192.168.137.101:8080 --service-account-private-key-file=/etc/kubernetes/server.key --root-ca-file=/etc/kubernetes/ca.crt
numprocs=1
autostart=yes
autorestart=yes
user=root
redirect_stderr=true
stdout_logfile=/var/log/kube-controller-manager.log
startsecs=5
stopasgroup=true

[program:kubectl-proxy]
command=/usr/bin/kubectl proxy --disable-filter=true --address 0.0.0.0 --accept-hosts '.*'
numprocs=1
autostart=yes
autorestart=yes
user=root
redirect_stderr=true
stdout_logfile=/var/log/kubectl-proxy.log
startsecs=5
stopasgroup=true

[program:kubelet]
command=/usr/bin/kubelet --address=0.0.0.0 --kubeconfig=/etc/kubernetes/master-kubeconfig.yaml --cluster-dns=100.0.0.250 --cluster-domain=cluster.local --resolv-conf=/etc/resolv.conf
numprocs=1
autostart=yes
autorestart=yes
user=root
redirect_stderr=true
stdout_logfile=/var/log/kubelet.log
startsecs=5
stopasgroup=true

[program:kube-proxy]
command=/usr/bin/kube-proxy --master=http://192.168.137.101:8080
numprocs=1
autostart=yes
autorestart=yes
user=root
redirect_stderr=true
stdout_logfile=/var/log/kube-proxy.log
startsecs=5
stopasgroup=true

[program:kube-scheduler]
command=/usr/bin/kube-scheduler --master=http://192.168.137.101:8080
numprocs=1
autostart=yes
autorestart=yes
user=root
redirect_stderr=true
stdout_logfile=/var/log/kube-scheduler.log
startsecs=5
stopasgroup=true

**Comment by maciaszczykm** [comment]
Quite important information is missing. How does your kubeconfig file look like (remember to redact sensitive data)?

/triage needs-information

**Comment by doudou0312** [comment]
[root@master tmp]# cat /etc/kubernetes/master-kubeconfig.yaml 
kind: Config
clusters:
- name: local
  cluster:
    server: http://192.168.137.101:8080
users:
- name: kubelet
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context

**Comment by floreks** [comment]
@doudou0312 There is no auth info in this file. It will not work. Use correct kubeconfig file with auth info defined in it or use token to log in.

**Comment by floreks** [comment]
@doudou0312 There is no auth info in this file. It will not work. Use correct kubeconfig file with auth info defined in it or use token to log in.

/close

**Comment by doudou0312** [comment]
I use token to log in ,but the web page cann't log in .
![image](https://user-images.githubusercontent.com/30106688/52781440-8b761280-3087-11e9-9519-7a35e423906d.png)
I use this command to get the token
kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')

**Comment by floreks** [comment]
Your browser is blocking the request. Either you are not using `localhost` to access Dashboard or you are trying to access it in a non-secure way. It is also possible that your browser has some extra security options enabled.
