### ISSUE TITLE
hello,What are the prerequisites for deploying this project?

### ISSUE THREAD

**Issue by bestbelief** [kubernetes/dashboard#3582]
Running

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml
```
from the README

Error: 
unable to recognize "https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused

Hello, I want to know the configuration conditions before deploying this project? I have reported the above errors according to README. MD command. I hope I can get your help. Thank you!

**Comment by jeefy** [comment]
Hi @bestbelief -- I love your avatar!

Based on that error, it looks like `kubectl` can't talk to the API Server it's configured for. I imagine if you ran `kubectl get pods` it would probably return a similar error. 

As this isn't a problem with the Dashboard and looks to be an issue with your local/kubectl config, I'm going to close this issue. Please re-open with additional clarifying information if there is any.

Thanks!

/close

**Comment by bestbelief** [comment]
Thank you Your avatar is also very stylish. It seems that my local host and port are not specified.

`The connection to the server localhost:8080 was refused - did you specify the right host or port?`
