### ISSUE TITLE
Hello, I failed to deploy this project locally. Would you please help me see it?

### ISSUE THREAD

**Issue by bestbelief** [kubernetes/dashboard#3592]
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ **sudo kubectl version**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

dev@ubuntu:/work/dev/project/angular-pen/dashboard$ **sudo  kubectl proxy**
Starting to serve on 127.0.0.1:8001

In http://localhost:8001 ， can see the API address. as follows
JSON
  paths
    /api
   /api/v1
   /apis
   /apis/
   /apis/admissionregistration.k8s.io
   /apis/admissionregistration.k8s.io/v1beta1
   /apis/apiextensions.k8s.io
   /apis/apiextensions.k8s.io/v1beta1
   /apis/apiregistration.k8s.io
   /apis/apiregistration.k8s.io/v1
   .......
   /swagger-2.0.0.pb-v1
   /swagger-2.0.0.pb-v1.gz
   /swagger.json
   /swaggerapi
   /version

But in http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/, Error

Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://172.17.0.4:9090/'

Would you please help me see why?

**Comment by floreks** [comment]
There is basically no information about how the cluster was created and how the Dashboard was deployed. Additionally, I see that your client version `v1.13` and server is `v1.10` which is a big difference and might not work correctly together.

**Comment by bestbelief** [comment]
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ **sudo minikube start**
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

dev@ubuntu:/work/dev/project/angular-pen/dashboard$ **sudo  kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml**
secret/kubernetes-dashboard-certs created
serviceaccount/kubernetes-dashboard created
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
service/kubernetes-dashboard configured
The Deployment "kubernetes-dashboard" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"k8s-app":"kubernetes-dashboard"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by maciaszczykm** [comment]
> The Deployment "kubernetes-dashboard" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"k8s-app":"kubernetes-dashboard"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

Try to deploy Dashboard with a different name because as you can see your deployment failed.

**Comment by maciaszczykm** [comment]
BTW your minikube already has Dashboard inside. Go to minikube docs to read more.

**Comment by floreks** [comment]
@maciaszczykm  doesn't minikube deploy some kind of Dashboard by default?

**Comment by bestbelief** [comment]
Sorry, what do you mean by other names? @maciaszczykm

**Comment by floreks** [comment]
I think you should refer to minikube docs and use Dashboard deployed by them. There should be info there how to access it.

/close

**Comment by bestbelief** [comment]
dev@ubuntu:/work/dev/project/angular-pen/dashboard$ **sudo  kubectl get po --all-namespaces**
NAMESPACE     NAME                                                    READY   STATUS    RESTARTS   AGE
kube-system   coredns-5bfd87b64b-tmwpm                      1/1          Running   0          19m
kube-system   etcd-minikube                                              1/1         Running   0          18m
kube-system   kube-addon-manager-minikube                  1/1         Running   0          18m
kube-system   kube-apiserver-minikube                              1/1       Running   0          18m
kube-system   kube-controller-manager-minikube              1/1       Running   0          18m
kube-system   kube-dns-b4bd9576-xwxgx                         3/3        Running   0          19m
kube-system   kube-proxy-xzvx8                                        1/1         Running   0          19m
kube-system   kube-scheduler-minikube                            1/1       Running   0          18m
kube-system   kubernetes-dashboard-866c7586d-spqth   1/1       Running   0          19m
kube-system   storage-provisioner                                     1/1       Running   0          19m

dev@ubuntu:/work/dev/project/angular-pen/dashboard$ **sudo minikube dashboard**
Opening http://127.0.0.1:45831/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
[25105:25105:0221/174343.276474:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[25115:25115:0221/174343.299951:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/dev which is owned by dev.)
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium-browser: not found
[25145:25145:0221/174343.354333:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://127.0.0.1:45831/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/'
failed to open browser: exit status 3
