### ISSUE TITLE
Are screen readers supported - are there shortcuts/docs?

### ISSUE THREAD

**Issue by molaachir** [kubernetes/dashboard#3601]
Basic screen reader support is there, but pages can be quite big and some elements may be hard to understand. I wouln't be able to tell you what a button labeled "arrow_drop_up arrow_drop_down" does, for example. it might be a good idea to create documentation about using the Kubernetes dashboard with a screen reader. Good labeling would also be appreciated, and last but not least giving important elements within the UI clear IDws. This can then be used to create scripts for Jaws or add ons for NVDA to be able to quickly move within the UI. That would greatly increase productivity within the UI. Right now the UI is hard to move around. I'd be happy to trade ideas with the development team about this, and to break this down in achievable tasks.

**Comment by floreks** [comment]
Screen readers are not supported and I am not sure if we'll ever support them officially, as we do not have resources to do that.

**Comment by maciaszczykm** [comment]
@molaachir Are you willing to work on it?

**Comment by molaachir** [comment]
@maciaszczykm, I would be, although I am not an FE developerr, and i might need some help getting started on it. Can that be arranged?

**Comment by maciaszczykm** [comment]
I think we can manage.

**Comment by molaachir** [comment]
Great

**Comment by maciaszczykm** [comment]
Closing as stale.
