### ISSUE TITLE
Unable to switch containers in the terminal

### ISSUE THREAD

**Issue by eightlimbed** [kubernetes/dashboard#3602]
##### Environment

```
Installation method:
Kubernetes version: v1.13.1
Dashboard version: v1.10.1
Operating system: MacOS
Node.js version ('node --version' output): v10.15.0
Go version ('go version' output): go1.11.1 darwin/amd64
```

##### Steps to reproduce

1. Deploy the kubernetes dashboard Deployment, NetworkPolicy, Service, etc.
2. Port-forward the deployment, mapping the `--insecure-port` to localhost:whatever
3. Select a Pod that has more than one container in it
4. Click "Exec" button to go to terminal
5. Terminal displays shell prompt for default container
6. Use drop-down arrow to switch to a different container in the Pod

##### Observed result

* A popup message appears that displays the message: `Normal closure`
* User is directed back to the shell of the default container

##### Expected result

* Terminal should display the shell prompt of the container that was selected from the dropdown menu.

**Comment by anuragprafulla** [comment]
I would like to work on this one. It's my first dashboard issue so it'll be great if I could get some help along the way.

**Comment by maciaszczykm** [comment]
@anuragprafulla Sure, it would be the best to open the PR and ask questions from there. If you don't know anything that should be asked before then you can do it from here or on #sig-ui Slack.

**Comment by huangcuiyang** [comment]
The problem is also happend after i upgrade dashboard from version v2.0.0-beta5 to version v2.0.0.0-beta8, why???
