### ISSUE TITLE
Show tooltip timestamp on time hover across pages

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/dashboard#3631]
##### What would you like to be added
We should show tooltip timestamps on hover of absolute and relative time displayed across the components to give specific time information to the users.

For example, dates as shown below are not very helpful, because I might want to know exactly when the events occured.

![screenshot from 2019-03-04 18-18-49](https://user-images.githubusercontent.com/11166933/53750446-150c4980-3eaa-11e9-8c6b-87706616fced.png)

##### Why is this needed
To improve the user experience of users by giving them more information about dates and times across the dashboard.

##### Comments
In general, tooltips can look like below, with the dotted underline added as a visual cue for users to know they can hover:

![screenshot from 2019-03-04 18-15-43](https://user-images.githubusercontent.com/11166933/53750338-ca8acd00-3ea9-11e9-9c9e-dec79ba32794.png)
(credit: [this article](https://uxmovement.com/content/absolute-vs-relative-timestamps-when-to-use-which/))

To proceed, you might need to check places where times/dates are shown, e.g. events, conditions etc, and then investigate the use of [Material Tooltips](https://material.angular.io/components/tooltip/overview) for the tooltips.

/good-first-issue

**Comment by anuragprafulla** [comment]
@eloyekunle I would like to give this a try. I have thought of a solution and am working on it.

**Comment by anuragprafulla** [comment]
Is this issue still open?
