### ISSUE TITLE
Hi CPU usage on 1.10.0 Kubernetes Dashboard

### ISSUE THREAD

**Issue by vasicvuk** [kubernetes/dashboard#3638]
##### Environment

Installation method:
Kubernetes version: 1.11.7
Dashboard version: 1.10.0
Operating system: Ubuntu 18.04.01

##### Steps to reproduce

1. Go into Pods for namespace having 50 pods
2. Api is getting back results in 70ms
3. Front end acts very slow in rendering giving 100% of CPU usage

Here is the picture from Chrome task manager.
![image](https://user-images.githubusercontent.com/5639877/54033063-9c600280-41b3-11e9-966d-2f7e290462bd.png)

##### Machine specs
Intel Core i7-7500U
16 gb ddr4

just to know that this is not slow machine to work on in general

##### Expected result

To have faster load of pages

**Comment by floreks** [comment]
Have you tried using the newest version of Dashboard `v1.10.1`? If issue persists then reopen

/close

**Comment by vasicvuk** [comment]
@floreks It's worse then 1.10.0. I will open it for 1.10.1
