### ISSUE TITLE
Hi CPU usage on 1.10.1 Kubernetes Dashboard

### ISSUE THREAD

**Issue by vasicvuk** [kubernetes/dashboard#3639]
##### Environment

Installation method:
Kubernetes version: 1.11.7
Dashboard version: 1.10.1
Operating system: Windows 10
Browser: Google Chrome - latest version

##### Steps to reproduce

1. Go into Pods for namespace having 50 pods
2. Api is getting back results in 70ms
3. Front end acts very slow in rendering giving 100% of CPU usage

Here is the picture from Chrome task manager.
![image](https://user-images.githubusercontent.com/5639877/54037823-57da6400-41bf-11e9-8a3e-3d6f01a5055c.png)

##### Machine specs
Intel Core i7-7500U
16 gb ddr4

just to know that this is not slow machine to work on in general

##### Expected result

To have faster load of pages

**Comment by floreks** [comment]
I am not sure how exactly you workflow looks like, but I don't see any issues with pod list view. Even having over 100 pods is not an issue.

![zrzut ekranu z 2019-03-08 17-01-23](https://user-images.githubusercontent.com/2285385/54039729-f8cb1e00-41c3-11e9-8fed-823adc8540bc.png)

**Comment by vasicvuk** [comment]
@floreks Your screenshot shows the rendered page. Mine was taken during the rendering. During the rendering it uses from 60 to 190 CPU % on Chrome which quite a value. 

Switch a little bit between pods and jobs and you will get the High CPU load.

Also the animations during the loading are very slow and the whole experience feels little blocked

**Comment by vasicvuk** [comment]
I tested Dashboard based on Angular 7 and it seems that it works better.

I really dont understand why the performance of current version is so bad specially when rendering Overview screen of some namespace.

**Comment by floreks** [comment]
New version is optimized better and rewritten from scratch. Some things work differently and it better handles async download of resources.
