### ISSUE TITLE
Remove old i18n files

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3645]
https://github.com/kubernetes/dashboard/tree/master/i18n

**Comment by floreks** [comment]
Only `*.xtb` file can be removed. Other 2 are actually configured for new angular.

**Comment by maciaszczykm** [comment]
Yes, noticed that after posting the issue in the Slack channel 🙂

**Comment by phoenixking25** [comment]
@floreks can you take a look on pr i think other 2 files are also not necessary. :)
