### ISSUE TITLE
Dashboard failing to get overview for all namespaces

### ISSUE THREAD

**Issue by AlexShemeshWix** [kubernetes/dashboard#3647]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Unknown Server Error (502):
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

##### Comments
It works fine on some of the cluster with low load. But when we create cluster with lots of resources.
It just hangs and gives this error.
Ive tried to give it more resources. Didnt help

**Comment by maciaszczykm** [comment]
>Ive tried to give it more resources. Didnt help

Can you give us numbers?

**Comment by floreks** [comment]
> `<hr><center>nginx/1.15.8</center>`

What is this? We are not using nginx in any way. I believe this might be configuration issue.

**Comment by AlexShemeshWix** [comment]
Ngnix is just ingress proxy. 
Can it be that ingress has not enough timeout? 
We have 120 nodes and 250 pods. And i have this error if i ask for pods in all namespaces.

**Comment by floreks** [comment]
I'd say first try to access Dashboard directly and see if same issue exists. In example you can use `kubectl proxy`.

**Comment by maciaszczykm** [comment]
Please reopen if the issue persists.

/lifecycle rotten
/close
