### ISSUE TITLE
exec crashes when traffic goes throw ingress-nginx  (v2.go:105] sockjs: session not in open state)

### ISSUE THREAD

**Issue by Ultrafenrir** [kubernetes/dashboard#3654]
##### Environment

```
Installation method: kubespray
Kubernetes version: 1.12.5
Dashboard version: 1.10.1 
Operating system: Centos 7
Node.js version ('node --version' output): wat
Go version ('go version' output): wat
```

##### Steps to reproduce

Setup an ingress-nginx controller (0.20.0) create an ingress for dashboard service with tls termination, access dashboard by https://some.domain and click on exec pod

##### Observed result

It working a random amount of time ( 1 min in average) and throw connection closed
In dashboard logs i see v2.go:105] sockjs: session not in open state
in ingress logs i see only 200 responses to dashboard service

##### Expected result

Working exec without termination every 30sec-1min

##### Comments

It working pretty nice throw a nodeport, but it's awfull to access dashboard like this.

**Comment by floreks** [comment]
If it works with a NodePort then it can't be just a Dashboard issue. I think it might be nginx that force closes the persistent connection. Try adjusting nginx config (timeouts, keepalive, etc.)

**Comment by Ultrafenrir** [comment]
> If it works with a NodePort then it can't be just a Dashboard issue. I think it might be nginx that force closes the persistent connection. Try adjusting nginx config (timeouts, keepalive, etc.)

I think that if this be only a issue with ingress-controller, the time of getting error every time being equal, and not correlating from 30 sec to 1-2mins. Thank you for a suggestion, i'am already increase all timeouts to 300 by annotating ingress object, and get the same result

**Comment by Ultrafenrir** [comment]
And if the kubernetes-dashboard need some special settings to work throw ingress, could you adjust installation manual with any ? It will be really great.

**Comment by floreks** [comment]
We do not officially offer information about exposing Dashboard through ingress because there are too many possible configurations and controllers that could be used. It would raise too many questions and it requires Kubernetes knowledge rather than just knowledge about some application (i.e. Dashboard).

Try to access Dashboard through `kubectl proxy` and see if issue persists. It is also a kind of proxy and if it will work fine then it can't be just a Dashboard issue.

**Comment by Ultrafenrir** [comment]
> We do not officially offer information about exposing Dashboard through ingress because there are too many possible configurations and controllers that could be used. It would raise too many questions and it requires Kubernetes knowledge rather than just knowledge about some application (i.e. Dashboard).
> 
> Try to access Dashboard through `kubectl proxy` and see if issue persists. It is also a kind of proxy and if it will work fine then it can't be just a Dashboard issue.

Thanks for an answer, ok, if u think so - this issue can be closed.
