### ISSUE TITLE
Observe if lint-staged works with Go files

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3656]
Tracker mentioned in https://github.com/kubernetes/dashboard/pull/3614.

**Comment by shu-mutou** [comment]
Following comments and observations were summerized from #3653:

https://github.com/kubernetes/dashboard/blob/1e9a6b1927da456cf6b2aeb07e4c0d317207bd2b/package.json#L68-L70

According to lint-staged documentation [1], file pathes would be passed as list.
[1] https://github.com/okonet/lint-staged#lintstagedrc-example

like: `golangci-lint run -c .golangci.yml --fix src/app/backend/handler/apihandler.go src/app/backend/integration/metric/heapster/client_test.go`

But if multiple file paths was passed to golangci-lint, it causes error like follow:
`ERRO Running error: context loading failed: no go files to analyze`

If single file path was passed to golangci-lint, the check runs successfully.

In my observations:
* It seems to run once even if we change 20 go files actually.
* Adding `src/app/backend/...` at the end, golangci-lint seems to run as we expected.

**Comment by shu-mutou** [comment]
I found that due to [bug on golangci-lint][https://github.com/golangci/golangci-lint/issues/391], multiple files check failes sometimes.
We need to check each files independently.
