### ISSUE TITLE
Display usage metrics for multiple resources

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#366]
Dashboard should provide kubedash-like functionality to allow for monitoring Kubernetes resources, like seeing resource usage of a pod over time.

**Comment by bryk** [comment]
As of now, mini-graphs of resource usage are worked on, see mocks: https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/11-11-2015/17_job%20details.png

When this is done, adding new graphs in other places will be easy, as the infrastructure will be there.

**Comment by bryk** [comment]
CC @bgrant0607-cc @aronchick @joeatwork

**Comment by vishh** [comment]
cc @vishh

**Comment by joeatwork** [comment]
I'm in the process of adding this fn now - the API freeze might make it more difficult, though.

**Comment by aronchick** [comment]
That's great to hear Joe! Let me know if there's anything we can do between
now and then.

**Comment by maciaszczykm** [comment]
I think it's almost finished. Only thing missing seems to be adding sparklines to the replication controller list cards. Am I right? Should we close this issue and create another for missing enhancement?

**Comment by bryk** [comment]
I think that this is not that close to be finished. We need more metrics displayed on more resources (e.g., containers or nodes).

**Comment by maciaszczykm** [comment]
Yes, I didn't consider containers and nodes. And there will be even more resources soon.

**Comment by floreks** [comment]
This is done already.

/close
