### ISSUE TITLE
 Kubernetes Dashboard start container error

### ISSUE THREAD

**Issue by miaoyukai** [kubernetes/dashboard#3683]
error log
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. 

I think it's a error.It's a configuration problem.But I don't know the exact configuration.

![)B B2WHC58K%_@~33LA815W](https://user-images.githubusercontent.com/38027640/54745072-9f231480-4c03-11e9-9775-c898d9eabfa1.png)

**Comment by floreks** [comment]
1. `dacloud.io/.../kubernetes-dashboard:1.8.3` is an outdated image not supported by us (not from an official registry). Latest version is `v1.10.1`.
2. We are not familiar with your configuration, therefore we can not help with the configuration itself.
3. `--apiserver-host` should not be used normally. Dashboard should be started inside the cluster, unless you know what you are doing.
4. This is not a `failing-test` issue, but a support request. Without properly describing the issue, setup, configuration, etc. we are not able to help.

/close
