### ISSUE TITLE
Unknown reference kind when working with CRDs

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes/dashboard#3684]
##### Steps to reproduce

Have pod reference custom CRD I'm developing

##### Environment
```
Installation method: helm chart 
Kubernetes version: 1.13.4
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Unknown Server Error (500):
```
Unknown reference kind Modbus

```

##### Comments
Also, there's minimal support for CRDs

**Comment by floreks** [comment]
Will be covered by #2493 

/close
