### ISSUE TITLE
Provide a config option to specify the statics path when running the Dashboard on a subpath using an Ingress rule (and controller)

### ISSUE THREAD

**Issue by michaelajr** [kubernetes/dashboard#3686]
Right now if you expose the Dashboard via an Ingress Controller and Ingress rule, and want to run the Dashboard on a subpath like `/dashboard`, statics can't load. This is because the URL for statics are embedded in the HTML as coming from the root. Most UI applications provide a way to start their app with a flag that specifies the application root so URLs are constructed properly in the page. This would be really nice to have for the Dashboard.

**Comment by maciaszczykm** [comment]
/lifecycle frozen

@michaelajr Would you be willing to work on that?

**Comment by webcoderz** [comment]
Would this solve: https://github.com/kubernetes/dashboard/issues/5017? If so then it's a great idea!

**Comment by luchillo17** [comment]
I took a different approach with rewrite/redirect on the Ingress resource, hard to find, not documented anywhere & took me a whole week to figure out (barely know much of Ingress) https://github.com/kubernetes/dashboard/issues/7616#issuecomment-1573320650

**Comment by floreks** [comment]
See my comment: https://github.com/kubernetes/dashboard/issues/8053#issuecomment-1979494075
