### ISSUE TITLE
Clicking sign in on web dashboard does nothing.

### ISSUE THREAD

**Issue by Aphris-Karu** [kubernetes/dashboard#3689]
I have followed a dozen different posts on how to create an admin account for the web dashboard, get the token, and log in as well as ways of making a kubeconfig to log in and none of them appear to work.

I did notice that some of them give an orange box with an error but the token ones dont seem to give any error or log me in. As a matter of fact, there is no reaction to clicking on the sign in button and no indication of it failing, rejecting, or anything. Almost like the button is broken. The last try was creating a login key that appears to be right but the interface does nothing.

Token key created

```
Name:         AK-token-mh8g9
Namespace:    default
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: AK
              kubernetes.io/service-account.uid: 1e7246ed-4e52-11e9-b9b9-525400d9bf06

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1025 bytes
namespace:  7 bytes
token:      eyJhbGciOiJS(rest of the key removed)
```

Posting it here under the assumption I dont know what I am doing and that the software works. ;)

**Comment by floreks** [comment]
How you are accessing Dashboard?

**Comment by Aphris-Karu** [comment]
Im using kunectl proxy as follows

kubectl proxy --accept-hosts='^*$' --address='192.168.1.201' --port=8001

Then pointing my browser to 

http://192.168.1.201:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Comment by floreks** [comment]
From the [Dashboard documentation](https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above)

> NOTE: Dashboard should not be exposed publicly using kubectl proxy command as it only allows HTTP connection. For domains other than localhost and 127.0.0.1 it will not be possible to sign in. Nothing will happen after clicking Sign in button on login page.

/close

**Comment by halsafar** [comment]
My experience with Kubernetes so far has been sifting through tons of misinformation.   I hate to add to the pile but since this page is the top search result for "sign in button does nothing".  Here is how I got external access working: https://www.thegeekdiary.com/how-to-access-kubernetes-dashboard-externally/

**Comment by aredridel** [comment]
And when "localhost" didn't work for me with dashboard 2.0.0-rc7, using 127.0.0.1 did.

**Comment by hatamiarash7** [comment]
I had the same problem and `127.0.0.1` worked for me ... Why ???

**Comment by qwfys** [comment]
> I had the same problem and `127.0.0.1` worked for me ... Why ???

You can use ssh port forwarding to complete the corresponding work. My blog has a detailed introduction, you can refer to it, the address is https://qwfys.blog.csdn.net/article/details/106359728

**Comment by sksaranraj** [comment]
Hi All,

I am using the AWS Ec2 server. I got the login page on http://<public_Ip>:8001 . When I put token and clicked on signup nothing has happened. Please help me on this issue.

But in EC2 I am getting the below error...

I0718 22:41:03.410128    1910 log.go:172] http: proxy error: context canceled
I0718 22:41:12.132283    1910 log.go:172] http: proxy error: context canceled

**Comment by floreks** [comment]
@sksaranraj update Dashboard to the latest version and you will see an error.

**Comment by sksaranraj** [comment]
Hi,

Can u explain this..i am noob to k8.

Started 2 days back. Please help me

Regards,
Saran Kumaar K
________________________________

**Comment by floreks** [comment]
@sksaranraj use latest version https://github.com/kubernetes/dashboard/releases/tag/v2.0.3

**Comment by sksaranraj** [comment]
Hi Sabestian,

Thanks for the revert. The issue got resolved once I changed the workers nodes node type to Nodeport instead of cluster IP.

Now iam accessing it through worker nodes public ip, it is working fine.

Regards,
Saran Kumaar K
________________________________
