### ISSUE TITLE
pods "undefined" not found

### ISSUE THREAD

**Issue by FANHIDE** [kubernetes/dashboard#3695]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.6.3
Commit: 5b3e0858b3c713052307f2ec83b06853b61fde84
```

##### Observed result
Dashboard reported Not Found (404):
```
pods "undefined" not found

```

**Comment by maciaszczykm** [comment]
Update your Dashboard. Pod probably was deleted before you have entered detail page.

/close
