### ISSUE TITLE
How to reload golang web server

### ISSUE THREAD

**Issue by rombie** [kubernetes/dashboard#3701]
During development, when ever I make front end changes, the changes automatically get reloaded, but back end changes do not. Is there a way to restart just the server part. It takes several minutes otherwise to kill and restart the development container

**Comment by floreks** [comment]
Apply [this fix](https://github.com/kubernetes/dashboard/pull/3615/files#diff-9cf2334b51a517d0b81d54dae0398c03R98) to your code and it will work. We will update it on master ASAP.

/close
