### ISSUE TITLE
Can not authenticate on dashboard through https

### ISSUE THREAD

**Issue by MaxCCC** [kubernetes/dashboard#3704]
I've a kubernetes cluster running:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

I've an Ubuntu 16.04 cluster in Vagrant. The Kubernetes is 1.14.0 version and dashboard is latest master version.

I've installed the dashboard and enabled the nodeport as described [here](https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#nodeport) . I can access the dashboard but I'm not able to authenticate with the token.

`$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
`
I tried this token:
```
kubectl -n kube-system get secret
kubectl -n kube-system describe secret deployment-controller-token-frsqj
```

**Comment by floreks** [comment]
Are you accessing it over http or https? Is there any error message?

**Comment by MaxCCC** [comment]
@floreks I've recreated the whole cluster and now it seems to work. Although I don't understand why it only works when the dashboard is deployed on the master (where the api is running). I can access it from both machines (master and node). I can telnet 10.0.2.15 443 on every node.

**Comment by floreks** [comment]
I have no idea how your environment looks like as you have provided very limited information. Probably connectivity between your nodes is limited and Dashboard cannot connect to apiserver from other node.

/close
