### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by renusharma21** [kubernetes/dashboard#3714]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result

After installing kubernete dashboard I am able to directly access dashboard without login page. Could you please help how can I set up control access through login page via authentication token.

**Comment by floreks** [comment]
Issue form not filled correctly. No information about setup and installation method.

/close
