### ISSUE TITLE
No admin-user-* token created

### ISSUE THREAD

**Issue by dwschulze** [kubernetes/dashboard#3715]
##### Environment

```
Installation method:
Kubernetes version:
Dashboard version:
Operating system:
Node.js version ('node --version' output):
Go version ('go version' output):
```

**Comment by dwschulze** [comment]
The command given to create a token for logging into the dashboard does not give token for the admin user:

kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')

This produces many tokens, but none of them named admin-user-*

**Comment by floreks** [comment]
Provide detailed information about steps to reproduce, your k8s installation, etc.

**Comment by floreks** [comment]
Provide detailed information about steps to reproduce, your k8s installation, etc. Basically, fill out the issue form correctly (with listings) and reopen.

/close

**Comment by sentient** [comment]
same issue here. Was there any resolution?

**Comment by sunsky** [comment]
![Uploading image.png…]()
same issue here

[root@k8s-master k8s]# kubeadm version &&  kubectl version && uname -a && cat /etc/*lease
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Linux k8s-master 3.10.0-514.6.2.el7.toa.2.x86_64 #1 SMP Tue Oct 31 14:54:31 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.3.1611 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core)
CentOS Linux release 7.3.1611 (Core)

**Comment by sunsky** [comment]
![image](https://user-images.githubusercontent.com/570405/57901602-6c5e6b00-7898-11e9-9cd3-f8deb57acd02.png)

**Comment by sunsky** [comment]
![image](https://user-images.githubusercontent.com/570405/57902299-2525a980-789b-11e9-88d8-4263e5a0ca09.png)
![image](https://user-images.githubusercontent.com/570405/57902307-3078d500-789b-11e9-8fd6-234d29d51f46.png)

**Comment by xianshuihu** [comment]
@dwschulze I have encountered the same situation as you, then I tried to put the first provided snippet (Create Service Account) into the yaml file and execute the kubectl command, then the second snippet(Create ClusterRoleBinding) for the same processing. In other words, they are treated as two separate steps, not mixed together, and finally solved.
