### ISSUE TITLE
Microsoft Edge - dashboard sign in

### ISSUE THREAD

**Issue by grahamehorner** [kubernetes/dashboard#3728]
running the dashboard using kubectl and accessing via Micrsoft Edge using a token fails to sign in.
using the same setup and token sign in is successful using Google Chrome

**Comment by xishian** [comment]
Same with you, but even worse when I try to login with token, nothing happened, it's still login page!

**Comment by smiklosovic** [comment]
Same as @xishian, it just does not do anything. With Firefox too.

**Comment by smiklosovic** [comment]
@floreks what that could be?

**Comment by grahamehorner** [comment]
I've reinstalled everything onto a refresh VM and it look as if IE Edge isn't submitting the token to the service for validation; the developer tools don't seem to be showing any errors and fiddler is not seeing any https get/post action out bound?

**Comment by grahamehorner** [comment]
correction:- IE Edge is showing the following errors in debug

HTTP401: DENIED - The requested resource requires user authentication.
(XHR)GET - http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/api/v1/settings/global

HTTP401: DENIED - The requested resource requires user authentication.
(XHR)GET - http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/api/v1/rbac/status

Error during global settings reload:  [object Object]

Possibly unhandled rejection: {"data":"MSG_LOGIN_UNAUTHORIZED_ERROR\n","status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/v1/rbac/status","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Unauthorized","xhrStatus":"complete","resource":{}}

**Comment by smiklosovic** [comment]
In my case it was about roles. You are probably having them wrong.

Start it in such way there is skip button. Then if you are in, you will have the most probably some warnings there. You have to resolve them. After that you can login with token and disable skip.

I used kubectl proxy, I dont think I needed ingress. Actually I did, but it is a parameter to kubectl apply -f _that_dashboard_file (same settings where you set skipping button, just check the doco for dashboard)

**Comment by grahamehorner** [comment]
@smiklosovic I'm not sure what your attempting to describe as I' new to kubernetes and I'm simply following the documented process on the repo; also unsure if this is a role issue as the same setup works using the Google Chrome browser for myself? note the errors occure in IE Edge prior to sign in with a token; but no errors occur in google chrome.

**Comment by maciaszczykm** [comment]
Two things:
1. Please try to verify it again with v2.0.0-beta1 as the frontend was completely rewritten.
2. Don't use Edge :)

/close

**Comment by grahamehorner** [comment]
@maciaszczykm this issue still exists and is present when using Edge and Internet Explorer; IMHO forcing user to use/install a given browser is not a solution.  Please re-open this ticket/issue, I'm happy to assist in trying to identify the root cause and resolve.

**Comment by Cellebyte** [comment]
Still broken with v2.0.0-rc.5 I was confused it only works with Chromium/Chrome. 
Firefox is not working at all.

Recreate it with an Token.
Paste it in the input field click login. The Server is returning a 200 but the SPA is not responding with a redirect.

**Comment by shu-mutou** [comment]
![image](https://user-images.githubusercontent.com/12838129/74815025-ca464480-533b-11ea-85db-10ffd2721e91.png)
Microsoft Edge 44.18362.449.0 can login to dashboard.

**Comment by Cellebyte** [comment]
> ![image](https://user-images.githubusercontent.com/12838129/74815025-ca464480-533b-11ea-85db-10ffd2721e91.png)
> Microsoft Edge 44.18362.449.0 can login to dashboard.

Correct because it is Chromium,
Firefox is still broken.

**Comment by shu-mutou** [comment]
Yes. This issue titled about MS Edge. Issue for firefox subscribed in #4922.

**Comment by floreks** [comment]
Closing this one in favor of #4922

/close
