### ISSUE TITLE
App name validation in deploy flow causes 500s

### ISSUE THREAD

**Issue by codegoblins** [kubernetes/dashboard#373]
<img width="1049" alt="screen shot 2016-02-12 at 3 29 09 pm" src="https://cloud.githubusercontent.com/assets/1609602/13024291/66a95436-d1a7-11e5-9cb3-8db2d4d06979.png">

Console output: 
```
2016/02/12 15:27:55 Validating runcmdtest34239i23 application name in jefsweeney namespace
2016/02/12 15:27:55 the server does not allow access to the requested resource (get replicationControllers runcmdtest34239i23)
2016/02/12 15:27:55 Outcoming response to 127.0.0.1:51717 with 500 status code
```
- This causes the form to be invalidated
- This happens in any namespace
- It seems only application names that start with "run" cause this, but I haven't tried everything

**Comment by floreks** [comment]
What version of kubernetes are you running? Do you have newest version of dashboard deployed? 
Maybe you have a service with that name in this namespace already? Validation also checks for services. Probably error message could be more clear when existing service blocks creation of app.

I've tried to reproduce it and couldn't. I was able to create apps with same name in different namespaces. Name starting with `run...` was fine.

**Comment by bryk** [comment]
@codegoblins What is your security setup? Are your namespaces restricted?

**Comment by codegoblins** [comment]
@floreks Our cluster is running Kubernetes 1.1. I am on the latest master commit of dashboard. Also no matching services in the namespace.  

@bryk It doesn't look like our namespaces are restricted, I have no problems creating pods in other tenants' namespaces. 

Any suggestions how I can further debug this?

**Comment by bryk** [comment]
I was able to reproduce this. Investigating....

**Comment by bryk** [comment]
@codegoblins This is a bug in `kubectl proxy`. Can you maybe contribute to k8s core to fix this? Should be as easy as changing a regex.

**Comment by floreks** [comment]
Ok, now I know why I couldn't reproduce the problem. I'm not using proxy. We should propose some kind of template for creating issues, so we can reproduce and fix problems faster.

**Comment by bryk** [comment]
Yeah, templates like this:https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by floreks** [comment]
This looks really nice. We should prepare a template at some point.
