### ISSUE TITLE
Fix `alternative` deploy files

### ISSUE THREAD

**Issue by Nican** [kubernetes/dashboard#3732]
##### Environment
Running on an ARM environment. 

```
Installation method: Kubernetes
Kubernetes version: v1.14.1
Dashboard version: Dashboard v1.10.0+282.g5fa3725
Operating system: Ubuntu 18.04.2 LTS
Node.js version: N/A
Go version: N/A
```
Attention: using `alternative` deploy. Not `recommended` deploy. 

##### Steps to reproduce
Running 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/alternative/kubernetes-dashboard-arm-head.yaml
```

##### Observed result
The pod does not start. 

Running 
```
kubectl -n kube-system logs -p kubernetes-dashboard-head-7d57ccc57b-7ns54
```
Shows the error message:
```
secrets "kubernetes-dashboard-csrf" not found
```

##### Expected result
The pod to run. 

##### Comments
The commit https://github.com/kubernetes/dashboard/commit/be4f2813b7cc13f682f2af5025d42813c8e7fbd3#diff-a0ed1ebb3f4da2a985b54b6a2ddc770f added the "kubernetes-dashboard-csrf" setting, but did not add it to the `alternative` version of the files. 

I have tried adding the missing configuration to the `alternative` files, and it works as expected: 
https://github.com/Nican/dashboard/commit/e47e94e79c35eb7d3c3b9a922c4aabcc78d8250e

**Comment by floreks** [comment]
@Nican could you create a PR fixing that?

**Comment by Nican** [comment]
Sure. I will make a PR tonight.
