### ISSUE TITLE
Error with networking(?)

### ISSUE THREAD

**Issue by SturdyFool10** [kubernetes/dashboard#3733]
##### Environment

```
Installation method:kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
Kubernetes version:1.14.0
Dashboard version:?
Operating system:"Bionic Beaver" Ubuntu
Node.js version ('node --version' output):8.10.0
Go version ('go version' output):"-bash: go: command not found"
```

##### Steps to reproduce
follow https://vitux.com/install-and-deploy-kubernetes-on-ubuntu/

##### Observed result

Hit command "kubectl describe pods $(Kubernetes-dashboard pod) --namespace=kube-system"
##### Expected result

Name:               kubernetes-dashboard-5f7b999d65-p7clv
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               kubernetes-slave1/10.0.0.215
Start Time:         Sun, 14 Apr 2019 10:20:42 +0000
Labels:             k8s-app=kubernetes-dashboard
                    pod-template-hash=5f7b999d65
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicaSet/kubernetes-dashboard-5f7b999d65
Containers:
  kubernetes-dashboard:
    Container ID:
    Image:         k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
    Image ID:
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-znrkr (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kubernetes-dashboard-token-znrkr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-znrkr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                        Message
  ----     ------                  ----                  ----                        -------
  Normal   Scheduled               37m                   default-scheduler           Successfully assigned kube-system/kubernetes-dashboard-5f7b999d65-p7clv to kubernetes-slave1
  Warning  FailedCreatePodSandBox  37m                   kubelet, kubernetes-slave1  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "4e6d9873f49a02e86cef79e338ce97162291897b2aaad1ddb99c5e066ed42178" network for pod "kubernetes-dashboard-5f7b999d65-p7clv": NetworkPlugin cni failed to set up pod "kubernetes-dashboard-5f7b999d65-p7clv_kube-system" network: failed to find plugin "loopback" in path [/opt/cni/bin], failed to clean up sandbox container "4e6d9873f49a02e86cef79e338ce97162291897b2aaad1ddb99c5e066ed42178" network for pod "kubernetes-dashboard-5f7b999d65-p7clv": NetworkPlugin cni failed to teardown pod "kubernetes-dashboard-5f7b999d65-p7clv_kube-system" network: failed to find plugin "portmap" in path [/opt/cni/bin]]
  Normal   SandboxChanged          31m (x25 over 37m)    kubelet, kubernetes-slave1  Pod sandbox changed, it will be killed and re-created.
  Normal   SandboxChanged          22m (x18 over 26m)    kubelet, kubernetes-slave1  Pod sandbox changed, it will be killed and re-created.
  Normal   SandboxChanged          18m (x13 over 21m)    kubelet, kubernetes-slave1  Pod sandbox changed, it will be killed and re-created.
  Normal   SandboxChanged          2m29s (x70 over 17m)  kubelet, kubernetes-slave1  Pod sandbox changed, it will be killed and re-created.

**Comment by SturdyFool10** [comment]
as a small note I clean installed and installed weave and that also returns the same warning after following the kubernetes.io instructions

**Comment by floreks** [comment]
This is a cluster issue, not related to Dashboard. Look for this error `Pod sandbox changed, it will be killed and re-created.` on the core repo.

/close
