### ISSUE TITLE
Edit service kubernetes-dashboard failed with ClusterIP

### ISSUE THREAD

**Issue by ylacaute** [kubernetes/dashboard#3737]
##### Environment

```
Installation method: kubeadm (manual)
Kubernetes version: v1.14.1
Dashboard version: 1.10.1
Operating system: Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
Node.js version ('node --version' output): No node installed
Go version ('go version' output): No go installed
```

##### Steps to reproduce

With a running cluster with a single node master :
Add the dashboard:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml 
```
Then edit the config by changing type ClusterIP to NodePort :
```
kubectl -n kube-system edit service kubernetes-dashboard
```
Everything ok, then do it again and change type NodePort to ClusterIP :
```
kubectl -n kube-system edit service kubernetes-dashboard
```

##### Observed result

We are unable to save back to ClusterIP type with the following output :
```
error: services "kubernetes-dashboard" is invalid
A copy of your changes has been stored to "/tmp/kubectl-edit-bhe72.yaml"
error: Edit cancelled, no valid changes were saved.
```
##### Expected result

We should be able to update the file exactly as it was after a fresh installation.

**Comment by floreks** [comment]
Not related to Dashboard. You are using CLI that is part of core.

/close
