### ISSUE TITLE
Feature: Add a Refresh button !

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#3740]
##### What would you like to be added
The UI should have are `refresh` button.

##### Why is this needed
So I can see if my job is finished, if my new pods finished loading, etc!

##### Comments

![image](https://user-images.githubusercontent.com/297498/56358101-048f0480-61b4-11e9-8a21-804973fb9c9f.png)

**Comment by floreks** [comment]
This would be handled by #2541. Closing as we will not add the refresh button, but rather go with #2541 implementation.

/close
