### ISSUE TITLE
Enable the login screen when using an Ingress

### ISSUE THREAD

**Issue by AndreKR** [kubernetes/dashboard#3743]
I have deployed the Kubernetes Dashboard behind an Ingress.

With the ["recommended" YAML file](https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/kubernetes-dashboard.yaml) only port 443 is exposed with an invalid certificate. Of course I don't want to fiddle with certificates *in the application*, the ingress controller already takes care of that using ACME.

So I used the ["alternative" YAML file](https://github.com/kubernetes/dashboard/blob/master/aio/deploy/alternative/kubernetes-dashboard.yaml). Unfortunately it seems that with this file the login screen is disabled.

I ran a diff of the two files but I was unable to identify the parameter that disables the login screen.

This should either be documented or - better IMO - there should be a third YAML file for exposing plain HTTP to be used with an Ingress.

I actually found [a section](https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#ingress) in the Wiki about using Dashboard with an Ingress, but that just links to a description what Ingresses are in general.

**Comment by floreks** [comment]
Look at `--enable-insecure-login` flag: https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments

**Comment by AndreKR** [comment]
That works. :+1:
