### ISSUE TITLE
dashboard style error

### ISSUE THREAD

**Issue by 0x2d3c** [kubernetes/dashboard#3744]
Docker                           `17.03.2-ce`
Browser :                      `Chrome 73.0.3683.103 Linux`
Kubernetes:                `v1.14.0`
Dashboard:                 `k8s.gcr.io/kubernetes-dashboard-amd64     v1.10.1`

Screenshot:
![k8s-dashboard](https://user-images.githubusercontent.com/20468895/56423399-782d3080-62de-11e9-80c6-a5d541604c94.png)

**Comment by floreks** [comment]
What is this color? This doesn't look like our official build.

**Comment by 0x2d3c** [comment]
> What is this color? This doesn't look like our official build.

The style was error, i'm not changed the source code

**Comment by floreks** [comment]
It's not possible that color has changed because of some bug. It looks like you are using unofficial dashboard or have misconfigured cluster.

**Comment by 0x2d3c** [comment]
> It's not possible that color has changed because of some bug. It looks like you are using unofficial dashboard or have misconfigured cluster.

Through my tests, this style problem I did not appear in firefox

**Comment by floreks** [comment]
Then it might be a browser related issue. I don't see how it could be caused by the Dashboard itself.

/close
