### ISSUE TITLE
failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.0": output: Error response from daemon

### ISSUE THREAD

**Issue by hyadav1987** [kubernetes/dashboard#3746]
I am trying to install minikube with kubernetes-version v1.14.0 and I see below error

[stderr =====>] :
I0420 21:27:15.304286    1668 kubeconfig.go:127] Using kubeconfig:  C:\Users\hyadav/.kube/config
-   Pulling images required by Kubernetes v1.14.0 ...
I0420 21:27:15.312316    1668 ssh_runner.go:101] SSH: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
I0420 21:27:15.409829    1668 utils.go:240] ! failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.0": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: connect: network is unreachable
I0420 21:27:15.409829    1668 utils.go:240] ! , error: exit status 1
X   Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.0": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: connect: network is unreachable
, error: exit status 1
: Process exited with status 1
-   Launching Kubernetes v1.14.0 using kubeadm ...
I0420 21:27:15.415829    1668 ssh_runner.go:137] Run with output:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

I0420 21:27:15.448969    1668 utils.go:240] ! cannot use "fe80::215:5dff:fe00:a08" as the bind address for the API Server
I0420 21:27:15.451073    1668 ssh_runner.go:137] Run with output: docker ps -a --filter="name=kube-apiserver" --format="{{.ID}}"
I0420 21:27:15.507754    1668 logs.go:155] 0 containers: []
W0420 21:27:15.508683    1668 logs.go:157] No container was found matching "kube-apiserver"
I0420 21:27:15.509721    1668 ssh_runner.go:137] Run with output: docker ps -a --filter="name=coredns" --format="{{.ID}}"
I0420 21:27:15.569060    1668 logs.go:155] 0 containers: []
W0420 21:27:15.570061    1668 logs.go:157] No container was found matching "coredns"
I0420 21:27:15.571079    1668 ssh_runner.go:137] Run with output: docker ps -a --filter="name=kube-scheduler" --format="{{.ID}}"
I0420 21:27:15.634144    1668 logs.go:155] 0 containers: []
W0420 21:27:15.634144    1668 logs.go:157] No container was found matching "kube-scheduler"
I0420 21:27:15.634922    1668 ssh_runner.go:137] Run with output: docker ps -a --filter="name=kube-proxy" --format="{{.ID}}"
I0420 21:27:15.692536    1668 logs.go:155] 0 containers: []
W0420 21:27:15.692536    1668 logs.go:157] No container was found matching "kube-proxy"
I0420 21:27:15.693534    1668 ssh_runner.go:137] Run with output: docker ps -a --filter="name=kube-addon-manager" --format="{{.ID}}"
I0420 21:27:15.751693    1668 logs.go:155] 0 containers: []
W0420 21:27:15.751693    1668 logs.go:157] No container was found matching "kube-addon-manager"
I0420 21:27:15.752268    1668 ssh_runner.go:137] Run with output: docker ps -a --filter="name=kubernetes-dashboard" --format="{{.ID}}"
I0420 21:27:15.806132    1668 logs.go:155] 0 containers: []
W0420 21:27:15.806132    1668 logs.go:157] No container was found matching "kubernetes-dashboard"
I0420 21:27:15.807178    1668 ssh_runner.go:137] Run with output: docker ps -a --filter="name=storage-provisioner" --format="{{.ID}}"
I0420 21:27:15.864116    1668 logs.go:155] 0 containers: []
W0420 21:27:15.864116    1668 logs.go:157] No container was found matching "storage-provisioner"
I0420 21:27:15.864839    1668 logs.go:73] Gathering logs for kubelet ...
I0420 21:27:15.868910    1668 ssh_runner.go:137] Run with output: journalctl -u kubelet -n 200
I0420 21:27:15.873841    1668 utils.go:240] > -- Logs begin at Sat 2019-04-20 21:24:39 UTC, end at Sun 2019-04-21 01:27:15 UTC. --
I0420 21:27:15.874840    1668 utils.go:240] > Apr 21 01:27:12 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
I0420 21:27:15.874840    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --allow-privileged has been deprecated, will be removed in a future version
I0420 21:27:15.878853    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0420 21:27:15.878853    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0420 21:27:15.879858    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0420 21:27:15.879858    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0420 21:27:15.879858    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0420 21:27:15.880839    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0420 21:27:15.880839    1668 utils.go:240] > Apr 21 01:27:12 minikube kubelet[3110]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0420 21:27:15.881838    1668 utils.go:240] > Apr 21 01:27:13 minikube kubelet[3110]: F0421 01:27:13.317753    3110 server.go:248] unable to load client CA file /var/lib/minikube/certs/ca.crt: open /var/lib/minikube/certs/ca.crt: no such file or directory
I0420 21:27:15.881838    1668 utils.go:240] > Apr 21 01:27:13 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
I0420 21:27:15.882842    1668 utils.go:240] > Apr 21 01:27:13 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
I0420 21:27:15.885838    1668 logs.go:73] Gathering logs for dmesg ...
I0420 21:27:15.887850    1668 ssh_runner.go:137] Run with output: sudo dmesg -PH -L=never --level warn,err,crit,alert,emerg | tail -n 200
I0420 21:27:15.895837    1668 utils.go:240] > [Apr21 01:24] smpboot: 128 Processors exceeds NR_CPUS limit of 64
I0420 21:27:15.895837    1668 utils.go:240] > [  +0.000000] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
I0420 21:27:15.899137    1668 utils.go:240] > [  +0.017064] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
I0420 21:27:15.899840    1668 utils.go:240] >               * this clock source is slow. Consider trying other clock sources
I0420 21:27:15.899840    1668 utils.go:240] > [ +17.838120] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
I0420 21:27:15.900840    1668 utils.go:240] > [  +0.868082] systemd-fstab-generator[1227]: Ignoring "noauto" for root device
I0420 21:27:15.900840    1668 utils.go:240] > [  +0.003017] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:35 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
I0420 21:27:15.901864    1668 utils.go:240] > [  +0.000002] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
I0420 21:27:15.901864    1668 utils.go:240] > [  +0.166610] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
I0420 21:27:15.902839    1668 utils.go:240] > [  +3.386416] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
I0420 21:27:15.904838    1668 utils.go:240] > [  +1.063630] vboxguest: loading out-of-tree module taints kernel.
I0420 21:27:15.908034    1668 utils.go:240] > [  +0.003646] vboxguest: PCI device not found, probably running on physical hardware.
I0420 21:27:15.908837    1668 utils.go:240] > [ +10.180040] systemd-fstab-generator[2372]: Ignoring "noauto" for root device
I0420 21:27:15.908837    1668 utils.go:240] > [Apr21 01:25] WARNING: CPU: 0 PID: 37 at drivers/hv/hv_balloon.c:1224 balloon_up+0x333/0x540 [hv_balloon]
I0420 21:27:15.909896    1668 utils.go:240] > [  +0.000001] Modules linked in: ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink xt_addrtype xt_conntrack br_netfilter bridge stp llc iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack overlay hv_netvsc hid_hyperv hv_utils hyperv_keyboard hv_storvsc scsi_transport_fc hv_balloon hv_vmbus
I0420 21:27:15.909896    1668 utils.go:240] > [  +0.000011] CPU: 0 PID: 37 Comm: kworker/0:1 Tainted: G           O     4.15.0 #1
I0420 21:27:15.910844    1668 utils.go:240] > [  +0.000001] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090007  06/02/2017
I0420 21:27:15.910844    1668 utils.go:240] > [  +0.000002] Workqueue: events balloon_up [hv_balloon]
I0420 21:27:15.911852    1668 utils.go:240] > [  +0.000002] RIP: 0010:balloon_up+0x333/0x540 [hv_balloon]
I0420 21:27:15.912836    1668 utils.go:240] > [  +0.000001] RSP: 0018:ffff9740c06c7e48 EFLAGS: 00010202
I0420 21:27:15.913839    1668 utils.go:240] > [  +0.000001] RAX: 0000000000009015 RBX: ffffffffc03f64a8 RCX: ffff911ff42204e0
I0420 21:27:15.919002    1668 utils.go:240] > [  +0.000001] RDX: 0000000000000001 RSI: ffff911ff42204e0 RDI: ffffffffc03f64a8
I0420 21:27:15.919002    1668 utils.go:240] > [  +0.000000] RBP: ffff911ff4224300 R08: 0000000000000203 R09: 0000000000000000
I0420 21:27:15.920024    1668 utils.go:240] > [  +0.000001] R10: 0000000000000c00 R11: 0000000000000c00 R12: 0000000000000000
I0420 21:27:15.920024    1668 utils.go:240] > [  +0.000001] R13: 0ffff911ff422430 R14: ffff911ff364a780 R15: ffff911ff42204c0
I0420 21:27:15.921002    1668 utils.go:240] > [  +0.000001] FS:  0000000000000000(0000) GS:ffff911ff4200000(0000) knlGS:0000000000000000
I0420 21:27:15.921002    1668 utils.go:240] > [  +0.000001] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
I0420 21:27:15.922002    1668 utils.go:240] > [  +0.000001] CR2: 00005556b2dff2f0 CR3: 000000007e810000 CR4: 00000000003406f0
I0420 21:27:15.922002    1668 utils.go:240] > [  +0.000002] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
I0420 21:27:15.923002    1668 utils.go:240] > [  +0.000001] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
I0420 21:27:15.923002    1668 utils.go:240] > [  +0.000000] Call Trace:
I0420 21:27:15.923002    1668 utils.go:240] > [  +0.000006]  process_one_work+0x1e9/0x3e0
I0420 21:27:15.924003    1668 utils.go:240] > [  +0.000002]  worker_thread+0x26/0x3e0
I0420 21:27:15.926354    1668 utils.go:240] > [  +0.000002]  ? process_one_work+0x3e0/0x3e0
I0420 21:27:15.929129    1668 utils.go:240] > [  +0.000001]  kthread+0x10e/0x130
I0420 21:27:15.930005    1668 utils.go:240] > [  +0.000002]  ? kthread_create_worker_on_cpu+0x40/0x40
I0420 21:27:15.931003    1668 utils.go:240] > [  +0.000002]  ? call_usermodehelper_exec_async+0x125/0x150
I0420 21:27:15.931003    1668 utils.go:240] > [  +0.000003]  ret_from_fork+0x35/0x40
I0420 21:27:15.932007    1668 utils.go:240] > [  +0.000001] Code: b6 08 10 00 00 49 8d 56 08 e9 5a fd ff ff 44 39 64 24 04 0f 84 35 ff ff ff 84 c0 0f 85 2d ff ff ff c6 44 24 08 00 e9 3e ff ff ff <0f> ff e9 e9 fc ff ff 48 c7 c7 18 52 3f c0 31 ed 48 c7 c3 90 64
I0420 21:27:15.932007    1668 utils.go:240] > [  +0.000060] ---[ end trace 8f38194bae79fbea ]---
I0420 21:27:15.933008    1668 utils.go:240] > [  +0.000002] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
I0420 21:27:15.933008    1668 utils.go:240] > [Apr21 01:26] NFSD: Unable to end grace period: -110
I0420 21:27:15.934024    1668 utils.go:240] > [Apr21 01:27] systemd-fstab-generator[3095]: Ignoring "noauto" for root device
I0420 21:27:15.934024    1668 utils.go:240] > [  +0.063125] systemd-fstab-generator[3104]: Ignoring "noauto" for root device
W0420 21:27:15.937003    1668 exit.go:99] Error starting cluster: kubeadm init:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

cannot use "fe80::215:5dff:fe00:a08" as the bind address for the API Server

: Process exited with status 1

!   Error starting cluster: kubeadm init:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

cannot use "fe80::215:5dff:fe00:a08" as the bind address for the API Server

: Process exited with status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by floreks** [comment]
This is not a minikube repository. Create an issue there.

/close
