### ISSUE TITLE
Unable to Access Dashboard

### ISSUE THREAD

**Issue by sharathmankala** [kubernetes/dashboard#3776]
Hi Team,
Today i have instaled K8s dashboard on aws ec2 instance.
After  adding token to Dashboard unable to respond .
Please suggest us.
Thanks in advance.
![Screenshot from 2019-04-29 12-33-46](https://user-images.githubusercontent.com/9713485/56880611-16598d00-6a7b-11e9-8e9c-1e153b186be4.png)

**Comment by floreks** [comment]
Logging in over `HTTP` is not possible as it is not secure. Domains other than `localhost` will not be allowed to log in. Set up secure connection or use `kubectl proxy` to access it on `localhost`.

**Comment by Nurlan199206** [comment]
how setup dashboard over https?
