### ISSUE TITLE
Make the dashboard work on IE

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#378]
Currently we have layout and JavaScript problems. This is a catch all issue to make sure the UI works on latest IE and Edge.

**Comment by taimir** [comment]
Hi, I'm currently working on fixing some layout issues in Edge, I will send a notification when I'm done.

**Comment by bryk** [comment]
Awesome! I'm really happy you're doing this :)

**Comment by floreks** [comment]
Isn't it fixed in #398? IE looks quite good now.
