### ISSUE TITLE
x509: certificate is valid for 10.61.164.153, not 10.0.0.1

### ISSUE THREAD

**Issue by timbunce** [kubernetes/dashboard#379]
Hi.

I'm running k8s 1.2.0-alpha.7 using the instructions in [getting-started-guides/docker.md](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md) - that much seems to be working fine.

I'm now trying to add the dashboard using the instructions in [docs/user-guide/ui.md](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/ui.md).
That seemed to startup fine but I wanted to access it externally, so I added `type: LoadBalancer` to dashboard-service.yaml and recreated the service (via `kubectl delete services --namespace=kube-system kubernetes-dashboard` then `kubectl create -f dashboard-service.yaml --namespace=kube-system`).

Now I can connect and I see a page with the Kubernetes header, but the only other thing on the page is a big message saying:
> Internal Server Error (500) Get https://10.0.0.1:443/api/v1/replicationcontrollers: x509: certificate is valid for 10.61.164.153, not 10.0.0.1

kubernetes/kubernetes#7828 reports a very similar error message, so I guess it might be relevant in some way, but I couldn't see how.

I'm new to k8s so please assume I know only enough to be dangerous!

**Comment by cheld** [comment]
I tried once to deploy dashboard in the docker based local cluster and failed because the service-account functionality is missing in the docker based local cluster. 

However, I had success when creating the local cluster by script. hack/local-up-cluster.sh

**Comment by bryk** [comment]
Correct, this is a problem with the docker cluster setup. It does not have service accounts enabled, which causes Dashboard to misbehave. It should have crashed loudly, though.

**Comment by timbunce** [comment]
Thanks. I'll experiment with hack/local-up-cluster.sh.

More generally, is there any reason service accounts could not be added to the local docker cluster setup? (It's a great low-friction way to people to start experimenting with Kubernetes and it would be a pity if dasdboard wasn't available in that setup.)

**Comment by bryk** [comment]
CC @fgrzadkowski 

I believe service accounts should work for the 1.2 local docker setup. Something may be wrong on HEAD, though.

**Comment by bryk** [comment]
@timbunce Does the UI work for you when you use service proxy? Like `https://<kubernetes-master>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` ?

**Comment by bryk** [comment]
@timbunce Btw, the docker install guide is broken on HEAD. https://github.com/kubernetes/kubernetes/issues/21303 We'll be able to help you when it is fixed.

**Comment by luxas** [comment]
Service accounts are working since my patch to these issues: kubernetes/kubernetes#16965 and kubernetes/kubernetes#16987
However, there were added some ([problematic](https://github.com/kubernetes/kubernetes/pull/17262/files#diff-e3f72884b2d06bdf22fc2f402297f940R34)) code too: 
```
CERT_DIR=/data /make-ca-cert.sh $(hostname -i)
```
That means the certificate won't be signed for `10.0.0.1`, just the IP of the node (if `hostname -i` works)

It should be something like this:
```
CERT_DIR=/data /make-ca-cert.sh $(hostname -I) IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local
```

I'm working on a patch for this. However, as @bryk said, @fgrzadkowski found yet another problem with `hyperkube`: kubernetes/kubernetes#21303

**Comment by timbunce** [comment]
@bryk kublet is started with `--api-servers=http://localhost:8080` and  `https://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` gives me an `curl: (35) SSL received a record that exceeded the maximum permissible length.` error. But I guess we're beyond that now. It all sounds promising.

If someone comments here when there's a new image to test I'd be happy to try it out. Thanks.

**Comment by bryk** [comment]
So, in summary, this is a problem with hyperkube? Do we have any action items on the Dashboard side?

**Comment by luxas** [comment]
Wait a little bit... @timbunce are you starting the cluster on `http://` and trying to connect on `https://`?

AFAIU that won't work in any scenario. Default `hyperkube` setup is configured for `http` traffic only and do not have `https` traffic on port `8080`. On port `6443` on the other hand, you _might_  try with `https`

**Comment by runseb** [comment]
I have the same issue in a slightly different setup.
Kubelet is running as a standard service, the other components are running in containers with hyperkube image (v1.1.4).

Service accounts and secrets work fine. I can run a rc that gets a secret mounted and I can expose a nodeport service.

But I have a certificate for TLS auth for the IP of master and not the cluster IP (10.0.0.1) used by the Kubernetes service. I get the same error as reported by @timbunce 

My manifest is at:
https://github.com/skippbox/kmachine/blob/kmachine/libmachine/provision/configure_kubernetes.go#L306

**Comment by runseb** [comment]
I fixed my issue. Added an alt_name to the API certififcate for the K8s service ip as described in https://coreos.com/kubernetes/docs/latest/openssl.html

I am now able to see the dashboard.

**Comment by luxas** [comment]
I'm fixing this on master, will probably be in for `v1.2`

**Comment by bryk** [comment]
Thanks for working on this @runseb! Can you maybe write a short user guide docs on how you set up your environment and fixed problems? This would be helpful for future users :)

**Comment by runseb** [comment]
@bryk I just posted a screencast https://www.youtube.com/watch?v=N-Z8nnvvzgA can't really write a generic short howto because I am using kmachine https://github.com/skippbox/kmachine to run the dashboard. That's where I fixed the certificate issue.

**Comment by bryk** [comment]
@runseb This looks awesome, thanks! :)

cc @cheld @maciaszczykm @floreks @f-higashi @taimir

**Comment by manojmeda** [comment]
The video https://www.youtube.com/watch?v=N-Z8nnvvzgA is not available anymore. I get the same error when I try to connect from kubectl. Can you let me know what the fix was ?

**Comment by jaytaylor** [comment]
Sadly, @sebgoa 's [coreos link has passed away](https://coreos.com/kubernetes/docs/latest/openssl.html), fortunately archive.org has it:

https://web.archive.org/web/20170104013944/https://coreos.com/kubernetes/docs/latest/openssl.html

And long-term snapshot is available here: http://archive.is/AHOTF
