### ISSUE TITLE
Event warning icon not displayed in events table

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#380]
When using `local-up-cluster` or some older version of kubernetes master event type data is empty and warning icon is not displayed together with error messages.

![zrzut ekranu z 2016-02-16 10-36-46](https://cloud.githubusercontent.com/assets/2285385/13072485/ee483660-d499-11e5-852f-dc6ce17a6e9e.png)

I'll work on that as I've already solved this issue while implementing card statuses.

**Comment by bryk** [comment]
Thanks!
