### ISSUE TITLE
 secrets "kubernetes-dashboard-certs" already exists

### ISSUE THREAD

**Issue by itkroplis** [kubernetes/dashboard#3803]
Hi!  I made secret with my godady wildcard certificate. And after dashboard install I get error  secrets "kubernetes-dashboard-certs" already exists.  How resolv it?

kubectl create secret generic kubernetes-dashboard-certs --from-file=$HOME/certs -n kube-system                                            
secret/kubernetes-dashboard-certs created

:~$ kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
serviceaccount/kubernetes-dashboard created
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal created
deployment.apps/kubernetes-dashboard created
service/kubernetes-dashboard created
Error from server (AlreadyExists): error when creating "https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yam
l": secrets "kubernetes-dashboard-certs" already exists

**Comment by floreks** [comment]
Well if you have created it then it exists. This is not an issue. We are creating only empty placeholder. Everything should work, but if you want to use custom certs you have to remove `auto-generate-certs` flag and use cert flags to provide your own that will be read from the secret.

/close

**Comment by itkroplis** [comment]
I didn't immediately realize dashboard was working. 

Maybe you know. Is it possible  install dashboard as HTTP with token auth?
All the descriptions I find do not allow me to create remote dashbord with token auth and my certificate.  I think, make HTTP dashboard + token auth and use nginx reverse proxy to apply my certificate.
