### ISSUE TITLE
Memory Graph on Workloads>Deployments not historically accurate

### ISSUE THREAD

**Issue by sebasb21** [kubernetes/dashboard#3816]
So the graph for memory seems to lose historical data when scaling down. 

If you add a pod Total memory goes up, graphs shows this. If you scale down graph starts showing current total memory, which is less, but it forgets the "bump" that occurred in the scale up.

##### Environment
```
Dashboard version: 1.10.1
```

##### Steps to reproduce

1. Open Workload>Deployments
2. Scale up a deployment
3. Wait for graph to show memory going up 
4. Scale down same deployment
5. Graph goes back to the value before scale up, but loses memory spike of the scale up

##### Observed result
Graph loses historical data

##### Expected result
Graph does not lose historical data

##### Comments

See here bump when scaling up

![Screenshot at May 16 11-23-17-11-22](https://user-images.githubusercontent.com/6624872/57846945-386a4380-77cd-11e9-8c1e-cfff26e33af7.png)

After the scale down a minute later, bump disappears (note total value on Y axis)

![Screenshot at May 16 11-26-21-11-25](https://user-images.githubusercontent.com/6624872/57847082-80896600-77cd-11e9-821c-190ddc3e6a8b.png)

**Comment by floreks** [comment]
This is not a bug. Heapster only collects metrics for a predefined time window (15 min) and graphs time window is exactly the same.

https://github.com/kubernetes-retired/heapster/blob/df26691b3b1113385e37afcf52afcfdad37cea9b/docs/model.md

/close

**Comment by sebasb21** [comment]
Sorry, can you explain further? I don't understand how your statement explains the behaviour.

**Comment by sebasb21** [comment]
The two snapshots show nearly the same time window but they show different data. So for example at 11:15 first snapshot shows ~1.86G and the second snapshot at 11:15 shows 1.12 G. So there is an inconsistency there, i think.

**Comment by floreks** [comment]
We are not doing anything with the data so it is heapster that has issues here. We are switching to metrics server so it will be fixed. The core issue lies in heapster though.

**Comment by sebasb21** [comment]
Ok
