### ISSUE TITLE
node events aren't displayed

### ISSUE THREAD

**Issue by t1mt** [kubernetes/dashboard#3826]
##### Environment
```
Installation method:
Kubernetes version: 1.11.6
Dashboard version: 1.8.6
Operating system: CentOS 7
Node.js version ('node --version' output):
Go version ('go version' output): 1.10.3
```

##### Steps to reproduce
1. stop cluster kubelet
2. start cluster kubelet
3. `kubectl describe node $YOUR_NODE_NAME`
4. request a backend node detail API 
```
GET /api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/api/v1/node/$YOUR_NODE_NAME?filterBy=&itemsPerPage=10&name=$YOUR_NODE_NAME&namespace=&page=1&sortBy=d,creationTimestamp
```
##### Observed result
responses a empty node eventList.
```
"eventList": {
    "listMeta": {
        "totalItems": 8
    },
    "events": [],
    "errors": null
},
```

##### Expected result
return same as the command line `kubectl describe node $YOUR_NODE_NAME` 'Events'

##### Comments
[https://github.com/kubernetes/dashboard/blob/2657e0b80f9957e93cb63ebd155d47311248c7a9/src/app/backend/resource/event/common.go#L136](https://github.com/kubernetes/dashboard/blob/2657e0b80f9957e93cb63ebd155d47311248c7a9/src/app/backend/resource/event/common.go#L136)

###### `kubectl describe node` implements
[https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe/versioned/describe.go#L2878L2879](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe/versioned/describe.go#L2878L2879)

**Comment by maciaszczykm** [comment]
<img width="1980" alt="Zrzut ekranu 2019-11-14 o 10 53 14" src="https://user-images.githubusercontent.com/2823399/68846208-fe6ef100-06cc-11ea-975c-3f972279bc31.png">

Closing as stale.
