### ISSUE TITLE
Config Map entries are not paginated when total count is greater than "Items per page" value

### ISSUE THREAD

**Issue by rsoto91** [kubernetes/dashboard#3835]
##### Environment
```
Kubernetes version: 1.12.6
Dashboard version: 1.10.1
Operating system: Ubuntu 16.04
Browser: Google Chrome 74.0.3729.169, Firefox 66.0.3, Safari 12.1 (14607.1.40.1.4).
```

##### Steps to reproduce
1. Have a total count of Config Maps greater than the "Items Per Page" value set in the Kubernetes Dashboard. (In this case, we have 32 config map entries and the "items per page" value set to 10. 
2. Navigate to "Config Maps" in the Kubernetes Dashboard. Entries "1-10 of 32" are displayed.
3. Click on right arrow to iterate through the remaining entries. 

##### Observed result
Only the first 10 entries are displayed, regardless of which page you're on (1-10, 11-20, 21-30, 31-32). 
![Screen Shot 2019-05-28 at 5 01 42 PM](https://user-images.githubusercontent.com/3992475/58515631-15e00f00-816b-11e9-9047-028a42ac4546.png)
![Screen Shot 2019-05-28 at 5 01 48 PM](https://user-images.githubusercontent.com/3992475/58515637-1b3d5980-816b-11e9-9ab7-bf5ab1fc96c9.png)
![Screen Shot 2019-05-28 at 5 01 58 PM](https://user-images.githubusercontent.com/3992475/58515656-27c1b200-816b-11e9-89e7-605c5581eb9f.png)

##### Expected result
Paginate through the elements and display the appropriate data. 

##### Comments
Currently working around this issue in the dashboard by setting "Items Per Page" value greater than the number of items needed to paginate through.

**Comment by maciaszczykm** [comment]
Thanks, we will take a look.

**Comment by maciaszczykm** [comment]
Fixed on master. Please wait for the new release:

<img width="1767" alt="Zrzut ekranu 2019-05-30 o 15 52 24" src="https://user-images.githubusercontent.com/2823399/58637507-ef4ce000-82f2-11e9-814e-ea33984c9e6c.png">
<img width="1766" alt="Zrzut ekranu 2019-05-30 o 15 52 16" src="https://user-images.githubusercontent.com/2823399/58637508-ef4ce000-82f2-11e9-8cf3-da7ed7487d54.png">
