### ISSUE TITLE
After uploading file with existing service it is not redirected to replicationcontroller view

### ISSUE THREAD

**Issue by batikanu** [kubernetes/dashboard#385]
I tried to upload kubernetes-dashboard.yaml under deploy directory twice. Before second time I didn't delete the service and received an error popup that service already exists. It is fine but replication controller is actually created and bound to the existing service. However it isn't redirected to replicationcontroller view after popup as if upload failed completely. Do you think that we should change/enhance this behavior? I can look for a solution if it is needed.

**Comment by bryk** [comment]
I think if at least one "thing" is created we should redirect and show errors (if any).

@floreks @cheld Opinions?

**Comment by floreks** [comment]
Initially we wanted to have something like transactions in backend and follow the idea `all or none`. I think that would be the best solution (not easiest). If something is blocking creation of any object from yaml file than nothing should be created and error message should be shown.

**Comment by bryk** [comment]
Yeah, but is it possible that we do this for 1.0? I don't think so... :(

**Comment by batikanu** [comment]
I am working on a solution (not transactions :) ) right now. I will create pull request soon.

**Comment by batikanu** [comment]
One question. If only namespace is created with the file, what would you expect? @bryk @floreks 
There is no card for namespaces.

**Comment by bryk** [comment]
@batikanu I'd say still reload the page. Everytime something is created.

**Comment by floreks** [comment]
I agree with @bryk

**Comment by floreks** [comment]
This can be closed.

**Comment by bryk** [comment]
Thanks!
