### ISSUE TITLE
Update colors in the dark theme

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3861]
Some of the colors that we are using at the moment are too dark. Also there is white border in around the graphs which is not visible in the light theme.

**Comment by gaojun5** [comment]
Hi all, I would love to work on this if this still need to be done

**Comment by floreks** [comment]
I am not sure. I think we have updated most colors? @maciaszczykm do you remember?

**Comment by maciaszczykm** [comment]
@floreks in the dark mode some of the links seem to be a bit too dark, also the colors of the graphs? This issue is for checking that once more.

**Comment by maciaszczykm** [comment]
We can work on it later (past v2). #3883 improved the colors a bit already.

Primary blue should be a bit more visible I think.

/close
