### ISSUE TITLE
Manually test the HEAD image and release the beta

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3863]

**Comment by maciaszczykm** [comment]
Hey, I think we are ready for a pre-release. What do you think?

How we will handle the metrics sidecar, should we add it to the recommended setup?

**Comment by jeefy** [comment]
At this point the scraper has 1.8k pulls and only one outstanding issue (that is more of a feature request) so I'm comfortable moving it into the recommended deployment.

I'll cut a PR now cloning it over. Besides that PR, I think we cut an RC release soon. I tested it a bunch just now and things looked solid. :)

**Comment by discostur** [comment]
just deployed the 2.0-beta1 - it looks really well! great job;)
