### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3865]

**Comment by toddbaert** [comment]
I'd like to help with this. I'll create .spec files in the same directories as the components/services under test, as in the default generated by the Angular CLI, unless anyone objects to this organization.

**Comment by floreks** [comment]
If you are willing to write actual tests it's fine. We can autogenerate all the spec files if needed. It's tests that matter. No boilerplate code.

**Comment by toddbaert** [comment]
Yep, real tests. I was just talking about their organization. I'll generate the spec files as needed.

**Comment by floreks** [comment]
That would be great. We do want to keep them in the same dirs as components/services.

**Comment by toddbaert** [comment]
https://github.com/kubernetes/dashboard/pull/4162 if you're interested.
