### ISSUE TITLE
Add graphs cluster, nodes, overview, workloads, daemon sets, cron jobs, deployments, pods, rc, rs, and stateful sets

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3866]

**Comment by maciaszczykm** [comment]
If something is missing we will track from https://github.com/kubernetes/dashboard/issues/366.

@wjywbs, are you aware of anything missing comparing to v1?

**Comment by wjywbs** [comment]
Many detail pages do not have graphs compared to v1, like individual deployment page.
