### ISSUE TITLE
can't access into dashboard

### ISSUE THREAD

**Issue by Nurlan199206** [kubernetes/dashboard#3895]
i'm deployed dashboard with command below.

and copied token but nothing happening.

`kubectl create secret generic kubernetes-dashboard-certs --from-file=$HOME/certs -n kube-system`

my folder with LE certs below

```
ls -l $HOME/certs
total 8
-rw-r--r-- 1 root root 3573 Jun 12 05:31 tls.crt
-rw-r--r-- 1 root root 1678 Jun 12 05:31 tls.key
```

```
k describe secret kubernetes-dashboard-certs -n kube-system
Name:         kubernetes-dashboard-certs
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
dashboard.crt:  3573 bytes
dashboard.key:  1678 bytes
```

`kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml`

![kube-dash](https://user-images.githubusercontent.com/22808731/59325227-0bde1480-8d04-11e9-95d0-2ad51ceb7103.gif)

**Comment by Nurlan199206** [comment]
![kube-dash1](https://user-images.githubusercontent.com/22808731/59333604-82860c80-8d1a-11e9-9bf1-1756f7b3ae44.PNG)

**Comment by floreks** [comment]
Did you expose it using `kubectl proxy`?

**Comment by Nurlan199206** [comment]
yes, my kubectl command looks like this: `kubectl proxy --address="192.168.0.105" -p 8001 --accept-hosts='^*$' &`

**Comment by Nurlan199206** [comment]
i'm added skip button... with skip button it's works...

![Снимок экрана 2019-06-12 в 22 36 16](https://user-images.githubusercontent.com/22808731/59369602-96edf780-8d62-11e9-8ee3-b76808e068b9.png)

![Снимок экрана 2019-06-12 в 22 37 16](https://user-images.githubusercontent.com/22808731/59369639-aa00c780-8d62-11e9-99dc-f475dc3e7d5f.png)

**Comment by Nurlan199206** [comment]
i'm stuck with token auth on httpS... via http token auth works also

**Comment by floreks** [comment]
As specified in our documentation accessing Dashboard over http is not secure and will not be allowed. This proxy only allows http access and should not be used to expose applications. Dashboard does this on purpose.

/close

**Comment by anubhav25gupta** [comment]
Hi Team,

I am not able to access the kubernetes-dashboard for my cluster. I am using system from cloud. So I am in confusion wether it supports Token authentication for the kubernetes services from cloud or not?

I am getting error: The requested URL could not be retrieved : everytime.

Thanks in advance!
