### ISSUE TITLE
Haproxy ingress controller giving me 503 randomly

### ISSUE THREAD

**Issue by n-rik** [kubernetes/dashboard#3896]
Hello ,

I am having the kuberenets cluster set up on AWS with cores
Kubectl version:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
I am using haproxy ingress controller, following is the deployment.yaml:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: QA-haproxy
  namespace: QA-haproxy
data:
    dynamic-scaling: "true"
    backend-server-slots-increment: "1"
    timeout-keep-alive: "10m"
    timeout-server: "10m"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: QA-haproxy
  name: QA-haproxy
  namespace: QA-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: QA-haproxy
  template:
    metadata:
      labels:
        app: QA-haproxy
    spec:
      hostNetwork: true
      serviceAccountName: ingress-controller
      containers:
      - name: haproxy-ingress-controller
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend        
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress-controller
        - --sort-backends
        - --verify-hostname=false
        - --ingress-class=ingress-$(POD_NAMESPACE)
        
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: QA-haproxy
  name: QA-haproxy
  namespace: QA-haproxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west- XXXXXXXXXXXXXXXXXX
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"

spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: stat
    port: 1936
  selector:
    app: QA-haproxy

—

How ever, when I deployed the application and write the ingress rules for that, for some hours its works fine for me.
But after some time I get the error 503 backend server is unable to handle the request, when I dig up I can see the Haproxy pod not having the IP and there are no inservice instances inside the ELB which created using above service.yaml file, when I restart this haproxy pod then thing will become normal, But I guess something has been messed up here, Not able to troubleshoot the issue also because the worker node on which this haproxy instance is present losses the it Internal IP so not able to ssh into the worker node.
Can somebody please help me on this?

**Comment by floreks** [comment]
I don't see how this is related to Dashboard.

/close
