### ISSUE TITLE
Bar Gauge Visualization 

### ISSUE THREAD

**Issue by preillyme** [kubernetes/dashboard#39]
Will we carry over the bar gauge visualization from the current dashboard?

**Comment by bryk** [comment]
Do you mean those round visualizations of CPU/memory usage of nodes?

@evasnee @kenmoore

**Comment by kenmoore** [comment]
The bar gauge visualizations have scalability issues--they're pretty bulky and couldn't fit many on a page, and aside from the "high water mark" they lack historical data. I think that mini usage graphs / sparklines would be more valuable and scale up better, so I'd like to explore that.  However we've been focused on the application layer recently and haven't designed any new stuff for infrastructure monitoring yet.

**Comment by stevesloka** [comment]
It would be nice to sort / filter / alert when things are in a bad state. I use kube-ui today to look for nodes with full disks, but I have to scan over all the graphs to find. This may be a different feature however.

**Comment by preillyme** [comment]
Yes @bryk I mean the round visualizations of CPU/memory usage of nodes a.k.a. a bar gauge.

I'm fine with exploring mini usage graphs / sparklines  as an alternative and I agree with @kenmoore.

@stevesloka we should start a new issue to track feature requests.

**Comment by cheld** [comment]
A lot of software can do monitoring. I would like to see UI that more specific to kubernetes.  e.g. kubernetes vision is to achieve a high degree of hardware utilization with smart schedulers. In this scenario, the CPU is always 100% and a classical monitoring not very helpfull to determin if your cluster is sized correctly.

**Comment by lohmander** [comment]
Would you be open to a PR on this issue that only shows a list of nodes and their current status for now?

**Comment by maciaszczykm** [comment]
@bryk @PiotrDabkowski Can we close it? It can be tracked from #962.

**Comment by bryk** [comment]
Yes, this is stale. We can close.

**Comment by preillyme** [comment]
Thanks for closing this @bryk
