### ISSUE TITLE
Redesign errors displayed on login page

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3904]
At the moment we are using simple component to display the error messages. It can be improved (see: `src/app/frontend/login/template.html:19`).

**Comment by anshulahuja98** [comment]
@maciaszczykm 
Any plans as to how to improve the errors messages?
I would be interested  in working on this

**Comment by maciaszczykm** [comment]
@anshulahuja98 Hi, first of all, we would like to improve how the errors are styled and we are open to suggestions.

**Comment by anshulahuja98** [comment]
Opinions on using a dialog box to show the error?
The dialog box will have an `ok` button to close the dialog

**Comment by maciaszczykm** [comment]
I'd avoid having a dialog here. It slows down the login. IMO just and well-styled information that doesn't need to be closed before second login attempt would work just fine.

**Comment by anshulahuja98** [comment]
How about using a [snackbar](https://material.angular.io/components/snack-bar/examples)?
Have a look at the demo I implemented
![snackbar](https://user-images.githubusercontent.com/36476228/64951569-d1a08800-d89b-11e9-9e81-4bd52737f2d4.gif)

**Comment by anshulahuja98** [comment]
If this seems a feasible approach, we can use it to improve error logging across the whole dashboard wherever relevant.

**Comment by maciaszczykm** [comment]
Looks good.

**Comment by anshulahuja98** [comment]
Great!
I'll drop a PR

**Comment by floreks** [comment]
I'd use it for errors on login view for now only and style as an error. Remember to check if it will be properly displayed after forced logout when the token expires.

**Comment by anshulahuja98** [comment]
So, there isn't a neat way to show multiple errors using this approach.
One method could've been to just concatenate all text into one snackbar, but it won't show up properly formatted.
Generating one snackbar per error would probably also not be a viable approach in this case.
