### ISSUE TITLE
Replace CommaSeparatedListComponent with join method or pipe

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3913]
Component is a bit too much for this. Use `join(', ')` method or our own pipe.

**Comment by malavindra5** [comment]
Hi I would like to work on this.

**Comment by medmedchiheb** [comment]
@maciaszczykm  i guess i have understand
would you help me, to fix this issue

**Comment by maciaszczykm** [comment]
Sure, what do you need?

**Comment by medmedchiheb** [comment]
pipe is it already added!  do you mention that `CommaSeparatedListComponent` should replaced in all places!
