### ISSUE TITLE
Error view is broken

### ISSUE THREAD

**Issue by ajatprabha** [kubernetes/dashboard#3927]
##### Environment

```
Installation method: Resository checkout
Kubernetes version: 1.14.3
Dashboard version: master(89f56f0)
Operating system: MacOS v10.14.5
Node.js version ('node --version' output): v12.1.0
Go version ('go version' output): go1.12.5 darwin/amd64
```

##### Observed result
Navigating to `/error` throws the following error:
```js
TypeError: Cannot read property 'toggle' of undefined
    at NavService.push../src/app/frontend/common/services/nav/service.ts.NavService.setVisibility (service.ts:27)
    at ErrorComponent.push../src/app/frontend/error/component.ts.ErrorComponent.ngOnInit (component.ts:33)
```

##### Expected result

Error view should work as expected.

**Comment by maciaszczykm** [comment]
Can you try again with the latest master?

**Comment by ajatprabha** [comment]
It is there on the latest master. Can you put some light on why `NavService` is required here?

**Comment by maciaszczykm** [comment]
@ajatprabha It is indeed some issue, but I think it does not exist on master. One bug was causing another. We can add checks for null here, but I think this was not normal use case.

**Comment by maciaszczykm** [comment]
Seems to be fixed now anyways.

/close
