### ISSUE TITLE
Q: possible performance issue: docker container/minikube cluster get loss on performance?

### ISSUE THREAD

**Issue by RogerWeihrauch** [kubernetes/dashboard#3932]
##### Steps to reproduce
1st) tech hints: using Docker Desktop on Mac; OS 10.14.5; 16GB RAM; MacBookPro Mid2010 13"
2nd) Install/setup as described in Docs
3rd) Stop/restart Docker Desktop W7 Kubernetes multiple times shows the effect: Performance reduction up to the point that kubernetes does no longer come up

##### Environment
```
Installation method: general installation way as described in docs
Versions:
- Docker version 18.09.2, build 6247962
- docker-compose version 1.23.2, build 1110ad01
- docker-machine version 0.16.1, build cce350d7
- minikube version: v1.1.0
Dashboard Version:
v1.10.1
Git Commit:
50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
after multiple restarts of Docker Desktop on Mac comiing up of the dashboard needs more and more time to start until it will no longer come up. Then, only a minikube delete and a new minikube start will help.

**Comment by RogerWeihrauch** [comment]
Where are my entered steps-on-reproduction and observed-result entries? Why are they missing?
I donno.

Thanks to all for your hepl/response on this.
Regards,
Roger

**Comment by floreks** [comment]
No idea how we could test/reproduce that. We would need very detailed info about symptoms, how we could try to reproduce, etc.

**Comment by maciaszczykm** [comment]
@RogerWeihrauch `<!-- -->` is used to comment things out.

**Comment by maciaszczykm** [comment]
I have edited your comment.

**Comment by maciaszczykm** [comment]
By the way, it is minikube issue, not dashboard. Please move it to minikube repo.

/close
