### ISSUE TITLE
Investigate to use `go mod` in Travis CI

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#3936]
`npm ci` seems to update `go.mod` file to use latest.
To use `go mod`, we need to investigate more.

BTW, Error about `src/app/backend/dashboard.go:158:26: undefined: prometheus.Handler` is caused due to prometheus.Handler() was removed in latest (1.0.0) prometheus/client-golang.

**Comment by eloyekunle** [comment]
In the `package.json` `postinstall`, I think we should download a specific version of `golangci-lint` (via `curl`), instead of via `go get`. Coincidentally, that's what's [recommended by the `golangci-lint` team](https://github.com/golangci/golangci-lint/#ci-installation).

**Comment by eloyekunle** [comment]
@shu-mutou Our `prometheus/client_golang` is currently fixed at `v0.9.2` ([here](https://github.com/kubernetes/dashboard/blob/f661b8a8bbe5b768279a7f2838c13230df27094f/go.mod#L20)). If `npm ci` is updating the version during the build, then #3938 should fix it.

**Comment by eloyekunle** [comment]
Fixed in #3938

**Comment by shu-mutou** [comment]
I understood we should not use `go get` to install tools.
In the future, if we would want to add the other tools written in golang,  we may meet same problem.
Can we move `export GO111MODULE=on` just before `npm ci`? If so, I think we can use `go get` before setting `GO111MODULE`.
Also, should we set `GO111MODULE` in our local environments?

**Comment by maciaszczykm** [comment]
@shu-mutou https://github.com/kubernetes/dashboard/blob/master/.travis.yml#L20 is already before `npm ci` I think.

**Comment by shu-mutou** [comment]
Oh, yes! You're right!! We can use `go get` before it. :sweat_smile:
