### ISSUE TITLE
apiserver-host paramter not propagated to deploy-from-yaml

### ISSUE THREAD

**Issue by Seb-Solon** [kubernetes/dashboard#395]
Hi there,

I'm using the dashboard and the apiserver-host option (https://github.com/kubernetes/dashboard/blob/master/src/app/backend/dashboard.go#L28). Unfortunately this looks like this option is not propagated in the whole code. 

I'm currently using the piece of code : https://github.com/kubernetes/dashboard/blob/0df77fbc03048e36f26eae74f2aaa6d75d853e9c/src/app/backend/deploy.go#L276-L296

the factory call try to connect to localhost:8080 which fail in my case. I have not manage to find a workaround in go for now. To make it work I have to have on another layer (/etc/hosts hack or proxy ...)

**Comment by bryk** [comment]
@floreks @digitalfishpond @batikanu Can you fix this? This is a blocker issue since it breaks YAML deploy on *all* non-test Dashboards.

**Comment by bryk** [comment]
Thanks @Seb-Solon for reporting this!

**Comment by Seb-Solon** [comment]
Hi,

We (me and @titilambert) kept on digging a bit and we found a workaround for now  but it requires a small fix too. 

The dashboard depends on : 
 * imdario/mergo@bc0f15622cd2a38ef83388501e4cd6747665b164 from  https://github.com/kubernetes/dashboard/blob/master/Godeps/Godeps.json#L66
 * kubernetes/kubernetes@90a7ac4aa120e22542a801e1113dcb9cc0335cb1 from  https://github.com/kubernetes/dashboard/blob/master/Godeps/Godeps.json#L158

but this version of kubernetes (and master actually) depends on : 
* imdario/mergo@6633656539c1639d9d78127b7d47c622b5d7b6dc from https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json#L694

Compiling the dashboard backend with imdario/mergo@6633656539c1639d9d78127b7d47c622b5d7b6dc make the environment variable override the default configuration.

So in our case KUBERNETES_MASTER matches the value of apiserver-host  and it works fine. 

I can make a PR to fix the dependency if you want. Would you prefer to remove the dep or to just update to the kubernetes one? I am not sure how go process deps, I would expect taht removing the dep would grab the one from kubernetes.

**Comment by bryk** [comment]
Yeah, please send a PR that updates the dependency. In the meantime we'll update the code to propagate host from the --apiserver-host param
