### ISSUE TITLE
Integration test fails for zero-state page in case there is already resources in the cluster

### ISSUE THREAD

**Issue by batikanu** [kubernetes/dashboard#396]
It doesn't happen in ci probably because the cluster is always empty. 
According to the current behavior it redirects to the replicationcontrollers page instead of zerostate if any resource is already deployed in the cluster. Therefore the css selector can't find the element. 

I think we should think about a solution to prepare an appropriate environment before the tests start and clean after finish. 

Deleting all the rcs before the test starts or controlling via namespaces might be option. 

console output:
Failures:
1) Zero state view should do something
  Message:
    Failed: No element found using locator: By.cssSelector(".kd-zerostate-deploy-bt")
  Stack:
    NoSuchElementError: No element found using locator: By.cssSelector(".kd-zerostate-deploy-bt")
        at process._tickCallback (node.js:366:9)
    Error
        at Object.<anonymous> (/home/urcan/k8s-dev/src/k8s.io/dashboard/src/test/integration/zerostate/zerostate_test.js:19:30)
    From: Task: Run it("should do something") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/urcan/k8s-dev/src/k8s.io/dashboard/src/test/integration/zerostate/zerostate_test.js:18:3)
        at Object.<anonymous> (/home/urcan/k8s-dev/src/k8s.io/dashboard/src/test/integration/zerostate/zerostate_test.js:9:1)
        at loader (/home/urcan/k8s-dev/src/k8s.io/dashboard/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
        at Object.require.extensions.(anonymous function) [as .js] (/home/urcan/k8s-dev/src/k8s.io/dashboard/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)

**Comment by bryk** [comment]
Yes, you're correct. Till now I've been ignoring zerostate page test when developing locally.

**Comment by floreks** [comment]
In our current case where zerostate is actually child of replica set state and can't be shown manually there is not much to do. For integration tests we assume that test environment is brand new and empty. 

What we could do is to start new cluster when integration tests are started with gulp in order to have clean env. for tests. This is however not part of this issue.

Can we close this? If needed issue can be opened for enhancement of gulp task.

@maciaszczykm @batikanu

**Comment by maciaszczykm** [comment]
All of tests assume, that cluster is empty. Making sure of it with new gulp task is nice idea.

**Comment by bryk** [comment]
Sounds good to close. We can create a follow up bug.

When 1.2 is out, it'll have fixed hyperkube setup. We'll be able to hook it up to all our integration test runs. Opinions?

**Comment by cheld** [comment]
I have a couple of concerns:
1. If we spin up a cluster for integration tests we can get a port clash if something is already running. 
2. we would need two gulp tasks to run tests: one for local cluster and one for real cluster
3. The zero-state tests would have to run first. Typically, not so nice to expect some order in tests
4. Tests that do not clean up probably might cause follow-up tests to fail.

So in the long run, I think it would be nice if we have some clean-up method that is executed before each test-scenario (-area).

However, implementation is a bit tricky but possible.

**Comment by bryk** [comment]
>I have a couple of concerns:
1. If we spin up a cluster for integration tests we can get a port clash if something is already running. 
2. we would need two gulp tasks to run tests: one for local cluster and one for real cluster
3. The zero-state tests would have to run first. Typically, not so nice to expect some order in tests
4. Tests that do not clean up probably might cause follow-up tests to fail.

These are valid concerns, but they mostly dont hurt as at the moment. If they start, we can be fixing them. 

>So in the long run, I think it would be nice if we have some clean-up method that is executed before each test-scenario (-area).

This is what we do already, AFIAK. 

> However, implementation is a bit tricky but possible. I am not sure how big our current pain point is. I guess it is ok to delay it to later.

I'm closing this then. Repoen if needed.
