### ISSUE TITLE
I have one question

### ISSUE THREAD

**Issue by smartkuk** [kubernetes/dashboard#3968]
***When will the integration mentioned in this [link](https://github.com/kubernetes/dashboard/wiki/Integrations) be released for the first time?***

My company prepare kubernetes cluster environment for service business platform.

I am looking for many blogs, open sources, repositories of github. So I think the best choice is your kubernetes dashboard and implement.

Thank you for reading

**Comment by maciaszczykm** [comment]
Which integration do you mean? Grafana, Weave Scope or what? 

At the moment we have added metrics server support, no other integration is on our roadmap at the moment.

**Comment by smartkuk** [comment]
> Which integration do you mean? Grafana, Weave Scope or what?
> 
> At the moment we have added metrics server support, no other integration is on our roadmap at the moment.

Thank you for answering !!!

I mean ```When will the content referred to in bold below apply```

[Currently only Heapster integration is supported, however there are plans to introduce integration framework to Dashboard. ***It will allow to support and integrate more metric providers as well as additional applications such as Weave Scope or Grafana.***](https://github.com/kubernetes/dashboard/wiki/Integrations)

**Comment by floreks** [comment]
@smartkuk https://github.com/kubernetes/dashboard/pull/3930/files

This will introduce plugin mechanism, so you can keep an eye on it,

/close

**Comment by smartkuk** [comment]
@floreks Thank you
