### ISSUE TITLE
Redirects to default namespace on resource deletion.

### ISSUE THREAD

**Issue by fentas** [kubernetes/dashboard#4001]
Deleting a e.g. Pod will redirect to `default` namespace.

##### Environment

```
Installation method: head deploy yaml
Kubernetes version: 1.14
Dashboard version: head
Operating system: Linux
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

Delete pod via dashboard.

##### Observed result

Will succeed and redirect to `default` namespace.

##### Expected result

Keep namespace which is activated.

##### Comments

Is there a way to fix a namespace via added header (like auth) or cookies?

**Comment by floreks** [comment]
This is related to https://github.com/kubernetes/dashboard/issues/3911. Once logic there gets restored, it will work the same as before.

/duplicate
/close
