### ISSUE TITLE
RC card is pending while it should be in error state

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#402]
It has pending pods that *fail* to schedule. It is pending though.
![screen shot 2016-02-19 at 12 34 17](https://cloud.githubusercontent.com/assets/1159999/13174632/5e31afb6-d705-11e5-88a7-b3330167145d.png)

@floreks opinions?

**Comment by floreks** [comment]
I believe event reason string doesn't contain failed in this case. Maybe error?

**Comment by floreks** [comment]
Could you provide me error message from events that was not recognized so I can track it?

**Comment by bryk** [comment]
![screen shot 2016-02-19 at 14 00 29](https://cloud.githubusercontent.com/assets/1159999/13176331/a3d2ef06-d711-11e5-812e-9fee180a2b4d.png)

**Comment by bryk** [comment]
```
Name:				kube-dns-v9-xb42d
Namespace:			kube-system
Image(s):			gcr.io/google_containers/etcd:2.0.9,gcr.io/google_containers/kube2sky:1.11,gcr.io/google_containers/skydns:2015-10-13-8c72f8c,gcr.io/google_containers/exechealthz:1.0
Node:				gke-guestbook-f35bcada-node-yxnp/
Start Time:			Tue, 22 Dec 2015 00:53:36 +0100
Labels:				k8s-app=kube-dns,kubernetes.io/cluster-service=true,version=v9
Status:				Failed
Reason:				CapacityExceeded
Message:			Pod cannot be started due to exceeded capacity
```

**Comment by floreks** [comment]
This is interesting. I can't really reproduce that myself and it will be hard to track exact problem without that. Events table recognized warnings correctly. I can add additional reason partials but i can't even track this `CapacityExceeded` in kubernetes code.

**Comment by floreks** [comment]
I've tracked the code that is doing this: https://github.com/kubernetes/kubernetes/pull/5501/files#diff-bf28da68f62a8df6e99e447c4351122dR1676

It is actually removed on newest k8s HEAD :) Still this partial should be recognized as error. I will add that and some other partial strings that may indicate errors. I think this is good base: https://github.com/kubernetes/kubernetes/blob/53f0f9d59860131c2be301a0054adfc86e43945d/pkg/kubelet/container/event.go

**Comment by bryk** [comment]
Ok, describe in your commit where did you get the list of partials from.

**Comment by bryk** [comment]
Corner case. Off to post 1.0
