### ISSUE TITLE
Add close buttons to all windows and move buttons to the right

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#4021]
- [ ] Move buttons to the right.
- [ ] Remove `Cancel` and `Close` buttons.
- [ ] Replace them with `X` icon button in the top right corner.

**Comment by floreks** [comment]
It's actually against rules of the material design: https://material.io/design/components/dialogs.html#actions

**Comment by maciaszczykm** [comment]
Ok, then. Let's close.
