### ISSUE TITLE
Dashboard install link is broken

### ISSUE THREAD

**Issue by openJT** [kubernetes/dashboard#4022]
Dashboard link specified in documentation is currently broken:

https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

**Comment by moming2k** [comment]
+1

**Comment by moming2k** [comment]
Seems happened once before change the url path

[Symlink old dashboard YAML to new](https://github.com/kubernetes/dashboard/issues/3448)

Is there any changes to the path again ?

**Comment by floreks** [comment]
Yes, we have completely refactored deployment files and are now using multiarch images. Our documentation will be soon updated. We will try to update external docs also. Please see release notes for up-to-date links.

**Comment by moming2k** [comment]
https://github.com/kubernetes/dashboard/commit/4fa3253c9e9efd5162597accab01aa1c716421ed

this commit removed aio/deploy/recommended/kubernetes-dashboard.yaml

**Comment by moming2k** [comment]
I think many people would use the old link. instead of delete it, would it better to at least give out some indication what is happening, this apply to other manual / blog post that already release.

**Comment by moming2k** [comment]
leaving the original link as 404 is really a bad idea, as I spend one hour questioning myself why it cannot run the script and find many other link from different page.

**Comment by moming2k** [comment]
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

this page need to update at least.

**Comment by floreks** [comment]
We already gave the notice months ago that using links which refer master directly is a bad practice. You should always use links that refer stable tagged branches instead.

**Comment by floreks** [comment]
I have already created a PR to update official docs: https://github.com/kubernetes/website/pull/15290

**Comment by moming2k** [comment]
This is a breaking changes as even the official docs does mention to use master branch, I agree that tag is a better idea, but it can be handle it more nicely. 

The better approach would be update installation instruction to the official doc, announce the graceful period, and then get the old link remove after the graceful period. Currently is the other way round with no graceful period, so all the documents broke at once.

**Comment by floreks** [comment]
Actually, official documentation is on this repo. Core k8s docs were updated by external contributors and we have not validated it.

**Comment by floreks** [comment]
Fixed by https://github.com/kubernetes/website/pull/15290

/close
