### ISSUE TITLE
Enable Angular Ivy

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/dashboard#4027]
##### What would you like to be added
[Ivy](https://angular.io/guide/ivy) is the code name for Angular's next-generation compilation and rendering pipeline. 

Guide: [Using Ivy in an existing project](https://angular.io/guide/ivy#using-ivy-in-an-existing-project)

##### Why is this needed
AOT compilation with Ivy is faster ([source](https://angular.io/guide/ivy#using-ivy-in-an-existing-project)).

##### Comments
Ivy is currently in preview, but can be used with `@angular/core@8.1.x`.

**Comment by KadenLNelson** [comment]
Have you tried building the source using `@angular/core@8.1.x`?

**Comment by eloyekunle** [comment]
Yes, but without Ivy. Works fine, using it in this PR: https://github.com/kubernetes/dashboard/pull/4002.

**Comment by KadenLNelson** [comment]
It would be cool to see the build time difference, I may try it locally.

**Comment by floreks** [comment]
We can check the difference but I'd wait with using it until it will be at least RC.
