### ISSUE TITLE
kubernetes-metrics-scraper on ARM on 2.0beta1: Unable to initialize database tables: Binary was compiled with 'CGO_ENABLED=0

### ISSUE THREAD

**Issue by Rick-Jongbloed** [kubernetes/dashboard#4029]
##### Environment

- Kubernetes Cluster with Raspberry PI 3 / 4
- ARM architecture
- Installation method: alternative deployment yaml for 2.0 beta 1 (kubectl apply -f .....)
- Kubernetes version: K3S (https://k3s.io/) 

` Server Version (outpunt from: kubectl version): version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3-k3s.1", GitCommit:"8343999292c55c807be4406fcaa9f047e8751ffd", GitTreeState:"clean", BuildDate:"2019-06-12T04:56+00:00Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/arm"} `

- Dashboard version: 2.0beta1
- Operating system: Debian Stretch 9.9
- Node.js version ('node --version' output): Node.js is not installed on the nodes
- Go version ('go version' output): go1.12.1

##### Steps to reproduce

1. apply alternative yaml file to the ARM kubernetes cluster (https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/alternative.yaml)
2. Log on to the dashboard after the dashboard is loaded.
3. The pod for kubernetes-metrics scraper is in error state.
4. The log file shows:

`2019-07-07T19:52:32.38087562+01:00  {"level":"info","msg":"Kubernetes host: https://10.43.0.1:443","time":"2019-07-07T18:52:32Z"}
2019-07-07T19:52:32.382007209+01:00  {"level":"fatal","msg":"Unable to initialize database tables: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub","time":"2019-07-07T18:52:32Z"}`

##### Observed result

See above.

##### Expected result

The kubernetes-metrics scraper is in running state.

##### Comments

I'm not really sure why the error occurs. If you need more infomation. please let me know.

**Comment by michael-robbins** [comment]
Getting this as well on my cluster of Raspberry Pi 3's 

Environment
* Kubernetes Cluster with Raspberry PI 3
* ARM architecture
* Installation method: alternative deployment yaml for 2.0 beta 1 (kubectl apply -f .....)
* Kubernetes version: k8s 1.15.0

Server Version (outpunt from: kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/arm"}
```

Dashboard version: 2.0beta1
Operating system: 
```
pi@node00:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A

**Comment by floreks** [comment]
@jeefy can we rebuild scraper for arm arch? Is it related to some dep or our build process?

**Comment by jeefy** [comment]
Huh, interesting. Our build currently does multiarch and is doing builds for `arm` and `arm64` but this might be an unforeseen failure in the sqlite library we use on arm. I've got a Pi3 at home I can play with, but it might not be till this weekend. 

/assign

Quick aside, `docker manifest inspect kubernetesdashboarddev/dashboard-metrics-sidecar` outputs all the different targets the container image will work on. :)

**Comment by MattJeanes** [comment]
Also getting this 
![image](https://user-images.githubusercontent.com/2363642/60886922-0b756280-a24b-11e9-9c6c-a07ed04f7aad.png)

Same as the others, Raspberry Pi cluster ARM32

**Comment by mmb-davidsmith** [comment]
I'm also seeing the same on an arm cluster:

`{"level":"info","msg":"Kubernetes host: https://10.96.0.1:443","time":"2019-07-09T20:30:39Z"}
{"level":"fatal","msg":"Unable to initialize database tables: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub","time":"2019-07-09T20:30:39Z"}`

I installed as per the instructions at https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/, using the recommended install

**Comment by jeefy** [comment]
Have a PR in flight to fix this. :) https://github.com/kubernetes-sigs/dashboard-metrics-scraper/pull/15

**Comment by Rick-Jongbloed** [comment]
I believe you fixed it.

`image: kubernetesdashboarddev/dashboard-metrics-sidecar`

Logging is now
`{"level":"info","msg":"Kubernetes host: https://10.43.0.1:443","time":"2019-07-16T11:20:16Z"}`

**Comment by lassebm** [comment]
@jeefy Can I ask you to fix this for `arm64` as well? Thanks!

**Comment by charles-d-burton** [comment]
This is still happening on on arm64.

**Comment by jeefy** [comment]
Reopening to track arm64 (hopefully won't stay reopened for long)

**Comment by zimme** [comment]
https://github.com/kubernetes-sigs/dashboard-metrics-scraper/releases/tag/v1.0.2

It seems as though they finally released a new version of the metric scraper with the arm64 fix :tada:
I guess we just need a new release which is using version 1.0.2 of the metric scraper to test this out.

**Comment by floreks** [comment]
This isn't ready yet. I started preparing Travis pipeline to automatically release scraper when GitHub release is created. Still, we have to fix the configuration. Once release notes will be there, it will be ready to use. You won't have to wait for us to release Dashboard. You can simply bump scraper to `v1.0.2` manually once it will be pushed to docker.

**Comment by floreks** [comment]
@zimme Scraper `v1.0.2` should be now working with ARM64. https://github.com/kubernetes-sigs/dashboard-metrics-scraper/releases/tag/v1.0.2

**Comment by zimme** [comment]
kubernetes-dashboard up and running on arm + arm 64 dev board cluster running k3os + k3s :tada:

**Comment by jonstelly** [comment]
I'm getting this error.  I just deployed beta 8 on k3s arm64 with `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml` but [recommended.yaml](https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended.yaml) still uses `kubernetesui/metrics-scraper:v1.0.1`.

I'm not sure of the process, but does the recommended.yaml need a manual update to v1.0.2?

**Comment by zimme** [comment]
@jonstelly I had to manually update `recommended.yaml` to use `1.0.2`.

**Comment by jonstelly** [comment]
Yeah, I forgot to mention I did the same and everything's working.  I just wanted to bump this to make sure it made it into the next beta.

**Comment by kamikaze** [comment]
having same issue on rpi4

**Comment by dawidslowik** [comment]
I'm also having this issue on rpi4 with ubuntu 19.10 64bit. Downgrading kubernetesui/metrics-scraper from 1.0.4 to 1.0.2 helps
