### ISSUE TITLE
Redirect after login always goes to default namespace

### ISSUE THREAD

**Issue by backbasejeff** [kubernetes/dashboard#4037]
##### Environment

```
Installation method: helm chart
Kubernetes version: 1.12
Dashboard version: tag: v1.10.1
Operating system: AWS EKS
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
In a clean browser session try to access a url for a specific namespace:
https://mydashboard/#!/overview?namespace=customns

##### Observed result
I get prompted to login and after providing a token valid for the customns namespace i get redirected to the dashboard homepage for the *default* namespace

##### Expected result
After providing the token I should be taken to the URL I originally requested (which contained the customns namespace name)

##### Comments

Not sure is related to #3911

**Comment by floreks** [comment]
This will be covered by https://github.com/kubernetes/dashboard/issues/2618

/close

**Comment by macrozone** [comment]
@floreks the linked merge request seem to have staled and does not mention this issue?

i think this should be reopened until the issue is actually fixed

**Comment by macrozone** [comment]
@backbasejeff ,  @floreks i'll reopen
