### ISSUE TITLE
A copy of your changes has been stored to "/tmp/kubectl-edit-4jyoa.yaml" error: Edit cancelled, no valid changes were saved.

### ISSUE THREAD

**Issue by Warok21** [kubernetes/dashboard#4039]
##### Environment

```
Installation method:
Kubernetes version: client : 1.14, server 1.14
Dashboard version:
Operating system:
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
When i want to edit my file to use the public IP of my server, I get the error in the tittle:
` sudo kubectl -n kubernetes-dashboard edit service kubernetes-dashboard
`
##### Observed result

> A copy of your changes has been stored to "/tmp/kubectl-edit-4jyoa.yaml" error: Edit cancelled, no valid changes were saved.

**Comment by floreks** [comment]
This error is coming from `kubectl`, so you should report it on their repo. This is only for Dashboard related issue.

/close
