### ISSUE TITLE
Shell does not work

### ISSUE THREAD

**Issue by chris-malloy-mri** [kubernetes/dashboard#4043]
##### Environment

```
Installation method: kubectl
Kubernetes version: 1.15
Dashboard version: 2.0 beta1
Operating system: Ubuntu
```

##### Steps to reproduce

Open any pod and try to exec into a shell

##### Observed result

Blank screen

##### Expected result

Should open shell

**Comment by maciaszczykm** [comment]
Does it work through `kubectl`? Can you share your pod image? It is not possible to enter all kinds of containers.

**Comment by chris-malloy-mri** [comment]
Yes it works from kubectl. This is for every single pod I tried.
