### ISSUE TITLE
Confusing measure for CPU usage

### ISSUE THREAD

**Issue by fwalker** [kubernetes/dashboard#405]
The unit for measuring the CPU usage - "mCPU" - hard to understand. Our K8s Ops as well as myself could not guess the meaning until @cheld let us know it's "milli CPU".
![mili](https://cloud.githubusercontent.com/assets/7731790/13178930/afee9fdc-d721-11e5-8ef5-773d6fc267a7.png)
Some options:

1. Enhance the tool-tip
2. Change the label to "‰ CPU"

**Comment by bryk** [comment]
@bgrant0607 How should we display CPU usage to users?

The more I think about this the more I'm in favor of changing `X mCPU` to `0.00X cores`. This is exactly what the spec says: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L2175. This means we're not introducing anything new. Also, the value `Y cores` is easier to understand than `Z mCPU`. 

Your opinions?

**Comment by cheld** [comment]
One more idea. What about:

 0.00X CPU(s). 

This is slightly incorrect. So, we explain it somehow in the tooltip. e.g.

Display:
2.5 CPUs 

Tooltip: (.... uses 2.5 CPU cores)

**Comment by bgrant0607** [comment]
I'm fine with showing CPU as a decimal. I'd make CPU singular.

We should expect double-digit numbers of cores.
