### ISSUE TITLE
Unable to access dashboard v2.0.0-beta1 with kubernetes version 1.14

### ISSUE THREAD

**Issue by parsh96** [kubernetes/dashboard#4054]

**Comment by maciaszczykm** [comment]
Closing as no description was provided.

**Comment by parsh96** [comment]
i have installed kubernetes version 1.14 using vagrant machine (centOs 7 ) and then tried to deploy the dashboard. the dashboard services were in running state but i was not able to access it .

**Comment by maciaszczykm** [comment]
Still too few details, please fill the template. Describe how you wanted to access Dashboard.

**Comment by parsh96** [comment]
##### Environment


```
Installation method: kubeadm
Kubernetes version: 1.14
Dashboard version: 2.0.0-beta1
Operating system: centos 7
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce


##### Observed result


Deployed using below command:-
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
i was able to deploy it but not able to access. when tried accessing through browser not able to find any errors so that i can resolve it.

##### Expected result


##### Comments

**Comment by maciaszczykm** [comment]
How exactly did you try to access? With proxy or how?

**Comment by maciaszczykm** [comment]
I will ask different question, can you access any other app in your cluster?

**Comment by parsh96** [comment]
i tried using proxy . and tried to change the service type to nodeport too but the same issue.

**Comment by Rick-Jongbloed** [comment]
have a look here: https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges

**Comment by parsh96** [comment]
[vagrant@kubernetes-master ~]$ kubectl get services -n kubernetes-dashboard
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
dashboard-metrics-scraper   ClusterIP   10.99.180.44    <none>        8000/TCP   16m
kubernetes-dashboard        ClusterIP   10.108.190.70   <none>        443/TCP    21m
[vagrant@kubernetes-master ~]$ kubectl get pods -n kubernetes-dashboard
NAME                                          READY   STATUS    RESTARTS   AGE
kubernetes-dashboard-6f89577b77-xg2cb         1/1     Running   0          5m5s
kubernetes-metrics-scraper-79c9985bc6-zn9qt   1/1     Running   0          5m14s

pods and services both are running still not able to access

**Comment by floreks** [comment]
Provide **detailed** steps about how you are trying to access it.

**Comment by parsh96** [comment]
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
executed the above command only

**Comment by floreks** [comment]
You still did not provide all the steps. Based on that we can not reproduce it properly. Most important piece of information is missing. URL used to access it...

**Comment by parsh96** [comment]
executed kubectl proxy on vagrant machine
from browser http://vagrant-ip:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Comment by floreks** [comment]
Dashboard is no longer in a `kube-system` namespace. Change namespace in url to `kubernetes-dashboard`

/close

**Comment by sondnpt00343** [comment]
The problem has been closed. But this post will help those who come later:
https://medium.com/@sondnpt00343/deploying-a-publicly-accessible-kubernetes-dashboard-v2-0-0-betax-8e39680d4067
