### ISSUE TITLE
Why can't I find Chinese i18n?

### ISSUE THREAD

**Issue by fuergaosi233** [kubernetes/dashboard#4059]
I can see that in the previous version someone submitted some pr about Chinese translation.
But now I can't find the translation file about Chinese in the i18n folder.Who can tell me what happened?

**Comment by maciaszczykm** [comment]
The project's frontend code was rewritten from the scratch and translation were lost too. We have Japanese and French translations thanks to contributors. Would you be willing to create Chinese translations?

**Comment by fuergaosi233** [comment]
I think i can do it. Can you tell me how to start?

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/blob/master/docs/developer/internationalization.md contains most of the info, you can also ask here.

cc @shu-mutou
