### ISSUE TITLE
Do not notify on access denied errors on the Overview page

### ISSUE THREAD

**Issue by jakerobb** [kubernetes/dashboard#4064]
##### What would you like to be added

When a user views the Overview but does not have permission to access something (e.g. Secrets), do not surface an error that must be dismissed, and do not render it in a distracting manner.

##### Why is this needed
The user did not explicitly ask for that resource; you should not interrupt them with the fact that they do not have access to it.

In 1.x, a distracting banner would appear at the top of the page every time I visited an Overview. In 2.x, now it’s a notification with a badge. It’s less distracting, which is an improvement, but now the badge number increments each time I visit an Overview, and those notifications persist through navigation to other pages. If there were any actual notifications I cared about, they’d be buried among numerous of these pointless errors instead.

Ideally, the Secrets section (for example; this applies to anything to which the user is denied access) should appear in its normal place on the Overview, listing no secrets, and including some text (not red or in any other way distracting) stating in plain language that I do not have access to secrets.

**Comment by maciaszczykm** [comment]
We have added an option to hide the notifications in the notification panel:

![Uploading Zrzut ekranu 2020-06-4 o 15.02.20.png…]()
