### ISSUE TITLE
Using dashboard Canary in Google container service 

### ISSUE THREAD

**Issue by lavvy** [kubernetes/dashboard#407]
Hello i want to use the Canary version as my dashboard in Google container service. 
I have installed it but if i visit the dashboard it still goes to the old kubeui dashboard. 
Please what commands do i use to enable it

**Comment by bryk** [comment]
Can you describe in detail what you did?

What command did you run?
How did you access kube-ui or dashboard? 
What happened?

**Comment by bryk** [comment]
Btw, Dashboard will be enabled by default on Google Container Engine when it is officially released, so you can just wait a few weeks to have it on by default.

**Comment by lavvy** [comment]
Ok,  maybe I wait.  When will dashboard be released?

**Comment by bryk** [comment]
Like in 2-3 weeks
