### ISSUE TITLE
Unable to see CPU and Memory dashboards for Kubernetes deployments in a private cluster (Although CPU/Memory dashboard data available for containers present in deployments)

### ISSUE THREAD

**Issue by varshama** [kubernetes/dashboard#4079]
##### Production GCP Environment Issue 
We have a private cluster in which there are 40+ deployments, we are unable to see CPU, memory, disk IO etc dashboard data for deployments (workloads) in GKE console.
**NOTE: The aggregated data is not available.**
Whereas, for containers in that deployments CPU. Memory dashboard data is available.
Could someone please help if there is anything we need to incorporate for private cluster in order to get data for deployments. 

Data not visible for deployments:
![image](https://user-images.githubusercontent.com/47240729/61441964-4884d780-a964-11e9-87b8-9aba490f5a1c.png)

But for containers, it is available:

![image](https://user-images.githubusercontent.com/47240729/61442052-7a963980-a964-11e9-8285-c3da22d16c88.png)

IT'S URGENT, PLEASE HELP!!

**Comment by maciaszczykm** [comment]
It's not Kubernetes Dashboard but GCP.

/close

**Comment by varshama** [comment]
@maciaszczykm Thanks for your prompt response.
I am aware that it's a GCP issue but its for Kubernetes deployments, could you please re-open the same  so that the experts can respond to my query.

**Comment by floreks** [comment]
This repository is **only** for Kubernetes Dashboard relates issues.
