### ISSUE TITLE
Internal error, no metric client found

### ISSUE THREAD

**Issue by soandos** [kubernetes/dashboard#4088]
##### Environment

```
Installation method:
Kubernetes version: 1.14.2
Dashboard version: 2.0.0-beta1
Operating system: Centos 7
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce

1. download https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
   1. Replace all instances of `namespace: kubernetes-dashboard` with `namespace: monitoring`
   1. Remove the first argument (aucogenerate certs)
   1. Change the second argument to `--namespace=monitoring`
   1. Add `--enable-insecure-login` to args
1. Change the dashboard open port to 9090
1. Change the service targetPort to 9090

##### Observed result

Logs show an inability to metrics for pods
##### Expected result

Show the metrics for pods on the dashboard
##### Comments

Logs show that "Internal error occurred: No metric client provided. Skipping metrics."

**Comment by ld-singh** [comment]
I am also facing same issue

**Comment by floreks** [comment]
Too little information. Show actual logs from the app.

**Comment by soandos** [comment]
The metrics exist (kubectl top nodes) works, and the metric-scraper seems to be working as well (printing logs saying {"level":"info","msg": "Database updated: 30 nodes, 429 pods, time: 2019-07-23T14:17:11Z"}

The cluster is on a closed network, so I can't cut an paste logs, but I am happy to retype things if you have something more specific

**Comment by ld-singh** [comment]
@floreks I am adding the logs from app in case they are helpful as I am also facing same issue
I am using EKS with weavenet. Metrics server works fine for me. I am using hostNetwork:true for metric server  and the version is v0.3.2
kubectl top works fine for me.

I am running beta2 version of dashboard.The below are the pods running:

kubectl get pods -n kubernetes-dashboard 
NAME                                         READY   STATUS    RESTARTS   AGE
dashboard-metrics-scraper-8677fbb57b-klh2f   1/1     Running   0          8s
kubernetes-dashboard-5549b56685-kch4l        1/1     Running   0          8s


The error "Internal error, no metric client found" appears when in click on pods in left side menu.
PFA the logs and manifest i used.
[k8s-dashboard_yaml.txt](https://github.com/kubernetes/dashboard/files/3424586/k8s-dashboard_yaml.txt)
[kubernetes-dashboard-pod.txt](https://github.com/kubernetes/dashboard/files/3424587/kubernetes-dashboard-pod.txt)
[dashboard-metrics-scraper-pod.txt](https://github.com/kubernetes/dashboard/files/3424589/dashboard-metrics-scraper-pod.txt)

**Comment by floreks** [comment]
**Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.**

This means that Dashboard can't connect to the metrics scraper to gather metrics. This looks like a cluster issue.

**Comment by ld-singh** [comment]
@floreks
Can you please help me understand how it is trying to connect and how can I get more information so that I can fix. I don't believe it is cluster issue. Even if it is I need to figure out a solution. My cluster is managed cluster and weavenet overlay do not run on master. But I don't understand how can a pod not connect to a service in same namespace. I am running application using multiple namespaces with pods talk to each other via services and all works just fine.

**Comment by floreks** [comment]
This error is thrown by the kubernetes itself: https://github.com/kubernetes/kubernetes/blob/b3c1bbb4710f4b178250ae1f5a61be6508501f93/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L412

It connects in here: https://github.com/kubernetes/dashboard/blob/master/src/app/backend/integration/metric/sidecar/restclient.go#L45

Basically, it looks for `dashboard-metrics-scraper` service in the same namespace as Dashboard and tries to access it. [Here](https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended.yaml#L111) there are defined privileges required to access the service and gather metrics. If everything in the cluster works, Dashboard should normally access metrics scraper pod through the service. As it is thrown by the API, then there is no way to debug it from Dashboard. You'd have to look at k8s control plane logs.

**Comment by ld-singh** [comment]
Thanks

**Comment by ld-singh** [comment]
@floreks Thanks for the code snippet. I was able to fix the issue by adding hostNetwork:true to dashboard-metrics-server Deployment.

**Comment by floreks** [comment]
I think this is the same issue for @soandos

Try the solution above.

/close

**Comment by ArvinSiChuan** [comment]
Simply I think its the v2.0beta issue with `https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml`. I used the 
v1.10.1 here and it works fine: 'https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml' (from https://github.com/kubernetes/dashboard/blob/master/README.md)

@floreks  I guess the doc in k8s.io dashbord section shouldn't introduce the beta version or it should be claimed.

**Comment by floreks** [comment]
v1 does not support metrics-server, only heapster. It's a different issue.
