### ISSUE TITLE
Viewing Config Map breaks dashboard

### ISSUE THREAD

**Issue by alastairpat** [kubernetes/dashboard#4092]
##### Environment

```
Installation method: kubectl apply
Kubernetes version: v1.13.7
Dashboard version: 2.0.0beta2
Operating system: macOS 10.14.5
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Create a configmap with data
2. View the configmap in Kubernetes dashboard
3. Click on the 'data' section of the config map
4. Wait ~5 seconds

##### Observed result

The 'data' section empties. Further interactions with Dashboard are broken, with changing tabs resulting in white boxes

##### Expected result

The 'data' section doesn't become empty and the Dashboard continues to work

##### Comments

<img width="1634" alt="Screenshot 2019-07-19 at 14 15 03" src="https://user-images.githubusercontent.com/159321/61508979-be09aa00-aa2f-11e9-82e3-b1358a942559.png">

**Comment by maciaszczykm** [comment]
Can you paste logs from the browser console?

**Comment by floreks** [comment]
Console error:
![Zrzut ekranu z 2019-07-19 10-12-40](https://user-images.githubusercontent.com/2285385/61520142-d5d03680-aa0d-11e9-8326-ab9d41b0b9c6.png)

As a quick workaround refresh the whole app. We will fix it.

**Comment by alastairpat** [comment]
Thanks @floreks - I put the whole development environment for our organisation onto the beta with a view to finding defects. Really appreciate the turnaround. An aside - all the end users are loving the improvements!

**Comment by maciaszczykm** [comment]
Interesting thing - it occurs only on prod, on dev everything works. Will be harder to fix.

**Comment by ElectricRabbit** [comment]
I think this issue could be connected with RBAC.
I have no issue with viewing configmaps accross all namespace with ClusterRole cluster-admin
But I have reported this issue from all developers with ClusterRole assigning only                                                        [get], [list], [watch] for all cluster resources

**Comment by korroot** [comment]
This bug is still valid for 2.0.0-beta3 version - after 5 seconds showing config map the UI is frozen. User cannot edit or exit the page, needs to reload the page and exit config map tab.

Any hints how to resolve this?

**Comment by floreks** [comment]
True. Now there is a different error being thrown. I'll reopen.

/reopen
/assign @maciaszczykm

**Comment by ivanfilippov** [comment]
This is still happening in beta4.

/reopen

**Comment by alastairpat** [comment]
@ivanfilippov - commit eb66d229a27e9faf747ad4b7b3b94d6710aef208 containing the fix didn't make it into beta4

**Comment by mausch** [comment]
I'm still seeing this in beta5

**Comment by autherlj** [comment]
yes, still happening in beta5

**Comment by LQBing** [comment]
I reproduced this issue in beta5, but the browser console error info is different.
![image](https://user-images.githubusercontent.com/6857508/66885290-741c6a00-f006-11e9-9d0e-2cccee8c9f4d.png)
