### ISSUE TITLE
Unable to open dashboard version v2.0.0-beta2 

### ISSUE THREAD

**Issue by parsh96** [kubernetes/dashboard#4100]
##### Environment

```
Installation method: kubeadm 
Kubernetes version: v1.15.1
Dashboard version: v2.0.0-beta2 
Operating system: centos 7
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

Deploy the dashboard :-
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta2/aio/deploy/recommended.yaml

kubectl proxy

##### Observed result

[root@localhost vagrant]# kubectl get pods --all-namespaces
NAMESPACE              NAME                                            READY   STATUS    RESTARTS   AGE
kube-system            coredns-749c59cd8d-c498f                        1/1     Running   0          7m21s
kube-system            coredns-749c59cd8d-xnzsc                        1/1     Running   0          7m21s
kube-system            etcd-localhost.localdomain                      1/1     Running   0          8m26s
kube-system            kube-apiserver-localhost.localdomain            1/1     Running   0          8m44s
kube-system            kube-controller-manager-localhost.localdomain   1/1     Running   0          8m35s
kube-system            kube-flannel-ds-amd64-746gz                     1/1     Running   0          8m30s
kube-system            kube-proxy-4tx9d                                1/1     Running   0          9m21s
kube-system            kube-scheduler-localhost.localdomain            1/1     Running   0          8m34s
kubernetes-dashboard   dashboard-metrics-scraper-6ff95d79d8-qtzwg      1/1     Running   0          6m14s
kubernetes-dashboard   kubernetes-dashboard-75dc45f799-66wfm           1/1     Running   0          6m14s

##### Expected result

should be able to access dashboard from browser

http://192.168.33.14:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

**Comment by floreks** [comment]
Observed result doesn't make sense. It does not tell us anything. Provide more useful information or close.

**Comment by parsh96** [comment]
unable to access dashboard from browser used the below url
http://192.168.33.14:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

dashboard pods are running successfully

**Comment by floreks** [comment]
You have written that you are using  `kubectl proxy` and it is exposed only on localhost. Using interface ip won't work.

/close

**Comment by parsh96** [comment]
should i expose service using nodeport

**Comment by parsh96** [comment]
[root@localhost vagrant]# kubectl get services -n kubernetes-dashboard
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
dashboard-metrics-scraper   ClusterIP   10.103.20.66    <none>        8000/TCP        6m20s
kubernetes-dashboard        NodePort    10.99.112.120   <none>        443:31559/TCP   6m20s

when exposed to nodeport got following error on browser.
Client sent an HTTP request to an HTTPS server.

can you please share any document for dashboard if present.

**Comment by floreks** [comment]
It was not updated for v2 but steps are basically the same: https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#nodeport

**Comment by parsh96** [comment]
According to the documentation older version has dashboard exposed using http but not for the newer beta release i found nothing.

**Comment by nirajbhatt7** [comment]
Works for me at
http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login

**Comment by sondnpt00343** [comment]
The problem has been closed. But this post will help those who come later:
https://medium.com/@sondnpt00343/deploying-a-publicly-accessible-kubernetes-dashboard-v2-0-0-betax-8e39680d4067

**Comment by rezabojnordi** [comment]
> Works for me at
> http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login

not for public-ip or external ip

**Comment by ytuan996** [comment]
> [root@localhost vagrant]# kubectl get services -n kubernetes-dashboard
> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> dashboard-metrics-scraper ClusterIP 10.103.20.66 8000/TCP 6m20s
> kubernetes-dashboard NodePort 10.99.112.120 443:31559/TCP 6m20s
> 
> when exposed to nodeport got following error on browser.
> Client sent an HTTP request to an HTTPS server.
> 
> can you please share any document for dashboard if present.

- Could your problem be solved, I have encountered the same problem now？

**Comment by DapengLan** [comment]
I also encountered the same problem. 

$sudo kubectl get service --all-namespaces
NAMESPACE              NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default                kubernetes                  ClusterIP   10.96.0.1        <none>        443/TCP                  39m
kube-system            kube-dns                    ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   39m
kube-system            kubernetes-dashboard        ClusterIP   10.104.134.130   <none>        80/TCP                   7m22s
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   10.96.115.226    <none>        8000/TCP                 30m
kubernetes-dashboard   kubernetes-dashboard        NodePort    10.100.236.99    <none>        443:30001/TCP            30m


$ curl 10.100.236.99:443
Client sent an HTTP request to an HTTPS server.

**Comment by nishantydv97** [comment]
> I also encountered the same problem.
> 
> $sudo kubectl get service --all-namespaces
> NAMESPACE NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> default kubernetes ClusterIP 10.96.0.1 443/TCP 39m
> kube-system kube-dns ClusterIP 10.96.0.10 53/UDP,53/TCP,9153/TCP 39m
> kube-system kubernetes-dashboard ClusterIP 10.104.134.130 80/TCP 7m22s
> kubernetes-dashboard dashboard-metrics-scraper ClusterIP 10.96.115.226 8000/TCP 30m
> kubernetes-dashboard kubernetes-dashboard NodePort 10.100.236.99 443:30001/TCP 30m
> 
> $ curl 10.100.236.99:443
> Client sent an HTTP request to an HTTPS server.



> > [root@localhost vagrant]# kubectl get services -n kubernetes-dashboard
> > NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> > dashboard-metrics-scraper ClusterIP 10.103.20.66 8000/TCP 6m20s
> > kubernetes-dashboard NodePort 10.99.112.120 443:31559/TCP 6m20s
> > when exposed to nodeport got following error on browser.
> > Client sent an HTTP request to an HTTPS server.
> > can you please share any document for dashboard if present.
> 
> * Could your problem be solved, I have encountered the same problem now？
```
Hi Mate,
I think your hitting URL is http://<NodeHost>:<NodePort>
our dashboard services are on https so we need to use the https protocol
try https://<NodeHost>:<NodePort>
it will work
```

**Comment by stanDXCisdaman** [comment]
> > I also encountered the same problem.
> > $sudo kubectl get service --all-namespaces
> > NAMESPACE NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> > default kubernetes ClusterIP 10.96.0.1 443/TCP 39m
> > kube-system kube-dns ClusterIP 10.96.0.10 53/UDP,53/TCP,9153/TCP 39m
> > kube-system kubernetes-dashboard ClusterIP 10.104.134.130 80/TCP 7m22s
> > kubernetes-dashboard dashboard-metrics-scraper ClusterIP 10.96.115.226 8000/TCP 30m
> > kubernetes-dashboard kubernetes-dashboard NodePort 10.100.236.99 443:30001/TCP 30m
> > $ curl 10.100.236.99:443
> > Client sent an HTTP request to an HTTPS server.
> 
> > > [root@localhost vagrant]# kubectl get services -n kubernetes-dashboard
> > > NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> > > dashboard-metrics-scraper ClusterIP 10.103.20.66 8000/TCP 6m20s
> > > kubernetes-dashboard NodePort 10.99.112.120 443:31559/TCP 6m20s
> > > when exposed to nodeport got following error on browser.
> > > Client sent an HTTP request to an HTTPS server.
> > > can you please share any document for dashboard if present.
> > 
> > 
> > 
> > * Could your problem be solved, I have encountered the same problem now？
> 
> ```
> Hi Mate,
> I think your hitting URL is http://<NodeHost>:<NodePort>
> our dashboard services are on https so we need to use the https protocol
> try https://<NodeHost>:<NodePort>
> it will work
> ```

Thank you all with https worked :)
