### ISSUE TITLE
Dashboard 2.0.0-beta2 has non-working exec

### ISSUE THREAD

**Issue by slavditore** [kubernetes/dashboard#4108]
##### Environment

```
Installation method: changed version of dashboard docker image to beta2 in deployment for beta1
Kubernetes version: 1.15.0
Dashboard version: 2.0.0-beta2
Operating system: Debian 9
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Choose deployment
2. Choose pod of deployment
3. Click 'Exec' into pod
##### Observed result

Black screen of terminal that hasn't any shell prompt

**Comment by floreks** [comment]
Not enough information how to reproduce, also do not just change images. With betas you should always fully reinstall the app.

**Comment by slavditore** [comment]
> Not enough information how to reproduce, also do not just change images. With betas you should always fully reinstall the app.

So, if I am unterstood you right, I should delete old resources and after this run new. Will be it right?

**Comment by floreks** [comment]
This is how you should always update beta releases. kubectl delete -f ... and then kubectl apply -f ...

**Comment by ld-singh** [comment]
@floreks I did fully re-install and still not able to exec.
Below are the logs i see:

2019/07/25 00:01:29 [2019-07-25T00:01:29Z] Incoming HTTP/1.1 GET /api/v1/pod/test-be/test-service-f7db794fc-ks85s/shell/test-service request from 10.32.0.4:45152: 
2019/07/25 00:01:29 [2019-07-25T00:01:29Z] Outcoming response to 10.32.0.4:45152 with 200 status code

**Comment by pog2g** [comment]
I did fully re-install ,but still not able to exec.

**Comment by ld-singh** [comment]
Also i noticed the below calls are going in loop with 200 http status and I keep seeing black screen with no prompt and it appears shell is loading repeatedly in loop :

v1/namespace
api/v1/pod/test-be/test-service-5bcc484787-vf7cd/container
/api/v1/pod/test-be/test-service-5bcc484787-vf7cd/shell/test-service

**Comment by floreks** [comment]
Can you share deployment that you are trying to exec into? Also we need detailed steps how you are accessing Dashboard.

**Comment by ld-singh** [comment]
@slavditore Apologies for hijacking your issue :) 
@floreks 
I am running EKS 1.12 with weavenet. I am accessing dashboard with token of service account with cluster admin access over Kubernetes Nginx ingress.
Below are the yamls:

[k8s-dashboard_yaml.txt](https://github.com/kubernetes/dashboard/files/3430534/k8s-dashboard_yaml.txt)
[deployment_yaml.txt](https://github.com/kubernetes/dashboard/files/3430536/deployment_yaml.txt)
[nginx_yaml.txt](https://github.com/kubernetes/dashboard/files/3430537/nginx_yaml.txt)

Deployment has image based on node:10.13.0

**Comment by mausch** [comment]
Exec doesn't work here either. Brand new 1.12 cluster, so it's definitely not an issue with a leftover previous beta...

**Comment by alx-kmn** [comment]
Same here. But for me i used it with NodePort and self-made certs.

**k8s**: 1.15.1 (brandnew)
**dashboard**: 2.0.0-beta2

Exeс does not work.

And than, i delete namespace, install **2.0.0-beta1** with NodePort and custom certs.
And Exec **works**!

**Comment by floreks** [comment]
so beta2 exec will work with `kubectl proxy` but beta1 not.  It's because [this](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/shell/component.ts#L191) part have changed from absolute to relative. Previously it was `/api/sockjs?${id}` and now it is `api/sockjs?${id}`. I have to recheck that.

**Comment by 0312birdzhang** [comment]
Same here.

**k8s:** 1.11.7
**dashboard:** 2.0.0-beta2
**dashboard url:** `/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#/pod?namespace=default`
