### ISSUE TITLE
Services are up to 24 chars long. Make app name at least that long.

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#411]
This is what happened when I wanted to create a service with more that 24 chars: 

```
 Details: must be a DNS 952 label (at most 24 characters, matching regex [a-z]([-a-z0-9]*[a-z0-9])?): e.g. "my-name"
```

**Comment by cheld** [comment]
@digitalfishpond 

The claim in the corresponding test is not correct!

https://github.com/kubernetes/dashboard/blob/master/src/test/frontend/deploy/deployfromsettings_controller_test.js#L433


Also, the pattern is not be correct!

https://github.com/kubernetes/dashboard/blob/master/src/test/frontend/deploy/deployfromsettings_controller_test.js#L374

Can you please verify that everything is correct?

**Comment by digitalfishpond** [comment]
I can fix this (sorry I didn't spot earlier), but the implication is that now, with our current setup (input from 'App name' is used for generating service name, label name, and RC name), the longest an app name can be is 24 chars, with the further restriction that the first character can no longer be a number. As I say, happy to fix for now, but that is one big restriction...

**Comment by digitalfishpond** [comment]
@cheld suggested that we keep the current implementation. I will have a fix shortly restricting app name field to 24 chars and only lowercase letter as first char in line with the service pattern.

**Comment by bryk** [comment]
Awesome

**Comment by cheld** [comment]
Layout is destroyed for 63 chars on firefox. 24 works
![long-name](https://cloud.githubusercontent.com/assets/7448799/13319763/4f7f63fa-dbc4-11e5-974a-78e410db145d.png)
