### ISSUE TITLE
docker run -it kubernetes-dashboard-amd64:1.10.1 /bin/bash Failed 

### ISSUE THREAD

**Issue by hll321** [kubernetes/dashboard#4115]
[root@node2 opt]# docker exec -it 8afad6272399 /bin/bash
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"

##### Environment

centos7.3
```
Installation method:
Kubernetes version:"v1.9.2"
Dashboard version:kubernetes-dashboard-amd64:1.10.1
Operating system:centos7.3
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Comments

How can I use kubernetes-dashboard-amd64:1.10.1 create a container and enter it ? please help me and thank you very much !

**Comment by floreks** [comment]
Dashboard container can not be entered as it uses scratch image as a base and has not bash inside.

/close
