### ISSUE TITLE
Improve docs for metrics

### ISSUE THREAD

**Issue by mylesagray** [kubernetes/dashboard#4121]
##### Environment

```
Installation method: Kubectl apply
Kubernetes version: 1.15.1
Dashboard version: 2.0.0-beta2
Operating system: HypriotOS (Debian) - RPi3
```

##### Steps to reproduce

Install kubernetes dashboard with:

```sh
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta2/aio/deploy/recommended.yaml
```
##### Observed result

No graphs/sparklines displayed in UI - metrics scraper pod is running as expected:

```sh
NAME                                             READY   STATUS    RESTARTS   AGE
pod/dashboard-metrics-scraper-6ff95d79d8-prfvx   1/1     Running   0          12h
pod/kubernetes-dashboard-75dc45f799-q5ztq        1/1     Running   0          12h


NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/dashboard-metrics-scraper   ClusterIP   10.106.49.54     <none>        8000/TCP   12h
service/kubernetes-dashboard        ClusterIP   10.107.222.226   <none>        443/TCP    12h


NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dashboard-metrics-scraper   1/1     1            1           12h
deployment.apps/kubernetes-dashboard        1/1     1            1           12h

NAME                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/dashboard-metrics-scraper-6ff95d79d8   1         1         1       12h
replicaset.apps/kubernetes-dashboard-75dc45f799        1         1         1       12h
```

##### Expected result

Graphs/Sparklines show in UI.

##### Comments

Not sure if this is the expected behaviour or not in 2.0.0?

**Comment by floreks** [comment]
Did you install `metrics-server`?

**Comment by mylesagray** [comment]
I assumed `metrics-server` was rolled into the scraper pod?

Does it make sense to add `metrics-server` to the recommended.yaml file?

**Comment by floreks** [comment]
`metrics-server` is only an implementation of metrics API. It is not the only thing that can be used here. That is why we are not adding it to our default setup. User has to choose here.

**Comment by mylesagray** [comment]
That did it! Thanks @floreks - perhaps one option - maybe adding another yaml file that includes its config as an example - I know I didn't have the easiest time finding the repo, the instructions or then even getting a working config. Something that works out of the box would be appreciated.

If you're open to it I can help contribute?

**Comment by floreks** [comment]
We can add information to the documentation and link to the files, but everything for `metrics-server` is already on their repo: https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy/1.8%2B

We don't really want to maintain specific setup if it's available and maintained on other repo. We can point people there. Also, there is no single setup that would work for all. Some clusters will require to set up metrics server with insecure kubelet connection and some will require secure connection. This requires adjusting the default deployment anyway.

**Comment by mylesagray** [comment]
Agree, I think some clear pointing documentation with an example on how to use it (and critically set the insecure kubelet flag - which will likely be most common) would be a great course of action.

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/issues/4008 will cover that.
