### ISSUE TITLE
CPU and Memory values not printing along graphs

### ISSUE THREAD

**Issue by ld-singh** [kubernetes/dashboard#4127]
##### Environment

```
Installation method: kubectl
Kubernetes version: 1.12.7
Dashboard version: v2.0.0-beta2
Operating system: AWS AMI
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

Click on pods on left hand menu
##### Observed result

Graphs for CPU and Memory but no values getting printed

<img width="549" alt="ActualOutcome" src="https://user-images.githubusercontent.com/43326506/61923295-c5d4cb80-afa6-11e9-83b3-c0aa1714e738.png">

##### Expected result

Values of CPU usage and Memory usage printed in front on graphs
(Taken this below screenshot from internet probably for older versions)
<img width="282" alt="Expected_Outcome" src="https://user-images.githubusercontent.com/43326506/61923586-f6693500-afa7-11e9-98ae-3d2c5f2d3b7e.png">

##### Comments

I am not sure if this is an issue or this is how version 2 is designed to work. But values printed definitely is better experience and more helpful to understand.

**Comment by floreks** [comment]
They have been moved to a tooltip to save some space.

**Comment by maciaszczykm** [comment]
We should move the unit from header or think how to add the values in the column.

**Comment by floreks** [comment]
They would need to be on top/bottom of the sparklines. We don't have that much space to show them in the same line.

**Comment by ld-singh** [comment]
Thanks for considering this feature. Both have to co-exist irrespective of the placement. You can only understand the trend in the graph if you see some value otherwise they all look the same. With tooltip you have to memorise the value which is kind of bit troublesome.
