### ISSUE TITLE
CPU and Memory sparklines appear next to incorret pods (and change position on refresh)

### ISSUE THREAD

**Issue by qikiqi** [kubernetes/dashboard#4129]
##### Environment

```
Installation method: kubectl apply
Kubernetes version: v1.14.4
Dashboard version: v2.0.0-beta1 and v2.0.0-beta2
Operating system: Ubuntu 18.04.2
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Setup kubernetes via [k3s](https://github.com/rancher/k3s/) (have not tried to reproduce via other installation methods)
2. Install dashboard
3. Install metrics-server
4. Open the dashboard, change the namespace to kubernetes-dashboard and open pods view
5. Refresh page and observe sparklines for memory and/or cpu to change positions
6. Incorrect values can be verified via `kubectl top pods --namespace kubernetes-dashboard` which shows correct values next to the corresponding pods

In the gif below the namespace is default and there are five pods deployed, this is where I observed the phenomenon the first time. It can be also reproduced within the kubernetes-dashboard namespace and with dashboards pods as stated above.

##### Observed result

Dashboards sparklines won't stay next to the corresponding pods.

![k3s_dashboard_bug_final3](https://user-images.githubusercontent.com/11520039/61932967-58687100-af8d-11e9-9dea-830c7aba2943.gif)

##### Expected result

Expected to see the sparklines to stay next to the corresponding pods

##### Comments

Observed behaviour experienced with Firefox Developer Edition 69.0b4 as well as with Chromium version 75.0.3770.100

EDIT: Tested on v2.0.0-beta2, same behaviour as in gif experienced there (although it seems that the sparklines correct their positioning after the first dynamic(?) refresh, without a page reload)

**Comment by floreks** [comment]
Looks like a backend issue. I don't see a way how frontend could be wrong here. We have to take a look at this.
