### ISSUE TITLE
MiniKube crash while installing Knative

### ISSUE THREAD

**Issue by m7albasha** [kubernetes/dashboard#4132]
##### Steps to reproduce

followed the steps in "https://github.com/knative/docs/blob/master/docs/install/Knative-with-Minikube.md"
1- installed minikube and Kubectl
2- ran the hello world
3- attempted to install Knative
4- Minikube crashed while installing
I have a system with a 12 core cpu and 16G ram + 500G HDD

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Bad Gateway (502):
```
No error data available
```

**Comment by floreks** [comment]
Not related to Dashboard

/close
