### ISSUE TITLE
Missed Internationalization texts

### ISSUE THREAD

**Issue by smartkuk** [kubernetes/dashboard#4147]
Hi~

I am working Internationalization to convert Korean.

And I found missed Internationalization source.

[This part] seems to fall into internationalization processing.

[This part]: https://github.com/kubernetes/dashboard/blob/6d184730c68d52b74c402f6c2324c4219c5a146e/src/app/frontend/resource/cluster/namespace/detail/actionbar/template.html#L22

**Comment by maciaszczykm** [comment]
More of an enhacement than a bug. It would be a bug if the translations were incorrect.

Are you willing to create some PRs?

**Comment by smartkuk** [comment]
I just wanted to let you know.

Can I make a PR?

I think I can fix it by referring to other sources...

**Comment by floreks** [comment]
I think there are many more places where we did not use i18n tag/attribute :slightly_smiling_face: . If you are willing to create PR fixing that, it would be great.

**Comment by smartkuk** [comment]
> I think there are many more places where we did not use i18n tag/attribute 🙂 . If you are willing to create PR fixing that, it would be great.

OK~

If I find the no use i18n sources, I often create PR for fixing~
