### ISSUE TITLE
[Parent Issue]: Add e2e Tests

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/dashboard#4153]
##### What would you like to be added
With the addition of the [Cypress](https://cypress.io) test framework in #4002, we can add e2e tests for some of the features that we currently have.

##### Why is this needed
To improve the quality and stability of the project.

**Comment by smohtadi** [comment]
Hi, is this issue still open? I would like to work on this.

**Comment by eloyekunle** [comment]
@smohtadi Yes it is still open. We want to have e2e tests for more components of the dashboard, so this is a parent issue to track this feature.
