### ISSUE TITLE
Image v2.0.0-beta3 doesn't exists in registry

### ISSUE THREAD

**Issue by vaivanov** [kubernetes/dashboard#4154]
Hello,

can you please push image with tag v2.0.0-beta3 to your [docker registry](https://hub.docker.com/r/kubernetesui/dashboard/tags)?

I can not install the latest version of dashboard because image with beta3 tag doesn't exists.

**Comment by filip-havlicek** [comment]
my testing ended with the same problem
```
Failed to pull image "kubernetesui/dashboard:v2.0.0-beta3": rpc error: code = Unknown desc = Error response from daemon: manifest for kubernetesui/dashboard:v2.0.0-beta3 not found
```

**Comment by lazedo** [comment]
now its there. you need to wait for the image to get published.
you can monitor [travis ](https://travis-ci.org/kubernetes/dashboard/builds)
