### ISSUE TITLE
Unable to access dashboard v2.0.0-beta1 with kubernetes version 1.15.0

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes/dashboard#4160]
1、proxy
kubectl proxy --address='192.168.0.205' --port=8001
Access http://192.168.0.205:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/ , Response Forbidden.

2、NodePort
https://192.168.0.205:31695/ 
![image](https://user-images.githubusercontent.com/15009201/62415121-4d7da280-b657-11e9-8eae-640258d84e1b.png)
![image](https://user-images.githubusercontent.com/15009201/62415115-39d23c00-b657-11e9-9ee0-91454b48d864.png)

**Comment by floreks** [comment]
This is a cluster config issue. Also do not expose proxy on any ip, because login will not work.
