### ISSUE TITLE
Shell exec doesn't work – sockjs 404

### ISSUE THREAD

**Issue by shankie-san** [kubernetes/dashboard#4166]
##### Environment
```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
Kubernetes version: v1.14.4 (Digital Ocean managed)
Dashboard version: 2.0.0-beta1
Operating system: Mac 10.14.5
```

##### Steps to reproduce
1. Install Dashboard
2. Configure user
3. Try to exec shell in running pod

##### Observed result
Blank shell screen. Sockjs error in browser console: `http://localhost:8001/api/sockjs/info?662cf4bab8bded4c617109a286faa884&t=1565007692486 404 (Not Found)` 
<img width="1457" alt="Screenshot 2019-08-05 at 13 38 08" src="https://user-images.githubusercontent.com/2608862/62465225-4c975e80-b786-11e9-9055-800101d6f5fc.png">

##### Expected result
Expected shell to work as it does using `kubectl` (which it does)

Thanks 😄

**Comment by floreks** [comment]
Latest beta is `v2.0.0-beta3` where this is fixed.

/close

**Comment by shankie-san** [comment]
Wonderful thanks @floreks . That must have been the fastest reply ever.

It might be worth updating the docs [here](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) as plenty of users will be installing beta1 😃

**Comment by romil-punetha** [comment]
Same issue with v2.0.0-beta8
