### ISSUE TITLE
Dashboard not staring up getting error

### ISSUE THREAD

**Issue by anupash147** [kubernetes/dashboard#4168]
After bringing up the eks 1.13 , the official documentation on dashboard does not support 1.13 but somehow eks is still supporting 1.10 dashboard version but am still seeing the issue..

12 issues of which one 1 is updated

configmaps is forbidden: User "system:serviceaccount:kube-system:ttl-controller" cannot list configmaps in the namespace "default" is showing up inside the Dashboard GUI, if we use kubectl proxy for access.

**Comment by floreks** [comment]
To be honest I don't understand anything from this description. Provide more information and describe it better.

**Comment by gharsallahmoez** [comment]
![Screen Shot 2019-08-06 at 14 55 07 1](https://user-images.githubusercontent.com/37015044/62545937-833ea900-b85a-11e9-80d6-e7f7ba047e18.png)
i got this error

**Comment by anupash147** [comment]
@floreks & @gharsallahmoez thanks for taking the initiative: My dashboard did come up after i load balanced it but on start up the first thing that showed up was the blocks of 12 errors

ex. of one of them
--------------------------------------------------------------------------------------------
configmaps is forbidden: User "system:serviceaccount:kube-system:ttl-controller" cannot list configmaps in the namespace "default" is showing up inside the Dashboard GUI, if we use kubectl proxy for access.
--------------------------------------------------------------------------------------------

I had my eks killed and trying out eks 1.12 and if i can i will attach a screen shot..

**Comment by floreks** [comment]
I have no idea how your Dashboard setup looks. Clearly, you do not have privileges to see resources in the cluster.

**Comment by anupash147** [comment]
![image](https://user-images.githubusercontent.com/8271182/62559948-0277b100-b84a-11e9-8dd3-f3b8b611f1b8.png)

This is the snap of the issue

**Comment by anupash147** [comment]
the version for this dashboard is 1.10 and applied to eks 1.13 ref https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html

**Comment by jeefy** [comment]
It looks like you're logging into the Dashboard with the `kube-system/ttl-controller` service account. That's probably not what you want, and you're running into an RBAC issue. The Dashboard itself seems to be behaving correctly.

**Comment by anupash147** [comment]
I think i solved it..  after i added https://github.com/kubernetes/dashboard/wiki/Creating-sample-user.. started working seems like i was using ttl token to access dash board
