### ISSUE TITLE
Clicking create then cancel didn't cancel as expected

### ISSUE THREAD

**Issue by kmarf** [kubernetes/dashboard#4184]
##### Steps to reproduce

I clicked create then clicked cancel but could not undo the create option 
Perhaps if I browsed away to another create page by accident 

##### Environment
```
Installation method: minikube
Kubernetes version:
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Unknown Server Error:
```
No error data available
```

**Comment by floreks** [comment]
Cancel does not cancel pending operation. Once create request is sent to the server there is no way to cancel it. K8S will always finish the creation of resources asynchronously. Cancel will not work as rollback. It means cancel my current form changes and get back.

/close
