### ISSUE TITLE
Dark Mode Palette Lacks Sufficent Contrast (Can be hard to read)

### ISSUE THREAD

**Issue by ncouse** [kubernetes/dashboard#4188]
##### Environment

Basic Microk8s installation.

Installation method: 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta3/aio/deploy/recommended.yaml
```

```
Kubernetes version: 1.15.0 
Dashboard version: 2.0.0-beta3
Operating system: Ubuntu 18.04
Node.js version ('node --version' output): v8.10.0
Go version ('go version' output):  1.12.7
```

##### Steps to reproduce

Installed beta3 of Dashboard.

Turned on Dark Mode.

##### Observed result

The colours palette made the screens hard to read. In particular the blue links are very hard to read against the dark background.

##### Expected result

Readable screens, with sufficient contrast.

##### Comments

The colour palette works great on standard mode.
The dark mode was very hard to read, and was almost vibrating for me.
![K8S_Dashboard](https://user-images.githubusercontent.com/20225047/62794572-57c2f500-bacc-11e9-8525-852aa4e68397.png)

Depending on your monitor, and the individual's eye sight, this may or may not be readable. The colour palette needs sufficient contrast.
I was looking forward to a dark mode on the dashboard, but cannot current use it in its current state.

**Comment by floreks** [comment]
No useful information provided.

/close

**Comment by ncouse** [comment]
@floreks: Description was accidentally submitted as blank. Description updated.

**Comment by therc** [comment]
I went to https://app.contrast-finder.org/?lang=en

I entered the values for the worst offenders, A elements. If I got it right, they're #326DE6 against the main view's #424242 background. That's a contrast ratio of 2.14, which is way lower than the recommended 4.5. Chrome's developer tools compute the same ratio, if you use CTRL-Shift-C to point at the hyperlinks. It even shows a warning sign.

Playing a bit, I found that e.g. using #52B5FF for the foreground gives you a ratio of 4.5.

The same #326DE6 against the darker #212121 looks better, but it still has a ratio of 3.42. I don't understand how this whole palette business in `_dark.scss` works, but hopefully the above is useful.

**Comment by floreks** [comment]
We can work further with provided information. Thanks @therc

**Comment by therc** [comment]
@floreks would it be enough if I did a global find/replace in `_dark.scss`? There are four occurrences of #326dE6 in `_dark.scss`...

**Comment by maciaszczykm** [comment]
Replace it and check how it works. You can attach some screenshots, so we will be able to see the difference.

**Comment by floreks** [comment]
Don't change the `326dE6` color. It's Kubernetes base blue. I'd rather change background color.

**Comment by ncouse** [comment]
I know you like to maintain the standard product colours, but consider for dark mode that this doesn't always work.

A mistake I see often in dark mode is that designers try to hard to stick to "brand" colours.

**Comment by floreks** [comment]
Primary color: `#3276F5`
Background color: `#121212`
Contrast ratio:  `4.50099`

![image](https://user-images.githubusercontent.com/2285385/67967406-d6c85500-fc05-11e9-8e8a-6eddabd04b31.png)

**Comment by therc** [comment]
@floreks a few screenshots from the latest PR changes. I used your values, but also dimmed the top toolbar.

![Screenshot from 2019-11-01 08-57-38](https://user-images.githubusercontent.com/13481082/68026457-2f3f3700-fc86-11e9-9c13-659c92b157a6.png)
![Screenshot from 2019-11-01 08-58-03](https://user-images.githubusercontent.com/13481082/68026459-31a19100-fc86-11e9-8861-69987cf106f4.png)
![Screenshot from 2019-11-01 08-58-39](https://user-images.githubusercontent.com/13481082/68026464-3403eb00-fc86-11e9-84c4-77d72b8a9c2b.png)

For some reason, GH scales all three images.

**Comment by therc** [comment]
The graphs have a lot of hardcoded colors, e.g. in `src/app/frontend/common/components/workloadstatus/component.ts` or `src/app/frontend/common/components/graph/component.ts`

**Comment by floreks** [comment]
I guess we should prepare new color palette for the background around this "black'ish" color.
