### ISSUE TITLE
Dashboard forbidden error

### ISSUE THREAD

**Issue by patrickl13** [kubernetes/dashboard#4196]
Hi, I was just wondering if anyone has run into this issue and could give some guidance. I finally got my dashboard set up but it is displaying this error as seen in the image below:
![issue](https://user-images.githubusercontent.com/33182833/63046143-db4f5e00-be9f-11e9-80c7-6dc2fac57e79.png)

Let me know if you can provide any insight,
Thanks

**Comment by qq1778551951** [comment]
i also have this error

**Comment by maciaszczykm** [comment]
The service account that you are using has no access to given resources. This is enforced by Kubernetes. 

/close
