### ISSUE TITLE
Validate container image name on deploy page

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#422]
Once https://github.com/kubernetes/dashboard/pull/403 gets merged we should validate containter image name. It should be easy since @f-higashi researched how the image should look like. 

@f-higashi Can you take this?

**Comment by f-higashi** [comment]
Yes. 
I can take this.

**Comment by f-higashi** [comment]
Docker has a difference format for reference between versions.
For example, v1.7 does not allow 'host:port/ns1/xxx/image:v1. 
V1.10 allow it.

I think our validation allow newer version.
Is it OK?

cf.)
1.7
https://github.com/docker/docker/blob/v1.7.1/registry/config.go#L35-L36
In L213, reference is split in only two. So if reference has three `/`,  repo has `/` and it does not matched validRepo.

1.10
https://github.com/docker/docker/blob/v1.10.2/reference/reference.go
https://github.com/docker/distribution/blob/docker/1.10/reference/reference.go#L6-L21

**Comment by bryk** [comment]
I think we should allow the less restrictive values. We don't know which version of Docker users have.

**Comment by f-higashi** [comment]
I think so.
Newer docker version allows the less restrictive values.
I'll use this.

**Comment by codegoblins** [comment]
reposting from slack for visibility: I’d like to see more integrations with container registries, e.g. being able to search public images from within the deploy from settings flow. I worked on a similar feature for an internal kubernetes UI and would be happy to contribute.

**Comment by bryk** [comment]
@codegoblins Yeah, sure. We wanted to do this at some point, but didn't have time to. Please report a feature request first, though. And let's discuss it there.
