### ISSUE TITLE
Enable Google Container Registry API

### ISSUE THREAD

**Issue by hawsers** [kubernetes/dashboard#4226]
##### What would you like to be added
Enable Google Container Registry API

##### Why is this needed
Error will be prompt when I try to list the image tag list:
{"errors":[{"code":"DENIED","message":"Please enable or contact project owners to enable the Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=kubernetesui before performing this operation."}]}

##### Comments
Nope.

**Comment by maciaszczykm** [comment]
This seems to be wrong repo for this issue. Contact GCP support.
