### ISSUE TITLE
Inconsistent behavior on logs page for different k8s master versions

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#423]
#### Issue details
I'm using `local-up-cluster` with newest kubernetes HEAD. After deploying some card with wrong `containerImage` pod stays in pending state with errors. Logs page show `Internal error(500)`. On older cluster we can see normal log entry saying that pod is not started and is in state pending.

##### Environment

```
Dashboard version: HEAD
Kubernetes version: v.1.2.0-alpha-8 (Newest HEAD)
```

##### Steps to reproduce

1. Deploy app with not existing `containerImage`.
2. Wait for card to show error status.
3. Go to logs page.
4. Check same page on older kubernetes version.

##### Observed result

Inconsistent behavior for logs page between different kubernetes versions.

##### Comments

It's hard to say what is the expected behavior here. Pod is actually in pending state so the older version is correct to show this entry but there are some errors related to this pod and newer version actually displays internal error with event error message. For me newest behavior seems more convenient.

Here are some screens.

Newest k8s:
![zrzut ekranu z 2016-02-25 09-57-39](https://cloud.githubusercontent.com/assets/2285385/13314834/7ff616d6-dba7-11e5-9b4f-cc6167afbee4.png)

Older k8s:
![zrzut ekranu z 2016-02-25 10-01-48](https://cloud.githubusercontent.com/assets/2285385/13314837/85100186-dba7-11e5-9512-a3941fe09e29.png)

What do you think? @bryk @maciaszczykm @cheld

**Comment by bryk** [comment]
To me there should be no `500` error. Backend should handle this case and either say that there are no logs or display message that is currently displayed.

**Comment by floreks** [comment]
I'll take a look at that.

**Comment by floreks** [comment]
Changing this https://github.com/kubernetes/dashboard/blob/master/src/app/backend/logs.go#L50
to `return err.Error(), nil` solves this issue and logs page is shown normally:

![zrzut ekranu z 2016-03-10 14-46-13](https://cloud.githubusercontent.com/assets/2285385/13671199/cc550bb8-e6ce-11e5-81be-4e25086e6c41.png)
 
Messages of course will differ between version so we shouldn't check for that. I'll have to adjust test also. Is this solution ok? I was also thinking about other solution but that would require complete redesign of logs backend :)

**Comment by floreks** [comment]
@bryk what do you think?

**Comment by bryk** [comment]
Sounds good to me. Ship it :)
