### ISSUE TITLE
HTTP 500 error thrown for unauthorized users

### ISSUE THREAD

**Issue by miff2000** [kubernetes/dashboard#4234]
##### Environment

Using Kubernetes, NGiNX Ingress with custom error pages, set up to respond to HTTP error codes

```
Installation method: Helm v3.0.0-beta.2
Kubernetes version: v1.15.1
Dashboard version: v1.10.1
Operating system: CentOS 7
Node.js version ('node --version' output): N/A
Go version ('go version' output): v1.12.5
```

##### Steps to reproduce

1. Install NGiNX Ingress via Helm and configure Custom Error Pages with it

```yaml
controller:
  config:
    custom-http-errors: 400,403,404,413,500,502,503,504

  kind: DaemonSet

defaultBackend:
  enabled: true
  name: default-backend
  image:
    repository: registry.internal/docker-images/nginx-ingress-custom-error
    tag: stable
    pullPolicy: IfNotPresent
  port: 8080

podSecurityPolicy:
  enabled: true
```

2. Test NGiNX Ingress works by visiting a URL which points to the NGiNX Ingress controllers, but which doesn't match an ingress. You should see a custom 404 error returned from the `default-backend` pod
3. Install Kubernetes Dashboard via Helm

```yaml
image:
  repository: k8s.gcr.io/kubernetes-dashboard-amd64
  tag: v1.10.1

replicaCount: 2

labels:
  kubernetes.io/name: kubernetes-dashboard
  
extraArgs:
  - --authentication-mode=basic
  - --authentication-mode=token

service:
  externalPort: 6443
  labels:
    kubernetes.io/name: kubernetes-dashboard

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/secure-backends: "true"
  hosts: dashboard.ingress.domain.name
```

4. Login using whatever method is supported. In my case it's basic auth
5. Wait for the token timeout period to expire

##### Observed result

Refresh and check your browser dev tools for response codes. I see some notable responses:
- <https://dashboard.ingress.domain.name> returns a `200`
- <https://dashboard.ingress.domain.name/api/v1/rbac/status> returns a `500`
- <https://dashboard.ingress.domain.name/api/v1/settings/global> returns a `500`
- <https://dashboard.ingress.domain.name/api/v1/login/status> returns a `200`
- <https://dashboard.ingress.domain.name/api/v1/csrftoken/token> returns a `200`
- <https://dashboard.ingress.domain.name/api/v1/token/refresh> returns a `401`
- <https://dashboard.ingress.domain.name/api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp> returns a `500`

##### Expected result

To be redirected to the login page again like normal. 

##### Comments

The custom error backend is configured to intercept HTTP errors 400, 403, 404, 413, 500, 502, 503 and 504. If there was only 401s being thrown from the dashboard then I suspect this would not occur. I'm not sure why 500s are being generated currently.

I see this in the Kubernetes Dashboard logs:
```none
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Incoming HTTP/1.1 GET /api/v1/login/status request from 10.233.82.126:44388: {}
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Outcoming response to 10.233.82.126:44388 with 200 status code
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/token request from 10.233.112.127:39140: {}
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Outcoming response to 10.233.112.127:39140 with 200 status code
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Incoming HTTP/1.1 POST /api/v1/token/refresh request from 10.233.76.100:44446: { contents hidden }
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Outcoming response to 10.233.76.100:44446 with 401 status code
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Incoming HTTP/1.1 GET /api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 10.233.116.150:53034: {}
2019/08/29 07:17:16 MSG_TOKEN_EXPIRED_ERROR
2019/08/29 07:17:16 [2019-08-29T07:17:16Z] Outcoming response to 10.233.116.150:53034 with 500 status code
2019/08/29 07:17:23 [2019-08-29T07:17:23Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/login request from 10.233.82.126:44388: { contents hidden }
2019/08/29 07:17:23 [2019-08-29T07:17:23Z] Outcoming response to 10.233.82.126:44388 with 200 status code
2019/08/29 07:17:23 [2019-08-29T07:17:23Z] Incoming HTTP/1.1 POST /api/v1/login request from 10.233.112.127:39140: { contents hidden }
2019/08/29 07:17:23 [2019-08-29T07:17:23Z] Outcoming response to 10.233.112.127:39140 with 200 status code
```

**Comment by miff2000** [comment]
I can also confirm, removing 500 error handling by changing the config map to this works:
```yaml
  custom-http-errors: 400,403,404,413,502,503,504
```

The issue is however that I can then not handle error 500s from other backends that are not the K8s Dashboard

**Comment by floreks** [comment]
Did you try latest v2.0.0-beta4 release? `v1.10.1` is quite old.

**Comment by miff2000** [comment]
> Did you try latest `v2.0.0-beta4` release? `v1.10.1` is quite old.

I've just given this a go, but now I get issues with RBAC:
```none
2019/08/29 09:44:33 Starting overwatch
2019/08/29 09:44:33 Using namespace: kube-system
2019/08/29 09:44:33 Using in-cluster config to connect to apiserver
2019/08/29 09:44:33 Using secret token for csrf signing
2019/08/29 09:44:33 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0005387e0)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x3b4
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc0004a2980)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:479 +0xc7
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc0004a2980)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:447 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:528
main.main()
        /home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x212
```

**Comment by floreks** [comment]
Ye, it has been moved to a new namespace. Some of the privileges have been removed to make it more secure. If you want to adjust helm chart you'd have to rely on our new deployment scripts and remove old version first: https://github.com/kubernetes/dashboard/tree/master/aio/deploy

**Comment by miff2000** [comment]
I've deployed using the recommended.yaml in that directory you've linked me to.  If I port-forward to the service IP directly on 443 I get a working dashboard. However, if I add an ingress I get presented back a 400. Any ideas what's going there there?

In NGiNX Ingress I see:
```none
192.168.1.4 - [192.168.1.4] - - [29/Aug/2019:10:52:45 +0000] "GET / HTTP/1.1" 400 20868 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36" 1725 0.006 [upstream-default-backend] [] 10.233.116.148:8443 : 10.233.116.187:8080 0 : 20831 0.000 : 0.005 400 : 400 da110ad4a110882cdefcfcb3cc7247f8
```

On the kubernetes-dashboard pod I don't see the request in the logs.

In the meantime I will wait for my token to expire again and see if the 500s go away. I'll report back

**Comment by miff2000** [comment]
> I've deployed using the recommended.yaml in that directory you've linked me to.  If I port-forward to the service IP directly on 443 I get a working dashboard. However, if I add an ingress I get presented back a 400. Any ideas what's going there there?

This was because the ingress didn't have required annotations for an SSL backend:
```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/secure-backends: "true"
```

**Comment by miff2000** [comment]
After allowing the token to expire and opening back up the browser tab, I get presented a HTTP 401 message banner and the login prompt. The issue I reported has gone away in the `v2.0.0-beta4` release, so thanks @floreks!

**Comment by floreks** [comment]
Glad to hear. Can we close then?

**Comment by miff2000** [comment]
Yep, absolutely 👍
