### ISSUE TITLE
dashboard 启动初始化错误

### ISSUE THREAD

**Issue by gitnapn** [kubernetes/dashboard#4242]
[root@localhost ~]#  kubectl describe pod  kubernetes-dashboard-65f89d475c-w84tf -n kube-system
Name:           kubernetes-dashboard-65f89d475c-w84tf
Namespace:      kube-system
Node:           10.10.10.14/10.10.10.14
Start Time:     Fri, 30 Aug 2019 10:14:09 +0800
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=65f89d475c
Annotations:    scheduler.alpha.kubernetes.io/critical-pod:
Status:         Running
IP:             172.17.82.3
Controlled By:  ReplicaSet/kubernetes-dashboard-65f89d475c
Containers:
  kubernetes-dashboard:
    Container ID:   docker://6c70964f0e6aeea16539193fc67a0e296f84d77f0c03ae79849881e8adef3b81
    Image:          registry.cn-shenzhen.aliyuncs.com/wengjx-vm/kubernetes-dashboard-amd64:v1.10.0
    Image ID:       docker://sha256:0dab2435c100b32892e676b9709978617a5472390ac951f764c292950b902b1f
    Port:           9090/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 30 Aug 2019 11:09:48 +0800
      Finished:     Fri, 30 Aug 2019 11:09:48 +0800
    Ready:          False
    Restart Count:  20
    Limits:
      cpu:     100m
      memory:  300Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Liveness:     http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-dc694 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kubernetes-dashboard-token-dc694:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-dc694
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
Events:
  Type     Reason     Age                    From                  Message
  ----     ------     ----                   ----                  -------
  Normal   Scheduled  59m                    default-scheduler     Successfully assigned kube-system/kubernetes-dashboard-65f89d475c-w84tf to 10.10.10.14
  Normal   Pulled     57m (x5 over 59m)      kubelet, 10.10.10.14  Container image "registry.cn-shenzhen.aliyuncs.com/wengjx-vm/kubernetes-dashboard-amd64:v1.10.0" already present on machine
  Normal   Created    57m (x5 over 59m)      kubelet, 10.10.10.14  Created container kubernetes-dashboard
  Normal   Started    57m (x5 over 59m)      kubelet, 10.10.10.14  Started container kubernetes-dashboard
  Warning  BackOff    39m (x103 over 59m)    kubelet, 10.10.10.14  Back-off restarting failed container
  Normal   Pulled     33m (x4 over 34m)      kubelet, 10.10.10.14  Container image "registry.cn-shenzhen.aliyuncs.com/wengjx-vm/kubernetes-dashboard-amd64:v1.10.0" already present on machine
  Normal   Created    33m (x4 over 34m)      kubelet, 10.10.10.14  Created container kubernetes-dashboard
  Normal   Started    33m (x4 over 34m)      kubelet, 10.10.10.14  Started container kubernetes-dashboard
  Warning  BackOff    4m23s (x149 over 34m)  kubelet, 10.10.10.14  Back-off restarting failed container
[root@localhost ~]#

[root@localhost ~]#  kubectl logs kubernetes-dashboard-65f89d475c-w84tf -n kube-system
2019/08/30 02:49:23 Starting overwatch
2019/08/30 02:49:23 Using in-cluster config to connect to apiserver
2019/08/30 02:49:23 Using service account token for csrf signing
2019/08/30 02:49:23 No request provided. Skipping authorization
2019/08/30 02:49:23 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service account's configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.128.10.1:443/version: x509: certificate is valid for 127.0.0.1, 10.10.10.12, 10.10.10.13, 10.10.10.14, not 10.128.10.1
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

k8s
master:10.10.10.12  node:10.10.10.{12,13}
master配置pod地址
--service-cluster-ip-range=10.128.10.0/24 

报错的是在10.128.10.1上无效认证的问题；求解

**Comment by floreks** [comment]
I don't see an issue here. It's an issue with your configuration.

/close
