### ISSUE TITLE
build.sh not working. 

### ISSUE THREAD

**Issue by meghasharma1234** [kubernetes/dashboard#4245]
##### Environment

```
Installation method: kubeadm
Kubernetes version: kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:11:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Dashboard version: v2.0.0-beta4
Operating system: ubuntu 16.04
Node.js version ('node --version' output):v4.2.6

Go version ('go version' output): not installed
```

##### Steps to reproduce

after cloning into home directory
>
cd dashboard/aio/scripts
>
./build.sh
>

##### Observed result

> kubernetes-dashboard@2.0.0-beta4 postversion /home/megha/dashboard
> node aio/scripts/version.js

/home/megha/dashboard/aio/scripts/version.js:1
(function (exports, require, module, __filename, __dirname) { const {gitDescribeSync} = require('git-describe');
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.15.0-55-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "postversion"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! kubernetes-dashboard@2.0.0-beta4 postversion: `node aio/scripts/version.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-dashboard@2.0.0-beta4 postversion script 'node aio/scripts/version.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kubernetes-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node aio/scripts/version.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kubernetes-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kubernetes-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/megha/dashboard/aio/scripts/npm-debug.log

##### Comments

npm-debug log-file

 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'postversion' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'postversion' ]
5 info lifecycle kubernetes-dashboard@2.0.0-beta4~postversion: kubernetes-dashboard@2.0.0-beta4
6 verbose lifecycle kubernetes-dashboard@2.0.0-beta4~postversion: unsafe-perm in lifecycle true
7 verbose lifecycle kubernetes-dashboard@2.0.0-beta4~postversion: PATH: /usr/share/npm/bin/node-gyp-bin:/home/megha/dashboard/node_modules/.bin:/home/megha/bin:/home/megha/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
8 verbose lifecycle kubernetes-dashboard@2.0.0-beta4~postversion: CWD: /home/megha/dashboard
9 silly lifecycle kubernetes-dashboard@2.0.0-beta4~postversion: Args: [ '-c', 'node aio/scripts/version.js' ]
10 silly lifecycle kubernetes-dashboard@2.0.0-beta4~postversion: Returned: code: 1  signal: null
11 info lifecycle kubernetes-dashboard@2.0.0-beta4~postversion: Failed to exec postversion script
12 verbose stack Error: kubernetes-dashboard@2.0.0-beta4 postversion: `node aio/scripts/version.js`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:821:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid kubernetes-dashboard@2.0.0-beta4
14 verbose cwd /home/megha/dashboard/aio/scripts
15 error Linux 4.15.0-55-generic
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "postversion"
17 error node v4.2.6
18 error npm  v3.5.2
19 error code ELIFECYCLE
20 error kubernetes-dashboard@2.0.0-beta4 postversion: `node aio/scripts/version.js`
20 error Exit status 1
21 error Failed at the kubernetes-dashboard@2.0.0-beta4 postversion script 'node aio/scripts/version.js'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the kubernetes-dashboard package,
21 error not with npm itself.

**Comment by floreks** [comment]
Those scripts should not be ran manually. Everything should be executed through prepare npm scripts. Also, minimal node version defined in `package.json` is `node >= 10.9.0` + `npm >= 6.0.0`

/close
