### ISSUE TITLE
v1.10.1: TTL Flag not working

### ISSUE THREAD

**Issue by berkil** [kubernetes/dashboard#4247]
##### Environment
Installation method: `kubectl apply -f dashboard.yaml`
Kubernetes version: 1.13
Dashboard version: 1.10.1
Operating system: whatever image your are using to build
Node.js version ('node --version' output): whatever nodejs you are using to build the image
Go version ('go version' output): whatever go version you are using to build the image

##### Steps to reproduce
Deployed the dashboard using the flags:  
```
args:
          - --tls-key-file=dashboard.key
          - --tls-cert-file=dashboard.crt
          - --token-ttl=43200
```

##### Observed result
The dashboard logged out after 15 minutes.

##### Expected result
The dashboard should stay logged in for 12 hours.

##### Comments
I have found similar issue here, that suggested manually changing the values, tried this voodoo method and ended with same logout period of 15 minutes .

**Comment by floreks** [comment]
`v1.10.1` is outdated and will not be updated. There are `v2.0.0` beta builds you should try.

/close
