### ISSUE TITLE
UI Enhancement: Add Restart Deployment Feature

### ISSUE THREAD

**Issue by ryanelian** [kubernetes/dashboard#4254]
##### What would you like to be added

![image](https://user-images.githubusercontent.com/8892187/64242065-15f06780-cf2f-11e9-9713-89516bfbe287.png)

An additional button labeled Restart should be added to the Deployment item dropdown menu.

##### Why is this needed

Kubernetes does not restart deployments when Secrets / ConfigMap are updated (CMIIW).  This feature is essential for quick restart after updating app secrets via the dashboard.

##### Comments

Related PRs:
https://github.com/kubernetes/kubernetes/pull/76062
https://github.com/kubernetes/kubernetes/issues/13488#issuecomment-481023838

**Comment by zehuaiWANG** [comment]
Do you mean to do a feature just like excuting `kubectl rolling-update deployment xxx`

**Comment by ryanelian** [comment]
Yes but the command is:

```
kubectl rollout restart deployment/$deployment
```

**Comment by rsjohn** [comment]
I have been using this for 3hrs now and the first thing I noticed was the lack of pod restarts.  It is needed

**Comment by galtonova** [comment]
Yes, it would help a lot. Exactly as rsjohn said, first thing when I started using dashboard was the lack of rolling update command for deployments. Especially for my deployments that use :latest tagged images.

**Comment by floreks** [comment]
It is quite an interesting feature. We will have to take a look at kubectl implementation and add that.
