### ISSUE TITLE
Card status overflows on IE

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#426]
Screenshot from an integration test: https://saucelabs.com/beta/tests/43ce4e134b6e425189ca8f7c14f410bd/commands

![ie-status overflow](https://cloud.githubusercontent.com/assets/1159999/13316874/532b6e48-dbb2-11e5-9fb9-71abde8f7454.png)

**Comment by floreks** [comment]
I think `word-wrap` doesn't work correctly on IE. Using `word-break` should do the trick

**Comment by bryk** [comment]
If you know the fix and it is easy, then please do it :)
