### ISSUE TITLE
Viewing Config Maps breaks dashboard

### ISSUE THREAD

**Issue by ivanfilippov** [kubernetes/dashboard#4263]
##### Environment
```
Installation method: RKE
Kubernetes version: 1.15.3
Dashboard version: v2.0.0-beta4+0.gf232c589
Operating system: RancherOS 1.5.4
```

##### Steps to reproduce
1. Open Dashboard
2. Navigate to a namespace with a Config Maps
3. Click the Config Map name
4. Wait a few seconds

##### Observed result
The Config Map contents are displayed for a few seconds in the Data pane then disappear. The Dashboard becomes unusable afterwards (clicking on other resources does not open them up and new 'blank' panes are inserted at the top of the current view).

##### Expected result
The Config Map Data pane stays populated and the Dashboard keeps functioning.

##### Comments
Chrome dev tools shows an error in the console when this issue happens. The log and a screenshot from dev tools is attached below.

[chrome.log](https://github.com/kubernetes/dashboard/files/3583690/chrome.log)

![image](https://user-images.githubusercontent.com/325998/64424867-784c8380-d067-11e9-952b-af94d999f9cf.png)

 This is a duplicate of #4092 which is closed and I'm not able to re-open issues in this project.

**Comment by maciaszczykm** [comment]
The fix is not yet part of any release: https://github.com/kubernetes/dashboard/compare/v2.0.0-beta4...master

Please reopen if it will persist after the next release.
