### ISSUE TITLE
Documentation for creating user, login is broken on windows

### ISSUE THREAD

**Issue by SidShetye** [kubernetes/dashboard#4264]
#### What should be cleaned up or changed

The documentation at https://github.com/kubernetes/dashboard/wiki/Creating-sample-user lacks coverage for windows/powershell.

You need to update that document to provide this command

`kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | select-string admin-user | % { ($_ -split "\s+")[0]})`

to get the token on windows dev machines.

**Comment by tombh** [comment]
That page doesn't even exist any more. I'm so lost at sea now :(

**Comment by maciaszczykm** [comment]
@tombh https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
