### ISSUE TITLE
Time ago filter issue

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#427]
##### Environment

```
Dashboard version: latest
Kubernetes version: v1.2.0-alpha.8.186+ac644e03bd6acb
Operating system: Ubuntu 14.04.1
Node.js version: v5.5.0
Go version: go1.5.1 linux/amd64
```

##### Steps to reproduce

1. Setup Kubernetes cluster and Dashboard on server with valiad time.
2. On second machine change time, for example by 1 hour ahead.
3. On second machine access Dashboard, create new pod and check time ago filter output on page.

##### Observed result

Difference between current local client machine time and server time (when pod was created) is displayed.

##### Expected result

Difference between server times is displayed.

##### Comments

Server time should be used in all cases. Otherwise we can spot situations like `didn't happen yet` on running pods.

**Comment by bryk** [comment]
Post 1.0 I think. Do you agree?

**Comment by maciaszczykm** [comment]
@bryk Yes, it won't be that easy to fix it.

**Comment by maciaszczykm** [comment]
A way to solve it is to create server endpoint returning its current time and use this time in relative time filter. However, simplest solution have obvious cons, it would check server time every time when filter would be executed. I'll try to find a way to do it once per page refresh, so we can limit requests to server,
