### ISSUE TITLE
When viewing Config Map data, the Config Map data is missing and all the functions on the page can not be operated.

### ISSUE THREAD

**Issue by HE-999** [kubernetes/dashboard#4294]
##### Environment

```
Installation method: kubectl
Kubernetes version: v1.15.3
Dashboard version: v2.0.0-beta4
Operating system: centos 7.6
Node.js version ('node --version' output): n/a
Go version ('go version' output): n/a
```

##### Steps to reproduce

Select one of the Config Map to view, wait a few seconds before the data disappears, and all the functions on the page can not be operated, you must refresh the browser to continue to operate.
##### Observed result

All the functions on the page can not be operated.

![微信图片_20190917112137](https://user-images.githubusercontent.com/55421926/65008880-5f807f80-d93d-11e9-8c9c-73f63b438f4d.jpg)
![微信图片_20190917112147](https://user-images.githubusercontent.com/55421926/65008882-5f807f80-d93d-11e9-99aa-154fbf50a89e.jpg)

##### Expected result

The Config Map data normal display without affecting other functions.

**Comment by maciaszczykm** [comment]
This should be fixed in the new release that is yet to happen. Please reopen if the problem will persist on your side after an update.
