### ISSUE TITLE
Container environment variables on pod pages are always flickering and the location of environment variables is changing

### ISSUE THREAD

**Issue by HE-999** [kubernetes/dashboard#4296]
##### Environment

```
Installation method: kubectl
Kubernetes version: v1.15.3
Dashboard version: v2.0.0-beta4
Operating system: centos 7.6
Node.js version ('node --version' output): n/a
Go version ('go version' output): n/a
```

##### Steps to reproduce

Choose Workloads->Pods->a pod, then drag the scroll bar to the bottom to see the container environment variables，you can see that the container environment variables are always flickering and the position is adjusting.

![微信图片_20190917162230](https://user-images.githubusercontent.com/55421926/65024826-290c2a00-d968-11e9-95ba-3b4de17e9a7b.jpg)

##### Observed result

The container environment variables are always flickering and the position is adjusting.

##### Expected result

Container environment variables remain static.

##### Comments

It is suggested that the layout of environmental variables should be adjusted. At present, such scattered display is not good-looking, which is worse than the previous version of v.1.10.1.

**Comment by floreks** [comment]
What does "flickering" mean here?

**Comment by HE-999** [comment]
> What does "flickering" mean here?

The container environment variable area is constantly refreshing and the page is shaking.

**Comment by HE-999** [comment]
Most importantly, the location of variables changes after each refresh. It's hard to keep looking.

**Comment by floreks** [comment]
If I understand correctly it means that the order of variables changes after refresh? We can sort them so it will be constant.

**Comment by HE-999** [comment]
> If I understand correctly it means that the order of variables changes after refresh? We can sort them so it will be constant.

yes

**Comment by floreks** [comment]
@HE-999 they do not flicker on their own. Did you click on them to reveal the value and then they flickered?
