### ISSUE TITLE
not able to get dasboard

### ISSUE THREAD

**Issue by jayapalreddy18** [kubernetes/dashboard#4297]
[root@eu-kubernetes-master ~]# kubectl -n kube-system get svc -o wide
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE     SELECTOR
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   3h26m   k8s-app=kube-dns

[root@eu-kubernetes-master ~]#  kubectl get pods --all-namespaces -o wide
NAMESPACE              NAME                                                           READY   STATUS    RESTARTS   AGE     IP            NODE                                   NOMINATED NODE   READINESS GATES
kube-system            coredns-5c98db65d4-c4tkr                                       1/1     Running   0          3h26m   10.32.0.2     eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            coredns-5c98db65d4-dn56w                                       1/1     Running   0          3h26m   10.32.0.3     eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            etcd-eu-kubernetes-master.prod.hclpnp.com                      1/1     Running   0          3h25m   10.14.82.21   eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            kube-apiserver-eu-kubernetes-master.prod.hclpnp.com            1/1     Running   0          3h26m   10.14.82.21   eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            kube-controller-manager-eu-kubernetes-master.prod.hclpnp.com   1/1     Running   2          3h26m   10.14.82.21   eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            kube-proxy-2dl5x                                               1/1     Running   0          178m    10.14.82.24   eu-kubernetes-node3.prod.hclpnp.com    <none>           <none>
kube-system            kube-proxy-g79hv                                               1/1     Running   0          3h10m   10.14.82.23   eu-kubernetes-node2.prod.hclpnp.com    <none>           <none>
kube-system            kube-proxy-jf97p                                               1/1     Running   0          3h26m   10.14.82.21   eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            kube-proxy-xhd5z                                               1/1     Running   0          3h19m   10.14.82.22   eu-kubernetes-node1.prod.hclpnp.com    <none>           <none>
kube-system            kube-scheduler-eu-kubernetes-master.prod.hclpnp.com            1/1     Running   2          3h25m   10.14.82.21   eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            weave-net-jfd59                                                2/2     Running   0          3h10m   10.14.82.23   eu-kubernetes-node2.prod.hclpnp.com    <none>           <none>
kube-system            weave-net-kl2cv                                                2/2     Running   0          3h25m   10.14.82.21   eu-kubernetes-master.prod.hclpnp.com   <none>           <none>
kube-system            weave-net-stbqn                                                2/2     Running   1          3h19m   10.14.82.22   eu-kubernetes-node1.prod.hclpnp.com    <none>           <none>
kube-system            weave-net-zl2nm                                                2/2     Running   0          178m    10.14.82.24   eu-kubernetes-node3.prod.hclpnp.com    <none>           <none>
kubernetes-dashboard   dashboard-metrics-scraper-6c554969c6-wltv2                     1/1     Running   0          39m     10.42.0.1     eu-kubernetes-node3.prod.hclpnp.com    <none>           <none>
kubernetes-dashboard   kubernetes-dashboard-6789669dd6-h47s6                          1/1     Running   0          39m     10.44.0.1     eu-kubernetes-node1.prod.hclpnp.com    <none>           <none>
kubernetes-dashboard   kubernetes-metrics-scraper-86456cdd8f-rwc94                    1/1     Running   0          87m     10.44.0.2     eu-kubernetes-node1.prod.hclpnp.com    <none>           <none>
[root@eu-kubernetes-master ~]#

**Comment by maciaszczykm** [comment]
It makes no sense, you can reopen after filling the template.

**Comment by jayapalreddy18** [comment]
please provide template
