### ISSUE TITLE
not able to access dashboard

### ISSUE THREAD

**Issue by jayapalreddy18** [kubernetes/dashboard#4299]
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"http:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "http:kubernetes-dashboard:",
    "kind": "services"
  },
  "code": 403
}

**Comment by jayapalreddy18** [comment]
please provide us the template

**Comment by floreks** [comment]
One more issue and we will have to block you from the organization. Stop.

/close
