### ISSUE TITLE
Deploy View - Deploy from file doesn't work on IE

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#430]
##### Environment

```
Dashboard version: HEAD
Kubernetes version: HEAD
Operating system: Windows 7 x64
Browser: IE 11.0.9600.18161
```

##### Steps to reproduce

1. Go to deploy page.
2. Select `Upload a YAML or JSON file` option
3. Open file browser
4. Select file

##### Observed result

After selecting file for deploy it is not shown in the UI and deploy does not work.

##### Comments

![deploy-from-file-bug](https://cloud.githubusercontent.com/assets/2285385/13319375/8acacc18-dbc1-11e5-9670-cd28c1d09df2.gif)

**Comment by floreks** [comment]
P1

**Comment by bryk** [comment]
Ouch, that hurts. Can you take this? My IE setup is horrible for any kind of development... :(

**Comment by floreks** [comment]
Sure. I'll work on that after #433
