### ISSUE TITLE
View ConfigMaps  Data will disappear after several secondes

### ISSUE THREAD

**Issue by autherlj** [kubernetes/dashboard#4311]
##### Environment

```
Installation method: 
Kubernetes version: 1.15.0
Dashboard version:  2.0.0.bate4
Operating system: Centos7.3
Node.js version ('node --version' output):
Go version ('go version' output): go1.12.5
```

##### Steps to reproduce

Click Config Maps and view any config Data will disappear after several secondes

##### Observed result

kubectl apply -f recommended.yaml
Dashboard page chaos if you not refresh the page.
![image](https://user-images.githubusercontent.com/30717333/65295303-79b39b00-db93-11e9-8af3-8c283c549a2d.png)

##### Expected result

page display normal
##### Comments

A user experience suggestion:  CPU MEM Usage display can direct show numbers, not need to put mouse.

**Comment by maciaszczykm** [comment]
Fix will be part of the new release.

**Comment by mausch** [comment]
I'm still seeing this in v2.0.0-beta5
