### ISSUE TITLE
'alternative' setup using http seems to ignore Authorization: Bearer <token>

### ISSUE THREAD

**Issue by llamahunter** [kubernetes/dashboard#4312]
##### Environment
Using the alternative deployment method to deploy an http based dashboard behind a reverse proxy that provides auth header bearer tokes

```
Installation method: alternate
Kubernetes version: 1.14.6
Dashboard version: v2.0.0-beta4
Operating system: amazon-linux
Node.js version ('node --version' output): ?
Go version ('go version' output): ?
```

##### Steps to reproduce
Deploy 'alternative' config behind an authenticating reverse-proxy.  Test using Requestly to inject headers.

##### Observed result
If deployed via 'recommended' yaml files, runs as https server and Requestly is able to provide bearer token to 'log in' to the dashboard.  If deployed via 'alternative' yaml files, runs as http server but Requestly bearer token headers are ignored.

##### Expected result
Bearer token authentication headers are honored whether run as http or https server via 'alternative' or 'recommended' yaml files.

##### Comments
It seems as though some part of the code path is ignoring auth headers if in http mode. But in http mode, auth headers are the *only* way to escalate permissions over the paltry ones the kubernetes-dashboard serviceaccount is granted.  This seem not to be working according to the stated design.

**Comment by floreks** [comment]
Yes, alternative setup is missing `enable-insecure-login` flag.

**Comment by llamahunter** [comment]
But, I don't want the 'login' dialog at all.  I just want it to honor the bearer token, per the docs.

**Comment by floreks** [comment]
Bearer token overrides the login dialog. It is disabled if the token is passed.

**Comment by llamahunter** [comment]
So, the bearer token is ignored if --enable-insecure-login is no passed?  The docs do _not_ make this clear

>Alternative setup
This setup is not fully secure. Certificates are not used and Dashboard is exposed only over HTTP. In this setup access control can be ensured only by using Authorization Header feature.

> Using authorization header is the only way to make Dashboard act as an user, when accessing it over HTTP. 

> To make Dashboard use authorization header you simply need to pass Authorization: Bearer <token> in every request to Dashboard. 

No where in there does it mention that you need to modify the 'alternative' deployment to add the --enable-insecure-login flag in order to make it work correctly.

**Comment by floreks** [comment]
You shouldn't have to modify it. We have to update it on our side. Documentation is not up-to-date and it refers to latest stable release v1.10, not the v2 beta.

We have had to change how it works after we've been informed about security issue that allowed to escalate some privileges in certain cases. Basically the 'login' functionality enables user to use header or login view, but header will always have a higher priority.
