### ISSUE TITLE
Beta4 version slows down after 1 hour

### ISSUE THREAD

**Issue by birladeanuadrian** [kubernetes/dashboard#4314]
After running a page for 1 hour, firefox reports that a scripts is slowing down the website and recommends killing it (the website does take a few seconds to respond to actions). After refresh, website is working well once again.

##### Environment
Firefox 69.0.1
```
Installation method: Using the recommended version for beta4
Kubernetes version: 1.15.3
Dashboard version: v2.0.0-beta4
Operating system: ubuntu 18.04
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
Open an overview page and stay there for about 1 hour

##### Observed result
website slows down considerably

##### Expected result
website works normally

**Comment by floreks** [comment]
Related to #4261. We have temporarily disabled workload statuses (https://github.com/kubernetes/dashboard/pull/4262) until a proper fix is prepared, but new beta hasn't been released yet.

/close
