### ISSUE TITLE
imagepullbackoff on dashboard:v2.0.0-beta4

### ISSUE THREAD

**Issue by wayfireme** [kubernetes/dashboard#4315]
Hello, world.
Trying to install the dashboard in Kubernetes with command:

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml`

The reply looks like this:

`Failed to pull image "kubernetesui/dashboard:v2.0.0-beta4": rpc error: code = Unknown desc = error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/68/6802d83967b995c2c2499645ede60aa234727afc06079e635285f54c82acbceb/data?verify=1568998309-bQcnrEV6vQpN4irzUtO2FEIv%2FkE%3D: dial tcp: lookup production.cloudflare.docker.com on 192.168.73.1:53: read udp 192.168.73.91:35778->192.168.73.1:53: i/o timeout`

And a simple ping command said:

`ping: unknown host https://production.cloudflare.docker.com`

After that I watched the domain from downforeveryoneorjustme service and it told me that the server is down.

`It's not just you! production.cloudflare.docker.com is down.`

Googling the problem showed that I need to configure the docker proxy, but I have no proxy in my setup..
[https://docs.docker.com/network/proxy/#configure-the-docker-client](url)

Any thoughts? Thank you in advance.

**Comment by floreks** [comment]
This is a configuration issue and not related directly to Dashboard. We do not provide support for such things. Try asking on stackoverflow.

/close
