### ISSUE TITLE
Modify the pod/common.go code to make it more concise and high performance

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4317]
##### What should be cleaned up or changed
I think the code in github.com/kubernetes/dashboard/src/app/backend/resource/pod/common.go：
```
	ready := false
	initialized := false
	for _, c := range pod.Status.Conditions {
		if c.Type == v1.PodReady {
			ready = c.Status == v1.ConditionTrue
		}
		if c.Type == v1.PodInitialized {
			initialized = c.Status == v1.ConditionTrue
		}
	}
	if initialized && ready && pod.Status.Phase == v1.PodRunning {
		return v1.PodRunning
	}
```
is modified as
```
	ready := true
	for _, c := range pod.Status.Conditions {
	  if c.Type == v1.PodReady || c.Type == v1.PodInitialized {
               if c.Status == v1.ConditionFalse  {
                    ready = false
                    break
               }
         }
      }
      if ready && pod.Status.Phase == v1.PodRunning {
	  return v1.PodRunning
      }
```
will be better， which will be more concise and high performance.
 I volunteer to fix it！
##### Provide any links for context
[commond.go](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/pod/common.go)

**Comment by floreks** [comment]
Performance-wise it would be basically identical but the code readability would be worse. Such conditions are always optimized by the compiler already at compile-time. No need to change it.

/close

**Comment by zehuaiWANG** [comment]
@floreks hi~floreks，I don't think it will be optimized by the compiler at compile-time beause the compiler will not know when the loop will break by the condition(c.Status == v1.ConditionFalse), I add a "break" in the code.  And I think the code readability is basically identical.

**Comment by floreks** [comment]
Readability is not the same as code cyclomatic complexity increases due to nested 'if' condition. It's better to split them if possible because it always increases readability. Code complexity on the other hand stays the same and is still O(n).

**Comment by zehuaiWANG** [comment]
@floreks I agree that the worst complexity is O(n)， but the best complexity of my writing is  O(1) and the best complexity of the original way of writing is O(n). I can also write high code readability like this.
```
	ready := true
	for _, c := range pod.Status.Conditions {
	  if c.Type == v1.PodReady  {
               if c.Status == v1.ConditionFalse  {
                    ready = false
                    break
               }
         }
         if c.Type == v1.PodInitialized  {
               if c.Status == v1.ConditionFalse  {
                    ready = false
                    break
               }
      }
      if ready && pod.Status.Phase == v1.PodRunning {
	  return v1.PodRunning
      }
```

**Comment by floreks** [comment]
You don't really consider best complexity at algorithm design. Always average is taken as default which is still O(n). As I've said nesting if's increases cyclomatic complexity of the code and we do not want that. I'd rather stay with the original.

**Comment by zehuaiWANG** [comment]
@floreks I agree that in software design, we always consider the average complexity rather than the best complexity. But in this case, the order in the pod.Status.Conditions array is always in the order of PodInitialized, PodReady and so on because this is a pod started order, so there is a big probability that the "average complexity" is O (1).  And getPodStatusPhase is a very common operation, I think we still have to consider this aspect of performance, even if there is only a small difference.

**Comment by floreks** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions

According to the docs, pod condition options are a limited set already. In any case, the array will be always very short. I don't see a reason to try an optimize that if we know it will always have very little elements.

**Comment by zehuaiWANG** [comment]
@floreks Okay, I agree with your point of view not to modify it, although I think modifying it will improve a little performance. Thank you for your reply and discussion.

**Comment by zehuaiWANG** [comment]
@floreks I also mentioned an issue #4318 about the wrong commen. Could you also have a look? Thank you every much.

**Comment by floreks** [comment]
> Okay, I agree with your point of view not to modify it, although I think modifying it will improve a little performance. Thank you for your reply and discussion.

In general, I do approve optimizing the code at the cost of code readability if it is certain that the algorithm change will i.e. lower the complexity or space consumption. In this case, it is far fetched assumption that adding a `break` and reordering conditions would change the actual complexity of the algorithm because in general, it wouldn't. Only if we consider particular data set as input it might.

On the other hand, if we have to sacrifice the code readability and increase cyclomatic complexity in order to gain just a few µs, I wouldn't do that.
