### ISSUE TITLE
The comment in comment.go is wrong.

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4318]
##### What should be cleaned up or changed
the comment in https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/pod/common.go line 49 is wrong
`// getPodStatus returns one of three pod statuses (pending, success, failed)`,
because  getPodStatus returns one of four pod statuses (pending, Running, success, failed).
 I volunteer to fix it and issue #4317 
##### Provide any links for context
[common.go](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/pod/common.go)

**Comment by floreks** [comment]
Yes, the current comment is wrong and should be updated.
