### ISSUE TITLE
Floating number can be entered as pod count

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#433]
##### Steps to reproduce
1. Open deploy from settings
2. enter 1.5 as number of pods

##### Observed result
no validation error

##### Expected result
validation error

**Comment by maciaszczykm** [comment]
We should also add validation for big numbers here. I've just killed my cluster with 1 000 000 pods.

**Comment by maciaszczykm** [comment]
Same for `edit pod count` action.

**Comment by bryk** [comment]
Should be as easy as creating a validator that verifies that a number is an integer. 1.0? What do you think?

**Comment by floreks** [comment]
I'll take this one then
