### ISSUE TITLE
v1.x support for kubernetes 1.16.0

### ISSUE THREAD

**Issue by zerkms** [kubernetes/dashboard#4332]
##### Environment

```
Installation method:
Kubernetes version: 1.16.0
Dashboard version: 1.10.1
Operating system: ubuntu:bionic
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

This report is more of a notification to everybody that dashboard v1.10.1 still uses the `apps/v1beta2` API group, while it was deprecated and is disabled by default in the kubernetes 1.16

**Comment by floreks** [comment]
I am not sure what do you expect from us. For notifications you can post message on sig-ui slack.

/close

**Comment by zerkms** [comment]
@floreks an official resolution: whether it is a genuine bug or `wontfix`

**Comment by floreks** [comment]
That's what issue template is for and this one section with 'Expected result'. We won't update v1 for sure. We will update v2 for sure this week.

**Comment by zerkms** [comment]
@floreks right, indeed that's my fault then, sorry and thanks.

**Comment by andrewsav-datacom** [comment]
@floreks 

>That's what issue template is for and this one section with 'Expected result'. We won't update v1. We will update v2 for sure this week.

Sorry, can we get any update on the update please? The front page of the github repo still says v1 and the kubernetes doco still says alpha.

**Comment by maciaszczykm** [comment]
@andrewsav-datacom https://github.com/kubernetes/dashboard/releases - here you will find current releases.

**Comment by AndrewSav** [comment]
Thank you for that. I was enquiring about "v2 update this week" that was mentioned 8 days ago. I'd like to get update on it's status if possible.

**Comment by maciaszczykm** [comment]
I think we can push a new beta today, right @floreks?

**Comment by floreks** [comment]
Ye, we can do that.

**Comment by AndrewSav** [comment]
@floreks thank you for this, is there a place where these issues can be tracked? The only one I could find  (besides this one) is https://github.com/kubernetes/dashboard/issues/4327 which is also closed. Many thanks!

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/pull/4377 PR will fix compatibility issues. Then we can do the release.

**Comment by AndrewSav** [comment]
@floreks looks like it has been merged!

**Comment by floreks** [comment]
Yep, we will do the release soon.
