### ISSUE TITLE
Replication Controllers List View - Wrong external endpoint link

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#435]
##### Environment

```
Dashboard version: HEAD
Kubernetes version: HEAD
Operating system: Windows 7 x64
```

##### Steps to reproduce

I've started cluster with `local-up-cluster` on ubuntu machine, then I've accessed deployed dashboard from notebook with windows.

##### Observed result

External link shows `localhost:<port>` on external machines.

##### Comments

Localhost link is not working for notebook as it is deployed on other machine. It can be accessed but only when actual `<ubuntu_machine_ip>:31521` is provided.

![screenshot_1](https://cloud.githubusercontent.com/assets/2285385/13320270/03be5a4e-dbc8-11e5-8a70-d669da7b4234.png)

**Comment by bryk** [comment]
@maciaszczykm @cheld 

We're coming back to this issue. What do you think about this localhost:1234 endpoints? Do we need them?

**Comment by cheld** [comment]
It is just local-cluster. IMHO, it is obvious for a person that uses local-cluster to replace localhost with the host IP. Currently, I would not spend effort trying to improve the behavior.

won't fix
