### ISSUE TITLE
Add "/language xx" label feature

### ISSUE THREAD

**Issue by atoato88** [kubernetes/dashboard#4352]
##### What would you like to be added

I18n translations is prepared for 2.0.0 release.
It is better to add `/language xx` feature to this repository. e.g. `/language ja`.
As of now, [here](https://prow.k8s.io/command-help?repo=kubernetes%2Fdashboard) says that anyone can use `/launguage xx`, but I got an error at [comment](https://github.com/kubernetes/dashboard/pull/4302#issuecomment-535791096) in #4302
It is similar with `/language xx` feature on kubernetes/website repository.

##### Why is this needed

From now on, we should label `/language xx` to PRs related to files on `i18n/xx` so that translation members can filter on pull requests page on GitHub, effectively.
If do so, translation member can know reviewable items in short time by run [`is:pr is:open label:language/ja `](https://github.com/kubernetes/dashboard/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Alanguage%2Fja) query on PRs page.

besides of this, If OWNERS file in `i18n/xx` contains items below (like [this](https://github.com/kubernetes/website/blob/master/content/ja/OWNERS#L12-L13)), It is possible to label `language/xx` in automatic if PR contains file changes in `i18n/xx`, I think.

```yaml
labels:
- language/xx
```

**Sample usecase**:
1. Someone creates PR that changes multiple `messages.xx.xlf` files in i18n/xx(all of `fr`,`ja`,`ko`,`zh`). e.g. update `template.html` files.
2. Label with `/language xx` on github comment or label automatically by OWNERS file definition.
3. Each translation member(fr, ja, ko, zh) can filter by `is:pr is:open label:language/xx` on PRs page on github.

##### Comments

It is needed to create PR to kubernetes/test-infra for implementing this feature.
Like a kubernetes/test-infra#14378

Relate to: #4259

**Comment by atoato88** [comment]
@shu-mutou Please add any comments if exists.

**Comment by floreks** [comment]
Added new labels to match supported languages.

**Comment by shu-mutou** [comment]
Thank you for investigating this! Since we seems to be able to add `language/ja` label, let's use it to find if PRs have texts needed to be translate.

**Comment by atoato88** [comment]
@floreks Thank you for quick comment !!
I confirmed that I can `/language ja` to both of issue and PR.

**Comment by atoato88** [comment]
I confirmed that a sample usecase in this PR description works correctly at present.
Any changes isn't needed. :smile:

#4353 for setting of label `language/ja` automatically, and checked it in #4354. 

/close
