### ISSUE TITLE
Sidecar containers for dashboard

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/dashboard#4355]
##### What would you like to be added
I want to have the option to specify a sidecar container as a configurable parameter with helm chart

##### Why is this needed
Many time I need to deploy the dashboard with a sidecar container (ex: an auth0 proxy like this https://github.com/trondhindenes/Kubernetes-Auth0 )

##### Comments
Please take a look to Prometheus Helm chart:
https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L508
https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-deployment.yaml#L137-L139

I also opened a ticket here: https://github.com/helm/charts/issues/15939

**Comment by floreks** [comment]
I think this is purely a helm chart issue and doesn't really belong to this repo. I don't see how we could change that in here.

**Comment by pierluigilenoci** [comment]
@floreks probably is true. But nobody takes care of the request on that side.

**Comment by floreks** [comment]
We are not responsible for the helm charts. It was contributed by external people. You can take over and update them if you want to maintain that.
