### ISSUE TITLE
dashboard-metrics-scraper Pod Goes into CrashLoopBackOff

### ISSUE THREAD

**Issue by harsha544** [kubernetes/dashboard#4359]
##### Environment

I am trying to setup Kubernetes Dashboard using the instructions listed here https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ on  

Kubernetes v1.16.0  with 
`GitCommit:2bd9643cee5b3b3a5ecbd3af49d09018f0773c77 `
`GitTreeState:clean`& `BuildDate:"2019-09-18T14:36:53Z"` & 
`GoVersion:"go1.12.9"` with `Compiler:"gc"`on `Platform:"linux/ppc64le" `
```
Installation method: apt sources
Kubernetes version:
Dashboard version:
Operating system: Ubuntu 1804 ppc64le
Node.js version ('node --version' output): NA
Go version ('go version' output): NA
```

##### Steps to reproduce
1) After bootstrapping the Kubernetes Cluster ( single node cluster ), I used Flannel as backboone for communication via 
`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`

2)Applied the Kubernetes Dashboard related changes via per the commands listed here 
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui 
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml`

##### Observed result

```
root@ubuntu:/home/harsha/dashboard# kubectl logs dashboard-metrics-scraper-566cddb686-2sbq9 -n kubernetes-dashboard
{"level":"info","msg":"Kubernetes host: https://10.96.0.1:443","time":"2019-09-30T10:56:33Z"}
{"level":"fatal","msg":"Unable to initialize database tables: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub","time":"2019-09-30T10:56:33Z"}
root@ubuntu:/home/harsha/dashboard# 
```

##### Expected result

Deployment should happen seamlessly.

**Comment by harsha544** [comment]
^^^ @mkumatag  -- FYI.

**Comment by floreks** [comment]
Unfortunately, metrics scraper does not support `ppc64le` architecture correctly right now. It is a known issue.

**Comment by floreks** [comment]
I'd suggest creating that issue on the metrics scraper repo. It's for dashboard issues only.

/close

**Comment by hakim** [comment]
Salam,
I had the same issue with metrics scrapper, I solved it by rebuilding the docker image with ppc64le as GOARCH, to use it you need to replace the name of the metrics scrapper image source in the deployment file recomended.yaml with the new one I upload it recently to docker hub
`abhakim1980/myopenrepo:metrics-scraper-ppc64le` 
Good luck,
