### ISSUE TITLE
Pod count is not limited

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#436]
#### Issue details
validation for pod count max value missing

##### Steps to reproduce
1. open deploy from settings
2. enter 999999999999999999999 as pod count

##### Observed result
Nothing. Pressing deploy has no effect

##### Expected result
Validation error.

##### Comments
A smaller number works like 999, but most likely kills your cluster. Not very nice. However, I don't have a convincing solution

**Comment by floreks** [comment]
I'll take this.

**Comment by floreks** [comment]
I'm thinking about good way of showing a warning as it should be the same for both deploy form and edit replicas dialog.

I've got few options. Add more if you have an ideas:

1. On Deploy/Ok show dialog with warning message and asking user to confirm that he wants to create/edit app with given number of pods.
2. Warning icon with tooltip near input field shown when number of pods is bigger then some number.
3. Text under field similar to error but orange indicating some warning and not blocking deploy/edit action.

**Comment by maciaszczykm** [comment]
I think second and third solutions are the best. First one could be annoying for users.

**Comment by bryk** [comment]
Agree with @maciaszczykm. Don't make this error. Make it a warning (i.e., yellow - should be some angular material class for this out there)
