### ISSUE TITLE
Edit pod count doesn't work

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#437]
##### Environment

```
Dashboard version: latest
Kubernetes version: v1.2.0-alpha.8.186+ac644e03bd6acb
Operating system: Ubuntu 14.04.1
Node.js version: v5.5.0
Go version: go1.5.1 linux/amd64
```

##### Steps to reproduce

1. Go to replication controller details view.
2. Click on pencil icon:

![image](https://cloud.githubusercontent.com/assets/2823399/13320452/77d36338-dbc9-11e5-9b35-f2446ef3a9cd.png)

##### Observed result

Nothing happens.

##### Expected result

Edit pod count dialog appears.

##### Comments

Link is not working, tested on Mozilla.

**Comment by floreks** [comment]
On IE this also doesn't work.

Works on chrome :)

**Comment by cheld** [comment]
P1

**Comment by maciaszczykm** [comment]
Taking this.
