### ISSUE TITLE
getting below error from dashboard-metrics-scraper

### ISSUE THREAD

**Issue by vinothkumar437** [kubernetes/dashboard#4372]
[root@kube-master ~]# kubectl logs -f -n kubernetes-dashboard-head dashboard-metrics-scraper-head-6b99f747bb-wf86q
{"level":"info","msg":"Kubernetes host: https://10.96.0.1:443","time":"2019-10-02T12:23:09Z"}
10.32.0.1 - - [02/Oct/2019:12:23:39 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:23:49 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:23:59 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
{"level":"error","msg":"Error scraping node metrics: the server could not find the requested resource (get nodes.metrics.k8s.io)","time":"2019-10-02T12:24:09Z"}
10.32.0.1 - - [02/Oct/2019:12:24:09 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:24:19 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:24:29 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:24:39 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:24:49 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:24:59 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
{"level":"error","msg":"Error scraping node metrics: the server could not find the requested resource (get nodes.metrics.k8s.io)","time":"2019-10-02T12:25:09Z"}
10.32.0.1 - - [02/Oct/2019:12:25:09 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.32.0.1 - - [02/Oct/2019:12:25:19 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"

**Comment by vinothkumar437** [comment]
Please help me to resolve this issue

**Comment by floreks** [comment]
1. You need to install `metrics-server` inside the cluster and configure it properly.
2. This belong to the `dashboard-metrics-scraper` repository rather than here.

/close
