### ISSUE TITLE
can't create dashboard

### ISSUE THREAD

**Issue by goodidea-kp** [kubernetes/dashboard#4376]
Docker-18.06.03
Kubernetes - 1.16
CentOS-7
command to create dashboard:
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml

1 master node only
Flannel installed
kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS             RESTARTS   AGE
kube-system            coredns-5644d7b6d9-7dzdh                     0/1     Running            0          9m21s
kube-system            coredns-5644d7b6d9-rsn8s                     0/1     Running            0          9m21s
kube-system            etcd-master                                  1/1     Running            0          8m33s
kube-system            kube-apiserver-master                        1/1     Running            0          8m25s
kube-system            kube-controller-manager-master               1/1     Running            0          8m23s
kube-system            kube-flannel-ds-amd64-4bxqd                  1/1     Running            0          8m58s
kube-system            kube-proxy-xccgg                             1/1     Running            0          9m20s
kube-system            kube-scheduler-master                        1/1     Running            0          8m24s
kubernetes-dashboard   dashboard-metrics-scraper-566cddb686-694bs   1/1     Running            0          8m37s
kubernetes-dashboard   kubernetes-dashboard-7b5bf5d559-54x82        0/1     CrashLoopBackOff   6          8m38s

 kubectl logs kubernetes-dashboard-7b5bf5d559-54x82 -n kubernetes-dashboard
2019/10/02 21:08:55 Starting overwatch
2019/10/02 21:08:55 Using namespace: kubernetes-dashboard
2019/10/02 21:08:55 Using in-cluster config to connect to apiserver
2019/10/02 21:08:55 Using secret token for csrf signing
2019/10/02 21:08:55 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: Get https://10.96.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf: dial tcp 10.96.0.1:443: connect: no route to host

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0004b0b20)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x3b4
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc000470100)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:479 +0xc7
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc000470100)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:447 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:528
main.main()
	/home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x212

**Comment by floreks** [comment]
This is a networking issue in your cluster. We can't really help with that. First fix connectivity between pods in the cluster.

/close

**Comment by goodidea-kp** [comment]
@floreks Not agree with you. I don't have any pods. Just 1 master. Are you sure dashboard deployment must be ONLY bare minimum configuration master + node?
Please specify that in the documentation. Otherwise, better to reopen the issue

**Comment by floreks** [comment]
Cluster configuration doesn't matter. You can have X masters and Y nodes. It is clearly a networking issue. Pods can't connect to the API server through kubernetes service. Error is very clear. Connection issue. No route to host. That's not a bug on our side.

**Comment by Isuama** [comment]
having same issue...not agreed with @floreks as we don't create any network stuffs here. if only the dashboard is getting failed where all other pods and nodes are healthy, there should have something..may be the way we are installing or anything...need to find out the exact reason.

**Comment by enros73** [comment]
Having the same issue with a different docker and kubernetes version, but same network configuration with flannel. Host(192.168.254.0/26) and pods(10.244.0.0/16) are in different network. so any conflicts between networks. not agreed with @floreks

**Comment by sammlearning** [comment]
> This is a networking issue in your cluster. We can't really help with that. First fix connectivity between pods/resources and API service in the cluster.
> 
> /close

so what the solutions.. please write down here..

**Comment by floreks** [comment]
Connectivity issues between pods/services is a k8s core issue, not related to Dashboard. We will not provide support for that here.
