### ISSUE TITLE
Problems with the pop-up window when switching namespaces

### ISSUE THREAD

**Issue by mlegeny** [kubernetes/dashboard#4379]
##### Environment
```
Installation method:
Kubernetes version: 1.13.10
Dashboard version: 1.10.1
Operating system: Amazon Linux
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Select a namespace from the drop-down menu in the left-hand side panel, e.g. "namespace-1".
2. Select a Deployment.
3. Select a Replica Set, then click "Logs" in the top menu bar.
4. When the logs are displayed, select another namespace from the drop-down menu in the left-hand side panel, e.g. "namespace-2".

##### Observed result
A pop-up window appears with the following text:

Change namespace?
Selected resource is in a different namespace than currently selected.
Do you want to change namespace from _namespace-2_ to _namespace-1?

[YES] [NO]

##### Expected result
It should read "from _namespace-1_ to _namespace-2_".
Also, if I click "Yes" then the UI stays on my current namespace, however if I click "No", it changes the namespace. It should be the other way around.

**Comment by floreks** [comment]
It has been changed already in the new v2 version.

Related to https://github.com/kubernetes/dashboard/issues/3909

/close
