### ISSUE TITLE
cpu/memory graphs switch places randomly

### ISSUE THREAD

**Issue by stephen-dahl** [kubernetes/dashboard#4389]
##### Environment
Installation method: kubectl
Kubernetes version: 1.13
Dashboard version: 2 beta 4
Operating system: ubuntu

##### Steps to reproduce
install beta 4 with metrics server

##### Observed result
cpu/memory graphs jump to different pods on update. if we have a list of pods like this

| pods | graphs |
| --- | --- |
| pod1 | graph1 |
| pod2 | graph2 |
| pod3 | graph3 |

then after an update they might be

| pods | graphs |
| --- | --- |
| pod1 | graph2 |
| pod2 | graph1 |
| pod3 | graph3 |

I have not noticed a pattern yet

##### Expected result
graphs stay on the right row

**Comment by stephen-dahl** [comment]
![graphs](https://user-images.githubusercontent.com/6061073/66325555-4df71b80-e8dc-11e9-9fd2-999d8d26c4d7.gif)
gif showing the bug

**Comment by floreks** [comment]
Already fixed on master. This is a duplicate. New release should be out soon.

/close

**Comment by stephen-dahl** [comment]
@floreks I just found the same thing with secrets on the pod screen, was that fixed to? (couldn't find the issue your referencing)

**Comment by floreks** [comment]
@stephen-dahl 

Issue: https://github.com/kubernetes/dashboard/issues/4129
PR: https://github.com/kubernetes/dashboard/pull/4272
