### ISSUE TITLE
Input label and validation message overlap

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#439]
#### Issue details
The validation error message and the label from the following input field might loverlap

##### Environment
Browser: Firefox

##### Steps to reproduce
Steps:
1. Enter test- into app name
2. Click into image field

##### Observed result
Text overlaps

##### Expected result
nicer

##### Comments
minor issue. not required to be fixed
![text-overlap](https://cloud.githubusercontent.com/assets/7448799/13320730/40936772-dbcb-11e5-991f-76e351ea84f6.png)

**Comment by bryk** [comment]
This is caused by layout issues on the deploy page. I'll fix this quickly.
