### ISSUE TITLE
Forbidden for user

### ISSUE THREAD

**Issue by cvetyx** [kubernetes/dashboard#4394]
Hello i am quite new to Kubernetes and I have no idea what is going no.
When i open the dashboard i can't create a new deployment and i am receiving a bunch of error notifications. 
![image](https://user-images.githubusercontent.com/33726107/66401617-baa90d80-e9e3-11e9-93d3-86576fbcba75.png)
Can someone explain to me how can i resolve this?

**Comment by maciaszczykm** [comment]
This is an error coming directly from Kubernetes cluster. Your are not authorized to view namespaces, daemon sets etc. Please refer to Kubernetes documentation.

/close
