### ISSUE TITLE
Editing Resources YAML/JSON TextArea Empty Glitch

### ISSUE THREAD

**Issue by timperez-weather** [kubernetes/dashboard#4399]
##### Environment
```
Installation method: Minikube Addon
Kubernetes version: Client & Server 1.16.1
Dashboard version: v2.0.0-beta4+0.gf232c589
Operating system: Windows
Node.js version: 10.15.0 
Go version ('go version' output): n/a
```

##### Steps to reproduce
Click edit on any resource to view yaml/json modal.

##### Observed result
Text area is empty...

##### Expected result
Should contain resource's yaml / json.

##### Comments
Trying to edit a configmap or secret does the same, except it will briefly populate the text area before suddenly clearing itself.

**Comment by floreks** [comment]
It is a duplicate. Already fixed on master.

/close
