### ISSUE TITLE
Dashboard  v1.10.1 can not use k8s 1.16.1 

### ISSUE THREAD

**Issue by zyl704126612** [kubernetes/dashboard#4401]
Installation method: kubeadm
Kubernetes version: 1.16.1 
Dashboard version: v1.10.1
Operating system: centos 7.4

when I use Authentication Token (RBAC) token to login dashbord, 

warning
configmaps is forbidden: User "system:anonymous" cannot list resource "configmaps" in API group "" in the namespace "default" 
warning
persistentvolumeclaims is forbidden: User "system:anonymous" cannot list resource "persistentvolumeclaims" in API group "" in the namespace "default" 
warning
 secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "default" 
...

when i use k8s 1.15.2 ,it works.

**Comment by floreks** [comment]
Dashboard `v1` is not being maintained and will not work with newer versions of K8S. `v2` will be updated and new beta will be released once https://github.com/kubernetes/dashboard/pull/4377 is merged.

/close
