### ISSUE TITLE
Maximum number of logs in context menu is 10

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#441]
##### Environment

```
Dashboard version: latest
Kubernetes version: v1.2.0-alpha.8.186+ac644e03bd6acb
Operating system: Ubuntu 14.04.1
Node.js version: v5.5.0
Go version: go1.5.1 linux/amd64
```

##### Steps to reproduce

1. Create replication controller with at least 11 pods.
2. Open logs context menu on replication controller list page.

##### Observed result

There are only 10 links to logs.

##### Expected result

There should be exactly the same number of links as pods in replication controller.

**Comment by maciaszczykm** [comment]
Not a bug according to https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/11-11-2015/16_card%20variations.png. 

@bryk @cheld @floreks Opinions?

**Comment by cheld** [comment]
hmm...I agree that the list cannot grow infinit. Some solution is needed for that. But, why 10? Seems to be a number out of thin air. Maybe after 10 the list should not be shown at all. 

Anyway, we should keep the current behavior, but still it must be improved, sometime. Or we need VERY, VERY good arguments for our QA!

P5

**Comment by bryk** [comment]
Yep, 10 was chosen arbitrarily. I agree this should be changed. No strong opinions how. Maybe show all? Or do pagination? Or show that we've truncated the list?

Anyway, adding to post 1.0

**Comment by digitalfishpond** [comment]
Any strong opinions about this? 
Here's a suggestion that uses the assumption that more than 10 pods per RC is a less usual use-case than fewer than 10 pods per RC (I don't know if this is accurate): 
How about a highlighted link saying 'More Pods...' or 'See all Pods...' at the bottom of a list of 10 pods, that takes you to the 'Pods' section of the workloads list page which shows all Pods with links to their respective logs?

**Comment by floreks** [comment]
How about implementing [virtual repeat](https://material.angularjs.org/latest/demo/virtualRepeat) on this menu, so user can see all pod logs links?

@maciaszczykm @bryk what's your opinion?

**Comment by maciaszczykm** [comment]
Virtual repeat seems to be exactly what we need here.

**Comment by digitalfishpond** [comment]
Looks ideal. I'll implement this now.

**Comment by bryk** [comment]
@digitalfishpond @maciaszczykm @floreks I don't think we have real estate to display all pods in that dropdown. The idea with "See all..." looks just about right, because it solves the problem and is easy to implement. What do you think?

**Comment by floreks** [comment]
"See all..." option would show user all pods not only pods related to the controller and I think that's not what user would expect to see. Virtual repeat shouldn't be hard to implement also, and it will show in an easy way all related pods with link to logs. What do you think?

**Comment by bryk** [comment]
Ok, after a round of thoughts I agree :) Showing all pods there is good. As long as it does not crash the UI.
