### ISSUE TITLE
The server could not find the requested resource

### ISSUE THREAD

**Issue by dkijkuit** [kubernetes/dashboard#4410]
##### Environment
I have a 4 node setup with a separate control plane. Everything is freshly installed using the same versions.

`v1.16.1  Debian GNU/Linux 10 (buster)   4.19.69-meson64   docker://18.9.9`

```
Installation method: kubeadm
Kubernetes version: 1.16.1
Dashboard version: 2.0.0-beta4
Operating system: Armbian (Debian 10)
```

When using kubectl I can create/update and deploy anything without issues. When using the dashboard to create a deployment or namespace I receive the error in the dashboard saying:

```
Deploying file has failed
the server could not find the requested resource
```

##### Steps to reproduce

1. Launch proxy: kubectl proxy
2. Open URL:
http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

3. Login using token
4. Create new namespace using the  '+' sign on the top right.
5. Paste namespace YAML into the window and click  'Upload'

##### Observed result
Error appears:
```
Deploying file has failed
the server could not find the requested resource
```

##### Expected result
Creation of the namespace

**Comment by floreks** [comment]
Search for issues before creating. This is a duplicate. Related to v1.16 support 

/close

**Comment by dkijkuit** [comment]
I did search the issue repo but no results came up regarding the error. When searching on 'v1.16 support' I did find the related issue, but the error message is shown in an image only. This is why it doesn't appear when searching.

Try to be more polite next time and thank you for your comment.

**Comment by floreks** [comment]
We have every day couple of issues created related to K8S 1.16. It is not officially supported by beta4. The compatibility matrix on releases page shows that. Under every issue that provides Kubernetes 1.16.X as used version I have to write the same answer.

Please also value our time and check closed issues/compatibility before opening new one.

There is even a PR open to add support for 1.16.

**Comment by dkijkuit** [comment]
What got me confused is that the matrix itself does not show 1.16 at all and that the official K8s website for v1.16 refers to 2.0.0-beta4 which gives you the impression that it is supported.

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

I really appreciate that you all take time to read and investigate each issue. Maybe it makes more sense to adjust the documentation accordingly.

Thanks again :)

**Comment by mariusmarais** [comment]
Since Google will bring future travellers here since kops now supports 1.16: See https://github.com/kubernetes/dashboard/issues/4332

v1.10.1 seems abandoned according to that issue, best options is to use latest v2.
