### ISSUE TITLE
Auto-detect Dark Mode by using prefers-color-scheme

### ISSUE THREAD

**Issue by donbeave** [kubernetes/dashboard#4411]
With new auto dark mode feature in macOS Catalina, it will be nice to see Kubernetes Dashboard will also  follow this trend, and by default will use that mode which currently set on system level:

<img width="780" alt="macOS settings" src="https://user-images.githubusercontent.com/139017/66705444-4bbc1380-ed59-11e9-85b7-8dc2346fa5fb.png">

**Comment by anshulahuja98** [comment]
So you basically want a time based dark/light mode?

**Comment by donbeave** [comment]
Yeah, time-based. Actually I mean respect my system settings, when the system setting is set to light mode Kubernetes Dashboard will be in light mode, when the system setting is set to dark mode, Kubernetes Dashboard will switch to the dark mode automatically.

**Comment by maciaszczykm** [comment]
We will have to check how the browser exposes this setting and if it is not only macOS-specific.

**Comment by donbeave** [comment]
@maciaszczykm you can use `prefers-color-scheme`: https://www.chromestatus.com/feature/5109758977638400

**Comment by vasicvuk** [comment]
Chrome on Windows also supports **prefers-color-scheme** and also Edge (Chromium based) supports it.

**Comment by zerefwayne** [comment]
Hey @maciaszczykm, I would love to work on this issue.

**Comment by maciaszczykm** [comment]
@zerefwayne Great! Do you need any help? If not please create a pull request as early as possible so we can discuss it before you will go into details. You can also create a short proposal of how it should work in your opinion.

**Comment by maciaszczykm** [comment]
It's already done.
