### ISSUE TITLE
Alternative deploy now asks for login

### ISSUE THREAD

**Issue by mausch** [kubernetes/dashboard#4420]
```
Installation method: Alternative
Kubernetes version: 1.12
Dashboard version: 2.0.0-beta5
Operating system: Ubuntu 16
Node.js version ('node --version' output):
Go version ('go version' output):
```

Up to 2.0.0-beta4 I was able to install https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/alternative.yaml and access the dashboard without login.

With 2.0.0-beta5 I get asked for a login.
Not sure if this change was intentional? Seems to be related to https://github.com/kubernetes/dashboard/issues/4312 / https://github.com/kubernetes/dashboard/pull/4341 .

My workaround is to remove the `--enable-insecure-login` flag.

BTW thanks for all the great work :)

**Comment by floreks** [comment]
That is actually not a bug. Alternative deployment was always meant to be used together with the `Authorization: Bearer <token>` header as a substitute for login. For the security reasons we've had to tighten the rules and now if header is to be used, login also is enabled. If you remove this `--enable-insecure-login` flag then you will only be able to use Dashboard's SA privileges and you will have to manually grant it more privileges.

**Comment by mausch** [comment]
Not sure what that means tbh... This is for a local cluster so I'm applying https://kubernetes.io/docs/reference/access-authn-authz/rbac/#permissive-rbac-permissions - I guess that enables all the necessary permissions?

In any case if it's going to be the new behaviour from now on I'll just keep using my workaround, no worries.

**Comment by floreks** [comment]
The way you are using is fine for local cluster. Remove the flag and use as before.
