### ISSUE TITLE
Accessing dashboard with id_token in Authorisation header

### ISSUE THREAD

**Issue by julien69740** [kubernetes/dashboard#4429]
Hello everyone,

I develop a small application in python which connect to my OIDC provider and get id_token and access_token.

The procedure is : 

The user access to a page which have only one button "connexion kubernetes".

![image](https://user-images.githubusercontent.com/10599434/66993323-a80d9300-f0cb-11e9-9641-0fd58b19e738.png)

When the user click on the button, It is redirect to the identity provider where the user logs in with his login credentials.
When he succeed to  login, the user is redirect to a web page with two button : 

![image](https://user-images.githubusercontent.com/10599434/66993383-c5426180-f0cb-11e9-9808-6e2091f279f5.png)

1) "Get kubeconfig" : When the user click on this button, the application generate a kubeconfig with the id_token of the user  and dowload it.
This part is working.

2) The second button is "Access dashboard": 
I would like when the user click on this button, the user is redirect to the dashboard and authentificate automaticly with the id_token .
I see i can pass the token in Authorisation header but I don't know how.

Note: in the page with the two button, I have in memory the id_token and access_token of the user but I don't know how to redirect and pass the token to the dashboard.

Thanks for your help.

**Comment by floreks** [comment]
We cannot help you with your application. The only thing you need to do on the Dashboard side is to add `Authorization: Bearer <token>` request header to every request that goes to the Dashboard. It will automatically recognize it and use it for auth.
