### ISSUE TITLE
Can we reduce the code duplication in handler/apihandler with code similar to the following?

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4433]
##### What should be cleaned up or changed
```go
func (apiHandler *APIHandler) handleGetStatefulSetList(request *restful.Request, response *restful.Response) {
	k8sClient, err := apiHandler.cManager.Client(request)
	if err != nil {
		errors.HandleInternalError(response, err)
		return
	}

	namespace := parseNamespacePathParameter(request)
	dataSelect := parser.ParseDataSelectPathParameter(request)
	dataSelect.MetricQuery = dataselect.StandardMetrics
	result, err := statefulset.GetStatefulSetList(k8sClient, namespace, dataSelect,
		apiHandler.iManager.Metric().Client())
	if err != nil {
		errors.HandleInternalError(response, err)
		return
	}
	response.WriteHeaderAndEntity(http.StatusOK, result)
}

func (apiHandler *APIHandler) handleGetStatefulSetDetail(request *restful.Request, response *restful.Response) {
	k8sClient, err := apiHandler.cManager.Client(request)
	if err != nil {
		errors.HandleInternalError(response, err)
		return
	}

	namespace := request.PathParameter("namespace")
	name := request.PathParameter("statefulset")
	result, err := statefulset.GetStatefulSetDetail(k8sClient, apiHandler.iManager.Metric().Client(), namespace, name)

	if err != nil {
		errors.HandleInternalError(response, err)
		return
	}
	response.WriteHeaderAndEntity(http.StatusOK, result)
}

func (apiHandler *APIHandler) handleGetStatefulSetPods(request *restful.Request, response *restful.Response) {
	k8sClient, err := apiHandler.cManager.Client(request)
	if err != nil {
		errors.HandleInternalError(response, err)
		return
	}

	namespace := request.PathParameter("namespace")
	name := request.PathParameter("statefulset")
	dataSelect := parser.ParseDataSelectPathParameter(request)
	dataSelect.MetricQuery = dataselect.StandardMetrics
	result, err := statefulset.GetStatefulSetPods(k8sClient, apiHandler.iManager.Metric().Client(), dataSelect, name, namespace)
	if err != nil {
		errors.HandleInternalError(response, err)
		return
	}
	response.WriteHeaderAndEntity(http.StatusOK, result)
}
```
there are **more than 90** function are written like this,  it's very similar and high code duplication. so could we find out some method to fix it. The following is some code I try to fix it (just a demo). 
```go
func (apiHandler *APIHandler) handleGetAllResource(request *restful.Request, response *restful.Response) {
  var result interface{}
  var err error
  k8sClient, err := apiHandler.cManager.Client(request)
  if err != nil {
    errors.HandleInternalError(response, err)
    return
  }
  name := request.PathParameter("name")
  namespace := parseNamespacePathParameter(request)
  namespaceStr := request.PathParameter("namespace")
  dataSelect := parser.ParseDataSelectPathParameter(request)
  kind := request.PathParameter("kind")
  switch kind {
  case "ClusterRoleList":
    result, err = clusterrole.GetClusterRoleList(k8sClient, dataSelect)
  case "ClusterRoleDetail":
    result, err = clusterrole.GetClusterRoleDetail(k8sClient, name)
  case "StatefulSetList":
    result, err = statefulset.GetStatefulSetList(k8sClient, namespace, dataSelect, apiHandler.iManager.Metric().Client())
  case "ServiceDetail":
    result, err = resourceService.GetServiceDetail(k8sClient, namespaceStr, name)
  case "NodeDetail":
    result, err = node.GetNodeDetail(k8sClient, apiHandler.iManager.Metric().Client(), name, dataSelect)
  }
  if err != nil {
    errors.HandleInternalError(response, err)
    return
  }
  response.WriteHeaderAndEntity(http.StatusOK, result)
}
```
I volunteer to submit a pr to modify them.
##### Provide any links for context
[apihandler.go](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/apihandler.go)
@floreks @maciaszczykm

**Comment by floreks** [comment]
I'd prefer to use a method per endpoint. Having generic method for many endpoints will eventually cause issues and will be problematic to debug.

**Comment by zehuaiWANG** [comment]
I don't agree that it will be problematic to debug. I don't think it will increase the possibility of bugs in the code or the difficulty of debugging. However, it is not elegant enough because it adds a variable to distinguish the method call and the coupling of various functions. I just think this code is worth optimizing. After all, it has more than 90 methods and has a high code repetition rate. Of course, I haven't found a good method yet.

**Comment by floreks** [comment]
To do this right, it would require a huge refactoring. It's not something to worry about before official v2 release. It's a rather low priority. Some of the newer handlers are defined in separate files which IMHO is a better approach, i.e. https://github.com/kubernetes/dashboard/blob/master/src/app/backend/settings/handler.go

**Comment by zehuaiWANG** [comment]
okay, I agree with you that the way to define handlers in separate files is a better way. It will be better to make the code classificated by feature which makes it looks cleaner . I volunteer to do it. Could I submit some pr to do this.

**Comment by floreks** [comment]
This is a rather low priority. Maybe take a look at some issues with higher priorities. I'd want to start initial work on such important and big refactoring on my own. Prepare first some base so it is clear how to proceed later on.

**Comment by zehuaiWANG** [comment]
okay， I agree， if there are any higher priorities issue which about the backend part, plz let me know, I am willing to fix it. And I will also to do some base so it is clear how to procceed later on. Thanks a lot.
