### ISSUE TITLE
App name field should indicate the max lenght

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#444]
#### Issue details
Some field in Dashboard indicate the number of chars that can be entered like 0/63. Some fields don't.

##### Steps to reproduce
1. Open deploy from settings
2. click in app name

##### Observed result
nothing

##### Expected result
max length indicator is shown below input field

##### Comments
same for some other fields

**Comment by cheld** [comment]
This is also material design default

**Comment by cheld** [comment]
P1

**Comment by bryk** [comment]
This is all about using `md-maxlengh` instead of `ng-maxlength`. I'll take this.
