### ISSUE TITLE
Getting i/o timeout when dashboard communicate with apiserver

### ISSUE THREAD

**Issue by jeffwji** [kubernetes/dashboard#4442]
I'm trying the latest version(2.0.0-bate5) of dashboard with K8S 1.16. I setup a minimal cluster with one master and 2 workers. but when I applied dashboard, it gave me the error message:

    panic: Get https://10.96.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf: dial tcp 10.96.0.1:443: i/o timeout

While the ip 10.96.0.1 is apiserver's service address:

    $ kubectl get service
    NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
    kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   9d

Service IP range is 10.96.0.0/24. Pods IP range is 10.95.0.0/16

The master node external IP is 192.168.56.106. Two workers external IP is 192.168.56.107/108

Installation command:

    $ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta5/aio/deploy/recommended.yaml

If I turn off iptables, the error will gone, but will back once iptables enabled again. I'm not sure is there anything special I need to pay attention? The settings for iptables is.

    $ cat /etc/sysconfig/iptables
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    -A INPUT -p icmp -j ACCEPT
    -A INPUT -i lo -j ACCEPT
    -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
    -A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT
    -A INPUT -p tcp -m state --state NEW -m tcp --dport 1443 -j ACCEPT
    -A INPUT -p tcp -m state --state NEW -m tcp --dport 2443 -j ACCEPT
    -A INPUT -i enp0s9 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
    -A INPUT -s 10.96.0.0/24 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
    -A INPUT -s 10.95.0.0/16 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
    -A INPUT -j REJECT --reject-with icmp-host-prohibited
    -A FORWARD -j REJECT --reject-with icmp-host-prohibited
    COMMIT

IP forwards is enabled:

    $ cat /etc/sysctl.d/99-sysctl.conf
    net.ipv4.ip_forward=1

What else should I do?

**Comment by floreks** [comment]
This is a networking issue in your cluster, not related directly to Dashboard. Core repo is for such issues.

/close
