### ISSUE TITLE
Trying to access/modify dashboard exclusive resource

### ISSUE THREAD

**Issue by yidasanqian** [kubernetes/dashboard#4444]
##### Environment

```
Installation method: docker-for-desktop
Kubernetes version: v1.10.1
Dashboard version:v1.14.6
Operating system:macos
Node.js version ('node --version' output): v11.1.0
Go version ('go version' output): not install
```

##### Steps to reproduce

login dashboard, enter namespace kube-system than click below link:
<img src="https://raw.githubusercontent.com/yidasanqian/picture-bed/master/img/1.jpg"/>

##### Observed result

<img src="https://raw.githubusercontent.com/yidasanqian/picture-bed/master/img/2.png"/>

##### Expected result

can normal access 

##### Comments

token generate by cmd:
```
$(kubectl -n kube-system describe secret default| awk '$1=="token:"{print $2}'
```

**Comment by floreks** [comment]
This is not a bug and the error message is quite clear. We do not allow access to resources strictly required and used by Dashboard only. The only way to access them is by using `kubectl`

/close
