### ISSUE TITLE
Consider adding a robots.txt to prevent search engine indexing

### ISSUE THREAD

**Issue by shankie-san** [kubernetes/dashboard#4456]
##### What would you like to be added
Consider adding a robots.txt to the root of K8S dashboard to reduce the chance of people who have (stupidly) publicly exposed their dashboards from appearing in search results.

##### Why is this needed
I was searching for why my (not publicly exposed) dashboard was displaying the following e

_There is nothing to display here_

But, if you [search](https://www.google.com/search?q=k8s+dashboard+"There+is+nothing+to+display+here") for this error message, most of the results that you get are people's live dashboards who have stupidly exposed them to the internet. Simply adding a robots.txt or similar would reduce the chance of people's stupidity being mae public.

**Comment by floreks** [comment]
Sure, it's not a problem for us to add this. It should slightly improve the "security" for such people :joy:, but there are other ways to scan for exposed Dashboard's though.

**Comment by shankie-san** [comment]
Great! I know it's trivial. But I'm didn't set out to do a hack and found loads of people's dashboards to mess with just with a Google search. Wild.

You'll be happy to know that I resisted the urge to hit 'delete' on a couple of haproxy deployments 😉 

Thanks guys 👍
