### ISSUE TITLE
No verification whether port number is given

### ISSUE THREAD

**Issue by olekzabl** [kubernetes/dashboard#446]
##### Steps to reproduce
1. Open "Deploy a Containerized App"
2. Select "Specify app details"
3. Enter:
  - app name: any valid
  - container image: I tried two values: "gcr.io/google_containers/heapster:v0.18.4" or "gcr.io/google_containers/etcd:2.0.9"
  - number of pods: 1
4. Enter target port "1", leave source port *empty* <br>
(alternatively - with the same effect - enter "1" as source and leave target empty)  
5. Click "deploy"

##### Observed result
- For the image "gcr.io/google_containers/heapster:v0.18.4": everything seems successful.
- For the image "gcr.io/google_containers/etcd:2.0.9": the request is initially apparently accepted, and the dashboard is shown back.
The new app is shown with some error in its creation. (See the screenshots). This is exactly the same result as if I did not specify any ports at all. (So, I guess that this image is invalid for some reason?)
![screenshot from 2016-02-25 20 13 12](https://cloud.githubusercontent.com/assets/17475944/13331333/4af93926-dbfd-11e5-9ef2-0e0b5352b97c.png)
![screenshot from 2016-02-25 20 20 52](https://cloud.githubusercontent.com/assets/17475944/13331339/4e974d3e-dbfd-11e5-9bb0-3139b058a326.png)

##### Expected result
In every case, I would expect the form to reject the request, showing some warning at the source port field that it's empty.
(Analogously as it would do for other obligatory fields).

##### Comments
I am also surprised that the details page of the faulty cluster (the 2nd screenshot) does not show any clear error message. (At least I can't see it).

**Comment by floreks** [comment]
Details Page -> Events tab should show related error events retrieved from kubernetes. Isn't it right?

**Comment by olekzabl** [comment]
You're right, thank you. The error message there is the same as in the main page.

**Comment by cheld** [comment]
hmm... I could reproduce that the port fields have a missing validation. But other than that I could not find a fundamental problem. (If only one field is entered than no service is created)

**Comment by cheld** [comment]
P2

**Comment by floreks** [comment]
This is not an issue with port mappings but with etcd image deployment and correctly an error is shown. Try deploying etcd giving just name and container image, result will be the same.

In the code we actually filter out empty port mapping so only when both `port` and `targetPort` are provided then it will be based to backend.
https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/deploy/deployfromsettings_controller.js#L194

Can be closed i think :)

**Comment by bryk** [comment]
Working as intended. If users start complaining about this behavior we'll change it.
