### ISSUE TITLE
Create documentation about building the Dashboard

### ISSUE THREAD

**Issue by erandu** [kubernetes/dashboard#4461]
##### What would you like to be added

Hi all,

I have just a suggestion I think it would be nice to add some documentations about the steps required to build the dashboard as a Docker image.
Currently we must check the `.travis.yml` file to be aware of these differents steps.

##### Why is this needed

My use case is that I need to customize the dashboard, so I need to build the dashboard and I think it would be better for users or contributor to have a small documentation about the steps required to build the dashboard as a Docker image.

Thanks for all :thumbsup:

**Comment by zehuaiWANG** [comment]
The dashboard is designed to be built through the operator, which means it needs to be used within the cluster environment, not as a docker image.

**Comment by PaulFurtado** [comment]
@zehuaiWANG what operator is supposed to build the dashboard code?

**Comment by zehuaiWANG** [comment]
sorry，I make a misstake，it's ok for dashboard to build into docker. The docker image is being released automatically after every master build， https://hub.docker.com/r/kubernetesdashboarddev/dashboard， this is latest dev image. And https://github.com/kubernetes/dashboard/blob/master/aio/deploy/head.yaml，this yaml even deploys this latest version of dashboard. And if you want to build dashboard docker by yourself, you can `exec` into the a centos docker(or any other docker you want) and follow the contributor's getting started's guide(https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md).

**Comment by zehuaiWANG** [comment]
@PaulFurtado

**Comment by zehuaiWANG** [comment]
@erandu

**Comment by floreks** [comment]
It's already described [here](https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md).

/close
