### ISSUE TITLE
The Deployment "kubernetes-dashboard" is invalid

### ISSUE THREAD

**Issue by Antoine77250** [kubernetes/dashboard#4462]
##### Environment

```
Installation method: Azure Kubernetes Cluster
Kubernetes version: v1.13.10
Dashboard version: v1.10.1
Operating system: Ubuntu
```

##### Steps to reproduce
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result

Deployment seems to be invalid while directly applying from the Github Version as told on the Readme.md file.

secret/kubernetes-dashboard-certs unchanged
serviceaccount/kubernetes-dashboard configured
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal configured
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal configured
service/kubernetes-dashboard configured
The Deployment "kubernetes-dashboard" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"kubernetes-dashboard"}: `selector` does not match template `labels`

##### Expected result
Deployment expected to finish successfully.

##### Comments
I have very little experience with bug issuing so tell me if you need anything more.

**Comment by floreks** [comment]
Dashboard v1.10.1 is no longer supported.

/close
