### ISSUE TITLE
View ConfigMaps Data will disappear after several secondes v2.0.0-beta5

### ISSUE THREAD

**Issue by AndySkyL** [kubernetes/dashboard#4464]
dashboard:v2.0.0-beta5 with same bug #4311  

```
Installation method:   kubectl apply -f  recommended.yaml
Kubernetes version: kubeadm 1.16.2   and  binary file 1.16.2 
Dashboard version:  v2.0.0-beta5
Operating system: CentOS 7.6.1810  kernel:  4.4.178
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
login dashboard click Config Maps and view any config Data will disappear after several secondes

##### Observed result
![dashboard-bug](https://user-images.githubusercontent.com/18067975/67615271-cc205100-f7fc-11e9-860f-0863f879cc90.jpg)

**Comment by floreks** [comment]
Already fixed on the master.

/close
