### ISSUE TITLE
Hanging Deploy App form (due to long label keys/values?)

### ISSUE THREAD

**Issue by olekzabl** [kubernetes/dashboard#447]
#### Issue details
Nothing happens after clicking "Deploy" button at the bottom. (Five times in a row).

##### Steps to reproduce
1. Deploy a Containerized App
2. Select "Specify app details below"
3. App name: olekz13 (sth not used before)
4. Container image: gcr.io/google_containers/heapster:v0.18.4
5. Expose service externally: Y
6. Description: abcdefghijkl
7. Add a label:
  - key: 199 repetitions of abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  - value: 165 repetitions of abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
8. Click "Deploy"

##### Observed result
Nothing happens at all. (Or I've missed something again). 

##### Expected result
Either a warning about faulty data in the form, or a successful deployment.

##### Comments
After clicking "Cancel", I get back to the dashboard, in which no new app has been deployed.
(That's just reasonable, given the above behaviour).

**Comment by cheld** [comment]
Validation missing on labels and keys

**Comment by cheld** [comment]
P1

**Comment by digitalfishpond** [comment]
looking into this now

**Comment by bryk** [comment]
Thanks @digitalfishpond!
