### ISSUE TITLE
 some feature about taints、tolerations and labels managerment

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4473]
##### What would you like to be added

 some feature about taints、tolerations and labels managerment

##### Why is this needed
I finded out dashboard don't have some feature about taints、tolerations and labels managerment，this is some important features for users. 

##### Comments

[taints and tolerations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/)

I am willing to implement it if everyone needs it. Thanks a lot~

**Comment by floreks** [comment]
I'd say that more important would be to add Role, ClusterRoleBinding and RoleBinding endpoints for list/details of those resources.

**Comment by zehuaiWANG** [comment]
Okay, is that anyone doing this part now？( add Role, ClusterRoleBinding and RoleBinding endpoints for list/details of those resources). Could I join them to submit some codes for the backend part，thanks~ @floreks

**Comment by floreks** [comment]
I don't think anyone is working on that. Feel free to take that.

**Comment by zehuaiWANG** [comment]
great, thank you~ i will try to do it.
