### ISSUE TITLE
Horizontal scroll bar is not shown in RC Detail page. 

### ISSUE THREAD

**Issue by f-higashi** [kubernetes/dashboard#448]
#### Issue details

Horizontal scroll bar is not shown when verticul scroll bar is  not at the bottom.

##### Environment

Dashboard version: cffd34a90ae4a2334db4f062202f3a00fdf73dc6 ( I used gulp serve:product)
Kubernetes version: v1.1.2
Operating system: Ubuntu 14.04.1
Node.js version: v5.2.0
Go version: 1.5.2
Browser: chrome, firefox, IE

##### Steps to reproduce

1. Create app with long name
2. Open Detail RC page and move to EVENTS tab

##### Observed result

![ds1](https://cloud.githubusercontent.com/assets/8746742/13344833/0dc9a46e-dc9d-11e5-832a-bc38fd13e1ab.PNG)
![ds2](https://cloud.githubusercontent.com/assets/8746742/13344836/1531cfb0-dc9d-11e5-95f2-f55259ccc3bf.PNG)

##### Expected result

Show horizontal scroll bar always.
Or 
Wrap long text in some columns (Pod column in PODS tab and Sub-object column in EVENTS tag).

**Comment by cheld** [comment]
P2

**Comment by floreks** [comment]
Please add some information about browser that you are testing on to the reported issues. This problem may be restricted to 1 browser only. I've had similar issues on IE, but on Chrome it was fine.

**Comment by f-higashi** [comment]
@floreks 
I added information.
Unfortunately this problem occurs on all browsers.

**Comment by floreks** [comment]
Thanks! Not all problems are related to all browsers so it's good to know how to reproduce them.

**Comment by bryk** [comment]
Post 1.0? Do you folks agree?

**Comment by digitalfishpond** [comment]
This no longer seems to be reproducable since @bryk fixed #644 
@f-higashi, can you still reproduce?

**Comment by f-higashi** [comment]
good.
I cannot reproduce this issue.
I close this issue.
