### ISSUE TITLE
Validation is inconsistent

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#449]
#### Issue details
Some fields validate as-you-type, while other fields validate on focus-out. Other inconsistencies exist.

##### Steps to reproduce
1. Open deploy from settings page
2. Enter app name that already exists
=> validation error before focus-out
3. Enter -1 as number of ports
=> validation error on focus-out

##### Observed result
1. Inconsistent behavior.
2. The debounce time of the app name validation seems to be too short => annoying to use 

##### Expected result
Consistent, non-annoying behavior

##### Comments
* In Gmail all fields are validated on focus-out
* in GCE all fields are validated as-you-type, however the debounce is longer (maybe 1s)
* In material design default we have a combination of both

**Comment by olekzabl** [comment]
Sometimes, a red error message appears just after typing the initial "-" sign (maybe after ~0.5s), but disappears after typing the first digit. Sometimes, it does (or seems to) not appear at all.

**Comment by digitalfishpond** [comment]
@olekzabl On which field?

**Comment by olekzabl** [comment]
Number of pods, in "Deploy App" form.

**Comment by cheld** [comment]
P1

**Comment by digitalfishpond** [comment]
1) Validation (with one exception - see point 3) happens after the first on-blur of a field. after that, validation happens on-the fly as the user makes corrections after re-entering the field. 
2) On-the-fly validation happens with some delay due to de-bounce necessary to not overload the server with requests at each keystroke.
3) The exception mentioned in point on is on the App name field: the 'unique name' check is asynchronous, and the error message is returned whenever the async validation is resolved. 
With this in mind, please agree how validation should change and I will implement the changes.

**Comment by digitalfishpond** [comment]
Another restriction is the Angular Material bug (for which I was asked to remove my fix) which causes the following behaviour: 
When an error message is shown, if a valid state is entered (blue line) and then another error is shown, then the error message is shown. (desired behaviour)
When an error message is shown, if an other error is caused immediately (without first entering a valid state), then the error message is not shown, only the line goes red (problem described by @olekzabl in combination with points raised above)

**Comment by cheld** [comment]
Asynchronous is no valid argument for keeping inconsistency. One can implement asynchronous validation in all three flavours. See GMail or GCE for examples. They implement synchronous and asynchronous validation consistently (in different ways)

I am not in a strong favor for one over the other. However, it must be consistent.

@bryk Do you have an opinion?

**Comment by bryk** [comment]
@cheld 

Ok, I'm convinced that we should have consistent behavior everywhere. Hence app name validation should be reverted to default material design behavior.

Can anyone take this issue?

**Comment by digitalfishpond** [comment]
default Material design causes validation on every keystroke. Since local validation cannot be decoupled from async validation, that would cause countless calls to the server... If you want consistency, we can apply debounce 500 everywhere or on-blur everywhere, but I'm not sure default is an option?

**Comment by bryk** [comment]
@digitalfishpond Oh yeah. We need to leave the debounce on name input. This will be an inconsistency we can live with. I saw many other apps that have some inputs debounced and some not .

**Comment by digitalfishpond** [comment]
Ok, I'll take this.

**Comment by cheld** [comment]
Right, I think this small inconsistency is ok. 

BTW: in GCE all input fields validate as you type and all fields have a debounce. For dashboard I would suggest to keep the inconsistency for the moment.

**Comment by digitalfishpond** [comment]
I have done some thorough checking, here are my findings. This issue can probably be closed, so please correct me if I'm wrong.

Fields are already all working with default Material behaviour (except for app name which has a small debounce). 

All fields behave in the following way (which is default to angular Material):

if field is $pristine (never been touched), when you focus in for the first time and enter an invalid input, no error message appears until you focus out.

if field is $touched (has had at least 1 focus and 1 focus-out at some point), validation is instant (or with the specified debounce delay. This is true for all fields on the Deploy page.

PTAL

**Comment by bryk** [comment]
> All fields behave in the following way (which is default to angular Material):
if field is $pristine (never been touched), when you focus in for the first time and enter an invalid input, no error message appears until you focus out.
if field is $touched (has had at least 1 focus and 1 focus-out at some point), validation is instant (or with the specified debounce delay. This is true for all fields on the Deploy page.
PTAL

Correct.

**Comment by bryk** [comment]
Closing. Let me know if should be reopened.
