### ISSUE TITLE
Not Found (404)  v1.16.1

### ISSUE THREAD

**Issue by China-Honey** [kubernetes/dashboard#4497]
##### Environment

```
Installation method:
Kubernetes version: v1.16.1
Dashboard version: v1.10.1
Operating system: centeos 7.6
```

##### Expected result

! Same deployment method, normal operation  v1.14.x  v1.15.x
! Run failed v1.16.x  （Not Found (404)。）
相同的部署方法，v1.14.x  v1.15.x   正常运行. v1.16.x则显示Not Found (404)。

![error](https://user-images.githubusercontent.com/20145158/68011383-1f454880-fcc2-11e9-8423-df6b471cc553.png)

**Comment by floreks** [comment]
This version of Dashboard does not support v1.16

/close

**Comment by tholu** [comment]
@floreks Any plans to support v1.16?

**Comment by floreks** [comment]
v2 does support it
