### ISSUE TITLE
Card should limit the space for labels

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#450]
#### Issue details
If a RC has too many labels, than the space the labels consume is too big. 

##### Steps to reproduce
1. open deploy from settings
2. enter 30 lables and values

##### Observed result
* Card becomes very long
* Layouting works correctly, I think

##### Expected result
Not sure. I think the label are should be limited
![too-many-labels](https://cloud.githubusercontent.com/assets/7448799/13345671/15d8dea4-dc61-11e5-9d56-81c2b5147aa7.png)

**Comment by cheld** [comment]
Enhancement

**Comment by bryk** [comment]
Yeah, you're right. Post 1.0? Seems like non-critical enhancement
