### ISSUE TITLE
Can login with incorrect token

### ISSUE THREAD

**Issue by RalphNeeleman** [kubernetes/dashboard#4503]
```
Installation method: baremetal
Kubernetes version: 1.16
Dashboard version: 2.0
Operating system: Ubuntu
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
- Print token and copy.
- Select in dashboard login with token
- Press space in the field
- Paste token
- Login

Why does this allow you to login? Possible security problem?

##### Observed result
Ability with incorrect token (only if its a space before actual token)

##### Expected result
Not loggin in

**Comment by floreks** [comment]
Your input is trimmed to not contain whitespaces. Token cannot contain them anyway. It's intentional.

/close
