### ISSUE TITLE
Support listing of all the items owned by CustomResource Objects

### ISSUE THREAD

**Issue by xm2** [kubernetes/dashboard#4510]
##### What would you like to be added
CRD and k8s operator pattern become more and more popular these days,  currently k8s dashboard can support listing CR objects under CRD, but it can't support listing all the items(k8s resources, e.g. pods, sts, deployment...) owned by a CR object in CR object detail view. 

It would be great if all the items(k8s objects) owned by a CR object can be grouped together under CR object detail view.  

##### Why is this needed
In some degree, dashboard mainly focused on container infrastructure rather than the application themselves.   

With CRD and k8s operator pattern,  CRD user could map their application to CR(s) + k8s operator(s), if dashboard show all the k8s resources owned by CR object,  CRD user could have a better view about their applications.

##### Comments
Though it's not a standard, it's highly recommended that CRD/operator developer should always fill the owner reference of all k8s objects created/managed by k8s operator, and point owner reference to the CR object who should own them.   
So from implementation perspective, it's possible to get all the items owned by CR object by owner reference info.

**Comment by zehuaiWANG** [comment]
Yes, it is, I agree with you. But for the k8s resource, we are clear about their data structure, so we can parse and display it. For different CRD resources, we can hardly parse because we don't know the yaml/json structure.

**Comment by xm2** [comment]
It's not necessary to parse the CR object spec/status, we could keep it as raw object format.  My point is, can we list all k8s objects whose **owner references** set to CR object under the CR detail view?

**Comment by zehuaiWANG** [comment]
It's easy for us to list the CR object as raw object format. But it's not easy to list all k8s objects whose owner references set to CR object under the each CR detail view, beacuse we have to  parse the CR data struct, and then wu can know what kubernetes resource the CRD uses.

**Comment by xm2** [comment]
OK, I got your point.  

If we don't know what kinds of resource is created by CR,  we may need to get all resources and filter by owner reference, but it's a bad idea, it cost too much.

**Comment by xm2** [comment]
But if performance is the concern, can we add some checkbox/radiobutton/droplist in the view, to let user decide which kind of k8s resources owned by current CR he/she wants to display?  

For example, if user select "Pods" kind in current CR detail view, we get all the pods under current namespace(namespace scoped CR),  filter the Pods by owner reference UID (Pod's metadata.ownerReferences[0].UID == CR's metadata.UID), then display the filtered PodList.

**Comment by zehuaiWANG** [comment]
Yes, but this is a special requirement, and the dashboard is a more general platform, I think the priority of this requirement will be low.

**Comment by grosser** [comment]
FYI ruby script that does this:
```
require 'json'
require 'parallel'

resource_kind, resource_name = ARGV
namespace = ENV["NAMESPACE"]
namespace_option = ("-n #{namespace}" if namespace)
owner_uid = JSON.parse(`kubectl get #{resource_kind} #{namespace_option} #{resource_name} -o json`).dig('metadata', 'uid')

mux = Thread::Mutex.new
apis = `kubectl api-resources #{'--namespaced' if namespace} --verbs list -o name`.split("\n")
Parallel.each(apis, in_threads: 10) do |api|
  JSON.parse(`kubectl get #{api} #{namespace_option} -o json`)['items'].each do |resource|
    next unless resource.dig('metadata', 'ownerReferences')&.any? { |ref| ref['uid'] == owner_uid }
    mux.synchronize do
      puts [api, namespace ? nil : resource.dig('metadata', 'namespace'), resource.dig('metadata', 'name')].compact.join("\t")
    end
  end
end

```
