### ISSUE TITLE
已经测试10组，1master2node 均失败，无法获得token。

### ISSUE THREAD

**Issue by arraycto** [kubernetes/dashboard#4518]
版本
centos :7.x
k8s:v1.16.2
web ui: dashboard 2.0 bete5

安装方式：
二进制安装

网络：
   公司内网，无外网
错误效果：

无法获取token，无法登录
 [root@bigdata001 k8s]# kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep dashboard-admin | awk '{print $1}')
Name:         kubernetes-dashboard-certs
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====

Name:         kubernetes-dashboard-csrf
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
csrf:  0 bytes

Name:         kubernetes-dashboard-key-holder
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
[root@bigdata001 k8s]# 
[root@bigdata001 k8s]# 
[root@bigdata001 k8s]# 
[root@bigdata001 k8s]# 
[root@bigdata001 k8s]# 

已经尝试30+机器，均失败。

**Comment by floreks** [comment]
Provide proper description in english then reopen.

/close
