### ISSUE TITLE
Header is broken in Log page when app name is long.

### ISSUE THREAD

**Issue by f-higashi** [kubernetes/dashboard#452]
#### Issue details

Header is broken in Log page when app name is long.
Contanier selection box, Running label and text color button are hidden.

#### Issue details

Dashboard version: cffd34a90ae4a2334db4f062202f3a00fdf73dc6 ( I used gulp serve:product)
Kubernetes version: v1.1.2
Operating system: Ubuntu 14.0.4
Node.js version: v5.2.0
Go version: 1.5.2
Browser: chrome, firefox, IE

##### Steps to reproduce

1. Create an app with long name
2. Open log page

##### Observed result

![ds_log](https://cloud.githubusercontent.com/assets/8746742/13346596/bc13969e-dcaa-11e5-9921-6f99c6b02321.PNG)

##### Expected result

All components are shown.

**Comment by bryk** [comment]
If we can fix this, I say let's do this for 1.0. @f-higashi Can you come up with a solution?

**Comment by f-higashi** [comment]
sorry. I cannot come up with a good solution right now.

**Comment by bryk** [comment]
Ok, I'll take this.

**Comment by bryk** [comment]
@floreks Works on the same issue in another bug. Closing.
