### ISSUE TITLE
dashboard port

### ISSUE THREAD

**Issue by encrylife** [kubernetes/dashboard#4520]
I modify the dashboard.yaml set targetPort=8442,because 8443 already use,when I kubectl apply -f dashboard.yaml,It not word ,I use curl tool,it print ：‘Error trying to reach service: 'dial tcp 10.244.0.45:8442: connect: connection refused'’，then I use kubectl logs kubernetes-dashboard-784496b896-pwnm7 -n kube-system, the text:2019/11/11 09:42:11 Starting overwatch
2019/11/11 09:42:11 Using namespace: kube-system
2019/11/11 09:42:11 Using in-cluster config to connect to apiserver
2019/11/11 09:42:11 Using secret token for csrf signing
2019/11/11 09:42:11 Initializing csrf token from kubernetes-dashboard-csrf secret
2019/11/11 09:42:11 Empty token. Generating and storing in a secret kubernetes-dashboard-csrf
2019/11/11 09:42:11 Successful initial request to the apiserver, version: v1.16.2
2019/11/11 09:42:11 Generating JWE encryption key
2019/11/11 09:42:11 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2019/11/11 09:42:11 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2019/11/11 09:42:11 Initializing JWE encryption key from synchronized object
2019/11/11 09:42:11 Creating in-cluster Sidecar client
2019/11/11 09:42:11 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
2019/11/11 09:42:11 Auto-generating certificates
2019/11/11 09:42:11 Successfully created certificates
2019/11/11 09:42:11 Serving securely on HTTPS port: 8443,
How can I let it work well

**Comment by floreks** [comment]
This is not a bug. This is a configuration issue. Ask on stackoverflow for support.

PS. You should first understand how kubernetes applications and services work.

/close
