### ISSUE TITLE
Both Role and ClusterRole in ClusterRole

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4527]
![clusterrole](https://user-images.githubusercontent.com/22339920/68656094-23981e00-056c-11ea-8a89-6774217db74b.png)

I found out that there are both cluster roles and role resources in the cluster role part. I am wondering if this setting is reasonable. Because ClusterRole can be used to grant read access to secrets in any particular namespace, or across all namespaces， but Role can only be used to grant access to resources within a single namespace. （According to https://kubernetes.io/docs/reference/access-authn-authz/rbac/）. So in my opinion,  Role resource is not belog to Cluster, so it will be better to have them separately.

By the way, I did not find the corresponding route in the backend code(/api/v1/rbac/role?filterBy=&itemsPerPage=10&name=&namespace=&page=1&sortBy=d,creationTimestamp) , I was wondering if the front end had a layer of routing forwarding. If you have any idea where it is, plz tell me, Thank you.

**Comment by floreks** [comment]
Roles should not be displayed under `Cluster Role` view. They should be under namespaced resources.
