### ISSUE TITLE
what is up ?token is null  dashboard is not 

### ISSUE THREAD

**Issue by arraycto** [kubernetes/dashboard#4529]
errlog  :

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "services"
  },
  "code": 404
}

http://192.168.186.128:8801/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

--------------------------------------------------------------------------------

[root@bigdata001 k8s]# kubectl create clusterrolebinding dashboard-admin --clusterrole=cluster-admin --serviceaccount=kubernetes-dashboard:dashboard-admin
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "dashboard-admin" already exists
[root@bigdata001 k8s]# 
[root@bigdata001 k8s]# kubectl describe secrets -n kubernetes-dashboard $(kubectl -n kubernetes-dashboard get secret | awk '/dashboard-admin/{print $1}')
Name:         kubernetes-dashboard-certs
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====

Name:         kubernetes-dashboard-csrf
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
csrf:  0 bytes

Name:         kubernetes-dashboard-key-holder
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
[root@bigdata001 k8s]#

**Comment by zehuaiWANG** [comment]
clusterrolebindings.rbac.authorization.k8s.io "dashboard-admin" already exists.
plz try `kubectl get clusterrolebinding | grep dashboard-admin`
and plz go to stackoverflow to ask your question, it's not a bug
