### ISSUE TITLE
Insufficient validation for non-ascii chars?

### ISSUE THREAD

**Issue by olekzabl** [kubernetes/dashboard#453]
#### Issue details
Pressing "Deploy" has no effect (as if the form hanged) if many fields contain non-ascii characters. Sometimes an error message is shown, but it's hard to notice (see below).

##### Steps to reproduce
1. Deploy a Containerized App
2. Select "Specify app details below"
3. Description, label key, label value, env-var value: all set to "ąćęłńóśźż 北京市"
  - (if it's not legible, that's nine extended Latin chars followed by a space and three Chinese chars)
4. App name:
  - Case 1: either the same string as above
  - Case 2: "olekz14"
5. Env-var name: set to "strange_string"
  - (I tried the non-ascii string, but here validation worked as desired :) )
6. Click "Deploy"

##### Observed result
- Case 1: 
  - Apparently: nothing happens at all.
  - Actually: A red error message appears beneath the project name, but I don't see it because it's well above the top edge of my 30' screen, and the page is not scrolled up.
- Case 2: Nothing really happens at all.

##### Expected result
- Always display an error message next to the appropriate field,

and, moreover,
- Either scroll the page up, or display an additional error message somewhere at the bottom of the page.

**Comment by digitalfishpond** [comment]
The error message actually appears on focus-out from any field, long before the Deploy button is reached.
Additional feature of auto-scroll-up could be introduced if any errors remain when DEPLOY button is pressed. @bryk @cheld, what do you think?

**Comment by cheld** [comment]
Actually, I was tempted to create the same issue. During testing I stumble over the problem myself. However, I thought it is a problem that will occur most likely only during testing, but not so much in production. 
A scroll-up on clicking deploy would be nice. I consider it as enhancement. Some Gmail pages also do not scroll up on validation errors (but the pages are not long).

**Comment by bryk** [comment]
The simplest, we could show error message next to deploy button something like "The form contains errors, please fix them". This would tell user what to do. 

The autoscroll solution seems nice, but I think it will be much harder to implement. 

What do you think?

**Comment by digitalfishpond** [comment]
Also happy to implement this as a P2?

**Comment by olekzabl** [comment]
@digitalfishpond "The error message actually appears on focus-out from any field, long before the Deploy button is reached."

I checked once more and I cannot see such message in my case. (Goobuntu; Chrome 48.0 64-bit; no "node"; if other config info is relevant, please tell me how to obtain it).

**Comment by digitalfishpond** [comment]
Thank you @olekzabl, you are right, those fields still don't have complete validation implemented. I will fix today. :)
