### ISSUE TITLE
Where is HPA view in Dashoard 2.x version ?

### ISSUE THREAD

**Issue by anwarchk** [kubernetes/dashboard#4540]
We can't seem to find the HPA details in 2.x release. I checked the release notes to see if it was removed, but didn't see any mention of it.

**Comment by floreks** [comment]
It is indeed missing. We've missed that one during rewriting Dashboard. Nice catch.

**Comment by anwarchk** [comment]
Thank you @floreks I thought it was just me :-)

**Comment by anwarchk** [comment]
There is code to handle the path, so just UI toggle is missing I guess, haven't looked in detail:
`
apiV1Ws.Route(
        apiV1Ws.GET("/horizontalpodautoscaler").
            To(apiHandler.handleGetHorizontalPodAutoscalerList).
            Writes(horizontalpodautoscaler.HorizontalPodAutoscalerList{}))
    apiV1Ws.Route(
        apiV1Ws.GET("/horizontalpodautoscaler/{namespace}").
            To(apiHandler.handleGetHorizontalPodAutoscalerList).
            Writes(horizontalpodautoscaler.HorizontalPodAutoscalerList{}))
    apiV1Ws.Route(
        apiV1Ws.GET("/horizontalpodautoscaler/{namespace}/{horizontalpodautoscaler}").
            To(apiHandler.handleGetHorizontalPodAutoscalerDetail).
            Writes(horizontalpodautoscaler.HorizontalPodAutoscalerDetail{}))
`

**Comment by maciaszczykm** [comment]
We have an issue for that already https://github.com/kubernetes/dashboard/issues/3867.
