### ISSUE TITLE
Header field name and value are not aligned in log page.

### ISSUE THREAD

**Issue by f-higashi** [kubernetes/dashboard#455]
#### Issue details

Header field name and value are not aligned in logs page.

##### Environment

Dashboard version: cffd34a90ae4a2334db4f062202f3a00fdf73dc6 ( I used gulp serve:product)
Kubernetes version: v1.1.2
Operating system: Ubuntu 14.0.4
Node.js version: v5.2.0
Go version: 1.5.2
Browser: IE

##### Steps to reproduce

1. Open Log page

##### Observed result

![ds_log1](https://cloud.githubusercontent.com/assets/8746742/13349408/f775416c-dcbc-11e5-8a10-9728d3d78a96.png)

##### Expected result

Header field name and value are aligned in log page.

![ds_log2](https://cloud.githubusercontent.com/assets/8746742/13349434/252465e8-dcbd-11e5-889f-c5728a92e573.PNG)

**Comment by maciaszczykm** [comment]
Working on it.
