### ISSUE TITLE
Unable to get resource information

### ISSUE THREAD

**Issue by wzxmt** [kubernetes/dashboard#4555]
##### Environment

```
Installation method:no
Kubernetes version:1.16.2
Dashboard version:Dashboard V2.0-beta6
Operating system:linux 7
Node.js version ('node --version' output):no
Go version ('go version' output): no
```

##### Steps to reproduce

I have some problems, install the dashboard: v2.0.0-beta6 successfully, can enter the web page, but can't see any information, the page displays "There is nothing to display here", the alarm prompt "events is forbidden: User "system :serviceaccount:kubernetes-dashboard:default" cannot list resource "events" in API group  in the namespace "default"
Before
Error
Pods is forbidden: User "system:serviceaccount:kubernetes-dashboard:default" cannot list resource "pods" in API group "" in the namespace "default"
Before
Error
##### Observed result
How can I configure it? My user rights are configured as follows:
apiVersion: v1
Kind: ServiceAccount
Metadata:
  Labels:
    K8s-app: kubernetes-dashboard
  Name: dashboard-admin
  Namespace: kubernetes-dashboard

apiVersion: rbac.authorization.k8s.io/v1
Kind: ClusterRoleBinding
Metadata:
  Name: dashboard-admin-bind-cluster-role
  Labels:
    K8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  Kind: ClusterRole
  Name: cluster-admin
Subjects:

- kind: ServiceAccount
  Name: dashboard-admin
  Namespace: kubernetes-dashboard
##### Expected result

**Comment by floreks** [comment]
This is a configuration issue, not a bug. You have logged in with user that has no access to certain resources. For configuration issues try stackoverflow. We don't have time to provide support for such issues here. Also there are dozens of already closed issues related to the same thing. Check it first.

/close
