### ISSUE TITLE
Error scraping node metrics: the server is currently unable to handle the request 

### ISSUE THREAD

**Issue by vinothkumar437** [kubernetes/dashboard#4557]
<pre>
{"level":"error","msg":"Error scraping node metrics: the server is currently unable to handle the request (get nodes.metrics.k8s.io)","time":"2019-11-16T13:34:18Z"}
<pre>

please help me to resolve the issue

**Comment by floreks** [comment]
This error is from metrics scraper. It has its own repo. Also you need to install metrics server first in the cluster to make it work.

/close

**Comment by sovereignoshan** [comment]
kubectl top pods
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods.metrics.k8s.io)
