### ISSUE TITLE
Stylesheet issues on Safari

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#456]
##### Environment

```
Dashboard version: latest
Kubernetes version: latest
Operating system: OS X 10.11.3 (15D21)
Node.js version: 4.2.2
Go version: 1.5.1
```

##### Steps to reproduce

1. Run Dashboard on environment described above.
2. Deploy at least one application.
3. Go to replication controller list view.

##### Observed result

<img width="1919" alt="screenshot at lut 28 12-30-44" src="https://cloud.githubusercontent.com/assets/2823399/13378949/810331ea-de17-11e5-9035-e45e56fd45d1.png">

##### Expected result

Page displays correctly.

##### Comments
Is Safari supported browser?

**Comment by bryk** [comment]
I cannot reproduce on my mac. The UI works as expected. I have many RCs, though.

**Comment by maciaszczykm** [comment]
I'll check it once more later. When I was doing this test everything worked on Chrome, but not on Safari. That's why I've created this issue.

**Comment by bryk** [comment]
Safari works for me. Please reopen if the issue persists.
