### ISSUE TITLE
I am wondering if the following apis is useless?

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4578]
I am wondering that if the code `handleCreateNamespace` and `handleCreateImagePullSecret` in apihandler is useless, because we use `appdeploymentfromfile` to create namespace and other resource, and I can not find anywhere use these apis in the front-end UI also. Should we remove it?

**Comment by maciaszczykm** [comment]
This seems to be used for example in`CreateNamespaceDialog`. Verify it next time before trying to delete something.

**Comment by maciaszczykm** [comment]
Even if it would be not used we should rather implement a UI for it instead of deleting it.

**Comment by zehuaiWANG** [comment]
okay, thank you~
