### ISSUE TITLE
After the dashboard is in the background for some time the page becomes unresponsive

### ISSUE THREAD

**Issue by zerkms** [kubernetes/dashboard#4594]
##### Environment

```
Installation method: recommended manifests
Kubernetes version: 1.16.3
Dashboard version: v2.0.0-beta6
Operating system: ubuntu 18.04
Node.js version ('node --version' output): n/a
Go version ('go version' output): n/a
```

##### Steps to reproduce

Open pods page of non-empty namespace, eg kube-system.
Switch to the other tab and do your normal work. Then about 10-15 minutes later switch back and see the white screen, while the google chrome consumes 100% for this very tab and asks whether you want to terminate the unresponsive page.

##### Observed result

It should not happen.

##### Expected result

It happens

**Comment by floreks** [comment]
True. The current graph library seems to cause a memory leak and high cpu usage. We have to change it.
