### ISSUE TITLE
Make it easy to spin up a cluster for development/integration tests/CI

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#46]
The project should have a script or a Gulp task that spins up a minimalist Kubernetes cluster, which later can be used for development, integration tests or continuous integration.

**Comment by bryk** [comment]
@gmarek @wojtek-t Do you have any hints for setting up a dev cluster easily & quickly?

**Comment by bryk** [comment]
@zreigz Can you take this?

**Comment by wojtek-t** [comment]
There is a script to start a light version locally:

    ./hack/local-up-cluster.sh

Is that what you want?

**Comment by gmarek** [comment]
I was just going to write the same thing:). If you want 'real' one, you can just use your GCE project and and use `cluster/kube-up.sh`

**Comment by bryk** [comment]
I'm thinking about a Kubernetes cluster that can be used on, e.g., CI for test. `./hack/local-up-cluster.sh` looks like exactly what we need. Thank you! 

I'll let @zreigz figure out how to integrate it with this project.

**Comment by wojtek-t** [comment]
Also, if you need something for integration tests - you can take a look how we are running integration tests. We already have some framework for it (maybe you can easily extend it for you purpose).
Take a look at:
- test/integration/framework (for framework implementation)
- test/integration/*_test.go (to see how it is used)

**Comment by gmarek** [comment]
To give you some more details - in integration tests we're locally running master components together with mocked "SimpleKubelets". As long as you need just information from etcd (i.e. no information from nodes) it should be enough.

**Comment by wojtek-t** [comment]
>
To give you some more details - in integration tests we're locally running master components together with mocked "SimpleKubelets". As long as you need just information from etcd (i.e. no information from nodes) it should be enough.

That's not entirely true IIUC - we are really starting pods on those SimpleKubelets there, so you have some data on nodes too.

**Comment by gmarek** [comment]
Nope. AFAICK It uses `FakeDockerClient`, even simpler than one that Kubemarks one.

**Comment by zreigz** [comment]
I can take this. My concept is use something similar what is done in
installation script: https://get.k8s.io but use gulp a specially gulp-exec
to execute some commands for downloading, retrieving latest version and
creating cluster (./hack/local-up-cluster.sh). When cluster will be created
we can access to master node also using gulp-ssh. When this part will be
done then we can thing for other stuff like CI.

**Comment by bryk** [comment]
@zreigz  Nice! I think all we need is access to the apiserver, e.g., its port and host like http://localhost:8080. With that the UI can connect to it and perform actions. No SSHing into nodes is needed.

**Comment by zreigz** [comment]
Ok, so first I will focus to set up cluster. When it will be ready then we
think about rest of it.

**Comment by cheld** [comment]
Is the CI supposed to run against a local cluster or a real cluster?

**Comment by bryk** [comment]
Yes, the CI is supposed to start a local cluster, then start the UI and finally perform integration tests on this environment. This yields in a reproducable build and test setup which can be used on CI and on developer's local machine. We want to get as productive as possible.

Connecting to an external ("real") cluster is, of course, doable. This may be, e.g., a staging cluster. We do not have resources to maintain such setup ATM, however.

**Comment by floreks** [comment]
We've got pretty good setup for tests/dev now. I think we can close.
