### ISSUE TITLE
How Kubernetes dashboard calculates the pod utilization?

### ISSUE THREAD

**Issue by udit0612** [kubernetes/dashboard#4602]
I installed Kubernetes dashboard but I am confused how pod utilization is calculated

I have metrics server installed on my cluster from that I can get the pod utilization
like
```
kubectl top pods -n kubernetes-dashboard
NAME                                         CPU(cores)   MEMORY(bytes)
dashboard-metrics-scraper-76585494d8-vnwhq   7m           8Mi
kubernetes-dashboard-b65488c4-w57n2          24m          34Mi
```

![image](https://user-images.githubusercontent.com/33015983/69621783-bf925100-1065-11ea-8014-bff1b26af841.png)

I don't understand one thing from how much value it got the CPU utilization of 7m and memory utilization of 8Mi?

I would be glad if you share me the formula for calculation of GitHub code for that

**Comment by floreks** [comment]
We do not calculate anything, we take raw data from metrics server and it is a separate project not related to Dashboard.

**Comment by udit0612** [comment]
Can you please share the documentation link
In my case, some pod occupies 1m of space but utilization graph reach to 100%
Whereas in some other cases 40m also less than 25%

**Comment by floreks** [comment]
Sparklines are not scaled to 100% because pod can use more than a single core and then it would in example use 1.5 core which is 1500m and in theory 150%. Trend line is only there to see usage over time, not overall usage.

Metric unit explanation is somewhere in Kubernetes core documentation. I don't have time right now to look for it.

**Comment by udit0612** [comment]
[spec.containers[].resources.requests.cpu of 0.5 is guaranteed half as much CPU as one that asks for 1 CPU. The expression 0.1 is equivalent to the expression 100m, which can be read as “one hundred millicpu”. Some people say “one hundred millicores”, and this is understood to mean the same thing. A request with a decimal point, like 0.1, is converted to 100m by the API, and precision finer than 1m is not allowed. For this reason, the form 100m might be preferred.](url)
I got that documentation but I still not able to figure out the actual pod resource usage of an individual pod because its vary from pod to pod

**Comment by floreks** [comment]
> not able to figure out the actual pod resource usage of an individual pod because its vary from pod to pod

That is normal. Processes in your system also have different resource consumption. I don't really get what more do you need.

**Comment by udit0612** [comment]
I simply need to calculate the CPU and memory percentage of individual pod 
![image](https://user-images.githubusercontent.com/33015983/69631929-7269ab80-1074-11ea-87b7-75cf4bdf36a6.png)

Look at the above four graphs according to you 1000m = 100% of pod utilization
as you see in the graph  the container which consumes 1m also has 100% and 4m also have less than 100% of utilization


How is it possible?

**Comment by floreks** [comment]
Did you read my previous post?

> Sparklines are not scaled to 100% because pod can use more than a single core and then it would in example use 1.5 core which is 1500m and in theory 150%. **Trend line is only there to see usage over time, not overall usage.**

Metrics server only provides information about current usage in millicores, not `%`. We do not have information about available resources. 

Once again **trend line is there ONLY to show USAGE OVER TIME, not current usage**. It scales to the highest usage for the given period of time.

If you want to calculate actual usage you need to know how many cores there are on the node that pod is running.

((current pod usage) / (1000m * (number of cores))) * 100%

**Comment by jaishirole** [comment]
@floreks I have found your responses very useful. Thanks!
