### ISSUE TITLE
Login dashboard but did't validate my input value

### ISSUE THREAD

**Issue by 348786639** [kubernetes/dashboard#4617]
I use token to login，and i input token value，but did't validate my input value。
e.g (i input '12346' to succeed)

why the correct token is 'eyJhbGciOiJSUzI1NiIsImtpZCI6I...' but i input '123456' success login???

**Comment by floreks** [comment]
This can only happen if your cluster is not configured properly. We do not validate token on our side. It's the API server that does that. If it accepts the token then we proceed to the overview.

Closing as this is a cluster configuration issue.

/close
