### ISSUE TITLE
Unable to access dashboard with NodePort HTTP  service on master-ip:node-port

### ISSUE THREAD

**Issue by MaheshBFattepur** [kubernetes/dashboard#4618]

**Comment by MaheshBFattepur** [comment]
I have followed the same steps given in repo readme. 
1. Deployed dashboard in kube-system namespace
2. Used the sample rbac yaml files and ran  in kubernetes-dashboard namespace
3. kubectl proxy --address <master-ip> --port=8080 -accept-hosts="^*$"
4. http://master-ip:port/......
5. Entered token but doesn't open anything.?????

**Comment by floreks** [comment]
Use search and read documentation. It was already explained many many times.
