### ISSUE TITLE
image: kubernetesui/dashboard:v2.0.0-beta6 hangs on chrome on linux

### ISSUE THREAD

**Issue by 1robroos** [kubernetes/dashboard#4629]
##### Environment

```
Installation method:
Kubernetes version: EKS 1.13
Dashboard version: kubernetesui/dashboard:v2.0.0-beta6
Operating system: Chrome Version 78.0.3904.108 (Official Build) (64-bit)  on UBuntu 18.04.3 LTS 
Node.js version ('node --version' output): v8.10.0
Go version ('go version' output): go1.12.5 linux/amd64
```

##### Steps to reproduce
Opening the dashboard is okay. Wait for a few minutes and the screen seems to hang. 

##### Observed result
Hoover over items does not change the mouse cursor anymore. Sometimes waiting a while results in psotive responsiveness, but most of the times the chrome tab hangs and pushing refresh takes a very long time before the tab is usable again.

##### Expected result
Working dashboard without hanging.

##### Comments
I reverted back to beta4, which seems to work. Small drawback is that for some namespaces the cpu/ram metrics are not shown with this version.

**Comment by floreks** [comment]
Already fixed on master. Dupliate of https://github.com/kubernetes/dashboard/issues/4594

/close
