### ISSUE TITLE
page slows down (high cpu usage) and freezes after a while when metrics are enabled

### ISSUE THREAD

**Issue by peterholak** [kubernetes/dashboard#4631]
##### Environment

```
Installation method: kubectl apply that link from the kubernetes docs
Kubernetes version: 1.16.0
Dashboard version: 2.0.0-beta6
Operating system: Windows 10 (browser running there, Chrome 78)
```

##### Steps to reproduce
- have 2.0.0-beta6 installed, refresh set to the default 5 seconds
- open the Pods page on a namespace with a number of pods (mine has 11) - verify that the CPU/memory metrics are visible
- go to another tab, keep the dashboard tab in background
- open the Chrome Task Manager (Shift+Esc, or from menu) to keep an eye on memory usage
- browse other websites in other tabs for 10 minutes or so (doesn't matter whether login session expires or not)
- go back to the dashboard tab

##### Observed result
- the page takes a long time to "unfreeze", with cpu of the tab at or over 100% the whole time (according to Chrome Task Manager)
- memory usage almost immediately jumps from ~350MB (depending on content, etc.) to 900MB+ (sometimes over 1.5GB), and stays much higher than it was before for the rest of the session
- every interaction on the page (clicking, scrolling) becomes incredibly slow, tab CPU usage is at 100%, eventually it becomes completely unresponsive
- have to close the tab and open a new one to resume normal operation

##### Expected result
- the page should work normally, regardless of being in the background for a while

##### Comments
I can attach the recorded JS profile from Chrome after I check there is no sensitive data in it, but it is quite easy to reproduce. Basically it's all layout/drawing stuff and GC from what I can tell.

When I disable the metrics (by scaling the dashboard-metrics-scraper deployment to 0), the problem goes away. Having the charts there also severely degrades performance even during normal use.

**Comment by floreks** [comment]
Already fixed on master. Duplicate.

/close
