### ISSUE TITLE
ANSI Support Missing in Logs

### ISSUE THREAD

**Issue by lawrencedudley** [kubernetes/dashboard#4632]
##### Environment
Kubernetes 1.16, Dashboard v2.0.0-beta6+0.g3175ce8

##### Steps to reproduce
View some logs that contain ANSI colours

##### Observed result
[94mSite:                         [0m [35muptime                        [0m
[94mBranch:                       [0m [35mmaster                        [0m
[94mEnvironment:                  [0m [35mproduction                    [0m
[94mPHP Version:                  [0m [35m7.2.17                        [0m
[94mAtatus:                       [0m [35mEnabled                       [0m
[94mAtatus Laravel Queues:        [0m [35mEnabled                       [0m
[94mPHP Memory Max:               [0m [35m128M                          [0m
[94mPHP Max Input Vars:           [0m [35m1000                          [0m
[94mPHP Opcache:                  [0m [35mEnabled                       [0m
[94mOpcache Memory Max:           [0m [35m16M                           [0m
[94mPHP Max Execution Time:       [0m [35m32                            [0m
[94mPHP-FPM Max Workers:          [0m [35m8                             [0m
[94mPHP Short Tags:               [0m [35mDisabled                      [0m
[94mMAIL_HOST:                    [0m [35mmaster-smtp.smtp-production   [0m
[94mMAIL_PORT:                    [0m [35m25                            [0m
[94mMAIL_DRIVER:                  [0m [35mmail                          [0m
[94mMAIL_DRIVER:                  [0m [35mmail                          [0m
[04-Dec-2019 13:47:52] NOTICE: fpm is running, pid 50
[04-Dec-2019 13:47:52] NOTICE: ready to handle connections

##### Expected result
The old dashboard parses ANSI colours, this just looks messy :(

**Comment by floreks** [comment]
We are using a different shell library now. The old one had some bugs that weren't addressed by the creators for a long time. We can look into it and see if there is an option to enable support for that. This is very low priority though.

**Comment by lawrencedudley** [comment]
I know it's not the most exciting thing in the world but it really helps clean up log output :)

**Comment by LSmyrnaios** [comment]
Hi, I'm also interested in this change.

It seems that the colors are per-configured to "black" and "white" to support the "Invert colors"-option.

[style.scss](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/logs/style.scss)

**Comment by greggbjensen** [comment]
I have completed a pull request for this change.

#4963
