### ISSUE TITLE
Can I use 2.0-beta6 on K8s 1.14?

### ISSUE THREAD

**Issue by keattang** [kubernetes/dashboard#4634]
Hi, 

I've just upgraded to K8s 1.14 (the latest that EKS allows) and it looks like I need to upgrade to dashboard 2.0 for a compatible version. I am currently running `beta1` as that's the only one that has full K8s 1.14 support. I notice that the later versions only have partial support. 

It seems like there have been a lot of improvements since `beta1`. Should I be sticking to `beta1` or is it ok to upgrade to `beta6`?  How broken is `beta6` on K8s 1.14?

Will dashboard 2.0 have full compatibility with K8s 1.14 when it's out of beta?

Sorry for posting here if this is not the right place. I looked in the slack group and there didn't seem to be an appropriate channel to ask in.

Thanks in advance

**Comment by jmriebold** [comment]
I've been running the most recent beta on K8s 1.14 and it seems to work fine, though I didn't use beta 1, so I can't say for sure if there have been any regressions.

**Comment by floreks** [comment]
`beta6` should mostly work with K8S v1.14, however not all functionalities have to work. For sure, CRD's will not be displayed properly. `beta7` will add CRD support for `v1beta1` API used by K8S up to v1.15. `beta6` supports only `v1` CRD API. I am not aware of any other issues.

Always check out the compatibility matrix that every release has to make sure how it looks like for your K8S version. 

https://github.com/kubernetes/dashboard/releases

/close
