### ISSUE TITLE
Environment variables specified via `envFrom` change position on page every few seconds

### ISSUE THREAD

**Issue by peterholak** [kubernetes/dashboard#4638]
##### Environment

```
Installation method: kubectl apply link from the docs
Kubernetes version: 1.16.0
Dashboard version: 2.0.0-beta7
```

##### Steps to reproduce
- Apply https://gist.github.com/peterholak/df19c286a205c16583397c739fc15955 into the cluster (pod that has its own 3 env. variables + 3 from a ConfigMap added via envFrom)
- Go to the page of the created `env-var-bug` Pod
- Look at the environment variable section for a while

##### Observed result
The position of the ConfigMap/envFrom variables changes. The position of the variables defined directly on the Pod stays the same.

##### Expected result
The position of all variables should stay the same.

##### Comments
Probably similar to https://github.com/kubernetes/dashboard/issues/4296, but only affects the envFrom variables, and still occurs in 2.0.0-beta7.

**Comment by floreks** [comment]
I can confirm that this happens for `envFrom` variables, but not regular `env` vars. Probably the `trackBy` id is not unique for them.
