### ISSUE TITLE
The dashboard has uses excessive memory over time

### ISSUE THREAD

**Issue by RubenAtPA** [kubernetes/dashboard#4640]
On our local development machine we use a single node kubernetes cluster with minikube. This cluster can be tracked with the default kubernetes dashboard. When this dashboard is active for a long period of time (in my use case it was for about 12 to 16 hours), the memory usage sky-rockets over time ending up with using 12G just before I closed the page. I think there might be an issue with javascript objects not being cleaned-up properly.

We use minikube installed on the Windows host machine and the kubectl gcloud binary installed on the Ubuntu WSL system and configured to use the cluster created by minikube.

**OS:** Windows 10 Pro
<details>

**Version:** 1903
**Build:** 18362.476
**WSL version:** 1
**WSL client:** Ubuntu 19.04

</details>

**Browser:** Chrome 
<details>

**Version:** 78.0.3904.108

</details>

**Kubernetes client version:** 1.13
<details>

**Major:** 1,
**Minor:** 13+,
**GitVersion:** v1.13.9-2+4a03651a7e7e04,
**GitCommit:** 4a03651a7e7e04a0021b2ef087963dfb7bd0a17e,
**GitTreeState:** clean,
**BuildDate:** 2019-08-16T18:57:20Z,
**GoVersion:** go1.11.5,
**Compiler:** gc,
**Platform:** linux/amd64

</details>

**Kubernetes server version:** 1.16
<details>

**Major:** 1,
**Minor:** 16,
**GitVersion:** v1.16.2,
**GitCommit:** c97fe5036ef3df2967d086711e6c0c405941e14b,
**GitTreeState:** clean,
**BuildDate:** 2019-10-15T19:09:08Z,
**GoVersion:** go1.12.10,
**Compiler:** gc,
**Platform:** linux/amd64

</details>

**Minikube version:** 1.5.2 
<details>

**commit:** 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty

</details>

**Comment by floreks** [comment]
Fixed in https://github.com/kubernetes/dashboard/releases/tag/v2.0.0-beta7

> Use ngx-charts to display graphs, workload statuses and allocations charts to fix high memory/cpu usage issues

/close

**Comment by RubenAtPA** [comment]
The issue is closed because of the new dashboard version, yet I have left the dashboard open overnight and it consumed over 6GB in memory on it's own. I think the memory leak issue hasn't been resolved completely yet. Can this be reopend?

**Comment by floreks** [comment]
I haven't experienced any memory spikes after leaving dashboard tab open on overview after 1h. Memory usage was 200mb. Make sure you are using latest beta.

**Comment by RubenAtPA** [comment]
I am currently using Dashboard v2.0.0-beta8+0.g4275399 (latests as far as I can see) on Chrome 79.0.3945.88. My dashboard provides information about 12 deployments (all containing a single pod, service and replicaset), 7 config maps, 6 PVC's, 5 secrets and 1 ingress. After one hour the memory usage is not too much, but when I have it running over night, the following day it has spiked into the multiple GB's.

**Comment by floreks** [comment]
I'll check it on our cluster.
