### ISSUE TITLE
v2.0.0-beta8 The ClusterRoleBinding "kubernetes-dashboard" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"kubernetes-dashboard"}: cannot change roleRef

### ISSUE THREAD

**Issue by fullstackwebdev** [kubernetes/dashboard#4642]
```
: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"kubernetes-dashboard"}: cannot change roleRef
```
##### Environment
Kubernetes version: v1.16.3:

```
Installation method:
Kubernetes version: Kubernetes version: v1.16.3:
Dashboard version: 2.0.0-beta8
Operating system: Ubuntu 18.04
Node.js version ('node --version' output): nvm/12
Go version ('go version' output): Not installed
```

##### Steps to reproduce

 kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml

##### Observed result
```
namespace/kubernetes-dashboard unchanged
serviceaccount/kubernetes-dashboard unchanged
service/kubernetes-dashboard unchanged
secret/kubernetes-dashboard-certs unchanged
secret/kubernetes-dashboard-csrf configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
secret/kubernetes-dashboard-key-holder configured
configmap/kubernetes-dashboard-settings unchanged
role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
deployment.apps/kubernetes-dashboard unchanged
service/dashboard-metrics-scraper unchanged
deployment.apps/dashboard-metrics-scraper unchanged
The ClusterRoleBinding "kubernetes-dashboard" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"kubernetes-dashboard"}: cannot change roleRef
```

##### Comments

Related? 

https://stackoverflow.com/questions/59020654/the-clusterrolebinding-kubernetes-dashboard-is-invalid-roleref-invalid-valu

**Comment by floreks** [comment]
You should delete Dashboard related resources before upgrading or only edit deployment to bump image version. 

/close

**Comment by jeanpoelie** [comment]
Would be usefull to give the command used to delete as well :)

**Comment by shreyansh-zazz** [comment]
I have deleted the resources and still facing the same issue. Though I am using minikube on local machine.

**Comment by zaneclaes** [comment]
This issue occurs if a user simply follows the instructions in the current `master` documentation to enable admin access. If you first apply `reccomended.yaml` and then [follow the admin instructions](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#admin-privileges) it appears.

**Comment by joeczucha** [comment]
In case it's useful for anyone, I needed to run this command: `kubectl delete clusterrolebinding kubernetes-dashboard` to stop the error appearing.

**Comment by marcusjwhelan** [comment]
@joeczucha  that did not stop the issue from appearing even after deleting the kubernetes-dashboard namespace

**Comment by kondalonline** [comment]
> In case it's useful for anyone, I needed to run this command: `kubectl delete clusterrolebinding kubernetes-dashboard` to stop the error appearing.

Thanks you Joe. It worked well for me

**Comment by os** [comment]
> Would be usefull to give the command used to delete as well :)

You can just run `kubectl delete` using the YAML file that you've used to create the previous Kubernetes dashboard resources like `kubectl delete -f <your-yaml-file-here>` and then run `kubectl apply` and use the new YAML file.
