### ISSUE TITLE
"Delete replication controller" button too verbose

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#465]
The button is very verbose. Perhaps we should rename it to "delete" and better indicate that this page is about RCs (if this confuses users). 

![selection_036](https://cloud.githubusercontent.com/assets/1159999/13401805/ed3e1496-df0d-11e5-9feb-88e991f14868.png)

@floreks @cheld @maciaszczykm

**Comment by cheld** [comment]
I think delete is obvious enough. You will get a pop-up anyway.

(In terms of UX, the button is slightly floating in open space. On the RC list page it is more obvious what you are deleting. E.g., placing the button next to the title "Replication controller" might be better. Anyway, I would not change anything)

**Comment by bryk** [comment]
I'll take it.
