### ISSUE TITLE
Improve plugin error logging

### ISSUE THREAD

**Issue by anshulahuja98** [kubernetes/dashboard#4654]
##### What would you like to be added
The errors for plugin should be more descriptive

##### Why is this needed
Facing issues while debugging the plugins

#4583

**Comment by ajatprabha** [comment]
Yes, error reporting could be more specific. Are you working on a PR, or should I take it up?

**Comment by anshulahuja98** [comment]
One thing I was planning to atleast add was
https://github.com/kubernetes/dashboard/blob/04a91c45b611d36c832d10ecc1519fe095e0f1f6/src/app/frontend/plugin/holder.ts#L56

Adding `console.log(e)` over here
it helped me to basically debug a bit

Otherwise, I don't have any specific ideas as of now, I am exploring the plugin related code as of now, I'll send PRs if I come across anything
