### ISSUE TITLE
Dashboard v2 can't get metrics (but kubectl top xxx works)

### ISSUE THREAD

**Issue by funkypenguin** [kubernetes/dashboard#4658]
##### Environment

```
Installation method:
Kubernetes version: 1.16.2
Dashboard version: v2.0.0-beta8
Operating system: CentOS 7
```

##### Steps to reproduce

1. Install metrics-server using https://github.com/helm/charts/tree/master/stable/metrics-server
2. Install kubernetes dashboard v2 using this adapted helm chart : https://github.com/funkypenguin/helm-kubernetes-dashboard (AFAIK, the "official" helm chart is not yet updated for v2)
3. Confirm it's possible to gather metrics using the Kube API, by running `kubectl top nodes`

##### Observed result

1. Dashboard shows expected information, but per-pod CPU/memory metrics are missing.
2. Dashboard logs show either:

```
2019/12/12 21:26:35 Getting pod metrics
2019/12/12 21:26:35 Internal error occurred: No metric client provided. Skipping metrics.
```

Or:

```
2019/12/12 21:31:11 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
```

##### Expected result

Dashboard correctly displays CPU/memory usage graphs per-pod

##### Comments

The metrics-scraper pod is logging the following, which leads me to believe that it's functioning normally (i.e., it has the necessary RBAC etc to scrape metrics).

```
192.168.33.24 - - [12/Dec/2019:21:33:38 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
192.168.33.24 - - [12/Dec/2019:21:33:48 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
{"level":"info","msg":"Database updated: 7 nodes, 205 pods","time":"2019-12-12T21:33:58Z"}
192.168.33.24 - - [12/Dec/2019:21:33:58 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
192.168.33.24 - - [12/Dec/2019:21:34:08 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
```

**Comment by benmyb** [comment]
Do you add ` - --kubelet-insecure-tls` in your metrics server values.yaml? Like this:
```
args: 
# enable this if you have self-signed certificates, see: https://github.com/kubernetes-incubator/metrics-server
 - --kubelet-insecure-tls
```

**Comment by funkypenguin** [comment]
I've tried with and without `--kubelet-insecure-tls` - no difference. 

It's worth pointing out that this works:

```
root@cn1:~# kubectl top nodes
NAME                     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
mn1.kube-cluster.local   516m         6%     4494Mi          28%
mn2.kube-cluster.local   611m         7%     4456Mi          28%
mn3.kube-cluster.local   837m         10%    4911Mi          31%
wn1.kube-cluster.local   2328m        19%    22915Mi         35%
wn2.kube-cluster.local   1157m        9%     16994Mi         26%
wn3.kube-cluster.local   2773m        23%    20819Mi         32%
wn4.kube-cluster.local   3427m        28%    17151Mi         26%
root@cn1:~#
```

**Comment by floreks** [comment]
I'd say that it's either faulty helm chart or cluster config issue. Dashboard can't connect to the metrics scraper. Metrics server is working fine.

**Comment by funkypenguin** [comment]
Could be helm chart - I modified the original helm chart for v1. Any ideas where to start re why dashboard can't connect to scraper?

**Comment by floreks** [comment]
I'd just use our official deployment methods. We do not really support anything else. Debugging app to app connectivity is a different issue. Official K8S docs can help you debug that. It's not really a Dashboard issue.

**Comment by laurencee** [comment]
@floreks 
I actually have this issue with the official deployment method, currently using v2.0.0-rc3.

The kubectl top nodes and top pods commands both return expected results but the dashboard does not display any values for any CPU/Memory usage and the top graph/chart section that usually shows cpu/memory graphs is missing:

```
$ kubectl top pods -n kubernetes-dashboard
NAME                                         CPU(cores)   MEMORY(bytes)
dashboard-metrics-scraper-7b8b58dc8b-t9kx5   1m           8Mi
kubernetes-dashboard-7867cbccbb-vk2nt        1m           13Mi
```

![image](https://user-images.githubusercontent.com/3850553/73504592-a4541100-441b-11ea-91ef-491089391cd4.png)

The dashboard and scraper logs dont seem to show anything interesting.
```
10.244.1.1 - - [31/Jan/2020:01:19:22 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
{"level":"info","msg":"Database updated: 3 nodes, 24 pods","time":"2020-01-31T01:19:29Z"}
10.244.1.1 - - [31/Jan/2020:01:19:32 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.244.0.26 - - [31/Jan/2020:01:19:33 +0000] "GET /healthz HTTP/1.1" 200 13 "" "dashboard/v2.0.0-rc3"
10.244.1.1 - - [31/Jan/2020:01:19:42 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.244.1.1 - - [31/Jan/2020:01:19:52 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.244.1.1 - - [31/Jan/2020:01:20:02 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.244.0.26 - - [31/Jan/2020:01:20:03 +0000] "GET /healthz HTTP/1.1" 200 13 "" "dashboard/v2.0.0-rc3"
10.244.1.1 - - [31/Jan/2020:01:20:12 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
10.244.1.1 - - [31/Jan/2020:01:20:22 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
{"level":"info","msg":"Database updated: 3 nodes, 24 pods","time":"2020-01-31T01:20:29Z"}
10.244.1.1 - - [31/Jan/2020:01:20:32 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
```

```
2020/01/31 01:07:33 Starting overwatch
2020/01/31 01:07:33 Using namespace: kubernetes-dashboard
2020/01/31 01:07:33 Using in-cluster config to connect to apiserver
2020/01/31 01:07:33 Using secret token for csrf signing
2020/01/31 01:07:33 Initializing csrf token from kubernetes-dashboard-csrf secret
2020/01/31 01:07:33 Empty token. Generating and storing in a secret kubernetes-dashboard-csrf
2020/01/31 01:07:33 Successful initial request to the apiserver, version: v1.16.4
2020/01/31 01:07:33 Generating JWE encryption key
2020/01/31 01:07:33 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
2020/01/31 01:07:33 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
2020/01/31 01:07:33 Initializing JWE encryption key from synchronized object
2020/01/31 01:07:33 Creating in-cluster Sidecar client
2020/01/31 01:07:33 Auto-generating certificates
2020/01/31 01:07:33 Successfully created certificates
2020/01/31 01:07:33 Serving securely on HTTPS port: 8443
2020/01/31 01:07:33 Successful request to sidecar
```

**Comment by ysaakpr** [comment]
This could be just becuase of the RBAC. https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#admin-privileges might help. For me, this was the issue.

**Comment by funkypenguin** [comment]
For reference, it was to do with the name of the metrics-scraper service. I've got a working chart here now: https://github.com/funkypenguin/helm-kubernetes-dashboard

**Comment by jerryyanmj** [comment]
After reading the code, I think the problem is the following code snippet in restclient.go.

```go
// Get creates request to given path.
func (c inClusterSidecarClient) Get(path string) RequestInterface {
	return c.client.Get().
		Namespace(args.Holder.GetNamespace()).
		Resource("services").
		Name("dashboard-metrics-scraper").
		SubResource("proxy").
		Suffix(path)
}

// HealthCheck does a health check of the application.
// Returns nil if connection to application can be established, error object otherwise.
func (self inClusterSidecarClient) HealthCheck() error {
	_, err := self.client.Get().
		Namespace(args.Holder.GetNamespace()).
		Resource("services").
		Name("dashboard-metrics-scraper").
		SubResource("proxy").
		Suffix("/healthz").
		DoRaw(context.TODO())
	return err
}
```
For whatever reason, the sidecar client which connects to scraper could not pass the health check, hence unavailable when the real pod metric retrieval happens.  In my case, the metricClient is empty and the code error out with **"No metric client provided. Skipping metrics."**

```go
func (self *DataSelector) getMetrics(metricClient metricapi.MetricClient) (
	[]metricapi.MetricPromises, error) {
	metricPromises := make([]metricapi.MetricPromises, 0)

	if metricClient == nil {
		return metricPromises, errors.NewInternal("No metric client provided. Skipping metrics.")
	}

	metricNames := self.DataSelectQuery.MetricQuery.MetricNames
	if metricNames == nil {
		return metricPromises, errors.NewInternal("No metrics specified. Skipping metrics.")
	}

	selectors := make([]metricapi.ResourceSelector, len(self.GenericDataList))
	for i, dataCell := range self.GenericDataList {
		// make sure data cells support metrics
		metricDataCell, ok := dataCell.(MetricDataCell)
		if !ok {
			log.Printf("Data cell does not implement MetricDataCell. Skipping. %v", dataCell)
			continue
		}

		selectors[i] = *metricDataCell.GetResourceSelector()
	}

	for _, metricName := range metricNames {
		promises := metricClient.DownloadMetric(selectors, metricName, self.CachedResources)
		metricPromises = append(metricPromises, promises)
	}

	return metricPromises, nil
}
```

I simply used the sidecar-host parameter to provide a service URL which connects to the metric-scraper.
```yaml
args:
  - --auto-generate-certificates
  - --namespace=kubernetes-dashboard
  - --token-ttl=3600
  - --sidecar-host=http://dashboard-metrics-scraper:8000
```

**Comment by Statemood** [comment]
> After reading the code, I think the problem is the following code snippet in restclient.go.
> 
> ```go
> // Get creates request to given path.
> func (c inClusterSidecarClient) Get(path string) RequestInterface {
> 	return c.client.Get().
> 		Namespace(args.Holder.GetNamespace()).
> 		Resource("services").
> 		Name("dashboard-metrics-scraper").
> 		SubResource("proxy").
> 		Suffix(path)
> }
> 
> // HealthCheck does a health check of the application.
> // Returns nil if connection to application can be established, error object otherwise.
> func (self inClusterSidecarClient) HealthCheck() error {
> 	_, err := self.client.Get().
> 		Namespace(args.Holder.GetNamespace()).
> 		Resource("services").
> 		Name("dashboard-metrics-scraper").
> 		SubResource("proxy").
> 		Suffix("/healthz").
> 		DoRaw(context.TODO())
> 	return err
> }
> ```
> 
> For whatever reason, the sidecar client which connects to scraper could not pass the health check, hence unavailable when the real pod metric retrieval happens. In my case, the metricClient is empty and the code error out with **"No metric client provided. Skipping metrics."**
> 
> ```go
> func (self *DataSelector) getMetrics(metricClient metricapi.MetricClient) (
> 	[]metricapi.MetricPromises, error) {
> 	metricPromises := make([]metricapi.MetricPromises, 0)
> 
> 	if metricClient == nil {
> 		return metricPromises, errors.NewInternal("No metric client provided. Skipping metrics.")
> 	}
> 
> 	metricNames := self.DataSelectQuery.MetricQuery.MetricNames
> 	if metricNames == nil {
> 		return metricPromises, errors.NewInternal("No metrics specified. Skipping metrics.")
> 	}
> 
> 	selectors := make([]metricapi.ResourceSelector, len(self.GenericDataList))
> 	for i, dataCell := range self.GenericDataList {
> 		// make sure data cells support metrics
> 		metricDataCell, ok := dataCell.(MetricDataCell)
> 		if !ok {
> 			log.Printf("Data cell does not implement MetricDataCell. Skipping. %v", dataCell)
> 			continue
> 		}
> 
> 		selectors[i] = *metricDataCell.GetResourceSelector()
> 	}
> 
> 	for _, metricName := range metricNames {
> 		promises := metricClient.DownloadMetric(selectors, metricName, self.CachedResources)
> 		metricPromises = append(metricPromises, promises)
> 	}
> 
> 	return metricPromises, nil
> }
> ```
> 
> I simply used the sidecar-host parameter to provide a service URL which connects to the metric-scraper.
> 
> ```yaml
> args:
>   - --auto-generate-certificates
>   - --namespace=kubernetes-dashboard
>   - --token-ttl=3600
>   - --sidecar-host=http://dashboard-metrics-scraper:8000
> ```

thanks! works for me!

**Comment by jensenity** [comment]
> ```yaml
> args:
>   - --auto-generate-certificates
>   - --namespace=kubernetes-dashboard
>   - --token-ttl=3600
>   - --sidecar-host=http://dashboard-metrics-scraper:8000
> ```

Genius!

**Comment by ftestte** [comment]
@jerryyanmj This helped me also. Thank you.
