### ISSUE TITLE
"Deploy and delete replication controller" integration test is flaky

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#466]
It causes the build pipeline to break, e.g., https://travis-ci.org/kubernetes/dashboard/builds/112631246

@maciaszczykm Can you fix this? Maybe by making the xpaths more resilient or doing some waiting.

**Comment by maciaszczykm** [comment]
I'll work on it.

**Comment by maciaszczykm** [comment]
Ok, I got it. Validation changed and random name generator created apps starting with digits from time to time... Will create fix in a minute.

**Comment by bryk** [comment]
Ouch, this was hard. Sorry we didn't find it during a code review... :(
