### ISSUE TITLE
Running apply command returns with `selector does not match template labels`

### ISSUE THREAD

**Issue by jeanpoelie** [kubernetes/dashboard#4662]
##### Environment

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
Kubernetes version: 1.15.5
Dashboard version: ?
Operating system: CLI (Ubuntu via Windows)
```

##### Steps to reproduce
Create clean kubernetes cluster in azure
Fire: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result
The Deployment "kubernetes-dashboard" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"kubernetes-dashboard"}: `selector` does not match template `labels`

##### Expected result
Successfull run

**Comment by floreks** [comment]
I think there might be already Kubernetes Dashboard installed in your cluster and you are trying to modify it using kubectl apply. That won't work. First remove old one then install a new one.

PS. 1.10.1 is no longer supported by us.

/close

**Comment by jeanpoelie** [comment]
Maybe update your readme.md than, you are still telling people to use the 1.10.1 version there :)
