### ISSUE TITLE
Something wrong happened when we run "npm run start:prod"

### ISSUE THREAD

**Issue by HanskAlan** [kubernetes/dashboard#4664]
We tried to run `npm run start:prod` when we tried to build the project from the source code, but it gives us error message as the picture discribes:
![image](https://user-images.githubusercontent.com/31760035/70861284-bca0c700-1f66-11ea-86a0-4898bf1bf5d4.png)
We are really confused and we 've tried many methods to solve the permission problem, like running the command in the root and change the authority of the relavant directory, but they don't work and give us the same message like before. 
we are looking forward to your help,thank you.

**Comment by maciaszczykm** [comment]
It's an error in your environment and it's hard to say what is wrong without more information. The fastest way would be to remove whole repo, download deps and trying again (using the same user):

```
rm -r .../dashboard
git clone ...
cd dashboard
npm ci
npm run start:prod
```
