### ISSUE TITLE
Logs view toolbar does not work on smaller screens

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#467]
##### Environment

Dashboard version: https://github.com/kubernetes/dashboard/commit/13e88ce9276186a383f64bdc56acba15f189fde7
Browsers: all

##### Steps to reproduce
Open logs page and shrink the window. 

![selection_037](https://cloud.githubusercontent.com/assets/1159999/13403362/eb87d536-df14-11e5-95c6-c0af617e40d6.png)

**Comment by bryk** [comment]
I take this.

**Comment by floreks** [comment]
Are you working on this?

**Comment by bryk** [comment]
No, can you take this?

**Comment by floreks** [comment]
Yeah, I wanted to do that :)

**Comment by bryk** [comment]
You now should be able change assignments of bugs, btw.

**Comment by floreks** [comment]
Perfect!
