### ISSUE TITLE
Separate serviceaccounts for end-user and dashboard app

### ISSUE THREAD

**Issue by driusha** [kubernetes/dashboard#4671]
##### What would you like to be added
There should be some arg which forces dashboard to use special ServiceAccount for technical purposes (to access dashboard's Secrets, CMs, etc). Meanwhile, the end-users should use their authorization resources (Bearer token, other static ServiceAccount, etc).

##### Why is this needed
In case of simple installation without Bearer tokens or anything other, we must allow access to dashboard resources but we don't need it.

**Comment by floreks** [comment]
And how is it different right now? Dashboard uses dedicated SA with custom privileges to access Dashboard specific resources. User has to provide any token that is acceptable by API server to log in and access other resources.

**Comment by driusha** [comment]
> Dashboard uses dedicated SA with custom privileges to access Dashboard specific resources. User has to provide any token that is acceptable by API server to log in and access other resources.

I am sorry,  i haven't mentioned that in some cases we use --insecure-port without --enable-insecure-login to provide the simplest installation of dashboard. In this case, end-user shares ServiceAccount with dashboard.

So, it turns out that we need arg like --insecure-end-user-service-account.

**Comment by floreks** [comment]
This is exactly the difference between insecure/secure setup. You choose if you want to use only Dashboard SA for full access or split it to use Dashboard SA for Dashboard resources access only and external token for the rest. I'd rather say that this is a configuration issue. You have chosen to give up security.

**Comment by driusha** [comment]
I've found a solution for my case. So the issue isn't actual for me.
Thank you.
