### ISSUE TITLE
Change namespaces in creating-sample-user.md to kuber-system

### ISSUE THREAD

**Issue by ahmadidev** [kubernetes/dashboard#4672]
##### Change namespace specified in [`creating-sample-user.md`](https://github.com/kubernetes/dashboard/commit/15c46a25bcd0fc13fda5001230bbad180885edf2) to kube-ststem instead of kubernetes-dashboard

The [kubernetes-dashboard.yaml](https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml) create dashboard objects under `kube-system` namespace, but `creating-sample-user.md` uses `kubernetes-dashboard` namespace. So applying .yml files to create admin-user and role binding fails.

**Comment by floreks** [comment]
Actually, we have to update README to use `v2` instead of `v1`. `creating-sample-user.md` is actually up-to-date with the latest changes. Dashboard has been moved out of `kube-system` namespace intentionally.

**Comment by floreks** [comment]
Closing in favor of #4690 as it is described better.
