### ISSUE TITLE
kubernetes-dashboard-amd64:v1.10.1 image gives Unkown Server Error (404) in k8s 1.17

### ISSUE THREAD

**Issue by ruben-visser** [kubernetes/dashboard#4679]
##### Environment
k8s 1.17 (latest) - bare-metal
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

helm 3
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

package: stable/kubernetes-dashboard --version 1.10.1

```
Installation method:
Kubernetes version:kubeadm
Dashboard version:
v1.10.1
Git Commit:
50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Steps to reproduce
install kubernetes, install helm 3, add kubernetes-dashboard through: helm install stable/kubernetes-dashboard --version 1.10.1, add service account: kubectl create serviceaccount dashboard-sa -n kube-system, bind sa to cluster-admin: kubectl create clusterrolebinding dashboard-cb --clusterrole=cluster-admin --serviceaccount=kube-system:dashboard-sa, retrieve bearer token (kubectl describe secret -n kube-system dashboard-sa-token-....) and login to dashboard

##### Observed result
After login kubernetes-dashboard presents server-error (404)
![dashboard-error](https://user-images.githubusercontent.com/8261532/71084732-38348b00-2196-11ea-99e8-36ed18c433ac.png)
![dashboard-error2](https://user-images.githubusercontent.com/8261532/71085291-72eaf300-2197-11ea-8ce6-80ce1d4ab3ed.png)
pod log:
![bd-logs](https://user-images.githubusercontent.com/8261532/71085930-e3464400-2198-11ea-967a-e047c3ac0aed.png)

##### Expected result
Did all the same on k8s 1.15.7, there the kubernetes-dashboard works. Only difference is k8s version!
![working-dashboard v1 15-2](https://user-images.githubusercontent.com/8261532/71085490-edb40e00-2197-11ea-971e-460df978eac7.png)
![working-dashboard v1 15](https://user-images.githubusercontent.com/8261532/71085506-fa386680-2197-11ea-91ce-87cc21eadc2a.png)
pod log:
![wd-logs](https://user-images.githubusercontent.com/8261532/71085954-ee996f80-2198-11ea-8945-cbcdee609f6a.png)

##### Comments
image v1.10.1 does not work for Kubernetes 1.17

**Comment by floreks** [comment]
Duplicate. Use search first and check compatibility matrix on the releases page.

/close
