### ISSUE TITLE
Dashboard reported Internal Server Error (500): square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by madhifallah** [kubernetes/dashboard#4680]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by stevenkitter** [comment]
why close it? already there

**Comment by maciaszczykm** [comment]
Did you provide any useful information? For example in the issue template there are steps to reproduce and they are missing.

**Comment by floreks** [comment]
Also, v1.10.1 has been deprecated long time ago.
