### ISSUE TITLE
No cert/key created within kubernetes-dashboard-certs secret

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes/dashboard#4684]
##### Environment

```
Installation method: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml`
Kubernetes version: 1.15.6
Dashboard version: 2.0.0-beta8
Operating system: Centos7
```

##### Steps to reproduce
1. kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml
2. kubectl describe secret/kubernetes-dashboard-certs -n kubernetes-dashboard
```
 kc describe secret/kubernetes-dashboard-certs -n kubernetes-dashboard        
Name:         kubernetes-dashboard-certs
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
```
3. kc describe secret/kubernetes-dashboard-csrf -n kubernetes-dashboard
```
Name:         kubernetes-dashboard-csrf
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
csrf:  256 bytes
```

4. kc describe secret/kubernetes-dashboard-key-holder -n kubernetes-dashboard 
```
Name:         kubernetes-dashboard-key-holder
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  
Type:         Opaque

Data
====
priv:  1679 bytes
pub:   459 bytes
```
##### Observed result
Log of the dashboard
```
kc logs kubernetes-dashboard-56c5f95c6b-fsg6n -n kubernetes-dashboard
2019/12/18 19:48:12 Starting overwatch
2019/12/18 19:48:12 Using namespace: kubernetes-dashboard
2019/12/18 19:48:12 Using in-cluster config to connect to apiserver
2019/12/18 19:48:12 Using secret token for csrf signing
2019/12/18 19:48:12 Initializing csrf token from kubernetes-dashboard-csrf secret
2019/12/18 19:48:12 Empty token. Generating and storing in a secret kubernetes-dashboard-csrf
2019/12/18 19:48:12 Successful initial request to the apiserver, version: v1.15.6
2019/12/18 19:48:12 Generating JWE encryption key
2019/12/18 19:48:12 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
2019/12/18 19:48:12 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
2019/12/18 19:48:12 Initializing JWE encryption key from synchronized object
2019/12/18 19:48:12 Creating in-cluster Sidecar client
2019/12/18 19:48:12 Successful request to sidecar
2019/12/18 19:48:12 Auto-generating certificates
2019/12/18 19:48:12 Successfully created certificates
2019/12/18 19:48:12 Serving securely on HTTPS port: 8443
```

##### Expected result
tls.crt and tls.key should be created as part of the secret

**Comment by floreks** [comment]
Works as designed. The secret is for the user to upload his custom certificates. Our certificates are autogenerated and stored in memory, not in the secret.

/close

**Comment by cmoulliard** [comment]
What is strange is that I dont suffer from this problem, if I install the dashboard top of a k8s cluster : 1.14.9 and not 1.15.6 !!

Steps followed
```
git clone https://github.com/snowdrop/k8s-infra
cd k8s-infra/ansible

# Export the IP address of your docker vm where you would like to install the k8s cluster
IP=116.202.128.93

ansible-playbook playbook/generate_inventory.yml -e ip_address=${IP} -e type=hetzner -e filename=${IP}_host
ansible-playbook -i inventory/${IP}_host playbook/post_installation.yml --tags k8s_cluster
ansible-playbook -i inventory/${IP}_host playbook/post_installation.yml --tags ingress
ansible-playbook -i inventory/${IP}_host playbook/post_installation.yml --tags k8s_dashboard -e k8s_dashboard_token_public="<PUBLIC_TOKEN>" -e k8s_dashboard_token_secret="<SECRET_TOKEN>"
```

**Comment by floreks** [comment]
Then this is a Kubernetes related issue, not Dashboard. I have explained how it works on our side.

**Comment by cmoulliard** [comment]
What do you suggest to do then: open a k8s and/or ingress-controller ticket with the reported issue ? @floreks

**Comment by floreks** [comment]
I am not entirely sure that this is an issue. It probably works as expected. If you want ingress to pick up the certificates for Dashboard, then upload your own custom certificates to the secret, otherwise, autogenerated secrets are not shared (only stored in memory).

**Comment by cmoulliard** [comment]
> If you want ingress to pick up the certificates for Dashboard, then upload your own custom certificates to the secret, otherwise, autogenerated secrets are not shared (only stored in memory).

Right. In fact, my config is wrong as the content of the secret is empty for kubernetes-dashboard-certs 
 (= no tls crt and key) but when it is deployed on k8s (= 1.14.x) with ingress nginx controller (= 0.23.0), then a fake SSL Certificate is generated and users can access the URL of the dashboard.

**Comment by tejanttf** [comment]
i''m having the same issue, the default kubernetes-dashboard-certs has no data, therefore i'm not able to get barer token, is there any solution to this issue ? please help
