### ISSUE TITLE
I'm getting error ecrets is forbidden: User "system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard" cannot list resource "secrets" in API group "" in the namespace "default"

### ISSUE THREAD

**Issue by agussang** [kubernetes/dashboard#4686]
i'm getting error ecrets is forbidden: User "system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard" cannot list resource "secrets" in API group "" in the namespace "default"

for access kubernetes web ui

**Comment by maciaszczykm** [comment]
You are authenticated with Dashboard's default SA which doesn't have necessary permissions. Please refer to the Kubernetes docs for RBAC documentation. And do not remove the template when you create an issue, there is no information about your setup at all.
