### ISSUE TITLE
Main documentation is not up to date

### ISSUE THREAD

**Issue by interone-ms** [kubernetes/dashboard#4690]
When installing a new k8s 1.17.0 cluster and trying to get the Dashboard installed, there are a couple of issues:

1. README.md refers to the 1.10 Dashboard YML file instead of the v2
2. The link on "Create an user" refers to the up-to-date Dashboard version - but the YML files in there do not work on Dashboard v2
3. Manually digging up the old wiki page with the v1.10 instructions in creating-sample-user.md works, but logging in with the token fails (see issue #4401)
4. There is no guide on how to upgrade Dashboard from v1.10 to v2

Please synchronize the documentation and provide something that a user of k8s 1.17.0 or later can actually follow through :(

**Comment by floreks** [comment]
As I have mentioned in #4672, we are aware of that. Currently, we are focusing on fixing all issues before official v2 release and unfortunately don't have time to update documentation properly.

Upgrade is not really an option as they differ too much. You simply remove old Dashboard resources and install v2 based on what is described in [releases](https://github.com/kubernetes/dashboard/releases). It also contains a compatibility matrix.

**Comment by shu-mutou** [comment]
All of pointed issues have been described and updated docs already.
