### ISSUE TITLE
Dashboard Scaling Failure

### ISSUE THREAD

**Issue by Srinivasa381224** [kubernetes/dashboard#4704]
Hi This is Srinu am deployed kube-dashboard in my kubernets dashboard it successfully up and i generated a token logged in to the dashboard after am trying to scale my pods in replica sets But it is saying the pod status error 
Terminated: ExitCode:${state.terminated.exitCode}
Am checking the logs for dashboard it is  
"""Incoming HTTP/2.0 GET /api/v1/replicaset/dev/web-85c8f9bf68?filterBy=&itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from IP:44274: {}
2019/12/23 05:21:14 Getting details of web-85c8f9bf68 service in dev namespace
2019/12/23 05:21:14 Getting replication controller web-85c8f9bf68 pods in namespace dev
2019/12/23 05:21:14 Getting pod metrics
2019/12/23 05:21:14 [2019-12-23T05:21:14Z] Outcoming response to 10.30.44.19:44274 with 200 status code"""

Success only please let me know what is the wrong i done here

**Comment by zehuaiWANG** [comment]
Please let us know which version of dashboard and kubernetes you are using

**Comment by Srinivasa381224** [comment]
kubectl version report
"""Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-afa464", GitCommit:"afa464ce9760bd08a53a207f505b133b93366ea3", GitTreeState:"clean", BuildDate:"2019-10-22T21:42:57Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}'''

Dashboard Version: v1.10.1

**Comment by zehuaiWANG** [comment]
Do not use v1.10.1. Please use newest version from releases page. v1.10.1 is not supported any more.

**Comment by Srinivasa381224** [comment]
I changed the version also
But it is not scaling getting same error """Terminated: ExitCode:${state.terminated.exitCode}"""

dash board version is : Dashboard v2.0.0-beta4

**Comment by Srinivasa381224** [comment]
Why I cant able to update replicasets from dashboard is there any roles and permissions 
issues

**Comment by floreks** [comment]
Use latest beta version and check compatibility matrix before deploying Dashboard. Also, do not scale replica set as it is controlled by deployment usually. Scale controlling resource.

/close

**Comment by Srinivasa381224** [comment]
thanks i got it
