### ISSUE TITLE
 Excuse me, explain to me the meaning of the following information, thank you very much.

### ISSUE THREAD

**Issue by wybaron** [kubernetes/dashboard#4713]
I don't know the meaning of the values ​​in the red box in the picture. The conjecture is a limitation on a single pod, not a limitation on the entire physical server resources. Expect to wait until the answer.
![image](https://user-images.githubusercontent.com/19605510/71442038-2414fe80-273f-11ea-96e4-81acfb3e2b07.png)

**Comment by wybaron** [comment]
The picture disappears and cannot be seen. Let me explain how the picture information appears:
1.Sign in to Kubernetes.
2.SeSelect "Node" in "Cluster" in the side navigation bar.
3.Select any node in the right interface and enter.
4.I don't know the meaning of the CPU allocation (cores) and memory allocation (bytes) limits.

**Comment by floreks** [comment]
https://kubernetes.io/docs/concepts/architecture/nodes/

/close

**Comment by wybaron** [comment]
> https://kubernetes.io/docs/concepts/architecture/nodes/
> 
> /close

Your help is very useful to me, thank you very much for your help.
