### ISSUE TITLE
Allow setting default values for local settings globally

### ISSUE THREAD

**Issue by hadrien-toma** [kubernetes/dashboard#4718]
##### What would you like to be added
I would like to change the default value of dashboard local settings (those stored in :cookie:s).

##### Why is this needed
I would like to avoid repetitively doing `dashboard > settings > dark-mode` :innocent:.

**Comment by hwdef** [comment]
+1
I think it would be better to add a language setting.

**Comment by maciaszczykm** [comment]
The light theme will stay as the default one, so at the moment we will not change anything.

**Comment by maciaszczykm** [comment]
> I think it would be better to add a language setting.

This is completely different issue, open another one in GitHub.

**Comment by hadrien-toma** [comment]
@maciaszczykm it is a shame that the default is not considered as customizable. Allow users to define their settings by code is a good practice and here it is not followed at all, so completly unusable in an automated way (my "open dashboard" script can not specify the dashboard settings I want...).
I admit I am quite disapointed of your answer...

**Comment by maciaszczykm** [comment]
@hadrien-toma You can always create a pull request that will introduce a way of changing the default and we can review it. I might have closed it too quickly but in general this has very low priority for us, there is plenty of more important things that would like to implement first.

/open

**Comment by hadrien-toma** [comment]
Thank you for this message :+1: !
I totally understand and I thank you and all the team for the work you do.

**Comment by yerzhant** [comment]
It's needed to broaden expiration of cookie isThemeDark (now it's until the end of a browser session), so that not to reset (re-enable) it on every launch of the dashboard.

**Comment by floreks** [comment]
It depends how you configure your browser. Most people do not clear all cookies on every browser launch as it would log you out from every used website.

**Comment by yerzhant** [comment]
@floreks Thanks a lot for a valuable advise. In my Chrome's settings in cookies section in subsection _Sites, whose cookie files are always deleted on closing windows_ was added something like [*.]localhost. After deleting it now dark mode persists after restarting the browser.

**Comment by hadrien-toma** [comment]
On my side, this is not a viable solution as what I want is a deterministic script running minikube and opening its dashboard in a mastered way (I don't want a manual configuration in the browser of each computer of each dev).
I just would like to be able to define if by *default* the dashboard is dark or not.

**Comment by maciaszczykm** [comment]
I think at the moment changing to the "system" theme as default will be enough. It's a new option that I've added recently.
