### ISSUE TITLE
Dashboard keyboard shortcuts interfering with shell commands

### ISSUE THREAD

**Issue by hamxabaig** [kubernetes/dashboard#4721]
#### Environment

Not really a Kubernetes problem just an annoying UI issue that whenever you start typing commands in shell. It triggers the keyboard shortcuts. Like type `ech` and pressing `o` will open this:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/12872177/71613630-70da5880-2bc9-11ea-82d9-2fdda59d67f9.png">

Or you start typing `r` and it'll reload the whole page :/

I think we should turn off the shortcuts for shell page?

```
Dashboard version: v1.10.1
```

##### Steps to reproduce

- Go to the shell of a pod
- Try typing `echo`

##### Observed result

- A popup opens (triggered due to `o` key)

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/12872177/71613630-70da5880-2bc9-11ea-82d9-2fdda59d67f9.png">

##### Expected result

It should be able to type commands like `echo` or `curl` (r will reload 😄)

##### Comments
N/A

**Comment by floreks** [comment]
Use v2 beta and see if issue persists. v1.10.1 is generally not supported anymore.

**Comment by hamxabaig** [comment]
@floreks I see, i'll let check that out. Thanks

**Comment by maciaszczykm** [comment]
@hamxabaig Does it work?

**Comment by hamxabaig** [comment]
@maciaszczykm I'm waiting for our devops to deploy new dashboard, is there a way i can check it out myself without waiting for him?

**Comment by maciaszczykm** [comment]
You can start it locally. Refer to https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md.

**Comment by hamxabaig** [comment]
@maciaszczykm @floreks It works in v2, thank you!
