### ISSUE TITLE
enableInsecureLogin=true creates Service with 443 port

### ISSUE THREAD

**Issue by kamilgregorczyk** [kubernetes/dashboard#4724]
According to this: https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard running `helm install dashboard stable/kubernetes-dashboard --namespace kubernetes-dashboard --set enableInsecureLogin=true` should create a service on 80 port but it created one on 443

**Comment by floreks** [comment]
It's not a bug. Their documentation is wrong. Works as designed.

/close

**Comment by kamilgregorczyk** [comment]
So what's the way of creating Kubernetes dashboard that works on http instead of https ?

**Comment by kamilgregorczyk** [comment]
I think the alternative yaml is supposed to be used as http if I'm not mistaken? https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/alternative.yaml

**Comment by floreks** [comment]
Yes
