### ISSUE TITLE
Kubernetes DAshboard and SAML tokens

### ISSUE THREAD

**Issue by manpreetsnehra** [kubernetes/dashboard#4727]
I don't know where to put this request, I have been trying to setup dashboard v2.0.0-beta1 on eks cluster but no matter which token I use, Service account or saml bot keep failing constantly. 

The SAML tokens for an account with cluster-admin access to the cluster looks like this
time="2020-01-06T09:49:05Z" level=warning msg="access denied" client="127.0.0.1:32948" error="input token was not properly formatted: non-whitelisted query parameter \"X-Amz-\"" method=POST path=/authenticate

This mostly shows that the token is not working since eks tokens have a few X-Amz params.  I tried posting the problem on slack #sig-ui and #eks but with no sueccess thoguht it might be useful to have  a record here.

**Comment by floreks** [comment]
Dashboard only proxies the token to API server. API server has to accept it. First test it with kubectl. If it will work then Dashboard will accept it too.
