### ISSUE TITLE
kubernetes dashboard not acessible

### ISSUE THREAD

**Issue by suadhika** [kubernetes/dashboard#4728]
`core@test-eu-k8s-k8s-master-nf-1 ~ $ kubectl get nodes
NAME                          STATUS   ROLES    AGE   VERSION
test-eu-k8s-k8s-master-nf-1   Ready    master   17d   v1.16.2
test-eu-k8s-k8s-node-nf-1     Ready    <none>   17d   v1.16.2
test-eu-k8s-k8s-node-nf-2     Ready    <none>   17d   v1.16.2`

`core@test-eu-k8s-k8s-master-nf-1 ~ $ kubectl get pods -n kube-system
NAME                                                  READY   STATUS    RESTARTS   AGE
calico-kube-controllers-5dccd86d8c-5vdvp              1/1     Running   0          17d
calico-node-5mwf8                                     1/1     Running   1          17d
calico-node-7wq76                                     1/1     Running   1          17d
calico-node-s29xr                                     1/1     Running   1          17d
coredns-58687784f9-crt5q                              1/1     Running   0          17d
coredns-58687784f9-nr8tj                              1/1     Running   0          17d
dashboard-metrics-scraper-76585494d8-lpvk5            1/1     Running   0          10d
dns-autoscaler-79599df498-v7vw4                       1/1     Running   0          17d
kube-apiserver-test-eu-k8s-k8s-master-nf-1            1/1     Running   0          17d
kube-controller-manager-test-eu-k8s-k8s-master-nf-1   1/1     Running   0          17d
kube-proxy-bqv5h                                      1/1     Running   0          17d
kube-proxy-stxjd                                      1/1     Running   0          17d
kube-proxy-vtrgl                                      1/1     Running   0          17d
kube-scheduler-test-eu-k8s-k8s-master-nf-1            1/1     Running   0          17d
kubernetes-dashboard-594b99b6f4-b5zzm                 1/1     Running   0          10d
nginx-proxy-test-eu-k8s-k8s-node-nf-1                 1/1     Running   0          17d
nginx-proxy-test-eu-k8s-k8s-node-nf-2                 1/1     Running   0          17d
nodelocaldns-d5gq5                                    1/1     Running   0          17d
nodelocaldns-g6brk                                    1/1     Running   0          17d
nodelocaldns-krkpc                                    1/1     Running   0          17d
tiller-deploy-969865475-snmkh                         1/1     Running   0          14d`

kubectl cluster-info

core@test-eu-k8s-k8s-master-nf-1 ~ $ kubectl cluster-info
Kubernetes master is running at https://172.21.97.117:6443
coredns is running at https://172.21.97.117:6443/api/v1/namespaces/kube-system/services/coredns:dns/proxy
kubernetes-dashboard is running at https://172.21.97.117:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

Now when I try to access the url https://172.21.97.117:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy I could see the title loaded but not few js associated with it. below are the javascript I got from browser's devtools

`<script src="runtime.380dd4d7ab4891f91b7b.js" defer></script><script src="polyfills-es5.65f1e5151c840cf04c3e.js" nomodule defer></script><script src="polyfills.8623bbc9d68876cdaaaf.js" defer></script><script src="scripts.7d5e232ea538f2c0f8a7.js" defer></script><script src="main.3036e86b43f81b098e24.js" defer></script></body>`

I could access the kubernetes dashboard container directly from the machine where is it deployed(worker 1) and the js as well but from master and other worker node the js is not loading.
eg: if I try curl -k https://10.233.61.46:443/runtime.380dd4d7ab4891f91b7b.js from 172.21.97.105 node it works (the dashboard container is deployed in here) but If i try it from anyother node it fails to load any of the js. 

Calico is working fine and route -n result also looks good
core@test-eu-k8s-k8s-master-nf-1 ~ $ sudo calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+------------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+---------------+-------------------+-------+------------+-------------+
| 172.21.97.105 | node-to-node mesh | up    | 2019-12-20 | Established |
| 172.21.97.102 | node-to-node mesh | up    | 2019-12-20 | Established |
+---------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.

core@test-eu-k8s-k8s-master-nf-1 ~ $ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.21.97.97    0.0.0.0         UG    1024   0        0 eth0
10.233.66.0     0.0.0.0         255.255.255.0   U     0      0        0 *
10.233.66.1     0.0.0.0         255.255.255.255 UH    0      0        0 calia95ef7a6993
10.233.66.2     0.0.0.0         255.255.255.255 UH    0      0        0 cali89a09c06bf1
10.233.82.0     172.21.97.102   255.255.255.0   UG    0      0        0 tunl0
10.233.124.0    172.21.97.105   255.255.255.0   UG    0      0        0 tunl0
169.254.169.254 172.21.97.97    255.255.255.255 UGH   1024   0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.21.97.96    0.0.0.0         255.255.255.224 U     0      0        0 eth0
Dashboard is installed from - https://github.com/kubernetes/dashboard- Kubernetes version is 1.16

**Comment by floreks** [comment]
It's a cluster configuration issue. We do not provide such support here. Also, I think you are using old version of Dashboard because it's installed in the `kube-system` namespace and should be in `kubernetes-dashboard` namespace.

/close
