### ISSUE TITLE
External Endpoint is abbreviated to useless

### ISSUE THREAD

**Issue by davidmankin** [kubernetes/dashboard#473]
##### Environment

```
Dashboard version: Images: gcr.io/google_containers/kubernetes-dashboard:canary
Kubernetes version: 1.1
```

The replication controller view shows the external endpoints for the service, which is great. But it shows it with a "..." in the middle that makes it unusable.

e.g.
```
External endpoint
af88883bcdea211e5b45606...b.amazonaws.com:80 TCP
```

This is a port 80 tcp port, so it might be nice to assume it's an http url and create an a href target=_blank link to the whole url.  But at the very least we should find a way to make it so I can copy the un-elided hostname so that I can paste it into my browser (without resorting to Chrome's Inspect Element).

**Comment by maciaszczykm** [comment]
External endpoints' links were added in #399, but it seems, that it's not in `gcr.io/google_containers/kubernetes-dashboard:canary` image yet.

@bryk Do you know when it will be updated?

**Comment by bryk** [comment]
@danwinship This is fixed already, but not released. I'll rebuild canary image today.

**Comment by bryk** [comment]
@maciaszczykm I've always had a dream that we release canary image on every successful master branch build. This should be easy to do, but post 1.0.

**Comment by bryk** [comment]
Pushed.
