### ISSUE TITLE
Dashboard v2 how to give full permission?

### ISSUE THREAD

**Issue by itkroplis** [kubernetes/dashboard#4731]
Hi!

I upgrade cluster to 1.17.0 and Dashboard to v2.  But I have a problem. I get access error:
cannot list resources ...  any (secrets,configmaps etc.). I try to give access similar as for dashboard v1 but it not work anymore. Please give me worked example for full access yaml.

**Comment by floreks** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

Read and understand. Then create your own roles and bindings, get token from SA and use it to log in.

/close
