### ISSUE TITLE
the pod status is not true

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4740]
hi, everyone,
I found that the dashboard can not handle the pod `Terminating` status,
BTW, when the pod phase is `Running ` and the `DeletionTimestamp` is not nil, dashboard will show the pod is Running, but it's `Terminating`  if I use `kubectl describe pod`.
```
func isTerminating(pod *corev1.Pod) bool {
	if pod.Spec.ActiveDeadlineSeconds != nil && *pod.Spec.ActiveDeadlineSeconds >= int64(0) {
		return true
	}
	return false
}
```
I found some code in kubernetes/kubernetes and I think we need more information about the pod status because it's a important part, the kubernetes offical doc seems not clear to describe it also.

**Comment by mukundmckinsey** [comment]
try this one https://grafana.com/grafana/dashboards/11802
