### ISSUE TITLE
Firefox operations result in "Internal server error [object Object]

### ISSUE THREAD

**Issue by everflux** [kubernetes/dashboard#4754]
##### Environment

```
Installation method: kubeadm
Kubernetes version: 1.17
Dashboard version: 2.0.0-rc1
Operating system: Arch Linux
Node.js version ('node --version' output): not installed
Go version ('go version' output): not installed

Dashboard is running behind traefik reverse proxy and traefik ingress, authentication by token (dashboard) and basic auth (traefik reverse proxy)
```

##### Steps to reproduce
Make any changes, for example delete a pod.

##### Observed result
Error dialog is show: "Internal server error  [object Object]"
BUT the operation is performed.

![Screenshot from 2020-01-10 11-01-13](https://user-images.githubusercontent.com/985728/72144259-8e14e100-3398-11ea-924a-17c0787fbf8a.png)

##### Expected result
No error dialog is shown.

##### Comments
Does not happen with chrome, just with firefox.
No errors in the javascript console.
Not errors in network tab visible.

Result from the tested DELETE operation on a pod:

Request URL: ... api/v1/_raw/pod/namespace/grpc/name/nest-5787bcbbc5-l5gs7
Method: DELETE

Status: 200 OK
Content-encoding: gzip
Content type: application/x-gzip
Version: HTTP/2
Body:
H4sIAAAAAAAE/wEAAP//AAAAAAAAAAA=

**Comment by mkhpalm** [comment]
Happens with k8s v1.16.3 as well. Every time I delete a pod it shows that error message.

**Comment by deepybee** [comment]
This is also occuring on minikube 1.6.2 running k8s 1.17.0.

**Comment by floreks** [comment]
Will be fixed by https://github.com/kubernetes/dashboard/pull/4791/files#diff-3583e52039a049a631f0f925ea8e3500R47

If there are any other actions that result in error in firefox please create an issue.
