### ISSUE TITLE
How to display Chinese on my dashboard 2.0-beta8?

### ISSUE THREAD

**Issue by wanghaiqing2015** [kubernetes/dashboard#4755]
How do I set parameters in yaml

**Comment by floreks** [comment]
You do not. It's based on your browser's locale. We might have an issue with choosing proper locale right now as discussed in #4734. We will prepare the correct directories soon. Right now you should be able to switch language by using locale switcher extensions for your browser.

**Comment by hwdef** [comment]
Change your browser language to `zh`, neither `zh-CN` nor `zh-TW`.

**Comment by wanghaiqing2015** [comment]
tks
