### ISSUE TITLE
Add links to dashboard tour

### ISSUE THREAD

**Issue by GertiPoppel** [kubernetes/dashboard#476]
#### Issue details
1. The Zero state page contains text only and no links to any documentation
2. The Deploy pages do not contain a link to the Dashboard tour. 

##### Environment
Dashboard version: 13e88ce
Browsers: all

##### Expected result

1. On Zero state page there is only one link to the "Dashboard tour" (http://kubernetes.io/v1.1/docs/user-guide/ui.html)

2. On the Deploy pages, there is a link to the "Dashboard tour" (http://kubernetes.io/v1.1/docs/user-guide/ui.html)

##### Comments

@maciaszczykm Please take care of this

**Comment by maciaszczykm** [comment]
I can do it on Monday.

**Comment by maciaszczykm** [comment]
Working on it.

**Comment by bryk** [comment]
Awesome. Can you take care of the zero-state banner today? I'll do the release afternoon. Does this work for you?

**Comment by maciaszczykm** [comment]
@bryk Sure. I'll start with first point and then do the second. Do you want to have it in separate pull requests?

**Comment by bryk** [comment]
No need to separate this.

**Comment by maciaszczykm** [comment]
It can be closed.
