### ISSUE TITLE
Having trouble adding languages to i18n

### ISSUE THREAD

**Issue by hwdef** [kubernetes/dashboard#4763]
##### What should be cleaned up or changed

`docs/developer/internationalization.md`

##### Provide any links for context

I am doing the work of adding languages follow `internationalization.md` , and I find two troubles:

1. I cannot find  `xfillmergeOptions` array , only `xliffmergeOptions`

![image](https://user-images.githubusercontent.com/13084946/72236231-ed7d2600-3610-11ea-828a-ddcdfa3d1802.png)

![image](https://user-images.githubusercontent.com/13084946/72236318-4cdb3600-3611-11ea-9b71-87f061ed2e6c.png)

2.I add `zh-cn` in xliffmergeOptions array ,and I run 

```shell
npm run fix:i18n
```
the result is 

![image](https://user-images.githubusercontent.com/13084946/72236371-89a72d00-3611-11ea-86eb-099846a9f3bf.png)

Is this a bug or am I running the wrong process?

**Comment by floreks** [comment]
Those steps are not really valid.

After `messages.zh-cn.xlf` is generated, create directory for your translation i.e. `zh-cn` and move the translation file there. Then add `zh-cn` to the `locale_conf.json` file. That should be all. Then you can translate the file.

**Comment by hwdef** [comment]
@floreks 
Thanks for your answer.
How should problem 1 be solved?Is it a spelling mistakes? Modify the array name in the `internationalization.md`?
I can perfect this document

**Comment by maciaszczykm** [comment]
@hwdef You can fix the mistake and add the description from @floreks to it.

**Comment by hwdef** [comment]
@maciaszczykm 
OK, I will do these.

**Comment by floreks** [comment]
Updated Documentation in #4792 

/close
