### ISSUE TITLE
App name validation message overlaps character counter

### ISSUE THREAD

**Issue by digitalfishpond** [kubernetes/dashboard#477]
Validation message for wrong pattern on Deploy --> Specify app details below --> App name overlaps the character counter 

![validationoverlap](https://cloud.githubusercontent.com/assets/13361549/13456916/a66bc91a-e065-11e5-9edb-a118fd2a5cd0.PNG)

##### Steps to reproduce
- Deploy
- select "Specify app details below"
- In App name field, type a string with illegal characters (capitals, underscores, etc)
- focus out 

##### Observed result
Message overlaps character counter

##### Expected result
Character counter should be separate from message

**Comment by bryk** [comment]
Hmm... Isnt this an angular material bug? The demo on material site works as expected: https://material.angularjs.org/latest/demo/input

**Comment by floreks** [comment]
This is our bug because `ng-messages` are surrounded with `div`: https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/deploy/deployfromsettings.html#L26

Height is changed and that's why text is overlapping counter. Deleting `div` fixes problem.

**Comment by digitalfishpond** [comment]
Ah. deleting `div` also causes jittering on a number of events... I wonder if it would be possible to assign a flex value (like '80') to the div? or put a div around the counter too?

**Comment by bryk** [comment]
> deleting div also causes jittering on a number of events..

Can you explain this?

**Comment by digitalfishpond** [comment]
If I remember correctly, the div was added to avoid the rest of the form jumping up and down (in Firefox at least) upon focus and upon showing error message.
