### ISSUE TITLE
Pods page show containers pvc relate information

### ISSUE THREAD

**Issue by autherlj** [kubernetes/dashboard#4788]
**kubernetes version 1.5.0
dashboard version v2.0.0-rc1
metric-scraper v1.0.2
Chrome version 72.0.3626**

##### What would you like to be added
Pods page show containers pvc related information, so that we can see which container has PVC claims.

##### Why is this needed
better customer experience. Previous dashboard had this feature like attach picture. I want to show the green part. 
![1111](https://user-images.githubusercontent.com/30717333/72485686-78456700-3843-11ea-986f-a6ddccf8d631.png) above image is dashboard v.1.10

##### Comments
BTW: why dashboard 2.0.0 cannot translate Chinese？

**Comment by zehuaiWANG** [comment]
In my opinion, the containers pvc related information should be added back. Maybe we forget to add it after refactoring the dashboard. BTW, you can change your Chrome into Chinese language to use the Chinese version.

here is some issue about this: https://github.com/kubernetes/dashboard/issues/2240

**Comment by autherlj** [comment]
> In my opinion, the containers pvc related information should be added back. Maybe we forget to add it after refactoring the dashboard. BTW, you can change your Chrome into Chinese language to use the Chinese version.
> 
> here is some issue about this: #2240

my chrome://settings/ already setting language Chinese as top, but v2.0.0 still show english, v1.10 is chinese.

**Comment by floreks** [comment]
@autherlj as Chinese has quite many language codes (`zh`, `zh-TW`, `zh-CN`, etc.) we do not have all of them translated and configured yet. Right now only supported code is `zh` if your browser presents different one then it will show english.
