### ISSUE TITLE
Config dashboard context root

### ISSUE THREAD

**Issue by huyinsong** [kubernetes/dashboard#4797]
##### What would you like to be added

Add a parameter to config kubernetes dashboard context path. With this parameter I could decide whether using root context path or not. 
For example: I could access dashboard with https://ip:31117/dashboard/ or https://ip:31117 or https://ip:31117/otheruri. 
##### Why is this needed
I want to access dashboard behind a Nginx server. I have many other angular project which have the same app construct as kubernetes dashboard. For now dashboard is listening on the root context path. And this can cause some issues when I want using one external port to redirect dashboard and other apps. Is there any solution could make dashboard doesn't  deployed on the root context path? 
##### Comments

See my issue here
https://stackoverflow.com/questions/59782121/how-to-using-nginx-to-handle-requests-to-kubernetes-dashboard

**Comment by floreks** [comment]
It's just the matter of configuring your proxy properly. We do not need to change root path on our side. For example kubectl proxy exposes Dashboard on a non root path and it works just fine.

/close
