### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by pirate-liuzz** [kubernetes/dashboard#4799]
execute：
kubectl create -f https://github.com/kubernetes/dashboard/tree/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

error: 
error parsing https://github.com/kubernetes/dashboard/tree/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml: error converting YAML to JSON: yaml: line 116: mapping values are not allowed in this context

**Comment by floreks** [comment]
`v1.10.1` is deprecated and might not be valid anymore for new K8S vesions.

/close
