### ISSUE TITLE
Multiple Clusters

### ISSUE THREAD

**Issue by ivelichkovich** [kubernetes/dashboard#4801]
##### What would you like to be added

I would like to add the ability to pass in a kube-config with many kube-contexts. The dashboard would have a dropdown to select context/cluster and an "all clusters" view similar to "all-namespaces"

##### Why is this needed

Many users are in situations where they run many different clusters. We have over 20 clusters, it would be nice to have one dashboard for them all and a way to get an aggregated view. 

##### Comments
Wondering if this is a feature the community would want, I'm going to be working on it anyway

**Comment by vp642** [comment]
+1

**Comment by shu-mutou** [comment]
Duplicated with #4522.
