### ISSUE TITLE
Configmap data is not displayed properly compared to old dashboard

### ISSUE THREAD

**Issue by g-sree** [kubernetes/dashboard#4808]
##### Environment

```
Installation method: helm chart
Kubernetes version: 1.15.8
Dashboard version: Dashboard v2.0.0-rc2
Operating system: Ubuntu/Debian
Node.js version ('node --version' output): NA
Go version ('go version' output): NA
```

##### Steps to reproduce
Created a configmap with following config

```
{
    "kind": "ConfigMap",
    "apiVersion": "v1",
    "metadata": {
        "name": "gsree-test-configmap",
        "namespace": "test",
        "labels": {
            "app": "gsree-test-app",
            "chart": "gsree-test-chart"
        },
        "annotations": {
            "build.mydomain.io/number": "123456",
            "build.mydomain.io/timestamp": "2020-01-16T07:20:04Z",
            "build.mydomain.io/url": "https://buildkite.com/mydomain/component-deploy/builds/123456"
        }
    },
    "data": {
        "kubernetes-config-map.properties": "app.db.username = app_username\napp.db.host = app-db.cluster-xxxxxxxxx.region.rds.amazonaws.com\napp.db.readHost = app-db.cluster-ro-xxxxxxxxx.region.rds.amazonaws.com\napp.db.name = testdb\napp.db.port = 3306\napp.db.readPort = 3306\n"
    }
}
```

in both old dashboard and the new 2.x dashboard where the data display different in both

##### Observed result

In new dashboard the data was displayed as follows 
```
{
	"kubernetes-config-map.properties": "app.db.username = app_username\napp.db.host = app-db.cluster-xxxxxxxxx.region.rds.amazonaws.com\napp.db.readHost = app-db.cluster-ro-xxxxxxxxx.region.rds.amazonaws.com\napp.db.name = testdb\napp.db.port = 3306\napp.db.readPort = 3306\n"
}
```

##### Expected result
whereas in old dashboard the data display was more readable

```
kubernetes-config-map.properties: app.db.username = app_username
                                                                 app.db.host = app-db.cluster-xxxxxxxxx.region.rds.amazonaws.com
                                                                 app.db.readHost = app-db.cluster-ro-xxxxxxxxx.region.rds.amazonaws.com
                                                                 app.db.name = testdb
                                                                 app.db.port = 3306
                                                                 app.db.readPort = 3306
```

##### Comments
<img width="1599" alt="old_dashboard" src="https://user-images.githubusercontent.com/41133731/72691931-16f00180-3b7d-11ea-9675-bfd97344759e.png">
<img width="1593" alt="new_dashboard" src="https://user-images.githubusercontent.com/41133731/72691933-16f00180-3b7d-11ea-84da-44e8b2568ef9.png">

**Comment by floreks** [comment]
It's not a bug. It is how json editor displays raw json data. It looks the same as what you have provided in configmap during creation.

/close

**Comment by g-sree** [comment]
@floreks  Can this be added as a feature for better readability.....

**Comment by martin-walsh** [comment]
Request reopen. 

Formatting incorrectly is certainly a ui issue.

Config map entries may be files. Failure to respect newline chars, tab chars etc is a bug

**Comment by martin-walsh** [comment]
@floreks pls reconsider.

There's little purpose in a human readable ui that is not human readable

**Comment by floreks** [comment]
We are using external library to display formatted json/yaml strings. If you'd manually provide new lines instead of '\n' then it would be read properly. This is how json standard works. We do not want to change that and manually parse content.

**Comment by martin-walsh** [comment]
I understand, however I'm questioning whether you can make that decision unilaterally as you don't know what the format of the data will be.

**Comment by floreks** [comment]
I have checked our code and we can slightly manipulate the data before editor processes it.

![Zrzut ekranu z 2020-01-29 11-13-33](https://user-images.githubusercontent.com/2285385/73347792-7be7dd80-4288-11ea-88e0-6bed7b9f0730.png)

![Zrzut ekranu z 2020-01-29 11-13-39](https://user-images.githubusercontent.com/2285385/73347803-8013fb00-4288-11ea-8730-afa70e75e3e8.png)

That should do it.

**Comment by floreks** [comment]
We'll add the fix for that and graphs tomorrow.

**Comment by g-sree** [comment]
@floreks thanks for that.. That looks better in terms of readability.

**Comment by g-sree** [comment]
Thanks @floreks  looks good now
