### ISSUE TITLE
Dashboard does not work offline

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#481]
#### Issue details
Dashboard cannot be run offline because Roboto font and MD icons are loaded from the internet. 

http://fonts.googleapis.com/icon?family=Material+Icons
http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic

##### Steps to reproduce
1. Remove internet connectivity
2. Reload
3. Do some actions in the UI

##### Observed result
Sometimes some icons are not shown

##### Expected result
Works.

##### Comments

Any workaround for the browser?
![offline](https://cloud.githubusercontent.com/assets/7448799/13462401/80d3235c-e087-11e5-8e3b-94948ddf254c.png)

Kubernetes/Docker has also some problems with pulling Redis-Master, although the image is already on disk. I have not investigated yet

**Comment by bryk** [comment]
Yes, known problem. We should be inlining styles to make this work on intranets.
