### ISSUE TITLE
Strange message after creating of any resource

### ISSUE THREAD

**Issue by slavditore** [kubernetes/dashboard#4812]
##### Environment

```
Installation method: via YAML file
Kubernetes version: 1.17.0
Dashboard version: 2.0.0-rc2
Operating system: Windows 10
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Create or change deployment
##### Observed result

Got an informative message box
##### Expected result

Got only this message
![изображение](https://user-images.githubusercontent.com/52867621/72749430-b2f02c00-3bc2-11ea-9c78-218f76661df5.png)

**Comment by floreks** [comment]
Is it perhaps firefox?

**Comment by slavditore** [comment]
> Is it perhaps firefox?

Yes, it was gained on Firefox 72

**Comment by shu-mutou** [comment]
Following strange response body was found in firefox.
"\u001f�\u0008\u0000\u0000\u0000\u0000\u0000\u0004�\u0001\u0000\u0000��\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
In chrome, response body for same request was empty.
Both browser got response status 201. But Angular checks parsablity of response body if response type is JSON, so in firefox the strange response body causes error and alert dialog was shown.
We can observe this strange response body at `node_modules/@angular/common/fesm5/http.js L:1582 onLoad function`.

Also, I found a workaround, I will submit PR soon.

**Comment by floreks** [comment]
I know how to fix that. Leave it for now.
