### ISSUE TITLE
Node CPU-Usage diagramm shows wrong values

### ISSUE THREAD

**Issue by Herr-Sepp** [kubernetes/dashboard#4827]
##### Environment

```
Installation method: apply ...v2.0.0-rc2/aio/deploy/recommended.yaml
Kubernetes version:V1.17 AKS
Dashboard version: v2.0.0-rc2+0.g1ce7fa1
Operating system: Ubuntu 16.04
```

##### Steps to reproduce

Compare the CPU usage graph (node) with the Kubectl top node instruction

##### Observed result

When calling the page, the scaling is very wrong.

The displayed values are too small by a factor of 1000.
After 1-2 seconds the display changes and the values are only 10 times too small. 

See gif.
0.0000215 directly after calling up the page (F5)
0.0215 after 1 second

![CPUUsage](https://user-images.githubusercontent.com/10489458/73276322-c9ad0900-41e8-11ea-9d06-1276c235fc64.gif)

##### Expected result

what Kubectl top node really shows:
![image](https://user-images.githubusercontent.com/10489458/73276582-388a6200-41e9-11ea-8ee4-ec7bafcc1b2e.png)

so 0.215 CPU should be displayed as value.

##### Comments

Manages Kubernetescluster inside Microsoft Azure with Kubernetes 1.17
aks-engine v45

The CPU-Usage diagramm for pods updates itself to the correct values:
after 1 Second on 0.0001 it jumps to 0.1 CPU what is the same what  `kubectl top po ...` gives me back (100m)

**Comment by ibrajel** [comment]
@shu-mutou I would like to work on this issue

**Comment by floreks** [comment]
@ibrajel I work on this one and already have a fix prepared. It required both scraper and dashboard fixes.
