### ISSUE TITLE
Deploy Page - styling issue when shrinking page on IE

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#483]
##### Environment

```
Dashboard version: HEAD
Kubernetes version: HEAD
Operating system: Windows 7 x64
Browser: IE 11.0.9600.18161
```

##### Steps to reproduce

1. Go to deploy page.
2. Resize browser so width is very small.

##### Observed result

After shrinking the browser windows all elements are collapsed and overlap each other.

##### Comments
![image](https://cloud.githubusercontent.com/assets/2285385/13463442/8b53950a-e08c-11e5-81c3-5dd7345db4fc.png)

**Comment by bryk** [comment]
I assume fixed.
