### ISSUE TITLE
Cannot configure apiserver URL

### ISSUE THREAD

**Issue by marcolenzo** [kubernetes/dashboard#484]
I am instantiating the kubernetes dashboard as described in the README.md.

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard-canary.yaml
```
However when looking at the dashboard I am notified that a 500 error occured:

```
Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
```

When looking at the logs of the pod I can see the following:

```
2016/03/02 16:10:19 Starting HTTP server on port 9090
2016/03/02 16:10:19 Creating API server client for http://localhost:8080
2016/03/02 16:10:19 Creating in-cluster Heapster client
2016/03/02 16:10:25 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 172.17.35.0:47665
2016/03/02 16:10:25 Getting list of all replication controllers in the cluster
2016/03/02 16:10:25 Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
2016/03/02 16:10:25 Outcoming response to 172.17.35.0:47665 with 500 status code
2016/03/02 16:10:27 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 172.17.35.0:47664
2016/03/02 16:10:27 Getting list of all replication controllers in the cluster
2016/03/02 16:10:27 Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
2016/03/02 16:10:27 Outcoming response to 172.17.35.0:47664 with 500 status code
```

My environment consist of a master and 2 nodes setup on CentOS7. I am running the very latest version of Kubernetes (i.e. v1.2.0-alpha.8)

Kubectl is set properly on all nodes as the cluster-info shows:

```
[marcol@kube-master dashboard-canary]$  kubectl cluster-info
Kubernetes master is running at http://10.239.32.77:8080
KubeDNS is running at http://10.239.32.77:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at http://10.239.32.77:8080/api/v1/proxy/namespaces/kube-system/services/kube-ui
```

How can I tell the dashboard where the apiserver resides? I'd like to have the option to do so passing some parameter to its container. Compiling the entire thing doesn't seem as a viable option.

**Comment by bryk** [comment]
Specify `--apiserver-host=http://my-address:port` param of the container. See linked PR for example.

**Comment by marcolenzo** [comment]
Thank you @bryk . It worked.

**Comment by SimoTabtaoui** [comment]
pease @marcolenzo can you describe how did you solve the probleme. actually i run kubernetes on mesos and and the dashbord dont work
```
Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
```
if the solution is to modify --apiserver-host=http://my-address:port how can i do that, and in wich port please ?

**Comment by bryk** [comment]
@SimoTabtaoui How do you install the UI? There's the YAML install file that you can use in `kubectl create -f` https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml.
Then, inside the file, there is instruction on how to specify `--apiserver-host`

**Comment by SimoTabtaoui** [comment]
very big thanks @bryk . It worked.

**Comment by Linuxing** [comment]
@SimoTabtaoui  谢谢
