### ISSUE TITLE
CPU & Memory graphs : Take into account metric resolution time lower than 1min

### ISSUE THREAD

**Issue by grunlab** [kubernetes/dashboard#4844]
- What would you like to be added:
See issue https://github.com/kubernetes/dashboard/issues/4818
CPU & Memory graphs are currently not supporting metric resolution time lower than 1min (default)

- Why is this needed
Sometime, short CPU spikes at container level could be not visible with a 1min resolution time.
Decreasing the resolution time under 1min could make visible those spikes.

**Comment by floreks** [comment]
I was thinking how we could solve that without too much hassle. What if we would take an average or median if there are more points in a single minute timespan? This should give more consistent view of the usage and not make graphs unreadable if there would be too many points to display.

**Comment by grunlab** [comment]
Yes, you are right, doing an average or median of the point(s) would be a good starting point (the cpu spikes that would appear between the 1min default frequency will then be somehow taken into account)
