### ISSUE TITLE
'skipLoginPage' cookie set with SameSite=None but not Secure

### ISSUE THREAD

**Issue by BrianKopp** [kubernetes/dashboard#4845]
The `skipLoginPage` cookie is being set with SameSite=None, but without a Secure flag. While this works on current browsers, it will not work after next Tuesday with Chrome 80 being released. It's preventing some of our developers from accessing the site.

https://www.chromium.org/updates/same-site
https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
https://www.chromestatus.com/features/schedule

##### Environment

Running `2.0.0-rc2`, ingress handled via private load balancer -> nginx ingress with cert-manager 0.12 for SSL certificates.

```
Installation method: kubectl apply
Kubernetes version: 1.13 on EKS
Dashboard version: 2.0.0-rc2
Operating system: Mac OS X 15 + Chrome 79
Node.js version ('node --version' output): unrelated
Go version ('go version' output): unrelated
```

##### Steps to reproduce

Turn on chrome 80 experimental samesite flags. Try to navigate past the login page by clicking "Skip"

##### Observed result

Cannot get past login page

##### Expected result

Should be able to access dashboard using default dashboard role, skipping login successfully. `skipLoginPage` cookie set with acceptable settings.

##### Comments

I'm happy to contribute a PR for this if it's not too difficult.

**Comment by floreks** [comment]
Actually all our cookies should use `SameSite=strict`. External pages should not be allowed to access any of them.
