### ISSUE TITLE
Link from Pod Shell back to Pod is wrong

### ISSUE THREAD

**Issue by BrianKopp** [kubernetes/dashboard#4846]
After executing shell on a pod, it is difficult to navigate back to the pod's page. The link back to the pod gets me stuck in a bad loop trying to navigate away, but being prompted with a dialog over and over again.

##### Environment

```
Installation method:
Kubernetes version: 1.13 EKS
Dashboard version: 2.0.0-rc2
Operating system: Mac OS X 15 + Chrome 79
Node.js version ('node --version' output): Unrelated
Go version ('go version' output): Unrelated
```

##### Steps to reproduce

1. Load the dashboard.
2. Click "Pods" section from left-hand toolbar.
3. Click a pod.
4. Click the shell icon to execute shell in pod.
5. Click breadcrumb link back to specific pod
(here is where I get stuck)

##### Observed result

Shown popup with text:
Namespace conflict
Selected namespace is different than namespace of currently selected resource.
Do you want to stay on current page and change namespace from default to <podname>?

If I click Yes, then I get a 404 page with:
Unknown error (404)
pods "<name>" not found

If I click No, then I keep getting prompted with the popup.

##### Expected result

Navigate back to the pod page. The log viewer behaves this way correctly, just not the shell page.

##### Comments

When on the logs page (e.g. https://example.com/#/log/default/pod-name/pod?namespace=default&container=container_name), the link back to the pod page is https://example.com/#/pod/default/pod-name?namespace=default&container=container_name

When on the shell page (e.g. https://example.com/#/shell/default/pod-name/container_name?namespace=default), the link back to the pod page is https://dashboard.dev.bombbomb.io/#/pod/pod-name/container_name?namespace=default

I think it's just a bad link. I'd be happy to contribute a PR for this.

**Comment by floreks** [comment]
You are welcome to create a PR. It seems like an easy one to fix.
