### ISSUE TITLE
Internal error occurred: No metric client provided. Skipping metrics.

### ISSUE THREAD

**Issue by nicoclau** [kubernetes/dashboard#4852]
Hello, all please can you tell me how Dashboard get this error please?

I installed metrics server on Kubernetes provided by Docker on my local machine.

When we run 

kubectl.exe top no, it returns the data 

NAME             CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
docker-desktop   227m         11%    1304Mi          68%

The same with the pods.

I used the deployment with the commands
command:
        - /metrics-server
        - --kubelet-insecure-tls
        image: k8s.gcr.io/metrics-

Thanks 

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"metrics-server"},"name":"metrics-server","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"metrics-server"}},"template":{"metadata":{"labels":{"k8s-app":"metrics-server"},"name":"metrics-server"},"spec":{"containers":[{"args":["--cert-dir=/tmp","--secure-port=4443"],"image":"k8s.gcr.io/metrics-server-amd64:v0.3.6","imagePullPolicy":"Always","name":"metrics-server","ports":[{"containerPort":4443,"name":"main-port","protocol":"TCP"}],"securityContext":{"readOnlyRootFilesystem":true,"runAsNonRoot":true,"runAsUser":1000},"volumeMounts":[{"mountPath":"/tmp","name":"tmp-dir"}]}],"nodeSelector":{"beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64"},"serviceAccountName":"metrics-server","volumes":[{"emptyDir":{},"name":"tmp-dir"}]}}}}
  creationTimestamp: "2020-02-03T09:14:40Z"
  generation: 5
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
  resourceVersion: "313839"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/metrics-server
  uid: 9bd72344-4665-11ea-bd8f-00155d073c14
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: metrics-server
      name: metrics-server
    spec:
      containers:
      - args:
        - --cert-dir=/tmp
        - --secure-port=4443
        command:
        - /metrics-server
        - --kubelet-insecure-tls
        image: k8s.gcr.io/metrics-server-amd64:v0.3.6
        imagePullPolicy: Always
        name: metrics-server
        ports:
        - containerPort: 4443
          name: main-port
          protocol: TCP
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metrics-server
      serviceAccountName: metrics-server
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp-dir
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-03T09:26:08Z"
    lastUpdateTime: "2020-02-03T09:26:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-03T09:14:40Z"
    lastUpdateTime: "2020-02-03T10:09:02Z"
    message: ReplicaSet "metrics-server-6f48c898dd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

**Comment by maciaszczykm** [comment]
Do you also have metrics scraper deployed?

**Comment by nicoclau** [comment]
I have

NAME                                         READY   STATUS    RESTARTS   AGE
pod/coredns-6dcc67dcbc-6z569                 1/1     Running   1          2d23h
pod/coredns-6dcc67dcbc-cqw67                 1/1     Running   1          2d23h
pod/etcd-docker-desktop                      1/1     Running   1          2d23h
pod/kube-apiserver-docker-desktop            1/1     Running   2          2d23h
pod/kube-controller-manager-docker-desktop   1/1     Running   1          2d23h
pod/kube-proxy-tr96d                         1/1     Running   1          2d23h
pod/kube-scheduler-docker-desktop            1/1     Running   1          2d23h
pod/metrics-server-6f48c898dd-278kt          1/1     Running   0          20m

NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
service/kube-dns         ClusterIP   10.96.0.10     <none>        53/UDP,53/TCP,9153/TCP   2d23h
service/metrics-server   ClusterIP   10.98.60.206   <none>        443/TCP                  74m

NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/kube-proxy   1         1         1       1            1           <none>          2d23h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/coredns          2/2     2            2           2d23h
deployment.apps/metrics-server   1/1     1            1           74m

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/coredns-6dcc67dcbc          2         2         2       2d23h
replicaset.apps/metrics-server-6f48c898dd   1         1         1       20m

How do I install metrics scraper? 
Thanks :)

**Comment by nicoclau** [comment]
I removed command

command:
- /metrics-server
- --kubelet-insecure-tls

and changed to args:

 containers:
      - args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - /metrics-server
        - --kubelet-insecure-tls

Now I see the error 

020/02/03 10:43:47 Metric client health check failed: the server could not find the requested resource (get services dashboard-metrics-scraper). Retrying in 30 seconds.
2020/02/03 10:44:17 Metric client health check failed: the server could not find the requested resource (get services dashboard-metrics-scraper). Retrying in 30 seconds.

**Comment by nicoclau** [comment]
Ok I made it work.

kubectl.exe get svc -n kubernetes-dashboard

only returned 

kubernetes-dashboard        ClusterIP   10.109.131.22   <none>        443/TCP    2d20h

So I must have deleted dashboard-metrics-scraper service

I applied again the dashboard deployment.

Then I got the services : 
kubectl.exe get svc -n kubernetes-dashboard
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
dashboard-metrics-scraper   ClusterIP   10.105.139.91   <none>        8000/TCP   8m37s
kubernetes-dashboard        ClusterIP   10.109.131.22   <none>        443/TCP    2d20h

The graphs didn't display, but the error in the logs were gone.

I had to restart the dashboard to get the graph displayed.

I am with kubernetes with docker , I used the commands:

      - /metrics-server
        - --kubelet-insecure-tls

I know it is bad to use kubelet-insecure-tls on prod, what is the best solution there ?
I know it is about cert self signed...

Thanks

**Comment by maciaszczykm** [comment]
You should ask on core repo -> kubernetes/kubernetes

**Comment by kenperkins** [comment]
Perhaps this should be re-considered? Through debugging with @jacobwagner, we discovered that if the `dashboard-metrics-scraper` service has a named port, for example:

```yaml
spec:
   clusterIP: 10.3.196.36
   ports:
   - port: 8000
     name: http
     protocol: TCP
     targetPort: 8000
   selector:
     k8s-app: dashboard-metrics-scraper
   sessionAffinity: None
   type: ClusterIP
```

The metrics-server will be unable to connect, as the proxy client is hard-coded to not assume a named port.

The error is the same as above.

Per commentary in https://github.com/kubernetes/kubernetes/issues/20070 the named port must be part of the proxy request, i.e. `dashboard-metrics-scraper:http`, but as per https://github.com/kubernetes/dashboard/blob/5c5c73639a0a43df552ff839d8e358c2430b71f7/src/app/backend/integration/metric/sidecar/restclient.go#L49 this is not configurable.

**Comment by floreks** [comment]
To be honest I do not see a reason why this should be configurable. Metrics scraper config should be used as-is. There is no need to change that.

**Comment by kenperkins** [comment]
At least at present, `dashboard-metrics-scraper` is not included in the helm chart proposed in https://github.com/kubernetes/dashboard/pull/4502. Even if it is, the current implemtnation strikes me as brittle; simply adding a name to a port in the service spec would break this. I can see having it be defaulted to a value but I'm not sure I agree it should be completely hardcoded. 

Would you be willing to consider a code change?

**Comment by shu-mutou** [comment]
We can specify URL for dashboard-metrics-scraper with `--sidecar-host` option of dashboard. See [Dashboard arguments](https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md#arguments)

And we can use `http://[ip addr]:[port]/api/v1/namespaces/kubernetes-dashboard/services/dashboard-metrics-scraper:http/proxy/` for it, AFAIK.

Although I'm not familier with `helm`, does it not satisfy your requisites?

**Comment by floreks** [comment]
I do not want to add an argument that will be basically useless and only related to the name of the port name specified in service. For in-cluster communication, we have to assume that the configuration we provide will not be changed. I do not see a reason why the user would mess with the service prepared by us and add a name, if there is really no need to do that.

If the user decides to change the default configuration, then something might break and the user has to be aware of those changes. As @shu-mutou pointed out. There is already `--sidecar-host` argument that allows specifying how Dashboard should connect to the metrics scraper. We will not add another argument, just to allow adding a port name to the service that handles metrics scraper.

**Comment by kenperkins** [comment]
Thank you for the feedback. I will look at submitting a patch to https://github.com/kubernetes/kubernetes/issues/20070#issuecomment-174412662 which would implicitly resolve the problem that would have manifested this in the first place.

**Comment by jerryyanmj** [comment]
After reading the code, I think the problem is the following code snippet in restclient.go.

```go
// Get creates request to given path.
func (c inClusterSidecarClient) Get(path string) RequestInterface {
	return c.client.Get().
		Namespace(args.Holder.GetNamespace()).
		Resource("services").
		Name("dashboard-metrics-scraper").
		SubResource("proxy").
		Suffix(path)
}

// HealthCheck does a health check of the application.
// Returns nil if connection to application can be established, error object otherwise.
func (self inClusterSidecarClient) HealthCheck() error {
	_, err := self.client.Get().
		Namespace(args.Holder.GetNamespace()).
		Resource("services").
		Name("dashboard-metrics-scraper").
		SubResource("proxy").
		Suffix("/healthz").
		DoRaw(context.TODO())
	return err
}
```
For whatever reason, the sidecar client which connects to scraper could not pass the health check, hence unavailable when the real pod metric retrieval happens.  In my case, the metricClient is empty and the code error out with **"No metric client provided. Skipping metrics."**

```go
func (self *DataSelector) getMetrics(metricClient metricapi.MetricClient) (
	[]metricapi.MetricPromises, error) {
	metricPromises := make([]metricapi.MetricPromises, 0)

	if metricClient == nil {
		return metricPromises, errors.NewInternal("No metric client provided. Skipping metrics.")
	}

	metricNames := self.DataSelectQuery.MetricQuery.MetricNames
	if metricNames == nil {
		return metricPromises, errors.NewInternal("No metrics specified. Skipping metrics.")
	}

	selectors := make([]metricapi.ResourceSelector, len(self.GenericDataList))
	for i, dataCell := range self.GenericDataList {
		// make sure data cells support metrics
		metricDataCell, ok := dataCell.(MetricDataCell)
		if !ok {
			log.Printf("Data cell does not implement MetricDataCell. Skipping. %v", dataCell)
			continue
		}

		selectors[i] = *metricDataCell.GetResourceSelector()
	}

	for _, metricName := range metricNames {
		promises := metricClient.DownloadMetric(selectors, metricName, self.CachedResources)
		metricPromises = append(metricPromises, promises)
	}

	return metricPromises, nil
}
```

I simply used the sidecar-host parameter to provide a service URL which connects to the metric-scraper.
```yaml
args:
  - --auto-generate-certificates
  - --namespace=kubernetes-dashboard
  - --token-ttl=3600
  - --sidecar-host=http://dashboard-metrics-scraper:8000
```

**Comment by ankit9787** [comment]
@jerryyanmj 
where to use these sidecar -host parameter args  ?

**Comment by willzhang** [comment]
metricsScraper default not enabled.
```
helm intall dashboard --set metricsScraper.enabled=true
```
