### ISSUE TITLE
Accessing the logs is not straightforward.

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/dashboard#4869]
##### What would you like to be added
Hi, I would like the "logs"-section to be made more easily accessible.

##### Why is this needed
At this point, a user looks though the information of a pod, which contains also the "events", but it appears as the application-logs are not accessible through the Dashboard.. when the user expects to see them below the "Events" section (expects at least to see a clear option to enable them).
So it's not easy to find how to access the logs.

##### Comments
I am new to the Dashboard, I got it set-up the day before.
I was searching for the logs of the application I have deployed on Kubernetes and I could not find them in the UI.
I started thinking it was not possible to see them and I was ready to submit an issue, until I found in  other issues that it somewhere exists such an option.
After some trial and error, I was able to find them.

**Comment by floreks** [comment]
Dashboard is designed to show similar output as kubectl. In example pod details show information based on `kubectl describe`. 

Logs are normally accessed through a different command as you can i.e. watch them and they have a separate page for that. It is not something you can display in a similar way to events.

UX is very similar to google services as we are heavily relying on material design guidelines. It is a standard way of accessing them.

It seems that you are not very familiar with kubernetes and cloud provider interfaces. With time you'll learn what's what.

**Comment by LSmyrnaios** [comment]
Thanks for your reply.
<br/>
> ...they have a separate page for that. It is not something you can display in a similar way to events.

I understand that, but it would still be possible for the "console" showing the logs, to be placed there, in smaller size and scrollable. It could be not-expanded but still easily accessible for anyone to click on to watch.
Or it could be just a button named "Watch the logs", which would navigate you to the existing logs-page.
<br/>
> It seems that you are not very familiar with kubernetes and cloud provider interfaces...

I have previous experience with "[Portainer](https://www.portainer.io/)", where the access to the logs is much easier and more straightforward.

**Comment by floreks** [comment]
Logs viewer is too advanced to be shown on the same view as pods. That is not a good idea. It also requires more data, as pod can contain multiple containers, etc. This is something that has to be placed on a separate page. We have made a decision to show icons + tooltips for most actions and I have to admit that you are the first one to report that it is not intuitive in a few years of Dashboard.

Logs can be accessed in 2 ways. Through entry on the list view by clicking on more actions button, or by using actionbar icons. All actions possible to be executed for a resource are always put on the action bar. If you do not know what is the meaning of some icon, there is always a tooltip.

**Comment by LSmyrnaios** [comment]
> Logs viewer is too advanced to be shown on the same view as pods [...] requires more data [...] pod can contain multiple containers, etc This is something that has to be placed on a separate page.

Ok, I agree with that.
<br/>
> I have to admit that you are the first one to report that it is not intuitive in a few years of Dashboard.

I showed the Dashboard to a co-worker, very experienced with Portainer, but a first-timer in Dashboard.
The "more actions" button (3 dots) was easily spotted in the multiple-pods-view and could access logs from there.
But in the specific-Pod's-view, confusion came in and could not find how to see them.

Anyway, this issue is not about me now, I learned how to access them and do my job.
I just wanted to provide my feedback of how not-straightforward this is for new users, so that Dashboard can be improved.

Maybe you could add some documentation in the repository or in the website.

This issue can close.

**Comment by floreks** [comment]
Unfortunately from experience, I know that most people are not reading the documentation, so UI explanation there would do basically nothing.

I guess everything is just a matter of learning how to use new UI. For example, when first using GCP, I have had major issues finding what I wanted to configure or use. It gets better with time.
