### ISSUE TITLE
Locl: a tool to translate templates and code

### ISSUE THREAD

**Issue by feloy** [kubernetes/dashboard#4871]
https://github.com/loclapp/locl/

This new tool (developed by @ocombe  the long time creator and maintainer of the ngx-translate translation tool) just born. I did not test it yet, but I would be interested in testing to see if it could fix the problems we have to translate some of the dynamic terms of the interface. 

Are some of the translators interested that I share my future experience here? Or do you have in mind others tools?

**Comment by ocombe** [comment]
Let me know if you need help to implement this

**Comment by feloy** [comment]
@shu-mutou
  @atoato88
 @gochist
  @seokho-son
@hwdef
  @tanjunchen

**Comment by floreks** [comment]
As interesting as it sounds, I'd prefer not to use anything that is in the early stages for Dashboard. Best option would be to use something that comes out-of-the-box with angular itself.

**Comment by shu-mutou** [comment]
Very interesting! Thanks for this information! 🎉 I could not found such a lib before.

It seems to enable to collect strings that should be translated from ts files by `ng xi18n` in our `fix:i18n` task.

But this library is too young, also we need time to introduce this into our ts files and translate to each lang. I think we should try this after 2.0.0.

**Comment by feloy** [comment]
For sure, my intention is not to use this library for the 2.0.0 release or in a near future release, but instead to test if the library features cover the needs for the dashboard, and in the opposite help the library developers cover these needs.

**Comment by shu-mutou** [comment]
`locl` needs angular 9, and `ng update` needs LTS version of nodejs. We shuld to update nodejs to latest 12.x at first.

**Comment by maciaszczykm** [comment]
cc @floreks You have experience in Angular updates :)

**Comment by maciaszczykm** [comment]
I'd rather avoid this. Especially with the issue that has zero response.
