### ISSUE TITLE
Docker image not available in Docker Hub with latest release candidate

### ISSUE THREAD

**Issue by Constantin07** [kubernetes/dashboard#4880]
Hi,

Any idea why a new version `v2.0.0-rc4` is being released, doc page updated but the docker image on Docker Hub not yet available to pull ?

https://hub.docker.com/r/kubernetesui/dashboard/tags - the last is `v2.0.0-rc3` ...

Regards

**Comment by floreks** [comment]
Wait for travis to push the images.

/close
