### ISSUE TITLE
Kubernetes dashboard not responding

### ISSUE THREAD

**Issue by astragier** [kubernetes/dashboard#4895]
##### Steps to reproduce
I have deleted my release lauching `helm del --purge my-release`.

After some time (less than one minute), the dashboard was not responding anymore (continous loading wheel).

I deployed anyway my new release launching `helm install --name my-release`.
It succeeded but the dashboard still wasn't answering, until I got the error message. 

##### Environment
```
Installation method: Azure embedded
Kubernetes version: 1.14.6
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
Get https://my-cluster-dns.hcp.francecentral.azmk8s.io:443/api/v1/namespaces/default/configmaps: read tcp 10.244.0.22:40892->xx.xx.xx.xx:443: read: connection timed out

```

**Comment by floreks** [comment]
We don't have any official helm releases. All information about how to install and use Dashboard can be found on this repo. We do not provide support for anything else.

/close
