### ISSUE TITLE
Error trying to reach service: 'Forbidden'

### ISSUE THREAD

**Issue by Sumit789** [kubernetes/dashboard#4907]
Getting Issue with Latest Version (v2.0.0-rc5) 

Error trying to reach service: 'Forbidden'

Kubeadm Version:

root@k8s-master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by floreks** [comment]
Cluster configuration issue.

/close
