### ISSUE TITLE
Firefox can not login

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#4922]
AFAIK, firefox had worked fine in Jan, but I can't login now.

Router does not work with firefox.
`navigate(['overview'])` at [here](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/login/component.ts#L107) was called but not jump to overview page.

**Comment by floreks** [comment]
Will investigate that tomorrow.

**Comment by shu-mutou** [comment]
Bumping angular modules from 8.0.3 to 8.2.14 was not effective for this. But chrome works fine.

**Comment by Wilm0r** [comment]
Same here, I have to switch to chromium to get past the login screen..

**Comment by shu-mutou** [comment]
I also see this. Angular 9 did not seem to fix this.

**Comment by floreks** [comment]
Not sure why it does not work for you, but I have latest FF and on dev/prod it works just fine.

**Comment by Wilm0r** [comment]
I could reproduce it even in a Private Window, using Firefox 68 (latest ESR packaged in for example Debian).

I'd be surprised if it mattered, but the Dashboard instance is running in k8s from the v2.0.0-rc5 recommended.yaml.

**Comment by floreks** [comment]
This has been fixed on master so no release with the fix yet.

**Comment by shu-mutou** [comment]
I could confirm that my latest firefix v73 on ubuntu and windows works fine today. 🎉 
Yesterday, dependencies might not be installed perfectly in my dev environment. 🤔

**Comment by shu-mutou** [comment]
This fix will be released in rc6 or later.
