### ISSUE TITLE
Disable auth error notifications

### ISSUE THREAD

**Issue by erichweiler** [kubernetes/dashboard#4941]
This is for the dashboard v2.0.0-beta6.

Hi All,

I have configured a dashboard token identify that has read-only access to everything in the k8s installation *except* the secrets in each namespace.  When viewing the dashboard, the "notifications center" on the top right continuously fills up with errors of the like:

"system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard"
cannot list resource "secrets" in API group "" in the namespace "foo" 

This is "correct" in that we don't want access to secrets, but the dashboard seems very aggressive in trying to access those secrets, and it results in a very large number of errors.  At the rate of about 1 error per 10 seconds or so.  I don't see it in the documentation, but is there a way to either disable those error messages in the notification center, disable the notification center altogether or somehow otherwise stop the flow of errors?

Thanks for all the good work!

**Comment by floreks** [comment]
There is not way to disable them unfortunately. We need to allow only unique errors to appear and not stack them indefinitely. This should partially solve the issue. We might also add some switch on settings page to filter out auth errors from notifications panel.

**Comment by erichweiler** [comment]
Thanks!  I'll keep an eye on it for the future.

**Comment by floreks** [comment]
I'll actually keep that open as a feature request.

/reopen
