### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/dashboard#4943]
I tried setting up dashboard using this link: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui

But dashboard not running at

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

When requested this page in browser. I got below output.
kind	"Status"
apiVersion	"v1"
metadata	{}
status	"Failure"
message	"no endpoints available for service \"kubernetes-dashboard\""
reason	"ServiceUnavailable"
code	503

How to fix this?

**Comment by floreks** [comment]
Use readme from this repo. Someone has provided invalid link in k8s repo.

/close

**Comment by ukreddy-erwin** [comment]
Still the issue persists:

To deploy Dashboard, execute following command:

$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc5/aio/deploy/recommended.yaml
To access Dashboard from your local workstation you must create a secure channel to your Kubernetes cluster. Run the following command:

$ kubectl proxy
Now access Dashboard at:

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

**Comment by EraYaN** [comment]
For anyone wondering: The URL http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:443/proxy/ (so you add the port, seems to work at least for newer versions of kubernetes (1.19).
