### ISSUE TITLE
Kubernetes Dashboard not working.

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/dashboard#4944]
Yes, I read your readme.md multiple times.
Yes, I used the same steps as in your readme.

Please don't close the issue by keeping the comment to read the readme.md file.

THe dashboard url is giving this output below.

	
kind	"Status"
apiVersion	"v1"
metadata	{}
status	"Failure"
message	"no endpoints available for service \"kubernetes-dashboard\""
reason	"ServiceUnavailable"
code	503

**Comment by floreks** [comment]
Check the pod status. Show logs. Based on this information I can only close it. Issue template is there for a reason.

**Comment by ukreddy-erwin** [comment]
THe status is container creating for a long time.



curl http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/.
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503

----

kubernetes-dashboard   dashboard-metrics-scraper-76585494d8-pblkz   0/1     ContainerCreating   0          5m47s
kubernetes-dashboard   kubernetes-dashboard-5996555fd8-95ztc        0/1     ContainerCreating   0

**Comment by floreks** [comment]
`ContainerCreating` status means that there is an issue with your cluster. It is not related to Dashboard.

**Comment by floreks** [comment]
`ContainerCreating` status means that there is an issue with your cluster. It is not related to Dashboard. You need to debug first why your cluster is not able to finish the container creation, then if there will be any error with Dashboard itself you can reopen and paste logs from running/failed container.

For the kubernetes cluster debug support, try stackoverflow or kubernetes core repository.

/close

**Comment by tariqkipkemei** [comment]
Running this command:
curl http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

Getting this error:
Error trying to reach service: 'Proxy Timeout ( The connection timed out.  )'

what could be causing this?
