### ISSUE TITLE
How to connect to dashboard from network machine

### ISSUE THREAD

**Issue by uday1kiran** [kubernetes/dashboard#4954]
Kubectl proxy -- will start running the dashboard available at localhost..but when I kill the command it is stopping..And also is there anyway to make this dashboard available to access in the network.

**Comment by floreks** [comment]
This is not strictly related to Dashboard. You need to learn how to expose applications running in your cluster (any application). Dashboard is simply a web app and the same rules will apply to any other application that you'll want to expose.

We do not provide support for managing Kubernetes cluster here. Our documentation gives basic examples about how to expose Dashboard. More advanced configurations are up to the user and Kubernetes handles all of that, not Dashboard. You should check stackoverflow/kubernetes core repo.

/close
