### ISSUE TITLE
missing file in this hub kubernetes-dashboard.yaml

### ISSUE THREAD

**Issue by rajendraprasad9** [kubernetes/dashboard#4956]
missing file in this hub kubernetes-dashboard.yaml in the recommendation

**Comment by floreks** [comment]
Explain it better and give more information or close.

**Comment by rajendraprasad9** [comment]
File is not found

**Comment by floreks** [comment]
Still, no explanation. I have no idea what are you talking about. All deploy files are exactly where they should be. https://github.com/kubernetes/dashboard/tree/master/aio/deploy

/close
