### ISSUE TITLE
Kubernetes dashboard not accessible

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/dashboard#4968]
I have changed Dashboard service from CLusterIP to NodePort. Because of the thsis, I am able to access Dashboard using url: <masternode_IP>:<Node_Port_assigned> 

But this is working only in the master node.

When I try to access outside from a machine in the same LAN, I am getting "Page not found"

This is not the case with other services like databases, web apps, etc

**Comment by floreks** [comment]
Not related to Dashboard. This is a cluster configuration issue. Read Kubernetes documentation and learn how to expose applications properly.

/close

**Comment by ukreddy-erwin** [comment]
Definitely not a cluster issue.

Because other services are working.
Only dashboard not accessible

**Comment by floreks** [comment]
If the pod is running and you can access it from master node, then it is not related to the application itself. Applications running inside the cluster have nothing to do with how they are exposed. Services, ingresses, etc. are used for this and they are Kubernetes resources.

**Comment by ukreddy-erwin** [comment]
This is the most common issue and no solution till now.It is been posted in many forums by many people, but you are not willing to provide any basic tips also.

And of course, this is not cluster issue, as many other apps are being accessed correctly. Only issue with dashboard. 

Try yourself in a demo environment, even you will end up with same problem.

**Comment by floreks** [comment]
Let's look at this.

### Fresh kubeadm cluster
![Zrzut ekranu z 2020-03-02 12-55-06](https://user-images.githubusercontent.com/2285385/75674358-2dfa3700-5c85-11ea-83fd-44fd47b7325a.png)

### Accessing from my machine where the cluster is running
![Zrzut ekranu z 2020-03-02 12-53-27](https://user-images.githubusercontent.com/2285385/75674426-4702e800-5c85-11ea-9f62-628aa598a3cb.png)

### Accessing from my phone
![Screenshot (2 mar 2020 12_53_17)](https://user-images.githubusercontent.com/2285385/75674498-6ef24b80-5c85-11ea-95fe-1257e5fc8d0d.png)

It seems to work just fine when exposed using `NodePort`.
