### ISSUE TITLE
Investigate locale codes in golang.org/x/text/language

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#4973]
To provide likely locale we supported, invesitgate handling of locale codes in golang.org/x/text/language.

**Comment by shu-mutou** [comment]
[Match](https://github.com/kubernetes/dashboard/blob/4cab78cec824446427e7e3128dd713579d97f0ce/src/app/backend/handler/localehandler.go#L132) returns tag for locale specified by browser as followings:
en-> en Exact
de-> de Exact
fr-> fr Exact, Parent = und, Raw = fr Zzzz ZZ, Base = fr Exact, Region = FR Low, Script = Latn High, Extensions = []
ja-> ja Exact
ko-> ko Exact
zh-> zh Exact
zh-Hans-> zh-Hans Exact
zh-Hant-> zh-Hant Exact
zh-HK-> **zh-Hant-HK** Exact, Parent = zh-Hant, Raw = zh Hant HK, Base = zh Exact, Region = HK Exact, Script = Hant Exact, Extensions = []
zh-SG-> **zh-Hans-SG** Exact, Parent = zh, Raw = zh Hant HK, Base = zh Exact, Region = SG Exact, Script = Hans Exact, Extensions = []
**If the tag is Exact and does not have Extensions, we can use itself.**
**_If Angular 9 supports `zh-Hant-HK` and  `zh-Hans-SG`, we don't need to replace `Accept-Language` header._**

en-US-> en-u-rg-uszzzz Exact
de-DE-> de-u-rg-dezzzz Exact
fr-FR-> fr-u-rg-frzzzz Exact
ko-KR-> ko-u-rg-krzzzz Exact
fr-FR-> fr-u-rg-frzzzz Exact, **Parent = fr**, Raw = fr Zzzz ZZ, Base = fr Exact, Region = FR Low, Script = Latn High, Extensions = (u- rg-frzzzz]
zh-CN-> zh-u-rg-cnzzzz Exact, **Parent = zh**
zh-TW-> zh-Hant-u-rg-twzzzz Exact, **Parent = zh-Hant**, Raw = zh Hant ZZ, Base = zh Exact, Region = TW Low, Script = Hant Exact, Extensions = [u-rg-twzzzz]
**If the tag is Exact and has Extensions, we can use Parent ().**

sq-> en High
eo-> en High
en-GB-> en-u-rg-gbzzzz High
fr-CA-> fr-u-rg-cazzzz High, Parent = fr, Raw = fr Zzzz ZZ, Base = fr Exact, Region = FR Low, Script = Latn High, Extensions = [u-rg-cazzzz]
**If the tag is High, we can use Base ().**

ar-DZ-> de-u-rg-dzzzzz No
la-> de No, Parent = und, Raw = de Zzzz ZZ, Base = de Exact, Region = DE Low, Script = Latn High, Extensions = []
**Else, i.e. Low or No, we can use default(en)**

**Comment by shu-mutou** [comment]
To support base locales, revert following:
https://github.com/kubernetes/dashboard/compare/f020bb006c228859fa520020a3ddb848ffd01cff..1ac7dc838c6260a0a14cd1eedeeb8c447c4195e0

**Comment by shu-mutou** [comment]
```

	locales := handler.SupportedLocales
	tag, _, confidence := language.NewMatcher(locales).Match(tags...)
	base, _ := tag.Base()

	localeDir := ""
	switch confidence {
	case language.Exact:
		// Locales supported by dashboard, i.e. locale_conf.json, can get proper locale directory.
		// e.g. `de`, `fr`, `ja`, `ko`, `zh-Hans`, `zh-Hant`, `zh-Hant-HK`
		localeDir = handler.getSupportedLocaleDir(tag.String())
		if localeDir == "" {	
			// Although locale matches as exact, locales unsupported by dashboard explicitly	
			// are handled as `xx-u-rg-xxzzzz`.	
			// e.g. map `en-US` to `en`, `fr-FR` to `fr`, `ko-KR` to `ko`	
			//      tag.String() returns `en-u-rg-uszzzz` for `en-US`	
			// See more, https://godoc.org/golang.org/x/text/language#NewMatcher	
			// Related issue: https://github.com/golang/go/issues/24211	
			localeDir = handler.getSupportedLocaleDir(base.String())	
		}	
	case language.High:	
		// Locales unsupported by dashboard, but matched as High.	
		// e.g. map `en-GB` to `en`, `fr-CA` to `fr`	
		localeDir = handler.getSupportedLocaleDir(base.String())	
	}
```

**Comment by floreks** [comment]
It has been investigated and we got rid of this logic for now. I guess we can close.

/close
