### ISSUE TITLE
Add retry limit on failure or sync period configuration on api call that runs in the background

### ISSUE THREAD

**Issue by onesolpark** [kubernetes/dashboard#4974]
##### What would you like to be added

Add retry limit on failure or sync period configuration on api call that runs in the background

##### Why is this needed
Dashboard requests apiserver every 5 seconds to sync with the current state of the cluster
For example namespace list through `/api/v1/namespace`

While it may be useful for syncing with the current status of the cluster,
it may send too many(unnecessary) request to the apiserver and it may cause 
a lot of request when a lot of users access the dashboard.

**Comment by floreks** [comment]
You can configure polling time globally on settings view or disable it completely so it will only refresh on view change.

![Zrzut ekranu z 2020-03-04 11-42-20](https://user-images.githubusercontent.com/2285385/75871692-3c735a80-5e0d-11ea-84e5-2651dbb6aaad.png)


/close
