### ISSUE TITLE
Unable to switch containers in the terminal

### ISSUE THREAD

**Issue by huangcuiyang** [kubernetes/dashboard#4988]
##### Environment

```
Installation method:
Kubernetes version:  v1.16.2
Dashboard version: v2.0.0-beta8
Operating system: CentOS Linux 7
Node.js version ('node --version' output):
Go version ('go version' output): go1.12.10
```

##### Steps to reproduce

1. Deploy the kubernetes dashboard Deployment, NetworkPolicy, Service, etc.
2. Port-forward the deployment, mapping the --insecure-port to localhost:whatever
3. Select a Pod that has more than one container in it
4. Click "Exec" button to go to terminal
5. Terminal displays shell prompt for default container
6. Use drop-down arrow to switch to a different container in the Pod

##### Observed result

* A popup message appears that displays the message: Normal closure

##### Expected result

* switch containers and get in shell

**Comment by floreks** [comment]
Use latest version (`rc5` as of now). It was fixed in between`beta8` and `rc5`.

https://github.com/kubernetes/dashboard/releases

/close

**Comment by huangcuiyang** [comment]
bad news, it does't work after upgrade to v2.0.0-rc5. Also can not switch container in one pod.

**Comment by floreks** [comment]
I have tested it on the latest rc5 and did not find any issues. `normal closure` message is perfectly fine as it informs you that the connection to the previous container was closed properly. Either you have to wait a bit longer or this second container does not have any bash that we can use to exec into it.

![Peek 2020-03-12 15-27](https://user-images.githubusercontent.com/2285385/76532457-eb9bdb80-6476-11ea-8442-5ad16f351e0d.gif)
