### ISSUE TITLE
Able to show a additional display name for CustomResourceDefinition

### ISSUE THREAD

**Issue by dmvolod** [kubernetes/dashboard#5008]
It would be nice to have alternative display name for CustomResourceDefinition
A new additional 'display' filed to the CRD's 'spec.names' that need to be created.
It very useful, when CRD defines as short or common name and display name could be advanced name and entity.
If 'display' filed not defined, the 'name' filed will be displayed as implemented currently.

**Comment by maciaszczykm** [comment]
I'd like to avoid using an additional fields. What about using `spec.names.kind` as an alternative? We could switch between current and new display using settings.

**Comment by dmvolod** [comment]
@maciaszczykm thanks for response.
I seems to "spec.names.kind" is immutable" field, it would be nice to have additional 'display' field which will be flexible and easy to change. It's a very desirable feature for most CRDs use-cases.
Could you please to help with implementation.

**Comment by floreks** [comment]
#5016 will add feature to use `names.Kind` first instead of `objectMeta.name` as the display name when pinning. I think that's more than enough to be able to easily distinguish different CRDs.

**Comment by maciaszczykm** [comment]
<img width="208" alt="Zrzut ekranu 2020-06-24 o 11 56 57" src="https://user-images.githubusercontent.com/2823399/85534717-dc016680-b611-11ea-8eec-0e791e528ecf.png">

I think we can consider this as done.
