### ISSUE TITLE
Finish remaining FBT sheets

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#503]
#### Issue details
We should complete the remaining FBT sheets.

Missing:
- Replication Details
- Logs

Any comments on the process? Should we adapt or change something?

@floreks , @digitalfishpond @maciaszczykm @f-higashi 
please pick

**Comment by maciaszczykm** [comment]
I'm preparing tests for replication controller details view.

**Comment by maciaszczykm** [comment]
I'm preparing tests for logs view.
