### ISSUE TITLE
rc6 adds <base href="/"> which breaks running in a non-root path (works with rc5)

### ISSUE THREAD

**Issue by rpardini** [kubernetes/dashboard#5031]
##### Environment

```
Installation method: kubeadm
Kubernetes version: 1.17.2
Dashboard version: 2.0.0-rc6
Operating system: Ubuntu
```

##### Steps to reproduce
Deploy rc5. Make it work under a subpath (`/dash` via nginx in my case). Everything works. Deploy rc6, find `<base href="/">` in the HTML, does not work. Back to rc5, works.

##### Comments
Angular/webpack wizardry seems to inserting a <base href="/"> tag that causes dashboard to not work under a subpath. See attached screenshots.
RC6 is broken:
![rc6-broken (2)](https://user-images.githubusercontent.com/639959/77641435-5c092900-6f5c-11ea-9b40-9352e37d411d.png)

RC5 actually works!
![rc5-ok (2)](https://user-images.githubusercontent.com/639959/77641444-5f9cb000-6f5c-11ea-8ac0-1ac8efc1b9a7.png)

**Comment by floreks** [comment]
Already fixed. Check closed issues/prs before opening.

/close
