### ISSUE TITLE
Unknown Error (no error data avaialble) in browser after idle period

### ISSUE THREAD

**Issue by Constantin07** [kubernetes/dashboard#5032]
##### Environment

```
Installation method: Helm chart
Kubernetes version: 1.14
Dashboard version: v2.0.0-beta8+0.g4275399
Operating system: EKS Optimised Amazon Linux
Browser: Chrome Version 80.0.3987.149 (Official Build) (64-bit)
Node.js version ('node --version' output):
Go version ('go version' output):
```
Note: Using official docker images.

##### Steps to reproduce
Open dashboard and leave the tab in browser inactive for some period of time.

##### Observed result
Getting: Unknown Error, No error data available. See screenshot below.

##### Expected result
Not getting this error.

##### Comments
If I do refresh the page - same issue, I need to click on some resource on the left pane to get it working.

![image](https://user-images.githubusercontent.com/11664677/77641709-66272980-6f54-11ea-87c7-e137631c533f.png)

**Comment by floreks** [comment]
Use latest version. There were many fixes between beta and rc6.

/close
