### ISSUE TITLE
Dashboard causes high CPU/load on apiserver when there are a lot of configmaps

### ISSUE THREAD

**Issue by jsmilani** [kubernetes/dashboard#5034]
##### Environment

```
Installation method: running docker image kubernetesui/dashboard:v2.0.0-rcX
Kubernetes version: 1.16.7
Dashboard version: v2.0.0-rc5 and v2.0.0-rc6
Operating system: centos 7.5
Node.js version ('node --version' output): na
Go version ('go version' output): na
```

##### Steps to reproduce

1. Create around 600 configmaps in a given namespace. Each configmap should have roughly 200KB of data (this is helm chart data and it is pretty big).
2. In Kubernetes Dashboard navigate to that namespace and visit config maps.

##### Observed result

The configmaps don't load on the screen, only see the spinner circle. On the backend the kube-apiserver will use over 200% cpu and after a minute or so starts to print errors in the logs like:
```
E0326 15:26:03.240227       1 wrap.go:39] apiserver panic'd on GET /api/v1/namespaces/kube-system/configmaps
I0326 15:26:03.240354       1 log.go:172] http2: panic serving 10.11.82.15:47726: killing connection/stream because serving request timed out and response had been started
```

The high cpu on the apiserver persists until you navigate away from the configmaps page and wait about a minute for all the timeouts to finish.

##### Expected result

It renders the first page of configmaps and apiserver CPU/load remains normal.

##### Comments

We use helm and helm creates a configmap record for every deploy and we have a lot of services and old versions are held for a long time until configmaps grow the point that the dashboard stops displaying them and causing apiserver problems which effects nearly everything using the apiserver. There is a chance it is a problem on the apiserver side but since I can do `kubectl -n $NAMESPACE get configmaps` and it returns in a timely manner without cpu spike I think it is something specific the dashboard is doing. I am hoping someone can help debug this from the dashboard perspective and see if it is the dashboard or provide information on how it is the apiserver's fault so I can report the bug there.

**Comment by floreks** [comment]
Increase CPU and memory limits for Dashboard. It has to load all config maps from apiserver on the backend. There is no way to avoid that.

**Comment by jsmilani** [comment]
I am not seeing memory or cpu issues on dashboard itself and we don't have limits on apiserver where we actually see the cpu issues.

Again, I don't know exactly what dashboard is asking from apiserver, but I can only reproduce this problem with the dashboard and not kubectl. If I report this to kubernetes core with reproduction steps that include using the dashboard I am concerned they will turn around and say this is a dashboard issue. To avoid more finger pointing I am just trying to isolate the problem as best as I can. I tried `kubectl -n kube-system get configmaps -o yaml` and it is pretty slow (takes about 30s) but the apiserver returns the results and CPU goes up to about 150% but load is relatively normal. When the dashboard tries it goes up to 250% or higher (probably capped by the system) and system load skyrockets. Are there any specific parameters you suggest I try when running `kubectl get configmaps` to simulate what the dashboard is requesting?

Is it plausible the amount of time it takes for a response is causing the dashboard to retry over and over and possibly causing duplicate requests happening simultaneously?

**Comment by floreks** [comment]
I'd suggest increasing or disabling refresh time for resources in settings. Requests will overlap and every new request will cancel the old one. Cancel will only be on the frontend side, but backend part will still try to finish them. This would be similar to running kubectl in new console every X sec.

**Comment by jsmilani** [comment]
@floreks I dropped the auto-refresh time to 0 so it never refreshes and that solved the load issue. The page takes about 35 seconds to render so I can probably raise it to 40-60s. Based on this behavior, if it was overlapping refreshes every 5 seconds then there would be at least 7 overlapping requests before it first renders, but as requests stack and load goes up it may never actually be able to complete the first request. This theory matches my observations since the page never did load and causes endless high cpu on the apiserver.

I am not thrilled about having all resources having the same high refresh time since it is only configmaps in this one namespace. I could see other resources having similar problems for any requests that take more than 5s since that is the default auto-refresh time.

I think it is reasonable to keep this bug open with the requested solution that refreshes for a given resource do not overlap because regardless of the resource if a request is in flight there is no point in requesting that information again until the previous request completes. I assume it is safe if 2 different resources overlap, but not 2 refreshes for the same resource.

**Comment by floreks** [comment]
This is something that would be solved by introducing either WebSockets or k8s controllers and cache informers. We will most likely not add an option to set refresh time per every resource. We've already got an issue for WS, so I will close this one.

https://github.com/kubernetes/dashboard/issues/2541

/close
