### ISSUE TITLE
issue with sign in 

### ISSUE THREAD

**Issue by lordcf** [kubernetes/dashboard#5035]
I have a CFCR cluster deployed  ,over  that I have deployed kubernetes dashboard as an application using the alternative.yml available in this repo.
https://github.com/kubernetes/dashboard/blob/master/aio/deploy/alternative.yaml
I created an ingress to expose the application externally over internet. My ingress file looks like:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: dashboard-ingress
spec:
  rules:
  - host: kubo-console.****.*****.net
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 9090
        path:

 Dashboard gets deployed successfully and i try to sign in with the admin token but nothing  happens.

**Comment by floreks** [comment]
I believe you are exposing it over HTTP instead of HTTPS. That is why login will not work. It is insecure. Works as designed and described in the documentation.

/close
