### ISSUE TITLE
Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper)

### ISSUE THREAD

**Issue by lordcf** [kubernetes/dashboard#5037]
deployed dashboard with cluster IP service and ingress
ingress file 👍 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: dashboard-ingress
spec:
  rules:
  - host: kubo-console.*****.net
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 8443
        path:

deployment.apps/kubernetes-dashboard logs

2020/03/27 12:42:53 Starting overwatch
2020/03/27 12:42:53 Using namespace: kubernetes-dashboard
2020/03/27 12:42:53 Using in-cluster config to connect to apiserver
2020/03/27 12:42:53 Using secret token for csrf signing
2020/03/27 12:42:53 Initializing csrf token from kubernetes-dashboard-csrf secret
2020/03/27 12:42:53 Empty token. Generating and storing in a secret kubernetes-dashboard-csrf
2020/03/27 12:42:53 Successful initial request to the apiserver, version: v1.15.5
2020/03/27 12:42:53 Generating JWE encryption key
2020/03/27 12:42:53 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
2020/03/27 12:42:53 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
2020/03/27 12:42:53 Initializing JWE encryption key from synchronized object
2020/03/27 12:42:53 Creating in-cluster Sidecar client
2020/03/27 12:42:53 Auto-generating certificates
2020/03/27 12:42:53 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
2020/03/27 12:42:53 Successfully created certificates
2020/03/27 12:42:53 Serving securely on HTTPS port: 8443

**Comment by floreks** [comment]
I don't see any issue or question here. This is error that suggests you have configuration issue. Either scraper is missing, not running properly, metrics-server is missing, etc.

/close

**Comment by sguidos** [comment]
I am confused, sorry.  If, by default, metricsScraper.enabled=false and metrics-server.enabled=false, why would the dashboard be trying to connect to the dashboard-metrics-scraper?

**Comment by floreks** [comment]
You are probably referring to the helm chart. It seems like it skips the installation of both metrics scraper and server, but does not update `metrics-provider` flag to `none`.
