### ISSUE TITLE
Please show more log lines by default and/or allow this to be changed

### ISSUE THREAD

**Issue by cameronbraid** [kubernetes/dashboard#5043]
Currently I use kubernetes dashboard to diagnose issues with pods, and quite often I miss the error that is reported in the logs because the dashboard doesn't show enough lines.

There is the download logs option, however that requires me to save it as a file, then open the file in a local editor, then remember to delete the file at some point.

Ideally I would be able to define the number of log lines to show in the settings panel.   Alternatively a default of more like 2000 would be helpful

Another option could be to add a "view" button to the download logs popup, and open that in a new tab, instead of forcing a file download.

**Comment by cameronbraid** [comment]
Another solution to this could be to do logging more like how tekton dashboard, or openshift webconsole do it.  I can have the page open and the log lines are streamed to the browser and you dont miss lines.

**Comment by floreks** [comment]
Logs are paginated. You can use buttons on the bottom to go to the next lines or go back. In the menu you also have a refresh button that every X seconds (defined in settings) refreshes the logs. This will stay as is. There are sometimes very big log files that have to be paginated in order not to crash the frontend.
