### ISSUE TITLE
Dashboard does not function with documented installation procedure

### ISSUE THREAD

**Issue by SrslyJosh** [kubernetes/dashboard#5047]
##### Environment

```
Installation method: As described in README.md
Kubernetes version: 1.15
Dashboard version: v2.0.0-rc7
Operating system: Amazon Linux
```

##### Steps to reproduce

Follow the documented installation instructions for installing and accessing dashboard:

1. `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc7/aio/deploy/recommended.yaml`
2. `kubectl proxy`
3. Visit http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

##### Observed result

No data in dashboard. Dashboard error messages complain of insufficient access to the kubernetes API, e.g.: `secrets is forbidden: User "system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard" cannot list resource "secrets" in API group "" in the namespace "default"`

##### Expected result

I expected to see data in the dashboard.

**Comment by floreks** [comment]
You have to provide the token that has access to those resources.

/close

**Comment by SrslyJosh** [comment]
@floreks I'm not sure how to explain this differently...but the installation procedure in your README, under "Getting Started" does not produce a functional install.

> You have to provide the token that has access to those resources.

Then that should be documented in the README, under "Getting Started", or just link StackOverflow, because that's where people who follow the directions under "Getting Started" end up finding out how to actually make the dashboard work.

I'm not trying to be a dick here, I'm trying to tell you that your README doesn't make it clear what needs to happen to have a functioning dashboard.

**Comment by floreks** [comment]
You mean something like this?
![image](https://user-images.githubusercontent.com/2285385/79915704-c14f1d80-8427-11ea-8235-3697398636a0.png)

and [this](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md#creating-sample-user)?
![image](https://user-images.githubusercontent.com/2285385/79915774-e04daf80-8427-11ea-8e24-69323e70f3b1.png)


Dashboard is fully functional after installation. It's up to the user to decide how to handle authentication and/or create user with proper privileges to log in. Steps to create admin user are also clearly available in the documentation.
