### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by cameronbraid** [kubernetes/dashboard#5048]
```
panic: send on closed channel
goroutine 527 [running]:
github.com/kubernetes/dashboard/src/app/backend/handler.handleTerminalSession(0x1984000, 0xc0000dd360)
	/home/travis/build/kubernetes/dashboard/src/app/backend/handler/terminal.go:205 +0x43a
created by gopkg.in/igm/sockjs-go.v2/sockjs.(*handler).sockjsWebsocket
	/home/travis/gopath/pkg/mod/gopkg.in/igm/sockjs-go.v2@v2.0.1/sockjs/websocket.go:31 +0x337
```

##### Environment
Kubernetes version: v1.17.2
Dashboard version: kubernetesui/dashboard:v2.0.0-rc7

##### Steps to reproduce
Not sure, I think it was when navigating from a shell window to the pod list

**Comment by floreks** [comment]
Seems to be related to #5064. Should be fixed by #5066. Reopen if it occurs again after we release `v2.0.0`. Should be done by the end of this week.

/close
