### ISSUE TITLE
the found the problem when I try https://www.katacoda.com/courses/kubernetes/getting-started-with-kubeadm#

### ISSUE THREAD

**Issue by GuoxiangZu** [kubernetes/dashboard#5049]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Unknown Server Error (502):
```
No error data available
```

**Comment by GuoxiangZu** [comment]
https://www.katacoda.com/courses/kubernetes/getting-started-with-kubeadm# It is timeout, then in the dashboard I found the 502 problem.

**Comment by floreks** [comment]
Also, it refers to `v1` which is deprecated.
