### ISSUE TITLE
System testing

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#505]
#### Issue details
We should start thinking about performance/system test. 

I suggest that we only test the performance of the backend. We can add prometheus to measure the API duration (it is quite simple)

We could run the normal selenium click tests and print out the 5 slowest API calls at the end (as far as I remember, this is done in core). 

However, the dataset is quite limited of the normal click tests. So we should do one extra test with a larger dataset. Could be outside of normal CI.

Any opinions?

@maciaszczykm , @floreks , @digitalfishpond , @f-higashi , @batikanu

**Comment by batikanu** [comment]
First of all, we can use our existing integration test stories to measure performance or create new ones (ex. for load tests)
We can use [browser-perf](https://github.com/axemclion/browser-perf) to collect the metrics from the browsers during running integration tests and use [protractor-perf](https://github.com/axemclion/protractor-perf) to create performance checks by instrumenting existing integration tests with it.

**Comment by cheld** [comment]
We can do like in core:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/metrics/metrics.go


https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go

**Comment by cheld** [comment]
What are the scenarios we see as performance critical? Suggestions?

e.g. 100 RCs or 1000 events, or something else?

**Comment by bryk** [comment]
Closing as stale.
