### ISSUE TITLE
CPU graph in infinite 'wobble' loop

### ISSUE THREAD

**Issue by cameronbraid** [kubernetes/dashboard#5050]
Dashboard v2.0.0-rc7+0.gdf23c19
 
A picture is work a thousand words

![graph-wobble](https://user-images.githubusercontent.com/672405/78418644-d25b0900-7689-11ea-9163-4a179de14f47.gif)

It doesn't always happen, but fairly often

**Comment by cameronbraid** [comment]
resizing the window sometimes fixes it, sometimes breaks it

**Comment by maciaszczykm** [comment]
1. What browser are you using?
2. Which k8s version are you using?

**Comment by cameronbraid** [comment]
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Using Chrome 80 on OSX

https://www.whatsmybrowser.org/b/2WGUV

**Comment by niorg** [comment]
I experience the same issue with Kubernetes 1.18.1 and Safari on MacOS.

**Comment by floreks** [comment]
Did you by any chance change metrics scraper configuration?

**Comment by cameronbraid** [comment]
No, I didnt change the metrics scape config.

It looks to me like its the graphing library in a loop trying automatically layout the axis

It seems to happen at the point between it animates between showing the labels horiz vs at an angle

If I slowly change the width of the browse to scale the chart this point it causes it to happen, and if I continue a little but beyond that point, they stabilise

![Apr-16-2020 21-54-26](https://user-images.githubusercontent.com/672405/79453343-eceb9580-802c-11ea-857b-a56b10556538.gif)

**Comment by floreks** [comment]
This is indeed an issue within chart library during size change.

https://github.com/swimlane/ngx-charts/issues/349

We can't fix this on our side, so we have to close this.

**Comment by cameronbraid** [comment]
Why not keep the issue open to track that the chart library needs to be upgraded once the bug is fixed ?

**Comment by floreks** [comment]
@cameronbraid we've got a bot that tracks all our dependencies and updates them whenever a new version comes out ([like here](https://github.com/kubernetes/dashboard/pull/5012)). If it will ever be fixed on their side, an automatic dependency update will fix it on our side also. There is no need to keep it open as there is nothing we can do about it. It's not directly our issue.

**Comment by cameronbraid** [comment]
Ok, thanks for the explanation

**Comment by ysaakpr** [comment]
I agree its not a direct issue, are there any client-side `hacks` possible? the https://github.com/swimlane/ngx-charts/issues/349 have opened three years ago and no triage on that shows that it's very likely to be closed soon. What would be the other plans in that case? Can we use another library or any short term fix possible?

**Comment by ysaakpr** [comment]
`rotateXAxisTicks: false`can make the automatic ticks rotation based on size, for time being we can make this as false till the issue fixed.

**Comment by floreks** [comment]
> rotateXAxisTicks: false can make the automatic ticks rotation based on size, for time being we can make this as false till the issue fixed.

I have tried multiple workarounds already and none of them worked.

As a manual workaround, for now, it's best to simply resize the window so it's not in between 2 view breakpoints.

**Comment by proea** [comment]
Still have same issue in v2.6.1 / v2.7.0
Browser: Chrome Version 107.0.5304.121 (Official Build) (arm64)
macOS: 12.6 (21G115), M1 Max

**Comment by danieltaub96** [comment]
Is this issue planned to be fixed,
we got multiple clusters and all the dashboards have this flickering effect, which can cause dizziness

**Comment by pierluigilenoci** [comment]
Perhaps many people involved in this problem have yet to notice that [this bug is not directly attributable](https://github.com/kubernetes/dashboard/issues/5050#issuecomment-614607026) to the dashboard code but to the graph framework used (`ngx-charts`). 🤷🏻‍♂️ 

So if you want it to be solved, you have to go and discuss it with the framework maintainers mentioned above, specifically in this issue: https://github.com/swimlane/ngx-charts/issues/349. 🚀 

FYI @danieltaub96 @proea @ysaakpr @niorg 👀

**Comment by pierluigilenoci** [comment]
@floreks in [this comment](https://github.com/swimlane/ngx-charts/issues/349#issuecomment-1089408017), a dirty workaround is explained to solve the problem. 
It may make sense, considering how much the framework has been in near disrepair.
