### ISSUE TITLE
"error in cryptographic primitive" after kubernetes reset

### ISSUE THREAD

**Issue by SteveTarter** [kubernetes/dashboard#5051]
##### Steps to reproduce

1. Use Dashboard to examine existing Kubernetes cluster in Chrome for Windows. 
2. From Docker for Windows Settings page, press "Reset Kubernetes Cluster"
3. Start re-installing new cluster, including this dashboard.
4. Attempt to log on to dashboard results in "Internal Server Error (500)" with added message "square/go-jose: error in cryptographic primitive"

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

##### Comments
If left alone for 30 minutes of so, I eventually get the logon screen, and can logon with token.  I can usually immediately logon using Incognito mode, but I have gotten locked out from there as well when I have been tearing down clusters while validating installation procedures.

**Comment by floreks** [comment]
Deprecated Dashboard version.

/close
