### ISSUE TITLE
Error trying to reach service: 'dial tcp 10.88.0.4:8443: connect: no route to host' on Fedora with crio

### ISSUE THREAD

**Issue by c3d** [kubernetes/dashboard#5053]
##### Environment

```
Installation method: Bare metal, kubeadm init
Kubernetes version: 1.18.0
Dashboard version: v2.0.0-rc7
Operating system: Fedora 32
Node.js version ('node --version' output): v12.16.1 (initially not installed)
Go version ('go version' output): go version go1.14 linux/amd64
```

##### Steps to reproduce

1.  dnf install -y cri-o (if installing docker, it does work). This provides a default CNI network as 10.88.x.y with 100-crio-bridge.conf  200-loopback.conf
2. Add Kubernetes repos fromhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64, and install kubeadm
3. kubeadm init --pod-network-cidr=10.244.0.0/16, with the intent to use flannel
4. Deploy flannel with kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
5. Verify that kubernetes is working well enough to deploy Jenkins with NFS storage
6. Deploy Dashboard with kc apply -f   https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc7/aio/deploy/recommended.yaml 
7. Add ClusterRoleBinding and ServiceAccount
8. Run kubectl proxy
9. Access http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

Note that the symptoms seem:
* Identical with or without flannel
* Different when installing docker instead of CRIO (with Docker, I seem to get the expected results)

##### Observed result

The loaded page shows

```
Error trying to reach service: 'dial tcp 10.88.0.6:8443: connect: no route to host'
```

The 10.88 is defined by `/etc/cni/net.d/100-crio-bridge.conf` which contains:

```
{
    "cniVersion": "0.3.1",
    "name": "crio-bridge",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "hairpinMode": true,
    "ipam": {
        "type": "host-local",
        "routes": [
            { "dst": "0.0.0.0/0" },
            { "dst": "1100:200::1/24" }
        ],
        "ranges": [
            [{ "subnet": "10.88.0.0/16" }],
            [{ "subnet": "1100:200::/24" }]
        ]
    }
}
```

I confirmed that by changing the network in that page, I get a different error message, so this is the source for the network being used.

##### Expected result

With docker, at that stage, I get a login page, and then a working dashboard. The ServiceAccount and ClusterRoleBindings are only necessary to get data on the page, but the page shows up even when they are not set.

##### Comments

I have tried to remove the `100-crio-bridge-conf` file. In that case, I get a different error message (a timeout if memory service me well), but Dashboard is still unable to reach the service.

**Comment by floreks** [comment]
We can't really help you with cluster configuration. If you'll create i.e. a busybox pod and try to access apiserver through the service you'll get the same results. This is a networking issue in your cluster. Our app requires that in-cluster networking works properly and pods can reach apiserver through default kubernetes service. If you have issues with configuration, you should ask on StackOverflow or K8S core repo. 

/close
