### ISSUE TITLE
Dashboard liveness failed

### ISSUE THREAD

**Issue by oopsoh** [kubernetes/dashboard#5054]
kubernetes version: v1.15.11
dashboard version: v2.0.0-beta4

Question:
    After the first installation is complete, they can be accessed normally, and the dashboard page cannot be accessed after two days.

    describe pod show info:
     Liveness probe failed: Get https://172.30.67.9:8443/: dial tcp 172.30.67.9:8443: connect: connection refused.
     
     IP can be pinged, no useful information is displayed in pod logs.

    Do I need to specify api-server-host to access api-server in https.
     
     Thanks.

**Comment by floreks** [comment]
I have no idea what is the issue here.

**Comment by oopsoh** [comment]
I want to know, if the api-server-host parameter is not specified, how does the dashboard automatically discover the api-server

**Comment by floreks** [comment]
This part is on `client-go` side. It uses in-cluster api-server service discovery to access the api-server.

https://github.com/kubernetes/client-go/blob/4b490f30cab2b67e0e2f6a642889525f37a0f1cb/rest/config.go#L447-L481

**Comment by oopsoh** [comment]
thanks，I increased the health check time to five minutes, and found that the dashboard startup process is slow, which can make the dashboard pod start normally, but I access the dashboard through api-server, the page loads slowly, and observe the dashboard logs, requests The api-server interface is also very slow, the dashboard page is still loading, the pod has been automatically restarted, the pod does not limit resources, but it is automatically restarted

![image](https://user-images.githubusercontent.com/20790067/78856675-f20f7a00-7a59-11ea-9c76-01df0f4d6ecb.png)

**Comment by oopsoh** [comment]
almost 7m 
`
2020/04/09 05:15:57 Generating JWE encryption key
2020/04/09 05:15:58 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
2020/04/09 05:15:58 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
2020/04/09 05:21:00 Initializing JWE encryption key from synchronized object`

**Comment by oopsoh** [comment]
There is no resource limitation in the yaml installation file of the dashboard. I changed to nodeport to access, and added resource limitation to increase the required resources of the dashboard. Now I can access the dashboard normally.
