### ISSUE TITLE
Internal error occurred: No metric client provided. Skipping metrics.

### ISSUE THREAD

**Issue by edselwang** [kubernetes/dashboard#5060]
hi~
I installed the dashboard by following the document: https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md

I have some promblem and wonder if anyone here could help me.
**I can not get metric information in dashboard**:
![1](https://user-images.githubusercontent.com/63399542/78891248-c44a2580-7a99-11ea-8db0-1b4dc0f8f679.png)
![2](https://user-images.githubusercontent.com/63399542/78891254-c7ddac80-7a99-11ea-9f75-7067ec2e6de8.png)

I have installed the metric server, and I think it work.
![3](https://user-images.githubusercontent.com/63399542/78891292-dd52d680-7a99-11ea-9e3b-bf8f426d8099.png)

and what's more? there are some error infor in the log:
![4](https://user-images.githubusercontent.com/63399542/78891358-02dfe000-7a9a-11ea-85fd-0b64f293448b.png)

I don't know why this happened, and how I can solve it.

**Comment by edselwang** [comment]
I had check the exist isuue: #4121 and #4088, because I am not build by `yaml` or something like `helm`, so I don't have a `deployment`.

**Comment by floreks** [comment]
This is not the whole log. The beginning is the most important where it tries to find the `metrics-scraper`. Basically you need `metrics-server` and `metrics-scraper` to be running in your cluster. `metrics-scraper` is bundled inside our deployment yamls, so it should work fine. Restart dashboard pod and show initial logs + logs of the `metrics-scraper`.

**Comment by edselwang** [comment]
@floreks hi, floreks. Because I use a `minikube` and build dashboard by following the [Developer Guide](https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md) in my server which installed the `minikube`. So I **don't** have a dashboard pod or anything other. I have installed the `metrics-server` and I can use `kubectl top`  to get metric information. But I haven't installed the `metrics-scraper`, so the problem is that I should install the `metrics-scraper` first? Is that any doc about how to install it? Thanks a lot.

**Comment by floreks** [comment]
You are running dev build? This changes everything. It's much harder to set it up properly then.

**Comment by edselwang** [comment]
Yes, I want to do some feature development based on dashboard. Are there any documents I can refer to. I think it's important for developers. @floreks

**Comment by floreks** [comment]
It's not. To enable metrics on dev you need to:

1. Install metrics scraper in your cluster
2. Do a port-forward of metrics server to your local machine running Dashboard

It was something like
"kubectl port-forward -n <namespace> <metrics-scraper-service> <port>"

Port that should be used is somewhere in the deployment yamls and in code.

**Comment by edselwang** [comment]
Great, I will try it later, thank you, floreks.

**Comment by edselwang** [comment]
What's more, is there any documents about how to install `metrics scraper`?

**Comment by floreks** [comment]
As I have already mentioned, it is bundled inside our deployment files. Everything is on this repository

**Comment by edselwang** [comment]
Great, I know how to do it now, thank you~ @floreks

**Comment by fauzan-n** [comment]
Just noticed in the helm chart , the default value of **metricsScraper.enabled** is **false**
