### ISSUE TITLE
When accessing via Ingress the Kubernetes Dashboard hijacks the ingress for all my other applications

### ISSUE THREAD

**Issue by reddog335** [kubernetes/dashboard#5062]
I'm using an ingress to access our Kubernetes Dashboard.  I'm experiencing a weird issue where after I navigate to the Kubernetes Dashboard in a browser (tested in Chrome and Firefox) via a defined ingress, any other defined application ingress I attempt to reach via the browser gets routed to the Kubernetes Dashboard.  I have to clear all of my browser data in order to reach other applications via ingress after hitting the Kubernetes dashboard.

##### Environment
Installation method: kubeadm
Kubernetes version: 1.16
Dashboard version: v2.0.0-rc3
Operating system:   RHEL 7.7

##### Steps to reproduce
1. Navigate to application ingress (https://k8-heyworld-jenkins-lab...) in browser.
![hey-world-1](https://user-images.githubusercontent.com/37052232/79040855-29dd0580-7bb1-11ea-9541-6b1d8ffeab0b.PNG)

2. In a new tab, navigate to the Kubernetes Dashboard ingress (https://k8-tkg-dashboard-jenkins-lab...)
![k8-dashboard](https://user-images.githubusercontent.com/37052232/79040861-306b7d00-7bb1-11ea-868e-dd9f88b20007.PNG)

3.  In a new tab, navigate to the same application ingress as step 1 which we already successfully hit. 

##### Observed result
I get directed to the Kubernetes Dashboard application instead of the hey-world application.
(https://k8-heyworld-jenkins-lab...)
![hey-world-hijacked](https://user-images.githubusercontent.com/37052232/79040878-4a0cc480-7bb1-11ea-982c-6a22e14c9f28.PNG)

##### Expected result
I hit the hey-world application same as step 1.
![hey-world-1](https://user-images.githubusercontent.com/37052232/79040895-6ad51a00-7bb1-11ea-8fdb-979cfae44391.PNG)

##### Comments
k8-dashboard-recommended.yaml:

[k8-dashboard-recommended.txt](https://github.com/kubernetes/dashboard/files/4464424/k8-dashboard-recommended.txt)

**Comment by floreks** [comment]
I don't think this is related in any way to Dashboard. It can't decide about routing itself. It's just an app. Ingress and kubernetes are the ones that decide here.

/close
