### ISSUE TITLE
Support for i386/arm

### ISSUE THREAD

**Issue by A-Kumpf** [kubernetes/dashboard#5063]
##### What would you like to be added

Either there's a hidden function I haven't seen, yet, or there's no support for i386/arm architecture of kubernetes-dashboard image.

##### Why is this needed

I was able to run a Centos SIG CentOS-Userland-7-armv7hl-RaspberryPI-Minimal-4-1908-sda.raw on a raspi 4 and, even more interesting, I was able to run a k3s.

As this is a 32 bit architecture I need some images on that platform to run like a dashboard, but:
Failed to pull image "k8s.gcr.io/kubernetes-dashboard-i386:v1.10.1": rpc error: code = NotFound
Failed to pull image "k8s.gcr.io/kubernetes-dashboard-386:v1.10.1": rpc error: code = NotFound
Failed to pull image "k8s.gcr.io/kubernetes-dashboard-arm:v1.10.1": rpc error: code = NotFound

##### Comments

What do I have to do to pull a working image for this special platform?

**Comment by floreks** [comment]
We do not support such architecture right now. Maybe we will in the future.

**Comment by A-Kumpf** [comment]
Okay, thanks.

**Comment by floreks** [comment]
@A-Kumpf just noticed that you tried to use `v1` which is deprecated. use `v2`. We've got a multiarch image.

https://hub.docker.com/layers/kubernetesui/dashboard/v2.0.1/images/sha256-19207cca570f61bce2294595a767b51b4d7e1f223a003c7972c350cf8689f49e?context=explore

It supports:
- linux/amd64
- linux/arm
- linux/arm64
- linux/ppc64le
- linux/s390x

/close
