### ISSUE TITLE
Can't exec into pod.

### ISSUE THREAD

**Issue by IceeMC** [kubernetes/dashboard#5064]
##### Environment

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc7/aio/deploy/recommended.yaml
Kubernetes version: v1.17.1
Dashboard version: v2.0.0-rc7
Operating system: Ubuntu 18.04.4 LTS
```

##### Steps to reproduce

1. Go to Workloads -> Pods
2. Try to exec into a pod

##### Observed result

In the console you'll see `GET https://cdn.sockjs.org/sockjs-0.3.min.js net::ERR_NAME_NOT_RESOLVED`

![Image](https://java.is-rocket.science/57474ea129.png)

##### Expected result

A shell opens that you can type commands into.

##### Comments

I am using k3s (lightweight kubernetes), but I'm sure that doesn't affect things.
Apparently according to the GitHub repo of sockjs, the new URL is `https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js`

Thanks! 😄

**Comment by shu-mutou** [comment]
I'm sorry. I had a misunderstanding. This is not fixed.
https://github.com/igm/sockjs-go/issues/89
I sumitted new PR for bumping sockjs-go.

**Comment by IceeMC** [comment]
Thanks! Would a release be following this also?

**Comment by shu-mutou** [comment]
v2.0.0 would include this. 😉

**Comment by IceeMC** [comment]
v2.0.0-rc8 or just v2.0.0?

**Comment by floreks** [comment]
The next one should be `v2.0.0`.

**Comment by IceeMC** [comment]
Alright!
