### ISSUE TITLE
Dashboard not accessing on browser

### ISSUE THREAD

**Issue by shivamnc** [kubernetes/dashboard#5070]
Dashboard accessing on Chrome Browser following error occurs

Your connection is not private
Attackers might be trying to steal your information from 192.168.1.100 (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_INVALID
Subject:

Issuer:

Expires on: Jan 10, 293878

Current date: Apr 16, 2020

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIBBTCBq6ADAgECAhEAol90jvolrrx/HEfxixqXdjAKBggqhkjOPQQDAjAAMCIY
DzAwMDEwMTAxMDAwMDAwWhgPMDAwMTAxMDEwMDAwMDBaMAAwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAAREfCwXDSueIiBmtnudLKqDQDOTwtWGZ/EhisZeUISFwSGQ
wL10Ml5USH2sy8UIyMUXzy3YzFncnS2sNjaINY9eowIwADAKBggqhkjOPQQDAgNJ
ADBGAiEAoy84oOM4zz0AXLidmG6SoeDn2YD4O4C9odbf0e5C5wUCIQDC38qZ2ksT
x4Kb/C/BbVBKts8cX1F3Dz4dlOACCbGwUw==
-----END CERTIFICATE-----

Help improve Chrome security by sending URLs of some pages you visit, limited system information, and some page content to Google. Privacy policy
192.168.1.100 normally uses encryption to protect your information. When Google Chrome tried to connect to 192.168.1.100 this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be 192.168.1.100, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit 192.168.1.100 right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by floreks** [comment]
Issue template not provided. There are already similar closed issue.

/close
