### ISSUE TITLE
Update metrics range

### ISSUE THREAD

**Issue by ajouve** [kubernetes/dashboard#5072]
##### What would you like to be added

I would like to see my metrics at least a day and not only a few minutes

##### Why is this needed

Get a betters understanding of cluster comportment 

##### Comments

I do not know if this has to be configured on the dashboard or `metrics-server`.
My gitlab installed grafana `k8s.gcr.io/heapster-grafana-amd64:v5.0.4` in the cluster, I do not know if it. can help

Thanks

**Comment by floreks** [comment]
If you need advanced graphs to see the resource usage grafana will be better as it mainly focuses on showing resource usage. In theory you can change dashboard metrics scraper resolution time to more than 15m, but a I'd not recommend using more than a few hours as our graphs are not destined to show long time usage. Their purpose is to show usage spikes over shorter period of time and overall usage across namespace/cluster.
