### ISSUE TITLE
will some day dashboard support CI/CD?

### ISSUE THREAD

**Issue by cifc** [kubernetes/dashboard#5081]
##### What would you like to be added
will some day dashboard support CI/CD?

##### Why is this needed
That will be an exciting thing

**Comment by cifc** [comment]
dashboard Integration with Tekton?

**Comment by maciaszczykm** [comment]
> will some day dashboard support CI/CD?

What do you mean?

**Comment by floreks** [comment]
Ye, I am not sure how it would even work.
