### ISSUE TITLE
pod exec freezes after few minutes 

### ISSUE THREAD

**Issue by iamsanketsingh** [kubernetes/dashboard#5082]
Environment
```
Installation method: - kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml 
Kubernetes version: - v1.16.7  (managed by azure -aks)
Dashboard version: v2.0.0-beta8 
operating system: mac os catalina 10.15.4
```

Steps to reproduce
1. I have used the AKS to create a cluster. 
2. deployed the dashboard using above template. (specified in installation method)
3. changed the svc type to loadbalancer and in deployment changed it to https to http
4. then associated the loadbalancer's ip to Application gateway. 

Observed result
<img width="1280" alt="Screen Shot 2020-04-20 at 4 21 52 PM" src="https://user-images.githubusercontent.com/37649015/79743899-0d646a00-8323-11ea-80ac-cec8fa461af7.png">
at first when i try to exec into pod, it works fine but after 1-2 minute it freezes, nothing works and I have to reload the page. 
When you open an exec terminal in a pod, it becomes unresponsive at the very momenty I close the web terminal window. 

Thanks

**Comment by floreks** [comment]
Probably related to https://github.com/kubernetes/dashboard/issues/5064. Should be fixed on master.

**Comment by iamsanketsingh** [comment]
@floreks I don't get any error and there is also nothing on logs. terminal just freezes and then i need to reload the page. No error message is shown neither on terminal nor in logs.

**Comment by floreks** [comment]
It might have something to do with your LB configuration. It might be closing the open connection due to some timeout. I kept terminal open for an hour without any interaction and it was working just fine after that in our reverse proxy setup. It also works fine when using `kubectl proxy`. This makes me think that there might be something wrong with your configuration here.

**Comment by iamsanketsingh** [comment]
Yeah that might be the case here, let me check it with aks and application gateways configuration.

**Comment by zetsub0u** [comment]
I have the same issue in bare metal kubernetes using contour as Ingress, any pointers? I've seen quite a few people talk about this before, some other people mentioned tunning some timeouts on ngnix, i don't see how to tune this on envoy, maybe there's a way to have more proactive keepalives in the dashboard so we don't all have to tune our ingresses?

**Comment by floreks** [comment]
Tracked from #2029

/close
