### ISSUE TITLE
github.com/kubernetes/dashboard@v2.0.0 is an invalid go module

### ISSUE THREAD

**Issue by bouk** [kubernetes/dashboard#5086]
##### Environment
```
Dashboard version: v2.0.0
Go version ('go version' output): go version go1.14.2 darwin/amd64
```

##### Steps to reproduce

I want to use this project inside my own, but I can't use it as a module because it's an invalid go module right now. To reproduce, run:

```
$ GO111MODULE=on go get github.com/kubernetes/dashboard@v2.0.0
go get github.com/kubernetes/dashboard@v2.0.0: github.com/kubernetes/dashboard@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

##### Observed result

Go says this is an invalid module.

##### Expected result

The module is installed correctly.

##### Comments

I noted this is a problem back in july: https://github.com/kubernetes/dashboard/issues/4110, so I think this does need to get resolved. I can create a PR for it.

**Comment by maciaszczykm** [comment]
If you are willing to work on that we can help you with review and provide some suggestions. It has no big priority for the reasons I have mentioned before but it might be useful for projects like yours. Let us know if you will need anything from us. Also, any early proposal/drafts are welcomed so we can discuss top-level things early.

**Comment by bouk** [comment]
What I think we'll have to do is move the source to `v2/` and then rename all references to that. Doesn't seem to complicated

**Comment by floreks** [comment]
Basically, Dashboard is not intended to be used as a Go module itself. It is a complete application, not only using Go, but also a lot of other things. I don't really want to change our code structure to satisfy this constraint. You can fork it and work on it, but from IMHO it should not be possible to only use it as a pure Go module.

**Comment by bouk** [comment]
Fair enough. I tried to quickly change it but it would involve changing the whole structure of the project which just isn't worth it. I'll fork, thank you!
