### ISSUE TITLE
Setup into a different namespace failed

### ISSUE THREAD

**Issue by vfabi** [kubernetes/dashboard#5087]
##### Environment
```
Installation method: apply yaml file https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
Kubernetes version: v1.17.2
Dashboard version: v2.0.0
Operating system: Linux Mint 19.2
Node.js version ('node --version' output): none
Go version ('go version' output): none
```

##### Steps to reproduce
1. Change namespace in https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml to 'monitoring'
2. Change all 'kubernetes-dashboard' to 'dashboard' in https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
3. Change kubernetes-dashboard Deployment arg '--namespace=kubernetes-monitoring' to '--namespace=monitoring'
4. kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

##### Observed result
Output of `kubectl logs -n monitoring dashboard-d9bf9c65f-84mxj`
```
2020/04/21 17:05:51 Using namespace: monitoring
2020/04/21 17:05:51 Using in-cluster config to connect to apiserver
2020/04/21 17:05:51 Starting overwatch
2020/04/21 17:05:51 Using secret token for csrf signing
2020/04/21 17:05:51 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:monitoring:dashboard" cannot get resource "secrets" in API group "" in the namespace "monitoring"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc000513340)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:41 +0x446
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc00047a100)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:501 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc00047a100)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:469 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:550
main.main()
        /home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x20d
```
Output of `kubectl get pods -n moniroting`
```
monitoring    dashboard-d9bf9c65f-84mxj                   0/1     CrashLoopBackOff
```
##### Expected result
Apply https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml with no errors with all pods state 'running'.

**Comment by floreks** [comment]
You must have updated yaml incorrectly as error clearly says that Dashboard does not have privileges to get secret in its' namespace.

```
2020/04/21 17:05:51 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:monitoring:dashboard" cannot get resource "secrets" in API group "" in the namespace "monitoring"
```

**Comment by vfabi** [comment]
> You must have updated yaml incorrectly as error clearly says that Dashboard does not have privileges to get secret in its' namespace.
> 
> ```
> 2020/04/21 17:05:51 Initializing csrf token from kubernetes-dashboard-csrf secret
> panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:monitoring:dashboard" cannot get resource "secrets" in API group "" in the namespace "monitoring"
> ```

Hmmm, but there is no 'kubernetes-dashboard-csrf' secret at all. As i said earlier, i changed all 'kubernetes-dashboard' values to 'dashboard', in this case my secret is 'dashboard-csrf' :)
It seems that is not access error but hardcoded 'kubernetes-dashboard-csrf' value error.

**Comment by floreks** [comment]
> Hmmm, but there is no 'kubernetes-dashboard-csrf' secret at all.

There surely is a `kubernetes-dashboard-csrf` secret in our deployment file.
https://github.com/kubernetes/dashboard/blob/1f66b1c1fde5282f2b5146c6e94018a916610b28/aio/deploy/recommended.yaml#L59-L68
