### ISSUE TITLE
After collapsing view expansion is no longer possible

### ISSUE THREAD

**Issue by everflux** [kubernetes/dashboard#5088]
##### Environment
dashboard 2.0.0 (release), firefox browser

##### Steps to reproduce
Go to any view, for example nodes.
Click the small up-arrow on the right in the title.
The view collapses / minimizes.

##### Observed result
It is no longer possible to get it back.

##### Expected result
Clicking the arrow again should unfold the view.

##### Comments
No errors in the browser console visible. Reloading the dashboard is a possible workaround.

**Comment by floreks** [comment]
Ye, it seems to be a bug in Firefox browser only. Works correctly in Chrome. We'll fix it.

**Comment by everflux** [comment]
Very fast feedback - thanks for taking care! :)
