### ISSUE TITLE
Feature request: Handle daemonsets

### ISSUE THREAD

**Issue by Seb-Solon** [kubernetes/dashboard#509]
Hi there,

I noticed that only RC are handled for now in the dashboard.  It could be great to have daemon set also are they are very similar.

This feature can be devided into 2 parts : 
* Add routes in the backend to handle rest call
* Add "stuff" in the fromtend to be able to see it in the UI

I did the first part (the backend) and I will submit a PR in a few seconds.

**Comment by floreks** [comment]
This sounds nice and work in the PR looks also good. Thanks! We have to wait however for @bryk to return as I'm not sure if this is in our scope for now. On hold for now :)

**Comment by Seb-Solon** [comment]
No problem !

**Comment by maciaszczykm** [comment]
@Seb-Solon we have currently some issues with Travis setup and integration tests fails on Internet Explorer. Due to this problem, you probably won't be able to make it green in 100% cases. We are working on this issue right now, it should be more stable within days. However, you can test it locally - there should be no problems.

We will return to it next week, when @bryk will come back.

**Comment by cheld** [comment]
@Seb-Solon we are currently working on the future road-map of Dashboard. We want to do this together with the community. I would ask you to join this process. We will post the details after Kubecon.

Adding more Kubernetes resources like nodes, pods, jobs , deamon sets is certainly on the agenda. But we need some planning and we need input from UX-experts.

**Comment by Seb-Solon** [comment]
@cheld sure no problem! What is the best way to join the conversation? On slack? Mailing-list ?

**Comment by therc** [comment]
There's also #384. I didn't realise there was all this Go code involved (I assumed most of it was fancy Node stuff); in that case, I can help with the REST parts.

**Comment by bryk** [comment]
> @cheld sure no problem! What is the best way to join the conversation? On slack? Mailing-list ?

Mailing list and github issue queue.

**Comment by Seb-Solon** [comment]
@bryk Is it https://groups.google.com/forum/#!forum/google-containers (google-containers@googlegroups.com)? Because it looks like it's more a general user list.

**Comment by bryk** [comment]
There's the group: https://groups.google.com/forum/#!forum/kubernetes-sig-ui

**Comment by bryk** [comment]
Done.
