### ISSUE TITLE
CRD screen does not show objects

### ISSUE THREAD

**Issue by Eddman** [kubernetes/dashboard#5090]
##### Environment

```
Installation method: kubeadm + Helm
Kubernetes version: 1.16.9
Dashboard version: 2.0.0
Operating system: N/A
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce
Go to "Custom Resource Definitions" and open any CRD. The list of Objects is empty. I assume it should be list of CRs associated with this CRD.

##### Observed result
List of CRs is empty.

##### Expected result
List of CRs is not empty.

##### Comments
We use token that has cluster-admin rights so it should not be an issue with missing privileges.

**Comment by floreks** [comment]
If there are no errors in console/network tab and `Objects` list is empty then it's just empty. Listing definitely works fine as we also use CRDs and never had any issues with listing objects. If there is an error in console then this might be due to incompatibilities between Kubernetes API versions. `v1.16` might not be fully supported as we use newest `client-go` right now. You should also check CRD API versions enabled in your cluster. It should use `v1`, not `v1beta1`.

**Comment by Eddman** [comment]
Hi, Kubernetes 1.16 was the first one were CRDs graduated to `v1`.

And I'm sure we have a lot of CRs for instance for `ServiceMonitor` CRD otherwise our Prometheus Operator would not work.

I'm not even seeing any errors in the logs only the requests:
```
Incoming HTTP/1.1 GET /api/v1/crd/cluster-tools/servicemonitors.monitoring.coreos.com/object?itemsPerPage=50&page=1&sortBy=a,age request from 10.36.0.6:37128:
```
However that log message made me realize that it is a namespaced CRD and I have to select particular namespace/All namespaces first. 

This is not very intuitive, maybe because it is separated by the horizontal separator from the "Namespace" section :man_shrugging:. Maybe if it's removed it we'll be more clear....

**Comment by floreks** [comment]
> This is not very intuitive, maybe because it is separated by the horizontal separator from the "Namespace" section man_shrugging. Maybe if it's removed it we'll be more clear....

CRDs can be namespaced or non-namespaced. That is why they are not in the same "section" as regular resources that are always namespaced. Non-namespaced CRDs will not be affected by the namespace selector. This is something that the user should be aware of when using CRDs. We can think about adding some hint for that.

**Comment by Eddman** [comment]
Yes, makes sense. Maybe just a text change for namespaced CRDs to make it obvious:

From:
```
There is nothing to display here
No resources found.
```
To:
```
There is nothing to display here
No resources found for namespace <namespace name>.
```
