### ISSUE TITLE
Will there me a a helm chart for the v2.00 release?

### ISSUE THREAD

**Issue by ghoben** [kubernetes/dashboard#5094]
Will there me a helm chart for the v2.00 release? Is helm still the way how dashboard should be deployed also for the new version, or will this become obsolete and kustomize will be used? What's the planned  future path going forward?

**Comment by floreks** [comment]
Check PR #4502. Officially, we do not maintain any other deployment method than the one in our README. Everything else is maintained by contributors.

/close

**Comment by ReSearchITEng** [comment]
till PR will be merged, here is a clone of the repo:
https://github.com/funkypenguin/helm-kubernetes-dashboard
(see there:
```
helm repo add funkypenguin-kubernetes-dashboard https://funkypenguin.github.io/helm-kubernetes-dashboard/
```
and install like:
```
helm install --namespace kubernetes-dashboard --name kubernetes-dashboard funkypenguin/kubernetes-dashboard - --set metrics-server.enabled=true,metricsScraper.enabled=true --set image.repository=kubernetesui/dashboard,image.tag=v2.0.0
```
#--set protocolHttp=true -set ingress.enabled=true --set ingress.hosts[0]={{ URLLL }}
