### ISSUE TITLE
To access Dashboard directly (without kubectl proxy) valid certificates should be used to establish a secure HTTPS connection.

### ISSUE THREAD

**Issue by nicoclau** [kubernetes/dashboard#5095]
Hello, I would like to access the dashboard without kubectl proxy.

What URL/port would be used then if valid certificates are present? 

Thanks for detailing this part.

**Comment by floreks** [comment]
It's not related to Dashboard, but to Kubernetes itself. Start by reading the documentation and some tutorials:

https://kubernetes.io/docs/concepts/services-networking/service/
https://kubernetes.io/docs/concepts/services-networking/ingress/
https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/
https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/

/close
