### ISSUE TITLE
Darktheme colours fix

### ISSUE THREAD

**Issue by vctrmn** [kubernetes/dashboard#5096]
##### What would you like to be added
I would like to propose some less saturated colors for darktheme (primary, warning, sucess, error)

##### Why is this needed
To keep a minimum color contrast ratios

##### Comments
Can i make a Pull Request that will show the changes and you review it ? It is just a very slight change on the scss files.

You can find a screenshot here : https://ibb.co/PzvTSBs

**Comment by vctrmn** [comment]
<img width="1676" alt="dark-k8s-dash" src="https://user-images.githubusercontent.com/23551110/80291085-b5769a80-874a-11ea-95ce-6721c647359f.png">

**Comment by floreks** [comment]
You are always welcome to open any PR you think would improve Dashboard. We can check it and discuss there.
