### ISSUE TITLE
Quash exec complaints (bash vs sh vs...)

### ISSUE THREAD

**Issue by mcandre** [kubernetes/dashboard#5097]
##### What should be cleaned up or changed

When execing to containers without bash, the dashboard is often able to fallback to sh, but blots an annoying exec failure onto the screen, which takes up valuable real estate.

Also, bash-less containers are becoming more common for efficiency, eg default Alpine.

If exec is completely unable to open any shell, then by all means show us a clear error message. But when a fallback is working, don't generate noise.

**Comment by floreks** [comment]
Tracked from https://github.com/kubernetes/dashboard/issues/2029

/close
