### ISSUE TITLE
what is the minimum permission for serviceaccount

### ISSUE THREAD

**Issue by lddhappy** [kubernetes/dashboard#5098]
I have a serviceaccount, now i want the account can manage just one namespace resource.
So,what is the minimum permission i need to allocate to the account?( not cluster-admin clusterrole)

**Comment by floreks** [comment]
This will always differ per individual use case. No one will tell you what will be the minimal set of privileges that is tailored for you.

Read Kubernetes documentation first and understand how RBAC (Roles, Bindings, etc.) works. Once you do that, you will be able to figure out what permissions you need and set them for your service account.

https://kubernetes.io/docs/reference/access-authn-authz/rbac/

You can test first with `kubectl`. The same permissions will be reflected in the UI.

/close

**Comment by lddhappy** [comment]
now kubernetes-dashboard document use cluster-admin cluster role binding.I just google one article <Installing Kubernetes Dashboard per Namespace>[https://akomljen.com/installing-kubernetes-dashboard-per-namespace/](url), it's so hard for user to config this,and man user need this, so why can't we document this for every one

**Comment by floreks** [comment]
This is related to Kubernetes itself, not directly to the Dashboard. It also heavily depends on how a user chooses to configure the cluster (OIDC, ABAC, RBAC, etc.). We won't be just copying Kubernetes documentation over to our repo. Everything is already there. The user has to understand how this works first in Kubernetes and learn how to properly apply privileges. Dashboard only reflects the permissions set for the Kubernetes user. There is no "dashboard user", there is only "kubernetes user".

**Comment by lddhappy** [comment]
I create a serviceaccount(md-tool-user),and bind it to kubernetes-dashboard role binding, kubernetes-dashboard cluster role binding.But the service account can't login.The kubernetes-dashboard service account has the same binding,it can login,so what do i lost in binding?

kubernetes-dashboard role binding
`apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2020-04-11T12:56:43Z"
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  resourceVersion: "7971753"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kubernetes-dashboard/rolebindings/kubernetes-dashboard
  uid: 63b349ae-d129-4303-9891-058022d4f961
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
- kind: ServiceAccount
  name: md-tool-user
  namespace: md-tool
- kind: ServiceAccount
  name: md-tool-user2
  namespace: kubernetes-dashboard
`

kubernetes-dashboard cluster role binding
`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-04-11T12:56:43Z"
  name: kubernetes-dashboard
  resourceVersion: "7971887"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kubernetes-dashboard
  uid: 405c6985-3846-49b6-9975-e5f3a7bf08a4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
- kind: ServiceAccount
  name: md-tool-user
  namespace: md-tool
- kind: ServiceAccount
  name: md-tool-user2
  namespace: kubernetes-dashboard
`

**Comment by lddhappy** [comment]
Thank you for your reply.   @floreks 
The problem has solved.
I allocate the admin  cluster role with role binding in the namespace.
It is worth mentioning that the service account token which used to login should be base64 decoded.
