### ISSUE TITLE
UX: Refresh scrolls the page to top

### ISSUE THREAD

**Issue by Eddman** [kubernetes/dashboard#5099]
##### Environment

```
Installation method: kubeadm + Helm
Kubernetes version: 1.16.9
Dashboard version: 2.0.0
Operating system: N/A
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce
Set the settings to show 50 items per page. Open a list of pods in a namespace where you have a lot of pods. Scroll to bottom. After few seconds on refresh the page scrolls to top.

##### Observed result
Page scrolls to to on each refresh, eg. every 5s

##### Expected result
Page should not scroll away from a viewpoint I'm looking at (based on an automated event).

**Comment by maciaszczykm** [comment]
Tip for later: this may be caused by the option to expand cards.

**Comment by cameronbraid** [comment]
I get this too, as soon as I scroll the pager into view

**Comment by floreks** [comment]
This issue is extremely weird. It happens due to chart redraw, but only if the user has scrolled to the very bottom of the page (like 90% down). To be honest I don't know right now how to fix this. The issue probably lies somewhere in `ngx-chart` library.
