### ISSUE TITLE
Deploy from local images

### ISSUE THREAD

**Issue by nicoclau** [kubernetes/dashboard#5100]
Hello, is it possible to deploy my app with local docker image on the dashboard?

I just used 

containers:      
      - name: myapp
        image: webapi:latest

But I got the error : 

Failed to pull image "webapi:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for webapi, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Thanks for your help

**Comment by floreks** [comment]
Dashboard has nothing to do with this. Kubernetes handles creation of resources. Dashboard only shows the data. The only thing that might be required is to ensure that imagePullPolicy is set to ifNotPreset or never. Other than that you should look for information how to run local docker images in Kubernetes. Small hint. It depends on your Kubernetes installation.

/close

**Comment by alexespejoch** [comment]
Hola,
En el terminal que estas utilizando agrega la instrucción **eval $(minikube docker-env)** para indicar que de ahora en adelante todos los comandos Docker se ejecutaran sobre Docker de Minikube.
Esto facilita la integración entre docker y minikube y más aún para realizar experimentos locales.

Luego tiene que cambiar el archivo **deployment.yml** y agregar la propiedad **imagePullPolicy: Never** en la especificación del contenedor.

Suerte!
