### ISSUE TITLE
CPU Usage flickers

### ISSUE THREAD

**Issue by marov** [kubernetes/dashboard#5101]
After upgrading to v2.0.0-rc7 CPU Usage counter starts flickering constantly on the "pod" sections. Happens after switching to a new namespace

**Comment by floreks** [comment]
Are you talking about this?

https://github.com/kubernetes/dashboard/issues/5050

**Comment by floreks** [comment]
No response and seems like a duplicate. Closing.

/close

**Comment by marov** [comment]
Yes, it looks like the duplicate of #5050. Thanks for quick response
