### ISSUE TITLE
Auth behaviors problems

### ISSUE THREAD

**Issue by orblazer** [kubernetes/dashboard#5103]
This issue talk about redirection when `sign in` and the access to that panel.

##### Environment

```
Installation method: On premise with kubeadm and Calico CNI
Kubernetes version: 1.18
Dashboard version: 2.0.0
Operating system: Linux AMD 64
Node.js version ('node --version' output):
Go version ('go version' output): 1.13.9
```

##### Steps to reproduce

1. Install dashboard
2. Create bearer token for login (i think its same problem with file)
3. The different bugs :
3.a **Bug 1 :** Access to dashboard with url `http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login`
3.b **Bug 2 & 3 :** Login to the panel
4. The different bugs :
4.a **Bug 2 :** Access to url `http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login`
4.b **Bug 3 :** Wait the token expire

##### Observed result

- **Bug 1 :**
  When click on `sign in` this have wrong redirection when we access to the panel directly with the login url. One submit we are redirected to the same url (`http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login`).
- **Bug 2 :**
  We can always access to the login panel
- **Bug 3 :**
  We are not redirected to the login panel when the token expire.

##### Expected result

- **Bug 1 :**
  This need to redirect to home page (`http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/overview`)
- **Bug 2 :**
  This need to redirect to home page (`http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/overview`)
- **Bug 3 :**
  This need to redirect to login page (`http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login`)

**Comment by floreks** [comment]
To be honest I don't really know what is this issue about. Needs better description.

**Comment by orblazer** [comment]
I have update my message for describe the different bugs.

**Comment by floreks** [comment]
1. How do you know it redirects you to the same page.
2. What happens after you provide token and click Sign In?
3. Video showing the issue would be best.

**Comment by orblazer** [comment]
1. I suppose (i don't have check the network) because i have check the console and doesn't have see any error
2. Nothing append
3. i can't, because for unknown reason i can't reproduce that bug, in that case i suppose is problem with my network or something else and never logged. If i am alone to have that bug we probably can ignore it but the 2 other bug is still present

**Comment by floreks** [comment]
Are you really using `localhost` or some othe IP/domain to access it?

**Comment by orblazer** [comment]
Yes i use `localhost` with proxy

**Comment by floreks** [comment]
That's interesting because the only reason I see nothing could happen on login view after providing token is if you are trying to access Dashboard over HTTP and your domain is not `localhost` nor `127.0.0.1`.

**Comment by floreks** [comment]
It would be best if you could share `Console` and `Network` tabs from your browser from the time when you provide a token and click `Sign In`. Also seeing `/login` request/response would be great.
