### ISSUE TITLE
Typing in edit secret with long text jumps page to top

### ISSUE THREAD

**Issue by greggbjensen** [kubernetes/dashboard#5104]
##### Environment

```
Installation method:  kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
Kubernetes version:  1.15.10
Dashboard version:  2.0.0
Operating system:  Windows 10 Enterprise  (Chrome 81.0.4044.129 (64-bit))
Node.js version ('node --version' output):  12.14.0
Go version ('go version' output):  go1.14 windows/amd64
```

##### Steps to reproduce
1. Sign in to dashboard
2. Click on `Secrets` on the left navigation
3. Click pencil icon next to a data value that has long text
4. Scroll to be bottom of the edit field and start typing
5. Page will jump to top with each key entry

##### Observed result
Page jumps to the top each time a key is pressed when editing a long data value on a secret.

##### Expected result
Page does not move, but stays as you type.

##### Comments
The would make the edit secret inline much more helpful to fix this.

**Comment by floreks** [comment]
This seems to be the same issue as https://github.com/kubernetes/dashboard/issues/5099

**Comment by greggbjensen** [comment]
@floreks it is similar. However, it happens every time you type one character and not on refresh.

**Comment by floreks** [comment]
I understand that it feels different, but underlying issue seems to be the same. Refr esh there means resource autorefresh, not page refresh.

**Comment by floreks** [comment]
This is actually a long time known issue in angular: https://github.com/angular/material/issues/3070

I'll work on some kind of workaround for this.
