### ISSUE TITLE
UI: Labels on chart are restless

### ISSUE THREAD

**Issue by milosjanda** [kubernetes/dashboard#5106]
In _Overview_ charts labels are constantly redrawing. It happens on both charts _CPU Usage_ a _Memory Use_ but each on another windows width.
Seen in the browsers:
- Chrome: 81.0.4044.138
- Safari: 13.1 (15609.1.20.111.8)

##### Environment

```
Installation method: ?
Kubernetes version: 1.16
Dashboard version: v2.0.0+0.g1f66b1c
Operating system: Mac OS
Node.js version ('node --version' output): ---
Go version ('go version' output): ---
```

##### Steps to reproduce

Go to the _Overview_, set browser window width so that labels on chart are oblique. 
Increase the width of the window in small steps until the graph labels are horizontal.

##### Observed result

![k8s dashboard](https://user-images.githubusercontent.com/1765118/81280267-815b7d80-9058-11ea-8f15-e4923bc01ca9.gif)

##### Expected result

Stable graph

**Comment by floreks** [comment]
#5102 #5050

/close
