### ISSUE TITLE
Base image so that AWS ECR will accept

### ISSUE THREAD

**Issue by mckunkel** [kubernetes/dashboard#5112]
##### What would you like to be added
Base the Image on something that AWS ECR will accept. Such as 
Amazon Linux, Amazon Linux 2, Debian, Ubuntu, CentOS, Oracle Linux, Alpine, and RHEL Linux distributions.
See [Supported ECR bases](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-troubleshooting.htm)l

##### Why is this needed
Users who have to rely on ECR image pulls for EKS behind a firewall.

**Comment by floreks** [comment]
That won't happen. We will not rely on a different image just to satisfy a constraint of a single company. We use secure base docker image. If you need to customize it, fork the repo and build your own custom version.

/close
