### ISSUE TITLE
Cannot close popup window after pressing certain links

### ISSUE THREAD

**Issue by erihanse** [kubernetes/dashboard#5116]
##### Environment

```
Installation method:
Kubernetes version: 1.15.9
Dashboard version: 2.0
Operating system: ubuntu 18.04
Chrome version: 81.0.4044.138 (Official Build) (64-bit)
Also present in firefox
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Log in to dashboard
2. Navigate to a pod
3. Click one of the blue links on the annotations for the pod - now window shows up
4. Press close
##### Observed result

Nothing happens.
##### Expected result

Window is closed.
##### Comments

Version 1 of the dashboard (no links, so issue not present):
![image](https://user-images.githubusercontent.com/9251274/81652596-4b414380-9434-11ea-8252-23a3cdfa84a2.png)

Version 2 of the dashboard:
![image](https://user-images.githubusercontent.com/9251274/81652629-55fbd880-9434-11ea-9509-38fbf9db429f.png)

**Comment by floreks** [comment]
Already fixed on master.

/close
