### ISSUE TITLE
Error 503: No Endpoints

### ISSUE THREAD

**Issue by SherazShahid17** [kubernetes/dashboard#5117]
Im looking to run the dashboard on my MiniShift cluster. 

Followed the steps and the Kubernetes dashboard had been created as a separate project (separate from the project I was wishing to monitor) and the URL gives error 503. 

Any help/advice??

**Comment by maciaszczykm** [comment]
We are not supporting OpenShift clusters. If it works then it's good, but it's not a priority for us. Our target is to be compatible with Kubernetes.

**Comment by SherazShahid17** [comment]
I assumed since that MiniShift and MiniKube are like for like them it would be compatible for both. Would it work on a MiniKube cluster?

**Comment by maciaszczykm** [comment]
It works on minikube.
