### ISSUE TITLE
CPU Usage Graph Layout Glitching

### ISSUE THREAD

**Issue by cclloyd** [kubernetes/dashboard#5118]
```
Installation method: kubectl using [this manifest](https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml) as of 05/12/2020.
Kubernetes version: 1.14.6
Dashboard version: v2.0.0+0.g1f66b1c
Operating system: ubuntu 18.04
```

##### Steps to reproduce
Deploy Dashboard manifest

##### Observed result
Short gif of resulting error: https://i.imgur.com/542tkIa.mp4

##### Expected result
Graph displays information correctly

##### Comments
Browser is Chrome 81.0.4044.138 on macOS 10.15.4.

**Comment by cameronbraid** [comment]
duplicate of https://github.com/kubernetes/dashboard/issues/5050
