### ISSUE TITLE
Implement sort by status for pods

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#5122]
The vaule in the UI has to be aligned with the value used during the sorting in the backend.

Related to: https://github.com/kubernetes/dashboard/pull/5121

**Comment by ijelliti** [comment]
@maciaszczykm I would like to work on this feature

**Comment by maciaszczykm** [comment]
/assign @ijelliti 

Very well :) If you need any help let us know here or on Slack.

**Comment by rmeloca** [comment]
It would be nice to also have a option to filter by status

**Comment by tcnt** [comment]
@maciaszczykm I would like to work on this issue. Can I just assign myself? Someone else is already assigned, but looks like nothing happened since 1 year.
Also I wonder if the request from @rmeloca on filtering should not be created as a new issue?

**Comment by maciaszczykm** [comment]
> @maciaszczykm I would like to work on this issue. Can I just assign myself? Someone else is already assigned, but looks like nothing happened since 1 year.(Looks like I was able to assign my self, so I just did it).

@tcnt Sure, please go ahead.

> Also I wonder if the request from @rmeloca on filtering should not be created as a new issue?

It should.
