### ISSUE TITLE
got this error when I try to see any pods/nodes/ from Kubernetes dashboard

### ISSUE THREAD

**Issue by shikam** [kubernetes/dashboard#5137]
Hi,
I got this error when I try to see any pods/nodes/ from Kubernetes dashboard:

secrets is forbidden: User "system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard" cannot list resource "secrets" in API group "" in the namespace "kubernetes-dashboard"

how I can to fix tis problem?

**Comment by shikam** [comment]
Hi, 
In addition, I get the following error:
shai@shai-pc:~$ kubectl proxy
Starting to serve on 127.0.0.1:8001
2020/05/19 01:20:13 http: proxy error: context canceled
2020/05/19 01:20:14 http: proxy error: context canceled
2020/05/19 01:20:14 http: proxy error: context canceled
2020/05/19 01:20:24 http: proxy error: context canceled
2020/05/19 01:20:24 http: proxy error: context canceled

please help me to fix this issue.
shai

**Comment by floreks** [comment]
Permission error is expected. Read the documentation first.

/close

**Comment by shikam** [comment]
Hi  floreks,
Which documentation need to read? can you send the link?
