### ISSUE TITLE
`cani` API endpoint returns `false` and cause frontend to refresh content every 5s

### ISSUE THREAD

**Issue by JackWindows** [kubernetes/dashboard#5170]
##### Environment

```
Installation method: docker image deployed directly to cluster
Kubernetes version: v1.18.1
Dashboard version: v2.0.0-rc5+0.g646b573
Operating system: macOS
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce

1. Go the pod list page in any namespace.
2. Click **show all** button to expand the pod labels.
3. Wait for about 5s.
##### Observed result

1. The row will automatically fold again.
2. If I open dev console and switch to "Network" tab, I can see the dashboard frontend is sending some request every 5s to refresh the content of the pod list.
##### Expected result

1. The row **shouldn't** fold again.
2. The frontend shouldn't make requests every 5s to refresh the pod list.

##### Comments

We did some debugging, and identified the issue to be `GET api/v1/settings/global/cani` returns `allow: false` while it should have been `true`.
We use auth head to login, and I verified my logged-in user does have `get` access to the `kubernetes-dashboard-settings` configmap in `kubernetes-dashboard` namespace (I can access the configmap directly on WebUI).

For now, we are using the workaround of `--disable-settings-authorizer` to artificially make the `cani` endpoint return `true`. And this solves the frontend refreshing issue.

**Comment by floreks** [comment]
`canI` endpoint here is only used to grant you access to the settings page and it uses `SelfSubjectAccessReview` API to check if the user has GET access to this settings config map. If you can access `Settings` view then it works fine, if not then it means that some privileges are missing. If it cannot access the settings map then default values are used (5s for the resource refresh). The code is quite simple here.

https://github.com/kubernetes/dashboard/blob/db3f8bf5a69d33382ab55bac2e3b8156dfb2fd33/src/app/backend/settings/handler.go#L66-L83

As for the actual issue with pod list state reset. It is already described in https://github.com/kubernetes/dashboard/issues/4882, which makes it a duplicate.

/close

**Comment by JackWindows** [comment]
Re-opening because I think the `cani` API endpoint is still not right.
Also the auto-refreshing issue doesn't only happen to `pods` list, but also to jobs list, event list, etc.

For the `cani` API endpoint issue, this is the response I got when I access the `api/v1/settings/global/cani` endpoinit:
```
{
 "allowed": false
}
```
When I access the setting page (left-bottom) corner, I can only see **Local Settings**.
But if I go to the configmap directly, I can definitely see the settings
![image](https://user-images.githubusercontent.com/1560135/82699312-697c2000-9c3a-11ea-82f2-720f40a8df88.png)

So the question remains: why `cani` endpoint is returning `false` while I have the access?
I looked the backend code, but all I can think is it should return `true`.

**Comment by floreks** [comment]
First, check it with kubectl using `kubectl auth can-i` command and see if it will return true. This API is different than actually getting the config map object. Our endpoint is only a proxy for API server. It's K8S API server that returns false, not really Dashboard.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#checking-api-access

**Comment by JackWindows** [comment]
I checked `kubectl auth can-i`, it's returning yes.
```
$ kubectl auth can-i get configmap/kubernetes-dashboard-settings -n kubernetes-dashboard
yes
```
So I really don't understand which part went wrong. 😕

**Comment by floreks** [comment]
Are you sure that you have used exactly the same auth method to check `kubectl` output? Did you pass the token to `kubectl`?

**Comment by JackWindows** [comment]
@floreks I believe so.
Today I tried a different method to start the dashboard.
I cloned the repo, use `npm start` to start a local dashboard with my `kubeconfig` file.
I believe this will make the dashboard use the same auth method in `kubectl`. 

I proceed to access the `api/v1/settings/global/cani` endpoint and it gives me `false`.

**Comment by floreks** [comment]
The only option I see right now is that maybe v1.18 introduced some changes in how SSAR should be created. I'll test on v1.18 tomorrow to check if I can reproduce that.

**Comment by JackWindows** [comment]
I have a theory
```
$ kubectl auth can-i get ConfigMap/kubernetes-dashboard-settings -n kubernetes-dashboard
yes
```
```
$ kubectl auth can-i GET ConfigMap/kubernetes-dashboard-settings -n kubernetes-dashboard
no
```
I will need to do some work to verify the golang k8s API.

**Comment by JackWindows** [comment]
I just finished some verifications on the k8s dashboard backend code. So there are two things that went wrong:
1. `verb` should be a lower case string, so `get` instead of `GET`.
2. `resource` should be a lower case string, and in plural form. The existing code uses `api.ConfigMapKindName` which is `ConfigMap`. I tested `ConfigMaps`, `configmap`, both are **not** working. Only the combination of `get` and `configmaps` will return `true`.

Here is an example request json captured from the `kubectl auth can-i get ConfigMap/kubernetes-dashboard-settings -n kubernetes-dashboard` with `--v=10`:
```
{
   "spec":{
      "resourceAttributes":{
         "namespace":"kubernetes-dashboard",
         "verb":"get",
         "resource":"configmaps",
         "name":"kubernetes-dashboard-settings"
      }
   },
   "status":{
      "allowed":false
   }
}
```

**Comment by floreks** [comment]
Here is how it looks for me with K8S v1.15 and admin access to the cluster. I'll have to check if there were some changes between K8S versions.

```bash
kubectl auth can-i get ConfigMap/kubernetes-dashboard-settings -n kubernetes-dashboard --v=10
```
```json
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "kubernetes-dashboard",
      "verb": "get",
      "resource": "configmaps",
      "name": "kubernetes-dashboard-settings"
    }
  },
  "status": {
    "allowed": true
  }
}
```

```bash
kubectl auth can-i GET ConfigMap/kubernetes-dashboard-settings -n kubernetes-dashboard --v=10
```
```json
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "kubernetes-dashboard",
      "verb": "GET",
      "resource": "configmaps",
      "name": "kubernetes-dashboard-settings"
    }
  },
  "status": {
    "allowed": true
  }
}
```

**Comment by JackWindows** [comment]
Can you try using a user with tailored permissions to query?
In my k8s cluster the admins don't have the issue, but regular users all have this problem.
Mu assumption is that admin probably get granted under some wildcard rule when accessing the `cani` api endpoint.

**Comment by floreks** [comment]
I have used the below yaml file for tests. Apparently Kubernetes uses case sensitive check and SSAR output will be false if as a verb it gets `GET` and your user permission to access the config map uses `get` verb.

Second issue you have already found. It requires a resource name in a lower-case plural format (`configmaps`). This one we have to fix on our side. I'll also update logic to use `get` instead of `GET` as it is more popular, although it is quite unexpected that they are not treated as equal.

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kubernetes-dashboard
  name: kubernetes-dashboard-settings-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-dashboard-settings-test
  namespace: kubernetes-dashboard
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  resourceNames: ["kubernetes-dashboard-settings"]
  verbs: ["get", "GET"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-dashboard-settings-test
  namespace: kubernetes-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard-settings-test
  namespace: kubernetes-dashboard
roleRef:
  kind: Role
  name: kubernetes-dashboard-settings-test
  apiGroup: rbac.authorization.k8s.io
```
