### ISSUE TITLE
Kubeconfig config file login

### ISSUE THREAD

**Issue by tirelibirefe** [kubernetes/dashboard#5184]
I'm using k8s 1.18
I've installaed kubernetes-dashboard from stable/kubernetes-dashboard --version 1.10.1 via Helm.
Kubernetes config file login doesn't work. it says:

``Not enough data to create auth info structure.``

**Comment by floreks** [comment]
We do not support v1 anymore and it definitely does not support K8S v1.18. Use v2.

/close
