### ISSUE TITLE
Option to change default values

### ISSUE THREAD

**Issue by rhefner1** [kubernetes/dashboard#5196]
##### What would you like to be added

I would like the ability to change the default values for auto-refresh and the other settings that are defined here: https://github.com/kubernetes/dashboard/blob/master/src/app/backend/settings/api/types.go#L118

I understand that it's possible to change them in the Settings page, but that only persists locally and I want everyone in my organization to use different defaults. For our workloads, a 5 second refresh time is distracting and makes it difficult to use the tool. I would like the ability to globally either disable it or set it higher (and the user would have the option to change it in their local browser of course).

It would also be helpful to change the items per page and the cluster name instead of making my users did it themselves.

##### Why is this needed
See above.

**Comment by floreks** [comment]
The "default" you have pointed to is only the default in-case our API fails to return it. It is already customizable through the global settings UI and enforced for everyone as it is persisted in a config map. We could provide an option to override it through the local settings, but they'll be lost after clearing cookies.

**Comment by maciaszczykm** [comment]
You can also edit the config map directly to change it without dealing with the UI.

**Comment by maciaszczykm** [comment]
Something like:

```
data:
  _global: >-
{"clusterName":"MyCluster","itemsPerPage":10,"logsAutoRefreshTimeInterval":5,"resourceAutoRefreshTimeInterval":5,"disableAccessDeniedNotifications":true}
```

In the config map that is deployed with dashboard.

**Comment by rhefner1** [comment]
Aha, got it. Thanks for clearing up my confusion @floreks and @maciaszczykm !
