### ISSUE TITLE
Integration with kubedash

### ISSUE THREAD

**Issue by vishh** [kubernetes/dashboard#52]
[Kubedash](https://github.com/kubernetes/kubedash) provides an easy to use resource monitoring dashboard for kubernetes clusters. Is it possible to integrate kubedash into the dashboard?

**Comment by bryk** [comment]
We're well aware of existence of Kubedash. It is theoretically possible to merge those two UIs. However, there will be no 1-to-1 mapping for kubedash views. This UI will display metrics for resources, but it will not be the main use case. 
What we can realistically do, is to take useful pieces of code from kubedash and integrate them with UX of this project.

Does this answer your question?

**Comment by vishh** [comment]
Fair enough.
Until resources are fully integrated iton this dashboard, can we add links
to kubedash in this dashboard (assuming kubedash will run as a cluster
service)?

**Comment by bryk** [comment]
@kenmoore @aronchick
