### ISSUE TITLE
ability to set default login-mode?

### ISSUE THREAD

**Issue by tony-kerz** [kubernetes/dashboard#5210]
##### What would you like to be added

would like to be able to pass a parameter similar to `--authentication-mode` that will determine the default selected sign-in method, something like `--login-mode=kubeconfig`

`10.x` versions defaulted to "Kubeconfig" which we happen to use most often, and the `2.x` versions now default to "Token" which requires an extra step for our users.

##### Why is this needed

to tailor the ux based on usage patterns

##### Comments

i took a quick glance at the typescript code and i thought `--authentication-mode=kubeconfig` might work, but it didn't. 

> i would be happy to attempt a p/r if the owners think this is a reasonable enhancement.

best,
tony.

**Comment by floreks** [comment]
Ye, this was done on purpose as based on our information and user feedback token is the most commonly used option. The backend flag for such a small thing is not really an option. It would have to be a part of i.e. global settings or something that could be added to local settings that are stored in a cookie.

**Comment by shu-mutou** [comment]
Order of login modes were set as order of `--authentication-mode` options before.
I confirmed following change became not working.
https://github.com/kubernetes/dashboard/pull/4921
I'll check it.

**Comment by shu-mutou** [comment]
`kubeconfig` is not allowed for `--authentication-mode` option. The option is also used when login with kubeconfig, and credencials in kubeconfig would be seleceted according to this option. `kubeconfig` is added as login mode in frontend. So this option can not use for setting `kubeconfig` as default.

@floreks How about store selected login mode (= selectedAuthenticationMode) into localStorage and use it again at next time? This would allow any user to use previous selection.

**Comment by tony-kerz** [comment]
thanks a lot for helping out with this @floreks and @shu-mutou, your #5246 solution is great, appreciate it!
