### ISSUE TITLE
Acces dashboard via kubeconfig environnement variable 

### ISSUE THREAD

**Issue by samsja** [kubernetes/dashboard#5211]
##### What would you like to be added
It would be realy nice to be able to connect to the k8s dashboard via the kubeconfig file by using the environment variable : KUBECONFIG to direclty find to path to the kubeconfig. It should work the same way kubectl work.

##### Why is this needed

It is needed because it take times to navigate to the ~/.kube/config files via the graphical interface of the file browser, especialy when they are a lot of hidden files/folders in the home directory.

It would facilitate the uses of the k8s dashboard a lot :)

Thanks in advance for reading this feature request

**Comment by floreks** [comment]
This is not possible. Websites are running in the browser. They do not have access to the env variables of the system. It would be a major security issue if any website could access your system data.

/close
