### ISSUE TITLE
Setup auto-release for Helm charts

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#5213]
See: .travis.yml

**Comment by floreks** [comment]
@desaintmartin `gh-pages` branch does not really need all the code, right? Can we only leave the readme and `*.tgz` archives?

**Comment by desaintmartin** [comment]
1/ Sure, only the index.yaml and the chart archives (one per version) is needed.
2/ When we discussed a few months ago, we did not have a r/w github token. Now that it seems it is the case, I probably can fully automate release of chart when creating a tag.

It may take a few days for this to be done!

**Comment by floreks** [comment]
2. I was actually talking about `sh ./aio/scripts/` executing whole directory instead of a single script.

**Comment by desaintmartin** [comment]
Hm, indeed. I'll solve this in the next PR (either by automating it, thus uncommenting and fixing, or just fixing).

**Comment by maciaszczykm** [comment]
@floreks I was thinking the same. At the beginning decided to keep everything, but I'd also prefer to clean things up eventually.

**Comment by desaintmartin** [comment]
Could you tell me what is the variable containing the github token in github actions?

**Comment by floreks** [comment]
I have to add it. It will be GITHUB_TOKEN.

**Comment by desaintmartin** [comment]
Hm, according to https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#naming-your-secrets, secrets can't start with `GITHUB_`, I propose `DEPLOY_TOKEN`.

**Comment by desaintmartin** [comment]
Done in https://github.com/kubernetes/dashboard/pull/5310.
