### ISSUE TITLE
Helm Chart: list chart in Helm Hub

### ISSUE THREAD

**Issue by desaintmartin** [kubernetes/dashboard#5216]
##### What would you like to be added
- Helm Chart being listed in https://hub.helm.sh
- Old Chart at https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard being deprecated

##### Why is this needed
- For discoverability. While chart is technically working without being listed, the Helm Hub is becoming the default search engine (also powering `helm search hub` behind the scene) for Helm Charts.
- Deprecation of old chart: so that no new work is done there, but in this repository instead.

**Comment by desaintmartin** [comment]
This is a follow-up of https://github.com/kubernetes/dashboard/pull/4502.

Work is being done at https://github.com/helm/hub/pull/356 and https://github.com/helm/charts/pull/22627.

**Comment by desaintmartin** [comment]
Dashboard is accessible from the Helm Hub: https://hub.helm.sh/charts/kubernetes-dashboard/kubernetes-dashboard

**Comment by desaintmartin** [comment]
Chart from https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard has been deprecated.

**Comment by desaintmartin** [comment]
Dashboard is accessible from the Helm Hub: https://hub.helm.sh/charts/kubernetes-dashboard/kubernetes-dashboard.

Note that my name appears instead of SIG UI as maintainer. @maciaszczykm is that acceptable?

**Comment by floreks** [comment]
You are the maintainer of the chart now, so it's fine for me :slightly_smiling_face:

**Comment by desaintmartin** [comment]
Perfect, closing.
