### ISSUE TITLE
Run Dashboard as nonroot user

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/dashboard#5222]
##### What would you like to be added
Move the dashboard from executing as the root user to a nonroot user.

##### Comments
There are a few ways to handle this:

1) Move to distroless/static:nonroot
2) Do something like the following (https://medium.com/@lizrice/non-privileged-containers-based-on-the-scratch-image-a80105d6d341)
```Dockerfile
FROM ubuntu:latest
RUN useradd -u 10001 scratchuser
FROM scratch
COPY dosomething /dosomething
COPY --from=0 /etc/passwd /etc/passwd
USER scratchuser
```
3) `USER 1000` (Im not actually sure if this will work but it was suggested as a potential workaround in another conversation Ive had)

Thoughts?

**Comment by jchauncey** [comment]
The reason for this is that security scans are showing that the image was built with a nonroot userwhich goes against the CIS guidelines. Even though a nonroot user may be set at run time this still fails the scan

**Comment by floreks** [comment]
Already available in the latest release.

/close
