### ISSUE TITLE
Getting 502 Errors when accessing Health-Cloud-Revolutionary Namespace

### ISSUE THREAD

**Issue by DeJesusa2** [kubernetes/dashboard#5226]
##### Steps to reproduce

1. Log on to kubernetes lab
2. Change name space to Health Cloud Revolutionary

Results 
Page eventually displays 502 error as indicated below

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.1
Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0
```

##### Observed result
Dashboard reported Unknown Server Error (502):
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

##### Comments
Might be just specific to health-cloud-revolutionary namespace as I can view health-cloud namespace with no issue.

**Comment by floreks** [comment]
I don't see how is this related to the Kubernetes Dashboard. `v1` is also deprecated.

/close
