### ISSUE TITLE
Add support to edit a secret resource

### ISSUE THREAD

**Issue by ericandrewlewis** [kubernetes/dashboard#524]
I'd like to add and edit secret resources via the dashboard.

**Comment by cheld** [comment]
We have created a new UI framework concept that can be extended for resources. See:

https://github.com/kubernetes/dashboard/issues/584

**Comment by digitalfishpond** [comment]
This can be closed now thanks to #1060

**Comment by maciaszczykm** [comment]
@digitalfishpond #1060 is not merged yet.

**Comment by bryk** [comment]
Should be merged soon.
