### ISSUE TITLE
Not able to access Dashboard homepage, getting 404

### ISSUE THREAD

**Issue by salujanitin** [kubernetes/dashboard#5242]
Hi Team,

I have deployed a Kubernetes Dashboard using the link (https://github.com/kubernetes/dashboard/blob/master/docs/user/installation.md#recommended-setup) over https.
Now when i'm trying to access the <my-domain>/kubernetes-dashboard/ it is giving me 404.
I have checked the old issues, where custom tls certs are used. But not able to fix the issue.

Please help.

Thanks
Nitin Saluja

**Comment by floreks** [comment]
Not sure what you are trying to access exactly. If you haven't actually configured any ingress or LB, then it will not be available publicly. Follow the readme steps and use `kubectl proxy` to access it.

**Comment by salujanitin** [comment]
@floreks I have configured ingress in private VPC on Amazon EKS.

**Comment by floreks** [comment]
Then I can't really help with that. This is a custom configuration. If the Dashboard pod status is `Running` then it's up to you to configure everything properly to access the application. 

/close
