### ISSUE TITLE
Wrong display of icons in producion

### ISSUE THREAD

**Issue by taimir** [kubernetes/dashboard#529]
##### Environment
```
Dashboard version: HEAD
Kubernetes version: HEAD
Operating system: Ubuntu 14.04 LTS
Node.js version: v4.2.3
Go version: 1.5.1
```

##### Steps to reproduce
Checkout HEAD of master branch of dashboard. If needed, run `npm install` to get the recent icons changes. Run `gulp serve:prod` to serve in production.

##### Observed result
The icons (e.g. in the deploy form) are not displayed correctly:

![dashboard_issue](https://cloud.githubusercontent.com/assets/8666527/13741745/1a3735c0-e9d8-11e5-9d38-853a4796ee44.png)

##### Expected result
The material design icons should be displayed correctly. The text on the screen should not overlap.

##### Comments
I think this was caused by 949f4c976a042ed9728753cf6d89eb803fd96276. When I check out a previous commit (e.g. fed0c9fed7f1a42a416005a7aa4b866999036f1a), there is no issue.

**Comment by taimir** [comment]
@maciaszczykm can you take a look? Might be a problem with my setup?

**Comment by maciaszczykm** [comment]
I'll check.

**Comment by maciaszczykm** [comment]
We need to use https://github.com/google/material-design-icons/tree/master/iconfont content and place it in our assets instead of adding new bower components like I did before.

**Comment by taimir** [comment]
You mean cloning into `src/app/assets`? I guess that would work. The alternative would be to actually move the `bower_components/... icon asset files ...` during the `gulp assets` task to the dist, but then the relative paths won't match in development vs. production. 

I think your suggestion might well be the easier / better way.
