### ISSUE TITLE
kubernetes-dashboard-settings configmap is not created by Helm chart

### ISSUE THREAD

**Issue by mfilocha** [kubernetes/dashboard#5295]
```
Installation method: helm chart 2.0.1
Kubernetes version: 1.15.11
Dashboard version: 2.0.3
```

##### Steps to reproduce
Install kubernetes-dashboard with Helm.

##### Observed result
Dashboard pod log says: _Cannot find settings config map: configmaps "kubernetes-dashboard-settings" not found_.

##### Expected result
The configmap should be created by the Helm chart. Dahsboard role itself is not allowed to create this configmap. 

##### Comments
I guess this change was reverted by a purpose: https://github.com/kubernetes/dashboard/pull/2619/files

**Comment by floreks** [comment]
Removing the privileges to create ConfigMaps was indeed intentional as create privileges cannot be limited to a single resource name just yet. All resources should be created beforehand and Dashboard should only be able to update them.

**Comment by mfilocha** [comment]
Sure, I understand this approach. I hope Helm can deal with that configmap creation.

**Comment by desaintmartin** [comment]
Solved in https://github.com/kubernetes/dashboard/pull/5310, feel free to close if you agree!

**Comment by mfilocha** [comment]
I can confirm, thanks!
