### ISSUE TITLE
Automatically select partially matching namespace in namespace selector

### ISSUE THREAD

**Issue by acehead** [kubernetes/dashboard#5327]
##### What would you like to be added
When user is typing in namespace name, the dashboard filters down the list of namespaces, highlighting matching ones. It would be very convenient that when when pressed Enter the best match would be highlighted and selected, forwarding user to the chosen namespace
![image](https://user-images.githubusercontent.com/2222878/86386971-28e0df00-bc9b-11ea-8f59-ece2a1904801.png)
In this case hitting enter would select "kube-system" namespace

##### Why is this needed
It would be very convenient if you have many temporary namespaces (aka preview environments) which have complex names based issue keys or commit hashes. Typing in just part of the namespace, for example issue number and hitting Enter would do the job, otherwise you should use cursor to pick your choice.

##### Comments
Hotkeys for namespace selector and search field would be appreciated. I was not able to find any info whether they exist or not.

**Comment by maciaszczykm** [comment]
This cannot be done as namespace selector allows to enter any name as some of the namespaces might be not listed but accessible. I remember discussing it some time ago but I cannot find an issue at the moment.
