### ISSUE TITLE
Update bower and npm deps

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#534]
Hey, greenkeeper has some hiccup for a couple of weeks and it is not updating our deps. We should do the update asap, as the longer we wait the more problems we'd have. The tool to use: https://github.com/tjunnone/npm-check-updates

**Comment by floreks** [comment]
We can add gulp task to maintain these updates. I see that there is integration with 3rd party code available. What do you think?

**Comment by bryk** [comment]
gulp task sounds good. Re 3rd party code: what is this? We've already been using greenkeeper, but it stopped working for some reason.

**Comment by floreks** [comment]
I'm just referring to this: https://github.com/tjunnone/npm-check-updates#integration

By 3rd party code they mean gulp/grunt I guess.

**Comment by bryk** [comment]
I like it. We can have a gulp task to update and a gulp check to *warn* in case of outdated deps. 

Can you take this? :)

**Comment by floreks** [comment]
Sure. I'll work on that.

**Comment by floreks** [comment]
I believe this is done. Right?

**Comment by bryk** [comment]
Yep
