### ISSUE TITLE
Helm Chart: Provide ability to define custom podLabels

### ISSUE THREAD

**Issue by oranje42** [kubernetes/dashboard#5362]
##### What would you like to be added
Ability to define custom `podLabels` when installing the dashboard via Helm, similar to the already existing `podAnnotations`

##### Why is this needed
By providing custom `podLabels`, the kubernetes-dashboard pods could be configured with addditional labels so that other cluster components can select those pods in order to perform further customization (or instrumentation) on those. In my particular use case, the dashboard pods are proxied by an Istio sidecar to which I would like to add a custom envoy filter to participate on existing SSO sessions. The filter is already present and gets applied automatically to all pods that contain a custom label, hence the need for custom `podLabels`.

**Comment by desaintmartin** [comment]
Solved by https://github.com/kubernetes/dashboard/pull/5363
Thanks!
/close
