### ISSUE TITLE
Update kubernetes.io/docs/user-guide/ui/ documentation

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#538]
Currently docs at http://kubernetes.io/docs/user-guide/ui/ start with "Accessing Dashboard" and explains some implementation details irrelevant to our users. Can we maybe split it into installation guide for users that do not have it? Basically we need to make it focused on beginner users. 

Next, the screenshots are stale. How about updating?

**Comment by bryk** [comment]
cc @GertiPoppel @cheld

**Comment by cheld** [comment]
On the website the UI user guide is in the section Support->Troubleshoot -> Web

I think this has legacy reasons from Kube-UI. I would suggest to move it to the user guide section

**Comment by bryk** [comment]
Yes, I agree. Do we have any spare cycles to work on this?

**Comment by cheld** [comment]
Github pages had some problems with the case sensitive user name of Gerti. I renamed to her from GertiPoppel => gertipoppel. 

@gertipoppel do you work on this?

**Comment by gertipoppel** [comment]
Yes, I will also update the zero state page with the link for "system applications". Will be done tomorrow.

**Comment by gertipoppel** [comment]
This issue is addressed by PR https://github.com/kubernetes/kubernetes.github.io/pull/223
@bryk @cheld 
Please review

**Comment by bryk** [comment]
Thanks! I've reviewed it and hope that docs folks will merge it soon.

**Comment by cheld** [comment]
I also reviewed it a while ago

**Comment by gertipoppel** [comment]
@bryk @cheld  This can be closed now... Finally merged :)

**Comment by cheld** [comment]
fine

**Comment by bryk** [comment]
Awesome :)
