### ISSUE TITLE
Keep the original URL when a login is needed

### ISSUE THREAD

**Issue by Congelli501** [kubernetes/dashboard#5380]
##### What would you like to be added
When going to a specific URL of the kubernetes dashboard (like https://localhost:9443/#/overview?namespace=some-namespace) and a login is required, we get redirected to the login page (https://localhost:9443/#/login) and, after the login, instead of going back to the original requested URL, we go to the default namespace (https://localhost:9443/#/overview?namespace=default)

##### Why is this needed
We bookmark some dashboard URLs, so it would be a usability improvement to always and up on the original requested URL.

##### Comments
To keep things stateless, a redirect to the login page with a "?redirectTo=/#/overview?namespace=some-namespace" should work fine. The login page would them redirect to that URL if provided or fallback to the default URL.

**Comment by floreks** [comment]
/duplicate https://github.com/kubernetes/dashboard/issues/5340
/close
