### ISSUE TITLE
error when kubectl create -f 

### ISSUE THREAD

**Issue by jadeStoneStonger** [kubernetes/dashboard#5394]
## when
kubectl create -f https://github.com/kubernetes/dashboard/tree/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

## then
error: error parsing https://github.com/kubernetes/dashboard/tree/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context

**Comment by jadeStoneStonger** [comment]
This is bug? or What did I do wrong  ？Need your help

**Comment by jadeStoneStonger** [comment]
Thanks

**Comment by floreks** [comment]
v1 is no longer supported, use v2

/close
