### ISSUE TITLE
Failed Job has green checkmark

### ISSUE THREAD

**Issue by DP19** [kubernetes/dashboard#5400]
##### Environment

```
Installation method: Helm
Kubernetes version: v1.16.8-eks-fd1ea7
Dashboard version: v2.0.3
Operating system: Amazon Linux
```

##### Steps to reproduce
1. Launch Job that is designed to fail by having a pod terminate with error

##### Observed result
The Job in the UI will show a green checkmark but the pod will show it's terminated with Error and kubectl will report the job as failed

##### Expected result
In v1 it showed the job with a red exclamation point indicating the job as failed, I would expect v2 to do the same

**Comment by floreks** [comment]
Related to #5214

**Comment by sneko** [comment]
@floreks could you reopen the issue/PR #5214 please? It seems the robot has closed it even if labeled as `priority/important-soon`

Thanks

**Comment by rasmusson** [comment]
This problem still exist

**Comment by rasmusson** [comment]
Sorry amature hour. Must have made a mistake. Status icons look good.
