### ISSUE TITLE
Make "Created" the default sort order for jobs

### ISSUE THREAD

**Issue by WoLpH** [kubernetes/dashboard#5415]
##### What would you like to be added

For jobs the default sort order is kind of useless. It's sorting by name right now, but with jobs the latest results are the most useful.

There's been an issue about this before but I believe that only added support for sorting when desired, it didn't change the default order: https://github.com/kubernetes/dashboard/issues/1677

##### Why is this needed

Job names are often arbitrary or even randomly generated. Sorting by the "Created" column would be far more useful.

**Comment by floreks** [comment]
It is definitely sorted by default by the `created` column in the latest version.

https://github.com/kubernetes/dashboard/blob/290b0e62b540dfdad12b9492412c57f01b28738b/src/app/frontend/common/components/resourcelist/job/template.html#L39-L45

![Zrzut ekranu z 2020-08-12 14-18-52](https://user-images.githubusercontent.com/2285385/90014090-c66dfc00-dca6-11ea-85ec-9154ce2204e3.png)

/close

**Comment by WoLpH** [comment]
Perhaps I've run into a bug in that case because it's definitely not working for me:

![image](https://user-images.githubusercontent.com/270571/90014595-a8ed6200-dca7-11ea-9a30-e80e3ea34c69.png)

I'm running: Dashboard v2.0.0+0.g1f66b1c

Could it be namespace dependent? I only have jobs in the non-default namespace

**Comment by WoLpH** [comment]
Nevermind... I'm now noticing that the default deploy file apparently fixes the version so it won't get any updates
I'll test again with the latest version

**Comment by WoLpH** [comment]
It should be noted that the readme on dockerhub points to 2.0.0 as well: https://hub.docker.com/r/kubernetesui/dashboard

Is there a reason why there isn't a `:latest` tag for the dashboard? That would be much easier than manually updating

**Comment by WoLpH** [comment]
Anyhow, it's working with the latest version. Sorry for the noise!
But should a `:latest` tag be added to dockerhub?

**Comment by floreks** [comment]
> It should be noted that the readme on dockerhub points to 2.0.0 as well:

Ye, we have to provide link to the GH readme there instead of copying it. Images are automatically updated, and we don't really update readme there.

> But should a :latest tag be added to dockerhub?

I am not sure. We have never used the latest tag for the official releases. We probably could. Not sure how many people would actually want to receive automatic updates of deployments on the production without their knowledge.

**Comment by WoLpH** [comment]
> I am not sure. We have never used the latest tag for the official releases. We probably could. Not sure how many people would actually want to receive automatic updates of deployments on the production without their knowledge.

It could be done as an addition. People can still use the tagged versions if they wish :)

**Comment by floreks** [comment]
@WoLpH I have created an issue for that #5417 and updated our README on DockerHub.
