### ISSUE TITLE
Age does not match with the creation time 

### ISSUE THREAD

**Issue by louhde** [kubernetes/dashboard#5416]
##### Environment

```
Installation method: documentation YAML
Kubernetes version: 1.18.0
Dashboard version: v2.0.2+0.g6e052ca15
Operating system: Debian 10 - Buster
Node.js version ('node --version' output): the version provided by image
Go version ('go version' output): the version provided by image
```

##### Steps to reproduce

No particular steps, just go to any ressources on dashboard 
I see this result on every ressources types 

##### Observed result

Will provide "a day ago" or "-" but not the right value 

##### Expected result

Don't really know, my dashboard is in french and it's called "age" but may be the uptime ? 

##### Comments

Here's a screenshot for french speaking people, in metadata section of Nodes 

![Capture d’écran 2020-08-12 141459](https://user-images.githubusercontent.com/16855765/90014457-63309980-dca7-11ea-8b31-3d9708c12418.png)

**Comment by floreks** [comment]
I guess we should get rid of age and leave only the `Created` since both of them use the same date underneath just with different formatting.

@maciaszczykm wdyt?

**Comment by maciaszczykm** [comment]
>I'd "merge" both of them and use Created with the formatting that is used in Age field.

I agree.

**Comment by louhde** [comment]
Could be a good idea @floreks. 
In the list of nodes in french you could see Date of creation and it give me the same wrong value.  

![Capture d’écran 2020-08-12 150957](https://user-images.githubusercontent.com/16855765/90018940-fd93db80-dcad-11ea-925d-3cae10f902ef.png)

**Comment by floreks** [comment]
Is the value here wrong? I'd say that it is a translation issue. In English it is ok since we have `Created: a day ago` and it makes perfect sense.

**Comment by louhde** [comment]
Yes it's wrong. It's the same ressource than the previous screenshot, I created this node the July, 31. This should a lot of days more

**Comment by floreks** [comment]
This is quite interesting. Can you hover over it and check the actual date?

**Comment by louhde** [comment]
![image](https://user-images.githubusercontent.com/16855765/90023330-e8ba4680-dcb3-11ea-90df-0eea7c00a748.png)

It gaves me the expected date

**Comment by floreks** [comment]
This is getting really interesting.

1. Please check the developer console in your browser for any errors
2. Please go to `http(s)://<your.dashboard.link>/config`

It should return something like this:
```json
{
  "serverTime": 1597240613708
}
```

Paste the result here.

**Comment by louhde** [comment]
No errors on the developer console. 

`serverTime | 1597240877198`

**Comment by louhde** [comment]
Wait ... I made litterally nothing on my cluster and it changes to the good value. Maybe a request was stuck somewhere, very strange
![image](https://user-images.githubusercontent.com/16855765/90024725-7c404700-dcb5-11ea-9563-73b1353962e6.png)

**Comment by floreks** [comment]
I can only think of 2 possible cases that might have caused it.

1. You haven't use Dashboard for some time and your browser used cached value of server time response from the API to calculate age.
2. Date in your system/browser was invalid.

**Comment by louhde** [comment]
It could be a caching issue, this is the most relevant option to me. Date is good everywhere by the way.
Thanks for your help and your time, have a good day

**Comment by floreks** [comment]
Good that it is working now :slightly_smiling_face: 

For the future, you can disable caching for the Dashboard in the developer tools.

In Chrome it looks like this
![Zrzut ekranu z 2020-08-12 16-19-05](https://user-images.githubusercontent.com/2285385/90026470-9da23280-dcb7-11ea-8545-83af88bc53a6.png)

Have a nice day.

/close
