### ISSUE TITLE
Wrong alignment of items on deploy page

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#544]
##### Environment

```
Dashboard version: latest
```

##### Steps to reproduce
1. Go to deploy page.
2. Show advanced options.

##### Observed result
![image](https://cloud.githubusercontent.com/assets/2823399/13849982/83a3ef80-ec58-11e5-9104-3e99d0b8bed9.png)

##### Expected result
Correct alignment of items.

**Comment by maciaszczykm** [comment]
I also believe, that paddings for this page should be a little bit larger. Space between text and border seems to be smaller than on other pages.

**Comment by bryk** [comment]
Yeah, this can be fixed by applying `layout-padding` attribute to the deploy card element. Can you do this? Should be fast & easy and fix this annoying issue.
