### ISSUE TITLE
Login to Dashboard is granted if invalid Token is provided

### ISSUE THREAD

**Issue by discostur** [kubernetes/dashboard#5447]
If you try to login with a wrong token you should normally see a message like:

```
Unauthorized (401): Invalid credentials provided
```

However, if you just type 8x whitespace you are logged in - but you cannot see anything (no pods, no resources, etc.). Seems like a bug for me ... you should also get a "401" message.

Works also with just 1x whitespace (select token as login method).

```
Kubernetes version: 1.15.x
Dashboard version: 2.0.3
```

**Comment by floreks** [comment]
### Request
![Zrzut ekranu z 2020-08-19 16-25-32](https://user-images.githubusercontent.com/2285385/90647542-b622c780-e238-11ea-915d-49d69578236f.png)

### Response
![Zrzut ekranu z 2020-08-19 16-26-40](https://user-images.githubusercontent.com/2285385/90647623-ca66c480-e238-11ea-9d9a-b8940f8c6edb.png)

Seems to be working just fine for me. It might be due to your API server accepting it or falling back to anonymous user in such case. We pass the token to the API server and check if user is able to get the response from version endpoint. If your API server allows that then there is nothing we can do.

Authn & Authz is relying fully on the Kubernetes API server. We do not manage that at all other than take whatever you provide and proxy it further.

**Comment by discostur** [comment]
Looks like you are right - i just found that the apiserver runs per default with 

```
--anonymous-auth = true
``` 

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

When i login via dashboard and whitespace token i am authenticated as system:anonymous. But what i don't understand is that i can only trigger anonymous login when i type a whitespace in the token box. If i type a wrong token or any random keys i get an 401 ... only whitespace triggers the anonymous login:

<img width="332" alt="Bildschirmfoto 2020-08-19 um 16 39 11" src="https://user-images.githubusercontent.com/2615420/90649802-6691cb00-e23b-11ea-932a-b50a8d5cdf41.png">

If thats expected behaviour we can close this issue ;)

**Comment by floreks** [comment]
I guess API server trims all whitespace characters and acts as nothing has been passed. That's why it falls back to the anonymous user. I can mark it as an enhancement to detect that on our side first.

**Comment by marcvs** [comment]
I have a similar twist over here: I can log in (to the web frontend) with a token that was generated yesterday.

After some time, I'm logged off with the 401 message saying that my token *expired*.

However, I can use that same token to authenticate again. So either it's not really the token that is expired, or I can use an expired token to log-in. The jwt itself does not seem to provide expiry information, though, so this might be a separate bug.

**Comment by floreks** [comment]
This is not a bug. The token you are using doesn't really matter. It is used as a password basically. The one that expires is the JWE token that we generate during logging in.

**Comment by euh2** [comment]
> This is not a bug. The token you are using doesn't really matter. It is used as a password basically. The one that expires is the JWE token that we generate during logging in.

I think I have a similar issue. My question then is how to extend the time a Dashboard-generated JWE token is valid? I looked trough the arguments and possible settings, but didn't find anything about token timeout.

I use `Keycloak as IdP, oauth-proxy and Ingress Nginx`. Login works as expected, but `kube-apiserver-NODE` shows "token  expired" after some minutes inactivity. I think it shouldn't be like that.

**Comment by euh2** [comment]
Timeout seems to be 5min.

**Comment by floreks** [comment]
Check Dashboard arguments in our documentation. There is a token-ttl argument that controls it.

**Comment by euh2** [comment]
I apparently overlooked that argument. I just tried adding the argument to my deployment, but the token still expires after 5 min.
```yaml
...
    spec:
      containers:
      - args:
        - --namespace=kubernetes-dashboard
        - --enable-insecure-login
        - --token-ttl=604800
        image: kubernetesui/dashboard:v2.0.4
```
Tried with value `0` which should never expire, and with `604800` (a week). One of many lines in apiserver log bellow:
```log
E1028 14:31:06.079693       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, oidc: verify token: oidc: token is expired (Token Expiry: 2020-10-28 13:26:18 +0000 UTC)]
```

**Comment by floreks** [comment]
This is not our token. This is the one that your OIDC provider gives you. It expires and we can't extend it for you.

**Comment by euh2** [comment]
> This is not our token. This is the one that your OIDC provider gives you. It expires and we can't extend it for you.

You're right! It was the IdP Access Token. I misunderstood, I thought the IdP Token never reaches the API Server. Thanks!

**Comment by floreks** [comment]
@euh2 Dashboard does not handle auth at all. We proxy everything to the API server and let it handle it for us.
