### ISSUE TITLE
How to secure dashboard access?

### ISSUE THREAD

**Issue by dcgoss** [kubernetes/dashboard#545]
Hey guys, sorry if this has been answered before.

What is the recommended way to secure access to the dashboard? It doesn't look like there is a mechanism for login, and the `kubectl create -f` command to launch the dashboard exposes the dashboard on the node port, which is obviously fairly insecure.

**Comment by bryk** [comment]
Currently if you want security you should access it via apiserver proxy, e.g., https://my-master/api/v1/proxy/namespaces/kube-system/services/kuberentes-dashboard. Or, if you run 1.2 cluster: https://my-master/ui. 
Next option is if you run in, say, company network. Then you can expose service via LoadBalancer option configure your firewall to do security.

Does this help?
