### ISSUE TITLE
can't login in the prod env

### ISSUE THREAD

**Issue by Frodez** [kubernetes/dashboard#5450]
dependencies version:
```
kubernetes-dashboard: v2.0.3 
Firefox: 79.0 
Chrome: 84.0.4147.135 
Ubuntu: 20.04 
```

Sorry for bother you another time.

I can login in the dev mode. However, I can't login in the prod mode. 

At first, I run the dashboard with `npm run start:prod`. Then I open the browsers(Firefox and Chrome), and input the token. Then nothing happens.

At the same with  #4922, the `router.navigate(['overview'])` has been called but not jumped to overview page.

**Comment by floreks** [comment]
Sounds like some dependency issue in your environment. This is definitely not a bug on our side.

**Comment by Frodez** [comment]
Ok, I have made some new discoveries based on the master branch.
I find the rxjs operators (`merge`, `of`, etc) are imported from `'rxjs/operators'` rather than `'rxjs'`.  Besides, the Subject is imported from `'rxjs/Subject'`. This is an old way to import operators. However, the version of rxjs in package.json is 'v6.6.2'. 
After I have changed them, the problem about `router.navigate(['overview'])` has disappeared.

Ref:

1. https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/components/list/filter/component.ts#L21
2. https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/resources/list.ts#L41
https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/resources/list.ts#L42
3. https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/components/breadcrumbs/component.ts#L44
https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/components/breadcrumbs/component.ts#L45
