### ISSUE TITLE
Show more labels / restrict by display size of labels

### ISSUE THREAD

**Issue by WoLpH** [kubernetes/dashboard#5456]
#### What would you like to be added

Currently the dashboard shows 2 labels which means I need to click "Show more" in many cases to be able to see the useful labels.

More annoyingly, it's limiting by the number of labels, not the length/size of them which means it often doesn't take any extra display space to display all instead of just 2 labels.

To illustrate:
![image](https://user-images.githubusercontent.com/270571/90963602-4c652080-e4b9-11ea-8c31-db4c4842a548.png)

![image](https://user-images.githubusercontent.com/270571/90963604-67379500-e4b9-11ea-877b-de580b065e1e.png)

It would be great if the amount of displayed labels would be configurable. And if the limit would be calculated based on the amount of characters (perhaps with a css `overflow: hidden` instead of removing the items).

##### Why is this needed

Because it requires needless clicking and it's not using screen space efficiently.

**Comment by maciaszczykm** [comment]
I'll add setting for that.
