### ISSUE TITLE
Styling issues on serve:prod

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#546]
##### Environment

```
Dashboard version: HEAD
Kubernetes version: HEAD
Browser: IE, FF, Chrome
```

On serve prod there are some styling issues. I've removed `node_modules` and `bower_components` and did a clean install. Could you check and confirm?

PS. On serve this issue does not exist.

![zrzut ekranu z 2016-03-18 11-08-26](https://cloud.githubusercontent.com/assets/2285385/13874690/c4633ba6-ecf9-11e5-9f76-5613a9298242.png)
![zrzut ekranu z 2016-03-18 11-08-36](https://cloud.githubusercontent.com/assets/2285385/13874692/c5eae1b8-ecf9-11e5-9ac7-390b55bdd1e2.png)

**Comment by bryk** [comment]
Oops, I can reproduce this. It looks like the HTML minifier is broken. It produces bogus output.

**Comment by bryk** [comment]
How about we make our bower and npm dependencies exact? And update them often?

**Comment by floreks** [comment]
We should do that. This way we will have better control over external changes that can potentially break something on our side.

**Comment by maciaszczykm** [comment]
All of them? Maybe better idea is to do it only for specific dependencies and keep others in current state?

**Comment by bryk** [comment]
I think this is fixed. I'll take care of dependencies next.

**Comment by floreks** [comment]
It's not. I've prepared a simple fix for that.

**Comment by bryk** [comment]
Ouch, sorry. My fault.
