### ISSUE TITLE
Cleanup the old way to import rxjs operators and rxjs Subject

### ISSUE THREAD

**Issue by Frodez** [kubernetes/dashboard#5470]
##### What should be cleaned up or changed

There are still some imports for rxjs operators and rxjs Subject, which use the old way before  v6. 

#5450 

##### Provide any links for context

https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/components/list/filter/component.ts#L21
https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/resources/list.ts#L41
https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/resources/list.ts#L42
https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/components/breadcrumbs/component.ts#L44
https://github.com/kubernetes/dashboard/blob/84c68469c09fa940d552204b0cffe66a142fcdbf/src/app/frontend/common/components/breadcrumbs/component.ts#L45

**Comment by floreks** [comment]
You are welcome to create a PR and clean this up.

**Comment by Frodez** [comment]
> You are welcome to create a PR and clean this up.

Thank you so much for your kindness replies.

**Comment by Frodez** [comment]
> You are welcome to create a PR and clean this up.

And my problems about the login view is fixed. Haha!

**Comment by floreks** [comment]
This is actually quite weird that changing import path fixed that. Both import ways end up in importing the same file. Additionally, no one on our side had any issues with that. This makes me wonder if the version that npm downloaded for you is really the same as ours.

**Comment by Frodez** [comment]
> This is actually quite weird that changing import path fixed that. Both import ways end up in importing the same file. Additionally, no one on our side had any issues with that. This makes me wonder if the version that npm downloaded for you is really the same as ours.
> 
> Anyway, I'm glad that it fixed the issue for you. We'll be releasing a new version tomorrow so if you fix it, it will be available in the new version.

Actually, this old way to import rxjs can cause the javascript which is finally built in prod mode works abnormally. I try to trace the errors, and find some strange logs, `filter is not a function` or `Subject is undefined`, etc. So I doubt if the rxjs is correctly imported, and my doubt is proved to be true.

That's why I find these cleanups.

**Comment by Frodez** [comment]
Okay I have pushed my PR just now, but the error message shows me that `Frodez needs CLA`. Is that normal? @floreks
