### ISSUE TITLE
Dashboard does not login due too big token

### ISSUE THREAD

**Issue by jvanz** [kubernetes/dashboard#5476]
##### Environment

```
Installation method: Helm

Kubernetes version:
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-07-30T12:00:00Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-17T12:00:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Dashboard version:
# helm list
        NAME            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
dapper-aardwolf 1               Wed Aug 19 16:00:20 2020        DEPLOYED        kubernetes-dashboard-2.3.0      2.0.3           default  

Operating system: SLES 15 SP1
```

##### Steps to reproduce

1. Configure Dex to authenticate using LDAP
2. Add a user with A LOT of groups in LDAP. I've tested with more then 100
3. Get the token for the user from step 2.
4. Try to authenticate in the dashboard using the token from step 3

##### Observed result
Dashboard gets stuck in the login page:

![error_k8s_token_too_big](https://user-images.githubusercontent.com/1514798/91344054-c8aa7d00-e7b3-11ea-8fac-2075bd7cbf74.png)

##### Expected result
Access into the dashboard

##### Comments
A similar problem has been addressed at gangway. https://github.com/heptiolabs/gangway/pull/117

**Comment by floreks** [comment]
This is a known issue. It is a part of https://github.com/kubernetes/dashboard/issues/2353

/close
