### ISSUE TITLE
Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by sumanp89** [kubernetes/dashboard#5484]
This issue is a extension of this : 
https://github.com/kubernetes/dashboard/issues/3570

The above one is closed with wrong solution.

This is happening because with new update chrome blocks 
"the cookie set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`"
The cookie in question in is named "jweToken" which we get after login. but since it is not set so it is not available for the next requests, so 401.

![image](https://user-images.githubusercontent.com/13543717/91526517-64fc8d00-e936-11ea-9c59-8569bf47fb06.png)

workaround: Currently firefox does not blocks the same, so it is working on Firefox.

Kube server: 1.16
Cloud: Azure AKS

**Comment by floreks** [comment]
Fill out the issue template correctly. I believe you are using old version of Dashboard as we are using Secure cookies for quite some time now.
