### ISSUE TITLE
Nice UI for forbidden error 

### ISSUE THREAD

**Issue by JakubJecminek** [kubernetes/dashboard#5491]
#5049 ### What would you like to be added
Currently when accessing kubernetes-dasbhoard with read-only service account (RBAC limited for only GET verb),
dashboard shows error dialog when attempting to delete/edit resources. The dialog just shows stack-trace, it would be nice for this particular case show some nice warning dialog with simple access denied message.

##### Why is this needed
Current UI is not very user friendly (just stack trace)

##### Comments
Example of current dialog is attached. 
<img width="626" alt="k8sError" src="https://user-images.githubusercontent.com/1268108/91759283-b07e9780-ebd1-11ea-86a2-f26b093f046b.png">

**Comment by JakubJecminek** [comment]
Also in certain cases (like when scaling up/down) it will show dialog with undefined 
<img width="629" alt="scale" src="https://user-images.githubusercontent.com/1268108/91834646-9d5ade80-ec48-11ea-9d85-fc8e05ea2c37.png">

**Comment by maciaszczykm** [comment]
<img width="666" alt="Zrzut ekranu 2021-08-5 o 11 38 34" src="https://user-images.githubusercontent.com/2823399/128328740-98665f57-e112-4d1a-aa09-40dc6e55e8cb.png">

I can no longer reproduce it.
