### ISSUE TITLE
RFE:  shell into container

### ISSUE THREAD

**Issue by wstrange** [kubernetes/dashboard#550]
This is more of an RFE than a bug

Something that would be incredibly useful is to be able to shell into a container from the GUI. This is something I do dozens of times per day.

Something like the ssh shell window that GCE provides...

**Comment by bryk** [comment]
Thanks for reporting this feature request!

**Comment by cheld** [comment]
I would like to understand the use case better. Could you give me a hint why you shell into a container so often?

**Comment by wstrange** [comment]
Debugging my container when something goes wrong. Usually during development. 

I might want to see container logs (that are not currently set up to  be collected through some other means), look at configuration files, verify DNS is working, see what filesystems have been mounted, etc.

**Comment by shamil** [comment]
I'm also interested in this feature.
Currently I use `weave-scope` for that, but having a native feature will be great

**Comment by rf232** [comment]
Closing this, all of the effort is in #1345
