### ISSUE TITLE
localSettings cookie for kubernetes dashboard is a session cookie and does not persist when browser is closed.

### ISSUE THREAD

**Issue by jeroenlandheer** [kubernetes/dashboard#5528]
##### Environment

```
Installation method:
Kubernetes version: 1.19
Dashboard version: v2.0.0+0.g1f66b1c
Operating system: Win10
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Open the kubernetes dashboard
2. Go to settings, select dark theme
3. Close browser
4. Open browser
5. Open the kubernetes dashboard

##### Observed result

You get the dashboard in the light theme

##### Expected result

Your settings should be preserved.

##### Comments

In Chrome, using the developer tools you can see the cookie `localSettings` is a session cookie. These expire once the browser session ends.

**Comment by maciaszczykm** [comment]
Good spot, thanks!
