### ISSUE TITLE
[WebUI Token Login] Enter any character that begins with a space to login successfully

### ISSUE THREAD

**Issue by 14032** [kubernetes/dashboard#5566]
**Dashboard v2.0.0**

![image](https://user-images.githubusercontent.com/32085009/94363822-7aacd000-00f7-11eb-82ac-697d7a7d0cfb.png)

🐛  **Enter any character that begins with a space and you will be able to login successfully，This problem is very**

**Comment by floreks** [comment]
Duplicate of https://github.com/kubernetes/dashboard/issues/5447

Fixed already in https://github.com/kubernetes/dashboard/pull/5550

Disable anonymous login in the API server. This is not a security issue since the anonymous user does not have any privileges.

/close
