### ISSUE TITLE
Kubernetes Dashboard does not work with AKS when "AKS-managed Azure Active Directory" is enabled

### ISSUE THREAD

**Issue by HansK-p** [kubernetes/dashboard#5578]
We have strong indications that Kubernetes Dashboard stops working in AKS when "AKS-managed Azure Active Directory" is enabled. This has been tested with:
- Kubernetes Dashboard 2.0.4
- AKS K8s version v1.18.8 and v1.17.9

What we see in the UI when we provide a "personal" K8s config file is: Unauthorized (401): Invalid credentials provided
What we see in the dashboard log is: Non-critical error occurred during resource retrieval: the server has asked for the client to provide credentials

Access works when providing the "system" K8s config file, but we can of course not distribute that file to our users as it gives users anonymous access to everything.

**Comment by floreks** [comment]
The only thing you have to provide is token that is acceptable by the API server, nothing else. We do not manage auth on our side, we only proxy API server response.

**Comment by HansK-p** [comment]
It looks like MS uses some new functionality when "AKS-managed Azure Active Directory" is enabled. Ref https://docs.microsoft.com/en-us/azure/aks/managed-aad where they write that Kubectl v. 1.18.1 or newer is needed when working against such a cluster (we have a user with kubectl 1.16.x who seems to have this working).

I've been able to use Octant after the change, so we do have a backup solution, but I would prefer to user Kubernetes Dashboard. I'll see if I can do a bit more investigations in the weekend. Validate 100% for sure that it is the setting "AKS-managed Azure Active Directory" that creates issues for us - and check if I can find a simple workaround.

**Comment by floreks** [comment]
Underlying provider should not impact it. It's still the K8S API server that does the authentication and authorization. If you can provide a token acceptable by it, then everything will work just fine.

**Comment by HansK-p** [comment]
Hello

My test did not go as expected. I simply did not get the Kubernetes Dashboard to work the way I expected.

What I did:
<pre>
az group create \
  --name mytest \
  --location westeurope

az aks create \
  --resource-group mytest \
  --name mytest \
  --node-count 1 \
  --generate-ssh-keys \
  --kubernetes-version 1.18.8

rm -vf ~/.kube/config

az aks get-credentials \
  --resource-group mytest \
  --name mytest

kubectl apply \
  -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

kubens kubernetes-dashboard

kubectl port-forward kubernetes-dashboard-7b544877d5-p2tdw 8443:8443
# Accessed dashboard on https://localhost:8443/ and supplied ~/.kube/config
# Did not get access (I had expected this to work)

octant # This works

az group delete \
  --name mytest \
  --yes \
  --no-wait
</pre>

It might be my test was invalid and we have a good working alternative in Octant, so I think I'll just leave it at that.

Br

Hans K.

**Comment by floreks** [comment]
> v2.0.0

This version is a bit outdated. Current version is `v2.0.4`.

> Accessed dashboard on https://localhost:8443/ and supplied ~/.kube/config

This won't really work as I believe your kubeconfig does not contain a simple token that can be used. `kubeconfig` option is only there as a substitute of `token` option if you use a valid token. Other ways of authentication will not work when using kubeconfig file. Standalone clients can offer more ways to authenticate user. Web apps are more limited here.

**Comment by HansK-p** [comment]
Hello

I was a bit afraid that my test was broken, I've now tested with v. 2.0.4 with the same result. Might be the login page should state something about this issue with using kubeconfig files. I did find information about it when I search in the documentation, but I think it would be wise to add a couple of words about this issue also in the login page. This probably explains why a kubeconfig file created using "az aks get-credentials   --resource-group mytest   --name mytest --admin" works.

In our "real" clusters, we have AAD integrate the cluster "the old AKS way" and placed KeyCloak Gatekeeper/Louketo Proxy in front of the Kubernetes Dashbard. This works fine for all our clusters, except the ones where we have activated "AKS-managed Azure Active Directory". This includes a cluster where someone activated "AKS-managed Azure Active Directory" by a mistake (which is when we discovered the issue). I still can't say 100% for sure that this activation is what broke the web interface and I didn't test this config simply because there are quite a few more steps involved (harder to reproduce, more time consuming).

I'll probably try to reproduce our issue 100% using Louketo Proxy within a few weeks, so I suppose we can close this ticket and I'll get back to you if/when we reproduce our problem.

It has to be said that I believe that technically, using user created tokens will work. But for our users this is a bit too cumbersome as we use AAD integration with RBAC, so manually creating tokens is not a realistic option (especially as long as we have a well working alternative).

Br

Hans K.

**Comment by floreks** [comment]
If you are using Keycloack and reverse proxy then it should be fairly easy for you to configure per-user access to Dashboard and disable the internal login screen. All you have to do is to add `--enable-insecure-login` argument to deployment and make proxy pass `Authorization: Bearer <token>` header with every request to Dashboard. A similar approach is described here: https://itnext.io/protect-kubernetes-dashboard-with-openid-connect-104b9e75e39c

In case you have any questions, you can ping me on kubernetes slack or write on `SIG-UI` channel there.

Good luck.

/close

**Comment by imranrazakhan** [comment]
@HansK-p  Following guide works well for Azure AD
[k8s-dashboard-with-aks-aad](https://github.com/weinong/k8s-dashboard-with-aks-aad )
