### ISSUE TITLE
Option to hide resources in sidebar that user does not have `list` permissions for

### ISSUE THREAD

**Issue by danrspencer** [kubernetes/dashboard#5586]
##### What would you like to be added
A config option that hides items in the sidebar that the currently logged in user does not have the permissions to list.

##### Why is this needed
If a user doesn't have list permissions for a resource then clicking the resource in the sidebar is always going to display this message:

```
There is nothing to display here
No resources found.
```

This means that the sidebar can contain a lot of useless links for restricted roles. In our specific use case we want to create a support role which can only list a small number of CRDs for use by our support users; currently they have a full sidebar of useless links apart from 4 links at the bottom which are the pinned CRDs. 

The ability to tidy up the sidebar based on RBAC would allows us to present a clear UI to different levels of users without having to explain which links will and will not work for them.

**Comment by floreks** [comment]
It's not something that can/should be done with configuration. It's a design choice that we made here as when the Dashboard project has started RBACs were in the very early stage and not that popular.

Design-wise you either disable/hide items that user does not have access to or show everything and then use empty lists/notifications to inform about insufficient permissions. We have chosen the second option.

As we are now working on a brand new API based on GRPC, we are already planning more granular permission management. This is something that we definitely want to have, but it will be done in a different way. Once we figure out the architecture, we'll create an issue with a better description.

I'll close this as with current API and frontend this feature is not really possible in the way you describe it.

/close
