### ISSUE TITLE
Show relative time or more detailed timestamp for first seen/last seen

### ISSUE THREAD

**Issue by WoLpH** [kubernetes/dashboard#5603]
##### What would you like to be added

Useful timestamps at the "Events" table for a pod.

##### Why is this needed

Currently only the date is visible while you often want to know the exact time or the relative time.

![image](https://user-images.githubusercontent.com/270571/95382872-9891e600-08ea-11eb-915c-4503351c15c4.png)

##### Comments

An exact timestamp would be ideal for me (ISO8601 for example), but a relative time with enough resolution (i.e. not just 5 minutes, but 5 minutes 10 seconds) would work too :)

**Comment by floreks** [comment]
Hover over the date and you'll see exact date. That's what those dots under date indicate.

/close

**Comment by WoLpH** [comment]
> Hover over the date and you should see exact date. That's what those dots under date indicate.
> 
> /close

I'm aware, but that doesn't make the current visible output any more useful.

**Comment by floreks** [comment]
@WoLpH done in #5604

**Comment by WoLpH** [comment]
thank you 🎉
