### ISSUE TITLE
Different time in logs

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#561]
##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: linux/amd64
Node.js version: v0.10.40
Go version: go1.4.2
```

##### Steps to reproduce
Create a new resource by a console "kubectl create -f name_of_image.yaml"

##### Observed result
Image was a created correctly, but in logs are a different times
![differenttimelog](https://cloud.githubusercontent.com/assets/18006407/13951618/7ecc42c2-f032-11e5-880b-d1c3c5bb981a.png)

##### Expected result
I think that these times should be the same 

##### Comments
This is probably due to set different time zones.  Is this a problem?

**Comment by bryk** [comment]
@maciaszczykm You're into timezones. What do you think?

**Comment by maciaszczykm** [comment]
In my opinion we cannot modify logs dates, messages etc. We should not touch them. Moreover, logs are not in structure containing date and message for example, we have access to raw strings only. So if dates in logs aren't matching our expectations (different timezones etc.) we should be aware of it, but I'd say we cannot do anything about it.

Regarding date in toolbar (it's pod creation timestamp from API) we should take care of it and display it for correct timezone. I don't know if it's correct in this case, @kwodzynski could you confirm it?

We should do more testing for timezones, it seems to be area, where many bugs may occur.

**Comment by cheld** [comment]
From a user perspective I would say the timezone in the  container should match the timezone of the system. So, maybe kublet should launch containers with something like `docker run -v /etc/localtime:/etc/localtime:ro`

**Comment by kwodzynski** [comment]
@maciaszczykm, I think that the solution proposed by you is rewarding

**Comment by digitalfishpond** [comment]
I will start looking into this now.

**Comment by kwodzynski** [comment]
Problem also occurs in other places eg. EVENT view in columns "First seen" and "Last seen". I think it is global bug in application.

**Comment by maciaszczykm** [comment]
To make @kwodzynski's comment more precise, by problem we mean different timezones/times set in containers. We have to make sure if it's working correctly (time and timezones).

>Regarding date in toolbar (it's pod creation timestamp from API) we should take care of it and display it for correct timezone. I don't know if it's correct in this case, @kwodzynski could you confirm it?

@kwodzynski Did you test if these dates are matching system time? What was system time during this test? I can see on screenshot, that in UI there are two dates `11:39` and `12:39`, but what was _real/valid_ time during this test? Was it one of these values, or perhaps not?

**Comment by digitalfishpond** [comment]
The time displayed in the toolbar matches system time. When I created kubernetes/examples/guestbook, the logs showed two hours earlier than system time (we had light-saving time change last Sunday). So the logs show time in standard GMT (not considering summer time-saving). Should we simply point this out?

**Comment by bryk** [comment]
How about we display all times and dates in UTC? Or at least display timezone in the selector?

**Comment by digitalfishpond** [comment]
If we changed everything to UTC ( @floreks  reckons that @maciaszczykm 's latest changes with do this anyway at least in this place - there will be others), then should we add "(UTC)" after time strings? Or is this something we would simply point out in our documentation?

**Comment by kwodzynski** [comment]
@maciaszczykm 

> @kwodzynski Did you test if these dates are matching system time? What was system time during this test? I can see on screenshot, that in UI there are two dates 11:39 and 12:39, but what was real/valid time during this test? Was it one of these values, or perhaps not?

Hour 12:39, which was displayed in the toolbar, was a real and valid system time, but hour 11:39 was a incorrect time (minus 1 hour)

**Comment by digitalfishpond** [comment]
Does anyone have an objection to making all times throughout the application UTC, and adding 'UTC' as a suffix to all time strings?

**Comment by digitalfishpond** [comment]
Little rectification. Time stamps in logs are not in UTC, they are in GMT. I made a mistake earlier. Time saving is considered. logs generated at 8:00 UTC show 9:00 in the logs, and the toolbar shows the system time. So my previous question should read:
"Does anyone have an objection to making all times throughout the application GMT, and adding 'GMT' as a suffix to all time strings?"

**Comment by cheld** [comment]
That logs are stored in GMT seems reasonable. Adding GMT seems ok for the moment. But, I am not sure if this is user-friendly... You may ask your logging neighbours how it is handled in Kibana and Monasca.
BTW: what about all other times in Dashboard? Must they be adapted as well?

**Comment by digitalfishpond** [comment]
On the details page, under the 'EVENTS' tab, there is a 'First seen' and 'Last seen' category that uses system time.
Also, the 'age' value on cards is based on system time. 
It seems to me that if we adapt one, we should adapt them all, unless we decide to specify time-zones which may (or may not) be a clunky solution... 
Further news: Google shows GMT to be equal to UTC (no light-saving considered for either), so these logs aren't even GMT, They're currently in GMT+1  (the current time in London, with light-saving applied)

**Comment by digitalfishpond** [comment]
I made some stupid mistakes yesterday. Here are the rectifications:
Logs feature time stamps ending with a 'Z'. This means 'Zulu Time' which is equivalent to UTC and also to GMT. So this information is already present in the logs which don't need to be / shouldn't be touched.
@floreks and @maciaszczykm both believe (as I do), that we should have all times throughout the application standardised to UTC / GMT / Zulu Time followed by a 'UTC' suffix.
The Monasca team say that they have not addressed the issue of time-zones in their project.

**Comment by digitalfishpond** [comment]
@bryk @cheld Does anyone have any objection to moving to a 24 hour format rather than the current AM/PM format that is default to the 'short' format currently in use in the UI? It would look less cluttered with the UTC suffix following it...

**Comment by bryk** [comment]
Hmm.. Re 24h format. Can we make this locale dependant? I.e., for en_UK do 24h and for en_US do AM/PM? This is because people in the US really only use AM/PM format.

**Comment by cheld** [comment]
So, let's Kubernetes is run in California. It is 7 am in the morning. A container is deployed. Then the UI would say the container is running since 2 PM UTC...right?

In this case I would say it is user unfriendly anyway and 14:00 UTC seems the better choice

**Comment by digitalfishpond** [comment]
(copied over from #617)
I think that AM/PM and UTC is just too much. How about I remove the 'UTC' suffix, and we add a comment in the documentation that all times in the UI are UTC? I can still make the 12/24 hour format locale dependent, but keeping both will look pretty cluttered in the US version I think. 
eg. Last seen at: 5/4/16 12:16 PM UTC

**Comment by digitalfishpond** [comment]
@bryk does have a point that the US (and the UK, btw) generally prefer the 12hour clock, so what would be user-friendly generally internationally wouldn't seem user-friendly in the US and vice-versa. What do you think about dropping the UTC suffix altogether though?

**Comment by digitalfishpond** [comment]
I have found this article about ISO 8601 (international standard date and time notation):
https://www.cl.cam.ac.uk/~mgk25/iso-time.html 

It states that dates should be in format yyyy-MM-dd and times as HH-mm-ss followed immediately by the letter z to signify utc/zulu-time. The question is now: should ISO 8601 apply to our UI?

**Comment by bryk** [comment]
Suffixing with UTC seems good enough to me.

**Comment by bryk** [comment]
Re AM/PM and 24h: Yeah, let it be. I'm for 24h format.

**Comment by digitalfishpond** [comment]
ok, I think that's what's currently in the PR #617
