### ISSUE TITLE
Unable to see graphs in k8s dashboard with metric-server

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/dashboard#5611]
Hi,
tried to deploy k8s dashboard with metric-server, but unable to see graph and pod level memory consumption.
##### Environment
Kubernetes is running with 1.16.3 version, deployed dashboard with v2.0.4 and metric-server 1.4.0

```
Installation method: using helm 
Kubernetes version: Kubernetes v1.16.3
Dashboard version: Dashboard v2.0.4+0.g4da3dfcd1
Operating system: ubuntu 16.04.5 server version
Node.js version ('node --version' output):
Go version ('go version' output):
```

**Comment by floreks** [comment]
No logs, no detailed description, no information whatsoever that could help find the cause. Provide more information or we'll have to close.

**Comment by akshaysharama** [comment]
Hi @floreks ,

I've installed metric-server and k8s dashboard pod in kube-system namespace.
In k8s web-UI , could see namespaces, pod and other information, but no information for pod cpu and memory usage and graphs also in workload section.

image for dashboard web UI,
EX:
<img width="801" alt="INFO" src="https://user-images.githubusercontent.com/53307589/95456472-ff67db80-098c-11eb-96d3-bd4b9f89b927.PNG"

Dashboard logs.
{"level":"info","msg":"Kubernetes host: https://10.233.0.1:443","time":"2020-10-08T11:44:44Z"}
xx.xx.xx.xx - - [08/Oct/2020:11:45:15 +0000] "GET /healthz HTTP/1.1" 200 13 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:45:23 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
xx.xx.xx.xx - - [08/Oct/2020:11:45:33 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
xx.xx.xx.xx - - [08/Oct/2020:11:45:43 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
{"level":"error","msg":"Error scraping node metrics: the server could not find the requested resource (get nodes.metrics.k8s.io)","time":"2020-10-08T11:45:44Z"}
xx,xx,xx,xx - - [08/Oct/2020:11:45:45 +0000] "GET /healthz HTTP/1.1" 200 13 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:45:53 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
xx.xx.xx.xx - - [08/Oct/2020:11:46:03 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
xx.xx.xx.xx - - [08/Oct/2020:11:46:13 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.16"
xx.xx.xx.xx - - [08/Oct/2020:11:46:15 +0000] "GET /healthz HTTP/1.1" 200 13 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:46:17 +0000] "GET /api/v1/dashboard/namespaces/default/pod-list/rms-node-exporter-l2v4b/metrics/cpu/usage_rate HTTP/1.1" 200 14 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:46:17 +0000] "GET /api/v1/dashboard/nodes/demo/metrics/cpu/usage_rate HTTP/1.1" 200 14 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:46:17 +0000] "GET /api/v1/dashboard/namespaces/default/pod-list/rms-node-exporter-l2v4b/metrics/memory/usage HTTP/1.1" 200 14 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:46:17 +0000] "GET /api/v1/dashboard/namespaces/default/pod-list/alertmanager-rms-kube-prometheus-alertmanager-0,prometheus-rms-kube-prometheus-prometheus-0,jms-server-0,db-0,kafka-0,zoo-keeper-0/metrics/cpu/usage_rate HTTP/1.1" 200 14 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:46:17 +0000] "GET /api/v1/dashboard/namespaces/default/pod-list/rms-prometheus-pushgateway-77fb7db694-df8l4,rms-kube-prometheus-operator-589765767f-8wh48,rms-kube-state-metrics-68498cf8bd-cvgv5,oad-service-deployment-569945b4f7-867x8,me-manager-5c447958cc-b6r2z,data-manager-6fc6688db4-6227k,database-manager-fb4d76649-z6zf2,soap-service-755df98bc8-4sndt,node-765f8dfbdf-8fs2b,fault-manager-cd88b8875-rb27n,event-manager-6b95bdd7c7-8dq7n,mail-manager-79cc944984-88m8f,task-manager-5d4d746cf4-nw7fh,op-manager-668c7564cc-qdwmv,op-service-manager-86dccbcd85-cgx24,op-adaptor-manager-6b97cb88fb-zw696,report-manager-85fd6f88bf-mbz7g,op-processor-deployment-77f8d47f8d-kzbbl,op-manager-7cbccddbdf-tb55k,op-collector-76fd8cfd6f-q24tb,schedule-manager-7f4cc7b47d-m4mbh,zconsumer-7fd9b55b6f-v964j,y-service-5bf846fcc9-trw5j,web-app-7f64d98d6-7x5q8,z-manager-7ccf4b8854-b4ksj/metrics/cpu/usage_rate HTTP/1.1" 200 14 "" "dashboard/v2.0.4"
xx.xx.xx.xx - - [08/Oct/2020:11:46:17 +0000] "GET /api/v1/dashboard/nodes/demo/metrics/memory/usage HTTP/1.1" 200 14 "" "dashboard/v2.0.4"

**Comment by floreks** [comment]
This is the log from the middle. It should show the start of the application. You shouldn't install it in `kube-system` namespace. We have moved it to a dedicated namespace to improve security.

**Comment by akshaysharama** [comment]
[dashboard.txt](https://github.com/kubernetes/dashboard/files/5347805/dashboard.txt)
I've tried with dedicated namespace for dashboard and metric server, still couldn't see any graphs or cpu or memory info.

Can we see historical data also in k8s dashboard??

**Comment by floreks** [comment]
`metrics-server` can be installed anywhere, usually in `kube-system` namespace.

Kubernetes Dashboard and `dashboard-metrics-scraper` should be installed together in `kubernetes-dashboard` namespace.

It look like you haven't enabled metrics scraper in the helm chart when installing it: https://github.com/kubernetes/dashboard/blob/master/aio/deploy/helm-chart/kubernetes-dashboard/values.yaml#L200

/close
