### ISSUE TITLE
Can it run in window10? 系统找不到指定的路径。

### ISSUE THREAD

**Issue by ying2025** [kubernetes/dashboard#5617]
D:\gospace\src\k8s.io\dashboard>npm i

> kubernetes-dashboard@2.0.4 postinstall D:\gospace\src\k8s.io\dashboard
> node aio/scripts/version.js && command -v golangci-lint >/dev/null 2>&1 || { curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/maste
r/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0; } && go mod download && ./aio/scripts/install-codegen.sh && ngcc

Version v2.0.4-39-g9306c63e0-dirty saved to ..\src\app\frontend\environments\version.ts
系统找不到指定的路径。
'{' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! kubernetes-dashboard@2.0.4 postinstall: `node aio/scripts/version.js && command -v golangci-lint >/dev/null 2>&1 || { curl -sSfL https://raw.gi
thubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0; } && go mod download && ./aio/scripts/install-c
odegen.sh && ngcc`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the kubernetes-dashboard@2.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by floreks** [comment]
It won't work on windows. Our dev environment is only prepared to work on Linux.

/close
