### ISSUE TITLE
Accessing kubernetes dashboard gives Error trying to reach service: 'dial tcp 10.44.0.2:8443: connect: connection refused'

### ISSUE THREAD

**Issue by godomainz** [kubernetes/dashboard#5620]
I used kubernetes hard way and managed to deploy a cluster successfully with kubernetes 1.18.6

I used vmware and kubernetes 1.18.6. I deployed metric-server and kubernets dashboard

I used this command --> kubectl proxy --address='0.0.0.0' --port=8001 --accept-hosts='^*$' to startup kuberenetes dashboard

Then I used below url to access kubernes dashboard from my master node

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

But I'm getting below error in my browser

Error trying to reach service: 'dial tcp 10.44.0.2:8443: connect: connection refused'
But I can access kubernetes dashboard without any issue on my worker nodes using the url https://10.44.0.2:8443/

What am I missing ?

Why I can't access kubernetes dashboard normal way ?

I created another cluster with kubeadm tool and I can access kubernetes dashboard outside of the cluster.

I have weave and coredns configured and I don't see any errors on them.

**Comment by floreks** [comment]
This has nothing to do with Kubernetes Dashboard. You can't even reach it through this URL, this means that this is a cluster configuration issue. Most likely a networking issue. This is just another app running inside your cluster. How you choose to access it is up to you. It could just as well be some simple hello world web app.

/close

**Comment by godomainz** [comment]
@floreks do you have any idea what should I be looking to fix this ?

**Comment by floreks** [comment]
Which documentation? Dashboard installation requires your cluster to be fully healthy and have a working in-cluster networking. This part is not working properly for you. This is a cluster issue then, not Dashboard. We do not provide support for Kubernetes, only Kubernetes Dashboard. Bare metal installations are much harder than using i.e. a kubeadm. It's up to you now to make sure everything is working as it should.
