### ISSUE TITLE
Why it always requests the backend and it's request frequency is very high?

### ISSUE THREAD

**Issue by ying2025** [kubernetes/dashboard#5622]
Why it always requests the backend?
![图片](https://user-images.githubusercontent.com/28092539/95729221-2553ef80-0caf-11eb-9400-153b205cdb4d.png)
![图片](https://user-images.githubusercontent.com/28092539/95729523-98f5fc80-0caf-11eb-9edf-effd55e03222.png)

**Comment by floreks** [comment]
Go to Settings and change refresh time if you want
![Zrzut ekranu z 2020-10-12 11-23-51](https://user-images.githubusercontent.com/2285385/95729696-82cf4880-0c7d-11eb-832a-dbf88f438348.png)

/close

**Comment by ying2025** [comment]
But when I logout,  it still request the backend and get the namespaces.

**Comment by floreks** [comment]
There is 1 additional request that fails because you are logged out and then it stops.
![Zrzut ekranu z 2020-10-12 11-37-31](https://user-images.githubusercontent.com/2285385/95731114-646a4c80-0c7f-11eb-97fa-321daa6f992a.png)

**Comment by ying2025** [comment]
I got the data in "namespace request" when I logout.
![图片](https://user-images.githubusercontent.com/28092539/95734811-8501c900-0cb6-11eb-93c9-1daf9c2924b3.png)

**Comment by floreks** [comment]
Not sure how you installed everything, and if logout works for you. Cookies should be deleted after logout. If the request is successful then it means that the cookie has not been deleted and the token is still available. This is only a very minor bug. We can enforce subscription cancellation with logout. The code is open-sourced so you can investigate what happens there.

**Comment by ying2025** [comment]
I git clone this project, and then run  'sudo "PATH=$PATH" npm start ' , after it compile the project, I login in. After I logout, the cookie is empty, but it still can request namespace directly.

**Comment by floreks** [comment]
`npm start` does not use login/logout mechanism. It uses your `kubeconfig` file only. Use `npm run start:https` if you want to enable https and log infeature.

**Comment by ying2025** [comment]
It doesn't seems a lot of difference with npm start expect https

**Comment by ying2025** [comment]
Another question, Why it compiles so slow?
