### ISSUE TITLE
Add lint rule to better manage subscription cancellation

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#5623]
In example namespace list request still happens after the user logs out due to wrongly used `takeUntil` pipe. We should add lint rules to check such things and also check if subscriptions are properly destroyed overall on changing views.

`src/app/frontend/common/components/namespace/component.ts`
```typescript
this.namespaceUpdate_
      .pipe(takeUntil(this.unsubscribe_))
      .pipe(startWith({}))
      .pipe(switchMap(() => this.namespace_.get(this.endpoint_.list())))
      .subscribe(...);
```

**Comment by romdhanisam** [comment]
Related subject, [Avoid takeUntil subscription leaks (no-unsafe-takeuntil)](https://github.com/cartant/eslint-plugin-rxjs/blob/main/docs/rules/no-unsafe-takeuntil.md#avoid-takeuntil-subscription-leaks-no-unsafe-takeuntil)
