### ISSUE TITLE
How to persist k8s dashboard data??

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/dashboard#5624]
Hi,

I'm running k8s dashboard and metric-scraper as a container in single pod, metric-server as a separate pod.
I want to persist the data showing in dashboard, if in case dashboard service restarts.

Is there any way we can achieve that?

**Comment by floreks** [comment]
metrics-scraper is reponsible for providing storing metrics data gathered from metrics-server. By default it creates DB file in /tmp dir IIRC. You can mount a persistent storage under this path and if it picks it up after restart it will use it. Check scraper repo for more information.

/close
