### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by eddie-fangv** [kubernetes/dashboard#5625]
##### Environment

```
Installation method:
Kubernetes version: v1.19.0
Dashboard version: v2.0.4
Operating system: centos
Node.js version ('node --version' output): v12.19.0
Go version ('go version' output):
```

##### Observed result

![image](https://user-images.githubusercontent.com/34231359/95846633-40d9fb80-0d7e-11eb-9abd-b3d23a77438b.png)

##### Expected result

all be chinese
##### Comments

i have edit deployment.yml 
like this  
![image](https://user-images.githubusercontent.com/34231359/95846898-9c0bee00-0d7e-11eb-8620-630bc078042a.png)
and tried <value: zh/zh-CN>  didn't work

**Comment by floreks** [comment]
Language is based on your browser locale and presented `Accept-Language` request header. Recognized codes are defined [here](https://github.com/kubernetes/dashboard/blob/master/angular.json#L16). `ACCEPT_LANGUAGE` env var should override it. You can also try clearing the cache and removing all cookies. If only some strings are localized then it might be our localization that needs an update. There were some major changes and some of the localization might have been lost.

**Comment by hwdef** [comment]
in #4705,  translator decided that some words would not be translated, such as `pod` and `service`, If you have other suggestions, please discuss with us.

But your browser is indeed incorrect, please try to clear the cache. I will also try to reproduce this problem.

@floreks  I will check for missing translated strings. The translation will be updated in a day or two.

**Comment by shu-mutou** [comment]
At first, please see https://github.com/kubernetes/dashboard/blob/master/docs/developer/internationalization.md in detail. We don't support `zh` and `zh-CN` as a result of long discussions. You can use `zh-Hans`, `zh-Hant` or `zh-Hant-HK` for Chinese.
Each translation underneeth  in `i18n` directory has `OWNERS` who are responsible in its translation. Please ask them for each translation.

**Comment by EvansFW** [comment]
my chrome version :85.0.4183.121（release） （64 位）

**And my language settings like this:
**move Chinese to the top****

![image](https://user-images.githubusercontent.com/34231359/95932014-376e8480-0dba-11eb-84f1-4ce755b81550.png)

**And this is requst headers:**

![image](https://user-images.githubusercontent.com/34231359/95932103-76043f00-0dba-11eb-88a2-49281ee961a7.png)

**I have deleted cache & cookies , remove the env arg from the deployment.yaml, restart pod. but it didn't work**

the result is : 
![image](https://user-images.githubusercontent.com/34231359/95932418-57eb0e80-0dbb-11eb-89d2-9f733f359610.png)

**and i see dashborad v1.10.0 ,  most words have been translated**

![image](https://user-images.githubusercontent.com/34231359/95932681-08591280-0dbc-11eb-9d8b-a12999e892ec.png)

**Comment by shu-mutou** [comment]
Also, each language team has each policy about whether k8s object name should be translated or not. So this issue relates Chinese traslation team.

But un-translated words are increased now.
@headcr4sh @kgroschoff @mkorbi @feloy @gochist @seokhoson @chenrui333 @zehuaiWANG @hwdef @tanjunchen Please update your translations. Thanks!

**Comment by hwdef** [comment]
@EvansFW 
Thanks for you replay ,I reproduced the problem, it's not a bug, it's due to a missing translation.
I will update these translation.

But honestly, it wouldn't change much. Proper nouns will not be translated.

**Comment by zehuaiWANG** [comment]
@EvansFW According to issue #4705 , the word such like 'namespace', 'node' will no be translated.

**Comment by headcr4sh** [comment]
The German translation (DE) has been updated in [PR #5672](https://github.com/kubernetes/dashboard/pull/5672).
All technical Kubernetes-specific terms should now be in English without a translation.

`/remove-language de`

**Comment by shu-mutou** [comment]
/close
If we need translation work for a new release, creates a new issue and manages it there.
