### ISSUE TITLE
kubernetes dashboard not showing options to sign in

### ISSUE THREAD

**Issue by chatwithruben** [kubernetes/dashboard#5627]
Hi All,

I am trying to bring up kubernetes dashboard which is namespace specific as we dont have permission to touch cluster role and cluster role binding. 

I have brought up the container and i was able to open the dashboard ui using the ingress url. 

But here one thing i noticed is that i am not able to see the login button or profile at the right side top. I was not getting any dialog box for providing the tokens as well.  

since i am not getting these these options to authenticate, none of details of my namespace is being listed in dashboard. 

Can someone please help/suggest.

<img width="1722" alt="Screenshot 2020-10-13 at 8 26 59 PM" src="https://user-images.githubusercontent.com/30433460/95878092-7557b280-0d92-11eb-9566-a5f458e28d9a.png">

Thanks,
Ruben

**Comment by floreks** [comment]
It must be configured with auth disabled and it is also some old version based on the ss. No information about the environment, versions, deployment type.

/close
