### ISSUE TITLE
no endpoints available for service

### ISSUE THREAD

**Issue by Gauravjaitly** [kubernetes/dashboard#5628]
created the k8s eks dashboard with terraform:
https://learn.hashicorp.com/tutorials/terraform/eks

also set permissions for admin with:
https://computingforgeeks.com/create-admin-user-to-access-kubernetes-dashboard/

added users to my aws-auth-cm.yaml and after adding users got the following error on my dashboard page

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

cant access my dashboard on http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login

**Comment by floreks** [comment]
Already discussed in closed issues like 100 times.

/close
