### ISSUE TITLE
self bearer token specified for login 

### ISSUE THREAD

**Issue by yechnlin** [kubernetes/dashboard#5635]
Hi,

#### Description

For now, it can get bearer token as https://github.com/kubernetes/dashboard/tree/master/docs/user/access-control#bearer-token ,  it means that the token managed by kubernetes.

#### Issue

Can user specify a self bearer token?, that means user can use the self token login dashboard, instead of token from ServiceAccount.

**Comment by floreks** [comment]
You can provide any token that API server will accept. It will always depend on how you have configured your cluster. Dashboard is only a proxy here.

/close
