### ISSUE TITLE
Can we use single k8s dashboard(web ui) for multiple k8s deployments or nodes?

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/dashboard#5639]
Hi,

I've deployed k8s dashboard and metric-server on say, NODE A. 
I want to monitor/see other remote machines(NODE B, NODE C) pods also.
Note: NODE (A,B, C) are single node k8s depolyments.
 
can we do that in dashboard?

**Comment by floreks** [comment]
Dashboard monitors a whole cluster that it is installed in. It gives similar output to kubectl. 

/close

**Comment by akshaysharama** [comment]
Hi @floreks ,

My question is not for single cluster , it is for multiple clusters. Basically, can a single k8s cluster dashboard monitor multiple k8s cluster information?

**Comment by floreks** [comment]
No
