### ISSUE TITLE
Run as a cluster-service?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/dashboard#565]
Should this be run as a cluster service?

If the metadata for the RC/Service were annotated with `kubernetes.io/cluster-service: "true"` then it would be treated as a cluster-service, and would appear in the output for `kubectl cluster-info`.

**Comment by bryk** [comment]
Yeah, makes total sense. This is already done for addon configuration [0], but not in the install guide here. Will fix.

[0] https://github.com/kubernetes/kubernetes/blob/fe269474ca0371a9fc1937046d029445898abd44/cluster/addons/dashboard/dashboard-service.yaml
