### ISSUE TITLE
A "Terminating" pod is shown incorrectly in the dashboard as "Waiting: ContainerCreating" 

### ISSUE THREAD

**Issue by nielsbasjes** [kubernetes/dashboard#5656]
##### Environment

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.4/aio/deploy/recommended.yaml
Kubernetes version: v1.19.0
Dashboard version: 2.0.4
Operating system: CentOS Linux release 7.8.2003 (Core)
Node.js version ('node --version' output): ??
Go version ('go version' output): ??
```

##### Steps to reproduce
I have a deployment that runs 3 pods.

Starting the pod takes a few seconds.

In my test I used this as the basis: https://github.com/nielsbasjes/yauaa/blob/master/webapp/yauaa-k8s-example.yaml

I see the effect when I simply do a restart of the deployment with
`kubectl -n yauaa rollout restart deployment yauaa`

##### Observed result
Looking at the pod status the same moment via command line and in the UI:
`kubectl -n yauaa get pods -owide`
Note: I sorted the results to match the ordering in the screenshot.

```
NAME                     READY   STATUS        RESTARTS   AGE     IP               NODE         NOMINATED NODE   READINESS GATES
yauaa-565956f64f-6dmd9   0/1     Running       0          7s      172.30.100.170   node11.xxx   <none>           <none>
yauaa-565956f64f-ftdxr   1/1     Running       0          26s     172.30.3.67      node10.xxx   <none>           <none>
yauaa-565956f64f-4x6r7   1/1     Running       0          46s     172.30.228.216   node12.xxx   <none>           <none>
yauaa-58fc466c4-vdpmr    1/1     Running       0          2m21s   172.30.100.171   node11.xxx   <none>           <none>
yauaa-58fc466c4-thqcj    0/1     Terminating   0          2m38s   <none>           node10.xxx   <none>           <none>
```

Kubernetes Dashboard 2.0.4
![image](https://user-images.githubusercontent.com/240096/96698571-91a8b000-138d-11eb-996c-d69e792653c3.png)

Looking at pod yauaa-58fc466c4-thqcj

The commandline shows it as `Terminating` which is correct.
The dashboard shows it as `Waiting: ContainerCreating` which is incorrect.

##### Expected result
The dashboard shows pod yauaa-58fc466c4-thqcj also as `Terminating`.

##### Comments
No comments.

**Comment by floreks** [comment]
Bookmarking `kubectl` logic as a reference when updating our logic: https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L734
