### ISSUE TITLE
Dashboard pods OOM upon search

### ISSUE THREAD

**Issue by estahn** [kubernetes/dashboard#5658]
##### Environment

```
Installation method: helm
Kubernetes version: v1.16.13
Dashboard version: 2.0.4
Operating system: Debian
```

##### Steps to reproduce

1. type in search term
2. press enter

##### Observed result

Error page followed by service unavailable. Upon checking the pod see OOMKilled.

##### Expected result

Not OOMKilled.

##### Comments

I've set the memory limit to 2Gi now and it appears to be fine. What's the expected resource usage for the dashboard?

**Comment by floreks** [comment]
Resource usage scales with your cluster size. Search checks all resources inside the cluster. For small clusters 2Gi is fine. For big cluster it might require even 8Gi or more. Caching and informers will be used in new API. Bigger clusters also should increase refresh time in settings to decrease a chance of creating overlapping requests.

/close

**Comment by estahn** [comment]
@floreks Thanks for your response.

> Bigger clusters also should increase refresh time in settings

Where is this being configured? We're using the helm chart to install the Kubernetes dashboard.

**Comment by floreks** [comment]
Simply open the settings view when using Dashboard and change it. This is a global config.
