### ISSUE TITLE
Add an ingress UI to create route

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes/dashboard#5659]
##### Ingress UI

Add an ingress UI to create/map routes from K8s services. The current dashboard of kubernetes currently only displays the K8s resources but dont offer UI screens able to simplify the work of the developers and mainly when they have to handle the mapping of a service to expose it outside of the cluster

okd project of openshift proposes such nice UI

![Screenshot 2020-10-22 at 09 11 54](https://user-images.githubusercontent.com/463790/96837508-d93f4280-1446-11eb-87a4-08c100597bb1.png)

##### Why is this needed

To simplify the life of the developers and accelerate K8s ingress adoption

**Comment by exagil** [comment]
@bryk I can pick this up if this is something we'd like to have

**Comment by floreks** [comment]
We're working on the new API v2 right now. I'd rather limit new issues that require old API changes so that we won't have to rewrite more and more features to the new style.

**Comment by floreks** [comment]
I'll actually close this one as we already have #1600 issue that is about adding better support for object creation. I have added a link to this one there as a future reference.

/close
