### ISSUE TITLE
Router register fail !!!!

### ISSUE THREAD

**Issue by ying2025** [kubernetes/dashboard#5667]
I add AddClComponent in addclu folder, then I register it routing, but it jump fail. So  I think the router has probelm, but I donnt not how to do. @floreks 
![图片](https://user-images.githubusercontent.com/28092539/97547293-9530dc80-1a08-11eb-8c77-2b69aa496a48.png)
Image 1
![图片](https://user-images.githubusercontent.com/28092539/97547426-c3aeb780-1a08-11eb-830c-2e88ab37a8c7.png)
Image 2
![图片](https://user-images.githubusercontent.com/28092539/97547568-ea6cee00-1a08-11eb-8aa3-77d623d8a15f.png)
Image 3
![图片](https://user-images.githubusercontent.com/28092539/97547650-02dd0880-1a09-11eb-8fd8-3ce10961f81f.png)
Image 4
![图片](https://user-images.githubusercontent.com/28092539/97547719-1daf7d00-1a09-11eb-9847-696063b2f6ff.png)
Image 5
![图片](https://user-images.githubusercontent.com/28092539/97548453-1c328480-1a0a-11eb-9c55-f9a6033fa900.png)
Image6

**Comment by floreks** [comment]
We do not provide support for angular or custom code changes here. Issues are for official Kubernetes Dashboard release problems. We can only review a working code if you decide to create a PR with some change.

/close

**Comment by ying2025** [comment]
I just try to verify some things, but It always fail, so I add a new component
