### ISSUE TITLE
 parent component calls the correct lifecycle hooks but any of the child components using navigate only the constructor is called

### ISSUE THREAD

**Issue by ying2025** [kubernetes/dashboard#5669]
My parent component calls the correct lifecycle hooks but any of the child components using navigate only the constructor is called. I think polyfills should't import. I want to know how do you solve this problem.
![图片](https://user-images.githubusercontent.com/28092539/97574297-f9ae6480-1a25-11eb-811a-23102ef9aa80.png)

This is my test, the link is [test](https://github.com/kubernetes/dashboard/issues/5667), and the 
[angular problem](https://github.com/angular/angular/issues/8012)

**Comment by floreks** [comment]
Please, stop creating Angular related issues. We do not provide such support here. Everything works as intended on our side. 

/close
