### ISSUE TITLE
[Helm chart] dashboard not working properly on eks

### ISSUE THREAD

**Issue by nparfait** [kubernetes/dashboard#5671]
##### Environment
Installation method: helm chart
Kubernetes version: 1.18
Dashboard version: chart 2.8.2 

When i install using the chart, with metricsScraper enabled no metrics are displayed in the dashboard. It knows how many resources etc, there are. and kubectl top commands work.
![image](https://user-images.githubusercontent.com/12601962/98193180-ab8ee900-1f70-11eb-8d03-ab90628ad7d9.png)

Installing via the yaml files works fine
https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.4/aio/deploy/recommended.yaml

**Comment by dirknilius** [comment]
I just ran into the same. But you just have to enable `metricsScraper.enabled=true` and `metrics-server.enabled=true` because they are `disabled` in this chart by default.

**Comment by floreks** [comment]
@dirknilius that is correct. This is not a bug.

/close

**Comment by nparfait** [comment]
I have  metricsScraper.enabled=true
and i am running metrics-server separately/standalone

kubectl top nodes
and 
kubectl top pods 
work correctly

**Comment by nparfait** [comment]
Experimenting with the chart
https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.5/aio/deploy/recommended.yaml

It appears that if i move the dashboard-scraper to run as a sidecar it causes the info to not display correctly.
This ends up being the only difference between the helm chart and the above yaml

**Comment by nparfait** [comment]
> @dirknilius that is correct. This is not a bug.
> 
> /close

See my above comments. Still having issues when scraper runs as a side car
