### ISSUE TITLE
Need to know how terminal works

### ISSUE THREAD

**Issue by zeromsi** [kubernetes/dashboard#5675]
Can anyone help me with a doc or diagram of how terminal works?

**Comment by floreks** [comment]
We do not have any kind of diagram or docs on how terminal works. You can take a look at the code.

[Frontend](https://github.com/kubernetes/dashboard/tree/master/src/app/frontend/shell)
[Backend](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/terminal.go)
