### ISSUE TITLE
What is ws url of shell? 

### ISSUE THREAD

**Issue by zeromsi** [kubernetes/dashboard#5677]
I'm creating a session by calling api -- > /pod/{namespace}/{pod}/shell/{container}
Now I want to open connection with returned sessionId.
I'm confused ``` http.Handle("/api/sockjs/", handler.CreateAttachHandler("/api/sockjs")) ``` is this the api to open connection. If so then how should I add sessionId with that?

**Comment by floreks** [comment]
You can take a look at the code to figure this out. We are using xterm and websockets.

[Frontend](https://github.com/kubernetes/dashboard/tree/master/src/app/frontend/shell)
[Backend](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/terminal.go)

/close
