### ISSUE TITLE
Helm Chart ingress annotations issue error unmarshaling JSON

### ISSUE THREAD

**Issue by vgokul984** [kubernetes/dashboard#5683]
##### Environment
Installed  kubernetes-dashboard in eks  using the helm3 with default values it works but when we enable the the ingress and add additional ingress.annotations it shows the error unmarshaling JSON

```
Installation method: helm 
Kubernetes version:kubernetes 1.17.
Dashboard version:kubernetes-dashboard-2.8.2.
Operating system:
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard --set 'ingress.annotations.kubernetes.io/ingress.class'="nginx", --set 'ingress.annotations.kubernetes.io/rewrite-target'='/$2', --set "ingress.enabled"="true"

##### Observed result
Error: YAML parse error on kubernetes-dashboard/templates/ingress.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string

##### Expected result
annotation should be added on the ingress .

**Comment by floreks** [comment]
Just by looking at it, I suspect it might be an issue with your helm command. @desaintmartin any ideas?

**Comment by vgokul984** [comment]
Hi Floreks, thanks for looking on the issue. I tried on both the by providing the annotations during the install as per the chart and k8s.

helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard --set=ingress.enabled=true,ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/ingress.class=nginx,ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/rewrite-target="/$2"

**Comment by desaintmartin** [comment]
I highly suggest you using a values.yaml instead of --set in order to avoid such horrors. --set is meant for very simple cases.

Note than in bash, sh or zsh (at least), "$2" will probably be replaced by an empty string. Use '$2'.

**Comment by vgokul984** [comment]
Thanks @desaintmartin  i can able to deploy by adding the annotations in the values.yaml .

Also i used --set for helm chart install it worked today 
[ec2-user@ip-172-31-46-56 terraform-aws-eks]$ helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard --set ingress.enabled=true --set ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/rewrite-target='/$2' --set service.externalPort=8080 --set metrics-server.enabled="true"
NAME: kubernetes-dashboard
LAST DEPLOYED: Fri Nov 13 14:18:23 2020
NAMESPACE: kubernetes-dashboard
STATUS: deployed
REVISION: 1
NOTES:
*********************************************************************************
*** PLEASE BE PATIENT: kubernetes-dashboard may take a few minutes to install ***
*********************************************************************************

Thanks for the help
