### ISSUE TITLE
Can't login using generated token

### ISSUE THREAD

**Issue by zrks** [kubernetes/dashboard#5688]
### Environment
On premise

```
Installation method: kubespray v2.14.1
Kubernetes version: v1.18.9
Dashboard version: v2.0.4
Operating system: CentOS Linux 7 (Core)
Node.js version ('node --version' output): 
Go version ('go version' output):
```
dashboard logs show:
```
2020/11/17 09:24:31 [2020-11-17T09:24:31Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/login request from 10.10.88.20: { contents hidden }
2020/11/17 09:24:31 [2020-11-17T09:24:31Z] Outcoming response to 10.10.88.20 with 200 status code
2020/11/17 09:24:31 [2020-11-17T09:24:31Z] Incoming HTTP/1.1 POST /api/v1/login request from 10.10.88.20: { contents hidden }
2020/11/17 09:24:31 Non-critical error occurred during resource retrieval: the server has asked for the client to provide credentials
2020/11/17 09:24:31 [2020-11-17T09:24:31Z] Outcoming response to 10.10.88.20 with 200 status code
```
api server logs show:
```
E1117 09:40:21.295753       1 authentication.go:53] Unable to authenticate the request due to an error: invalid bearer token
```

##### Steps to reproduce
1. log in to dex using ldap credentials
2. copy generated token
3. log in to dashboard using copied token
##### Observed result

 Unauthorized (401): Invalid credentials provided 
##### Expected result
Log in to dashboard

##### Comments
Token length is 1101, however previously it was 1096, don't know if this is relevant.

**Comment by floreks** [comment]
K8S API server validates the token here, not Dashboard. If it says that the token is invalid then it is being rejected by the API server. This is a configuration issue. The only limitation right now is that the token size cannot exceed 4096 bytes, otherwise it will get truncated. This is however the browser limitation.

/close

**Comment by zrks** [comment]
Just for the record - issue was missing oidc parameters to api-server.

Confusion arised because of exact cluster reinstallation steps and somehow these paras weren't added, weird one...
