### ISSUE TITLE
Chart requirement uses deprecated helm repo

### ISSUE THREAD

**Issue by joejulian** [kubernetes/dashboard#5689]
##### What should be cleaned up or changed
The helm repo has been deprecated for a year and the domain `kuberntes-charts.storage.googleapis.com` will be going away very soon (within weeks). The chart requirement will need to change. The only metrics-server chart that seems to be maintained, still, is the one by bitnami: https://artifacthub.io/packages/helm/bitnami/metrics-server

##### Provide any links for context
https://github.com/kubernetes/dashboard/blob/db5d61502acaad0c19c20f325f4d0fc5429757ec/aio/deploy/helm-chart/kubernetes-dashboard/requirements.yaml#L4

**Comment by joejulian** [comment]
Looks like this will be fixed by https://github.com/kubernetes/dashboard/pull/5666

**Comment by shu-mutou** [comment]
Thank you for your information! 😄
