### ISSUE TITLE
Logs Refresh Button

### ISSUE THREAD

**Issue by andrii29** [kubernetes/dashboard#5707]
##### What would you like to be added
When we check pod logs in k8s dashboard we have next options:
![image](https://user-images.githubusercontent.com/31315876/101501326-461b8700-3978-11eb-9f25-f1ddd840e273.png)
It would be nice to add refresh (logs) now option.

##### Why is this needed
Sometimes it's useful to disable logs auto refresh, but refresh them once when it is needed

**Comment by floreks** [comment]
You can simply click one of the pagination buttons to force refresh the logs. You can also adjust the logs auto-refresh time in settings.

/close
