### ISSUE TITLE
Kubeconfig sign in with file does not work on v2.0.5 

### ISSUE THREAD

**Issue by thanos1983** [kubernetes/dashboard#5709]
##### Environment

```
Installation method: recommended method (kubectl apply -f etc)
Kubernetes version: 1.19.4
Dashboard version: v2.0.5 (latest)
Operating system: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Node.js version ('node --version' output): On the node I am not running Node.js
Go version ('go version' output): go version go1.15.2 linux/amd64
```

##### Steps to reproduce

Deploy cluster with Ingress etc and try to login through kubeconfig button. On the previous version v2.0.4 I was able to login by using my `~/.kube/config` file.

Sample of file:

```bash
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://IP:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: REDACTED
```

##### Observed result

There are no logs on the pod that indicate any errors. I can login perfectly fine with the token (copy / paste) but not with kubeconfig.

##### Expected result

Being able to login to the node just like as with token.

**Comment by floreks** [comment]
Works as designed. Please read the documentation. It is described which kubeconfig configurations are accepted.

/close

**Comment by thanos1983** [comment]
> It should work. I think you should provide only the token without cert config.

It used to work exactly with the same structure of the file on the previous version v2.0.4

I can try to remove the cert config but it want make a difference I assume.

Is there any way that I can debug this? I can not see any logs on the pod. I can only see logs when I am using the token directly and everything seems to be working fine.

**Comment by floreks** [comment]
@maciaszczykm could you test it tomorrow?

**Comment by tomoncle** [comment]
# **I had the same problem.**
## dashboard version
* `v2.0.5` :  `Open browser debugging mode, no response, no error, no log`
* `v2.0.0-rc2` : `success`
## k8s version
* `v1.18.6`
## kubeconfig
```config
current-context: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: kubernetes
current-context: kubernetes
users:
- name: admin
  user:
    token: [token value]
```

**Comment by maciaszczykm** [comment]
I can confirm that it doesn't work on the master. I'll investigate.

**Comment by maciaszczykm** [comment]
I found the bug, I will send the fix soon.
