### ISSUE TITLE
Incorrect sorting some columns in PODS and EVENTS views

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#571]
#### Issue details

Incorrect sorting some columns in PODS and EVENTS views

##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: linux/amd64
Node.js version: v0.10.40
Go version: go1.4.2
```

##### Steps to reproduce
I have correctly replication controler, I go to POD and EVENTS views, and I start sorting

##### Observed result

in POD view:
- Columns which contains the same, or empty values are sorting by name of POD - it is OK?
- Column "Status" also sorting by name of POD, although it contains various values 
![image](https://cloud.githubusercontent.com/assets/18006407/14012655/5ebc7d00-f1a7-11e5-8488-82dc1877152c.png)
![status](https://cloud.githubusercontent.com/assets/18006407/14012681/99a602f6-f1a7-11e5-956c-6a31e6bce40a.png)

in EVENTS view:
- Sorting by column "Source" returns different results every time

##### Expected result
Sorting by columns "Status" and "Source" should return correctly results.

##### Comments
What do you think about sorting by columns which contains the same, or empty values? In this case sorting by name of POD is ok?

**Comment by bryk** [comment]
Yeah, this looks bad.

**Comment by bryk** [comment]
@maciaszczykm You implemented the table. Do you know what might be wrong?

**Comment by maciaszczykm** [comment]
> Columns which contains the same, or empty values are sorting by name of POD - it is OK?

Yes.

> Column "Status" also sorting by name of POD, although it contains various values

There is a bug, someone forgot to update column ID in HTML while updating pod object members name. I'll create pull request for it.

> Sorting by column "Source" returns different results every time.

Results seem to be same all the time in my environment, but order is not correct. I'll investigate it.
