### ISSUE TITLE
authentication-mode=basic cannot login

### ISSUE THREAD

**Issue by autherlj** [kubernetes/dashboard#5711]
As below kubernetes info of v1.19,--basic-auth-file cannot used, instead of --token-auth-file. how can I set args       - args:
        - --authentication-mode= ? I want use account and passwords to login.
_"ACTION REQUIRED: Support for basic authentication via the --basic-auth-file flag has been removed. Users should migrate to --token-auth-file for similar functionality. (#89069, @enj) [SIG API Machinery]"_

kubernetes-dashboard version 2.0.5
kubernetes version 1.19.13

**Comment by shu-mutou** [comment]
If passwords are unique in all users, or you can generate unique token for each user from username and password for basic auth, you can simply use `--token-auth-file` for API server option and login with token.

e.g.) 
Current Static Password File
```
P@ssw0rd,user1,uid1,"group1,group2,group3"
```
Convert to Static Token File that has unique tokens for each user.
```
user:P@ssw0rd,user1,uid1,"group1,group2,group3"
```

If tokens are not unique, token on lower line has priority.

**Comment by autherlj** [comment]
> If passwords are unique in all users, or you can generate unique token for each user from username and password for basic auth, you can simply use `--token-auth-file` for API server option and login with token.
> 
> e.g.)
> Current Static Password File
> 
> ```
> P@ssw0rd,user1,uid1,"group1,group2,group3"
> ```
> 
> Convert to Static Token File that has unique tokens for each user.
> 
> ```
> user:P@ssw0rd,user1,uid1,"group1,group2,group3"
> ```
> 
> If tokens are not unique, token on lower line has priority.

**Comment by autherlj** [comment]
> If passwords are unique in all users, or you can generate unique token for each user from username and password for basic auth, you can simply use `--token-auth-file` for API server option and login with token.
> 
> e.g.)
> Current Static Password File
> 
> ```
> P@ssw0rd,user1,uid1,"group1,group2,group3"
> ```
> 
> Convert to Static Token File that has unique tokens for each user.
> 
> ```
> user:P@ssw0rd,user1,uid1,"group1,group2,group3"
> ```
> 
> If tokens are not unique, token on lower line has priority.

so only used token to login for v2.1.0 futher? cannot used password and accnout?

**Comment by shu-mutou** [comment]
Yes, we can use token only. So we need to devise how to create token, I think.
e.g.) Create a token by combining the username and password.
