### ISSUE TITLE
What do the different shades of green mean?

### ISSUE THREAD

**Issue by va3093** [kubernetes/dashboard#5720]
<img width="244" alt="Screenshot 2020-12-12 at 21 14 20" src="https://user-images.githubusercontent.com/8058892/101995052-1396c480-3cbf-11eb-99b2-bf1352a28eeb.png">

Sometimes my pods and jobs have a pie chart with different shades of green. Can someone explain what these different shades mean?

**Comment by floreks** [comment]
Hover over it. It will show a tooltip.

It's Completed/Running.

/close
