### ISSUE TITLE
pod detail info，Container don't have container state.

### ISSUE THREAD

**Issue by twilight327426371** [kubernetes/dashboard#5728]
##### Environment

```
Installation method:  tencent tke
Kubernetes version:  1.16
Dashboard version:  v2.0.0
Operating system:  centos 7.4
Node.js version ('node --version' output):
Go version ('go version' output): 1.14
```

##### Steps to reproduce

pod detail struct , Container struct not have container state. 

##### Expected result

pod detail struct , Container struct  with container state.

**Comment by twilight327426371** [comment]
// Container represents a docker/rkt/etc. container that lives in a pod.
type Container struct {
	// Name of the container.
	Name string `json:"name"`

	// Image URI of the container.
	Image string `json:"image"`

	// List of environment variables.
	Env []EnvVar `json:"env"`

	// Commands of the container
	Commands []string `json:"commands"`

	// Command arguments
	Args []string `json:"args"`
}

**Comment by floreks** [comment]
Fixed in https://github.com/kubernetes/dashboard/pull/5975

/close
