### ISSUE TITLE
Differences between displaying "Age" in the Dashboard and in a console

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#573]
#### Issue details
Differences between displaying "Age" in the Dashboard and in a console.
In web application are empty values in column "Age" when POD has status "Pending", but in console in the same situation "Age" is normally displaying

##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: linux/amd64
Node.js version: v0.10.40
Go version: go1.4.2
```

##### Steps to reproduce
I have correctly Replication controller and i go to PODS view. Next I type the command "kubectl get pods --all-namespaces" into console.

##### Observed result
In console "Age" is displaying for all of PODS, but in Dashboard only if status is "Running", for "Pending" column "Age" has empty values.
![noage](https://cloud.githubusercontent.com/assets/18006407/14014919/e4bb3fd2-f1b5-11e5-8836-99dff3c836e7.png)

##### Expected result
Views in Dashboard and in consol should be the same.

**Comment by bryk** [comment]
Hmm... Interesting. Marcin, take a look and triage this bug.

**Comment by maciaszczykm** [comment]
`-` character is shown when `pod.startTime` is not provided to front-end. In back-end we take this value from Kubernetes API:

``` go
StartTime:    pod.Status.StartTime,
```

Where it's described as:

``` go
// Date and time at which the object was acknowledged by the Kubelet.
// This is before the Kubelet pulled the container image(s) for the pod.
StartTime *unversioned.Time `json:"startTime,omitempty"`
```

It works in most of the cases, but when we are testing it on replication controllers with bigger number of pods it doesn't return any value for some of them (usually ones, that are in pending status and won't be started soon).

I'd say we need to investigate how `kubectl` works and follow their way of getting pods age to make it work. Moreover, I'm still not sure why it doesn't work at the moment...

**Comment by maciaszczykm** [comment]
Result of `log.Print(pod.Status.StartTime);` in the back-end:

```
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 <nil>
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 <nil>
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 <nil>
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 <nil>
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 <nil>
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
2016/03/29 14:12:53 2016-03-29 14:00:10 +0200 CEST
```

So it's not entirely our fault. `kubectl` should be an answer to this issue.

**Comment by maciaszczykm** [comment]
Okay, it seems, that I've solution for this issue. We've to use `pod.CreationTimestamp` instead of `pod.Status.StartTime` to always get pod start time:

``` go
// CreationTimestamp is a timestamp representing the server time when this object was
// created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
CreationTimestamp unversioned.Time `json:"creationTimestamp,omitempty"`
```

I'll create pull request soon :)
