### ISSUE TITLE
Persistent token in client browser

### ISSUE THREAD

**Issue by kfirfer** [kubernetes/dashboard#5743]
##### What would you like to be added

Optionally config property to persist the token while login into the client browser storage

##### Why is this needed

Any cluster that does not have SSO mechanism 
After revisit, he would not necessery retype the token manually

**Comment by floreks** [comment]
The token is already persisted. It's expiration time is set to 15m, so it feels like it is removed after closing the browser. It only expires and logs you out automatically. Check dashboard arguments in documentation to extend it.

/close

**Comment by kfirfer** [comment]
When I close the browser immediately and reopen somehow he asks me for the token
I cant see the token when I inspect 

![Selection_019](https://user-images.githubusercontent.com/7741545/103606093-4e86c380-4f1e-11eb-8a4a-fdce7e866054.jpg)

**Comment by kfirfer** [comment]
@floreks 
What do you think ?

**Comment by floreks** [comment]
We intentionally do not want to persist sensitive data inside the local storage as it is not considered safe. You can update your browser settings to keep some of the cookies for some pages and not delete all of them after every restart. This is normal for basically every web page that when you clear your cookies you will have to log in again.

**Comment by kfirfer** [comment]
@floreks 
You right, its less safe, but in my situation I dont mind to keep them in local storage ,
Mabye making a command argument flag when deploying the dashboard ? and by default its disabled ? and if someone want it he could enable it 
What do you think ?

**Comment by floreks** [comment]
We don't really want to promote unsafe methods of storing sensitive data. It could be considered a security vulnerability by the Kubernetes security team. We are following best practices here and don't want to knowingly compromise security in any way simply to improve usability a bit. 

The solution here is to update browser settings and do not allow deletion of `jweToken` cookie for Dashboard. I don't see any downside here and it is a much simpler solution.
