### ISSUE TITLE
Custom password for kubernetes dashboard when using eks

### ISSUE THREAD

**Issue by Tanya2212** [kubernetes/dashboard#5744]
Is it possible to configure a custom password for the Kubernetes dashboard when using eks without customizing "kube-apiserver"
This URL mentions changes in "kube-apiserver"
 https://techexpert.tips/kubernetes/kubernetes-dashboard-user-authentication/

**Comment by floreks** [comment]
It's not possible. Kubernetes Dashboard does not have its own auth. We fully rely on kubernetes and its' API server.

/close
