### ISSUE TITLE
Replace status indicator with colored dots instead of using icons

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#5750]
<img width="138" alt="Zrzut ekranu 2021-01-8 o 11 59 04" src="https://user-images.githubusercontent.com/2823399/104007871-eb5c9180-51a8-11eb-8c48-98169c6368dc.png">
<img width="176" alt="Zrzut ekranu 2021-01-8 o 11 58 56" src="https://user-images.githubusercontent.com/2823399/104007872-ebf52800-51a8-11eb-9585-62668496eebb.png">

**Comment by therc** [comment]
Are the dots meant to show the status of each container in the pod?

**Comment by maciaszczykm** [comment]
I don't think so. This is just a cosmetical change.

**Comment by therc** [comment]
Bummer, I was hoping it would be a fix for this: https://github.com/kubernetes/dashboard/pull/5660#issuecomment-741749028

**Comment by therc** [comment]
Since the status indicators are changing anyway... one way to address both would be to have as many dots as there are containers. As the pod goes into Running state, the dots are green if ready and pale green if not.

**Comment by maciaszczykm** [comment]
@therc You can report the new issue for that, but it seems like it may be hard to design how the dots would be displayed.

**Comment by floreks** [comment]
> one way to address both would be to have as many dots as there are containers.

It would very quickly clutter the UI and become unreadable for pods with multiple containers. The solution should work well for all scenarios.
