### ISSUE TITLE
Cannot reconnect after token expiration

### ISSUE THREAD

**Issue by Pyrrha** [kubernetes/dashboard#5769]
##### Environment

```
Installation method: documentation
Kubernetes version: 1.20.2
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.1.0
Operating system: Debian
Browser: Safari 14.0.2
```

##### Steps to reproduce

1. Connect to dashboard (using token) through `kubectl proxy`
2. Wait until being disconnected
3. Try to connect again using token

##### Observed result

The message is still

```
Unauthorized (401): You have been logged out because your token has expired.
```

But there's no change when clicking on `Sign In` button. Like if the interface froze. We need to actualise the page to login again.

##### Expected result

No problem during re-connection 😃 

##### Comments

Logs indicates that they received some kind of call...

```
2021/01/22 18:49:38 [2021-01-22T18:49:38Z] Incoming HTTP/2.0 GET /api/v1/plugin/config request from 127.0.0.1: 
2021/01/22 18:49:38 [2021-01-22T18:49:38Z] Outcoming response to 127.0.0.1 with 200 status code
```

 Thanks.

**Comment by floreks** [comment]
Tested 3 different scenarios on the latest version (v2.1.0):
- prod build started locally
- accessed it using kubectl proxy
- accessed it over the reverse proxy

All those scenarios worked correctly. After being automatically logged out I simply put the token and clicked `Login`. I was correctly logged in and redirected to the overview. Unless you can provide actual steps to reproduce I don't see anything that needs fixing.

**Comment by Pyrrha** [comment]
Maybe it's a mismatch with browser compatibility?
I encountered this issue on Safari 14.0.2.

**Comment by floreks** [comment]
@maciaszczykm could you test it on Safari to confirm?

**Comment by maciaszczykm** [comment]
I'll try to do it on Thursday.

/assign

**Comment by maciaszczykm** [comment]
I've tested it with `DASHBOARD_ARGS="tokenTTL=5" npm run start:https` locally both on Chrome and on Safari. For me it works in both scenarios. I'm using Chrome 88.0.4324.96 and Safari 14.0.2 on Big Sur 11.1.

**Comment by floreks** [comment]
Since we couldn't reproduce that on multiple browsers I will close this one. Unless this can be reproduced there is nothing we can do.

/close
