### ISSUE TITLE
Minikube tunnel command issue in windows 10

### ISSUE THREAD

**Issue by thirdpartyusage** [kubernetes/dashboard#5772]
minikube start -p test
* [test] minikube v1.17.0 on Microsoft Windows 10 Enterprise 10.0.19041 Build 19041
* Using the docker driver based on user configuration
* Starting control plane node test in cluster test
* Creating docker container (CPUs=2, Memory=8100MB) ...
* Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "test" cluster and "default" namespace by default

**Then** 

minikube tunnel --profile='test' --alsologtostderr --v=2
I0126 13:48:19.951269   17256 out.go:229] Setting OutFile to fd 88 ...
I0126 13:48:19.955224   17256 out.go:276] TERM=,COLORTERM=, which probably does not support color
I0126 13:48:19.955224   17256 out.go:242] Setting ErrFile to fd 92...
I0126 13:48:19.955224   17256 out.go:276] TERM=,COLORTERM=, which probably does not support color
I0126 13:48:19.976229   17256 mustload.go:66] Loading cluster: test
I0126 13:48:20.009229   17256 cli_runner.go:111] Run: docker container inspect test --format={{.State.Status}}
I0126 13:48:20.531365   17256 host.go:66] Checking if "test" exists ...
I0126 13:48:20.538387   17256 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" test
I0126 13:48:21.010962   17256 api_server.go:146] Checking apiserver status ...
I0126 13:48:21.028960   17256 ssh_runner.go:149] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0126 13:48:21.035959   17256 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" test
I0126 13:48:21.503667   17256 sshutil.go:48] new ssh client: &{IP:127.0.0.1 Port:49212 SSHKeyPath:C:\Users\muthirulandie\.minikube\machines\test\id_rsa Username:docker}
I0126 13:48:21.680774   17256 ssh_runner.go:149] Run: sudo egrep ^[0-9]+:freezer: /proc/2030/cgroup
I0126 13:48:21.704782   17256 api_server.go:162] apiserver freezer: "7:freezer:/docker/0dec78edc03e209a629cbcbfef2a9b936402d957e20b0aba6e5f2327c14d426d/kubepods/burstable/pod55c89bcbdeb83c8e170424682dd9a951/1bb7d538a165b064917135ab9b4cc02a6984374f5cab1f04a6402ceea4eb0a98"
I0126 13:48:21.738417   17256 ssh_runner.go:149] Run: sudo cat /sys/fs/cgroup/freezer/docker/0dec78edc03e209a629cbcbfef2a9b936402d957e20b0aba6e5f2327c14d426d/kubepods/burstable/pod55c89bcbdeb83c8e170424682dd9a951/1bb7d538a165b064917135ab9b4cc02a6984374f5cab1f04a6402ceea4eb0a98/freezer.state
I0126 13:48:21.760466   17256 api_server.go:184] freezer state: "THAWED"
I0126 13:48:21.760466   17256 api_server.go:221] Checking apiserver healthz at https://127.0.0.1:49209/healthz ...
I0126 13:48:21.784511   17256 api_server.go:241] https://127.0.0.1:49209/healthz returned 200:
ok
I0126 13:48:21.784511   17256 tunnel.go:57] Checking for tunnels to cleanup...
I0126 13:48:21.791509   17256 kapi.go:59] client config for test: &rest.Config{Host:"https://127.0.0.1:49209", APIPath:"", ContentConfig:rest.ContentConfig{AcceptContentTypes:"", ContentType:"", GroupVersion:(*schema.GroupVersion)(nil), NegotiatedSerializer:runtime.NegotiatedSerializer(nil)}, Username:"", Password:"", BearerToken:"", BearerTokenFile:"", Impersonate:rest.ImpersonationConfig{UserName:"", Groups:[]string(nil), Extra:map[string][]string(nil)}, AuthProvider:<nil>, AuthConfigPersister:rest.AuthProviderConfigPersister(nil), ExecProvider:<nil>, TLSClientConfig:rest.sanitizedTLSClientConfig{Insecure:false, ServerName:"", CertFile:"C:\\Users\\muthirulandie\\.minikube\\profiles\\test\\client.crt", KeyFile:"C:\\Users\\muthirulandie\\.minikube\\profiles\\test\\client.key", CAFile:"C:\\Users\\muthirulandie\\.minikube\\ca.crt", CertData:[]uint8(nil), KeyData:[]uint8(nil), CAData:[]uint8(nil), NextProtos:[]string(nil)}, UserAgent:"", DisableCompression:false, Transport:http.RoundTripper(nil), WrapTransport:(transport.WrapperFunc)(0x146f4e0), QPS:0, Burst:0, RateLimiter:flowcontrol.RateLimiter(nil), Timeout:0, Dial:(func(context.Context, string, string) (net.Conn, error))(nil)}
I0126 13:48:21.856436   17256 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" test

**Tunnel not working. I updated the latest openssh also. **

ssh -V
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

https://github.com/PowerShell/Win32-OpenSSH/issues/1693

https://github.com/kubernetes/minikube/pull/9753

Referred above two tickets, but still no luck .

Please let me know what i need to add? 

@medyagh

**Comment by maciaszczykm** [comment]
This is the wrong repo.
