### ISSUE TITLE
Custom path in ingress not working and giving "404 page not found" error 

### ISSUE THREAD

**Issue by PerfDOPS** [kubernetes/dashboard#5776]
Hi All,

I have an issue with the custom path on k8s dashboard ingress and when any custom path (/k8s) is being used by ingress, kubernetes dashboard won't work. it only work with "/*" path

apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: cert
      alb.ingress.kubernetes.io/group.name: example
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/subnets: subnet-1, subnet-2
      external-dns.alpha.kubernetes.io/hostname: www.example.com
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: kubernetes-dashboard
            servicePort: 80
          path: /k8s

when I try to access www.example.com/k8s to access to dashboard i get "404 page not found" error. The only way that I can access to dashboard is to use "/*" path.
The configuration of the ALB in AWS looks right and it forward the /k8s traffic to the right target group
Any idea , how can i use a custom path with dashboard ?

**Comment by floreks** [comment]
Probably a configuration issue. It has been fixed quite some time ago and it is possible to use Dashboard on a sub-paths.

Related PR: https://github.com/kubernetes/dashboard/pull/5022
Issue with example config: https://github.com/kubernetes/dashboard/issues/5017

**Comment by floreks** [comment]
With proper configuration it is possible. You can try asking on a `sig-ui` slack channel. There might be some people using similar configurations willing to share their configs. I have only tested it locally with nginx, but don't have the config files anymore.

/close
