### ISSUE TITLE
Dev Issue: One needs 29 GB of RAM to run npm run fix:frontend:ts

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#5781]
##### What should be cleaned up or changed
Unless one has 29 GB of RAM on Linux, 
`npm run fix:frontend:ts`  AKA `./node_modules/.bin/gts` fails because it uses too much memory.

That, keeping in mind I remembered to set NODE_OPTIONS="--max-old-space-size=100000". Else it fails all the time.

**Comment by floreks** [comment]
8GB is enough. I have it set this way for a long time and don't have any issues. You do not need to set such a big number.
`export NODE_OPTIONS="--max-old-space-size=8192"`

/close

**Comment by marcosdiez** [comment]
That does not work over here.

`npm run fix:frontend:ts` needs about 28 GB RAM to work here.
I used `npm ci` to make sure I have all the right libraries.
What version of nodejs do you use ? I have `v14.15.4` here.
on Ubuntu 20.04

**Comment by marcosdiez** [comment]
![image](https://user-images.githubusercontent.com/297498/106343328-87972700-6283-11eb-8b6b-99d6452df404.png)

**Comment by shu-mutou** [comment]
You can use clean development environment with docker, see https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md#easy-way-to-build-your-development-environment-with-docker

**Comment by floreks** [comment]
I have tried it with multiple different `max-old-space-size` limits and could never make node use more than 4% of my RAM (32GB total). I am using `npm: 6.14.11` and `node v14.11.0`.

**Comment by marcosdiez** [comment]
Just for the record, the container trick did not work over here. I still get out of memory. But it seems I am the only one affected by this, so I can just find a workaround...

**Comment by maciaszczykm** [comment]
```
~ ➜ echo $NODE_OPTIONS
--max-old-space-size=8192

~ ➜ npm --version    
6.14.8

~ ➜ node --version
v14.11.0
```

Im using Mac, but this works for me too.
