### ISSUE TITLE
404 error /api/v1/serviceaccount/default/dashboard 

### ISSUE THREAD

**Issue by helight** [kubernetes/dashboard#5793]
![image](https://user-images.githubusercontent.com/433500/107168673-ed5b7f80-69f6-11eb-9c13-5700cc40c98c.png)
![image](https://user-images.githubusercontent.com/433500/107168727-11b75c00-69f7-11eb-80bb-16e97be58662.png)
2021/02/08 10:16:35 [2021-02-08T10:16:35+08:00] Incoming HTTP/2.0 GET /api/v1/serviceaccount/default/dashboard request from 10.99.16.41:45715: 
2021/02/08 10:16:35 [2021-02-08T10:16:35+08:00] Incoming HTTP/2.0 GET /api/v1/serviceaccount/default/dashboard/secret?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 10.99.16.41:45715: 
2021/02/08 10:16:35 Getting details of dashboard service account in default namespace
2021/02/08 10:16:35 [2021-02-08T10:16:35+08:00] Incoming HTTP/2.0 GET /api/v1/serviceaccount/default/dashboard/imagepullsecret?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 10.99.16.41:45715: 
2021/02/08 10:16:35 [2021-02-08T10:16:35+08:00] Outcoming response to 10.99.16.41:45715 with 404 status code
2021/02/08 10:16:35 [2021-02-08T10:16:35+08:00] Outcoming response to 10.99.16.41:45715 with 404 status code
2021/02/08 10:16:35 [2021-02-08T10:16:35+08:00] Outcoming response to 10.99.16.41:45715 with 404 status code

**Comment by floreks** [comment]
Where is the issue? The binding has some non-existent SA configured. It is defined inside the role but it does not exist overall thus the not found information. Seems to be working fine for me.

**Comment by floreks** [comment]
Not enough information provided. Not reproducible.

/close
