### ISSUE TITLE
Add support for extraArgs for dashboard-metrics-scraper in kubernetes-dashboard Helm chart

### ISSUE THREAD

**Issue by lmserrano** [kubernetes/dashboard#5801]
##### What would you like to be added

Currently, the `kubernetes-dashboard` Helm chart ( https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard ) is capable of setting whether we want the `dashboard-metrics-scraper` to be installed or not, via the `metricsScraper.enabled` flag. However, it is not possible to provide a `metricsScraper.extraArgs` to pass in additional configuration flags, which the project itself supports (https://github.com/kubernetes-sigs/dashboard-metrics-scraper)

##### Why is this needed

Among the list of the `dashboard-metrics-scraper` supported configuration flags, there are useful and important options for configuring the scrape resolution, duration, eventual database file, and kubeconfig configuration.

Being able to configure those, becomes even more important and useful when there seems to be no other `dashboard-metrics-scraper` chart readily available on artifacthub.io.

##### Comments

I'm tagging the maintainer of the official helm chart for this project, in hopes of also getting their attention to this issue. Thank you.

@desaintmartin (https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard)

**Comment by desaintmartin** [comment]
Indeed. I think the way to go would be to outsource the metrics scraper as a subchart, so that it would allow to have a correct separation on concern. The only downside would be an additional Pod...

**Comment by pierluigilenoci** [comment]
@lmserrano please take a look https://github.com/kubernetes/dashboard/pull/6093
