### ISSUE TITLE
Highlighting code blocks in docs

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#5805]
We use following code highlighters:
- `yaml`
- `shell`, not `sh` or `bash`. Unify `sh` and `bash` into `shell`.
- `json`

All of code highlighters are listed [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).
We can use top level item name and `aliases` for code highlighter and use them in lowercase in our documents.

Also, do followings:
- Separate command and result
- Remove `$` from code block.

Documents to be improved:
- [x] README.md on root #5808 @ydFu
- [x] common #5809 @ydFu
- [x] developer #5806 @shu-mutou
- [x] plugins #5810 @ydFu
- [x] user #5802 @ydFu

Out-of-dated, we need to reflesh this later.
- design

**Comment by ydFu** [comment]
I will do the following sub-task in this issue(#5808).
List the information that is PR Related this issue.
|  **Issue Name**  | **PR  number**  | **State**  |
|  ----  | ----  | ----  |
| docs/user  |  #5802  | Open |
| README.md at root.  |  #5808 | Open  |

**Comment by shu-mutou** [comment]
/close
@ydFu thank you for your cooperation!
