### ISSUE TITLE
Discussion: We should have a security session on the side panel

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#5816]
On the side panel, the *Cluster* session should be split in two. The new section should be called *Security* and have the following items:

* Cluster Role Bindings
* Cluster Roles
* Role Bindings
* Roles
* Service Accounts

This is trivial to implement and I can do it myself. But before making the move, I need to know if you guys agree with it.
For *Nodes* and *Namespaces* have nothing to do with *Roles* :)

**Comment by maciaszczykm** [comment]
We follow the same structure as https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/ and for me it's better to stick to it.

**Comment by floreks** [comment]
As @maciaszczykm said. We follow the K8S convention here and we do not want to diverge from it.

**Comment by marcosdiez** [comment]
Fair enough! Thank you!
