### ISSUE TITLE
Multi cluster support

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#582]
Tracking issue for support for multi cluster UI (aka Ubernetes) in Dashboard project.

**Comment by secabrera** [comment]
Whats about this ??

**Comment by maciaszczykm** [comment]
Closing as stale. Let's reopen in the future if required.

Related:
- https://www.reddit.com/r/kubernetes/comments/cb6vav/ubernetes_what_happened_to_this/etdmh5e/
- https://github.com/kubernetes-sigs/kubefed is currently alpha only

**Comment by lyveng** [comment]
Can Kubernetes dashboard be extended to work as a UI dashboard for cluster-api(Kubernetes-sigs/cluster-api#2916) supporting multiple clusters that are provisioned by cluster-api. Is this a valid use case or would the Kubernetes dashboard not suit this requirement.

**Comment by maciaszczykm** [comment]
At the moment we do not offer any features specific for Cluster API, but you can easily display all the resources that are deployed to the cluster by it (if we do not cover something then it probably is in our backlog). To manage some important CRDs, you can add them to the menu and have quick access.

**Comment by floreks** [comment]
We do not plan right now to offer cluster API support. There is a work in progress on a context switching feature to allow saving connection information for multiple clusters and connecting to them from a single Dashboard instance. My understanding is that cluster API is about the management of the cluster creation/deletion/scaling, etc. This is a bit out of scope for us right now. Maybe we'll rethink that in the future.
