### ISSUE TITLE
list event increate the apiserver load pressure

### ISSUE THREAD

**Issue by shiyajuan123** [kubernetes/dashboard#5853]
When obtaining the resource list of certain objects, the events of all pods under the resource will be obtained, but they are not displayed in the dashboard. If the number of resources is large, the number of events will also be large, and this operation will increase the apiserver load pressure.

**Comment by floreks** [comment]
Events are scanned for errors/warnings and if any occurs you will be able to see them on the list. They are also used when calculating the status of a resource.

![Zrzut ekranu z 2021-03-02 13-00-21](https://user-images.githubusercontent.com/2285385/109645593-5d24dc00-7b57-11eb-8353-a46283fb6130.png)
