### ISSUE TITLE
Follow logs does not work

### ISSUE THREAD

**Issue by shaozi** [kubernetes/dashboard#5854]
##### Environment

```
Installation method: kubeadm
Kubernetes version: 1.20.4
Dashboard version (v1.x is not supported. Use v2.0 or later.):v2.2.0+0.g0a30039e0
Operating system: Ubuntu 20
Node.js version ('node --version' output): 15.8
Go version ('go version' output):1.15.8
```

##### Steps to reproduce

Install Kubernetes-dashboard 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml
```
create service user and rbac

##### Observed result

View the Log of a pod in a deployment in default namespace, make sure "Follow Logs" is checked in the dropdown menu.

Logs does not follow. If you click the `>|` button, it will refresh, but no live follow of logs

##### Expected result

logs should follow

**Comment by floreks** [comment]
It's actually the autorefresh option that does not work and not follow logs. Follow logs might be misinterpreted here. It means that on refresh log viewer should scroll to the latest log line. It does not influence refreshing. `Auto-refresh` option does that. We have to fix the autorefresh.

**Comment by shaozi** [comment]
When I saw "Follow Logs" I interpret it equivalent to "-f", or "Watch()", kind of function that will append new logs to the end of the view as soon as when new logs are generated by a pod.

Is this feature supported?

**Comment by floreks** [comment]
No, it is only responsible for scrolling to the end of log container on refresh. We will have to change naming here. Currently we have a pure REST API and don't have any real live updates other than refreshes based on defined intervals.

**Comment by yanggeorge** [comment]
> No, it is only responsible for scrolling to the end of log container on refresh. We will have to change naming here. Currently we have a pure REST API and don't have any real live updates other than refreshes based on defined intervals.

Hi, do you mean that if the number of logs in the refresh interval more than 100, the some logs will missing on the log view?
