### ISSUE TITLE
Possible XSS vulnerabilities in logs and emulated console.

### ISSUE THREAD

**Issue by luks** [kubernetes/dashboard#5866]
##### Environment
Ubuntu 18.04

```
Installation method:
Kubernetes version: 1.16
Dashboard version  v2.0.4+0.g4da3dfcd1

```

##### Steps to reproduce
Looking on pod logs, we notice that it evaluate colours. So it is quite possible that javascript code will be evaluated as well. Same behaviour in emulated console when we exec into pod.

##### Observed result
Looking at the log pods we noticed coloured lines, bash colour. 

##### Expected result
All inputs filtered, encoded in order to prevent XSS attacks.

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/pull/5737
https://github.com/kubernetes/dashboard/releases/tag/v2.2.0

/close

**Comment by jf352** [comment]
Is there any possibility of bringing back coloured logs through some other means, or bringing back this functionality? In the linked issue it does say that there wasn't 

At the moment, some of the log files in our production system are borderline unreadable after upgrading as colours were a really good way of distinguishing between various components of the log. 

Also, not all codes are stripped - for example see the numerous `[30m` elements here:

![Screenshot 2021-08-20 at 17 56 01](https://user-images.githubusercontent.com/33285502/130267897-3980f512-672a-4004-abee-945e2a13c306.png)
