### ISSUE TITLE
Improve translation management

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#5872]
When we are updating the templates the translation files get updated and even small change result in thousands of lines changed. This needs to be improved, we have to find a way to change only the things that are necessary.

**Comment by floreks** [comment]
@shu-mutou do you know if it is possible to fix this?

**Comment by shu-mutou** [comment]
I will investigate this. 😉

**Comment by shu-mutou** [comment]
I found `ng extract-i18n` outputs items in `messages.xlf` in uncertain order.
A couple of result of running `ng extract-i18n` has differences in spite of no-change in html files.
I'll keep on tackling this.

**Comment by shu-mutou** [comment]
Ref: https://github.com/angular/angular/issues/41236
