### ISSUE TITLE
logs downloaded for a pod should get the extention .log inplace of .txt that is happening today.

### ISSUE THREAD

**Issue by rajattrt** [kubernetes/dashboard#5873]
Today if we download logs for a pod the log file has extension .txt - I am not sure if there is any specific reason for this. If not, probably we should consider having its extension as .log?

Release version where we found this - Dashboard v2.0.3+0.g665b4d367

**Comment by rajattrt** [comment]
Please update the label to the appropriate kind if needed.

**Comment by floreks** [comment]
Done :slightly_smiling_face: 

https://github.com/kubernetes/dashboard/commit/022c0a96cd766b50ac2a9081df4aa8d7ca45c2cb

/close
