### ISSUE TITLE
Install the development environment on windows, use the k8s cluster connected to linux, report an error。what should i do.help me ,please

### ISSUE THREAD

**Issue by pyjlwc2016** [kubernetes/dashboard#5903]
2021/03/18 16:40:53 Using namespace: kube-system
2021/03/18 16:40:53 Using in-cluster config to connect to apiserver
2021/03/18 16:40:53 Could not init in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: The system cannot find the path specified.
panic: could not create client config

**Comment by floreks** [comment]
Cluster configuration issue. Not related to the Kubernetes Dashboard itself. Service account tokens are not properly mounted into the container. You need to fix your cluster first.

/close
