### ISSUE TITLE
Some ports can be specified but are not working

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#591]
#### Issue details
Ports like 1 or 65535 can be assigned, but are not working

##### Steps to reproduce
1. press +
2. enter required fields
3. enter port 1 and target port 80
4. deploy

##### Observed result
internal endpoint is not working

##### Expected result
Maybe the validation range should be decreased

**Comment by cescoferraro** [comment]
should't this range be the same as --service-node-port-range

**Comment by cheld** [comment]
thanks for the hint

**Comment by floreks** [comment]
@cescoferraro Node port for the service is autogenerated as you can see [here](https://github.com/kubernetes/kubernetes/blob/421249785d15fb7af203a34fd3054a4765b96b67/pkg/api/v1/types.go#L1862).

We are actually setting here target port which according to the [documentation](https://github.com/kubernetes/kubernetes/blob/421249785d15fb7af203a34fd3054a4765b96b67/pkg/api/v1/types.go#L1852) is in range 1-65535.

I believe we can not really do anything about that. It will depend on system configuration and if given port in this range will be available then kubernetes will correctly use it for internal communication.

**Comment by cheld** [comment]
Finally, I had some time to retest properly. Issue is nonsense. Port 1 and 65536 works fine when testing properly....
