### ISSUE TITLE
Extra args for metrics-scraper

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/dashboard#5915]
##### What would you like to be added

I want to add extra args to metrics-scraper.

##### Why is this needed

To configure log verbosity.
Example:
```
      args:
        - --logtostderr=true
        - --v=0
```

**Comment by floreks** [comment]
Are you referring to the helm chart or metrics scraper itself?

**Comment by pierluigilenoci** [comment]
According to my knowledge, metrics-scraper should already have the configuration options. So I was only referring to the chart. Of course I could be wrong. 

Ref: https://github.com/kubernetes-sigs/dashboard-metrics-scraper/blob/master/server.go#L51-L62

**Comment by pierluigilenoci** [comment]
@floreks I was talking about my specific case. Of course, it makes sense that the ability to put generic extraArgs is added, not just what I need. But if you think it makes more sense to add two specific parameters to manage the logs do as you see fit.

**Comment by maciaszczykm** [comment]
cc @desaintmartin

**Comment by desaintmartin** [comment]
PR accepted! ;)

**Comment by pierluigilenoci** [comment]
Duplicate of #5801

**Comment by pierluigilenoci** [comment]
@desaintmartin @maciaszczykm done!
https://github.com/kubernetes/dashboard/pull/6093 please take a look ❤️

**Comment by desaintmartin** [comment]
Closed by https://github.com/kubernetes/dashboard/pull/6093
/close
