### ISSUE TITLE
Exec into multiple containers pod, Switch to a different container,  Can't enter the command line correctly

### ISSUE THREAD

**Issue by wisheen** [kubernetes/dashboard#5921]
##### Environment

```
Installation method:
Kubernetes version: 1.18.12
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.0.4  or 2.2.0
Operating system: ubuntu 18.0.4
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

1. Select a Pod with multiple containers
2. Exec into pod, Can enter the command line correctly
3. Switch to a different container,  At the bottom of the tip Normal closure
4. Switch agen, It's correctly
5. Switch agen, But it is still wrong

**Comment by floreks** [comment]
Already fixed by #5868. Will be available in the next release.

/close
