### ISSUE TITLE
Exclude `do-not-merge/invalid-commit-message` check for PRs from dependabot.

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#5932]
##### What should be cleaned up or changed
Dependa bot was introduced, but some commit messages for updating package that includes GitHub keyword, like `@angular`, are labeled as `do-not-merge/invalid-commit-message`.

##### Provide any links for context
Asked test-infra for this issue as following:
https://github.com/kubernetes/test-infra/issues/21534

This issue is for tracking above in dashboard repo.

**Comment by shu-mutou** [comment]
Dependabot
Issue: https://github.com/dependabot/dependabot-core/issues/3378
Fix: https://github.com/dependabot/dependabot-core/pull/3404
Release: https://github.com/dependabot/dependabot-core/pull/3415

**Comment by shu-mutou** [comment]
But v0.139.1 is not released now. https://github.com/dependabot/dependabot-core/releases

**Comment by shu-mutou** [comment]
v0.139.1 is released now!

**Comment by shu-mutou** [comment]
But new PRs are not fixed. https://github.com/kubernetes/dashboard/pull/5952
So asking current available version of dependabot https://github.com/dependabot/dependabot-core/pull/3415

**Comment by shu-mutou** [comment]
Seemed to be fixed again in v0.139.2 https://github.com/dependabot/dependabot-core/pull/3448

**Comment by maciaszczykm** [comment]
It looks like the problem is still there: https://github.com/kubernetes/dashboard/pull/6040.

**Comment by shu-mutou** [comment]
This has not been resolved completely and Dependabot team recognizes and is considering this yet.
https://github.com/dependabot/dependabot-core/issues/3378#issuecomment-825508310

**Comment by maciaszczykm** [comment]
Closing as we will be moving away from dependabot anyways (see: https://github.com/kubernetes/dashboard/issues/7470).
