### ISSUE TITLE
Allow sign-in for http

### ISSUE THREAD

**Issue by BryanDollery** [kubernetes/dashboard#5937]
##### What would you like to be added
I would like to sign-in via HTTP. 

##### Why is this needed
I have a tls terminating proxy in front of my cluster so I don't want/need to deploy dashboard with tls enabled -- I want http. Also, I run this behind an ingress controller that rewrites the URLs so dashboard never sees https or localhost, or any of the other stuff you want to see in order to make this usable. However, I find that I'm unable to sign in because Dashboard thinks that this is somehow less secure than terminating tls at the dashboard service.

##### Comments
I can understand why you've implemented this restriction -- there are a lot of people out there who will leave dashboard unsecured. However, an option to enable this would go a long way towards making this a more useful tool for me, and probably for a lot of other people.

**Comment by floreks** [comment]
The only thing that matters here is if in the end you are accessing Dashboard over HTTPS. How you choose to expose it is up to you. You can decide to serve Dashboard over HTTP inside the cluster and then use proxy to serve it over HTTPS to end users. The only restriction here is that the end user uses either localhost or HTTPS to access it.

**Comment by BryanDollery** [comment]
I tried that. I terminated tls at my layer 4 lb then routed the traffic to port 80. Dashboard's sign-in screen won't let me log in because the request isn't tls.

**Comment by floreks** [comment]
If you want to serve Dashboard over HTTP and use your custom proxy with custom certs then pass `allow-insecure-login` to the Dashboard. It will then disable internal HTTPS check on the backend side and only maintain a check for the frontend part.
