### ISSUE TITLE
Feature request: handle Deployments

### ISSUE THREAD

**Issue by mikedewar** [kubernetes/dashboard#595]
#### Show deployments as top-level application in the UI

Using Deployments (http://kubernetes.io/docs/user-guide/deployments/) to deploy pods seems to be the recommended (but new?) approach to getting containers out in the wild. However, with the GCE dashboard UI (kubernetes-dashboard-v1.0.0 ) the Deployments don't show up as applications, only replication controllers show up. 

It would be great if the UI would handle deployments as top level Applications in the same way that the UI handles replication controllers.

**Comment by bryk** [comment]
We have this on our roadmap, which will be formalized on GitHub in a matter of days.

We already started design work on this in #589. 

Btw, you're strongly encouraged to contribute to help us with the support of deployments.

**Comment by rata** [comment]
@bryk is this expected soon and can maybe be included in a kubernetes 1.2.x release?

**Comment by bryk** [comment]
No sooner than a month from now, but definitely for some of 1.2.x releases

**Comment by jowy** [comment]
What's the current status of this? I'd like to help contribute to this feature.

**Comment by bryk** [comment]
Everything is unblocked. You are very welcome to contribute and do this :) We now (almost) have a page for Replica Sets + Replication Controllers, so there is a space for Deployments there.

How can I help you with contribution?

**Comment by Draiken** [comment]
I started implementing the backend for deployment details. 
Is there a reference for a similar detail page? All details I looked at are using direct api requests and have TODO comments to use channels, so I was looking for somewhere where that was done before.

What info is going to be on the page itself? Not sure how to approach this. Do you want specific PRs for backend, frontend or even smaller parts?

Followed the devel docs, setup the environment, built a naive implementation of getting the details of the deployments but I'm pretty lost here :smile:

**Comment by floreks** [comment]
Regarding backend. Just get deployment object in similar way as it's done for i.e. replicasetdetail. I know there is todo but we will change it once channels for single resources are done.

Regarding what should be displayed. Use kubectl describe and try to show similar details. Events on different tab. Most important data from describe. Related objects can be added later.

You can separate frontend and backend in 2 PRs it will be easier to review.

Thanks for help!

**Comment by Draiken** [comment]
Should I submit a PR early or wait until I think it's done?

**Comment by floreks** [comment]
It depends. If you are not sure about something and need our help then you can submit it early, otherwise I think you can work until you think it's done and then we'll review and discuss.

**Comment by bryk** [comment]
Send PR as early as you think it can be reviewed :) Thanks!

**Comment by bryk** [comment]
This is being worked on. Basic support for deployment will land in next beta release.

**Comment by bryk** [comment]
This is done. Beta2 release (this Friday) will include it.
