### ISSUE TITLE
dashboard login error

### ISSUE THREAD

**Issue by bidianqing** [kubernetes/dashboard#5968]
I'm use the url setup `https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md`
Getting a Bearer Token, but show login error ,Please tell me what to do? thanks
![image](https://user-images.githubusercontent.com/12196280/113886698-7888a400-97f3-11eb-9ba1-89067e3f3749.png)

**Comment by floreks** [comment]
Wrong issue template. No info about setup.

/close
