### ISSUE TITLE
Helm chart could expose token-ttl parameter

### ISSUE THREAD

**Issue by torrescd** [kubernetes/dashboard#5980]
Helm chart could expose token-ttl parameter.

If this is wanted, I could try to make the PR.

Regards

**Comment by floreks** [comment]
That's what `extraArgs` param is for.

https://github.com/kubernetes/dashboard/blob/c4f06de50e95a4ecbf8ba919e7a79910d7a72793/aio/deploy/helm-chart/kubernetes-dashboard/values.yaml#L33-L38

/close
