### ISSUE TITLE
Not working when I change service of kubernetes dashboard (type: LoadBalancer)

### ISSUE THREAD

**Issue by skri547** [kubernetes/dashboard#5987]

**Comment by skri547** [comment]
I don't want to run Kube-proxy in all the clusters I manage, Is there a way I can create a service load balancer and look at the same dashboard with a load balancer address?  

I did this step but couldn't resolve anything with load balancer IP.

**Comment by floreks** [comment]
This is not a Dashboard-related issue. It is purely related to the Kubernetes itself and exposing the application (any application) to the outside. We do not provide Kubernetes support here.

Closing as this is a configuration issue only.

/close

**Comment by skri547** [comment]
@floreks When i deploy any application i will be accessible but this particular one is not accessible on load balancer IP. But this works fine when I use kubeproxy with service set to cluster IP.
