### ISSUE TITLE
Release v.1.0.1

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#600]
Recently we've done a bunch of bugfixes and small features. How about we do a patch release?

**Comment by bryk** [comment]
@maciaszczykm @floreks How about one of you do this? You should have all permissions needed. This is a nice opportunity for visibility and I don't want to be a single point of failure for doing releases :)

**Comment by maciaszczykm** [comment]
Should we do it now?

**Comment by bryk** [comment]
Yeah, I say yes.

**Comment by floreks** [comment]
That's fine. We can also do that :) Maybe we should wait for events fix to go in and then release?

**Comment by bryk** [comment]
Of course. If you think events fix will go in soon, then let's wait.
