### ISSUE TITLE
Set default settings via command line / env variables

### ISSUE THREAD

**Issue by MattJeanes** [kubernetes/dashboard#6000]
##### What would you like to be added

When we upgrade the Kubernetes Dashboard or the pod gets destroyed or moved in any way the server-side dashboard settings such as max items per page all reset back to default.

##### Why is this needed
This behaviour is very annoying as our team likes to use the maximum items per page but it will "randomly" reset back to default. We also use the cluster name feature which is useful when working on multiple clusters and this changes back as well.

##### Comments

I've not found any way to do this currently in the docs, but please let me know if this functionality already exists. A possible workaround might be mounting persistent storage to the dashboard pod but this shouldn't be necessary.

**Comment by maciaszczykm** [comment]
`kubernetes-dashboard-settings` contains all the settings. You can modify it on your own. You can also make sure that you will not override it during update. It's not connected to the pod.

**Comment by maciaszczykm** [comment]
See: https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended.yaml#L83

**Comment by maciaszczykm** [comment]
Please reopen if you need anything else from us.

**Comment by MattJeanes** [comment]
That's perfect thank you, I've also just seen that the helm chart contains a `settings` object for this - not sure how I missed that one!
