### ISSUE TITLE
Support networking.k8s.io/Ingresses

### ISSUE THREAD

**Issue by rfvermut** [kubernetes/dashboard#6021]
##### What would you like to be added

Users of built-in readonly dashboard will see their networking.k8s.io/Ingresses together with deprecated extensions/Ingresses
##### Why is this needed

extensions/Ingresses are being deprecated. new tools are creating networking.k8s.io/Ingresses and they don't get displayed in UI.

https://github.com/kubernetes/dashboard/pull/6020

**Comment by floreks** [comment]
Fixed by #6124
/close
