### ISSUE TITLE
Chinese translation – i18n/zh-Hans/messages.zh-Hans.xlf 

### ISSUE THREAD

**Issue by wisheen** [kubernetes/dashboard#6032]
The Chinese translation of 1.x is correct, but 2.x (master) is incomplete

i18n/zh-Hans/messages.zh-Hans.xlf
target translate chinese

      <trans-unit id="c97f017e8bd3fb17065c3c94515a2cca404f0157" datatype="html">
        <source>Cron Jobs</source>
        <target>定时任务</target>
      </trans-unit>
      <trans-unit id="d41640b21b662e4d9ee00c35239d30d15f1de9c7" datatype="html">
        <source>Daemon Sets</source>
        <target>守护进程集</target>
      </trans-unit>
      <trans-unit id="969a1d5188e9bde32221c1230eab21a3398b0cbe" datatype="html">
        <source>Deployments</source>
        <target>部署</target>
      </trans-unit>
      <trans-unit id="43f1cc191ebc0b8ce89f6916aa634f5a57158798" datatype="html">
        <source>Jobs</source>
        <target>任务</target>
      </trans-unit>
      <trans-unit id="7357d53d819cc1f5dd329a4fff4c582461ee1317" datatype="html">
        <source>Pods</source>
        <target>容器组</target>
      </trans-unit>
      <trans-unit id="d9161a5f702c1f98ea34e4996c2d0b0c9eb1b66a" datatype="html">
        <source>Replica Sets</source>
        <target>副本集</target>
      </trans-unit>
      <trans-unit id="900ec6b108c64adf2f23a3a84699be1217050001" datatype="html">
        <source>Replication Controllers</source>
        <target>副本控制器</target>
      </trans-unit>
      <trans-unit id="0756fdca226249dcff9d05651d50b7acdade2aba" datatype="html">
        <source>Stateful Sets</source>
        <target>有状态副本集</target>
      </trans-unit>

**Comment by helight** [comment]
those words we discussed and decide  do not translate

**Comment by shu-mutou** [comment]
/close
Whether translate k8s objects is decided in each language team.
