### ISSUE TITLE
crd json formate display error

### ISSUE THREAD

**Issue by helight** [kubernetes/dashboard#6072]
json formate turn to yaml formate when it is refresh.

![image](https://user-images.githubusercontent.com/433500/118428923-1a5cb400-b703-11eb-989f-cc726cf4bcb1.png)

**Comment by maciaszczykm** [comment]
If you refresh the page then it will go back as this feature wasn't implemented. It's not a bug but a feature. We might keep preferred format in the cookie/local storage.

/label feature
/unlabel bug

**Comment by floreks** [comment]
Yep, this is desired behavior for now. We'd need to add some kind of switch to the settings maybe to set this.

**Comment by helight** [comment]
the refresh I mean is auto refresh，ajax request silence

**Comment by floreks** [comment]
I see. This happens only for the CRD details. I was able to reproduce. Should be a very minor fix.
