### ISSUE TITLE
dashboard logs download excludes timestamp despite being toggled on

### ISSUE THREAD

**Issue by Yoshi275** [kubernetes/dashboard#6087]
##### Environment

```
Installation method:Helm chart
Kubernetes version:1.15+, or `1.15.12-eks-31566f` for Git version
Dashboard version (v1.x is not supported. Use v2.0 or later.): Should be v2.2.0, using Helm chart v4.0.0 [here](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard)
Operating system:Linux/UNIX
```

##### Steps to reproduce

1. View the information of any Pod
2. Click "View Logs"
3. Enable showing of timestamps
4. Download logs using the "Download" icon

##### Observed result

<img width="658" alt="Screenshot 2021-05-20 at 11 00 12 AM" src="https://user-images.githubusercontent.com/19257264/118912695-bd5b3b00-b95a-11eb-88f2-d24bbf5f9765.png">
Timestamps are missing from logs

##### Expected result

![Screenshot 2021-05-20 at 11 34 16 AM](https://user-images.githubusercontent.com/19257264/118915377-6b68e400-b95f-11eb-9721-68fa5756eb84.png)
It'll be really great to be able to have the timestamps appear when prompted, for downloading the dashboard's pod logs?

**Comment by floreks** [comment]
This was intended behavior. Log viewer and download are 2 completely different features. Our download endpoint simply does not support the timestamp switch. It would be an enhancement and it will require an additional checkbox inside the download dialog to control timestamp visibility.
