### ISSUE TITLE
Metrics graph labels get squished when using longer than 15m window

### ISSUE THREAD

**Issue by jclangst** [kubernetes/dashboard#6109]
##### Environment

```
Installation method: Custom
Kubernetes version: 1.20
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.2.0
```

##### Observed result
![kube_dashboard](https://user-images.githubusercontent.com/13301098/119420481-3a234780-bcc2-11eb-9875-b8590fba9b48.png)

##### Expected result

Not squished

##### Comments

Gets very bad after an hour or two so imposes a practical limit on the metrics window. We'd like to show the last few hours to our team.

**Comment by jclangst** [comment]
Looks like if the window is allowed to grow long enough 5+ hours, it will in fact re-adjust. I'd still recommend better spacing for the intermediate period.

**Comment by floreks** [comment]
This is actually not a bug. We simply do not support this. Current code only normalizes the data and it tries to show all available metrics for the specified time window. Only default metrics scraper is currently supported. It might now work properly if you decide to change it to custom values.

**Comment by floreks** [comment]
We should be able to calculate some kind of average/median in case there are more than i.e. 15 metrics available. I'll check that.

**Comment by floreks** [comment]
@jclangst #6126 should add generic support for all possible metric duration/resolution combinations.
