### ISSUE TITLE
Frontend: Text `ago` is duplicated in notifications panel

### ISSUE THREAD

**Issue by dom111** [kubernetes/dashboard#6116]
##### Environment

Installation method: n/a
Kubernetes version: n/a
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.2.0+0.g0a30039e0
Operating system: n/a
Node.js version ('node --version' output): n/a
Go version ('go version' output): n/a

##### Steps to reproduce
Perform an action that results in a notification (e.g. access something your user doesn't have access to).

##### Observed result
The relative time should is shown (e.g. a minute ago) with duplicated text `ago`.

![Screenshot showing issue](https://user-images.githubusercontent.com/842680/119482731-1efd1a00-bd4c-11eb-9c5c-3c257c49cbf8.png)

##### Expected result
The duplicate `ago` should not be shown.

##### Comments
Looks to be this [`template.html`][0] conflicting with [`relativetime.ts`][1].

Happy to raise a PR to remove either (probably the superfluous content in `template.html`?). Should this value (ago) also be localised in `relativetime.ts` using [`Intl.RelativeTimeFormat`][2] at the same time[3]?

[0]: https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/chrome/notifications/template.html#L46
[1]: https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/common/pipes/relativetime.ts#L121
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat
[3]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat#polyfill

**Comment by floreks** [comment]
Nice catch! You are welcome to fix this. We can remove it from the template as it will be a much simpler solution than going through all templates where the pipe is being used.

**Comment by floreks** [comment]
What is your node version?

**Comment by dom111** [comment]
14.16.1

**Comment by floreks** [comment]
I think this is not an issue on your side. It seems that our CI is broken and didn't properly report tests failure and angular 12 migration PR was merged as it seemed that all tests have passed. I have just checked the logs and it seems that unit tests have actually failed there. I'll have to investigate and fix that tomorrow. This is definitely related to https://github.com/kubernetes/dashboard/pull/6014.

**Comment by dom111** [comment]
Happy to help if I'm able (and around at the right time!) Thanks again for coming back quickly

**Comment by floreks** [comment]
Finally, I was able to find and fix the CI/test/build issues with https://github.com/kubernetes/dashboard/pull/6119.

You are welcome to create your PR now. Remember to run `npm ci`.

**Comment by dom111** [comment]
Ahh, sorry I wasn't able to get back to this, my new daughter arrived. Looks like you're all sorted :)
