### ISSUE TITLE
Images to k8.gcr.io

### ISSUE THREAD

**Issue by tanneeru111** [kubernetes/dashboard#6165]
Can we please upload below images to k8s.gcr.io location  as we are facing the docker limits issues, and update the recommended.yaml files.
kubernetesui/dashboard:v2.3.0
kubernetesui/metrics-scraper:v1.0.6

**Comment by floreks** [comment]
Unfortunately we can't do it as every push there has to be done by the Google employee and we weren't able to automate it, thus we have had to switch to dockerhub registry.

**Comment by medyagh** [comment]
we in minikube would appreciate this feature too, as we are building preload images we hit rate limit.
most of k8s images are already on gcr except this one, this could make our lives much easier

**Comment by cmoulliard** [comment]
Images could also be pushed to quay.io, ghcr.io ;-)
