### ISSUE TITLE
Documentation bug: dashboard/docs/user/accessing-dashboard/README.md

### ISSUE THREAD

**Issue by faisalchishtii** [kubernetes/dashboard#6173]
The accessing-dashboard README.md (dashboard/docs/user/accessing-dashboard/README.md) says the following:

> In case you are trying to expose Dashboard using NodePort on a multi-node cluster, then you have to find out IP of the node on which Dashboard is running to access it. Instead of accessing https://<master-ip>:<nodePort> you should access https://<node-ip>:<nodePort>.

Why do I need to find out IP of the node on which Dashboard is running. My understanding is that NodePort makes the service available from all nodes within the cluster as it exposes the service on each Node’s IP at the NodePort using `NodeIP:NodePort`?

**Comment by floreks** [comment]
It might expose it on every node however if you won't scale deployment to all available nodes then using `NodeIP:NodePort` of the node on which the application is not running directly will not work. Unless K8S changed their logic lately it should work exactly as described in our docs. The pod is always assigned to a single node.
