### ISSUE TITLE
Pod detail page not loading (v.2.3)

### ISSUE THREAD

**Issue by discostur** [kubernetes/dashboard#6175]
```
Installation method: helm
Kubernetes version: 1.20.5
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.3.0
```

If i click on some pods, the details page opens but most of the fields just show the loading spinner and loading never finishes: 

<img width="1801" alt="Bildschirmfoto 2021-06-16 um 11 38 28" src="https://user-images.githubusercontent.com/2615420/122196933-fde5a000-ce97-11eb-9ab9-0fa8c1ffe107.png">

My chrome console log shows me the following error output: 

```
polyfills.35fb40cb94e43d6de47e.js:1 Uncaught TypeError: Cannot read property 'port' of undefined
    at b (de.main.68d8f8ee9c48a786784c.js:3)
    at ko (de.main.68d8f8ee9c48a786784c.js:3)
    at xo (de.main.68d8f8ee9c48a786784c.js:3)
    at de.main.68d8f8ee9c48a786784c.js:3
    at xo (de.main.68d8f8ee9c48a786784c.js:3)
    at de.main.68d8f8ee9c48a786784c.js:3
    at xo (de.main.68d8f8ee9c48a786784c.js:3)
    at de.main.68d8f8ee9c48a786784c.js:3
    at xo (de.main.68d8f8ee9c48a786784c.js:3)
    at Qo (de.main.68d8f8ee9c48a786784c.js:3)
```

However, this only happens one some pods - others are show fine. I was not able to find any difference between the pods which are working and the broken ones. 

I just reverted to dashboard `v.2.2.0` and all pods are showing fine - so the error is related to `v2.3.0`. 

Regards,
Kilian

**Comment by floreks** [comment]
@discostur created a PR to fix it and will do a 2.3.1 release soon.

**Comment by discostur** [comment]
@floreks nice, thanks for your quick response / help ;)

**Comment by discostur** [comment]
@floreks i just deployed `v2.3.1` and i can confirm the error is fixed - details page is loading like it should ;)
