### ISSUE TITLE
Encountering Dashboard Container Restart on Flannel Implementation 

### ISSUE THREAD

**Issue by Richard-Barrett** [kubernetes/dashboard#6180]
##### Environment

```
Installation method: https://www.tecmint.com/install-kubernetes-cluster-on-centos-7/ on OpenStack VMs 
Kubernetes version: 1.21.1
Dashboard version (v1.x is not supported. Use v2.0 or later.):
Operating system: 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
Node.js version ('node --version' output):
Go version ('go version' output): go1.16.4
```

##### Steps to reproduce

- Set Up VMs on OpenStack
- Install Kubernetes on Centos7 Images Using https://www.tecmint.com/install-kubernetes-cluster-on-centos-7/
- Use Flannel 
- Initialize Kubeadm with --pod-network-cidr
```
kubeadm init --pod-network-cidr=10.244.0.0/16
```
- Ensure Every VM has a file /run/flannel/subnet.env on each VM in the Cluster
```
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=10.244.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
- Deploy the Dashboard https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

##### Observed result

Container for Dashboard goes into an error state and crashloopbackoff after 4 errors it just stays in Terminating State.
```
[root@kubernetes-master001 flannel]# kubectl logs -f kubernetes-dashboard-78c79f97b4-ldpbm  -n kubernetes-dashboard
2021/06/16 13:36:26 Using namespace: kubernetes-dashboard
2021/06/16 13:36:26 Using in-cluster config to connect to apiserver
2021/06/16 13:36:26 Using secret token for csrf signing
2021/06/16 13:36:26 Initializing csrf token from kubernetes-dashboard-csrf secret
2021/06/16 13:36:26 Starting overwatch
panic: Get "https://10.96.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf": dial tcp 10.96.0.1:443: i/o timeout
goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc00000d2e0)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x413
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc0001bf400)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:503 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc0001bf400)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:471 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:552
main.main()
        /home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:105 +0x21c
```
##### Expected result

Dashboard is Accessible via SSH Tunnel and SOCKS5 Proxy 

##### Comments

My Openstack Security Group has the following:

![image](https://user-images.githubusercontent.com/32808365/122233980-15199300-ce82-11eb-814f-4529c79a7311.png)

![image](https://user-images.githubusercontent.com/32808365/122234044-26629f80-ce82-11eb-8282-1e87af3d623b.png)
![image](https://user-images.githubusercontent.com/32808365/122234116-3aa69c80-ce82-11eb-862e-19b8d3841d71.png)

**Comment by floreks** [comment]
That's definitely not a bug but a configuration issue on your side. Dashboard does not manage its' connection, Kubernetes handles that. It need access to the api server.

/close
