### ISSUE TITLE
old metrics-scraper in 2.3.1

### ISSUE THREAD

**Issue by dfateyev** [kubernetes/dashboard#6182]
##### Environment

```
Installation method: yaml deploy
Kubernetes version: 1.20, 1.21
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.3.1
```

##### Steps to reproduce
Check the `https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml`.
The version of `metrics-scraper` used there is older than announced at the release page: `kubernetesui/metrics-scraper:v1.0.7`

##### Observed result
Metrics-scraper old version is installed

##### Expected result
There should be an actual version used in the manifest

**Comment by floreks** [comment]
Updated release info. We'll update it in the next release as tag edition is not an option for us.

/close
