### ISSUE TITLE
Implement "kubectl get events" in the side panel

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#6186]
During fires the first thing I need to know is "what's going on".

One way to get that is to type

`kubectl get  events`
or even better
`kubectl get -A  events -w`

The dashboard currently does not have that.

If I implement it, would you guys approve it/accept it ?

It would be a new item in the side panel

**Comment by maciaszczykm** [comment]
Sounds good. @floreks @shu-mutou what do you think?

**Comment by shu-mutou** [comment]
+1. Dashboard has event list, but it is on only namespace detail view, i.e. the events are namespaced and we can not see events with `All namespaces`. Under `Cluster` side menu is good place for this, I think.

**Comment by maciaszczykm** [comment]
Yes, cluster seems to be fine: https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/

**Comment by floreks** [comment]
Sounds good to me

**Comment by floreks** [comment]
I'll take it.

**Comment by marcosdiez** [comment]
@floreks Sorry, I just saw that now. I actually did it. Feel free to modify as you please.
