### ISSUE TITLE
How can I access Kubernetes dashboard running on Linux VM from my local laptop?

### ISSUE THREAD

**Issue by aakashshukla** [kubernetes/dashboard#6195]
I tried configuring the kubernetes-dashboard service as ClusterIP, NodePort, ExternalIPs. I even tried giving full access using ClusterRoleBinding. I also tried creating an Ingress resource to expose kubernetes-dashboard service. Nothing worked.

When I try to access https://<master-ip>:6443/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login - I get the following error.

`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}`

Any help would be really appreciated.

**Comment by floreks** [comment]
No steps to reproduce. No information about the setup and dashboard installation. Fill out the issue template.

/close
