### ISSUE TITLE
Can't open dashboard on public IP

### ISSUE THREAD

**Issue by aabed** [kubernetes/dashboard#620]
#### Issue details
I can't access the dashboard running on 
Get https://<REALIP>:443/api/v1/replicationcontrollers: x509: failed to load system roots and no roots provided

##### Environment
CoreOS on Azure
using the getting-started scripts

```
Dashboard version:1.0.1
Kubernetes version:1.2.1
Operating system:CoreOS
```

##### Steps to reproduce
using the kubernetes-dashboard.yml file on the repo
just edited the  - --apiserver-host=https://<REALIP>:443

##### Observed result
Internal Server Error (500)

Get https://40.68.221.132:443/api/v1/replicationcontrollers: x509: failed to load system roots and no roots provided

**Comment by bryk** [comment]
This is most likely a problem with your configuration. I.e., you have invalid certificates. Take a look at the issue and tell us whether this helps: https://github.com/kubernetes/dashboard/issues/374

**Comment by aabed** [comment]
I have been in there for a while, tried all the solutions mentioned there ,
and nothing worked

**Comment by bryk** [comment]
> using the getting-started scripts

The getting started scripts are known to not-work-that-good for Azure. I bet this is something wrong with certs.

@luxas do you have any pointers for @aabed ?

**Comment by aabed** [comment]
@bryk can you recommend another way to deploy it, rather than the getting started scrips?

**Comment by bryk** [comment]
To Azure? I don't know, I'm not expert in this matter.

I know, however, that hack/local-up-cluster.sh config works with Dashboard. See https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh

**Comment by bryk** [comment]
Closing. Please reopen if needed.
