### ISSUE TITLE
RBAC is not working for Kubernetes dashboard

### ISSUE THREAD

**Issue by Laxmanpathare** [kubernetes/dashboard#6238]
##### Environment

```
Installation method: Helm Chart
Kubernetes version: 1.19 (EKS)
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.1.0
Operating system: Linux
```

##### Steps to reproduce

1. Deploy kubernetes-dashboard helm chart(version 4.0.0) with clusterReadOnlyRole: true
2. Access the dashboard
3. select any namespace
4. select pod and delete

##### Observed result

1. Describe secret kubernetes-dashboard-token-xxxx
2. Copy token to login to dashboard
3. Tried deleting pod
4. It's getting deleted

##### Expected result

It should deny for deletion or fetch an error for RBAC

##### Comments

-bash-4.2$ k describe clusterrolebinding kubernetes-dashboard-readonly
Name:         kubernetes-dashboard-readonly
Labels:       app.kubernetes.io/instance=kubernetes-dashboard
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kubernetes-dashboard
              app.kubernetes.io/version=2.1.0
              helm.sh/chart=kubernetes-dashboard-4.0.0
Annotations:  meta.helm.sh/release-name: kubernetes-dashboard
              meta.helm.sh/release-namespace: kube-system
Role:
  Kind:  ClusterRole
  Name:  kubernetes-dashboard-readonly
Subjects:
  Kind            Name                  Namespace
  ----            ----                  ---------
  ServiceAccount  kubernetes-dashboard  kube-system

---------------------------------------------------------------------------------------------------------
-bash-4.2$ k describe clusterrole kubernetes-dashboard-readonly
Name:         kubernetes-dashboard-readonly
Labels:       app.kubernetes.io/instance=kubernetes-dashboard
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kubernetes-dashboard
              app.kubernetes.io/version=2.1.0
              helm.sh/chart=kubernetes-dashboard-4.0.0
Annotations:  meta.helm.sh/release-name: kubernetes-dashboard
              meta.helm.sh/release-namespace: kube-system
PolicyRule:
  Resources                                      Non-Resource URLs  Resource Names  Verbs
  ---------                                      -----------------  --------------  -----
  persistentvolumeclaims                         []                 []              [get list watch get list watch]
  bindings                                       []                 []              [get list watch]
  configmaps                                     []                 []              [get list watch]
  endpoints                                      []                 []              [get list watch]
  events                                         []                 []              [get list watch]
  limitranges                                    []                 []              [get list watch]
  namespaces/status                              []                 []              [get list watch]
  namespaces                                     []                 []              [get list watch]
  nodes                                          []                 []              [get list watch]
  persistentvolumes                              []                 []              [get list watch]
  pods/log                                       []                 []              [get list watch]
  pods/status                                    []                 []              [get list watch]
  pods                                           []                 []              [get list watch]
  replicationcontrollers/scale                   []                 []              [get list watch]
  replicationcontrollers/status                  []                 []              [get list watch]
  replicationcontrollers                         []                 []              [get list watch]
  resourcequotas/status                          []                 []              [get list watch]
  resourcequotas                                 []                 []              [get list watch]
  serviceaccounts                                []                 []              [get list watch]
  services                                       []                 []              [get list watch]
  daemonsets.apps                                []                 []              [get list watch]
  deployments.apps/scale                         []                 []              [get list watch]
  deployments.apps                               []                 []              [get list watch]
  replicasets.apps/scale                         []                 []              [get list watch]
  replicasets.apps                               []                 []              [get list watch]
  statefulsets.apps                              []                 []              [get list watch]
  horizontalpodautoscalers.autoscaling           []                 []              [get list watch]
  cronjobs.batch                                 []                 []              [get list watch]
  jobs.batch                                     []                 []              [get list watch]
  daemonsets.extensions                          []                 []              [get list watch]
  deployments.extensions/scale                   []                 []              [get list watch]
  deployments.extensions                         []                 []              [get list watch]
  ingresses.extensions                           []                 []              [get list watch]
  networkpolicies.extensions                     []                 []              [get list watch]
  replicasets.extensions/scale                   []                 []              [get list watch]
  replicasets.extensions                         []                 []              [get list watch]
  replicationcontrollers.extensions/scale        []                 []              [get list watch]
  networkpolicies.networking.k8s.io              []                 []              [get list watch]
  poddisruptionbudgets.policy                    []                 []              [get list watch]
  clusterrolebindings.rbac.authorization.k8s.io  []                 []              [get list watch]
  clusterroles.rbac.authorization.k8s.io         []                 []              [get list watch]
  rolebindings.rbac.authorization.k8s.io         []                 []              [get list watch]
  roles.rbac.authorization.k8s.io                []                 []              [get list watch]
  storageclasses.storage.k8s.io                  []                 []              [get list watch]
  volumeattachments.storage.k8s.io               []                 []              [get list watch]

-----------------------------------------------------------------------------------------------------------------------

-bash-4.2$ k describe role kubernetes-dashboard
Name:         kubernetes-dashboard
Labels:       app.kubernetes.io/instance=kubernetes-dashboard
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kubernetes-dashboard
              app.kubernetes.io/version=2.1.0
              helm.sh/chart=kubernetes-dashboard-4.0.0
Annotations:  meta.helm.sh/release-name: kubernetes-dashboard
              meta.helm.sh/release-namespace: kube-system
PolicyRule:
  Resources       Non-Resource URLs  Resource Names                     Verbs
  ---------       -----------------  --------------                     -----
  configmaps      []                 [kubernetes-dashboard-settings]    [get update]
  secrets         []                 [kubernetes-dashboard-certs]       [get update]
  secrets         []                 [kubernetes-dashboard-csrf]        [get update]
  secrets         []                 [kubernetes-dashboard-key-holder]  [get update]
  services/proxy  []                 [dashboard-metrics-scraper]        [get]
  services/proxy  []                 [heapster]                         [get]
  services/proxy  []                 [http:dashboard-metrics-scraper]   [get]
  services/proxy  []                 [http:heapster:]                   [get]
  services/proxy  []                 [https:heapster:]                  [get]
  services        []                 [dashboard-metrics-scraper]        [proxy]
  services        []                 [heapster]                         [proxy]

--------------------------------------------------------------------------------------------------------------------

-bash-4.2$ k describe rolebinding kubernetes-dashboard
Name:         kubernetes-dashboard
Labels:       app.kubernetes.io/instance=kubernetes-dashboard
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kubernetes-dashboard
              app.kubernetes.io/version=2.1.0
              helm.sh/chart=kubernetes-dashboard-4.0.0
Annotations:  meta.helm.sh/release-name: kubernetes-dashboard
              meta.helm.sh/release-namespace: kube-system
Role:
  Kind:  Role
  Name:  kubernetes-dashboard
Subjects:
  Kind            Name                  Namespace
  ----            ----                  ---------
  ServiceAccount  kubernetes-dashboard  kube-system

----------------------------------------------------------------------------------------------------------------

-bash-4.2$ k describe sa kubernetes-dashboard
Name:                kubernetes-dashboard
Namespace:           kube-system
Labels:              app.kubernetes.io/instance=kubernetes-dashboard
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=kubernetes-dashboard
                     app.kubernetes.io/version=2.1.0
                     helm.sh/chart=kubernetes-dashboard-4.0.0
Annotations:         meta.helm.sh/release-name: kubernetes-dashboard
                     meta.helm.sh/release-namespace: kube-system
Image pull secrets:  <none>
Mountable secrets:   kubernetes-dashboard-token-4q8jg
Tokens:              kubernetes-dashboard-token-4q8jg
Events:              <none>

**Comment by floreks** [comment]
You can do a very simple test to see if this is really an issue on our side. Try
```
kubectl delete pod xxx --token <token>`
```
where `<token>` is a token that you use to log in.

**Comment by Laxmanpathare** [comment]
> You can do a very simple test to see if this is really an issue on our side. Try
> 
> ```
> kubectl delete pod xxx --token <token>`
> ```
> 
> where `<token>` is a token that you use to log in.



I have tried it, and it's deleting it.

Please see below
'''
-bash-4.2$ k delete pod kubernetes-dashboard-67cbfbb697-584qd --token xxxxxx
pod "kubernetes-dashboard-67cbfbb697-584qd" deleted
-bash-4.2$
'''

**Comment by floreks** [comment]
Then it is not an issue on the Dashboard side. We are fully relying on Kubernetes here. Your cluster configuration might be an issue here.

**Comment by Laxmanpathare** [comment]
Also i have tried below.

``` kubectl auth can-i delete po --token  xxxxx -v=10```
``` Response Body: {"kind":"SelfSubjectAccessReview","apiVersion":"authorization.k8s.io/v1","metadata":{"creationTimestamp":null,"managedFields":[{"manager":"kubectl","operation":"Update","apiVersion":"authorization.k8s.io/v1","time":"2021-07-07T16:26:15Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:resourceAttributes":{".":{},"f:namespace":{},"f:resource":{},"f:verb":{}}}}}]},"spec":{"resourceAttributes":{"namespace":"default","verb":"delete","resource":"pods"}},"status":{"allowed":true,"reason":"RBAC: allowed by ClusterRoleBinding \"cluster-role-binding\" of ClusterRole \"cluster-role\" to Group \"system:serviceaccounts\""}}

yes```

**Comment by Laxmanpathare** [comment]
Issue is resolved now, Thank you for your support!

Root Cause : One of the clusterrolebinding was having "system:serviceaccounts" like below.
                      Also the cluster role to which this clusterrolebinding is associated was having ```delete``` verb for ```pod``` resources.

```subjects:
  - kind: Group
    name: 'system:serviceaccounts'
    apiGroup: rbac.authorization.k8s.io```

Resolution : 
  I have removed the ```delete``` verb from the clusterrole for ```pod``` resources.
