### ISSUE TITLE
ellipsis on long name not applied on window re-size

### ISSUE THREAD

**Issue by digitalfishpond** [kubernetes/dashboard#625]
##### Issue Description
on details page, when starting with a small-sized window, when increasing the window size to the point of triggering the full-sized UI, the ellipsis is not applied to the app name.

##### Environment
Dashboard version: 1.0.1
Kubernetes version: v1.2.0
Operating system: Ubuntu 15.10
Node.js version: v5.9.1
Go version: 1.5.3
Browser: chrome, firefox, IE

##### Steps to reproduce
1. deploy a new application with a very long app name via yaml or json
2. make browser window small enough to trigger the small screen layout
3. click on the new application to go to its details page
![kubernetes dashboard - google chrome_003](https://cloud.githubusercontent.com/assets/13361549/14346162/28ff4e9e-fcb1-11e5-8c0d-c71350db33cb.png)

4. maximise the screen
![kubernetes dashboard - google chrome_004](https://cloud.githubusercontent.com/assets/13361549/14346183/49fa978e-fcb1-11e5-8423-809b8698942f.png)

##### Observed result
the app name in the title and in the details section do not have the ellipsis applied
the screen has to be reloaded in order to trigger the ellipsis.
once it has been triggered once, it scales gracefully when screen is resized.

##### Expected result
ellipsis should be applied to name on re-size, even when starting from a small window view.

**Comment by digitalfishpond** [comment]
will add screenshots in a moment

**Comment by bryk** [comment]
@floreks Should be easy to fix. Just set up $watcher on the size and remove one time bindings. What do you think?

**Comment by floreks** [comment]
Yep, this should fix it. Will take a look.
