### ISSUE TITLE
The dashboard should have a way to browse files inside of a pod

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#6283]
Again, I volunteer to develop it, but before I want to discuss acceptance and implementation details.

The idea is that in pod details panel, on the right side of the toolbar, we add a new icon called "file manager".

It should show a "windows explorer" like view of all files within a specific container, allowing one to browse/view/download/edit? files inside of a contaier

Something very similar to https://marketplace.visualstudio.com/items?itemName=sandipchitale.kubernetes-file-system-explorer

Initially, it  could work like the above extension, grabbing the data using the go api with commands equivalentes to 

`kubectl exec -it pod-name -c containername -- ls -f /`

I have ideas to make it work in containers that don't have `ls`, like the kubernetes dashboard, but that's a discussion for a second topic.

**Comment by maciaszczykm** [comment]
Like I said in the pull request. The method is not reliable enough.

**Comment by maciaszczykm** [comment]
Please reopen if you want to discuss it further or you will find some other method to do this. We have a lot of open issues so if you are willing to help with development please pick something else.
