### ISSUE TITLE
Skipping login needs to be way easier by default

### ISSUE THREAD

**Issue by justinmchase** [kubernetes/dashboard#6301]
##### What would you like to be added
There should be a default one shot template which just completely skips all logging in.

##### Why is this needed
Because I don't care at all about logging in for local development and its a royal pain.

##### Comments
I get why you need all of the various complex log in options and thats great, but when I'm running it locally I just want to do `kubectl proxy` and then hit the dashboard and I'm ready to go.

You have the skip option, its just buried and requires me to just through a couple of additional hoops to enable it and every time I update the dashboard I have to go figure it out again. Its a constant source of frustration.

Please right on the front page of the docs where you have the main installation URL, please just add another one for "insecure, use for local development only":

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/insecure.yaml
```

Installing this would totally remove the login screens.

**Comment by floreks** [comment]
> Installing this would totally remove the login screens.

There are currently 2 ways that will allow you to omit/disable the login screen:
1. Provide an authorization header in the request to Dashboard which is usually done by the reverse proxy configured in front of the Dashboard.
2. Do not provide any custom certs and set `auto-generate-certificates` flag to `false`. Also, do not provide `enable-insecure-login` flag. This way the login menu will be completely disabled and you will be automatically redirected to the workloads view. In this case, you need to manually grant Dashboard SA admin access to the cluster.

> There should be a default one shot template which just completely skips all logging in.

I have to disagree. I do understand your use case and how you'd benefit from this however from our point of view it is mandatory to not provide easy access to configurations that are insecure by default. You can always create your own custom deployment yaml and simply bump the version from time to time or use the edit option available in your already deployed dashboard, change the version and hit save.

**Comment by justinmchase** [comment]
In case anyone comes here searching for a way to easily enable skipping I came up with this simple one liner to enable it. The first step is to just install the dashboard per the usual recommended way but then you can run this second command to enable authentication skipping.

> I just want to emphasize, per the general recommendations of the kubernetes team that **_you should not do this in production_**. You should only consider this in local dev or extremely low trust environments, be smart!

```sh
kubectl patch \
  -n kubernetes-dashboard \
  deployment kubernetes-dashboard \
  -p '{"spec": { "template": { "spec": { "containers": [{ "name": "kubernetes-dashboard", "args": ["--auto-generate-certificates", "--namespace=kubernetes-dashboard", "--enable-skip-login" ] }] } } } }'
```
