### ISSUE TITLE
Cards stretch off screen on dashboard version 2.3.0 and higher.

### ISSUE THREAD

**Issue by clavierpaul** [kubernetes/dashboard#6336]
On versions v2.3.0 and v2.3.1 of the dashboard, some cards stretch off the screen rather than being fit to the screen size. Tested on Microsoft Edge v92.0.902.67 and Safari v14.1.1 (16611.2.7.1.4), both on macOS.

##### Environment

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.0/aio/deploy/recommended.yaml
Kubernetes version: v1.21.3
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.3.0, v2.3.1
Operating system: Linux
```

##### Steps to reproduce

1. Install Kubernetes Dashboard via the recommended method.
2. Run `kubectl proxy`
3. Go to http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/ and log in.

##### Observed result

Example where card stretches off screen:

![image](https://user-images.githubusercontent.com/53355311/128780456-4b9611b4-1b14-434e-a7c5-9c33aa8f6066.png)

Example where card is resized correctly:

![image](https://user-images.githubusercontent.com/53355311/128780509-42d5bfe3-93cd-45d8-be0f-a47b94a33cd1.png)

##### Expected result

Version v2.2.0:

![image](https://user-images.githubusercontent.com/53355311/128780634-e5d96d73-f2b0-4b2f-9e28-d454e57ac5b2.png)

**Comment by floreks** [comment]
This change was intentional for some cards as there are currently so many columns that shrinking them further makes the information in the table so condensed that it is much harder to read. That's why on smaller screens you'll now see the horizontal scrollbar.

/close
