### ISSUE TITLE
Material design replication controller list 

### ISSUE THREAD

**Issue by cescoferraro** [kubernetes/dashboard#634]
### should not this
![image](https://cloud.githubusercontent.com/assets/6259987/14415483/06ee989c-ff76-11e5-882b-3ab1563fcd0a.jpg)

### Follow  Google material design rules?

![image](https://cloud.githubusercontent.com/assets/6259987/14415484/06ef87b6-ff76-11e5-958e-ddb3dd0bf879.jpg)

**Comment by bryk** [comment]
We're migrating from the concept of cards :) See and comment our proposal at https://github.com/kubernetes/dashboard/pull/589

**Comment by bryk** [comment]
Should we close this? Or is there something more to discuss?

**Comment by cescoferraro** [comment]
@bryk all right!
