### ISSUE TITLE
Adding statement validation for empty " Namespaces " for Service when try deploy app by yaml file

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#635]
##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: Ubuntu 15.10 4.2.0-34-generic
Node.js version: v0.10.40
Go version: go1.5.1
```
##### Steps to reproduce

I try deploy app by yaml file in which there values "Namespace" are empty for Service and supplemented for Replication Controller (namespace are not exist)
##### Observed result

Message appears: "namespaces "test" not found" but service was created without Replication Controllers.
At the next attempt deploy the same yaml file (only with correct namespace for RC) I see message: "services "testtest" already exists"
##### Expected result

I think in the same situation we should display message:
- Service "name_of_service" was created + already existing message (possibly add information that "Namespace" applies to RC) or
- other message, you have any ideas?

**Comment by kwodzynski** [comment]
BTW I think we should consider the issue of adding capabilities create new namespace during deploying app by yaml/json file (for example beneath "YAML or JSON file" input). Such as option exist when deploy app by form.

**Comment by bryk** [comment]
Yes, I like the idea.

**Comment by digitalfishpond** [comment]
Started working on this

**Comment by floreks** [comment]
Already fixed.
