### ISSUE TITLE
"no endpoints available for service \"https:kubernetes-dashboard:https\""

### ISSUE THREAD

**Issue by danfinn** [kubernetes/dashboard#6352]
##### Environment
kubernetes dashboard was installed via https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml.  When trying to access it I get the following:

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:https\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

This is a dev cluster but it has been functional.  I'm able to deploy apps to it.  I got not errors when using the yaml file above with kubectl apply.  The kurnetes-dashboard pods are running without errors:

```
kubectl get pods -n kubernetes-dashboard
NAME                                         READY   STATUS    RESTARTS   AGE
dashboard-metrics-scraper-856586f554-854sv   1/1     Running   0          6m3s
kubernetes-dashboard-67484c44f6-fm6pk        1/1     Running   0          6m4s
```

```
kubectl logs pods/dashboard-metrics-scraper-856586f554-854sv -n kubernetes-dashboard
{"level":"error","msg":"Error cannot set logtostderr: no such flag -logtostderr","time":"2021-08-12T21:28:55Z"}
{"level":"info","msg":"Kubernetes host: https://100.64.0.1:443","time":"2021-08-12T21:28:55Z"}
{"level":"info","msg":"Namespace(s): []","time":"2021-08-12T21:28:55Z"}
100.108.148.0 - - [12/Aug/2021:21:29:03 +0000] "GET /healthz HTTP/1.1" 200 13 "" "dashboard/v2.3.1"
10.152.80.185 - - [12/Aug/2021:21:29:25 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.21"
100.108.148.0 - - [12/Aug/2021:21:29:33 +0000] "GET /healthz HTTP/1.1" 200 13 "" "dashboard/v2.3.1"
10.152.80.185 - - [12/Aug/2021:21:29:35 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.21"
10.152.80.185 - - [12/Aug/2021:21:29:45 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.21"
10.152.80.185 - - [12/Aug/2021:21:29:55 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.21"
{"level":"error","msg":"Error scraping node metrics: the server could not find the requested resource (get nodes.metrics.k8s.io)","time":"2021-08-12T21:29:56Z"}
```

```
kubectl logs pods/kubernetes-dashboard-67484c44f6-fm6pk -n kubernetes-dashboard
2021/08/12 21:29:03 Starting overwatch
2021/08/12 21:29:03 Using namespace: kubernetes-dashboard
2021/08/12 21:29:03 Using in-cluster config to connect to apiserver
2021/08/12 21:29:03 Using secret token for csrf signing
2021/08/12 21:29:03 Initializing csrf token from kubernetes-dashboard-csrf secret
2021/08/12 21:29:03 Empty token. Generating and storing in a secret kubernetes-dashboard-csrf
2021/08/12 21:29:03 Successful initial request to the apiserver, version: v1.21.3
2021/08/12 21:29:03 Generating JWE encryption key
2021/08/12 21:29:03 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
2021/08/12 21:29:03 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
2021/08/12 21:29:03 Initializing JWE encryption key from synchronized object
2021/08/12 21:29:03 Creating in-cluster Sidecar client
2021/08/12 21:29:03 Auto-generating certificates
2021/08/12 21:29:03 Successful request to sidecar
2021/08/12 21:29:03 Successfully created certificates
2021/08/12 21:29:03 Serving securely on HTTPS port: 8443
```

```
Installation method: kops
Kubernetes version: v1.21.2
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.3.1
```

##### Steps to reproduce
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml

##### Observed result
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:https\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

##### Expected result
The dashboard login page

**Comment by maciaszczykm** [comment]
How exactly are you trying to access the cluster?

**Comment by danfinn** [comment]
Ah, sorry, I think it's working now.  The issue was that I had been using

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

and that says to run kubectl proxy and then access:

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:https/proxy/

which was giving me the error above but I tried the link from the README on this page which uses:

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

and that does seem to work, I'm now getting prompted for a token.  I think I'm all set here and kubernetes maybe needs to update their documentation?

**Comment by floreks** [comment]
Ye, we'll try to update it there. Good that it works.

/close

**Comment by GaTechThomas** [comment]
Identical issue here. Thread saved a lot of continued frustration.

**Comment by DanWahlin** [comment]
Thanks for bringing this up @danfinn. I hit this as well after hearing about it from someone going through one of my Kubernetes courses. Fortunately I found this issue quickly with the updated URL, but I suspect others going through the docs are going to be pretty frustrated (until that link gets updated anyway :-)).

**Comment by internet-diglett** [comment]
Just reaching out to say that I was about to put my head through a wall before I found this. Thank you so much for posting your resolution, @danfinn! You saved my face and the drywall.
