### ISSUE TITLE
Incorrect links in form

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#637]
##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: Ubuntu 15.10 4.2.0-34-generic
Node.js version: v0.10.40
Go version: go1.5.1
```

##### Steps to reproduce
I checked all of link "Learn more" in the form to deploy app. 2 of them are incorrect.
##### Observed result
![zrzut ekranu2](https://cloud.githubusercontent.com/assets/18006407/14426290/4adb3128-ffee-11e5-9197-af7143a26030.png)

1. http://kubernetes.io/v1.1/docs/admin/limitrange/
After click We are moving on page which doesn't exist but fast we are redirecting to correctly page (Error 404 is visible < 1 sec.)

2. http://kubernetes.github.io/docs/docs/design/expansion/
This page doesn't exist and we see 404 error

##### Expected result

1. Correctly link is: http://kubernetes.io/docs/admin/limitrange/
We need to change it

2. At this moment I don't know what is the correctly link, but I'll try to find it

**Comment by kwodzynski** [comment]
Hmmm maybe it: http://kubernetes.io/docs/user-guide/services/#environment-variables
or am I wrong? Can someone check it, please?

**Comment by cheld** [comment]
Yes, links should have no version number. 

@gertipoppel what is the second link?

**Comment by digitalfishpond** [comment]
I've got the second link: https://github.com/kubernetes/kubernetes/blob/master/docs/design/expansion.md
I will make a PR in a few minutes with a fix

**Comment by digitalfishpond** [comment]
I have the second link: http://kubernetes.io/docs/user-guide/configuring-containers/#environment-variables-and-variable-expansion.
I have also noticed that many of our URLs feature 'kubernetes.github.io'. this should be shortened to 'kubernetes.io' (the url actually featured on the pages, I guess the .github version redirects)
I will make a pool request with this fix in a few minutes.

**Comment by cheld** [comment]
Gerti is not in office. 

In this bug doesn't it mention either:
https://github.com/kubernetes/dashboard/issues/276

I think @digitalfishpond is best (not perfect though)

**Comment by bryk** [comment]
Closed?
