### ISSUE TITLE
kubernetes dashboard timing out frequnently

### ISSUE THREAD

**Issue by pradpath8** [kubernetes/dashboard#6378]
kubernetes dashboard is getting timed out after 2-3 minutes with following error:
Http failure response for api/v1/pod/monitoring/kubernetes-dashboard-67cd876c98-sxxzd: 0 Unknown Error 

container configuration is as follows:

 kubernetes-dashboard:
    Image:         kubernetesui/dashboard:v2.2.0
      --namespace=monitoring
      --sidecar-host=http://127.0.0.1:8000
      --enable-insecure-login
      --token-ttl=36000

**Comment by floreks** [comment]
Old version (latest is v2.3.1) and not enough information. If there is such error then there has to be an underlying issue. Most probably related to the cluster configuration or lack of computer resources. Logs should show more information.

Fill out the issue form properly next time as based on such description we basically can't do anything.

/close
