### ISSUE TITLE
Implement basic version of zero state view

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#64]
Based on Ken's designs. We can start with no logic on backend - just show the UI. Then we should agree on when the zero state is triggered and implement the logic.

https://github.com/kubernetes/dashboard/blob/master/designs/11-11-2015/03_welcome%20-%20zero%20state.png

**Comment by bryk** [comment]
CC @floreks

**Comment by floreks** [comment]
I'm working on it. Just some cosmetics left to make it work on different browsers. View itself is done. Which browsers should we support anyway? I believe it should be responsive UI working also on mobile phones, right?

**Comment by bryk** [comment]
Now just think about Chrome and Firefox (this is where our tests run). Later we'll think about what browsers to actually support.

**Comment by bryk** [comment]
Re responsiveness: Does this require much additional work for you?

**Comment by floreks** [comment]
I've briefly checked it on different browsers and mobile phone. It looks good. I will open PR soon.

**Comment by floreks** [comment]
I think this can be closed as PR #72 is merged.
