### ISSUE TITLE
Set 'All namespaces' as the Default namespace

### ISSUE THREAD

**Issue by rmeloca** [kubernetes/dashboard#6406]
##### What would you like to be added

In the global settings is not possible to set 'All namespaces' as the Default namespace.
Also, is not possible to set it to the fallback namespace.

##### Why is this needed

This way it would be easier to quickly check the cluster health at the first glance when opening the dashboard.

**Comment by floreks** [comment]
That's not really possible for fallback namespaces. The whole idea of fallback namespaces is to use this list when user does not have privileges to list namespaces and all namespaces feature does not work without listing.

It would be possible to use it as the default namespace but only if user will have list privileges.

**Comment by os14** [comment]
we need this let's reopen this issue

**Comment by os14** [comment]
> That's not really possible for fallback namespaces. The whole idea of fallback namespaces is to use this list when user does not have privileges to list namespaces and all namespaces feature does not work without listing.
> 
> It would be possible to use it as the default namespace but only if user will have list privileges.

how It would be possible to use it as the default namespace?
