### ISSUE TITLE
403 errors on some resources

### ISSUE THREAD

**Issue by sgrimee** [kubernetes/dashboard#642]
#### Issue details
From the dashboard, clicking View Details on some RC gives back a 403 Unauthorized error, while it works for most others.

##### Environment
```
Dashboard version: 1.0.1 or 1.0.0
Kubernetes version: 1.0.2
Operating system: CoreOS
```

##### Steps to reproduce
1. launch kubectl proxy
2. open http://localhost:8001/ui
3. select a RC and click on the ... symbol, then on 'view details'

##### Observed result
For some RC, it gives a blank page with 403 unaothorized error

The dashboard container logs shows nothing at all
The browser console shows:
```
Request URL:http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/api/v1/replicationcontrollers/bdb-interactive/attachments
Request Method:GET
Status Code:403 Forbidden
Remote Address:127.0.0.1:8001
```
##### Expected result
For some RC, it works as expected and shows a new screen with pods and events.
In that case the dashboard logs show
```
2016/04/12 11:55:01 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 10.2.68.0:37760
2016/04/12 11:55:01 Getting list of all replication controllers in the cluster
2016/04/12 11:55:03 Outcoming response to 10.2.68.0:37760 with 201 status code
```
and the browser console shows no error

**Comment by bryk** [comment]
Hmm... Do you have any custom security/user control configured for your cluster? Maybe you really cannot access some resources?

**Comment by bryk** [comment]
However, I'm nearly sure that this is caused by: https://github.com/kubernetes/kubernetes/issues/21464

Basically, the apiserver proxy rejects all calls that have `run`, `exec`, etc. in the URL... Can you +1 the linked issue or fix it?

**Comment by sgrimee** [comment]
@bryk you are right! This happens only for RC whose name starts with 'attach', and that is one of the strings filtered by [this regex](https://github.com/lavalamp/kubernetes/blame/e68ea9e8d480240ad5bbbb98e0cc83fa51a37c79/pkg/kubectl/proxy_server.go#L38)

Thanks a lot!
