### ISSUE TITLE
Support setting ResourceVerion="0"

### ISSUE THREAD

**Issue by jacky68147527** [kubernetes/dashboard#6430]
When the number of Nodes more than 1000, get pods is very slow, and the traffic of etcd is 300MB/s
![image](https://user-images.githubusercontent.com/6057029/132028146-c1c26c1d-7a53-4bef-9059-e9a9944a0264.png)

After setting ResourceVersion="0",  etcd traffic and apiserver load are down
So I hope dashboard can support setting resourceVersion="0" in ListOptions

**Comment by floreks** [comment]
According to the [documentation](https://v1-18.docs.kubernetes.io/docs/reference/using-api/api-concepts/) sending `resourceVersion="0"` does not guarantee that the returned resources will be at their newest version. We definitely do not want such behavior as it breaks consistency.
![image](https://user-images.githubusercontent.com/2285385/132061902-eb170e51-b823-4d55-943b-ab2515e1813e.png)

This issue has to be handled completely differently and we'd need an API v2 with proper caching to improve this.

/close

**Comment by Xunzhuo** [comment]
@floreks To solve this issue, we can maybe try to get pods from lister in informer, which can both reduce the pressure to apiserver and improve the speed?

**Comment by floreks** [comment]
Yes, we'd like that but this is something that would be part of the new API. I would be too much trouble to rework our current API for this.

**Comment by jacky68147527** [comment]
What a pity ^V^
We hope the dashboard can provide this kind of support.
The increase in the cluster is inevitable at present
If the dashboard cannot support this scenario, the usage scenarios are very limited. the scope of application should be explained in docs
BTW, Is there  schedule for dashboard support support informers?

**Comment by jacky68147527** [comment]
@floreks Somebody submitted an issue supporting inforers, but it was closed.
https://github.com/kubernetes/dashboard/issues/5197

**Comment by floreks** [comment]
Unfortunately, we are occupied with a lot of different things right now and don't have much time to work on the new API. I could only recommend avoiding using `All namespaces`. Single namespace resource viewing should work fine.
