### ISSUE TITLE
unknown error (0) for resources in specific namespaces

### ISSUE THREAD

**Issue by sui77** [kubernetes/dashboard#6431]
I only get this weird error when I use a namespace called `matomo`. Tried on two completely different k8s clusters.

##### Environment

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v...
Kubernetes version: 1.22.1
Dashboard version: kubernetesui/dashboard:v2.3.1
Host Operating system: Centos 8
```

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v...
Kubernetes version: 1.19.6
Dashboard version: kubernetesui/dashboard:v2.2.0
Host Operating system: Ubuntu 20.04
```

##### Steps to reproduce

Create a deployment in a namespace called "matomo". 

    apiVersion: v1
    kind: Namespace
    metadata:
      name: matomo
    
    ---
    
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ubuntu
      namespace: matomo
    spec:
      selector:
        matchLabels:
          run: ubuntu
      replicas: 1
      template:
        metadata:
          labels:
            run: ubuntu
        spec:
          containers:
          - name: ubuntu
            image: ubuntu:focal
            command: [ "sleep", "1000000" ]

- Select that namespace in dashboard => Deployments => Select that deployment  or
- Select that namespace in dashboard => Pods => Select that pod from that deployment

##### Observed result
![image](https://user-images.githubusercontent.com/7593527/132050971-7295b867-c0ee-4b3e-9094-d034e875d58c.png)

##### Expected result
show the details without error

**Comment by floreks** [comment]
`blocked:(other)` is quite obvious 🙂 check your ad blocker and disable it for this page.

**Comment by sui77** [comment]
yeah, now that you say 😁 thanks a lot :)
