### ISSUE TITLE
Ingress view is not working

### ISSUE THREAD

**Issue by wwwlde** [kubernetes/dashboard#6449]
##### Environment

```
Installation method: Helm
Kubernetes version: v1.18.15
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.3.0
Operating system: Ubuntu Server 20.04
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce

N/A

##### Observed result

Everything works well except Ingress views. I get 404 error with text below.

```bash
curl 'https://kubernetes-dashboard.mydomain.com/api/v1/ingress/minecraft?itemsPerPage=10&page=1&sortBy=d,creationTimestamp' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3' ...

**the server could not find the requested resource**
```

![изображение](https://user-images.githubusercontent.com/62915566/132965873-95e9259b-d8f4-4c3b-acdf-798593f87223.png)

![изображение](https://user-images.githubusercontent.com/62915566/132965993-78d15839-8988-4e82-8e43-4f1c390a23d2.png)

Debug logging doesn't show anything useful :-(

##### Expected result

Display Ingress view.

##### Comments

Couldn't find the reason. Please advise in which direction to move. I'm frustrated by this error :-(

**Comment by floreks** [comment]
Check the compatibility matrix and use latest version: https://github.com/kubernetes/dashboard/releases/tag/v2.3.1

/close
