### ISSUE TITLE
BareMetal Kubernetes dashboard setup

### ISSUE THREAD

**Issue by arjunm183** [kubernetes/dashboard#645]
#### Issue details
I want to access kubernetes dashboard for my baremetal kubernetes cluster. I have already setup kubernetes cluster and i am able to view my nodes . I want to view it through dashboard and see how can i deploy applications.
##### Environment

```
Dashboard version: 
Kubernetes version:kubernetes-master-1.2.0-1.2.x86_64
Operating system:SLES 12 SP1
Node.js version:
Go version:
```

**Comment by cheld** [comment]
What exactly is the problem? A bare metal setup is not different to any other setup.

Have you deployed dashboard?

What happens if you access https//<master-ip>/ui?

**Comment by arjunm183** [comment]
Hello,

Thanks for the reply buddy

I have installed installed kubernetes as follows

Master Node:

Kubernetes-master
Kubernetes-client

Client Node:
Kubernetes-node
Kubernetes-client
Services are running and I am able to see the nodes when I use kubectl get nodes

And I don’t have a kubernetes dashboard addon. But however I have downloaded the kubernetes from the kubernetes official repository and it looks like below screenshot.
[cid:image001.jpg@01D1957C.BC106750]

Can you let me know how do I deploy it
Thanks and Regards,
Arjun Murugan

**Comment by maciaszczykm** [comment]
@arjunm183 Image doesn't display.

Regarding installation instructions please take a look at https://github.com/kubernetes/dashboard/blob/master/README.md and let us know if something doesn't work after going through it.

**Comment by arjunm183** [comment]
OK Here we go. This is what was on the image I attached.

hostname:~/kubernetes/cluster # ls
OWNERS     cloudimages        images        kube-util.sh    mesos                test-network.sh            vsphere
README.md  common.sh          juju          kubectl.sh      options.md           test-smoke.sh
addons     gce                kube-down.sh  kubemark        ovirt                ubuntu
aws        get-kube-local.sh  kube-env.sh   lib             rackspace            update-storage-objects.sh
azure      get-kube.sh        kube-push.sh  libvirt-coreos  test-conformance.sh  vagrant
centos     gke                kube-up.sh    log-dump.sh     test-e2e.sh          validate-cluster.sh

hostname:~/kubernetes/cluster # cd addons/
hostname:~/kubernetes/cluster/addons # ls
README.md  cluster-loadbalancing  cluster-monitoring  dashboard  dns  fluentd-elasticsearch  fluentd-gcp  python-image  registry
hostname:~/kubernetes/cluster/addons # cd dashboard/
hostname:~/kubernetes/cluster/addons/dashboard # ls
MAINTAINERS.md  README.md  dashboard-controller.yaml  dashboard-service.yaml

Thanks and Regards,
Arjun Murugan

**Comment by maciaszczykm** [comment]
@arjunm183 Existence of dashboard files doesn't mean, that dashboard is deployed in the cluster. Like it's written in README.md:

>It is likely that Dashboard is already installed on your cluster. To access it navigate in your browser to one of the following URLs: `https://<kubernetes-master>/ui` which redirects to `https://<kubernetes-master>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard`.

>If you find that you’re not able to access the Dashboard you can install and open the latest stable release by running the following commands:

> ```
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
kubectl proxy --port=9090
```

> And then navigate to `http://localhost:9090/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard`

>If it asks password, use `$ kubectl config view` to find it.

**Comment by maciaszczykm** [comment]
@arjunm183 To get all replication controllers from the cluster you can use following command:

```
maciaszczykm@celcius:~$ kubectl get rc --all-namespaces
NAMESPACE   NAME      DESIRED   CURRENT   AGE
default     nginx     3         3         8s
```

And then add dashboard:

```
maciaszczykm@celcius:~$ kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
replicationcontroller "kubernetes-dashboard" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:30072) to serve traffic.

See http://releases.k8s.io/HEAD/docs/user-guide/services-firewalls.md for more details.
service "kubernetes-dashboard" created
maciaszczykm@celcius:~$ kubectl proxy --port=9090
F0413 10:05:06.498175   21243 proxy.go:132] listen tcp 127.0.0.1:9090: bind: address already in use
maciaszczykm@celcius:~$ kubectl get rc --all-namespaces
NAMESPACE     NAME                   DESIRED   CURRENT   AGE
default       nginx                  3         3         3m
kube-system   kubernetes-dashboard   1         1         19s
```

**Comment by arjunm183** [comment]
Hello Marcin,

I agree with you , however I have doubt that when I try to use the kubernetes-dashboard.yaml file it says the line

image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1

where the image is pulled from. Is there a way that I can pull the image to my local registry and create the service then view the dashboard like how you said.

Thanks and Regards,
Arjun Murugan

**Comment by maciaszczykm** [comment]
> I agree with you , however I have doubt that when I try to use the kubernetes-dashboard.yaml file it says the line

> image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1

> where the image is pulled from. Is there a way that I can pull the image to my local registry and create the service then view the dashboard like how you said.

And why do you need it locally? Is it due to some proxy/firewall issues? I'm not sure if we have these images available to download elsewhere. Still you can build them manually from this repository if you really need it.

**Comment by cheld** [comment]
> Is there a way that I can pull the image to my local registry and create the service then view the dashboard like how you said.

`docker save <bla>`

**Comment by arjunm183** [comment]
Thanks for the reply Marcin. Can you let me know how do I “ build them manually from this repository if you really need it”

How do I build it manually from the repository.


Thanks and Regards,
Arjun Murugan

**Comment by maciaszczykm** [comment]
@arjunm183 Could you please tell why do you need to build it on your own?

To build images by yourself you should use gulp tasks from `build/deploy.js`, for example:

```
maciaszczykm@celcius:~/workspace/dashboard$ gulp docker-image:release
[15:09:18] Requiring external module babel-register
[15:09:19] Using gulpfile ~/workspace/dashboard/gulpfile.babel.js
[15:09:19] Starting 'package-backend-source'...
[15:09:19] Starting 'clean-dist'...
[15:09:19] Starting 'angular-templates'...
[15:09:19] Starting 'styles:prod'...
[15:09:19] Finished 'clean-dist' after 114 ms
[15:09:19] Starting 'fonts'...
[15:09:19] Starting 'icons'...
[15:09:19] Starting 'assets'...
[15:09:19] Starting 'docker-file'...
[15:09:19] Finished 'docker-file' after 729 μs
[15:09:19] Finished 'assets' after 22 ms
[15:09:19] Finished 'icons' after 32 ms
[15:09:19] Finished 'fonts' after 58 ms
[15:09:19] Finished 'angular-templates' after 218 ms
[15:09:19] Starting 'scripts:prod'...
[15:09:19] Finished 'styles:prod' after 281 ms
[15:09:19] Finished 'package-backend-source' after 299 ms
[15:09:19] Starting 'backend:prod'...
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /home/maciaszczykm/workspace/dashboard
godep: [WARNING]:	$GOPATH: /home/maciaszczykm/workspace/dashboard/.tmp/backend
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
[15:09:26] Finished 'scripts:prod' after 6.47 s
[15:09:26] Starting 'index:prod'...
[15:09:26] Finished 'index:prod' after 67 ms
[15:09:26] Starting 'build-frontend'...
[15:09:26] Finished 'build-frontend' after 258 ms
[15:09:48] Finished 'backend:prod' after 29 s
[15:09:48] Starting 'build'...
[15:09:48] Finished 'build' after 6.39 μs
[15:09:48] Starting 'docker-image:release'...
Sending build context to Docker daemon 45.41 MB
Step 1 : FROM scratch
 ---> 
Step 2 : MAINTAINER Piotr Bryk <bryk@google.com>
 ---> Running in c499ec16af02
 ---> cf3f2af3470d
Removing intermediate container c499ec16af02
Step 3 : ADD . /
 ---> bcc33598ed45
Removing intermediate container cea2b955dc4b
Step 4 : EXPOSE 9090
 ---> Running in 59b6a510d367
 ---> 46e2421479b2
Removing intermediate container 59b6a510d367
Step 5 : ENTRYPOINT /dashboard --port=9090
 ---> Running in 41ffa8f2fc11
 ---> 5c3d40788ef0
Removing intermediate container 41ffa8f2fc11
Successfully built 5c3d40788ef0
maciaszczykm@celcius:~/workspace/dashboard$ docker images
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kubernetes-dashboard-amd64   v1.0.1              5c3d40788ef0        49 seconds ago      45.39 MB
kube-build                                            build-4b51b674b1    41362f0746c2        2 days ago          1.495 GB
gcr.io/google_samples/gb-frontend                     v4                  e2b3e8542af7        3 days ago          512.2 MB
nginx                                                 latest              eb4a127a1188        9 days ago          182.7 MB
gcr.io/google_containers/debian-iptables-amd64        v2                  45369b4ba650        10 days ago         129.2 MB
<none>                                                <none>              f33198caac8e        2 weeks ago         44.09 MB
busybox                                               latest              47bcc53f74dc        3 weeks ago         1.113 MB
gcr.io/google_containers/kube-cross                   v1.6.0-1            619ffcddd5f4        4 weeks ago         1.389 GB
hello-world                                           latest              690ed74de00f        6 months ago        960 B
gcr.io/google_containers/pause                        2.0                 2b58359142b0        6 months ago        350.2 kB
gcr.io/google_containers/kube-registry-proxy          0.3                 b86ac3f11a0c        7 months ago        151.2 MB
```

**Comment by maciaszczykm** [comment]
It seems, that problem is resolved.

@arjunm183 Let us know if you need any more help.
