### ISSUE TITLE
Head deployment has wrong service definition

### ISSUE THREAD

**Issue by bjakubiak** [kubernetes/dashboard#6462]
##### Environment

```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/head.yaml
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.3.1 HEAD
```

##### Comments
Service kubernetes-dashboard-head tries to reach port 8443: https://github.com/kubernetes/dashboard/blob/master/aio/deploy/head.yaml#L42
But pod listens at port 9090: https://github.com/kubernetes/dashboard/blob/master/aio/deploy/head.yaml#L181 and on plain http

**Comment by floreks** [comment]
Nice catch! Fixed by https://github.com/kubernetes/dashboard/commit/4dd896d5cfeaa691368f12c3a8ccbb260baab9c8

/close
