### ISSUE TITLE
can not download logs file from dashboard

### ISSUE THREAD

**Issue by AlyssaBetty** [kubernetes/dashboard#6473]
when i want to download logs file from dashboard,it seems that the log file cannot be downloaded or is too large to download，it stay on this page all the time.
![图片](https://user-images.githubusercontent.com/84139094/134446691-f67ecf88-2331-4f16-ac75-d1eefddccfbd.png)

what's way can i resolve it and then i can download logs file from dashboard?

**Comment by floreks** [comment]
`Save` button is available once the log file is downloaded from the server to the browser's cache. I have tested it with a bigger log file and could not reproduce this. 
![image](https://user-images.githubusercontent.com/2285385/135997792-c43f71a1-9f58-4c75-9632-65e503fe7e45.png)

Also, you haven't provided any information about your setup and version used.

/close
