### ISSUE TITLE
Bearer token not giving everyone the same access

### ISSUE THREAD

**Issue by aardbol** [kubernetes/dashboard#6496]
##### Environment

```
Installation method: Helm
Kubernetes version: 1.18
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.2.0
Operating system: 
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce

Install version 4.0.3 of the chart.
Set up in readonly mode
Disable skip login and login with bearer token

##### Observed result

I have full access to all components (any browser), colleagues have limited access with the same token (namespaces not visible). Log mentions error with system:anonymous permissions

##### Expected result

Everyone has the same level of access with the same token.

**Comment by floreks** [comment]
Dashboard does not have any control over the access level. Kubernetes API server decides, based on the token what will be available. This is a configuration issue of some sort on your side. We are only a proxy and pass the raw token directly to the API server. We basically work the same as kubectl here.

/close
