### ISSUE TITLE
Error: chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.18.0

### ISSUE THREAD

**Issue by Giancarlo1974** [kubernetes/dashboard#6499]
##### Environment
Rancher 2.5.9
downstream cluster kubernetes: v120.11-rancher1-1
```
Installation method:
Kubernetes version:  v120.11-rancher1-1
Dashboard version (v1.x is not supported. Use v2.0 or later.):  5
```

##### Steps to reproduce
1) install rancher via docker (in node 1)

https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/single-node-docker/

2) Add a downstream cluster kubernetes (existing nodes)

3) in node 2 paste the docker command to install k8s (from step 2)

4) Try to install kubernetes dashboard 5

##### Observed result
The charts return this error:

Wait helm template failed. Error: chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.18.0 Use --debug flag to render out invalid YAML : exit status 1

##### Expected result

chart installed ad 4.03 version

**Comment by floreks** [comment]
Not a bug. New major version is no longer compatible with k8s v1.18 and older.

/close

**Comment by Giancarlo1974** [comment]
Yes it is a bug
I have installed in kubernetes: v120.11-rancher1-1
20 > 19
