### ISSUE TITLE
chart does not understand that I have installed a version of kubernetes >= 19

### ISSUE THREAD

**Issue by Giancarlo1974** [kubernetes/dashboard#6501]
I have already reported this bug, which was closed incorrectly

https://github.com/kubernetes/dashboard/issues/6499

chart does not understand that I have installed 
kubernetes: v120.11-rancher1-1

it incorrectly detects the rancher version as outdated

**Comment by maciaszczykm** [comment]
Well, this is not pure Kubernetes but Rancher custom version of it. There can be many issues with that as this is not supported by us. If it will work then good, but our only target is to support official Kubernetes releases.

With that said, can you provide output of `kubectl version`?

**Comment by Giancarlo1974** [comment]
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by floreks** [comment]
This looks like a rancher issue. Their versioning scheme seems to be incompatible with the helm `kubeVersion` logic check.

Ref: https://github.com/rancher/rancher/issues/30766

/close

**Comment by Shaked** [comment]
Why was this closed? I'm experiencing the same in v2.5.8

**Comment by maciaszczykm** [comment]
@Shaked This is not Rancher repo.
