### ISSUE TITLE
kubernetes-dashboard container uses "kubernetes-dashboard" instead of correct namespace is installed on

### ISSUE THREAD

**Issue by Psycopg6** [kubernetes/dashboard#6534]
Logs:

2021/10/14 19:33:24 Starting overwatch
2021/10/14 19:33:24 Using namespace: **kubernetes-dashboard**
2021/10/14 19:33:24 Using in-cluster config to connect to apiserver
2021/10/14 19:33:24 Using secret token for csrf signing
2021/10/14 19:33:24 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:**kube-dashboard**:kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "**kubernetes-dashboard**"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc00035d9c0)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x413
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc00022bd00)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:502 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc00022bd00)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:470 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:551
main.main()
	/home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:95 +0x21c

Perhaps the image is hard-coded to use the default namespace?

**Comment by floreks** [comment]
Fill out the issue template properly. This does not tell us anything.

/close
