### ISSUE TITLE
Accessing pod logs results in 503 error when logs are large

### ISSUE THREAD

**Issue by yissachar** [kubernetes/dashboard#654]
I have a pod that generates a large amount of logs. I can access it for a short while after it starts, while the logs are not yet so large. However, after a short period of time it seems the logs become too much for the dashboard to handle and I receive the following error:

```
Service Unavailable (503)

Error: 'EOF'
Trying to reach: 'http://10.244.1.5:9090/api/v1/logs/default/mypod-v10-ptul8'
```

I can access the pod logs with `kubectl` with no problems:

`kubectl logs mypod-v10-ptul8`

**Comment by cheld** [comment]
Is this duplicate?

https://github.com/kubernetes/dashboard/issues/351

**Comment by yissachar** [comment]
Looks like it is 👍
