### ISSUE TITLE
Token field login space sanitization issue

### ISSUE THREAD

**Issue by Seanland** [kubernetes/dashboard#6543]
##### Environment

```
Installation method: Deployed via yaml
Kubernetes version: 1.22.2
Dashboard version (v1.x is not supported. Use v2.0 or later.): Dashboard v2.3.1+0.g8d9f8e76c
Operating system: Ubuntu 20.04.3
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
Proceed to Login page. 
Select authentication via token
Type a space character, then any sort of characters after. (Ex. " asdfa", " apples", " 1232") 
Hit enter to Submit

##### Observed result
User is logged in as system:anonymous user and granted access to the GUI.

##### Expected result
Login should be rejected.

##### Comments
Feel free to reach out, or rename if the issue title is not appropriate. 
Thanks, Sean.

**Comment by tcnt** [comment]
Issue was raised earlier in https://github.com/kubernetes/dashboard/issues/2917
Issue was closed without changes
