### ISSUE TITLE
Dashboard v2.4.0 show blank page

### ISSUE THREAD

**Issue by Tendrun101** [kubernetes/dashboard#6563]
##### Environment

```
Installation method: upgrade from v2.0.4 to v2.4.0  (replace image directly)
Kubernetes version: 1.20.10
Dashboard version (v1.x is not supported. Use v2.0 or later.):  v2.4.0  
Operating system:  CentOS Linux release 7.6.1810
Node.js version ('node --version' output): ?
Go version ('go version' output): ?
```

##### Steps to reproduce

replace "kubernetes-dashboard" ds image directly, upgrade from v2.0.4 to v2.4.0

##### Observed result

access dashboard by nodeport svc , it just showed blank page without erro in logs

##### Expected result

The dashboard page can be opened successfully.

##### Comments

It seems there are some problems dashboard v2.4.0. I try dashboard v2.3.1, dahsboard page can be opened successfully

**Comment by floreks** [comment]
Closing as stale. No answer.

/close
