### ISSUE TITLE
dashboard cannot show all namespaces

### ISSUE THREAD

**Issue by fvdcx** [kubernetes/dashboard#657]
##### Environment
```
Dashboard version:   gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1
Kubernetes version:   v1.2.0
Operating system:   ubuntu 14.04

```

After I start kubernetes cluster, dashboard pod is already running by default. And I did not configure dashboard specially.

When I visit `ip:port/ui`, redirecting to `ip:port/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/replicationcontrollers`,but it only shows kube-system namespace pods, I cannot see default namespace pods or all namepaces pods.

I also try to replace `kube-system` to `default` (`default` namespace really exists in my cluster and there are some running pods belonging to `default namespace`) in url  `ip:port/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/replicationcontrollers`, but it doesn't work.

In dashboard [Usage](https://github.com/kubernetes/dashboard#usage), It seems that default path `https://<kubernetes-master>/ui` will redirect to `kube-system` namespace:

> It is likely that Dashboard is already installed on your cluster. To access it navigate in your browser to one of the following URLs: **https://<kubernetes-master>/ui which redirects to https://<kubernetes-master>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard.**

**Comment by ApsOps** [comment]
I believe that url says `kube-system` since dashboard exists in that namespace. That doesn't mean it will only show pods in that namespace.
Are you sure there are other ReplicationControllers or ReplicaSets? what does `kubectl get rc --all-namespaces` say?

**Comment by bryk** [comment]
I'm 100% sure that we show RCs from all namespaces. Maybe you have dangling pods?

**Comment by ApsOps** [comment]
@bryk BTW it doesn't show ReplicaSets (or deployments) yet, right?

**Comment by bryk** [comment]
Correct. ReplicaSets will be show soon.

**Comment by fvdcx** [comment]
In dashboard [Usage](https://github.com/kubernetes/dashboard#usage), It seems that default path `https://<kubernetes-master>/ui` will redirect to `kube-system` namespace:

> It is likely that Dashboard is already installed on your cluster. To access it navigate in your browser to one of the following URLs: **https://<kubernetes-master>/ui which redirects to https://<kubernetes-master>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard.**

@bryk

**Comment by bryk** [comment]
@fvdcx That's correct. The Dashboard UI lives in `kube-system` namespace, but it shows things from *all* namespaces.
