### ISSUE TITLE
Details page for services

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#659]
I'll take care of implementation of details page for services. Generic details page template:

![Design template](https://github.com/kubernetes/dashboard/blob/master/docs/design/mockups/23-03-2016-scale-and-navigation/details-page-template.png?raw=true)

**Comment by bryk** [comment]
All right. Can we discuss concrete proposal? Can you mock it out or prototype? I.e., tell what is going to be displayed in overview pane, what related objects will be there (semantics), etc.

**Comment by maciaszczykm** [comment]
Yes, I can do that. I wanted to start with backend to retrieve services and then iterate.

**Comment by maciaszczykm** [comment]
Frontend done in #726 and #739. Closing.

![image](https://cloud.githubusercontent.com/assets/2823399/15470933/a061aa16-20f3-11e6-902a-fa3ecaeb65f2.png)
