### ISSUE TITLE
Kubernetes Dashboard and Metrics Scrapper on Apple Silicon (Arm64v8) starting AMD64 images

### ISSUE THREAD

**Issue by goafabric** [kubernetes/dashboard#6597]
##### Environment
Kubernetes Dashboard 2.4.0
Apple Silicon M1
Docker Desktop

##### Steps to reproduce
Basically just
docker run kubernetesui/dashboard:v2.4.0

##### Observed result
It will allways pull and start an amd64 image.

##### Expected result
It should run an arm64(v8) image

##### Comments
The Problem can be observed directly in docker, as well inside of kubernetes in docker.
Instead of using an arm64 image, docker will always retrieve the wrong AMD64 image and running in emulation.
Even adding the correct DIGEST/SHA256 does not seem to help.

What I also observed is that the architecture type is "linux/arm64", in constrast for example to postgres
where the type is "linux/arm64/v8" and i think Docker expects the additional v8 .. not an expert here though

**Comment by gmuth** [comment]
check supported architectures:
 
```
% docker manifest inspect kubernetesui/dashboard:v2.4.0|grep arch
            "architecture": "amd64",
            "architecture": "arm",
            "architecture": "arm64",
            "architecture": "ppc64le",
            "architecture": "s390x",
```

pull the image for arm64: 

```
% docker pull --platform inux/arm64 kubernetesui/dashboard:v2.4.0
v2.4.0: Pulling from kubernetesui/dashboard
2f554c6f6f2c: Pull complete 
476e0d029a85: Pull complete 
Digest: sha256:526850ae4ea9aba360e72b6df69fd3126b129d446efe83ac5250282b85f95b7f
Status: Downloaded newer image for kubernetesui/dashboard:v2.4.0
docker.io/kubernetesui/dashboard:v2.4.0
```

verify the platform: 

```
% docker inspect kubernetesui/dashboard:v2.4.0|grep Arch   
        "Architecture": "amd64",
```

I pulled arm64 - so why is it now amd64?
I think the images ARE amd64 images!
It looks like the multiplatform image building process has issues.
For some reason the digests don't correlate as expected. 
Maybe there is something wrong with the manifest.

**Comment by floreks** [comment]
The real question here is if it runs correctly? I have recently tested it on the centos with `aarch` CPU and even though it pulled `amd64` arch image it started without any issues. I wouldn't spend too much time on this investigating if there is no real issue in running the application.

**Comment by maciaszczykm** [comment]
I'll take this issue to check it later. There is a warning currently when using the image on Apple Silicon. I didn't test it yet though.

**Comment by goafabric** [comment]
@floreks wo already have  a similar discussion elswehere with the spring boot paketo people
In case of the kubernetes-dashboard, yes it works ...
During bootstrap Docker on M1 will just patch Qemu into the mix ... and Golang and Java Native Binaries tend to work.
But the performance suffers, .i.e. memory usage is higher and startup time also .. also the possibility of crashes during startup rises .. that's at least what i observed

And as mentionend right at the beginning ... conerning a lot of standard multi arch images (postgres, elastic, whole grafana stack ... etc..) they all just work correct.
So if the dashboard is already multi arch, i would expect that this should be easily fixable by setting the right "trigger" somehwere .. as @gmuth already mentioned, the auto detection seems to fail for whatever reason here ..

**Comment by floreks** [comment]
We might try switching to the `docker buildx` as it is a much newer and easier way of building multiarch images. Currently, we are using the `docker manifest` which is a bit more complex and we might have an issue there.

**Comment by goafabric** [comment]
@floreks 
Dragging in the latest Helm Chart 5.2.0, with Dahsboard 2.5.0
The Dashboard is now correctly ARM.
Thanks for that

But Metrics Scrapper and Server are still the same old version and thus still AMD64.
This is why I named the Ticket "and Metrics Scrapper"

Was this also taken into account ?
I see that these are two different repos on github, but I would have hoped that all of these will be fixed together.
