### ISSUE TITLE
Establish code styles and practices for the project 

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#66]
As the number of contributors to the project grows, we need to establish coding styles and practices so that the codebase stays unified and healthy for long time.

The areas that should be covered include (at least):
* how to create a view (what's the code layout, what to place where)
* what to do on the backend and what on the frontend
* how to communicate with backend
* what is the style of JS code (e.g., formatting, JSDoc annotations, patterns to use)
* what is the style of Go code (should be easy, if we follow gofmt)
* other trivia like: tabs/spaces, line width, comments 

Any other ideas?

**Comment by cheld** [comment]
* Supported form factors
* Supported browsers
* Unit test coverage in backend and UI

**Comment by cheld** [comment]
We could enhance eslint and/or check-in formating rules for WebStorm and Atom. What is your opinion?

**Comment by bryk** [comment]
Check in the rules into the repository? Do you have idea whether this is anything generic or just for WebStrorm?

**Comment by cheld** [comment]
I have never configured eslint myself, but some trivial things could be configured as warnings, e.g. line-width, camelcase, spacing,... These warnings can be shown in editors like webstorm or atom. So, this would be generic. However, my experience with eslint is limited. I cannot judge if it makes sense or not.

**Comment by SebastianM** [comment]
My $0.02:

* How to create a view: I think we should create a "boilerplate" view (that is not visible of course) that can be used to create new views. It should be up to date all the time and should be well documented.
* how to communicate with backend: Yeah, this is really important (especially REST API design). We should document REST API patterns that get used in the project. I think it's also super helpful to document all REST related API with Swagger (like in Kubernetes but with Swagger v2)
* what is the style of JS code:
  * JSDoc
  * ESLint rules (with failing CI builds when rules are violated)
  * AngularJS patterns that make the migration to Angular 2 easy (beta is coming soon)
  * Clang formatted code (with Google style rules), it's also used by the [Angular team](https://github.com/angular/angular/blob/master/.clang-format). There's also a gulp plugin that can do format checking **and formatting** (ESLint plugins have very limited support to fix style errors)
* I think an [.editorconfig](https://github.com/angular/angular/blob/master/.editorconfig) is also a good idea.
* other trivia like: tabs/spaces, line width, comments: should be covered with ESLint and clang.
* Go code:
  * gofmt
  * [golint](https://github.com/golang/lint)
* [Greenkeeper](http://greenkeeper.io/) for NPM packages.
* Supported browsers (and screen resolutions)
  * Documented in the README
  * Tested in CI builds (would be possible with [Saucelabs](https://saucelabs.com/))

Regarding ESLint:
There a ESLint plugins for all common editors/IDEs that use the existing ESLint configuration of the project root folder. They show up errors in the editor so the developer can fix them faster. So IMO there's nothing todo in this regard.

**Comment by SebastianM** [comment]
Missed one thing:

* [Conventional changelogs](https://github.com/ajoslin/conventional-changelog) with [angular style commits](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md) (and no "merge pull request from ..." commits). So we could generate a clean `CHANGELOG.md` and tag releases properly.

**Comment by SebastianM** [comment]
And last but no least:
* Use of Github labels for PR and issues (with categories like type, component, etc.)

**Comment by bryk** [comment]
Another thing that I've stumbled upon:
* how to use JSDoc `@type` annotations and ES6 modules: when to use relative paths, when absolute

**Comment by bryk** [comment]
Thank you all for your input. The plan is to wait a few days for people to list their ideas here and go through the list next week to settle on the standards.

**Comment by taimir** [comment]
In general automation seems better than documentation. It would be nice to have some kind of automatic check or correction of common flaws in pull requests, like line wraps, spacing or empty line at end of file. 

I have tried clang-format a bit and run it on the existing code. Default Google formatting is fine in most cases. Some rules might require some tweaking. It can be installed as an npm package. A plugin exists for Atom, but probably not for WebStorm, though. Maybe it would make sense to add clang-formatting as a git commit hook?

I've also noticed that in the file build/check.js the "lint" function does not yet include "golint". I could probably bind a "golint" call to it, but I've noticed that on the github page (https://github.com/golang/lint) the authors strongly advice against integration into the build process:


> In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced
> automatically, for example as part of a build process. 

Thoughts on this?

**Comment by bryk** [comment]
>In general automation seems better than documentation. It would be nice to have some kind of automatic check or correction of common flaws in pull requests, like line wraps, spacing or empty line at end of file.

Yes. I think every style check that be automated, will be automated. This is particularly true for line wraps or spacing. Things that cannot be automated will land in a style guide. 

> > In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced
> > automatically, for example as part of a build process.

> Thoughts on this?

If the creators of the tool say so... However, there's gofmt (and govet) which many go projects use. It is good enough, in my opinion.

>I could probably bind a "golint" call to it
How about checking whether gofmt changes something in a file? And fail if yes.

**Comment by bryk** [comment]
I think the wish list has stabilized, so we should be moving forward with this.

I've already done some tasks mentioned here that are no brainers. I.e., I enforced clang-format for the project and added as much as possible eslint rule enforcements. 

Anyone interested in taking specific areas mentioned here? If not, I'll spin off separate issues to discuss and assign them.

**Comment by maciaszczykm** [comment]
@bryk I think it can be closed. We can do further updates of build tools via new issues and pull requests. Do you agree?

**Comment by bryk** [comment]
Yes, close.
