### ISSUE TITLE
Backspace in the shell behaves weirdly

### ISSUE THREAD

**Issue by bmgdc** [kubernetes/dashboard#6602]
##### Environment

```
Installation method: `snap`
Kubernetes version: Client is `1.22.3`. Server is `1.19.13-gke.1900`.
Dashboard version (v1.x is not supported. Use v2.0 or later.): N.D.
Operating system: `Ubuntu 20.04.3 LTS`
Node.js version ('node --version' output): N.D.
Go version ('go version' output): N.D.
```

##### Steps to reproduce

1. Connect to a pod with `kubectl -n <some_kind_of_paramenter> exec -it <pod> -- bash`
2. In the resulting Bash shell, type something in the propmt.
3. Delete a character with <kbd>Backspace</kbd>

##### Observed result

The cursor moves to the right instead of the left and the character is still seen in the prompt. *However*, it is actually deleted, I just don't see it.

##### Expected result

I expected the typical behavior.

##### Comments

It seems to me like this is the same issue as [this](https://github.com/kubernetes/dashboard/issues/2346). Other keys don't work properly either, for example, the directional keys.

I tried multiple values for the environment variable `TERM`, including the same as in my local terminal. This didn't fix it.

**Comment by floreks** [comment]
It will depend on your container, how it is set and what kind of shell it has available for access. You can try for example a busybox container to compare the behavior.

> Dashboard version (v1.x is not supported. Use v2.0 or later.): N.D.

Without this information, there is literally nothing we can do.

**Comment by bmgdc** [comment]
> It will depend on your container, how it is set and what kind of shell it has available for access. You can try for example a busybox container to compare the behavior.
> 
> > Dashboard version (v1.x is not supported. Use v2.0 or later.): N.D.
> 
> Without this information, there is literally nothing we can do.

Sorry, I really don't know the technology I'm trying to give the relevant information. As I understand it, I don't have the dashboard app. How would I get its version to include up to? What other information can I give you and how?

**Comment by floreks** [comment]
If you are using `kubectl` only then this is not our issue. This is a repository of `Kubernetes Dashboard`, not `kubectl`. You should try and create an issue in their repo.

/close
