### ISSUE TITLE
RC details page loads slowly when there are a lot of events

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#662]
##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: linux/amd64
Node.js version: v0.10.40
Go version: go1.4.2
```

##### Steps to reproduce
I had generated a large number of events in short period time

##### Observed result
Load time RC detail page is very long (for 10000 events time load is over 60 s), more then 10000 events crashes script. Moreover I've seen that command "kubectl get events ..." displaying all of events (node and pods) but in Dashboard we may see only events for pods.

##### Comments
I think we should do pagination for Events page. This should solve the problem.
IMHO it is not our fault that script in browser was crashed.
I don't know we should displaying all of events (like a "kubectl...") what are your opinions?

**Comment by maciaszczykm** [comment]
> I don't know we should displaying all of events (like a "kubectl...") what are your opinions?

For replication controllers we are loading events connected to them and to their pods, nodes are skipped. 

@kubernetes/dashboard-maintainers Do you think that we need to load events connected to nodes? At the moment I'm not even sure how this should be done, but it seems, that `kubectl get events` offers that functionality. 

> I think we should do pagination for Events page. This should solve the problem.
IMHO it is not our fault that script in browser was crashed.

Yes, we already have an issue for that. Take a look at #351.

**Comment by bryk** [comment]
> @kubernetes/dashboard-maintainers Do you think that we need to load events connected to nodes?

I think not. For RCs show Pod and RC events. What do you think?

**Comment by maciaszczykm** [comment]
@bryk I agree, then we can close this issue and work on pagination it #351.

**Comment by cheld** [comment]
@maciaszczykm 
If we have a node-details view sometime in the future then I think this view should also show the node events, right? But this is not relevant right now. 

@kwodzynski 
About the numbers. 10.000 events seem a lot to me.  Does anyone know what is realistic? When are events created exactly? How long does events exist in the system?

Can we define some meaningful scenario? e.g. one RC with 10 pods. The RC is scaled down every night to 5 pods and scaled up every morning to 10 pods. How many events do we have after 30 days?

What is a scenario for 10000 events? So we can understand the severity?

About 60 seconds. I think 5 seconds is already an extremely long loading time for a web page. You basically can stop measuring at this point. Maybe you do an addition measurement if we are curious.

 #351 was just a guess. Before we start implementing pagination we should judge if it is needed (and how urgent it is). From the given numbers I could not do so. 

Could you please do more investigation and improve the bug description?

**Comment by cheld** [comment]
@kwodzynski please reopen if you have meaningful results
