### ISSUE TITLE
Support Showing Installed Helm Charts

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#6621]
What if the Kubernetes Dashboard had a new item in the left sidebar which would show all the installed `Helm Charts` in a specific namespace. Something similar to `helm list` ?

By clicking on the installed name, a secondary screen could show every single resource installed by the `helm chart` (very similar to the search page)

I may be able to help implement it, assuming this feature is considered relevant.

**Comment by floreks** [comment]
I don't think we want to have any hard dependencies on the external tools that are not part of the core Kubernetes. It would be something that the plugins could handle, but there are currently some issues with them. We'd have to first fix the plugins feature.
