### ISSUE TITLE
Configurable ingress annotation prefix in Helm Chart

### ISSUE THREAD

**Issue by hoepfnerj** [kubernetes/dashboard#6626]
##### What would you like to be added
The Helm-Chart currently uses the hard coded annotation `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` in [templates/ingress.yaml](https://github.com/kubernetes/dashboard/blob/a45339437acbd61bf960b99af3b43660f030306e/aio/deploy/helm-chart/kubernetes-dashboard/templates/ingress.yaml#L32) when the value [protocolHttp](https://github.com/kubernetes/dashboard/blob/870b0696383ffdaad3df352cc8dd641d9f73cd16/aio/deploy/helm-chart/kubernetes-dashboard/values.yaml#L105) is false (default). When using a custom annotation prefix, the chart is not deployable:
```
Error: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: This deployment has a custom annotation prefix defined. Use 'ingress.kubernetes.io' instead of 'nginx.ingress.kubernetes.io'
```
It would be helpful, if the annotation prefix is configurable.

##### Why is this needed
This makes the chart more flexible.

##### Comments
I can create a pull request if needed.

**Comment by pierluigilenoci** [comment]
@hoepfnerj I suggest opening a PR for this.

**Comment by pierluigilenoci** [comment]
@hoepfnerj I suggest opening a PR for this.

**Comment by webcoderz** [comment]
Would this solve this? : https://github.com/kubernetes/dashboard/issues/5017 if so then that's a great feature

**Comment by floreks** [comment]
Closing as it is possible now to provide custom ingress annotations

/close
