### ISSUE TITLE
How can we collect metrics of Kube-dashboard usage?

### ISSUE THREAD

**Issue by sana-jawad** [kubernetes/dashboard#6633]
Is there a proposed way to get the usage numbers of a deployed Kube-dashboard on a cluster?
We basically want to track:

1. Total number of requests received.
2. Number of Successful requests
3. Latency of requests by customers.

**Comment by sana-jawad** [comment]
Gentle reminder to please take a look at this issue.

**Comment by floreks** [comment]
There is no way to track any kind of usage metrics. Dashboard does not offer such functionality.
