### ISSUE TITLE
The dashboard's Service disappears on k8s-1.1.7 due to kube-addons.sh

### ISSUE THREAD

**Issue by romanek-adam** [kubernetes/dashboard#665]
#### Issue details
I followed the instructions from the README, i.e.:
```
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```
and managed to open the dashboard.

After a few minutes the dashboard became inaccessible.

It turned out the dashboard's k8s Service disappeared from the cluster.

I searched all the logs and found out that it's kube-addons.sh fault. Here's what I found in `/var/log/syslog`:
```
Apr 21 06:04:37 ip-172-21-1-9 kube-addons.sh[3886]: INFO: Stopping Service kube-system/kubernetes-dashboard
Apr 21 06:04:37 ip-172-21-1-9 kube-addons.sh[3886]: service "kubernetes-dashboard" deleted
Apr 21 06:04:37 ip-172-21-1-9 kube-addons.sh[3886]: INFO: == Kubernetes addon update completed successfully at 2016-04-21T06:04:37+0000 ==
```

While I understand that it's not the dashboard's fault that it disappeared I was surprised it disappeared after I had followed the installation instructions from the README.

##### Environment
I created the dashboard as described in the README:
```
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```

```
Dashboard version: v1.0.1
Kubernetes version: v1.1.7
Operating system: Ubuntu 15.04
Node.js version: ?
Go version: ?
```

**Comment by bryk** [comment]
Yeah. As a quick remedy, you can change the namespace in `kubectl create -f`

**Comment by aabed** [comment]
Try to split kubernetes-dashboard.yaml into

dashboard-service.yml and dashboard-controller.yml
And place them under /etc/kubernetes/addons/dashboard
