### ISSUE TITLE
the server could not find the requested resource (get ingresses.extensions)

### ISSUE THREAD

**Issue by dmanbu** [kubernetes/dashboard#6650]
##### Environment
```
Installation method: kubectl apply -f https://raw.githubusercontent.com/kubernetes/kubernetes/v1.22.4/cluster/addons/dashboard/dashboard.yaml
Kubernetes version: 1.22.4
Dashboard version (v1.x is not supported. Use v2.0 or later.): kubernetesui/dashboard:v2.0.1
Operating system: CentOS 7.9.2009
Ingress version: 1.1.0
```

##### Steps to reproduce
* Browser access: https://[kube-apiserver-ip-address]:8443/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/ 

##### Observed result
I get an error when logging in to the dashboard:

![20211205103105](https://user-images.githubusercontent.com/10231091/144731227-8088cb97-67f4-4583-99a9-591a92cc5f78.png)

##### Expected result

ingress 1.1.0 : 
I try to query Resources:  
$ kubectl describe role ingress-nginx -n ingress-nginx
```
Name:         ingress-nginx
Labels:       app.kubernetes.io/component=controller
              app.kubernetes.io/instance=ingress-nginx
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=ingress-nginx
              app.kubernetes.io/version=1.1.0
              helm.sh/chart=ingress-nginx-4.0.10
Annotations:  <none>
PolicyRule:
  Resources                           Non-Resource URLs  Resource Names               Verbs
  ---------                           -----------------  --------------               -----
  events                              []                 []                           [create patch]
  configmaps                          []                 []                           [get list watch create]
  endpoints                           []                 []                           [get list watch]
  pods                                []                 []                           [get list watch]
  secrets                             []                 []                           [get list watch]
  services                            []                 []                           [get list watch]
  ingressclasses.networking.k8s.io    []                 []                           [get list watch]
  ingresses.networking.k8s.io         []                 []                           [get list watch]
  configmaps                          []                 [ingress-controller-leader]  [get update]
  namespaces                          []                 []                           [get]
  ingresses.networking.k8s.io/status  []                 []                           [update]
```

$ kubectl api-resources -o wide  | grep ingresses
```
ingresses                         ing          networking.k8s.io/v1                   true         Ingress                          [create delete deletecollection get list patch update watch]
```

ingress 0.43.0 : 
$ kubectl api-resources -o wide  | grep ingresses
```
ingresses                         ing          extensions                     true         Ingress                          [create delete deletecollection get list patch update watch]
ingresses                         ing          networking.k8s.io              true         Ingress                          [create delete deletecollection get list patch update watch]
```

ingress 1.1.0 not find ingresses.extensions

I checked the deploy.yaml of ingress v1.1.0, the apiGroups: extensions was not found
And extensions exist in ingress 0.43.0

ingress 1.1.0 deploy.yaml: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/baremetal/deploy.yaml

ingress 0.43.0 deploy.yaml: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/baremetal/deploy.yaml

##### Comments
The api-resources of ingress 1.1.0 has no ingresses.extensions, but the dashboard is still using ingresses.extensions

**Comment by floreks** [comment]
Fill out the issue form correctly. We need more information.

**Comment by dmanbu** [comment]
> Fill out the issue form correctly. We need more information.

I have updated this issue
I am not sure what more information is needed

**Comment by floreks** [comment]
When you create a new issue there is a template that requires you to provide i.e. dashboard/k8s version, OS, etc. It seems that you have removed it.

The most improtant for us is always K8S and Dashboard version to see if you are using compatible and supported version.

**Comment by dmanbu** [comment]
> When you create a new issue there is a template that requires you to provide i.e. dashboard/k8s version, OS, etc. It seems that you have removed it.
> 
> The most improtant for us is always K8S and Dashboard version to see if you are using compatible and supported version.

I have updated this issue
Hope it helps you, thanks

**Comment by floreks** [comment]
You are using incompatible K8S/Dashboard versions. There is compatibility matrix for every release on our releases page: https://github.com/kubernetes/dashboard/releases

/close

**Comment by eddietisma** [comment]
I arrived here with the same issue due to compatibility. I think that a warning/notification message about incompatible versions would be nice!

**Comment by floreks** [comment]
This is out of scope for us. It's on the user to use compatible version. It would be too much effort to add and maintain such feature.

**Comment by vndark** [comment]
Installation of kubernetes-dashboard in EKS cluster on AWS using documentation with eks-admin role binding results in 404 error message. I thing it doesn't support nginx or has an issue with cluster role binding in version v2.0.5.
So you can edit deployment and change dashboard version to v2.5.0 or v2.5.1 without change any other configuration.

**kubectl edit -n kubernetes-dashboard deployment kubernetes-dashboard**
