### ISSUE TITLE
Global Settings do not appear to save from UI

### ISSUE THREAD

**Issue by tjchambers** [kubernetes/dashboard#6665]
##### Environment
Using Google Chrome

```
Installation method: From DigitalOcean
Kubernetes version: v1.21.5
Dashboard version v2.0.3+0.g665b4d367
Operating system:Ubuntu 20.04
```

##### Steps to reproduce
- Go to DO Kubernetes Dashboard
- Click Settings on left pane
- Under Global Settings see cluster name with placeholder of "Cluster Name"
- Enter Cluster Name = Staging
- Save button becomes enabled - Click "Save"
- Screen refreshes with original default info. 
-
##### Observed result
- Screen refreshes with original default info. Cluster name is "Cluster name" placeholder.

##### Expected result
Cluster name should be set to "Staging"

##### Comments
Appears that all other items under Global Settings also do not save. Changing any settings and clicking Save returns them to the original value. 
Also noted that if these are to be saved to "kubernetes-dashboard-settings" ConfgMap that does not change.

**Comment by floreks** [comment]
Check compatibility matrix on releases page. v2.0.3 definitely does not support K8S 1.21. We also do not provide support for outdated Dashboard versions.

/close
