### ISSUE TITLE
Helm repository 404

### ISSUE THREAD

**Issue by TonySma** [kubernetes/dashboard#6669]
Hi

I just trying to install the dashboard following these instructions: 
https://github.com/kubernetes/dashboard/tree/master/aio/deploy/helm-chart/kubernetes-dashboard#installing-the-chart
but the helm repository is 404 here: https://kubernetes.github.io/dashboard/

Maybe there is a new url or a mirror available ? 
Thanks for your help,
Tony

**Comment by tcassaert** [comment]
How did you solve this? Did you find a mirror?

**Comment by floreks** [comment]
Possibly, just followed the main page README: https://github.com/kubernetes/dashboard#install
