### ISSUE TITLE
Cant view workloads in one namespace, Secrets, Service work - All other NS's Work on all resources

### ISSUE THREAD

**Issue by ssurovich** [kubernetes/dashboard#6671]
I thought this may be a potential bug since I have the issue in multiple versions of the Dashboard.

##### Environment

Installation method:  Deployment
Kubernetes version: 1.18.13
Dashboard version (v1.x is not supported. Use v2.0 or later.):  Tried 2.0.3 and 2.4.0 - Same Issue
Operating system: Ubuntu 18.04

##### Steps to reproduce
Im unsure - I cant seem to pinpoint the issue, and its only a single namespace with the issue.

##### Observed result
What I am seeing in a multi-tenant cluster with around 70 namespaces is that one namespace cannot view anything under workloads.  I can view secrets and services in the namespace in the Dashboard, but clicking on Workloads says there is nothing to display, although there are 2 deployments and a few pods in the namespace.  If I click on any resource that is empty, no issues - it says nothing to display here.  If I click on deployments, replica sets or pods, dashboard will hang forever until it finally times out.

The logs for the dashboard do not show anything odd when this is happening - it shows all 200's in an endless loop for the requested resource.

##### Expected result
To see the deployments, pods, and replica sets for that namespace.

Any ideas or anything I can look at to offer additional information?   Its a really odd issue since its only impacting one single namespace. 

Thanks!

**Comment by floreks** [comment]
You are using pretty outdated K8S that we do not support anymore. One thing that comes to my mind is that some resources created in this namespace were created using the old API as base version, i.e. extensions/v1beta1 and we are using i.e. extensions/v1 client to list them.

For sure we can't guarantee that new releases will be working with your K8S version. We provide support only according to our compatibility matrix for the latest release. If issue would persist there, we could investigate 

/close

**Comment by ssurovich** [comment]
Yeah, I was thinking the same on the version - Ill come back around if it persists after the cluster is upgraded.
