### ISSUE TITLE
Can the backend code supports timeout context

### ISSUE THREAD

**Issue by jacky68147527** [kubernetes/dashboard#6675]
What would you like to be added

We have used dashboard backend code to query the resources of kubernetes, but when the apiserver is busy and the caller makes multiple requests, the backlog of requests will increase and the load of the apiserver will be higher, and eventually stop responding. We hope that dashboard can supports timeout context to cancel request after the timeout, thank you~

**Comment by floreks** [comment]
Our API is specifically designed for our UI. We do not provide support for it nor work on features that are related to it being used in a third party applications. You can always fork and adjust it on your own if needed.

/close
