### ISSUE TITLE
Repackaging of go code

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#668]
I think we should repackage our backend code, this includes putting `.go` files into subdirectories. Soon we'll have a lot more of them and it could get hard to maintain.

**Comment by bryk** [comment]
Yeah, I agree. We need structure there. 

Do you have any proposal for this?

**Comment by maciaszczykm** [comment]
I'll come back with proposal after finishing initial services backend.

**Comment by floreks** [comment]
I've prepared some proposal. 

```
- resources
  |
   - rc
   - service
   - secret
   - event
   - ...
- resourcescommon - ( functions usable by all other resources f.e. getPodsEvents )
  |
   - eventscommon
   - servicescommon
   - ...
- handlers
  |
   - apihandler
   - confighandler
   - ...
- clients
  |
   - apiserverclient
   - heapsterclient
   - ...
- validation
  |
   - validateprotocol
   - validateappname
   - ...
- dashboard.go
```

I'm not sure what to do with `resourcechannels`. Example packages: `common`, `components`, `util

What do you think?

**Comment by maciaszczykm** [comment]
@floreks It matches my current changes. After I'll update all imports and resolve all conflicts I'll create a pull request with it.

**Comment by bryk** [comment]
LGTM :) Awesome, thanks for taking care of this.
