### ISSUE TITLE
[BUG] ReplicaSet Error when deploying dashboard from helmchart

### ISSUE THREAD

**Issue by janlauber** [kubernetes/dashboard#6685]
##### Environment
Production Kubernetes Cluster staged with RKE2

```
Installation method:
Kubernetes version: 1.22.5
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.4.0
Operating system: Ubuntu 20.04.3 (each K8S node)
```

##### Steps to reproduce
Just deploy the current helm chart version (5.0.5 on Artifacthub) or the 5.1.0 Version in the source code. The result will be the same. There will be no pods created via the deployment. (vanilla, no values provided)

##### Observed result
Pod cannot be deployed. When describing the replicaset you can see the following error message:
```
message: 'pods "kubernetes-dashboard-local-699c8b95fc-" is forbidden: PodSecurityPolicy:
      unable to admit pod: [pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]:
      Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/kubernetes-dashboard]:
      Forbidden: seccomp may not be set]'
```
##### Expected result
Deployment should complete and there should be one running pod.

##### Comments
I tried to fix this locally and it works for me now. I will create and link a PR which you can check out.

**Comment by floreks** [comment]
Not an issue on our side. Explained in https://github.com/kubernetes/dashboard/pull/6686#issuecomment-1011089997

/close
