### ISSUE TITLE
Dashboard Not Allowing Sign In Via HTTP

### ISSUE THREAD

**Issue by ThePieMonster** [kubernetes/dashboard#6693]
##### Environment
```
Installation method: CLI
Kubernetes version: 1.23
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.4
Operating system: Ubuntu 20.04
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce
Attempt to login to Kubernetes Dashboard using the single MicroK8S nodes IP address and node port.

YAML for dashboard config
https://pastebin.com/raw/qsjmuQ2Z

https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md

Worth looking at line 187 in YAML config:

>           args:
>             - --namespace=kubernetes-dashboard
>             - --enable-insecure-login=true
>             - --insecure-port=9090
>             - --insecure-bind-address=0.0.0.0

http://10.1.50.101:30051/#/login

##### Observed result
Dashboard displays error on login.
Error: Insecure access detected. Sign in will not be available. Access Dashboard securely over HTTPS or using localhost. Read more here .
![image](https://user-images.githubusercontent.com/11359134/149862933-c27b0008-2e00-4065-bc20-3f6f3215a8ff.png)

##### Expected result
Kubernetes Dashboard loads and allows login via HTTP

**Comment by floreks** [comment]
From our arguments [docs](https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md):
enable-insecure-login | false | When enabled, Dashboard login view will also be shown when Dashboard is not served over HTTPS.
-- | -- | --

From the [link](https://github.com/kubernetes/dashboard/tree/master/docs/user/accessing-dashboard#login-not-available) available at the end of the error message:

> If your login view displays below error, this means that you are trying to log in over HTTP and it has been disabled for the security reasons.
>
> Logging in is available only if URL used to access Dashboard starts with:
>
> http://localhost/...
> http://127.0.0.1/...
> https://<domain_name>/...

It works as expected and mentioned argument is only to enable the login mechanism when accessing Dashboard over `localhost` or `127.0.0.1` when the `HTTP` protocol is used.

/close

**Comment by ThePieMonster** [comment]
@floreks Can we get a feature request for allowing login over HTTP when using another computer to contact the dashboard?
Also, one needs HTTP if they want to use a proxy server infront of the K8S node. 
I have a IIS setup as a proxy which sends the requests to a Micro K8S node running the dashboard. This does not work if HTTPS is enabled on the K8S dashboard however.

**Comment by floreks** [comment]
Since this is a security issue, we will not be providing such a feature. You can use `kubectl proxy` or configure a reverse proxy with the HTTPS so that in the end Dashboard will be accessible over HTTPS even though it will be served internally over HTTP. This way frontend will allow logging in.

**Comment by ThePieMonster** [comment]
@floreks 
> Since this is a security issue, we will not be providing such a feature. You can use `kubectl proxy` or configure a reverse proxy with the HTTPS so that in the end Dashboard will be accessible over HTTPS even though it will be served internally over HTTP. This way frontend will allow logging in.

Can you take a look at the following:
https://pastebin.com/nszYVEaC
> args for kind: Deployment
Line: 197

> Kind: Service
Line 32 - 46

In the Service, you can see that I have a node port setup on 30051. This allows a different computer to contact the K8S node via its IP-Address:30051 and get the dashboard. I believe this is doing something similar to kubectl proxy? Having the site available to just localhost users is pointless as there are no localhost users on the K8S node. Is there some other way that the dashboard should be made accessible?

**Comment by floreks** [comment]
There are plenty of options. Using Kubernetes Ingress or some kind of reverse proxy in front of Dashboard is how you'd normally expose in-cluster application. The only requirement is that in the end, you'll access it using HTTPS. HTTP is restricted to localhost, not HTTPS.

**Comment by ThePieMonster** [comment]
@floreks I have tried many different solutions over the past week but none have worked. See the below thread to get details on the issue.
https://community.spiceworks.com/topic/2345274-allow-self-signed-certificate-iis-10-windows-server

The TLDR is, you need HTTP if you want to proxy to the K8S dashboard. HTTPS will not work and there is no working models of it either.

**Comment by ZhenlanJi** [comment]
Try to do a port-forward, like this:
` kubectl port-forward -n kubernetes-dashboard service/kubernetes-dashboard <any port number>:443 --address 0.0.0.0`
