### ISSUE TITLE
text is missing identation in the log view after upgrade to 2.4.0

### ISSUE THREAD

**Issue by ViliusS** [kubernetes/dashboard#6696]
##### Environment

```
Installation method: alternative.yaml
Kubernetes version: 1.21.8
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.4.0
Operating system: Rocky Linux 8.5
```

##### Steps to reproduce

1. Install or upgrade to 2.4.0.
2. Go to any of the applications which log data with spaces before text, like structured JSON array output.

##### Observed result

Log text is completely left aligned and missing indentation.

##### Expected result

The log text should be idented.

##### Comments

I have confirmed that log text spaces actually exist in HTML code, it's probably an issue in CSS which messes alignment.

**Comment by ViliusS** [comment]
[screenshot](https://pasteboard.co/ZQ4exhhe96Tc.png)

**Comment by floreks** [comment]
It would be great if you could provide a test deployment YAML that would output the wrongly formatted logs.

**Comment by ViliusS** [comment]
Here you go:
<pre>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-test
  namespace: default
  labels:
    app: log-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-test
  template:
    metadata:
      labels:
        app: log-test
    spec:
      containers:
      - image: mariuzm/test-log_amd:latest
        name: log-test
        ports:
        - containerPort: 4000
</pre>

You should see JSON array output in the logs which should be properly indended.
