### ISSUE TITLE
Display more logs in the dashboard UI

### ISSUE THREAD

**Issue by Manu10744** [kubernetes/dashboard#6700]
##### What would you like to be added
I noticed that only very few logs are displayed when i check the logs of a pod. The amount of logs displayed is very disappointing to me. it is approximately .... 50 lines?
Why not add a possibility to configure the amount of logs that are displayed in the UI? Or the possibility to select a time interval and set some default, like last 2 hours or something?
 
##### Why is this needed
If an exception occurs, it messes it all up and the log view in the dashboard UI is pretty much useless then. To see whats going on i would have to download the log file or use a shell and take a look with `kubectl`. Downloading lots of files is not really a desirable state imo, when you could just display more logs. Why not, i guess?
The same happens when i just want to check what happened, for example, a day ago.

**Comment by floreks** [comment]
I see 2 features here:
- allow configuring a number of log lines per view
- add an option to select a starting timestamp for the logs

The first one should be fairly simple however, we would have to add some sane max number for the log lines per view not to overload the API too much.

The second one would be a bit more difficult as we would need to offer a range of valid timestamps to choose from. Probably we would need a new endpoint to handle this.

Both features feel quite useful to me. We will take a look.

**Comment by glendsoza** [comment]
Hi, I have tried to implement  

> allow configuring a number of log lines per view

in this PR https://github.com/kubernetes/dashboard/pull/6741/files

Currently, I made the number of logs to be configurable as 100,200,500 and max 1000

This is how the UI looks like
![logs_screen_1](https://user-images.githubusercontent.com/95934259/151703824-22592284-31be-4d50-a74d-28f504cfab19.png)
![logs_screen_2](https://user-images.githubusercontent.com/95934259/151703826-ed71d6ea-e916-4a45-93f5-5afaacc27e42.png)

Any review and feedback would be appreciated!

**Comment by ctigrisht** [comment]
bump

**Comment by oingooing** [comment]
is this merged?

**Comment by Manu10744** [comment]
@oingooing As far as I know its not, because apparently there is a lack of people willing to implement this feature...
