### ISSUE TITLE
can't visit kubernetes-dashboard

### ISSUE THREAD

**Issue by luguangzhen** [kubernetes/dashboard#672]
After deploy kubernetes ui follow the guide http://kubernetes.io/docs/getting-started-guides/ubuntu/, and visit http://10.136.97.229:8080/ui, it responses below
Error: 'dial tcp 172.16.40.2:9090: i/o timeout'
Trying to reach: 'http://172.16.40.2:9090/'

Any suggestions would be welcome!
Thanks~

lgzh@ubuntu:~/k8s/kubernetes-master/cluster/addons/dashboard$ kubectl get pods --namespace=kube-system
NAME                                READY     STATUS    RESTARTS   AGE
kube-dns-v11-ws06k                  4/4       Running   0          5h
kubernetes-dashboard-bhs7e          1/1       Running   0          2h
kubernetes-dashboard-v1.0.1-4k6vl   1/1       Running   0          5h

lgzh@ubuntu:~/k8s/kubernetes-master/cluster/addons/dashboard$ kubectl get services --all-namespaces
NAMESPACE     NAME                   CLUSTER_IP     EXTERNAL_IP   PORT(S)         SELECTOR                       AGE
default       kubernetes             192.168.3.1    <none>        443/TCP         <none>                         5h
kube-system   kube-dns               192.168.3.10   <none>        53/UDP,53/TCP   k8s-app=kube-dns               5h
kube-system   kubernetes-dashboard   192.168.3.34   <none>        80/TCP          k8s-app=kubernetes-dashboard   5h

**Comment by ZhuPeng** [comment]
You must make sure your dashboard was correctly running. As the error, `Error: 'dial tcp 172.16.40.2:9090: i/o timeout'`, I guess the ip of `172.16.40.2` was the exactly dashboard container ip, which you should check whether or not it could accessing firstly. Secondly, you should check the service running correctly. At last, look over `http://10.136.97.229:8080/ui`, which use kubernetes proxy to access your dashboard service.

**Comment by bryk** [comment]
Can you give us logs from kubernetes-dashboard? E.g., `kubectl logs kubernetes-dashboard-v1.0.1-4k6vl`

**Comment by bryk** [comment]
You can also run the dashboard manually and set the `--apiserver-host` param. Use `kubectl create -f http:...` 
https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml

**Comment by bryk** [comment]
Btw, the ubuntu getting started guide is known to miss some things. We'll investigate it soon to find the root issue.

**Comment by luguangzhen** [comment]
Logs from kubernetes-dashboard

lgzh@ubuntu:~$ kubectl logs --tail=100  kubernetes-dashboard-v1.0.1-4k6vl   --namespace=kube-system
2016/04/25 11:18:06 Starting HTTP server on port 9090
2016/04/25 11:18:06 Creating API server client for https://192.168.3.1:443
2016/04/25 11:18:06 Creating in-cluster Heapster client

---------------------

And i found the dashboard container is running with ip 172.16.40.2

root@ubuntu:/opt/bin# docker ps
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
32a62621d876        gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1   "/dashboard --port=90"   23 minutes ago      Up 23 minutes                           k8s_kubernetes-dashboard.40f0932e_kubernetes-dashboard-v1.0.1-4k6vl_kube-system_a6645a45-0a8e-11e6-903e-005056b4d5fd_4cf5a04c
9b053af80510        gcr.io/google_containers/pause:2.0                           "/pause"                 23 minutes ago      Up 23 minutes                           k8s_POD.3a1c00d7_kubernetes-dashboard-v1.0.1-4k6vl_kube-system_a6645a45-0a8e-11e6-903e-005056b4d5fd_84448dac

**Comment by luguangzhen** [comment]
My kubernetes environment is located in the private network, that needs proxy setting to connect the Internet. Maybe some things should be configured. Like yesterday, i hasn't configured no_proxy=127.0.0.1,localhost,10.136.97.229 for user lgzh, which leads to deploy kunernetes failed at calling validate cluster.

**Comment by luguangzhen** [comment]
@bryk  Do you have other suggestions for this question?

**Comment by iamthemuffinman** [comment]
I'm also having this issue. Any ideas?

**Comment by luguangzhen** [comment]
This issue has been solved by adding an route item in the master machine:
root@ubuntu:~# route add -net 172.16.40.2 netmask 255.255.255.255 gw 10.136.97.224
The above 10.136.97.224 is the ip of  node, which the dashboard pod locates.
----------------------------
Maybe some step was wrong when i deployed the kubernetes dashboard service, or the kubernetes should add such route item automatically.

**Comment by bryk** [comment]
@luguangzhen Dashboard has no knowledge or understanding of routes. It just crates kubernetes Service for access. So Kubernetes core should create a route for you if it is correctly configured.

**Comment by damienjoldersma** [comment]
I recently ran into this as well, @luguangzhen, do you mind describing which ip was 172.16.40.2?  Is that the ip address of the host that the pod is located on or is that the ip of the master?
