### ISSUE TITLE
[FR] Allow the Chart to create extra manifest

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/dashboard#6740]
##### What would you like to be added

Sometimes, accessory to the installation there may be manifest to be installed (for example a SecretProviderClass).

It would be nice to be able to do this directly via the Chart using the approach that ArgoCD also uses.

Ref: https://github.com/argoproj/argo-helm/blob/cf57a71a154a1a8a19f5f9d3980d60eb3efd80c8/charts/argo-cd/values.yaml#L62-L87

##### Why is this needed

See above

**Comment by pierluigilenoci** [comment]
@floreks could you please take a look?

**Comment by floreks** [comment]
I am not really using helm, so it's hard to say if it's something we need. @desaintmartin is in charge of our helm integration. WDYT?

**Comment by pierluigilenoci** [comment]
@floreks thank you so much!
@desaintmartin can you take a look?

**Comment by desaintmartin** [comment]
That looks like a reasonable request, thanks for the suggestion, PR accepted!

Indeed, as a cluster operator managing hundreds of Helm Releases, I often find myself in need of Helmfile in order to add extra resources still managed by helm, which is not convenient.
