### ISSUE TITLE
Provide an option to filter namespaces list based on ressouce access

### ISSUE THREAD

**Issue by gprossliner** [kubernetes/dashboard#6785]
##### What would you like to be added
As a none admin user, it would be nice if the select box for the namespace contains the namespaces that "I can access".

It's clear that this cannot be done by RBAC only. If a user has a clusterrole assigned for verb "LIST" resource "Namespaces", he can retrieve all namespaces. If this has not been granted, the list of namespaces cannot be populated.

For a user it's very inconvenient if the namespace list is empty, because of RBAC setup. If an administrator grants "LIST" on "namspaces", s/he sees all namespaces, but if a namespace is selected where s/he cannot access any resource, the dashboard shows the RBAC related errors.

I would filter the list of namespaces based on the response to an SelfSubjectAccessReview. To retrieve the list of namespaces for the dashboard, the following logic would apply:

1. LIST all namespaces
2. If error => empty list (the current behavior)
3. For each namespace, issue a SelfSubjectAccessReview. If `!status.allowed` the namespace will filtered out

To opt-in this feature, and allow some configuration, I would add some Arguments, like:

* `--namespaces-rbacfilter`: Enables the feature (default: `false`)
* `--namespaces-rbacfilter-verb`: Specifies the verb for the issued SelfSubjectAccessReview (default: 'get')
* `--namespaces-rbacfilter-resouce`: Specifies the resource for the issued SelfSubjectAccessReview (default: 'pods')

##### Why is this needed

As a user, I ask for the ability to see and select namespaces. If the admin setup RBAC to allow "LIST" on "Namespaces", 
all namespaces are displayed, resulting in erros if I have no permissions on anything.

##### Comments

* Please note that this feature is not supposed to implement a kind of Security improvement. If a user can list namespaces, 
it can list them everywhere, like `kubectl get ns`. This feature should be understood as usability improvement, because if I can list namespaces, but I am no cluster-admin, I am not distracted by namespaces in the list, where I cannot access anything. 

* As an optimization, we could test if the user is a cluster-admin, an skip testing each namespace individually.

* The RBAC related data is not supposed to change frequently, so a caching implementation may be desirable to limit the number of api requests issued. I have not checked in the source code if there is an existing cache structure.

**Comment by floreks** [comment]
1. There is already a namespace fallback list that can be configured in case user does not have access to LIST all namespaces. It is available in the settings view.

2. I do not see how we could "test every namespace" if we do not have a way to actually get the LIST of namespaces without the proper privileges. Dashboard itself does not have almost any privileges and we do not want to change that for security reasons. We purely act on behalf of user, nothing else and can access Dashboard related resources such as our config map with settings or secret with self-signed certificate.

**Comment by gprossliner** [comment]
Hi floreks, thanks for the prompt response!

You didn't quite get me right. I know about the architecture regarding RBAC permissions ob the dashboard.

My proposal will not change the "all acts behalf of the user" principle (which I really like btw) . If the user doesn't have LIST on namespaces, then there is no change in behavior.

But if it has the permission to list (all) namspaces, and the feature is enabled, it filters the list based on SelfSubjectAccessReview requests for every namespace (defaults "view" "pod").

**Comment by floreks** [comment]
I didn't get the initial idea.

> As an optimization, we could test if the user is a cluster-admin, an skip testing each namespace individually.

There is no real way to check this. 

> The RBAC related data is not supposed to change frequently, so a caching implementation may be desirable to limit the number of api requests issued. I have not checked in the source code if there is an existing cache structure.

Unfortunately, we do not have any caching right now and due to this I don't think we could properly implement this feature without putting extra pressure on the API server. Clusters with lots of namespaces would be basically unusable due to this.

The only way would be to add a layer of informers that would be responsible for dealing with cache, but this requires a huge refactoring on the backend side.

**Comment by gprossliner** [comment]
>> As an optimization, we could test if the user is a cluster-admin, an skip testing each namespace individually.

> There is no real way to check this.

Yes, there is no real way to check this. "cluster-admin" is not even something real. Testing for "cluster-admin" cluster role would require to list all ClusterRoleBindings (and evaluate all subject kinds), which feels very wrong. And it's incorrect, as nothing prevents you from creating another ClusterRole and grand *, *.

As all you can check is the permission for some specific resource and verb (and namespace for namespaced resources), I would implement this by testing `kubectl auth can-i "*" "*" -n kube-system`. If this is allowed the user is "as much admin as possible" ;-)

> Unfortunately, we do not have any caching right now ... 

Sorry that this is a longer answer, including some thoughts not directly related to this issue.

#### Caching in the backend

Because there is no caching right now, and due to the fact that the dashboard (better "any dashboard") always needs to execute a larger number of requests, the number of namespaces on a "typical" cluster" is in the range of dozens, and the fact that the feature is opt-in, maybe it would be ok to implement this request without caching.

I really thing the implementing a cache-infrastructure on the backend would be hard because:

1. If you want to align the cache into the "all acts behalf of the user" principle, the cache would need to be keyed for one user. I think that this would dramatically increase the Memory Usage, and the Cache Hit Ratio would not be great, since it only hits on if a single user has opened multiple tabs, or requests the same objects in a short time interval.

2. If you keep a global cache which doesn't "act behalf of the user", you would need to evaluate all RBAC within the backend, which I consider fragile and hard to test.

3. It's very hard to not break the assumption of the Users: If I press "F5" I want the latest version, not the cached ones. With the proper use of informers (like you commented), this would be solvable. but 1. and 2. still apply.

#### Caching in the frontend

I monitored the calls to the `/api/v1/namespaces` endpoint from the browser, as this would be affected by this issue. It seems to happen in a very short interval (seems like every 5 seconds), **and** whenever the select list is opened. This seems way to often. I would cache it until the User hits F5, or when the select box is expanded, but not every five seconds. I don't have any data at hand, so I think this would reduce the overall requests to the API Server.

This may be considered to be implemented as an own PR.

**Comment by gprossliner** [comment]
> BTW: I can implement a PR for further discussion (already signed CLA for my contribution to kind).

@floreks can you tell me if you’re ok with that?

**Comment by floreks** [comment]
I don't consider the frontend cache a viable solution for this issue. There is no way to tell if we are working with the up-to-date or outdated data at this point and it can very easily and very quickly cause conflicts with the real backend state. One scenario is that you log in with user A and use it for some time and then someone else logs in with the same user A but gets fresh data. The first person might end up with outdated information and the second one with the newest one just because everything is stored only on the frontend side.

The proper solution should be done on the backend side. Using informers requires the application to have full access to the resources and then the application needs an internal authorization layer in order to check user privileges per every request i.e. based on the SelfSubjectAccessReview. This however requires a major redesign of our API. I don't see any middle ground here, unfortunately.
