### ISSUE TITLE
oauth2-proxy integration

### ISSUE THREAD

**Issue by aug70** [kubernetes/dashboard#6804]
##### What would you like to be added

Short description: I want to be able to use the dashboard Helm chart and easily integrate with oauth2-proxy. (There's a PR for this in the past https://github.com/kubernetes/dashboard/pull/6038) which was rejected.

Long description: I'm using existing Helm chart and integrate with oauth2-proxy via kubectl commands. Whereas ingresses and oauth2-proxy stuff could be integrated into the existing Helm chart. 
Another way, I'm trying to get this done, is to create a Helm chart and use dashbord and oauth2-proxy as dependencies, so I can install the dashboard with oauth2-proxy integration with a single Helm chart.

Both ways, either using kubectl or extra Helm chart are not very elegant solutions. This could be done with the existing Helm chart.
I don't know if this already possible, if it is, it surely needs documentation.

##### Why is this needed
Enhanced security.

**Comment by floreks** [comment]
It could be done, but we intentionally never did this for a couple of reasons:
1. We do not want to enforce a single solution and favor it over others (also meaning external software outside of the k8s core)
2. It requires an additional maintenance effort to keep everything in sync and up-to-date with the latest standards
3. It always favors certain groups of users over others as some of them simply won't be able to use it for many different reasons and will start creating issues wanting to support also their use cases and their configurations

**Comment by aug70** [comment]
I solved this problem by using ArgoCD and configuring each helm chart as dependency. Cleaner solution and I agree with the above statement. Closing this...
