### ISSUE TITLE
open dashboard  in Chrome show js error of two "??" not support

### ISSUE THREAD

**Issue by luckybirdme** [kubernetes/dashboard#6859]
##### Environment

```
Installation method: kubectl appy -f file.yaml
Kubernetes version:  v1.23.4
Dashboard version (v1.x is not supported. Use v2.0 or later.): v2.5.0
Operating system: centos
```

##### Observed result

![PVAO~_~9`VH9Q0A~YMEH1{E](https://user-images.githubusercontent.com/14368495/156089938-575fc637-9a2b-431e-a210-6d1bef02f265.png)

![QQ图片20220301095627](https://user-images.githubusercontent.com/14368495/156090041-33448da2-ff6a-4d4f-8869-8697349dbf60.png)

**Comment by floreks** [comment]
This won't really help us since it is a production build and code is compiled. It would be good to get a logs from the Dashboard.

**Comment by floreks** [comment]
Not enough information was provided.

/close
