### ISSUE TITLE
Download log problem form v.2.4.0

### ISSUE THREAD

**Issue by kittisuw** [kubernetes/dashboard#6888]
##### Environment

```
Kubernetes version:1.22.5
Dashboard version (v1.x is not supported. Use v2.0 or later.):v2.4.0
```
Currently I use kube dashboard v.2.4.0  but I got problem when I download pod log It can download only 1-2% of logs. pls, advise me.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/53901743/157798856-2c9821b5-2e0b-48ea-a4c4-993b7d71076d.png">

**Comment by floreks** [comment]
v2.4.0 should only be used with k8s v1.21 and lower. Use the latest Dashboard and recheck. Also, provide more information and fill out the issue template properly. 

/close

**Comment by kittisuw** [comment]
After upgrade 2.5.1 with Kubernetes 1.22.5. Still have a problem

**Comment by floreks** [comment]
Tested with our example pods that generate logs and can't reproduce (https://github.com/kubernetes/dashboard/tree/master/aio/test-resources). The whole log is being downloaded.
