### ISSUE TITLE
Add standard md-delay to all our tooltips

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#690]
Currently our tooltips appear with zero delay, which is super annoying when you move mouse around. Recently angular material added delay settings, so we should utilize it globally for our app: https://material.angularjs.org/latest/demo/tooltip

**Comment by digitalfishpond** [comment]
Working on this now

**Comment by digitalfishpond** [comment]
just to check, is 500ms an acceptable delay?

**Comment by floreks** [comment]
I think it's ok.

**Comment by digitalfishpond** [comment]
Leaving this issue for now as surprisingly difficult to do this in a clean way.
