### ISSUE TITLE
Using an access token generated by oidc provider does not work when pasted in login UI

### ISSUE THREAD

**Issue by zupalex** [kubernetes/dashboard#6904]
##### Environment

```
Installation method:
Kubernetes version: 1.20.4
Dashboard version: v2.5.1
Operating system: Debian 11
```

##### Steps to reproduce
1. Configure kube-apiserver to accept access tokens obtained from Azure, by adding this in the kube-apiserver arguments
```yaml
    - --oidc-client-id=**redacted**
    - --oidc-issuer-url=https://sts.windows.net/**redacted**/
    - --oidc-username-claim=samAccountName
    - "--oidc-username-prefix=oidc:"
    - --oidc-groups-claim=groups
```

2. Create a cluster role binding for a specific group and give is cluster-admin ClusterRole

3. Get an access token which has the group mentioned in step 2 in the groups claim, and pass it to kubectl with `--token`. I can do whatever I want on any resource in the cluster (get, delete, update, ...)

4. Connect to the kubernetes dashboard web interface over HTTPS and paste the same token used at step 3. Click sign-in. nothing happens, not even an error message stating that the authentication is unsuccessful

5. Using the kubernetes dashboard service account token, we can log in successfully, which rules out a problem with HTTPS, preventing remote access

##### Observed result
Nothing happens when providing an Azure access token to kubernetes dashboard web interface, while this token works with `kubectl --token`. A standard ServiceAccount token works with kubernetes dashboard, ruling out a remote access problem.

##### Expected result
The token which works with `kubectl --token` should work with the kubernetes dashboard

##### Comments
Logs from kubernetes dashboard pod when clicking "Sign-in" after pasting the Azure access token

```bash
2022/03/17 11:24:26 [2022-03-17T11:24:26Z] Incoming HTTP/2.0 GET /api/v1/csrftoken/login request from **redacted**:54595: { contents hidden }
2022/03/17 11:24:26 [2022-03-17T11:24:26Z] Outcoming response to **redacted**:54595 with 200 status code
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Incoming HTTP/2.0 POST /api/v1/login request from **redacted**:54595: { contents hidden }
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Outcoming response to **redacted**:54595 with 200 status code
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Incoming HTTP/2.0 GET /api/v1/plugin/config request from **redacted**:54595: 
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Incoming HTTP/2.0 GET /api/v1/login/status request from **redacted**:54595: 
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Outcoming response to **redacted**:54595 with 200 status code
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Outcoming response to **redacted**:54595 with 200 status code
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Incoming HTTP/2.0 GET /api/v1/login/status request from **redacted**:54595: 
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Outcoming response to **redacted**:54595 with 200 status code
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Incoming HTTP/2.0 GET /api/v1/login/status request from **redacted**:54595: 
2022/03/17 11:24:27 [2022-03-17T11:24:27Z] Outcoming response to **redacted**:54595 with 200 status code

```

**Comment by floreks** [comment]
Related to https://github.com/kubernetes/dashboard/issues/2353 `Allow logging in when a very long token is provided (i.e. Azure with groups, etc.)`. Azure login tokens are normally too big to be handled by the browser cookies. I know that azure allows configuring what kind of information should be embedded into the token itself and it is possible to strip down the unnecessary information from the token so that it could be used here.

/close

**Comment by zupalex** [comment]
I'm not sure I understand. For context, if I use a oauth2 proxy with an Ingress resource and set (for test purposes only)

```yaml
nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header 'Authorization' 'Bearer <insert azure access token here>';
```

in the annotations, then it works.
