### ISSUE TITLE
Breadcrumbs configuration: make all clients explicit

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#695]
Currently all clients that use breadcrumbs config do this by:
```js
      'kdBreadcrumbs': {
        'label': 'Replication Controllers',
      },
```

How about we move the `'kdBreadcrumbs'` string into a constant that is imported? This would then help us to keep track of all clients and fail if something is wrong. 

@floreks What do you think?

**Comment by floreks** [comment]
Yeah, I like it.
