### ISSUE TITLE
Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").

### ISSUE THREAD

**Issue by Joseph-Goergen** [kubernetes/dashboard#7057]
### What happened?

Page will not load through proxy microservice (from another website). Right now it's just a blank white page.
It works with 2.5.0, but on 2.5.1 it ends up with just a blank page with the javascript error. It works with a local `kubectl proxy`

The js console gives the error
```
Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").
```

### What did you expect to happen?

Dashboard showing up and working properly.

### How can we reproduce it (as minimally and precisely as possible)?

Setup a content security policy to load the page
The one we use is
```
Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; frame-ancestors 'self'; "form-action 'self'
```

### Anything else we need to know?

I was told that this could be solved by adding `unsafe-eval` to `script-src` to fix this, but doing so opens it up for eval functions to be ran by 3rd parties (which can potentially be dangerous if left open).

I could be completely wrong, but my guess is that from the 2.5.0 update to 2.5.1, there was a dependency update that is running `script-src` `unsafe-eval` code. (The description of `script-src` `unsafe-eval` is “allows arbitrary code to be executed on the page”).

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

### Kubernetes Dashboard version

2.5.1

### Kubernetes version

1.24

**Comment by floreks** [comment]
I see only dependency version updates between `2.5.0` and `2.5.1`. Most of them are minor bumps. There are no new dependencies. We'd have to investigate deeper and find out how to pin down the problematic dependency (if it's even a dependency issue). Most changes are also rather small. This issue might be hard to debug.

Could you provide an example configuration that we could use to reproduce this issue?

**Comment by Joseph-Goergen** [comment]
I think I was able to replicate this for reproduceability in a local environment. I spent a good part of the day getting it working (mainly because this is the first time I've ever tried modifying code with the dashboard, and partially because I didn't know that there was documentation for development until later)

I believe you can reproduce this by adding `<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; frame-ancestors 'self'; form-action 'self'">` to https://github.com/kubernetes/dashboard/blob/v2.5.1/src/app/frontend/index.html

I will deploy a 2.5.0 one with this meta tag just to double check I didn't mess up somewhere else along the way.

**Comment by floreks** [comment]
I was actually more interested in your setup. 

1. How is Dashboard exposed?
2. Are you using some kind of reverse proxy?
3. How is the CSP configured in your cluster?

I'd like to reproduce this without changing the code and better understand the difference between `2.5.0` and `2.5.1`.

**Comment by Joseph-Goergen** [comment]
I believe we have a dashboard proxy microservice that handles the proxying to our frontend, I didn't set this up and I'm not part of the team that owns this component, so I can only give you a simple answer. The CPS I provided is the one we currently use in the microservice and I was able to run into the same js error when I threw it into the header of the html.

**Comment by Joseph-Goergen** [comment]
@floreks Is there anything else you need for this? Since I was able to replicate it by modifying dashboard code (and deploying it locally) I don't believe the proxy microservice we use is all that important other than the fact we have a content security policy setup when connecting to it.

**Comment by Joseph-Goergen** [comment]
It's been a couple of months since I've heard anything about this. May we get a status update of where this is sitting? We are unable to update past 2.5.0 due to this bug

**Comment by Joseph-Goergen** [comment]
@maciaszczykm 

I ended up finding what caused it. It was harder than I thought to debug because just inserting the CSP into the html broke at every release whereas our proxy setup (in special environment I don't have full access to modify/spin up) only loaded it in initially (or through some forwarding?). Basically, it didn't load/debug the same way I thought it did. Eitherway, I found the troublesome commit that has been causing us issues.

https://github.com/kubernetes/dashboard/commit/5839fbf7c14435f4866fa5611a2a09e5763afb24

I even tested this by modifying it at master and building a test image with `ng-in-viewport` at `6.1.5`.

**Comment by floreks** [comment]
wow, this must have been a lot of work to pin down the exact issue. Thanks for taking the time to do that! I am wondering if `13.0.1` actually solved the CSP issue. We will try to do a minor release this week since there were a couple of minor fixes anyway and you should be able to test once again. If the issue will persist we will drop this dependency and find a replacement.

**Comment by maciaszczykm** [comment]
I'll do it.

**Comment by Cutshadows** [comment]
worker-src 'self' blob:;  " fixed it by adding the following CSP directive to my server:"
