### ISSUE TITLE
Middle-ellipsised text do not scale when flex auto is used

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#706]
As discussed in https://github.com/kubernetes/dashboard/pull/694#issuecomment-216817491 middle ellipsised text do not always scale correctly. 

As workaround I've used `flex=90` to limit container width but this should be avoided.

Code reference:
https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/common/components/infocard/infocardentry.html#L20

**Comment by bryk** [comment]
Removed middle ellipsis entirely.
