### ISSUE TITLE
None of the releases have a checkmark for Kubernetes 1.22

### ISSUE THREAD

**Issue by volkert-fastned** [kubernetes/dashboard#7067]
### What should be cleaned up or changed?

Dashboard release [v2.4.0](https://github.com/kubernetes/dashboard/releases/tag/v2.4.0) lists K8s version 1.21 as the last fully supported version (i.e. with a checkmark). The first release after that, [v2.5.0](https://github.com/kubernetes/dashboard/releases/tag/v2.5.0), lists K8s version 1.23 as the only fully supported version (having a checkmark, with all the older Kubernetes versions including 1.22 having a question mark).

So which Kubernetes Dashboard version is the recommended version for Kubernetes 1.22?

Please clarify this in the release notes.

Thank you.

### Why is this needed?

To make sure one doesn't install an incompatible (too old or too new) Dashboard version on a Kubernetes 1.22 cluster.

**Comment by floreks** [comment]
We don't have a release that officially fully supports the `v1.22`. For the `v1.22` only the Dashboard `v2.5.0+` will work. There should not be any breaking changes between K8S `v1.22` and `v1.23` that affect Dashboard. Our support matrix is mostly based on the `client-go` version that we use and their support matrix.

/close
