### ISSUE TITLE
Build does more than building

### ISSUE THREAD

**Issue by FrenchBen** [kubernetes/dashboard#7077]
### What happened?

Introduced with the multi-arch support PR https://github.com/kubernetes/dashboard/pull/6657/, we are now pushing on every build, when the target is to build, not push. 

This results in a failed push (no access), but could inadvertently pushing the wrong image to a repo.

### What did you expect to happen?

I expect build targets to only build the artifact, not push them.

### How can we reproduce it (as minimally and precisely as possible)?

`make docker-build-head` or `make docker-build-release` have the `--push` flag, which will build & push the image. 

We have dedicated "push" targets that should be used instead:
* `docker-push-release`
* `docker-push-head`

### Kubernetes Dashboard version

2.5.1

### Kubernetes version

all

**Comment by floreks** [comment]
A good explanation why it has to be done this way:

```
--push : when you supply this parameter, the built images will be pushed to the remote registry directly. Please note: if you do not supply this parameter, docker will not attempt to generate the manifest and push it to a docker registry. On the other hand, a local docker repository can’t serve multi-arch images behind one manifest. Therefore, the built result will be simply discarded. Unless you only want to test your image build scripts, you likely will always want to include --push in your command.
```
[Source](https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-1-the-basics-2fa97869a99b)

Anyway this only

**Comment by FrenchBen** [comment]
Closing thanks to above explanation
