### ISSUE TITLE
error executing template "{{.data.token | base64decode}}": template: output:1:16: executing "output" at <base64decode>: invalid value; expected string

### ISSUE THREAD

**Issue by bmmpp** [kubernetes/dashboard#7081]
### What happened?

error executing template "{{.data.token | base64decode}}": template: output:1:16: executing "output" at <base64decode>: invalid value; expected string   
when create user account

### What did you expect to happen?

get sa token to  login dashboard

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

2.5.1

### Kubernetes version

1.24

**Comment by floreks** [comment]
Not enough information about the issue and how to reproduce it. You can reopen once the issue template is filled properly and it is clear what is the issue and how to reproduce it.

/close

**Comment by va-len-tine** [comment]
I ran into the same problem

**Comment by bmmpp** [comment]
> I ran into the same problem

Do you have any idea? According to the steps on the official website, I can't get the token to login dashboard!

**Comment by va-len-tine** [comment]
> > I ran into the same problem
> 
> Do you have any idea? According to the steps on the official website, I can't get the token to login dashboard!

I solved，create token：
kubectl -n kubernetes-dashboard create token admin-user

**Comment by robertgartman** [comment]
In case you arrive here searching for a clue - see [breaking changes in Kubernetes 1.24](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade): point 3 regarding  _LegacyServiceAccountTokenNoAutoGeneration_

You can create the secret and wire it with the ServiceAccount. Note `kubernetes.io/service-account.name: "sa-name"` in this example: https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
