### ISSUE TITLE
error: error executing template "{{.data.token | base64decode}}": template: output:1:16: executing "output" at <base64decode>: invalid value; expected string

### ISSUE THREAD

**Issue by va-len-tine** [kubernetes/dashboard#7094]
### What happened?

When I Getting a Bearer Token

Execute the flow command:
kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get sa/admin-user -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"

An error occurred:
error: error executing template "{{.data.token | base64decode}}": template: output:1:16: executing "output" at <base64decode>: invalid value; expected string

### What did you expect to happen?

A Token

### How can we reproduce it (as minimally and precisely as possible)?

Refer to official documentation

### Kubernetes Dashboard version

latest

### Kubernetes version

v1.24.0

### Go version

1.18.1

**Comment by floreks** [comment]
Ref: https://github.com/kubernetes/dashboard/pull/6967
Compatibility matrix: https://github.com/kubernetes/dashboard/releases/tag/v2.5.1

v1.24 is not officially supported at this time. Once we'll update our backend to support it, documentation will be updated also.

/close
