### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#71]
Created an issue because it is a cross-cutting concern. 

We need japanese and english.

Any special requirements?

**Comment by bryk** [comment]
We haven't started thinking about this yet. It is a nice enhancement, though. So if you want to work on this, then perfect. We should use standard Angular mechanisms, however. And have plan on how the translations would happen.

**Comment by SebastianM** [comment]
Good idea :+1:
IMO the de facto standard solution for Angular1 is [angular-translate](https://github.com/angular-translate/angular-translate). The simplest way would be to use the [static file loader](https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translateStaticFilesLoader) and ship multiple JSON files (maybe seperated per module) with the GUI assets.

**Comment by SebastianM** [comment]
Could help out on this if you want

**Comment by cheld** [comment]
About the translation process - I think something simple is fine. I think we have to worry only about the detection of strings that have to be re-translated. Three options come to my mind:


*Option1; Use a three-way compare tool or a real translation tool, like eclipse-bable. There are many tools. We would have to find something suitable.
*Option2: If developers update the english properties, they must add a TODO prefix to the key - value of all other languages. e.g.

 
button.deploy=Deploy an app

eventually it is translated

button.deploy=アプリを展開します

now, if the value is changed:

button.deploy=Deploy a microservice
button.deploy=TODO アプリを展開します

*Option3: Use a horizontal line. New and updated keys must be moved below the line. (Eclipse used to do it this way)

----------------------------all updated strings below this line------------------------------------
button.deploy=Deploy a microservice


I would suggest option 2. Any other idea?

**Comment by cheld** [comment]
We should also add a few gulp tasks:
1. Do constistency checks on number of keys and parameters
2. Create a artificially translation that doubles each value and replaces spaces with underscores. The reason is that some languages like german are much longer than english, while other languages do not use spaces e.g. Japanese. So a developer can check the layout in a worst-case scenario.

**Comment by cheld** [comment]
@taimir
@SebastianM

Sebastian, are you working on this? Our working student Atanas is looking for a task. I think this would be a good fit. Can you collaborate and split up the work a bit?

**Comment by SebastianM** [comment]
@cheld Yes, I'm working on the Gulp related stuff. I'm not sure how we could split up the work. Should have something at the end of this week.

**Comment by bryk** [comment]
Done.
