### ISSUE TITLE
Can not generate token on k8s v1.24.0

### ISSUE THREAD

**Issue by 0YHR0** [kubernetes/dashboard#7101]
### What happened?

when I follow the guide of generating the token:

`root@pcss22task2vm1:/home/haoran# kubectl apply -f add.yaml 
serviceaccount/admin-user created
clusterrolebinding.rbac.authorization.k8s.io/admin-user created
root@pcss22task2vm1:/home/haoran# kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get sa/admin-user -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"
Error executing template: template: output:1:16: executing "output" at <base64decode>: invalid value; expected string. Printing more information for debugging the template:
	template was:
		{{.data.token | base64decode}}
	raw data was:
		{"apiVersion":"v1","items":[{"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"labels\":{\"k8s-app\":\"kubernetes-dashboard\"},\"name\":\"kubernetes-dashboard-certs\",\"namespace\":\"kubernetes-dashboard\"},\"type\":\"Opaque\"}\n"},"creationTimestamp":"2022-05-13T08:25:21Z","labels":{"k8s-app":"kubernetes-dashboard"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:k8s-app":{}}},"f:type":{}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2022-05-13T08:25:21Z"}],"name":"kubernetes-dashboard-certs","namespace":"kubernetes-dashboard","resourceVersion":"108275","uid":"5c217bc2-2b26-42b1-8ada-0e897ec448a2"},"type":"Opaque"},{"apiVersion":"v1","data":{"csrf":"+F9yMb7OUgn+EvekcluhujN6pyxtcC7ygQopG51IAKmtmfHh5pfZckHXxJtpnttnydsl8Sf9I5PxC2xtdCizMhP+YLjQqCYRyWQlKf1AtuNAmDU5qZ49OA/v9i90Q1PtzXQbkFrbz275HsD/xnnfIcrFkH4RICBAFHGYGADX8sDkGe/AcYCmg5UAW8aNhGamE2Ak+eOmrYe2gJtmKihsMBcZnpLmUuVMl6fU96pSKTPE28kxqk4HxX1F+MvXkZlwgwHpfl3dpQpIiZ8TTHBfCNw3Mxvh06hLKmpR4N1zritevVLsweLj3I0nueMgRlYb3hISF+CSNTdN12j2mGr4Og=="},"kind":"Secret","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"csrf\":\"\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"labels\":{\"k8s-app\":\"kubernetes-dashboard\"},\"name\":\"kubernetes-dashboard-csrf\",\"namespace\":\"kubernetes-dashboard\"},\"type\":\"Opaque\"}\n"},"creationTimestamp":"2022-05-13T08:25:21Z","labels":{"k8s-app":"kubernetes-dashboard"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:k8s-app":{}}},"f:type":{}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2022-05-13T08:25:21Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{"f:csrf":{}}},"manager":"dashboard","operation":"Update","time":"2022-05-13T08:25:27Z"}],"name":"kubernetes-dashboard-csrf","namespace":"kubernetes-dashboard","resourceVersion":"108351","uid":"07410051-e99a-4c9f-bef1-5230d2c680d1"},"type":"Opaque"},{"apiVersion":"v1","data":{"priv":"LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBc2ZIRzYvMnNTUWZlTVM1UUtvWGMvQzZGZHdrd1hEZHBIMTlMemJzREhHeEJtYlFGCml6N3VQWTJSY2xobWdrekMyS0hCY0IwdU1XVDE0b2ZaLzJMY1ZHbjFseXFuUlVMUmE1Z2ZnOVgwZ09VR05jQWkKZVZGOE1yem1sOUZ3S2NCenBaZnpNUDEwYUU5UW42RlpZWlI3NTZpN0RKbUYzY0ZzVU0zWmdOU1lmcjVWMjlxLwpyd0hxeTY4c2RJWkIzTkIyVERIS1l4QWJIWk5maFBpSVQzMmZaelFiY1RpVzc2T2kycGpJbEtVWE04aHBMUDZICkpsanh4cUR5TlhBN2p0MWlTSkZEaHVzNEhNbEl1WEtOYUNrK280YldGa1lZa1VSWWEyeVlhTSt1RlRXRTBIaGEKaURrVHhraUc4ajdrR1YzSW1LQzRMMVJTTjN5NStZbTEwNDlzQndJREFRQUJBb0lCQUZ0ZS92bm14RFNyNlpmdgpaQkt4c2d0OEIrUmJ2NDFhbG93WmJ0OHhEQ1BvSXJjK0RTcTNJYlpSbjBITHlyZFZteWVKeDc0OS9aNDNiVnJvCnp6T29HK0xzbGNNTmo5NnN0TVErMU0vcGFTZFdjcDNmRHRTazF0Vm0wakZheGZGcWRQZXUwcDF4Ui9qWDRWcFcKaTRManI4d0FoQ3V3R1dFSkZRbFk2anFRNzgwRUsrcWhTTVZ5cXhoR1Y5OVRFWE10b1NHaGp2Y3RqVGYwT1k3RQpZbFlKdnQyYXpjVjhTK05qK2JyQUEzYk1Ec01tWTdreXMzYjVSbkt0NUh1NWthRlppQXlTODRaRHdmTUw4RlJKCnAvZFhJWS9RTzdOKy94K3E3M2F5QTRZYXNFUUdRZlI4SnlrK0NSNWlnSFdKQ1BUZzNiU0V5MlNvazBna2x5TGgKejNLMG5lRUNnWUVBMEp4T25GV21pR0VrQUVwV1RnMnBiL1BkUmFkTDFHaHBSRjBta0pnaDVZdnRLdjVCTXVFTgovOWxhWDJ4SHZvaVE4NmYvcjBtMG41Z0Rsa0hOUmEyelBKb1pRc3M4L20yTXFlRC90SnFuWVJHZVNqSEhyVE1pCnZtMzNFdlhPOXRDSUJmVmlPMU44WDFJbk8xNmNaOVR5TnozZ0I4MVZHNGJ4Z0FmbjZSbXNpOE1DZ1lFQTJsNFcKenR0cVNtS2ZBdHdkUTFWeGEreEpVT2c0UFF6Wm85bkpBMW9uUW1XWVY0S2ZJdEhCL214dXA0dmZGWXhhVHhjNApJdHRidE5WazI5VTQ1NTNVMkFLc2RqMjFwZjJqWW1HVDFJRXlycUE2RWRmdnYzUVYzTXpLck9vMUNURjFMOGUzCnJEUXVLRFBscWJsYS9ROGYvaURFS0pqY1gyM0F3YkV0RGxQTHptMENnWUFuWjA3bDhydTVDUGcrNGN1NWhKVWIKbzJtSlRaZGlNTEtwaWhyTnR4NjMrQjA5UUxkWi8rNmdCQk13OFFnQU1sV0c0SlhJSzFqbHlGWHRITkxFTlpJawpnVXNDTmRkNGk0TEZWODJVOUoxbkZXZmJ4ZGxjbXNzV1F6a25LSzBHSzg5MXFLcjhYOEdmVTZvN2FaeUxkRXFvCktwVFZoSEJ0K2FoR01iZ1piSk1OOXdLQmdBM3h2akVkYjg4cU53OCtzUnV3cEJxSkx6RmNjdUxySkNiRGJJT3IKU1NDRFRsUWdRanM5Kzg1Y2JFQ0V2UTBxTmtZZ3JIUUZYL2pQTzY2U0VoMHdSZnc1UjN3UmVyMEwwbGdnOVFpMwo2MTJkVzdmeCt4eFZ0R095TENzWWxhUnRwUmNWQU5TZFRHbEN6eUtrZEh2K2NFT1JJaFdabFZEK3VEVm1OQU5iCk5JT05Bb0dBVUV5UjZSaHV2bE5oUTlMMFRTblp6c21pVS9uOTVEWFp5NHVHNjZOaUdDN0dpaHFNbURRK3pQTlAKektwRlVkNm5OSUpIcDhsYURsNnJuV3Z6STB0eXNpY2htcXpYSjliL0dqbXNLRkdpUngwOWRxeWRHTVRxSDJQVAo1NTNaV1krNjdNaFMzby9FTW5lYjFEOGZVUTVOYlJmUXo4ZTgyVG9lWDAyb0xqcmwxcVk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==","pub":"LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc2ZIRzYvMnNTUWZlTVM1UUtvWGMKL0M2RmR3a3dYRGRwSDE5THpic0RIR3hCbWJRRml6N3VQWTJSY2xobWdrekMyS0hCY0IwdU1XVDE0b2ZaLzJMYwpWR24xbHlxblJVTFJhNWdmZzlYMGdPVUdOY0FpZVZGOE1yem1sOUZ3S2NCenBaZnpNUDEwYUU5UW42RlpZWlI3CjU2aTdESm1GM2NGc1VNM1pnTlNZZnI1VjI5cS9yd0hxeTY4c2RJWkIzTkIyVERIS1l4QWJIWk5maFBpSVQzMmYKWnpRYmNUaVc3Nk9pMnBqSWxLVVhNOGhwTFA2SEpsanh4cUR5TlhBN2p0MWlTSkZEaHVzNEhNbEl1WEtOYUNrKwpvNGJXRmtZWWtVUllhMnlZYU0rdUZUV0UwSGhhaURrVHhraUc4ajdrR1YzSW1LQzRMMVJTTjN5NStZbTEwNDlzCkJ3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K"},"kind":"Secret","metadata":{"creationTimestamp":"2022-05-13T08:25:21Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:type":{}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2022-05-13T08:25:21Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:priv":{},"f:pub":{}}},"manager":"dashboard","operation":"Update","time":"2022-05-13T08:25:27Z"}],"name":"kubernetes-dashboard-key-holder","namespace":"kubernetes-dashboard","resourceVersion":"108352","uid":"466cec7c-8145-465f-a5b1-05e386de6acf"},"type":"Opaque"}],"kind":"List","metadata":{"resourceVersion":""}}
	object given to template engine was:
		map[apiVersion:v1 items:[map[apiVersion:v1 kind:Secret metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard-certs","namespace":"kubernetes-dashboard"},"type":"Opaque"}
] creationTimestamp:2022-05-13T08:25:21Z labels:map[k8s-app:kubernetes-dashboard] managedFields:[map[apiVersion:v1 fieldsType:FieldsV1 fieldsV1:map[f:metadata:map[f:annotations:map[.:map[] f:kubectl.kubernetes.io/last-applied-configuration:map[]] f:labels:map[.:map[] f:k8s-app:map[]]] f:type:map[]] manager:kubectl-client-side-apply operation:Update time:2022-05-13T08:25:21Z]] name:kubernetes-dashboard-certs namespace:kubernetes-dashboard resourceVersion:108275 uid:5c217bc2-2b26-42b1-8ada-0e897ec448a2] type:Opaque] map[apiVersion:v1 data:map[csrf:+F9yMb7OUgn+EvekcluhujN6pyxtcC7ygQopG51IAKmtmfHh5pfZckHXxJtpnttnydsl8Sf9I5PxC2xtdCizMhP+YLjQqCYRyWQlKf1AtuNAmDU5qZ49OA/v9i90Q1PtzXQbkFrbz275HsD/xnnfIcrFkH4RICBAFHGYGADX8sDkGe/AcYCmg5UAW8aNhGamE2Ak+eOmrYe2gJtmKihsMBcZnpLmUuVMl6fU96pSKTPE28kxqk4HxX1F+MvXkZlwgwHpfl3dpQpIiZ8TTHBfCNw3Mxvh06hLKmpR4N1zritevVLsweLj3I0nueMgRlYb3hISF+CSNTdN12j2mGr4Og==] kind:Secret metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","data":{"csrf":""},"kind":"Secret","metadata":{"annotations":{},"labels":{"k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard-csrf","namespace":"kubernetes-dashboard"},"type":"Opaque"}
] creationTimestamp:2022-05-13T08:25:21Z labels:map[k8s-app:kubernetes-dashboard] managedFields:[map[apiVersion:v1 fieldsType:FieldsV1 fieldsV1:map[f:data:map[] f:metadata:map[f:annotations:map[.:map[] f:kubectl.kubernetes.io/last-applied-configuration:map[]] f:labels:map[.:map[] f:k8s-app:map[]]] f:type:map[]] manager:kubectl-client-side-apply operation:Update time:2022-05-13T08:25:21Z] map[apiVersion:v1 fieldsType:FieldsV1 fieldsV1:map[f:data:map[f:csrf:map[]]] manager:dashboard operation:Update time:2022-05-13T08:25:27Z]] name:kubernetes-dashboard-csrf namespace:kubernetes-dashboard resourceVersion:108351 uid:07410051-e99a-4c9f-bef1-5230d2c680d1] type:Opaque] map[apiVersion:v1 data:map[priv:LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBc2ZIRzYvMnNTUWZlTVM1UUtvWGMvQzZGZHdrd1hEZHBIMTlMemJzREhHeEJtYlFGCml6N3VQWTJSY2xobWdrekMyS0hCY0IwdU1XVDE0b2ZaLzJMY1ZHbjFseXFuUlVMUmE1Z2ZnOVgwZ09VR05jQWkKZVZGOE1yem1sOUZ3S2NCenBaZnpNUDEwYUU5UW42RlpZWlI3NTZpN0RKbUYzY0ZzVU0zWmdOU1lmcjVWMjlxLwpyd0hxeTY4c2RJWkIzTkIyVERIS1l4QWJIWk5maFBpSVQzMmZaelFiY1RpVzc2T2kycGpJbEtVWE04aHBMUDZICkpsanh4cUR5TlhBN2p0MWlTSkZEaHVzNEhNbEl1WEtOYUNrK280YldGa1lZa1VSWWEyeVlhTSt1RlRXRTBIaGEKaURrVHhraUc4ajdrR1YzSW1LQzRMMVJTTjN5NStZbTEwNDlzQndJREFRQUJBb0lCQUZ0ZS92bm14RFNyNlpmdgpaQkt4c2d0OEIrUmJ2NDFhbG93WmJ0OHhEQ1BvSXJjK0RTcTNJYlpSbjBITHlyZFZteWVKeDc0OS9aNDNiVnJvCnp6T29HK0xzbGNNTmo5NnN0TVErMU0vcGFTZFdjcDNmRHRTazF0Vm0wakZheGZGcWRQZXUwcDF4Ui9qWDRWcFcKaTRManI4d0FoQ3V3R1dFSkZRbFk2anFRNzgwRUsrcWhTTVZ5cXhoR1Y5OVRFWE10b1NHaGp2Y3RqVGYwT1k3RQpZbFlKdnQyYXpjVjhTK05qK2JyQUEzYk1Ec01tWTdreXMzYjVSbkt0NUh1NWthRlppQXlTODRaRHdmTUw4RlJKCnAvZFhJWS9RTzdOKy94K3E3M2F5QTRZYXNFUUdRZlI4SnlrK0NSNWlnSFdKQ1BUZzNiU0V5MlNvazBna2x5TGgKejNLMG5lRUNnWUVBMEp4T25GV21pR0VrQUVwV1RnMnBiL1BkUmFkTDFHaHBSRjBta0pnaDVZdnRLdjVCTXVFTgovOWxhWDJ4SHZvaVE4NmYvcjBtMG41Z0Rsa0hOUmEyelBKb1pRc3M4L20yTXFlRC90SnFuWVJHZVNqSEhyVE1pCnZtMzNFdlhPOXRDSUJmVmlPMU44WDFJbk8xNmNaOVR5TnozZ0I4MVZHNGJ4Z0FmbjZSbXNpOE1DZ1lFQTJsNFcKenR0cVNtS2ZBdHdkUTFWeGEreEpVT2c0UFF6Wm85bkpBMW9uUW1XWVY0S2ZJdEhCL214dXA0dmZGWXhhVHhjNApJdHRidE5WazI5VTQ1NTNVMkFLc2RqMjFwZjJqWW1HVDFJRXlycUE2RWRmdnYzUVYzTXpLck9vMUNURjFMOGUzCnJEUXVLRFBscWJsYS9ROGYvaURFS0pqY1gyM0F3YkV0RGxQTHptMENnWUFuWjA3bDhydTVDUGcrNGN1NWhKVWIKbzJtSlRaZGlNTEtwaWhyTnR4NjMrQjA5UUxkWi8rNmdCQk13OFFnQU1sV0c0SlhJSzFqbHlGWHRITkxFTlpJawpnVXNDTmRkNGk0TEZWODJVOUoxbkZXZmJ4ZGxjbXNzV1F6a25LSzBHSzg5MXFLcjhYOEdmVTZvN2FaeUxkRXFvCktwVFZoSEJ0K2FoR01iZ1piSk1OOXdLQmdBM3h2akVkYjg4cU53OCtzUnV3cEJxSkx6RmNjdUxySkNiRGJJT3IKU1NDRFRsUWdRanM5Kzg1Y2JFQ0V2UTBxTmtZZ3JIUUZYL2pQTzY2U0VoMHdSZnc1UjN3UmVyMEwwbGdnOVFpMwo2MTJkVzdmeCt4eFZ0R095TENzWWxhUnRwUmNWQU5TZFRHbEN6eUtrZEh2K2NFT1JJaFdabFZEK3VEVm1OQU5iCk5JT05Bb0dBVUV5UjZSaHV2bE5oUTlMMFRTblp6c21pVS9uOTVEWFp5NHVHNjZOaUdDN0dpaHFNbURRK3pQTlAKektwRlVkNm5OSUpIcDhsYURsNnJuV3Z6STB0eXNpY2htcXpYSjliL0dqbXNLRkdpUngwOWRxeWRHTVRxSDJQVAo1NTNaV1krNjdNaFMzby9FTW5lYjFEOGZVUTVOYlJmUXo4ZTgyVG9lWDAyb0xqcmwxcVk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg== pub:LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc2ZIRzYvMnNTUWZlTVM1UUtvWGMKL0M2RmR3a3dYRGRwSDE5THpic0RIR3hCbWJRRml6N3VQWTJSY2xobWdrekMyS0hCY0IwdU1XVDE0b2ZaLzJMYwpWR24xbHlxblJVTFJhNWdmZzlYMGdPVUdOY0FpZVZGOE1yem1sOUZ3S2NCenBaZnpNUDEwYUU5UW42RlpZWlI3CjU2aTdESm1GM2NGc1VNM1pnTlNZZnI1VjI5cS9yd0hxeTY4c2RJWkIzTkIyVERIS1l4QWJIWk5maFBpSVQzMmYKWnpRYmNUaVc3Nk9pMnBqSWxLVVhNOGhwTFA2SEpsanh4cUR5TlhBN2p0MWlTSkZEaHVzNEhNbEl1WEtOYUNrKwpvNGJXRmtZWWtVUllhMnlZYU0rdUZUV0UwSGhhaURrVHhraUc4ajdrR1YzSW1LQzRMMVJTTjN5NStZbTEwNDlzCkJ3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K] kind:Secret metadata:map[creationTimestamp:2022-05-13T08:25:21Z managedFields:[map[apiVersion:v1 fieldsType:FieldsV1 fieldsV1:map[f:type:map[]] manager:kubectl-client-side-apply operation:Update time:2022-05-13T08:25:21Z] map[apiVersion:v1 fieldsType:FieldsV1 fieldsV1:map[f:data:map[.:map[] f:priv:map[] f:pub:map[]]] manager:dashboard operation:Update time:2022-05-13T08:25:27Z]] name:kubernetes-dashboard-key-holder namespace:kubernetes-dashboard resourceVersion:108352 uid:466cec7c-8145-465f-a5b1-05e386de6acf] type:Opaque]] kind:List metadata:map[resourceVersion:]]

error: error executing template "{{.data.token | base64decode}}": template: output:1:16: executing "output" at <base64decode>: invalid value; expected string

When i check the secret, no secret for this token are generated

### What did you expect to happen?

Generate a token for me to login

### How can we reproduce it (as minimally and precisely as possible)?

You can try the deployment guide on k8s v1.24.0

### Kubernetes Dashboard version

V2.5.1

### Kubernetes version

v1.24.0

**Comment by floreks** [comment]
Duplicate of https://github.com/kubernetes/dashboard/issues/7094 and https://github.com/kubernetes/dashboard/issues/7081

/close
