### ISSUE TITLE
[k8s 1.21] BoundServiceAccountTokenVolume refresh token 

### ISSUE THREAD

**Issue by mo-saeed** [kubernetes/dashboard#7103]
### What happened?

Hi,

Kubernetes version 1.21 graduated BoundServiceAccountTokenVolume feature [1] to beta and enabled it by default. This feature improves security of service account tokens by requiring a one hour expiry time, over the previous default of no expiration. This means that applications that do not refetch service account tokens periodically will receive an HTTP 401 unauthorized error response on requests to Kubernetes API server with expired tokens.

In our kubernetes audit logs we see that kubernetes dashboard still using stale tokens 

```
"authentication.k8s.io/stale-token":"subject: system:serviceaccount:kube-infrastructure:kubernetes-dashboard, seconds after warning threshold: 1200715"
```
As per my understanding, that should be fixed by upgrading kubernetes client SDK to latest release `Go v0.15.7 and later`

### What did you expect to happen?

kubernetes dashboard to support BoundServiceAccountTokenVolume refresh token after upgrading to k8s 1.21 

### How can we reproduce it (as minimally and precisely as possible)?

install kubernetes daashboard in kubernetes cluster with version >= 1.21 and check the kubernetes audit logs for stale-token

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

latest

### Kubernetes version

1.22

**Comment by amalendur** [comment]
I am using EKS 1.21 and kubernetesui/dashboard:v2.5.1 (chart v5.5.1). and getting the same issue.

**Comment by baturozgur** [comment]
I am using EKS 1.21 and getting the same issue.

**Comment by floreks** [comment]
We have pushed a new release of dashboard-metrics-scraper with updated dependencies. Issue should be resolved now, if not please reopen an issue in the scraper repository.

https://github.com/kubernetes-sigs/dashboard-metrics-scraper/releases

/close
