### ISSUE TITLE
Kubernetes v1.24 DashBoard Token

### ISSUE THREAD

**Issue by zhhkheaven** [kubernetes/dashboard#7130]
### What happened?

Due to the Kubernetes update to v1.24 When create user will not create token automatic. so you should create token by yourself.

The really reason is  **LegacyServiceAccountTokenNoAutoGeneration** is beat  and k8s v1.24 will disable this feature by default.

If you follow the guide [creating sample user](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md) will  miss leading user.

### What did you expect to happen?

Can't create user token automic.

### How can we reproduce it (as minimally and precisely as possible)?

Add the command **kubectl create token <sa name> --namespace <name> ** in the [creating sample user](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md)
for example  
**kubectl create token admin-user -n kubernetes-dashboard**

Now you get the token! 

### Kubernetes Dashboard version

latest

### Kubernetes version

v1.24

**Comment by floreks** [comment]
Duplicate.

/close
