### ISSUE TITLE
Misguiding warning when creating new resource: The form has not been submitted yet, do you really want to leave

### ISSUE THREAD

**Issue by navilg** [kubernetes/dashboard#7133]
### What happened?

When we create new resource using `+` icon on top right corner, using YAML input. 

It throws WARNING message `The form has not been submitted yet, do you really want to leave ?` after we click upload. 

Resource is getting created successfully.  But there is no success message as such and warning message seems misguiding.

![image](https://user-images.githubusercontent.com/37469234/170976108-e3bbe51c-525e-4ae1-9fcd-262e45708cf7.png)

### What did you expect to happen?

After clicking upload, If resource is created successfully, A success message should appear.

### How can we reproduce it (as minimally and precisely as possible)?

1. Click on `+` icon from top right (Create new resource)
2. Use `Create from input` tab.
3. Add resource's YAML in form field.
4. Click upload. A warning message as seen in above screenshot will pop-up.
5. Check the resource. It must have been created if YAMLs are correct.

### Anything else we need to know?

Kubernetes Dashboard is deployed using helm chart version 5.4.1

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

2.5.1

### Kubernetes version

1.20.13

**Comment by floreks** [comment]
Fixed by #7007 and available in https://github.com/kubernetes/dashboard/releases/tag/v2.6.0

/close
