### ISSUE TITLE
no matches for kind "APIService" in version "apiregistration.k8s.io/v1beta1" - kube 1.22 support

### ISSUE THREAD

**Issue by purduemike** [kubernetes/dashboard#7155]
### What happened?

I'm getting the following error when trying to install the kube dashboard with metrics server helm chart.

Helm chart: kubernetes-dashboard/kubernetes-dashboard
Helm chart version: 5.4.1
image:
  repository: kubernetesui/dashboard
  tag: v2.6.0
image:
  repository: kubernetesui/metrics-scraper
  tag: v1.0.8

Commands:
helm pull kubernetes-dashboard/kubernetes-dashboard --version 5.4.1
helm upgrade -f values.yaml --install kubernetes-dashboard --namespace cluster-system kubernetes-dashboard/kubernetes-dashboard --version 5.4.1

Error Message:
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "APIService" in version "apiregistration.k8s.io/v1beta1"

### What did you expect to happen?

Install without errors

### How can we reproduce it (as minimally and precisely as possible)?

helm pull kubernetes-dashboard/kubernetes-dashboard --version 5.4.1
helm upgrade -f values.yaml --install kubernetes-dashboard --namespace cluster-system kubernetes-dashboard/kubernetes-dashboard --version 5.4.1

### Kubernetes Dashboard version

v2.6.0

### Kubernetes version

1.22

**Comment by floreks** [comment]
I don't think we are using the `apiregistration.k8s.io/v1beta1` in any of our deployment files. I have tried to reproduce but everything works on my side.

### Kubernetes Version
```bash
$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

### Helm Version
```bash
$ helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

### Installation
```bash
$ helm install -n kubernetes-dashboard dashboard kubernetes-dashboard/kubernetes-dashboard

NAME: dashboard
LAST DEPLOYED: Sun Jun  5 21:06:51 2022
NAMESPACE: kubernetes-dashboard
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
*********************************************************************************
*** PLEASE BE PATIENT: kubernetes-dashboard may take a few minutes to install ***
*********************************************************************************

Get the Kubernetes Dashboard URL by running:
  export POD_NAME=$(kubectl get pods -n kubernetes-dashboard -l "app.kubernetes.io/name=kubernetes-dashboard,app.kubernetes.io/instance=dashboard" -o jsonpath="{.items[0].metadata.name}")
  echo https://127.0.0.1:8443/
  kubectl -n kubernetes-dashboard port-forward $POD_NAME 8443:8443
```

No errors. Everything is running.

**Comment by floreks** [comment]
Closing as there is no response from the OP.

/close
