### ISSUE TITLE
K8s dashboard upgrade for v1.22

### ISSUE THREAD

**Issue by pallasite99** [kubernetes/dashboard#7169]
### What would you like to be added?

* Compatibility for 1.22 with kubernetes-dashboard.
*  Currently the release page only mentions compatibility for 1.21, 1.23 and 1.24 with the releases in place.

### Why is this needed?

* upgrading addons related to cluster from 1.21 to 1.22
* upstream support for dashboard in 1.22

**Comment by floreks** [comment]
Unfortunately, we officially can only support the latest K8S version at the time of the Dashboard release. Older versions should work just fine. It only means that in case some features do not work with the unsupported K8S version, we will not provide official fixes for them.

/close

**Comment by pallasite99** [comment]
So just for info, would it be safe for us to do v2.4.0 for 1.22?

That seems to be the one closest to 1.22 release

**Comment by pallasite99** [comment]
Cool, thanks
