### ISSUE TITLE
Break v1 presentation layer compatibility

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#719]
I think we should break v1 api compatibility and say that next major release cannot be updated in place (i.e., new version will not be able to talk to the old version). This is because our v1 presentation layer API will needs many changes to support scalability for the future. We don't have many prod users anyway and the update will still be very easy.

1. We should pass ObjectMeta-like info with each object, instead of copy&pasting name, namespaces, etc. 
2. Api should be singular (i.e., `api/v1/pod/` instead of `api/v1/pods/`) - with this we can have lots of generic code that takes resource type and then does operation on it. 

@floreks @cheld @digitalfishpond  @joeatwork What do you think?

**Comment by cheld** [comment]
Hmm...not sure if I understand correctly. We talk about the backend / presentation logic? This is just an internal API used only by Dashboard, isn't? Rolling upgrade of Dashboard should be a problem.

**Comment by cheld** [comment]
Ok, I think I got it. In angular, the browser is not reloaded with every click, so it can happen that the old browser will access new backend during rolling upgrade...

IMHO, breaking compatibility is ok

**Comment by bryk** [comment]
Yeah, so for example:
The endpoint `/api/v1/replicationcontrollers` will no longer exist or return different data that current released version of Dashboard expects. With that, you cannot do, e.g., in place rolling update, because old frontend can hit new presentation layer API and vice versa. But if you turn down all old instances and turn up new version it'll all work. 
This makes things much easier for us and a little bit harder for updaters.

**Comment by floreks** [comment]
> Api should be singular (i.e., api/v1/pod/ instead of api/v1/pods/) - with this we can have lots of generic code that takes resource type and then does operation on it.

I like this idea. So for example if we want to list objects of one type then we use `api/v1/resource/list` instead of `api/v1/resources`, right?

> We should pass ObjectMeta-like info with each object, instead of copy&pasting name, namespaces, etc.

Yes, this would allow to remove part of code that is always repeated in our structures. 

Update should not be a problem as dashboard is stateless. We do not have to migrate anything. Updaters can just tear it down and bring up new version.

**Comment by cheld** [comment]
@bryk the user would get an error page and press reload and everything would work again. Dashboard is not used by a lot of users concurrently. Most likely the only active session is the person that triggered the rolling update. IMHO no problem.

**Comment by bryk** [comment]
Perfect. I see general agreement here. 

> I like this idea. So for example if we want to list objects of one type then we use api/v1/resource/list instead of api/v1/resources, right?

This may be, but I didn't have such plans. I proposed only making api endpoints singular. With all the semantics unchanged. But suffixing with `/list` looks also good. 
The point is that from resource type we'll be able to get api endpoints and all this. Pluralization is hard to do programatically :)
