### ISSUE TITLE
5s cancel

### ISSUE THREAD

**Issue by icyxp** [kubernetes/dashboard#7218]
### What happened?

![image](https://user-images.githubusercontent.com/1527903/176100689-2e8bd3bc-c09f-480f-9c6e-e7a244a2feb6.png)

### What did you expect to happen?

![image](https://user-images.githubusercontent.com/1527903/176100773-115298ea-6153-4861-9ae7-9f539213eb79.png)

### How can we reproduce it (as minimally and precisely as possible)?

reply xhr is ok
![image](https://user-images.githubusercontent.com/1527903/176100915-e54bac85-5be2-4b1f-87cb-aa3cf7b5cd4c.png)

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

2.6.0

### Kubernetes version

1.17

**Comment by floreks** [comment]
Go to settings and increase resource refresh time. It should fix it.

/close

**Comment by icyxp** [comment]
@floreks  Can you provide a document? I didn't find the configuration, thanks
