### ISSUE TITLE
set a user/pass to the dashboard

### ISSUE THREAD

**Issue by herbalizer404** [kubernetes/dashboard#722]
#### Issue details
I just configured my first dashboard, but there is no security to access to it. How do I set a user/pass to secure the dashboard.

thank you

##### Environment

Dashboard version:  1.0.1
Kubernetes version: 1.2.3
Operating system: debian

**Comment by cheld** [comment]
access it over https://<api-server>/UI

normal authentication of API server will be used

**Comment by maciaszczykm** [comment]
Closing as stale. 

Security layer is in our plans, check #964.
