### ISSUE TITLE
how can access into local enviroment with https

### ISSUE THREAD

**Issue by johnfelipe** [kubernetes/dashboard#7311]
### What happened?

http://192.168.0.19:8080/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login

that is local ubuntu 20 instance with vcenter

![SNAG-0059](https://user-images.githubusercontent.com/428820/182037064-cfd2a7f3-41ab-4978-b6fc-57c0f5ff41eb.png)

### What did you expect to happen?

enter in dashboard

### How can we reproduce it (as minimally and precisely as possible)?

i run all aws eks with
https://www.eksworkshop.com/beginner/040_dashboard/connect/

but not using cluod9 
im using a simple local ubuntu env

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

latest

### Kubernetes version

latest

**Comment by floreks** [comment]
Error is quite clear here. There is even a link to documentation. This will not be changed and is working as expected. Use HTTPS.

/close

**Comment by johnfelipe** [comment]
yes dear, but using makecert or something?
