### ISSUE TITLE
create a self-signed certificate for enter with ip LAN vcenter enviroment

### ISSUE THREAD

**Issue by johnfelipe** [kubernetes/dashboard#7312]
### What would you like to be added?

https://github.com/fresh2dev/ShinyStudio/blob/master/certify.sh

create a self-signed certificate, or to request one from LetsEncrypt (more on that).

### Why is this needed?

enable use ip address with ssl

**Comment by floreks** [comment]
I have honestly no idea what this issue is about and what is expected to change in Dashboard.

**Comment by floreks** [comment]
Closing as I am not sure what this issue is about.

/close
