### ISSUE TITLE
exec into pod issue - Kubernetes dashboard

### ISSUE THREAD

**Issue by rshiva777** [kubernetes/dashboard#7320]
### What happened?

I am trying to exec into kubernetes pod from dashboard UI, within 2 to 3 seconds, getting the below error

In UI:
------
**Sending error: Error: http status 404 (or) Server lost session**

In dashboard logs:
--------------------

2022/08/01 11:04:32 [2022-08-01T11:04:32Z] Outcoming response to 10.0.11.1 with 200 status code
2022/08/01 11:04:34 [2022-08-01T11:04:34Z] Incoming HTTP/1.1 GET /api/v1/pod/test/nginx/container request from 100.102.124.192:
2022/08/01 11:04:34 [2022-08-01T11:04:34Z] Outcoming response to 10.0.11.1 with 200 status code
E0801 11:04:35.190647       1 v2.go:105] **sockjs: session not in open state**
2022/08/01 11:04:35 sockjs: session not in open state
2022/08/01 11:04:35 handleTerminalSession: can't Recv: sockjs: session not in open state
2022/08/01 11:04:37 [2022-08-01T11:04:37Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 10.0.11.1:
2022/08/01 11:04:37 Getting list of namespaces
2022/08/01 11:04:37 [2022-08-01T11:04:37Z] Outcoming response to 10.0.11.1 with 200 status code

### What did you expect to happen?

Pod exec should to timeout or get error unless i do manually exit from shell

### How can we reproduce it (as minimally and precisely as possible)?

Install dashboard version 2.5.0 onto cluster and try to access any of the pods from dashboard UI

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Kubernetes Dashboard version

2.5.0

### Kubernetes version

1.20

**Comment by floreks** [comment]
The unsupported version was used. Use the latest version and make sure to use the supported k8s version also.

/close

**Comment by rshiva777** [comment]
@floreks  I am using kubernetes dashboard version v2.5.0 (image: kubernetesui/dashboard:v2.5.0) and cluster version 1.20.5

I am able to see dashboard version from https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
Could you please provide the specific version, if the above mentioned once is incorrect

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/releases/tag/v2.6.0
