### ISSUE TITLE
Remove created secrets permissions if the dashboard is in another namespace

### ISSUE THREAD

**Issue by JJotah** [kubernetes/dashboard#7330]
### What happened?

If you deploy the kubernetes dashboard in another namespace (like dashboard namespace) 

It's showing this error:

- panic: secrets is forbidden: User "system:serviceaccount:dashboard:kubernetes-sa" cannot create resource "secrets" in API group "" in the namespace "dashboard"

If I give creation permissions in this namespace is working fine but after that the dashboard will no create any secret

### What did you expect to happen?

Deploy dashboard in another namespace

### How can we reproduce it (as minimally and precisely as possible)?

Deploy https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml in another namespace

### Kubernetes Dashboard version

2.6.0

### Kubernetes version

1.24.1

**Comment by JJotah** [comment]
When we give the create role secrets for the service account automatically the pod will create this secret
kubernetes-dashboard-key-holder

**Comment by JJotah** [comment]
I'm working on this topic

**Comment by floreks** [comment]
If you want to deploy Dashboard in a different namespace you should:
1. Download yaml file and change `kubernetes-dashboard` namespace to the one of your choice
2. Updated [--namespace](https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended.yaml#L200) argument

It should work after that.

**Comment by JJotah** [comment]
Hi @floreks,
Even if we changed the namespace also the secrets are hardcored in the go code.
I will work on give this new feature into the code.

**Comment by floreks** [comment]
I don't think so. We have updated the logic quite a long time ago to use namespace from the dashboard binary `--namespace` argument. All our dashboard exclusive resources are using it. Only the resource names are hardcoded, not the namespace itself. 

`panic: secrets is forbidden: User "system:serviceaccount:dashboard:kubernetes-sa" cannot create resource "secrets" in API group "" in the namespace "dashboard"`

This error also does not seem right. I think your Dashboard is working, but you misunderstood how it works. You have to create a user account with proper privileges on your own since Dashboard itself does not have any privileges. We only act as a proxy between user and API server and do not manage the privileges.

**Comment by JJotah** [comment]
Hi @floreks, 
The kubernetes dashboard needs update, watch and get permissions. Not create because the rbac are hardcording the secrets name (thing that is good to minimize the security risks) so we need to change the yaml file to give create secrets permissions without hardcording the secrets as a resourceNames. Because the application dashboard can't hardcore the secret in the go code. I want to give the possibility to change the secrets name and resources to give more possibilities for users. 
I created a helm chart with dashboard, oauth and dex but the secrets on the dashboard are in the code. If you want to update the helm chart and change the name of the secrets the dashboard will fail

**Comment by floreks** [comment]
The lack of create secrets permissions for Dashboard is intentional and we don't want to change it. That's why secret is created via yaml and should not be deleted. We can only agree to fully scoped permissions with resourceName provided. It's done by design to increase security.

**Comment by JJotah** [comment]
@floreks
Yeah I understood the point but can we make the possibility to change the secrets name?
That's my main point of this topic.

**Comment by floreks** [comment]
> Yeah I understood the point but can we make the possibility to change the secrets name?
That's my main point of this topic.

You might have missed this part as I have edited my message:
> We also don't really want to allow name changes of resources right now. It would require a complete overhaul of our config system. This is a big change and as mentioned in the README we do have a soft code freeze now.
