### ISSUE TITLE
"Require contributors to sign off on web-based commits" is not enabled.

### ISSUE THREAD

**Issue by kaovilai** [kubernetes/dashboard#7331]
### What would you like to be added?

People with repository settings access should go to https://github.com/kubernetes/dashboard/settings and check
- [x] **Require contributors to sign off on web-based commits** 
 Enabling this setting will require contributors to sign off on commits made through GitHub’s web interface. Signing off is a way for contributors to affirm that their commit complies with the repository's terms, commonly the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). [Learn more about signing off on commits](https://docs.github.com/en/organizations/managing-organization-settings/managing-the-commit-signoff-policy-for-your-organization).

### Why is this needed?

Checking this options assists with passing DCO check when editing in GitHub web editor.

**Comment by maciaszczykm** [comment]
It's done.
