### ISSUE TITLE
creating-sample-user.md recommended command for token creation failing

### ISSUE THREAD

**Issue by nsteblay** [kubernetes/dashboard#7337]
### What happened?

I'm attempting to get the kubernetes dashboard running on an M1 MBP with Docker Desktop.  I'm following the direction on the creating-sample-user.md page.

When executing the "kubectl -n kubernetes-dashboard create token admin-user" command I get the following output:

Error: must specify one of -f and -k
error: unknown command "token admin-user"
See 'kubectl create -h' for help and examples

### What did you expect to happen?

I expected to see the token I need to login to the dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

Run the commands on a MBP M1 Pro.  I simply followed the directions on README.MD and creating-sample-user.md.  

### Anything else we need to know?

I don't think so.  I am using the latest Docker Desktop on the MBP M1 Pro.  The dashboard appears to be working but I can't log in with an authorized user by following the directions provided.  

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

v2.6.0

### Kubernetes version

v1.24.1

**Comment by floreks** [comment]
What is the output of `kubectl version --short`?

**Comment by robozb** [comment]
+1

**Comment by maciaszczykm** [comment]
@robozb Can you provide details, especially output of `kubectl version --short` as @floreks mentioned?

**Comment by Writetoprabhat** [comment]
I am facing the same problem. Here is the output from kubectl version --short
Client Version: v1.23.0
Server Version: v1.24.2

**Comment by floreks** [comment]
As per the `kubectl` changelog for [v1.24](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md):
> `kubectl create token` can now be used to request a service account token, and permission to request service account tokens is added

It isn't available in older versions.

/close

**Comment by robozb** [comment]
> @robozb Can you provide details, especially output of `kubectl version --short` as @floreks mentioned?

root@kubernetes-master-ubuntu:~# kubectl version --short
Client Version: v1.23.5
Server Version: v1.23.5

Finally I could solve the problem with these commands:
info from here: https://stackoverflow.com/a/46720109

kubectl -n kube-system get secret
...Any name from the list...

For example: deployment-controller-token-rvc5r
kubectl -n kube-system describe secret deployment-controller-token-rvc5r

And here is the token: 
Name:         deployment-controller-token-rvc5r
Namespace:    kube-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: deployment-controller
              kubernetes.io/service-account.uid: 80ac0699-77ab-4003-bbbd-3907102dcb7e

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1099 bytes
namespace:  11 bytes
token:      eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5aQU1tWFlrLXFCVzF2VF9TQ0FmTnlrd3VzQUoxemZLM2VmWjcwOEFjZFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3...

**Comment by xiongyu0523** [comment]
The short answer from the previous docs for people who had the problem on an old version.

`kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get sa/admin-user -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"`
