### ISSUE TITLE
Error on manual scaling deployment

### ISSUE THREAD

**Issue by jorenvandeweyer** [kubernetes/dashboard#7344]
### What happened?

I tried scaling a deployment manually and received an error 

<img width="755" alt="image" src="https://user-images.githubusercontent.com/22756123/184076207-3f1ac64e-d2b8-4035-9137-f9a26af15e5d.png">

### What did you expect to happen?

Scale the deployment from 1 to 2 pods.

### How can we reproduce it (as minimally and precisely as possible)?

Scale a deployment

### Anything else we need to know?

The dashboard is hosted on scaleway (managed kubernetes)

Support:

> The deployed dashboard is the following image: https://hub.docker.com/r/kubernetesui/dashboard
> Based on your cluster version, you have the v2.6.0, which is apparently their latest release.
> 
> May I invite you to open a GitHub issue please? https://github.com/kubernetes/dashboard/issues
> We do not alter the image, so the bug is from the upstream and I believe they will be interested.

### What browsers are you seeing the problem on?

Chrome, Safari

### Kubernetes Dashboard version

v2.6.0

### Kubernetes version

v1.23.9

**Comment by floreks** [comment]
Unfortunately, I can't reproduce that. Tried on fresh `v1.21` and `v1.24` clusters and the scale feature works as expected. Is there anything special about your configuration that might cause this?

**Comment by maciaszczykm** [comment]
@jorenvandeweyer Can you provide deployment's YAML?

**Comment by jorenvandeweyer** [comment]
I upgraded to v1.24 and it seemed to be fixed.
