### ISSUE TITLE
issue in 'Getting a Bearer Token' while setting up user for dashboard

### ISSUE THREAD

**Issue by hks1** [kubernetes/dashboard#7362]
### What happened?

Running 'Getting a Bearer token' step from creating-sample-user.md.
It gives following error:

```
$ kubectl -n kubernetes-dashboard create token admin-user
```
```
Error: must specify one of -f and -k

error: unknown command "token admin-user"
See 'kubectl create -h' for help and examples
```

### What did you expect to happen?

As per documentation, expectation is
- to get back the token which could be used for login to dashboard

### How can we reproduce it (as minimally and precisely as possible)?

follow steps to create a sample user as per [documentation](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md)

### Anything else we need to know?

Running kubernetes with Docker desktop

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

v2.2.0+0.g0a30039e0

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"
windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"
linux/amd64"}

**Comment by maciaszczykm** [comment]
You didn't provide kubectl output.

**Comment by floreks** [comment]
Duplicate. Exact same issue was closed today. Search in closed issues.

/close

**Comment by hks1** [comment]
> You didn't provide kubectl output.

updated
