### ISSUE TITLE
v2.6.1: search is broken

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#7367]
### What happened?

one can't search on v 2.6.1:

![image](https://user-images.githubusercontent.com/297498/184919143-80e41fdf-9660-4563-a053-e59fcedc77d9.png)

The issue seems to be on the server side:

the request:
https://kdash.lightboxre.com/api/v1/cronjob/kubernetes-dashboard?itemsPerPage=50&page=1&sortBy=d,creationTimestamp&filterBy=name,search_is_broken

the server response:
```
the server could not find the requested resource
```

the server logs do not show anything interesting.

### What did you expect to happen?

it should show results :)

### How can we reproduce it (as minimally and precisely as possible)?

try to search anything in the upser search bar (next to the namespace pull down) :)

### Anything else we need to know?

Works on v2.6.0, tested on AWS EKS v1.20

Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

v2.6.1

### Kubernetes version

1.20

**Comment by floreks** [comment]
K8S `v1.20` is not officially supported by the `v2.6.1`. client-go and API version updates might have broken the search for older K8S versions. If the issue persists on the supported version, we can investigate.

/close
