### ISSUE TITLE
kubernetes dashboard recommended.yaml is missing a tolerance when trying to run on control plane

### ISSUE THREAD

**Issue by saikyt** [kubernetes/dashboard#7378]
### What happened?

Installed k8s using kubeadm, kubernetes dashbaord and metrics always remained in **pending** state.
```
m8s@m8scontrol:~/mydev/m8s$ kubectl get pods --all-namespaces
NAMESPACE              NAME                                        READY   STATUS    RESTARTS   AGE
calico-apiserver       calico-apiserver-bf4446bb4-qsqrc            1/1     Running   0          27h
calico-apiserver       calico-apiserver-bf4446bb4-xsgwl            1/1     Running   0          27h
calico-system          calico-kube-controllers-5c69d6b448-qqh5v    1/1     Running   0          27h
calico-system          calico-node-stx8j                           1/1     Running   0          27h
calico-system          calico-typha-545c786f9b-pd87g               1/1     Running   0          27h
calico-system          csi-node-driver-2xkq5                       2/2     Running   0          27h
kube-system            coredns-6d4b75cb6d-m6lz5                    1/1     Running   0          27h
kube-system            coredns-6d4b75cb6d-mb4zm                    1/1     Running   0          27h
kube-system            etcd-m8scontrol                             1/1     Running   289        27h
kube-system            kube-apiserver-m8scontrol                   1/1     Running   2          27h
kube-system            kube-controller-manager-m8scontrol          1/1     Running   0          27h
kube-system            kube-proxy-6hgzz                            1/1     Running   0          27h
kube-system            kube-scheduler-m8scontrol                   1/1     Running   291        27h
kubernetes-dashboard   kubernetes-dashboard-6c75475678-7pdnq       0/1     Pending   0          3m24s
kubernetes-dashboard   kubernetes-dashboard-6d5c5bbbd8-fp6kt       0/1     Pending   0          40s
tigera-operator        tigera-operator-7ff575f7f7-7kvjd            1/1     Running   0          27h
```
Notice there are two taints to the control-plane node.

NAME         STATUS   ROLES           AGE   VERSION
m8scontrol   Ready    control-plane   27h   **v1.24.3**
```
m8s@m8scontrol:~/mydev/m8s$ kubectl describe node m8scontrol
Name:               m8scontrol
Roles:              control-plane
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=m8scontrol
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node.kubernetes.io/exclude-from-external-load-balancers=
Annotations:        csi.volume.kubernetes.io/nodeid: {"csi.tigera.io":"m8scontrol"}
                    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 192.168.1.75/24
                    projectcalico.org/IPv4VXLANTunnelAddr: 172.16.131.64
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 20 Aug 2022 16:35:22 -0400
Taints:             node-role.kubernetes.io/control-plane:NoSchedule
                    node-role.kubernetes.io/master:NoSchedule
```

### What did you expect to happen?

Both kubernetes dashboard and metrics should be in **running** state 

### How can we reproduce it (as minimally and precisely as possible)?

Install k8s kubeadm on Ubuntu 22.04.1 LTS
Install Callico CNI
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.6.1/aio/deploy/recommended.yaml

### Anything else we need to know?

Both the tolerations should be added to recommend.yaml. This fixed my issue
```
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
```

### Kubernetes Dashboard version

2.6.1

### Kubernetes version

1.24.3

**Comment by floreks** [comment]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation

/close

**Comment by saikyt** [comment]
I am sorry why would I taint all nodes on the control plane if I just want to run Kubernetes Dashboard on it ?? Would it not open up to run "any" pods? The whole point of opening this issue was to fix the tolerance so we can allow only Kubernetes Dashboard on the control plane if we wanted it to.
      **# Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule**

**Comment by floreks** [comment]
This is not something we want to do by default. You can manually update the yaml if you want to run on the control plane node.

**Comment by saikyt** [comment]
Why do we have this entry by default then ?
tolerations:
**- key: node-role.kubernetes.io/master
effect: NoSchedule**

**Comment by floreks** [comment]
In most prod cases running applications on the control plane is not desired, that's why this is our default. If you want, you can remove the taints manually using `kubectl taint` or edit the YAML and redeploy.

**Comment by saikyt** [comment]
Sorry if I am not clear.  The file you have checked into this repository has the tolerance added by default. This means you are allowing the Kubernetes Dashboard to run on the master ( now called the control plane). Based on what you are saying this line should be commented out or removed by default not to allow dashboard pods to run on it. People who want to run the Kubernetes dashboard should add this tolerance by default instead of tainting the master node which is less secure because they can schedule any pods (not just Dashboard).
