### ISSUE TITLE
Deployment Manager

### ISSUE THREAD

**Issue by ekozan** [kubernetes/dashboard#74]
I think permit to deploy app via the new kubernetes deploy manager can be an overkill feature for this dashboard, any plans for implement this feature ?

**Comment by bryk** [comment]
I hope that this will happen in the future. At the moment we do not have solid plans for support for deployment objects, however.

@kenmoore @aronchick

**Comment by bryk** [comment]
Closing as stale.

**Comment by marcolenzo** [comment]
Excuse me if I bump this old discussion. Is the decision of not supporting deployments still holding?

**Comment by bryk** [comment]
Deployment resources? The ones from here: http://kubernetes.io/docs/user-guide/deployments/

We'll support them soon.


Deployment manager/helm (https://github.com/kubernetes/helm): this is unknown yet.

**Comment by marcolenzo** [comment]
Yeah I was referring to the Kubernetes Deployments. Thanks a lot for the info!
