### ISSUE TITLE
Localization of all the text message across dashboard.

### ISSUE THREAD

**Issue by taimir** [kubernetes/dashboard#742]
#### Issue details
With PR https://github.com/kubernetes/dashboard/pull/725 we now have a way to do localization (l10n) of dashboard, translating all of the text into different languages. The translations are then automatically picked up by the build pipelines and integrated into our production version.

For this, we can define MSG variables like this:
```{js}
/**
 * @export
 * @type string
 * @desc an example text message to be translated
 */
this.MSG_HELLO_WORLD = goog.getMsg('Text message to translate');
```
And then reference them in our HTML templates:
```{html}
<some-html-block>
<!-- localized automatically based on the language selected by the user -->
{{ctrl.MSG_HELLO_WORLD}}
</some-html-block>
```

Now the quesiton arises, how we should organize those variables. One possibility would be placing them as members in the respective controllers, inline in our angular `.js` code. Another would be to bundle all message up and somehow separate them from the angular files of the rest of the application (e.g. wrap them up in a dedicated service?).

Notice that the actual human translation happens inside separate `message-<locale>.xtb` files, automatically created during the build process. Therefore this issue does not directly concern the actual translators (they are not supposed to look at the code).

Feel free to discuss.

@floreks @f-higashi @cheld @bryk @maciaszczykm @digitalfishpond

**Comment by bryk** [comment]
I think it is best to place the messages in controllers. This is closest to the place they are used.

**Comment by taimir** [comment]
@bryk I just started extracting the messages into the controllers yesterday and the ones for `deplofromsettings_controller` take up more than 350 lines. How about putting the messages for a given controller (e.g. `deployfromsettings`) into a file right next to it (e.g. `deployfromsettings_i18n.js`) and then importing this file into the controller `deployfromsettings_controller.js` as a member variable? With proper naming the `i18n` files will be right next to their respective controllers. What do you think?

Obviously it is a trade-off between keeping the cohesion and not over-cluttering the controllers.

**Comment by bryk** [comment]
I see. How about doing the same, but adding stuff to the bottom of the controller file? It is one less file per controller (we currently have lots of them...) and the number of lines does not hurt here, because is it I18N config. 

I agree that putting this inside a controller pollutes it. But moving to the bottom of the file shouldn't. 

What do you think?

**Comment by taimir** [comment]
Personally, as long as it does not increase the scroll time to the actual methods of each controller, I am fine with your idea. What do the others think? @floreks

**Comment by floreks** [comment]
I'd add i18n data at the end of the controller file as @bryk proposed. We have already many files in our tree and I wouldn't want to make it bigger and add new file per controller/component.

**Comment by taimir** [comment]
Great! Now we have a unified solution. I'll continue working on this then :) If anyone else has something to add, please feel free to do so.

**Comment by bryk** [comment]
If something like this works, then it'd be perfect. Basically, the shorter the better :) 

```js
class Controller {
  constructor() {
  /** @export */
  this.messages = messages; 
  }
}

const messages = {
   /** @export @desc The foo */
   MSG_FOO: 'foo',
   /** @export @desc The bar */
   MSG_BAR: 'bar',
};
```

**Comment by taimir** [comment]
yes, so that's what I'm doing exactly. The only thing I'll have to try out is if I can put the annotations on the same line as you did, in order to reduce the space those constants eat up.

**Comment by bryk** [comment]
Done? I think yes. If there's something that remains, it shouldn't be tracked here. Because otherwise this issue would be always open

**Comment by taimir** [comment]
:+1:
