### ISSUE TITLE
Korean localization for dashboard (prepare for 2.7.0)

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/dashboard#7424]
### What would you like to be added?

This issue is to invite Korean contributors and assign localization tasks.

## How to contribute

- leave a comment to get involved with this issue (I'd like to invite native Korean or folks who speak Korean well) and let me assign task lines to contributors.

- Procedure 
  - Search `<target state="new">` from the https://github.com/kubernetes/dashboard/blob/master/i18n/ko/messages.ko.xlf and translate strings between `<target state="new">`Strings to translate`</target>` within assigned lines.
  - Change `<target state="new">` to `<target>`
  - Open a PR (target branch is `master`).

- Note
  - This localization effort is related with 2.7.0 release. So, please understand the contribution needs to be fast :)
  - Please note that contributing to a single file can introduce conflicts easily. Please fetch and rebase frequently. :)

- Some references
  - #5029
  - #4819
  - #4174
  - #7415

### Why is this needed?

For 2.7.0 release, Korean contents need to be updated accordingly.

- related issue: #7316 (https://github.com/kubernetes/dashboard/pull/7316#issuecomment-1232413725)

**Comment by seokho-son** [comment]
- [ ] 1 - 500 : TBD
- [ ] 501 - 1000 : TBD
- [ ] 1001 - 1500 : TBD
- [ ] 1501 - 2000 : TBD
- [ ] 2001 - 2500 : TBD
- [ ] 2501 - 3000 : TBD
- [ ] 3001 - 3500 : TBD
- [ ] 3501 - 4000 : TBD
- [ ] 4001 - 4500 : TBD
- [ ] 4501 - 5000 : TBD
- [ ] 5001 - 5500 : TBD
- [ ] 5501 - 6000 : TBD
- [ ] 6001 - 6662 (EOL) : TBD

**Comment by bconfiden2** [comment]
1 - 500 시도하겠습니다 !!

**Comment by seokho-son** [comment]
Please note that contributing to a single file can introduce conflicts easily. Please fetch and rebase frequently. :)

**Comment by rollony** [comment]
1001 - 1500 해보겠습니다!

**Comment by Seo-yul** [comment]
1501 - 2000 작업 할당 부탁드립니다~!

**Comment by gy-ulbak96** [comment]
2001-2500 할당 부탁드립니다 :)

**Comment by jinnypark9393** [comment]
2501 - 3000 해보겠습니다 :)

**Comment by onestone9900** [comment]
3501 - 4000 해보겠습니다 !! :)

**Comment by seokho-son** [comment]
@rollony 올려주신 PR은 머지되었습니다! 감사합니다. :)
Task 하나 더 해결해주실 수 있을까요? ㅎㅎ

**Comment by rollony** [comment]
> @rollony 올려주신 PR은 머지되었습니다! 감사합니다. :) Task 하나 더 해결해주실 수 있을까요? ㅎㅎ

리뷰 감사합니다 :) 네 4001 - 4500도 한번 해보겠습니다!

**Comment by NayeonKeum** [comment]
5001 - 5500 해보겠습니다!

**Comment by seokho-son** [comment]
Thanks to all !!

/close
