### ISSUE TITLE
Allow GetExternalEndpoints to handle unversioned.LabelSelector

### ISSUE THREAD

**Issue by Seb-Solon** [kubernetes/dashboard#743]
Hi,

The function GetExternalEndpoints from common package  https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/common/endpoint.go#L36 takes a map[string]string as parameter. This does not match the type of "new" label selector : unversioned.LabelSelector

As daemonset.Spec.Selector is a unversioned.LabelSelector, daemon cannot use this function properly. It could be good to be able to get endpoints with those selectors too.

IsLabelSelectorMatching and IsSelectorMatching are introduced in #510. It may help to solve the issue

**Comment by floreks** [comment]
`unversioned.LabelSelector` type is actually only used by new types introduced in `extensions` package. We'd have to introduce new method, one for old types and one for new ones.

From what I understand `MatchExpression` allows to target subset of resources in more flexible way and `MatchLabels` is simplified to expression `key in (value) and `key-2 in (value-2)...`.

For cases when we have old object i.e. service and we want to get related replica sets we have to use `MatchLabels` anyway as service contains only labels map.

Are there any plans to extend already existing object such as services to support new label selectors?

**Comment by bryk** [comment]
@floreks Are we doing this today?

**Comment by floreks** [comment]
Probably not. I'm not sure how to proceed with that. There are too many open points. This should be more clear once we start adding related services to all resources.

**Comment by maciaszczykm** [comment]
It seems, that code changed a lot since then and issue can be closed. Please reopen if I am wrong.
