### ISSUE TITLE
Kubernetes Dashboard Token Expiration Issue 

### ISSUE THREAD

**Issue by ankit-unicloud** [kubernetes/dashboard#7444]
### What would you like to be added?

I have configured Kubernetes Dashboard in my AKS.

I have used token system to login in dashboard but after generating token it is going to expired after few minutes. and need regenerate token again and again. 

I need to setup an static token to login kubernetes Dashboard for permanent use.

 

### Why is this needed?

i needed this because i am not use kubernetes dashboard.

**Comment by ankit-unicloud** [comment]
I have configured token-ttl=0 but still token gets expired after few minutes.
![image](https://user-images.githubusercontent.com/109526042/189680173-86cee5ad-b104-47d9-96ca-2dbbb64c76ea.png)

**Comment by floreks** [comment]
Then you need to generate the token used to log in without expiration time. The steps to do this depend heavily on your provider and k8s installation.

This is not strictly a Dashboard issue. Using kubectl with this token would most probably result in the same issue.

**Comment by ankit-unicloud** [comment]
Can you share the steps or commands to generate token without expiration time.

**Comment by floreks** [comment]
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

There is a "kubectl create token" documentation. It supports duration parameter.
