### ISSUE TITLE
Use renovate instead of dependabot

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#7470]
### What would you like to be added?

Switch from dependabot to renovate (see: https://docs.renovatebot.com/getting-started/installing-onboarding/).

### Why is this needed?

Dependabot doesn't support Yarn v2 which we are using (see: https://github.com/dependabot/dependabot-core/issues/1297).

**Comment by shu-mutou** [comment]
Now dependabot seems to support yarn v2.
https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-1285998196

Would you like to migrate to renovate?

**Comment by maciaszczykm** [comment]
@shu-mutou We can keep using dependabot as request for renovate is still not approved at org level.

**Comment by shu-mutou** [comment]
@maciaszczykm Got it. I would like to investigate restoring npm dependency checking and yarn support.

**Comment by shu-mutou** [comment]
Re-enabled npm update check with #7574

**Comment by maciaszczykm** [comment]
Let's close it for now. If we will get approval for renovate we can reconsider. Most important thing is fixed already.
