### ISSUE TITLE
Option to skip SSL verification or use kubecfg

### ISSUE THREAD

**Issue by oba11** [kubernetes/dashboard#748]
#### Issue details
I'm having trouble connecting the dashboard to the kubernetes api 

##### Environment

```
Dashboard version: 1.0.1
Kubernetes version: 1.2.4
Operating system: CoreOS on AWS
```

##### Steps to reproduce

Create kubernetes cluster with self-signed SSL certificate (without admission control)
Add the option - --apiserver-host=https://kube-api:443

##### Expected result

Internal Server Error (500)
Get https://username:password@kube-api:443/api/v1/replicationcontrollers: x509: certificate signed by unknown authority

##### Comments
Currently do launch the cluster without service accounts/admission control but works with heapster and kube-dns by using mounting the kubecfg (with skip ssl verification) and passing the --kubecfg option to the args.

Initially got the error Get https://username:password@kube-api:443/api/v1/replicationcontrollers: x509: failed to load system roots and no roots provided but followed the instructions in https://github.com/kubernetes/dashboard/issues/620 to mount the ca-certs. 

I think if there could be a way to pass the kubernetes option `insecure-skip-tls-verify: true` or use the kubecfg like other cluster addon would work

**Comment by bryk** [comment]
We added support for kubeconfig files, but this hasn't been released yet. You'd be able to use config file the same as, e.g., in kubectl. 

Does this help?

**Comment by oba11** [comment]
It would really help, excited about the release.
Thanks alot @bryk

**Comment by bryk** [comment]
Btw, beta1 release has this. Feel free to test and provide feedback.

https://github.com/kubernetes/dashboard/releases/tag/v1.1.0-beta1

**Comment by bpradipt** [comment]
@bryk, I tested the new image successfully by passing custom kubeconfig file. Thanks

**Comment by oba11** [comment]
@bpradipt please can you share how you passed the kubeconfig file, I tried both `--kubeconfig="/tmp/config"` and `--kubecfg-file="/tmp/config"` but didnt seem to work.

Below is my output of printing the help

```
$ docker run -it --rm gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0-beta1 -h

Usage of /dashboard:
      --alsologtostderr value          log to standard error as well as files
      --apiserver-host string          The address of the Kubernetes Apiserver to connect to in the format of protocol://address:port, e.g., http://localhost:8080. If not specified, the assumption is that the binary runs inside aKubernetes cluster and local discovery is attempted.
      --heapster-host string           The address of the Heapster Apiserver to connect to in the format of protocol://address:port, e.g., http://localhost:8082. If not specified, the assumption is that the binary runs inside aKubernetes cluster and service proxy will be used.
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at value         when logging hits line file:N, emit a stack trace (default :0)
      --log_dir value                  If non-empty, write log files in this directory
      --logtostderr value              log to standard error instead of files (default true)
      --port int                       The port to listen to for incoming HTTP requests (default 9090)
      --stderrthreshold value          logs at or above this threshold go to stderr (default 2)
  -v, --v value                        log level for V logs
      --vmodule value                  comma-separated list of pattern=N settings for file-filtered logging
```

Thanks.

**Comment by bpradipt** [comment]
@oba11, there is no command line option to pass kubeconfig file. Either it needs to be in ${HOME}/.kube/config or the actual location available in the environment var KUBECONFIG.
May be a documentation might help.

Here is how I use the image on my setup
On x86_64
 docker run -itd -v /etc/hosts:/etc/hosts -v /etc/kubernetes/kubectl.pradipta:/etc/kubeconfig -e KUBECONFIG=/etc/kubeconfig -p 82:9090 gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0-beta1

On ppc64le
 docker run -itd -v /etc/hosts:/etc/hosts -v /etc/kubernetes/kubectl.pradipta:/etc/kubeconfig -e KUBECONFIG=/etc/kubeconfig -p 82:9090 gcr.io/google_containers/kubernetes-dashboard-ppc64le:v1.1.0-beta1

**Comment by oba11** [comment]
Thanks alot @bpradipt this works perfectly for me.

**Comment by bpradipt** [comment]
Great @oba11 .. I believe this issue can be closed now.
