### ISSUE TITLE
Actions > CD Helm has problem

### ISSUE THREAD

**Issue by Hokwang** [kubernetes/dashboard#7483]
### What happened?

please check your helm chart release process.

there's error so v5.11.0 didn't released.

### What did you expect to happen?

release v5.11.0

### How can we reproduce it (as minimally and precisely as possible)?

see Actions page

### Kubernetes Dashboard version

v.2.7.0

### Kubernetes version

1.22

**Comment by floreks** [comment]
Done in https://github.com/kubernetes/dashboard/pull/7486
