### ISSUE TITLE
Helm chart repo inaccessible

### ISSUE THREAD

**Issue by LedAlex** [kubernetes/dashboard#7494]
### What happened?

Helm chart repo at https://kubernetes.github.io/dashboard/ returns 404.

### What did you expect to happen?

![image](https://user-images.githubusercontent.com/27248144/194451164-ea845c1d-dcd5-4ffd-8e95-36eb2f037d9d.png)

### How can we reproduce it (as minimally and precisely as possible)?

Hit the link.

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

-

**Comment by floreks** [comment]
It was never accessible via browser. You only need it for the helm commands.

/close

**Comment by LedAlex** [comment]
Don't know what was fixed.
index.yaml was also inaccessible, neither helm or kubeapps were able to install chart.
Now it works.
![image](https://user-images.githubusercontent.com/27248144/194497115-61068216-5776-4784-9a6a-5de179659ae1.png)

**Comment by floreks** [comment]
Probably just a github issue. This page is stored here: https://github.com/kubernetes/dashboard/tree/gh-pages

**Comment by LedAlex** [comment]
Think so, same problem was with another pgAdmin repo.
