### ISSUE TITLE
Sorting pods by restart count

### ISSUE THREAD

**Issue by djkormo** [kubernetes/dashboard#7505]
### What would you like to be added?

I'd like to sort all pods in one namespace by restart count. 

### Why is this needed?

The goal is to find the most restarting pods.

**Comment by bdowling** [comment]
Generally speaking, I think you should be able to sort on just about any column.  I was surprised when I noticed you can't.

Seems a few issues popping up in this regard, #2794, #7535, #882(albeit more complicated).

Definitely any ordinal data column should be sortable, nominal alphabetically where possible.
