### ISSUE TITLE
Unable to autenticate the kubernetes dashboard using the Azure AD user account token

### ISSUE THREAD

**Issue by Melbink** [kubernetes/dashboard#7507]
### What happened?

We have deployed a kubernetes dashboard in the nprod cluster  The pods are up and running. I am not able to login to the kubernetes dashboard using the Azure AD RBAC user token, Would you be able to assist on finding the cause for this. I am able to login using the service account kubeconfig but not with the user account token.
The log error I am getting is as below:
Metric client health check failed: unknown (get services dashboard-metrics-scraper). Retrying in 30 seconds.

### What did you expect to happen?

Login successfully to kubernetes dashboard

### How can we reproduce it (as minimally and precisely as possible)?

use  the azure ad user token from the kube config and try to autenticate the kubernetes dashboard

### Kubernetes Dashboard version

dashboard:v2.0.4

### Kubernetes version

1.22.6

**Comment by aservera** [comment]
Same issue here

**Comment by floreks** [comment]
Duplicate of: https://github.com/kubernetes/dashboard/issues/6904, https://github.com/kubernetes/dashboard/issues/3081, https://github.com/kubernetes/dashboard/issues/3081

I can only recommend trying to configure the token in azure (strip obsolete information) to make it less than 4KB.
