### ISSUE TITLE
Kubernetes Dashboard Metric client health check failed

### ISSUE THREAD

**Issue by gvd22** [kubernetes/dashboard#7508]
### What happened?

When I open the Endpoint http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/ as instructed. Then the browser is trying to connect for at least two minutes. And after it I got this error message in my browser.
![grafik](https://user-images.githubusercontent.com/75640016/198126801-f20cee3c-7e8f-45f6-b868-eb9c9853de88.png)

So I looked into the logs from the pods

I think with the dashboard-metrics-scraper is everything okay.
`kubectl --namespace kubernetes-dashboard logs  dashboard-metrics-scraper-8c47d4b5d-dfdlx`
![grafik](https://user-images.githubusercontent.com/75640016/198126866-14ef4a09-8dac-48ef-90ba-82dd978e9374.png)

But when I look at the logs from the kubernetes-dashboard-67bd8fc546-flmpt I see that their is a problem with the metrics-scrapper. `kubectl --namespace kubernetes-dashboard logs kubernetes-dashboard-67bd8fc546-flmpt`
![grafik](https://user-images.githubusercontent.com/75640016/198127020-7df0e277-80b6-4268-8aa2-9f549d4b9ad7.png)

But I don't know how to solve this one?

### What did you expect to happen?

I expected that the website would show up so that I coul enter the token.

### How can we reproduce it (as minimally and precisely as possible)?

I installed a k3s cluster with three nodes.
![grafik](https://user-images.githubusercontent.com/75640016/198126574-6dfad691-1e1d-4614-a0b7-27d72179c179.png)

I deployed the Kubernetes dashboard on the cluster. 
![grafik](https://user-images.githubusercontent.com/75640016/198126738-80d1a5a0-d814-4405-b3d9-6040252f963c.png)

After this I installed the dashboard with the official documentation.

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

v1.24.6+k3s1

**Comment by floreks** [comment]
The metrics client health check is just a warning. This only means that the metrics would not be available in the frontend as they cannot be scraped. Frontend should work just fine. This actually looks like some kind of internal networking issue within your cluster. This is the K8S API server that throws this error, not the Dashboard itself.

**Comment by gvd22** [comment]
Thank you very much for the rapid response. 
Do you happen to know where I could find the error?

**Comment by gvd22** [comment]
I found out that the problem was something with the kubectl proxy which is installed on my device.
But thanks for your help :)

**Comment by floreks** [comment]
@gvd22 great that you figured it out :tada:
