### ISSUE TITLE
Workload status circle draws black

### ISSUE THREAD

**Issue by jc01rho** [kubernetes/dashboard#7515]
### What happened?

Workload status circle draws black

![image](https://user-images.githubusercontent.com/4989674/199420225-920dd858-3275-42ec-9120-ea6b9d07c7c6.png)

### What did you expect to happen?

green colored when running.

### How can we reproduce it (as minimally and precisely as possible)?

just access with token.

after yaml applied.
kubectl apply  -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jc01rho** [comment]
![image](https://user-images.githubusercontent.com/4989674/199422013-52aabd42-9fe9-4b22-b16f-29a5d3572f4e.png)


<path class="arc" d="M3.878048197299952e-15,-63.333333333333336A63.333333333333336,63.333333333333336,0,1,1,-3.878048197299952e-15,63.333333333333336A63.333333333333336,63.333333333333336,0,1,1,3.878048197299952e-15,-63.333333333333336Z" fill="" style="pointer-events: auto; user-select: auto;"></path>

**Comment by BOKYUNGGG** [comment]
why the fill attr is empty...?
![image](https://user-images.githubusercontent.com/113874167/201211855-ba0ca366-ec09-4a6e-b602-f3fcf4586229.png)

**Comment by jc01rho** [comment]
#7523 says same problem.
