### ISSUE TITLE
Unknown Error in pod logs

### ISSUE THREAD

**Issue by alexeych0** [kubernetes/dashboard#7517]
### What happened?

Can't access pod logs since the "Unknown Error" appears

![image](https://user-images.githubusercontent.com/26777982/199735719-7c005039-514c-4f5a-b1ee-f658553dcf00.png)

### What did you expect to happen?

Seeing the container logs screen

### How can we reproduce it (as minimally and precisely as possible)?

Choose any pod in a namespace and click "Logs" link in the list or "View Logs" icon in the pod itself

![image](https://user-images.githubusercontent.com/26777982/199735960-7cbdd5f3-41e0-477b-911c-22473efa81e2.png)

### Anything else we need to know?

Ubuntu 20.04.2 LTS Chromium 107.0.5304.87  
I also tried Firefox, the issue also appears

Meanwhile, I asked my college to try out the same steps with my token from Mac, and he had no problem viewing the logs

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

v2.7.0+0.g42deb6b32

### Kubernetes version

v1.19.15-gke.500

**Comment by maciaszczykm** [comment]
Is there anything in the browser's console?

**Comment by alexeych0** [comment]
```
net::ERR_BLOCKED_BY_CLIENT
```

Thanks) It was "Ublock Origin" extension. I have it installed in all my browsers

**Comment by maciaszczykm** [comment]
Can we close then?

**Comment by alexeych0** [comment]
Yes, of course
