### ISSUE TITLE
Dashboard, metrics server and controller not running crash loop back off

### ISSUE THREAD

**Issue by wahaj4311** [kubernetes/dashboard#7541]
### What happened?

I've am ampere arm64 machine. Just installed kubernetes (microk8s). After that I realized many things weren't working. Dashboard wasn't showing up.

**ubuntu@ampere:~$ kubectl -n kube-system get po
NAME                                         READY   STATUS             RESTARTS        AGE
calico-node-xr52r                            1/1     Running            3 (29m ago)     38m
coredns-d489fb88-fr28h                       0/1     Running            0               10m
hostpath-provisioner-757fddb7cb-j45cr        1/1     Running            0               10m
dashboard-metrics-scraper-64bcc67c9c-btjp5   1/1     Running            0               9m12s
kubernetes-dashboard-74b66d7f9c-bdmz9        0/1     CrashLoopBackOff   6 (3m18s ago)   9m12s
metrics-server-5fd798f94c-rv8pb              0/1     CrashLoopBackOff   21 (71s ago)    32m
calico-kube-controllers-6c79576885-fsfbf     0/1     CrashLoopBackOff   32 (60s ago)    38m**

**Output from describe command**
**ubuntu@ampere:~$ kubectl describe -n kube-system po calico-kube-controllers-6c79576885-fsfbf
Name:                 calico-kube-controllers-6c79576885-fsfbf
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      calico-kube-controllers
Node:                 ampere/10.0.0.212
Start Time:           Tue, 22 Nov 2022 04:39:45 +0000
Labels:               k8s-app=calico-kube-controllers
                      pod-template-hash=6c79576885
Annotations:          cni.projectcalico.org/containerID: d1ae19a45e8fc505de33237861c1189bb80f156ad0d67f0c9e04499eb5e69200
                      cni.projectcalico.org/podIP: 10.1.214.13/32
                      cni.projectcalico.org/podIPs: 10.1.214.13/32
                      kubectl.kubernetes.io/restartedAt: 2022-11-22T04:39:31Z
Status:               Running
IP:                   10.1.214.13
IPs:
  IP:           10.1.214.13
Controlled By:  ReplicaSet/calico-kube-controllers-6c79576885
Containers:
  calico-kube-controllers:
    Container ID:   containerd://0c4cd6858e12548027daf35fcafecdfd943100e9b8faaf90b1718ece0a94011e
    Image:          docker.io/calico/kube-controllers:v3.23.5
    Image ID:       docker.io/calico/kube-controllers@sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 22 Nov 2022 05:17:21 +0000
      Finished:     Tue, 22 Nov 2022 05:17:21 +0000
    Ready:          False
    Restart Count:  32
    Liveness:       exec [/usr/bin/check-status -l] delay=10s timeout=10s period=10s #success=1 #failure=6
    Readiness:      exec [/usr/bin/check-status -r] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ENABLED_CONTROLLERS:  node
      DATASTORE_TYPE:       kubernetes
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-95lwt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-95lwt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/master:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                 From     Message
  ----     ------   ----                ----     -------
  Warning  BackOff  53s (x57 over 11m)  kubelet  Back-off restarting failed container**

### What did you expect to happen?

I expected to run it without any errors.

### How can we reproduce it (as minimally and precisely as possible)?

- Ampere machine arm64 (Ampere)
- Install microk8s using snap
- Enable dns dashboard etc

### Anything else we need to know?

Sorry if i submitted the error in wrong format or anything wrong. It's my new time.

### Kubernetes Dashboard version

Inbuilt of that kubernetes 

### Kubernetes version

ubuntu@ampere:~$ kubectl version WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-11T08:33:23Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/arm64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-11T08:35:19Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/arm64"}

**Comment by floreks** [comment]
That's probably because coredns and calico are failing too. Dashboard needs a working connection to the api server to work. With DNS failing it most probably won't be able to start. You need to fix issues with your cluster fix.

/close
