### ISSUE TITLE
ImagePullBackOff when pulling dashboard container

### ISSUE THREAD

**Issue by xiongyu0523** [kubernetes/dashboard#7551]
### What happened?

I got ImagePullBackOff when pulling the dashboard container from k8s.gcr.io, when deploy 2.7.0. Is this impacted by the new https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/ change? My cluster 1.22

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  28m                   default-scheduler  Successfully assigned kubernetes-dashboard/kubernetes-dashboard-658b66597c-4nnqg to desktop-otf0281-ledge
  Normal   Pulling    25m (x4 over 28m)     kubelet            Pulling image "kubernetesui/dashboard:v2.7.0"
  Warning  Failed     25m (x4 over 28m)     kubelet            Failed to pull image "kubernetesui/dashboard:v2.7.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubernetesui/dashboard:v2.7.0": failed to resolve reference "docker.io/kubernetesui/dashboard:v2.7.0": failed to do request: Head "https://registry-1.docker.io/v2/kubernetesui/dashboard/manifests/v2.7.0": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
  Warning  Failed     25m (x4 over 28m)     kubelet            Error: ErrImagePull
  Warning  Failed     25m (x6 over 28m)     kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m24s (x96 over 28m)  kubelet            Back-off pulling image "kubernetesui/dashboard:v2.7.0"
```

### What did you expect to happen?

Previously my setup can pull image and run dashboard without problem

### How can we reproduce it (as minimally and precisely as possible)?

Reproduceable 

### What browsers are you seeing the problem on?

Others

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

1.22.6

**Comment by maciaszczykm** [comment]
Does `docker pull docker.io/kubernetesui/dashboard:v2.7.0` work for you?

**Comment by floreks** [comment]
> dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

There is nothing we can do about it. It's either a temporary docker registry issue or your cluster networking. We are not using k8s gcr. Only docker for now.

/close
