### ISSUE TITLE
Change the display style of resource names

### ISSUE THREAD

**Issue by hwdef** [kubernetes/dashboard#7553]
### What would you like to be added?

Currently, many resource names in the dashboard are displayed separately.
Thanks for the reminder @tengqm in https://github.com/kubernetes/dashboard/pull/7416, We should discuss whether these names should be displayed separately

![image](https://user-images.githubusercontent.com/13084946/206221341-3850c5e8-19a1-48dc-baba-ba423cf7bf98.png)

### Why is this needed?

1. This display can be misleading.
2. According to the requirements in the [official documentation](https://kubernetes.io/docs/contribute/style/style-guide/#documentation-formatting-standards), the resource name should not be displayed separately

**Comment by floreks** [comment]
> This page gives writing style guidelines for the Kubernetes documentation. These are guidelines, not rules. Use your best judgment...

I am not convinced if those guidelines should be applied to the Web UI that tries to present Kubernetes in a user-friendly way. I agree that any documentation, in-code comments etc. should follow this, but I am not convinced we should follow it in the UI.

**Comment by hwdef** [comment]
This results in a resource with two names, such as `cronjob` and `cron job`.It's confusing.

**Comment by hwdef** [comment]
@floreks 
Why shouldn't we follow it in UI?
