### ISSUE TITLE
Auto skip login page

### ISSUE THREAD

**Issue by Thearas** [kubernetes/dashboard#7572]
### What would you like to be added?

Found a way to allow auto skipping login page.
E.g. Add query parameter `skipLoginPage=true`.

### Why is this needed?

We use kube-dashboard in our internal system, all users are trusted. It's a bit tedious to click skip every time a new user jumps to kube-dashboard.

**Comment by BerlinKoche** [comment]
That would be awesome, i search for ages for a way to remove the login window.

**Comment by Thearas** [comment]
Hi @BerlinKoche.

Maybe in the next version, you can specify `skipLoginPage=true` in the query to skip the login page.
Implemented by #7645.
