### ISSUE TITLE
UI for kubectl set image DEPLOYMENT_NAME CONTAINER_NAME=IMAGE_URL

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/dashboard#7576]
### What would you like to be added?

On the deployment pane, we should have a new button next to scale resource, restart, edit resource and delete resource called "deploy new image" or "change container image" or something like that.

It should open a dialog box similar to the "scale a resource" button, except that it should ask for a new container image.

To make it even better, it should, by checking the existing replica set, show the previous versions in a table.

something like this:

![image](https://user-images.githubusercontent.com/297498/211718895-2e32074f-8320-4f54-877a-2ce4fb609d5c.png)

The buttons should be links. When one clicks, it it populates the container image to the text box.

### Why is this needed?

Sometimes one needs to deploy/revert something FAST.

That's a 3 click revert. Hard to beat :)

ps: I am implementing this and should finish soon.

**Comment by floreks** [comment]
Technically this can easily be done using the edit action and updating image in yaml/json. There are lots of available actions for resources and trying to use separate button/dialog for everything can overwhelm the UI pretty quickly.
