### ISSUE TITLE
Default proxy url (frontpage) did not work with helm chart deployment

### ISSUE THREAD

**Issue by lanwin** [kubernetes/dashboard#7589]
### What happened?

I felt upon the problem that the default dashboard proxy url on the github frontpage not works with the helm deployment.

It took my a while to figure out what the problem was and its not even obvious.

### What did you expect to happen?

Since most people (even my peers) lookup the dashboard proxy url on the frontpage it would be very helpful if this also works by default for the helm chart.

Personally I would suggest to remove the port name or at least allow to remove the name form via values changes.

### How can we reproduce it (as minimally and precisely as possible)?

deploy with helm

### Anything else we need to know?

kubectl url: http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
helm url: http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:https/proxy/

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

2.7.0 chart version 6.0.0

### Kubernetes version

0.25

**Comment by floreks** [comment]
Outdated and no longer valid

/close
