### ISSUE TITLE
Implement current logs form

### ISSUE THREAD

**Issue by zreigz** [kubernetes/dashboard#76]
I took this view:
https://github.com/kubernetes/dashboard/blob/master/designs/11-11-2015/21_logs%20current.png

**Comment by zreigz** [comment]
I wanted create generic service for logs to be able retrieve current logs and from some period. I notice problem on server side when I request for logs since some time. The simplest way to trigger it is use kubectl command. I've created bug:
https://github.com/kubernetes/kubernetes/issues/17561

Currently we can only retrieve all logs for particular pod.

**Comment by bryk** [comment]
Starting your work with all logs is a good way. Then we can iterate on the view :)

**Comment by zreigz** [comment]
PTAL

Now result looks like this

![logscreen](https://cloud.githubusercontent.com/assets/13030040/11364650/84813840-9299-11e5-9f53-fcb0e02f6ea3.png)
