### ISSUE TITLE
fix depricated package

### ISSUE THREAD

**Issue by romdhanisam** [kubernetes/dashboard#7601]
### What should be cleaned up or changed?

NPM libraries

### Why is this needed?

> Still using depricated package

- npm WARN deprecated @angular/flex-layout@14.0.0-beta.40: This package has been deprecated. Please see https://blog.angular.io/modern-css-in-angular-layouts-4a259dca9127
- npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
- npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
- npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.

**Comment by romdhanisam** [comment]
angular/flex-layout still depricated https://www.npmjs.com/package/@angular/flex-layout.

/reopen

**Comment by maciaszczykm** [comment]
We are using latest version: 
https://www.npmjs.com/package/@angular/flex-layout
https://github.com/kubernetes/dashboard/blob/master/modules/web/package.json#L51

If package doesn't include any security vulnerabilities then not using latest version shouldn't be considered as an issue though.

**Comment by romdhanisam** [comment]
> We are using latest version: https://www.npmjs.com/package/@angular/flex-layout https://github.com/kubernetes/dashboard/blob/master/modules/web/package.json#L51
> 
> If package doesn't include any security vulnerabilities then not using latest version shouldn't be considered as an issue though.

Hello,
As stated by the author, the entire package is deprecated.
![SmartSelect_20231013_205016_Chrome](https://github.com/kubernetes/dashboard/assets/18246134/8bfe95fb-d486-4b60-87e6-f71719c8afe1)

**Comment by maciaszczykm** [comment]
Ah, okay, makes sense. We will probably switch it at some point. Perhaps with new Material.
