### ISSUE TITLE
Cronjob view breaks on GKE v1.25 with latest 2.7.0

### ISSUE THREAD

**Issue by tzachmona** [kubernetes/dashboard#7604]
### What happened?

Clicking on "Cron Jobs"  on the left menu works and I can see the list of cronjobs. When clicking on any of the jobs, I'm getting the "Not Found (404)" and "the server could not find the requested resource"

I can also say that I briefly see the cronjob page loads for 1 sec and then it switched to the 404

### What did you expect to happen?

The cronjob page view with ability to see the latest jobs, events and configurations.

### How can we reproduce it (as minimally and precisely as possible)?

1. GKE version  1.25.4-gke.2100
2. Install the latest helm chart (6.0.0 or 5.10.0)
3. clusterrolebinding - give the clusterrole "cluster-admin" to the service account of the kubernetes dashboard.

### Anything else we need to know?

1. I tried to have an older version of the helm chart but it didn't work
2. on the logs of the pod:
```
2023/01/26 09:32:14 [2023-01-26T09:32:14Z] Incoming HTTP/1.1 GET /api/v1/cronjob/default/cronjobname/event?itemsPerPage=10&page=1&sortBy=d,lastSeen request from 10.100.7.18:
2023/01/26 09:32:14 [2023-01-26T09:32:14Z] Incoming HTTP/1.1 GET /api/v1/cronjob/default/cronjobname/job?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 10.100.7.18:
2023/01/26 09:32:14 [2023-01-26T09:32:14Z] Incoming HTTP/1.1 GET /api/v1/cronjob/default/cronjobname request from 10.100.7.18:
2023/01/26 09:32:14 [2023-01-26T09:32:14Z] Outcoming response to 10.100.7.18 with 404 status code
2023/01/26 09:32:14 [2023-01-26T09:32:14Z] Outcoming response to 10.100.7.18 with 404 status code
```
3. can it be related to the k8s version 1.25 where cronjobs with v1beta1 are no longer supported?
more info here: https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25#cronjob-v125

### What browsers are you seeing the problem on?

Chrome, Safari

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

1.25

**Comment by maciaszczykm** [comment]
@tzachmona Thank you for the report. We will take care of it.

**Comment by tzachmona** [comment]
Thanks for fixing this so fast, @maciaszczykm!
Just a qq - Do I have a way to use the fixed version without waiting for a release?

**Comment by hasefumi23** [comment]
I am experiencing the same issue. As you can see in the attached image, the manifest definition appears empty. Also, the GET request is returning 404 Not Found.

![image](https://github.com/kubernetes/dashboard/assets/18630999/34fa582f-0b88-4f2e-8349-19a7c88c84aa)

**Kubernetes Dashboard version**  
2.7.0(No use helm)

**EKS version**
1.25

**Kubernetes version**  
1.25
