### ISSUE TITLE
The status dashboard displays black for some languages

### ISSUE THREAD

**Issue by omijh** [kubernetes/dashboard#7605]
### What happened?

When you set the language to Japanese or Korean in the kuberneties dashboard the status pie chart turns black which is meaning less. When you set the language to English or Spanish it displays green as expected 

Tested in chrome and edge browsers so far.

### What did you expect to happen?

The status pie charts for all namespaces should be green for Japanese or Korean languages

### How can we reproduce it (as minimally and precisely as possible)?

Go to settings in the dashboard and set the language to Japanese. Then go to the dashboard and check the pie chart.

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

1.24

**Comment by floreks** [comment]
Already fixed in https://github.com/kubernetes/dashboard/pull/7546 and will be available in the next release.
