### ISSUE TITLE
Support HorizontalPodAutoscaler v2

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#7607]
### What would you like to be added?

Support HorizontalPodAutoscaler v2 (`autoscaling/v2`)

### Why is this needed?

HPA v2 became stable in k8s v1.25.

**Comment by lisenet** [comment]
Adding HPA to Kubernetes Dashboard would be very useful as it currently prevents us from changing deployment replicas.

**Comment by metroidprototype** [comment]
Any chance this support could be added? We're at k8s 1.29 now, so its been stable for several minor versions.
