### ISSUE TITLE
Is there a way to build docker from latest code? Or should I wait for the release?

### ISSUE THREAD

**Issue by tzachmona** [kubernetes/dashboard#7611]
### What would you like to be added?

Hi,

Please forgive me if I should have been able to find this info somewhere..

I opened a bug about 2 weeks ago (https://github.com/kubernetes/dashboard/issues/7604)
and it got fixed and merged (thanks!). 
My simple question is if there's a way for me to get the fixed code in an updated docker image and use it on my test environment? or, should I wait for a release? If I need to wait, can I know when will it happen?

### Why is this needed?

Thanks a lot

**Comment by maciaszczykm** [comment]
Wait for the new release. We will need to do https://github.com/kubernetes/dashboard/pull/7544 first but we are quite busy at the moment.
