### ISSUE TITLE
too much logging

### ISSUE THREAD

**Issue by tooptoop4** [kubernetes/dashboard#7618]
### What happened?

logs are filled with loads of entries such as :

2023/02/10 02:03:30 Getting list of all deployments in the cluster
2023/02/10 02:03:30 Getting list of all jobs in the cluster
2023/02/10 02:03:30 Getting list of all pods in the cluster
2023/02/10 02:03:30 Getting list of all replica sets in the cluster
2023/02/10 02:03:30 Getting list of all replication controllers in the cluster
2023/02/10 02:03:30 Getting list of all pet sets in the cluster
2023/02/10 02:03:32 received 0 resources from sidecar instead of 3
2023/02/10 02:03:32 received 0 resources from sidecar instead of 3
2023/02/10 02:03:32 received 50 resources from sidecar instead of 51
2023/02/10 02:03:32 received 0 resources from sidecar instead of 3
2023/02/10 02:03:32 received 0 resources from sidecar instead of 3
2023/02/10 02:03:32 received 50 resources from sidecar instead of 51
2023/02/10 02:03:32 Getting pod metrics
2023/02/10 02:03:32 received 0 resources from sidecar instead of 3
2023/02/10 02:03:32 received 9 resources from sidecar instead of 10
2023/02/10 02:03:32 received 0 resources from sidecar instead of 3
2023/02/10 02:03:32 received 9 resources from sidecar instead of 10
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
2023/02/10 02:03:32 Skipping metric because of error: Metric label not set.
[restful] 2023/02/10 02:04:58 log.go:33: There was an error during transformation to sidecar selector: Resource "cronjob" is not a native sidecar resource type or is not supported
[restful] 2023/02/10 02:04:58 log.go:33: There was an error during transformation to sidecar selector: Resource "cronjob" is not a native sidecar resource type or is not supported

### What did you expect to happen?

want to disable all logs

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Kubernetes Dashboard version

v2.6.1

### Kubernetes version

1.24

**Comment by maciaszczykm** [comment]
That's a valid point. We should set log levels and allow selecting them.

**Comment by maciaszczykm** [comment]
We have added new arg to metrics scraper that allows to switch logging level: https://github.com/kubernetes/dashboard/blob/master/modules/metrics-scraper/pkg/args/args.go.

It will be available in the upcoming release.
