### ISSUE TITLE
"Sign Out" Option Missing when logged in to Kubernetes Dashboard as "LOGGED IN WITH AUTH HEADER"

### ISSUE THREAD

**Issue by DileepAP** [kubernetes/dashboard#7623]
### What happened?

Configured Kubernetes Dashboard, Keycloak is the IAM solution. OAuth is configured in kubernetes and Nginx is used for ingress.

Able to login to dashboard with the user created in keycloak. But in the dashboard, "Sign Out" is missing.
![image](https://user-images.githubusercontent.com/49062083/219085782-bb63489e-9056-46ec-97b4-9819d86185f2.png)

 I have another cluster for testing with the same versions of kubernetes and Dashboard. 
In this cluster Keycloak and Oauth not configured.
Dashboard and Nginx Ingress is configured (Same Versions)  
In this Cluster, if I am "LOGGED IN WITH TOKEN" "Sign Out" is available
 
![image](https://user-images.githubusercontent.com/49062083/219086648-eead2536-dd47-4e7a-93b0-061d600bd7ff.png)

### What did you expect to happen?

I assume the "Sign Out" option should be available even if logged in as "LOGGED IN WITH AUTH HEADER"

### How can we reproduce it (as minimally and precisely as possible)?

Ingress - Nginx
Dashboard - Dashboard v2.3.0+0.gccb45d8ca
Kubernetes Version - v1.24.10-2+8627c559b36fc7
This is a microk8s cluster
Keycloak
oauth2-proxy

### Anything else we need to know?

Issue appeared in edge, chrome and mozilla browsers

### What browsers are you seeing the problem on?

Chrome, Firefox, Others

### Kubernetes Dashboard version

v2.3.0+0.gccb45d8ca

### Kubernetes version

v1.24.10-2+8627c559b36fc7

**Comment by floreks** [comment]
That's because there is no dedicated OIDC support built into the Dashboard. You have to use external proxies for that. There is no way to autodiscover the configuration inside the app. We would need to add direct OIDC support. 

Since we already have an open issue related to that I am closing this one.

/close

**Comment by DileepAP** [comment]
Could you please help me with the details of the "Open Issue" related to this as mentioned in the closure comment.

**Comment by floreks** [comment]
It's in #2353
