### ISSUE TITLE
Helm chart recommends using private labels

### ISSUE THREAD

**Issue by sftim** [kubernetes/dashboard#7624]
### What happened?

https://github.com/kubernetes/dashboard/blob/bc518f75345d9022a16519208f99e2ba46fa7790/charts/recommended.yaml suggests using the `k8s-app` label.

### What did you expect to happen?

The labels that we recommend follow the guidance in https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

### How can we reproduce it (as minimally and precisely as possible)?

Read https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ and then look at https://github.com/kubernetes/dashboard/blob/bc518f75345d9022a16519208f99e2ba46fa7790/charts/recommended.yaml 

### Anything else we need to know?

Labels that don't contain a subdomain before the `/` are cluster private

### Kubernetes Dashboard version

Git commit bc518f75345d9022a16519208f99e2ba46fa7790

### Kubernetes version

1.26.0

**Comment by sftim** [comment]
Any thoughts?

**Comment by floreks** [comment]
Manifest-based installation will no longer be supported and it has been removed. Helm uses a recommended set of labels already. This should be fixed.

/close
