### ISSUE TITLE
Specify image registry in sample manifests.

### ISSUE THREAD

**Issue by sftim** [kubernetes/dashboard#7625]
### What would you like to be added?

```yaml
          image: kubernetesui/dashboard:v2.7.0
```

When we provide sample manifests, we should specify what registry. 

### Why is this needed?

It's better than assuming that the container runtime defaults to fetching from Docker Hub, and avoids accidental favoritism.

**Comment by maciaszczykm** [comment]
We have added registry when listing images in releases. We do no longer provide sample manifests, only Helm chart which also has registry specified.
