### ISSUE TITLE
Support automatic selection of the namespace corresponding to token through token login

### ISSUE THREAD

**Issue by huweihuang** [kubernetes/dashboard#7644]
### What would you like to be added?

A token with the specified namespace has been created. If you login through this token, the default namespace is default, and you cannot view the corresponding namespace.

```
kubectl -n <namespace> create token default
```

![image](https://user-images.githubusercontent.com/29064882/222628119-7d718aa2-712a-445a-88d1-4f528217dcf1.png)

### Why is this needed?

Support automatic selection of the namespace corresponding to token through token login. and the user don't input the namespace name by themselves.

**Comment by floreks** [comment]
It's not possible to detect a namespace based on the token itself. You can update the default namespace in the settings view and it will be selected by default after logging in again.

/close
