### ISSUE TITLE
Official Dockerfile removed from repo in commit 92a8491b99afa2cfb94dbe6f3410cadc42b0dc31

### ISSUE THREAD

**Issue by regnaio** [kubernetes/dashboard#7646]
### What would you like to be added?

The official Dockerfile https://github.com/kubernetes/dashboard/blob/f8ca73e738aecd8df1183ea89553f29fcedf4395/aio/Dockerfile was removed from the repo in commit https://github.com/kubernetes/dashboard/commit/92a8491b99afa2cfb94dbe6f3410cadc42b0dc31

Can we add this Dockerfile back?

### Why is this needed?

Harder to find what's in the image https://hub.docker.com/r/kubernetesui/dashboard if the official Dockerfile is removed from the repo

**Comment by floreks** [comment]
They are still there. Build system has changed due to architecture changes in the app.

This one is for the web container:
https://github.com/kubernetes/dashboard/blob/master/modules/web/Dockerfile

/close
