### ISSUE TITLE
Deployment details page: add related objects

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#767]
@Draiken

We have now a deployment detail page. Can we add there related objects as it is on, e.g., replication controllers page?

**Comment by Draiken** [comment]
@bryk not sure I'll have much time this week to work on this. If I find some time and nobody started it, I'll gladly do it

**Comment by bryk** [comment]
Awesome, thanks!

**Comment by floreks** [comment]
@Draiken are you working on this? I'm just asking because I can take it if you don't have time.

**Comment by Draiken** [comment]
No, I'm a bit swamped ATM. Please take it

**Comment by floreks** [comment]
Are there any other related objects than replica sets for deployment? Currently we are showing old/new replica sets and pods are related to them, not to deployment itself. I don't see any other related objects.

cc @bryk @maciaszczykm

**Comment by bryk** [comment]
We could potentially also show pods, but this is good enough for now. I think we should close this :)
