### ISSUE TITLE
pie chart has no color on specific language setting

### ISSUE THREAD

**Issue by roeniss** [kubernetes/dashboard#7684]
### What happened?

The pie charts on the main page are just black circles on my dashboard :

![Screenshot 2023-03-24 at 16 55 57 by seonghyeok](https://user-images.githubusercontent.com/26613280/227459099-393affe5-fae9-499a-9147-690d729af43e.png)
I found there is no "fill" attribute in \<path\> tags. 

Then I changed my language settings, which have been Korean, to English. It makes the problem solved : 

![Screenshot 2023-03-24 at 16 59 46 by seonghyeok](https://user-images.githubusercontent.com/26613280/227459913-f755478d-5ac0-42ec-87a0-620c64064913.png)

So, I think that Dashboard Langauge Setting affects some UI elements by chance.

### What did you expect to happen?

Pie charts with green or other than black color

### How can we reproduce it (as minimally and precisely as possible)?

Set Dashboard Langauge to Korean

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

Dashboard v2.7.0+0.g42deb6b32

### Kubernetes version

1.26.1

### Dev environment

- Minikube: v1.29.0
- OS: macOS 13.2.1 22D68 arm64

**Comment by maciaszczykm** [comment]
Is is already fixed by https://github.com/kubernetes/dashboard/pull/7546. You will need to wait for new release or use master.
