### ISSUE TITLE
Pressing enter when typing to search for a namespace in the drop down does not select the highlighted namespace

### ISSUE THREAD

**Issue by zandermar18** [kubernetes/dashboard#7685]
### What happened?

When typing a partial namespace in the `Select Namespace` drop down menu, it will highlight the namespace that is closest to your search in typical typeahead fashion. However, when pressing the enter key to select the highlighted namespace, the partial namespace that is typed in is used instead of the highlighted namespace.

### What did you expect to happen?

I expect the behavior of pressing enter to act the same as pressing tab.

### How can we reproduce it (as minimally and precisely as possible)?

See attached gif for reproduction:
![As-is](https://user-images.githubusercontent.com/5048322/227748765-3f2c68ff-d9b2-4d06-812f-c2d5537b9083.gif)

### Anything else we need to know?

I can get a fix up for this after getting my dev environment setup.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Kubernetes Dashboard version

v2.7.0+0.g42deb6b32

### Kubernetes version

v1.25.7+k3s1

**Comment by floreks** [comment]
This is actually intentional. It allows manual switch to namespace with provided name in case user can't list namespaces but can access some of them.
