### ISSUE TITLE
Stylesheet not loading

### ISSUE THREAD

**Issue by llamahunter** [kubernetes/dashboard#7687]
### What happened?

I am accessing via an https terminating proxy server. When I load the page, it appears to come up with the data, but the stylesheet is not loading. When I look a the debug console for the browser, I see 

>Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src-attr 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

I tried this in both Chrome and Safari, and both complain with similar error.

### What did you expect to happen?

Page to load completely, including with stylesheets

### How can we reproduce it (as minimally and precisely as possible)?

Run kubernetes-dashboard via http behind an https terminating load balancer

### Anything else we need to know?

Seems to work if accessing directly via http. It seems to be something about the https termination that triggers the browsers to find the HTML insecure.

### What browsers are you seeing the problem on?

Chrome, Safari

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

1.24

**Comment by llamahunter** [comment]
![image](https://user-images.githubusercontent.com/843173/228711208-a86309db-8779-4504-ba31-760ffca4e484.png)

**Comment by llamahunter** [comment]
The Content-Security-Policy in the returned headers from the dashboard are:
>default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests

**Comment by llamahunter** [comment]
I think it's the 'script-src-attr' set to 'none' that is the problem? The style sheet load on line 20 has an inline 'onload' handler.

**Comment by llamahunter** [comment]
Hrm... the proxy is just an AWS load balancer. I don't think it has any CSP configuration options.

**Comment by llamahunter** [comment]
I found the place where the CSP was being injected and removed. However, it does seem that the way the dashboard is written, it is prone to triggering CSP issue due to having javascript onLoad handlers inlined on stylesheets.

**Comment by floreks** [comment]
This is most probably triggered by one of our bundled dependencies. It might be hard to track down the exact one to replace it.
