### ISSUE TITLE
Kubernetes dashboard UI elements not loading

### ISSUE THREAD

**Issue by samir321-pixel** [kubernetes/dashboard#7703]
Check this screenshot.
Tried with different browsers and different devices still all CSS are removed and not able to visit dashboard.
![image](https://user-images.githubusercontent.com/65664404/231424920-ba8beb91-adf2-430d-9c0f-fc967d01e38a.png)

![image](https://user-images.githubusercontent.com/65664404/231424533-42c2da26-2151-4fc0-8e78-40aa91c73c1d.png)

**Comment by maciaszczykm** [comment]
@samir321-pixel Can you post logs from browser console?

**Comment by floreks** [comment]
Duplicate of https://github.com/kubernetes/dashboard/issues/7687. Probably triggered by a CSP check at a proxy level. We do not have any information about the installation and setup, but it looks like you are using some kind of proxy to expose Dashboard. You might need to alter the configuration there.

**Comment by floreks** [comment]
Closing as stale

/close
