### ISSUE TITLE
CronJobs always show Unknown error (404) the server could not find the requested resource

### ISSUE THREAD

**Issue by karl18** [kubernetes/dashboard#7717]
### What happened?

Cron Jobs Tab in the Dashboard always shows this error:
Unknown error (404) the server could not find the requested resource
<img width="1337" alt="Screenshot 2023-04-26 at 10 55 01" src="https://user-images.githubusercontent.com/30005437/234526368-280197b3-af21-43eb-86ba-845814eebba1.png">

Unfortunately, looks like it only happened after upgrading the k8s cluster to version v1.25.6
I’m using Kubernetes Dashboard chart version: v1.25.6

### What did you expect to happen?

open the page normally as other tabs

### How can we reproduce it (as minimally and precisely as possible)?

Just opening CronJobs anytime, it shows the error above

pod logs: 

2023/04/26 09:04:27 Getting list of all cron jobs in the cluster
2023/04/26 09:04:27 [2023-04-26T09:04:27Z] Outcoming response to 172.16.6.167 with 404 status code
2023/04/26 09:04:27 [2023-04-26T09:04:27Z] Incoming HTTP/1.1 GET /api/v1/login/status request from 172.16.6.167: 
2023/04/26 09:04:27 [2023-04-26T09:04:27Z] Outcoming response to 172.16.6.167 with 200 status code
2023/04/26 09:04:29 [2023-04-26T09:04:29Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 172.16.6.167: 

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

v6.0.7

### Kubernetes version

v1.25.6

**Comment by yinyangsx** [comment]
Same error in my cluster,

Kubernetes Dashboard version
v2.7.0
Kubernetes version
v1.25.4

**Comment by qmercier** [comment]
Same error in my cluster,

Kubernetes Dashboard version
v2.7.0
Kubernetes version
v1.25.6

**Comment by kaykhan** [comment]
Tried rolling back dashboard version, but no luck.

Has anyone found a work around for this problem?

**Comment by jnoordsij** [comment]
I think https://github.com/kubernetes/dashboard/pull/7465 should have fixed this, but no new release has been made yet.

**Comment by Shivam0609** [comment]
Hello, can someone confirm when can we expect a new dashboard version with the fix ?

**Comment by dannmartens** [comment]
> Hello, can someone confirm when can we expect a new dashboard version with the fix ?

Indeed, a patch update with this fix would be greatly appreciated!

**Comment by fontexD** [comment]
also waiting here on it :D

**Comment by davidroth** [comment]
Yeah same. Last release is 9 months old🥲

**Comment by DiogoMCampos** [comment]
Hello, is there something the community can help with here? 😃

**Comment by maciaszczykm** [comment]
You can do some testing for https://github.com/kubernetes/dashboard/pull/7969 if you want.

**Comment by fapinheiro** [comment]
Same error here.

Dashboard v2.7.0
Kubernetes 1.26.6

Any updates on this subject?

**Comment by fontexD** [comment]
there is a guy that got tired of waiting (1 year now i think) with no updates on this so he fixed it himself within 5 min and uploaded his branch of the dashboard, and it works flawlessly :) 
ima try find the repo for ya

**Comment by furacas** [comment]
I temporarily fell back to version 2.6.1 to avoid this problem

**Comment by kaykhan** [comment]
> 

Is there an existing PR with these changes, maybe we can up-vote that PR?

**Comment by steveannett** [comment]
The project has been restructured since these changes were originally made, and it seems they have now incorporated the necessary changes in, but not yet released. Both
[jobs.go](https://github.com/kubernetes/dashboard/blob/82cbe0ecc7b2f0fbeac6eed5fa64ce674af0e50e/modules/api/pkg/resource/cronjob/jobs.go#L51) and [types.go](https://github.com/kubernetes/dashboard/blob/82cbe0ecc7b2f0fbeac6eed5fa64ce674af0e50e/modules/api/pkg/api/types.go#L227) have the modifications.

I assume we would have to wait for version 3.0.0 before the Cron Jobs tab works again

**Comment by marekhanus** [comment]
Hi @floreks, please could you release 2.7.1 with fix from #7465? I think that it will solve this issue.

The issue still persists and no 3.x release was made.

/remove-lifecycle rotten

**Comment by jooosh** [comment]
@marekhanus I was able to get an image built using the patch created by beffe123.  The image is posted on [docker hub](https://hub.docker.com/repository/docker/superhumane/kubernetes-dashboard-amd64/general).  I make no guarantee that it won't blow up your k8s environment but it's running on ours without issue. 😉

**Comment by floreks** [comment]
A new release that will contain the fix should be available next week. There will be lots of other changes too. Ref: https://github.com/kubernetes/dashboard/pull/8708

**Comment by liuqi-sun** [comment]
I have found out the cause of this problem, please refer to https://github.com/kubernetes/dashboard/issues/9622
