### ISSUE TITLE
Hide label column from resource overviews

### ISSUE THREAD

**Issue by Andrioden** [kubernetes/dashboard#7725]
### What would you like to be added?

Most views have a Label column, that show 3 labels per entity. Se image below. This clutters the view alot and make each row taller. A good ux change would be to remove it.

Alternatives:
- Only show 1 label (and show all button)
- Make it a per-user-cookie setting wheter or not it should be shown
- Make it a deploy configuration of the dashboard, through param or such.

![image](https://user-images.githubusercontent.com/393376/236442333-b9587fe4-55c4-4b8c-bdbe-3ab243514e5c.png)

### Why is this needed?

Less clutter in ui.

**Comment by maciaszczykm** [comment]
This would need to be put into settings, but makes sense.

**Comment by floreks** [comment]
There is already a labels limit setting on settings view that can control a default number of visible labels.
![image](https://github.com/kubernetes/dashboard/assets/2285385/47849b42-dbe8-4f99-8ffc-1a16df467889)

/close
