### ISSUE TITLE
`secret/kubernetes-dashboard-key-holder` loses labels/annotations

### ISSUE THREAD

**Issue by jcpunk** [kubernetes/dashboard#7731]
### What happened?

When installing kubernetes-dashboard from helm, after the initial setup the `secret/kubernetes-dashboard-key-holder` loses labels/annotations.

### What did you expect to happen?

The labels/annotations set on `secret/kubernetes-dashboard-key-holder` would remain.

### How can we reproduce it (as minimally and precisely as possible)?

values.yaml
```yaml
---
commonLabels:
  label: value
commonAnnotation:
  note: text
```

helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -f values.yaml 

sleep 2m

`kubectl describe secret/kubernetes-dashboard-key-holder`

### Anything else we need to know?

This also breaks helm's detection of installed and managed objects.

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

1.27

**Comment by peterellisjones** [comment]
This is aftecting us as well as [kapp](https://carvel.dev/kapp/) is constantly detecting changes to this resource as the labels are being cleared

**Comment by jcpunk** [comment]
I'm still interested in this.

**Comment by maciaszczykm** [comment]
With the new release dashboard api becomes stateless, that means it will no longer hold keys. Please switch to the next release when it will be out.
