### ISSUE TITLE
 I'm using kubernetes dashboard but after a while, the proxies fall off.

### ISSUE THREAD

**Issue by misupopo** [kubernetes/dashboard#7746]
### What happened?

I’m using kubernetes dashboard.
I use only http to communicate.
Authentication is skipped.

However, the nohup watch kubectl proxy process doesn't keep.

Proxy process crash occurs after the command is executed.

```
■ process
nohup watch kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' -n kubernetes-dashboard &

■ dashboard log
ubuntu@master:~$ kubectl logs kubernetes-dashboard-5c9968d778-phbks -n kubernetes-dashboard
2023/05/18 03:36:42 Using apiserver-host location: http://{ipv4 address}:{port number}
2023/05/18 03:36:42 Using namespace: kubernetes-dashboard
2023/05/18 03:36:42 Skipping in-cluster config
2023/05/18 03:36:42 Using random key for csrf signing
2023/05/18 03:36:42 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service account's configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get "http://{ipv4 address}:{port number}/version": dial tcp {ipv4 address}:{port number}: connect: connection refused
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

■ pod status
ubuntu@master:~$ kubectl get pod -n kubernetes-dashboard
NAME                                        READY   STATUS             RESTARTS         AGE
dashboard-metrics-scraper-8c47d4b5d-kcnm8   1/1     Running            0                3h
kubernetes-dashboard-5c9968d778-phbks       0/1     CrashLoopBackOff   18 (2m39s ago)   3h
```

### What did you expect to happen?

Permanent proxy process continuity.

### How can we reproduce it (as minimally and precisely as possible)?

Execute the following command.

```
nohup watch kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' -n kubernetes-dashboard &
```

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by floreks** [comment]
kubectl does not belong to this repo. This is not directly related to dashboard.

**Comment by frozenprocess** [comment]
I believe you should be able to fix it by adjusting the `streamingConnectionIdleTimeout` value in your [kubelet configuration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#:~:text=servers.%20Default%3A%20nil-,streamingConnectionIdleTimeout,-meta/v1.Duration). (Default is 4h)

As @floreks pointed out it is not a dashboard-related problem. I think you can find a better explanation and guidance in kubelet or Kubectl projects.

**Comment by floreks** [comment]
> I believe you should be able to fix it by adjusting the `streamingConnectionIdleTimeout` value in your [kubelet configuration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#:~:text=servers.%20Default%3A%20nil-,streamingConnectionIdleTimeout,-meta/v1.Duration). (Default is 4h)
> 
> As @floreks pointed out it is not a dashboard-related problem. I think you can find a better explanation and guidance in kubelet or Kubectl projects. 

Exactly, thanks for responding.

/close

**Comment by misupopo** [comment]
Thank you for your reply.
