### ISSUE TITLE
Can the k8s dashboard support SSO login mode?

### ISSUE THREAD

**Issue by huweihuang** [kubernetes/dashboard#7752]
### What would you like to be added?

Can help support SSO login and integrate custom authentication interfaces.

### Why is this needed?

The login methods for token and kubeconfig are very inconvenient. Can help support SSO login and integrate custom authentication interfaces.

**Comment by maciaszczykm** [comment]
Check https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#access-control.
