### ISSUE TITLE
recommendation.yaml mismatched 

### ISSUE THREAD

**Issue by sysnet4admin** [kubernetes/dashboard#7759]
### What should be cleaned up or changed?
Reference case #7506

**Between** 

https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
And 
https://github.com/kubernetes/dashboard/blob/master/charts/recommended.yaml

Here is main differentiation. 
<img width="1144" alt="image" src="https://github.com/kubernetes/dashboard/assets/29163931/255632ba-2b03-4ce6-9630-84046e370569">

It may need to follow up web-page as well if minor version change. 
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui

### Why is this needed?

`master` node already changed to `control-plane` with label. 
And other is miscellaneous I guess. (i.e. 1.0.8 to 1.0.9)

**Comment by maciaszczykm** [comment]
You are comparing master version of chart with v2.7.0 version of deployment. Check https://github.com/kubernetes/dashboard/blob/master/charts/recommended.yaml instead. Helm chart is going to be updated in https://github.com/kubernetes/dashboard/pull/7544.

**Comment by sysnet4admin** [comment]
@maciaszczykm 
Thank you for your update. 
So you mean that this URL's recommended.yaml need to change from 

![image](https://github.com/kubernetes/dashboard/assets/29163931/4c118fdc-ad46-4c64-9f5a-ac2eef3ede66)

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui

My point is... [aio/deploy/recommended.yaml] (https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml) still `master` label.

Please let me clarify web-page need to change whether or not.

**Comment by maciaszczykm** [comment]
Readme needs to point to official release not to master which config is not tested that much.

**Comment by sysnet4admin** [comment]
Okay. Thank you for your kindness explanation.
