### ISSUE TITLE
No service mode picked by default

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#780]
No service mode is picked by default in deploy view:

![image](https://cloud.githubusercontent.com/assets/2823399/15648206/4302bfc4-2669-11e6-95e0-7d43b5457773.png)

`None` should be selected:

![image](https://cloud.githubusercontent.com/assets/2823399/15648264/9eb2e830-2669-11e6-914b-d6370d7bd92e.png)

**Comment by bryk** [comment]
Yep, that's correct.
