### ISSUE TITLE
Unknown error (0)

### ISSUE THREAD

**Issue by DileepAP** [kubernetes/dashboard#7858]
### What happened?

Unknown error (0)
http failure response for https://fqdn/kube-dashboard/api/v1/deployment/%20?itemsPerPage=10&page=1&sortBy=d,creationTimestamp:0 Unknown Error

This error is reporting in kubernetes dashboard and upon refresh, the page loads back. It can come on any object, like Pods, deamonsets etc

### What did you expect to happen?

The Dashboard automatically shows the error intermittently.
Unknown error (0)
http failure response for https://fqdn/kube-dashboard/api/v1/deployment/%20?itemsPerPage=10&page=1&sortBy=d,creationTimestamp:0 Unknown Error 

### How can we reproduce it (as minimally and precisely as possible)?

kubernetes Version as mentioned below. Integrated with Oauth2, keycloak and dashboard version (Mentioned below)

Dashboard POD logs.
2023/06/12 05:14:20 [2023-06-12T05:14:20Z] Incoming HTTP/1.1 GET /api/v1/deployment/%!?(MISSING)itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 10.40.101.86:
2023/06/12 05:14:20 Getting list of all deployments in the cluster
2023/06/12 05:14:20 received 0 resources from sidecar instead of 1
2023/06/12 05:14:20 received 0 resources from sidecar instead of 1
2023/06/12 05:14:20 [2023-06-12T05:14:20Z] Outcoming response to 10.40.101.86 with 200 status code
2023/06/12 05:14:24 [2023-06-12T05:14:24Z] Incoming HTTP/1.1 GET /api/v1/deployment/%!?(MISSING)itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 10.40.101.86:

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

kubectl version WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-30T17:44:46Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-30T17:45:40Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

### Dev environment

Kubernetes Dashboard v2.7.0, 
Microk8s kubernetes with version v1.26.5. 
Kubernetes Dashboard Integrated with Keycloak 21.0.2.
oauth2-proxy:v7.4.0

**Comment by floreks** [comment]
It looks like the request has been terminated or timed out at the proxy level and that's why Dashboard reported an error. It doesn't look like a Dashboard issue directly. Some timeout/retry config might need to be updated at the proxy level.

/close
