### ISSUE TITLE
The error messages about exceed max-length are not shown

### ISSUE THREAD

**Issue by Yamagami-Takuma** [kubernetes/dashboard#786]
#### Issue details
The error messages are not shown when create a new namespace with too long name.

##### Environment

```
Dashboard version: 819be162d1a7e7fdc3489f7375df86e87dfe538b
Kubernetes version: 1.2.4
Operating system: Ubuntu 14.04
Node.js version: 5.11.1
Go version: 1.6.2
```

##### Steps to reproduce

1. Access to the page of Deploy a Containerized App.
2. Click Create a new namespace.
3. Fill input form with over 64 characters.
4. The error messages don't appear which should display under the input form.

##### Observed result

![not display error message when charactor too long](https://cloud.githubusercontent.com/assets/13443650/15698403/49f64714-27ff-11e6-8050-317fa225417e.png)

##### Expected result

The error messages "Name must be up to 63 characters long." should display under the input form.

##### Comments

At [this line]( https://github.com/kubernetes/dashboard/blob/819be162d1a7e7fdc3489f7375df86e87dfe538b/src/app/frontend/deploy/createnamespace.html#L32), the value of ng-message is "maxlength".
But I think it should be "md-maxlength".

I don't check all of the dashboard, but perhaps there are other issues same as this.
e.g. input form of App name at the page of Deploy a Containerized App.

**Comment by bryk** [comment]
@Yamagami-Takuma thanks for reporting this! :) Can you maybe fix the issue?

**Comment by Yamagami-Takuma** [comment]
@bryk OK I will fix this issue.
