### ISSUE TITLE
The "Age" on workloads/deployments is always "a year"

### ISSUE THREAD

**Issue by mattthias** [kubernetes/dashboard#790]
#### Issue details
No matter what age ``kubectl get deployments`` shows in the dashboard it is always "a year". 

##### Environment

We run a Kubernetes 1.2.4 on AWS instances. 

```
Dashboard version: v1.1.0-beta1 (published image) / master @b5263fc (build with  ``build/run-gulp-in-docker.sh docker-image:canary``
Kubernetes version: 1.2.4
Operating system:  CoreOS stable (899.17.0)
```

##### Steps to reproduce

Deploy the dashboard and a deployment in the cluster. Look at the 'workloads'  page.

##### Observed result

The age of the deployments is always "a year"
##### Expected result

The actual age of the deployment. 

##### Comments

Thanks for developing this nice tool!

Best wishes,
Matthias

**Comment by floreks** [comment]
Thanks for reporting this bug! Will be fixed soon.
