### ISSUE TITLE
 The dashboard is not accessible when accessed through the Azure Application Gateway

### ISSUE THREAD

**Issue by imranrazakhan** [kubernetes/dashboard#7932]
### What happened?

I have deployed dashboard with [recommended.yaml] 
 (https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml) without modifying default config, but at appgw level I am getting following error

`The Common Name (CN) of the backend server certificate does not match the host header entered in the health probe configuration (v2 SKU) or the FQDN in the backend pool (v1 SKU). Verify if the hostname matches with the CN of the backend server certificate.`

I tried to get CN from certificate with command

`curl -v  -k -w "\n%{certs}\n" https://10.0.227.164`

Output is below

```
Subject:
Issuer:
Version:2
Serial Number:71c41f3cc6567ae436eb168a868090de
Signature Algorithm:ecdsa-with-SHA256
Public Key Algorithm:id-ecPublicKey
Start date:Jun 23 19:52:28 2023 GMT
Expire date:Jun 22 19:52:28 2024 GMT
Signature:30:45:02:21:00:80:6b:35:82:13:bb:96:e3:bb:05:fa:56:71:16:70:c0:5e:b2:bc:63:57:f5:1e:0e:75:1a:da:eb:b6:0f:98:47:02:20:50:f9:f0:c1:de:41:ec:d9:a1:31:c4:2f:bf:77:04:30:a1:e4:96:6c:61:8d:54:fe:e2:62:da:38:23:41:95:b6:
-----BEGIN CERTIFICATE-----
MIH7MIGioAMCAQICEHHEHzzGVnrkNusWioaAkN4wCgYIKoZIzj0EAwIwADAeFw0y
MzA2MjMxOTUyMjhaFw0yNDA2MjIxOTUyMjhaMAAwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAASSFFUP0PT4RDcpA5LEzaLICZlQfoXR0c9UiyLb7WK/J+Dn62RyR5MZ
Mhjql1kg2eWMaMcSW8yfddO9iQUkVtGHMAoGCCqGSM49BAMCA0gAMEUCIQCAazWC
E7uW47sF+lZxFnDAXrK8Y1f1Hg51Gtrrtg+YRwIgUPnwwd5B7NmhMcQvv3cEMKHk
lmxhjVT+4mLaOCNBlbY=
-----END CERTIFICATE-----
```

It mean auto generated certificates doesn't have CN.

### What did you expect to happen?

I should be able to access dashboard

### How can we reproduce it (as minimally and precisely as possible)?

Deploy dashboard and access via Azure Application gateway.

### Anything else we need to know?

If its bug can i expose dashboard over HTTP? As certificate part will be taken care by AppGW?

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

1.25.0

**Comment by floreks** [comment]
`recommended.yaml` is not really destined to work with all cloud providers. You'd need to customize the configuration and flags passed to Dashboard or use helm chart with custom config. I presume that Azure App gateway is something like a reverse proxy that gives you access to apps inside the cluster. In such case you would need to disable certificate auto-generation and run Dashboard in HTTP mode, then proxy would handle exposing Dashboard over HTTPS.

**Comment by imranrazakhan** [comment]
`In such case you would need to disable certificate auto-generation and run Dashboard in HTTP mode, then proxy would handle exposing Dashboard over HTTPS.`

@floreks Thanks for reply, Yes i did same as suggested and its now working.
