### ISSUE TITLE
Fix IE compatibility issues with new design

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#794]
Master is failing due to some IE protractor tests. Let's disable them for now until this issue is fixed.

Details can be seen at: https://saucelabs.com/jobs/7d19e448a3b4438bb5de18b554f4239b

**Comment by bryk** [comment]
It is all about tests. IE works. Moving to post 1.1

**Comment by maciaszczykm** [comment]
We will track from #2420.
