### ISSUE TITLE
Direct helm install not installing the services(api, web) and ingress

### ISSUE THREAD

**Issue by ajay56611** [kubernetes/dashboard#7964]
### What happened?

I tried to install the v2.7.0 latest helm chart in my eks 1.26 but it is not creating services and ingress causing 503 when accessing from browser. 

### What did you expect to happen?

helm install should created all the resources and dashboard should be accessible.

### How can we reproduce it (as minimally and precisely as possible)?

your cluster should have cert-manager, nginx-ingress-controller.
make sure you have TLS  certificate created and use it in overrides and do the direct helm install of latest chart.

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

1.26

**Comment by floreks** [comment]
From what I see in the chart Ingress is only created if you override and set `--set ingress.enabled=true`. Service on the other hand is always created, but you might need to pass some provide-specific annotations to make it work properly.
