### ISSUE TITLE
Support live updates of resource state

### ISSUE THREAD

**Issue by yissachar** [kubernetes/dashboard#797]
Currently the Dashboard only updates the state of resources on a page refresh. This is very annoying when applying a change to a resource and watching it through the Dashboard to see when the change has been fully implemented. E.g. a common flow for me is to deploy a new RC, and constantly hit refresh for the next minute or two to view the progress of the deploy. 

It would be great if Dashboard has some type of push mechanism so that resource state could be updated automatically without having to refresh the page.

**Comment by bryk** [comment]
We'd love to implement this, but at the moment we focus on covering all K8s resources. Once we have this we can start doing power features like this.

If you have time, you can contribute to implement this :)

And thanks for reporting this feature request! :)

**Comment by maciaszczykm** [comment]
Will track it from #1296.
