### ISSUE TITLE
Dashboard login screens Authentication Link goes to 404

### ISSUE THREAD

**Issue by prionkor** [kubernetes/dashboard#7970]
### What should be cleaned up or changed?

![image](https://github.com/kubernetes/dashboard/assets/1277201/2df515e4-9bfb-4025-bed6-9a5afb8b8cec)

It links to https://kubernetes.io/docs/admin/authentication/ which doesn't exists

### Why is this needed?

Goes to 404 page

**Comment by devashishTaneja** [comment]
@floreks I am a first time contributor to this repo, Can I take up this issue?

**Comment by nikhilchauhangithub** [comment]
It links to https://kubernetes.io/docs/admin/authentication/ which doesn't exists, so what can we expect after selecting or clicking token

**Comment by Kallepan** [comment]
This [https://kubernetes.io/docs/reference/access-authn-authz/authentication/](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) seems to be the correct one. It is also linked in the documentation about creating ["a sample user"](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md)

**Comment by nikhilchauhangithub** [comment]
@Kallepan can you please enlighten me on how to installation of this Dashboard, every single point

**Comment by Kallepan** [comment]
@prionkor The issue can be closed. See #7982.
