### ISSUE TITLE
Explicit container path for helm chart

### ISSUE THREAD

**Issue by jcpunk** [kubernetes/dashboard#7985]
### What would you like to be added?

Explicit paths to the containers in use.

### Why is this needed?

Currently the containers are set to `kubernetesui/dashboard:xyz` and `kubernetesui/metrics-scraper:xyz`.  This is a non-explicit source which my auditors flag as a possible risk.

They recommend setting it to explicitly `docker.io/kubernetesui/xyz`

### Other information

The chart source has this feature implemented, but the helm repository does not.

**Comment by floreks** [comment]
It has been already fixed on the master [here](https://github.com/kubernetes/dashboard/blob/master/charts/helm-chart/kubernetes-dashboard/values.yaml) and [here](https://github.com/kubernetes/dashboard/blob/master/charts/kubernetes-dashboard.yaml).

/close
