### ISSUE TITLE
Implement label handling in deploy form

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#80]
This issue is to implement label handling in deploy form for (RC, Pods, Services, etc.)

Based on this view:
https://raw.githubusercontent.com/kubernetes/dashboard/master/designs/11-11-2015/14_deploy%20more.png

I'm on it :)

**Comment by floreks** [comment]
@bryk: I have some questions.

Should all defined labels be set for created RC, Service and Pods? Same labels for all?
What should we do when someone defines 2 labels with same key. Error, warning, block deploy button?

**Comment by bryk** [comment]
Yes, apply the labels to everything. Take a look at: https://raw.githubusercontent.com/kubernetes/dashboard/master/designs/11-11-2015/14_deploy%20more.png

Re what to do in case of multiple labels with same key: This should be validation error. One of the inputs should be red and say what is wrong. The deploy button should be disabled too. Take a look on how validation is done in Angular and Angular Material: https://material.angularjs.org/latest/demo/select

CC @kenmoore
