### ISSUE TITLE
Deploy page: wrong alignment

### ISSUE THREAD

**Issue by gertisdemo** [kubernetes/dashboard#801]
On the Deploy page, the checkbox "Expose service externally" has been removed. Now the user can select "Internal" and "External". The descriptive text "Ports are optional..." no longer fits with the left-hand option. It has to be moved down a bit or displayed only in case the user selects internal or external service.

**Comment by cheld** [comment]
I think the definition of at least one port mapping is required, in case internal or external is selected. 

The two input fields are one component and have only one help text together. I would rather like to fix this by changing the message

**Comment by digitalfishpond** [comment]
Starting work on this

**Comment by digitalfishpond** [comment]
done
