### ISSUE TITLE
[Metrics scraper] The memory metrics are returned also for storage

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#8016]
Due to a coding error, the memory metrics are returned for both types.

Unfortunately the real metrics are always zero, but that's another story...

Opened by @afbjorklund.

See https://github.com/kubernetes-sigs/dashboard-metrics-scraper/issues/50 for more details.

**Comment by afbjorklund** [comment]
Currently storage isn't shown, so I'm not sure it's a problem (yet) ?

* https://github.com/kubernetes/dashboard/issues/7371
