### ISSUE TITLE
Why so many new pods in Helm chart?

### ISSUE THREAD

**Issue by regnaio** [kubernetes/dashboard#8019]
### What happened?

# Now
```shell
kubectl get po -n kubernetes-dashboard

NAME                                                           READY   STATUS    RESTARTS   AGE
kubernetes-dashboard-api-59978fdccb-8l2mp                      1/1     Running   0          6m47s
kubernetes-dashboard-cert-manager-6d98886d86-hmk6g             1/1     Running   0          6m47s
kubernetes-dashboard-cert-manager-cainjector-cf447686d-shpdt   1/1     Running   0          6m47s
kubernetes-dashboard-cert-manager-webhook-6494445df6-nbbbw     1/1     Running   0          6m47s
kubernetes-dashboard-metrics-scraper-689cbc745b-r8mnl          1/1     Running   0          6m47s
kubernetes-dashboard-nginx-controller-6d77b89c6d-gfltb         1/1     Running   0          6m47s
kubernetes-dashboard-web-864448b499-cgpdt                      1/1     Running   0          6m47s
```

---

# Before
Only the web dashboard and metrics scraper

---

# Question
Why are there so many new pods? And the Service name changed from `kubernetes-dashboard` to `kubernetes-dashboard-web`. This was a breaking change I had to fight in prod even without changing the Helm Chart (6.0.8) and App (v2.7.0) version

---

Was this caused by the [commit](https://github.com/kubernetes/dashboard/commit/d6c217d20b1ab52815955ea819bdc832529d71db)? @floreks 

### What did you expect to happen?

No breaking changes if Helm Chart and App version remain the same

### How can we reproduce it (as minimally and precisely as possible)?

Deploy Helm chart

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/releases/tag/v3.0.0-alpha0
https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard
https://github.com/kubernetes/dashboard#installation

It's clearly stated that the latest release introduces breaking changes and requires additional dependencies to run. There were major architecture changes and Dashboard is now a multi-container deployment. API and UI were split into separate containers and now require an ingress controller or API gateway to run correctly.

Note that this is still an alpha release and we expect there will be some issues.

/close
