### ISSUE TITLE
ingress proposed fixes

### ISSUE THREAD

**Issue by cipianpascu** [kubernetes/dashboard#8021]
### What happened?

1. refered services do not match the actual service names:
service/dashboard-kubernetes-dashboard-api     ClusterIP   10.44.183.116   <none>        9000/TCP   19m
service/dashboard-kubernetes-dashboard-web     ClusterIP   10.44.101.77    <none>        8000/TCP   19m

versus

        paths:
        - backend:
            service:
              name: kubernetes-dashboard-web
              port:
                name: web
          path: /
          pathType: ImplementationSpecific
        - backend:
            service:
              name: kubernetes-dashboard-api
              port:
                name: api
          path: /api
          pathType: ImplementationSpecific

2. it would be easier to work with clusterIssuer instead of the namespace issuer.  A better approach would be to leave this annotation for the clients to configure.

### What did you expect to happen?

reference to the service should match the actual service name

### How can we reproduce it (as minimally and precisely as possible)?

helm install with the following values:

nginx-ingress:
  enabled: false
cert-manager:
  enabled: false
app:
  ingress:
    issuer: letsencrypt-dashboard
    ingressClassName: nginx
    annotations:
        kubernetes.io/tls-acme: "true"
    hosts:
    - internet.url
    secretName: secret-prod

### Kubernetes Dashboard version

helm dashboard version: 7.0.0

### Kubernetes version

1.27

**Comment by floreks** [comment]
Good catch and a great idea with adding support for cluster issuer annotation too. I have updated the ingress resource and pushed the helm update. If you've got any other ideas on how to improve the new chart, feel free to create more issues. I am not that familiar with the DevOps side of Kubernetes, mostly the dev side :slightly_smiling_face:. There is definitely a lot to improve when it comes to deployment.

**Comment by cipianpascu** [comment]
thank you Sebastian

There is still an issue with the chart. Apparently, it tries to create the IngressClass even if this is the job of the ingress controller.

│ Error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "dashboard": current value is "nic"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kube-dashboard": current value is "ingress-controller"
│ 
│   with module.dashboard.helm_release.dashboard,
│   on dashboard/main.tf line 14, in resource "helm_release" "dashboard":
│   14: resource "helm_release" "dashboard" {


Kind regards,
Ciprian
