### ISSUE TITLE
CRDs not automatically installed?

### ISSUE THREAD

**Issue by jorgnyg** [kubernetes/dashboard#8026]
### What happened?

Trying to deploy the dashboard with flux in fresh aks cluster. Added source and helmrelease manifest below:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 30s
  url: https://kubernetes.github.io/dashboard/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-dashboard
      sourceRef:
        kind: HelmRepository
        name: kubernetes-dashboard
  targetNamespace: dashboard
  install:
    createNamespace: true
  values:
    metrics-server:
      # Set to false since it already exist
      enabled: false
```

It results in:
```
Last Helm logs:
  Warning  error  55s  helm-controller  reconciliation failed: Helm install failed: failed post-install: unable to build kubernetes object for deleting hook kubernetes-dashboard/templates/networking/post-install-ingress-issuer.yaml: resource mapping not found for name: "selfsigned" namespace: "" from "": no matches for kind "Issuer" in version "cert-manager.io/v1"
ensure CRDs are installed first
```

Might be missing something obvious here..

### What did you expect to happen?

Error about missing crds should not appear.

### How can we reproduce it (as minimally and precisely as possible)?

Create fresh aks cluster and apply the source and helmrelease added earlier.

### Kubernetes Dashboard version

v7

### Kubernetes version

1.26.3

**Comment by floreks** [comment]
I am not sure how flux works, but when using helm it for sure creates CRDs required by cert manager. Normally post-install hooks are called by helm after main chart have been installed successfully.

It might be an issue with how flux handles it.

**Comment by dvob** [comment]
@floreks Could we add an option in the Helm values to make cert-manager optional? In our environment we also don't have cert-manager and it would be nice if we could install the dashboard without installing cert-manager.

**Comment by floreks** [comment]
Right now cert-manager is a required dependency, so either you can install it manually in your cluster and disable it via chart values or let Dashboard chart install it. Dashboard Ingress won't work properly without it.

Chart already has value that allows enabling/disabling all dependencies. For cert-manager it is `cert-manager.enabled=false`.

**Comment by eigood** [comment]
We already have cert-manager installed(it's a cluster-level service installed *once* for all applications to use), why should kubernetes-dashboard think it needs to *install* it?  Sure, an enabled flag to turn on/off use of the cert-manager CRDs, but don't install them at all.

**Comment by floreks** [comment]
@eigood 

> Chart already has value that allows enabling/disabling all dependencies. For cert-manager it is cert-manager.enabled=false.

**Comment by dvob** [comment]
@floreks Thank you for the response. Didn't saw that this is already configurable.

**Comment by floreks** [comment]
Closing in favor of #8048

/close
