### ISSUE TITLE
Publish the chart for alpha releases as an "dev" version

### ISSUE THREAD

**Issue by jouve** [kubernetes/dashboard#8047]
### What happened?

the helm chart containing an alpha appVersion is published as a stable version

### What did you expect to happen?

the helm chart is published as a devel (as in needing helm `--devel` flag)

### How can we reproduce it (as minimally and precisely as possible)?

helm search repo kubernetes-dashboard

### Anything else we need to know?

helm `--devel` is consistent with [semver](https://semver.org/#spec-item-9): 

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.--.

### Kubernetes Dashboard version

na

### Kubernetes version

na

**Comment by floreks** [comment]
We can append chart version with `alpha` suffix too. I will have to check how hard it will be to update existing v7+ chart releases to also include this.

**Comment by floreks** [comment]
We have cleaned up all "stable" v7 releases and started over with the new `v7.0.0-alpha0` release for the chart. I hope it won't cause too much trouble for the users.

/close
