### ISSUE TITLE
[Helm] Chart updates

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#8048]
We will use this issue to track all approved changes to the helm chart. It will be easier to find and see what needs to be changed and what was already changed. Feel free to discuss further changes here and we can update it along the way. 

- [x] Allow `cert-manager` and `nginx` to be optional
  - [x] Allow disabling `cert-manager` annotations and providing secret with custom certificate
- [x] Allow disabling Ingress resource completely to allow usage of custom proxies (#8046)
- [x] Update default configuration and use internal nginx service by default
- [x] Fix NetworkPolicy configuration (#8045)
- [ ] Update documentation to inform that all chart dependencies (`cert-manager`, `nginx`, `metrics-server`) can be replaced with other alternatives and are only required by the default deployment.

Ref: #8038, #8043, #8044

**Comment by jcpunk** [comment]
Support for the GatewayAPI would be nice too.

https://github.com/kubernetes-sigs/gateway-api

**Comment by yamenkaba** [comment]
When I install the Helm after I install the crt-manager I get the following error,
![image](https://github.com/kubernetes/dashboard/assets/13351942/dbc8573b-5e85-45fb-a0f4-879cf70531a3)
The only wat it works is by installing first the Helm, get the crt-manager messing error, installing crt-manager and then re installing the helm
K8s 1.27.2
