### ISSUE TITLE
YAML/JSON editor: UX issues

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#814]
#### Issue details

Impossible to scroll down the JSON/YAML.
When I'm on my laptop, I can't scroll down the content of the modal with the trackpad, instead, it's the entire page which tries to scroll down. And there is no vertical scroll bar.

Also, as you can see in the screenshot, this blue bar does not display properly.

![image](https://cloud.githubusercontent.com/assets/7731641/15781706/bc59d05e-29ea-11e6-81e2-4e9aa56bd40d.png)

##### Environment
```
Dashboard version: v1.1.0-beta2
Kubernetes version: v1.2.4
Operating system: CoreOS
Chrome version: MacOSX / 50.0.2661.102
```

##### Steps to reproduce
Try to edit a JSON/YAML resource and to scroll down the content.

**Comment by edouardKaiser** [comment]
I can't reproduce anymore. The editing looks fine now and I can scroll. Maybe it was a browser cache issue. But I'm 99.9% sure I cleaned my cache before using the new dashboard. I close this one and will re-open if necessary.

**Comment by bryk** [comment]
Please reopen if you can reproduce this. We have betas for fix such issues :)

**Comment by bryk** [comment]
Reproduced this. Fixing.
