### ISSUE TITLE
Cannot install with helm

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [kubernetes/dashboard#8143]
### What happened?

$ helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
Release "kubernetes-dashboard" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: APIService "v1beta1.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "kubernetes-dashboard": current value is "dev-cm-kvision-metrics-server"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kubernetes-dashboard": current value is "kube-system"

### What did you expect to happen?

Installation succeeded

### How can we reproduce it (as minimally and precisely as possible)?

Provided command

### Anything else we need to know?

$ k version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.3-eks-a5565ad", GitCommit:"78c8293d1c65e8a153bf3c03802ab9358c0e1a14", GitTreeState:"clean", BuildDate:"2023-06-16T17:32:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

latest

### Kubernetes version

1.27.3

**Comment by maciaszczykm** [comment]
@DavidPerezIngeniero do you try to install newest version, v3 alpha? If that is the case then [**clean installation is required**](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard#breaking-change).

**Comment by floreks** [comment]
You might want to disable the metrics server via chart values. It looks like it is already installed in your cluster.

**Comment by DavidPerezIngeniero** [comment]
> @DavidPerezIngeniero do you try to install newest version, v3 alpha? If that is the case then [**clean installation is required**](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard#breaking-change).

no, I  prefer to play with stable ones

**Comment by DarkSmile92** [comment]
Just ran into the same issue… used this terraform code:
```
resource "helm_release" "kubernetes_dashboard" {
  name       = "kubernetes-dashboard"
  repository = "https://kubernetes.github.io/dashboard/"
  chart      = "kubernetes-dashboard"
  namespace  = "kube-system"

  set {
    name  = "service.type"
    value = "LoadBalancer"
  }
}

# expose kubernetes dashboard
resource "kubernetes_ingress_v1" "dashboard_ingress" {
  metadata {
    name      = "dashboard-ingress"
    namespace = "kube-system"
  }

  spec {
    rule {
      http {
        path {
          backend {
            service {
              name = helm_release.kubernetes_dashboard.metadata[0].name
              port { number = 80 }
            }
          }

          path      = "/"
          path_type = "Prefix"
        }
      }
    }
  }
}
```

**Comment by stuarta** [comment]
> You might want to disable the metrics server via chart values. It looks like it is already installed in your cluster.

We install the metrics-server via it's own helm chart, and disable the metrics server via the chart values, yet we still hit this error. This implies that the chart is still trying to install metrics server even though it's meant to be disabled

**Comment by floreks** [comment]
Metrics server was already installed in the cluster. It is controlled by `metrics-server.enabled` flag. This is a configuration issue.

/close
