### ISSUE TITLE
Error 500 when 

### ISSUE THREAD

**Issue by aabed** [kubernetes/dashboard#815]
##### Environment
kubectl create -f <file from github repo>

```
Dashboard version:v1.1.0-beta2
Kubernetes version:1.2.0
Operating system:fedora 23

```

##### Steps to reproduce
Navigate to dashboard and click on any deployment's name

##### Observed result
![screenshot from 2016-06-03 22-19-43](https://cloud.githubusercontent.com/assets/1152929/15792107/da10c47e-29e3-11e6-8e16-973e115a80f2.png)

**Comment by edouardKaiser** [comment]
Duplicate with #812 I guess

**Comment by aabed** [comment]
@edouardKaiser  yes, you are right, I will close it
