### ISSUE TITLE
Error installing via HELM

### ISSUE THREAD

**Issue by Neumsy** [kubernetes/dashboard#8150]
### What happened?

Executed the helm installation command on a kube cluster running on RHEL8.

helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
Release "kubernetes-dashboard" does not exist. Installing it now.
Error: 1 error occurred:
	* Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://kubernetes-dashboard-1690314648-nginx-controller-admission.kubernetes-dashboard.svc:443/networking/v1/ingresses?timeout=10s": service "kubernetes-dashboard-1690314648-nginx-controller-admission" not found

### What did you expect to happen?

Helm chart to install the dashboard with no errors.

### How can we reproduce it (as minimally and precisely as possible)?

Bare metal install of kubernetes on RHEL8 with 1 worker node and 1 master node.

### Kubernetes Dashboard version

3.0.0-alpha0

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by floreks** [comment]
Looks like a flake. Did you try rerunning it? Maybe with a `--wait` arg?

**Comment by Neumsy** [comment]
@floreks I ran
```
helm delete kubernetes-dashboard --namespace kubernetes-dashboard
```
Then
```
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard --wait
```

**Comment by KagariSan** [comment]
@Neumsy 
I did a clean install and got the error differently.
In my case, the hook response refused to connect instead.
`helm install my-kubernetes-dashboard k8s-dashboard/kubernetes-dashboard --version 7.0.3 -n kube-dashboard
Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install kubernetes-dashboard/templates/networking/post-install-ingress-issuer.yaml failed: Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://my-kubernetes-dashboard-cert-manager-webhook.kube-dashboard.svc:443/mutate?timeout=10s": dial tcp 10.152.183.222:443: connect: connection refused`

**Comment by imdmahajankanika** [comment]
> @floreks Another note. I was able to access the dashboard with port forwarding to the service (ingress access is pending due to our network configuration).
> 
> However, I do get the following error during the install:
> 
> ```
> Release "kubernetes-dashboard" does not exist. Installing it now.
> Error: failed post-install: warning: Hook post-install kubernetes-dashboard/templates/networking/post-install-ingress-issuer.yaml failed: 1 error occurred:
> 	* Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://kubernetes-dashboard-1690314648-cert-manager-webhook.kubernetes-dashboard.svc:443/mutate?timeout=10s": service "kubernetes-dashboard-1690314648-cert-manager-webhook" not found
> ```
> 
> Again, I can access the dashboard via port forwarding even with this error.

Hello, I am also getting the same issue

**Comment by floreks** [comment]
Starting from the next release (this week) ingress controller and cert-manager will no longer be default dependencies. This should simplify the installation and help with this annoying webhook race-condition/leftover issue.

/close
