### ISSUE TITLE
Namespace selection dropdown

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#816]
#### Issue details

I think the default choice behaviour is not obvious.
By default, the drop down is on "namespace not selected". You would expect from this, to display all the resources from every namespace. But actually it displays the resources from whatever namespace is configured as the `default` namespace.

I see two possibilities personally:
- Remove this entry, and by default, select whatever is the default namespace
- Keep the entry but display everything from every namespace

Thoughts ?
##### Environment

```
Dashboard version: v1.1.0-beta2
Kubernetes version: v1.2.4
Operating system: CoreOS
```

**Comment by edouardKaiser** [comment]
Also, does that make sense to still display the dropdown on the details view of a resource ?
Because, it doesn't matter what I do with the dropdown, the details of the resource does not change.

Example where the selected namespace in the dropdown is different from the namespace of the resource:

![image](https://cloud.githubusercontent.com/assets/7731641/15799228/6f965e82-2a98-11e6-9dc0-ec42e945f6ed.png)

**Comment by bryk** [comment]
Starting work on this...

**Comment by maciaszczykm** [comment]
@edouardKaiser @bryk Can we close it?

**Comment by floreks** [comment]
Fixed in #892

**Comment by edouardKaiser** [comment]
The dropdown is still displayed when viewing the details of a resource.

**Comment by maciaszczykm** [comment]
IMO we should disable namespace selector when we're on details page, not on list/summary page. It should be also disabled for non-namespaced resources like namespaces or nodes.

**Comment by maciaszczykm** [comment]
Second solution is to redirect to list page when changing namespace from details page.

**Comment by bryk** [comment]
Yep. I think we should tackle this problem in our second iteration of Nav&Chrome.

**Comment by jaiew** [comment]
Is this still being looked at?

It's still confusing when switching a namespaces but it stays on the current resource you were looking at.

Eg. If in a staging namespace and looking at deployments, if you switch to production namespace it shows a loading screen but you're still viewing the previous staging resource. Changing namespaces should send land you on the Workloads screen

**Comment by maciaszczykm** [comment]
Taking care of it right now.
