### ISSUE TITLE
make default clusterrolebinding configurable

### ISSUE THREAD

**Issue by kaiehrhardt** [kubernetes/dashboard#8160]
### What would you like to be added?

Pretty much [this](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#admin-privileges) just natively supported by helm chart.

### Why is this needed?

Get rid of helm post config.

**Comment by floreks** [comment]
The next release drops support for "act on behalf of Kubernetes Dashboard" making this issue no longer valid. Only acting on behalf of the user will be supported now.

/close
