### ISSUE TITLE
Can't auto-start kubectl-proxy

### ISSUE THREAD

**Issue by romanad** [kubernetes/dashboard#8170]
### What happened?

Dear friend,
When I run manually "kubectl-proxy" - Dashboard starts OK.
But if I put "kubectl-proxy" In Cron or systemctl service I keep getting this error: "dial tcp 127.0.0.1:8080: connect: connection refused"
Could you explain why this strange behavior occurs and how to configure autostart for kubectl-proxy?

### What did you expect to happen?

Expected to be able to open dashboard page: http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/workloads?namespace=default

### How can we reproduce it (as minimally and precisely as possible)?

Install Kubernetes and Dashboard

Try to put kubectl-proxy to Cron or create kubectlproxy.service with systemd and then run http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/ at control plane. You will get  "proxy error: dial tcp [::1]:8080: connect: connection refused".

But if you run "kubectl-proxy" in terminal manually - dashboard works.

### Kubernetes Dashboard version

Dashboard v2.7.0+0.g42deb6b32

### Kubernetes version

GitVersion:"v1.27.4"

### Dev environment

go version go1.18.1 linux/amd64

node --version v12.22.9

**Comment by romanad** [comment]
My bad, misconfig. Everything is fine!

**Comment by janithcooray** [comment]
Having an identical issue, the document only describes how to get it up and running on localhost using a proxy. it's a bit confusing for beginner.
