### ISSUE TITLE
Every version in the 7.x.y range got wiped from the Helm repository after merging #8103

### ISSUE THREAD

**Issue by WyriHaximus** [kubernetes/dashboard#8191]
### What happened?

When iterating over a dashboard set up before lunch everything work, after lunch I'm now getting the following error:
```
Error: failed to fetch https://kubernetes.github.io/dashboard/kubernetes-dashboard-7.0.3.tgz : 404 Not Found
```

### What did you expect to happen?

For helm to complete the installationHelm

### How can we reproduce it (as minimally and precisely as possible)?

```
helm install my-kubernetes-dashboard k8s-dashboard/kubernetes-dashboard --version 7.0.3
```

### Anything else we need to know?

Merging this change https://github.com/kubernetes/dashboard/pull/8103/files#diff-a5576e0c4e7c41a18e24d61963d76c69d9e181d8b9a88f87ce56842a922586a1R17 wiped out in the `7.x.y` range and only leaves `7.0.0-alpha0` there as can be seen here: https://github.com/kubernetes/dashboard/commit/5fba1112af120e1aba6be52230a1035215d11c08 (Through https://github.com/kubernetes/dashboard/pull/8190.) Note that this also wiped the tarballs so anyone with an old repo version can't use that anymore.

### Kubernetes Dashboard version

n/a

### Kubernetes version

1.27

### Dev environment

kind

**Comment by floreks** [comment]
Unfortunately, this was intentional. We shouldn't release a stable chart version when the app was marked as an alpha in the first place and that was our mistake. It was brought to our attention by some of the users. In order to fix that, the only way was to clean up invalid "stable" chart releases and start over with the v7 alpha release. We are sorry for any issue it might have caused but to be in sync with the correct versioning scheme and app version, we've had to do this.

Ref: https://github.com/kubernetes/dashboard/issues/8047

**Comment by WyriHaximus** [comment]
> Unfortunately, this was intentional. We shouldn't release a stable chart version when the app was marked as an alpha in the first place and that was our mistake. It was brought to our attention by some of the users. In order to fix that, the only way was to clean up invalid "stable" chart releases and start over with the v7 alpha release.

Thank you for clarifying why those versions were yanked. And yes that makes sense and I fully agree. It was a bit of an off moment, and I missed the `updated helm chart versioning to start with alpha. When releasing the helm chart we will remove previous "official" releases without alpha suffixes.` in #8103 now that I'm having a better look at it.

> We are sorry for any issue it might have caused but to be in sync with the correct versioning scheme and app version, we've had to do this

Shit happens, going back to v6 for now :+1:
