### ISSUE TITLE
502 Error while accessing the Dashboard using ALB Controller

### ISSUE THREAD

**Issue by manali14** [kubernetes/dashboard#8208]
### What happened?

I deployed my Kubernetes Dashboard using v7.0.0-alpha0 of the chart by customizing the following values:

`
app:
    ingress:
    enabled: true
    hosts:
    # Keep 'localhost' host only if you want to access Dashboard using 'kubectl port-forward ...' on:
    # https://localhost:8443
    ingressClassName: alb
    pathType: Prefix
    secretName: kubernetes-dashboard-certs
    issuer:
      name:
      # Scope determines what kind of issuer annotation will be used on ingress resource
      # - default - adds 'cert-manager.io/issuer'
      # - cluster - adds 'cert-manager.io/cluster-issuer'
      # - disabled - disables cert-manager annotations
      scope: disabled
    labels: {}
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
 ......
    paths:
      web: /
      api: /api
cert-manager:
  enabled: false
  installCRDs: false
nginx:
  enabled: false
`

IMy pods are running fine and post updating the Service Type from `ClusterIP` to `NodePort` my Ingress is able to attach to an existing LB. But, when I am trying to access the endpoint using the DNS/LB Url, I am getting a 502

### What did you expect to happen?

Expected it to load the Dashboard Page asking for Token/Kube config

### How can we reproduce it (as minimally and precisely as possible)?

helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -n kubernetes-dashboard  -f k8s-dashboard/values.yaml  --version 7.0.0-alpha0

Run the above command with values.yaml having the values for alb ingress controller

### Kubernetes Dashboard version

7.0.0-alpha0

### Kubernetes version

1.26

**Comment by floreks** [comment]
A new release will change the way Dashboard is being exposed invalidating this issue.

/close
