### ISSUE TITLE
Provide context to `GetPluginSource`

### ISSUE THREAD

**Issue by artemmarkaryan** [kubernetes/dashboard#8211]
### What should be cleaned up or changed?

Now `GetPluginSource` uses `context.TODO()` stub to call both dashboard and k8s api client. 

```go
// GetPluginSource has the logic to get the actual plugin source code from information in Plugin.Spec
func GetPluginSource(client pluginclientset.Interface, k8sClient kubernetes.Interface, ns string, name string) ([]byte, error) {
	plugin, err := client.DashboardV1alpha1().Plugins(ns).Get(context.TODO(), name, v1.GetOptions{})
	...
	cfgMap, err := k8sClient.CoreV1().ConfigMaps(ns).Get(context.TODO(), plugin.Spec.Source.ConfigMapRef.Name, v1.GetOptions{})
	...
}
```

`GetPluginSource` is only called in `servePluginSource` handler, which has a request context. Context of the request, as far as I can judge, could be passed to `GetPluginSource` as argument.

### Why is this needed?

It is useful to control application's state through context at least not to waste resources on canceled requests.

**Comment by Sajiyah-Salat** [comment]
Hello @artemmarkaryan I am new to this repo it would be good if you can provide me context like where change is required. and how or any details about this issue. It would be highly helpful for me to work on this. Thank you!

**Comment by artemmarkaryan** [comment]
Hi @Sajiyah-Salat! 

Thanks for your willingness to help but I actually was going to fix this myself. 

Actually i came across several place in dashboard codebase where context.TODO() is used, although it is quite possible to provide real context from request. If you'd like, you may try to find such places yourself. I'm not sure that fixes in other places should be related to this issue. It seems more reasonable to create a separate issue for each.

**Comment by artemmarkaryan** [comment]
@maciaszczykm, hi! There are several other places, where `context.TODO()` is used instead of request's context. Is it okay to fix them as a part of this issue or I should create an issue for each? 

Also, by any chance, could these `context.TODO()` have been left intentionally? Maybe they should not be replaced? I couldn't find a reason for that, but maybe there's some point i'm missing.

**Comment by maciaszczykm** [comment]
>  Is it okay to fix them as a part of this issue or I should create an issue for each?
@artemmarkaryan Sure.

> Also, by any chance, could these context.TODO() have been left intentionally? Maybe they should not be replaced? I couldn't find a reason for that, but maybe there's some point i'm missing.
I don't think there is specific reason. Let's do PR and review then.

**Comment by vlasebian** [comment]
Hello! Is there someone working on this issue? I would like to take this up if it's possible.
