### ISSUE TITLE
Error message is not shown when cause it continuously

### ISSUE THREAD

**Issue by Yamagami-Takuma** [kubernetes/dashboard#822]
#### Issue details

At the Deploy a Containerized App page, when we cause different type errors continuously on the same input box, subsequent error messages are not shown.

##### Environment

```
Dashboard version: 1709a3223517c7146964d50528a8f715098b10ac
Kubernetes version: 1.2.4
Operating system: Ubuntu 14.04
Node.js version: 5.11.1
Go version: 1.6.2
```

##### Steps to reproduce

1. Access to the page of Deploy a Containerized App.
2. focus on the input form of app name and focus out it. Then error message 'Application name is required.' is shown.
3. Type the not available character (e.g. '+') into input form.
4. No error message is shown.

Once valid value is input, the next error message is shown.

##### Observed result

![issue](https://cloud.githubusercontent.com/assets/13443650/15815892/cc61ff04-2c0a-11e6-99cd-baf475306668.gif)

##### Expected result

Any time error messages are shown.

**Comment by cheld** [comment]
This is a material-design bug. It appears on the demo widgets as well. Can you open an issue there too?

**Comment by Yamagami-Takuma** [comment]
Sure.
But this issue is already open at angular material project when I check issues.
angular/material#8635

**Comment by bryk** [comment]
Should we close this?

**Comment by Yamagami-Takuma** [comment]
I think not to close now.
I'm watching that issue. And after it is closed, I close this.

**Comment by bryk** [comment]
Ok, perfect

**Comment by Yamagami-Takuma** [comment]
The issue of angular material project is closed.  
So I close this issue.

**Comment by cheld** [comment]
Thanks, for follwoing this

**Comment by maciaszczykm** [comment]
I guess we should wait till we update Angular version in Dashboard, so bug will no longer occur.

**Comment by bryk** [comment]
That's fine. Angular will autoupdate for our next release.
