### ISSUE TITLE
Configurable path prefix

### ISSUE THREAD

**Issue by jkroepke** [kubernetes/dashboard#8224]
### What would you like to be added?

Please add the possible to run the Kubernetes api and web under different web prefixes, like

- https://localhost/dashboard/api
- https://localhost/dashboard/web

### Why is this needed?

I would like to run all my management tools under the same domain.

If possible, any cookies created by the dashboard should also have the prefix inside it.

**Comment by floreks** [comment]
We could potentially allow frontend to be server under a different suffix, but the API path is required to be accessible as a subpath of the UI right now. This means that if web will be accessible under `xyz.com/dashboardui` then API has to be available under `xyz.com/dashboardui/api`. This is currently a hard requirement.

**Comment by jkroepke** [comment]
That fine for me.

**Comment by jkroepke** [comment]
I make the setup having the dashboard behind a reverse proxy more simple. Currently. I have to deal with rewrite rules on nginx

**Comment by jkroepke** [comment]
Up

**Comment by jkroepke** [comment]
Up

**Comment by floreks** [comment]
See my comment: https://github.com/kubernetes/dashboard/issues/8053#issuecomment-1979494075
