### ISSUE TITLE
Memory metrics shows data on Gi instead of Mi

### ISSUE THREAD

**Issue by droslean** [kubernetes/dashboard#8240]
### What happened?

![image](https://github.com/kubernetes/dashboard/assets/8650912/8b3418f3-07f9-4d7a-bc09-82c23f0e4eb5)

### What did you expect to happen?

I would expect the memory usage to be in `Mi` instead of `Gi`

### How can we reproduce it (as minimally and precisely as possible)?

Just run a pod and observe the memory metrics

### Kubernetes Dashboard version

v2.4.0

### Kubernetes version

1.18.8

**Comment by floreks** [comment]
Dashboard `v2.4.0` is not supported anymore and we do not provide fixes for it.

/close
