### ISSUE TITLE
New stable version doesn't support api arguments settings through Helm

### ISSUE THREAD

**Issue by roin-orca** [kubernetes/dashboard#8263]
### What happened?

Setting-up arguments for the api component under the api.containers.args array in the values.yaml helm manifest do nothing.

### What did you expect to happen?

I tried enable-skip-login and enable-insecure-login=false and none of them took effect.

### How can we reproduce it (as minimally and precisely as possible)?

helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -f values.yaml --create-namespace --namespace kubernetes-dashboard

where values.yaml contains
api:
  containers:
    args:
      - --enable-skip-login

### Kubernetes Dashboard version

latest

### Kubernetes version

Client Version: v1.28.0

**Comment by floreks** [comment]
I will take a look on Friday but I don't see a reason why it wouldn't be propagated. Values are dumped directly into the template. Did you check `kubectl describe ...` for the API deployment to make sure args are not there?

https://github.com/kubernetes/dashboard/blob/c32a81d32f23928542070cc7c6de1c32f161a5b1/charts/helm-chart/kubernetes-dashboard/templates/deployments/api.yaml#L49-L54

**Comment by floreks** [comment]
Looks like invalid user configuration. Closing

/close
