### ISSUE TITLE
Dashboard can not sort PVs by status in a descending order

### ISSUE THREAD

**Issue by Sebastian-RG** [kubernetes/dashboard#8320]
### What happened?

On the dashboard PV tab, it is not possible to switch sorting PVs by ascending and descending status.
If the "sort by status" arrow is clicked more than once, the list of PVs will not change to sort by descending.

### What did you expect to happen?

Clicking the "sort by status" arrow a second time would change the order of the list of PVs, showing Released PVs first.
This has been tested on Dashboard version v2.7.0, v2.6.1 and v2.4.0

### How can we reproduce it (as minimally and precisely as possible)?

Have both Bound and Released PVs. Go to the dashboard PV tab. Click the arrow to order by status more than once.

### Anything else we need to know?

Ordering of other resources and ordering PVs by name works correctly

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

v2.7.0 

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:14:46Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:08:49Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Sebastian-RG** [comment]
It is possible that this is a similar bug, but for PVs
https://github.com/kubernetes/dashboard/issues/5119

**Comment by jvleminc** [comment]
Maybe @maciaszczykm could have a look also at this one?

**Comment by Sebastian-RG** [comment]
PR open, waiting for review

**Comment by Sebastian-RG** [comment]
PR merged, closing issue
