### ISSUE TITLE
The workload status indication graph is displayed in black.

### ISSUE THREAD

**Issue by bkkoli** [kubernetes/dashboard#8321]
### What happened?

The workload status indication graph is displayed in black.

### What did you expect to happen?

I think it should be displayed in a different color depending on the state of the resource.

### How can we reproduce it (as minimally and precisely as possible)?

Go to the Kubernetes dashboard page and click on the workload page.

![image](https://github.com/kubernetes/dashboard/assets/41296400/d43ed70d-2aa0-49f5-afaa-4fedb333f63f)

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

v1.28.2

**Comment by maciaszczykm** [comment]
Is is already fixed by https://github.com/kubernetes/dashboard/pull/7546. You will need to wait for new release or use master.

**Comment by bkkoli** [comment]
@maciaszczykm Thank you for your kind answer.
