### ISSUE TITLE
Minor: Ingress display

### ISSUE THREAD

**Issue by aug70** [kubernetes/dashboard#8328]
### What happened?

Minor UI issue.
Ingress list "Hosts" column doesn't put any whitespace between multiple hosts.

### What did you expect to happen?

See the two links separated by whitespace

### How can we reproduce it (as minimally and precisely as possible)?

Just have multiple hosts under ingress and visit ingress page.

### Kubernetes Dashboard version

kubernetes-dashboard helm chart 7.0.0-alpha1

### Kubernetes version

1.27.x

**Comment by RafikFarhad** [comment]
@maciaszczykm Can I work on this?

**Comment by maciaszczykm** [comment]
@RafikFarhad yes.

/assign @RafikFarhad
