### ISSUE TITLE
kube manifest  ootb deploy working but helm deploy not accable 

### ISSUE THREAD

**Issue by tim-oe** [kubernetes/dashboard#8350]
### What happened?

I'm using a rpi based cluster with K3s

deployed using manifest deployment and added user
https://github.com/kubernetes/dashboard/releases/tag/v3.0.0-alpha0
https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

but deploying using helm chart via terraform
https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard
`provider "kubernetes" {
  config_path = "~/.kube/config"
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "kubernetes_namespace" "kubernetes_dashboard" {
  metadata {
    name = "kubernetes-dashboard"

    labels = {
      name = "kubernetes-dashboard"
    }
  }
}

resource "helm_release" "kubernetes_dashboard" {
  name             = "kubernetes-dashboard"
  repository       = "https://kubernetes.github.io/dashboard/"
  chart            = "kubernetes-dashboard"
  create_namespace = true
  namespace        = "kubernetes-dashboard"

  depends_on = [kubernetes_namespace.kubernetes_dashboard]
}

resource "kubernetes_service_account" "admin_user" {
  metadata {
    name      = "admin-user"
    namespace = "kubernetes-dashboard"
  }

  depends_on = [helm_release.kubernetes_dashboard]
}

resource "kubernetes_cluster_role_binding" "admin_user_binding" {
  metadata {
    name = "admin_user_binding"
  }

  subject {
    kind      = "ServiceAccount"
    name      = "admin-user"
    namespace = "kubernetes-dashboard"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  depends_on = [kubernetes_service_account.admin_user]
}

resource "kubernetes_secret" "admin-user-token" {
  
  metadata {
    name = "admin-user-token"
    namespace = "kubernetes-dashboard"

    annotations = {
      "kubernetes.io/service-account.name" = "admin-user"
    }
  }

  type = "kubernetes.io/service-account-token"
  depends_on = [kubernetes_service_account.admin_user]
}`

trying to access the UI i get the following response:

`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:\"",
  "reason": "ServiceUnavailable",
  "code": 503
}`

### What did you expect to happen?

the UI to load and be able to access the dashboard

### How can we reproduce it (as minimally and precisely as possible)?

use deployment methods to deploy above

### Kubernetes Dashboard version
v3.0.0-alpha0

### Kubernetes version
v1.27.6+k3s1

### Dev environment

`
NAME        STATUS   ROLES                VERSION      OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
kube-n2     Ready    <none>               v1.27.6+k3s1 Ubuntu 22.04.3 LTS   5.15.0-1038-raspi   containerd://1.7.6-k3s1.27

kube-n1     Ready    <none>               v1.27.6+k3s1 Ubuntu 22.04.3 LTS   5.15.0-1038-raspi   containerd://1.7.6-k3s1.27

kube-ctlr   Ready    control-plane,master v1.27.6+k3s1 Ubuntu 22.04.3 LTS   5.15.0-1038-raspi   containerd://1.7.6-k3s1.27

kube-n3     Ready    <none>               v1.27.6+k3s1 Ubuntu 22.04.3 LTS   5.15.0-1038-raspi   containerd://1.7.6-k3s1.27
`

**Comment by floreks** [comment]
This does not look like an issue on our side but rather your terraform configuration. If there will be an issue with helm directly that we can reproduce using only Helm then we can fix it.

/close
