### ISSUE TITLE
service object doesn't have ExternalEndpoints data

### ISSUE THREAD

**Issue by digitalfishpond** [kubernetes/dashboard#836]
src/app/backend/resource/service/servicecommon.go doesn't have ExternalEndpoints implemented

**Comment by therc** [comment]
Given that I'm (partially) improving the current `kubectl get` behaviour, a quick pointer:

https://github.com/kubernetes/kubernetes/pull/26749/files#diff-0fc00b94def20930bb77075c7e2c7599

You basically need to get Spec.ExternalIPs and, if missing, for LoadBalancer services return the ingresses (their IPs, or, if missing as is the case under AWS, their Hostnames).

**Comment by bryk** [comment]
@therc Oh, thanks!
