### ISSUE TITLE
Dashboard not working in Hyperkube

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#838]
#### Issue details
Dashboard that is deployed by Hyperkube crashes

##### Environment
Hyperkube

```
Dashboard version:  v1.1.0-beta2
Kubernetes version: 1.3.0-alpha.5
Operating system: Linux
```

##### Steps to reproduce
- Open hyperkube.sh
- change version to v1.3.0-alpha.5
- run it
- kubectl get pods --all-namespaces

##### Observed result
Dashboard does not start. Logs:

2016/06/06 13:33:47 Starting HTTP server on port 9090
2016/06/06 13:33:47 Creating API server client for http://localhost:8080
2016/06/06 13:33:47 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get http://localhost:8080/version: dial tcp [::1]:8080: getsockopt: connection refused

##### Comments
I tried the following:

```
kubectl run debain2 --image debian sleep 1000000
kubectl exec debain2-1251972161-9gmx5 ls /var/run/secrets/kubernetes.io/serviceaccount
```
Result is empty dir. Is service account broken in Hyperkube? Any quick idea?

@luxas, @bryk

**Comment by bryk** [comment]
I remember that last time @fgrzadkowski told me that there are no service accounts on hyperkube.

**Comment by cheld** [comment]
ok, I see. it is not super obvious.... I tried the following with v1.2.4 & v1.3.0-alpha.4

```
kubectl run debain2 --image debian sleep 1000000
kubectl exec debain2-1251972161-9gmx5 ls /var/run/secrets/kubernetes.io/serviceaccount
ca.crt
namespace
token
```
Also

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/addon-manager/namespace.yaml
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```

works. I am glad...

So it seems that something changed between v1.3.0-alpha.4 and v1.3.0-alpha.5

**Comment by cheld** [comment]
hmm, I think I create a bug in core...

**Comment by cheld** [comment]
Let's see...

https://github.com/kubernetes/kubernetes/issues/26943

**Comment by cheld** [comment]
we only need one bug.

**Comment by santanu-dey** [comment]
This issue seems to be propagated all the way down to v1.4.0-alpha.1

**Comment by bryk** [comment]
@santanu-dey Please ping the linked issue. The problem is with hyperkube.

**Comment by bweston92** [comment]
I have this issue too, how do I create a service account or what I need?

**Comment by cheld** [comment]
Finally, the prerequisites steps are documented:

https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/docker.md

**Comment by bryk** [comment]
@cheld The link is dead. Can you provide a new one?

**Comment by luxas** [comment]
@bryk The hyperkube getting-started-guide is dead, to avoid confusing new users.
It's a fully working way to setup a one-node cluster (and maybe one of the easiest ways too), but it's not user-friendly given the long command, linux only, not obvious how to turndown and use, so therefore it was removed.
But you may still run kubelet in docker just fine, and many deployments will do it.

**Comment by bryk** [comment]
@luxas Interesting. Thanks for the answer.
