### ISSUE TITLE
Helm chart and ALB(AWS) controller configuration 

### ISSUE THREAD

**Issue by Yolooman** [kubernetes/dashboard#8420]
### What would you like to be added?

Hi,

I'm trying the new helm chart for kube-dashboard v3 but i want to use the ALB controller and not the nginx one.
As it was configured it is not possible to use it (or changes has to be made manually).
As we need to use a /* and /api/* path for the ALB controller, we never reach the /api endpoint as the /* hold the request first.

Moreover, the /api endpoint return a 404 (which is normal) and the alb check failed (i can hold it accepting any 404 as a right request but it's not a normal behaviour)

### Why is this needed?

Switch the path on the ingress, using the /api first or at least add the possibility to use one ingress for / and another for /api

**Comment by floreks** [comment]
We will be releasing v3.0.0 stable version soon and it will handle access through kong gateway. Only the root path will be exposed by it, which should give you more flexibility in configuring your ingress. 

/close
