### ISSUE TITLE
npm ERR! enoent Could not read package.json

### ISSUE THREAD

**Issue by willzhang** [kubernetes/dashboard#8431]
### What happened?

The developer getting-started docs not work：https://github.com/kubernetes/dashboard/blob/master/docs/developer/getting-started.md

### What did you expect to happen?

npm start success, but it failed

```
root@ubuntu:/data/git/dashboard# npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /data/git/dashboard/package.json
npm ERR! errno -2
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/data/git/dashboard/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-31T03_00_48_318Z-debug-0.log
```

### How can we reproduce it (as minimally and precisely as possible)?

```
git clone https://github.com/kubernetes/dashboard.git
cd dashboard
make --directory modules/common/tools install
yarn
npm start
```

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

master

### Kubernetes version

v1.25.11

**Comment by enneitex** [comment]
hey, can you trying doing it from modules/web directory ?

**Comment by willzhang** [comment]
it work ,but listen on 127.0.0.1, how can i change this?

**Comment by floreks** [comment]
Do not run it from web module unless you know what you're doing. Use Makefile targets. They are documented and can run prod and dev version of app.

**Comment by able8** [comment]
I have also encountered this issue.

**Comment by floreks** [comment]
Follow root makefile targets to get started. We will update our dev docs eventually.

/close
