### ISSUE TITLE
Workload page does not display services

### ISSUE THREAD

**Issue by therc** [kubernetes/dashboard#848]
```
Dashboard version: 1.1.0-beta2
Kubernetes version: HEAD, 1.3
Operating system: CoreOS
Node.js version: whatever is in the image
Go version: ditto
```

##### Steps to reproduce
Open the top page, workloads

##### Observed result
No list of services

##### Expected result
Services are listed

##### Comments
The workload backend seems to open a channel to list services, but it doesn't seem to make use of it.

**Comment by maciaszczykm** [comment]
Services will be available from menu. You can check our resource categorization at kubernetes/kubernetes/issues/22687.

**Comment by bryk** [comment]
@maciaszczykm That's true. We should think, however, about including Services on workloads pages as an interim solution. This is because we likely will not have the menu for 1.1 release, but later.

**Comment by edouardKaiser** [comment]
That would be awesome as an interim solution, definitely. Service is a major resource in Kubernetes.

**Comment by bryk** [comment]
And anyway, you can just now manually type the URL: `#/service`.

**Comment by edouardKaiser** [comment]
Great, didn't know that trick, just tried, it works.

**Comment by therc** [comment]
I knew about `#/service`, but only because I had looked at the source. :-)

**Comment by maciaszczykm** [comment]
@therc @edouardKaiser @bryk Can we close it?

**Comment by therc** [comment]
The service URL is not discoverable. Could we at least have a link from the workload page, in one of the two bars at the top?

**Comment by maciaszczykm** [comment]
@therc It's discoverable only for replication controllers:

![image](https://cloud.githubusercontent.com/assets/2823399/16257599/cc101d5a-3859-11e6-97c8-e2891a3cb8d4.png)

We'll also add it to the menu, which should be introduced soon. That's why I think we shouldn't add link to workloads page.

**Comment by bryk** [comment]
@therc That's, unfortunately, true. But we will have a next release with menu soon.
