### ISSUE TITLE
[Developer Experience/DX] Easy way to docker build api and web images w/ modifications

### ISSUE THREAD

**Issue by mecampbellsoup** [kubernetes/dashboard#8495]
### What would you like to be added?

Hi guys,

We use [Skaffold](https://skaffold.dev/) as a core part of our development workflow.

I'm looking for an easy way to:

1. Checkout the source code locally (easy/done)
2. Build development versions of the web and api images w/ my own modifications

I see `hack/develop/run-dev-container.sh` but is there an easy way I'm missing to do a simple `docker build` or `ko` invocation whereby I can produce a local image?

### Why is this needed?

I'm trying to add logging and understand why I'm still getting 401 Unauthorized responses from the apiserver despite having proxy auth configured (i.e. am passing an `Authorization: Bearer` token w/ all my proxied requests to web and api).

**Comment by floreks** [comment]
Check out main [Makefile](https://github.com/kubernetes/dashboard/blob/master/Makefile). There are `build` and `run` targets to simplify development.
