### ISSUE TITLE
enable skip login page

### ISSUE THREAD

**Issue by dilsonac** [kubernetes/dashboard#8497]
### What would you like to be added?

Hello

I would like the option to skip the login screen and go directly to the dashboard to be added

Currently it is possible to enable the login skip button

![image](https://github.com/kubernetes/dashboard/assets/48865969/88f201c1-1791-45aa-aa72-e8f9b301e8dd)

### Why is this needed?

However, I would like to have the option to skip the login screen, with this we can provide a read-only dashboard, many users end up having difficulty finding the skip button, since there is a need for the login skip, It would be great to be able to skip the login screen too!

**Comment by tamilselvan1102** [comment]
Yes I agree, it would be good future if we can skip the login screen

**Comment by floreks** [comment]
To completely skip the login button you can run a reverse proxy with hardcoded authorization bearer token header configured that will have read-only permissions and expose that. It will automatically skip the login view if auth header is found.

**Comment by autarchprinceps** [comment]
@floreks Using static credentials that can be externally used to authenticate with the Kubernetes API by anybody and brute forced, is in itself a big security red flag though and at least for us forbidden in all clusters. Is there really no other way to use kubernetes dashboard? Presuming you setup proper authentication yourself in front of it, as is typical with Kubernetes Ingresses.

**Comment by AndeYashwanth** [comment]
I'm using this workaround `kubectl -n kubernetes-dashboard create token admin-user --duration=999999h` to create a token that doesn't expire in my lifetime.
Edit: It still asks for token when I reopen the browser. So I changed the expiry of the `token` cookie from Session to `2040-06-16T13:22:47.637Z`

**Comment by developerinlondon** [comment]
so if someone is still getting this issue 2 years on., you can put it behind a traefik proxy which injects the token.
