### ISSUE TITLE
The "refer to the Authentication section" no longer works

### ISSUE THREAD

**Issue by adelton** [kubernetes/dashboard#8517]
### What happened?

The Kubernetes Dashboard logon page says for the Token method

> Every Service Account has a Secret with valid Bearer Token that can be used to log in to Dashboard. To find out more about how to configure and use Bearer Tokens, please refer to the Authentication section.

where the "Authentication" link points to https://kubernetes.io/docs/admin/authentication/.

However, that now gives 404 Page not found.

### What did you expect to happen?

Clicking the link, I expected to find out more about how to configure and use Bearer Tokens. :-)

### How can we reproduce it (as minimally and precisely as possible)?

`$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml`
`$ kubectl proxy`
In browser, to go http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/.
Click the "Authentication" link on the logon page.

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

2.7.0

### Kubernetes version

v1.27.7+k3s2

**Comment by adelton** [comment]
https://web.archive.org/web/20230126160024/https://kubernetes.io/docs/admin/authentication/ suggests that back then the original URL had a redirect to https://kubernetes.io/docs/reference/access-authn-authz/authentication/.

So that's likely the location to use.

**Comment by adelton** [comment]
Basically, it'd be nice to backport https://github.com/kubernetes/dashboard/pull/7982 to 2.7.

**Comment by maciaszczykm** [comment]
It's fixed in the latest version and will be part of the next release.
