### ISSUE TITLE
[helm] cannot use default ingressClass

### ISSUE THREAD

**Issue by jmnote** [kubernetes/dashboard#8593]
### What would you like to be added?

using default ingressClass by default

### Why is this needed?

`internal-nginx` is not always the default `IngressClassName`.
```
ingressClassName: internal-nginx
```

similar issue: https://github.com/prometheus-community/helm-charts/issues/3823

**Comment by floreks** [comment]
It can be changed via values override: https://github.com/kubernetes/dashboard/blob/master/charts/helm-chart/kubernetes-dashboard/values.yaml#L88

**Comment by jmnote** [comment]
> It can be changed via values override: https://github.com/kubernetes/dashboard/blob/master/charts/helm-chart/kubernetes-dashboard/values.yaml#L88

Yes, as you said, we can currently use the IngressClass by specifying the name of IngressClass. Aside from that, this issue points out a case where not specifying a name allows to use the default IngressClass.
