### ISSUE TITLE
etcdserver: leader changed

### ISSUE THREAD

**Issue by mayzyo** [kubernetes/dashboard#8594]
### What happened?

The dashboard periodically throws a 500 error stating "etcdserver: leader changed".

![image](https://github.com/kubernetes/dashboard/assets/25147960/bce7f354-63b0-4e06-864f-1b4990dfadbf)

### What did you expect to happen?

Continue to run smoothly.

### How can we reproduce it (as minimally and precisely as possible)?

Create a basic High Availability Cluster with all the defaults and run kubernetes dashboard.

### Anything else we need to know?

After a brief moment, if I remove the "error" part of the url and hit refresh, everything runs normally again until the next leader change.

### Kubernetes Dashboard version

3.0.0-alpha0+0

### Kubernetes version

v1.27.9

**Comment by mayzyo** [comment]
I'm aware the periodic change in leadership has more to do with my cluster's health than bug in the dashboard code. I just thought I should still raise an issue to see if this is something that can be made smoother on the dashboard side.

**Comment by floreks** [comment]
I am unsure if we can do anything about that since it is an internal server error. Frequent leader change might be a symptom of underlying cluster configuration issue. It should rarely happen in a healthy cluster.
