### ISSUE TITLE
Migrate fixing and checking quotes for scss

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#8611]
### What should be cleaned up or changed?

We need to migrate this functionality from `string-quote` of `stylelint` to the other solution.

### Why is this needed?

The rule `string-quote` was removed from `stylelint` v16.
https://stylelint.io/migration-guide/to-16#breaking-changes
https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules

**Comment by maciaszczykm** [comment]
Stylelint will no longer provide formatting options. I will switch us to use prettier for all formatting.

**Comment by maciaszczykm** [comment]
Done in https://github.com/kubernetes/dashboard/pull/8708/commits/823bd9a1a8a7e31896ec5a3bcef753acbc7c7f5b.
