### ISSUE TITLE
Login with token of URL parameters

### ISSUE THREAD

**Issue by gokhangunduz** [kubernetes/dashboard#8640]
### What happened?

Hello everyone, I want to auto-login to a currently running k8s dashboard application by transferring a token transferred from the URL with a parameter.

URL: https://domain.com/login

i needed URL: https://domain.com/login?token=TOKEN

### What did you expect to happen?

This way I was expecting to be logged in when the request was sent.
 
https://domain.com/login?token=TOKEN

### How can we reproduce it (as minimally and precisely as possible)?

As far as I researched, although there is no definitive information, this feature was removed in January 2022. But I definitely need this, is there a config where I can turn it on? Or is it a feature that still exists and I couldn't find it?

### Kubernetes Dashboard version

Dashboard v2.7.0+0.g42deb6b32

### Kubernetes version

1.27

**Comment by tamilselvan1102** [comment]
TOKEN is the secret code and it is a lengthy code as well, that is why not prescribed as a query param in URL

**Comment by floreks** [comment]
That is most definitely not something we want to be sending through query param. That's what request headers are for. You should be using `Authorization: Bearer <token>` request header.

/close
