### ISSUE TITLE
Kubernetes upgrade from 1.24 to 1.25 broke search and cron jobs tab under workload section

### ISSUE THREAD

**Issue by skolagsa** [kubernetes/dashboard#8649]
### What happened?

Kubernetes upgrade from 1.24 to 1.25 broke search and cron jobs tab under workload section, getting below errors when we click 
On dashboard:
1. Not Found (404) the server could not find the requested resource
2. Unknown Error No error data available.

In dasboard deployment logs:
2024/01/26 15:02:19 received 1 resources from sidecar instead of 2
2024/01/26 15:02:19 received 1 resources from sidecar instead of 2
2024/01/26 15:02:19 received 1 resources from sidecar instead of 2
2024/01/26 15:02:19 received 1 resources from sidecar instead of 2
2024/01/26 15:02:19 Skipping metric because of error: Metric label not set.
2024/01/26 15:02:19 Skipping metric because of error: Metric label not set.

### What did you expect to happen?

Display results

### How can we reproduce it (as minimally and precisely as possible)?

with Dashboard v2.6.0+0.g8cf47b594 on Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-8cb36c9", GitCommit:"3a3ea80e673d7867f47bdfbccd4ece7cb5f4a83a", GitTreeState:"clean", BuildDate:"2023-11-22T21:53:22Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

Dashboard v2.6.0+0.g8cf47b594

### Kubernetes version

Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-8cb36c9", GitCommit:"3a3ea80e673d7867f47bdfbccd4ece7cb5f4a83a", GitTreeState:"clean", BuildDate:"2023-11-22T21:53:22Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by skolagsa** [comment]
![Snapshot-workload-api-calls-error](https://github.com/kubernetes/dashboard/assets/122551679/cc1ac2de-517f-491a-86ea-a9ced154cdab)
![Snapshot-workload-search-error](https://github.com/kubernetes/dashboard/assets/122551679/8195b005-a806-4bf1-8716-b3aa4da623eb)

**Comment by ZimmSebas** [comment]
It is horribly documented, but I fixed this issue by upgrading Dashboard to 2.7. 

Kubernetes 1.25 deprecates the cronjob endpoint `batch/v1beta1` in favor of `batch/v1`, and it seems Dashboard 2.6 was using that endpoint to check all cronjobs. Things like EKS insights let you know about it, but you can also check if something is using that by using `kubectl` and `grep`. 

That said, there's an ongoing issue (that keeps on 1.26 and 1.27, and hopefully it's fixed on dashboard 3.0+), see [this](https://github.com/kubernetes/dashboard/issues/7717)

**Comment by maciaszczykm** [comment]
Can you retry with https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.0.0? We didn't encounter this issue while testing.
