### ISSUE TITLE
Strange description of service

### ISSUE THREAD

**Issue by Yamagami-Takuma** [kubernetes/dashboard#866]
About the description of service on the page of Deploy a Containerized App.

The description says 'ports are optional'.
But now ports appear only when service is specified and ports are required in this this time.
How about removing the sentence 'Ports are optional.' ?

##### Environment

```
Dashboard version: 6d72beee413a15bb03931d52f8cd8b984d3df4a1
Kubernetes version: 1.2.4
Operating system: Ubuntu 14.04
Node.js version: 5.11.1
Go version: 1.6.2

**Comment by cheld** [comment]
yes...this was also reported by Gerti. I could not find the issue, though.

@gertipoppel can you link the issue?

**Comment by gertipoppel** [comment]
Here it is: 
https://github.com/kubernetes/dashboard/issues/801

**Comment by floreks** [comment]
Ok.Closing as duplicate in favor of #801.
