### ISSUE TITLE
Inquiry Regarding Kubernetes Dashboard Compatibility with Kubernetes Version 1.29

### ISSUE THREAD

**Issue by SIT-PRO** [kubernetes/dashboard#8717]
### What should be cleaned up or changed?

Dear all

We are reaching out to inquire about the current compatibility status between Kubernetes Dashboard and Kubernetes version 1.29.

Currently, we have observed challenges in running Kubernetes Dashboard seamlessly with version 1.29. Our team has encountered instances of CrashLoopBackOff, and the following error has been consistently reported:

bash
Copy code
panic: Get "https://10.96.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf": dial tcp 10.96.0.1:443: i/o timeout
Despite these challenges, our Kubernetes cluster is operational, and all configurations appear to be in order. We have ensured that the settings align with the recommended guidelines.

Given the importance of keeping our environment up to date and the critical role that Kubernetes Dashboard plays in our workflow, we are keenly interested in understanding if there are plans or timelines for an adaptation of Kubernetes Dashboard that is compatible with version 1.29.

Any insights, updates, or recommendations you could provide would be greatly appreciated. We value your expertise and look forward to continuing to leverage Kubernetes Dashboard as a vital component of our Kubernetes ecosystem.

Thank you for your attention to this matter.

Best regards,

### Why is this needed?

Kubernetes Dashboard Compatibility with Kubernetes Version 1.29

**Comment by floreks** [comment]
We do plan to release a new version with support for K8S v1.29. It should be available in a couple of weeks.

The error you are seeing is quite strange to be honest and does not look like a compatibility issue. Please provide more information about your setup, used dashboard version and possibly some logs from both web/api containers.

**Comment by SIT-PRO** [comment]
"Kubernetes consists of a Master Node and 2 Worker Nodes. The installed components include Kubernetes 1.29.2, Cri-o, Calico, (kubeadm kubectl kubelet), helm v3. The Kubernetes dashboard was installed using Helm, but an error has occurred. I have tried several troubleshooting steps without success, and I suspect it might be due to compatibility issues. To assist in diagnosing the issue, could you please provide the error messages from the log files? I'll be happy to review them for further analysis."

**Comment by maciaszczykm** [comment]
Try https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.0.0 and let us know if anything doesn't work.
