### ISSUE TITLE
unable to save settings in 7.0.0 when installed to a non-default namespace

### ISSUE THREAD

**Issue by Infinoid** [kubernetes/dashboard#8749]
### What happened?

I installed the latest helm-release into the `kube-dashboard` namespace.  (NOTE: that's "`kube`", not "`kubernetes`".)  Once I logged in, I changed some settings in the settings view, clicked "Save", and got this error:

![image](https://github.com/kubernetes/dashboard/assets/50254/e73c0a62-569e-4fa0-a4ef-02ac89657546)

### What did you expect to happen?

Settings are saved without error.

### How can we reproduce it (as minimally and precisely as possible)?

1. Install kubernetes-dashboard using the new helm release 7.0.0 (released today :tada:), specifying the namespace `kube-dashboard` and name `dashboard`.
2. Connect your browser to it (via port-forward or whatever).  Log in using the token.
4. Click on "Settings", at the bottom of the menu.
5. Change a setting.  (The "Items per page" value is sufficient.)
6. Click "Save".

### Anything else we need to know?

Logs from the `web` pod seem to suggest that it is trying to use the namespace `kubernetes-dashboard`, not the `kube-dashboard` that I passed to helm:
```
[GIN] 2024/03/06 - 17:03:54 | 200 |     859.608µs |     172.21.6.29 | GET      "/settings"
[GIN] 2024/03/06 - 17:03:54 | 200 |    1.530362ms |     172.21.6.29 | GET      "/settings/cani"
I0306 17:03:54.977713       1 manager.go:84] Could not get settings config map: configmaps "kubernetes-dashboard-settings" is forbidden: User "system:serviceaccount:kube-dashboard:dashboard-kubernetes-dashboard-web" cannot get resource "configmaps" in API group "" in the namespace "kubernetes-dashboard"
[GIN] 2024/03/06 - 17:03:54 | 200 |     403.114µs |     172.21.6.29 | GET      "/settings"
I0306 17:04:21.074197       1 manager.go:84] Could not get settings config map: configmaps "kubernetes-dashboard-settings" not found
I0306 17:04:21.075868       1 manager.go:84] Could not get settings config map: configmaps "kubernetes-dashboard-settings" not found
[GIN] 2024/03/06 - 17:04:21 | 500 |   98.667679ms |     172.21.6.29 | PUT      "/settings"
```

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.0.0

### Kubernetes version

7.0.0

**Comment by Infinoid** [comment]
The `kube-dashboard` namespace was the only one that helm created.  The `kubernetes-dashboard` namespace does not exist in my cluster.  But that's clearly where it's looking according to the web pod logs.

Was that namespace string hardcoded somewhere?  Was I supposed to set a value somewhere to override the default?  I looked in values.yaml and I don't see one.

**Comment by Infinoid** [comment]
I edited the web deployment and added this to the program arguments:
```
        - '--namespace=kube-dashboard'
```

And now I'm able to save settings as expected.  So I think that's what was missing.

**Comment by floreks** [comment]
Oh yes, `namespace` arg is missing from web deployment. It should be inherited from the release namespace. We will release a fix tomorrow. For the time being you can also use `web.containers.args` to append this argument.

**Comment by Infinoid** [comment]
I verified that helm chart 7.0.1 fixes this issue.  Thanks for the quick fix!
