### ISSUE TITLE
Reactivity bug in web UI login form

### ISSUE THREAD

**Issue by jnoordsij** [kubernetes/dashboard#8755]
### What happened?

When logging in (latest version of web UI) and autofilling the token field with my password manager plugin, the value is filled but the Sign in button remains disabled. Only after manually focussing on the field and pressing enter the value is detected and the Sign in button becomes enabled.

### What did you expect to happen?

The Sign in button to become enabled as soon as a value is present in the token input field.

### How can we reproduce it (as minimally and precisely as possible)?

Programmatically set the token value in any manner (e.g. through a browser plugin).

### Anything else we need to know?

I'm pretty sure this worked previously; I have not yet attempted to look for the differences in the UI compared to previous versions myself, but that might be a good place to start.

### Kubernetes Dashboard version

7.0.0

### Kubernetes version

1.29

**Comment by maciaszczykm** [comment]
We will probably need to listen for different event to support password managers.

**Comment by floreks** [comment]
Possibly it directly overrides value of the element via code and only triggers change event. Should be an easy fix.

**Comment by lokeshsingh3721** [comment]
Would love to work on this issue. can you please assign it to me.
