### ISSUE TITLE
Define registries of sub-charts in air-gappend installation

### ISSUE THREAD

**Issue by dagobertdocker** [kubernetes/dashboard#8758]
### What would you like to be added?

When trying to install chart v.7.0.1, by default, the kong sub-chart is enabled. However, that defaults to pulling images from docker.io. I need to override this in values.yaml in existing `kong` section like in `api.image.repository`

### Why is this needed?

This is needed to install the default chart v.7.0.1 in air-gapped mode with a private registry.

**Comment by floreks** [comment]
You can already override it. Since kong is a subchart of our chart then all its values can be overridden via custom `values.yaml` or `set` argument. They already expose the image configuration in their chart: `--set kong.image.repository=xxx` and `--set kong.image.tag=xxx`.

/close
