### ISSUE TITLE
Unable to skip login by adding Authorization header

### ISSUE THREAD

**Issue by csuich2** [kubernetes/dashboard#8760]
### What happened?

After upgrading to v7.0.0 I'm trying to adapt to the removal of the `--enable-skip-login` page. I did this as indicated in the docs by having our proxy add the Authorization header however I'm still presented with the login page.

The docs also indicate:

> IMPORTANT: Authorization header will not work if Dashboard is accessed through API server proxy. kubectl port-forward described in [Accessing Dashboard](https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/README.md) guide will not work. It is due to the fact that once request reaches API server all additional headers are dropped.

however it isn't clear if that also applies to the Kong gateway.

Update: I tried removing the Kong gateway from the equation by having our proxy forward `/api` requests to the api service and all other requests to the web service but am still seeing the login page.

### What did you expect to happen?

With the Authorization header present the login page should not be presented.

### How can we reproduce it (as minimally and precisely as possible)?

Use Requestly as described in the docs to add the header when loading the dashboard.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### Kubernetes Dashboard version

v7.0.0

### Kubernetes version

v1.27.3

**Comment by csuich2** [comment]
Woah - thanks for the quick turnaround!

I've upgraded my chart to 7.1.1 but unfortunately I'm still experiencing the same behavior. Do you have any suggestions on how to debug further to ensure this isn't a problem with my setup? AFAICT I'm properly setting the Authorization header. Can you confirm that the Kong gateway doesn't strip this header?

**Comment by csuich2** [comment]
Oops! Turns out I just needed to bounce the Kong Proxy pod since it didn't recreate after the ConfigMap change.

Thanks again for the super quick fix!!!

**Comment by floreks** [comment]
> Oops! Turns out I just needed to bounce the Kong Proxy pod since it didn't recreate after the ConfigMap change.
> 
> Thanks again for the super quick fix!!!

Not sure if we can automate restart on change since this is a subchart but I will take a look. I will add a note to the release notes though.

Great that it works for you!
