### ISSUE TITLE
kubernetes-dashboard-kong not starting

### ISSUE THREAD

**Issue by dandresm** [kubernetes/dashboard#8765]
### What happened?

I try to make a clean install  on a kubernetes cluster (minikube), but kong proxy is not starting correctly.

### What did you expect to happen?

The instalation of kubernetes dashboard fineshes ok and you can access vía https://localhost:8443/

### How can we reproduce it (as minimally and precisely as possible)?

Execute these commands on a clean cluster (minikube):
```bash
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
```

### Anything else we need to know?

This is de log of kubernetes-dashboard-kong pod (`kubectl logs pod/kubernetes-dashboard-kong-64f887fc84-4dmww --namespace kubernetes-dashboard`):
```
Defaulted container "proxy" out of: proxy, clear-stale-pid (init)
Error: could not prepare Kong prefix at /kong_prefix: nginx configuration is invalid (exit code 1):
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /kong_prefix/nginx.conf:7
nginx: the configuration file /kong_prefix/nginx.conf syntax is ok
nginx: [emerg] bind() to [::1]:8444 failed (99: Cannot assign requested address)
nginx: configuration file /kong_prefix/nginx.conf test failed


  Run with --v (verbose) or --vv (debug) for more details`
```

### Kubernetes Dashboard version

7.1.1

### Kubernetes version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Dev environment

Go:
go version go1.20.7 linux/amd64

Node: 
v15.14.0

**Comment by floreks** [comment]
> nginx: [emerg] bind() to [::1]:8444 failed (99: Cannot assign requested address)

This is due to minikube occupying port 8444 by default. It conflicts with kong default configuration. You can disable kong admin UI as it is not required anyway and it will work just fine.

```
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard --set kong.admin.tls.enabled=false
```

/close
