### ISSUE TITLE
Exec-ing into pod not working - "Server lost session"

### ISSUE THREAD

**Issue by dagobertdocker** [kubernetes/dashboard#8771]
### What happened?

When trying to initiate new terminal session in pod from dashboard, the terminal screen stays black, and a message is displayed "Server lost session".
In the logs, I see
```
[kubernetes-dashboard-api] 2024/03/11 13:59:01 handleTerminalSession: can't Recv: sockjs: session not in open state
```

### What did you expect to happen?

Interactive terminal session established and shell prompt visible.

### How can we reproduce it (as minimally and precisely as possible)?

  1. Deploy Kubernetes Dashboard via helm chart
  2. Navigate to a pod details page
  3. Click "Exec into pod"
  4. Observe "Server lost session" error message

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

7.1.2

### Kubernetes version

1.26.9

**Comment by floreks** [comment]
I could not reproduce it based on the provided steps. Tested on Firefox/Chrome and exec works just fine.

**Comment by dagobertdocker** [comment]
I upgraded to k8s 1.28.7, and since then, the problem is gone.

**Comment by dagobertdocker** [comment]
For future reference:

I am using a setup with HAProxy -> NGINX Inc's Ingress -> gogatekeeper (OAuth2 proxy) -> Kong service of Dashboard.
In the end, I had to whitelist the `/api/sockjs` path in gogatekeeper (it seems to remove auth headers) to get it to work consistently..

**Comment by shnigam2** [comment]
I have this issue on 1.28.5 EKS as well

**Comment by dagobertdocker** [comment]
Correction, it does not work consistently, but randomly. So, this issue is open and being tracked in #8838 I assume..
