### ISSUE TITLE
Facing latency issue in kubernetes dashboard in v 7.1.2

### ISSUE THREAD

**Issue by Sandeepsac** [kubernetes/dashboard#8787]
### What happened?

We facing latency issue in latest version 7.1.2 , mainly in list of Node details taking more than 2 min or getting 504 error timeout. other than this we facing issue in list of pods, jobs , deployment  taking time maximum of 30sec.
we having more than 80 nodes running in our cluster , we have increased resource value max of 1 core CPU, 1Gb of memory for Dashboard API.   still we facing same issue
![image](https://github.com/kubernetes/dashboard/assets/136812799/59743c93-6895-4332-8cc7-4a2b6283a1e8)

### What did you expect to happen?

we expecting faster as in previous version [v2.7.0](https://github.com/kubernetes/dashboard/releases/tag/v2.7.0) 

### How can we reproduce it (as minimally and precisely as possible)?

we are using 80+ nodes,  more than 200 pods,.. version of k8s 1.27.1

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.1.2

### Kubernetes version

1.27

**Comment by floreks** [comment]
Check `resource refresh time` on the Settings view. By default, it is 10 seconds. It might not be enough to fetch a big amount of data. Extend it to 1 minute or more.

**Comment by Sandeepsac** [comment]
Its 10sec.

![image](https://github.com/kubernetes/dashboard/assets/136812799/b1a30025-667c-4bdc-bfeb-3ed6282949ff)

**Comment by floreks** [comment]
Ye, that is the default value. Increase it until you will not see any requests being cancelled in the network tab.

**Comment by Sandeepsac** [comment]
@floreks Still list of pods and node getting more time.

**Comment by floreks** [comment]
You can just set it to 0 and disable auto refresh. API server heavily throttles requests with such a big amount of data.

**Comment by Sandeepsac** [comment]
Can't able to set 0 to disable auto refresh, if we save by keeping zero, it getting revert to default 10 again

**Comment by floreks** [comment]
> Can't able to set 0 to disable auto refresh, if we save by keeping zero, it getting revert to default 10 again

That's a bug then. We will fix that.

**Comment by Sandeepsac** [comment]
Thanks for Update @floreks , is there any possible way to reduce latency. ? we have checked by increasing API resource limit in deployment Still facing latency

**Comment by floreks** [comment]
Could you try overriding "kong.env.dns_order" value to "A,CNAME,LAST,SRV" and see if it improves anything?

I have also noticed some latency issues with kong, but it usually worked better on subsequent requests.

**Comment by floreks** [comment]
Closing in favor of #8835

/close
