### ISSUE TITLE
Add control for log text size

### ISSUE THREAD

**Issue by therc** [kubernetes/dashboard#879]
The black-on-white vs white-on-black toggle in the log viewer is very cool. Would it be possible to also add a setting for text size? As it is, it takes too much screen estate on my system. I'd love to see more lines at once. Hard-coding a smaller default might not be the best idea. Bonus points if the preferences are persisted.

**Comment by bryk** [comment]
Yep, logs view has limitations that we are aware off. Hope to fix this soon after 1.1.
