### ISSUE TITLE
Serve a different favicon

### ISSUE THREAD

**Issue by therc** [kubernetes/dashboard#880]
The current one is identical to the one used for the Kubernetes home, the submit queue, etc. It would be great to differentiate it from the others.

**Comment by therc** [comment]
Maybe something along these lines:
![kubernetesdashboard138](https://cloud.githubusercontent.com/assets/13481082/15991308/33842c72-307d-11e6-977d-79f7933ef398.png)

That's 138x138 like the current one.

**Comment by bryk** [comment]
You're correct. We didn't yet engage with a graphics designer to make a logo for the project. We've been busy adding features. But yes, we're approaching the moment to fix this.

**Comment by bryk** [comment]
Did you make the logo by yourself? :)

**Comment by therc** [comment]
I took the official SVG and played with it in GIMP in five minutes. It was just an idea. For one, the green-yellow-red borders are too thin to really show up when shrunk to the average favicon size. :-)

**Comment by arieljatib** [comment]
Here's another quick 138x138 option.

![k8s-dashboard-favicon](https://cloud.githubusercontent.com/assets/1958997/17387729/621c634a-59c4-11e6-8dfb-08ead050371b.png)

The design replaces the helm with the dashboard icon, leveraging the polygon to map back to the k8s logo. The dashboard icon comes from the Material Design set. Below, it is presented in contrast to the project website tab. 

![chrome-example](https://cloud.githubusercontent.com/assets/1958997/17387941/2a718c84-59c6-11e6-80d6-ad7d8cafb13e.png)

### Reference
https://design.google.com/icons/#ic_dashboard

**Comment by arieljatib** [comment]
This is an alternative take on the example mentioned in the previous comment. With this one, I invert the color-way. 

![k8s-dashboard-favicon-alt](https://cloud.githubusercontent.com/assets/1958997/17388092/a724533c-59c7-11e6-91f1-57f28e89860f.png)

![chrome-example-alt](https://cloud.githubusercontent.com/assets/1958997/17388095/aa351c28-59c7-11e6-8f71-60b009e91741.png)

**Comment by maciaszczykm** [comment]
@arieljatib I like the last one.

Let's wait for @bryk and see what will be his opinion. I'll add few more guys too.

CC @floreks @romlein @digitalfishpond @batikanu

**Comment by bryk** [comment]
Thanks @arieljatib for this. I like the idea of combining an icon for "dashboard" with kubernetes to have "Kubernetes Dashboard" :) 

@romlein @Lukenickerson Do you have any opinions on this? Should we explore more ideas or are we happy with this proposal?

**Comment by bryk** [comment]
@arieljatib Do you have some more ideas for the thumbnail? We want to make sure we've explored the topic throughly :)

**Comment by arieljatib** [comment]
@bryk -  not at the moment. this solution feels like the right direction. 

I might tweak it a bit - for example, increase the thickness of the border. But overall, I think it accomplishes some important goals.

1. It differentiates itself from the marketing website favicon.
2. It adheres to Google design language by leveraging the polygon **and** icon from the Material Design set.

Essentially, it looks enough like it's related icon, but not so much as to cause confusion. 

Is there any other goals we should consider?

Also, we can always change it if we come up with a better idea. 😁

**Comment by romlein** [comment]
@arieljatib I prefer the second version – maybe with a white background to make the icon stand out more? @bryk I know you've talked about a separate logo for Dashboard, and I'm not sure how I feel about that: to me Dashboard _is_ a part of Kubernetes, so it seems unnecessary to distinguish that with it's own brand?

**Comment by arieljatib** [comment]
thanks @romlein - i like the idea of the white background.

**Comment by bryk** [comment]
@bgrant0607 @pwittrock Should we have a separate icon for Dashboard UI or use the standard Kubernetes icon? What is your opinion? 

The rationale for a separate icon is to distinquish it from Kubernetes docs and marketing pages. But @romlein makes good point that Dashboard UI is the UI for Kubernetes, hence having the same icon makes sense.

**Comment by cheld** [comment]
If I look to my browser right now the title "Kubernetes Dashboard" is shortened to "Kubernetes", because I have too many tabs open. In addition I also have a couple of other documentation pages open that have the title shortened to "Kubernetes" as well. 

What about keeping the icon, but changing the title to "Dashboard"?

**Comment by maciaszczykm** [comment]
Isn't "Dashboard" is too generic? There can be more than one "Dashboard" tab in developer/operator browser. There will be Kubernetes icon nearby, but still I like full name more. There is an option to display "Dashboard - Kubernetes" title too.

**Comment by bryk** [comment]
I think titles of pages is a separate issue. We should start having them different for each page, e.g., "Workloads - Kubernetes Dashboard" or "pod my-pod-4344 - Kubernetes Dashboard".

**Comment by edouardKaiser** [comment]
The good side of having a different icon is that people can clearly see the difference in their bookmark bar between a link to the Kubernetes Documentation and the Dashboard for example.

**Comment by Lukenickerson** [comment]
Re: the icon -- I like keeping the Kubernetes icon. If we want to be different we could always invert the colors or use some minor (but brand-acceptable) variation.

> Isn't "Dashboard" is too generic? There can be more than one "Dashboard" tab in developer/operator browser. 

This is a good point. In my mind a "dashboard" is typically a single view, and it seems like the current UI encompasses several dashboards -- what we're currently calling [Overview pages](https://github.com/kubernetes/dashboard/issues/1068) -- and it now provides a lot of controls (CRUD) in addition to displaying data. Is there a point where this project might outgrow the name "dashboard"?

**Comment by maciaszczykm** [comment]
Closing this issue as we are keeping Kubernetes icon for now. Custom page titles have just been introduced.
