### ISSUE TITLE
nil pointer dereference error in deployment details page

### ISSUE THREAD

**Issue by ravilr** [kubernetes/dashboard#881]
#### Issue details
clicking on a deployment resource with spec.strategy.type = Recreate (other than RollingUpdate) leads to a nil pointer dereference:
[restful] recover from panic situation: - runtime error: invalid memory address or nil pointer dereference
    /usr/local/go/src/runtime/asm_amd64.s:472
    /usr/local/go/src/runtime/panic.go:426
    /usr/local/go/src/runtime/panic.go:45
    /usr/local/go/src/runtime/sigpanic_unix.go:24
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/resource/deployment/deploymentdetail.go:150
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/resource/deployment/deploymentdetail.go:123
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/handler/apihandler.go:565
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/handler/apihandler.go:217
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/handler/apihandler.go:67
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95
    /usr/local/go/src/net/http/server.go:1618
    /usr/local/go/src/net/http/server.go:1910
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264
    <autogenerated>:32
    /usr/local/go/src/net/http/server.go:1910
    /usr/local/go/src/net/http/server.go:2081
    /usr/local/go/src/net/http/server.go:1472
    /usr/local/go/src/runtime/asm_amd64.s:1998

##### Environment

```
Dashboard version:  gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0-beta3
Kubernetes version:  v1.2.4
Operating system: RHEL 7
Node.js version:
Go version: 1.6
```

**Comment by bryk** [comment]
Thanks for reporting this! Will be fixed soon.
