### ISSUE TITLE
Login page not consistently skipped with bearer token

### ISSUE THREAD

**Issue by mrlhansen** [kubernetes/dashboard#8813]
### What happened?

I have a reverse proxy (Nginx) in front of the dashboard where I pass the Bearer token for authentication. The first time I load the dashboard the login page is shown, but after refreshing the page a couple of times, the login page is skipped and the dashboard loads correctly.

I can consistently reproduce this with different browsers, but it's more pronounced in Firefox. Sometimes the login page is skipped completely, but most of the time the login page will be shown and I have to refresh the page a couple of times before the dashboard loads. Once it loads, there are no problems.

I can even see that `/api/v1/me` is called when the login page is shown and the endpoint returns `authenticated: true`.

This was never a problem with the older versions of the Dashboard, but it is present with the new 7.x release.

### What did you expect to happen?

I expect the login page to never be shown.

### How can we reproduce it (as minimally and precisely as possible)?

I use [nginxinc](https://docs.nginx.com/nginx-ingress-controller/) ingress for Kubernetes, with the following annotation to pass the Bearer token.
```
    nginx.org/location-snippets: |
      proxy_set_header Authorization "Bearer <token>";
      proxy_pass_header Authorization;
```

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

### Kubernetes Dashboard version

7.x

### Kubernetes version

1.27.9

**Comment by jaynis** [comment]
I am experiencing exactly the same issue. In my case I use a OIDC proxy in front of the dashboard and it almost always needs an additional page refresh after the OIDC redirect in order to skip the login. The `/api/v1/me` endpoint in the auth service indicates no problems which means my token seems to be valid all the time.
