### ISSUE TITLE
Allow Custom Resource to deploy and monitor from GUI

### ISSUE THREAD

**Issue by kavinduxo** [kubernetes/dashboard#8826]
### What would you like to be added?

Dashboard would be great if it can work with the custom resources too. Or is there any guide that we can customize this GUI in order to deploy custom resources and monitor them.

### Why is this needed?

We often use operators and CRDs for some automation tasks. So, it's better to be able to to deploy CRs with this dashboard.

**Comment by maciaszczykm** [comment]
You can do it via deploy from file/text input. CRDs are currently displayed, you can pin the ones you use the most to the main menu.
