### ISSUE TITLE
Learn more link missing in Create Namespace dialog

### ISSUE THREAD

**Issue by gertipoppel** [kubernetes/dashboard#888]
To be consistent with the other "Create..." dialogs, a Learn more link should be added to the Create Namespace dialog.

**Comment by bryk** [comment]
Where should we link to? Do you have ideas?

**Comment by gertipoppel** [comment]
I would set the link to 
<a href="http://kubernetes.io/docs/admin/namespaces/" target="_blank" tabindex="-1">
