### ISSUE TITLE
Allow hiding "All namespaces" in namespaces dropdown list

### ISSUE THREAD

**Issue by chri4774** [kubernetes/dashboard#8894]
### What would you like to be added?

We would like to be able to globally hide the "All namespaces" list item in the namespace drop-down list. Either through global settings or some other method such as command line arguments.

### Why is this needed?

On larger clusters with thousands of pods, selecting "All namespaces" results in huge memory consumption and possible OOMs of the Dashboard API pod. As I've read in other bug reports here, there is no real solution to this problem in the foreseeable future. 
For normal users, we've already removed the ability to list resources cluster-wide in k8s so that clicking "All namespaces" doesn't list anything, but this is not a viable option for people who need cluster admin privileges.
Instead of trying to fiddle with dashboard refresh times and pod resource limits, we would like to hide the "All Namespaces" list item altogether. This would eliminate the possibility of someone accidentally clicking on it and triggering an OOM in the dashboard.

**Comment by sephialaureenciaa** [comment]
Hi, can I contribute to this?
