### ISSUE TITLE
Kubernetes-Dashboard out of sync in ArgoCD because of rollme annotation

### ISSUE THREAD

**Issue by Alwinius** [kubernetes/dashboard#8903]
### What happened?

I installed the Helm Chart of Kubernetes-Dashboard via ArgoCD. Since the update to 7.0.1 the deployments of api, auth and the kubernetes-dashboard-csrf secret repeatedly show out of sync with the difference being in the secret value and rollme annotations and the pods of the deployments. This is because ArgoCD runs helm template to render the manifests to compare with the live manifests. 

See https://github.com/kubernetes/dashboard/pull/8757 for the responsible changes.

### What did you expect to happen?

I sync once and the dashboard stays in sync

### How can we reproduce it (as minimally and precisely as possible)?

Install ArgoCD, install the Helm Chart of Kubernetes-Dashboard via ArgoCD

### Anything else we need to know?

A minimal solution would be to include a flag in values.yaml that allows to disable the rollme annotation. The csrf secret content can already be given explicitly

### Kubernetes Dashboard version

7.1.3

### Kubernetes version

1.29.2

**Comment by floreks** [comment]
Use latest chart. It now uses secret sha instead of rollme annotation and allows providing custom csrf key to override it and disable autogeneration.

/close
