### ISSUE TITLE
How to set affinity rule and requests/limits for kong

### ISSUE THREAD

**Issue by G-Despacito** [kubernetes/dashboard#8942]
### What happened?

As title. Need a way to set affinity rule and requests/limits for kong

Found that the affinity rule set in app section is not applied to kong. And there is no place in the values.yaml template to set it for kong. Also need a way to set requests/limits for it.

### What did you expect to happen?

There is a way to set affinity rule and requests/limits for kong

### How can we reproduce it (as minimally and precisely as possible)?

Not relavant

### Kubernetes Dashboard version

7.3.1

### Kubernetes version

1.27.10

**Comment by floreks** [comment]
Same as: https://github.com/kubernetes/dashboard/issues/8954#issuecomment-2068589691

https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

/close
