### ISSUE TITLE
Helm chart does not have a nodeSelector field for Kong service, and it doesn't use at least the global option from app field

### ISSUE THREAD

**Issue by ammirator-administrator** [kubernetes/dashboard#8954]
### What happened?

At the moment the kong service/pods are deployed randomly on the node where kubernetes decides
There is no nodeSelector field available in chart to determine where it should land, not even affinity field available or something like that (I checked the Helm values yaml)
It should at least respect the 'app.scheduling.nodeSelector' from Helm values but at the moment it doesnt

### What did you expect to happen?

Kong deployment should at least respect 'app.scheduling.nodeSelector' or have it's own nodeSelector Field

### How can we reproduce it (as minimally and precisely as possible)?

Just have few worker nodes and set the app.scheduling.nodeSelector to worker-0 for example and you'll see that kong pod doesn't respect that sometime it is deployed on other nodes

### Anything else we need to know?

nop

### What browsers are you seeing the problem on?

Others

### Kubernetes Dashboard version

7.3.1

### Kubernetes version

1.29

### Dev environment

kube dashboard helm chart version 7.3.1

**Comment by floreks** [comment]
Kong is a dependency chart. We cannot control what is available in the external chart. Look into their values.yaml to see what is available.

/close

**Comment by ammirator-administrator** [comment]
@floreks 

They have a nodeSelector field
But how do I apply that? Only by doing a Patch?
Is there a posibility to tell helm to do that using our values file? Or some --set flag
Because from what I understand when using --set flag it will pass values to kubernetes dashboard, how do I tell to pass some var to a sub dependency?

**Comment by floreks** [comment]
https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

**Comment by ammirator-administrator** [comment]
Thanks
Didn't know about this posibility
