### ISSUE TITLE
Delete resource should have an option to choose the deletion cascading strategy

### ISSUE THREAD

**Issue by jenting** [kubernetes/dashboard#8959]
### What would you like to be added?

On the delete resource dialog, provide an optional to make user choose the deletion cascading strategy ("background", "foreground", or "orphan"). Default is "background".

### Why is this needed?

The Kubernetes can't increase the PVC size of the StatefulSet volumeClaimTemplates automatically because of the [issue](https://github.com/kubernetes/enhancements/issues/661). To increase the PVC size of the StatefulSet volumeClaimTemplates _without_ downtime, we have to
1. Orphan delete the StatefulSet to make the Pod+PVC running (remove the StatefulSet resource only).
2. kubectl apply the new StatefulSet with new volumeClaimTemplates PVC size.

It would be good that the Kubernetes dashboard UI can support different deletion cascading strategy so we would not have to rely on the kubectl command to achieve above.

**Comment by MiirzaBaig** [comment]
Is this issue still on?
I would like to contribute to this...

**Comment by MiirzaBaig** [comment]
Ohkayy, cool..
