### ISSUE TITLE
Setup HTTPS for Kubernetes Dashboard

### ISSUE THREAD

**Issue by Trourest186** [kubernetes/dashboard#8964]
### What happened?

Hi, 

I recently installed kubernetes dashboard to serve for monitoring my cluster (Using helm chart). I setted up cluster and ingress nginx controller before. I sent below information, hope to receive support from everyone.

* Ingress (true)
![image](https://github.com/kubernetes/dashboard/assets/74035725/6e0cbe3d-a328-435d-9fad-e037fad09ac0)

* Kong (true)
![image](https://github.com/kubernetes/dashboard/assets/74035725/5e8586d1-105f-44bb-a4f5-4343767dafb5)

### What did you expect to happen?

You want to access "cluster-checking.sotaicg.com" domain through HTTPS. Then all components be installed completely. I curl my domain and it appear strange error. I can't think method to solve this problem
![image](https://github.com/kubernetes/dashboard/assets/74035725/20ef508a-a544-45fd-8c2e-9f2f2d27f383)

### How can we reproduce it (as minimally and precisely as possible)?

No response

### Anything else we need to know?

Before i install lastest version. I ran 1.2.7 version with secret and domain above and everything runs as I want

### Kubernetes Dashboard version

latest

### Kubernetes version

v1.28.9

**Comment by floreks** [comment]
Provide some kind of logs/statuses from nginx, kong, and dashboard pods. This is most probably a configuration issue on your side.

**Comment by KaiSforza** [comment]
It's actually an issue here:

https://github.com/kubernetes/dashboard/blob/36f7c4fe8377dccbd859d361a2f09944fd407c42/charts/kubernetes-dashboard/templates/networking/ingress.yaml#L75C1-L75C68

If the host is specified, dashboard uses the kong [*service* port, not the *container port*.](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L310-L314)
