### ISSUE TITLE
Broken link to Dashboard Tour on default landing page

### ISSUE THREAD

**Issue by neitsab** [kubernetes/dashboard#8965]
### What happened?

After connecting for the first time to the Dashboard on a fresh install (Ubuntu 22.04.4 Server + MiniK8s, following the steps at https://microk8s.io/#install-microk8s#install-microk8s), I clicked on "[take the Dashboard Tour](https://kubernetes.io/docs/user-guide/ui/)" and landed on a 404:

![dashboard](https://github.com/kubernetes/dashboard/assets/2963014/0bb817b8-ff46-4e46-9779-b69904efac25)

![404](https://github.com/kubernetes/dashboard/assets/2963014/ddb020a4-bb2f-44ab-912a-23dc0f555c03)

Maybe the link could be changed to https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ or anything else appropriate.

### What did you expect to happen?

Clicking on the "take the Dashboard Tour" link would bring me to the Dashboard Tour

### How can we reproduce it (as minimally and precisely as possible)?

* install Ubuntu Server 22.04.4 using default options
* install MicroK8s using the instructions at https://microk8s.io/#install-microk8s#install-microk8s
* connect to the Dashboard using the address and token provided by the last command
* click on the "take the Dashboard Tour" link

### Anything else we need to know?

The "deploy a containerized app" link doesn't do anything either, but I am not sure whether this is because of my config.

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

v2.7.0+0.g42deb6b32

### Kubernetes version

Client Version: v1.29.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.2

**Comment by HanNguyen-dev** [comment]
The url has been updated about 1 year ago.

https://github.com/kubernetes/dashboard/blob/bac8c5fb752c118ed5aa8de2b2b323f7ec57c595/modules/web/src/common/components/zerostate/template.html#L41-L42

**Comment by neitsab** [comment]
Thanks for the pointer, I didn't consider it could be a downstream issue. Reporting it there and closing here then, sorry for the inconvenience 🙏🏻
