### ISSUE TITLE
With Ingress to reach the svc , the expose site report error /api/v1/login not found 

### ISSUE THREAD

**Issue by chenm0520** [kubernetes/dashboard#8970]
### What happened?

I build a site for dashboard with a ingress yaml
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-k8s-chenm-xyz
  namespace: kubernetes-dashboard
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  tls:
    - hosts:
      - k8s.local.xyz
      secretName: k8s-chenm-xyz-ssl-tls
  ingressClassName: nginx
  rules:
  - host: k8s.local.xyz
    http:
      paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-web
                port:
                  name: web
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-api
                port:
                  name: api
`  ,after applying it , I can vist the site with static page ,most APIs are inaccessible(the  only accessible api I found is /api/v1/csrftoken/login)

### What did you expect to happen?

full APIs are accessible and enter the site

### How can we reproduce it (as minimally and precisely as possible)?

dashboard version lastest 
install by
`# Add kubernetes-dashboard repository
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
# Deploy a Helm Release named "kubernetes-dashboard" using the kubernetes-dashboard chart
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard`
apply the ingress yaml mentioned above;
the  reporduce

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

lastest

### Kubernetes version

1.30

**Comment by chenm0520** [comment]
> Use our embedded ingress and override its configuration via helm values. Your ingress is invalid and does not match our kong gateway configuration. It is a configuration issue on your side.
ok, I get it,the route rules are encapsulated into the kong gateway ,I can access the dashboard with the ingress to kong-proxy,but this way the system's gateway rules could be  redundant and I think the rule of the path to api/web  is not complicated，but I can't find some document about it。where is the  introduction about the part?

**Comment by floreks** [comment]
It is not documented because this is our internal configuration detail and is a subject to change in the future. If you would disable kong and use only ingress then any changes we make in kong gateway config will impact you and force you to update your config too.

You can see kong config here: https://github.com/kubernetes/dashboard/blob/master/hack%2Fgateway%2Fprod.kong.yml

**Comment by chenm0520** [comment]
> It is not documented because this is our internal configuration detail and is a subject to change in the future. If you would disable kong and use only ingress then any changes we make in kong gateway config will impact you and force you to update your config too.
> 
> You can see kong config here: https://github.com/kubernetes/dashboard/blob/master/hack%2Fgateway%2Fprod.kong.yml

thanks,I can now access the dashboard without kong ingress.
