### ISSUE TITLE
Firefox has troubles loading workloads page

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#899]
#### Issue details

```
Dashboard version: HEAD
Operating system: Ubuntu 15.10
```

On Firefox (47.0) there are problems with some js code and workloads page is loading very long. Sometimes even crashes before showing. It seems that this is related to middle ellipsis formatting.

**Comment by bryk** [comment]
Can you take this? I also encountered the problem, but couldn't find a concrete solution. Try using a debugger or something.

**Comment by floreks** [comment]
Sure, I'll check this.

**Comment by floreks** [comment]
Unfortunately it is due to middle ellipsis formatting. Firefox has issues with DOM manipulaton `width = measurementElement.offsetWidth` takes ~100ms to execute on workloads page. I'm not sure what we can do right now other than redesign in in a way not to use DOM manipulation. @bryk @maciaszczykm any ideas?

**Comment by bryk** [comment]
I agree. Make it use standard CSS `text-overflow: ellipsis` rules.

**Comment by bryk** [comment]
So, we have less problems now, but the root of the issue is still there. Move to post 1.1?

**Comment by floreks** [comment]
Yep. Let's move it to post 1.1

**Comment by bryk** [comment]
This is fixed.
