### ISSUE TITLE
Display of pod name could be wider

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#902]
#### Issue details

The space allocated to display a pod name could be wider, the empty space is not used:

![image](https://cloud.githubusercontent.com/assets/7731641/16069068/f384c160-330e-11e6-8301-3429a7be77de.png)

```
Dashboard version: 1.1-beta3
Kubernetes version: 1.2.4
Operating system: CoreOS stable
```

**Comment by floreks** [comment]
This is probably related to #706 and #691. Try hovering over the text or refreshing the page and it should be ok. It is a known bug with middle ellipsis formatting. It is supposed to dynamically adjust to available space and calculate text width but in some cases it fails.

Thanks for testing and reporting. We'll fix it eventually :)

**Comment by edouardKaiser** [comment]
Yep you're right ! I'll close this one, thanks.
