### ISSUE TITLE
Not able to install kubernetes-dashboard helm chart with default values file

### ISSUE THREAD

**Issue by sitikanthamishra** [kubernetes/dashboard#9020]
### What happened?

Getting below error

Error: template: kubernetes-dashboard/templates/secrets/csrf.yaml:22:6: executing "kubernetes-dashboard/templates/secrets/csrf.yaml" at <include "kubernetes-dashboard.app.csrf.secret.value" .>: error calling include: template: kubernetes-dashboard/templates/_helpers.tpl:83:63: executing "kubernetes-dashboard.app.csrf.secret.value" at <$secret.data>: wrong type for value; expected map[string]interface {}; got interface {}

### What did you expect to happen?

Helm chart should be installed successfuly

### How can we reproduce it (as minimally and precisely as possible)?

kubernetes version : v1.27.13
helm chart version : 7.3.2

### Kubernetes Dashboard version

7.3.2

### Kubernetes version

v1.27.13

**Comment by pasdoy** [comment]
Same problem for me on Kubernetes 1.23 with Chart version 7.4.0

It work with chart version 7.1.3. Note I didn't try versions between 7.3.1 and 7.1.3.

**Comment by floreks** [comment]
Duplicate of https://github.com/kubernetes/dashboard/issues/8955

/close
