### ISSUE TITLE
Error installing dashboard on docker for desktop Macos 

### ISSUE THREAD

**Issue by mcnealjw63** [kubernetes/dashboard#9031]
### What happened?

Followed directions for helm install
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
 helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard

Get the following response:

Release "kubernetes-dashboard" does not exist. Installing it now.
Error: template: kubernetes-dashboard/templates/secrets/csrf.yaml:22:6: executing "kubernetes-dashboard/templates/secrets/csrf.yaml" at <include "kubernetes-dashboard.app.csrf.secret.value" .>: error calling include: template: kubernetes-dashboard/templates/_helpers.tpl:83:63: executing "kubernetes-dashboard.app.csrf.secret.value" at <$secret.data>: wrong type for value; expected map[string]interface {}; got interface {}

### What did you expect to happen?

Expected dashboard to install

### How can we reproduce it (as minimally and precisely as possible)?

Attempt to install on docker for desktop on mac os

### Kubernetes Dashboard version

7.0.0

### Kubernetes version

Kubernetes v1.29.2

### Dev environment

docker for desktop 4.30.0 (149282)
Kubernetes v1.29.2
helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}

Mac OS Somona 14.4.1 (23E224)

**Comment by floreks** [comment]
Duplicate of #9020 #8955

/close
