### ISSUE TITLE
What happened to the `--enable-skip-login` flag?

### ISSUE THREAD

**Issue by regnaio** [kubernetes/dashboard#9038]
`--enable-skip-login` used to be available to allow us to skip logging in the web UI

The flag is no longer available?

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.0.0

> #### API container
> It is now fully stateless, meaning it does not rely on Kubernetes resources to run. It will always require an authorization token to be present to authorize the request. It is no longer possible for the API container to use its own SA privileges to skip authorization. All arguments that were frontend specific have either been removed or moved to the [Web container](https://github.com/kubernetes/dashboard/releases?page=3#web-container).

/close

**Comment by tbernacchi** [comment]
I don't think this is makes sense - what if I'd to use some external tool to authenticate my users and I want to get rid of the login screen?

**Comment by edify42** [comment]
This is very much the case of the current maintainers of this software not understanding how users were using and deploying it in their environments.

For us, the dashboard was a simple kubernetes 'reader' which was more human friendly than using `kubectl` to view things.

As the dashboard was deployed inside the k8s cluster you wanted to view, it made sense as you could share a URL with a resource that might have had an issue.

While I support breaking the dashboard into smaller, easier to work with pieces, the removal of the native integration with the k8s service account to read the k8s API makes no sense.
