### ISSUE TITLE
Helm values Affinity does not get applied to Kong Deployment

### ISSUE THREAD

**Issue by regnaio** [kubernetes/dashboard#9053]
### What happened?

[Values Affinity](https://github.com/kubernetes/dashboard/blob/master/charts/kubernetes-dashboard/values.yaml#L124) does not get applied to Kong Deployment

It does get applied to all other Deployments besides Kong

Also, where is the Kong Deployment in the Helm chart? [`charts/kubernetes-dashboard/templates/deployments`](https://github.com/kubernetes/dashboard/tree/master/charts/kubernetes-dashboard/templates/deployments) only shows 4 Deployments (no Kong)

### Kubernetes version

Helm chart version: `7.4.0`
Kubernetes Dashboard version: `v3.0.0-alpha0`

**Comment by floreks** [comment]
This comment should answer this: https://github.com/kubernetes/dashboard/issues/9051#issuecomment-2114992287

/close
