### ISSUE TITLE
🚨 Helm `metrics-server` Deployment uses `web` `env`

### ISSUE THREAD

**Issue by regnaio** [kubernetes/dashboard#9054]
https://github.com/kubernetes/dashboard/blob/master/charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml#L64

I believe that

```yaml
{{- with .Values.web.containers.env }}
```

should be replaced with:

```yaml
{{- with .Values.metricsScraper.containers.env }}
```

**Comment by manojks1999** [comment]
Hi @regnaio ,
Made changes in the config file, here is the PR: https://github.com/kubernetes/dashboard/pull/9057
