### ISSUE TITLE
dashboard login page responds with Unknown error (200): Http failure during parsing for http://10.255.15.136:32260/api/v1/csrftoken/login 

### ISSUE THREAD

**Issue by giorgiberia** [kubernetes/dashboard#9066]
### What happened?

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
fallowed this guide 
created
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: kubernetes-dashboard
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: "admin-user"
type: kubernetes.io/service-account-token

![image](https://github.com/kubernetes/dashboard/assets/6876423/22cab2df-2e35-4696-b76f-1f5b4d377a6a)
and created long lived token successfully 

### What did you expect to happen?

after inserting token and clicking on sign in i expect to login and access dashboard

### How can we reproduce it (as minimally and precisely as possible)?

i had earlier dashboard version even before helm got default.
deleted everything that was associated with that.

kubectl delete deployment kubernetes-dashboard -n kubernetes-dashboard
kubectl delete service kubernetes-dashboard -n kubernetes-dashboard
kubectl delete deployment dashboard-metrics-scraper -n kubernetes-dashboard
kubectl delete service dashboard-metrics-scraper -n kubernetes-dashboard
kubectl delete replicaset -l k8s-app=kubernetes-dashboard -n kubernetes-dashboard
kubectl delete secret kubernetes-dashboard-certs -n kubernetes-dashboard
kubectl delete serviceaccount kubernetes-dashboard -n kubernetes-dashboard
kubectl delete secret kubernetes-dashboard-csrf kubernetes-dashboard-key-holder -n kubernetes-dashboard

and installed using helm

helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
Release "kubernetes-dashboard" does not exist. Installing it now.
NAME: kubernetes-dashboard
LAST DEPLOYED: Tue May 21 12:20:57 2024
NAMESPACE: kubernetes-dashboard
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
*************************************************************************************************
*** PLEASE BE PATIENT: Kubernetes Dashboard may need a few minutes to get up and become ready ***
*************************************************************************************************

when everything was ready 
i did what i described in "What happened?" section

### What browsers are you seeing the problem on?

Chrome, Firefox

### Kubernetes Dashboard version

kubernetes-dashboard-7.4.0

### Kubernetes version

v1.30.1

### Dev environment

i am not running dashboard locally

**Comment by floreks** [comment]
I don't see any description of what actually happened and how did you access dashboard? Can you provide more details?

**Comment by m839336369** [comment]
I closed Kong and used Istio to create it. The routing rules exposed the web and prompted http://10.255.15.136:32260/api/v1/csrftoken/login .
Then I exposed the authorization in the routing rule, prompting Unauthorized (401): Invalid credentials provided

**Comment by giorgiberia** [comment]
did you expose dashboard by changing web's service from clusterip to nodeport?

**Comment by giorgiberia** [comment]
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
after i ran this command i was shown this.

kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443
and ran this.
tried access with http://10.255.15.136:8443 
was not accessible 

then i changed kubernetes-dashboard-web service from clusterip to nodeport giving 32260 but 

getting Unknown error (200): Http failure during parsing for http://10.255.15.136:32260/api/v1/csrftoken/login

**Comment by m839336369** [comment]
> I closed Kong and used Istio to create it. The routing rules exposed the web and prompted Unknown error (200): Http failure during parsing for http://10.255.15.136:32260/api/v1/csrftoken/login
> 
> Then I exposed the authorization in the routing rule, prompting Unauthorized (401): Invalid credentials provided
> 
> apiVersion: gateway.networking.k8s.io/v1 kind: HTTPRoute metadata: name: kubernetes-dashboard-http-route namespace: kubernetes-dashboard spec: parentRefs:
> 
> * name: gateway
>   namespace: istio-system
>   rules:
> * matches:
>   
>   * path:
>     type: PathPrefix
>     value: /api/v1/login
>   * path:
>     type: PathPrefix
>     value: /api/v1/csrftoken/login
>   * path:
>     type: PathPrefix
>     value: /api/v1/me
>     backendRefs:
>   * kind: Service
>     name: kubernetes-dashboard-auth
>     port: 8000
> * matches:
>   
>   * path:
>     type: PathPrefix
>     value: /api
>     type: PathPrefix
>     value: /metrics
>     backendRefs:
>   * kind: Service
>     name: kubernetes-dashboard-api
>     port: 8000
> * matches:
>   
>   * path:
>     type: PathPrefix
>     value: /
>     backendRefs:
>   * kind: Service
>     name: kubernetes-dashboard-web
>     port: 8000

I have resolved this issue, as the access is IP access and cannot carry cookies, which contain token verification information, resulting in 401
Using domain name access can solve the problem

**Comment by giorgiberia** [comment]
> > helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard after i ran this command i was shown this.
> > kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443 and ran this. tried access with http://10.255.15.136:8443 was not accessible
> > then i changed kubernetes-dashboard-web service from clusterip to nodeport giving 32260 but
> > getting Unknown error (200): Http failure during parsing for http://10.255.15.136:32260/api/v1/csrftoken/login
> 
> you shuold expose NodePort for kong-proxy rather than board-web.

i reinstalled it and exposed kong proxy instead of board-web and got 401
created token and accessed dashboard
thank you

**Comment by MainClass2017** [comment]
@giorgiberia how you access url without exposing the dasboard-web service beacuse kong svc  is not  landing any url
facing same issues 

![image](https://github.com/user-attachments/assets/2c618111-2285-4732-ad93-40f8e2baa5ad)

**Comment by giorgiberia** [comment]
@MainClass2017 
I changed Kong proxy type from ClusterIP to NodePort
Gave it a nodePort 32000 
Somebody mentioned to expose not web container but 
Kong proxy

**Comment by MainClass2017** [comment]
@giorgiberia can you give me proper steps  because i did same expose the kong proxy instead of web not able to login when i expose the web i able to login dashboard after that i face the bearer token steps

![image](https://github.com/user-attachments/assets/63f107ce-ca58-48f5-82de-ebfc02b3cdff)

**Comment by giorgiberia** [comment]
i found there was newer version
saw my current version with -- helm list
then upgraded with this ->
helm upgrade kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --namespace kubernetes-dashboard

then edited service of kong proxy with this
kubectl edit service kubernetes-dashboard-kong-proxy -n kubernetes-dashboard 

changed ClusterIP -> NodePort 
gave it nodePort of 32260 
saved

than did this and verified that
kubectl get all -n kubernetes-dashboard

kube proxy really has 32260 and nodeport
service/kubernetes-dashboard-kong-proxy        NodePort    ip     <none>        443:32260/TCP                   66d
accessed this with mozilla

https://internal_ip_of_master_or_worker:32260/#/login
i get this 
![image](https://github.com/user-attachments/assets/2b42f4c2-61c8-438e-a043-48b493bc22e4)
notice https

then i created token and accessed normally
kubectl -n kubernetes-dashboard create token admin-user --duration=1999h

**Comment by MainClass2017** [comment]
@giorgiberia thank you so much for your quick support

**Comment by SlawekKarczewski** [comment]
Great support, guys thank you. Kong-proxy service type change to NodePort and accessing through exposed port solved the issue for me as well.

I am still wondering how to reconfigure the 'kubernetes-dashboard-web' service to get the access working to it as well. I am assuming it would present exactly the same data and Kong-proxy although ?
looking into the logs of the 'kubernetes-dashboard-auth' service i can see the error details with the same response as on web UI service:
![image](https://github.com/user-attachments/assets/e4ce04fe-c2b7-4fab-8727-f55b576dbf64)

and kong config map on default is configured as below:
{
	"kong.yml": "_format_version: \"3.0\"
		services:
		  - name: auth
		    host: kubernetes-dashboard-auth
		    port: 8000
		    protocol: http
		    routes:
		      - name: authLogin
		        paths:
		          - /api/v1/login
		        strip_path: false
		      - name: authCsrf
		        paths:
		          - /api/v1/csrftoken/login
		        strip_path: false
		      - name: authMe
		        paths:
		          - /api/v1/me
		        strip_path: false
		  - name: api
		    host: kubernetes-dashboard-api
		    port: 8000
		    protocol: http
		    routes:
		      - name: api
		        paths:
		          - /api
		        strip_path: false
		      - name: metrics
		        paths:
		          - /metrics
		        strip_path: false
		  - name: web
		    host: kubernetes-dashboard-web
		    port: 8000
		    protocol: http
		    routes:
		      - name: root
		        paths:
		          - /
		        strip_path: false
		"
}

**Comment by MainClass2017** [comment]
@giorgiberia  (--enable-insecure-login  ) this parameters still supported on newer version of dashboard ?

**Comment by giorgiberia** [comment]
I did Not check frankly to say. But I could say new version 7.5.0 worked same as I described above

**Comment by MainClass2017** [comment]
@giorgiberia  when we mention the parameters in deployment of web under the argue spec  (--enable-insecure-login)  ,pod goes to Crash state and showing the Unknown flag
FYI 
![image](https://github.com/user-attachments/assets/6443fae0-773e-43b4-8e95-f41c84e24833)

**Comment by giorgiberia** [comment]
You have skip instead of insecure. Does changing that fix the issue?

**Comment by MainClass2017** [comment]
@giorgiberia  yes when i remove  this  parameters  pod come back to running state.

**Comment by filipisaci** [comment]
I exposed my SVC of kubernetes-dashboard-kong-proxy (as a LoadBalancer or NodePort) and it`s works for me.

**Comment by renanramonh** [comment]
I'm also having the same issue when I set my helm chart like this
```
  kong:
    proxy:
      http:
        enabled: true
 ```
 
 and I use another gateway/ingress that does the tls termination and forward to port 80
 ```
 kubernetes-dashboard-kong-proxy        ClusterIP   10.43.160.195   <none>        80/TCP,443/TCP                  8m6s
```

**Comment by TheOpsDev** [comment]
> > helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard after i ran this command i was shown this.
> > kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443 and ran this. tried access with http://10.255.15.136:8443 was not accessible
> > then i changed kubernetes-dashboard-web service from clusterip to nodeport giving 32260 but
> > getting Unknown error (200): Http failure during parsing for http://10.255.15.136:32260/api/v1/csrftoken/login
> 
> you shuold expose NodePort for kong-proxy rather than board-web.

Fixed my issue, thanks!

**Comment by petgan** [comment]
After tring different ingresses I found out the following:
In my case started by geting a token with : kubectl -n kubernetes-dashboard create token SERVICE_ACCOUNT
I used Edge work profile. 
After that I used the token from in the login page. And it failed miserably. In that case the fault was mine because I did not use the Kong proxy and just expose the kubernetes-dashboard-web service.
Even after reconfiguring and installing Kong proxy service it did not help. In short I ended up adding in kubernetes-dashboard-auth and kubernetes-dashboard-api to my Treafik ingressroute. It seams that the probleme persisted but!!! When I trayed it in  Chrome Incognito mode it worked just fine, then in Chrome and then in Edge InPrivate and then in Edge with my personal profile it work juste fine.
Fanny thing the login error is persistent in my Edge work profile: **Unknown error (200): Http failure during parsing for https://kubernetes-dashboard.my.domain.com/api/v1/csrftoken/login**
Developer Tools in Edge did not revele something like cookie or invalid storage data. 

I may add some extra info if deploy to another cluster and fine more details!
home that will help!

**Comment by garry-t** [comment]
I've read topic. And nothing helped in my case. I have traefik as main ingress for TLS termination, I want to expose dashboard on public subdomain and protect it via Cloudlfare zero trust. Changing value in helm to deploy dashboard without https no luck. 
Who can explain how to expose it in human way without this kubectl dance and expose api.
