### ISSUE TITLE
Failed to receive reply from UDP server xxx:timeout.

### ISSUE THREAD

**Issue by DunZane** [kubernetes/dashboard#9077]
### What happened?

<img width="1367" alt="image" src="https://github.com/kubernetes/dashboard/assets/141797381/0d8e896d-c2f4-4951-8c9b-a40d0ee01b7c">
i try to **https:<my_public_id>:8443** but got error like this

### What did you expect to happen?

Access to dashboard WebGUI and login success.

### How can we reproduce it (as minimally and precisely as possible)?

I try the step provided in github like:
1. install
```
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
```
2. check install
```bash
kubectl get svc -A
root@cluster-master-gz:~# kubectl get svc -A
NAMESPACE              NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
default                kubernetes                             ClusterIP   10.96.0.1        <none>        443/TCP                         42h
kube-system            kube-dns                               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP          42h
kubernetes-dashboard   kubernetes-dashboard-api               ClusterIP   10.104.105.185   <none>        8000/TCP                        57s
kubernetes-dashboard   kubernetes-dashboard-auth              ClusterIP   10.108.210.59    <none>        8000/TCP                        57s
kubernetes-dashboard   kubernetes-dashboard-kong-manager      NodePort    10.99.244.5      <none>        8002:31623/TCP,8445:32653/TCP   57s
kubernetes-dashboard   kubernetes-dashboard-kong-proxy        ClusterIP   10.100.99.125    <none>        443/TCP                         57s
kubernetes-dashboard   kubernetes-dashboard-metrics-scraper   ClusterIP   10.104.163.73    <none>        8000/TCP                        57s
kubernetes-dashboard   kubernetes-dashboard-web               ClusterIP   10.99.68.227     <none>        8000/TCP                        57s
```
3. Change kong-proxy's CLUSTER-IP from ClusterIP to NodePort
```
root@cluster-master-gz:~# kubectl patch service kubernetes-dashboard-kong-proxy -n kubernetes-dashboard -p '{"spec":{"type":"NodePort"}}'
service/kubernetes-dashboard-kong-proxy patched
root@cluster-master-gz:~# kubectl get svc -A
NAMESPACE              NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
default                kubernetes                             ClusterIP   10.96.0.1        <none>        443/TCP                         42h
kube-system            kube-dns                               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP          42h
kubernetes-dashboard   kubernetes-dashboard-api               ClusterIP   10.104.105.185   <none>        8000/TCP                        2m59s
kubernetes-dashboard   kubernetes-dashboard-auth              ClusterIP   10.108.210.59    <none>        8000/TCP                        2m59s
kubernetes-dashboard   kubernetes-dashboard-kong-manager      NodePort    10.99.244.5      <none>        8002:31623/TCP,8445:32653/TCP   2m59s
kubernetes-dashboard   kubernetes-dashboard-kong-proxy        NodePort    10.100.99.125    <none>        443:31480/TCP                   2m59s
kubernetes-dashboard   kubernetes-dashboard-metrics-scraper   ClusterIP   10.104.163.73    <none>        8000/TCP                        2m59s
kubernetes-dashboard   kubernetes-dashboard-web               ClusterIP   10.99.68.227     <none>        8000/TCP                        2m59s
```
4.Accssing to Dashboard(The required ports are already open on the firewall of the cloud server)
```bash
 kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443  --address='<sever_intranet_ip>'
```
5. Visit the web
```
https://<server_public_ip>:8443
```
6. Error Ocurred.
Error
failed the initial dns/balancer resolve for 'kubernetes-dashboard-web' with: failed to receive reply from UDP server 10.96.0.10:53: timeout.

request_id: 2172230fe938b220d29cec488bdd4a3f

### Anything else we need to know?

I try the:
```bash
 kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-web 8080:8000 --address='10.1.20.17'
```
try **http://<server_public_ip>:8080/** in chrome and the login web  page can be success visited but got error like:
<img width="1184" alt="image" src="https://github.com/kubernetes/dashboard/assets/141797381/9bded23e-35f2-4e09-af62-40fdc87719de">
And same issue in https://github.com/kubernetes/dashboard/issues/9066,but his problem is not set the kong-proxy from Cluster-IP to NodeProxy. But from my ` kubectl get svc -A` output:
```
root@cluster-master-gz:~# kubectl get svc -A
NAMESPACE              NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
default                kubernetes                             ClusterIP   10.96.0.1        <none>        443/TCP                         42h
kube-system            kube-dns                               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP          42h
kubernetes-dashboard   kubernetes-dashboard-api               ClusterIP   10.104.105.185   <none>        8000/TCP                        2m59s
kubernetes-dashboard   kubernetes-dashboard-auth              ClusterIP   10.108.210.59    <none>        8000/TCP                        2m59s
kubernetes-dashboard   kubernetes-dashboard-kong-manager      NodePort    10.99.244.5      <none>        8002:31623/TCP,8445:32653/TCP   2m59s
kubernetes-dashboard   kubernetes-dashboard-kong-proxy        NodePort    10.100.99.125    <none>        443:31480/TCP                   2m59s
kubernetes-dashboard   kubernetes-dashboard-metrics-scraper   ClusterIP   10.104.163.73    <none>        8000/TCP                        2m59s
kubernetes-dashboard   kubernetes-dashboard-web               ClusterIP   10.99.68.227     <none>        8000/TCP                        2m59s
```
kong-proxy'type has been NodePort.

### Kubernetes Dashboard version

NAME: kubernetes-dashboard LAST DEPLOYED: Mon May 27 08:58:08 2024 NAMESPACE: kubernetes-dashboard STATUS: deployed REVISION: 1 TEST SUITE: None

### Kubernetes version

Client Version: v1.28.10 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.10

### Dev environment

go version go1.22.3 linux/amd64

**Comment by floreks** [comment]
This is not how you should expose applications in Kubernetes publicly. This is a configuration issue. GitHub is only for the actual bugs, not support.

/close

**Comment by lgmg** [comment]
Sorry, I know that this is not the place for this kind of discussion, but it may help. I had the same issue, my kubernetes cni (flannel) range pod cidr was not consistent with the one at the init.
- at kubeadm init 10.85.0.0/16
- flannel : 10.244.0.0/16
the core dns pods was created before flannel deployment which has a different subnet range than the one where the core dns was created. I deleted the all the pods replica (kubernetes will create new ones with the correct Cluster IP subnet) and dns is working fine after. But it should be cleaner to reinstall.

**Comment by LyunSs** [comment]
I got the same issue, did you solve it? @DunZane

**Comment by abhijith-zupaloop** [comment]
Any solutions ?? @DunZane @LyunSs  ??

**Comment by Martin-Luther** [comment]
Kernel 4.19.0-27-amd64
Kubernetes 1.30.5 + containerd 1.6.33
calico-cni v 3.28.2

----
I am having the same issue :'( 
The only way I have found to make this go away was to restart coredns and everything went back as usual.

```tty
kubectl rollout restart deployment -n kube-system coredns
```

**Comment by anlexN** [comment]
My solution is that restart my virtual machine.
