### ISSUE TITLE
dashboard does not display CPU/ram metrics

### ISSUE THREAD

**Issue by GrimMIAC** [kubernetes/dashboard#9091]
### What happened?

when installing helm according to the standard instructions, the service is fully functional, but I cannot determine the problem of metric-scarper. kubectl top reports error: Metrics API is not available, and dashboards do not have information about memory and processor usage of pods. Еhe logs also report errors Skipping metric because of error: Metric label not set. and No persistentvolumeclaims found related to *-*-* pod
![api](https://github.com/kubernetes/dashboard/assets/171009315/133f187b-ed9a-403c-8a94-2b3de289da23)
![metric](https://github.com/kubernetes/dashboard/assets/171009315/d3ec034c-fba0-4c12-910d-e089ddacbca1)
![pods](https://github.com/kubernetes/dashboard/assets/171009315/7056921d-3e50-433b-99a3-6f88bba08809)

### What did you expect to happen?

with standard settings, all the functionality works

### How can we reproduce it (as minimally and precisely as possible)?

helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard

kubectl -n kubernetes-dashboard edit service kubernetes-dashboard-kong-proxy

changing the port to NodePort

installing roles and users:
--
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
--

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: kubernetes-dashboard
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: kubernetes-dashboard
--
apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: admin-user
type: kubernetes.io/service-account-token
--
and getting an authorization token

### Anything else we need to know?

the system is empty, kubernetes is installed via kubeadm, as well as cri-o and callico
![all](https://github.com/kubernetes/dashboard/assets/171009315/d7daaaeb-64af-47c0-ae95-472b18064b4b)

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.4.0

### Kubernetes version

1.28.8

**Comment by floreks** [comment]
As you can see from kubectl top output, you do not have metrics server installed in your cluster. It is an optional dependency of our chart, disabled by default: 

```
## Optional Metrics Server sub-chart configuration
## Enable this if you don't already have metrics-server enabled on your cluster and
## want to use it with dashboard metrics-scraper
## refs:
##  - https://github.com/kubernetes-sigs/metrics-server
##  - https://github.com/kubernetes-sigs/metrics-server/tree/master/charts/metrics-server
metrics-server:
  enabled: false
```

Either override it during chart installation or install metrics server separately.

/close
