### ISSUE TITLE
How long is the Kubernetes Dashboard Token valid for

### ISSUE THREAD

**Issue by l1douhua** [kubernetes/dashboard#9102]
### What should be cleaned up or changed?

After I login with the token, it is valid for about ten minutes.

### Why is this needed?

How to extend your visit time

**Comment by floreks** [comment]
Missing information about your setup and dashboard version. It differs depending on your setup.

**Comment by l1douhua** [comment]
> 缺少有关您的设置和仪表板版本的信息。它因您的设置而异。

7.0.0-alpha1

**Comment by lgmg** [comment]
you can eventually decode you jwt token to have the expiration date. For example with : https://jwt.io/

**Comment by floreks** [comment]
Outdated (unsupported) version of dashboard used. Closing.

/close
