### ISSUE TITLE
Bad Request (400): Empty token provided

### ISSUE THREAD

**Issue by spagu** [kubernetes/dashboard#9109]
### What happened?

When I tried to log in, I got the message `Bad Request (400): Empty token provided` even though a token was provided. 

### What did you expect to happen?

Access dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

Install microk8s with a dashboard 

### Anything else we need to know?

using microk8s 1.28 not 1.30+( as 1.30 is broken )  

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

image: kubernetesui/dashboard:v2.7.0

### Kubernetes version

Client Version: v1.30.1 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

**Comment by floreks** [comment]
Use the latest Dashboard version. `v2.7.0` is no longer supported.

/close
