### ISSUE TITLE
Kubernetes dashboard not list all namespaces on namespaces dropdown list

### ISSUE THREAD

**Issue by maisam94** [kubernetes/dashboard#9136]
### What happened?

After upgrade to version 7.4.0, the kube dashboard have access only to default namespace resources

### What did you expect to happen?

show all namespaces on namespaces dropdown list

### How can we reproduce it (as minimally and precisely as possible)?

upgrade from version 6.0.8 to 7.4.0 

### Kubernetes Dashboard version

7.4.0

### Kubernetes version

Client Version: v1.29.3-eks-ae9a62a Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.4-eks-036c24b

**Comment by floreks** [comment]
`All namespaces` option is only available if you have permission to list namespaces. You haven't provided any steps to reproduce. I can only assume that you are not logging in with a user that has required permissions.

**Comment by maisam94** [comment]
I logging in with token for service account, after adding cluster role binding with list permission i got all namespaces. 
why the chart not have role with readonly permission like in past version.
how can configure chart to have permission list all namespaces ?

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.0.0

> ### API container
> It is now fully stateless, meaning it does not rely on Kubernetes resources to run. It will always require an authorization token to be present to authorize the request. It is no longer possible for the API container to use its own SA privileges to skip authorization. All arguments that were frontend specific have either been removed or moved to the [Web container](https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.0.0#web-container).

Previously, readonly role was used as part of the internal SA tied to the Dashboard in order to allow skipping the login view and acting on behalf of Dashboard. Since it is no longer possible to do that, it has been removed from the chart. You need to create your own SA/Role/Bindings and get the token in order to log in now.

/close
