### ISSUE TITLE
Display the port for NodePort services

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#919]
#### Issue details

In the service details view, we don't display the port that has been allocated when it's a NodePort service.
I personally would find it useful. 

![image](https://cloud.githubusercontent.com/assets/7731641/16176877/be4e969e-365e-11e6-86ad-e864ce546956.png)

Thoughts ?

##### Environment
```
Dashboard version: 1.1.beta3
Kubernetes version: 1.2.4
```

**Comment by floreks** [comment]
I agree that this should be added. `kubectl` is also showing this information.

**Comment by bryk** [comment]
@floreks Can you fix this?

**Comment by floreks** [comment]
Sure, how should we refer it? External node endpoint?

**Comment by bryk** [comment]
Yes, sounds good.
