### ISSUE TITLE
Unauthorized (401): Invalid credentials provided

### ISSUE THREAD

**Issue by xjdtd** [kubernetes/dashboard#9201]
### What happened?

when using the token by the command of kubectl -n kubernetes-dashboard create token sa-dashboard-admin，the error is here：Unauthorized (401): Invalid credentials provided

[root@master01 https]# kubectl -n kubernetes-dashboard get sa sa-dashboard-admin 
NAME                 SECRETS   AGE
sa-dashboard-admin   0         89m
[root@master01 https]# kubectl -n kubernetes-dashboard get clusterrolebinding | grep cluster-dashboard-admin
cluster-dashboard-admin                                         ClusterRole/cluster-admin                                                          71m
[root@master01 https]# kubectl -n kubernetes-dashboard describe clusterrolebindings cluster-dashboard-admin
Name:         cluster-dashboard-admin
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind            Name                Namespace
  ----            ----                ---------
  ServiceAccount  sa-dashboard-admin  kubernetes-dashboard
[root@master01 https]# kubectl -n kubernetes-dashboard create token sa-dashboard-admin 
eyJhbGciOiJSUzI1NiIsImtpZCI6IkhvNThnVWV1cTl1Zi1sMF83STdFUGpOUF95eFRvcEtnWjZLaUxRdVJuTUkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzE5NTc0MjA1LCJpYXQiOjE3MTk1NzA2MDUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYmY5YzkyZWItYjg5Ny00YmQzLTkxMDQtMmE5NjQ2YzhkODlmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJzYS1kYXNoYm9hcmQtYWRtaW4iLCJ1aWQiOiI3MmY0NzExNS03NmI3LTQzNGYtODMyZC0yNmY3NzU1ZWU5YzUifX0sIm5iZiI6MTcxOTU3MDYwNSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmVybmV0ZXMtZGFzaGJvYXJkOnNhLWRhc2hib2FyZC1hZG1pbiJ9.d316chkX5N6OqX19IkU41P6187vuwLK742p_MMnLmbhMOKzmrJNef0M6sojRSWfhKaZZfpqJ0in3E_7VQQs0WEBUwFoSf158ZKmWCU249SfhCgrcyBDu5iF9yiP5H-J3ffE9poqt-jkhN8XTvoJenNdODRHRmlur9HBn9oM7QFle9aQdS5b1bNqlrxIEmqmQBN-jNR6qEISwL_MUZ7uHmo_TsbLdRqSHDzDSjuJCbyTcQENAlWg7TRzB1T7dJn2U3eDY5VGP6bIoKgnuYO4LcAWOr1Q_TFsOO0hXRtOxPCdjxopK5VUT54dabcvkIYCTnOw1uwcyODOvcGIklAu6yA
[root@master01 https]# 

[root@master01 https]# kubectl -n kubernetes-dashboard logs  kubernetes-dashboard-auth-6fcff4cb57-brhj7 |tail -3
E0628 10:25:39.883479       1 handler.go:33] "Could not get user" err="MSG_LOGIN_UNAUTHORIZED_ERROR"
[GIN] 2024/06/28 - 10:52:08 | 200 |    6.300135ms |  10.244.186.227 | GET      "/api/v1/me"
[GIN] 2024/06/28 - 10:52:38 | 200 |    3.200158ms |  10.244.186.227 | GET      "/api/v1/me"
[root@master01 https]# 

but
[root@master01 https]# curl http://dashboard.jdxu-k8s.com/api/v1/me --header "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkhvNThnVWV1cTl1Zi1sMF83STdFUGpOUF95eFRvcEtnWjZLaUxRdVJuTUkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzE5NTc0MjA1LCJpYXQiOjE3MTk1NzA2MDUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYmY5YzkyZWItYjg5Ny00YmQzLTkxMDQtMmE5NjQ2YzhkODlmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJzYS1kYXNoYm9hcmQtYWRtaW4iLCJ1aWQiOiI3MmY0NzExNS03NmI3LTQzNGYtODMyZC0yNmY3NzU1ZWU5YzUifX0sIm5iZiI6MTcxOTU3MDYwNSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmVybmV0ZXMtZGFzaGJvYXJkOnNhLWRhc2hib2FyZC1hZG1pbiJ9.d316chkX5N6OqX19IkU41P6187vuwLK742p_MMnLmbhMOKzmrJNef0M6sojRSWfhKaZZfpqJ0in3E_7VQQs0WEBUwFoSf158ZKmWCU249SfhCgrcyBDu5iF9yiP5H-J3ffE9poqt-jkhN8XTvoJenNdODRHRmlur9HBn9oM7QFle9aQdS5b1bNqlrxIEmqmQBN-jNR6qEISwL_MUZ7uHmo_TsbLdRqSHDzDSjuJCbyTcQENAlWg7TRzB1T7dJn2U3eDY5VGP6bIoKgnuYO4LcAWOr1Q_TFsOO0hXRtOxPCdjxopK5VUT54dabcvkIYCTnOw1uwcyODOvcGIklAu6yA" --insecure -w '\n'
{"name":"sa-dashboard-admin","authenticated":true}
[root@master01 https]#

### What did you expect to happen?

use token to login

### How can we reproduce it (as minimally and precisely as possible)?

helm install 

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.5

### Kubernetes version

1.30

**Comment by WangYihang** [comment]
I also encountered the same problem, and I tried open dashboard on the private tab, it works.

So this problem can be solved it by clearing the follow browser cookies.

* `token`
* `refresh_token`

After cleaning the token, I can login sucessfully.

Hope it helps.
