### ISSUE TITLE
Edit a ConfigMap

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#922]
#### Issue details

Any plan to offer ConfigMap edition ?
I think they are a pretty useful resource. I'm asking because I didn't see anything in the mockup (https://github.com/kubernetes/dashboard/tree/master/docs/design/mockups) regarding the ConfigMap.

**Comment by bryk** [comment]
Yes, this is in plans. After we're done with our 1.1 release we will update the roadmap so that this is reflected. And yes, this is pretty high on the list :)

**Comment by edouardKaiser** [comment]
Awesome, thanks

**Comment by edouardKaiser** [comment]
The YAML editor works pretty well in most of the cases, but I think we need something different for ConfigMap. It's pretty hard to edit correctly the data of a config map into the YAML editor (because of the CR).

Example:
![image](https://cloud.githubusercontent.com/assets/7731641/17538888/fc452aba-5eec-11e6-9591-4d94ef5b8fd2.png)

![image](https://cloud.githubusercontent.com/assets/7731641/17538916/28fa2722-5eed-11e6-9ac9-390984612d87.png)

**Comment by bryk** [comment]
Yeah, we're aware of this. The YAML editor does not work well with secrets and config maps. We need something custom for them.

**Comment by maciaszczykm** [comment]
It's already possible to edit a config map. Further updates of YAML editor can be followed in https://github.com/kubernetes/dashboard/issues/1221.
