### ISSUE TITLE
Bring back the `--enable-skip-login` flag. --version 7.x.0

### ISSUE THREAD

**Issue by tbernacchi** [kubernetes/dashboard#9247]
### What would you like to be added?

I'd to get rid of the login screen and seems that's not possible [anymore](https://github.com/kubernetes/dashboard/issues/9038).  

### Why is this needed?

I don't believe removing this feature makes sense - what if we'd to use some external tool to authenticate my users and we don't want to land on that login screen? What are the options?

**Comment by edify42** [comment]
>Is there still no way to skip token based auth for dev installations in v7+?

No it's by design
