### ISSUE TITLE
kubernetes dashboard problems

### ISSUE THREAD

**Issue by ghprimerib** [kubernetes/dashboard#926]
#### Issue details

I've created the dashboard pod.  Logs imply it's running and talking to the api server okay.   But when I go to the url:  https://paas1.r1dev.com/ui    I am unable to connect.

Logs:
[~]$ kubectl get pods --namespace=kube-system
NAME                         READY     STATUS    RESTARTS   AGE
kube-dns-v10-umyn4           4/4       Running   0          1h
kubernetes-dashboard-9x8dl   1/1       Running   0          10m
[routeone@paas1 ~]$ kubectl logs kubernetes-dashboard-9x8dl --namespace=kube-system
Starting HTTP server on port 9090
Creating API server client for http://paas1.r1dev.com:8080
Successful initial request to the apiserver, version: v1.2.0
Creating in-cluster Heapster client

On our node box:
[~]$ ps -ef |grep 9090
root      6730  6715  0 16:59 ?        00:00:00 /dashboard --port=9090 --apiserver-host=http://paas1.r1dev.com:8080

grep dashb out of kube log:

Jun 20 17:58:35 paas1 kube-apiserver: I0620 17:58:35.419404   18032 handlers.go:152] GET /api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: (2.599777ms) 200 [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/5cb86ee/endpoint-controller] 192.168.11.75:60210]
Jun 20 17:59:04 paas1 kube-apiserver: I0620 17:59:04.428377   18032 handlers.go:152] GET /api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: (4.005176ms) 200 [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/5cb86ee/endpoint-controller] 192.168.11.75:60335]
Jun 20 17:59:33 paas1 kube-apiserver: I0620 17:59:33.440993   18032 handlers.go:152] GET /api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: (2.500746ms) 200 [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/5cb86ee/endpoint-controller] 192.168.11.75:60443]
Jun 20 18:00:02 paas1 kube-apiserver: I0620 18:00:02.447065   18032 handlers.go:152] GET /api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: (3.416828ms) 200 [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/5cb86ee/endpoint-controller] 192.168.11.75:60579]

##### Environment
Dashboard version: app=kubernetes-dashboard,version=v1.1.0-beta3
Kubernetes version: Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Operating system: RHEL 7.2
Node.js version: 
Go version: go1.6.2

##### Comments
Any suggestions of where to look for what is wrong?  The log output above doesn't show any errs.

**Comment by bryk** [comment]
What do you see? An error? Or maybe empty page? Can you send a screenshot?

**Comment by ghprimerib** [comment]
The error is that the browser said unable to connect.  But I was trying to connect: https://paas1.r1dev.com/ui

That was what the dashboard docs said to connect to:
https://<kubernetes-master>/ui

Turns out that I can access the dashboard via our node FQDN at:  http://paas2.r1dev.com:30347

So no real issue here.  Just didn't know how to connect to dashboard correctly.
Thanks
