### ISSUE TITLE
Should we check nil pointer query in dataselect

### ISSUE THREAD

**Issue by warjiang** [kubernetes/dashboard#9262]
### What would you like to be added?

The `dataselect` is well designed to filter、sort、paginate datacells. I want to reuse the `dataselect` module in my project.  But I metioned that `FilterQuery`、`SortQuery`、`PaginationQuery` may be nil and cause panic error, for example
```
// Filter the data inside as instructed by DataSelectQuery and returns itself to allow method chaining.
func (self *DataSelector) Filter() *DataSelector {
	filteredList := []DataCell{}

	for _, c := range self.GenericDataList {
		matches := true
		for _, filterBy := range self.DataSelectQuery.FilterQuery.FilterByList {
			v := c.GetProperty(filterBy.Property)
			if v == nil || !v.Contains(filterBy.Value) {
				matches = false
				break
			}
		}
		if matches {
			filteredList = append(filteredList, c)
		}
	}

	self.GenericDataList = filteredList
	return self
}
```
when we iterate `self.DataSelectQuery.FilterQuery.FilterByList`, if the `FilterQuery` is nil, it will panic.

The use-case of my code is following:
```
selectableData := dataselect.DataSelector{
    GenericDataList: ToCells(listResult.Items),
    DataSelectQuery: &dataselect.DataSelectQuery{
	//FilterQuery:     nil,
	//SortQuery:       nil,
	//PaginationQuery: nil,
	//FilterQuery:     dataselect.NewFilterQuery([]string{"name", "111"}),
	SortQuery: dataselect.NewSortQuery([]string{"a", "name"}),
	//PaginationQuery: dataselect.NewPaginationQuery(10, 2),
    },
}
selectableData.Filter().Sort().Paginate()
```

Apart from QueryFilter, the `DataSelectQuery` should also be checked to avoid nil pointer error.

### Why is this needed?

For more robust, when the `dataselect` pkg is resued by other project.
```[tasklist]
### Tasks
```

**Comment by maciaszczykm** [comment]
@warjiang are you willing to work on it?

**Comment by warjiang** [comment]
> @warjiang are you willing to work on it?

Yes, I think it should check the nil pointer, but no repsonse or no more discussion about it. Should I make contribution and ask for some review the changes?

**Comment by maciaszczykm** [comment]
@warjiang Yes, that would be perfect.
