### ISSUE TITLE
Embedding Kubernetes Dashboard in Iframe throws Auth Error

### ISSUE THREAD

**Issue by mikeNetHopper** [kubernetes/dashboard#9291]
### What happened?

I have installed my kubernetes dashboard with the kong proxy as a NodePort in an AWS ec2 machine running minikube. Everything is up and running perfectly. I'm able to successfully login to my dashboard from an individual web browser tab at the ip address and associated port: https://{external-IP}:{port} using a service account token. However, when trying to embed the dashboard using the URL in an iFrame, the login auth fails on the /api/v1/me network call with an error "401 Unauthorized":
```json
{
    "ErrStatus": {
        "metadata": {},
        "status": "Failure",
        "message": "MSG_LOGIN_UNAUTHORIZED_ERROR",
        "reason": "Unauthorized",
        "code": 401
    }
}
```
 

The api call to the /me endpoint is not including the authorization header because it's in an iFrame. Does anyone have a work around or a way to configure the helm values on install in order to get this to work? 

### What did you expect to happen?

I would expect the login process to successfully work on an iFrame the same way it does through an individual we browser tab

### How can we reproduce it (as minimally and precisely as possible)?

once you have an up and running dashboard instance that's publicly reachable over the internet with the kong proxy as a NodePort, you can use the following code block at the following web address replacing "src" with your kubernetes dashboard url: 
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_iframe_sandbox 

```html
<!DOCTYPE html>
<html>
<body>

<iframe src="" width="600px" height="500px sandbox="
        allow-scripts
        allow-same-origin
        allow-forms
">
</iframe>
</body>
</html>
```

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

kubernetes-dashboard-7.5.0

### Kubernetes version

1.30.0

**Comment by floreks** [comment]
We do not really support running dashboard in an iframe for security reasons. It is highly likely that the csrf protection will reject the actual login POST request. Also our cookies use strict domain checking.
