### ISSUE TITLE
QoS Tier (cpu/memory) information in pod details view

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#932]
I was having a look at the pod details view and was thinking that we could display extra useful  information potentially.

What about those one:
- args
- volumes
- QoS Tier (cpu/memory)

Thoughts ?

**Comment by maciaszczykm** [comment]
We have it in our plans, but cannot provide any date yet.

**Comment by bryk** [comment]
@edouardKaiser And we highly encourage you to contribute to add missing features :) It should be easy job

**Comment by edouardKaiser** [comment]
You're probably right, but my Go Lang skills are literally null. I guess it's an opportunity to learn Go lang ;)

**Comment by bryk** [comment]
It is a nice language :) And when it is things that we did in the past, you have plenty of places around the codebase for inspiration

**Comment by therc** [comment]
Custom resources, too. Actually, I added alpha support for GPU scheduling, it would be great to show that.

**Comment by edouardKaiser** [comment]
That's another issue, but I tried to setup the dev environment. Not sure how to configure IntelliJ properly but it doesn't recognise all the external import (github, k8s,io...) and when I start a local cluster with `gulp local-up-cluster` the API server is not exposed on localhost 8080 (probably because I'm using Docker Beta for Mac). If someone is willing to spend time help me to setup the dev environment, I'll be more than happy to try to come up with some pull requests. (I'm a Java/Scala developer, totally not familiar with NodeJS/NPM/Gulp/Bower....).

**Comment by floreks** [comment]
I'm using IntelliJ Ultimate so I can help you configure it. 

1. Download `Go` and `AngularJS` plugins.
1. IntelliJ should recognize project as `Go project` and offer to change its type.
1. Settings -> Languages & Frameworks -> JavaScript -> Set language version to ES 6
1. Settings -> Languages & Frameworks -> Go -> Go Libraries -> Add Project libraries `<dashboard_home>`, `<dashboard_home>/Godeps/_workspace`, `<dashboard_home>/.tmp/backend` (this one is generated when you run gulp serve/serve:prod/build and only then IntelliJ will resolve our imports)
1. Settings -> Editor -> Code Style -> Set `Right margins (columns)` to 100 and select wrap on typing.

Also you can change `Tab size` and `Indent` for JS (2, 2) and Go (4, 4) code.

As for the local cluster, I'm not using it for a long time. I prefer to use local cluster build from k8s repo. @bryk and @maciaszczykm are using Mac so maybe they know how to configure it properly.

**Comment by edouardKaiser** [comment]
Thanks Sebastian, much appreciated, I'll give it a try.

**Comment by bryk** [comment]
> @bryk and @maciaszczykm are using Mac so maybe they know how to configure it properly.

I have an external remote cluster that I access via `kubectl proxy --port=8080`

**Comment by edouardKaiser** [comment]
@bryk it's perfect, I can do that
