### ISSUE TITLE
kubernetes-dashboard-metrics-scraper memory leak ?

### ISSUE THREAD

**Issue by fykyx521** [kubernetes/dashboard#9325]
### What happened?

![image](https://github.com/user-attachments/assets/eb647aba-2cfe-4068-8d75-85bdef04e2d8)

### What did you expect to happen?

kubernetes-dashboard-metrics-scraper-79f948766b-dg268   1m           15Mi     

### How can we reproduce it (as minimally and precisely as possible)?

kubernetes-dashboard-metrics-scraper-79f948766b-dg268   1m           15Mi     

### Anything else we need to know?

https://github.com/kubernetes/dashboard/blob/4eda6647c3f6c697dbe40c20d7bb8ba96fecd4e7/modules/metrics-scraper/main.go#L121

[https://github.com/AlexiaChen/AlexiaChen.github.io/issues/139](url)

### Kubernetes Dashboard version

7.5.0

### Kubernetes version

v1.27.4+k3s1

**Comment by floreks** [comment]
This graph actually does not look like a memory leak. It stabilizes itself pretty fast and it makes sense. Scraper is using in-memory storage by default to store metrics for the configured time window (defaults to last 15 minutes). After ~15 minutes it should be more or less stable. 

/close
