### ISSUE TITLE
Kong-proxy pod unable to access to the kubernetes-dashboard-web svc

### ISSUE THREAD

**Issue by samcoolong** [kubernetes/dashboard#9346]
### What happened?

Hello,

I got an error message as below while I tried access to kubernetes-dashboard-kong-proxy service by using curl(or browser)

[error] 1315#0: *3507 [lua] init.lua:371: execute(): DNS resolution failed: failed to receive reply from UDP server 10.96.0.10:53: timeout. Tried: ["(short)kubernetes-dashboard-web.kubernetes-dashboard.svc.cluster.local:(na) - cache-miss"

But the coredns was working well, i did some test by nslookup then confirmed coredns works well.

And then I reset the k8s cluster but it didn't work also.

### What did you expect to happen?

works

### How can we reproduce it (as minimally and precisely as possible)?

no comment

### Anything else we need to know?

OS:  AlmaLinux 9.4
CRI-O version: 1.29.1

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Kubernetes Dashboard version

7.5

### Kubernetes version

1.29.7

**Comment by floreks** [comment]
This looks like a cluster configuration issue. If pods cannot access other pods via service internal DNS, you should debug your cluster networking. This is not directly related to Dashboard. Any in-cluster app that might require access to other in-cluster resources will most likely fail.

/close

**Comment by samcoolong** [comment]
> This looks like a cluster configuration issue. If pods cannot access other pods via service internal DNS, you should debug your cluster networking. This is not directly related to Dashboard. Any in-cluster app that might require access to other in-cluster resources will most likely fail.
> 
> /close

Thanks for reply, but the dns works well when I use the busybox for testing. The coredns respones correctly while I use ping or nslookup in the busybox pod.

nslookup kubernetes-dashboard-web.kubernetes-dashboard.svc.cluster.local

then it gave me the correct  IP address of the kubernetes-dashboard-web service.

**Comment by floreks** [comment]
Could be related https://github.com/Kong/kong/issues/7588#issuecomment-894772687

Still, it looks like an issue with the overlay network. I'd also recommend looking into coredns logs. In general, networking issues are not directly related to the application code, but to the configuration and how it is being accessed. It can also vary between different kubernetes installations, whether it's cloud (GKE, EKS) or local cluster (kind, minikube, baremetal).

**Comment by samcoolong** [comment]
Agree, I considered this could the overlay network issue too. I remove the cri-o then changed to containerd + calico last night, the dns issue gone. It maybe caused by the cni plugin which came from the cri-o installation.
