### ISSUE TITLE
[k8s 1.31.0 arm64] Metrics scraper and metrics don't run with helm installation

### ISSUE THREAD

**Issue by lprimak** [kubernetes/dashboard#9398]
### What happened?

Installed a new v1.31.0 cluster, metrics server and dashboard (via helm)
Metrics scraper pod is not deployed, not is it running
Obviously metrics are missing

### What did you expect to happen?

Metrics are working and are shown in dashboard

### How can we reproduce it (as minimally and precisely as possible)?

install k8s v1.31.0 on arm64, make sure metrics server is running, and install k8s dashboard via helm

### Anything else we need to know?

Used to work find under 1.30.3 and earlier

### Kubernetes Dashboard version

latest via helm

### Kubernetes version

1.31.0

**Comment by lprimak** [comment]
ping.... Anybody around to help me with this issue please?
Thank you!

**Comment by lprimak** [comment]
I had to add this to my `helm` command line to get metrics to work again:
`--values https://raw.githubusercontent.com/kubernetes/dashboard/master/charts/kubernetes-dashboard/values.yaml`

Is this normal? I would think helm would add default values automatically no?

**Comment by zozfabio** [comment]
I had to add this to my helm command line `--set metrics-server.enabled=true`

**Comment by lprimak** [comment]
Problem resolved... closing
