### ISSUE TITLE
What should I do if I want to monitor PyTorch Job type resources. The version used is v2.7.0

### ISSUE THREAD

**Issue by lizu18xz** [kubernetes/dashboard#9417]
### What would you like to be added?

What should I do if I want to monitor PyTorch Job type resources. The version used is v2.7.0

### Why is this needed?

What should I do if I want to monitor PyTorch Job type resources. The version used is v2.7.0

**Comment by floreks** [comment]
Not sure what this is about. You would need to elaborate. Also, v2.7.0 is no longer supported.
