### ISSUE TITLE
Kong image pull issues in AWS EKS

### ISSUE THREAD

**Issue by warrenellerbeck** [kubernetes/dashboard#9434]
### What happened?

when running the helm scripts the installer for Kong installer/deployment fails with an error : Failed to pull image "kong:3.6": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/kong:3.6": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/kong/manifests/sha256:611e2c550ad4e97c14c3ff781cb69aff95d89673ccf6b9b3c8b2ca5eafca3f38: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

logging in to docker does not resolve this issue as this is AWS EKS related image pull issues. All other components deploy OK except for the kong pod.

### What did you expect to happen?

the image pull to work 

### How can we reproduce it (as minimally and precisely as possible)?

simply running the helm install command

### Kubernetes Dashboard version

7.5.0

### Kubernetes version

1.26

**Comment by floreks** [comment]
This is an issue on your side. See the error message.

> 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

/close

**Comment by tjwangws** [comment]
Can I specify docker.io/library/kong:3.6 manually?  I use Harbor to build my own image server.
  image:
    repository: harbor.horimed.com/kubernetesui/dashboard-auth
    tag: 1.2.2
