### ISSUE TITLE
create from file not working for v2.5.1

### ISSUE THREAD

**Issue by liuqi-sun** [kubernetes/dashboard#9440]
### What happened?

when I import file by create from file, clicking upload button is not working. that resource is not created successfully in cluster.

### What did you expect to happen?

I hope the resource is created successfully in cluster.

### How can we reproduce it (as minimally and precisely as possible)?

import file directly

### What browsers are you seeing the problem on?

Firefox

### Kubernetes Dashboard version

v2.5.1

### Kubernetes version

1.23.8

**Comment by floreks** [comment]
We do not provide support for old Dashboard versions.

/close
