### ISSUE TITLE
The edit resource dialog don't get large on Internet Explorer

### ISSUE THREAD

**Issue by Yamagami-Takuma** [kubernetes/dashboard#945]
#### Issue details

The edit resource dialog don't get large on Internet Explorer.

The dialog can get small when make browser's window size smaller.
Then enlarge window size, the dialog is still small.

e.g. compare Internet Explorer and chrome
Internet Explorer
![ws000008](https://cloud.githubusercontent.com/assets/13443650/16292062/c22e3d9a-3948-11e6-8ab9-d0fb7ef28928.JPG)
chrome
![ws000000](https://cloud.githubusercontent.com/assets/13443650/16292064/c67cf184-3948-11e6-89f3-4a4a19b11c50.JPG)

e.g. make Internet Explorer window size small and large
make Internet Explorer window size very small
![ws000001](https://cloud.githubusercontent.com/assets/13443650/16292269/c458a77a-394a-11e6-8713-96d32ef18bcb.JPG)
then make it large, still dialog small
![ws000002](https://cloud.githubusercontent.com/assets/13443650/16292281/e31c3294-394a-11e6-9dfc-d955b4b8a5f8.JPG)
##### Environment

```
Dashboard version: 0df1fa0cb033972c80ee12d7e0617d548641b6e7
Kubernetes version: 1.2.4
Operating system: Ubuntu 14.04
Node.js version: 5.11.1
Go version: 1.6.2
```

**Comment by Yamagami-Takuma** [comment]
```
Internet Explorer ver: 11.0.9600.18321
Chrome ver: 51.0.2704.103 m (64-bit)
```

**Comment by maciaszczykm** [comment]
We will track from #2420.
