### ISSUE TITLE
Image pull secret dialog is larger than window on Chrome

### ISSUE THREAD

**Issue by Yamagami-Takuma** [kubernetes/dashboard#946]
#### Issue details

On Chrome, when window size is small, Create a new image pull secret dialog is larger than window size.
Other dialog is OK. Only Create a new image pull secret dialog causes this.

e.g. window size is 510×450, compare chrome and Internet Explorer
On Chrome. Dialog is larger than window. Cannot read sentences.
![ws000007](https://cloud.githubusercontent.com/assets/13443650/16292882/7632b3c8-3950-11e6-8f82-80406e9dcd32.JPG)
On Internet Explorer. Dialog fits window.
![ws000009](https://cloud.githubusercontent.com/assets/13443650/16292881/74fb86ec-3950-11e6-8756-45f51afbbd04.JPG)
##### Environment

```
Dashboard version: 0df1fa0cb033972c80ee12d7e0617d548641b6e7
Kubernetes version: 1.2.4
Operating system: Ubuntu 14.04
Node.js version: 5.11.1
Go version: 1.6.2
Internet Explorer version: 11.0.9600.18321
Chrome version: 51.0.2704.103 m (64-bit)
```

**Comment by bryk** [comment]
What happens when the window is large enough? E.g., desktop?

**Comment by Yamagami-Takuma** [comment]
This is depends on width of window.
The enough size is about 600 width.

If window is large enough, the dialog fits window, like other dialogs.

**Comment by floreks** [comment]
Fixed.
