### ISSUE TITLE
The full text of the column labels are not shown on Internet Explorer

### ISSUE THREAD

**Issue by Yamagami-Takuma** [kubernetes/dashboard#948]
#### Issue details

On Internet Explorer, the full text of the column labels are not shown when window width is not enough.
On Chrome, it's shown as multiple lines.

IE
![ws000012](https://cloud.githubusercontent.com/assets/13443650/16297565/4f4fbcc6-396c-11e6-9de4-0fa62f410fd5.JPG)

Chrome
![ws000011](https://cloud.githubusercontent.com/assets/13443650/16297559/496401b4-396c-11e6-833a-90b43ebb7e83.JPG)
##### Environment

```
Dashboard version: 0df1fa0cb033972c80ee12d7e0617d548641b6e7
Kubernetes version: 1.2.4
Operating system: Ubuntu 14.04
Node.js version: 5.11.1
Go version: 1.6.2
Internet Explorer version: 11.0.9600.18321
Chrome version: 51.0.2704.103 m (64-bit)
```

**Comment by maciaszczykm** [comment]
We will track from #2420.
