### ISSUE TITLE
Incorrect `GOMAXPROCS` and `GOMEMLIMIT` being set on latest Helm chart

### ISSUE THREAD

**Issue by jnoordsij** [kubernetes/dashboard#9485]
### What happened?

After upgrading from 7.5.0 to the latest Helm chart version (7.6.1), the `GOMAXPROCS` and `GOMEMLIMIT` values set in my pod are no longer correct.

### What did you expect to happen?

The values to remain as before.

### How can we reproduce it (as minimally and precisely as possible)?

Set CPU limits and/or memory limits using the latest Helm chart version (7.6.1).

E.g.: setting CPU limit of `250m` and a memory limit of `200Mi` on the `api` containers with values
```
  api:
    containers:
      resources:
        limits:
          cpu: 250m
          memory: 200Mi
```
will result in a pod with the incorrect values `GOMAXPROCS=250` (should be 1) and `GOMEMLIMIT=200` (should be 209715200).

### Anything else we need to know?

This regression was caused by #9226, which introduced a `divisor` value to the chart of `1m` for CPU and `1Mi`, which results in strictly different behavior than before. The Kubernetes default value is (plain) `1` for both; see also [the docs](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/):

> The `divisor` field is optional and has the default value of `1`. A divisor of 1 means cores for `cpu` resources, or bytes for `memory` resources.

Side note: I'm unsure why this change was introduced, as in my eyes it looks like this is a bug with `ArgoCD` defaulting to an invalid value for an unset field, rather than an issue with the chart.

### Kubernetes Dashboard version

N/A

### Kubernetes version

N/A

**Comment by floreks** [comment]
You are right. We should follow the kubernetes defaults and not provide workarounds for possible bugs in other tools.
