### ISSUE TITLE
The difference between the web UI login user and serviceAccountName in deployment

### ISSUE THREAD

**Issue by liuqi-sun** [kubernetes/dashboard#9573]
### What happened?

What is the difference between the web UI login user and the serviceAccountName in deployment?Who gives dashboard final access to k8s?

### What did you expect to happen?

When I deployed dashboard, the kubernetes-dashboard serviceaccount I used in deployment, other users I used to log in the web UI, can also operate the k8s resources, although I deleted some permissions from the kubernetes-dashboard account.

### How can we reproduce it (as minimally and precisely as possible)?

nothing

### Kubernetes Dashboard version

2.5.1

### Kubernetes version

1.23.8

**Comment by floreks** [comment]
Dashboard 2.5.1 is no longer supported and was using different permission policy than the latest version. You should not be granting Dashboard deployment any permissions on your own.

/close
