### ISSUE TITLE
Add "equivalent kubectl" to UI actions

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#959]
The UI can currently do a couple of verb actions on resources and will do more in the future. The idea is to add "equivalent kubectl" commands to UI actions. E.g., when I delete a resource I also see: "You can do the same in CLI via `kubectl delete rs foo --namespace bar`". 

Thoughts?

**Comment by maciaszczykm** [comment]
Good idea, it would make UX even better.

**Comment by Lukenickerson** [comment]
Would this be like pop-up tips for actions that a user has just completed? Another way would be for this to be text (or more likely tooltips) that's displayed near action buttons -- similar to how you see "Ctrl+T" next to "New Tab" in the hamburger menu in Chrome -- so the user can see the command line command _before_ performing an action.

I think this would be very helpful for someone who wants to transition from using the UI to using the CLI. Do we have any data on current/potential users to know what they think of UI vs. CLI?

Depending on how this is implemented, it might also be good to have a toggle so the tips aren't shown for users who know they have no interest in learning the CLI.

**Comment by bryk** [comment]
> Would this be like pop-up tips for actions that a user has just completed? 

It should be an alternative to performing actions. E.g., you show CLI copy&paste command next a delete button or in the confirmation dialog.
What's more, we can implement some actions only through the "CLI equvalents". E.g., doing rolling update in the UI is hard, so, as a stopgap, we may just show a card in replication controller details that has the CLI command for the rolling update. 
What do you think? 

> I think this would be very helpful for someone who wants to transition from using the UI to using the CLI. Do we have any data on current/potential users to know what they think of UI vs. CLI?

I've used tools in the past that provided CLI equivalents and I used the equivalents a lot The usual pattern was: find and drill down the thing through the UI and then perform the action on it using CLI. The reason was feature gap (CLI could do more than UI) and "feeling safe" (I just felt safer doing long running verb operations through CLI, but that might have been just the problem of the UI, not that CLI is inherently better)

**Comment by Lukenickerson** [comment]
> The reason was feature gap (CLI could do more than UI) and "feeling safe" (I just felt safer doing long running verb operations through CLI, but that might have been just the problem of the UI, not that CLI is inherently better)

This sounds like an argument for putting more effort towards getting UI parity with the CLI and making sure it handles long-running operations well. :)

How did the tools you used in the past provide the CLI equivalents? I don't suppose you could find a screenshot of an example?

**Comment by bryk** [comment]
> How did the tools you used in the past provide the CLI equivalents?

This was like that: I look at a page that shows a job (similar to K8s replica set/deployment). The page would show me details of it, metrics and all that stuff. On the bottom there would be a box with command line actions you could take on the job (like restart, delete, and stuff). 

> This sounds like an argument for putting more effort towards getting UI parity with the CLI and making sure the UI handles long-running operations well. :)

Yes, definitely. But we need to be realistic and deliver value to the users in incremental steps. Rather than have a perfect UI, but only after a couple of years of development. That's why I was saying that this is a stop-gap enabler, but ideally this would be in the UI itself.

**Comment by Lukenickerson** [comment]
>  On the bottom there would be a box with command line actions you could take on the job (like restart, delete, and stuff).

:+1: 
I think this approach will work well. It'll be out of the way, but there if you need it. @romlein - This could be a good thing to mockup.

Ideally (long term) it'd be nice to also include functionality for turning these tips on/off. @bryk : Slightly off topic - but is there a plan to have user-specific dashboard options saved somewhere? (Easy to just use localStorage, but there may be some things that need to be stored server-side.)

**Comment by bryk** [comment]
> Slightly off topic - but is there a plan to have user-specific dashboard options saved somewhere? (Easy to just use localStorage, but there may be some things that need to be stored server-side.)

Yes, we plan to have user options, like namespace that they own. But this requires significant design and engineering effort, so we didn't do this yet. Re implementation: local storage may be a good start before we figure out how to persist user PII on backend.

**Comment by bryk** [comment]
I prioritized this as P2 - meaning that we'll look at this on next iteration. @Lukenickerson Agreed?

**Comment by maciaszczykm** [comment]
Added it in the last commit to the `angular-migration` branch.
