### ISSUE TITLE
Move pagination to server side

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#960]
Currently pagination is client side only. We should move it to the backend to be real pagination.

@floreks Can you take this?

**Comment by floreks** [comment]
This will be interesting. As far as i know kubernetes does not offer pagination so we can only get all resources and paginate them on our backend or is there another option?

**Comment by bryk** [comment]
Yep, this would be the solution for now. Note that Dashboard backend most often lays next to the apiserver, so they can exchange large amount of data quickly. Sending stuff to the client is expensive. 

And anyway, in the future I expect pagination in the apiserver. So we could plug into it when we have pagination implemented on the backend :)

**Comment by floreks** [comment]
We should think also about using HTTP compression, i.e. gzip. It would significantly reduce size of data transmitted between client and server.

**Comment by bryk** [comment]
Yep. But I think that it is either enabled by default or we just need to tweak a know in the go-restful lib

**Comment by floreks** [comment]
It appears that it is not enabled by default. There is package [gzip](https://golang.org/pkg/compress/gzip/) for that.

**Comment by bryk** [comment]
> It appears that it is not enabled by default. There is package gzip for that.

Can you spin a separate issue for this?

**Comment by floreks** [comment]
> Can you spin a separate issue for this?

Done in #967

**Comment by bgrant0607** [comment]
FYI, the issue for pagination in K8s proper is https://github.com/kubernetes/kubernetes/issues/2349

**Comment by bryk** [comment]
@bgrant0607 Cool, thanks. We've implemented pagination in our backend and it can be easily hooked up to pagination in K8s proper, when it is done.

**Comment by maciaszczykm** [comment]
Already done.
