### ISSUE TITLE
Namespace dropdown broken after upgrading chart 7.8.0 -> 7.9.0

### ISSUE THREAD

**Issue by Sir-Jacques** [kubernetes/dashboard#9605]
### What happened?

After upgrading to chart 7.9.0 the namespace-selection (dropdown) is empty for users that do have list/namespaces permissions. We are using token-passthrough (JWT used for authentication is passed-through to the api-server)

The call to /api/v1/namespace is responded with:
```
{
 "listMeta": {
  "totalItems": 0
 },
 "namespaces": [],
 "errors": [
  {
   "ErrStatus": {
    "metadata": {},
    "status": "Failure",
    "message": "forbidden: : ",
    "reason": "Forbidden",
    "details": {
     "name": "MSG_FORBIDDEN_ERROR"
    },
    "code": 403
   }
  }
 ]
}
```

### What did you expect to happen?

I expected this /api/v1/namespace call to still be responded like before:

```
{
 "listMeta": {
  "totalItems": 193
 },
 "namespaces": [
  {
   "objectMeta": {
    "name": "<redacted>",
    "labels": {
     <redacted>
    },
    "annotations": {
     <redacted>
    },
    "creationTimestamp": "<redacted>",
    "uid": "<redacted>"
   },
   "typeMeta": {
    "kind": "namespace"
   },
   "phase": "Active"
  },
  <... 192 more namespaces here ...>
}
```

### How can we reproduce it (as minimally and precisely as possible)?

When using token-passthrough, upgrade to version 7.9.0 and try to open the namespace-selection dropdown on the main-screen. 

Using F12 you can see the response from /api/v1/namespace (which is a statuscode 200, but contains the error in the response-body).

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

7.9.0 (Helm chart)

### Kubernetes version

1.29

### Dev environment

When swapping between helm chart 7.9.0 and 7.8.0 it is immediately resolved in 7.8.0 and immediately broken again in 7.9.0.

**Comment by floreks** [comment]
Fixed in https://github.com/kubernetes/dashboard/releases/tag/kubernetes-dashboard-7.10.0

/close

**Comment by Sir-Jacques** [comment]
Can confirm that 7.10.0 fixes this issue, thanks guys! :-)
