### ISSUE TITLE
Resource sorting in the UI

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#966]
We display list of resources in many places. The tables are not sortable, though. We should make them so.

@maciaszczykm What do you think?

**Comment by maciaszczykm** [comment]
I agree, that sorting is very valuable functionality, but at the moment I'd say we need to wait before we can start implementing it. Is must be aligned with pagination and if we are moving pagination to the backend then we need to find a way to implement both functionalities at the same time.

I'm also thinking what is the best possibility:
1. Frontend sorting & backend pagination - we'll be able to sort only items displayed in the UI, not all of them.
2. Backend sorting & backend pagination - will take most time to implement, should the best solution.
3. Other?

**Comment by maciaszczykm** [comment]
CC @floreks

**Comment by bryk** [comment]
> 2. Backend sorting & backend pagination - will take most time to implement, should the best solution.

This was the implementation I've been thinking about. As you've correctly noticed, with backend-based pagination it does not make sense to sort on the frontend.

**Comment by maciaszczykm** [comment]
Linking it with #960.

**Comment by ryanwalls** [comment]
Just wondering if there are any updates on this?  Really would love this in lieu of a search capability (which I would actually prefer/prioritise).

**Comment by floreks** [comment]
This is almost done. Filtering/Search per list should be added shortly after that. Global search has no ETA.
