### ISSUE TITLE
I can not install kubernetes-dashboard with helm.

### ISSUE THREAD

**Issue by taogone** [kubernetes/dashboard#9675]
### What happened?

This command is not working.
"helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard"

When I had tried to install with above command, I had got following error messages.
---------------------------------------------------------------------------------------------
Release "kubernetes-dashboard" does not exist. Installing it now.
Error: template: kubernetes-dashboard/templates/secrets/csrf.yaml:24:6: executing "kubernetes-dashboard/templates/secrets/csrf.yaml" at <include "kubernetes-dashboard.app.csrf.secret.value" .>: error calling include: template: kubernetes-dashboard/templates/_helpers.tpl:95:63: executing "kubernetes-dashboard.app.csrf.secret.value" at <$secret.data>: wrong type for value; expected map[string]interface {}; got interface {}
---------------------------------------------------------------------------------------------

How can I install kubernetes-dashboard.

OS: Ubuntu

### What did you expect to happen?

install kubernetes-dashboard

### How can we reproduce it (as minimally and precisely as possible)?

Try follow command.
----------------
"helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard"

### Kubernetes Dashboard version

Check above error message

### Kubernetes version

Client Version: v1.30.6

**Comment by taogone** [comment]
Kubernetes Server version is v1.29.10

**Comment by floreks** [comment]
Try updating helm to the latest version

**Comment by kundan2707** [comment]
@taogone  I am able to install kubernetes dashboard with same command on ubuntu OS.
```
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
Release "kubernetes-dashboard" does not exist. Installing it now.
NAME: kubernetes-dashboard
LAST DEPLOYED: Tue Dec 10 14:34:58 2024
NAMESPACE: kubernetes-dashboard
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
*************************************************************************************************
*** PLEASE BE PATIENT: Kubernetes Dashboard may need a few minutes to get up and become ready ***
*************************************************************************************************

Congratulations! You have just installed Kubernetes Dashboard in your cluster.

To access Dashboard run:
  kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443

NOTE: In case port-forward command does not work, make sure that kong service name is correct.
      Check the services in Kubernetes Dashboard namespace using:
        kubectl -n kubernetes-dashboard get svc

Dashboard will be available at:
  https://localhost:8443
```

**Comment by floreks** [comment]
Ye, I think that this is just an issue with an outdated helm client.

/close
