### ISSUE TITLE
delete in dashboard does not cascade

### ISSUE THREAD

**Issue by puja108** [kubernetes/dashboard#980]
#### Issue details

When deleting a deployment/rc/rs in dashboard the delete does not cascade like it does with `kubectl delete`. I'd say the cascading should be the expected behavior as it is also the default with `kubectl`.
##### Environment

```
Dashboard version: 1.1.0
Kubernetes version: 1.2.5
Operating system:
Node.js version:
Go version:
```
##### Steps to reproduce
1. Delete any deployment, rc, or rs
##### Observed result

The delete does not cascade to resources managed by the deleted resource.
##### Expected result

Cascading delete like with `kubectl delete` (default behavior), i.e. deployment->rs->pods; rs->pods; rc->pods

**Comment by floreks** [comment]
I've encountered same issue lately. We have to rethink our generic approach to delete, because it leaves orphaned resources on the cluster.

cc @bryk

**Comment by bryk** [comment]
I definitely agree. We need to wait until this is implemented on the server side: https://github.com/kubernetes/kubernetes/issues/19054

Otherwise, it is us duplicating kubectl and apiserver work. 

Thoughts?

**Comment by floreks** [comment]
Nice. Didn't know about that. We should definitely wait for kubernetes to get this feature.

**Comment by puja108** [comment]
Same here, looks like we should wait then, also good discussion about what the default should be. For me the default for UI should be same as for `kubectl` to have a coherent UX across CLI and UI.

**Comment by floreks** [comment]
> For me the default for UI should be same as for kubectl to have a coherent UX across CLI and UI.

That's our goal :)

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
In the upcoming 1.4 release, server-side cascading deletion of rc and rs is possible, dashboard just needs to send to apiserver a deletion request with [`DeleteOptions.OrphanDependents=false`](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L2377).

We will work on the other use cases in 1.5.

**Comment by floreks** [comment]
Great! We should support this. 

cc @bryk @maciaszczykm

**Comment by bryk** [comment]
@caesarxuchao Cool, thanks.

Will we get cascade delete for free for future use cases when we just send `DeleteOptions.OrphanDependents=false` with all delete requests?

**Comment by caesarxuchao** [comment]
@bryk what are the future use cases in have in mind? We will support cascading deletion for Deployment in the future.

**Comment by puja108** [comment]
Can't test right now, but Jobs would be good.

On a sidenote: Does deletion of namespaces (I'd guess that always incl all their resources) work in Dashboard?

**Comment by bryk** [comment]
@puja108 We dont (yet) support deletion/modification of cluster admin resources. It is challenging, as you already noticed, so we want to tackle this only when we have time to do this right.

**Comment by bryk** [comment]
@caesarxuchao 
> what are the future use cases you have in mind? We will support cascading deletion for Deployment in the future.

Yes, cases like cascade delete for Deployments or Namespaces.

**Comment by maciaszczykm** [comment]
Will track it from #1570.
