### ISSUE TITLE
Target Port should not be required with Port

### ISSUE THREAD

**Issue by dvohra** [kubernetes/dashboard#984]
##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0
Kubernetes version: 3.0
Operating system: Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-9abea4fb on Amazon EC2
Node.js version:
Go version:
```
##### Steps to reproduce

1. Create a Deployment and Service for dashboard using the https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

The `--apiserver-host=http://my-address:port` setting may need to be modifed to the Public URI.
1. Navigate to the Dashboard in a browser.
2. Deploy an App
3. In the Service settings the fields for Port and Target Port are provided. Specify a Port.  
##### Observed result

If the Port is specified the Target Port is being required to be specified.
##### Expected result

Target Port is not required if Port is set if used with `kubectl expose` command to create a service. Target Port should not be required in the Dashboard either and should default to the Port setting value.
##### Comments

Also, the Dashboard does not have provision to specify the service type, such as LoadBalancer, NodePort.

**Comment by bryk** [comment]
> Target Port is not required if Port is set if used with kubectl expose command to create a service. Target Port should not be required in the Dashboard either and should default to the Port setting value.

Yes, we can default Target Port to Port, if unspecified. But re-typing is not that huge problem.

> Also, the Dashboard does not have provision to specify the service type, such as LoadBalancer, NodePort.

Actually it does. Internal is nodeport, external is loadbalancer. Was this misleading? 

@floreks @cheld Should we document or indicate this relationship somehow?

**Comment by cheld** [comment]
@bryk actually you are not correct :-) Internal is service and external is nodeport/loadbalancer depending on platform capabilities.

I assume part of the problem is that internal/external is not used in Kubernetes documentation. We could add more documentation to the right.

A better design might be:

Access      \/
  Internal through service
  External through load balancer

**Comment by dvohra** [comment]
External IP is different feature and could be used with any service type. Typically, LoadBalancer is used with a cloud provider such as EC2 and NodePort is used to expose the service  on each node of the cluster. 
http://kubernetes.io/docs/user-guide/services/#type-loadbalancer

The choices should be
ClusterIP (the default)
LoadBalancer
NodePort

**Comment by cheld** [comment]
Load Balancer is also Node Port. We display accordingly. And clusterip is internal.

**Comment by dvohra** [comment]
What is meant by "Load Balancer is also Node Port"? These are different service types.

**Comment by cheld** [comment]
Your suggestion is a bit technical, but maybe more clear

**Comment by cheld** [comment]
Load Balancer uses Node Port. In case Load Balancer cannot be created than only Node Port will be created

**Comment by pwittrock** [comment]
FYI when I encountered this there was no error, the deploy button just didn't work at all and I had to guess at what needed to change

**Comment by dvohra** [comment]
_Load Balancer uses Node Port._

LoadBalancer does not use NodePort but a LoadBalancer type service would also be a NodePort type service and a ClusterIP. And a NodePort type service would also be a ClusterIp type.

**Comment by dvohra** [comment]
_FYI when I encountered this there was no error, the deploy button just didn't work at all and I had to guess at what needed to change_

Does an application not get deployed? At least an application should get deployed without an issue.

**Comment by colemickens** [comment]
LoadBalancer sometimes does use NodePort, if the cloudprovider does DNATing.

**Comment by dvohra** [comment]
But the AWS provides a public DNS for the LoadBalancer. What is the need to use NodePort.

**Comment by colemickens** [comment]
What does that have to do with it? Azure can provision a DNS name for the load balancer but what bearing does that have on whether or not the LB sends traffic directly to the node on the service port versus on the NodePort.

**Comment by colemickens** [comment]
Azure, for example, has to use NodePort (even if the LB has a public IP and/or DNS name) because the LB does DNATing so when the packet hits the node, there's no iptable rule to route it to an appropriate Pod... thus it has to send traffic to the NodePort.

**Comment by dvohra** [comment]
But, is it known which cloud provider and when does it send traffic through a NodePort?

**Comment by colemickens** [comment]
I'm not sure I understand your question. Each cloudprovider wires up the load balancer as they see fit. On Azure, we use NodePort because we must (we wrote that code). On GCE, for example, I believe that they send traffic to the normal service Port because their LoadBalancer preserves the destination IP.

**Comment by dvohra** [comment]
Only Azure seems to be using NodePort for LoadBalancer. The earlier statement was too general "Load Balancer uses Node Port. ".

**Comment by colemickens** [comment]
I think the comment earlier meant that if you make a Service Type=LoadBalancer that it also always allocates a NodePort... which is true. Even if the LB doesn't use it.

**Comment by dvohra** [comment]
According to definition of LoadBalancer it does use NodePort.

"LoadBalancer: on top of having a cluster-internal IP and exposing service on a NodePort also, ask the cloud provider for a load balancer which forwards to the Service exposed as a <NodeIP>:NodePort for each Node."

**Comment by colemickens** [comment]
At the risk of repeating myself...

1. Any time you make a Service of Type=LoadBalancer... you get all three allocated: LoadBalancer, NodePort, ClusterIP

2. If the cloudprovider supports destination IP preservation, then it will not route requests to the NodePort but instead directly to the service's port on each node (at that point there are iptables rules for that Service's ingress destination IP that then routes the request to the relevant Pod).

3. If the cloudprovider's load balancer does DNATing, and does not support destination IP preservation, then it *has* to use the NodePort.

Is there any issue with this? I don't really see how this relates the initial issue anyway.

**Comment by dvohra** [comment]
Thanks for the additional info which is not in the documentation.
