### ISSUE TITLE
build issue on ubuntu 14.04 ERROR - variable goog is undeclared

### ISSUE THREAD

**Issue by zhi-feng** [kubernetes/dashboard#985]
#### Issue details
I follow the steps in https://github.com/kubernetes/dashboard/blob/master/docs/devel/getting-started.md , installed all these requirements  .  But when I try use gulp to build a docker images I always get the error like this.

gulp docker-image:canary
..... 
Error: Command failed: java -jar -XX:+TieredCompilation /root/kubernetes/dashboard/node_modules/google-closure-compiler/compiler.jar --flagfile="/tmp/7a699a48-b0f9-4d69-b409-a733a15b3cc1" --angular_pass --entry_point=index_module --compilation_level=ADVANCED_OPTIMIZATIONS --export_local_property_definitions --externs=/root/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.5.js --externs=/root/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.5-http-promise_templated.js --externs=/root/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.5-q_templated.js --externs=/root/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-material.js --externs=/root/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular_ui_router.js --externs=/root/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.4-resource.js --externs=/root/kubernetes/dashboard/src/app/externs/backendapi.js --externs=/root/kubernetes/dashboard/src/app/externs/uirouter.js --generate_exports --js_module_root=src/app/frontend --jscomp_error=* --jscomp_off=lintChecks --jscomp_off=unnecessaryCasts --jscomp_off=analyzerChecks --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT3 --dependency_mode=LOOSE --use_types_for_optimization --translations_file=/root/kubernetes/dashboard/i18n/messages-en.xtb --js_output_file="app.js"
src/app/frontend/common/filters/relativetime_filter.js:101: ERROR - variable goog is undeclared
  MSG_TIME_UNIT_SECOND_LABEL: goog.getMsg('a second'),
                              ^

1 error(s), 0 warning(s)

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

##### Environment
go version
go version go1.6.2 linux/amd64
node --version
v6.2.2
git show 
commit 953d003a7a75d1b5e89ffc2241ab063ad291e0a3
Operating system:
uname -a
Linux ip-172-31-6-189 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

##### Steps to reproduce
I tried to build on aws ubuntu instance and my laptop (both are ubuntu 14.04 ) get the same error.

**Comment by bryk** [comment]
Hmm... Did you do `npm install`? Do you have `java` installed? Can you run `bower install`?

**Comment by zhi-feng** [comment]
Sorry for response later .  It turn out that the install of bower is not completely. I tried to install bower several times to make  all its packages downloaded and installed, then error is gone
