### ISSUE TITLE
No backend support for daemon set events

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#991]
![zrzut ekranu z 2016-07-06 09-31-22](https://cloud.githubusercontent.com/assets/2285385/16610584/6d1e443a-435c-11e6-8545-0d2cef1f30d3.png)

**Comment by bryk** [comment]
What this means? That we dont send events to the frontend?

**Comment by floreks** [comment]
Yes. Frontend supports events but backend does not get them and don't even have them in this structure.

**Comment by digitalfishpond** [comment]
@bryk this can probably be closed now.
