### ISSUE TITLE
List of secrects

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#992]
Page with list of secrets, as defined in: https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/23-03-2016-scale-and-navigation/secret-details-page.png

**Comment by bryk** [comment]
cc @PiotrDabkowski

**Comment by digitalfishpond** [comment]
This can be closed now thanks to #1060

**Comment by maciaszczykm** [comment]
#1060 is not merged yet.
