### ISSUE TITLE
Document vendor requirements

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#994]
I've encountered some issues after switching to `vendor` dependencies. It requires `GO15VENDOREXPERIMENT` environment variable to be set to `1` or to be undefined in order to correctly build backend. I think it will be used up to go 1.7 because they are planning to depreceate this variable then.

According to docs:
> Go 1.5 introduced experimental support for vendoring, enabled by setting the GO15VENDOREXPERIMENT environment variable to 1. Go 1.6 keeps the vendoring support, no longer considered experimental, and enables it by default. It can be disabled explicitly by setting the GO15VENDOREXPERIMENT environment variable to 0. Go 1.7 will remove support for the environment variable.

**Comment by bryk** [comment]
So you had this variable set to `false`?

**Comment by floreks** [comment]
Yeah, I've added this switch when I've upgraded go to 1.5. It works also when it is unset.

**Comment by bryk** [comment]
Ok
