### ISSUE TITLE
Pods are not deleted even though Replication Controller is deleted.

### ISSUE THREAD

**Issue by srikanthpeetha** [kubernetes/dashboard#995]
When ever I delete a rc from dashboard I could see pods are not deleted though rc is deleted. Then I tried deleting rc from CLI and it worked pods are deleted. So I think it might be a bug.

Dashboard version: 1.1.0
Kubernetes version: 1.3.0
Operating system: ubuntu 14.04

I observed this in kube-controller-manager.log 
`I0707 14:24:13.245338     611 replication_controller.go:510] Replication Controller has been deleted apps/gowikii-v1`
`I0707 15:41:24.799915     611 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"gowiki", UID:"6466b9f5-41e7-11e6-ba41-74867ad1a3ba", APIVersion:"v1", ResourceVersion:"900703", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: gowiki-s2egq`
`I0707 15:41:25.790912     611 replication_controller.go:510] Replication Controller has been deleted default/gowiki`

default/gowiki is the rc deleted from CLI and apps/gowikii-v1 from dashboard

**Comment by maciaszczykm** [comment]
We already have an issue for it. Check #980. Closing as duplicate.
