### ISSUE TITLE
Dashboard apiserver-host parameter is ignored

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#996]
On current HEAD if we provide `apiserver-host` parameter to the dashboard it will still use `localhost:8080`. I've investigated this issue and it is related to our recent vendor update.

Core issue is related to dependency used by kubernetes core which is [mergo](https://github.com/imdario/mergo#usage). It is used to merge structures but its behavior has changed and kubernetes explicitly have chosen to use older version of this dependency in [here](https://github.com/kubernetes/kubernetes/commit/98b11e82d5cc3d79fdb9681d624e91f71ddcd007#diff-d6faff13e3088419c7fb361fd8f05ea1R36). With recent vendor migration it must have been updated and that's why [this part of code](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/client_config.go#L326) no longer overrides default cluster settings.

I'll update it to the version used by kubernetes core.

**Comment by bryk** [comment]
Perfect, thanks!
